### ISSUE TITLE
Regex - \s also replaces \r\n

### ISSUE THREAD

**Issue by TK1987** [notepad-plus-plus/notepad-plus-plus#10014]
### Description of the Issue
"\s" not only replaces spaces, but also line breaks and carriage returns.
If i use a real space " " instead, it works fine.

![unbenannt](https://user-images.githubusercontent.com/45066172/122176910-66775180-ce85-11eb-837c-dd12c224fa30.gif)

### Debug Information
Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.1052
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextViz.dll Python Indent.dll RegexTrainer.dll

**Comment by chcg** [comment]
See https://www.regular-expressions.info/shorthand.html

`\s stands for “whitespace character”. Again, which characters this actually includes, depends on the regex flavor. In all flavors discussed in this tutorial, it includes [ \t\r\n\f]. That is: \s matches a space, a tab, a carriage return, a line feed, or a form feed. Most flavors also include the vertical tab, with Perl (prior to version 5.18) and PCRE (prior to version 8.34) being notable exceptions. In flavors that support Unicode, \s normally includes all characters from the Unicode “separator” category. Java and PCRE are exceptions once again. But JavaScript does match all Unicode whitespace with \s.`

So I would consider it expected behaviour.

**Comment by sasumner** [comment]
@chcg Just curious why you labelled this as a "question" ?

**Comment by chcg** [comment]
@sasumner Just because I had no better category  at my first look in mind as at least an explanation about the behaviour could be found here. Seems "not bug but feature" matches better.

**Comment by sasumner** [comment]
@chcg Should every issue get a label? Hmmm.

**Comment by chcg** [comment]
I think labelling each issue is not necessary.
