### ISSUE TITLE
File incorrectly identified as having Unix style line endings

### ISSUE THREAD

**Issue by colejohnson66** [notepad-plus-plus/notepad-plus-plus#1002]
I have a subtitle file that Notepad++ detects as having Unix style line endings, when in fact, it doesn't. _At all._ To test this, I did the following:

 1. Open file
 2. Observe Notepad++ claims Unix style line endings
 3. Replace `\r` with nothing
 4. Save with different name
 5. Reopen new file
 6. EOL conversion to Dos/Windows style
 7. Save
 8. Reopen new file
 9. Observe Notepad++ claims Unix style line endings

If you diff the original file with the new one, you'll find that they're _identical_! In fact, a regex search (wrap-around, "." flag off) on the file for `[^\r]\n` returns nothing.

Here's the file in question: [`Inception (2010).BRRip.English.srt`](https://mega.nz/#!ZwkynaQb!iAxX8xVRPebuQF6dPBiw9pyyxUo10AJX5T34moLdUS0)

**Comment by dail8859** [comment]
I can confirm something is definitely wrong. Even at step 2 it shows it has `\r\n` line endings but reports as "Unix" style line endings. This is very problematic since any time you hit enter it inserts `\n` instead of `\r\n`. 

This file is UTF-8-BOM. I removed the BOM from the file and when I reopened it, then it correctly detects the line endings. So it appears the BOM is causing N++ to incorrectly detect line endings in this case. @colejohnson66 I'm not meaning you have to edit the file this way, just hopefully this additional information will help someone fix the bug quicker. :)

**Comment by colejohnson66** [comment]
@dail8859 It's odd because I have plenty of subtitle files that are UTF-8-BOM with Windows line endings that get detected correctly

**Comment by donho** [comment]
@colejohnson66 To download your file, it needs to install MEGAsyncSetup.exe in which I don't trust.
Could you attach your file directly in this issue?

**Comment by dail8859** [comment]
Somehow I got around downloading the exe. Here is the file (renamed as a png, because Github requires repository write permissions to attach a txt but not a png).

![inception 2010 brrip english srt](https://cloud.githubusercontent.com/assets/3694843/10742472/ae9f5848-7c03-11e5-8287-5255931cc81f.png)

**Comment by donho** [comment]
Thank you @dail8859 !
