### ISSUE TITLE
[Feature Request] Don't force style and tab icons when toogling dark mode

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#10049]
### Description of the Issue

Don't force style and tab icons when toggling dark mode.
Make it optional, or allow to choose default styles and icons.

I am using my own dark and light theme, and it can be annoying when toggling between modes.
For icon currently many plugins don't support new darkmode icons, so they appear blank, when using fluent icons.
So I currently prefer standard icon set.
### Steps to Reproduce the Issue

1. Open preferences
2. Enable or disable dark mode

### Expected Behavior

Style and icons remain same.

### Actual Behavior

Icon is changed to fluent and style to Default or DarkModeDefault.

**Comment by donho** [comment]
@ozone10 
In order to provide a better UX for ppl who switch to dark mode for the first time, it's inevitable to show users the "suitable" configuration. For me, if users have tried dark mode, they should decide which side they wanna stay. Maybe it could not the case for the developers of this project (ie. you and others who are working in dark mode), but for the most of users, you are in dark mode, or you are not.

**Comment by ozone10** [comment]
@donho 
What about adding checkbox `Use default style theme`,  which will be enabled by default.
Same with toolbar icons.

**Comment by donho** [comment]
@ozone10 
If we add more options for 1 option, then there's a problem.
Too many options, no option.
