### ISSUE TITLE
Switching to dark mode via UI doesn't make edit zone in dark  mode 

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#10076]
### Description of the Issue
After installing Notepad++ v8.1 under an user account (with admin privilege), then switch to another user account  (with or without admin privilege), launch Notepad++ and turn dark mode on. The dark theme on edit zone won't be applied.

### Steps to Reproduce the Issue

1. Install Notepad++ v8.1 under an user account with admin privilege
2. Switch to another user account  (with or without admin privilege), launch Notepad++
3. Turn dark mode on

### Expected Behavior
Dark theme is applied to the edit zone.

### Actual Behavior
Dark theme is NOT applied to the edit zone.

### Debug Information
Notepad++ v8.1   (64-bit)
Build time : Jun 26 2021 - 19:19:18
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19042.1052
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by TheByKotik** [comment]
Hi! Sorry in advance for not opened new issue but i'm think this is part of described above problem.

### Description of the Issue
I have almost same issue but with **Don't use %AppData%** option.
Release 8.1.1 did not fix this.

### Steps to Reproduce the Issue
1. Install with **Don't use %AppData%** option.
2. Turn dark mode on.

### Expected Behavior
Dark theme is applied to the edit zone.

### Actual Behavior
Dark theme is NOT applied to the edit zone.

### Debug Information
Notepad++ v8.1.1   (64-bit)
Build time : Jul  1 2021 - 14:10:53
Path : C:\Programs\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1083
Current ANSI codepage : 1251
Plugins : none
