### ISSUE TITLE
File Rename should suggest current directory, not Default Save Directory

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#10095]
As mentioned [HERE](https://community.notepad-plus-plus.org/topic/21397) a simple _File_ > _Rename_ of file should probably not suggest the directory specified with _Default Open/Save file Directory_ when that setting is not _Follow current document_.   Rather, it should always suggest the directory that the file is currently in.  Optionally, a new preference setting could be made for controlling this functionality.

### Debug Information
Notepad++ v8.1   (64-bit)
Build time : Jun 17 2021 - 01:56:07
Path : C:\\............\\npp.8.1.portable.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1556
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by mere-human** [comment]
Note, this is not a regression, it has been like this at least since version 7.9.1.

The suggested preference could be in _Default Directory_ section and look like this:
![image](https://user-images.githubusercontent.com/9664141/124228212-890b9a80-db14-11eb-9dfe-2c2cf65d25e7.png)
It could be outside the group box.
The wording could be:
- Apply to rename dialog
- Rename always follows current document

**Comment by sasumner** [comment]
@mere-human Did you want this to be assigned to you?

**Comment by mere-human** [comment]
@sasumner Yes, please.

**Comment by sasumner** [comment]
@mere-human Note that we don't have @donho concurrence on this, so...

**Comment by donho** [comment]
@mere-human 
Please don't add the addition option.
Rename operation should be out of Open/Save file directory settings.
Its behaviour is renaming onto its current directory, and no other option. User can change the location manually anyway.
