### ISSUE TITLE
CAN NOT edit the "*.lnk" file correctly

### ISSUE THREAD

**Issue by John8C** [notepad-plus-plus/notepad-plus-plus#10139]
### Description of the Issue

can not edit the "*.lnk" file correctly 

(If the old way gone forever with no choice, then, it is ok, but I have to force myself to turn to other editors. Sorry for the trouble. I do not want to edit the "target file" when I open the "*.lnk" file, I do know where the target files are, I can and I will open them directly if I want to edit them.)

### Steps to Reproduce the Issue

1. drag&drop the "*.lnk" file to the npp or open by File-->Open

### Expected Behavior

can edit the "*.lnk" file itself

### Actual Behavior

edit the linked/target file

**Comment by Suesskirsche** [comment]
Actually I would NOT want the requested behaviour. 
If it would be considered changing the behaviour, maybe this could be a compromise: 
a) If file type "link" is selected in open file dialogue, the "*.lnk" file itself is opened 
b) for all other file types the behaviour remains unchanged so that the file at which the "*.lnk" is pointing, is opened. 


Am 10. Juli 2021 19:51:35 MESZ schrieb John8C ***@***.***>:

**Comment by sasumner** [comment]
Behavior was changed with this: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e44ed31434a4768e797d8097406c9b8283e76049

It isn't going to be reconsidered; sorry.

**Comment by donho** [comment]
In PR #15364, Windows shortcut files itself can be opened, if its file extension is changed to whatever.
For example, rename `desktop.ini.lnk` to `desktop.ini.lnk.whatever`, then open `desktop.ini.lnk.whatever`, the shortcut content will be shown in Notepad++, instead of `desktop.ini` content.
Of course, if you modify the content, you're modifying `desktop.ini.lnk.whatever` but not `desktop.ini`.
