### ISSUE TITLE
Security flaw

### ISSUE THREAD

**Issue by notjaril** [notepad-plus-plus/notepad-plus-plus#10191]
not an issue per say, but a flaw non the less :)

the uninstall path in regedit is not quoted

![image](https://user-images.githubusercontent.com/4310548/126158395-f28a9152-3c84-453d-b865-57021a24e6dd.png)

**Comment by mere-human** [comment]
What are the risks? Why is it bad?

**Comment by vitaliyg2** [comment]
Hi @notjaril,
Can you please expand on this.
- why this is security flaw?
- why this path should be quoted?
- is there some documentation or guidelines about this?

**Comment by notjaril** [comment]
https://cwe.mitre.org/data/definitions/428.html this should sum it up pretty good
generally its best practise to quote any paths with whitespaces in it 😊

**Comment by oyundev** [comment]
You can use windows environment variables like this: %ProgramFiles%\Notepad++\uninstall.exe

**Comment by vitaliyg2** [comment]
Most of the software on my system have UninstallString quoted, but I also found some with unquoted paths.
I was able to reproduce this privilege escalation on Windows 10 system, so there is definitely security issue because of the unquoted path.
After dropping C:\Program.exe file - Uninstalling a program will execute Program.exe with elevated permissions instead of uninstaller if UninstallString contains unquoted path.

**Comment by notjaril** [comment]
> You can use windows environment variables like this: %ProgramFiles%\Notepad++\uninstall.exe

i can change it yes, but that is a rather reactive behavior instead of proactive behavior :)

**Comment by schenardie** [comment]
From my understanding thaty is a vulnerability on recurring executions like Services or things that will re-run.
Having that on an uninstall command line will only trigger:
1 if whoever created the program.exe had access to write to c:\ (not allowed for standard users by default)
2 the uninstall of notepad++ was triggered to happend at every reboot or x hours to consitute persistence.

That said is a best practice to use quoted paths or environment variables.

**Comment by ozone10** [comment]
duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6165

**Comment by ozone10** [comment]
@donho
this can be fixed with changing this line
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/4cc3d9fd1a5d4eeb7be093729a8885d3f049b622/PowerEditor/installer/nsisInclude/tools.nsh#L174
to
`WriteRegStr HKLM "${UNINSTALL_REG_KEY}" "UninstallString" '"$INSTDIR\uninstall.exe"'` 

from https://nsis.sourceforge.io/mediawiki/index.php?title=How_can_I_use_quotes_in_a_string%3F

currently I don't have access to my PC so I can't do PR
