### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by ellenkampguus** [notepad-plus-plus/notepad-plus-plus#10216]
I have been a very satisfied user of Notepad++ for a long time, also on Linux for the last few years. Works fine with Wine.

However, right now I am using a Raspberry Pi and it seems not easy to make Notepad++ run on that. So right now I am considering using another editor, no matter how satisfied I am with Notepad++.

Any clue if and when Notepad++ would be ported to Linux?

And I am looking for a project to learn C++, so this might just be it, to help with this port.

P.S. Couldn't find any related post really to my issue, except closed issues.

**Comment by mere-human** [comment]
Hi @ellenkampguus 

Notepad++ is a Win32 application so it's not easy to run it on Linux.
However, there are some ways to do that using Wine or Snap package.
Please, refer to these topics on the community forum:
https://community.notepad-plus-plus.org/topic/15377/notepad-as-a-linux-snap-app
https://community.notepad-plus-plus.org/topic/17192/npp-on-usb-for-unix
https://community.notepad-plus-plus.org/topic/13738/notepad-on-linux

If you search the issues, you may find a lot of similar ones.
Here you can get more info about why the Linux version isn't in the plans currently:
https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/FAQ#support-for-systems-other-than-the-ms-windows-family

Also, I'd suggest you asking questions on the community forum first:
https://community.notepad-plus-plus.org
This is a great place with people who might actually help you.
While GitHub exists to report BUGS (things that doesn't work as they should) or request features. 
So that the developers can actually implement them.

If that answers your question, please close the issue.

**Comment by ellenkampguus** [comment]
That doesn't relate to my issue. It seems some kind of standard reply. I am running Notepad++ on Linux for a long time already e.g. and I know it is a Windows application and why there is no Linux version (yet).

Just interested in a Linux version and interested helping with that.

**Comment by ozone10** [comment]
Notepad++ is using win32 API which doesn't work on linux. 
If you want Notepad++ to run natively on linux you have to rewrite it.
And because most code is Windows specific and using win32 API, you have to rewrite almost everything.

**Comment by mere-human** [comment]
@ellenkampguus If you read carefully the links I provided, you can definitely understand that the Linux version isn't a priority now. Nor is it in plans.
The priority is the stability/functionality of a Windows version.
This was mentioned a lot of times:
#108
#332
#6151
#7548
#9816
Hence is the section in FAQ.

**Comment by ArkadiuszMichalski** [comment]
There are no such plans, if something changes it will surely be communicated somehow.
