### ISSUE TITLE
N++ installer does not request elevation (on windows 10 under administrator account)

### ISSUE THREAD

**Issue by aaroneg** [notepad-plus-plus/notepad-plus-plus#1025]
This is a problem that especially affects the auto-updater. Any installer that doesn't request elevation will not be able to update/install notepad++ correctly on any machine with user account control turned on.

**Comment by dail8859** [comment]
I just downloaded the v6.8.5 installer and the first thing it does is request elevated privileges.

**Comment by aaroneg** [comment]
I have the same installer, and it doesn't ask. I don't know what the difference might be but here's a picture of it next to the NSIS installer. It's missing whatever flag Windows looks for to decide that the installer will need to be run as admin.
![10-19-2015 1-06-03 pm](https://cloud.githubusercontent.com/assets/1396671/10586563/5ffb5774-7662-11e5-801c-d4d1f44a8b17.png)

Are you running as a limited user? My account is an administrator but on Windows 10, programs are not automatically run with administrator permissions even under an admin account. The program has to be marked as 'needs admin' before it will run with admin permissions or prompt if there aren't any available under an account.

**Comment by dail8859** [comment]
I'm on W7 as a limited user. For me it does have the shield icon thingy. Also I have never touched W10 so maybe someone else can help out.

**Comment by aaroneg** [comment]
Thanks for having a look anyway. It's possible someone more familiar with NSIS can just look at the icons and know what's wrong. I'm looking at the code for the installer and it's over 2 thousand lines so I'm a bit overwhelmed as to where to begin.

**Comment by hanzworld** [comment]
Agreed. Had the same problem again even with 6.9.2. Administrator account, but when I run the installer I do not get prompted for elevated priveleges and as a result the install fails due to inaccessible files.

**Comment by donho** [comment]
@hanzworld @aaroneg I tested with an account non admin, I've got UAC popup for adm credential to install.
Could you give me more details of your environment so I can reproduce your issue?

**Comment by cdokolas** [comment]
I'm experiencing this same problem for many months now (I just kept putting-off the upgrade until it either worked or I would actually bother doing it manually). I can't complete the automatic update because of this. I downloaded the 6.9.2 installer and I can confirm that it doesn't ask for elevated privileges. I had to "Run as Administrator" for it to work.

**Comment by AlanLaViolette** [comment]
My system (Win7 x64) also does this and causes the upgrade to fail every time.  I had this issue with another software package we build and tracked it down to our IT department changes a UAC setting via GPO. 
“User Account Control: Detect application installations and prompt for elevation”
You can find this in the “Local Security Policy” under Local Policies | Security Options.  When disabled windows will not auto detect an install and so will not elevate to admin automatically thus forcing me to context click and select “Run as Admin”.  

To fix this you need to mark the installer with a UAC manifest as needing elevation
Microsoft KB on the issue
https://msdn.microsoft.com/en-us/library/aa905330.aspx

And how to enable in NSIS
http://nsis.sourceforge.net/Reference/RequestExecutionLevel 

And this issue is also the same problem https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1856

**Comment by MetaChuh** [comment]
not reproducible.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by aaroneg** [comment]
Well sure *now* it's not reproducible. 😂

**Comment by MetaChuh** [comment]
@aaroneg 

😂

my apologies, we have to write a closure reason, even when closing an issue that was forgotten to be closed a looooong time ago. 😉

some replies to an answer after 3-4 years can be very funny.
quite a few don't even remember that they have filed an issue back then, or what this notification is all about 😂😂😂

thanks and greetings
