### ISSUE TITLE
Trouble upgrading notepad++ using winget

### ISSUE THREAD

**Issue by scadden365** [notepad-plus-plus/notepad-plus-plus#10277]
### Description of the Issue

I want to use winget to upgrade notepad++. There is a problem, if notepad++ is open when the winget command is run, it doesn't upgrade, but winget reports that it has upgraded successfully. 
### Steps to Reproduce the Issue

1. open notepad++
2. run "winget upgrade notepad++" from windows terminal
Output
Found Notepad++ [Notepad++.Notepad++]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.1.2/npp.8.1.2.Installer.x64.exe
Successfully verified installer hash
Starting package install...
Successfully installed

### Expected Behavior
For notepad++ installer to have alerted that the application was open, and to ask to close it before the installation continues. 
This is the functionality with WinSCP

### Actual Behavior
It appears to be installed, and running : "winget list notepad++"
Name Id Version
Notepad++ Notepad++.Notepad++ 8.1.2

Winget thinks the latest version is installed.
But when you check "?" "About Notepad++" , it still shows the old version v8.1.1

### Debug Information

See winget ticket: https://github.com/microsoft/winget-pkgs/issues/22514

**Comment by OfficialEsco** [comment]
Again, this is false blaming. This has nothing to do with WinGet.
The issue is with the Silent Install, if you run the Notepad++ installer in interactive mode it will show this message
![image](https://user-images.githubusercontent.com/15158490/127215621-ec082ae0-a6ae-4d77-8c38-4a0d7adca04c.png)
If you run the Notepad++ installer in silent mode it will not display any message and exit with code 0, since it exists with code 0 it will "successfully" install Notepad++, however the program itself is not updated, but the registry strings are so it displays as it updated.

You can replicate this by having Notepad++ 8.1.1 installed and then having Notepad++ open while executing the 8.1.2 installer in silent mode.

The difference between the Notepad++ and WinSCP installer is that WinSCP is Inno while Notepad++ is NSIS.

**Comment by mere-human** [comment]
Related: #8514

**Comment by scadden365** [comment]
Related: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10189

**Comment by donho** [comment]
Notepad++ is not in Windows Store. The one on Windows store IS NOT Notepad++ official release.

**Comment by OfficialEsco** [comment]
Hes not talking about the unofficial Windows Store version, the winget-pkgs repo just contain installers (exe's, appxbundle, msix etc)
Anyways this is a duplicate of #10189 as scadden365 said
