### ISSUE TITLE
[DarkMode] Dark UDL and Styler

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#10283]
Notepad++ v8.1.2 does not apply dark mode on UDL and styler.

![image](https://user-images.githubusercontent.com/55940305/127371080-48afbac3-a749-4db0-a912-08fb499b9cbc.png)

**Comment by kczx3** [comment]
This might need to be revisited.  The tabs don't really look like tabs...  Just sort of floating there in the middle of the dialog.  At least to me, its not very clear of their function other than knowing due to experience with this dialog.
![image](https://user-images.githubusercontent.com/15206020/133218995-1d36b7dc-d8d7-4c9f-8421-f054f1e190e3.png)
