### ISSUE TITLE
Version 6.8.5 txt extension

### ISSUE THREAD

**Issue by arthurritic** [notepad-plus-plus/notepad-plus-plus#1029]
Version 6.8.5
When I save a txt file it no longer includes the txt extension
the file saves as "new 1" instead of "new 1.txt"

**Comment by donho** [comment]
In order to take advantage of modern save dialog, the save dialog behaviour is changed in the 2 latest releases.
**The old behaviour**: if user chooses one of the filters, the file name will be concatenated with a file extension.
**The new behaviour**: the file name won't be concatenated with a file extension if a filter is selected. User has to add the extension manually. The filter is used only for filter files.
It's a standard behaviour.

**Comment by nikunjbhatt** [comment]
@donho What does this mean "The filter is used only for filter files"? which files known as filter files? I have NPP 6.8.5, I will use the NPP of latest older version in which automatic extension was supported.

**Comment by nikunjbhatt** [comment]
I looked at the bug fixes info for all the version-subversion to 6.5 but unable to locate where this "bug" was fixed!
