### ISSUE TITLE
[MinGW] Questions about appveyor builds

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#10328]
Both MinGW appveyor builds (release and debug) are same, any reason building it twice?

Any reason to build dynamic binary, static is somehow working, but dynamic will crash for me.

Should warning flags `-Wall -Wpedantic` be enabled, to check for issues with code?

**Comment by donho** [comment]
@ozone10 
> Both MinGW appveyor builds (release and debug) are same, any reason building it twice?

What do you mean by `release and debug are same`? It follows the same schema of x86, x64 and ARM64, doesn't it?

**Comment by ArkadiuszMichalski** [comment]
Flag was commented:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/appveyor.yml#L38

**Comment by ivan-u7n** [comment]
> Any reason to build dynamic binary, static is somehow working, but dynamic will crash for me.

That's strange, for while I disable the build of the dynamic binary, I do it for speed of getting a binary after changing something in bundled Scintilla.

So I checked and it works for me (after copying required MinGW libraries into PowerEditor\bin):
```
Notepad++ v8.1.2   (64-bit)
Build time : Jul 26 2021 - 00:04:19
Path : F:\develop\notepad-plus-plus-master\PowerEditor\bin\NotepadPP_dynamic.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise LTSC 2019 (64-bit) 
OS Version : 1809
OS Build : 17763.2061
Current ANSI codepage : 1251
Plugins : DSpellCheck.dll mimeTools.dll nppConverter.dll NppExport.dll NppFTP.dll 
```

**Comment by ozone10** [comment]
@donho 
as @ArkadiuszMichalski  said flag was commented so appveyor now builds "release" version twice

@ivan-u7n 
I think I have figured it out, you need to have right version mingw installed to get the correct version of dll files.
If you have no mingw installed, it will give you error with not able to find function in dll and if you have wrong version it can crash.

So I think dynamic build can be disabled.

**Comment by ivan-u7n** [comment]
> I think I have figured it out, you need to have right version mingw installed to get the correct version of dll files.
> If you have no mingw installed, it will give you error with not able to find function in dll and if you have wrong version it can crash.

@ozone10 yeah, I copied three required DLLs strait from the `bin` directory of the mingw version I use to build Notepad++ with. Ofcourse, mismatched DLLs can ruin everything.

> So I think dynamic build can be disabled.

I agree, especially considering that all required system libraries are still linked dynamically even in the static build. And without having the required mingw DLLs, the dynamic binary alone is useless.

PS. By the way, do I have to make a pull request for considering a patch for inclusion?

**Comment by mere-human** [comment]
Maybe @chcg can provide some information.

**Comment by donho** [comment]
@ivan-u7n 
> PS. By the way, do I have to make a pull request for considering a patch for inclusion?

If the change is only build system, go ahead please.
Also remove [the comment](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10328#issuecomment-892685794) please so the debug build is included.

**Comment by ivan-u7n** [comment]
@donho

> If the change is only build system, go ahead please.
> Also remove [the comment](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10328#issuecomment-892685794) please so the debug build is included.

Here we go: [notepad-gcc-build.patch.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6947163/notepad-gcc-build.patch.txt)

The `makefile` was rewritten:
- to auto-discover headers, sources and resources;
- to have independent build directory;
- to support debug build for Notepad++ itself;
- to support overlaying files from the `../src` directory;
- to fully work from the MSYS2 shell (the current doesn't `clean` at all).

Not sure I recalled all the new features. But some things are commented out:
- I tried to call Scintilla's makefile directly to have only one command to execute, but that makefile doesn't clean up everything and causes problems;
- it turned out that full debug build (with `DEBUG` defined) currently isn't possible because mingw `std::ifstream` doesn't know how to work with `wchar_t` filenames, and thus this part is also commented out.

However to "compensate" for the latter, the debug build enables `-Wall` and `-Wpedantic`, and it produces loads of warnings.

The compilation of resources from the `../src` directory causes the deletion of now unnecessary `resources.rc`. The small `gcc-manifest.rc` was added to embed the proper manifest into the resulting binary.

The patch also modifies `include/various.h` to the bare minimum required for build with mingw-w64 8.1.0 to success. Still, I'd rather have moved this file into its parent `gcc` directory, renamed it to something like `gcc-fixes.h`, and deleted from it all of the commented out legacy. But moving or renaming files and preserving their history isn't possible via a patch.

The `appveyor.yml` file is also modified to follow the changes in `makefile`.

**Comment by mere-human** [comment]
> Here we go: [notepad-gcc-build.patch.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6947163/notepad-gcc-build.patch.txt)

@ivan-u7n Why don't you submit a normal PR?

**Comment by ivan-u7n** [comment]
@mere-human Because I don't use git on a daily basis, or rather I don't use git at all. Thus for me to learn some basics of git and GitHub for a single PR is IMHO an overkill.

Also I asked whether a patch would be accepted, otherwise I wouldn't have bothered with making it.

**Comment by chcg** [comment]
@ivan-u7n Thanks for providing the patch. I will have a look at it and create a PR out of it. Commenting out the debug build for scintilla was just by accident.
I didn't do larger reworks of the makefile as I don't build with mingw locally, but just as additional check via appveyor and therefore don't want to invest to much time into it.

**Comment by ivan-u7n** [comment]
> I didn't do larger reworks of the makefile as I don't build with mingw locally, but just as additional check via appveyor and therefore don't want to invest to much time into it.

Yep, I understand. But I do build Notepad++ locally with mingw, moreover I use the resulting binary instead of the official build. Thus a better build system for gcc will make my job a little easier.

I have prepared [an updated patch](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6950439/notepad-gcc-build-2.patch.txt). It now builds Scintilla as a part of the build process, thus now there is no need to build it separately. The patch also updates `BUILD.md` to reflect the changes in `gcc/makefile`. The latter is also tweaked a little, but its functionality is the same.

I won't make more updates to the patch as now I consider it as good as it can be.

PS. I googled a bit and found out that creating PR isn't that hard, but I still need to install git. I'll look at it when I can spare some time, but it's a patch file for now.

**Comment by chcg** [comment]
See https://github.com/chcg/notepad-plus-plus/commit/ef8084f0dbbaa6aa36e5659865e9fb35d733bc17 for the changes from the first patch and the corresponding  build https://ci.appveyor.com/project/chcg/notepad-plus-plus/builds/40491562. For N++ no debug build was possible before. 
It takes ~ 2 minutes more and the artifact is 104 MB. The release version is just 5 MB now and similar in size to the VS Studio one. The dynamic build is skipped and I think that is ok as otherwise a mingw environment/additional dlls would be necessary to run the binary. @donho Is that ok for you?

I will check the updated patch.

**Comment by donho** [comment]
@chcg 
It seems good to me. We can remove debug build from our build system.
Please do a PR and I will merge it into master.
