### ISSUE TITLE
Consider renaming cancel button in save all dialogue

### ISSUE THREAD

**Issue by Wxrlds** [notepad-plus-plus/notepad-plus-plus#10339]
The ``cancel`` button on the save all dialogue is kind of non intuitive and should be renamed to ``Yes, don't ask again``.
Yes, while the box says exactly what the ``cancel`` button does, I think it's function can be made more descriptive by renaming it to say ``Yes, don't ask again``.
Background of this is, the save and save-all button are right next to each other, so a misclick is guaranteed to happen at some point. When that happens I assume most people don't read what the dialogue box says but just hit the ``cancel`` button because essentially everywhere cancel means don't do whatever I just clicked. Renaming that button to ``Yes, don't ask again`` most likely causes people to hit ``no`` instead.
![image](https://user-images.githubusercontent.com/42120270/128382042-e3532736-8a26-441f-8e69-125978b1e3ff.png)

### Debug Information
Notepad++ v8.1.2   (64-bit)
Build time : Jul 16 2021 - 01:59:50
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19043.1110
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppSaveAsAdmin.dll

**Comment by mere-human** [comment]
But it is explicitly said in the dialog what "Cancel" does:
`
Choose "Cancel" if your answer will always be "Yes" and you won't be asked this question again.
You can re-activate this dialog in Preferences dialog later.
`

**Comment by Wxrlds** [comment]
I suppose it's just not consistent with the other dialogues.
Like when you have a new (or existing) modified file and press the close file button it shows this dialogue where cancel doesn't save the file neither discards the changes but just closes the dialogue box.
![image](https://user-images.githubusercontent.com/42120270/128549005-0567cb33-ca44-4268-8fbc-3c8da8eb6eaf.png)
The same dialogue shows when you press the close-all button where cancel behaves the exact same as with the close single file dialogue.
I'm sure there are a lot more other dialogue boxes where cancel just closes the dialogue and pretends as if that box never was open like in "replace all in all open documents"

**Comment by pryrt** [comment]
> But it is explicitly said in the dialog what "Cancel" does:

I agree that it says explicitly what it does, but "Cancel" still holds a longstanding tradition in Windows UI, saying "don't do whatever I opened this dialog box to do".  And by using the "Cancel" button here to do completely the opposite (ie, "Always do whatever I opened this dialog box to do"), it breaks the standard expectations of users -- and "[least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)" is an important concept in user-interface/software design, which "Cancel" in this dialog box breaks.

I understand that Yes/No/Cancel is a simple dialog box to program.  And when you've got a limited suite of UI commands available to you (ie, just using the MessageBox command in a language like VBA for making an Excel macro), it makes sense to abuse the meaning of those buttons because you only have a limited set.  But in a custom-written application, where it's not overly difficult to create a new custom dialog box with three buttons that mean exactly what you want, it is better to go the route that doesn't change the meaning of standard windows buttons.

See the discussion in the Forum [here](https://community.notepad-plus-plus.org/topic/21654/control-shift-s-save-all-file-repeats-dialogue-again-and-again) for one user-in-the-wild's frustration.

**Comment by mere-human** [comment]
I agree, it might be not very intuitive. I'd like to rework it.

**Comment by vsrawat** [comment]
suggest to give a separate tick box somewhere in the warning window saying “don’t ask me again”, and then just "Yes" or "No" would have suffice.

**Comment by mere-human** [comment]
So I have these options:

1. Show "Save All" dialog with 4 options: 
[Yes] [No] [Yes to all] [No to all], [X] button cancels the process.
![image](https://user-images.githubusercontent.com/9664141/129440804-2931bab5-ff56-4b02-86ac-7d2e2ea6577e.png)
This would be consistent with the dialog shown upon closing when there are several modified documents.

2. Show "Save All" dialog with 3 options + checkbox:
[Yes] [No] [Cancel]. When checkbox is checked, the selected option is applied to all the documents.
![image](https://user-images.githubusercontent.com/9664141/129441098-fddbc4e9-76e9-4890-946a-ea98d2aaa69c.png)
This is less consistent with other places. But someone might like it more.

Option 2 is a modified solution of @vsrawat idea. I just want to emphasize here that the choice will affect "Save All" only this time.
I think "Don't ask me again" can be interpreted as "don't ask me never again". While this is also an option, it looks more like a preference (or a shortcut for a preference).

@pryrt @Wxrlds What do you think?

**Comment by vsrawat** [comment]
On 8/14/2021 2:46 PM, mere-human wrote:
> So I have these options:
> 
>  1.
> 
>     Show "Save All" dialog with 4 options:
>     [Yes] [No] [Yes to all] [No to all], [X] button cancels the process.
>     image
>     <https://user-images.githubusercontent.com/9664141/129440804-2931bab5-ff56-4b02-86ac-7d2e2ea6577e.png>
>     This would be consistent with the dialog shown upon closing when
>     there are several modified documents.
> 
>  2.
> 
>     Show "Save All" dialog with 3 options + checkbox:
>     [Yes] [No] [Cancel]. When checkbox is checked, the selected option
>     is applied to all the documents.
>     image
>     <https://user-images.githubusercontent.com/9664141/129441098-fddbc4e9-76e9-4890-946a-ea98d2aaa69c.png>
>     This is less consistent with other places. But someone might like it
>     more.
> 
> Option 2 is a modified solution of @vsrawat <https://github.com/vsrawat> 
> idea. I just want to emphasize here that the choice will affect "Save 
> All" only this time.
> I think "Don't ask me again" can be interpreted as "don't ask me never 
> again". While this is also an option, it looks more like a preference 
> (or a shortcut for a preference).

Good analysis.

Yes, I concede that "Don't ask me again" can be interpreted that way.

So instead of "Don't ask me again", you can make that "Remember my answer".

That leaves no confusion that this will the answer every time.

--

Ever since I started using npp I have using Control-Shift-S to save all 
open files in one go.

What prompted you to change that? Does some user want some other event 
to be associated with this key-combo?

What he/ she wants Control-Shift-S to do instead, if it will not be 
saving all open files?

Thanks.
-- 
Rawat


> 
> @pryrt <https://github.com/pryrt> @Wxrlds <https://github.com/Wxrlds> 
> What do you think?

**Comment by mere-human** [comment]
> What prompted you to change that? Does some user want some other event to be associated with this key-combo?

I can only say it was a fix for #2124, #9931

**Comment by pryrt** [comment]
> While this is also an option, it looks more like a preference (or a shortcut for a preference).

Technically, it already is a preference, one which you could in theory checkmark before doing your first SaveAs.  It's just affected by your choice in the existing dialog.

> 1. Show "Save All" dialog with 4 options:
> 2. Show "Save All" dialog with 3 options + checkbox

Both your #1 and your #2 only have buttons that are just for this instance of the SaveAs.  And I do like the feature in the current dialog which allows it to toggle the MISC preference setting so that it doesn't ask for confirmation -- I just don't like its name.  So I would want some way to affect that setting from this dialog.

Personally, with a Save All dialog, I don't understand the need for a "No to All" that's separate from "Cancel", because they both mean, "no, I didn't actually mean to Save All".

Maybe something like
![image](https://user-images.githubusercontent.com/17455758/129456916-5606026f-6a08-4e1b-b935-daa4f1c5c383.png)

**Comment by mere-human** [comment]
> Personally, with a Save All dialog, I don't understand the need for a "No to All" that's separate from "Cancel", because they both mean, "no, I didn't actually mean to Save All".

Right.

> Maybe something like

This is good. Except that it seems like a lot of text in there. I consider that even in the current state, there are a lot of text.
We're all busy so often we want to skip this.

I had an idea of controlling the preference explicitly via the checkbox. This is done in some other programs:
![image](https://user-images.githubusercontent.com/9664141/129459382-d7f774a1-967e-4167-b385-0531c710e479.png)

To give user a hint, we can show a tooltip on it.
So here's my new version of this dialog:
![image](https://user-images.githubusercontent.com/9664141/129459367-631056da-bdd2-4b7a-a07d-93f8a82149a4.png)

**Comment by pryrt** [comment]
Yeah, the four option with a checkbox would work for me

You might want to run that one by the Forum post (linked above) so Alan can chime in, too.

**Comment by MarkusBodensee** [comment]
Have you considered the use case of:

- Do not ask again --> checked.
- Hit No Button

It will not save files anymore and the Dialog won't show up anymore. So the button just makes nothing without user information. Not user friendly, if a user clicked by accident.

I think, "Do not ask again option" should only be checkable if the anwer is "yes". So a checkmark control is not good.

**Comment by mere-human** [comment]
> It will not save files anymore and the Dialog won't show up anymore. So the button just makes nothing without user information.

Wrong. No means "don't save the current file". After checking the "Do not ask again", this confirmation dialog won't be shown. But the Save As dialog for any unsaved files left will be shown.



> I think, "Do not ask again option" should only be checkable if the anwer is "yes".

Not possible, because pressing any button will confirm the dialog and close it. This is how dialogs work.
I've updated my comment above with the explanation. Check it out.

**Comment by MarkusBodensee** [comment]
Misunderstanding: What I meant with "the button just makes nothing" is, that the "Save All Button" makes nothing anymore, because I interpreted the option as "Remember my decision and don't ask anymore". If this is done by accident, would be really bad, because the functionality of this button would be removed.

But I think you mean it the other way round: The checked checkbox just don't show up the dialog anymore after confirmation. But in this case, the user still gets confused with the use case of checked checkbox and hitting "No". Because of the answer for the next file switches implicitly to "Yes" (you say Save As diaglogue will show up), and dirty files will be saved, too, without further confirmation.

**Comment by mere-human** [comment]
> I interpreted the option as "Remember my decision and don't ask anymore". If this is done by accident, would be really bad, because the functionality of the "Save All Button" would be removed.

What I meant for "Don't ask again" is just a shortcut for the checkbox in Preferences > MISC > Enable Save All confirm dialog.
That's all. It is not related to Yes/No buttons.
The preference only affects the confirmation dialog for Save All. It doesn't disable the Save As dialog that is shown for each modified file.


> Because of the answer for the next file switches implicitly to "Yes" (you say Save As diaglogue will show up), and dirty files will be saved, too, without further confirmation.

Right. But since the Save As dialog will be shown, the user has an opportunity to cancel the saving of an individual file by hitting the Cancel button:
![image](https://user-images.githubusercontent.com/9664141/129689704-ad3e8388-e800-446d-b310-e1ed2af36239.png)

**Comment by MarkusBodensee** [comment]
But not if it is just a dirty file which is already saved to disc. With your logic, further dirty files would be saved implicitly if the checkbox is checked and the user hits "no".

The option from the settings only makes sense if your answer will be "yes to all". This is why a checkbox as suggested is not good and will only add confusion.

Looks like the discussion went away from the original issue, and is now more like a feature request. ;-) I like the per file choice for yes/no. So the user can just hit "Save All" and then control with the confirmation dialogue to just save some files without having to navigating through the tabs and hit "Save" for each file individually.

@pryrt 's dialogue suggestion would cover all use cases.

**Comment by vsrawat** [comment]
On 8/18/2021 1:46 AM, MarkusBodensee wrote:
> 
> I like the per file choice for yes/no. 
> So the user can just hit "Save All" and then control with the 
> confirmation dialogue to just save some files without having to 
> navigating through the tabs and hit "Save" for each file individually.
> 

Ever since I started using npp, I have some 5-8 files open in npp all 
the times, and I coolly used to pressed Control-Shift-S to save all, and 
it did the job well.

I didn't ever go to Menu-File-SaveAll

Now, that thing is broken for millions of users to suit one person's 
problem.

Why would you want me to click - Menu - File - SaveAll and then click 
Yes for each of the 5-8 files.

You are increasing my work to suit your need, when you are not able to 
make any change in your way of working. That is not fair.

When a new user comes to know of a software and start using it, he has 
to learn it, know its defaults, keyboardshortcuts, menu, settings, etc. 
And he has to adapt to whatever is already there. If some thing is not 
working or is creating confusion to him, he an raise in forum and 
something can be done about it.

But one user saying that he has problem with one Command, so it has to 
be, must be changed for all user, this is not the way any software work.

Did you or the OP ever tried to make MS to one single change in MS Word 
or MS Excel? God forbid, they will not listen, they will not 
acknowledge, they will not respond, they would just ignore us fully and 
totally. And we have to live with all the bugs and confusions of MS 
products.

But, here is a responsive developer and contributing forum, so we tell 
our problem and give suggestion.

Whenever I install npp afresh, I takes me several minutes to change 
defaults, settings, various files and folder disks, to make it reflect 
how it was in my previous npp installation. Then I use it for years 
without any complaint till the next breakdown of "not" npp, but of windows.

I change some shortcut every new install because I am used to MS Word, 
and I change npp's shortcuts to match MS word's keyboard shortcuts.

Similarly, if a single user has a problem, why doesn't he/ she just go 
to shortcut mapper and delete or change the problematic shortcut.

And saying that "I accidently end up clicking SaveAll every time instead 
of Save", it is kiddish really.

If you want confirmation dialogue, then their has to be confirmation 
dialogue to each and every thing we do in npp because this or that 
person must be clicking something wrongly. That will kill npp.
--

Another solution for the user having that problem is -

He should select verbose backup in npp, so that various versions of same 
file gets saved.

Whenever he commits the mistake of wrongly "savingall", he can fetch 
older versions of all his open files from npp backup folder. Of course, 
some minutes changes would have been lost, but still his entire file has 
not got bad, and he can revive a good great part of it.

And once he takes trouble of doing this drill for certain time, it will 
train his mind to work more cautiously and he will not click saveall by 
mistake.

--
My Control-Shift-S should not get changed in any whatever miniscule way, 
that is all my worry is and that is what I want.

Thanks.
-- 
Rawat

**Comment by pryrt** [comment]
@vsrawat ,

You have already been told in the forum: for now, if you want to not be asked, just read the dialog box and follow those instructions, or go to the Preferences and uncheck the "Enable Save All confirm dialog" setting on the MISC page.  The discussion in this issue is about how best to design a better dialog box so that people won't be as confused in future versions.  Your big rant doesn't help design a better dialog box.

**Comment by vsrawat** [comment]
If this is not related, I don't know why somebody gave me the link to 
this issue to me.

What a wastage of my time and energy.

Thanks for saving me from this.

However, I think the developers have lost their grip on coding and 
thinking, the shabby implementation of that SaveAll thinggy. So they 
should first solve that to the satisfaction of all users, then take up 
anything else, otherwise they will spoil other parts also.

-- 
Rawat

**Comment by pryrt** [comment]
@vsrawat ,

If you're talking about this
![image](https://user-images.githubusercontent.com/17455758/129924998-7fe7118e-cb34-486e-ada2-35c40f337a0e.png)
that link was from _me_.  (notice my icons are the same on both sites, even though I use PeterJones over there and pryrt here)

I directed the readers of that discussion to this issue so they could constructively contribute, and weigh in on the suggested new designs for the dialog box, to make it better like you wanted.  

If you had said, "yes, that new design that has been suggested will be an improvement, and I would understand what it was trying to do", that would be helpful; if you had said, "no, this doesn't quite solve my problem; instead, could you try xxxx or yyyy", that would have been helpful.

On the other hand, saying
> However, I think the developers have lost their grip on coding and
thinking, the shabby implementation of that SaveAll thinggy.

is just being rude for the sake of being rude, and will not help anything.

If you had constructive replies to the ideas suggested in this issue, feel free to weigh in again.

**Comment by ArkadiuszMichalski** [comment]
Using `Cancel` here is very confusing, Now when testing a new approach I noticed that I often click `Cancel` (intuitively) and instead of canceling the action (which `Cancel` should does) I actually approve it permanently and have to restore this dialog via Preferences again. I know there is a description, but it should be for some non-standard names.

The question is whether this dialog should apply to all files only (as it is now), or to all and each of them separately. Because this determines the number of potential buttons. And if the switch (to not ask again) necessarily have to be in this dialogue, or can't it stay only in MISC? A similar question is in Searching, and there is no additional switch in the Replace window.

@donho do you have any suggestions/preferences here?

**Comment by vsrawat** [comment]
and when you wrote

 >  Your big rant doesn't help...

You were also being rude, so the provocation was first fired by you.

Terming something "rant", "trolling" gives a bad color to it, and then 
no one looks at what exactly the content was, they just don't read a 
rant or trolling.

You did that. called it that and didn't see that I am writing no jokes 
or film stories, I am actually and 100% talking about npp and the 
problem that brought me here and my suggestions were to the point to 
solve the op's problem without disturbing others.

But you don't find that part appreciable, you call it a rant. as if I 
had written about Afghanistan or Talibans here.

Good. You love rants or you love to call things rant. tells something 
about your personality or thinking or psychological needs.

Anyway. At least you have no right to talk about "someone being rude" as 
you yourself have been. You don't see you own action and come to advise 
others.

You keep a good friendly helping environment, and other will also do the 
same.

Thanks.

**Comment by pryrt** [comment]
I did not intend to offend.  If you took it as such, all I can offer is my apologies.

If you have something constructive to add to the issue, feel free to contribute.

**Comment by ozone10** [comment]
I prefer this approach https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10339#issuecomment-898956064
Here is some inspiration from Firefox when closing multiple tabs
window
![image](https://user-images.githubusercontent.com/55940305/129940962-655d467a-6a01-4dbb-a576-0a1c01c62f18.png)
setting
![image](https://user-images.githubusercontent.com/55940305/129941008-d96006df-1e43-48b2-963f-8a8137bc3779.png)

**Comment by donho** [comment]
This dialog is introduced for preventing from miss-click of save all button. I agree the "Cancel" button is misleading.

> So here's my new version of this dialog:
> ![image](https://user-images.githubusercontent.com/9664141/129459367-631056da-bdd2-4b7a-a07d-93f8a82149a4.png)
> 
> _Yes to all_ - save all modified documents, show the _Save As_ dialog for each of them.

The checkbox may be good, but there are too many buttons, too much info, and do too many stuffs. 
IMO, all we need is the same dialog, but rename the button "Cancel" to "Always Yes" + tooltip to notice user that he/she can change this setting in preference dialog.
