### ISSUE TITLE
JSHint and JSLint have stopped working in NPP 6.8.5

### ISSUE THREAD

**Issue by axtens** [notepad-plus-plus/notepad-plus-plus#1035]
Context: Windows 10 Home 64bit.

Ever since the upgrade to 6.8.5, I have not been able to use this tool. I have uninstalled and reinstalled this tool to no effect. I'm stuck with using Sublime Text until it's fixed. Total show stopper.

**Comment by dail8859** [comment]
Define "not been able to use this tool", this could mean *alot* of different things. Also, try posting a bug report to the authors of JSHint and JSLint.

**Comment by dail8859** [comment]
> I'm stuck with using Sublime Text until it's fixed.

Why don't you just stick with whatever version of Notepad++ last worked for you

**Comment by axtens** [comment]
>  whatever version of Notepad++ last worked for you

Yeah, less panic, more thought. Thanks.

OK, by not working I mean that I open a .js file, make sure that the language is set for javascript, and then request a jshint pass. NPP then tells me that it can only do that for javascript files.

**Comment by axtens** [comment]
Went back to 6.8.3. Everything working now. Phew ... sort of.

**Comment by ffes** [comment]
Those plugins most likely need to be made aware of the new `L_JAVASCRIPT` language that was introduced in one of the latest version (not sure which one exactly, can't find it in the release notes sadly enough, haven't look at the code, assume it is since 6.8.4).

The `L_JS` apparently is now used for embedded JS (in html, with a gray background color) and the new one is used for standalone js files, with a white background color in the editor (at least in the default color scheme).

You need to contact the authors of those plugins to ask them to make their plugin aware of this new `LangType`. It is probably a small fix for them.

**Comment by XelaNimed** [comment]
I can propose workaround. It is possible to use NodeJS the JSHint module by means of NppExec plug-in.

1. Install NppExec plugin.
2. Install NodeJS, if it isn't install yet.
3. Install JSHint: `>npm install -g jshint`.
4. Press `F6` in NPP or select in submenu `Plugins>NppExec>Execute...` and insert: 

    NPP_SAVE
    cmd /K (CD "$(CURRENT_DIRECTORY)" && jshint "$(FILE_NAME)" && exit) || exit
5. Press on `Save` button and set name for this snippet, ex. `Run JSHint`.
6. Press in menu `Plugins>NppExec>Advanced options...` and make sure that checkbox `Place to the Macros submenu` is checked. In select menu `Associated script` select snippet name (see Step 5) , ex. `Run JSHint`. In text field `Item name` you can set name which displayed in `Macro` submenu.
7. Now you can set shortcut for this snippet in `Macro>Modified Shortcut/Delete Macro...` submenu, tab `Plugins commands`.

I hope it to somebody will help.

**Comment by axtens** [comment]
Wow, that is really cool. Brilliant idea. Thanks!!!!!

**Comment by XelaNimed** [comment]
May be closed this issue, because plugin is already updated?
http://sourceforge.net/projects/jslintnpp/files/0.8.3/
