### ISSUE TITLE
Issue: No Toolbar Tooltips

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#10355]
After commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/733c7e73de6d5dece3bcd9eb8784fd2bf61da359 main toolbar tooltips are not showing

**Comment by Yaron10** [comment]
I couldn't reproduce it.
I've downloaded a fresh portable NPP, replaced the EXE file with the one containing https://github.com/notepad-plus-plus/notepad-plus-plus/commit/733c7e73de6d5dece3bcd9eb8784fd2bf61da359 and, indeed, no toolbar tooltips.

It turns out that with the "Customize Toolbar" plugin, the toolbar tooltips do show.

**Comment by Ashfaaq18** [comment]
@ozone10, thanks for spotting this issue. Ill look into this.
