### ISSUE TITLE
Seems smart quotes in License text transform into strange symbols

### ISSUE THREAD

**Issue by WanderingProgrammer** [notepad-plus-plus/notepad-plus-plus#10370]
### Description of the Issue

Screenshot
![](https://i.imgur.com/szaQJx5.png)

(It probably occurs in few more places in License text)

This issue was found in Notepad++ v8.1.2 (though it probably spans since v7.9.3) Windows 32-bit
Some details were offered in forum thread [https://community.notepad-plus-plus.org/topic/21622/notepad-v8-1-2-license-strange-symbols](https://community.notepad-plus-plus.org/topic/21622/notepad-v8-1-2-license-strange-symbols)
It was suggested that this problem started with commit [ab5c1d3](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ab5c1d3)

**Comment by pryrt** [comment]
As I mentioned in that forum discussion, the two possible fixes:
1) improve the installer's dialog, so that it properly displays a UTF-8-encoded file
or
2) edit the source [LICENSE](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/LICENSE) file to not use smart quotes and instead have straight ASCII quotes.

The first would be the "right" thing to do.  But the second would be a simpler solution -- just search for `[“”]` and replace with `"`

**Comment by mere-human** [comment]
> 2\. edit the source [LICENSE](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/LICENSE) file to not use smart quotes and instead have straight ASCII quotes.

I would suggest simply replacing the quotation symbol.
This way it is done in other repositories (look for "TERMS AND CONDITIONS"):
https://github.com/x64dbg/x64dbg/blob/development/LICENSE
https://github.com/gorhill/uBlock/blob/master/LICENSE.txt

**Comment by donho** [comment]
@WanderingProgrammer 
Could you provide your `Debug Info` please?

**Comment by pryrt** [comment]
@donho,

`Debug Info` comes after the installation.  This is the installer itself that's having the problem.  So I'll provide links to the exact downloads that I used to replicate/confirm the original problem.

I just tried with the [v7.9.3 64bit installer](https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.9.3/npp.7.9.3.Installer.x64.exe) and the [v8.1.3-64bit installer](https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.1.3/npp.8.1.3.Installer.x64.exe) and both showed the problem.  (I cancelled these installations after the license page to not mess up my normal installation)

![image](https://user-images.githubusercontent.com/17455758/129457833-41a62685-914b-4a45-a62f-7445338a1358.png)
![image](https://user-images.githubusercontent.com/17455758/129457858-d9dee6cb-ad4a-4f90-a1e8-f3117122391f.png)

I then also downloaded the [v7.9.3 32bit installer](https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.9.3/npp.7.9.3.Installer.exe) and [v8.1.3 32bit installer](https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.1.3/npp.8.1.3.Installer.exe) and they did the same thing (not shown, because those installer dialogs are identical)

If I download [v7.9.2 64bit installer](https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.9.2/npp.7.9.2.Installer.x64.exe), it _doesn't_ show this problem:
![image](https://user-images.githubusercontent.com/17455758/129458020-3fd354fc-3b5c-4057-9be4-0f71a2f3aedb.png)

This is because in commit ab5c1d3 when GPL was updated from v2 to v3, the new GPL v3 file had smart quotes, encoded as UTF-8, whereas previously, the GPL v2 file only used ASCII quotes.  See this screenshot of the LICENSE file:
![](https://community.notepad-plus-plus.org/assets/uploads/files/1628628752863-c34d7c4e-7097-4d62-bb93-212a02b6561b-image.png)
or look at the [LICENSE](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/LICENSE) file itself to see the smart quotes in the file.

Commit ab5c1d3 was first released in v7.9.3, which is why the installer didn't show the funny characters in v7.9.2-or-earlier, but does in v7.9.3-and-later

**Comment by donho** [comment]
> `Debug Info` comes after the installation. This is the installer itself that's having the problem. So I'll provide links to the exact downloads that I used to replicate/confirm the original problem.

I would like to have debug info not for having the version of Notepad++ but for having the version of Windows. But if such problem happens also under Windows 10, it should be fixed. @pryrt could you confirm that?

**Comment by pryrt** [comment]
Yes, mine is Windows 10.  Specifically, 
```
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19043.1165
Current ANSI codepage : 1252
```
