### ISSUE TITLE
CSS pseudo-elements not recognized

### ISSUE THREAD

**Issue by vsl7** [notepad-plus-plus/notepad-plus-plus#10425]
Notepad++ doesn’t recognize CSS pseudo-elements in the form `::pseudo-element`, unlike `:pseudo-element`. SciTE doesn’t have this problem.

**Comment by mere-human** [comment]
Which version of SciTE did you try?

**Comment by vsl7** [comment]
@mere-human Latest version.

**Comment by mere-human** [comment]
> @mere-human Latest version.

You should post the exact numbers. So that people who'll read this in future don't need to guess what was "the latest" at that time.
Also, I'm asking because Notepad++ uses a specific version of Scintilla ([4.4.6](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9550) IIRC) which may be not the latest.

**Comment by vsl7** [comment]
SciTE v. 4.4.6 also doesn’t have this problem.

**Comment by ArkadiuszMichalski** [comment]
Only two list was set:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScintillaComponent/ScintillaEditView.h#L680

```
	void setCssLexer() {
		setLexer(SCLEX_CSS, L_CSS, LIST_0 | LIST_1);
	};
```

what represents "CSS1 Properties" and "Pseudo-classes"
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/lexers/LexCSS.cxx#L555

Now it's wrong because pseudo-elements was listed as pseudo-classes:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/langs.model.xml#L122

 and in practice when we use "::" for them  (not ":" as for pseudoclasses)  we get `UNKNOWN_PSEUDOCLASS` style, so even not `PSEUDOCLASS` style. 
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/stylers.model.xml#L331

Info:
https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements

**Comment by vsl7** [comment]
@ArkadiuszMichalski @donho
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScintillaComponent/ScintillaEditView.h#L681
Should it be
`setLexer(SCLEX_CSS, L_CSS, LIST_0 | LIST_1 | LIST_0 | LIST_0 | LIST_1);`
or
`setLexer(SCLEX_CSS, L_CSS, LIST_0 | LIST_1 | | | LIST_1);`
?

**Comment by ArkadiuszMichalski** [comment]
I suppose `LIST_0 | LIST_1 | LIST_4` (at least), but you also need to update `langs.model.xml` and `stylers.model.xml` properly.

**Comment by vsl7** [comment]
@donho The problem is that _known_ pseudo-elements in the form with double colon (`::after` element here) are recognized as UNKNOWN_PSEUDOCLASS. The two “unknown” elements are given for example of highlighting of unknown pseudo-elements and unknown pseudo-classes. It is seen that in Notepad++ `::after` is not recognized as well as these two. In SciTE unknown elements have red highlighting, so `::after` is recognized.

**Comment by donho** [comment]
@vsl7 
Considering the following CSS code you provide:
```
:active, ::after, :after, ::unknown, :unknown {

}
```
`:active` and `:after` are **PSEUDOCLASS**.
`::after` is **PSEUDOELEMENT**.
 `:unknown` and `::unknown` are **UNKNOWN_PSEUDOCLASS** & **UNKNOWN_PSEUDOELEMENT** respectively.
 
 Could you confirm the description above?

**Comment by ArkadiuszMichalski** [comment]
@donho 
`:after` is also pseudoelement (notation with `:` comes from old specs). In new specs only `::` should be used for pseudoelement (browsers still support old notation for compatibility reasons).

In[ css lexer](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/af56713079c9e31b8c81b5603a6c841afb3e2005/scintilla/lexers/LexCSS.cxx) this [SCE_CSS_UNKNOWN_PSEUDOCLASS](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/88ee2eddb043193a1162957a862394dfa620781a/scintilla/include/SciLexer.h#L874) represents both not recognized `:` and `::`.

The question is what to do with the old `:` because the lexer doesn't recognize it as a pseudoelement (will use pseudoclass style). They can be omitted from pseudoclass words (so they will be treated as unknown, which makes sense because it's not pseudoclass anyway) or listeed in pseudoclass words and will get pseudoclass style.

I planned to open a bug for the css lexer to recognize the old `:` for pseudoelements,  but it's only 4 cases, checking each class for only these 4 cases can affect performance. I have encountered the same problem recently in this library:
https://github.com/highlightjs/highlight.js/issues/3240

**Comment by donho** [comment]
@ArkadiuszMichalski 
Thank you for the explanation.

Could you provide me the psudo-element keyword list (or the link) please? I'm updating CSS keywords list and adding new stylers.

**Comment by donho** [comment]
Found this link:
https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements

Not sure it's all keyword list.

**Comment by ArkadiuszMichalski** [comment]
Actually MDN is official for all browsers (there are also links to specs):
https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements

but not much in this case, so:
https://www.w3.org/TR/CSS1/#pseudo-classes-and-pseudo-elements
https://www.w3.org/TR/CSS22/selector.html#pseudo-element-selectors
https://www.w3.org/TR/selectors-3/#pseudo-elements
https://drafts.csswg.org/selectors-4/#pseudo-elements

https://drafts.csswg.org/css-pseudo-4/
https://drafts.csswg.org/css-pseudo-4/#index-defined-here << see those with "::".

Some are also defined elsewhere, still in the testing phase. Generally, it is best to just add support for the pseudo-element list and provide some basic ones in it. This list can be completed in the future.

This are support in all current browsers:

::after (:after)
::before (:before)
::first-letter (:first-letter)
::first-line (:first-line)

::selection
::cue
::file-selector-button
::placeholder

**Comment by donho** [comment]
@ArkadiuszMichalski 

Thank you!

I can add "slotted part" in the list. But with or without  parentheses ?

**Comment by ArkadiuszMichalski** [comment]
Withoiut, I checked it in the last SciTE.

**Comment by ArkadiuszMichalski** [comment]
These old pseudo-elements notation can be expressed with the "Browser-Specific Pseudo-classes" list, assuming you won't expose it anyway for it oryginal purpose:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/lexers/LexCSS.cxx#L562

So use also `List_6`, define these 4 cases in it and use `SCE_CSS_EXTENDED_PSEUDOCLASS 20` with the same style as for pseudoelements. Unfortunately, the style configurator will show `EXTENDED_PSEUDOCLASS`, which can be confusing (because it will cover these 4 cases and not everyone has to know about it), so it probably doesn't make sense.

**Comment by donho** [comment]
> So use also `List_6`, define these 4 cases in it and use `SCE_CSS_EXTENDED_PSEUDOCLASS 20` with the same style as for pseudoelements. Unfortunately, the style configurator will show `EXTENDED_PSEUDOCLASS`, which can be confusing (because it will cover these 4 cases and not everyone has to know about it), so it probably doesn't make sense.

I don't quit follow you.
Please review/comment on https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10501 directly, that will be easier.
