### ISSUE TITLE
backup could include session.xml

### ISSUE THREAD

**Issue by fgnievinski** [notepad-plus-plus/notepad-plus-plus#10444]
hi, thanks for the great notepad++, this is a feature request.

#10402 reports a common case when session.xml gets corrupted.

I just wanted to suggest including session.xml in the backup folder.

that way, it could be manually restored, in case it gets corrupted.

thank you.

**Comment by mtvessel** [comment]
More to the point, it would be great if session.xml was saved every time backups are saved.  If notepad++ doesn't close cleanly (usually a Windows issue), session.xml may not be current.

Thank you!

**Comment by southisup** [comment]
Another use case: I often have multiple files open from network drives that are not always immediately available. If I forget and open NP++ before the drives are connected, I lose most of my previous session, and this often happens when I haven't recently manually saved my session.

**Comment by k-rol** [comment]
Before someone closes this request, I want to emphasize that many people have requested this feature over the years but it always gets refused. Turning off automatic reboot after Windows update is unfortunately not a solution to many use cases.

**Comment by xomx** [comment]
1. Emptying of the session.xml has been fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12388
2. Backup (1) of the session.xml implemented by https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13648 and enhanced by https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14858

This issue can be CLOSED.
