### ISSUE TITLE
the github wiki "Changes" is out of date

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#10516]
https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Changes is missing revisions 8.1.3 and 8.1.4.

Does @ArkadiuszMichalski still have his script for extracting those (as mentioned in the original #9745)?

Is there a way that this could be automated (a new GitHub action triggered by a tag action, for example... maybe using https://github.com/marketplace/actions/publish-to-github-wiki)) -- because forcing @ArkadiuszMichalski to manually run his script every release could get tedious.

**Comment by ArkadiuszMichalski** [comment]
I made this manually (mainly because of the links to issues, which are only listed on [downloads),](https://notepad-plus-plus.org/downloads/) @mere-human has some script but for [other format](https://gist.github.com/vinsworldcom/2e03bc9dc58390841ab0e0b236b3d305). I treat it for historical purposes rather than as an up-to-date list of changes. This can be found at https://notepad-plus-plus.org/, that's why I don't update it immediately after the release of the new version. 

Well, if it can be automated, why not. Just remember that links to issues in old versions were extracted by hand. So when generating a new list, it is best to base it on the current list (so old data will not be lost).

**Comment by pryrt** [comment]
@ArkadiuszMichalski ,

Thanks for your response.  Yes, I agree that just adding the new Change history to the old document is a better idea than re-processing the entire history every time.

I will spend some time this week in a dummy repo and see if I can figure out the GitHub action required to automate it on future tags.

> BTW, keeping everything in one file very often returns this: `The wiki page took too long to render.`

I just saw that today for the first time.  I might play around with the wiki structure (again, first in my dummy repo) to see if it can work better with a hierarchical wiki (so v7.x change history will go on one page, and v8.x on another)...

**Comment by dail8859** [comment]
So this looks like it has been addressed now? Can this be closed?
