### ISSUE TITLE
workspace not sorted in 8.1.4

### ISSUE THREAD

**Issue by broecher** [notepad-plus-plus/notepad-plus-plus#10557]
Using 8.1.4 and sorting in workspace is not working. Its not in any order that I can recognize. 
I'm using npp on windows, the files are on a linux share.

**Comment by broecher** [comment]
![image](https://user-images.githubusercontent.com/1410332/133512379-0a1278c9-fe35-4fb9-aafa-0d55f48ad227.png)

**Comment by easylog-info** [comment]
Hello,
I have sa same problem with npp on windows and file in google folder share

**Comment by easylog-info** [comment]
Hello,
I add an information because i made a manipulation that solved the problem.
If that can be useful to debug ...
At the begining, the list in my Workspace was not sorted in the screen
I have created a new file with the CTRL+N Shortcut
And when I have saved my file, the list in the workspace ordered correctly.
Bye

**Comment by Kipjr** [comment]
I was just fiddling around and found out that choosing "Documents" instead of "General Items" in File Explorer folder properties fixed the sorting from CreationTime to alphabetical (name) in Notepad++

**Before:**
![image](https://user-images.githubusercontent.com/12066560/166414550-d80651da-02e4-4167-a4a6-37a217476055.png)

![image](https://user-images.githubusercontent.com/12066560/166414732-4faca620-bd03-479c-958f-3faa5ed77426.png)

**After:**
![image](https://user-images.githubusercontent.com/12066560/166414602-fde1f0c5-1008-435f-aad5-01a62e4c73aa.png)

**Comment by saturdaywalkers** [comment]
v8.4.6
Have the same issue opening a webdav folder
The windows file explorer workaround doesn't help

Big thanks to the dev team!

**Comment by nl03228** [comment]
![bug](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/6312305/ae05579d-407e-4ed6-b30a-b6559887b96f)

Sorting in Folder as a Workspace seems to be random
Expecting alfabetical - that is why I have choosen number as a prefix

Using version Notepad++ 8.6.7  (64-bit)

**Comment by nl03228** [comment]
@donho Sorry if this is the wrong way to ask, but will this issue ever be fixed?
Or in other words, how do issues get prioritized?

**Comment by xomx** [comment]
@nl03228 
> Sorry if this is the wrong way to ask, but will this issue ever be fixed?
Or in other words, how do issues get prioritized?

This was not for me but allow me to answer that. There are too many open issues, many of them invalid or duplicate or poorly described or not related to this app at all. And capable programmers, willing to devote their free time, are evidently only few... Don't you want to join and help? :-)

---

Anyway, back to this issue.

According to some reports, it looks like this problem might occur in conjunction with the *nix systems only (I myself cannot reproduce this problem on my Windows systems).

And it would be good to include here at least the information obtained through the N++ menu > ? > Debug Info...

**Comment by nl03228** [comment]
Hi, I surely want to help...I even had a look at the code, but I fear my level of programming is not sufficient.
Otherwise I would have gladly assisted !

What do you mean with nix-system?
Wait...Linux I guess. I am working on Windows 2016.
From what I have read, is the issue caused by the NTFS b-tree storage.
And indeed, this issue is not the only issue reported.

**Below** you can find the debug information:
Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "*******" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows Server 2016 Standard (64-bit)
OS Version : 1607
OS Build : 14393.6981
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)

**Comment by xomx** [comment]
Ok, I can replicate the issue (in WSL Ubuntu VM).

This seems to be a common problem in between the *nix (Samba, WebDAV, WSL..) & Win storage, as I found also other apps having such a problem on the net. Anyway, N++ should ensure itself that the initial FAW-treeview will be sorted even under such circumstances, so I am going to fix that.

(Note: There is another issue for that non-Windows storages - the FAW file/dir change-watchdog is not working (at least not for me in my testing WSL), so a manual FAW reset (Remove/Add FAW-root) is needed there.)

**Comment by saturdaywalkers** [comment]
think it depends on the type of filesystem, e.g webDav has it 
but even then a choice of sorting by alpha, last modified, file type would be nice

**Comment by xomx** [comment]
Could the affected users here test the GitHub Actions PR-fix build [binaries](https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/10005349670) & report back the result here?

e.g. for the MSVC x64 Release build - dl, unzip and replace your current "notepad++.exe" file:
https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/10005349670/artifacts/1718353634

---

@saturdaywalkers 
> a choice of sorting by alpha, last modified, file type would be nice

Yes, I already wrote a [note](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/15457#issuecomment-2237389256) about that in my PR, but let me fix the worst part of this problem first with a simple PR. Maybe someone will add some new features like sorting commands to the FAW later.
