### ISSUE TITLE
Feature Request: Command line option to activate monitoring (tail -t) for a file

### ISSUE THREAD

**Issue by FeydCron** [notepad-plus-plus/notepad-plus-plus#10562]
### Feature Request
Introduce a command line option to instantly activate monitoring (tail -t) for a given file, for example notepad++ [-tail] [filePath].

### Expected Behavior
The file is opened with the monitoring (tail -t) option already enabled.

### Actual Behavior
Currently no such command line option is described to be available.

**Comment by elazarcoh** [comment]
I would love to have it also as a windows explorer context menu entry, which I can setup with the installer (though with the CLI option I can create my own context entry).

**Comment by EmeraldFlame** [comment]
Would really love to see a tail parameter added to the CLI as well.

**Comment by Ayaykos** [comment]
I was recently working on this and was able to implement this command line option. I thought it would be clearer to use `-monitor` instead of `-tail` as such:
`notepad++ -monitor filePath`

This also works with multiple files.

Is it okay for this issue to be assigned to me? I can submit the pull request.

**Comment by FeydCron** [comment]
Hi, this is great news. Yes, please assign the issue to you to complete it. I am looking forward to see it in action in one of the next versions ;)
