### ISSUE TITLE
Cannot make LaTeX default language for tex files.

### ISSUE THREAD

**Issue by DeaconLinkhorn** [notepad-plus-plus/notepad-plus-plus#10609]
### Description of the Issue
TeX and LaTeX both have tex as default extensions, seemingly TeX takes priority. Even after moving TeX to disabled items in preferences this behaviour persists. 

### Steps to Reproduce the Issue
1. Open preferences, languages. Move TeX to disabled items. 
2. Open file with .tex extension.
3. Observe that TeX syntax highlighting and styling is still used. 

### Expected Behavior

LaTeX styling should be used, or some method to enforce LaTeX as the default language for tex files should be available. 

### Actual Behavior

TeX styling and syntax highlighting is still used. No option to remove extensions from the default extensions associated to a language.

**Comment by ArkadiuszMichalski** [comment]
>Even after moving TeX to disabled items in preferences this behaviour persists.

Because it does not modify the extension, but only disables the language in the menu. Unfortunately, both languages use the same extension for file and there is a conflict, TeX is first and wins. To change it you have to edit the `langs.xml` file and remove / change the extension for TeX to another.

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/langs.model.xml#L371

**Comment by donho** [comment]
In the next version (v8.7.4) you can defined the extension "tex" in LaTeX (in Style Configurator) for overriding the default behaviour.
