### ISSUE TITLE
command to go to the parent folding point

### ISSUE THREAD

**Issue by VictorelPetrovich** [notepad-plus-plus/notepad-plus-plus#10634]
This is a feature request for a command that will allow very fast traversal of the hierarchical tree of folding points in a file. 
_command_: Move the cursor from current location to the line with the folding point for the fold/block in which the cursor/caret currently resides.

As example, in following code, 
```python
print(9)                  # 1
    # asd a as          # 1.5 
def f(x):                 # 2
    """ doc string;       # 3
          ad;fad , leaf   # 4
         """
    for i in L:               # 5
         print(234)      # 5.5
          # asdf           # 5.8
    print(x-y)           # 6
print(3)                # 7
#  asd fasdf          # 8
```
If currently in:
- 3, 5, or 6 : move to 2; 
- 1, 2 or 7: don't move anywhere
- 5.5, 5.8 : move to 5
- for blanc or comment lines (except doc strings): (probably) move to the first non-blank line above it

**Comment by VictorelPetrovich** [comment]
needs more thinking; maybe I'll come back to it in the future.

**Comment by victorel-petrovich** [comment]
I'd like the same thing, as stated in the title.
@ghost 
> *command*: Move the cursor from current location to the line with the folding point for the fold/block in which the cursor/caret currently resides.

I got the intention, but this particular phrasing will not move, in the examples above, from 5 to 2 , because line with 5 is itself a fold point. 
I think it should be stated as: 

**v2:** Move cursor to the line whose fold point that will hide at folding the line where the cursor currently resides. 

--------------------------

>for blanc or comment lines (except doc strings): (probably) move to the first non-blank line above it

> needs more thinking; maybe I'll come back to it in the future. 

One issue, in Python, is that a last comment line, even if indented correctly, is not part of the first fold block of above it. 
Because of that, 5.8 does not belong to (is not folded into) 5, but to 2, and only because there is non-comment 6 that also belongs to 2. 
Perhaps this is an issue with the lexer itself; I too would expect that 5.8 to be folded into 5, per indentation rules. 

Switch the Language to Nim, for the same code, and you will see 5.8 belonging to 5 indeed, and if you had another comment below 6, at same indent as "print", it will belong to 2. 

However, even Nim lexer does not treat comment the way I think we meant by specifying indentation, so that 1.5 belongs to 1, because it's indented to mean describing 1. Also note that Nim lexer creates fold points even inside the doc-string, just based on indentation level.

So, I think **v2** would be a good start, working just with the fold points defined by the lexer in question.

If it's possible to make exception for comments, or inside comment/doc -string then I would go with:  
**v2.1**: if indented, just to to the first line above, comment or not, that is less indended (more to the left) than the line where the comment is. So that 1.5 goes to 1; if you had another comment below 8, indented , then would go to 8; and 4 goes to 3.

**Comment by victorel-petrovich** [comment]
@donho , are you interested in such a feature, to reopen this issue?
