### ISSUE TITLE
Reload file message if saved on network drive since v8.1.6

### ISSUE THREAD

**Issue by monkyyx** [notepad-plus-plus/notepad-plus-plus#10688]
### Description of the Issue

Since v8.1.6 the reload file message appears after editing & saving a file on a network drive ~~and switching between open files~~.
### Steps to Reproduce the Issue

1. Open a file saved on a network drive
2. Edit and save the file
3. ~~Switch between open files or minimize/maximize Notepad++~~
(sometimes it takes a minute or two before the message appears)

### Expected Behavior

no reload file message
### Actual Behavior

reload file message appears
### Debug Information

Notepad++ v8.1.7   (64-bit)
Build time : Oct 15 2021 - 01:20:46
Path : C:\Users\xxx\Desktop\npp.8.1.7.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.1288
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

![npp](https://user-images.githubusercontent.com/88665772/137716394-8ca6e2b4-a882-449f-8ae4-4c71ab2e92fe.PNG)

**Comment by michelgvandijk** [comment]
I had the same problem in v8.1.9 (64-bit), went back to v8.1.5 (64-bit), haven't had the problem since.

**Comment by rdipardo** [comment]
Looks like a regression caused by 11b2dd0:

> The goal of Release 8.1.6 is fix 2 [long time critical issues] [. . .]. In order to remedy these 2 problems, the __file saving API is changed from POSIX IO functions to Win32 native IO API__

https://notepad-plus-plus.org/news/v816-released (edited)

[long time critical issues]: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6133#issuecomment-929074742

**Comment by donho** [comment]
I have no network drive/samba so I can't reproduce this issue.
However, I find some incoherent code of timestamp detection and did a blend fix:
http://download.notepad-plus-plus.org/repository/MISC/

@monkyyx @michelgvandijk @Docteh @SirHesti @rdipardo 
Could you guys test the fixed binary (download above) and confirm me if it work (and the message you see) please?

**Comment by rdipardo** [comment]
1. Reprocduced in 8.1.9 (32-bit, portable):

<img width="701" alt="repro-2021-11-12 003508" src="https://user-images.githubusercontent.com/59004801/141417254-57e1e887-0ee9-47e0-b2a3-7ee411699b24.png">

SAMBA version: 4.9.5-Debian

2. Patched version seems O.K.(🤞🏼); ran it for ~20 mins. and no more pop-ups

**Comment by monkyyx** [comment]
No reload file message with the new binaries but a new message which can't be closed with OK or X. I have to close NP++ via Task-Manager.

![np++](https://user-images.githubusercontent.com/88665772/141440146-bc8b69ad-5b7c-417f-8ddc-ee564d3b9b48.png)

**Comment by donho** [comment]
@monkyyx @rdipardo 
Could you try the new fix please?
It should be fine now:
http://download.notepad-plus-plus.org/repository/MISC/NewFix/

**Comment by monkyyx** [comment]
Seems to be working fine with the new fix. Tested for about 30 minutes. Thanks!

**Comment by michelgvandijk** [comment]
Tested the x64 version of this fix, haven't had the problem since.

**Comment by donho** [comment]
@monkyyx @rdipardo @Docteh @michelgvandijk 

The fix of this issue has caused another regression, so the fix has [been revert](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bab3573be708bb908b8080e3e2007ea78a7f1932). In order to avoid this issue happening again in the next release, could you guys help us to identify the real problem, by using the following binary: [Notepad++ x86](https://ci.appveyor.com/api/buildjobs/l55mssnvg431a717/artifacts/Notepad%2B%2B.Win32.Release.exe) or [Notepad++ x64](https://ci.appveyor.com/api/buildjobs/50e43knu62r917mq/artifacts/Notepad%2B%2B.x64.Release.exe).

The binary contains the writing log ability in case of problem. To activate log, you should:

1.    Add an empty "nppLogNetworkDriveIssue.xml" file beside of notepad++.exe, or if you have no admin privilege, you can add this file into `%APPDATA%\Notepad++\`.
2.    Create `C:\temp\` directory, if it doesn't exist yet.
3.    Start notepad++.exe, and wait for the false alert happens from the network drive. If the errors occur, there should be some trace in "C:\temp\nppLogNetworkDriveIssue.log". Please provide nppLogNetworkDriveIssue.log to us.

With the information you provide, there might be better chance to fix it finally.
Thank you in advance!

**Comment by rdipardo** [comment]
Here's what mine said: [nppLogNetworkDriveIssue.log](https://github.com/notepad-plus-plus/notepad-plus-plus/files/7616811/nppLogNetworkDriveIssue.log); the last entry shows what's happening in the GIF below.

Some steps for others to try:

1. Open a network file

2. Remove some bytes __*from the end of the document*__ (e.g. cut the last line).
    Editing the start or middle did not raise an error; neither did _adding bytes_ to the end.

---
   BTW, this is exactly what @pjcs00 reported at https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10787#issuecomment-972744009:

> - the error seems to happen when the file is re-saved and the new version
> is shorter than the old one - even by 1 character
> - the error does not occur if the new version being saved is longer than
> the old one

And: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10787#issuecomment-972973831:

>  I have gone back to 8.1.9 and [. . .] it does display the error if I reduce the file size.
---

3. Save the file

4. In ~10 sec, you're prompted to reload:

![npp_ v8 1 9 2_timestamp_no_sync](https://user-images.githubusercontent.com/59004801/143836590-e76d1f92-c6b1-4a5a-9d17-9682bcc592df.gif)

5. Log file will say `attributes.ftLastWriteTime` is earlier than `_timeStamp`

---
File server host: Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
Samba version: 4.9.5-Debian

Notepad++ v8.1.9.2   (32-bit)
Build time : Nov 28 2021 - 02:40:52
Path : C:\Users\Public\Downloads\dev\Notepad++.Win32.Release.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 2009
OS Build : 19042.1348
Current ANSI codepage : 1252
Plugins : none

**Comment by michelgvandijk** [comment]
I had three files open, all three opened from a share, edited something in the first and saved, then went to the third tab/file, edited something and saved, went back to the first, got the message, went to the third, got the message. Here's the log:
```
2021-11-29 15:43:13  \\nas\1.txt  in checkFileState(): attributes.ftLastWriteTime (1429702173/30926127) < _timeStamp (1429704484/30926127)
2021-11-29 15:48:39  \\nas\3.txt  in checkFileState(): attributes.ftLastWriteTime (1788163575/30926127) < _timeStamp (1788167400/30926127)
```

**Comment by donho** [comment]
@monkyyx @rdipardo @Docteh @michelgvandijk

Thank you for your tests.
Could you please test these both binaries with new fix: [x86](https://ci.appveyor.com/api/buildjobs/lvqrv5ubw3dptmty/artifacts/Notepad%2B%2B.Win32.Release.exe) and [x64](https://ci.appveyor.com/api/buildjobs/r6pwcniyn0i6tfcm/artifacts/Notepad%2B%2B.x64.Release.exe)

**Comment by rdipardo** [comment]
No more log messages running latest release (32- and 64-bit)

**Comment by Docteh** [comment]
Hi, I gave the latest build a go and since I wasn't getting the error consistently I ran the build for 30mins just doing some minor tweaks. No message, and nothing in the log. I was about to look more closely at this thread and ask if I was supposed to get information or success.

I only tried 32bit, but a-ok for me.

**Comment by michelgvandijk** [comment]
Using 64 bit, no problems so far.
