### ISSUE TITLE
Preferences dialog has no borders resulting in white-dialog-on-white-paper usability issue

### ISSUE THREAD

**Issue by TomaszSzt** [notepad-plus-plus/notepad-plus-plus#10692]
### Description of the Issue
The preferences dialog has no borders around it. As a result I can see a white area on white document what makes rather hard to figure out which part of what I can see do belong to a dialog and what belongs to other windows. Really guys, I spent some time on figuring out that "Close" belonged to a dialog, not a main window behind it.

![notepad++bug](https://user-images.githubusercontent.com/87855864/137915270-cc95ea11-9c05-4ad2-afd9-38ea0e5ad6b5.png)

### Steps to Reproduce the Issue

1.Start Notepad++, make it large
2.Open Settings->Preferences
3.Play moving it around over other application. Depending on Your system settings You may have a great difficulty to figure out which elements on screen do belong to that window or not.

### Expected Behavior

Border should be visible clearly telling where the window ends.

### Actual Behavior

No border visible, hard to figure out where the window ends if the window behind it is also white.

### Debug Information

Notepad++ v7.8.8   (32-bit)
Build time : Jun 24 2020 - 00:15:36
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1288
Current ANSI codepage : 1250
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

## Additional information
I did disable all fancy Windows shadows, animations and etc. due to usability issues they do present. 

I also did observe, that this problem relates in my system only to Notepad++ and to "Preferences", "Style configurator", "Debug info" (which is gray-on-gray case) but not to "Shortcut mapper" nor "About Notepad (F1)".

The issue is also present in some windows in GIMP which has "gray-on-gray" problem, so this is most probably the Windows issue. Since this issue is well known and happily ignored I would like You to know, that it may create some serious usability issues in Notepad++.

**Comment by Docteh** [comment]
Hello, two thoughts here.
1. That version is fairly old, ideal to test with current stable release (auto-updater should be handing out 8.1.5, but 8.1.7 is available today)
2. I think that the steps to reproduce might need some suggestions on what options to disable in Windows, and since we're in the Windows 10/11 era, where to  find those options might be important.
![image](https://user-images.githubusercontent.com/190571/137995012-7cb74738-fbcc-4316-99f7-b723cd9443ff.png)
![image](https://user-images.githubusercontent.com/190571/137995467-1e47cb06-5198-4d79-9792-1cf3fc91eaf5.png)
I should have set my desktop background to white before taking some of these, but this notepad has a 1 pixel wide blue border around the window
![image](https://user-images.githubusercontent.com/190571/137995767-3b1d781c-33c8-44a2-9cd8-74dae76dffe0.png)

I'm including the notepad screen capture as I'm assuming that the correct option will cause `notepad.exe` to have a more conventional window border.
