### ISSUE TITLE
MATLAB Codes need more Parsing

### ISSUE THREAD

**Issue by JAMESY9868** [notepad-plus-plus/notepad-plus-plus#1076]
1. Please add the functionality for Function List for MATLAB;
2. Please treat the "end" for indices and syntactical "end" differently if possible...

**Comment by JAMESY9868** [comment]
The keyword system in MATLAB is not well-functioning.
When having multi-line commenting such as %{ and %},
it displays the function block (the vertical line usually shown when a function is detected) in a weird way.
Please try it if possible. What I did was:

%{
    AdoptedMethod
%}

%% Adopted methods
% Simple ones:

**Comment by JAMESY9868** [comment]
Also, please note that we might need a special displaying for this:

    %% This is a Section Divider

Originally in MATLAB, **Bolded Text** and a Division Line above the line is displayed.
In NPP, as far as I know, making texts bold is possible so please do that.

If you want to do it, here is the Regular Expression to searching for the Bolded Part (if you need this):

    (?=^|\n)(?: *)%% .*(?>=\n|$)

Some explanation of this:
You cannot have any non-blank characters from beginning of line until the double percentage,
  otherwise it is a regular comment;
You need to have at least one blank character, otherwise it is a regular comment as well.
This whole line, excluding the \n, and the beginning/end_of_file, is all the Section Divider.

Thanks

**Comment by MAPJe71** [comment]
@JAMESY9868 

I hope it's not to late ...
1. Please supply (link to) grammar (BNF, EBNF);
2. In what way should the "end"s be treated differently?
3. Is a section divider some kind of indicator for a group of functions?

Thanks

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
