### ISSUE TITLE
Macro problem with "Go To Matching Brace"

### ISSUE THREAD

**Issue by etienne-boireau** [notepad-plus-plus/notepad-plus-plus#1081]
"Go To Matching Brace" is not working fine inside a macro: it is either not moving the cursor, or jumping to a wrong brace.

Example:
1/ Record a macro containing only the command "Go To Matching Brace":
    - "Macro / Start Recording"
    - "Search / Go To Matching Brace"
    - "Macro / Stop Recording"
2/ Play it back:
    - Position the cursor on a curly brace or on a parenthesis, in a C or C++ source code
    - "Macro / Playback"
    => the cursor is not moving, or is jumping to the wrong brace.

Seen with:
    - Windows 7 and Notepad++ v6.8.6
    - Windows Vista and Notepad++ v6.7.8.2
    - Problem still seen after removing all plugins (with "plugins" folder renamed)

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by Faq** [comment]
@MetaChuh you didnt close it.

**Comment by MetaChuh** [comment]
ooops, thanks @Faq 
sorry
