### ISSUE TITLE
Notepad++ does not save file extension when period in file name

### ISSUE THREAD

**Issue by KyleCrawford** [notepad-plus-plus/notepad-plus-plus#10824]
### Description of the Issue
When saving a file, if you include a '.' in the file name it will not automatically add the file extension at the end
eg.
Trying to save file named "9. Test" (without the quotes), selecting 'normal text file (*.txt)' as the type
![image](https://user-images.githubusercontent.com/14237962/143119365-275a2158-0620-4d32-bd74-43cff2126694.png)

The file extension will not get added to the file name unless specifically added.
![image](https://user-images.githubusercontent.com/14237962/143121318-044bbb80-4db7-4aaf-8b3f-4f54aa148c55.png)

### Steps to Reproduce the Issue
1.  Create new file, attempt to save it with a period in the name

### Expected Behavior
For the file extension to be added. Same as if there was no '.' in the name.

### Actual Behavior
No file extension is appended.

### Debug Information
Notepad++ v8.1.9.2   (32-bit)
Build time : Nov 21 2021 - 04:27:12
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1348
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by 80ROkWOC4j** [comment]
There should be logic to check the file title before append extension.

**Comment by donho** [comment]
I would say it's a tolerable limitation.
@Yaron10 & @mere-human what do you think about this issue?

**Comment by mere-human** [comment]
> I would say it's a tolerable limitation. @Yaron10 & @mere-human what do you think about this issue?

@donho It is completely expected behavior.
Notepad++ thinks that anything that comes after `.` is a file extension.
There's no reliable way to differentiate a file extension from "just a suffix separated by a dot".
If you choose to use dots in the file name, then you should append the extension manually.
I'd suggest closing it.

**Comment by donho** [comment]
Thank you @mere-human for your opinion.
Yes, as I said, the extension not being appended in case of dot being part of file name is a tolerable limitation.
Trying to manage such situation will make code complex, and I even wondering if there is a solution.

**Comment by KyleCrawford** [comment]
"Thank you @mere-human <https://github.com/mere-human> for your opinion.
Yes, as I said, the extension not being appended in case of dot being part
of file name is a tolerable limitation.
Trying to manage such situation will make code complex, and I even
wondering if there is a solution.""

You're kidding me right? You know every other program has logic where this
works.
Whatever. Can't expect much from you guys I guess.

**Comment by karlisi** [comment]
If taking everything after first dot as extension is expected behavior, what purpose then serves checkbox 'Append extension' in such case? Expected behavior is if extension is added regarding of dots in filename. If someone wants to add custom extension, he can remove this checkbox to not add default extension.
