### ISSUE TITLE
No option for a black canvas in dark mode?

### ISSUE THREAD

**Issue by jwdonahue** [notepad-plus-plus/notepad-plus-plus#10849]
### Description of the Issue
Some parts of the app are actually black in dark mode, but not the canvas where I would be focusing most of my time.  It's really annoying having grey text on a grey background. When I think of "dark mode", grey canvas doesn't come to mind.  I'd call that soot or something other than dark.

Like so many pseudo dark mode apps I've encountered in the past, this will have been uninstalled before the bits were dried on my SSD. 

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by CennoxX** [comment]
You can change the appearance of the canvas at Settings > Style Configurator and select another theme.

**Comment by ArkadiuszMichalski** [comment]
As above, use theme.

**Comment by jwdonahue** [comment]
Tried it. Didn't work.  Darkest theme I could find had pitch black chrome and current line highlight, but the canvas was a dark grey, not black.

**Comment by CennoxX** [comment]
@jwdonahue Could you explain, what you mean with canvas?

**Comment by mere-human** [comment]
Try Deep Black theme 
![image](https://user-images.githubusercontent.com/9664141/144668187-967bd514-370d-48da-88aa-63ae2813bd68.png)

**Comment by jwdonahue** [comment]
@CennoxX the canvas is the background that you write on.

Here's what your dark mode looks like on my system. See how the main edit window is no where near as dark as some of the window chrome?  It's gray with grey foreground text. I expect dark mode to be black with white text. 

@mere-human The deep black is much better, thank you.  That should be the default for dark for mode. All I had to do was kill that annoying current line highlighter.  The selected text highlighter is too milky, it washes out the text. 

Now if I could just set the frame and menu to black background I'd really be elated. 

![Notepad++InDarkMode](https://user-images.githubusercontent.com/9858984/144685538-62db17a2-e075-4369-83fb-2c162e32ff43.png)

**Comment by CennoxX** [comment]
Okay, I was confused what you meant with canvas, because you wrote there would be no themes with black canvas. There are multiple themes with black or nearly black canvas: Black Board, Deep Black, Plastic Code Wrap, Twilight, Vibrant Inc. Also, you could set the background color style to black and enable global foreground color.

>  That should be the default for dark for mode. 

I also think the default theme should be darker, but not black. A dark theme uses dark grey, rather than black. But the default background color isn't the subject of this issue.


Issue should be closed as there are multiple options for a black canvas.

**Comment by jwdonahue** [comment]
Closing, thank you.
