### ISSUE TITLE
Printing wirelessly on 3830 printer not working (works with Wordpad)

### ISSUE THREAD

**Issue by ADVENTAvenger** [notepad-plus-plus/notepad-plus-plus#10854]
### Description of the Issue
Printing with Notepad++ on a DeskJet 3830 by Wireless 2.4GHz prints out white blank pages. Printing the same document over the same driver with Wordpad works.

### Steps to Reproduce the Issue
1. Open Notepad++
2. Print a raw text document over wireless to a 3830 printer (my document contains IP addresses and MAC addresses)
3. Enjoy the white sheet

### Expected Behavior
The page should print out the characters sent to the printer.

### Actual Behavior
The page was blank coming out. No error messages on Windows or the printer.

### Debug Information
Notepad++ v8.1.9.2   (32-bit)
Build time : Nov 21 2021 - 04:27:12
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1348
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by dail8859** [comment]
Have you tried printing the same document to a different printer?

**Comment by ADVENTAvenger** [comment]
I do not have a second printer so no unfortunately

**Comment by SinghRajenM** [comment]
What if send this to file port instead of actual print port? Does generate `prn` file has some data in it? If possible, can you share the `prn` file?

To enable file prot, you need to follow below steps - 
1. go to `Control Panel\All Control Panel Items\Devices and Printers`
2. Right click on your printer and select `Printer properties"
3. Select "port" and then `FILE:` port and apply.
4. Once you fire a print job, it will ask for save the prn file. Choose the location to save the file.
5. Revert step 3 to redirect your print jobs to printer again.

**Comment by ADVENTAvenger** [comment]
Fixed in new patch for Windows  19044.1499 (21H2) (KB5009596)


   - We fixed an issue that stops printing or prints the wrong output when
   you print using USB on Windows 10, version 2004 or later.
