### ISSUE TITLE
Sort by Column/Character 

### ISSUE THREAD

**Issue by BQFord** [notepad-plus-plus/notepad-plus-plus#1086]
Hello Notepad++ developers

I learned of your software about a year ago and have enjoyed using it.  Before this I used TextPad for my text editing and searching.  It appears you have most of the features in Notepad++ as they have in TextPad, like block select, file comparison, and Find/Search in files.  The one feature I use a lot is to sort data by columns of data instead of rows.  In TextPad you can sort by three different data columns.

![image](https://cloud.githubusercontent.com/assets/15623156/10900472/db1e3af4-81a5-11e5-94b0-bc55b9e5c052.png)

The “key” numbers are the character/columns in the text document.

Do you have this feature in the Notepad++ and I can’t find it?
If not would you please consider adding this feature to your already very good software?

Thanks

**Comment by jonandr** [comment]
This is partially available in Notepad++. See the available options in the "Edit -> Line operations -> Sort..." menu.

If you want to sort by column you will have select the column by holding down the Alt key and doing a selection with the mouse. (This means that you can only sort by one key.)

**Comment by BQFord** [comment]
Has there been any more thought to this feature request?

Also when I first requested this last year you said I could “kind of” do what I requested.  What do the Sort Lines option mean?

[cid:image001.png@01D16438.CC168870]

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
