### ISSUE TITLE
Differerence in selected text

### ISSUE THREAD

**Issue by rwblues** [notepad-plus-plus/notepad-plus-plus#10899]
### Description of the Issue

Text selected with ctrl-A shows a space at the end of each line.
When selecting some line with the mouse, pressing the left button,  this space is not seen.

### Steps to Reproduce the Issue

1.  selected all text with ctrl-A
2.  select text line with mouse, giving enough room at the end. That is when you start selecting at the end.
3.  select text line with mouse, starting at the beginning of the line.

### Expected Behavior

All existing spaces should be seen

### Actual Behavior
There is a difference in display. Selecting with the mouse does not show all spaces.

### Debug Information
Notepad++ v8.1.9.1   (64-bit)
Build time : Nov 13 2021 - 15:28:20
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "x:\xxx\worldcities.csv"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 8.1 Pro (64-bit) 
OS Build : 9600.19505
Current ANSI codepage : 1252
Plugins : AutoSave.dll NppExport.dll 

Textsample:
"city","city_ascii","lat","lng","country","iso2","iso3","admin_name","capital","population","id"
"Malishevë","Malisheve","42.4822","20.7458","Kosovo","XK","XKS","Malishevë","admin","","1901597212"
"Prizren","Prizren","42.2139","20.7397","Kosovo","XK","XKS","Prizren","admin","","1901360309"
"Zubin Potok","Zubin Potok","42.9144","20.6897","Kosovo","XK","XKS","Zubin Potok","admin","","1901608808"
"Kamenicë","Kamenice","42.5781","21.5803","Kosovo","XK","XKS","Kamenicë","admin","","1901851592"

**Comment by vortaj** [comment]
I would argue with the expected behavior. If the sample you are provided is correct, there are no actual spaces at the lines' ends. If anything, the expected behavior should be the opposite, i.e. no spaces. If you try this in your browser, you will probably see the same behavior, unless you use Firefox.

![selection](https://user-images.githubusercontent.com/95566457/145407921-10d21865-1001-46e5-9edf-8391c965d388.png)

**Comment by rwblues** [comment]
I accept your argument that theire are no spaces, I tested it in two editors, but in this case N++ displays something wrong and this in a nonecoherent way. The whole issue should be testet in N++ only.
Thanks

**Comment by dail8859** [comment]
Ultimately this behavior is determined by the 3rd party library [Scintilla](https://scintilla.org/) (which is the core of Notepad++) so that project would need to make the changes. Scintilla is a very widely used text editing component and this is the first I've heard about this type of 'issue'. I would assume this long standing behavior is expected.

**Comment by dail8859** [comment]
https://sourceforge.net/p/scintilla/bugs/2301/

**Comment by dail8859** [comment]
@rwblues Closing this issue as the referenced Scintilla issue has been closed. If the Scintilla issue is opened back up feel free to post on this issue and it will be reopened.
