### ISSUE TITLE
About column mode.

### ISSUE THREAD

**Issue by Teeis** [notepad-plus-plus/notepad-plus-plus#10904]
### Description of the Issue

About column code.If I copy 1-21 from excel and hold ALT on the Notepad + + page, I can't get the result I want

### Steps to Reproduce the Issue

1. Open excel, Ctrl + C a column of numbers
2. Open Notepad + +, press and hold alt, press and hold the left mouse button to pull down a column, and then Ctrl + V
3. You'll see me in the video

### Expected Behavior

I want to copy only one column that does not duplicate
### Actual Behavior

It does copy only one column, but it is repeated many times
### Debug Information

Copy debug info into clipboard
Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\yan\OneDrive\文档\重要.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 22000.348
Current ANSI codepage : 936
Plugins : 3P.dll AutoSave.dll ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppQrCode64.dll urlPlugin.dll 

I may not be accurate. I recorded a video here：https://streamja.com/qalw2
I hope it can be solved as soon as possible. Best wishes！

**Comment by dail8859** [comment]
When you copy the column from excel you are technically copying several lines of text. So if you want to paste them into Notepad++ you just click once in the file (don't press and hold alt).

I see you are using virtual whitespace too. I doubt that is going to work correctly. There are going to be limitations since Excel is so much different than Notepad++ in terms of how it stores data.

The reason you are seeing so many lines pasted is because when you press alt and drag you are technically creating several cursors. Then when you paste you are pasting 20 lines of text at each cursor.
