### ISSUE TITLE
Comment after & in Batch

### ISSUE THREAD

**Issue by Zaidy036** [notepad-plus-plus/notepad-plus-plus#10908]
When a comment is used as the second command in Batch it does not get the comment style applied.

Example where comment style is Bold and Italics:
:: **_Increment_**
Set /P xxx=%xxx%+1 & :: Increment

**Comment by dail8859** [comment]
https://sourceforge.net/p/scintilla/bugs/2304/

**Comment by mpheath** [comment]
Neil Hodgson commited the patch that I submitted to fix this issue at Lexilla.

https://github.com/ScintillaOrg/lexilla/commit/aead36c4cc4bd5b451b3283dbac9bcce0ae21b28

Since NPP is using an older version 4.4.6 of Scintilla + Lexilla, I did a compile of NPP with GCC with the patch supplied.

```diff
--- a/LexBatch.cxx
+++ b/LexBatch.cxx
@@ -197,9 +197,12 @@
 				wbo = 0;
 
 				// Check for Comment - return if found
-				if ((CompareCaseInsensitive(wordBuffer, "rem") == 0) && continueProcessing) {
-					styler.ColourTo(endPos, SCE_BAT_COMMENT);
-					break;
+				if (continueProcessing) {
+					if ((CompareCaseInsensitive(wordBuffer, "rem") == 0) || (wordBuffer[0] == ':' && wordBuffer[1] == ':')) {
+						styler.ColourTo(startLine + offset - strlen(wordBuffer) - 1, SCE_BAT_DEFAULT);
+						styler.ColourTo(endPos, SCE_BAT_COMMENT);
+						break;
+					}
 				}
 				// Check for Separator
 				if (IsBSeparator(wordBuffer[0])) {

```

and this is the result themed as Deep Black:

![npp,png](http://users.tpg.com.au/mpheath/lexilla/npp.png)

It may work fine until NPP fully updates Scintilla + Lexilla. That is your choice for what best suits NPP.

Not sure if the testlexer.exe test files are compatable between the versions. Version 4.4.6 test passes with the x.bat from the NPP repo. Tested with CRLF and with another copy with LF EOLs.

**Comment by dail8859** [comment]
@mpheath It is pretty rare Notepad++ will cherry pick commits for syntax highlighting fixes. From #10504 it sounds like work is being done to update to a newer version of Scintilla/Lexilla in an upcoming Notepad++ release.

**Comment by ArkadiuszMichalski** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a61b03ea8887e21c6e1b7374068962f635b79b80.
