### ISSUE TITLE
Save-All confirmation not needed when only one modified document

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#10995]
### Description of the Issue
If I have only one modified document, if I press Save All, I get a confirmation popup to confirm saving of all files.  As there really is nothing to confirm here, the popup shouldn't appear.

### Steps to Reproduce the Issue

1. Close all documents if any
2. Create some new docs, `new 1`, `new 2`, `new 3`
3. Add some data to only document `new 2` (it now has red disk icon, the other tabs have blue)
4. Press Save All button on toolbar

### Expected Behavior
To not see the save-all-modified-documents confirmation popup and to just see the _Save As_ box:

![image](https://user-images.githubusercontent.com/77065706/148103289-426ee29a-2dcc-4f50-88e4-ca85b69835ad.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/77065706/148103129-1888c549-6a40-4ece-8d98-08bcc00dd1b5.png)

### Debug Information
Notepad++ v8.2   (64-bit)
Build time : Dec 30 2021 - 03:40:42
Path : C:\.......\npp.8.2\npp.8.2.portable.x64\notepad++.exe
Command Line : -titleAdd="8.2 64-bit" -multiInst 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1348
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
Already implemented (Not reproducible in v8.4.2)

**Comment by alankilborn** [comment]
@donho said:

> Already implemented (Not reproducible in v8.4.2)

Not implemented.
Easy to reproduce following STR, on 8.4.2.

**Comment by alankilborn** [comment]
I always test and write STR based upon a freshly extracted portable of the specified version; I suppose I need to state that as step 1 of my STR?

**Comment by donho** [comment]
@alankilborn 
The behaviour of implement of this issue is:
1. If there's only one file dirty, and it's current edit one, then SaveAll dialog won't display.
2. If there's only one file dirty, and it's NOT current edit one, then SaveAll dialog WILL display.
3. If there's 1 editing file which is dirty, and its clone (dirty also) is on the other view, then SaveAll dialog WILL display.

**Comment by alankilborn** [comment]
I really think it should be "if there's only one file dirty and SaveAll is invoked, SaveAllConfirmDialog won't display" with no other conditions, but I suppose your case 1 covers the main thrust of this issue.
Your case 3 really makes no sense -- it should be treated as case 1 -- but as it is a rare condition (at least for me), it is not that important.
Thanks for the work on this issue.

**Comment by MarkusBodensee** [comment]
@alankilborn
Looks like the only reason why your point: case 3 should be treated as case 1, isn't implemented is: the current implementation is easy, and doing more effort for this complicates things and isn't worth it, because case 3 is rare :-D Apart from this reason, I think, everybody agrees with you. :-D
