### ISSUE TITLE
Find in file broken

### ISSUE THREAD

**Issue by PlumHunter** [notepad-plus-plus/notepad-plus-plus#11019]
### Description of the Issue
I go to search for word using the search function  (ctrl-f) and it fails. Does not find word I know is in document

### Steps to Reproduce the Issue

1. hit ctrl-f
2. enter word to find
3. is not found!
3.

**Comment by alankilborn** [comment]
It is going to depend upon other settings on the _Find_ window.  What are yours?  Show a screenshot like this:

![image](https://user-images.githubusercontent.com/77065706/148787953-59ae375f-1040-4d2a-a852-bdfa3733cafb.png)

Actually, just retest using the settings from my screenshot, but put your word in the _Find what_ box instead of the `myword` I show.

**Comment by donho** [comment]
@PlumHunter 
Please provide complete info for any bug report.
This issue is rejected due to its poor content.
