### ISSUE TITLE
[Feature request] Open in new instance

### ISSUE THREAD

**Issue by kennui** [notepad-plus-plus/notepad-plus-plus#11039]
As title, I would like the option to open a new blank document in a new instance (new window as I have set it up). I personally do not like the file-tab system so it's hidden and files are opened in new instances/windows.

However, if you have a file already open, opening a document (CTRL N) will create a tab, meaning the previous file is hidden since the tab bar is disabled.

Alternatively, an option to disable all file-tab behaviours (this would also have to auto-enable multi-instance mode). I use notepad++ as the default text editor and as a replacement for windows notepad, which DOES have 'open in new window' as an option.

**Comment by Ekopalypse** [comment]
From your explanation I get that setting the multi instance mode in settings
and remapping the ctrl+n with a Run entry `notepad++.exe` will do what you want.

![image](https://user-images.githubusercontent.com/47723516/149300919-6f8df872-135a-4661-b337-f6b01701e360.png)

**Comment by Ekopalypse** [comment]
No, you simply run the method Run... from the Run menu and type `notepad++.exe` or the more fancy `$(NPP_FULL_FILE_PATH)` as shown by @alankilborn and save it under a meaningful name. I chose the name `New instance`. That's it,

**Comment by alankilborn** [comment]
>I chose the name New instance

...and after saving it with that name you went into ShortcutMapper and mapped it to Ctrl+n

**Comment by kennui** [comment]
Didn't realise you could save that and remap it. Would still be good to see it as a default option under 'New' just like in windows notepad.

**Comment by alankilborn** [comment]
>Would still be good to see it as a default option under 'New' just like in windows notepad.

Probably not a lot of N++ users do your way of working.  Multiple instances have drawbacks.

**Comment by ArkadiuszMichalski** [comment]
>Didn't realise you could save that and remap it. Would still be good to see it as a default option under 'New' just like in windows notepad.

Windows Notepad it's by nature a multi-instance, which is why it works like that. In Notepad ++ you have tab support and the default Ctrl+N is for tabs, not new windows. You can add your own macro and set a shortcut. See how it looks like in the default `Open selected file path in new instance` in `shortcuts.xml` file:
```
<Command name = "Open selected file path in new instance" Ctrl = "no" Alt = "yes" Shift = "no" Key = "117"> $ (NPP_FULL_FILE_PATH) $ (CURRENT_WORD) -nosession -multiInst </Command>
```

Remember that you can also use Notepad++ command line arguments.

https://npp-user-manual.org/docs/config-files/#userdefinedcommands
https://npp-user-manual.org/docs/command-prompt/

This can be achieved with available mechanisms, so I close it. @Don, if you plan to add such a command, then please reopen.
