### ISSUE TITLE
Wrapping long indented lines NPP 6.8.6

### ISSUE THREAD

**Issue by mchels** [notepad-plus-plus/notepad-plus-plus#1107]
When wrapping a long indented line a newline is inserted between the indentation (whether spaces or tabs) and the long word:
![wrap_behavior](https://cloud.githubusercontent.com/assets/7964436/11015907/669e39c6-8570-11e5-88ef-9bb53d1b49c8.PNG)
Expected behavior is to put indentation whitespace and first part of the word on the same line:
![wrap_expected_behavior](https://cloud.githubusercontent.com/assets/7964436/11015909/85a8ef1e-8570-11e5-9e6e-d6b9a7fbf5e3.PNG)

This issue applies to all Line Wrap settings (Default, Aligned, Indent). It's tested on a portable install of NPP 6.8.6 with default settings and only default plugins.

**Comment by leewz** [comment]
I'm pretty sure this behavior wasn't always there, because it's bugging me a lot. I paste URLs into my documents and they LOOK like they're on new lines.

The long word doesn't have to be the only thing on the line. If a line has indentation, the first long word on it is just wrapped to the next line, even if it don't fit on that line, either. It's just uglier if there's nothing else on the line.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
