### ISSUE TITLE
Find in Files Filters don't support both file and ! folders

### ISSUE THREAD

**Issue by Skrell** [notepad-plus-plus/notepad-plus-plus#11086]
### Steps to Reproduce the Issue

Search through a directory with inclusive, specific filetype filters but exclude ANY folder.  So in other words: 
`*.cpp;*.h;!+\FOLDERNAME*;`

### Expected Behavior
All cpp and h files would be searched in ALL folders recursively EXCEPT the ones with FOLDERNAME in the path.  

### Actual Behavior
FOLDERNAME is still searched 

### Debug Information
Notepad++ v8.2

**Comment by alankilborn** [comment]
Missing "Actual Behavior"

**Comment by dfs-** [comment]
Could reproduce the issue as described by @Skrell. Using space as the separator does however not exhibit the problem.

`*.cpp;*.h;!+\FOLDERNAME*;` will search all subfolders named foldername*, whereas
`*.cpp *.h !+\FOLDERNAME* ` will not.

Notepad++ used to support both ways of writing, so this could be regarded as a bug.

**Comment by dfs-** [comment]
Very basic fix would be adding a ` || *pEnd == ';'`to the if in `cutString()` @ notepad-plus-plus\PowerEditor\src\Parameters.cpp

`void cutString(const TCHAR* str2cut, vector<generic_string>& patternVect)
{
	if (str2cut == nullptr) return;

	const TCHAR *pBegin = str2cut;
	const TCHAR *pEnd = pBegin;

	while (*pEnd != '\0')
	{
		if (_istspace(*pEnd) || *pEnd == ';')
		{
			if (pBegin != pEnd)
				patternVect.emplace_back(pBegin, pEnd);
			pBegin = pEnd + 1;
		
		}
		++pEnd;
	}

	if (pBegin != pEnd)
		patternVect.emplace_back(pBegin, pEnd);
}`

**Comment by ArkadiuszMichalski** [comment]
Separator on filters list is space:
https://npp-user-manual.org/docs/searching/#find-in-files-tab
>The Filters list is a space-separated list of wildcard expressions that cmd.exe can understand, like *.doc foo.*.

Also when you move cursor over `Filters` label you get tooltip with some examples:
![image](https://user-images.githubusercontent.com/2730894/151681814-7a62195c-872a-42b8-8b61-48fe8b45cfaa.png)

**Comment by dfs-** [comment]
@ArkadiuszMichalski That’s correct, but then why did it work using semicolon as separator and still does? Is there some built-in Windows function, that does support it but will obviously fail with the exclude directory syntax?

**Comment by Skrell** [comment]
Also, what do you then do if the directory name has a space in it like so many window's paths do?

**Comment by dfs-** [comment]
When you directory has a space you could use either `!+\Folder?Name` or `!+\Folder*Name`

**Comment by ArkadiuszMichalski** [comment]
@pryrt Maybe add some info to manual about handling space in folders filter? When implementation of folder filters, [there were no plans](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10927#issuecomment-998839029) to do it any other way than the above methods.

**Comment by pryrt** [comment]
According to [Microsoft docs](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#naming-conventions), the semicolon is a valid character inside file names and folder names (it allows any character from the current codepage except that small list, and that small list doesn't show semicolon, so it is officially accepted).

I then confirmed that I can create a file in windows called `semi;colon.txt`.  If I put an `x` in that file, and do a Find in Files with the filter = `semi?colon.txt`, where `?` is the wildcard, it works just fine; but if I filter for `semi;colon.txt`, it will _not_ find the `x` in that file, even though I know it's there.

So, @ArkadiuszMichalski and @donho: is splitting on semicolon `;` a bug, and should be eliminated from the Filters behavior (so that in the future, `;` is treated like Windows explains it, as a potential path character)?  Or should the manual include an explanation that `;` will not work as a literal character in the Filters box, and that like a space, you need to use a `?` or `*` wildcard to match a semicolon?

**Comment by donho** [comment]
> is splitting on semicolon ; a bug, and should be eliminated from the Filters behavior (so that in the future, ; is treated like Windows explains it, as a potential path character)?

No. The filter uses always only the white space ` ` as separator.

> Or should the manual include an explanation that ; will not work as a literal character in the Filters box, and that like a space, you need to use a ? or * wildcard to match a semicolon?

Yes, rather in this way.

**Comment by donho** [comment]
Use rather "*.cpp *.h !+\FOLDERNAME*" as filter - it should work.
