### ISSUE TITLE
Notepad++ should stop using political slogans in its release names

### ISSUE THREAD

**Issue by iDm1** [notepad-plus-plus/notepad-plus-plus#11153]
### Description of the Issue
Notepad++ 8.3 release has "(Boycott Beijing 2022)" text in the title on download page.

### Steps to Reproduce the Issue
1. Open https://notepad-plus-plus.org/downloads/v8.3/

### Expected Behavior
Title should be "Notepad++ 8.3"

### Actual Behavior
Current title is "Notepad++ 8.3 (Boycott Beijing 2022)"

Notepad++ is an advanced text editor focused primarily on editing code and configuration files. But for some unknown reason it uses   political slogans in its title on download page. This decision looks plainly stupid, because the world is not made up of black and white colors, every situation is much more complicated. 

This hurts Notepad++ and makes it a weapon against some group of people instead of being a useful tool to help everyone. It's not an open source way. Notepad++ is not an open source software, today it's just a tool in hands of positions. It's time to be smart and stop being someones attack dog.

**Comment by lanzhiquan** [comment]
Unfortunately, npp author is a political dog.

**Comment by jiuanchangzhi** [comment]
We must Boycott Notepad Plus Plus.

**Comment by Wang-Yumin** [comment]
Boycott Notepad Plus Plus immediately. I'm uninstall it just now!

**Comment by Shawnsdaddy** [comment]
For the past couple of years, notepad ++ has always been my 1st choice when editing text. I feel very sad when I see this announcement today when I was trying to download the latest version of Notepad++ to my new PC. (It turns out they are doing this low play xxxx starting from 2008 and never succeeded, lol)
However, I stand against those under-educated people spreading fake news about China on the internet. 

xxxxx（口吐芬芳），什么跳梁的小丑，就凭你也抵制冬奥会？你也配？

**Comment by itsmevjnk** [comment]
Let's be real, it's just incredibly sad that meaningful contributions to the open-source community specifically, and to the world in general such as this have a political gatekeep in place. I mean, isn't this a violation of the idea of open source (where everyone is free to use and contribute to the software)?
And if this gets minimized too, then wow, the author of this software really does not respect free speech.

**Comment by Archaoss** [comment]
@itsmevjnk Well, you ARE free to use it or not, contribute or not... If a release name is enough for you to just quit using the software, just do it. No gatekeeping here. Claiming a “disrespect of free speech” is at best hypocrite, but I think it is just dishonest propaganda. Nothing is forbidden here. Free speech, hey.

**Comment by birjolaxew** [comment]
@itsmevjnk Complaining about the Notepad++ author using their right to free speech to criticize human rights violations, while pre-emptively accusing them of not respecting your right to free speech? A bit hypocritical, don't you think?

You're free to use or not use this free software, just like the author is free to use or not use their platform for political outreach. That's what open source is all about.

**Comment by itsmevjnk** [comment]
@birjolaxew @Archaoss Yes, I'm aware that it is my right to use or not use Notepad++, and it is the author's right to use Notepad++ for political outreach, that's fine and all, and it's just me voicing out my opinion on this matter (which is my freedom of speech too).
And as for the "disrespect of free speech" that I mentioned earlier, by minimizing comments, I believe that it is an act of censoring the opinions of those who don't agree with the author's political view (or at least preventing those opinions from being read by others without a GitHub account, who may just want to get a glimpse of the two sides' arguments).

**Comment by birjolaxew** [comment]
@itsmevjnk ... and you're trying to censor the authors political views.

Having your own political views is fine. Attempting to force others to follow them is not. The Notepad++ authors are allowed to express their distate for the human rights violations China are committing, and if you do not want to hear about it, then you are free to walk away from the software. That's your recourse here. There's no point attempting to push the authors to hide their political views - this is something they have every right to express, and which they clearly want to do.

**Comment by itsmevjnk** [comment]
@birjolaxew I will make it clear (again) that was just an opinion, and it's not intended to force anyone to follow any political view.
What I'm upset about is the fact that opposing comments get censored (plus the politicization thing, but the author clearly has the right to do so, so I won't argue further about that). And of course, the author has the freedom to either care or ignore my distaste for the politicization of Notepad++, and I totally acknowledge that right.

**Comment by DenizCapan** [comment]
> ### Description of the Issue
> Notepad++ 8.3 release has "(Boycott Beijing 2022)" text in the title on download page.
> 
> ### Steps to Reproduce the Issue
> 1. Open https://notepad-plus-plus.org/downloads/v8.3/
> 
> ### Expected Behavior
> Title should be "Notepad++ 8.3"
> 
> ### Actual Behavior
> Current title is "Notepad++ 8.3 (Boycott Beijing 2022)"
> 
> Notepad++ is an advanced text editor focused primarily on editing code and configuration files. But for some unknown reason it uses political slogans in its title on download page. This decision looks plainly stupid, because the world is not made up of black and white colors, every situation is much more complicated.
> 
> This hurts Notepad++ and makes it a weapon against some group of people instead of being a useful tool to help everyone. It's not an open source way. Notepad++ is not an open source software, today it's just a tool in hands of positions. It's time to be smart and stop being someones attack dog.




Why do you find this boycott strange when China acts so politically on such products?

**Comment by shoasom** [comment]
this is really non free software spirit, please make softwares, not politics.

**Comment by Yharimium** [comment]
The first step to turn Taiwan into "Ukraine" has been extremely successful. Today, Taiwan's open-source software announced a break with Chinese Mainland, and tomorrow it will be industrial and agricultural products. People on both sides of a strait fall into a cycle of discrimination against each other. Taking the conflict between Russia and Ukraine as a reference, one day, Taiwan leaders such as Tsai Ing wen will become the trigger for war, and Chinese Mainland and Taiwan Island will shoot missiles at each other like Russia and Ukraine. Some people are willing to be clowns and fantasize that the real invaders can save the world they think is in deep water. Some innocent civilians are blown to pieces while a "certain country" will be great again. People have never learned anything from history, even the history at hand.

**Comment by ru61sco** [comment]
As an open source project, it's impossible for npp to really boycott anything at all. People in Beijing are probably using npp to record meeting minutes of 2022 and find it very handy. The author of the "boycott" is just lying to himself to get some illusion of power.

**Comment by donotsdubba** [comment]
A pity to see the "author" (or, more accurately, project (mis)**_appropriator_**, considering the multiple authors behind libre/"open"-source software projects in general) is still engaging in general ideology-shoving and propaganda-pushing as a whole, even in 2023.

I don't refer to the "boycott Beijing" bit specifically, but rather to the recurring issue of the above over all sorts of topics. This "bejing" issue being similar enough, however, I feel there is no need to open another issue anew.

As of today, the main page for NotePad++ defends greenwashing propaganda which is being used as a push for the notion that, and I quote the actual institutions pushing it, "human rights are a secondary right". It's disgusting to see the NotePad++ project appropriators engaging, promoting and pushing agendas that have nothing but genocide in mind.

While real climate issues exist, they scientifically have near-nothing (less than 1%) to do with "carbon footprint", see the renowned meteorologist Dane Wigington's [material and on-the-field coverage of the real cause for over a decade](https://www.geoengineeringwatch.org/), which is military-led climate engineering AKA geoengineering worldwide (US, China, Russia, Israel etc. all alike, and in bed together behind-the-scenes, demonstrably), and [the consequences](https://www.youtube.com/watch?v=GJpYLDSXTaA). If you look around, you will see a lot of declassified US army documents and patents demonstrating this, spanning across numerous decades. These are public, official documents.

Let's also not try to conveniently ignore [Spain's 2015 lead dioxide parliamentary revelation as seen on the EU parliament's website](https://www.europarl.europa.eu/doceo/document/E-8-2015-007937_EN.html), not to mention the [2020 official publication by the Spanish government directly regarding further such actions as per a UN program](https://www.boe.es/boe/dias/2020/04/17/pdfs/BOE-A-2020-4492.pdf) [last link being in Spanish, naturally, translate it if needed].

So when is the release of the **Notepad++** version "**9.0.0 - We were wrong about everything and humbly apologize**" coming? Cease from being a brainless, irresponsible, ignorance-spreading, murder-pushing, denialist TV parrot.

Also, let's see if you will even keep this comment non-minimized or at all available, you self-proclaimed "free speech" advocators. According to your earlier comments above from 2022, YOU guys aren't hypocrites whatsoever. Right? Well, just behold your own actions revealing your true selves _now_ (rather, _again_).

**Comment by Korb** [comment]
This is a duplicate of #6288 (disrespect for other members of the FOSS community by posting political propaganda spam in text editor resources).

**Comment by itsmevjnk** [comment]
Perhaps you should stop telling people that a dead issue is a duplicate of
another dead issue ;) I know you're doing it en masse to other issues too.

**Comment by MatthewMer** [comment]
> @itsmevjnk Well, you ARE free to use it or not, contribute or not... If a release name is enough for you to just quit using the software, just do it. No gatekeeping here. Claiming a “disrespect of free speech” is at best hypocrite, but I think it is just dishonest propaganda. Nothing is forbidden here. Free speech, hey.

It's actually fairly simple, a fundamental concept of the world is to differentiate between things. An open source project is about software, not about politics. We probably already peaked and now we evolve backwards.

**Comment by AnubyteCode** [comment]
My concern is that, in the past, the app has been exploited by state actors in hacks. Adding politics to the release titles invites attacks on users.

In some cases prevents good people from legally using the app in any country that bans it as a result of the messaging. One has to wonder how many people have been restricted, fined or imprisoned as a result of few to no comprehensive alternatives.

In summary, I don't think there has been a single positive effect from doing this. I will continue looking for alternatives that don't paint a target on my backend.

**Comment by cheesecakejohnsonturbo** [comment]
politically tinted software feels unsafe.

**Comment by ghost** [comment]
![Image](https://github.com/user-attachments/assets/fcef27db-de33-47ab-b1d3-666a67e29476)

This is unbearable, it feels like an having political agenda in software

Why is political slogan in Notepad++ release still exists?

**Comment by matxav** [comment]
Usually, when people say the common "don’t like politics", they in fact just don’t like different political opinions that make them worry that their own opinions might be less than perfect. So let me guess - most contributors in this issue complain because their political beliefs are not quite the same (welcome to the RU and PRC users, wink wink). 

If it were me (which I admit it isn't in this case), I wouldn't care much what the SW or its author thinks opposite, as long as my political beliefs were truly solid based (otherwise it might seem like you are weak, hint hint). And if I were to stop using all the SW that says something I don't agree with in its Abouts/ReadMes/Licenses, the first thing I'd have to throw away is even the underlying MS Windows OS.

And for some who doesn't feel comfortable with the spirit of the Notepad++, there's always the option to create a fork and be happy again, e.g.:
https://github.com/PelerYuan/notepad-plus-plus-nationalism

**Comment by Shararamosh** [comment]
No party lasts forever.
<img width="736" height="545" alt="Image" src="https://github.com/user-attachments/assets/77a16efb-7534-43d3-b6f4-2f531fac114e" />

**Comment by studyingegret** [comment]
@matxav I think people may avoid political opinions (same or different from their owns) because e.g. they think arguments about some political topics sometimes feel like a tug-of-war that never ends; their situation is worse than they used to think but there's not much they can do to change it, making them sad every time they think about it; arguing will change nothing unless they have the power, letting them more want to focus more on their daily lives and work; etc. You can argue that avoiding politically tinted software suggests "weak" (and to hint hint about it), but I think everyone have different reasons to do so such that hint hint-ing is not generally accurate. (You don't need to argue back, I just feel your comment is judging books from their covers and that feels not nice.)

**Comment by studyingegret** [comment]
@matxav I think people may avoid political opinions (same or different from their owns) because e.g. they think arguments about some political topics sometimes feel like a tug-of-war that never ends; their situation is worse than they used to think but there's not much they can do to change it, making them sad every time they think about it; arguing will change nothing unless they have the power, letting them more want to focus more on their daily lives and work; etc. You can argue that avoiding politically tinted software suggests "weak" (and to hint hint about it), but I think everyone has different reasons to do so such that hint hint-ing is not generally accurate. (You don't need to argue back, I just feel your comment is judging books from their covers and that feels not nice.)

**Comment by nickolind** [comment]
> politically tinted software feels unsafe.

Exactly. It instantly raises a question: if the person, who prepared the release with such naming, also added some malicious code to it (there are lots of examples of targeting russian speaking users or russian IPs).

**Comment by studyingegret** [comment]
@nickolind Agree. I guess if the software is open-source, those people will expect(?) that users read the source code themselves to find out if there is malicious code in it when asked about this. Like, expect people with (possibly) no programming experience to read the code. Even people with good programming expertise can need to jump through hoops like in [the xz backdoor incident](https://arstechnica.com/security/2024/04/what-we-know-about-the-xz-utils-backdoor-that-almost-infected-the-world/). And if a user gives up investigating, the developer may just say the user asked for spending the effort himself. Looking at the discussion here, I feel it's likely to happen somewhere else.

**Comment by rociomarielgnas** [comment]
Any kind of political messaging is gross ang against the spirit of open source. It is not an issue of free speech, it is an issue of remaining neutral and apolitical because such is the spirit of foss. Writing blahblahblah about Ukraine automatically makes you appear as hostile to Russian users, even if they have zero connection or agreement with the war. What you are doing is exactly what every company that suddenly decided to withdraw Russian people their services overnight: within your right (and EULA, or whichever agreement applies) to do it, but still being an ass. Innocent people lost access to their steam libraries, things they PAID for, because of this. Yes, we are talking about propietary software in this case, but there's a small parallel you can draw between these.

Frankly, including any kind of ideological poisoning anywhere in software meant to be free as in freedom is grotesque to me.
