### ISSUE TITLE
Notepad++ crashed when closing html/xml tags

### ISSUE THREAD

**Issue by KoenigerStefan** [notepad-plus-plus/notepad-plus-plus#11157]
### Description of the Issue
Notepad++ crashed after typing the last letter of the closing tag before the bracket.
Only works when typing both the opening and closing tag.
Copy pasting the tags as well as completing the closing tag before the opeing tag work just fine.

### Steps to Reproduce the Issue
1. Select Language (I tried html and xml)
2. Type Opening Tag eg. `<html>`
3. Type Closing Tag eg. `</html>`
Alternative: 2->1->3

### Expected Behavior
```
<html>
</html>
```
with fancy syntax highlighting and formating

### Actual Behavior
crash

### Debug Information
Notepad++ v8.3   (64-bit)
Build time : Feb  3 2022 - 03:39:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19043.1466
Current ANSI codepage : 1252
Plugins : HTMLTag.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

I'm new to notepad++, but I don't think thats on me.

**Comment by alankilborn** [comment]
Notepad++ 8.3 has changes that affect plugins, and this is probably what you are experiencing.
Plugin authors need to make a change and publish new versions.
As plugins are not associated with the core product, plugin specific sites need to be checked to see if this change is in-progress for a specific plugin.
It appears to be XMLTools in this case.

**Comment by rdipardo** [comment]
Related to #11128 and #11137 

> Plugins : HTMLTag.dll 

Version 1.1 (or older) is known to [crash N++ 8.3 (64-bit)](https://sourceforge.net/p/npp-plugins/discussion/725650/thread/08c8e87447/).
There's a new version (1.2) that should be safe: <https://community.notepad-plus-plus.org/topic/22503/new-version-of-html-tag>

> XMLTools.dll

You need at least version [3.1.1.11](https://github.com/morbac/xmltools/releases/tag/3.1.1.11) to run this without crashing N++ 8.3 (64-bit). [Plugins Admin](https://github.com/notepad-plus-plus/nppPluginList/blob/0a71162cf1426f1ee1ebd73530af702089d58333/src/pl.x64.json#L1238-L1239) has not updated to the safe version yet. You have to upgrade manually for now.

If the issue persists after removing/upgrading the mentioned plugins, then it will probably be fixed in the next N++ release: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/73a4cdc1040c15cee87ff21de94dd7669cdda607

For now, try turning off the built-in tag highlighter at  `Settings > Preferences > Highlighting` 

![](https://user-images.githubusercontent.com/10229320/152581019-950bc51a-3e9e-4311-871c-638ef3d85de8.png)

**Comment by donho** [comment]
Fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/73a4cdc1040c15cee87ff21de94dd7669cdda607
The fix will be in the next release.
