### ISSUE TITLE
Regular Expressions hangs

### ISSUE THREAD

**Issue by marcovianini** [notepad-plus-plus/notepad-plus-plus#11180]
### Description of the Issue
If I make a search using regular expression and I insert a double pipe for mistake, Notepad++ hangs! (Because it matches everything in the file)

### Steps to Reproduce the Issue
1.  Try to search for the following string "test||test2"

### Expected Behavior
I expect the double pipe is ignored automatically by Notepad++
Or
I expect a button to stop Search Process without waiting until search completes. Because the Search needs a very long time to complete (some hours if the file is very big)

### Actual Behavior
Notepad++ hangs for a very long time (some hours)

**Comment by alankilborn** [comment]
>I expect the double pipe is ignored automatically by Notepad++

This is not a realistic expectation.

**Comment by marcovianini** [comment]
Ok, but what about the second expectation? That is a button to stop Search Process without waiting until search completes.

This is a feature that any well-structured app should include: immediate termination of the research process

**Comment by alankilborn** [comment]
>but what about the second expectation?

I purposefully didn't comment on that part. :-)
I'll let someone else do that.

**Comment by dail8859** [comment]
> I expect the double pipe is ignored automatically by Notepad++

I don't think this is something Notepad++ needs to try to guess when a user is making a potential error in the regular expression. It is possible this zero match behavior might be needed. It is very easy for regular expressions to be written poorly or incorrectly.

> I expect a button to stop Search Process without waiting until search completes.

I completely agree this would be useful. If I recall correctly there are open issues regarding stopping/halting find operations. I would suggest searching through the issues and post any additional information on an issue if it is open. If you can't find any open issues then I'd recommend opening another issue specifically just for being able to stop searches so that it can be discussed.
