### ISSUE TITLE
Notepad++ x86 on 64Bit Windows can't save files in C:\Windows\Sysnative\...

### ISSUE THREAD

**Issue by dodmi** [notepad-plus-plus/notepad-plus-plus#11196]
### Description of the Issue
- Notepad++ 8.1.6 x86 and later fail to save files in C:\Windows\Sysnative\... which points to C:\Windows\System32\ on 64 bit Windows systems. I noticed this trying to change my hosts file. This works fine in Notepad++ 8.1.5.

### Steps to Reproduce the Issue

1.  Open an elevated command prompt
2.  Run `PathToNPP\notepad++.exe -noPlugin C:\Windows\Sysnative\drivers\etc\hosts`
3. Change something
4. Hit Save
5. An error will appear, that the file can't be saved

### Expected Behavior

The file should be saved.

### Actual Behavior

The file can't be saved.

### Debug Information

Notepad++ v8.2   (32-bit)
Build time : Dec 30 2021 - 03:36:49
Path : C:\Program Files (x86)\Office\Notepad++\notepad++.exe
Command Line : -noPlugin C:\Windows\Sysnative\drivers\etc\hosts
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 (64-bit) 
OS Version : 2009
OS Build : 19044.1526
Current ANSI codepage : 1252
Plugins : none

![image](https://user-images.githubusercontent.com/4572946/153731846-269277a1-233a-469d-9cd0-600ccf88fccf.png)

**Comment by mere-human** [comment]
This file is probably protected and requires administrator rights in order to edit it.
I tried a similar command line:
`-nosession -multiInst -noPlugin  C:\Windows\System32\drivers\etc\hosts`
And I got this message:
![image](https://user-images.githubusercontent.com/9664141/154272010-85b0a065-7298-46e4-8c33-e412b7cc276b.png)
After pressing Yes I was able to modify and save the file.
Did you see a similar message?

**Comment by xomx** [comment]
@mere-human 

From the @dodmi report is clear (e.g. look at the N++ screenshot taken - there is the [Administrator] visible), that the N++ has been already elevated before by launching from the elevated cmd. So there should not be the "Save failed - Do you want ... Administrator mode?" msgbox visible.

@dodmi 

I have tried exactly your steps but with the current 8.3.1 x86 portable. And I was able to save that file. So there should be something else in your way.

But - on another PC I have the ZoneAlarm firewall installed and it failed to do so. When I looked at the ZoneAlarm setting, I have found an advanced setting "Lock host file" checked. After I unchecked that, I have started to be able to save ok. So maybe you have a similar SW installed on your computer(?). Maybe an antivirus solution(?).

**Comment by xomx** [comment]
@dodmi 

Ok, now I am able to reproduce your issue reported.
I forgot to use your "Sysnative" substitute for the x64 "System32".
When I used "PathToNPP\notepad++.exe -noPlugin C:\Windows\System32\drivers\etc\hosts", the saving worked ok.

**Comment by xomx** [comment]
I have found the culprit here - it is the default using of the flag `FILE_FLAG_POSIX_SEMANTICS` in the ".\PowerEditor\src\MISC\Common\FileInterface.h".

Without this flag the CreateFile call in the described situation succeeds, so such writing is then possible.

Contrary to the N++, the standard Windows Notepad works ok in such situation, you can try that by:
"C:\Windows\SysWOW64\notepad.exe C:\Windows\Sysnative\drivers\etc\hosts"
then modify the file & save.

**Comment by dodmi** [comment]
@xomx Thank you for your extensive testing.
Actually as I wrote in my bug report, this was/is also working in Notepad++ prior to version 8.1.6

**Comment by xomx** [comment]
@dodmi 

> this was/is also working in Notepad++ prior to version 8.1.6

Yes, in the version 8.1.6 has been exchanged the original POSIX IO (fopen/fwrite) for the WIN32 API one (CreateFile/WriteFile) for the file saving. For this issue is problematic only the use of the 'case sensitive file access flag' [FILE_FLAG_POSIX_SEMANTICS](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea#parameters).

To tell the truth - I do not fully understand yet, why this 'case sensitive' flag causes this fail of the CreateFile API. One explanation could be that the Windows OS inherent substitute for the "Sysnative" is e.g. "SYSTEM32" instead of the real "System32" used on the disk ("at least that is used on my PC ... "C:\Windows\System32\").

@pnedev 
Is that `FILE_FLAG_POSIX_SEMANTICS` really needed?
Is it equivalent to the previously used POSIX fopen-way? (I suppose that it is relevant when accessing a *NIX file systems, but was something like that there before with the fopen-way?)

**Comment by pnedev** [comment]
Hi @xomx ,
Very good analysis, perhaps the system indeed replaces "Sysnative" with "SYSTEM32" and the new case sensitivity flag is problematic in that case.

The `FILE_FLAG_POSIX_SEMANTICS` is not needed actually - it is not equivalent with `fopen` in any way and is additional option in the Win32 API. I added it as a personal preference (because I'm mainly working on Linux and because I thought that having case sensitive file naming in the new API can't hurt the existing functionality and perhaps could even help in cases with mapped UNIX like drives).
So this flag is new and can be safely removed to fix this issue - the file saving function then will behave as in pre-8.1.6 Notepad++ versions.

**Comment by xomx** [comment]
@pnedev 
Thanks for your quick confirmation.

So I am going to do a PR for it to others can also test & confirm my findings.

But the final decision will be up to @donho and I know that he will not be happy from any change in this WIN32 IO area...

**Comment by pnedev** [comment]
Thanks @xomx .

> But the final decision will be up to @donho and I know that he will not be happy from any change in this WIN32 IO area...

I guess that Don will not have problems merging your PR because we discussed that flag before and he was asking me about the justification of `FILE_FLAG_POSIX_SEMANTICS` flag as well. We decided back then that it will not be problematic and it will be safe to leave it as an enhancement.

**Comment by xomx** [comment]
@dodmi 
Could you please download & re-test the patched Notepad++.Win32.Release.exe artifact:
https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/42608795/job/8km2iajucog6fkma/artifacts

**Comment by dodmi** [comment]
@xomx I can confirm, it's working again, using the executable from https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/42608795/job/8km2iajucog6fkma/artifacts

Thank you both

**Comment by donho** [comment]
> But the final decision will be up to @donho and I know that he will not be happy from any change in this WIN32 IO area..

These codes are contributed by @pnedev , so if he feel it's save to remove FILE_FLAG_POSIX_SEMANTICS flag, I have no problem with it.

**Comment by donho** [comment]
@xomx 
> I forgot to use your "Sysnative" substitute for the x64 "System32".

How can I do the same?

**Comment by xomx** [comment]
@donho 

Just use it like:
- start the 32-bit cmd (goto "C:\Windows\SysWOW64\" and run the "cmd.exe" there)
- in the cmd-window enter the "C:\Windows\System32\notepad.exe" (e.g. Ctrl+C on the text here & then right-click in the cmd-window & 'Paste')
- check in a task manager that you are running the 32-bit version of the notepad.exe (though you have used the 64-bit path "C:\Windows\System32\")
- close the opened 32-bit Notepad
- in the same cmd-window enter the "C:\Windows\Sysnative\notepad.exe"
- check in a task manager that now you are running the 64-bit notepad.exe

A 64-bit Windows OS internal 'shim' translates transparently this "Sysnative" string to its 64-bit equivalent.
This is the easiest way for 32-bit apps, how to handle those 32/64 redirections without additional code-changes.

**Comment by donho** [comment]
@xomx 
Thank you for the explanation.So `Sysnative` is only visible for x86 appz, isn't it?
