### ISSUE TITLE
Feature Request: Scroll "Document List" to make the selected item/tab always visible

### ISSUE THREAD

**Issue by dz15mlru** [notepad-plus-plus/notepad-plus-plus#11204]
Notepad++ "Document List" mode does not remember the location of the active open tab after relaunching N++.

E.g. I have over 300 open tabs and "Document List" mode enabled. If I am on the 300th tab, then when launching N++ it will not show the "Document List" at the 300th tab, but it will display it at the beggining of the list of open tabs, and I need to scroll down the "Document List" to reach the end of the list.

**Comment by komurugov** [comment]
Hi everybody, hi @donho,
I would like to fix this issue. The solution (already tested) is to initiate call of ListView_EnsureVisible at the end of Notepad_plus::launchDocumentListPanel().
As I understand from Contributing.md, I may request to be assigned to this issue (because the issue hasn't been accepted), right? Does it mean that I should create a Pull Request?
I've no previous experience in GitHub contributing, so please excuse me, if it's not the right workflow.

**Comment by ArkadiuszMichalski** [comment]
When we switch document on `Document List` then corresponding document in `Tab Bar` is selected and the view is updated too (we can see this tab). But the reverse action doesn't update the view in the `Document List` (it just selects it). So if we have a long list on `Document List` we need scroll it manually. 

@donho This is probably not intentional and could be fixed?
