### ISSUE TITLE
Don't sync window position through the cloud

### ISSUE THREAD

**Issue by michael-kenzel** [notepad-plus-plus/notepad-plus-plus#1121]
I work on multiple machines and I could not live without the cloud sync feature. However, one slight annoyance is that np++ simply stores its entire config in the cloud which includes things like the window position and file history both of which are examples of settings that only make sense on a specific machine. Whenever I switch from one machine to another, I have to reposition np++ because it will open its window at the coordinates that it had the last time it was opened on another machine which will be dramatically different, e.g., when one machine is a desktop with two 1080p displays and the other one is a laptop with a 4K display.

I propose to split the config files, one config file that is always stored in the local user directory and holds machine-specific settings such as the window position and file history and the other one is optionally stored in the cloud.

**Comment by u01jmg3** [comment]
Find this irritating too so +1.

My only suggestion would be to have a folder for the settings for N++ at _work_ and then another for at _home_. However, you would have to sync the settings manually between the two. For me anyway, I don't change my settings very often.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
