### ISSUE TITLE
Increase the number of open documents displayed in Window menu

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#11229]
**STR:**
Menu -> Window.

**Result:**
The number of open documents displayed is limited to 10.

**Suggestion:**
Change the limit to 20.

https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11190#issuecomment-1042859100

***

Notepad++ v8.3.1   (64-bit)
Build time : Feb 16 2022 - 22:55:56
Path : C:\---\notepad++ Original.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1255
Plugins : ComparePlus.dll HTMLTag.dll MenuIcons.dll PythonScript.dll _CustomizeToolbar.dll

**Comment by alankilborn** [comment]
I think the limit was originally designed because of the "underlining":

![image](https://user-images.githubusercontent.com/77065706/154496883-be316d27-65aa-4c53-addc-e449c4d2b097.png)

If there were more files they wouldn't have underlines in their number.

Just pointing this out for historical reasons; this limit could certainly be increased if the author agrees.

**Comment by Yaron10** [comment]
@alankilborn,

👍 
Very nice! I loved that comment. :)

I've actually changed the number for my personal use.
Being a "mouse-oriented" user, I've never noticed it.

Thank you.

**Comment by Yaron10** [comment]
@alankilborn,

Your point is relevant to the _Recent Files_ list as well. :)
And the number is not limited to 10.

**Comment by alankilborn** [comment]
>Your point is relevant to the Recent Files list as well. :)
>And the number is not limited to 10.

But the default is 10.
Suggests same development history occurred there.
At least at first; then at some point it was expanded and also made configurable.
