### ISSUE TITLE
Find: (-> Search -> Find -> Find All in Opened Documents, Bug Not highlighting in find results window 

### ISSUE THREAD

**Issue by bcomegys** [notepad-plus-plus/notepad-plus-plus#1122]
A search through two text files using -> Search -> Find -> Find All in Opened Documents
It would also be nice in -> Find -> Count, if the counted items where highlighted. 
Bold = Highlighted 
Shows in the display for the text file buffer (on top). 
Text File 1 
**fred** george **fred**
**fred**
**fred** **fred**
Text File 2
**fred** **fred**
**fred**
**fred** george **fred**

In the find result windows shows 
Find result - 10 hits 
Search "fred" (10 hits in 2 files) 
new 2 (5 hits)
**fred** fred
fred **fred**
**fred**
**fred** george fred 
fred george **fred**
new 3 (5 hits)
**fred** george fred
fred george **fred**
**fred**
**fred** fred 
fred **fred**

Thanks for a great product!

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
