### ISSUE TITLE
Session is Auto-Saved on Exit

### ISSUE THREAD

**Issue by ronstudy1** [notepad-plus-plus/notepad-plus-plus#11249]
### Description of the Issue
Session is saved after exiting npp even though "Multi-Instance settings" is set to "Default (Mono-instance)"

### Steps to Reproduce the Issue
(using latest version 8.3.1)
1. In Preferences:
1.1 set "Multi-Instance" mode to "Default (Mono-instance)"
1.2 In "Backup", uncheck "Remember current session for next launch"
2. open npp session file ("notepad++.exe"  -multiInst -openSession "c:\path\to\mySession.nppSession")
3. make some session-modifications (e.g. change active tab, close tab, open another tab)
4. close npp
5. re-open the session file (as in step 2)

### Expected Behavior
session looks the same as in the end of step (2)

### Actual Behavior
session looks the same as in the end of step (3)

**Comment by xomx** [comment]
This seems to be a regression caused by the #10935 arisen from the incomplete implementation of the loaded session auto-saving on exit.

At the N++ exit the code-flow ends up in the ".\PowerEditor\src\NppBigSwitch.cpp" -> `Notepad_plus::process()` -> `case WM_CLOSE:`, relevant code for this issue is:

```
	//
	// saving session.xml into loaded session if a saved session is loaded and saveLoadedSessionOnExit option is enabled
	//
	generic_string loadedSessionFilePath = nppParam.getLoadedSessionFilePath();
	if (!loadedSessionFilePath.empty() && PathFileExists(loadedSessionFilePath.c_str()))
		nppParam.writeSession(currentSession, loadedSessionFilePath.c_str());
```
- the comment there ("... saveLoadedSessionOnExit option is enabled") is a little bit misleading, as there is no explicit `saveLoadedSessionOnExit` implemented, the 'session auto-saving on exit' should be triggered only when `_multiInstSetting` is `multiInstOnSession` (enum 1) or `multiInst` (enum 2):

	Notepad_plus::fileLoadSession(), relevant code:
```
	if (nppParam.loadSession(session2Load, sessionFileName.c_str()))
	{
		const bool isSnapshotMode = false;
		const bool shouldLoadFileBrowser = true;
		isAllSuccessful = loadSession(session2Load, isSnapshotMode, shouldLoadFileBrowser);
		result = true;
		if (isEmptyNpp && (nppGUI._multiInstSetting == multiInstOnSession || nppGUI._multiInstSetting == multiInst))
			nppParam.setLoadedSessionFilePath(sessionFileName);
	}
```
- but there is also 2nd similar session loading code at `Notepad_plus::loadCommandlineParams()`, where is no such checking, so the `nppParams.setLoadedSessionFilePath()` is called even for the `monoInst` (enum 0) mode:
```
	if (nppParams.loadSession(session2Load, fnss.getFileName(0)))
	{
		const bool isSnapshotMode = false;
		const bool shouldLoadFileBrowser = true;

		nppParams.setLoadedSessionFilePath(fnss.getFileName(0));
		loadSession(session2Load, isSnapshotMode, shouldLoadFileBrowser);
	}
```

I will do some additional testing and if it works ok I will do a PR for it.

**Comment by donho** [comment]
Does it really a regression? I don't think so.
When we open a new session in a new instance specially, the behaviour should be the same on the option "Open session in a new instance (and save session automatically on exit)".

Can anyone here provide his/her opinion and suggestion here?

**Comment by ronstudy1** [comment]
> Is it really a regression?

it's a regression since i firstly noticed this issue on 8.2.1. it started at some recent version

> When we open a new session in a new instance specially...

the issue  happens even without using the "-multiInst" flag

**Comment by xomx** [comment]
It is a bug, not a feature. The missing cmdline implementation of the logic:
```
	if (nppGUI._multiInstSetting == multiInstOnSession || nppGUI._multiInstSetting == multiInst)
```
causes that the following code always succeeds at exit, regardless of the current `nppGUI._multiInstSetting`, when using the cmdline '-openSession' possibility:
```
	generic_string loadedSessionFilePath = nppParam.getLoadedSessionFilePath();
	if (!loadedSessionFilePath.empty() && PathFileExists(loadedSessionFilePath.c_str()))
		nppParam.writeSession(currentSession, loadedSessionFilePath.c_str());
```

Also consider please that at the present state the session file loading via File menu 'Load Session...' behaves differently than the cmdline loading via '-openSession'. The File-menu way is ok (with the N++ settings described in this issue, the session is not auto-saved), the cmdline way is not ok.
