### ISSUE TITLE
user prompt spawning outside of screen space

### ISSUE THREAD

**Issue by Redundanz** [notepad-plus-plus/notepad-plus-plus#11240]
### Description of the Issue

using for example the "save all" routine (regardless of invocation method) opens the dialog box outside of screenspace in contrast to for example the "save as..." routine which follows windows api standard behaviour.

### Steps to Reproduce the Issue

1.  move a commonly sized notepad++ window towards bottom of the screen so that at least 70-80% of the window are leaving the screen space on the bottom
2.  create or change at least one document with multiple documents open
3. invoke "save all" (i.e. clicking on toolbar button)

### Expected Behavior

"save all" dialog box spawns inside screen space - at least as far inside as to be noticable and movable. preferable the way a standard api dialog box spawns when main window is dragged over (any) edge of the screen.

### Actual Behavior

"save all" dialog box spawns outside of screen space - providing no visual feedback to user - user has to assume he has to use either ENTER or ESCAPE to resolve prompt.

### Debug Information

Notepad++ v8.3.1   (64-bit)
Build time : Feb 13 2022 - 15:41:12
Path : C:\Program Files\npp\notepad++.exe
Command Line : "C:\Users\Administrator\Desktop\pixelated.txt"
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 2009
OS Build : 19044.1466
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

additional note:
other dialog boxes of other npp routines may of course behave similarly, i haven't tested every routine upon finding this issue.
i just saw that for example "save as..." and "save copy as..." and also "print" all show expected behaviour and spawn inside screen space.

**Comment by alankilborn** [comment]
Presume you mean this window:

![image](https://user-images.githubusercontent.com/77065706/154692246-57e75707-dd9b-4a81-b2e5-3984d4a50577.png)

Basically there are 2 types of these windows:

* Windows standard windows (Open, SaveAs, Print...)
* Notepad++ created windows (of which the one in the screenshot is of this type)

Probably what you'll find is that the Windows standard stuff won't open offscreen like you describe, and sometimes N++ created windows will.  It's because the N++ created windows aren't specifically checking for that situation.
