### ISSUE TITLE
Will not auto-complete with Enter, have to click with mouse

### ISSUE THREAD

**Issue by bartfran** [notepad-plus-plus/notepad-plus-plus#11313]
### Description of the Issue
Auto-complete in Notepad++ v8.2.1 to 8.3.2 (Tried all versions, 8.2.0 works fine) on Windows 10 64 bit has to be clicked with the mouse, instead of selecting from the list with keyboard and pressing Enter, instead Notepad++ generates a CR + LF instead

### Steps to Reproduce the Issue

1. Start to type something that can be expected to auto-complete
2. Select auto-complete from list with keyboard and press Enter

### Expected Behavior
When Enter is pressed after an auto-completion the auto-complete word is filled in

### Actual Behavior
A CR + LF is generated instead of the auto-complete item

### Debug Information

Notepad++ v8.2.1   (64-bit)
Build time : Jan 19 2022 - 18:43:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1526
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll 

Notepad++ v8.3.2   (64-bit)
Build time : Feb 27 2022 - 03:35:46
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1526
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll 

![image](https://user-images.githubusercontent.com/100652219/156087837-c52af34f-4fa1-494a-808d-a598eb9e493a.png)

**Comment by alankilborn** [comment]
![image](https://user-images.githubusercontent.com/77065706/156093505-68a11e83-1836-4adb-9429-312f897fc713.png)

**Comment by Jens-G** [comment]
I can confirm this issue. I told you yesterday.

**Comment by alankilborn** [comment]
@Jens-G Maybe you should be grateful that you get to use this excellent software for absolutely no cost, instead of complaining.  If you read the history on this, the default was changed and the option added because the older behavior was judged to be a bug.

**Comment by Jens-G** [comment]
@alankilborn I am indeed grateful and love Notepad++ because it was just perfect until this particular change was made (and the slow startup which is the other thing driving me crazy for weeks now). Also I might add that I work on FOSS myself, so I do know the ropes.  Nevertheless, "its free" is just not an excuse for everything, so please stop using that as a killer argument.

**Comment by alankilborn** [comment]
>Why are you silently changing defaults?

Not all that silent; it is in the release notes, and probably the user manual by now.

>Who on earth should find out that there is now a setting that one must enable...

Those that read the release notes.

>PS: The n umber of tickets on that topic in this issue tracker alone tells a lot.

Perhaps, but there aren't any tickets from those that are grateful the "bug" has finally been fixed, so those are impossible to count.  I put "bug" in quotes because it existed for so long that some thought it was a feature.  However you look at it, just tick the box and move on.

>"its free" is just not an excuse for everything

Not using it as an excuse, just trying to present a reality check.

**Comment by bartfran** [comment]
Thank you for the quick response and I can confirm this fixes my issue. Thought I had done a review of the change notes and did not notice this change anywhere, obviously I must be incorrect. I am grateful for Notepad++ it is an awesome editor, but I have to agree, changing something that is considered a default is never good, and auto-complete has used the Enter ever since I can remember starting using it in Notepad++, but can also appreciate the ability to disable it if desired.

Thanks for Notepad++
