### ISSUE TITLE
NPP crashes on opening a session file

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#11325]
**STR:**
Create two files: _C:\T1.txt_ and _C:\T2.txt_.
Create a session file containing the following lines:
```
<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="0">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="514" startPos="0" endPos="0" selMode="0" lang="None (Normal Text)" encoding="-1" filename="C:\T1.txt" backupFilePath="" originalFileLastModifTimestamp="1462017716" />
        </mainView>
        <subView activeIndex="0">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="514" startPos="0" endPos="0" selMode="0" lang="None (Normal Text)" encoding="-1" filename="C:\T2.txt" backupFilePath="" originalFileLastModifTimestamp="1461982719" />
        </subView>
    </Session>
</NotepadPlus>
```
Open that session file (i.e. double-click on it or drag it into NPP).

**Result:**
NPP crashes.

**Caused by** https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ca8c302805f882ed61717bb26efbc141a6991ea7.

***

Notepad++ v8.3.2   (64-bit)
Build time : Feb 27 2022 - 16:11:01
Path : C:\---\Notepad++ Original.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1255
Plugins : ComparePlus.dll HTMLTag.dll MenuIcons.dll PythonScript.dll _CustomizeToolbar.dll

**Comment by xomx** [comment]
@Yaron10 
Where have you got this session file? Is it an old one? Or is it created manually somehow?

I am asking because of there are missing usual items in it (that is the reason for the crash, e.g. there is missing a `offset="0"`, so then the `(childNode->ToElement())->Attribute(TEXT("offset")` returns NULL instead of a string). One cannot simply create such file now, when uses the menu File -> 'Save Session...'

Anyway, I can fortify the relevant `NppParameters::getSessionFromXmlTree()` code to prevent that.

**Comment by Yaron10** [comment]
@xomx,

Yes, it's an old session file. Not created manually.

> One cannot simply create such file now, when uses the menu File -> 'Save Session...'

Correct. But I suppose that many users still have the old-format session files.

> Anyway, I can fortify the relevant...

Great. 👍 
Thank you for your time and work.
