### ISSUE TITLE
Issue editing large files

### ISSUE THREAD

**Issue by charlieb000** [notepad-plus-plus/notepad-plus-plus#1132]
I have a 40.5MB XML spreadsheet which i wanted to take a peak at but for some reason the drawing of the window slows down badly, if i cover it and uncover the window (turns out to only occur if i cover an inactive line, even just hovering the mouse over it will trigger it), the program hangs. its even worse if bookmarks are open.

content inside the options dialog is immune. effects scrolling. effects changing of lines with mouse (shading of desired line is enabled first, then a pause and shading of previous (now inactive) line is removed). still can select kinda fast (no scrolling). 

i attempted to select text from one row into the next and bookmarks kept reupdating (slowly), i gave up and closed the process.

So the big question is, why is it tossing out what the window looked like and redoing?

the XML spreadsheet megabytes of content content in certain Rows.

**Comment by charlieb000** [comment]
I have found a fix it, but i suggest that that it could be done in the background so user will never see it.
all i did was i replace <row> with \n <row>.

If a line happens to be so long, ask user if they can specify a word that is repeated (or scan file for one) so NPP can usefully highlight blocks within a block of text.
the <row> delimiter encompasses a number of <cell></cell> delimiters. and it actually would be useful to have the group highlighted.

Charlie.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
