### ISSUE TITLE
Please add YAML Syntax

### ISSUE THREAD

**Issue by labeldevops** [notepad-plus-plus/notepad-plus-plus#11336]
I am writing YAML files - it is really annoying that there is no default syntax highlight for YAML files that comes with NPP - please add that. Instead of doing the real work I am now yakshaving NPP to install some YAML syntax file from the internet and wonder why it has no effect, I just want it to work and it does not. Jeezuz, wat a pain. Please add YAML! THANKS!

**Comment by dail8859** [comment]
YAML support was added in c83d5801c96a96af26e383cca702e8d3e3247c19 which was part of the v4.7.4 release.

This was 14 years ago.

It seems something is misconfigured on your system. I recommend opening another issue and follow the issue template so that enough information is provided so that we can try to help you fix it.

**Comment by davef1487** [comment]
I think it's that it's theme-dependent. If I select the Twilight theme, YAML disappears from the style configurator, is rendered as plain text, and cannot be associated with another styler.
