### ISSUE TITLE
Interface changes with BOM vs -BOM, is causing a lot of confusion

### ISSUE THREAD

**Issue by KrisZane** [notepad-plus-plus/notepad-plus-plus#1133]
So recently'ish you changed the interface to UTF8 encoding being UTF8 without BOM and the "UTF8 without BOM" became UTF8-BOM and apparently UTF8 with BOM.
Now I am all for this but a heads up for people with this would have caused a lot less problems for a lot of people, especially because these settings not only change names but also switched places.

On to the actual issue, the new document setting has not been updated with this same methodology, leaving people very confused as to how this actually works, can I suggest you fix the naming in there as well?

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
