### ISSUE TITLE
Document switcher dialog is outside screen area

### ISSUE THREAD

**Issue by kometbomb** [notepad-plus-plus/notepad-plus-plus#1134]
When having lots and lots of documents open in Notepad++, pressing Ctrl+Tab to open the documents list, it is not aligned properly and the topmost few documents are above the top of the screen. If I keep the keys pressed and use the mouse to resize the document selector dialog (dragging the borders) the dialog top will snap to screen bounds (but still be tall enough to have the last items outside the screen). 

This happens in Windows 7 and 8.1 without any plugins installed, it pretty much has been like this always as I remember.

Not sure if relates to #859 since I never touch the DPI settings etc. text size settings.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
