### ISSUE TITLE
Improve Notepad++ stability by filtering better incompatible plugins on startup

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#11358]
In commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/f9118dd13c637a4054c101e685c9030115f790c8 "npp-compatible-versions" has been added in plugin list for helping not only Pllugin Admin but also Plugin Manager (Plugin Loader) to check the compatibility with the latest version of plugin (if the version of installed plugin is the latest one).

However, for Plugin Manager if the version of installed plugin is the previous one, there's no info to know if this plugin with old version is compatible with running Notepad++. In order to filter better old version plugins, "old-versions-compatibility" is added in plugin list, so Plugin Manager can use it to check the compatibility to decide load it or not.

**Comment by rdipardo** [comment]
### Some perspective

- Compatibility is a Yes/No proposition. A plugin either __*is*__ or __*is not*__ loadable __*by the currently running N++ application!*__ The logic to decide this was just implemented by f9118dd. Can we take the time to test it first, before making it even more complicated?

- At the moment, only [21 x64 plugins] have published compatibility restrictions. This change will affect ~16% of 64-bit plugins; that's ~7% of all installation candidates, including 32-bit and ARM64. Can plugin authors have time to adopt this model, before making it even more complicated?

- Show me a package manager that needs to know what older versions used to do, instead of __*just upgrading your installation to whatever is newest*__.

[21 x64 plugins]: https://github.com/notepad-plus-plus/nppPluginList/blob/3eb0b6581324a21f97f2c6457818fd06749b549a/src/pl.x64.json

**Comment by rdipardo** [comment]
I've already [said enough] on this topic. Here are my final thoughts, in point form. 

### Existing Functionalities

1. get the version of the running N++ application

  &#x2705;  e.g., Debug Info window

2. get the version of every installed plugin

  &#x2705;  e.g., the "Installed" tab of the Plugins Admin dialog

3. get the latest release version of every available plugin, and compare it with what's already installed

  &#x2705; e.g., the "Upgrades" tab of the Plugins Admin dialog


### Required Functionalities

a. check if a plugin has compatibility constraints (=> `"npp-compatible-versions"` != `NULL`)

  &#x2705; available since f9118dd

b. is the plugin with the constraint installed ?

  &#x2705; functionality n.<sup>o</sup> 2, above

c. does the installed plugin match the version with the constraint ?

  &#x2705; functionality n.<sup>o</sup> 3, above

d. if yes, does the running N++ version satisfy the constraint ?

  + &#x2705; functionality n.<sup>o</sup> 1, above
  + &#x2705; f9118dd

e. if no, upgrade the installed plugin to the newer version, and repeat all steps

f. if yes, load the plugin

[said enough]: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11356#issuecomment-1062687235

**Comment by donho** [comment]
@rdipardo 
> if no, upgrade the installed plugin to the newer version, and repeat all steps

Yes, it's a very interesting feature, but it needs a lot of coding effort. I will consider it, but it won't be in upcoming release for sure.
