### ISSUE TITLE
WinGet version out of date. Fails to install.

### ISSUE THREAD

**Issue by simsrw73** [notepad-plus-plus/notepad-plus-plus#11398]
It looks like WinGet is trying to download a version that is no longer available:

PS C:\Users\simsrw73> winget install --id Notepad++.Notepad++
Found Notepad++ [Notepad++.Notepad++] Version 8.3.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.3.2/npp.8.3.2.Installer.x64.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).

**Comment by rdipardo** [comment]
It really is no longer available: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v8.3.2 
It's a push to get users onto 8.3.3, since things have been crazily unstable since 8.3 (which was also [withdrawn after release][1]).

[1]: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v8.3

**Comment by simsrw73** [comment]
Will WinGet installer be updated so that it installs the updated version instead of failing? It's been failing since yesterday at least, so it's no longer possible to install with WinGet.

**Comment by dail8859** [comment]
Installing via WinGet is not supported by the Notepad++ team. Whoever maintains that entry for WinGet needs to fix it.

https://github.com/microsoft/winget-pkgs/pull/54453
