### ISSUE TITLE
Word wrap: add option to wrap on column 80

### ISSUE THREAD

**Issue by dewi-ny-je** [notepad-plus-plus/notepad-plus-plus#1140]
I think the word wrap button option in the menus should open a submenu with three options: "none/window/custom column (XX)/set custom column..."
On the toolbar the button should cycle between the first three elements of the submenu I suggested.

This is useful to format README or similar files, where I don't want to go beyond the 80th column, and also useful when I use Notepad++ to write simple text files: the eye reads better when the lines are no too long. Changing the width of the window is possible, but if I am also working on other tabs with code, resizing all the time is not feasible.

**Comment by aaaxx** [comment]
Related: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/482

**Comment by donho** [comment]
Such feature depends on Scintilla, so it won't be implemented in Notepad++.

**Comment by Darklocq** [comment]
What does that mean in English?

**Comment by sasumner** [comment]
>What does that mean in English?

Presume you are asking about "Such feature depends on Scintilla, so it won't be implemented in Notepad++."

Notepad++ embeds another project, called "Scintilla" as its editing component.  Because of this, certain features are under Scintilla control and not Notepad++ control.  So, if something is requested here that Notepad++ doesn't have control of, either the request has to be made of the Scintilla project (possibly followed-on by some minor Notepad++ changes), or it just can't be (reasonably) done.

**Comment by dewi-ny-je** [comment]
@donho @sasumner 
I'm not skilled enough to submit a proper bug report/feature request in Scintilla.

Could you do it, as developer(s) of a project that embeds said library?

**Comment by mentallurg** [comment]
It is not correct that this ticket is closed. From the point of view of user of Notepad++ the developers of of Notepad++ are responsible for providing this feature. It doe NOT matter if they should implement it or if this should be implemented in some library. If latter, it is a responsibility of developers of Notepad++ (not responsibility of a user) to create needed feature request in other libraries like Scintilla, integrate them and only then close the ticket in Notepad++.

The current behaviour of developers of Notepad++ shows that they are not interested in satisfying the users. If you don't do that for users, for whom them?

**Comment by sasumner** [comment]
>From the point of view of user of Notepad++ the developers of of Notepad++ are responsible for providing this feature.

Nope. 100% wrong.  Or more.

**Comment by dewi-ny-je** [comment]
Well the developers cannot implement the feature in Scintilla of course, but I'm very surprised that the ticket got closed: it should be assigned a tag "required library support" and left open.
When Scintilla gets the feature, this ticket will be closed with "updates to latest Scintilla, closes #1140" or similar.

If you close it, no trace will be left of the reques feature...

**Comment by sasumner** [comment]
@dewi-ny-je That's reasonable, but who's to say Scintilla will ever get the feature?  I don't think the responsibility for working with the Scintilla folks to get a feature implemented is now on the plate of N++ devs.

**Comment by mentallurg** [comment]
@sasumner:
>  I don't think the responsibility for working with the Scintilla folks to get a feature implemented is now on the plate of N++ devs.

If I understand you correctly, developers of Notepad++ expect that **users** (instead of developers) **organize** the work of developers on Notepad++: That users (instead of developers) analyze the source code of Notepad++, find out where which function is implemented, find the authors of the needed library, post there feature request, wait for implementation, when ready - post request at Notepad++, etc. Sure you have right to work in such way. But it is pretty **frustrating** for users.

**Comment by mentallurg** [comment]
@dewi-ny-je: 

> ... I'm very surprised that the ticket got closed: it should be assigned a tag "required library support" and left open.
> When Scintilla gets the feature, this ticket will be closed with "updates to latest Scintilla, closes #1140" or similar.
> 
> If you close it, no trace will be left of the reques feature...

Correct. That is what I expect from developers of Notepad++. Would you reopen the ticket, please?

**Comment by sasumner** [comment]
>If I understand you correctly, developers of Notepad++ expect that users (instead of developers) organize the work of developers on Notepad++: That users (instead of developers) analyze the source code of Notepad++, find out where which function is implemented, find the authors of the needed library, post there feature request, wait for implementation, when ready - post request at Notepad++

Ummm, pretty much "no" to all of that...
