### ISSUE TITLE
8.3.3 breaks screen reader accessibility

### ISSUE THREAD

**Issue by LJWatson** [notepad-plus-plus/notepad-plus-plus#11424]
The upgrade to 8.3.3 on Windows 11 has completely broken screen reader accessibility. It is not possible to read or interact with the content in a file.

Opening a file known to have content and selecting everything, then pasting it into another text editor, confirms there is content present, but using the usual keyboard commands for reading text (arrow keys being the most simple), it's as though no content were in the Notepad++ file at all.

Checked with Narrator, Jaws, and NVDA screen readers (all latest versions).

Returning to Notepadd++ 8.2.1 (the last .exe file I had to hand) restores accessibility.

**Comment by alankilborn** [comment]
Can you narrow it down to which release after 8.2.1 and before 8.3.3 broke it?

**Comment by rdipardo** [comment]
> Can you narrow it down to which release after 8.2.1 and before 8.3.3 broke it?

I think I can guess:

- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11133#issuecomment-1030905971
- nvaccess/nvda#13364
- derekriemer/nvda-notepadPlusPlus#32

A better question is what _architecture_ was the 8.3.3 release?
The 64-bit version will crash immediately if you just open a file with NVDA 2021.3.4 running.

**Comment by ggordon-vispero** [comment]
The problem is the result of changing Sci_PositionCR from long to intp. Screen readers use the Scintilla API for retrieving text and other information from the document. Passing in two longs for the min and max of the desired text range no longer works on x64 because you're expecting a 64-bit rather than a 32-bit value for each.

We decide which API to use for text retrieval based on window class, and in this case, that class is the same as all other embeds of Scintilla that still have  Sci_PositionCR defined as long for all platforms.

I realize that reverting this change will once again make it impossible to edit files larger than 2gb, but it will once again allow screen readers to work. As someone who represents the JAWS screen reader, I can say that we're happy to brainstorm possible paths forward to accomodate large files without breaking us. I'm sure the NVDA folks feel similarly.

**Comment by alankilborn** [comment]
@ggordon-vispero 

>I realize that reverting this change will once again make it impossible to edit files larger than 2gb

This isn't going to happen.

If what you say is true, why wouldn't the screen-readers themselves be updated, just like a lot of N++ plugins had to be?

**Comment by lukaszgo1** [comment]
@ggordon-vispero wrote:
> As someone who represents the JAWS screen reader, I can say that we're happy to brainstorm possible paths forward to accomodate large files without breaking us. I'm sure the NVDA folks feel similarly.

For NVDA this is already solved and the fix would be available in NVDA 2022.1 which is currently in beta.
The fix on NVDA side was to use `long` for 32-bit processes and `inpt` for 64-bit processes of Notepad++ version 8.3 or greater. I understand that for JAWS this might not be so easy as you're accessing Scintilla controls in process and probably there is a single DLL which is injected for all Scintilla controls.

**Comment by ggordon-vispero** [comment]
We can do the same thing for JAWS, but this just feels wrong to me. It means that we’re moving from a world where Scintilla has predictable semantics for basic functionality regardless of the app that hosts it, to one where different semantics are used depending upon the app that hosts it and whether or not that app has decided to use 64-bit  values for file positions.  But I fear this argument isn’t falling on sympathetic ears.

**Comment by alankilborn** [comment]
>But I fear this argument isn’t falling on sympathetic ears.

I don't really see how it could.  Time marches on.  Consider some sort of configurability in your tool?

**Comment by xomx** [comment]
Ask Scintilla, why are they still hesitating to do what they [promised](https://www.scintilla.org/ScintillaDoc.html#TextRetrievalAndModification) a long time ago:

"Sci_TextRange and Sci_CharacterRange
These structures are defined to be exactly the same shape as the Win32 TEXTRANGE and CHARRANGE, so that older code that treats Scintilla as a RichEdit will work.

`In a future release the type Sci_PositionCR will be redefined to be 64-bits when Scintilla is built for 64-bits on all platforms`."

**Comment by ggordon-vispero** [comment]
Point taken! JAWS will  properly handle this in it’s April update.

**Comment by rdipardo** [comment]
> Ask Scintilla, why are they still hesitating to do what they [promised](https://www.scintilla.org/ScintillaDoc.html#TextRetrievalAndModification) a long time ago
> 

The [announcement of Scintilla 4.1.6][1] reads in part:

> The major feature of this release is support for files larger than 2 gigabytes in SciTE

The [enabling revision][2] dates from version 4.0.0.

Only thing left for Scintilla to do is update their website.

[1]: https://groups.google.com/g/scintilla-interest/c/4czxAqELLeQ/m/2XzoM5gsBwAJ
[2]: https://sourceforge.net/p/scintilla/code/ci/rel-4-0-0/tree/include/Sci_Position.h#l15

**Comment by rdipardo** [comment]
> Ask Scintilla, why are they still hesitating to do what they [promised](https://www.scintilla.org/ScintillaDoc.html#TextRetrievalAndModification) a long time ago
> 

Until now:

> Since modifying SCI_GETTEXTRANGE is too likely to cause failures, it will be better to define a new 64-bit safe API and gradually migrate to the new API. A new SCI_GETTEXTRANGEFULL API is proposed along with Sci_CharacterRangeFull and Sci_TextRangeFull structs which use Sci_Position (ptrdiff_t) positions.

<https://groups.google.com/g/scintilla-interest/c/mPLwYdC0-FE>

**Comment by rdipardo** [comment]
Using NVDA version 2022.1 may resolve this issue, as reported [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11629#issuecomment-1135434814).

**Comment by LJWatson** [comment]
> Using NVDA version 2022.1 may resolve this issue, 


I appreciate the sentiment, but that's like suggesting someone switches to Windows 11 because macOS is no longer doing what they need. Switching screen readers is not a thing done lightly or easily for most people.

Fortunately @ggordon-vispero and co have resolved the issue in Jaws, so suggest this issue can be closed.
