### ISSUE TITLE
Inverted colors in auto-completion window

### ISSUE THREAD

**Issue by EuropeanDeveloper** [notepad-plus-plus/notepad-plus-plus#11637]
### Description of the Issue

Colors in auto-completion window are inverted.

### Steps to Reproduce the Issue

1. Open a new file.
2. Select some language, e.g. `C`.
3. Start typing.

### Expected Behavior

The background of auto-completion window is white, the focused line is grey.

### Actual Behavior

Colors in auto-completion window are inverted.

### Debug Information

Notepad++ v8.4   (64-bit)
Build time : Apr 20 2022 - 03:31:06
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1645
Current ANSI codepage : 1250
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll 

![screenshot](https://user-images.githubusercontent.com/52759436/166670573-704a4a74-f987-4157-a06c-560eb043ee46.png)

**Comment by Kieruss** [comment]
I can't find where to change these colours, and they're now terrible (black highlight on dark grey, with broken icons) since the update, even with the default theme :(

![notepad++_uCFtEUJIUm](https://user-images.githubusercontent.com/24835155/173212377-aeda1c0e-b9e0-44e1-8356-6bc5b9ac4122.png)
![notepad++_nOd9gCfnOa](https://user-images.githubusercontent.com/24835155/173212379-7107dcd1-8afb-484c-ba72-5a538de415b6.png)
