### ISSUE TITLE
Incorrect mapping for BEGIN and appropriate END keyword

### ISSUE THREAD

**Issue by gal20040** [notepad-plus-plus/notepad-plus-plus#11715]
### Description of the Issue
There is incorrect mapping for BEGIN and appropriate END keyword.

### Steps to Reproduce the Issue
1.Check the following sql code in Notepad++
```
if (1=1)
begin
	select getdate() --1

	if (2=2)
	begin
		select getdate() --2
		
		if (3=3)
		begin
			select getdate() --3
		end
		
		select getdate() --4
	end

	select getdate() --5
end
```
![image](https://user-images.githubusercontent.com/11201733/169882231-50f5743e-41e9-485b-bfbd-1d9867f5835b.png)
2. Try to collapse outer BEGIN-END block by clicking '-' near BEGIN.

### Expected Behavior
All code inside outer BEGIN-END block should be hide:
![image](https://user-images.githubusercontent.com/11201733/169882365-66405f55-a2fc-43b6-8a1c-ba0321408aea.png)
![image](https://user-images.githubusercontent.com/11201733/169882516-f15112ba-e857-4858-a656-d384bde8639e.png)

### Actual Behavior
There is incorrect hiding of code between outer BEGIN and inner END:
![image](https://user-images.githubusercontent.com/11201733/169882569-72f75850-32ab-42ff-818a-d61b5c8ddab0.png)
![image](https://user-images.githubusercontent.com/11201733/169882591-2faaf307-bf74-4b5c-a1de-adb82435b6ec.png)

### Debug Information
Notepad++ v8.4.1   (64-bit)
Build time : May  8 2022 - 19:51:18
Path : C:\apps\npp.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1586
Current ANSI codepage : 1251
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll

**Comment by gal20040** [comment]
Actual correct behaviour in SSMS:
![image](https://user-images.githubusercontent.com/11201733/169882983-945d83ce-3fce-4fc3-b80b-ac6b1e04ea82.png)
![image](https://user-images.githubusercontent.com/11201733/169883029-1ecf64ed-d13e-4f01-8c89-ec9dd60520de.png)

**Comment by rdipardo** [comment]
Please report it to the upstream project as it is their bug: https://github.com/ScintillaOrg/lexilla/issues
Use the image below to better illustrate the issue:

![LexSQL_npp_issue11715](https://user-images.githubusercontent.com/59004801/169903842-c8ab2d8c-bd05-44a0-88e6-94df7eaffd13.png)

**Comment by gal20040** [comment]
Thanks!
Created: https://github.com/ScintillaOrg/lexilla/issues/85

Should I close the current issue?

**Comment by rdipardo** [comment]
> Should I close the current issue?

There are plenty of open issues waiting for upstream patches: <https://github.com/notepad-plus-plus/notepad-plus-plus/issues?q=is%3Aopen+is%3Aissue+label%3A"scintilla+dependent">

I think the convention is to keep them open until Lexilla publishes a patched version.

**Comment by gal20040** [comment]
Hi, @rdipardo!
ScintillaOrg provided some kind of workaround - use semicolon ';' (I'm almost happy with it):
https://github.com/ScintillaOrg/lexilla/issues/85

I'm not sure if ScintillaOrg will fix it.

**Comment by rdipardo** [comment]
Since you're editing T-SQL queries, and older editions don't require semi-colons after statements [^1], there's [a UDL][0] for SQL Server 2008 that may be more suitable:

![T-SQL-MSServer2008r2_bySergeyIvanov](https://user-images.githubusercontent.com/59004801/170106031-8f70aed2-fa9f-4f06-bcce-0f893cbfdafb.gif)

Most Lexilla lexers target a general standard syntax, so the real problem here is how your script is written. If you want the SQL lexer to support (deprecated [^2]) styles of T-SQL, that's a feature request, not a bug.

[^1]: "Although the semicolon is not required for most statements in this version of SQL Server, it will be required in a future version." [Transact-SQL Syntax Conventions](https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms177563(v=sql.105)?redirectedfrom=MSDN#:~:text=Although%20the%20semicolon%20is%20not%20required%20for%20most%20statements%20in%20this%20version%20of%20SQL%20Server%2C%20it%20will%20be%20required%20in%20a%20future%20version.) 

[^2]: <https://docs.microsoft.com/en-us/sql/database-engine/deprecated-database-engine-features-in-sql-server-2016?view=sql-server-ver16#:~:text=End%20Transact%2DSQL%20statements%20with%20a%20semicolon%20(%20%3B%20).>

[0]: https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/UDLs/T-SQL-MSServer2008r2_bySergeyIvanov.xml

**Comment by rdipardo** [comment]
THis can be closed since upstream confirmed it's not a bug: https://github.com/ScintillaOrg/lexilla/issues/85#issuecomment-1137895906

**Comment by gal20040** [comment]
> THis can be closed since upstream confirmed it's not a bug: [ScintillaOrg/lexilla#85 (comment)](https://github.com/ScintillaOrg/lexilla/issues/85#issuecomment-1137895906)

I'm ok with it.
Close it.
