### ISSUE TITLE
[GCC] Debug builds missing

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#11728]
As of commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d6595ad836c6a8c9618631bab38b3f900e01994f we have debug builds in appveyor but no artifacts are pushed

**Comment by ArkadiuszMichalski** [comment]
@donho
It was probably discussed earlier, but debug for MinGW in appveyor is necessary? Takes a bit of space (over 120MB) and extends the build time. Probably for these reasons debug was omitted in appveyor.

I brought it back for testing https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11730 but I don't know if it's needed now. Can be skipped again with lines :
```
matrix:
  exclude:
    - compiler: GCC
      configuration: Debug
```

**Comment by rdipardo** [comment]
@ArkadiuszMichalski,
> It was probably discussed earlier

I did mention it [here](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11701/files) but no one replied. (For some reason GitHub will only show reviews when you're logged in.)

Like I said before:

> It will add ~15 mins. of build time to every Appveyor run.
If someone has to pay for it at month's end, I don't believe supporting MinGW is worth the money.
There's really no good reason to use GCC unless you're compiling GTK widgets.

**Comment by donho** [comment]
122 MB + 139 MB = 261 MB on Appveyor!
Do you guy think it's worth to push the GCC debug binaries?
Among:
1. excluding GCC Debug compiling (skipped lines suggested above) 
2. compiling GCC Debug but not pushing the binaries (current situation) 
3. including GCC Debug binaries

What do you guys suggest?

**Comment by rdipardo** [comment]
It's really a choice between 1. or 3. 
Building *without* pushing the binary is a waste of time, so #11730 is appropriate &#x2014; __*if*__ we commit to debug builds in the first place: ["in for a penny, in for a pound"][0]

[0]: https://www.merriam-webster.com/dictionary/in%20for%20a%20penny,%20in%20for%20a%20pound

**Comment by MarkusBodensee** [comment]
My 2 cents would be: Build time should never be an argument if there is any kind of benefit, like revealing errors with unportable code etc. Same is true for storage space.

Of course, only if there are no additional financial expenses which are not acceptable.

According storage space, is there a mechanism to drop build artifacts after a certain period of time?

**Comment by donho** [comment]
We don't pay for Appveyor due to the nature of this project (Open Source).
Your arguments are legit to me.
Thank you for you suggestions.

**Comment by ozone10** [comment]
If space is issue we can always add flag `-s` to makefile, correct me but debug builds here are mainly used for loading json plugin admin.

And gcc building will show some warnings, which is helpful.

**Comment by rdipardo** [comment]
> And gcc building will show some warnings, which is helpful.

MSVC has a builtin [static analyzer][0], and there's always [cppcheck](http://cppcheck.net). GCC's warnings are only useful if acted on. While some effort [has been made][1] in the past, there are still dozens and dozens more, none of which pose any risk to users because GCC builds are never released for public download.

I think the true reason that MinGW is still supported is what @chcg said in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9139#issuecomment-727257488:

> Apart from what @sasumner already mentioned developers have the chance to build also on linux as the mingw toolchain is also available for linux.
 
I don't really buy that since Linux is __*not*__ an officially supported platform, nor is there any roadmap to make it so, despite the many, many times it's been requested:

- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11392
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11085
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11002
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10770
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10216
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9474
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5162
- ` . . .`


[0]: https://docs.microsoft.com/en-us/cpp/build/reference/analyze-code-analysis?view=msvc-170
[1]: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10038

**Comment by ozone10** [comment]
@rdipardo 
Of course, I am also using clang to analyze and build for testing, but this is more convenient for me, as it is shown in appveyor log.

Most warning are about -Wreorder, some related to code style or behave differently on gcc  which can be easily fixed (-Wpedantic, -Wparentheses, -Wdangling-else, -Wmisleading-indentation, -Wmisleading-indentation, -Wunused-variable, -Wswitch, -Wunknown-pragmas, -Wformat=), some about conversion and comparing (-Wconversion-null, -Wnonnull-compare, -Wchar-subscripts, -Wsign-compare).

But this warning seems interesting -Wclass-memaccess.

There might be other warnings.
