### ISSUE TITLE
Use Same App Language When Updating

### ISSUE THREAD

**Issue by Bonifatius94** [notepad-plus-plus/notepad-plus-plus#11823]
### Description of the Issue
I appreciate the update mechanism a lot. Notepad++'s updates are dummy-proof and don't screw things up.
But one thing is really annoying. The installation setup for updating always suggests the system language
instead of the previously installed app language. I'm living in Germany, but want to use most of my dev tools
in English, so it really annoys me to select the language all the time.

### Steps to Reproduce the Issue
- use e.g. German Windows 10 OS
- install Notepad++ with English language
- once Notepad++ suggests an update -> agree to update
- the Notepad++ installer shows up, suggesting German instead of English although my previously installed Notepad++ was configured to run English

### Expected Behavior
When running the installer for updating the app, use the app language of the previously installed Notepad++ version.

### Actual Behavior
The default system language is selected, no matter what.

**Comment by jalgithub** [comment]
Lol, I just came here to report the same. It always annoys me to no end, and sometimes I don't look too good and click the system language, and oh noez! Notepad++ in Dutch and I can't find anything anymore 🤬.

**Comment by alankilborn** [comment]
@Bonifatius94 

Given that Notepad++ releases average 9 times a year since 2017 (okay, 2021 was an exception with DOUBLE that amount), and thus you are dealing with this once or twice a month, does it really qualify as a big annoyance?  Don't answer that, I'm sure to you it does. :-)

However, I do agree that it would be nice to obtain the _Expected Behavior_ for this.

@jalgithub said:

>oh noez! Notepad++ in Dutch and I can't find anything anymore

If you find yourself in this situation you can start Notepad++ from the command prompt like this:

`notepad++ -Len`

at least for English (because of the `en`).  If you desire a different choice, try the one you want from [HERE](http://4umi.com/web/html/languagecodes.php).

After doing that, navigate the Notepad++ UI to here:

![image](https://user-images.githubusercontent.com/77065706/175049673-d0d8dd13-0eb1-47a3-9832-147954c58e6d.png)

and (important!) RESELECT "English" (or whatever) from the dropdown.  This will cause the change to persist.

After that, next time you can start Notepad++ without the `-L` argument.

**Comment by jalgithub** [comment]
Once or twice a month _for years and years_, yes that's really a _big_ annoyance 😄.

**Comment by alankilborn** [comment]
@jalgithub You could always _permanently_ add `-Len` to your Notepad++ invocation; then it never bothers you again. :-)

**Comment by CennoxX** [comment]
That was already added in 8.4.2 see #10582 / https://github.com/notepad-plus-plus/notepad-plus-plus/commit/054e3d0ae1c95e05c91a6e6616f19272697d1596

**Comment by Bonifatius94** [comment]
> That was already added in 8.4.2 see #10582 / [054e3d0](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/054e3d0ae1c95e05c91a6e6616f19272697d1596)

I'm currently using version 8.4.2 and it still had the undesired behavior. Does your feature work now or not? 😅

**Comment by rimrul** [comment]
> > That was already added in 8.4.2 see #10582 / [054e3d0](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/054e3d0ae1c95e05c91a6e6616f19272697d1596)
> 
> I'm currently using version 8.4.2 and it still had the undesired behavior. Does your feature work now or not? 😅 

Yes. On the next update (assuming you've set your desired language in the installer).
