### ISSUE TITLE
"Save a Copy As..." window title should be "Save a Copy As"

### ISSUE THREAD

**Issue by AndiKiissel** [notepad-plus-plus/notepad-plus-plus#11860]
`File` -> `Save As...` -> window title is "Save As".
`File` -> `Save a Copy As...` -> window title is the same "Save As", which is misleading - what did I _actualy_ select from `File`...?

**Comment by alankilborn** [comment]
At first look, it might seem as simple as inserting some code here https://github.com/notepad-plus-plus/notepad-plus-plus/blob/980cbcccc6a02ba983d425d4f2ed5b8285fc4da0/PowerEditor/src/NppIO.cpp#L1728

The code could be:

```
if (isSaveCopy)
{
    fDlg.setTitle(TEXT("Save a Copy As"));
}
```

but a fix would be a little more complicated than that, because the code shown would cause it to appear in English even when Notepad++ is set to a non-English localization.
