### ISSUE TITLE
Join line (ctrl+j) requires select some part of the last line (not sure if intentional)

### ISSUE THREAD

**Issue by Tipoff4317** [notepad-plus-plus/notepad-plus-plus#11993]
### Description of the Issue

Join line (ctrl+j) requires selecting some part of the last line, i.e., if the cursor is on the last line at the beginning but none of the characters are selected, then the last line doesn't get joined.  Not sure if this is intentional, but some previous versions (haven't tracked down which) didn't have this behavior.

### Steps to Reproduce the Issue

1. first line "abcd", second line "efgh"
2. select first line moving cursor to the beginning of the second, not selecting anything on the second
3. "ctrl+j", or the menu Edit->Line operation->Join lines

### Expected Behavior

Expect the two lines to be joined.

### Actual Behavior

Nothing.

### Debug Information

Notepad++ v8.4.4   (32-bit)
Build time : Jul 15 2022 - 17:56:38
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 874
Plugins : 
    ComparePlugin (2)
    dbgpPlugin (0.0.13.27)
    LocationNavigate (0.4.7.7)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    NppSaveAsAdmin (1.0.211)
    SnippetPlus (1.4)
    XBrackets (1.3)
    XMLTools (2.4.11)

![notepad++ Capture](https://user-images.githubusercontent.com/17734927/183266618-3ab181e0-0a24-4435-a70c-2a6ce6511ba6.JPG)

**Comment by alankilborn** [comment]
>Not sure if this is intentional, but some previous versions (haven't tracked down which) didn't have this behavior.

It is intentional.
And its behavior was changed some time ago.

Some users were disconcerted that selecting complete lines (via click and drag on the line numbers, for ex.) and creating this to join:

![image](https://user-images.githubusercontent.com/77065706/183290676-86bd6bc3-6f33-45a3-93a0-82a9dc22286f.png)

Would result in this:

![image](https://user-images.githubusercontent.com/77065706/183290716-beb72eac-7e1b-4415-8889-74f98e3cb0eb.png)

Instead of the more-intuitive this:

![image](https://user-images.githubusercontent.com/77065706/183290699-38d235ed-8101-4cfe-ac3f-b940c607020c.png)

There were other functions besides join-lines that exhibited this behavior when acting on a selection.
The "upper-level" code was changed so that all such functions worked the new way.

Recommend CLOSURE of this item.

**Comment by Tipoff4317** [comment]
Thanks for explaining in details!
