### ISSUE TITLE
Find all improvement

### ISSUE THREAD

**Issue by jsapp111** [notepad-plus-plus/notepad-plus-plus#12003]
It would be nice to have an option when doing find all to have an option to place all results on the same line in the source file on the same line in the the find results.

### Steps to Reproduce the Issue
1. Open a text file and type "this bad example is bad"
2. Find all for the word "bad"
3. Find results will show two distinct results show bad twice but on the same line from the source file

### Expected Behavior
The number of find results would match the number of lines that the token occurred on

### Actual Behavior
There is a find result for every instance of the token 

### Debug Information
Notepad++ v8.4.4   (32-bit)
Build time : Jul 15 2022 - 17:56:38
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 21H2
OS Build : 22000.795
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by alankilborn** [comment]
>It would be nice to have an option

There IS an option:

![image](https://user-images.githubusercontent.com/77065706/183535047-ee14595f-ec03-4c15-a5c5-6ea1a1d42719.png)

And in 8.4.4 it is turned on by default.

So you will see your expected behavior:

![image](https://user-images.githubusercontent.com/77065706/183535100-04f95064-b2d6-4e3c-bf9f-4bfc30762ae1.png)

Please CLOSE this issue.
