### ISSUE TITLE
[Feature Request] Add 'Change History' to N++ (support provided in Scintilla 5.3.0)

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#12046]
Add in to Notepad++ the "change history" feature, new to Scintilla 5.3.0:
`Added change history which can display document changes (modified, saved, ...) in the margin or in the text.`

Not sure what is needed for this to be realized in Notepad++, but at a minimum I'd suppose letting the user turn the feature on/off.

**Comment by chcg** [comment]
Needs merge of https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12045

**Comment by alankilborn** [comment]
I strongly suggest this feature be defaulted to "on" in Notepad++, so that users know of its existence.
Users would always be able to turn it "off", although IMO only users that aren't "thinking clearly" would do so.

I started out using Notepad++ with the Location Navigate plugin, solely for changed-lines markers, and then later switched to @vinsworldcom 's Changed Lines plugin port.
I consider this feature to be mandatory, and if I hadn't been able to use a plugin for it in the past, I wouldn't be using Notepad++.

**Comment by alankilborn** [comment]
Documentation link for using "change history" in Scintilla:  https://www.scintilla.org/ScintillaDoc.html#ChangeHistory

**Comment by vinsworldcom** [comment]
I'm playing around with this by cloning @chcg 's N++ repo and compiling the `scintilla_530` branch.  I made the change to deconflict the N++ margin symbols:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/08acfe99b8dcfef40c7e7c244fe5c75cab0338b5/PowerEditor/src/ScintillaComponent/ScintillaEditView.h#L116-L119

changed to:

PowerEditor\src\ScintillaComponent\ScintillaEditView.h:
````
116: const int MARK_BOOKMARK = 20;
117: const int MARK_HIDELINESBEGIN = 19;
118: const int MARK_HIDELINESEND = 18;
119: const int MARK_HIDELINESUNDERLINE = 17;
````

and then I have @d0vgan 's [NppExec](https://github.com/d0vgan/nppexec) installed as a plugin for this test version so I can enable and change the feature on the fly.  The NppExec commands required are:

```
SCI_SENDMSG SCI_SETMARGINS 8
SCI_SENDMSG SCI_SETMARGINWIDTHN  7 10
SCI_SENDMSG SCI_SETMARGINMASKN 7 31457280
SCI_SENDMSG 2780 7
```

That creates some extra margins, we use the 7th margin as the one to put the change history in; set the width to 10, set the mask to accommodate the [markers 21 - 24 that Scintilla is using for this feature](https://www.scintilla.org/ScintillaDoc.html#ChangeHistory) and then enable the feature for both markers and in-text indicators.  To use just the margin markers, change the last command to:  `SCI_SENDMSG 2780 3`.

Note you need to run the last command in NppExec every time you open a new N++ buffer / Scintilla edit component - as says the Scintilla docs on this.

![image](https://user-images.githubusercontent.com/9657169/187053222-6700ecc4-697f-4a8a-974a-4745b5a25bbd.png)

I can get the saved and changed markers to show, but not the `SC_MARKNUM_HISTORY_REVERTED_TO_ORIGIN` or `SC_MARKNUM_HISTORY_REVERTED_TO_MODIFIED`, unless the colors are so similar and I may be color blind.

So far, the hide lines and N++ bookmarks seem to be unaffected by my simple change so hopefully they are correctly referenced by name (rather than integer) throughout the code base.  I have not cross checked all the indicators to see if there is any conflict there.

I can see some downstream issues:

+ my [ChangedLines](https://github.com/vinsworldcom/nppChangedLines) plugin uses margins and markers which do conflict, happy to make the required changes
+ [LocationNavigate](https://sourceforge.net/projects/locationnav/) plugin is in  a similar situation as I copied much of ChangedLines from it
+ [PythonScript](https://github.com/bruderstein/PythonScript) and @pryrt "[PerlScript](https://metacpan.org/pod/Win32::Mechanize::NotepadPlusPlus)" plugins both enumerate markers so they _may_ need to update if they have constants for the Notepad++ bookmark and hide lines markers that I changed above
+ @pnedev [Compare / ComparePlus](https://github.com/pnedev/comparePlus) plugin uses markers and margins which _may_ conflict if this is implemented

Important to note **NOTHING** has changed yet, but just tagging those folks I see that may have some downstream impact so they are aware.  Overall, I'm so looking forward to getting this into Notepad++ through "native" Scintilla functionality rather than through a plugin.

Cheers.

**Comment by alankilborn** [comment]
@vinsworldcom said:

>I have not cross checked all the indicators to see if there is any conflict there.

Scintilla uses indicators 36-43 for the change history feature.  There is no conflict with N++ usage as the highest indicator number used by N++ is 31 (used by the _Mark_ feature that colors text background red).

**Comment by alankilborn** [comment]
@vinsworldcom said:

>PythonScript plugins enumerate markers so they may need to update if they have constants for the Notepad++ bookmark and hide lines markers that I changed above

PS doesn't directly deal with these markers in any way, so... no conflict there.

**Comment by alankilborn** [comment]
@vinsworldcom said:

>my [ChangedLines](https://github.com/vinsworldcom/nppChangedLines) plugin uses margins and markers which do conflict, happy to make the required changes

Your "required changes" might be deleting all remnants of an extinct plugin.  :-)
Hmm, well, ChangedLines does give some additional functionality (which I don't use but maybe some users do).

**Comment by alankilborn** [comment]
>const int MARK_HIDELINESUNDERLINE = 21;

As of Scintilla 5, there is a better way to do this than to dedicate a marker to it.
Basically, the drawing of the green line across the screen is best left to Scintilla itself, saving N++'s wasted use of a marker, and code complexity to implement it.

Here's the line to which I refer (shown as currently implemented in N++):

![image](https://user-images.githubusercontent.com/77065706/187207373-fff2f8e2-d400-415d-b886-4042c64fc96d.png)

To tell Scintilla 5 to handle this line, one uses [SCI_SETELEMENTCOLOUR](https://www.scintilla.org/ScintillaDoc.html#SCI_SETELEMENTCOLOUR) and the _element_ argument of SC_ELEMENT_HIDDEN_LINE.

This is off-topic to the current issue, but I don't really know what to do with this information.  I don't know that it makes a good independent "issue" as it doesn't really improve N++ functionality, it just simplifies the code a bit.  It's a good idea to offload the handling to Scintilla, but...  @donho : thoughts?

**Comment by donho** [comment]
@alankilborn 
> As of Scintilla 5, there is a better way to do this than to dedicate a marker to it.
> Basically, the drawing of the green line across the screen is best left to Scintilla itself, saving N++'s wasted use of a marker, and code complexity to implement it.

If Scintilla has built-in function to hide lines with markers, yes it would be better. But I think there's no such feature (of whole package) in Scintilla. Please let me know if I'm wrong.

>  I don't know that it makes a good independent "issue" as it doesn't really improve N++ functionality, it just simplifies the code a bit. It's a good idea to offload the handling to Scintilla.

I'm always for simplifying the code of Notepad++ and reuse the features done in Scintilla - you are welcome to do your PR and the PR will be accepted if it does simplify the code.

**Comment by vinsworldcom** [comment]
@donho I _think_ (and @alankilborn correct me if I'm wrong) Scintilla essentially supplies the "line" for which Notepad++ currently dedicates a marker.  Thus we could save one marker from the renumbering:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/b627d6a4554b095487d41f11765ab106d1884c9d/PowerEditor/src/ScintillaComponent/ScintillaEditView.h#L116-L119

no longer needing marker 21.

Cheers.

**Comment by dinkumoil** [comment]
@vinsworldcom 

I have written a Npp plugin called _CustomLineNumbers_, it's part of the official plugin list. This plugin allows users to enable line numbers that are zero-based and/or displayed as hex numbers.

To accomplish its task, the plugin makes the standard line numbers margin invisible and creates a new margin to display its self-generated line numbers.

So I would like to ask you if you would test the plugin with your modified version of Npp to see if there are any problems related to the new change history margin.

**Comment by vinsworldcom** [comment]
@dinkumoil there doesn't seem to be any conflict with the margins and I don't think you're using markers or indicators in the plugin so that should be OK too.  I did see some strange behavior though with line numbering when using N++ hide lines feature:

![image](https://user-images.githubusercontent.com/9657169/187913214-c1439079-1e3f-4ae3-b52c-cf249ec20ee2.png)

notice the last few line numbers repeat.  I cannot find a way to reliably duplicate this issue though.

It's worth noting I can duplicate the behavior in my regular N++ 8.4.5 RC1 portable (this does not include the Scintilla change history feature):

![image](https://user-images.githubusercontent.com/9657169/187913995-d312f2bd-f59c-492c-b65a-02814aa053ac.png)


Cheers.

**Comment by dinkumoil** [comment]
@vinsworldcom 

Many thanks for testing my plugin!

I'm aware of the code folding related issue, it also occurs when using Npp's line hiding feature (`(menu) View -> Hide lines`). It was introduced after an optimization to prevent the plugin from massively decrease scrolling performance.

Since I don't have any idea for a quick fix and I'm currently not able to do time-consuming research how to solve the problem or work on my plugins in general, I will leave it like this for now, sorry. So, the only "solution" is not to use code folding or line hiding as long as my plugin is activated.

**Comment by vinsworldcom** [comment]
I'm thinking the UI is pretty simple.  A check box for markers, a checkbox for indicators; if both are unchecked, the feature is disabled.

Something like this mock-up:

![image](https://user-images.githubusercontent.com/9657169/188225869-22bd7269-2862-496f-b84d-4ad422e5a978.png)

Cheers.

**Comment by alankilborn** [comment]
>check box for markers, a checkbox for indicators

Does it really need the Scintilla-like naming?
Users that aren't advanced may not know "markers" making the inclusion of that term not-helpful to them
Same for "indicators"

I might lean towards:

* Via symbols in margin
* Via text background colouring

**Comment by vinsworldcom** [comment]
For those of us on the bleeding edge that want to test this out, after grabbing commit 1646ea6, I added a PythonScript to enable this feature.  You **WILL** need _another_ PythonScript to make `editor1.hwnd` and `editor2.hwnd` available to this script.

```Python
import ctypes
from ctypes.wintypes import HWND, LPARAM, UINT, WPARAM
from enum import Enum

from Npp import editor1, editor2, NOTIFICATION

from NppPyS.StdMod import StdMod

SendMessage          = ctypes.windll.user32.SendMessageW
LRESULT              = LPARAM
SendMessage.argtypes = [HWND, UINT, WPARAM, LPARAM]
SendMessage.restype  = LRESULT

SCI_SETCHANGEHISTORY = 2780
SCI_GETCHANGEHISTORY = 2781

class SC_CHANGE_HISTORY(Enum):
    DISABLED   = 0
    ENABLED    = 1
    MARKERS    = 2
    INDICATORS = 4


class SC_MARKNUM_HISTORY(Enum):
    REVERTED_TO_ORIGIN   = 21
    SAVED                = 22
    MODIFIED             = 23
    REVERTED_TO_MODIFIED = 24


class ChangeHistory():
    def __init__(self):
        self._ENABLED = False
        self._nppCallbacks = {
            self._on_buffer_activated:
            [NOTIFICATION.BUFFERACTIVATED, NOTIFICATION.LANGCHANGED]
        }
        self.MARGIN     = 7
        self.WIDTH      = 10
        self._mask      = 0
        for mark in SC_MARKNUM_HISTORY:
            self._mask += (1 << mark.value)
        self.CHFLAGS    = SC_CHANGE_HISTORY.ENABLED.value | SC_CHANGE_HISTORY.MARKERS.value

    def start(self):
        """Start the ChangeHistory service"""
        for cb in self._nppCallbacks:
            notepad.callback(cb, self._nppCallbacks[cb])
        self._ENABLED = True
        self._on_buffer_activated([])

    def status(self, all=False):
        """Status of the service"""
        if self.__dict__['_ENABLED']:
            print("ENABLED")
        else:
            print("DIS-abled")
        for item in sorted(self.__dict__):
            if all or not item.startswith("_"):
                print("{0:<25} : {1}".format(item, self.__dict__[item]))

    def stop(self):
        """Stop the service"""
        for cb in self._nppCallbacks:
            notepad.clearCallbacks(cb)
        for cb in self._edCallbacks:
            editor.clearCallbacks(cb)
        self._ENABLED = False

    def _on_buffer_activated(self, args):

        for ed in editor1, editor2:
            ed.setMargins(self.MARGIN + 1)
            ed.setMarginWidthN(self.MARGIN, self.WIDTH)
            ed.setMarginMaskN(self.MARGIN, self._mask)

        self.setChangeHistory(self.CHFLAGS)

    def setChangeHistory(self, chflags = SC_CHANGE_HISTORY.DISABLED.value):
        for ed in editor1, editor2:
            SendMessage(ed.hwnd, SCI_SETCHANGEHISTORY, chflags, 0)

    def getChangeHistory(self):
        ch1 = SendMessage(editor1.hwnd, SCI_GETCHANGEHISTORY, 0, 0)
        ch2 = SendMessage(editor2.hwnd, SCI_GETCHANGEHISTORY, 0, 0)
        if ch1 != ch2:
            return (ch1, ch2)
        else:
            return ch1


if __name__ == '__main__':
    ch = ChangeHistory()
    ch.start()
```

Called in my 'startup.py' with:

```Python
# Change History
from ChangeHistory import ChangeHistory
ch = ChangeHistory()
ch.start()
```

and then from the PythonScript console, you can change some stuff with:

`ch.status()`, `ch.CHFLAGS`, etc...

Cheers.

**Comment by ArkadiuszMichalski** [comment]
Implemented by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/fc32fbdcce371bb669c9361d62c959b1b61e33f0.

**Comment by florom** [comment]
Hi @vinsworldcom @alankilborn ,

How do I turn this off? 
there is no setting chnage History in Notepad++ Preferences Editing or General Tab.

IMO the Icon Save is sufficient to determine of the document is fully saved or not.
I do not need a line specific view which is new or not.
I just find it annoying and it uses up space for no additional info nobody needs. 

Thank you.

![image](https://user-images.githubusercontent.com/32240626/203007286-e899a8ce-5a96-42c4-995c-1efb093c7ee5.png)

**Comment by florom** [comment]
@alankilborn  Thanks.
