### ISSUE TITLE
Style Configurator: Missing Options

### ISSUE THREAD

**Issue by hnvy** [notepad-plus-plus/notepad-plus-plus#12066]
### Description of the Issue
Hello all,

Here are some typos/inconsistencies which I found in the various Notepad++ themes. I am more than happy to fix them all, and send in a pull request.
I appreciate all of your effort.

Kind regards,

HR

### Steps to Reproduce the Issue
This affects all of the themes:
  - [ ] C: change "TYPEWORD" to "TYPE WORD" to make it more consistent with C++ and C#
  - [ ] Python: `keywordClass="instre2"` is missing from the XML, and hence causes it to be missing from the Style Configurator menu. To fix this, navigate to the `themes/` directory, and add something like this `<WordsStyle name="KEYWORDS 2" styleID="14" fgColor="839496" bgColor="002B36" fontName="" fontStyle="0" fontSize="" keywordClass="instre2" />` (this is for the Solarized theme). This line needs to be added under `<LexerType name="python" desc="Python" ext="">` in each of themes. You can probably add the exact same line as the above (well, you may need to change `styleID`, `fgColor`, and `bgColor`).

### Expected Behavior
- I expected the Style Configurator to allow me to edit the style of second set of Python keywords.

### Actual Behavior
- As the above is missing, I am not able to edit the style of second set of Python keywords through the Style Configurator menu.

### Debug Information
As you can see, after I have edited the `Solarized.xml` file to include the line above, I was able to access the style configurations.
![image](https://user-images.githubusercontent.com/84394475/187698797-85068429-0f8f-4189-a1cf-2c57cd4839e7.png)

**Comment by alankilborn** [comment]
I say "go for it" and make these changes.  Note that I'm not an "official" Notepad++ person, just a helper-outer.

**Comment by vinsworldcom** [comment]
@hnvy You did not provide your debug information.  I have Notepad++ 8.4.3:

```
Notepad++ v8.4.3   (64-bit)
Build time : Jul 12 2022 - 17:11:36
Path : C:\Users\mvincent\Downloads\npp\notepad++.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.1889
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
```

and do not have this issue.

![image](https://user-images.githubusercontent.com/9657169/187720634-7e20ec17-8a7d-4f5f-8641-735507fb78ed.png)

Note, they are called `BUILTINS`, not `KEYWORD 2` and you'll see them in the 'stylers.model.xml' file:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/27e489623cf6e6bc9104723d3eecbab6fa438734/PowerEditor/src/stylers.model.xml#L971

If your issue is specifically related to the 'solarized.xml' theme, then yes, themes are **_not_** maintained by the developer so it is probably wildly out of date with Notepad++ language updates.  You won't only find missing keywords, but some languages will be entirely missing as well as many of the categories of each language being not current.

I went through 'obsidian.xml' and updated most languages and the keyword category definitions based on the latest 'stylers.model.xml' but with colors that match the 'obsidian.xml' theme.  It is hard work, but if you're up for it, you could updated 'solarized' and then issue a PR which may be accepted.

Cheers.

**Comment by hnvy** [comment]
Thank you for your reply.

My apologies, I did not think that the debug information was needed here. Here they are:
```
Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 21H1
OS Build : 19043.1889
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.6)
```

> I have Notepad++ 8.4.3 and do not have this issue.

I think it's specific to a handful of old themes, rather than `stylers.xml` (due to the reasons you've neatly explained).

> Note, they are called BUILTINS, not KEYWORD 2 and you'll see them in the 'stylers.model.xml' file

Yes, I have realised this shortly after posting this issue :)

> If your issue is specifically related to the 'solarized.xml' theme, then yes, themes are not maintained by the developer so it is probably wildly out of date with Notepad++ language updates. You won't only find missing keywords, but some languages will be entirely missing as well as many of the categories of each language being not current.

Hmmm, well, I have fixed all of them. I have also fixed the "TYPEWORD" typo. Shall I just make a pull request?



Kind regards,


Harvey R.

**Comment by vinsworldcom** [comment]
@hnvy I think yes, you should definitely make a pull request with your theme update.  You'll need to cite this issue in the PR with the "Fix #xxx" text and it will automatically test build and link this issue.  That would be the best chance of it getting accepted.

Note I'm not a developer per se, but have contributed through some pull requests and I think a PR that fixes a single theme file and makes it up-to-date would have a pretty good chance of getting merged.

Thank you for supporting Notepad++ themes!

Cheers.

**Comment by hnvy** [comment]
Thank you for the pointers @vinsworldcom, much appreciated!

This is the least I could do in return.

Enjoy the rest of your day!


Kind regards,

HR
