### ISSUE TITLE
First UpperCase of Each Word

### ISSUE THREAD

**Issue by Dvorak-Stepan** [notepad-plus-plus/notepad-plus-plus#12103]
### **Please add a function:**
**Right Mouse Button** on **Text** -> First UpperCase of Each Word

![First Letter UpperCase ](https://user-images.githubusercontent.com/23320581/188469080-238429ee-4ec8-4da4-a2b3-8c4df539fb03.png)

**Comment by alankilborn** [comment]
What you really want is the _Proper Case_ option from this part of the menus:

![image](https://user-images.githubusercontent.com/77065706/188477612-a04804e9-9094-4d86-bec4-f2fa3db69f9a.png)

Since you seem to want it on the right-click context menu, you need to configure your own specific context menu to have it.  See the user manual on how to do this, [HERE](https://npp-user-manual.org/docs/config-files/#:~:text=a%20given%20setting.-,The%20context%20menu,-%3A%20contextMenu.xml).

Please CLOSE this issue.
