### ISSUE TITLE
Add customization of color for individual tab

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#12156]
Now we have 5 predefined colors. It would be nice to be able to change them via the `Style Configurator` dialog. Something similar what we have for `Mark Style`.

![image](https://user-images.githubusercontent.com/2730894/189635241-068c0d50-b57b-467f-bfd2-f5657387eea2.png)

![image](https://user-images.githubusercontent.com/2730894/189635142-1e0c8eba-ced7-4be9-bf31-febac82a898d.png)

**Comment by Teasy** [comment]
the colors appear to be hardcoded in **NppDarkMode.cpp**:
`	static constexpr IndividualTabColours individualTabHuesFor_Dark  { { HLSColour{37, 60, 60}, HLSColour{70, 60, 60}, HLSColour{144, 70, 60}, HLSColour{255, 60, 60}, HLSColour{195, 60, 60} } };`
`	static constexpr IndividualTabColours individualTabHues          { { HLSColour{37, 210, 150}, HLSColour{70, 210, 150}, HLSColour{144, 210, 150}, HLSColour{255, 210, 150}, HLSColour{195, 210, 150}}};`

on one computer (windows 7), color 1 and 4 are particularly indistinguishable;
both in light mode:
![Screen Shot 01-23-24 at 05 25 AM](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/1706625/6207a75d-8de6-4075-9c4f-9a14b4aa2b33)
and in dark mode:
![Screen Shot 01-23-24 at 04 59 AM](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/1706625/b4c5f2e8-c57f-42f6-a326-fc8e9725deef)
(although the definitions in the code seem to indicate otherwise?)

and on another computer (windows 10), color 4 and 5 are particularly indistinguishable:
in light mode:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/1706625/85b1ec55-7b36-458e-a2d1-5033c60c5506)
but not so bad in dark mode:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/1706625/a2564775-601b-43c0-b8f7-536efda5c789)

i'm guessing the screenshot above from [ArkadiuszMichalski](https://github.com/ArkadiuszMichalski) was from an older version of NotePad++, which had a different (better!) set of colors? :)

**Comment by pit181** [comment]
This request was marked as done,
How do i use this feature?

**Comment by ArkadiuszMichalski** [comment]
It will be available in the next release.

**Comment by pit181** [comment]
@ArkadiuszMichalski i downloaded the newest version, still cannot see option,
are you sure it was released?

**Comment by alankilborn** [comment]
@pit181

Go https://npp-user-manual.org/docs/user-interface/#tabs then search for `color`

**Comment by dictovod** [comment]
I have started the development of a new Notepad++ plugin that will automatically change the color of tabs when files are modified by external programs. This plugin will also support features like sorting tabs by the most recently modified files to improve workflow visibility and efficiency. Looking forward to sharing updates as development progresses!

**Comment by alankilborn** [comment]
@dictovod An additional place to share updates is: https://community.notepad-plus-plus.org/
