### ISSUE TITLE
[suggestion] Add "Find Previous" to FIND (remove checkbox "Backward direction")

### ISSUE THREAD

**Issue by dbareis** [notepad-plus-plus/notepad-plus-plus#12175]
It is currently too annoying the odd times when you want to go back (you have decided you have gone one or two matches too far).
I would like to see a find next & find prev button.  It is also too easy to accidently leave the checkbox enabled and have all your searches fail....

I'm unsure how best replace mode would change or if it needs to).

**Comment by alankilborn** [comment]
>I would like to see a find next & find prev button.

It is unknown which version you are using, because you ignored the request to provide that in the "issue" template...

However, in any relatively recent Notepad++ version (8.4.5 shown below), do the following:

Tick this box:

![image](https://user-images.githubusercontent.com/77065706/190392861-470273ea-8c4c-4a97-bd5d-c3c0fc67d25a.png)

To achieve a find-toward-beginning and a find-toward-end button:

![image](https://user-images.githubusercontent.com/77065706/190392996-b188e082-7e9a-4f5d-9091-ccd12bfb5a85.png)

Please CLOSE this issue.

**Comment by dbareis** [comment]
Thanks @alankilborn 

I was using the latest version v8.4.5 (64 bit) but it never occurred to me what the checkbox was for, I have to wonder about the requirements for needing an on the fly change what should be a once off setting change.

**Comment by alankilborn** [comment]
>I have to wonder about the requirements for needing an on the fly change what should be a once off setting change.

Indeed, and agreed.

>and it doesn't remove or grey out the "backward direction" button

That remains as it influences the behavior of Enter and Shift+Enter when those keys are used from the _Find_ window to find-next.
