### ISSUE TITLE
Big file issue: red highlights curly braces { } doesn't show up after update v8.4.6

### ISSUE THREAD

**Issue by lmao04** [notepad-plus-plus/notepad-plus-plus#12260]
### Description of the Issue
Last month August 2022, I could still see the curly braces/brackets/parentheses highlighted in red color. Which greatly helped me in my Crusader Kings save files modification. However, those braces were no longer highlighted in red color whenever I clicked around the braces. I tried looking in other unofficial forums for help and fixes but was unsuccessful. I also tried clean uninstall and reinstall Notepad++. It only worked the first time I open, and unfortunately stopped highlighting again during the next usage.

### Steps to Reproduce the Issue
1. Opening any worded or coded files containing curly braces commands, such as _always = { yes }_, and click at the curly braces.
2. It doesn't highlight in red like it used to, like how it always highlighted in the past years.

### Expected Behavior
Just like the default settings in **Style Configurator --> Global Styles --> Brace highlight style**. The curly braces were supposed to highlight in red color, sometimes highlighting the dotted lines that's connecting the opening brace.

### Actual Behavior
Curly braces won't highlight in red or any color that I customized anymore. I already attempted every option in **Brace highlight style**. No curly braces were highlighted at all.

### Debug Information
Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\James\Documents\Paradox Interactive\Crusader Kings III\save games\Blemmyia2.ck3"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 21H2
OS Build : 19044.2006
Current ANSI codepage : 932
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by alankilborn** [comment]
Seems to work for me, if I'm understanding your meaning:

![image](https://user-images.githubusercontent.com/77065706/193108779-4b9f8ce8-12ea-4f42-af3e-14d8d8daec13.png)

![image](https://user-images.githubusercontent.com/77065706/193108948-65de3e50-2fc5-468d-9a0a-14226702b872.png)

>sometimes highlighting the dotted lines that's connecting the opening brace.

Not sure at all what that means.

**Comment by lmao04** [comment]
Hi alankilborn,
That's what I'd see last month August 2022. But recently not anymore. It'll look like these screenshots below.

> > sometimes highlighting the dotted lines that's connecting the opening brace.
> 
> Not sure at all what that means.
![chaoji](https://user-images.githubusercontent.com/114689034/193110739-13e37f19-6c3b-4d42-b5dc-075a3d5261ef.png)
It's the grey small dotted vertical lines before each command. That would be highlighted in red too, to make it easier to navigate extremely long codes and commands.

Here is another screenshot showing my Brace highlight style settings.
![chaoji2](https://user-images.githubusercontent.com/114689034/193111303-509a6f68-3236-4a0b-a304-da23d83cf569.png)

**Comment by ArkadiuszMichalski** [comment]
@lmao04 Maybe you use file bigger than 200MB? If yes then this matching brackets is automatically turned off.

@donho Some control of what should be disabled / enabled for large files (and from what size) would be handy. In some cases (like simple lexers) some mechanisms may work better for bigger limits (or slowdown may be acceptable to users).

**Comment by alankilborn** [comment]
>Some control of what should be disabled / enabled for large files (and from what size) would be handy. In some cases (like simple lexers) some mechanisms may work acceptable for bigger limits (or slowdown may be acceptable to users).

Agreed; I had forgotten about this.  
Is there a list somewhere of the threshold size and what gets turned off?

**Comment by ArkadiuszMichalski** [comment]
Read above quote (comes from linked commit).

**Comment by lmao04** [comment]
Thank you for the insight!

> While loading files over more 200MB, they are all considered as Normal text files, that improve loading speed (for example for huge XML or SQL file).
> Also, the feature as braces match, smart highlightingg, tag match and URL colorization are disabled for not penalizing the editing performance.

If large file size disables those features, is there any custom setting or plugin that enables them back with a large file size? I'm running a beast PC that can definitely handle large files with braces match and smart highlighting on. Thank you once again! 😃

**Comment by rdipardo** [comment]
> I'm running a beast PC that can definitely handle large files with braces match and smart highlighting on.

Hardware specs have nothing to do with it. The problem is code highlighting (and *especially* code folding) are memory intensive operations, and Notepad++ is not optimized to handle them at scale without crashing or freezing up [^1]. See, for example, #11075, #10967, #8747, and #5267.

[^1]: Some optimizations that could help are listed at https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10193#issuecomment-1114819246

**Comment by alankilborn** [comment]
>>Is there a list somewhere of the threshold size and what gets turned off?

>Read above quote (comes from linked commit).

Well, I was hinting that there maybe should be a list and details for users somewhere.
I guess I should have been more explicit in the asking; sorry.
I had a look at the user manual and didn't see anything; could have missed it.

**Comment by ArkadiuszMichalski** [comment]
Unfortunately, this is not describe in the manual yet. But it is also not known if and what control could be made available https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11389#issuecomment-1068006048.
Maybe a solution is a new Performance tab in Preferences, where we can turn off/off [ ] each option separately for large files. In addition, the limit size could be given  common to all or separately for each option.

Now these disabling are permanent and cannot be enabled (even manually). One exception is switching language from menu but I don't know if it has any effect (some lexers have own limits). Now it's too restrictive because some of these options may work at an acceptable level (for example in a Plain text file a little over than this 200MB limit).

**Comment by alankilborn** [comment]
>this is not describe in the manual yet

I guess a new item for the inbox of @pryrt

**Comment by ArkadiuszMichalski** [comment]
Btw, new Change history is always enabled (although it could also be controlled for large files):
https://www.scintilla.org/ScintillaDoc.html#ChangeHistory
>This feature uses a moderate amount of memory proportional to the amount of modifications made. On huge documents, this could be significant so could be disabled when it would cause excessive memory use.

**Comment by donho** [comment]
> Maybe a solution is a new Performance tab in Preferences, where we can turn off/off [ ] each option separately for large files. In addition, the limit size could be given common to all or separately for each option.

@ArkadiuszMichalski Which existing items could be in the  Preferences tab ?

**Comment by ArkadiuszMichalski** [comment]
I will not be original if I say everyone? I have already seen requests for lexer, braces match and smart highlighting. Probably there will be requests for the others, it's a matter of time.  Especially when they might work in a larger Plain text file. We cannot predict all cases, because everyone works differently, so the widest possible configuration of this lock would be recommended (by default, all restrictions can still be turned on).

For examle:
```
Size limit for all: [200]

[x] lexer 
[ ] smart highlighting
[x] braces match
...

```

We can even put a limit on an individual:
```
[x] lexer                        [100]
[ ] smart highlighting           [200]
[x] braces match                 [500]
...
````

But that's a decision on how to control it in detail.
