### ISSUE TITLE
N++ 8.4.6 "Print black on white" vs "Display Change History"

### ISSUE THREAD

**Issue by shawnkhall** [notepad-plus-plus/notepad-plus-plus#12281]
### Description of the Issue
The new "Display Change History" does not play well when printing with the "Print black on white" option. Instead of black on white, as expected, it prints black on a solid orange page for new documents. 

### Steps to Reproduce the Issue

1. Settings, Print, [x] Black on white.
2. Settings, Margin/Border/Edge, [x] Display Change History.
3. File, New.
4. Type something.
5. File, Print, Print. 
6. Horror as you view the printed page.

### Expected Behavior
Print black text only on a normal white page.

### Actual Behavior
Printed black text on a full wall of orange ink. (photo below)

### Debug Information
Notepad++ v8.4.6   (32-bit)
Build time : Sep 25 2022 - 19:55:26
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 21H2
OS Build : 19044.2006
Current ANSI codepage : 1252
Plugins : 
    ElasticTabstops (1.3.1)
    Explorer (1.9.4)
    GitSCM (1.4.4.2)
    mimeTools (2.8)
    NppConverter (4.4)
    nppcrypt (1.0.1.6)
    NppExport (0.4)
    NppFavorites (1.0.0.1)
    NppHasher (1)
    NPPJSONViewer (1.40)
    NppQrCode32 (0.0.0.1)
    PoorMansTSqlFormatterNppPlugin (1.6.13.31502)
    pork2sausage (2.2)
    _CustomizeToolbar (5.3)

![IMG_20221003_121901291](https://user-images.githubusercontent.com/6037167/193660865-3cf60c52-b4df-455e-a370-7f69875de165.jpg)

**Comment by alankilborn** [comment]
I believe it is a known issue, with Scintilla.
See similar: https://community.notepad-plus-plus.org/post/80213

**Comment by alankilborn** [comment]
Possibly similar:  https://community.notepad-plus-plus.org/post/80273

**Comment by alankilborn** [comment]
>Type something.

This might be a little misleading, because the screenshot contains 132 lines of "something".  I'd say this data was pasted, not typed.  But as all these lines are "new", they would normally be changed-marked with orange.

What appears to be happening is that Scintilla is applying the change history background mode when printing.  Notepad++'s intention (at least when just editing, not printing) is to not use background mode but only to use margin mode.

Perhaps this is Scintilla's default, and it works this way unless some Scintilla setting is set to tell it NOT to do this?  If Scintilla doesn't have such a setting, I would call this a Scintilla bug of omission.

If Notepad++ merely isn't programming a Scintilla setting, then the bug of omission is Notepad++'s.  :-)

**Comment by shawnkhall** [comment]
> > Type something.
> 
> This might be a little misleading, because the screenshot contains 132 lines of "something".

No, the steps are snarky but not misleading at all. If it helps, here's a print where I wasted more colored ink to demonstrate with the word "something" just for you. 

![npp-something-2022-10-04_13-10-21](https://user-images.githubusercontent.com/6037167/193916648-19e75cd6-15b5-442c-a3ca-500fd5ab94d7.png)

![npp-something-IMG_20221004_130243388](https://user-images.githubusercontent.com/6037167/193915338-1a7816bf-6e2b-497e-816f-6b63ec41df36.jpg)

Whether the source of the issue is new behavior in Scintilla or the new feature in N++ or a plugin that uses a hardcoded value in place of a constant, the bottom line is that it's the N++ setting `Print black on white` is not being observed. Maybe, like you, I'm just being too literal and I just wasn't aware N++ was trying to push "orange is the new black."

**Comment by alankilborn** [comment]
You don't have to waste ink.  Just print to a PDF-printer.  Same effect when the PDF is viewed.

My main point was that the screenshot made me jump the gun and assume that the bug was that everything, all the time, would print with an orange background.  Sure, my bad, but when someone says "type something" as a repro step and then shows 132 lines of orange-backgrounded text, it's a head-scratcher (again, maybe just for dense me).

Note that if the 132 lines of data is saved to a file, and then subsequently printed, it will print with a green background.  (Don't take "print" too literal; I have never actually printed anything onto paper from Notepad++)

I did NOT take _something_ literally, although the actual word "something" is more credible in the original scenario than typing 132 lines of new data.

I don't think it has to do with _Print black on white_.

I did take a look at the Scintilla documentation on Change History and there's nothing about configuration for printing.  So either it isn't documented, or the control just isn't there.  

It's a problem; a workaround technique has been [PROPOSED](https://community.notepad-plus-plus.org/post/80277).

**Comment by rdipardo** [comment]
> I believe it is a known issue, with Scintilla.

https://sourceforge.net/p/scintilla/bugs/2358

**Comment by Intrepid-MR** [comment]
Same problem. All documents printing with an orange background (gray with a B/W printer).

**Comment by alankilborn** [comment]
Fixed in 8.4.7.
Change History FAQ is [HERE](https://community.notepad-plus-plus.org/topic/23616/faq-desk-new-change-history-feature).
