### ISSUE TITLE
Impossible to open Huge file (3.6 GB for example)

### ISSUE THREAD

**Issue by FabienPoirierPrincipia** [notepad-plus-plus/notepad-plus-plus#12298]
### Description of the Issue
When trying to open a huge file, there is an error message telling that it could not be done.

### Expected Behavior
Many text file editors can open such files, even if they are too large to fit in process memory. It could be nice to read the filesize of the file first, then if too big, to switch to a kind of huge file mode which does not load the entire file but just a "window" of several thousands of lines before and after the current point and load only this part in memory.

It could be much better if the user has a clear information/view of this mode, and some way to move quicky to a specified line or part of the file.
If there is a background thread that read the file and keep track of an array of, as an example, each line number each 10k, and the according file cursor position, it could be quick enough to retrieve a line number of a part of the file from this array by jumping directly to the correct file position. The array could be each 10k line, or be fixed size (like 100 for any file) and get the line number of fixed parts of the file (which work whatever the size and number of lines of the file).

**Comment by xomx** [comment]
@FabienPoirierPrincipia 

> When trying to open a huge file, there is an error message telling that it could not be done.

I can open even bigger files in my 64-bit N++ (my largest one was around 6 GB).

Do you use a 32-bit N++?
Do you use a N++ older that the v8.3?
(that is why you should follow the N++ issue template and put here at least your N++ debug-info...)

> a kind of huge file mode which does not load the entire file but just a "window" of several thousands of lines before and after the current point and load only this part in memory.

This is currently not possible due to the N++ "in-memory-whole-file" design. It can be rewritten to e.g. [file-mapping](https://learn.microsoft.com/en-us/windows/win32/memory/file-mapping) for sure, but such change would not be possible without HUGE changes in both the code and the design of the whole application (and also do not forget that such change possibly influences some N++ plugins). So anybody who is willing to contribute such feature should discuss thoroughly his/her ideas and possible solutions with the N++ author first.

**Comment by FabienPoirierPrincipia** [comment]
Hi sorry, in fact yes it is a 32 bits version 8.4.5.
Will try using 64 bits version. I am upgrading 32b versions since years....

**Comment by ArkadiuszMichalski** [comment]
Such a large file for 32-bit Notepad ++ may be too large. Use the 64-bit version (even portable).
