### ISSUE TITLE
Compare Plugin issue when two views are present

### ISSUE THREAD

**Issue by kapilvpatel** [notepad-plus-plus/notepad-plus-plus#12354]
### Description of the Issue

Compare Plugin causes issue when two views are present. It does not consider the last two active tabs of the same view for the comparison.

### Steps to Reproduce the Issue

1. 
2. 
3. 

### Expected Behavior

Ideally last two active tabs of the current view should be considered for the comparison by the compare plugin but it is not the case.

### Debug Information

Compare plugin v2.0.2
Notepad++ v8.4.6 64 bit

**Comment by Yaron10** [comment]
@kapilvpatel,

This is the expected behavior.
You can achieve your Compare by using "Set as First to Compare".

If you want to continue this discussion, please close this issue and open a new one in:
https://github.com/pnedev/comparePlus.

You can upgrade to the much-improved ComparePlus.
https://community.notepad-plus-plus.org/topic/23434/new-plugin-compareplus-v1-0-0.

**Comment by ArkadiuszMichalski** [comment]
Such asking you should report to plugin author.
