### ISSUE TITLE
When saving in Korean file name in Save As, the file name is saved differently than intended.

### ISSUE THREAD

**Issue by lunamoth** [notepad-plus-plus/notepad-plus-plus#12366]
### Description of the Issue
When saving in Korean file name in Save As, the file name is saved differently than intended.

### Steps to Reproduce the Issue
1. Save As
2. Write "한글" and enter

### Expected Behavior
Save as "한글.txt" file

### Actual Behavior
Save as "한글글" file

There is a problem that the last character is repeated and the .txt extension is not attached.

### Debug Information
Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line :
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.2006
Current ANSI codepage : 949
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    Remove Duplicate Lines (1.3)

**Comment by Avtem** [comment]
Can not reproduce on **Windows 7, Notepad++ v8.4.6   (64-bit)**

**Comment by lunamoth** [comment]
Occurs when you write "한글" and hit Enter when a block is set in "글"

It doesn't happen if you write "글" and hit enter with the arrow keys → block setting is off.

In Windows default Notepad, there is no problem even when blocks are set.

**Comment by Avtem** [comment]
Hm, i think video here would be very useful, because i don't fully understand what you mean by "block". Also as i don't speak Korean i don't how to type those characters and  don't have the correct keyboard layout enabled on my machine
To run the test i simply copied the text - i didn't type it. Maybe that's relevant for this issue

**Comment by tomasz1986** [comment]
Korean uses letters which form syllables. Each syllable is a "block". If you type Korean, the letters you type form syllables. This is done automatically by the OS input system. In this specific case, once you type (note: not copy and paste) "한글", and then you press enter, you will end up with a file named something like.

```
한글.txt글
```

instead of the desired

```
한글.txt
```

If you want to reproduce the issue yourself, you will likely need to actually install Korean language input first, then type "한글" (which translates to "gksrmf" on the English keyboard layout) in the "save as" window. In fact, you don't need to type "한글" specifically, a just using the Korean input to type any kind of gibberish will be enough, and you will see that the last block/character ends up being repeated at the end.

**Comment by gamplaying** [comment]
I'm having the exact same problem.
When I save a file name "테스트", but actual file is saved as "테스트트" or "테스트.txt트" according to Windows setting.
From v8.3.1 to the current version, This problem occurs. And before v8.2.1, this does not occur.
