### ISSUE TITLE
Search and replace: replacing ß (&szlig;) also replaces occurrences of "ss"

### ISSUE THREAD

**Issue by Dvaeer** [notepad-plus-plus/notepad-plus-plus#1245]
If you try to replace all occurrences of ß (ß) in your document, notepad++ also replaces all occurrences of ss (double s).

E.g. if you want to replace ß with x in the string

ausschließlich 

it ends up with

auxchliexlich

which is wrong.

**Comment by Ede123** [comment]
Reproduced in Notepad++ 6.8.8 on Windows 7.
Seems pretty serious given the fact that this could potentially damage data in unexpected ways!

```
Notepad++ v6.8.8
Build time : Dec 10 2015 - 01:11:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : none

```

**Comment by wutzebaer** [comment]
when will this Bug removed?

**Comment by PauloFrancaLacerda** [comment]
Could NOT reproduce it in np++ v6.9.0.0 on Windows 7 (x86).

**Comment by Ede123** [comment]
Still reproduced in Notepad++ v6.9.1 on Windows 7 (x64).

Make sure to replace in "Normal" or "Extended" modes.
The issue is *not* present in "Regular expression" mode.

**Comment by PauloFrancaLacerda** [comment]
Tested in "Normal", "Extended" and "Regular expression" modes. All fine, no bugs!
Notepad++ v6.9.0.0 on Windows 7 (x86).

**Comment by modbw** [comment]
Tested in 6.9.1 in Windows 7
It only appears in UTF-8 documents. ANSI is not affected.

**Comment by wutzebaer** [comment]
Just paste 'Haftungsausschluss' in a new Document and replace 'ß' with 'x' in normal mode, i'm on 6.9.1 and Windows 10

**Comment by tcmaps** [comment]
Still buggy with UTF-8 in Notepad 7.5.7 on W10 x64

**Comment by MetaChuh** [comment]
please use regex mode for ß replacements.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by Ede123** [comment]
@MetaChuh Could you please re-open this issue?

This is an actual bug, not a glitch, or missing function.

Workarounds are not sufficient here, because a user first needs to be made aware that there is an issue to start with (it's often not immediately visible when replacing in a large document), and even then this bug can potentially cause loss of data, so *needs* to be addressed IMHO.

Also the fact that there's an issue with "ß" begs the question if there are not even more Unicode characters that are not handled properly.

**Comment by Ede123** [comment]
There also seem to be various similar issues:  
https://github.com/notepad-plus-plus/notepad-plus-plus/issues?utf8=%E2%9C%93&q=%C3%9F

**Comment by MetaChuh** [comment]
@Ede123 

> Workarounds are not sufficient here

this is not a workaround, this is how you have to use notepad++ due to the scintilla component.

scintilla follows the unicode standard for locale independent case folding to do case insensitive searching.
this standard specifies that `ß` matches `ss` when searching/replacing case insensitive.

so your choices are:
* use **case sensitive** when searching/replacing, which will correctly identify any `ß`.
* use **regex** search, as it uses another engine. (boost)
* file an issue at the [**scintilla project bug tracker**](https://sourceforge.net/p/scintilla/bugs/).
* use an editor that is not scintilla based. (none of these: [Software based on Scintilla](https://en.wikipedia.org/wiki/Scintilla_(software)#Software_based_on_Scintilla))

there is nothing we can do about that.

**Comment by Ede123** [comment]
Thanks, if that's "by design" and not an encoding issue it's obviously a different scenario.

Are you sure this can not be configured by Notepad++ in Scintilla? Even if the Unicode standard says this (I assume because there's no upper case "ß") it might be useful for searching, but certainly seems problematic when replacing.
