### ISSUE TITLE
Undo EOL conversion causes mixed line endings

### ISSUE THREAD

**Issue by Baptistou** [notepad-plus-plus/notepad-plus-plus#12472]
### Description of the Issue
If I do EOL conversion and then undo modifications, the file restores previous line endings but keeps new EOL format in status bar.

### Steps to Reproduce the Issue
1. Open a new file with Windows Format (CRLF)
2. Go to menu Edit > EOL Conversion > UNIX Format (LF)
3. Undo the file modifications, menu Edit > Undo or CTRL+Z
4. Add a new line to the file

### Expected Behavior
The file should switch back to Windows Format (CRLF) after undo.

### Actual Behavior
![image](https://user-images.githubusercontent.com/16428197/200515474-e1f1cf66-7c86-473e-9b9c-feb20d0c97b0.png)
![image](https://user-images.githubusercontent.com/16428197/200515498-1d2f9ebf-a0b4-4ad9-85c1-b1519f5eb81b.png)

### Debug Information
Notepad++ v8.4.6   (32-bit)
Build time : Sep 25 2022 - 19:55:26
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.1415
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by alankilborn** [comment]
Unfortunately, I don't know that the "Expected Behavior" is reasonable.

"Undo" undoes modifications to text, not the state of a command setting.  

Another example would be turning on of visible line-endings, and then invoking Undo and expecting the line-endings to no longer be visible -- it just doesn't work this way.

**Comment by Yaron10** [comment]
EOL Conversion modifies the file, unlike turning on/off of visible EOL.

**Comment by alankilborn** [comment]
The title of this issue might be misleading.
The undo undoes the modification to the text.
When the user does step 4 (add a new line to the file), that's when mixed line endings happen.
User's "Expected Behavior" IS satisfied.
User just has unstated expected behavior; they expect the current line-ending type to be detected (and reset to the previous setting) in the menu.
Not sure if it is reasonable that at every undo, the line-ending type of the file (read from line 1 only) gets checked and/or set.

**Comment by Yaron10** [comment]
> they expect the current line-ending type to be detected (and reset to the previous setting) in the menu.

I also think that's the expected behavior. And this is the result in other editors (e.g. EditPad).

**Comment by Yaron10** [comment]
> Not sure if it is reasonable that at every undo, the line-ending type of the file (read from line 1 only) gets checked and/or set.

That's a good point.
Perhaps only a document whose EOL has been converted should be "monitored".

**Comment by donho** [comment]
When convert EOL from a system to another, implicitly users want the all the EOL set to the converted one, so reset new EOL action is done also for such purpose. The Undo action undo the file content but doesn't reset to the old EOL - I consider it's normal behaviour and it's not a bug.
