### ISSUE TITLE
Document Map shows on all desktops

### ISSUE THREAD

**Issue by mikebei** [notepad-plus-plus/notepad-plus-plus#1247]
If you have multiple desktops configured in WIndows 10, a shadow of the document map shows up on all desktops, not just the one where the main app window is open. Notepad++ version 6.8.6.
![doc-map](https://cloud.githubusercontent.com/assets/6351501/11786403/14ae805a-a24c-11e5-87b9-40ce3a145654.png)
![extra-doc-map](https://cloud.githubusercontent.com/assets/6351501/11786402/14ad8a6a-a24c-11e5-9cba-fdd2c1cbdbcc.png)

**Comment by AnasFB** [comment]
Same thing for me, it's appear on all desktops, also it make some problem when I use shortcut to move between desktops.

**Comment by wolf99** [comment]
I have the same issue.

If I open Notepad++ and show the document map view (View > Document Map). Then switch to a different or new desktop (WinKey + Ctrl + D, or if another desktop is already open: WinKey + Ctrl + LArrow/RArrow) Then the document map overlay is visible in the new desktop as shown in the OP's image.

The only way I have found to prevent this so far is to use Notepad++ without the document map.

This is with Notepad++ v7.1 on MS Windows 10 v1607

**Comment by h2ad2** [comment]
This is **STILL HAPPENING** !!! (w10 32bit latest, NPP 7.6)

**Comment by excrucio** [comment]
**Present still!**

**Comment by mrhyper** [comment]
Still present in 2019 :/

**Comment by pidgeon777** [comment]
Still happening even with latest Notepad++ version. I hope this very annoying bug will be fixed...

**Comment by VL4DST3R** [comment]
Came here to also bump this issue, still very much present.

**Comment by Uhf7** [comment]
Verified the problem using Windows Virtual Desktops (not with a second monitor).

Windows has a build-in 'mechanism', switching the windows of all applications not living on the current desktop invisible. Now, assume the application not living on the current desktop is Npp. The mechanism switches the Npp main window and all child windows of Npp invisible. Unfortunately, the transparent window, which marks the current range within the Document Map, is not a child window of Npp. That's why it remains visible on all desktops.

We can change this replacing the `WS_POPUP` attribute of the `IDD_DOCUMENTMAP` dialog in **documentMap.rc** with a `WS_CHILD` attribute.

**Comment by xylographe** [comment]
For those who would like to test the fix above, try the [npp-32-bit](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/32899165/job/l970eyh4n2exbe1i/artifacts) or [npp-64-bit](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/32899165/job/wn1coya0vx5omo5p/artifacts) Artifacts.

Replace only `notepad++.exe`. Do NOT replace `SciLexer.dll`,

**Comment by ArmandDelessert** [comment]
I tested it and I didn't encounter the bug. The fix seems to be working! 🙌
Thanks! 😃
