### ISSUE TITLE
Autocompletion for ignoreCase="yes" and mixed words case works incorrect

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#12495]
When we have `ignoreCase="yes"` (default) and mixed words in `xml` file then the popup does not work properly.

Str:
1. Open Notepad++ and select `ActionScript` language.
2. Press `a`. We will get:
![image](https://user-images.githubusercontent.com/2730894/201340804-942bd156-be4c-4f07-b41e-fa5b01dc4772.png)
This is correct. We get a list of words starting with `a` and `A` (because we ignore case), and `a` is selected because it fits better in the text. 
3. Press `b`.  Popup will be closed. It's wrong because the word `abs` exist on list.

Same happend when in step 3. we press `c` or `d`. The interesting thing is that there is no problem with e.g. `l`, `n`, `p`, `s`. 

Another casae:
1. Open Notepad++ and select `ActionScript` language.
2. Press `a`. We will get:
![image](https://user-images.githubusercontent.com/2730894/201340804-942bd156-be4c-4f07-b41e-fa5b01dc4772.png)
This is correct. We get a list of words starting with `a` and `A` (because we ignore case), and `a` is selected because it fits better in the text. 
3. Press `r`. We will get:
![image](https://user-images.githubusercontent.com/2730894/201342059-c3cd7029-2cbe-408a-b574-33e8dcb695e6.png)
Still acceptable because it fits better than `Array`.
4. Press `r`.  Popup will be closed. It's wrong because the word `Array` exist on the list.

This works fine when we have only one variant of `name` value in `.xml` (only upper or only lower) or when we set `ignoreCase="no"`.
But still I want to be able to put on the list mixed case even when language is case insensitive (names are more readable and often appear in this form in the specification).

Another question: would not be better if pressing next case will refresh popup list to show only the matching items? Now when we press one char like `a` we get list of all words started with `a`, now when press `b` this list is the same (still show all words started with `a`) but select `ab` word.
The problem is when we have `AZ1, AZ2, AZ3...` and `az` word and there are a lot of other words started wit `a` or `A` between them. Now when on the list `az` word was selected we don't see (don't know) that words like `AZ1, AZ2, AZ3....` exist (we don't see it). If pressing next case will refresh popup list to show only the matching items then this problem would be reduced (even if a scroll appears, it won't be so long).

```
Notepad++ v8.4.6   (32-bit)
Build time : Nov  7 2022 - 21:47:42
Path : D:\_test\NPPClean\notepad++.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 21H2
OS Build : 22000.1219
Current ANSI codepage : 1250
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
```

**Comment by mpheath** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5719558588c5d6467c76b2b6778538fceb4c29eb/PowerEditor/src/ScintillaComponent/AutoCompletion.cpp#L379

does a case sensitive sort of items every time. A case insensitive list will operate better with a case insensitive sort of items.

So, could be replaced with

```cpp
	if (_ignoreCase)
		sort(wordArray.begin(), wordArray.end(), [](const generic_string &a, const generic_string &b)
		{
			return (generic_stricmp(a.c_str(), b.c_str()) < 0);
		});
	else
		sort(wordArray.begin(), wordArray.end());
```

<details>

<summary>Debug Info...:</summary>

```
Notepad++ v8.4.8   (64-bit)
Build time : Dec 25 2022 - 15:35:20
Built with : GCC 11.2.0
Path : D:\Reports\Notepad++\notepad-plus-plus\PowerEditor\gcc\bin.x86_64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : none
```

Compiles nicer now than with the old makefile :+1: 

</details>

<details>

<summary>Responses to OP:</summary>

**Note**: Images below are captured from a patched Notepad++ unless specified as from the OP.

<hr>

>Str:
>
>    1. Open Notepad++ and select ActionScript language.
>    2. Press a. We will get:

![autoc_1](https://user-images.githubusercontent.com/58158242/209524344-e210cc4c-290f-47fe-b80f-255bbcf9ac39.png)

`a` at top of an case insensitive list. SciTE does display a similar insensitive list so must surely be over the target.

![autoc_4](https://user-images.githubusercontent.com/58158242/209539551-00a845f3-8534-4884-8dd1-54d271067fee.png)

This is case insensitive autocomplete for C++ in SciTE. Todo: I should probably should set C++ autocomplete as sensitive.

<hr>

>Another case:
>
>    1. Open Notepad++ and select ActionScript language.
>    2. Press a. We will get:
>
>This is correct. We get a list of words starting with a and A (because we ignore case), and a is selected because it fits better in the text.

***Image below from the OP !***

![](https://user-images.githubusercontent.com/2730894/201340804-942bd156-be4c-4f07-b41e-fa5b01dc4772.png)

The selected item might be correct though the list is sorted as case sensitive which is why the list does not operate correct as more keys are pressed. Example `Array` is above `a` instead of below `a`.

<hr>

>    3. Press r. We will get:

![autoc_2](https://user-images.githubusercontent.com/58158242/209524402-996d3134-bab7-47f1-b6de-c99f0bbeeba6.png)

`argument` is the 1st case insensitive match for `ar` as `arg` comes before `arr`. Anything else would surely be incorrect.

<hr>

>Still acceptable because it fits better than Array.
>
>    4. Press r. Popup will be closed. It's wrong because the word Array exist on the list.

`Array` is certainly in the list so if typed `arr`, we will get:

![autoc_3](https://user-images.githubusercontent.com/58158242/209524429-40c7d71e-ce75-4578-acc8-8430d3f358bb.png)

<hr>

>Another question: would not be better if pressing next case will refresh popup list to show only the matching items? Now when we press one char like a we get list of all words started with a, now when press b this list is the same (still show all words started with a) but select ab word.

Autocomplete can disregard checking if active and force to reshow on the next key press though recommended to press <kbd>ESC</kbd> to close the autocomplete and the type the next key. Then a refined list will show based on the existing word. Forcing will destroy list options like keeping the initial list active while typing more keys. Probably better to let the user have options instead of a hyperactive autocomplete beyond user control.

<hr>

>The problem is when we have `AZ1, AZ2, AZ3...` and `az` word and there are a lot of other words started with `a` or `A` between them. Now when on the list `az` word was selected we don't see (don't know) that words like `AZ1, AZ2, AZ3....` exist (we don't see it). If pressing next case will refresh popup list to show only the matching items then this problem would be reduced (even if a scroll appears, it won't be so long).

A case insensitive list will group the leading `A` and `a` items together so `AZ` should be close to `aZ`.

I can suggest "Preferences" -> "Auto-Completion" -> "From `1`th character" and set it to `2` or `3`. Or do as mentioned aboved to press the <kbd>ESC</kbd> key.

Even though a language might be case insensitive, it might be better to set as case sensitive so the list displayed in example ActionScript, is more refined as items beginning with `a` will not match items beginning with `A` and vice versa. This would be a personal preference.

The responses are mine alone. Don or others may disagree.

</details>

If the fix is regarded as OK, I could PR it. My C++ experience is not advanced so perhaps somebody might have a better fix.

**Comment by ArkadiuszMichalski** [comment]
@mpheath
>If the fix is regarded as OK, I could PR it. My C++ experience is not advanced so perhaps somebody might have a better fix.

Regardless of accepted or not it would be good to create this PR so anyone can test your solution. I'm also wondering how autocomplete will work for this insensitive sort.

**Comment by mpheath** [comment]
@ArkadiuszMichalski 

If you get to test, try `acc` in `ActionScript`.

 1. Type `a` and it selects `a` at the top.
 2. Type `c` and it selects `acos`. This is like case sensitive match rather then case insensitive. It passes 2 items starting with `Ac`.
 3. Type `c` again and it selects `Accessibility`. This is a upward movement of selection which I think is weird behaviour for case insensitive matching. Strangely SciTE does similar behaviour.
 
An option exists and I tried it earlier and saw no difference. Though with a reproducible action I can see a difference.

That option is

```cpp
_pEditView->execute(SCI_AUTOCSETCASEINSENSITIVEBEHAVIOUR, _ignoreCase);
```

https://www.scintilla.org/ScintillaDoc.html#SCI_AUTOCSETCASEINSENSITIVEBEHAVIOUR

With this option set at step 2, typing `c` selects `Accessibility`. This appears more natural behaviour for insensitve selection as if considered that items being treated as if all the same case, then `Accessibility` should be expected as the selection.

Now this option seems like a improvement.

**Comment by ArkadiuszMichalski** [comment]
@mpheath 
Yes, in case insensitive meaning selecting `Accessibility` before `acos` seems more appropriate. You can create next commit with this change so we can compare various builds.

**Comment by mpheath** [comment]
@ArkadiuszMichalski 

Added commit to the 4 autocomplete functions with the behaviour change. I lost some time with the [path autocomplete](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11147#issuecomment-1365724574) crashing on me while testing as I need to ensure no ill behaviour occurs with any type of autocomplete.

The autocomplete behaviour change seems very good with testing.

**Comment by mpheath** [comment]
@ArkadiuszMichalski 

I have gone into "Settings" -> "Preferences" -> "Auto-Completion" and checked "Function completion" and so unchecks "Function and word completion". This autocomplete is case sensitive sorted. Added commit to fix.

Only leaves word completion and not sure if it needs case insensitive sorting. It seems to default to only case sensitive items. So it might be good without any change.

**Comment by mpheath** [comment]
Downloaded Notepad++.x64.Release.exe artifact from https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/45782398/job/j4yf4fyp8b8tr51a/artifacts page and personally confirm as good as expected.

<details>

<summary>Before fixes:</summary>

![old](https://user-images.githubusercontent.com/58158242/209772032-5a963849-32e3-4759-908d-a132ba9ce3a7.gif)

Fails:

 * List is not case insensitve.
 * Autocomplete automatically closes once `c` is typed.

</details>

<details>

<summary>After fixes:</summary>

![new](https://user-images.githubusercontent.com/58158242/209772047-5e5c6e13-10dc-4b24-82fb-8083535ad601.gif)

Successes:

 * List is case insensitve.
 * Autocomplete remains active once `c` is typed. Type `o` selects `acos`

</details>

Waiting for review to merge. :pray:
