### ISSUE TITLE
Deleting search results results in app lock-up

### ISSUE THREAD

**Issue by scott-smith-immersedvr** [notepad-plus-plus/notepad-plus-plus#12555]
### Description of the Issue
Deleting search results results in app lock-up ("Not Responding").

I've noticed this happening when I do searches that result in lots of hits over many files -- hereafter referred to as a "_big search_". So far, I've only noticed the lock-up when I try to clean up the results view after one or more big searches by removing other (usually non-big) search results. It's not necessary to attempt remove the big search itself.

I've first  noticed this problem not long ago, so I suspect that it was introduced relatively recently. I'm using Notepad++ in the same way I have been for years, and this problem just started occurring in the last few months or so.

### Steps to Reproduce the Issue
1. Do two or more **Find in Files** searches, one of which results in lots of hits over lots of files (e.g. "22539 hits in 1983 files of 13138 searched"). The other search(es) can have few or zero hits.
2. Try to delete one of the other (non-big) search results by clicking on its parent item in the search results view.
3. Even though the search being deleted has a small number of hits, the app enters a "Not Responding" state and never recovers.

### Expected Behavior
I might expect that deleting the results of a really big search could take some time. But deleting search results with a small number of hits shouldn't take long, just because the view also has one or more big search results in it. In fact, it's not clear why the mere presence of a large search result would impact the deletion of a small or zero-result search that's either earlier or later in the Search results view.

### Actual Behavior
The app enters a "Not Responding" state and never recovers (I've let it sit for hours on at least one occasion).

### Debug Information
Notepad++ v8.4.6   (32-bit)
Build time : Sep 25 2022 - 19:55:26
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2251
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

![image](https://user-images.githubusercontent.com/110685010/203392414-8dfbc742-22c6-4d6f-8c39-e69d8bfdaaac.png)

**Comment by Rinakles** [comment]
Same issue here. Started a few versions ago, been waiting for it to be fixed but no changes so far.
It doesn't actually lock up, the time to close the results has simply increased by something like 10000x.

For instance, `120983 hits in 6836 files of 15651 searched` took over two hours to close, when previously it was about 15-20 seconds.

**Comment by Yaron10** [comment]
@donho,

I can reproduce that.

**Comment by alankilborn** [comment]
> I can reproduce that.

I wonder if it is related to the introduction of this:

![image](https://user-images.githubusercontent.com/77065706/204292665-d54397e5-6c8b-4c42-adb1-5ccc39b9094d.png)

@Yaron10 could you try your reproduction scenario on released software, just _before_ the above was added in?

**Comment by Yaron10** [comment]
@alankilborn,

The binary of the commit just before `Show only one entry...` is no longer available.
I've tested it with v8.4.2.

The search itself takes much longer (quite significantly, black screen etc.) with v8.4.2 compared to v8.4.7.

**Deleting an entry in the Search Results window:** 
Much faster with v8.4.2.
v8.4.7 hangs.

**Comment by alankilborn** [comment]
@Yaron10 

>The search itself takes much longer (quite significantly, black screen etc.) with v8.4.2 compared to v8.4.7.

One step forward...

>Deleting an entry in the Search Results window:
Much faster with v8.4.2.
v8.4.7 hangs.

...and one back.

Such are the hazards of s/w development.

**Comment by Yaron10** [comment]
@alankilborn,

https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12048 by @Ashfaaq18 is a major factor in the search performance improvement.

**Comment by Rinakles** [comment]
Curious. I tried downgrading to 8.4.2, but the issue persisted.
Tried downgrading further from there. 8.4.0 is the first version that freezes for me, while 8.3.3 still works.
The update notes for 8.4.0 includes this search-related item:
- Make Find in Files search result line number aligned. (Fix [#11119](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11119))

**Comment by Yaron10** [comment]
@Rinakles,

I've tested it more thoroughly and, you're right, 8.4.2 hangs as well on deleting an entry.

I haven't tested 8.3.3 now.
But I suppose it might hang as well under certain circumstances.
And the difference you see in your test-case is probably due to 
> Update Scintilla from v4.4.6 to v5.2.1 and add Lexilla v5.1.5. (Fix [#10504](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10504)).

in 8.4.0.

**Comment by patrickcoyne** [comment]
Not sure if this is necroposting but I run into this issue every day searching debug logs while doing dev work.

I'm running 8.4.8.

1. Open file
2. Search for a string with many instances (10000+)
3. Click on search results
4. CTRL+A to select all of them
5. Hit del to delete them all

The app is now hung. The more results I'm deleting, the long it is hung. Deleting 100,000+ results will hang so long I force quit the app.

This used to work fine. I thought maybe it was related to a plugin but seems like other people are seeing this too. Love Notepad++, please fix!

**Comment by Rinakles** [comment]
I recommend switching back and sticking to the latest working version, which is 8.3.3.
I'm not sure what's going on with this project, as new critical issues like this keep popping up and then ignored.

**Comment by alankilborn** [comment]
>I recommend switching back and sticking to the latest working version, which is 8.3.3.

If that's the case, then I'd look to the change.log for 8.4; the only relevant item seems to be:

* _Make Find in Files search result line number aligned. (Fix #11119)_

Maybe that is the root cause?

**Comment by rdipardo** [comment]
@Rinakles,
> I recommend switching back and sticking to the latest working version, which is 8.3.3.

That was the last N++ version built with [Scintilla 4.x.x].

> I'm not sure what's going on with this project

Scintilla v5 has been a steep learning curve for the develoeprs (to put it mildly).

*À propos* the search result window, the root of the problem is how the editor folds (or "collapses") the matching lines. See <https://sourceforge.net/p/scintilla/bugs/2339>, and the many threads it links to; also #11774.

[Scintilla 4.x.x]: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a61b03ea8887e21c6e1b7374068962f635b79b80

**Comment by nyamatongwe** [comment]
Its worthwhile profiling every performance issue.

In Visual C++

1. Select the **Release** configuration.
2. Perform **Debug | Performance Profiler...**
3. Select **CPU Usage**
4. Press **Start**
5. Once application is running, perform an example slow operation
6. Close application
7. Select the heavy CPU % (green) range in the timeline
8. The **Hot Path** is the calling sequence that is slow although the underlying cause might be elsewhere

![NPP_DeleteFindInFiles](https://user-images.githubusercontent.com/225818/211174409-0bb4f030-821e-4d68-ab3b-3a027e925c7e.png)

The profile shows that the time is being spent in `FoldSearchResultDoc`. Placing a breakpoint at the start of `FoldSearchResultDoc` shows that it is being run from position 0 many times instead of incrementally moving through the document. Lexers are responsible for marking the range that has been lexed but that isn't occurring here. Breaking in `ColouriseSearchResultDoc` shows that lexing is restarted from 0 `styler.StartAt(startPos);` but an absence of "@MarkingsStruct" results in early exit without updating the styled range.

Solution: either style the range or mark it as styled with `styler.StartAt(startPos + length);` if the existing styles should be valid.

**Comment by donho** [comment]
@nyamatongwe
Thank you for pointing out the Find in files searching performance issue. 
I will check it ASAP.
