### ISSUE TITLE
Incorrect display of Cyrillic in the macros submenu

### ISSUE THREAD

**Issue by rddim** [notepad-plus-plus/notepad-plus-plus#12670]
### Description of the Issue

When I use Cyrillic in the macros submenu it appears unreadable in the `Macro` menu.
### Steps to Reproduce the Issue

1. Download the latest v8.4.8 RC2 `npp.8.4.8.portable.minimalist.x64.7z` from http://download.notepad-plus-plus.org/repository/8.x/8.4.8.RC2/
2. Open the `shortcuts.xml`
3. Follow the instructions in the file and add `макрос` for the submenu (i.e. `FolderName="макрос"`) to the existing `Trim Trailing Space and Save` macro
4. Save and close the file
5. Open `notepad++.exe` and click on `Macro` menu

### Expected Behavior

![npp_shortcuts_readable](https://user-images.githubusercontent.com/8998791/208510774-289d45cf-2401-468b-b58a-0c0fe66e43ac.png)

### Actual Behavior

![npp_shortcuts_unreadable](https://user-images.githubusercontent.com/8998791/208510844-8b034712-ea27-4d02-901e-09429063730e.png)

### Debug Information

```
Notepad++ v8.4.8   (64-bit)
Build time : Dec 19 2022 - 02:31:02
Path : X:\xxx\npp.8.4.8.portable.minimalist.x64\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1251
Plugins : none
```

**Comment by rdipardo** [comment]
The bug is in the [TinyXML](https://sourceforge.net/p/tinyxml/bugs/) library. It parses files with [`fgetws()`] (a.k.a. `generic_fgets`) [^1], which does not properly decode multi-byte text.

<img width="732" alt="tinyxml-fgetws-wrong-decoding" src="https://user-images.githubusercontent.com/59004801/208567949-d59bd001-5f8d-4ea2-8bbb-c547ebf306da.png">

An explicit encoding declaration at the top of `shortcuts.xml` does not seem to make any difference [^2].

[^1]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/58416114da14536dcc7a8ad36010da3382366ba6/PowerEditor/src/TinyXml/tinyxml.cpp#L761-L764
[^2]: i.e., `<?xml version="1.0" encoding="UTF-8"?>`

[`fgetws()`]: https://learn.microsoft.com/ru-ru/cpp/c-runtime-library/reference/fgets-fgetws

**Comment by ozone10** [comment]
Hmm TinyXML is not being developed anymore.

Maybe Notepad++ should try to move to [TinyXML2](https://github.com/leethomason/tinyxml2), but this will require major refactoring.
