### ISSUE TITLE
INI File styles can not be changed

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#12696]
**STR:**
Open an INI file.
Open Style Configurator.
Change any style.

**Result:**
Changes are not applied.

https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c0e207328057b9ce321587a053ff1476cbb19562.

***
Notepad++ v8.4.8   (32-bit)
Build time : Dec 20 2022 - 18:10:30
Path : C:\---\npp.8.4.8.portable\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Enterprise (32-bit) 
OS Build : 7601.23964
Current ANSI codepage : 1255
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by rdipardo** [comment]
> **Result:**
> Changes are not applied.

To elaborate: style choices for the Properties file type are being applied to *both* Properties *and* INI files &#x2014; i.e., INI files are detected as Properties.

![ini-style-same-as-props](https://user-images.githubusercontent.com/59004801/209444621-567552cf-38b0-4700-9e92-bdad9817c3af.gif)

Changing any style when the INI file type is selected has no effect, because [INI files are never detected][0].

[0]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/c0e207328057b9ce321587a053ff1476cbb19562/PowerEditor/src/ScintillaComponent/ScintillaEditView.h#L676-L677

**Comment by rdipardo** [comment]
### Quick Fix
~~~diff
diff --git a/PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp b/PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp
index 28f5e220..4e88abb0 100644
--- a/PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp
+++ b/PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp
@@ -1541,7 +1541,7 @@ void ScintillaEditView::defineDocType(LangType typeDoc)
 			setMakefileLexer(); break;
 
 		case L_INI :
-			setPropsLexer(false); break;
+			setPropsLexer(true); break;
 
 		case L_USER : {
 			const TCHAR * langExt = _currentBuffer->getUserDefineLangName();
~~~

**Comment by Yaron10** [comment]
👍 
Thank you for fixing it.

@donho, @rdipardo & all,

Happy Holidays!

**Comment by donho** [comment]
@Yaron10 
Thank you for reporting it.

@rdipardo 
Thank you for the quick fix.

Happy Holidays to you too!
