### ISSUE TITLE
Trying To Conquer What I Thought Was Simple.

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#127]
I recently joined this site, Cytube, and was wondering how other people on this site made background images. I have learned of the HTML/CSS fairly good, but they all give tutorial for your OWN website.

The site is not mine. All I want to do is add a few words with a hyperlink, and add a background image. I don't want to get super fancy like this one, let alone me achieving such a thing: http://cytu.be/r/mlpanniversary

Anyway....
https://www.youtube.com/watch?v=BYbKYUCLjNU

This video clearly shows the background image settings, but HOW did he get the whole site up there? Like I said, the site I'm editing is not my own, so how exactly CAN I edit it if I don't even have the code?

Also, I am using the most recent version of Notepad++, and when I attempt to do what the guy does in the video at 5:30, nothing appears, on top of all this.

I am in desprate need of help. I honestly would very, very much appreciate anyone who tries to help!

**Comment by andreas-jonsson** [comment]
The guy in the video is using some other program (maybe he says which one in the beginning). N++ doesn't have those advanced features, so when you type in "background-image" you won't get a file dialog where you can choose a background image file. You will have to type the name of the file manually.

Take an image, rename it to "bg.jpg" and place it in some folder. Copy the below HTML code and place it in a file called "test.html" in the same folder that you blaced bg.jpg. If you open test.html in a browser you should get a background image.

```html
<html>

<head>
<style type="text/css">
body {
	background-image: url(bg.jpg)
}
</style>
</head>

<body>

Some text. <a href = "http://www.github.com">A link</a>

</body>

</html>
```

**Comment by oriju** [comment]
I figured out the program - it's called DreamWeaver.
One more thing out of the way.

Thanks for specifying about the notepad++, I shall surely try it out.
*********

Now onto problem 2.

As I've said before, this site (that is not mine) wants me to edit a site using CSS for this background image I want, but how do I connect it to the CSS, especially since I don't have the code for the site that tells me to do this?
![untitled](https://cloud.githubusercontent.com/assets/12620731/7849876/381ca45a-048f-11e5-94ea-5e108dfff535.png)

I pointed to the site link above because I want to ask...Is that all I have to do to connect this site?
******
Either way, I am so very relieved someone is trying to help me. A thousand thanks coming from me to you.

**Comment by oriju** [comment]
(4hrs later)
*
Hey it worked! Now to only apply it to the page somehow and I'll be set. Thank you a lot there.

**Comment by oriju** [comment]
I talked with one of the heads of the site on live chat and I got right on track. Thank you for your help, though, I really needed that.

I'll take my leave now.

Once again, thank you.

**Comment by Croydon** [comment]
When I got it right then this was never a Notepad++ issue. I guess it can be closed :)
