### ISSUE TITLE
Loss of syntax highlighting during "save as"

### ISSUE THREAD

**Issue by dail8859** [notepad-plus-plus/notepad-plus-plus#1298]
1. Start typing some code in a new file
2. Set appropriate language
3. Save it with a name that Notepad++ doesn't recognize the extension for (e.g. `.file`)
4. Language is set back to normal text

When it does a "save as" it tries to auto detect the language, and since it is an extension that isn't recognized, it gets reset to normal text.

**Comment by sanastasiou** [comment]
I guess you are referring here to just the active session?

**Comment by dail8859** [comment]
> I guess you are referring here to just the active session?

If you mean just the file that gets saved, then yes.

**Comment by neo291** [comment]
Hi @donho , I've analyzed the code for this modification and I've found a way to make it work as @dail8859 says.
I think that the work can be splitted in 2 separate phases:

1st. Add a `LangType defaultLang = L_TEXT` parameter to the function `NppParameters::getLangFromExt` in order to return the selected `defaultLang` (If specified, if not specified the default remains `L_TEXT`) instead of the fixed `return L_TEXT`. This allow to behave as the comment row `// If the ext is not in the list, the defaultLang passed as argument will be set.` says for the function `Buffer::setFileName` and fix its behavior with unknown extensions

2nd. If you want behave as the "save" button also for the "save as" I think that I can implement a sort of `bool dontReDetectLang = flase` parameter for the function `Buffer::setFileName`, that if it is set to true avoids the the change of the `_lang` var into the current `Buffer` object. In this way when the file is saved with "save as" the selected language is not changed, but when the file is open it will be auto-detected as always

Let me know if you want to let me handle this issue.

I've the 1st part already ready for a commit and a pull request, if we also want to proceed with the second part I can make it and when ready do another separate commit and pull request for that, in order to separete the two modifications in two different commits. If you want the two modification in the same commit let me know.

**Comment by donho** [comment]
@neo291 Thank you, I'll check your pr.

@dail8859 so the correct behaviour to you is:
A new file is applied to C++ syntax highlighting.
When we save this file as `main.mycpp`, the C++ syntax highlighting should be kept since `.mycpp` is an unknown extension.

Could you confirm it?

**Comment by dail8859** [comment]
@donho Yes that is correct.
