### ISSUE TITLE
"New Document" language setting does not apply anymore

### ISSUE THREAD

**Issue by madmoonman** [notepad-plus-plus/notepad-plus-plus#13066]
### Description of the Issue
In earlier versions of Notepad++, we could provide a default language for "new documents" which are files without an extension. This is still possible, but the setting seems to be ignored. We usually use this to quickly open c++ files w/o extension. We are then readily able to use block comments or uncomment blocks. Somewhere in recent versions this functionality was lost. We now have to set the language first each time we open a "new document".

### Steps to Reproduce the Issue

1. Create a file w/o extension, save.
2. Open the file.
3. No syntax highlighting or functionality like block comments are available-

### Expected Behavior
Block comments readily available.

### Actual Behavior
Language is not recognized, no specific functionality available.

### Debug Information
Notepad++ v8.4.9   (32-bit)
Build time : Jan 27 2023 - 03:08:31
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 22H2
OS Build : 19045.2486
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by madmoonman** [comment]
The setting I am talking about:
![grafik](https://user-images.githubusercontent.com/79474757/216948804-0aade4a9-b858-4e2c-8767-75e901e928cd.png)

**Comment by rdipardo** [comment]
@madmoonman,
> In earlier versions of Notepad++, we could provide a default language for "new documents" which are files without an extension.

I think you specifically mean [release version 8.4.4] and earlier.

8.4.5 made some ill-advised changes to the file detection mechanism, prompted by [a bug report] that, in hindsight, should have never been acted upon:

- #12226
- #12253
- #12378

The "fix" was fixed in [version 8.4.7]. *That* fix required another minor fix in [version 8.4.8].

This particular issue comes from there being no explicit logic to handle files without an extension; i.e., this `if` expression has no `else [if]` to balance it:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f38195a0da5657f447ccc949bc77f38dba06aa61/PowerEditor/src/ScintillaComponent/Buffer.cpp#L197-L214



[release version 8.4.4]: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v8.4.4
[version 8.4.7]: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a26599794cfd5bc7c6754d240e7563f24b90e4cb
[version 8.4.8]: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c63cc6f21993ac50f4f41c2f5013c6e79819927b
[a bug report]: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11504

**Comment by madmoonman** [comment]
Great. Looking forward to using this in the new versions (again)! :) Thank you.

**Comment by donho** [comment]
The "New Document settings" means the settings in this panel applied only to new document - the only exception is UTF8 with an extra option. So the change of v8.4.4 (and previous versions) concerning behaviour makes no more ambiguity.
Therefore the old behaviour won't be restored.

**Comment by madmoonman** [comment]
Hello, I am coming back to this.
That it only applies to "New documents" (docs w/o extension) is kind of the point. Some files do not use extensions and we could handle them according to the setting in the older versions.
If you do not intent to restore the behavior for "new documents", what about adding controls for "files w/o extension"? This would be a clear distinction between "new doc" and "extensionless file" which, technically, are not the same thing.
