### ISSUE TITLE
Documentation - old supported OS table

### ISSUE THREAD

**Issue by sXNA** [notepad-plus-plus/notepad-plus-plus#13074]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/SUPPORTED_SYSTEM.md
is old.

Windows 8.1 support ended
https://learn.microsoft.com/en-us/lifecycle/products/windows-81

Windows Vista doesn't work with latest notepad++ 8.4.9.
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ce85323a9e899e02ebc4c682298a7398cad99f60#commitcomment-89820581
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12513

And Windows 8 has "No" in 3rd column other OS have "NO"

**Comment by alankilborn** [comment]
>Windows 8.1 support ended

It doesn't matter that M$ has ended support; the question here for the table is "does N++ run on the OS"

**Comment by sXNA** [comment]
It can run but it should be still supported?

"The column supported contains the status of Notepad++ team supporting Notepad++ under the specific OS. It means if a bug is present under an OS no more supported but not under supported OS, then this issue won't be treated by the team."

**Comment by ozone10** [comment]
@donho 
Should be Vista removed from "can be run" or try to figure out why it does not work.

**Comment by rimrul** [comment]
> Windows Vista doesn't work with latest notepad++ 8.4.9.
> https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ce85323a9e899e02ebc4c682298a7398cad99f60#commitcomment-89820581

That doesn't seem entirely accurate. There's at least one issue that clearly says it does work on Vista](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13078)

**Comment by rdipardo** [comment]
> @donho Should be Vista removed from "can be run" or try to figure out why it does not work.

v8.4.7 implicitly calls `::CoGetApartmentType`, as revealed by the import table:

<img width="756" alt="npp-v8 4 7-pe-header" src="https://user-images.githubusercontent.com/59004801/221376757-b8671899-7d2a-41f8-bd68-f0dd8f0564a7.png">

The [API docs] for `::CoGetApartmentType` say that Windows __*7*__ is the minimum supported desktop OS (with Windows Server 2008 R2 being the minimum supported server OS).

v8.4.6 and earlier doesn't import `::CoGetApartmentType`, so no dependency on any Win 7 APIs:

<img width="756" alt="npp-v8 4 6-pe-header" src="https://user-images.githubusercontent.com/59004801/221376765-dfdd5252-ba70-4e89-a7fb-b16376d32895.png">

Just attach N++ to a debugger and watch the call stack for `::CoGetApartmentType` to see where the dependency got introduced.

[API docs]: https://learn.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-cogetapartmenttype#:~:text=Minimum%20supported%20client

**Comment by chcg** [comment]
Seems Mingw build still don't need `::CoGetApartmentType`

**Comment by donho** [comment]
@ozone10 
It's always better to know why and if it's worth to not support Vista anymore.
Do you want to look into it? You're more than welcome if you want to.

**Comment by rdipardo** [comment]
@chcg,
> Seems Mingw build still don't need `::CoGetApartmentType`

Correct; and in fact Vista can still run GCC builds:

![npp-git-win-vista](https://user-images.githubusercontent.com/59004801/221391591-b8e5bd04-76bf-4005-817b-8e0b95dc7631.png)

@donho,
> It's always better to know why and if it's worth to not support Vista anymore.

The obvious reason why is the dependency since v8.4.7 on `::CoGetApartmentType`.

Vista was never popular, had endless driver compatibility problems, and runs like a dog even on modern hardware. Extended support ended [almost six years ago](https://learn.microsoft.com/en-us/lifecycle/products/windows-vista). Who's going to miss it?

**Comment by ozone10** [comment]
@donho 
seems toolset v143 does not support Windows Vista
https://learn.microsoft.com/en-us/visualstudio/releases/2022/compatibility#build-apps-that-run-on-windows-clients

**Comment by donho** [comment]
@rdipardo 
> Vista was never popular, had endless driver compatibility problems, and runs like a dog even on modern hardware. Extended support ended [almost six years ago](https://learn.microsoft.com/en-us/lifecycle/products/windows-vista). Who's going to miss it?

You're right about it. But my purpose is identify the cause to prevent Notepad++ from other such regression. And if the Vista support is effortless, why don't we?

@ozone10 
Indeed it seems this "regression" is due to 4c96f86979b51fcf0064d9a252464e82405d0d80 - If it is then Vista will be dropped.
I prefer to have the confirmation from the users.

@rdipardo @sXNA @a80b8829
I'll build 2 binaries (x86 &x 64) with platform toolset 143 and provide them here. Could you test under Vista?

**Comment by ozone10** [comment]
@donho 
> I'll build 2 binaries (x86 &x 64) with platform toolset 143 and provide them here. Could you test under Vista?

I think you mean toolset **v142**

Users might try using GCC builds since it is not affected by commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/4c96f86979b51fcf0064d9a252464e82405d0d80

**Comment by donho** [comment]
@rdipardo @sXNA @a80b8829
I'll build v8.4.6 (x86 &x 64) with platform toolset 143 and provide them here. Could you test under Vista?
[notepad++.846.x64.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10834093/notepad%2B%2B.846.x64.zip)
[notepad++.846.x32.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10834096/notepad%2B%2B.846.x32.zip)

@ozone10 
> I think you mean toolset v142

No, I did mean v143, but with v8.4.6 - the current state of v8.5 cannot be compiled with toolset v142 anymore :)

**Comment by chcg** [comment]
Seems indeed the toolset is causing the incompatibility:
![grafik](https://user-images.githubusercontent.com/12630740/221431898-c7a65da9-e86b-48d2-8544-f2aaa2b3fef7.png)

**Comment by donho** [comment]
@chcg 
Thank you for the confirmation!

**Comment by rdipardo** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/8a69ab841f1307c8a20a16787d4edf3da65b4040/SUPPORTED_SYSTEM.md?plain=1#L18-L19

Not to complicate things too much, but officially Windows Server 2008 __*R2*__ [is still supported] by the v143 toolset.

[is still supported]: https://learn.microsoft.com/en-us/visualstudio/releases/2022/compatibility#build-apps-that-run-on-windows-clients:~:text=Windows%20Server%202008%20R2

**Comment by win98se** [comment]
I recommending merging the `Windows Vista` & `Windows Server 2008` lines, then add `Windows Server 2008 R2` to after `Windows 7` (making it `Windows 7 & Windows Server 2008 R2`).

Because Windows Server 2008 is NT 6.0 (so its latest service pack is SP2), Windows Server 2008 R2 is NT 6.1 (so its latest service pack is SP1). (Meanwhile WS2003 and WS2003R2 are both NT 5.2 which is confusing)

Expansions (probably not necessary):
- `Windows 8 & Windows Server 2012` (they're both NT 6.2)
- `Windows 8.1 & Windows Server 2012 R2` (they're both NT 6.3)

**Comment by sredna** [comment]
CoGetApartmentType can be manually implemented on older systems, MSDN even tells you how. The question is, is there a decent way to redirect to a trampoline function?

**Comment by win98se** [comment]
> CoGetApartmentType can be manually implemented on older systems, MSDN even tells you how. The question is, is there a decent way to redirect to a trampoline function?

I'm not sure, but is [this](https://github.com/Chuyu-Team/YY-Thunks/blob/master/src/Thunks/api-ms-win-core-com.hpp) sufficient for you?
