### ISSUE TITLE
[Feature request] Solution to the "lost panel" problem

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#13084]
### Description of the Issue
Sometimes panels seemingly get "lost" in Notepad++.
Typically this happens with the _Search results_ window/panel.
The size of the window is reduced (somehow) to zero or near zero, and the user can no longer locate the panel.
Users seek technical support when this happens, resulting in a cumbersome and raw "edit the config file" approach to solution, meaning restoration to a viewable and workable size.

It would be nice if some means for locating such a "lost" window were available in the Notepad++ UI itself; perhaps some sort of minimal size limit, or perhaps a command to provide more size to a suspected lost panel.  We leave it to Notepad++ devs to come up with the best solution.

More discussion on this problem is located in the Community site, including ideas for solutions, [HERE](https://community.notepad-plus-plus.org/topic/23344/).

### Debug Information
Comments based on behavior observed in Notepad++ 8.4.8.

**Comment by Slayer95** [comment]
This is a bug happening since at least 8.4.2. <i>Sometimes</i>, a ``Search All`` execution will suddenly fail and subsequent fails will too.

**Comment by pryrt** [comment]
To the Developers: [here's another report](https://community.notepad-plus-plus.org/topic/24588/find-all-in-all-open-documents-simply-closes-find-window-without-results) in the forum

A possible practical and simple solution: Add a **View** menu command called **Reset Docking Panel Sizes** which would take all four docking panel edges immediately back to their default width -- that would then immediately show any Panels that had been hidden because they were 0 pixels.  Or call it **Reset Any Tiny Docking Panels** which would only change Panels sizes that were 10pixels or fewer.  Or something.

**Comment by Slayer95** [comment]
Since these reports didn't exist before, it's reasonable to hypothesize that something has gone wrong in the software side, rather than suddenly developers becoming dumb and triggering these "accidents".

Last time this happened, I couldn't reproduce your fixing steps as shown in the images posted, but editing the config manually did work. Note, however, that I _can_ use the mouse resize a normally-working search results panel to 0, and back to normal.

**Comment by pryrt** [comment]
> Since these reports didn't exist before

Before when?  Before you posted here?  Before Julia [posted](https://community.notepad-plus-plus.org/post/85123) in March 2023?  Before Kriston in [Jan 2023](https://community.notepad-plus-plus.org/post/83610)?  Before James in [Aug 2022](https://community.notepad-plus-plus.org/post/79058)?  Before Muthuraj in [Aug 2022](https://community.notepad-plus-plus.org/post/78924)?  Before Sylvester in [Aug 2020](https://community.notepad-plus-plus.org/post/56888) (two years earlier)?  Before that same Sylvester in a separate complaint in [Jan 2020](https://community.notepad-plus-plus.org/post/49773)?  Users have occasionally dropped in and complained about this happening, but it's never been anything systematic in one particular version -- no increase in complaints about it after a specific version being released

> becoming dumb

I did not say you or anyone else was dumb for making this mistake.  If I have not been completely clear: Making a mistake is not dumb.  I make mistakes essentially every day.  As Adam Savage has famously said, "failure is always an option".

And I also said that it was "most likely" to be user error, not that it must be.  I said "most likely", because in my many years of using Notepad++ _daily_, it has never happened to me without my intentionally or accidentally resizing the panel.  If there is some way of the panel resizing without my input, I haven't found it yet.

> it's reasonable to hypothesize that something has gone wrong in the software side

When it's not a sudden increase, but just an occasional occurrence with very limited number, user error is actually the more natural assumption than a change in the software.  If it had been as you had implied, with a sudden increase of the problem in the same version of Notepad++ just after that version went public, my reaction would be different.  

But maybe it's some unique combination of problems with your setup: maybe you've got a plugin which isn't playing nice with the panel.  Or maybe it's something unique with the out-of-support Win 7 that you're using (in case you haven't seen, Notepad++ doesn't [officially support](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/SUPPORTED_SYSTEM.md) Windows 7 -- that table says it should run, but isn't supported.  And in case you don't remember, [Microsoft does not support Windows 7](https://www.microsoft.com/en-us/windows/end-of-support?r=1) anymore, either).

But when I take the exact same config.xml DockingManager settings that you quote above, and paste them into the config.xml for v8.4.9 in Win11, when I first run, before doing a search, I see:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/17455758/7055c8e7-493a-461d-9fb1-71a9f83db76f)

After I do a "Find All in File" for `GUIConfig` (which is obviously in my active file)
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/17455758/ecdeaa63-56bc-4e73-8902-cf4dda195def)

I can see a slight gap on the bottom.  If I zoom in on the screenshots (4x), you can see the slight Y difference between various graphical elements, as I highlighted with some red lines and arrows):
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/17455758/868db68f-922d-47ee-aa53-f94c12219b21)

So, I still cannot replicate your results -- if I use the closest to your setup that I can, including the values from your config.xml, I can always resize it using the mouse.  So if you really were in a weird state that I cannot replicate, my next guess is that it's either a plugin you had that I don't, or it's something specific to Win7 (which I don't have access to).  But either way, the feature request that Alan made, with my suggestions for implmentation, should fix it, even for you, since you said that changing from the `bottomHeight="0"` to a non-zero value and restarting fixed it for you.

**Comment by pryrt** [comment]
Two more recent reports in the forum:

- https://community.notepad-plus-plus.org/topic/24866/findinfiles-results-display
- https://community.notepad-plus-plus.org/topic/24875/find-search-not-showing-the-results

This requested feature would _really_ help users not accidentally lose their **Search Results** panel.

**Comment by pryrt** [comment]
Here's another user who had accidentally shrunk the bottom docking panel to 0 pixels, and cannot figure out where to place their cursor to be able to drag the panel bigger (it's not the **Find Results** panel this time, but that's irrelvant, really; _any_ panel, on _any_ edge, can have this problem):

* https://community.notepad-plus-plus.org/post/89988

Having a button in the GUI which resets all docking panels to their original size and location would be _so_ useful to a plethora of users.  Or a way to set a minimum size so it's always at least 10 pixels, which would make it noticable as a shrunken panel.

**Comment by xomx** [comment]
Well, as one of the occasional victims of this "feature", I will try to fix it.

> perhaps some sort of minimal size limit,

> Or a way to set a minimum size so it's always at least 10 pixels, which would make it noticable as a shrunken panel.

I am for this option (have some predefined minimum), as it does not need any new GUI. Moreover, it will then be coherent with the current behavior of the floating docking windows (you cannot minimize them more than to the red close button as is also shown in the videos below).

Is the behavior shown in the fix-video ok?

Current state:

https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/bf1825d7-f2c1-4b47-b79f-4470818b88ca

Fixed:


https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/2dcda327-2846-45b3-a28f-d799ab77d2cb

**Comment by pryrt** [comment]
> Well, as one of the occasional victims of this "feature", 

☹

> I will try to fix it.

🎉


> > perhaps some sort of minimal size limit,
> 
> > Or a way to set a minimum size so it's always at least 10 pixels, which would make it noticable as a shrunken panel.
> 
> I am for this option (have some predefined minimum), as it does not need any new GUI. 

I am fine with that.

> Moreover, it will then be coherent with the current behavior of the floating docking windows (you cannot minimize them more than to the red close button as is also shown in the videos below).

Makes sense.

> Is the behavior shown in the fix-video ok?

For the docked versions, that's great.  

For the undocked/floating version, your video shows that you can still shrink that down to just the X.  If the same minimum size could be applied to the floating window, so there's _something_ beyond just the X, that would be nice, too.  One application that I use has a minimum size like:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/17455758/4d23d636-dc77-4815-b75c-a083a3bca71f) 
... so there's just enough room for the app icon (shown as red box) and maybe a little bit between the icon and the X (so even just part of the title for the window).  

But while it would be nice to have, if the floating version isn't as easy to implement as the docked minimum size, then I'd happily live with the implementation shown in the video.

Thank you!

**Comment by donho** [comment]
> Having a hardcoded minimum is fine with me.

@xomx OK for me too a hardcoded minimum size, but no GUI option please.
As well, make sure that we don't write 0 into and read 0 from XML while shutdown & startup.

**Comment by xomx** [comment]
To summarize (mainly notes for me because I will not start it right now...):

1. no new GUI
2. a definition of the minimum size of the docked panels (will try a dynamic sizing according to the current panel wnd title-bar area size, otherwise some hardcoded value adjusted only by the current DPI)
3. similar definition for the floating panels (unless difficult to implement) 
4. some additional security mechanism for checking the saved/read config.xml DockingManager data (IMO the checking/adjusting at the xml-data-reading-stage will be enough, users/OS could externally manipulate/corrupt the config.xml somehow...)

**Comment by donho** [comment]
> (IMO the checking/adjusting at the xml-data-reading-stage will be enough, users/OS could externally manipulate/corrupt the config.xml somehow...)

I doubt it's not due to users' action, but some flaw in the code - hence these security check.

**Comment by xomx** [comment]
@donho 
> > (IMO the checking/adjusting at the xml-data-reading-stage will be enough, users/OS could externally manipulate/corrupt the config.xml somehow...)
> 
> I doubt it's not due to users' action, but some flaw in the code - hence these security check.

Agree, users mouse movements are responsible for these zero-sized wnds, not a N++ code-flaw.

What I rather meant by my note was that there is no need to check the DockingManager data being written (after I make the necessary code changes preventing such zero-sized wnds), but only the saved data being read back to the DockingManager.

**Comment by donho** [comment]
@xomx 
> Agree, users mouse movements are responsible for these zero-sized wnds, not a N++ code-flaw.

In the contrary, I suppose it's Notepad++ code-flaw which causes such problem. If you can find it, it would be great.

**Comment by rdipardo** [comment]
> (IMO the checking/adjusting at the xml-data-reading-stage will be enough, users/OS could externally manipulate/corrupt the config.xml somehow...)

@xomx is absolutely correct. A while back I posted a proof of concept showing how a crafted `config.xml` can make N++ execute arbitrary plugin functions when starting up: <https://community.notepad-plus-plus.org/post/89445>

Credit goes to @thosrtanner for [discovering this behaviour](https://community.notepad-plus-plus.org/post/89279).

**Comment by xomx** [comment]
@rdipardo 
Interesting reading.
So in this case, user intentionally edit the config.xml file for the plugin's purposes and screwed something up, right?

**Comment by Yaron10** [comment]
If the user manually (and wrongly) edits other parts of config.xml, anything might happen and IIRC NPP can even crash.

**Comment by donho** [comment]
> If the user manually (and wrongly) edits other parts of config.xml, anything might happen and IIRC NPP can even crash.

@Yaron10
Crash should not happen in any way. 
Feel free to open crash issue if you reproduce any crash by editing config.xml

**Comment by rdipardo** [comment]
@xomx

> So in this case, user intentionally edit the config.xml file for the plugin's purposes and screwed something up, right?

It was a polluted development environment resulting in the `id` attribute falling out of sync with the plugin function's actual command id. The same would happen if you installed a new version of a plugin after the developer changed the command ids; the stale config will blindly execute whatever the old id points to now. What's needed is some kind of logic to purge invalid `PluginDlg` elements, similar to how unreachable files get dropped from session files.

**Comment by rdipardo** [comment]
@donho 

> Crash should not happen in any way. Feel free to open crash issue if you reproduce any crash by editing config.xml

This example is pretty contrived but should give you some idea. 

Simply add a node like this under `/NotepadPlus/GUIConfigs/GUIConfig[@name="DockingManager"` (note the value of `curr[ent container]` is > 0x7fffffff):

~~~xml
<!-- <GUIConfig ...> -->
    <PluginDlg pluginName="Notepad++::InternalFunction" id="2051" curr="2415919103" prev="-1" isVisible="no" />
<!-- </GUIConfig> -->
~~~ 

N++ will start and run just fine. But when you try to exit . . .

<div align="center">
<img width="420" alt="plante-du-npp-001" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59004801/488699a7-c919-4e9e-974b-4fe26fe12981">
</div><br/>

OTOH, it's an exceptionally well-handled crash; it even takes the time to write a crash dump!

<div align="center">
<img width="325" alt="plante-du-npp-002" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59004801/25f66012-9382-489c-9339-fee4dc4eae21">
</div>

**Comment by Yaron10** [comment]
> If the user manually (and wrongly) edits other parts of config.xml, anything might happen and IIRC NPP can even crash.

I meant as follows:
Does NPP need to add extra code/checks dealing with manually messed files? - There might be no end to that.
The user can mess some Registry entries and crash Windows.

***

A simple example (not a crash): replace the `<GUIConfig name="AppPosition"` fields with letters or large numbers.

**Comment by donho** [comment]
@rdipardo 
> Simply add a node like this under /NotepadPlus/GUIConfigs/GUIConfig[@name="DockingManager" (note the value of curr[ent container] is > 0x7fffffff):

Adding your provided value doesn't make my Notepad++ crash:
```xml
        <GUIConfig name="DockingManager" leftWidth="562" rightWidth="200" topHeight="200" bottomHeight="200">
            <PluginDlg pluginName="Notepad++::InternalFunction" id="44085" curr="0" prev="-1" isVisible="yes" />
            <PluginDlg pluginName="Notepad++::InternalFunction" id="2051" curr="2415919103" prev="-1" isVisible="no" />
            <ActiveTabs cont="0" activeTab="0" />
            <ActiveTabs cont="1" activeTab="-1" />
            <ActiveTabs cont="2" activeTab="-1" />
            <ActiveTabs cont="3" activeTab="-1" />
        </GUIConfig>
```

My debug info:
```
Notepad++ v8.5.8   (64-bit)
Build time : Oct 15 2023 - 21:43:56
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Home (64-bit)
OS Version : 22H2
OS Build : 22621.2428
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    PythonScript (2)
```

**Comment by donho** [comment]
@Yaron10 
> Does NPP need to add extra code/checks dealing with manually messed files? - There might be no end to that.
> The user can mess some Registry entries and crash Windows.

MS Windows is out of my responsibility, but Notepad++ isn't.
In the perfect world, no application should crash.
In reality I do my best to prevent Notepad++ from crash.

**Comment by donho** [comment]
> Adding your provided value doesn't make my Notepad++ crash:
@rdipardo please ignore my previous message, I can reproduce the crash with debug build.
I will provide the fix ASAP. Thank you for your help.

**Comment by Yaron10** [comment]
@donho,

> In reality I do my best to prevent Notepad++ from crash.

👍 
I was just wondering what should be the correct balance between extra checks and performance.

> replace the `<GUIConfig name="AppPosition"` fields with letters or large numbers.

If the user intentionally modifies those fields (and it can't be caused by NPP itself), it's their problem.
Dealing with the various performance issues where NPP hangs (practically it's a crash) IS important. :) 

Thank you for https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e2fb15a70332488438a36e73742cb8d11cd716aa.

***

@rdipardo,

Could you please test https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e2fb15a70332488438a36e73742cb8d11cd716aa?

Thank you.

**Comment by donho** [comment]
@Yaron10 
> I was just wondering what should be the correct balance between extra checks and performance.

I understand your point.
However, even we do all the controls of read value at the startup, each control is just a simple value checking. I do believe there's no impact for the performance. 
OTOH, the crash could lead the vulnerability and be exploited by the hackers for the attack, especially config.xml is usually located in the non-protected zone.
For this reason any reproducible crash should be fixed, even it's due to PEBCAK.

**Comment by rdipardo** [comment]
@Yaron10 

> Could you please test [e2fb15a](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e2fb15a70332488438a36e73742cb8d11cd716aa)?

No more crashes. :+1:

**Comment by Yaron10** [comment]
@donho,

> However, even we do all the controls of read value at the startup, each control is just a simple value checking. I do believe there's no impact for the performance.

There must be _some impact_. And the more, the merrier. :)

> For this reason any reproducible crash should be fixed, even it's due to PEBCAK.

You have convinced me.
My first comment here was a response to:

> some additional security mechanism for checking the saved/read config.xml DockingManager data (IMO the checking/adjusting at the xml-data-reading-stage will be enough, users/OS could externally manipulate/corrupt the config.xml somehow...)

And that, like modifying `<GUIConfig name="AppPosition"` shouldn't result in a crash.

***

@rdipardo,

Thank you for testing and confirming.

@donho,

Thank you again for fixing it.

**Comment by xomx** [comment]
> A while back I posted a proof of concept showing how a crafted config.xml can make N++ execute arbitrary plugin functions when starting up: https://community.notepad-plus-plus.org/post/89445

So I finally took the time to try it out on a N++ plugin.
As a model case for my debugging, I chose a problem where the currently visible docked panel of the PluginScript (PS) plugin is not shown after the N++ restart while with another plugin (e.g. NppExec) it works as expected.

tl;dr - Conclusion:
- I am not going to add some more sophisticated security checks of the config.xml data for the DockingManager (as it is almost impossible or it needs a lot of additional code)
- it is up to plugins/users to behave themselves right in this matter
- I will just add a check for panels with zero sizes because there might be some previously hidden docked panels that the N++ users are not aware of. (Or maybe I will also add checks for some nonsense big sizes, e.g. for bigger than the current monitor size etc, but that is all.)


=================================================================


PythonScript issue debugging / possible-fix:

0) I used the "Show Console" PS plugin command and closed the N++ app (the relevant saved config.xml data is shown below), then I restarted N++ & debugged...

```
<GUIConfig name="DockingManager" leftWidth="200" rightWidth="593" topHeight="200" bottomHeight="165">
            <PluginDlg pluginName="Python Script" id="-1" curr="3" prev="-1" isVisible="yes" />
            <ActiveTabs cont="0" activeTab="-1" />
            <ActiveTabs cont="1" activeTab="-1" />
            <ActiveTabs cont="2" activeTab="-1" />
            <ActiveTabs cont="3" activeTab="0" />
</GUIConfig>
```

1) Problem of the PS `pszModuleName` & `dlgID` (in fact a zero based index of the plugin's published funcs array) in the PS [ConsoleDialog::doDialog()](https://github.com/bruderstein/PythonScript/blob/184c7cade64bccff7ddca3f765d409c59766175f/PythonScript/src/ConsoleDialog.cpp#L547)

```
m_data->pszModuleName = _T("Python Script"); // FIX: = _T("PythonScript.dll"); ... it should be the plugin filename!
m_data->dlgID = -1; /* IDD_CONSOLE */  // FIX: = 1 ... index of the relevant plugin func ("Show Console")
```

2) The PS "Show Console" displayed command name is in fact the [toggleConsole](https://github.com/bruderstein/PythonScript/blob/184c7cade64bccff7ddca3f765d409c59766175f/PythonScript/src/PythonScript.cpp#L173) PS func
  

3) When the N++ DockingManager init-code [called](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/cab4d40b3f1feadf146aacc748fab66e25f125c3/PowerEditor/src/Notepad_plus.cpp#L844) the docked PS code at the N++ startup after restart, the PS console stuff has not been initialized yet at this stage (g_console == false), so nothing happens - the PS console is not shown (I can fix this PS code if there will be an interest...):

```
static void toggleConsole()
{
	if (g_console)
	{
		CHECK_INITIALISED();
		if (MenuManager::getInstance()->s_menuItemConsoleChecked)
		{
			g_console->hideDialog();
		}
		else
		{
			g_console->showDialog();
		}
	}
}
```


4) Only when the N++ init is done and it is [calling](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/cab4d40b3f1feadf146aacc748fab66e25f125c3/PowerEditor/src/Notepad_plus_Window.cpp#L325) all its plugins with the `NPPN_READY`, the PS plugin is fully [initialized](https://github.com/bruderstein/PythonScript/blob/184c7cade64bccff7ddca3f765d409c59766175f/PythonScript/src/PythonScript.cpp#L299) at last

```
static void initialise()
{
    g_mainThreadID = ::GetCurrentThreadId();
	g_console.reset(new NppPythonScript::PythonConsole(nppData._nppHandle));

	pythonHandler = new NppPythonScript::PythonHandler(g_tPluginDir, g_tConfigDir, (HINSTANCE)g_hModule, nppData._nppHandle, nppData._scintillaMainHandle, nppData._scintillaSecondHandle, g_console);

	aboutDlg.initDialog((HINSTANCE)g_hModule, nppData);

	g_shortcutDlg = new ShortcutDlg((HINSTANCE)g_hModule, nppData, _T("\\PythonScript\\scripts"));

	g_console->init((HINSTANCE)g_hModule, nppData);

	MenuManager* menuManager = MenuManager::getInstance();
	//menuManager->idsInitialised();
	menuManager->populateScriptsMenu();
	menuManager->stopScriptEnabled(false);
	menuManager->initPreviousScript();
}
```


Conclusion:
It is almost impossible to check sanity of these plugin's commands ids in the config.xml DockingManager data from the N++ app, so I will not opt for that.

Note: If there is an interest(?), I could create a PR for fixing the PluginScript panel incorrect behavior described above.

**Comment by rdipardo** [comment]
> 1. Problem of the PS `pszModuleName` [ . . . ]
>
> ```
> m_data->pszModuleName = _T("Python Script"); // FIX: = _T("PythonScript.dll"); ... it should be the plugin filename!
> m_data->dlgID = -1; /* IDD_CONSOLE */  // FIX: = 1 ... index of the relevant plugin func ("Show Console")
> ```

The purpose of `TbData.pszModuleName` seems to be widely misunderstood by plugin devs, judging from this identical issue (actually two): mohzy83/NppMarkdownPanel#90

I can't see anything lacking in [the documentation][0]; each data member is annotated with original code comments, e.g,

~~~cpp
const TCHAR*  pszModuleName;  // it's the plugin file name. . .
~~~

Maybe it's not obvious enough that "file name" means "name *and extension*"? But without the extension, it's not really a file, is it?

[0]: https://npp-user-manual.org/docs/plugin-communication/#2057-nppm-dmmregasdckdlg

**Comment by vinsworldcom** [comment]
> Note: If there is an interest(?), I could create a PR for fixing the PythonScript panel incorrect behavior described above.

There is interest - https://github.com/bruderstein/PythonScript/issues/312 - and 2 failed pull requests as I did not understand the full issue until @rdipardo pointed it out to me in a comment over there.

Cheers.

**Comment by Tampa** [comment]
```
       <GUIConfig name="DockingManager" leftWidth="296" rightWidth="415" topHeight="200" bottomHeight="348">
            <FloatingWindow cont="4" x="1437" y="6" width="1914" height="1038" />
            <FloatingWindow cont="5" x="536" y="16" width="1441" height="1033" />
            <FloatingWindow cont="4" x="1437" y="6" width="1914" height="1038" />
            <PluginDlg pluginName="MarkdownViewer++" id="0" curr="1" prev="-1" isVisible="no" />
            <PluginDlg pluginName="Notepad++::InternalFunction" id="44085" curr="4" prev="1" isVisible="yes" />
            <PluginDlg pluginName="Notepad++::InternalFunction" id="44070" curr="5" prev="0" isVisible="yes" />
            <PluginDlg pluginName="PreviewHTML.dll" id="0" curr="4" prev="2" isVisible="no" />
            <PluginDlg pluginName="Notepad++::InternalFunction" id="44080" curr="5" prev="1" isVisible="no" />
            <PluginDlg pluginName="Notepad++::InternalFunction" id="44081" curr="0" prev="-1" isVisible="no" />
            <PluginDlg pluginName="Notepad++::InternalFunction" id="44084" curr="6" prev="1" isVisible="no" />
            <PluginDlg pluginName="NppFTP.dll" id="0" curr="7" prev="0" isVisible="yes" />
            <PluginDlg pluginName="Notepad++::InternalFunction" id="0" curr="3" prev="-1" isVisible="no" />
            <PluginDlg pluginName="NppMarkdownPanel" id="1" curr="8" prev="1" isVisible="no" />
            <PluginDlg pluginName="NppFTP.dll" id="99" curr="3" prev="-1" isVisible="no" />
            <PluginDlg pluginName="Notepad++::InternalFunction" id="44082" curr="0" prev="-1" isVisible="no" />
            <PluginDlg pluginName="ComparePlugin.dll" id="11" curr="1" prev="-1" isVisible="no" />
            <PluginDlg pluginName="ccc.dll" id="1" curr="1" prev="-1" isVisible="no" />
            <PluginDlg pluginName="dummy" id="0" curr="3" prev="-1" isVisible="no" />
            <PluginDlg pluginName="FunctionList.dll" id="0" curr="1" prev="-1" isVisible="yes" />
            <PluginDlg pluginName="NppDocShare.dll" id="0" curr="1" prev="-1" isVisible="no" />
            <PluginDlg pluginName="ComparePlugin.dll" id="9" curr="1" prev="-1" isVisible="no" />
            <ActiveTabs cont="0" activeTab="-1" />
            <ActiveTabs cont="1" activeTab="-1" />
            <ActiveTabs cont="2" activeTab="-1" />
            <ActiveTabs cont="3" activeTab="-1" />
            <ActiveTabs cont="4" activeTab="0" />
            <ActiveTabs cont="5" activeTab="0" />
        </GUIConfig>
```

This seems related, disregard if not.

I could not get the Function List view to show up. Document List and and Folder as Workspace I could see. Document Map also worked, but always showed up really large, size of what I had the html preview set to(which I could also toggle fine). nppftp also didn't work.

This happened after I closed all the undocked views to get a clearer view. After a restart I could not get them back.

I removed the entire section I pasted above and now it works again. Suspect somewhere in that it gets confused with the docking manager on what is visible. And no, they weren't just minimized to zero.

By default these views are all docked in the main window right? So a button to reset them to that state would be neat to have to solve this. Just hard reset them if they break(much like apparently removing the section) so they can be undocked and moved again. Course getting to the root cause would be nice, but in the meantime and for the future just a reset would be really nice to have :)

**Comment by xomx** [comment]
@Tampa 

Your report is valid but rather belongs to the issue #14478. There is a flaw in the undock/redock N++ handler code for which I still does not have a simple fix. 

> `<PluginDlg pluginName="Notepad++::InternalFunction" id="44084" curr="6" prev="1" isVisible="no" />`

> This happened after I closed all the undocked views to get a clearer view. After a restart I could not get them back.

This line in your config.xml is for the missing Function List. Note the `curr="6"` - there is no entry for that in your `FloatingWindow` part (there should be a `FloatingWindow cont="6"` line for it).

> I removed the entire section I pasted above and now it works again. 

Yes, this is currently the only way to solve this. 

> By default these views are all docked in the main window right?

Yes.

> So a button to reset them to that state would be neat to have to solve this. Just hard reset them if they break(much like apparently removing the section) so they can be undocked and moved again. Course getting to the root cause would be nice, but in the meantime and for the future just a reset would be really nice to have :)

I am still hoping that I (or anyone else) can fix that. 

But I have also to say - if we look at your proposal from another angle, not as a one-time hack but as a general feature-request, maybe it would not be bad to have a way how to reset the N++ panels-view to the default "factory" state. After all, even a user without any error status might appreciate a quick return to the original N++ settings. So I recommend - go for it and create a separate feature request issue just only for that. The question is an appropriate form/GUI-placement in the N++, but this should be discussed in that new FR-issue, not here.

---
OTOH - I already have a fix for this issue with the disappearing docked panels, but I made the mistake of trying to solve these two issues together. Now I need to find a time to rewrite the fix of this issue and leave the undocked/redocked #14478 solution for later.
