### ISSUE TITLE
"Find (volatile)" is always case sensitive

### ISSUE THREAD

**Issue by NeilS-Wpg** [notepad-plus-plus/notepad-plus-plus#13145]
### Steps to Reproduce the Issue
case sensitive -- casE sENsitive -- case sensitive   <== paste the present line in to a tab and try it

### Expected Behavior
Search should follow dialog settings, same as non-volatile analogs, esp. non-volatile Select and Find

### Debug Information
I discovered it in 8.1.9 (32-bit portable); confirmed in 8.4.5 (32-bit portable) & 8.4.6 (64-bit, normal install). They all have different plugins.

**Comment by alankilborn** [comment]
The user manual states:
_All dialog-free search actions do preserve the current search options set in the Find dialog like Match case or Wrap around._

I'm wondering if the phrase "do preserve" there should be "respect" -- @pryrt ?

And if it _should_ be "respect" then this issue is for a bug.

**Comment by alankilborn** [comment]
Behavior of `Match Case` as outlined above by @NeilS-Wpg is confirmed in N++ 8.4.9.

The "volatile" commands have other deficiencies, when comparing against other similar commands, as well as stated user manual behavior for non-dialog based searches:

* `Match whole word only` setting is ignored (always performs a non-whole-word search)
* `Wrap around` setting is ignored (always wraps around)

**Comment by donho** [comment]
> And if it _should_ be "respect" then this issue is for a bug.

I don't think if we can define any bug according the description of Notepad++ User Manual, though it's an important reference.
I would ask myself the following question, from users' perspective: 
Is it a bug if volatile search always case sensitive? If yes, what's the good behaviour for the most of users?

**Comment by pryrt** [comment]
I will start by saying that I don't believe (and never have) that the manual itself provides the definition of "bug" (though that would make my job more fun: I'd just get to describe how I want Notepad++ to behave, and then you'd have to fix it because it's a bug ;-) ).  There are plenty of times when the manual has gotten it wrong, and needed to be fixed.

However, in this case, the description from the manual _matched_ user expectation, and Notepad++ behavior did not match the expectation (as shown by the creator of this issue).  The expectation is that "Find (Volatile) Next" behaves exactly like "Select and Find Next", except that the search-string doesn't get saved (and is thus "volatile").  Since "Select and Find Next" honors the case-sensitivity option in the Find dialog, user expectation (and historically documented behavior) is that "Find (Volatile) Next" would also honor the case-sensitivity option.

Thus, in my opinion, the label of "bug" vs "enhancement" is not the important point; what's important is that Notepad++ provide a well-defined and consistent behavior across multiple similar features.  The consistent and expected behavior, in this case, is for "Find (Volatile) Next" to honor that option just like "Select and Find Next" does; and that's what @alankilborn's PR implements.

**Comment by alankilborn** [comment]
@pryrt @donho 
Maybe it is a testament to how good the user manual has become, that it is more accurate in certain respects than the software itself!

**Comment by donho** [comment]
@pryrt 
> I will start by saying that I don't believe (and never have) that the manual itself provides the definition of "bug" (though that would make my job more fun: I'd just get to describe how I want Notepad++ to behave, and then you'd have to fix it because it's a bug ;-) ). There are plenty of times when the manual has gotten it wrong, and needed to be fixed.

It's undeniable that Notepad++ User Manual is well done, and even me I have to check in Notepad++ User Manual site sometimes to make sure Notepad++'s behaviour :) - The statement of @alankilborn made me say that but I ensure you that you've done an awesome job!


> Thus, in my opinion, the label of "bug" vs "enhancement" is not the important point; what's important is that Notepad++ provide a well-defined and consistent behavior across multiple similar features.

So we are on the same page.

> Maybe it is a testament to how good the user manual has become, that it is more accurate in certain respects than the software itself!

Amen.

> in this case, is for "Find (Volatile) Next" to honor that option just like "Select and Find Next" does; and that's what @alankilborn's PR implements.

> All dialog-free search actions do preserve (*or respect*) the current search options set in the Find dialog like Match case or Wrap around.

Well, the description above could be a "better" behaviour than the current one. However, I'm not convinced it's the best behaviour (which the most users expect). 
Regarding case sensitive (or not) for Find volatie, we can have 3 behaviours:
1. case sensitive (current behaviour)
2. case insensitive
3. use find dialog settings

The issue is about the 1st one, so let's say it is too restrictive.
When users launch a volatile search on a fly without invoking find dialog, they won't expect to open find dialog for modifying the case sensitive state, if it's not what they want. So the 3rd one is not suitable.
As  a result, it seems to me that the 2nd one (case insensitive) is the best behaviour for volatile search - it's less strict and it will find everything in the text. If user want case sensitive, they can always open find dialog.

The same argument can be applied to "Mach Whole Word Only" & "Wrap around" - I just tested, it's the case already.

**Comment by alankilborn** [comment]
So let's summarize what has been deemed correct behavior, at least as far as I understand it:

**_Find (Volatile) Next_** / **_Find (Volatile) Previous_** :
* uses the selected text as the search text
* uses _Match case_ = false (as this is most "flexible", i.e., "less strict")
* uses _Match whole word only_ = false (as this is most "flexible")
* uses _Wrap around_ = true (as this is most "flexible")
* uses _Search mode_ = _Normal_

...and for comparison, another "dialog-less" searching mechanism:
**_Select and Find Next_** / **_Select and Find Previous_** :  
* copies the selected text to _Find what_ box of _Find_ window, then uses it
* uses _Match case_ setting from _Find_ window
* uses _Match whole word only_ setting from _Find_ window
* uses _Wrap around_ setting from _Find_ window
* uses _Search mode_ = _Normal_

**Comment by donho** [comment]
@alankilborn 
Yes, both are reasonable behaviours to me.
