### ISSUE TITLE
Where is my spaces??

### ISSUE THREAD

**Issue by LexaGV** [notepad-plus-plus/notepad-plus-plus#13182]
In settings I have preference Tab size=4, [x] Replace by space
BUT! When I edited plain *.txt file (using tabs to align text), those tabs was saved to the file! It's a bug. Why tabs wasn't replaced according to my settings?

**Comment by alankilborn** [comment]
Existing tab characters aren't replaced.  Only new usage of the Tab key follows the setting you mention.  If you want existing tab characters to be converted, use _Edit_ menu > _Blank Operations_ > _TAB to Space_.

If that's not your problem, you need to be more explicit in what you mean; i.e., fill out the issue template instead of deleting the whole thing out before posting.

Additionally, yours seems more of a question, and questions belong on the support site, [HERE](https://community.notepad-plus-plus.org/).

**Comment by LexaGV** [comment]
@alankilborn First, it's silly solution "keep existing tabs" - I set " [x] Replace by space" to FOREVER eliminate idiotic 'tab' from my files! It's not 1980 to save bytes. Editor AT LEAST must have setting [x] Keep existing tabs (which should be OFF by default). Second, options page doesn't give me any hint that setting doesn't touch existing tabs. It's fail of usability.

I explained my issue and it's obvious bug (not a question) - no need in formal items.

**Comment by alankilborn** [comment]
>options page doesn't give me any hint that setting doesn't touch existing tabs.

Not everything can be fully explained in the limited space in the controls of the program; the user manual exists to supplement.  The online user manual is available from within Notepad++ via this menu selection:

![image](https://user-images.githubusercontent.com/77065706/220202335-39283a53-88b0-41fb-b7ca-f10e645b514c.png)


It is clear in the user manual what _Replace by space_ does; see [HERE](https://npp-user-manual.org/docs/preferences/#language:~:text=%E2%98%90-,Replace%20by%20space,-%3A%20when%20set%2C%20hitting).
It doesn't say anything about doing any conversions on data already in the document, simply what happens when the Tab key is pressed.

Please CLOSE this issue.

**Comment by LexaGV** [comment]
It's usability issue and lack of proper settings. AT LEAST I expect one more setting
    [ ] Keep existing tabs
This setting will hint user that just "[x] Replace by space" IS NOT ENOUGH.
Software should improve instead of hiding/postponing existing problems.

**Comment by alankilborn** [comment]
I disagree with most of your assessment and I personally don't feel that any additional settings are required.

However, after some thought, it seems as if the use of _Replace by space_ on the UI _could_ be interpreted to mean that a search-and-replace operation will take place.  I have created #13186 to deal with this.

**Comment by ArkadiuszMichalski** [comment]
This setting is for the currently inserted characters, not for what already existed in the file. Conversion is responsible for this and you have the appropriate separately commands. You can call them manually or automatically in some sequence with other commands/events (e.g. via macro or plugins).

This will not change, because there will be requests for which tabs should be changed (all, leading, trailing, etc.). Your specific behavior should be resolved through the available mechanisms (as a last resort, there are plugins like PythonScript/NppExec/LuaScript).
