### ISSUE TITLE
NPP jumps from "new 1" to "new 3" when document map is visible

### ISSUE THREAD

**Issue by RodneyRabbit** [notepad-plus-plus/notepad-plus-plus#13194]
### Description of the Issue

If the document map is enabled, NPP will not create a "new 2" document but will jump to "new 3".
I believe this is similar to issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8677 that was fixed.

### Steps to Reproduce the Issue

1. Open NPP.
2. Click View > Document Map.
3. Create a new document.

### Expected Behavior

See "new 1" then "new 2" in the tab / document list.

### Actual Behavior

See "new 1" then "new 3" in the tab / document list.

### Debug Information

Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 22H2
OS Build : 19045.2673
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.4.24)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppXmlTreeviewPlugin (2)
    XMLTools (3.1.1.13)
    zoomdisabler_x64 (1.2)

The issue no longer occurs when the document map is disabled.
Probably not high priority, just a mild inconvenience for me. I copy paste into 10+ documents at a time from other sources "output1.txt" to "output10.txt" etc, and like to use the document map. It would be easier to align source and destination documents if they were created as "new 1-10" instead of "new 1" then "new 3-11".

**Comment by alankilborn** [comment]
It isn't related specifically to the document map.  

Try this alternative StR:

Close the document map if it is open.
Restart N++ so that you have a single document open, `new 1`.
Press Ctrl+f and do a _Find All in Current Document_ search so that the _Search results_ window/panel appears.
Create a new tab/doc via Ctrl+n; observe that `new 3` is created.

The numbering has to do with how many "Scintilla" buffers are open.
The _Search results_ window is a Scintilla buffer.
_Document Map_ is apparently also a Scintilla buffer.

The real intent of tabs named "new X" is to just give you a quick starting point for creating a document, and that you should save to a hard-named disk file as soon as possible.  If you make this a part of your workflow, it doesn't matter what the "new X" tabs are named.  Sure, you're not forced to do this, but it is a reasonable workflow.

**Comment by donho** [comment]
891e8f936e03586b0bbf2850523a4af72701f622
