### ISSUE TITLE
Search history not updated using "Select and Find Next"

### ISSUE THREAD

**Issue by thdoan** [notepad-plus-plus/notepad-plus-plus#1322]
When you search using the "Select and Find Next" command, the search history should be updated just as if you were to press Ctrl+F, enter/paste some text, and press Enter.

**Comment by MetaChuh** [comment]
this is fixed in newer versions.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
>this is fixed in newer versions.

It is NOT "fixed" in newer versions, but I am not convinced the original issue is valid anyway.

Do we ***want*** the text from a "select and find next/previous" to be added to the history?  I never thought about it until now, and I'm not sure of the answer.  Given that before thinking about it (or seeing this issue) I would have expected it to ***NOT*** be added to the history, I'm going to go with "no, I don't want it added". :)
