### ISSUE TITLE
Wrong Categories in Shortcuts Mapper

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#13285]
**STR:**
Settings -> Shortcuts Mapper.

**Result:**
Some commands are listed under the wrong Category.
A few examples:

![תמונה](https://user-images.githubusercontent.com/10229320/222902043-32662456-e978-4e7d-a718-acb489fe31d9.png)
![תמונה](https://user-images.githubusercontent.com/10229320/222902302-3652e48a-7bc5-486c-b582-8d730a288061.png)
![תמונה](https://user-images.githubusercontent.com/10229320/222902224-7d1e5e91-6098-476b-9727-c975299a3d27.png)

***

Notepad++ v8.4.9   (64-bit)
Build time : Feb 24 2023 - 10:04:40
Path : C:---notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 20H2
OS Build : 19042.985
Current ANSI codepage : 1255
Plugins : 
    ComparePlus (1.1)
    HTMLTag (1.3.6)
    MenuIcons (2.0.2)
    PythonScript (2)
    _CustomizeToolbar (4.2)

**Comment by alankilborn** [comment]
Move/Clone belong under _View_
Text Direction belong under _View_
Style Configurator belongs under _Setting_

And shouldn't _Setting_ be _Settings_ ?

**Comment by Yaron10** [comment]
@alankilborn,

_Settings_, _Language_ and _Tools_.
And Format to Encoding?

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/081e8ad11b019a4cac082416ba855a98549a4fe1/PowerEditor/src/WinControls/shortcut/shortcut.cpp#L1229

If you're interested.

**Comment by ArkadiuszMichalski** [comment]
These are categories for shortcuts and they don't necessarily have to match what you see in the top menu. Although if they are similar it is easier to locate where a given command is located.

Actually `Fromat` represents `Encoding` menu and some EOL conversion commands.

![image](https://user-images.githubusercontent.com/2730894/222916128-9a97ba17-467e-47c5-9442-6f015065af61.png)

Maybe EOL conversion should belong to `Edit` (like trim and others) and `Format` rename to `Encoding`.

These categories are based on the value of `IDM_xxx`. Probably these values will not change because it can affect many places in the code. Mayb we could add some exceptions in `CommandShortcut()` that will assign some shortcuts to other categories.

**Comment by Yaron10** [comment]
@ArkadiuszMichalski,

> Although if they are similar it is easier to locate where a given command is located.

Sure.

> Maybe EOL conversion should belong to Edit (like trim and others) and Format rename to Encoding.

👍 

I haven't tested it - but are the conditions in `CommandShortcut::CommandShortcut()` structured properly?

**Comment by ArkadiuszMichalski** [comment]
>I haven't tested it - but are the conditions in CommandShortcut::CommandShortcut() structured properly?

I think it's OK, just a bit weird. But thanks to this, you do not need to specify the exact range (in most case).

The names of the categories come directly from the definitions:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/0d9b16634d55fe9bee1833c2f6be40921b8fa5a6/PowerEditor/src/menuCmdID.h

EOL conversion still sits on `FORMAT`.
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/0d9b16634d55fe9bee1833c2f6be40921b8fa5a6/PowerEditor/src/menuCmdID.h#L387-L389

Changing these definitions each time when commands being moved to a different menu may require many changes (including all translation files).  Were there any PRs where category name in command were changed due to relocations?

I think the categories for shortcut should not be changed and should stay in line with these definitions. But for standard users, it's probably more useful to know where a command resides in the `Main menu`. Especially when the tab in `Shortcut Mapper` is named `Main menu`.
![image](https://user-images.githubusercontent.com/2730894/222967175-b2760171-a0bf-49fc-bf3b-b256e65899f8.png)

This `Category` column could display 2 things:
- category name (without translation)
- name of the item in the `Main menu` (with translation)

Maybe if the category is the same as translated `Main menu` entry name, then display only a single string. For example:
```
File
About | ?
Format | Edit
Format | Language
Setting | Settings
```
or duplicate:
```
File | File
About | ?
Format | Edit
Format | Language
Setting | Settings
```

For me personally above presentation  would be more useful, because sometimes it's hard to locate a command in the `Main menu` (we have different names for categories and menu items).

Adding a new separate column `Menu entry` is probably too much? Or not show the category at all, only the position occupied in the main menu?

**Comment by Yaron10** [comment]
@ArkadiuszMichalski,

> I haven't tested it - but are the conditions in CommandShortcut::CommandShortcut() structured properly?
>> I think it's OK, just a bit weird. But thanks to this, you do not need to specify the exact range (in most case).

👍 

> The names of the categories come directly from the definitions:
...
Changing these definitions each time when commands being moved to a different menu may require many changes (including all translation files).

👍 

> Were there any PRs where category name in command were changed due to relocations?

I have no idea. :)

> But for standard users, it's probably more useful to know where a command resides in the Main menu. Especially when the tab in Shortcut Mapper is named Main menu.

I was only referring to the `Main menu` tab.

> This Category column could display 2 things:

I don't quite understand your suggestion.

Aren't most of the entries OK now?
Can't the entries which are not compatible with the main menu be changed by slightly modifying the conditions in `CommandShortcut::CommandShortcut()`?

Thank you.

**Comment by ArkadiuszMichalski** [comment]
>This Category column could display 2 things:
>>I don't quite understand your suggestion.

Display original category name and menu entry name where this command resides (second could be translated), like:
```CategoryName | MenuEntryName```

So for English would be:
```
File | File
About | ?
Format | Edit
Format | Language
Setting | Settings
```

For some commands that were moved to other place we can adjust their `MenuEntryName` (like mentioned above EOL conversion).

**Comment by Yaron10** [comment]
How about replacing `Category` with `Menu` and making all entries correspond to their menus?
Wouldn't that be more useful and simpler for most users?

**Comment by ArkadiuszMichalski** [comment]
>Wouldn't that be more useful and simpler for most users?

I wrote the same above https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13285#issuecomment-1455283110. But displaying the categories would also be helpful, although mainly for people playing with the code. 

On the other hand we have everything we need to correct it (to one way or other way).
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/c8e4e671dad405d60e95ba483991a4b3b77bf2c2/PowerEditor/installer/nativeLang/english.xml#L592
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/c8e4e671dad405d60e95ba483991a4b3b77bf2c2/PowerEditor/installer/nativeLang/english.xml#L601-L611

Note that the translation does not change the original values of `_category` so if we ever need them, they will be available. We only need to make a slight adjustment for those that have been moved to other menu. I only note that instead of `About` should appear `?`, and that can be a bit ambiguous (like unrecognized).

It's just a matter of determining what this column should show, the rest is small stuff.

**Comment by Yaron10** [comment]
@ArkadiuszMichalski,

> I only note that instead of About should appear ?, and that can be a bit ambiguous (like unrecognized).

Personally I prefer `About` in the menu as well. But this is probably not going to be changed.
What do you think of `About (?)` in the Shortcuts Mapper?

> It's just a matter of determining what this column should show

Would you mind settling this with Don?
 
Thank you for the additional info and for working on this issue.
