### ISSUE TITLE
Wrong Syntax Highlighting for HTML/JavaScript ECMA Template Strings

### ISSUE THREAD

**Issue by Borkason** [notepad-plus-plus/notepad-plus-plus#1332]
Wrong Syntax Highlighting for HTML/JavaScript ECMA Template Strings within SCRIPT element, if coding language is set to HTML.

![htmljavascript](https://cloud.githubusercontent.com/assets/2971735/12165851/933a90f2-b521-11e5-8229-7c5ca5285433.PNG)

**Comment by madebycambiamentico** [comment]
i think javascript cannot read multiple line as string. you should escape the row end with backslash "\" like this:
```javascript
var multilineString = 'beginning\
        something else after spaces... and...\
end string';
```

else you should concatenate strings:
```javascript
var multilineString = 'beginning'+
        'something else... and...'+
        'end string';
```

**Comment by Borkason** [comment]
It's valid JavaScript alright.

**Comment by madebycambiamentico** [comment]
whoa, sorry, i didn't saw it was the template string we were talk about (" ` " and not " ' ").
yes, i confirm the bug (for PHP too). fine in js files

**Comment by dev-101** [comment]
This issue is still present in Notepad++ 7.6.3 (Release Date: 2019-01-27)
except **template strings** are now called **template literals**.

Some screenshots:

.js file is fine/ok
![test js-template-literal-notepad example](https://user-images.githubusercontent.com/5383059/53680585-11c46280-3cde-11e9-8a2a-9cb6a64ba233.png)

.html files - highlighting is broken
![test html-template-literal-notepad example](https://user-images.githubusercontent.com/5383059/53680595-21dc4200-3cde-11e9-8b98-e0326241500d.png)

**Comment by donho** [comment]
It's due to the limit of HTML lexer in Scintilla.
It won't be fixed until Scintilla includes this fix.

**Comment by dev-101** [comment]
Thanks for explanation, so this is a known bug to them?
