### ISSUE TITLE
Column Editor: value in config.xml does not match user's preference

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#13370]
If the last selected section is "Text", we have "number" in config.xml. And vice-versa.

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5645ca150bf9b24813d5da7ee3a061e1306837d9/PowerEditor/src/Parameters.cpp#L2497
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5645ca150bf9b24813d5da7ee3a061e1306837d9/PowerEditor/src/Parameters.cpp#L4095

It seems the values should be swapped.

***

Notepad 8.5.1

**Comment by alankilborn** [comment]
This happened because, in this "ancient" code part of the codebase, it was decided to use a variable/tag name of "_mainChoice" and then give it boolean meaning.  Well, if "_mainChoice" is false, say, what does that mean?  Who knows, without looking it up each time?  And apparently, the coder "forgot" to look it up right at the time of writing to the config file.  Thus, bug.  It's a non-user bug, but still...
