### ISSUE TITLE
Dragging tab takes too long if document list presents

### ISSUE THREAD

**Issue by maxox** [notepad-plus-plus/notepad-plus-plus#13479]
if the number of tabs is above 150, dragging tab from the last position would trigger the the document list refresh for couple seconds.
it would take like forever to move the last one to the first one.

https://user-images.githubusercontent.com/7052069/230031302-e6ce9f72-c7cb-479a-9748-3425c854e722.mp4

**Comment by molsonkiko** [comment]
I tried opening like 150 tabs on both an older version of NPP and also the most recent version.
In both cases, moving tabs wasn't too slow.
Admittedly, the tabs were all empty documents (I just mashed Ctrl+n a bunch of times), but that probably shouldn't change how long it takes the document list to update.

**Comment by Orden4** [comment]
This has been annoying me for months now. The thing is that I have a ton of tabs. I do try to periodically clear the bulk of them, but it builds up again before long. However, the ones at the top are always the same, in the same order. Sometimes I close a tab by accident, and then I have to go through this absolutely painful process of moving that tab to the start again, since restore recent closed file doesn't retain its position either. NavigateMe isn't really a solution to this, since it's just a lot more convenient to have them all at the top than to have them spread around and always navigate my way around via searches.

So anyway, to assist with getting this issue fixed: I've confirmed that this issue occurs even with all plugins removed
The reason that I suspect that you did not experience this issue is because you probably tried to move documents around near the top of the list. I don't really understand what exactly is happening behind the scenes, but it sort of boils down to that it will scroll through the document list until it has returned to your currently selected tab. If you try to get the last tab to the front in this way, you'll find that it speeds up over time as you get closer to the start of the document list.
