### ISSUE TITLE
Move Line Up leaves odd Change History status

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#13534]
### Description of the Issue
See StR.

### Steps to Reproduce (StR) the Issue
1. Have some text and a caret position on an intermediate line, e.g.:
![image](https://user-images.githubusercontent.com/77065706/232137755-a19fd8e3-892c-462b-bd09-ed5ddd89a643.png)
2. Execute Shift+Ctrl+UpArrow (_Move Up Current Line_) 

### Expected Behavior
"Change History" marker positions like this:
![image](https://user-images.githubusercontent.com/77065706/232138312-d1999ac9-c39f-4adc-b61e-cd7013fd1aed.png)

### Actual Behavior
Observe strange "Change History" marker positions:
![image](https://user-images.githubusercontent.com/77065706/232138105-b9ea3c7f-3e1d-490c-a04e-9c575b7ba2e0.png)

### Debug Information
Notepad++ v8.5.2   (64-bit)
Build time : Apr  4 2023 - 19:55:32
Path : W:\npp.misc\_NoBackup\Releases\npp.8.5.2\npp.8.5.2.portable.x64\notepad++.exe
Command Line : -titleAdd="8.5.2 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 21H2
OS Build : 19044.2728
Current ANSI codepage : 1252
Plugins : 
    ColumnsPlusPlus (0.0.0.1)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    PythonScript (3.0.14)

**Comment by nyamatongwe** [comment]
This is the designed and expected behaviour. Turn on per-character change marks and visible line ends and you'll see:

![LineMoveChange](https://user-images.githubusercontent.com/225818/232165354-5ebb259a-0732-4342-9ff8-8861fcc230b2.png)

The line is first removed, placing a deletion in change history at the start of the 'e' line (it is after the CRLF of the 'c' line), then the line is inserted at its new position placing an insertion in change history covering the `d\r\n` text.

The deletion is at the start of one line which is also the end of the preceding line and it could be displayed for either line or both. There could be options to choose where to show line start/end deletions but the current behaviour seems the best in most cases.

**Comment by alankilborn** [comment]
>This is the designed and expected behaviour. 

It seems like it is rather just a consequence of its implementation.
For me, the expected behavior remains what I put above for "Expected Behavior".

>...but the current behaviour seems the best in most cases.

Sure, if you say so.
I'll close as "won't fix".
