### ISSUE TITLE
Regression: menu strings are cut off

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#13556]
**STR:**
Replace `hebrew.xml` with [this file](https://github.com/notepad-plus-plus/notepad-plus-plus/files/11290996/hebrew.zip) (I've modified the currently provided file with some English entries).
Use the binary of the current master (https://github.com/notepad-plus-plus/notepad-plus-plus/commit/15decdb3d93a165ce362743ba32164391373687a).
Change NPP interface to Hebrew.
Restart NPP.
Edit -> Line Operations.

**Result:**

![תמונה](https://user-images.githubusercontent.com/10229320/233502869-ff71071e-4e00-4434-bc8a-bca2cdb28d2d.png)

**Expected (with binary prior to https://github.com/notepad-plus-plus/notepad-plus-plus/commit/fff5f9b24c1e7a6f33633b665c06e8785f6a3455):**

![תמונה](https://user-images.githubusercontent.com/10229320/233503465-4fc77e14-d8d6-4ce7-b6a9-c4a2173b3559.png)

***

Notepad++ v8.5.2   (64-bit)
Build time : Apr 20 2023 - 09:12:20
Path : ---Notepad++.x64.Release.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 20H2
OS Build : 19042.985
Current ANSI codepage : 1255
Plugins : 
    ComparePlus (1.1)
    HTMLTag (1.3.6)
    PythonScript (2)
    _CustomizeToolbar (4.2)

**Comment by Yaron10** [comment]
Reproducible on Windows 7 as well.

**Comment by rdipardo** [comment]
[Quick fix](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/15decdb3d93a165ce362743ba32164391373687a/PowerEditor/src/WinControls/shortcut/shortcut.h#L26):

~~~diff
diff --git a/PowerEditor/src/WinControls/shortcut/shortcut.h b/PowerEditor/src/WinControls/shortcut/shortcut.h
index a4b25ae4..62c32c12 100644
--- a/PowerEditor/src/WinControls/shortcut/shortcut.h
+++ b/PowerEditor/src/WinControls/shortcut/shortcut.h
@@ -23,7 +23,7 @@
 #include "Common.h"
 #include "menuCmdID.h"
 
-const size_t nameLenMax = 64;
+const size_t nameLenMax = 128;
 
 class NppParameters;
 
~~~

64 is the max number *of bytes*. UTF-8 strings can easily exceed that when converted to (*single-byte*) ANSI strings (which fff5f9b does):

~~~sh-session
> python3 -c "print(len(bytes('מיין שורות לקסיקוגרפית בסדר עולה (Ignore Case)', 'utf8')))"
74
~~~

**Comment by Yaron10** [comment]
@rdipardo,

Great. :+1: 
Thank you for looking into it.

There are also some `GetMenuString()` calls across the project.
The `cchMax` parameter seems too small in some cases. Some of the values can be unified and more consistent.

**Comment by rdipardo** [comment]
@Yaron10,
> The `cchMax` parameter seems too small in some cases.

The particular issue with `hebrew.xml` is caused by precisely this code path:

_`const char *name` = `menuName` = "מיין שורות לקסיקוגרפית בסדר עולה (Ignore Case)"_

[csc.setName(name)] &#x2192; [lstrcpynA(_menuName, menuName, nameLenMax)]

The XML data is UTF-8, but TinyXML is too old to handle Unicode gracefully, so fff5f9b goes out of its way to accommodate TinyXML by turning everything into ANSI when building the menu, then turning everything *back* into Unicode before drawing the GUI.

##### Before fff5f9b

| Unicode &#x2192; Unicode |
| :--: |
| `wchar_t` &#xD7; 64 &#x003D; `wchar_t` &#xD7; 64 |

##### After fff5f9b

| Unicode &#x2192; ANSI &#x2192; Unicode |
| :--: |
| `wchar_t` &#xD7; 64 &#x2248; `char` &#xD7; 2[^1] &#xD7; 64 &#x2248; `wchar_t` &#xD7; 64 |

The same *amount* of memory is reserved in both case; in the *latter*, the meaning of `nameLenMax` changes from *character* count to *byte* count. As you said:

>  Some of the values can be unified and more consistent.

Good luck with this one; I don't have a Visual Studio license anymore.

[^1]: *`wchar_t` &#x2248; `char[2]`*

[csc.setName(name)]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/bc7d6b26a4614da83e117ae9429f2ee6d57e5914/PowerEditor/src/localization.cpp#L1046
[lstrcpynA(_menuName, menuName, nameLenMax)]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/bc7d6b26a4614da83e117ae9429f2ee6d57e5914/PowerEditor/src/WinControls/shortcut/shortcut.cpp#L160

**Comment by Yaron10** [comment]
@rdipardo,

Thank you for the detailed explanation. 👍

**Comment by Yaron10** [comment]
BTW,

I've tested `polish.xml`.
If you add a few more characters to the long Sort commands, some are cut off.

**Comment by rdipardo** [comment]
New report: https://community.notepad-plus-plus.org/post/86291

**Comment by Yaron10** [comment]
Thank you @rdipardo.

**Comment by Yaron10** [comment]
> Notepad++ v8.5.2 (64-bit)
Build time : **Apr 20 2023 - 09:12:20**

The problem does not exist in the official v8.5.2.
Caused by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/fff5f9b24c1e7a6f33633b665c06e8785f6a3455.
