### ISSUE TITLE
Language Menu

### ISSUE THREAD

**Issue by Timski0** [notepad-plus-plus/notepad-plus-plus#13551]
### Description of the Issue
When Language is selected from the menu bar on a low-resolution monitor the scroll-down button at the bottom is not visible and any languages which do not fit on the display are not accessible 

### Steps to Reproduce the Issue

1. use a monitor with a vertical resolution set below about 1040
2. select Language from the main menu
3. 
### Expected Behavior

bottom scroll button should display, (ideally an alternative method of selecting the language would be better as the menu is sluggish even when displayed correctly)

### Actual Behavior

The scroll-down button at the bottom is not visible

### Debug Information

![Language](https://user-images.githubusercontent.com/89320698/233135598-f23223e6-c7cf-4211-bb6c-06e719af711b.jpg)

**Comment by alankilborn** [comment]
@Timski0 

Do you have a single or multiple monitor setup?

**Comment by Timski0** [comment]
Thanks @ozone10 I missed that, Problem Solved

**Comment by alankilborn** [comment]
>bottom scroll button should display

How can the problem be solved??
If the bottom scroll button is not displayed?

**Comment by Timski0** [comment]
Sorry @alankilborn, you are correct, the issue is still present, however, the workaround suggested by @ozone10 is sufficient to make the menu usable. in answer to your previous question, I have a 2 monitor setup, one is 1080p, and the other is 1440 x 900

**Comment by alankilborn** [comment]
@Timski0 The still-present problem can't get fixed if you close the issue.  A workaround is fine, but it doesn't help the next person that encounters the problem (well, unless they find the workaround, and are happy with it), and the person after that, and so on...

The problem happens because the overall desktop, when considered as a big rectangle of all of your monitors, dips "lower" on another monitor, than on the monitor you screenshotted, thus the system "thinks" it is showing you the entire menu and the bottom arrow.

@ozone10 Is this just a Windows bug or is there something Notepad++ can do about it?
