### ISSUE TITLE
hangs on paste through wine

### ISSUE THREAD

**Issue by brianlambert93** [notepad-plus-plus/notepad-plus-plus#13693]
### Description of the Issue
With the update today or possibly an earlier but still recent update, I can't paste into Notepad++ anymore

### Steps to Reproduce the Issue
1. copy some text from somewhere
2. open a new document Ctrl+N
3. paste text in Ctrl+V

### Expected Behavior
text will appear in the document

### Actual Behavior
box appears from system saying Notepad++ is not responding

### Debug Information
could not copy paste the debug info, had to retype it. although copying did not cause any hangs, it just didn't put it in my clipboard

Notepad++ v8.5.3 (32-bit)
Build time : May 15 2023 - 06:07:16
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Microsoft Windows 7 (64-bit)
OS Build : 7601.0
Current ANSI codepage : 1252
WINE: 6.0.3
Plugins : 
   IndentByFold (0.7.3)
   mimeTools (2.9)
   NppConverter (4.5)
   NppExport (0.4)

not sure if this is wine making this dialog box or the linux mint
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/49658731/f5d27b96-786e-41ae-8a8d-2e91ba550523)

**Comment by superbonaci** [comment]
it happens only with wine logs or with just any text? How much lines are those?

**Comment by brianlambert93** [comment]
Just with any text. I was trying to paste things from the terminal or from email like I would do before.

I may have caused this by deleting some files and breaking wine. I was about to reinstall my computer and wanted to backup my home folder and so just started deleting things I thought were just caches. I think I might have just deleted the whole ~/.wine folder or something. So if this doesn't happen to anyone else it is probably not an issue with notepad++

**Comment by superbonaci** [comment]
The first thing to know is if it's a wine or notepad++ issue.

**Comment by brianlambert93** [comment]
I did reinstall my computer so I can't look into it further, I have not yet installed wine again.

**Comment by brianlambert93** [comment]
sorry I didn't realize I was the only one who could do that

**Comment by MullPointer** [comment]
Think this has solved itself for me as well, but posting here for the next person. After operating fine for a couple of months through Wine, notepad++ suddenly started hanging on paste for me today. After looking into it for rather too long, I restarted the computer and found the issue fixed. I think the issue was triggered when I was forced to restart X with ctrl+alt+backslash due to a graphics card issue. So again likely more a Wine than notepad++ issue. 

Here are my Wine logs from when the issue occurred:
``38048.930:045c:0460:Ret  user32.GetClipboardData() retval=00000000 ret=140236302
38048.930:045c:0460:Call user32.GetClipboardData(0000000d) ret=140236359
38048.930:045c:0460:trace:globalmem:LocalAlloc flags 0, size 0x400
38048.930:045c:0460:Call ntdll.RtlAllocateHeap(00240000,00000300,00000400) ret=1740457f7
38048.930:045c:0460:trace:heap:RtlAllocateHeap handle 0000000000240000, flags 0x300, size 0x400, return 00000000042D55D0, status 0.
38048.930:045c:0460:Ret  ntdll.RtlAllocateHeap() retval=042d55d0 ret=1740457f7
38048.930:045c:0460:Call ntdll.RtlSetUserValueHeap(00240000,00000300,042d55d0,042d55d0) ret=174045810
38048.930:045c:0460:trace:heap:RtlSetUserValueHeap handle 0000000000240000, flags 0x300, ptr 00000000042D55D0, user_value 00000000042D55D0.
38048.946:045c:0460:Ret  ntdll.RtlSetUserValueHeap() retval=00000001 ret=174045810
38048.946:045c:0460:trace:globalmem:LocalAlloc return 00000000042D55D0
38048.948:045c:0460:trace:clipboard:NtUserGetClipboardData CF_UNICODETEXT sending WM_RENDERFORMAT to 0x1002e
38048.948:045c:0460:trace:class:NtUserGetClassName 0x1002e 0 0x21efe0
38048.948:045c:0460:trace:sync:NtQueryInformationAtom c012 -> L"__wine_clipboard_manager" (0)
38048.948:045c:0460:trace:message:spy_enter_message     (0x1002e) L"{__wine_clipbo}" [0305] WM_RENDERFORMAT sent from tid 0460 wp=0000000d lp=00000000
38048.948:045c:0460:trace:msg:send_inter_thread_message hwnd 0x1002e msg 305 (WM_RENDERFORMAT) wp d lp 0
38048.948:045c:0460:trace:event:call_event_handler 2073 DestroyNotify for hwnd/window (nil)/600000e
38048.948:045c:0460:trace:event:process_events processed 1 events, returning 0
38053.497:045c:0484:Ret  ntdll.NtDelayExecution() retval=00000000 ret=17407509c
38053.497:045c:0484:Ret  KERNEL32.Sleep() retval=00000000 ret=1401263ee
38053.497:045c:0484:Call user32.PostMessageW(001202e8,00000430,00000000,00000000) ret=140126421
38053.497:045c:0484:trace:class:NtUserGetClassName 0x1202e8 0 0x55ee500
38053.497:045c:0484:trace:msg:NtUserPostMessage hwnd 0x1202e8 msg 430 (WM_USER+48) wp 0 lp 0
38053.503:045c:0484:Ret  user32.PostMessageW() retval=00000001 ret=140126421
38053.503:045c:0484:Call KERNEL32.Sleep(00001b58) ret=1401263ee
38053.503:045c:0484:Call ntdll.NtDelayExecution(00000000,054efd18) ret=17407509c
38060.509:045c:0484:Ret  ntdll.NtDelayExecution() retval=00000000 ret=17407509c
38060.509:045c:0484:Ret  KERNEL32.Sleep() retval=00000000 ret=1401263ee
38060.509:045c:0484:Call user32.PostMessageW(001202e8,00000430,00000000,00000000) ret=140126421
38060.509:045c:0484:trace:class:NtUserGetClassName 0x1202e8 0 0x55ee500
38060.509:045c:0484:trace:msg:NtUserPostMessage hwnd 0x1202e8 msg 430 (WM_USER+48) wp 0 lp 0
38060.510:045c:0484:Ret  user32.PostMessageW() retval=00000001 ret=140126421
38060.510:045c:0484:Call KERNEL32.Sleep(00001b58) ret=1401263ee
38060.510:045c:0484:Call ntdll.NtDelayExecution(00000000,054efd18) ret=17407509c
38067.516:045c:0484:Ret  ntdll.NtDelayExecution() retval=00000000 ret=17407509c
38067.516:045c:0484:Ret  KERNEL32.Sleep() retval=00000000 ret=1401263ee
38067.516:045c:0484:Call user32.PostMessageW(001202e8,00000430,00000000,00000000) ret=140126421``
