### ISSUE TITLE
BASH HEREDOC color for ending DELIMITER

### ISSUE THREAD

**Issue by RobMahn** [notepad-plus-plus/notepad-plus-plus#13740]
### Description of the Issue
In a BASH script, the HEREDOC ending delimiter is colored in the style of **HERE Q**
instead of **HERE DELIM**.

Thus, the delimiter colors do not match and then ending delimiter looks like HEREDOC content.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by rdipardo** [comment]
@RobMahn, your issue is valid but was submitted to the wrong project.

The code highlighting component is maintained [here](https://github.com/ScintillaOrg/lexilla). Other editors using the same component behave exactly like N++.

![gscite-536-bash-herdoc](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59004801/c187e94b-bb31-4202-8525-9c35841cad3c)

- Go to the menu in the top corner of your original comment and select <kbd>Edit</kbd>.

    ![gh-edit-comment-btn](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59004801/e3bfc357-edaa-43c0-9662-2a9cd7d94d8c)

- Copy all the markup that appears in the edit box and submit it to the other project as [a new issue](https://github.com/ScintillaOrg/lexilla/issues/new/choose).

**Comment by RobMahn** [comment]
Thank you for pointing me in the right direction.  The issue has been re-filed here:
https://github.com/ScintillaOrg/lexilla/issues/177
