### ISSUE TITLE
Ctrl+Alt+M Shortcut have more than one Operation assigned

### ISSUE THREAD

**Issue by Vignesh-Venkatraman** [notepad-plus-plus/notepad-plus-plus#13786]
### Description of the Issue
Ctrl+Alt+M is menioned as shortcut for

Plugins > Compare plus > Compare file/Selection to keyboard
Plugins > JSTool > JSFormat

When I try to use the Shortcut it always executes Compareplus Operation but I wanted to Format Json.

Refer attachment for more details.

![Compare n++](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/25180811/842744a5-79bc-408f-8ea3-ebcbf849b1a9)
![JStool n++](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/25180811/6bc89619-6402-4b23-b20d-61de384793eb)

**Comment by alankilborn** [comment]
Plugins are not the responsibility of Notepad++.
This site is for Notepad++ issues.
Thus, this issue is misplaced -- please close this issue.

However, you can solved the conflict by going to Notepad++'s _Settings_ menu, choosing _Shortcut Mapper..._ and changing keycombinations on the _Plugin commands_ tab.
