### ISSUE TITLE
AdditionalIncludeDirectories: notepadPlus.vcxproj or notepadPlus.Cpp.props

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#13798]
Some time ago the `AdditionalIncludeDirectories` entries were moved from _notepadPlus.vcxproj_ to _notepadPlus.Cpp.props_.

https://github.com/notepad-plus-plus/notepad-plus-plus/commit/7077e304aa1245f2b674067082e36545bac5194b has re-added them to _notepadPlus.vcxproj_.

Is that intentional/necessary?

**Comment by donho** [comment]
@Yaron10
Non, it's not intentional. 
It was modified by VS while using its editor for adding new include directories.
It's not harmful, but still, let's keep editing manually notepadPlus.Cpp.props for adding stuffs in it to maintain notepadPlus.vcxproj as clean as possible.

Thank you for revealing this issue.

**Comment by Yaron10** [comment]
@donho,

Thank you for the explanation and for your recent work. 👍
