### ISSUE TITLE
Settings->Style Configurator...:Font Style:Font Size - incorrect pixel font height is used (glyph height is 1px less then in other app - notepad.exe)

### ISSUE THREAD

**Issue by atlka** [notepad-plus-plus/notepad-plus-plus#13863]
### Description of the Issue
While choosing font size from list notepad++ really uses choosen size - 1pt.

### Steps to Reproduce the Issue
1. Choose some font in notepad++ and for example in Windows Terminal settings: for example Fira Code 12pt.
2. Enlarge view by Win+"+" and see the differences in bitmaps used.

### Expected Behavior
If "Font size" in settings is 12pt size font the appropriate size should be used in editor - not smaller or bigger.

### Actual Behavior
Really used font size is -1p smaller then the one set in config panel.

### Debug Information
Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3155
Current ANSI codepage : 1250
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

Left is Fira Code 11pt with wt.exe and right is npp.exe with Fira Code 12pt - the sam bitmap size is used.
![firawtnpp11_12](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/52749958/4b7c55a9-1e8c-4a38-8b41-9566becbd6be)

**Comment by alankilborn** [comment]
More of an apples to apples compare:  Use notepad.exe.

What I did:

* Set Notepad++ to use Fira Code Retina size 9; turn OFF DirectWrite; use a "Normal text file" format (so lexing doesn't mess with anything)

* Set notepad.exe to use Fira Code Retina size 9

* Note that for size 9 on both there is a corresponding match when using a "ruler" on the screen (for some data on a line approximately 100 characters long)

* Increase the font size to 10 on Notepad++; note that there is no longer a "ruler" match with notepad.exe's rendering -- the N++ font is bigger

* Decrease the font size to 8 on Notepad++; note that there is no longer a "ruler" match with notepad.exe's rendering -- the N++ font is smaller

I don't see a problem here.

**Comment by atlka** [comment]
I am using a bitmap only TTF font which has only 12px and 16px bitmaps which gives 9pt and 12pt font heights at default virtual 96DPI MS Windows display - https://www.pg.gda.pl/~atlka/fonts/terminusa.ttf - but with npp 9pt size is working while I choose 10pt in settings. 12pt size cannot be used at all because we can not choose 13pt from displayed list. In other programs I can use 9pt and 12pt sizes without problems specifying those sizes in settings.

**Comment by alankilborn** [comment]
I've no idea what any of that means, sorry.  Still, I doubt Notepad++ is wrong in this.

**Comment by atlka** [comment]
Another example of difference beetwen npp.exe and notepad.exe with Consolas 28pt
![consolas28npp](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/52749958/5a0e3de4-c6d2-48c0-b9a3-d873da6faff1)
As You can see bitmap used by npp is 1px smaller the this used by notepad so something is not working correctly here. If we have a TTF font with bitmaps in some sizes these bitmaps will not be used at all.

**Comment by pryrt** [comment]
> An example of difference beetwen npp.exe and notepad.exe with Consolas 28pt below: As You can see the bitmap used by npp is 1px smaller then bitmap used by notepad so something is not working correctly here. 

"Here" appears to be the appropriate term, because it may be different at your "here", but it's not different here at my "here".

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/17455758/9e5b885c-2532-4912-b89c-fa4993a9e0d5)

That's a screenshot with Consolas 28 on Notepad++ and notepad.exe: they are exactly the same number of pixels tall.

And here it is in the same two windows, with DejaVu Sans Mono 10pt:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/17455758/a443c3e5-4b7d-4257-9fdf-81952a4500f0)

Once again, they match in height exactly.  I do not believe Notepad++ is rendering the font size any differently than notepad.exe.

You might want to try Notepad++ > **View > Zoom > Restore Default Zoom** (maybe you accidentally zoomed in/out without noticing).  Or MS Notepad > **View > Zoom > Restore Default Zoom** -- if either one is zoomed, it won't match the other.

Or you mentioned "virtual 96dpi" -- that implies that maybe your monitor isn't _really_ that DPI; the drivers for high-DPI monitors can sometimes do weird things, and Notepad++ cannot control what your _virtual_ dpi will show; maybe your driver is scaling differently for Notepad++ compared to notepad.exe.

**Comment by atlka** [comment]
That was it!
I hit **View > Zoom > Restore Default Zoom** and now it looks correctly.
Thanks for your attention.

**Comment by atlka** [comment]
That was it!
I hit View > Zoom > Restore Default Zoom and now it looks correctly.
Thanks for your attention.
