### ISSUE TITLE
Notepad++ 8.5.4.0 crashes due to ComparePlus 

### ISSUE THREAD

**Issue by AlexPi86** [notepad-plus-plus/notepad-plus-plus#13956]
### Steps to Reproduce the Issue

1.  Notepad++ 8.5.4.0
2.  Install last ComparePlus plugin
3.  Install last NppTextFX2 plugin
4. ComparePlus -> Compare for 2 files

### Expected Behavior

Files are compared

### Actual Behavior

Notepad++ crashes

### Debug Information

Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : C:\SOFT\14. Notepad++Portable\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise LTSC 2021 (64-bit)
OS Version : 21H2
OS Build : 19044.3208
Current ANSI codepage : 1251
Plugins : 
    ComparePlus (1.1)
    HexEditor (0.9.12)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (2.0.5)
    NppTextFX (1.4.1)
    NppTextViz (0.4.2)
    NppToolBucket (1.10.6622.41516)
    Remove Duplicate Lines (1.3)
    SessionMgr (1.4.4)
    XMLTools (3.1.1.13)

**Comment by rdipardo** [comment]
Please report the bug to https://github.com/rainman74/NPPTextFX2/issues and close this issue

**Comment by rdipardo** [comment]
#### Update

The problem seems to be fixed by pnedev/comparePlus@58c415a

For some reason, TextFX invalidated the parameters to [a window procedure callback][0] used by comparePlus in version 1.1.0. That callback has been removed, so the next release of comparePlus should be fine.

I would suggest asking @pnedev to push a new release if possible.

In any case, this issue can now be closed.

[0]: https://github.com/pnedev/comparePlus/blob/7ed84a89ed33781bb33d6d2d250499f4d1336ed0/src/Compare.cpp#L1222
