### ISSUE TITLE
Offensive Installer - Please Fix

### ISSUE THREAD

**Issue by jcoog** [notepad-plus-plus/notepad-plus-plus#14052]
### Description of the Issue
I support over 14,000 users at hospitals across multiple states in the USA. I am on the phone with nurse practitioners daily, recommending that they use Notepad++ (instead of Windows Notepad) when attempting to solve complex issues with medical data that is transmitted in text file format.

Our contracts are with state and federal agencies. We have gone as far as to reference Notepad++ as a great time saver and we tout it’s awesome features.

However, the installation screen is a continual embarrassment to us, please see the included picture. It is making our organization look juvenile, and it is personally a great embarrassment to be on the phone with doctors, hospital CEO’s, and nurses especially, while helping them to install your software.

So, I respectfully ask: Please remove the statement about sex from your installation screen. Imagine how it makes a nurse practitioner feel when she is tasked with providing medical care to an abused sex worker.

Thanks.
John Coogan

![np](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/143201774/dd69cb77-68df-4a4e-b2ee-8cd6bda836d7)

**Comment by xomx** [comment]
I see that the project maintainer labeled this as accepted, so the following solutions are probably a waste of time, but all the same - you can:
- use a portable Notepad++
- run the installer with the /S (silent) argument
- fork the Notepad++ project and keep it synchronized with the current master

> Imagine how it makes a nurse practitioner feel when she is tasked with providing medical care to an abused sex worker.

An argumentative foul, but ok. Imagine this:
- you create an open-source software
- you contribute endless hours of work on it for free
- the SW becomes very useful and well-known
- thanks to its widespreadness, you have started to have problems with not being able to please everyone
- and now the fun is over, you can't even speak freely

**Comment by rdipardo** [comment]
> * and now the fun is over, you can't even speak freely

Nobody asked for the removal of the Linus Torvalds Easter egg, the apparent source of the quote:

~~~sh-session
$ git grep  -En "(Software is like)" | awk '{print $1,$2,$3,$4,"..."}'

PowerEditor/installer/nppSetup.nsi:333:BrandingText "Software is like ...
PowerEditor/src/Notepad_plus.cpp:7572: {TEXT("Linus Torvalds"), QuoteParams::slow, ...
~~~

Anther way to frame the issue is:

- Once enterprise users come to depend on your software, maybe it's time to grow up a little bit?

Dirty jokes are juvenile stuff at the very least, whether or not they offend someone's P.C. *mores*.

**Comment by donho** [comment]
*Sigh* Time to change the slogan.

**Comment by xomx** [comment]
@rdipardo 
Make no mistake - I am NOT for such quote in a SW myself. In fact, I have already removed the quote from the installer few times when I needed so before. But I also respect when someone else likes to have it (for whatever reason, even a juvenile one). After all it is so easy to create a Notepad++ Mature Edition fork. And pushing to hide that quote has the same effect as removing :-)

**Comment by gwinkless** [comment]
> Anther way to frame the issue is:
> 
> * Once enterprise users come to depend on your software, maybe it's time to grow up a little bit?

s/depend on/pay for/

By being snotty and shouting about your "enterprise user" status to get something removed, you are taking time away from the developers that they could be spending on other good things for all the other users of the software. You are literally stealing from the users because of your fake morality. Grow up and either pay for your software or accept the tiny inconvenience.

**Comment by tuenut** [comment]
@jcoog Why your nurses install a software on pc? Why you showing them how to install software? Why not install necessary apps silently and remotely by using domain policies or smthn?
Also as people said before - it is a free open source - you pay nothing for app and waiting for it should be meet to your "enterprise" standarts (whereas you still asking nurses to install soft manually). If you want to be looks like an adult then use enterprise paid solutions. Or, because it is open source, fork it, like as people said before.

**Comment by azjio** [comment]
It is unlikely that nurses need the functionality of Notepad++.
Use AkelPad, it does not contain gay propaganda or politics. By the way, AkelPad has well-organized code highlighting; you can use regular expressions. At work, I have text files that are convenient to read with technical words highlighted. Moreover, txt files are recognized automatically based on the text in the file and switch to special highlighting. I posted my assembly on the Internet and even did it in English upon request. I won’t give links, the author of the subject will delete them anyway.

**Comment by jonathanlermitage** [comment]
Ca me rappelle NetBeans (à l'époque sous le giron d'Oracle) qui refusait les plugins sous licence WTFPL, sous prétexte que c'était "offensant".  
Enfin bon, nous devons respecter ton choix, c'est la moindre des choses. Et merci pour ton logiciel, c'est une merveille !  
Ha, et _fuck, fuck, fuck fuck fuck fuuuuck_ (c'est l'intro d'un album de The Offspring, au cas où) aux puritains. Vala un truc qu'ils n'auront pas.

**Comment by yopgaming** [comment]
You cannot complain about free software on a such large scale of users. 

- Make a fork
- It's possible to buy software on Microsoft Windows, such as Ultra Edit. 
- Keep it and deploy a silent installer, pre-installed images.

**Comment by jcoog** [comment]
Wow.  I'm not sure where the personal attacks in some responses are coming from.

I'm not an enterprise status person.  I'm just a guy living hand-to-mouse, working a help desk.  The help desk we provide is free of charge to 1000's of locations.  They don't pay for it.  I can't suggest they purchase software.  I don't work at these 1000's of separate locations so I can't auto install software via domain policies.  I can't create a fork (I assume a fork is a recompiled version with my desired features - I am lacking understanding here).  I can't host software downloads.  I am paid to answer phones and do some internal development.

The files in question are highly technical billing transactions that originate from every kind of development tool and server out there.  Linux, IBM, Microsoft, Oracle, MySQL, Apple, etc.  File types are stream. Cr, CrLf, Lf, tape-block padded, etc.  The non-technical users we end up supporting can't actually solve their file problems.  They basically have to involve their vendor (who we don't have a relationship with, we we can't contact vendors directly).  About the best thing we can do is educate the end-user just enough so they can pass along the data/file issue to their vendor for resolution.  Perhaps this helps explain why we like Notepad++ so much, because it levels the playing field of variety with the files, and it's free (thanks again).

We began suggesting that users search the internet for a product called Notapad++ as a much better alternative to Windows Notepad.  Am I making any sense ... I don't control these users, I can only make suggestions.

I'm sorry that the tone of my original post was somewhat frustrated.  Admittedly, I was in a moment of frustration over what appears to be a stark contrast in professionalism in one of my favorite software apps.  Please realize that I have been using Notepad++ for almost 2 decades now.  It just seemed like after all this time maybe it wasn't unreasonable to request a change.

I see earlier posts regarding 'accepting the issue' and 'perhaps it's time to change the slogan'.  Regardless of how this turns out, thanks for your consideration of the request, it is genuinely appreciated.  :)

**Comment by azjio** [comment]
**jcoog**
You haven’t watched the “About the Program” dialogue yet, sometimes it contains gay propaganda, sometimes it collects money to kill Ukrainians.

**Comment by FueledBy-Pizza** [comment]
End of a golden era.

**Comment by donho** [comment]
I often receive complaints from some conservative users (who are many) about the installer slogan, but I don't care and ignore them. The case of @jcoog is different, as he has given me solid and valid arguments instead of just saying "I'm appalled". I agree with his points, so I decided to remove the old slogan. This is my free choice as the author of a free software, and there is nothing more to say. I hope this is the end of the story.

**Comment by davefl67** [comment]
What a ride. When I saw the OP by @jcoog, it kind of pissed me off. Looked like your average "Karen" clutching their pearls and making demands. I mean the quote is not "dirty," it's barely suggestive.

Reading through the entire thread, I get it. And I agreed with his situation. When @donho decided to make the adjustment to the code because he agreed with the points of the post. 

Us computer geeks really do grow up. Some of us even grow old. Good for you, guys.

**Comment by azjio** [comment]
> Your joke sucks.

It wasn't a joke. It is forbidden to tell the truth in your media. A coup d'etat took place in the western part of Ukraine, which the eastern part of Ukraine did not agree with. The western part has been shelling and killing the eastern part of Ukraine for 8 years. The western part is not the voice of the whole of Ukraine and has not privatized the opportunity to call itself Ukraine and the other part of Ukraine non-Ukrainians. When you pay the western part of Ukraine to kill the eastern part of Ukraine, then you are collecting money to kill Ukraine.
