### ISSUE TITLE
Security issues: Notepad++ reads and writes past the end of a buffer bounds on opening a crafted file.

### ISSUE THREAD

**Issue by Stefan1200-de** [notepad-plus-plus/notepad-plus-plus#14073]
Notepad++ reads and writes past the end of a buffer bounds on opening a crafted file.
This bugs still exists in v8.5.6

More details:
https://securitylab.github.com/advisories/GHSL-2023-092_Notepad__/

Reference numbers from GitHub Security Labs:
GHSL-2023-092, GHSL-2023-102, GHSL-2023-103, GHSL-2023-112

CVE numbers and score:
CVE-2023-40031 (7.8 High)
CVE-2023-40036 (5.5 Medium)
CVE-2023-40164 (5.5 Medium)
CVE-2023-40166 (5.5 Medium)

**Comment by dstrzelec** [comment]
Is there an estimate of when a release will be available that closes these vulns?

**Comment by slin-cls** [comment]
I see a possible cause of CVE-2023-40031 in the UniConversion.cxx, in the UTF8FromUTF16 function. The remaining size of the destination buffer is not checked in the loop.
As I see the code belongs to the Scintilla component. But as I'm not a contributor in this project, I don't know if the code is only the integration of the component or it is the Scintilla itself. If it comes from the Scintilla project, the bug should be fixed there first. Is anyone here who knows the origin of this code and where it should be fixed?

**Comment by domivogt** [comment]
The CVE is a ridiculous exaggeration of the situation.  While it is technically a "buffer overflow" is really only an off-by-two bug with practically zero chance to allow for arbitrary code execution:

--

If the document has an odd length (malformed utf16), the CVE suggests that the incomplete last utf16 character at the end of the file is still converted to utf8.

But the length calculation is two bytes off:

  > newSize = len + len/2 + 1;

E.g. if "len" is 1, the formula results in 1 + 0 + 1 = 2 where it should be 4.  The fix is very simple.  Round up "len" before the calculation:

 > len = len + (len & 1); // If len is odd, add one to make it even.
 > newSize = len + len/2 + 1;

There is _no_ way that this leads to arbitrary code execution.

--

There's probably also an off-by-one read bug in the same situation (the missing byte at the end of file must come from somewhere.)

**Comment by rdipardo** [comment]
@slin-cls,

> I don't know if the code is only the integration of the component or it is the Scintilla itself. If it comes from the Scintilla project, the bug should be fixed there first. Is anyone here who knows the origin of this code and where it should be fixed?

The only third-party code identified in the advisory comes from [uchardet], which has [already been patched] in a newer version than what N++ currently uses. [GHSL-2023-102]/[3] can be resolved with a simple dependency update.

Scintilla's core components are [hosted on SourceForge][sci] and would never receive GitHub's attention.

[uchardet]: https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/src/uchardet
[already been patched]: https://gitlab.freedesktop.org/uchardet/uchardet/-/commit/2694ba6363d4b8555d8c57eb4e85b081f754f6d3
[GHSL-2023-102]: https://securitylab.github.com/advisories/GHSL-2023-092_Notepad__/#issue-2-global-buffer-read-overflow-in-chardistributionanalysishandleonechar-ghsl-2023-102
[3]: https://securitylab.github.com/advisories/GHSL-2023-092_Notepad__/#issue-3-global-buffer-read-overflow-in-nscodingstatemachinenextstate-ghsl-2023-103
[sci]: https://sourceforge.net/p/scintilla/code/ci/default/tree/

**Comment by donho** [comment]
CVE-2023-40164 is merged: 5402622
GHSL-2023-112: A Change Request has been done, waiting reply.

**Comment by Slapbox** [comment]
Since I haven't used it in a while I went to uninstall until there's an update. Since there's the existing concerns about security, when the unsigned installer asked for admin privileges I was in the mindset to virus-scan it. While it's marked clean by nearly every vendor, I found the uninstaller's behaviors/capabilities a bit concerning: https://www.virustotal.com/gui/file/7022af4ff6b2dcb3fd856d0d6f8b8b66faaa22068903e574954e2ed62272d667/relations

I'm no security expert so I don't know how common these are in generic uninstallers, but I don't know why it would need:

> Open clipboard
> Capture webcam image
> Permissions Requested: SE_LOAD_DRIVER_PRIVILEGE (This in particular drew my attention)
> Contacted domains: windowsupdatebg.s.llnwi.net

Can anyone shine some light?

**Comment by speneos** [comment]
Thank you for the updates. @donho When is the expected release date for update please to resolve these CVEs? Thank you

**Comment by donho** [comment]
@speneos 
When it's ready.

**Comment by donho** [comment]
CVE-2023-40164 merged: 5402622abc1e0fd9477d3e4645240cc97791c081
GHSL-2023-112 merged: 4b66d80b2f310fc3d6948c36ca44608b3b9a7a5d
GHSL-2023-102 merged: ea063246f16a73334ce84934152499c249e626f6
GHSL-2023-103 merged: 8c561ba74b35a48d102f9057ff20491f6be05ca7

Thank @JarLob for his contribution!

**Comment by aledeniz** [comment]
> Since I haven't used it in a while I went to uninstall until there's an update. Since there's the existing concerns about security, when the unsigned installer asked for admin privileges I was in the mindset to virus-scan it. While it's marked clean by nearly every vendor, I found the uninstaller's behaviors/capabilities a bit concerning: https://www.virustotal.com/gui/file/7022af4ff6b2dcb3fd856d0d6f8b8b66faaa22068903e574954e2ed62272d667/relations

This is unrelated, you should have raised a separate issue.

**Comment by realityexists** [comment]
The timeline posted in the [linked advisory](https://securitylab.github.com/advisories/GHSL-2023-092_Notepad__/) paints a _very_ bleak picture of this project's maintainer's attitude to security. 4 months and 4 releases with fixes such as [Minor style bug](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13728), but without the fix for a critical vulnerability (arbitrary code execution), no replies to the security researcher repeatedly trying to get this fixed, and the fix was only finally released weeks after public disclosure? Anyone every opening files they don't completely trust must seriously consider using a different editor.

**Comment by vablings** [comment]
> The timeline posted in the [linked advisory](https://securitylab.github.com/advisories/GHSL-2023-092_Notepad__/) paints a _very_ bleak picture of this project's maintainer's attitude to security. 4 months and 4 releases with fixes such as [Minor style bug](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13728), but without the fix for a critical vulnerability (arbitrary code execution), no replies to the security researcher repeatedly trying to get this fixed, and the fix was only finally released weeks after public disclosure? Anyone ever opening files they don't completely trust must seriously consider using a different editor.

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14073#issuecomment-1700740629

Please learn to read and count

**Comment by eabase** [comment]
> Since I haven't used it in a while I went to uninstall until there's an update. Since there's the existing concerns about security, when the unsigned installer asked for admin privileges I was in the mindset to virus-scan it. While it's marked clean by nearly every vendor, I found the uninstaller's behaviors/capabilities a bit concerning: https://www.virustotal.com/gui/file/7022af4ff6b2dcb3fd856d0d6f8b8b66faaa22068903e574954e2ed62272d667/relations
> 
> I'm no security expert so I don't know how common these are in generic uninstallers, but I don't know why it would need:
> 
> > Open clipboard
> > Capture webcam image
> > Permissions Requested: SE_LOAD_DRIVER_PRIVILEGE (This in particular drew my attention)
> > Contacted domains: windowsupdatebg.s.llnwi.net
> 
> Can anyone shine some light?

This is incredibly disturbing. The uninstaller is calling the content delivery network and collecting significant personal and os info that should not be exfiltrated from your computer. 

Please file a separate issue.

**Comment by Slapbox** [comment]
@eabase see #14368. I won't have time to follow up on this. I removed Notepad++ entirely from my devices. I'm not sure how much attention an issue can get when there are over 2k open.
