### ISSUE TITLE
[feature request] Search in TABS.

### ISSUE THREAD

**Issue by Zibri** [notepad-plus-plus/notepad-plus-plus#14135]
I usually have more than 200 tabs opened in notepad++
It would be nice to have a search option to search in the open tabs.
Most of those tabs are scraps that are not even saved...
It would be very handy.

**Comment by HmiHps** [comment]
Maybe a search in tab names?

**Comment by alankilborn** [comment]
Doesn't make much sense to me, but...

**Comment by CennoxX** [comment]
@HmiHps Do you mean, the option should be renamed to "Find All in All Opened Tabs"?

**Comment by alankilborn** [comment]
>...should be renamed to "Find All in All Opened Tabs"?

I don't think this is what OP means but there is some merit for a rename:

* In some places in the UI, the nomenclature "Tab" is used; e.g. _Apply Color to Tab_; _Close Multiple Tabs_.
* In other places in the UI, the nomenclature "Document" is used; e.g. _Find All in Current Document_, _Find All in All Opened Documents_.

The nomenclature should be unified.  I'm neutral on which way to go, I see merits for both "Tab" and "Document".  "Tab", however, is shorter and there are plusses for being shorter.

**Comment by Zibri** [comment]
> > nice to have a search option to search in the open tabs
> 
> ![image](https://user-images.githubusercontent.com/77065706/267345310-9da3d678-44c0-46bb-bffb-c03a69206164.png)
> 
> Please CLOSE this issue.

Damn... I didn't see that... sorry guys...

**Comment by alankilborn** [comment]
But I still think there is merit in getting the "tab" / "document" naming consistent.

@donho, what do you think?  See https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14135#issuecomment-1717363489

If Don agrees, I will make a new issue on exactly that; otherwise, I won't bother.

@pryrt Your opinion on this would be a good datapoint as well.

**Comment by donho** [comment]
@alankilborn 
There are TAB (character) and tab, that could be confusing. So I prefer the term "Document" - no ambiguity to me.

**Comment by HmiHps** [comment]
> in All Opened Tabs"?

I mean search in labels of Tabs. Because when you have 200 tabs it could be hard to find the one you want to see.
It could be useful but since last comment of Zibri I understood that this was not his request

**Comment by alankilborn** [comment]
>There are TAB (character) and tab, that could be confusing. So I prefer the term "Document" - no ambiguity to me.

That makes sense.

Something like _Close Multiple Tabs_, though, still feels ambiguous.  It could just as easily be _Close Multiple Documents_.  (And indeed, I think "document" is better in this application.)

Unlike _Apply Color to Tab_, which is fine the way it is, because in this case the color is applied to the "tab" in the page control, NOT the "document".  But, it still overlaps the tab-character notion.  :-(

**Comment by pryrt** [comment]
Interesting.  I had thought that the user interface was reasonably consistent: in most places, "tab" seemed to refer to the GUI element, which you can move around (**View > Tab > Move Tab Forward/Backward**), or colorize (**Apply Color To Tab**); whereas "document" usually referred to the underlying text itself, which you can search (**Find in All Open Documents**) or save to a file.  But the **View > Move/Clone Current Document** and the tabbar's right-click **Move Document** menus use "document" when I would have called it the "tab", so I wouldn't call it 100% consistent.  And I would think it would be "document", not the "tab", that got closed.

I still think the color refers to "tab", not the "document", so maybe I should narrow my definition to "the 'tab' is the title piece on a tabbar, whereas the panel where the text is and the text itself is the 'document' -- in which case, moving the document from one view to another doesn't violate the definition (though it's actually moving/cloning both the document and its tab under my newly-reworded definitions).

Whether the user manual completely agrees with my mental definition is a bit uncertain -- I vaguely remembering trying at one point to make it better match those distinctions, but I wouldn't guarantee I caught them all.  But I'll wait until a final verdict is rendered...

(And now it looks like this meta-discussion might be moot, because the OP apparently actually wanted to search through the tab names, not through the document text.)

**Comment by alankilborn** [comment]
>(And now it looks like this meta-discussion might be moot, because the OP@HmiHps apparently actually wanted to search through the tab names, not through the document text.)

Not moot, as I volunteered earlier to make a new issue on just the "document" vs. "tab" thing, if it has merit.  I'm still not sure @donho thinks ANY change is warranted...perhaps he needs to weigh in again.
