### ISSUE TITLE
Right Click context menu button "N" shortcut still not working

### ISSUE THREAD

**Issue by wongcc2012** [notepad-plus-plus/notepad-plus-plus#14158]
### Description of the Issue
Using the keyboard menu key (right click context key) from the text file / script file. the keyboard shortcut N key no longer working

### Steps to Reproduce the Issue

1. Select any text file / .bat  / any kind of file
2. the N key edit with notepad ++ is missing
3. 

### Expected Behavior
Right click key, N can go to the edit with notepad ++ application

### Debug Information

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/111074201/5d55b75f-b6ab-46f1-9998-943914225e0c)

**Comment by xomx** [comment]
For the classic right click menu it has been fixed in the NppShell v1.2 by https://github.com/notepad-plus-plus/nppShell/pull/40 (I think it is in any N++ installer v8.5.5+). New Win11 menu still does not support this (a MS "feature", not a N++ limitation).

With N++ v8.5.7:

![npp-classic-menu-ampersand-fixed](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/d467a489-69a3-4e13-b35c-b638cdb0ee3e)

**Comment by wongcc2012** [comment]
Sorry, so I have to install  NppShell v1.2 and Npp 8.5.7+?

**Comment by xomx** [comment]
Just reinstall your N++ with any v8.5.5+ installer.
Sometimes it then also needs logoff/logon (or Windows restart) to complete the older NppShell extension replacement.

**Comment by wongcc2012** [comment]
thank you!
