### ISSUE TITLE
Possible (?) minor bug in JSON parser

### ISSUE THREAD

**Issue by JMoulding1958** [notepad-plus-plus/notepad-plus-plus#14150]
### Possible minor bug in JSON parser
Parser flags an error in valid(?) JSON string

### Steps to Reproduce the Issue

1. Open JSON file
2. Format JSON file - works perfectly
3. Parse JSON file: flags error: "Syntax error (severity = FATAL) at position nnn (char '}'): JSON Lines document does not contain exactly one JSON document per line"

### Expected Behavior
No error

### Actual Behavior
Error flagged with final curly bracket position

### Debug Information

This is the formatted JSON string that caused the error:
{
	"results": {
		"message": "User does not exist||Invalid supply type",
		"status": "No Content",
		"code": 204,
		"requestid": ""
	}
}
The problem appears to lie with the "||" pipe characters in the message field pair value.  If I remove or escape them,  the parser no longer reports an error.  I didn't think the pipe was a reserved character in JSON.

The parser error can also be removed by adding a trailing comma to the final field pair, like this:
		"requestid": ""**,**
	}

Which is odd, as I believe the last field pair in any object within a JSON string should not have a trailing comma.

My assumptions re. correct JSON formatting may (of course) be completely wrong, hence the question mark in the title.  If they are, then apologies for timewasting.

Thank you for such a brilliant product.

Cheers,

John

**Comment by molsonkiko** [comment]
It's a good thing I noticed this issue, because I'm the maintainer for [JsonTools](https://github.com/molsonkiko/JsonToolsNppPlugin), which is the plugin you're having an issue with.

Issues with __the core functionality of Notepad++ (not its plugins)__ should be posted here, because the core developers are the ones who can solve them.

__Issues with the plugins should be submitted to the maintainers of those plugins directly.__ In the case of JsonTools (and many others), that means creating an issue in their GitHub repo, similar to what you've done here.

To reiterate: you've done the right thing (created an issue on GitHub) in the wrong repository.

Once you've reposted this issue in my repo (preferably with some information on which version of JsonTools was giving you problems), I'll take a look at it and try to help you.

**Comment by molsonkiko** [comment]
I'm opening an issue at my repo just to save some time, because I know what your issue is and I can just solve it now.

**Comment by JMoulding1958** [comment]
Apologies:  I'm a bit of a Newbie with this, and I'm grateful to you for picking it up.

John
