### ISSUE TITLE
Question about Plugin updates and new releases

### ISSUE THREAD

**Issue by Ekopalypse** [notepad-plus-plus/notepad-plus-plus#14267]
Is there any kind of workflow or deadline for deploying a plugin update to be included in the next npp version? I updated one of my plugins before the new npp version came out and it was merged in the npppluginlist repository, but it is still listed with an outdated version in the current 8.5.8 release. 
Have I possibly done something wrong?

**Comment by rdipardo** [comment]
The simplest explanation seems to be that v1.6.6 of the Plugin List was never published. The [most recent tag](https://github.com/notepad-plus-plus/nppPluginList/tags) and [release](https://github.com/notepad-plus-plus/nppPluginList/releases) are both 1.6.5.

**Comment by freezer2022** [comment]
Ekopalypse :
- we are on the bug tracker, follow the guideline :  https://github.com/notepad-plus-plus/notepad-plus-plus#contribution
- questions are handled elsewhere :
   - on forum : https://community.notepad-plus-plus.org/, 
   - optionally here for plugins : https://github.com/notepad-plus-plus/nppPluginList
- before asking questions, use search functionality, to avoid opening duplicate questions,
especially given a fact that such questions like the one you asked were already answered in the past as far I remember

> rdipardo : The simplest explanation (...)

- PluginList v1.6.6 is already bundled with Notepad++ 8.5.8
- he didn't mention name of the plugin

**Comment by rdipardo** [comment]
> > rdipardo : The simplest explanation (...)
> 
> * PluginList v1.6.6 is already bundled with Notepad++ 8.5.8
> * he didn't mention name of the plugin

The "merge window" closes when @donho pushes a tag. Assuming @Ekopalypse was talking about EnhanceAnyLexer, it was updated *after* 1.6.6 was (supposed to be) pushed. It's [in queue for the next release](https://github.com/notepad-plus-plus/nppPluginList/milestone/63?closed=1), so it does not look like it would be included with N++ 8.5.8 in any case

**Comment by Ekopalypse** [comment]
Thanks for the comments.
@freezer2022 - I searched the Issues using the search terms `plugin` and `release` and found nothing useful.
The issue itself seems more related to npp itself in my opinion, but if it is preferred to have such issues in the npppluginlist repo, then I will do it there from now on. The community is the wrong place to ask such questions, as there is hardly anyone with the authority to post this kind of thing. And I didn't name the plugin because it was a question about a general thing that affects every plugin.

@rdipardo - yes, it's about the EnhanceAnyLexer plugin and the link provided is the missing piece I was looking for.

**Comment by freezer2022** [comment]
> Ekopalypse : The community is the wrong place to ask such questions, as there is hardly anyone with the authority to post this kind of thing.

Very strange what you've said, because it's the opposite - its the best place to ask because :
- on the forum are the same people who are on bug tracker + a lot more of experts
 - documentation https://npp-user-manual.org/docs/plugins/#how-to-develop-a-plugin clearly says where to ask further questions : 
   - > You can visit the [Plugin development forum](https://notepad-plus-plus.org/community/category/5/plugin-development) for any technical questions/answers and the announcement of your new plugin.
    - > Questions & support : Ask your questions here: https://notepad-plus-plus.org/community/topic/16789/support-for-plugins-admin-npppluginlist-round-2
 - also all such questions about plugin updates you asked were discussed already in the past many times on the ofrum and on the plugins tracker

**Comment by Ekopalypse** [comment]
@freezer2022 we seem to have a different understanding of what kind of question I asked, but that's ok. I will ask questions about the plugin in the community from now on.

**Comment by alankilborn** [comment]
@Ekopalypse 
If I were you, I certainly wouldn't change my behavior based on the opinions of @freezer2022 .  

---

@freezer2022 
Please consider your audience, i.e., who you are lecturing to, before you provide lectures.  One way to do this is to check reputation levels for users on the Community site:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/83d5faca-f9ac-4c0f-b1e7-740a8f9139da)

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/4e34e4e6-b31c-487e-a1e7-406305fec36b)

Please consider that someone with 4562 reputation points knows a little something more about things than someone with 3 reputation points.

**Comment by freezer2022** [comment]
> Ekopalypse: we seem (...)

I don't know what exactly do you mean, because any question can be asked on forums, and your question is not different, but that's ok, I only try to help to keep tracker clean, I don't serve as a firewall here, only as an information drone, thus I don't give orders, only tips / guidance, the final decision belongs to you, especially if you are a known guy (I'm not a moderator here).

> alankilborn: (...)

No need to dramatize, like already explained above, I don't enforce anyone to do anything, I only provide tips/guidance, by the way it wasn't an "opinion", but facts and quotes / rules from official docs, what is an opinion is "If I were you (...)"  (I can write the same).

> donho : Hope it's clear for everyone.

Maybe would be good to put it into documentation : https://npp-user-manual.org/docs/plugins/#how-to-develop-a-plugin, (I know it's not official, but it can be mentioned that it's unofficial.)

**Comment by donho** [comment]
@freezer2022 
There are 2 labels (just set) which have been there for several years now.
So it's OK for asking questions here, especially about technical question or workflow question.

**Comment by freezer2022** [comment]
OK, but this doesn't change a fact, the documentation was saying to ask on forums, and didn't mention about issue tracker (like already mentioned in: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14267#issuecomment-1779115161).

**Comment by alankilborn** [comment]
A "problem" is that a _development_ question, if asked on the Community site, isn't guaranteed to get an answer from possibly the only person that can answer it (because Don doesn't tightly-follow the Community site).  No guarantees here either, but it is much more likely.  This isn't really an opinion, just a long-standing observation of _both_ places (this is not something everyone has).

**Comment by donho** [comment]
It's fault of no one. My point is that the technical questions from devs are welcome here, especially for the question about release workflow which is practiced only by me. 
And @alankilborn is right: I'm focusing on Github issues and coding (if I can), I barely follow the discussion on community, though I wish I could have time for it.
