### ISSUE TITLE
Placeholders: missing "File does not exist" message

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#14272]
**STR:**
Use the binary from https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e5ee4c3638a4b7d96504de6beba088016f1922f3.
Enable "Remember current session" & "Remember inaccessible files".
Open file A.
Close NPP.
Delete file A.
Open NPP.
Choose "Yes" to create the placeholder.
Restore file A.
Reload on prompt (-> _file A should be a normal file now_).
Delete file A.
Activate NPP.

**Result:**
No "File does not exist" message.

**Comment by xomx** [comment]
I can reproduce this, after the restore-delete-activate sequence I have got:

- when the "Remember inaccessible files" is ON (note that the asterisk '*' indication works ok - unsynced N++ state, only the msgbox is missing, but when I then tried to close N++ in such state, there was the correct save-msgbox offer "Your backup file cannot be found (deleted from outside). Save it otherwise your data will be lost Do you want to save file "...fileA.txt"):

![npp_file_restore delete_with_placeholders](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/b86de16b-9007-4027-9c84-6fa6062e9ef0)

- "Remember inaccessible files" OFF:

![npp_file_restore delete_wo_placeholders](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/5b51e533-f6dc-4470-907a-63b9ac36277e)
