### ISSUE TITLE
Search Results: display range & conditions

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#14306]
Quite often users are bewildered after executing a search and seeing the result(s).
[A recent example](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14304).

**Suggestion:**
 Display the range & conditions in the Search Results window.

***

Notepad++ v8.5.8.

**Comment by alankilborn** [comment]
Although I can't find a ref to it now, I think someone proposed before adding some symbols into the _Search results_ output; maybe something like this as an example:

`Search "foo" [cwn] (1 hit in 1 file of 3 searched)`

where the proposed new part is the `[cwn]` which indicates that the search was run with _Match case_ checked (because of the `c` being present), _Match whole word only_ checked (because of the `w` being present), and in _Normal_ search mode (because of the `n`).

If the search were done in _Extended_ mode with neither of the other two checkboxes checkmarked, the output would be thus:

`Search "foo" [e] (1 hit in 1 file of 3 searched)`

Regular expression mode, because of the additional `. matches newline` could be done as:

`Search "foo" [r] (1 hit in 1 file of 3 searched)` if `. matches newline` is uncheckmarked

and 

`Search "foo" [r.] (1 hit in 1 file of 3 searched)` if `. matches newline` is checkmarked

**Comment by alankilborn** [comment]
Note that I'm not sure how well one-word abbreviations translate into other localizations.  Maybe not so well??

**Comment by Yaron10** [comment]
@alankilborn,

Thank you for looking into it.

Interesting. It requires some thinking.
Would you mind discussing it once https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14307 is settled? :)

**Comment by alankilborn** [comment]
>Would you mind discussing it once https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14307 is settled?

As this issue is only slightly tangentially related to 14306, I don't think any conclusions drawn or outcomes from 14306 are going to affect this issue, so I think it can be discussed concurrently.  But if you choose not to participate now, I'm not saying/doing any more here (well, until *someone* engages in discussion).

**Comment by Yaron10** [comment]
@alankilborn,

> so I think it can be discussed concurrently.

You're absolutely right.
I just don't have enough free time currently. And this issue can be quite lengthy. :)

I hope you understand.
And thanks again for looking into it. I appreciate that. 👍

**Comment by donho** [comment]
I believe this issue has been fixed by: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/05f339b0cfe11095dc5590241bc8ff8cc4aec835

**Comment by Yaron10** [comment]
It's not fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/05f339b0cfe11095dc5590241bc8ff8cc4aec835.

The user could easily compare results of the same search-term with Case/Word ON/OFF.

***

@alankilborn,

Personally I'd prefer `Word, Case, Reg, Reg.`. 
Is `Normal` needed?

**Comment by alankilborn** [comment]
>Personally I'd prefer Word, Case, Reg, Reg.

I was going with single letters for the utmost in brevity.

>Is Normal needed?

As search mode isn't an on/off thing like the others, I specifically included all 3 search mode possibilities.

---

I don't see the point of going any farther with this without some sort of @donho endorsement.

**Comment by donho** [comment]
@Yaron10 
[A recent example](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14304) you provided is on Find, which has been fixed by providing the range on Find and Replace + info tip.

@alankilborn 
> I don't see the point of going any farther with this without some sort of @donho endorsement.

I don't want to make consistency for only making consistency. So let's stop here until there are more confusing false alert report from users.

**Comment by alankilborn** [comment]
>I don't want to make consistency for only making consistency. So let's stop here until there are more confusing false alert report from users

I think you're confusing this one with #14307.  They really are two different things.

**Comment by donho** [comment]
> I think you're confusing this one with https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14307. They really are two different things.

No, I'm not.
If by Search Results it means Find in Files & Find in Opened document and etc..., then the example provided by @Yaron10 has nothing to do with it.
My question is: Are there people who complain about Find in Files & Find in Opened document and other concerning operations confusing specifically?

**Comment by alankilborn** [comment]
In my mind this is more of a functionality enhancement than trying to fix PEBKAC users.
Perhaps @Yaron10 thinks differently on it.

I see it as a way for users who run many similar searches to see exactly what parameters they ran the prior searches with.  Currently all users can see is the _Find what_ text they ran a previous search with, in `Search "foo"`.

This would allow seeing case, word, and search mode for each previous search.  Perhaps regex is easy to infer from the content of foo, but why not be explicit for that part of it as well.

**Comment by donho** [comment]
Let's wait & see if such requests coming!

**Comment by alankilborn** [comment]
I'd think that YOU could decide if you like it or not, when your expert users recommend such an enhancement.
Normal users don't know what they're missing...until they're given an enhancement.

**Comment by Yaron10** [comment]
@alankilborn,

> In my mind this is more of a functionality enhancement than trying to fix PEBKAC users.

Indeed.

It is related to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14307 in the broader view.
\- **Provide info on the executed search**.

You provide info In the Find dialog status bar even though the user can see which setting is checked or not.
_In the Search Results window, the user (usually) can not see those settings._

The user executes a 30-minute search for `Hello`.
An hour later, and after some more searches _with different settings_, they might wonder: 
**Was Case checked on the `Hello` search?** - **Not sure, let's re-executes the 30-minute search.**

**Comment by alankilborn** [comment]
If it doesn't prove too difficult, I might throw together a demo of this.
I've often thought that it would be a valuable thing.

**Comment by alankilborn** [comment]
I've also wondered, could "Re run this search" be a right-click menu item for _Search results_?".
THAT would need to know the info as well -- not sure what is currently carried along in the code to make this possible.
It's off topic, but I'm just noting it here.
