### ISSUE TITLE
Display range & conditions after executing a search

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#14305]
Quite often users are bewildered after executing a search and seeing the result(s).
[A recent example](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14304).

**Suggestion:**
 Display the range & conditions in the Find dialog status bar & in the Search Results window.

***

Notepad++ v8.5.8.

**Comment by Yaron10** [comment]
Do you want me to close this one and open two separate issues?
It's the same issue IMO.

You can always "partially fix". :)

**Comment by alankilborn** [comment]
>Do you want me to close this one and open two separate issues?

It's OK, just not optimal.
Partially fix isn't great, as Don can't close PR and issue at same time (more mental bookkeeping for him?)

---

>Another advantage of implementing it

Plenty of advantages, all around...

---

BTW, I requested 2 separate ones, but it was in an "edit" to where I just requested "put in an issue".  Do you read issues via email notification, mentally formulate a response, and then go to github site to actually respond?  I find it best to forget the email notify except as a jumping point, and go to the site to read what someone said.  Why? Because people (me!) like to edit what they've said, and the email only gets what was said _first_, not any edits.

**Comment by Yaron10** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14306.
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14307.

> but it was in an "edit"

I read the "edited" version, but it had a `?` at the end. :)

**Comment by alankilborn** [comment]
Considering 14306 and 14307, I think that 14306 is easier to implement, perhaps by far.  The main problem is _how_ to display the info, and I think 14306 might lend itself better to that task.  Also, I think perhaps 14306 was broached with Don some time ago and got put down because it violates KISS.  Or, my brilliant memory (haha) could be doing one of its detours. :-)

**Comment by Yaron10** [comment]
@alankilborn,

Your suggestion to split the issues was smart! See https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14307#issuecomment-1793199173.

>  Also, I think perhaps 14306 was broached with Don some time ago

It was a misunderstanding.

> The main problem is how to display the info...

This can be discussed. :)
