### ISSUE TITLE
Allow Read-Only Session Files

### ISSUE THREAD

**Issue by Ionwerks** [notepad-plus-plus/notepad-plus-plus#14312]
I've always kept most of my session files read-only.

I use them to group source files into projects, adding and removing entries by hand (in Windows Notepad) before protecting them again. They're most valuable to me if they are always in a predictable/known state rather than reflecting what I last closed or dragged in.

Recent versions have started complaining about this on failing to save and again on next open and also creating inCaseOfCorruption & fail2Load droppings everywhere.

Is it possible that if a session file is marked read-only (vs some other permission error) it might be assumed that this is intentional?

Thanks!

**Comment by alankilborn** [comment]
>Recent versions

?

(there was an issue template for you to fill out)

**Comment by xomx** [comment]
It is so due to this set of the N++ `NppParameters::writeSession` changes:
- Fix session file saving problem if it's read-only https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3aa9e9280fdd478923bf40914202cac6b537d00c
- Add session.xml.fail2Load for analyzing  https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ccf80a0699f9584b6349e6adf1eec6be31d8fdad
- Backup session file in case of its corruption  https://github.com/notepad-plus-plus/notepad-plus-plus/commit/50b81eadefa0aaeeece6e4458f45e9b931191191
- Add more info on save session error message  https://github.com/notepad-plus-plus/notepad-plus-plus/commit/7e353903b82a8035ead20759db8ec32a4ff88d94
- Add more info on save session error message part 2  https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bf475862593fabcc4e1fb4783fca540ea516036e

@alankilborn 
> droppings?? What are droppings?

Because the user deliberately sets his session files to RO, now he has started to have problems and the "droppings" (N++ generated files...).

@Ionwerks 
Looks like you will have to change your habits, sorry.
