### ISSUE TITLE
Dropped file may be opened in the wrong view

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#14354]
**STR:**
Open two files.
Move one to the other view (-> SUB_VIEW is active).
Execute a search opening the Search Results window.
Drag & drop a third file _into the Search Results window_.

**Result:**
The file is opened in MAIN_VIEW.

```
Notepad++ v8.5.8   (64-bit)
Build time : Nov 14 2023 - 03:38:15
Path : ---notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 20H2
OS Build : 19042.985
Current ANSI codepage : 1255
Plugins : 
    ComparePlus (1.1)
    HTMLTag (1.4.1)
    MenuIcons (2.0.5)
    PythonScript (2)
    _CustomizeToolbar (4.2)
```

**Comment by alankilborn** [comment]
When I try dragging and dropping into anywhere in Notepad++ that is not view 1 nor view 2, the result is that the file opens in view 1.  I don't know that the expectation that a dropped file should open in the active view (when not dropped specifically there) is bug-worthy.  Maybe more of a feature-request. :-)

An argument could be made that if the drop target isn't specifically view 1 or view 2 that nothing should happen (i.e., the mouse cursor should not change, and no file should open if dropped).  I personally don't like that because often I have most of the N++ window covered with other stuff and I can just see a tiny corner -- enough of a file drop target for me to get my file open and N++ put on top in the Z order.

**Comment by Yaron10** [comment]
> When I try dragging and dropping into anywhere in Notepad++ that is not view 1 nor view 2, the result is that the file opens in view 1.

The Search Results window was just an example.

> I don't know that the expectation that a dropped file should open in the active view (when not dropped specifically there) is bug-worthy.

Allow me to disagree.

> An argument could be made that if the drop target isn't specifically view 1 or view 2 that nothing should happen
...
I personally don't like that

I wouldn't like that either.

**Comment by Yaron10** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/05f339b0cfe11095dc5590241bc8ff8cc4aec835/PowerEditor/src/Notepad_plus.cpp#L4313

Replace with:
```cpp
if ((hWin == _mainEditView.getHSelf()) || (hWin == _mainDocTab.getHSelf()))
	switchEditViewTo(MAIN_VIEW);
else if ((hWin == _subEditView.getHSelf()) || (hWin == _subDocTab.getHSelf()))
	switchEditViewTo(SUB_VIEW);
```
