### ISSUE TITLE
line operation (delete, copy & cut) problem

### ISSUE THREAD

**Issue by circcc** [notepad-plus-plus/notepad-plus-plus#14401]
v8.6, 2 Problem

1.When text is not selected, the Cut/Copy menu and toolbar icons are disabled and cannot be used.
The Cut/Copy menu and toolbar icons should always be active for line operation.
Ultraedit 'Enable copy/cut of current line with no selection active' option work like this.
![line](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/72944033/c393e04c-ca5e-4381-9bf4-c045c6f7a4c2)

2.Shift + Delete: without selected text, it shoud 'Cut'(not 'Delete') the whole line.
This is the standard and UltraEdit works like this too.

**Comment by alankilborn** [comment]
>When text is not selected, the Cut/Copy menu and toolbar icons are disabled and cannot be used.

I think the _intention_ of the new feature of 8.6 is that it is keyboard only.  Thus, toolbar button and menu states are correct.

>Shift + Delete: without selected text, it should 'Cut'(not 'Delete') the whole line.
This is the standard

It does indeed seem to be the way Visual Studio works; apparently bad information was provided to the developer of N++ when he implemented the feature.  However, as implemented it is more flexible -- use Ctrl+x for "cut", Shift+Del for "delete".  (But, if you want to remap the keycombinations so that Shift+Del is "cut", sadly, you can't)

**Comment by Yaron10** [comment]
@circcc,

> When text is not selected, the Cut/Copy menu and toolbar icons are disabled and cannot be used.

👍 
Good and basic point.

> Ultraedit 'Enable copy/cut of current line with no selection active' option work like this.

I'm pretty sure it's not only UltraEdit, but every editor which enables Copy/Cut when there's no selection implements it that way.

See https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14296#issuecomment-1796858382.

**Comment by alankilborn** [comment]
From the start, the feature was implemented in a "second class" way (not as full commands, hard-coded keycombos).  Why now expect it to be a "first class" feature (where menu and toolbar icons are involved)?

**Comment by donho** [comment]
> From the start, the feature was implemented in a "second class" way

There is no "second class" feature in Notepad++, every single feature is the first class. They are just different.

**Comment by donho** [comment]
Cut & Copy commands will be visible all the time with PR #14415.

> 2.Shift + Delete: without selected text, it shoud 'Cut'(not 'Delete') the whole line.
This is the standard and UltraEdit works like this too.

There are a lot standards, so there's no standard for it to me.
Visual studio that I use for coding Notepad++ uses Shift-DEL to delete current line when there's no selection. I find it kind of logic so Notepad++ follows this logic.

**Comment by alankilborn** [comment]
> > Visual studio that I use for coding Notepad++ uses Shift-DEL to delete current line when there's no selection. I find it kind of logic so Notepad++ follows this logic.
> 
> Which Visual Studio do YOU use? I use this one:
> 
> ![image](https://private-user-images.githubusercontent.com/77065706/286234512-d7d94976-787e-4397-9577-a3a04369c1df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExODM0NTIsIm5iZiI6MTcwMTE4MzE1MiwicGF0aCI6Ii83NzA2NTcwNi8yODYyMzQ1MTItZDdkOTQ5NzYtNzg3ZS00Mzk3LTk1NzctYTNhMDQzNjljMWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE0NTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ODE0MmYzMzI1ZmE3NTZkMDgxZDUyODE3MzNmMDUxNTNiMzFjNmFmMzY1OTZhNjdmNGQxYTQ3NWZhMDVlN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WtEATdrMXyVCcSatrLcrWPfd5W7pD0QLM5wbvL0Jzq4)
> 
> and the behavior of Shift+Delete in MY Visual Studio is "cut", not "delete".
> 
> That being said, "cut" is already handled (in Notepad++) with Ctrl+x, so why not have functionality to "delete" without having a selection active as well (thus, I endorse the behavior, just not on Shift+Delete).
> 
> HOWEVER, it is confusing that:
> 
> * default shortcuts are this way:
>   ![image](https://private-user-images.githubusercontent.com/77065706/286235383-1b0f025b-8264-4159-ba02-d0f67a9b73cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExODM0NTIsIm5iZiI6MTcwMTE4MzE1MiwicGF0aCI6Ii83NzA2NTcwNi8yODYyMzUzODMtMWIwZjAyNWItODI2NC00MTU5LWJhMDItZDBmNjdhOWI3M2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE0NTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZDdmZTM2YWM1MDkwNzI2ZmQ2MzRjZjQ1MjdmMDk4ZDJiYmNmZjhhYzc1OTllYjRiMzFjY2EzZGRjM2NiYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AooS5qDbAdfvXjEskUQTTH3_Y-VXIDrAhOsJotFRsiw)
> * Ctrl+x with or without a selection will do some sort of "cut"
> * Shift+Delete **_with_** a selection will "cut", but **_without_** a selection it will "delete" (THIS IS THE CONFUSING PART, because _Shortcut Mapper_ leads one to believe that Shift+Delete does a "cut")

**Comment by pryrt** [comment]
So @donho, as implemented, this is how the User Manual has to describe the behavior of these keystrokes:

> - `Shift+Delete` will cut the current selection, or if there is no selection, it will delete the current line (assuming you have not changed the shortcut `Shift+DEL` from `SCI_CUT` to anything else; if you do, this functionality will _not_ be accessible). (Yes, it cuts to the clipboard if there's a selection, but deletes the line without affecting the clipboard if there is a selection.) (The no-selection variant is new to v8.6.)
> - `Ctrl+C` will copy the current selection, or if there is no selection, it will copy the current line (assuming you have not changed the shortcut `Ctrl+C` from `SCI_COPY` to anything else; if you do, this functionality will _not_ be accessible). (The no-selection variant is new to v8.6.)
> - `Ctrl+X` will cut the current selection, or if there is no selection, it will cut the current line (assuming you have not changed the shortcut `Ctrl+X` from `SCI_CUT` to anything else; if you do, this functionality will _not_ be accessible). (The no-selection variant is new to v8.6.)

I am sure this will be confusing to users, because the fundamental behavior of `Shift+Delete` changes from "cut" (which affects the clipboard) in one mode, then "delete" (which does not affect the clipboard) in another.  And it's also confusing, because those no-selection behaviors go away if you change your keyboard shortcuts in the Shortcut Mapper.

And I can also confirm with another version of Visual Studio (2019) that `Shift+Delete` in Visual Studio does a CUT of the selection of there's a selection, and it does a CUT of the whole line if there's no selection.  In Visual Studio, `Shift+Delete` and `Ctrl+X` behave identically to each other, and both always affect the clipboard.
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/17455758/ab2d9f66-bdf8-4786-8987-58973d606403)

**Comment by Yaron10** [comment]
> Shift+Delete with a selection will "cut", but without a selection it will "delete" (THIS IS THE CONFUSING PART, because Shortcut Mapper leads one to believe that Shift+Delete does a "cut")

👍

**Comment by donho** [comment]
@alankilborn @pryrt @Yaron10
Taking account the current situation that the existence of Shif-DEL with and without selection but it could make user confusing, 
What's the best remedy (behaviour) you suggest?

**Comment by donho** [comment]
I would remove all the shortcut Shift-DEL, Ctrl-INS - they are not really useful, and if user wants, they can use Shortcut mapper to remap them.

**Comment by Yaron10** [comment]
> it will copy the current line (**assuming you have not changed the shortcut Ctrl+C from SCI_COPY to anything else; if you do, this functionality will not be accessible**).

> I've forgot Ctrl-C and Ctrl-X are managed directly by Scintilla.

You have a problem that other editors don't.
So it's not only Shift+Delete. It's the basic approach.

The simplest solution is separate "Copy/Cut/Delete Current Line" commands.

***

> I would remove all the redundant shortcut like Shift-DEL & Ctrl-INS

And Ctrl+C?

**Comment by donho** [comment]
> You have a problem that other editors don't.
So it's not only Shift+Delete. It's the basic approach.

> And Ctrl+C?

Yes, it's removed from Scintilla but, Notepad++ take over this shortcut.
Please see PR #14422.

**Comment by xomx** [comment]
@donho 

> Yes, it's removed from Scintilla but, Notepad++ take over this shortcut.
> Please see PR #14422.

You cannot simply move the Ctrl+C, Ctr+V... to the winKeyDefs, I have been there once too:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11401#issuecomment-1178897298

**Comment by Yaron10** [comment]
@xomx,

https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14422#issuecomment-1830668467. :)

**Comment by donho** [comment]
@xomx 
> You cannot simply move the Ctrl+C, Ctr+V... to the winKeyDefs, I have been there once too:

Yes, we can :)
Check latest commit of PR #14422.

**Comment by cezariuszmarek** [comment]
> I would remove all the redundant shortcut like Shift-DEL & Ctrl-INS

Please don't do that - some people are got used to them across all the editors. Don't stick out of the common standards.

**Comment by Coises** [comment]
> > > I would remove all the redundant shortcut like Shift-DEL & Ctrl-INS - they are not really useful, and users can always use Shortcut mapper to remap them
> 
> > Please don't do that - some people are got used to them
> 
> Strongly agree. Changing something that has long been a default mapping is not a good idea.

Not just in Notepad++, or even in editor software, but throughout Windows, it is standard that Shift+Delete, Ctrl+Insert and Shift+Insert are synonyms for Ctrl+x, Ctrl+c and Ctl+v. (For example, in the web control in which I am writing this comment.)

Breaking that behavior _by default_ would be very user-unfriendly.

**Comment by Coises** [comment]
When pasting into a rectangular selection, SCI_PASTE ignores direction (top down vs bottom up) and always pastes “right side up.” This is consistent with how cut and copy behave for rectangular selections, and differs (for all three) from the behavior for multiple stream selections.

The Notepad++ menu command IDM_EDIT_PASTE does not duplicate the behavior of SCI_PASTE; it takes selection order into account for rectangular selections, which is unexpected. I never noticed this before as, like most people, I almost never use the menu commands for cut/copy/paste.

However, since the remapping, the unexpected behavior [has been noticed](https://community.notepad-plus-plus.org/topic/25234/npp-v8-6-reverses-the-order-of-lines-on-column-copy-paste?_=1702402674947).

This is not how we expect rectangular selections to behave.

**Comment by donho** [comment]
@cezariuszmarek @alankilborn @Coises 
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14513

**Comment by vlakoff** [comment]
Before finding this thread, I actually thought the same as you guys, about the behavior of <kbd>Shift</kbd>+<kbd>Del</kbd> shortcut, which should not delete but cut, whether it's with or without text selection: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14296#issuecomment-1879299528.

I also suggested to implement <kbd>Ctrl</kbd>+<kbd>Insert</kbd> without text selection, to copy the whole line.

**Comment by henryford-metoffice** [comment]
For me, I noticed immediately on upgrade to 8.6.1 that Ctrl+Insert doesn't copy and Shift+Insert doesn't paste.

I'm happy to find this thread that people recognise these shortcut alternatives for Ctrl+XCV being (Shift+Del, Ctrl+Ins, Shift+Ins, resp.), but I'm not so happy that I'm here trying to troubleshoot why I don't copy things into clipboard and how to solve it.

I knew there would be one day when these really old shortcuts would stop working, it's annoying enough when people redesign web-based text boxes to remove these shortcuts, but why on NP++ 8.6.1 do they now not work?

Does the community (or Author) think they'll come back or is there a workaround to bring them back?

**Comment by alankilborn** [comment]
>I knew there would be one day when these really old shortcuts would stop working

No reason for something that's really old to stop working...

>Does the community (or Author) think they'll come back or is there a workaround to bring them back?

Well, depending upon author decision (of course), I'd say they'll be back.  :-)

**Comment by PauloJFMartins** [comment]
> > it will copy the current line (**assuming you have not changed the shortcut Ctrl+C from SCI_COPY to anything else; if you do, this functionality will not be accessible**).
> 
> > I've forgot Ctrl-C and Ctrl-X are managed directly by Scintilla.
> 
> You have a problem that other editors don't. So it's not only Shift+Delete. It's the basic approach.
> 
> The simplest solution is separate "Copy/Cut/Delete Current Line" commands.
> 
> > I would remove all the redundant shortcut like Shift-DEL & Ctrl-INS
> 
> And Ctrl+C?

Great!
Let's redesign the wheel and the steering wheel and make them square.
Sir; I've bee working in IT for 35 years and I've used Windows since it exists, and I've always used CTRL+INS, SHIFT+DEL and SHIFT+INS.
These shortcuts are so transversal and well established that even other Operating Systems adopted.
If we were to remove something, then CTRL+C, CTRL+X and CTRL+V should go first. These are the redundant ones.
This BUG affects Notepad++ 8.6.1 so I rolled back to version 8.6 and will wait for a fix.

**Comment by PauloJFMartins** [comment]
> I would remove all the redundant shortcut like Shift-DEL & Ctrl-INS - they are not really useful, and users can always use Shortcut mapper to remap them: By disabling the shortcuts of Scintilla, we can have the homogeneous behaviour for each commands, even user remaps the shortcuts (and less complex code).

Great!
Let's redesign the wheel and the steering wheel and make them square.
Sir; I've bee working in IT for 35 years; I've used Windows since it exists, and I've always used CTRL+INS, SHIFT+DEL and SHIFT+INS.
These shortcuts are so transversal and well established that even other Operating Systems adopted them.
If we were to remove something, then CTRL+C, CTRL+X and CTRL+V should go first. These are the redundant ones.
This BUG affects Notepad++ 8.6.1 so I rolled back to version 8.6 and will wait for a fix.
