### ISSUE TITLE
Can notepad++ 8.6 new version realize .....

### ISSUE THREAD

**Issue by hqhbaby** [notepad-plus-plus/notepad-plus-plus#14427]
notepad++ tab bar Can you implement the function

1. Show close button only when mouse pointing to tabs
2. Automatically activate the current tab when the mouse points to the tab bar
3. Right-click to close the current tab

**Comment by alankilborn** [comment]
What real use is there in "1"?

"2" doesn't make sense because the mouse will often "come to rest" at a (to the user) random spot, and thus a tab could be inadvertently closed.

For "3" there is already a right-click menu for tabs where the top item is (conveniently) _Close_.

**Comment by donho** [comment]
> "2" doesn't make sense because the mouse will often "come to rest" at a (to the user) random spot, and thus a tab could be inadvertently closed.
For "3" there is already a right-click menu for tabs where the top item is (conveniently) Close.

Agree with @alankilborn 

> For me a more suitable option might be: "Show close button only on active tab"
Because:
a) Save space otherwise wasted for not needed buttons, but allow it at least for the active tab
b) Prevent unintended closure of inactive tabs when trying to activate a tab (tabs might be short, and so they might be easily closed inadvertently. Therefore actually I don't use close buttons at all).

The option sounds good, but it's not must-have feature.
For point b), when user points on the inactive tab's close button, the button becomes highlighted so it's improbably to me that a document could be closed by accident.   
For point a) indeed, it could save a small amount space on a tab. But it needs more coding effort and makes the code even more complex. 
Therefore this feature won't be implemented.
