### ISSUE TITLE
Need help to build: Folding by indentation in plain text (not UDL), similar to notepad2

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#14465]
I use notepad++ for taking very-long notes.
So the feature "folding by indentation in plain text files" is very useful.

After long time in studing, I see that Notepad2 support the feature.
The feature should only change a file: LexNull.cxx

Could anyone please build Notepad++ with the feature?

Thank you very much.

Notepad2:
https://github.com/zufuliu/notepad2/blob/main/scintilla/lexers/LexNull.cxx

Notepad++:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/lexilla/lexers/LexNull.cxx

**Comment by rdipardo** [comment]
> Notepad++: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/lexilla/lexers/LexNull.cxx

All the source code under the `lexilla` subtree is third-party. Enhancements can be requested here: https://github.com/ScintillaOrg/lexilla/issues

**Comment by xomx** [comment]
I think that there already is such lexer:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/lexilla/lexers/LexIndent.cxx

I have not tried that myself, but I think it can be used at the moment e.g. via the PythonScript plugin (you need to create SCLEX_INDENT lexer object ptr and then use it in the SCI_SETILEXER message to Scintilla...).

**Comment by rdipardo** [comment]
> This is LexIndent.cxx with feature FoldIndent [LexNullWithFoldIndent.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/13622636/LexNullWithFoldIndent.zip)

Since it's basically a matter of activating a lexer module (which is already part of the distributed application, but "turned off"), you can get it working right now with the help of [Python Script](https://npppythonscript.sourceforge.net).

Here's a quick example inspired by [an old post on the user community forum](https://community.notepad-plus-plus.org/post/82654):

~~~python
import os
import ctypes
from ctypes import windll, create_unicode_buffer
from ctypes.wintypes import HWND, WPARAM, LPARAM, UINT, LPCWSTR, c_long
from Npp import editor, notepad, NOTIFICATION

SendMessage          = windll.user32.SendMessageW
LRESULT              = LPARAM
SendMessage.argtypes = [HWND, UINT, WPARAM, LPCWSTR]
SendMessage.restype  = LRESULT

LEX_INDENT = b'indent'
LEX_INDENT_STATUS_BAR_DESCR = b'Folded plain text file'
NPPM_CREATELEXER    = 2134
NPPM_SETSTATUSBAR   = 2048
STATUSBAR_DOC_TYPE  = 0
_SC_MARGE_FOLDER    = 3  # PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp
FOLD_MARGIN_WIDTH   = 18


def _activate_indent_lexer(args):
    npp_hwnd = windll.user32.FindWindowW(u'Notepad++', None)
    ext = os.path.splitext(notepad.getCurrentFilename())[1]
    if ext in  [ '.txt', '.log' ]: # add more as needed
        lexerPtr = SendMessage(npp_hwnd, NPPM_CREATELEXER, 0, create_unicode_buffer(LEX_INDENT))
        editor.setILexer(lexerPtr)
        editor.setProperty('fold', 1)
        editor.setMarginWidthN(_SC_MARGE_FOLDER, FOLD_MARGIN_WIDTH)
        SendMessage(npp_hwnd, NPPM_SETSTATUSBAR, STATUSBAR_DOC_TYPE, create_unicode_buffer(LEX_INDENT_STATUS_BAR_DESCR))


if __name__ == '__main__':
    notepad.callback(_activate_indent_lexer,
                     [NOTIFICATION.BUFFERACTIVATED,
                      NOTIFICATION.LANGCHANGED,
                      NOTIFICATION.WORDSTYLESUPDATED])

~~~

<img width="683" alt="lexindent py-gh-draft" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59004801/feeb27d7-7dfa-4ee0-8881-9596b73f103a">

<img width="385" alt="lexindent-demo" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59004801/353c7489-f0c2-4f52-b4aa-9fc8cdf22e9c">

**Comment by alankilborn** [comment]
> The solution only applies to files with extension. If files are new or without extension, it does not work. It's not so convenient.

Wow...beggars are trying to be choosers...

@rdipardo I tried it and it works great ... under PythonScript2.  But unlike some others, I'm not going to complain, I'm just going to figure out how to change it for PythonScript3.

**Comment by alankilborn** [comment]
> Not working

In the code is this:

`if ext in  [ '.txt', '.log' ]`

Thus it should only work if the file has been saved with these extensions, NOT with `new 1` or `new 2` as you show in your screenshot.

If you don't like that, change the script code to make it work the way you want.

Or change Notepad++ C++ code to make whatever you want.

---

>Idiot. Trash.

Calling people names isn't going to get you anything you want.

**Comment by anpsoft** [comment]
not correct fold it !!! need stop folding in line after subtask2

*-  task1
|        subtask1
|        subtask2
|
|
*-
  task2
      subtask2-1
