### ISSUE TITLE
Closing the last tab switches back to the first tab (far left)

### ISSUE THREAD

**Issue by SmileSoftSr** [notepad-plus-plus/notepad-plus-plus#14475]
### Description of the Issue

When working with a fairly large number of tabs (more than 40), closing the last tab switches the display back to the first tab on the left. This becomes annoying as all the newly opened tabs are at the end of the tabs (far to the right).

This happens regardless of the other tabs' contents and status (temporary notes and not a saved / existing file, or a regular file opened for viewing, or a regular file which was opened and changed, but not saved, etc).

In previous versions, if the last tab was closed, the display would switch to the one which was to the left of it.

### Debug Information

Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3693
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
Why did you not supply `Steps To Reproduce` as requested in the issue template?
Supplying this info is critical (that's why it is there in the template).

---

Here's mine (may or may not have any relation to yours):

* fresh/portable 8.6
* type `a` into `new 1` that appears when N++ runs
* press Ctrl+n to get `new 2` to appear; type `a` to modify that
* repeat previous step to get as many tabs as you like (e.g. `new 40`)
* make sure you've put an `a` into tab `new 40`
* press the red X on `new 40`'s tab to close it; confirm closure without saving by pressing No in the popup

The tab to the immediate left (`new 39`) becomes active.

Conclusion:  Can't reproduce the original issue.

---

Next:

* restart N++ (tab `new 39` is active)
* press the red X on `new 39`'s tab to close it; confirm closure without saving by pressing No in the popup

The `new 1` tab (leftmost) becomes active.

Conclusion:  N++ doesn't remember that tab `new 38` was most-recently active (MRU) of the existing tabs.  Question: Is it responsible for doing this over a restart cycle?

---

Next:

* uncheckmark this box:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/e286b8b6-3916-4070-baa5-13ecba05854b)

* make tab `new 38` active
* restart N++  (tab `new 38` is active)
* with tab `new 38` active, press the red X on `new 38`'s tab to close it; confirm closure without saving by pressing No in the popup


The `new 37` tab becomes active.

Conclusion:  Not sure.  :-)

**Comment by SmileSoftSr** [comment]
> Why did you not supply `Steps To Reproduce` as requested in the issue template? Supplying this info is critical (that's why it is there in the template).
> 
> Here's mine (may or may not have any relation to yours):
> 
>     * fresh/portable 8.6
> 
>     * type `a` into `new 1` that appears when N++ runs
> 
>     * press Ctrl+n to get `new 2` to appear; type `a` to modify that
> 
>     * repeat previous step to get as many tabs as you like (e.g. `new 40`)
> 
>     * make sure you've put an `a` into tab `new 40`
> 
>     * press the red X on `new 40`'s tab to close it; confirm closure without saving by pressing No in the popup

Apologies, I thought the description would have made the steps redundant. Your steps are exactly what I was doing, and what was causing the issue.

Unchecking the Enable MRU behaviour box solved the issue.
