### ISSUE TITLE
Open file from shared folder

### ISSUE THREAD

**Issue by omidkosari** [notepad-plus-plus/notepad-plus-plus#1452]
Hi,

I have awful problem . I open a file from another persons laptop \192.168.1.15\sample.txt and forgot to close it . Then hibernate my laptop . Tomorrow i came to work and turn on my laptop but that person is absent . now the Notepad++ freezes(Not Responding) for long time

**Comment by j-mok** [comment]
Same here. Could really use a fix for that.

**Comment by donho** [comment]
@omidkosari @j-mok 
Could you provide full info (please check: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/ISSUE_TEMPLATE.md)

**Comment by j-mok** [comment]
Sure, here's the details:

Notepad++ hangs on startup when it tries to recreate a session which contains a no longer reachable file from a remote share.

My setup:

- Windows 8.1

- Notepad++ v7.2.2 32-bit

Repro steps:

1. Have Notepad++ restore previous session on startup (Prefs->Backup->Remember current session for next launch)

1. Open a file from a shared folder on a remote PC
1. Close Notepad++
1. Shut down the remote PC or stop sharing
1. Launch Notepad++

Expected behavior: Notepad++ is responsive, restores the session partially, allows the user to start working on files that opened successfully. As for the unreachable file, maybe Notepad++ should give some  unobtrusive info to the user after timeout?

Actual behavior: Notepad++ is unresponsive (although it seems to unfreeze after longer waiting).

**Comment by omidkosari** [comment]
In addition to @j-mok 

Notepad++ hangs if you opened a file on remote share , then the remote share shutdown or timeout or unreachable .

My setup:

    Windows 10 64-bit

    Notepad++ v7.2.2 32-bit

Steps to Reproduce the Issue

1. Open a file (with notepad++) from remote shared folder

2. Unplug the network or power cord of the remote computer

Expected behavior: Notepad++ show a message like: The file is not there anymore . Do you want to keep the tab open or close it ?

Actual behavior: Notepad++ is unresponsive (although it seems to unfreeze after longer waiting sometimes about 1 hour).

**Comment by omidkosari** [comment]
@donho Is there anything else that we should do ?

**Comment by dr-abadis** [comment]
Hi. I have exactly the same problem here !!!

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
