### ISSUE TITLE
[Feature Request] Save state of folded/collapsed blocks on exit.

### ISSUE THREAD

**Issue by Yay295** [notepad-plus-plus/notepad-plus-plus#1454]
It would be nice if I could collapse some blocks in my code, close NP++, open NP++, and still have the blocks be collapsed.

**Comment by Gabr-F** [comment]
This should already happen, if you have session restore enabled (Preferences -> Backup -> Remember current session for next launch)

**Comment by Yay295** [comment]
No, that only saves which files are open, scroll position, and cursor position. It doesn't save collapsed blocks as being collapsed.

**Comment by atompkins** [comment]
It only remembers the fold settings for the first tab

**Comment by sambuccid** [comment]
The error is not on html but it appears with javascript files.
Saving the session with "save session" and then reloading it with "load session", everything works.
Also by compiling the program, the error is not there

**Comment by YakovL** [comment]
I'll subscribe to this thread. I'm having a similar issue, but I have to isolate it better. In my main window (session of which is saved) I have a number of files, mostly .txt's with syntax set to Python (to collapse indented blocks) but also .js and none of the fold states are saved once I reopen n++ (session is stored). If this is a file type/selected syntax -specific issue, I should backup my session and try that with separate files.

**Comment by YakovL** [comment]
Ok, here's what seems perfectly reporducible for me:

1. create a txt (in my case that's "test 2.txt") which can even be empty
2. create another txt (in my case that's "test 1.txt") with the following content:

       . one
        . two

3. select Python syntax for the second txt and fold the second line as a block indented from `. one`
4. close n++ (session autosaving should be enabled); reopen it

**Expected behaviour**: the second line (`. two`) stays folded
**Actual behaviour**: the second line is unfolded (shown normally)
**Note**: the behaviour depends on the tab order: "test 2.txt" must be the left tab and "test 1.txt" must be the right tab: if I switch the order, close and reopen, the second line stays folded

Debug info:

Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\1my\tools_and_components\in_use_or_used\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : AutoSave.dll ComparePlugin.dll DSpellCheck.dll EmmetNPP.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll PythonScript.dll

**Comment by YakovL** [comment]
PS the behaviour stays even if we remove the quirk of using txt with Python syntax: just rename "test 1.txt" to "test 1.py" and the problem is still there

**Comment by donho** [comment]
This feature has been implemented since long time ago

**Comment by YakovL** [comment]
But it doesn't work in some cases! @donho have you tried the described scenarios to reproduce the problem? Should I create a separate issue to report the bug.. again?

**Comment by donho** [comment]
@Yay295 Then please create a bug with full description. 
This issue is a FR.

**Comment by Yay295** [comment]
It's a feature request because this feature obviously doesn't exist.

**Comment by Yay295** [comment]
Reopened #5525
