### ISSUE TITLE
notepad 8.5.8 and newer, plugin conflict causes NPP crash

### ISSUE THREAD

**Issue by swgmike** [notepad-plus-plus/notepad-plus-plus#14564]
### Description of the Issue
Installed npp 8.5.8, then replaced with 8.6, then replace 8.6.1 as clean installs. It doesn't matter which of these versions are
installed on a windows 10 pro system.
I then installed all the plugins I had on the old computer plus a few. more.  However, when the two plugins listed below are installed ,npp will try to open but crash. If one or the other is present, it will work with all my other plugins that I selected on old computer. Therefore, these two plugins when both are present causes npp to crash.

This problem was narrowed down by deleting each of my plugins one by one to find what was causing the crash.
Note: To save time on plugin installs, the plugins on install were moved to a backup sub directory and copied as needed to the plugins directory. The backup sub directory was in the plugins directory.

### Steps to Reproduce the Issue

1.  install the plugins "JN" and  "Npp-Highlighter"  with the default plugins together and select npp to run. NPP will try to open and
    crash.
3. Delete either the "JN" or the "Npp-Highligher" and select npp to run. It will execute without problem along with any other plugins that get installed. Therefore, these two plugins are in conflict.

### Expected Behavior
That npp will open and display a window and not crash.

### Actual Behavior
npp crashes on opening npp for use.

### Debug Information
Note: I can't attached the debug info since npp crashes when the conflicting plugins are installed.
Foloow the steps above to reproduce the issue.

**Comment by rdipardo** [comment]
Here's a couple better places to report this:

- https://github.com/sieukrem/jn-npp-plugin/issues
- https://github.com/michaelxzhang/Npp-Highlighter/issues

**Comment by BrianG61UK** [comment]
What is this "JN" plugin? I haven't got a plugin called JN or JN something yet Npp-Highlighter still causes slow operation and extensive corruption to the GUI.

**Comment by rdipardo** [comment]
> Npp-Highlighter still causes slow operation and extensive corruption to the GUI.

Npp-Highlighter implements a feature to track file revisions by drawing colorful annotations in the margin. The same capability has been been built into Notepad++ since [version 8.4.6](https://notepad-plus-plus.org/downloads/v8.4.6/#notepad-v8-4-6-bug-regression-fixes-and-new-features). It's more than likely that the plugin's custom implementation interferes badly with the native one.

**Comment by chcg** [comment]
There are some reports about problems with Npp 8.5 and newer. As @rdipardo mentioned the plugin is likely not compatible with newer N++ versions any more.

**Comment by swgmike** [comment]
The other plugin "JN" I listed is "JN notepad++ plugin"

https://github.com/KOLANICH-tools/jN-npp-scripts

**Comment by shodanx2** [comment]
Hello,

I have captured this issue on video.

This is version 8.6.1

I have these plugins installed, but the problem appears to come from Npp-Highlighter, which I otherwise really like. And I have had no other issues in months

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10621885/78dba530-eeaf-4e15-a391-2595583f464b)

and here is the video itself


https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10621885/a14f0eed-85c0-4a45-99f9-ec4fa858f7c3
