### ISSUE TITLE
Chinese colon problem with default font

### ISSUE THREAD

**Issue by orwithout** [notepad-plus-plus/notepad-plus-plus#14616]
### Description of the Issue
In the default font, the Chinese colon ":" is very similar to the ANSIC colon ":". In some extreme cases, it will be very difficult to troubleshoot.
### Steps to Reproduce the Issue
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/154397137/365f1a26-266f-4352-9009-5e15d57a84c9)

### OS
OS Name:                   Microsoft Windows Server 2022 Standard
OS Version:                10.0.20348 N/A Build 20348
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Server
OS Build Type:             Multiprocessor Free

**Comment by alankilborn** [comment]
If you don't fill out the issue template in its entirety, your issue is very likely to be closed without any response.

**Comment by rdipardo** [comment]
For reference, the OP is probably referring to [`U+FF1A (FULLWIDTH COLON)`](https://www.compart.com/en/unicode/U+FF1A).

@orwithout

There is no built-in function for detecting CJK punctuation marks, except maybe the lightly wider spacing around the character in more modern fonts than `Courier New`. Even the very old `Consolas` manages to distinguish them a little bit.

If the issue is really about invalid URLs creeping into the file, there's [a plugin](https://github.com/rdipardo/nppHTMLTag#usage) that will convert Unicode characters into their hexadecimal ordinals. You can try using that in combination with mark, search and replace to "clean" a file of Unicode punctuation, e.g.

<div align="center">
<img width="580" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59004801/79d37601-0436-47ff-a670-729069a79513" alt="reveal-cn-colon" />
</div>
