### ISSUE TITLE
Shift F3 search backward does not work...

### ISSUE THREAD

**Issue by klamser** [notepad-plus-plus/notepad-plus-plus#14647]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by alankilborn** [comment]
https://npp-user-manual.org/docs/searching/#:~:text=Regular%20expression%20%E2%80%9Cbackward%E2%80%9D%20search%20is%20disallowed%20due%20to%20sometimes%20surprising%20results

**Comment by monkeycoder99** [comment]
Thanks for the documentation link but the issue remains regardless. F3 works fine. Shift+F3 has stopped working. Note, for me, I have not added any additional Shortcuts. Further, I have verified in the Shortcut Mapper that only Find Previous is associated with Shift+F3. I have version 8.6.5.

Steps to Reproduce:
1. Select some text and press Ctrl+F3 to search forward. Or, use the Search dialog.
2. Press F3 to search for the next hit. Everything works.
3. Press Shift+F3 to go back to the first hit.

Expected Behavior:
Return to previous hit

Actual Behavior:
Nothing happens

Note: If you press Ctrl+Shift+F3, assuming text is still selected, it will search backward.

**Comment by alankilborn** [comment]
@monkeycoder99 If you look at the _Find_ window (if it is not currently open, open it), the circumstances you describe would seem consistent with _Search mode_ of _Regular expression_ being selected.

**Comment by donho** [comment]
@klamser 
If you don't want to take the time to provide the detail info, how people can help you?
