### ISSUE TITLE
Better 'sort windows order' for a manually customized sequence

### ISSUE THREAD

**Issue by andradadad** [notepad-plus-plus/notepad-plus-plus#14642]
### Description of the Issue

Having to drag the windows to organize the order of them is very tiring if the list is big.

### Steps to Reproduce the Issue

1. create new tab with tons of others
2. have to drag them
3. takes a long time

### Expected Behavior

Having to organize them faster by dragging, or even clicking here and there to better and easier organization.

### Actual Behavior

Dragging is horrible and takes an hour to actually reorganize, specially when opening a new tab which will take at least 1 minute of drag.

### Debug Information

Notepad++ v8.6.2   (64-bit)
Build time : Jan 14 2024 - 02:16:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Ultimate (64-bit)
OS Build : 
Current ANSI codepage : 1252
Plugins : 
    CustomLineNumbers (1.1.7)
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (3)
    NppConverter (4.5)
    NppExport (0.4)
    PreviewHTML (1.3.2)

The document list can't also drag down to my preferential order, so, relying on the slider drag takes even more time.
The option 'windows' or 'sort' are not taking in consideration a customized list of my intention.

**Comment by alankilborn** [comment]
So...dragging a tab is slow...?

**Comment by rjb1000** [comment]
From a UI design perspective, dragging tabs around manually is quite cumbersome, especially when there are many open tabs and even more so when the filenames are long so that only two or three tabs can be displayed on screen at a time.

Enabling the **multi-line tab bar** configuration option is one effective workaround that makes manual reordering a bearable user experience, but only up to a point. Irrespective of whether the **Reduce** option is selected or not, and whether horizontal or vertical layout is configured, the multi-line tab bar consumes precious screen real estate when there are many open tabs and/or when the filenames are long, so I wouldn't want to leave that option turned on all of the time.

My suggested solution is to add **drag and drop reordering of tabs in the Document List**. This would be a very handy feature when working with a lot of open tabs. And because the width of the Document List can be adjusted by a simple drag operation, the full filename can be exposed during the reordering task and then the Document List can then be shrunk down again afterwards.

**Comment by andradadad** [comment]
Nice answer, @rjb1000 
Multiline actually will be enough.
