### ISSUE TITLE
Change to NPPM_RELOADFILE in development build affects plugins

### ISSUE THREAD

**Issue by vinsworldcom** [notepad-plus-plus/notepad-plus-plus#14693]
### Description of the Issue
Testing with latest Notepad++ 64-bit development build, I can no longer use the `NPP_OPEN` function in [NppExec](https://github.com/d0vgan/nppexec).  The issue seems to stem from the commit:

https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bb278b26fc9a772242e702d2fac40c18c6cc21b9

where before this commit it worked and with this commit and after, it does not.

Checking first on the [NppExec issues](https://github.com/d0vgan/nppexec/issues), we had [this dialog](https://github.com/d0vgan/nppexec/issues/93).

### Steps to Reproduce the Issue

1. Install Notepad++ 64-bit development build from commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bb278b26fc9a772242e702d2fac40c18c6cc21b9
2. Install NppExec plugin
3. Open NppExec console and open a file with `NPP_OPEN c:\full\path\to\filename.ext`

where you use an actual path/file that exists on your system.

### Expected Behavior
The file should open in Notepad++

### Actual Behavior
The file does not open in Notepad++

### Debug Information
Notepad++ 64-bit from commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bb278b26fc9a772242e702d2fac40c18c6cc21b9
[NppExec 8.8](https://github.com/d0vgan/nppexec/releases/tag/v088)

**Comment by d0vgan** [comment]
In short, should return TRUE on success and return FALSE on failure.
As the "Notepad_plus_msgs.h" says:
~~~
#define NPPM_RELOADFILE (NPPMSG + 36)
	//BOOL NPPM_RELOADFILE(BOOL withAlert, TCHAR *filePathName2Reload)
~~~

**Comment by rdipardo** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/bb278b26fc9a772242e702d2fac40c18c6cc21b9/PowerEditor/src/NppBigSwitch.cpp#L683-L687

The call to `_pluginsManager.relayNppMessages()` at the end of `Notepad_plus::process` is unreachable because the `NPPM_RELOADFILE` callback returns immediately, whereas [before][0] there was only a `break` statement in there.

> [!TIP]
> Documentation changes are best done in separate commits from code changes.

[0]: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bb278b26fc9a772242e702d2fac40c18c6cc21b9#diff-535b965e72daa4f1a7d2c13666d39543c7b87c35b093f93dbfb7c621c085198cL685

**Comment by vinsworldcom** [comment]
To be clear, we think this is a breaking change in Notepad++, not the plugin.

**Comment by rdipardo** [comment]
@vinsworldcom 

> To be clear, we think this is a breaking change in Notepad++, not the plugin.

What's broken is the (until now) implicit assumption that `NPPM_RELOADFILE` would be forwarded to plugins via `PluginsManager::relayNppMessages`. Despite the documentation, the API would have always returned FALSE before (instead of always TRUE as now); the default value of the local `result` variable was never updated anywhere along the old code path. Plugins can send `NPPM_RELOADFILE` by themselves as they always could before; they just have to reverse their expectation about the return value.

Having said that, it does not look like a deliberate API change was intended here. In a function that's so overlong the compiler warns about how much local data is pushed to the stack [^1], it's easy to forget there's a call site at the bottom.


[^1]: ``...\PowerEditor\src\NppBigSwitch.cpp(256): warning C6262: Function uses '34776' bytes of stack.  Consider moving some data to heap.`` <https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/7846105861/job/21412038103#step:5:1102>

**Comment by donho** [comment]
@vinsworldcom 
Could you check the PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14708 please?

**Comment by MarkusBodensee** [comment]
For documentation reasons/tracking information: The result value has been adapted to return TRUE on success and FALSE on failure.

See commit:
060396c6988e278dbc10208099010947e72be6dc
