### ISSUE TITLE
Pressing the context menu key shows the context menu on the mouse position.

### ISSUE THREAD

**Issue by xMRi** [notepad-plus-plus/notepad-plus-plus#14727]
1.  Open a document in NotePad++
2.  Move the caret into the text
3.  Move the mouse cursor somewhere outside the text editor
4. Presse the context menu key (Windows Key, or Shift+F10)
5. The context menu pops up at the mouse position not near the caret position

I would expect that the context menu shows up at the caret position´(input position in the text)
Using x64 Notepad++ v8.6.2

Hint for the programmer:
The WM_CONTEXTMENU message is sent, with a position. If the context menu key is pressed than the x/y position is (-1,-1).

If the keyboard is used the caret position in the text should be used...

**Comment by alankilborn** [comment]
It seems reasonable, indeed, even the [WM_CONTEXTMENU](https://learn.microsoft.com/en-us/windows/win32/menurc/wm-contextmenu) documentation says so:

"If the context menu is generated from the keyboard ... then the application should display the context menu at the location of the current selection rather than at (xPos, yPos)."

Although that statement is intended to be application generic, I think we can interpret "location of the current selection" as caret position in Notepad++.
