### ISSUE TITLE
[FR] Allow multiple simultaneous windows in single sidebar

### ISSUE THREAD

**Issue by sdasda7777** [notepad-plus-plus/notepad-plus-plus#14745]
### Description of the feature
Would it be possible to allow multiple windows to be shown in single sidebar at the same time? There are windows that would be really helpful to be able to see, but are almost empty, so there isn't a reason why they should take up the whole sidebar.
I'd honestly be surprised if this isn't a duplicate, because this seems like a no-brainer, but I haven't found anything similar.

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/17746796/932ea7d3-2fc3-4dbf-afdf-3f104d5d7e0e)

**Comment by alankilborn** [comment]
Well, _usually_ people have the _Search results_ panel open, which defaults to full-length across the bottom, and that cuts down some vertical space for a side panel.

For me, I have never needed what you're asking for in your request, because the side panels I typically use fill the vertical space rather fully.

**Comment by xomx** [comment]
https://stackoverflow.com/a/68542006

If the above is what you want maybe you could ask the author (KnIfER) of that modification to back-port it to the Notepad++.

**Comment by sdasda7777** [comment]
Yeah, that looks exactly like what I'm looking for. I'll try, tysm!

**Comment by sdasda7777** [comment]
Hey, I started looking into this, but I got stuck. I believe most of the changes concern the `Gripper` class, specifically `onMove` and `onButtonUp`, but I can't seem to figure out where the "tab data exchange" happens when a floating `DockingCont` gets dragged into a docked one. I'll make a PR draft just so the code is saved somewhere.

**Comment by donho** [comment]
The requested feature behaviour is not well defined and hard to defined, also it's hard to implemented because concerning classes are not designed for such purpose. Therefore this feature will not be implemented.

**Comment by sdasda7777** [comment]
Huh? For one it seems pretty clear what the requested feature is. I'm also not asking anyone to implement it, but clearly there is demand for it, given how many people commented on the SO question with their own various hacks.

**Comment by sdasda7777** [comment]
By the way, [Kate](https://kate-editor.org/) seems to be able to do this. It doesn't have a ton of plugins, but it does have very nice git integration out of the box and supports LSP, while being comparable with N++ in terms of lighweightness.

**Comment by dogancelik** [comment]
I believe, the author suggested to support vertical and horizontal stacking for panels instead of stacking panels as tabs (and only show a single panel at a time). This could improve the user experience for users who want to have multiple panels visible.

A user from StackOverflow [suggested](https://stackoverflow.com/a/61622979) to manually move the panel windows like the screenshow below but this is not ideal as the panels are not moved automatically when the main window is moved or resized.
<img src="https://i.sstatic.net/aueww.png" width="500">
