### ISSUE TITLE
Data loss when using sort lines

### ISSUE THREAD

**Issue by JolanGorges** [notepad-plus-plus/notepad-plus-plus#14758]
### Description of the Issue

When using Edit -> Line Opertations -> Sort Lines Lexicographically Ascending on this file [sort.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/14335099/sort.txt)
 it goes from 34307 lines to 10505 lines, resulting in data loss.

### Debug Information
Notepad++ v8.6.2   (64-bit)
Build time : Jan 14 2024 - 02:16:00
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Home (64-bit)
OS Version : 24H2
OS Build : 26058.1100
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    JSMinNPP (1.2205)
    mimeTools (3)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by molsonkiko** [comment]
Your document contains `NUL` characters (ASCII code `0`), which cause weird issues with Notepad++. If you go to position 537062 in your file (which is the length of the document after attempting to sort lines) and turn on `Show All Characters`, you will see the first `NUL` character.

`NUL` characters should not occur in text documents, so I think this is a bug with your data source. You can use the find/replace form (`Ctrl+H` with normal keybindings) to replace `\x00` with nothing (with `Search Mode` set to `Regular expression`) and remove all the `NUL`s from the document.

That said, I feel like Notepad++ should make it a bit more obvious when `NUL` characters are causing problems. Maybe the methods that care about `NUL` characters should throw up a message box indicating that a `NUL` character was found?

**Comment by rdipardo** [comment]
See #13942, which this issue duplicates.

As [explained](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13942#issuecomment-1656902239) there, the document is truncated at the first `NULL` because the sorter loads the buffer into a __*null-terminated*__ C-string, or `char *`.

> **That said, I feel like Notepad++ should make it a bit more obvious when `NUL` characters are causing problems.** 

The problem is that Notepad++ will happily fill the buffer with any stream of bytes you feed it, even a binary octet stream. Some Scintilla editors refuse to open files with no obvious encoding; Geany does this even against the wishes [of some users][0] who prefer N++'s more lackadaisical programming.

[0]: https://github.com/geany/geany/discussions/3687
