### ISSUE TITLE
Update also for major versions - feature request

### ISSUE THREAD

**Issue by OpenGreenStreet** [notepad-plus-plus/notepad-plus-plus#14835]
### Steps to Reproduce the Issue

I often check for updates via the "?" - "Update Notepad++" menu. The updates work perfectly within a major version.
Unfortunately, I am not offered new major versions in this way. Unfortunately, this is only possible via the website https://notepad-plus-plus.org/downloads/
I would like to see new major versions also offered via the "?" - "Update Notepad++" menu

### Expected Behavior
Update also for major versions

### Actual Behavior
Updates only work within a major version

**Comment by pryrt** [comment]
I am not sure what _you_ mean by "major version", but if I open a portable v7.9.5 (which is a different major version -- 7 vs 8), and check for updates, it goes to https://notepad-plus-plus.org/update/getDownloadUrl.php?version=7.95 and finds 
```
<GUP>
<NeedToBeUpdated>yes</NeedToBeUpdated>
<Version>8.6.2</Version>
<Location>https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.6.2/npp.8.6.2.Installer.exe</Location>
</GUP>
```

The same is true if you go from v8.5.8 (which is a minor-version different, because of the difference between v8.5.x and v8.6.x), which goes to https://notepad-plus-plus.org/update/getDownloadUrl.php?version=8.58 and gets the same results.  And version 8.6.1, which varies only in the rightmost version, will poll https://notepad-plus-plus.org/update/getDownloadUrl.php?version=8.61 and also find out it needs upgrading.

However, my guess is that you're on v8.6.2, and when it polls https://notepad-plus-plus.org/update/getDownloadUrl.php?version=8.62, it will tell you that it doesn't need to be updated, even though [v8.6.4 actually exists](https://notepad-plus-plus.org/downloads/v8.6.4/).  I'm not sure why you use the phrase "major version" for this, but not everyone uses the same terminology, and maybe in your mind, any "released version" is a "major version".
```
<GUP>
<NeedToBeUpdated>no</NeedToBeUpdated>
</GUP>
```

This is because v8.6.3 and v8.6.4 have been released, but they were never triggered for automatic update (because of known issues) -- and until it's triggered for automatic update, the check-for-update won't find it.  The Online User Manual describes why this happens, at https://npp-user-manual.org/docs/upgrading/#no-new-version-found-safety-delay

So the **? > Update Notepad++** will always find if there's a newer released version than what you're using, assuming that the newer version has been triggered for automatic update.  The system is working as designed.

**Comment by OpenGreenStreet** [comment]
@pryrt Thank you very much for your feedback 

Hm, I don't know how to express it better : I'll try again using the points:

My experience over many version is:

Updates after the "second dot" (X.Y.z) are offered reliably. New versions after the first point (x.y.Z) are not offered to me. I have to download them myself. (Perhaps this is intentional, but I would like to always be offered the latest "Current Version" (at least optionally).)

**Comment by alankilborn** [comment]
> My experience over many version is:

I think that is how you _feel_ about it, not what is really happening.
As @pryrt tried to explain, update-notifications are enabled (or not) for any version based upon the whim of Notepad++'s author, not by any version numbering scheme algorithm.

>I would like to always be offered the latest "Current Version"

Sometimes "latest" versions have critical bugs.  Perhaps you want those as well. :-)
Seriously, the way it works now is designed to protect you from such critical bugs.
Just keep using whatever version you have, and if you get an update notification, feel good about doing that update (because it has been somewhat vetted against a terrible bug).

**Comment by pryrt** [comment]
> Updates after the "second dot" (X.Y.z) are offered reliably. New versions after the first point (x.y.Z) are not offered to me.

Your emphasis in those doesn't seem to agree to me with your "nth dot" nomenclature, so I cannot tell which way you are arguing.

So instead, let's look at actual data, instead of your vague memories and confusing nomenclature.

In the last 2 years, here is the list of every version that was triggered for auto-update:

| Date         | Version Triggered  | URL Evidence                                       |
|--------------|--------------------|----------------------------------------------------|
| Jan 21, 2024 | 8.6.2              | https://community.notepad-plus-plus.org/post/92252 |
| Dec 02, 2023 | 8.6 (8.6.0)        | https://community.notepad-plus-plus.org/post/90914 |
| Oct 24, 2023 | 8.5.8              | https://community.notepad-plus-plus.org/post/90059 |
| Sep 15, 2023 | 8.5.7              | https://community.notepad-plus-plus.org/post/89268 |
| Aug 16, 2023 | 8.5.6              | https://community.notepad-plus-plus.org/post/88652 |
| Jun 26, 2023 | 8.5.4              | https://community.notepad-plus-plus.org/post/87421 |
| May 21, 2023 | 8.5.3              | https://community.notepad-plus-plus.org/post/86479 |
| Dec 31, 2022 | 8.4.8              | https://community.notepad-plus-plus.org/post/82927 |
| Nov 20, 2022 | 8.4.7              | https://community.notepad-plus-plus.org/post/81806 |
| Oct 09, 2022 | 8.4.6              | https://community.notepad-plus-plus.org/post/80429 |
| Sep 14, 2022 | 8.4.5              | https://community.notepad-plus-plus.org/post/79812 |
| Jul 21, 2022 | 8.4.4              | https://community.notepad-plus-plus.org/post/78569 |
| Jun 09, 2022 | 8.4.2              | https://community.notepad-plus-plus.org/post/77404 |
| Mar 21, 2022 | 8.3.3              | https://community.notepad-plus-plus.org/post/75342 |
| Jan 30, 2022 | 8.2.1              | https://community.notepad-plus-plus.org/post/73479 |
| Dec 10, 2021 | 8.1.9.3            | https://community.notepad-plus-plus.org/post/72040 |
| Nov 04, 2021 | 8.1.9              | https://community.notepad-plus-plus.org/post/71120 |
| Oct 03, 2021 | 8.1.5              | https://community.notepad-plus-plus.org/post/70224 |
| Aug 30, 2021 | 8.1.4              | https://community.notepad-plus-plus.org/post/69374 |
| Aug 18, 2021 | 8.1.3              | https://community.notepad-plus-plus.org/post/69037 |
| Jul 23, 2021 | 8.1.2              | https://community.notepad-plus-plus.org/post/68243 |
| Jul 07, 2021 | 8.1.1              | https://community.notepad-plus-plus.org/post/67745 |
| Mar 28, 2021 | 7.9.5              | https://community.notepad-plus-plus.org/post/64447 |

In the 23 versions triggered for update in that timeframe, ONE was an X.Y (aka X.Y.0) version.  The other 23 were X.Y.Z versions.

This is likely because the X and X.Y versions (ie, 8, 8.1, 8.2, 8.3, 8.4, and 8.5) are more likely to have the fancy new features; but the implementations of the fancy new features are more likely to require X.Y.Z versions (or even X.Y.Z.W versions) to fix bugs that were accidentally introduced in the new features.  (Even 8.6, which was deemed good enough for auto-update, was quickly replaced by 8.6.1 and 8.6.2, in a matter of three weeks, to get a more-stable release as the auto-update.)

And, as we've said before, until a release is deemed "stable", Don doesn't like to "force" them on users using auto-update.  

So if you are saying that you don't often see X.Y (or X.Y.0) versions in auto-update, I would agree with you.  And this is because they ended up not being stable, and had annoying bugs that made a large number of users complain in the first week or two after that new version was released, so that version didn't trigger auto-update, to protect you against annoyance.  If you'd rather be annoyed by being asked to update to unstable versions, you are allowed to _want_ that, but don't be surprised when Don doesn't do that, because he doesn't want to send a known-bad version automatically to thousands of users.

**Comment by OpenGreenStreet** [comment]
@pryrt Thank you very much for the detailed explanation. I can understand that very well.

Let's take a look at the website:

https://notepad-plus-plus.org/downloads/

How can I tell which version is "triggered for auto-update"? This would be very important for people who are responsible for providing software in larger organizations. Either because Notepad++ is being deployed for the first time or because automatic updates are not desired or not possible due to user permissions.

**Comment by OpenGreenStreet** [comment]
Perhaps there could be a link at the bottom of the download page ("Notes for administrators" or similar) that leads to the above overview and shows which version is released for automatic updates?

**Comment by pryrt** [comment]
> https://notepad-plus-plus.org/downloads/
> 
> How can I tell which version is "triggered for auto-update"? This would be very important for people who are responsible for providing software in larger organizations.

Good point.  Right now, you could go to the download page for a version, follow the link to the Announcement Topic in the Forum, then skim through to see if Don has a post saying it is triggered for automatic update.  But that's a lot of work on your part.  

Maybe @donho will implement some indication in the downloads page and the individual version download pages so that admins can easily see if that version was triggered.

**Comment by donho** [comment]
> for any version based upon the whim of Notepad++'s author

To clarify, it is indeed my responsibility to determine whether a version should be popularized and trigger auto-updates. However, the sole criteria for this decision is stability and the absence of regression. The statement that it is based on the "whim" of Notepad++'s author is absolutely inaccurate.

@pryrt 
> Maybe @donho will implement some indication in the downloads page and the individual version download pages so that admins can easily see if that version was triggered.

I'll see what I can do about it.

**Comment by alankilborn** [comment]
> The statement that it is based on the "whim" of Notepad++'s author is absolutely inaccurate.

It's probably a language problem rather than an inaccuracy.
What was meant here is that it is totally an author decision...others may disagree with that decision but have no voice in it.
And, as stated much above, it has no firm tie to version numbering.

**Comment by OpenGreenStreet** [comment]
@donho & @pryrt:
Thank you, I would be very happy if a possibility could be found that contains a hint for administrators without interfering with the necessary process of field testing. (for example as a link "Notes for network administrators")

**Comment by donho** [comment]
https://notepad-plus-plus.org/downloads/

**Comment by OpenGreenStreet** [comment]
@donho great, thank you very much
