### ISSUE TITLE
Find dialog doesn't allow to select a different tab easily via the keyboard

### ISSUE THREAD

**Issue by xMRi** [notepad-plus-plus/notepad-plus-plus#14975]
### Steps to Reproduce the Issue
1.  Open the find dialog
2.  The first tab is active 
3. Try to access the Tab "Mark" just with the keyboard

### Expected Behavior
I want to use F6, or Shift+F6, Ctrl+PageUp, Ctrl+PageDown, or press Alt+Hotkey to activate another tab page in the Find Dialog 
This are standard hotkey in Windows!

Or Ctrl+Number to access the first, second, third tab.

### Actual Behavior
The onyl way is to press Shift+Tab, move the focus to the tab, press right or left.
The focus turns back onto the first control in the tab.
I have to repeat Shift+Tab, Right.

### Comment
The keyboard interface of Notepad++ is horrible and!

**Comment by sXNA** [comment]
@xMRi 
I just tried your standard hotkeys in some tabbed applications and not all of them did work (Windows 11 explorer, explorer properties window, notepad, terminal, ...). All hotkeys work only in browsers for me. 

So these "standard" hotkeys are not so standard even for MS.
And if keyboard interface of Notepad++ is horrible, you can always change shortcuts in Shortcut mapper or do some PR to improve it.

Except for Find in Project tab I can easily switch between them using keyboard.
Ctrl+F : Find
Ctrl+H : Replace
Ctrl+Shift+F : Find in Files
Ctrl+M : Mark

**Comment by xMRi** [comment]
Standard Windows Property Sheets:
Open Explorer (Windows+E)
Open Properties of A file (Alt+Enter

Paging in Property Sheet: Ctrl+PgUp/dn

**Comment by xomx** [comment]
@alankilborn 

I do remember that Ctrl+Tab / Ctrl+Shift+Tab request: #7932
There was even a good PR for that, but unfortunately it was rejected: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10170

I am somewhat used to that shortcuts from another apps, so having this also in N++ would be a nice feature for me.

**Comment by xMRi** [comment]
If I look into the Wine code I find Ctrl+Tab, Shift+Ctrl+Tab, Ctrl+PgUp, Ctrl+PgDn
https://github.com/wine-mirror/wine/blob/master/dlls/comctl32/propsheet.c

I just debugged into the proerty sheet message handler and it seams that there is the same code in it.

**Comment by ozone10** [comment]
@xMRi 
I've checked some apps with tabs and <kbd>F6</kbd>, or <kbd>Shift</kbd>+<kbd>F6</kbd> did not work, same with <kbd>Alt</kbd>+<kbd>Hotkey</kbd> since they did not have accelerators.
<kbd>Ctrl</kbd>+<kbd>PgDn</kbd> and <kbd>Ctrl</kbd>+<kbd>PgUp</kbd> worked only in property sheet and process explorer select columns dialog, so IMHO only "default" win32 implementation, unless developer implement it.

Only <kbd>Ctrl</kbd>+<kbd>Tab</kbd> and <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Tab</kbd> worked.
IMHO only <kbd>Ctrl</kbd>+<kbd>Tab</kbd> and <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Tab</kbd> should be implemented in Notepad++.

**Comment by alankilborn** [comment]
> IMHO only Ctrl+Tab and Ctrl+Shift+Tab should be implemented in Notepad++.

(I agree, but...) Isn't that just one more way to make/keep the UI inconsistent?

Some points:

* editing tabs: "Next Tab" (default Ctrl+PgDn) and "Previous Tab" (default Ctrl+PgUp)
* editing tabs (invoking popup "switcher"): Ctrl+Tab / Ctrl+Shift+Tab
* find dialog (proposed): next tab (Ctrl+Tab) and previous tab (Ctrl+Shift+Tab)
* find dialog (existing): no next/prev, but rather direct jump via (defaults) of Ctrl+f et al
* other areas in the UI, e.g. "Shortcut Mapper" window (currently no way to change tabs -- via keyboard -- that I see; a way to do it should be added)

I'm fine with Ctrl+Tab / Ctrl+Shift+Tab, but it seems like it should be that way everywhere that there is a page-control/tabbed interface.

**Comment by ozone10** [comment]
> * editing tabs: "Next Tab" (default Ctrl+PgDn) and "Previous Tab" (default Ctrl+PgUp)
> * editing tabs (invoking popup "switcher"): Ctrl+Tab / Ctrl+Shift+Tab

Switcher is even hardcoded, and if you disable it, it will work same as Next/Previous Tab
also https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14988#issuecomment-2053536354

> * find dialog (proposed): next tab (Ctrl+Tab) and previous tab (Ctrl+Shift+Tab)

this PR  https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14988

> * find dialog (existing): no next/prev, but rather direct jump via (defaults) of Ctrl+f et al

I would keep this since user can change shortcut for them. But Find in Project is missing

> * other areas in the UI, e.g. "Shortcut Mapper" window (have to use Tab to get input focus on one of the tabs, then can use left/right arrow keys to switch tabs)

Every tabbed dialogs (Plugin Admin, UDL, Shortcut Mapper) in Notepad++ except Find allow arrow keys to switch tab.

> I'm fine with Ctrl+Tab / Ctrl+Shift+Tab, but it seems like it should be that way everywhere that there is a page-control/tabbed interface.

I agree, but unlike Find dialog this will require more work, but it should be easy since it's mainly "copy&pasting" existing implementation for Find dialog.

**Comment by alankilborn** [comment]
>find dialog

>I would keep this since user can change shortcut for them

But that would do nothing for for unifiying UI behavior. 

>But Find in Project is missing

And adding something for that was rejected at one time.

**Comment by ozone10** [comment]
> But that would do nothing for for unifiying UI behavior.

I consider it as feature and very old I think. And I am sure some users are already used to workflow <kbd>Ctrl</kbd>+<kbd>F</kbd> -> <kbd>Ctrl</kbd>+<kbd>H</kbd> or may have changed shortcut for it. So removing it may bring new issues. 

And mainly as solution to lost dialog I find it very useful.
