### ISSUE TITLE
[BUG] Find window: Checkboxes working if clicked in blank space.

### ISSUE THREAD

**Issue by kaustubh43** [notepad-plus-plus/notepad-plus-plus#15006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

In the find menu, 
The check boxes get checked/unchecked if we click in blank space which is inline with the option
![notepad++-misclick](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/68014091/0f838f59-2bf6-4b99-af31-0dc5c0e80c36)

### Steps To Reproduce

1.  CTRL + F : to open Find window
2.  Click next to the option Backward direction(or any other option) in the blank space

### Current Behavior

Check boxes getting checked/unchecked if clicked in blank space.

### Expected Behavior

Check boxes should not be checked/unchecked when clicked in blank space next to it.
They should be functional only when clicked on the text or the checkbox.

### Debug Information

```shell
Notepad++ v8.6.5   (64-bit)
Build time : Mar 29 2024 - 17:04:43
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : D:\
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit
OS Version : 23H2
OS Build : 22631.3447
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    Explorer (1.9.9)
    JsonTools (5)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (2.0.5)
    Python Indent (1.0.0.4)
    PythonScript (2)
    XMLTools (3.1.1.13)
```

**Comment by xomx** [comment]
It has to be that, it is due to reserved space for a possible GUI translation.

English text labels are usually shorter than its translated counterparts. So a label area has to be somewhat longer, e.g.:

![npp-longer-text-fields-for-translation](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/35fa03d0-a895-4c61-ac90-3bb6582b366e)

**Comment by donho** [comment]
It's not bug.

**Comment by alankilborn** [comment]
@xomx 
Is it feasible to resize (at runtime) such controls after they get their localization text set, so that @kaustubh43 's complaint would not occur?

**Comment by xomx** [comment]
@alankilborn 
> Is it feasible to resize (at runtime) such controls after they get their localization text set

Yes (probably, I did something like that a long time ago, I do not remember much). But you have to set the dynamic layout properties programmatically at runtime because the N++ users can change their langs at runtime too. For that you use the CreateDialogIndirectParam WINAPI, which creates a modeless dlg from a dlg template in memory (and not from the static resource one...). So that way all is theoretically customizable, even the ctrl label sizes (you adjust your in-memory dlg-template by checking the ctrl current text length, recalculate to actual pixel-size, an so on...). IMO - too much hassle for too little gain.

**Comment by alankilborn** [comment]
@xomx 

"too much hassle for too little gain" == "infeasible" :-)

I wonder if it gets more reasonable if you don't worry about it when users change their localization language at runtime -- users typically only do this _once_ anyway.

**Comment by alankilborn** [comment]
@kaustubh43 

I presume this is a problem for you when the _Find_ window is not focused but you want to make it active and you do so with the mouse by clicking in what you think is an empty area.  If this is the case, then suggest workarounds of (pick one):

* Always click the titlebar of the _Find_ window to activate it
* Use the direct keycombo for the _Find_ window tab page you want to go to (e.g., Ctrl+f, Ctrl+h, etc) -- this is not ideal because _Find in Projects_ doesn't have a keycombo, and/or pressing Ctrl+f can auto-populate _Find what_ and that may not be wanted)

**Comment by kaustubh43** [comment]
@alankilborn Yes, that is when the issue exactly occurs(when Find window is not focused). It has led to me missing out on keywords that I am searching for, simply because some option got checked. 

We can close this issue since it is identified as infeasible.

**Comment by alankilborn** [comment]
Final thought, and I'm interested in @xomx 's opinion most here, I suppose:  Should a click anywhere (client area) on an inactive window simply activate the window, or, if the click happens to be on a control, should it activate the window AND actuate the control's functionality?

**Comment by kaustubh43** [comment]
@alankilborn I suppose it is already closed. Correct me if I am wrong. Thank you!

**Comment by ozone10** [comment]
@alankilborn @xomx 
if it's only checkboxes and radio buttons it's easy when using [Button_GetIdealSize](https://learn.microsoft.com/en-us/windows/win32/api/commctrl/nf-commctrl-button_getidealsize)

@kaustubh43 
you can check PR

Still I am not sure if it will be accepted.

**Comment by xomx** [comment]
@ozone10 
Nice, works ok!
I was originally going to ping you with this, but then I decided I would not bother you with this one :-)

@alankilborn 
> should it activate the window AND actuate the control's functionality

this one is correct, test:
[DlgApp.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/14999899/DlgApp.zip)

**Comment by alankilborn** [comment]
> this one is correct, test:
> DlgApp.zip

I'm away from my PC until late tomorrow -- give me a preview, though... what is this DlgApp ?

**Comment by alankilborn** [comment]
> and it reacts exactly according to your second option.

Still not back at PC but presume this means that this little demo dialog app, when it doesn't have input focus but you move the mouse and click on `Check 1` that it will activate the app **AND** check the checkbox in one action?

I notice that different apps act differently in this regard, the most recent example in my mind about this is Windows' "Snipping Tool".  If I take a screenshot with Win+Shift+s, then "Snipping Tool" opens, and for me it does so with the "yellow highlighter" tool active and ready to go to make highlights on the captured image.  If I then shift input focus to another app (e.g. N++), but then realize I want to do more highlighting on the image, I can see "Snipping Tool" seems to be set up to continue my yellow highlighting.  But, if I move to the inactive window and click+drag to highlight, the window is made active but highlighting doesn't happen.  I have to lift the mouse and restart my click+drag to do it.

So the "Snipping Tool" example isn't exactly the same situation, (as the checkbox example) but I'm just wondering if there is supposed to be some sort of standard in this regard?

**Comment by xomx** [comment]
> this little demo dialog app, when it doesn't have input focus but you move the mouse and click on `Check 1` that it will activate the app **AND** check the checkbox in one action?

Yes.
I chose that DialogBox app to match the reported N++ problem with Find-dlg as closely as possible and to rule out a bug or non-standard behavior of the N++.

> I notice that different apps act differently in this regard,

I can confirm this. 
While I e.g. opened a Firefox and overlapped it partially with Explorer, clicking in to the inactive Firefox-wnd on a place where is something possible to activate, it works as in the N++ Find-dlg case. But when I used the MS Word instead of the Firefox, it behaves like in your SnippingTool case.

> I'm just wondering if there is supposed to be some sort of standard in this regard?

Probably not. I guess that it will depend on the GUI framework and on the relevant Windows messages handling used.

**Comment by alankilborn** [comment]
>  I'm just wondering if there is supposed to be some sort of standard in this regard?
 
> Probably not. I guess that it will depend on the GUI framework and on the relevant Windows messages handling used.

What I meant was, if there _IS_ a standard, Notepad++ could be made to follow that standard.  But...if no standard...then it is a free-for-all.

So in 2 Microsoft apps (my Snipping Tool example and your Word example) that work similarly in this regard...could it be a Microsoft standard, and, as the Operating System vendor, that's enough to _set_ a pseudo-standard?  This has clearly caused a problem for @kaustubh43 in this issue (i.e., if clicking a control merely activates an inactive window, and doesn't execute control functionality, this issue would be moot).

**Comment by xomx** [comment]
> Perhaps I was seeking the "short answer"

Thanks to your persisting answer-searching and the @ozone10 UI programming skillz, we will probably have more error-proof and useful app-GUI. Moreover I learned something new useful, so 👍

**Comment by kaustubh43** [comment]
>This has clearly caused a problem for @kaustubh43 in this issue (i.e., if clicking a control merely activates an inactive window, and >doesn't execute control functionality, this issue would be moot).

@alankilborn exactly my issue, it does check/uncheck if I click on it and it is out of focus.

Thank you guys for the support.

**Comment by alankilborn** [comment]
So there's two schools of thought...if the _Find_ window is not active:

* a click anywhere in it should simply activate the window
* a click on a control in the window should activate the window and then run the clicked-on control's click event
