### ISSUE TITLE
[8.6.2] Display live console to work with Python script?

### ISSUE THREAD

**Issue by Shohreh** [notepad-plus-plus/notepad-plus-plus#15049]
Hello,

I'd like to find how to get NppExec to display the output from a Python script [in a console](https://community.notepad-plus-plus.org/topic/12743/how-to-show-the-console-window/5) within NPP so I don't need to switch back and forth to Windows' cmd window, but [the forum](https://community.notepad-plus-plus.org/) provides no way to sign up — it only displays a "Login" link.

Thank you.

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/1541861/310d95be-0df0-4929-af99-53ba25446a46)

**Comment by alankilborn** [comment]
You should be able to login to the Community forum using your Github credentials.

Regardless, your question isn't appropriate here, and is likely to go unanswered.

**Comment by gitgrub** [comment]
If you just want to write python scripts, I think its better to use an appropriate IDE.
The PyCharm Community Edition works very well for me, find it at https://www.jetbrains.com/pycharm/download/?section=windows - scroll down. It is free and helpful.

I love Notepad++, using it since many years, but better find the right tool for a given job.

**Comment by Shohreh** [comment]
Tried logging with Github: "Invalid Email"

Thanks for the tip on PyCharm.

**Comment by ArkadiuszMichalski** [comment]
Please ask such a question on the official forum.
https://community.notepad-plus-plus.org/
