### ISSUE TITLE
RegEx Select & Wrap URLs /w Angle Brackets Functionality

### ISSUE THREAD

**Issue by alienfxfiend** [notepad-plus-plus/notepad-plus-plus#15114]
NPP lacks the functionality to wrap characters (delimiters) around a URL [for instance] using Replace dialog RegEx. Currently I believe it only modifies the first occurrence. I would welcome a Python script to achieve this also. Other text editors allow doing this, but NPP being my mainstay —I'd like to have this handy.

**Comment by molsonkiko** [comment]
Before claiming that any regex implementation lacks the capability to do X, you should learn about the [capabilities of the regex engine](https://npp-user-manual.org/docs/searching/#regular-expressions) and fully articulate what you want, including examples of things that should and should not match your regex.

Until you provide some examples, nobody is going to be inclined to give you any assistance beyond recommending that you read the documentation.

**Comment by alankilborn** [comment]
> Until you provide some examples

...which would have taken care of itself if @alienfxfiend had submitted an issue using the issue template.

**Comment by alienfxfiend** [comment]
Oh sorry, I cannot use this RegEx select: (http://[^\s]+) to Replace links into this (add wrapping Angle Brackets surrounding it): <$1> (it only selects the first occurrence, (& I remember reading about how NPP does not support this kind of multi-selects (I think, in an AI model prompt).)

**Comment by molsonkiko** [comment]
@alienfxfiend 

__Don't ask large language models (LLMs) about Notepad++.__ They will mostly tell you lies. This is because there just isn't enough *true* information about Notepad++ in their training data.

I would also discourage using LLMs for regex. There are better sources; I think StackOverflow is better. It is still useful to learn how regular expressions work, so that if you find a regular expression that doesn't work for you, you can modify it to make it work better. In your example, `(http://[^\s]+)` only matches URLs with the `http` protocol, whereas you probably want to match the `https` protocol as well.

In any case, a quick DuckDuckGo search for `url match regex` turned up [this StackOverflow post](https://stackoverflow.com/a/3809435/18441560), from which I got a regular expression that I modified slightly to `(?-i)https?://(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)`

Also, you don't need to wrap the regular expression in grouping parentheses in Notepad++. If you want to wrap `some text` in `()`, you can just regex-replace `some text` with `(${0})`, because Notepad++ supports backreferences to the entire captured string as `${0}`.

**Comment by alienfxfiend** [comment]
Apologies, I was addressing the wrong issue. So I have a list of words & I want to add a prefix -= and suffix =- to each multi-selected words, but the "In Selection" in the "Replace" dialog grays out the option. The result is every word in the current document gets the delimiters -= & =-    .I need NPP to allow me to add prefix -= & suffix =- to multiple selections of words among a text. I used this RegEx: \b(\w+)\b    & replaced with: -=$1=-    .This is why I said NPP doesn't have this functionality. Links can be wrapped in Angle-Brackets but multiple words among many cannot using RegEx ! Please try to fix this in the future.

**Comment by alienfxfiend** [comment]
O.K. I got it all sorted, thank you. Sorry for the bewildering lengthy posts /w so many issues being listed. In the end, Notepad++ has a robust solution to these problems !

**Comment by alankilborn** [comment]
> I want to add a prefix -= and suffix =- to each multi-selected words

As N++ doesn't support multiselected text as the result of a search, the way to achieve something like that is doing a replace instead, where you add in the `-=` / `=-` (or whatever) delimiters as part of the _Replace with_ text expression.
