### ISSUE TITLE
[Feature request] Auto-indentation in Python

### ISSUE THREAD

**Issue by BlueBatSamurai** [notepad-plus-plus/notepad-plus-plus#15122]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Description of the Issue

In Python it's nessessary to indent every statement inside an if, loop, function definition or similar block. 

Therefore e.g. IDLE automatically indents the next line with an additional tab when you press enter after a colon. 
But apparently Notepad++ doesn't support this.

### Describe the solution you'd like.

It would be very helpful if you could add this feature to Notepad++ too. 
(But maybe _only_ for files in Python language, as in other contexts you may not want this to happen. 
And you should be able to disable it in the settings.)

### Debug Information

```shell
Notepad++ v8.6.5   (64-bit)
Build time : Mar 29 2024 - 17:04:43
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit
OS Version : 22H2
OS Build : 19045.4291
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by DroidFreak36** [comment]
Please change this feature from always-on to optional. I prefer the old style of auto-indentation (where it simply maintains indentation) but it seems that this is no longer possible in new versions of NPP because turning auto-indent off makes it not maintain indentation and turning it on makes it automatically indent after folds. As it is, I will have to stick with older versions to get the behavior I prefer.

**Comment by alankilborn** [comment]
@DroidFreak36 

In the next release of Notepad++ will be an increased option set:

![image](https://github.com/user-attachments/assets/bedb8396-c12f-4081-92f6-a6a16ad76ad7)

To get your desired behavior, you will want to choose _Basic_:

![image](https://github.com/user-attachments/assets/31abf78e-f42b-47fe-821f-f60e61c1f22e)

**Comment by alankilborn** [comment]
@donho Is this feature going to be further changed so that the _Auto-indent_ is a per-language feature?  That is, will it be moved into the _Indent Settings_ box so that it can be set differently for different languages?  For example, users might not want _Advanced_ indent for Python, but would want it for C...

I would be willing to do this work, if it is desired.

**Comment by donho** [comment]
> Is this feature going to be further changed so that the Auto-indent is a per-language feature? 

I don't think so. Because not all languages have "smart" indent, it cannot be per language.

**Comment by alankilborn** [comment]
@donho 

>Because not all languages have "smart" indent, it cannot be per language.

It's true that not all have "smart", but it could be shown as greyed/disabled for those languages that don't have it, right?
I think it would be valuable to have it per language.

**Comment by donho** [comment]
> It's true that not all have "smart", but it could be shown as greyed/disabled for those languages that don't have it, right?
I think it would be valuable to have it per language.

IMO, it'll make the confusion.
It's good to preview some eventual problem. But let's see if such problem can really happen (and happen to many users).
