### ISSUE TITLE
[BUG] Negative repeat value in Column Editor causes hang

### ISSUE THREAD

**Issue by cddiffz** [notepad-plus-plus/notepad-plus-plus#15153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

If you try to use the Column Editor to insert numbers with a negative number pasted into the "Repeat" field, the program hangs.

### Steps To Reproduce

1.  Copy -1 to the clipboard
2.  Open Column Editor, select "Number to Insert", paste -1 into the "Repeat" field
3.  Press "OK"

### Current Behavior

Program stops responding

### Expected Behavior

Either the repeat value is internally set to 1 (as if nothing or 0 was entered) or an error is reported.

### Debug Information

```shell
Notepad++ v8.6.7   (64-bit)
Build time : May 12 2024 - 20:04:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 1809
OS Build : 17763.1579
Current ANSI codepage : 1252
Plugins :
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by molsonkiko** [comment]
Looks like it can be fixed with a simple change of [this line](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/382c33e99a7e4b9a18ceaba83275c9a7a40d12c6/PowerEditor/src/ScintillaComponent/columnEditor.cpp#L245) from a `==` comparison to a `<=` comparison (i.e., would become `if (repeat <= 0)`) would fix this problem.

**Comment by molsonkiko** [comment]
This problem is fixed in [this commit](https://github.com/molsonkiko/notepad-plus-plus/commit/320527196194d5e094b036ad7288eef74bd0efd8), but I'm holding off on submitting a PR, because __I think this issue is mainly due to a lack of understanding of what the `repeat` field is for.__ 
IMO any user who understands the purpose of the `repeat` field would not deliberately paste in a negative number, and it's not possible to enter a negative number except by pasting, so I'm not sure this is even worth a PR. If a core dev disagrees, I'll submit the PR.
The relevant documentation is [here in the user manual](https://npp-user-manual.org/docs/editing/#selection-modes--column-editor), and I think it's already clear enough as is, but maybe if it were clearer people wouldn't make this mistake?

**Comment by alankilborn** [comment]
>and it's not possible to enter a negative number except by pasting

Sigh.  Because users apparently will try this, IMO it deserves to be prevented.

**Comment by donho** [comment]
@molsonkiko 
It's not about the common sense of the users, but the attack from hackers - for the sake of security, any crash should be prevented.
You can summit the PR for fixing the issue, it will be merged into the master.
