### ISSUE TITLE
[BUG] Integer overflow in Column Editor

### ISSUE THREAD

**Issue by cddiffz** [notepad-plus-plus/notepad-plus-plus#15167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When you insert a sequence of numbers with the Column Editor, you expect the sequence to be monotonically increasing, but this is not the case if the number becomes too large at some point.

### Steps To Reproduce

1.  Create a new file with 216 empty lines
2.  Place the cursor in the first line
3.  Open Column Editor, select "Number to Insert", set "Increase by" to 9999999, "Repeat" to 1, and "Format" to "Dec"
4.  Press "OK"

### Current Behavior

A negative number is displayed on the last line.

### Expected Behavior

A consistent positive number is displayed on the last line.

### Debug Information

```shell
Notepad++ v8.6.7   (64-bit)
Build time : May 12 2024 - 20:04:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 1809
OS Build : 17763.1579
Current ANSI codepage : 1252
Plugins :
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by molsonkiko** [comment]
At present it looks like the Column Editor uses [32-bit integers](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/106bdcc0164e819cc83f999bd4f95978ecf2f1ea/PowerEditor/src/ScintillaComponent/columnEditor.cpp#L275) to calculate the number to be placed in lines. This means that integer overflow is guaranteed to occur after `2147483647` and wrap around to `-2147483648`.
The Column Editor could instead use 64-bit integers, but that doesn't eliminate this problem; it only increases the range of permissible integers to between +/- `9.223372e+18`. AFAIK there is no signed integer larger than that in the C++ standard library, and I hardly think that fixing this issue is important enough to justify the inclusion of a third-party dependency that implements Python-style big integers.

@cddiffz 
Given that integer overflow in the Column Editor is presumably here to stay, what do you think would be a reasonable patch? Create a message box that warns the user when integer overflow is detected?

**Comment by cddiffz** [comment]
As you can see above, I tested with a 64-bit build where `int` is also only 32 bits wide.
Aborting the sequence after the overflow and inserting fewer numbers would be an easy solution.
But I think the best solution would be to upgrade to 64 bits. Since the input values are limited to 9999999, the overflow can practically never happen.

**Comment by donho** [comment]
@cddiffz 
Could you check #15222 please?
