### ISSUE TITLE
[Feature request] AutoCompletion and FunctionList in userDefineLangs

### ISSUE THREAD

**Issue by MdU2023** [notepad-plus-plus/notepad-plus-plus#15183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Hello Community,

It would be great if the AutoCompletion and FunctionList entries could somehow be configured for user-defined languages within NotePad++. I've spent several hours unsuccessfully trying to integrate word suggestions, syntax displays, and block suggestions into the XML files. However, setting up the highlighting worked without any problems.

I'm currently working on implementing the LibreOffice Basic language.

Neither adding various blocks within the corresponding userDefineLangs XML file nor creating custom XML files within the autoCompletion and functionList directories seem to be recognized by NotePad++. No matter how I try and adjust it.
![ScreenshotDemoLob2](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/140939855/cbbe2f52-b8ad-4408-9455-20a7e69cf270)

### Describe the solution you'd like.

My suggestion is to have buttons within the style settings of user-defined language syntax highlighting that generate the basic files for each point (e.g., word suggestions, syntax, or example code blocks). These buttons would create files with a basic example as a comment. That would be fantastic. Possibly, after creating the files, the same button could be used to directly open and edit them. It wouldn’t need to be configurable directly via the GUI.

Additionally, it would be great if any internal references could also be set automatically. Furthermore, it might be beneficial to have the option to publish complete translations (including used colors, syntax, etc.) as a package directly or to forward them to the developers.

### Debug Information

```shell
I tried with NPP 8.6.7 portable, also with the local installed Version:

Notepad++ v8.6.7   (64-bit)
Build time : May 12 2024 - 20:04:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.3593
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by pryrt** [comment]
> It would be great if the AutoCompletion and FunctionList entries could somehow be configured for user-defined languages within NotePad++. I've spent several hours unsuccessfully trying to integrate word suggestions, syntax displays, and block suggestions into the XML files. However, setting up the highlighting worked without any problems.

Notepad++ can handle AutoCompletion and FunctionList for UDL languages; but like all AutoCompletion and FunctionList, they use their own XML definitions, and are not part of the GUI -- but that's no different from the built-in languages, where you also cannot define or edit the AutoCompletion or FunctionList definitions in the GUI.  

> My suggestion is to have buttons within the style settings of user-defined language syntax highlighting that generate the basic files for each point (e.g., word suggestions, syntax, or example code blocks). These buttons would create files with a basic example as a comment. That would be fantastic.

The way that I always create them is I copy them from a known-good XML definition, and then edit it from there.  Which is effectively the same as "generate the basic example", but doesn't use a button in the GUI.

If you need help implementing the AutoCompletion and FunctionList, I suggest going to the [Notepad++ Community Forum](https://community.notepad-plus-plus.org/), and posting something in the Help Wanted -- because the Forum is better set up for helping users to make use of features that already exist, whereas this Issues list focuses on feature requests and bugs.  We've helped a lot of people with such definitions in the past, so if you share what you've tried so far over there, we can probably help you get it working.

This Issue will be left open as a feature request, because I am not the one who decides what features will be implemented, and having a button to generate / edit AutoCompletion and FunctionList in general (and not just for UDL) seems like a good idea to me.... though getting an interface as detailed as you requested is probably not simple.

**Comment by MdU2023** [comment]
Hello everyone,

thank you for your support and the responses to my request about simplifying the creation of user-defined syntax recognition for new languages in Notepad++.

I would like to inform you that I am withdrawing my request, as I have now created the project specifically for Visual Studio Code, including syntax highlighting, arguments view, code completion, and code examples.

Thanks again for your help and the great work you are doing!

Best regards,
Mike
