### ISSUE TITLE
[Feature request] Have backspace delete spaces back to previous tabstop

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#15180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

In a nutshell, implement [SCI_SETBACKSPACEUNINDENTS](https://www.scintilla.org/ScintillaDoc.html#SCI_SETBACKSPACEUNINDENTS)(true/false), with a new preference setting controlling the true/false part as an enable/disable.

Preference setting could go on the `Editing2` subpage, with checkbox text of `Enable Backspacing Unindent` or `Enable backspacing of multiple spaces to previous tabstop` or ...?

Enable by default (so that users realize that it is a new feature).

### Describe the solution you'd like.

See Description above.

### Debug Information

```shell
Notepad++ v8.6.7   (64-bit)
Build time : May 12 2024 - 20:04:00
Path : C:\NotepadPlusPlus\Misc\_NoBackup\Releases\npp.8.6.7\npp.8.6.7.portable.x64\notepad++.exe
Command Line : -titleAdd="8.6.7 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.3593
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    PythonScript (3.0.16)
```

**Comment by alankilborn** [comment]
@donho If you like this, assign me please.  If not, let's close it.

**Comment by donho** [comment]
@alankilborn 
Hmm... In Notepad++, TAB is always one unit of indent. So what's the point of this Scintilla API for Notepad++?

**Comment by alankilborn** [comment]
>what's the point...

So if you have:

`ssssSsssSsssSsssSsssC`

where `s` is space
and `S` is space at a tabstop
and `C` is your caret

Normally presses of backspace gets you this, one press at a time:

`ssssSsssSsssSsssSssC`
`ssssSsssSsssSsssSsC`
`ssssSsssSsssSsssSC`
`ssssSsssSsssSsssC`
`ssssSsssSsssSssC`
etc., one character removal at each press

but with this Scintilla feature turned on you get this:

`ssssSsssSsssSsssC`
`ssssSsssSsssC`
`ssssSsssC`
`ssssC`
`C`

which is one tabwidth of whitespace removal with each press.

**Comment by donho** [comment]
@alankilborn 
Your `ssssSsssSsssSsssSsssC` made me confused. I guess it should be `sssSsssSsssSsssSsssC`.

**Comment by alankilborn** [comment]
@donho said:

> Your `ssssSsssSsssSsssSsssC` made me confused. I guess it should be `sssSsssSsssSsssSsssC`.

I was trying to illustrate for Python where tabstops are every 4 positions, so column 1, column 5, column 9, etc.

It may be that it is harder to explain than to actually understand the Scintilla feature.

The Community forum has some workaround scripts, but I thought it would be an easy native feature addition.  It's one line of actual code added, plus addition lines for a checkbox preference setting.

**Comment by donho** [comment]
Hmm... it could be a interesting feature. 
But firstly, I would like talk about the naming:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/90293/1b6758a2-170b-47ef-b4df-bf26ae83ee6f)

Shouldn't **Tab Settings** be `Indent Settings` ?

**Comment by alankilborn** [comment]
@donho 

>Shouldn't Tab Settings be Indent Settings ?

Makes sense to me.

But then wouldn't _Tab size_ need to be _Indent size_?

And then maybe _Replace by space_ is more accurate as _Tab key inserts "size" spaces_ with maybe a tooltip that says "When uncheckmarked Tab key inserts one tab character".

---

We could make the newly requested feature language-specific if you'd want to put its setting here, but then the code that does the main action would no longer be a single line.

**Comment by pryrt** [comment]
I think the group section should be named `Indent Settings`: it's not just the `Tab` key, because those settings also affect how auto-indent works.

The radio buttons could be:
```txt
Indent using:
( ) Tab character
( ) Space character(s)
```

or, if you don't like the "header" row:
```txt
( ) Indent using Tab character
( ) Indent using Space character(s)
```

The first seems less redundant to me, but both convey the correct information.

**Comment by molsonkiko** [comment]
@pryrt 
I think I like `Backspace key unindents instead of removing single space` best. Not sure what hover text would be best, but your suggestion in the comment immediately above this one seems fine as a starting point.

I would advise against turning this on by default.

I recognize that if it is off by default, many people will never recognize that it is available, but I'm pretty confident that the initial implementation of this feature will have a variety of weird unintended consequences that will probably annoy more users than it pleases.

I would also note that the implementation should probably set a maximum to the number of characters it backtracks to detect the beginning of the line, so it doesn't waste too much time on files that for whatever reason have a ton of non-newline whitespace all over the place.

**Comment by alankilborn** [comment]
> the implementation should probably set a maximum to the number of characters it backtracks to detect the beginning of the line, so it doesn't waste too much time on files that for whatever reason have a ton of non-newline whitespace all over the place.

The implementation is merely telling Scintilla to turn its feature for this on/off, so I'd say if this has been a problem in the Scintilla world, they would have already dealt with it in their code.

**Comment by alankilborn** [comment]
> I would advise against turning this on by default.

You're probably right about this.

If it's going to be a per-language setting, though, it could be considered to default to on for non-Normal files.

**Comment by donho** [comment]
@pryrt @alankilborn 
Thank you for the suggestions. I use Peter's 1st suggestion partially:
```
Indent using:
( ) TAB
( ) White space
```
for making it more clear and simpler.
Here's PR: #15203

**Comment by donho** [comment]
Regarding the command [SCI_SETBACKSPACEUNINDENTS](https://www.scintilla.org/ScintillaDoc.html#SCI_SETBACKSPACEUNINDENTS)(true/false), should it be per language settings, or a global settings?
What do you guys thinking?

Also, are there other interesting indent features in Scintilla which are not (yet) included in Notepad++ ?

**Comment by alankilborn** [comment]
> Regarding the command [SCI_SETBACKSPACEUNINDENTS](https://www.scintilla.org/ScintillaDoc.html#SCI_SETBACKSPACEUNINDENTS)(true/false), should it be per language settings, or a global settings?

I think it is okay as a global setting.  It could be made per-language in the future if it is what users want, but I doubt there would be much user complaint about it being global.

**Comment by pryrt** [comment]
> should it be per language settings, or a global settings?

I like the idea of it being per-language... And maybe, like the tab-vs-whitespace option, have it list _three_ options: inherit default, backspace unindents, or backspace single-space.

> ```
> Indent using:
> ( ) TAB
> ( ) White space
> ```

Just so you know, the reasons I phrased my original the way I did, rather than using the phrasings you used:
1. `TAB` in all-caps is not actually the official name for the character.  `HT` is the [official abbreviation](https://en.wikipedia.org/wiki/ASCII#Control_code_chart) for the "Horizontal Tab" character (though very few people would know this, which is why I wouldn't recommend using it), and "Tab" is the normal English rendering for the character.  And `TAB` on its own (and to a lesser extent, `Tab` on its own) would imply to a large subset of people that it's the "tab key" should be used for indenting, and they wouldn't realize that what the option is talking about is the _character_ that will be stored in the file, not the _key_.  Thus, I phrased it as `Tab character`, because that's explicit about key-vs-character.
2. `White space` is a generic term meaning _any_ whitespace character, including ASCII 32 space, ASCII 9 HT, VT, CR, LF, NBSP, and a bunch of other less common ones.  Once again, "Space character" makes it very explicit that it's the single ASCII 32 space character, and not any of the other potential whitespace characters; and `Space character(s)` makes it more obvious that a single indentation level might use more than one space character.

If you don't like repeating "character" for both options, maybe this would be more to your liking?
```
Indent uses character(s):
( ) Tab
( ) Space
```

**Comment by alankilborn** [comment]
I'm not sure where `TAB` (that exact thing) comes from with @donho , but obviously it is deeply ingrained.  :-)

Could go with `U+09` for tab-character, and `U+20` for space.  That's absolutely clear -- for those that understand the notation -- but I wouldn't recommend it.  :-)

Maybe:

```
Indent uses:
( ) Tab character
( ) Space character(s)
```

**Comment by alankilborn** [comment]
> are there other interesting indent features in Scintilla which are not (yet) included in Notepad++ ?

I'm sure there are.  We'll let you know as we think/find them!  :-)

**Comment by donho** [comment]
@pryrt 
> Just so you know, the reasons I phrased my original the way I did, rather than using the phrasings you used...

Argument accepted.

@alankilborn 
> I'm not sure where TAB (that exact thing) comes from with @donho , but obviously it is deeply ingrained. :-)

LOL. `TAB` (char) for me is for distinguishing from the `tab` interface which allows users to switch among the different documents in Notepad++. BTW IIRC my old keyboard has a **TAB** on this key.

> Maybe:
```
Indent uses:
( ) Tab character
( ) Space character(s)
```

I find it more suitable finally. The reason of using `Space character(s)` instead of `Space characters` is because users can set the value of "Indent size" to 1, isn't it?

**Comment by pryrt** [comment]
> The reason of using `Space character(s)` instead of `Space characters` is because users can set the value of "Indent size" to 1, isn't it?

Yes.  And because the setting also influences later-in-line Tab-key usage (so `abcd123[TabKey]` would only insert one space for settings of 8, 4, 2, or 1)

**Comment by alankilborn** [comment]
@donho OK, assign to me.

**Comment by alankilborn** [comment]
@donho 

---

Would renaming of internal variables be accepted?  

Example:  `useDefaultTab` --> `useDefaultIndentSettings`, `getTabInfo` --> `getIndentInfo`, and other similar?  It would make review harder, but I think it would be a wise change for the code.

---

Items in `langs.xml` and `config.xml` would NOT be renamed, for backward compatibility reasons.  Example:

`<GUIConfig name="TabSetting" replaceBySpace="yes"...`

would remain as `TabSetting`

**Comment by donho** [comment]
> Example: useDefaultTab --> useDefaultIndentSettings, getTabInfo --> getIndentInfo, and other similar? It would make review harder, but I think it would be a wise change for the code.

Please keep them as they are now.
I will rename them if it's really necessary.

**Comment by alankilborn** [comment]
@donho 

_Indent size:_ looks lonely centered in the groupbox, can it be moved to line up with everything else on the left?:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/827cc5ec-039a-4de5-8ca9-d60900603338)

**Comment by donho** [comment]
@alankilborn 
The right aligned label "Indent size:" translation could be longer, so it's moved at center so the length could be increased toward to the left. OTOH, I tried to separate size zone from radio button zone, so I prefer to keep it at the current position.

**Comment by alankilborn** [comment]
@donho 

Are you in love with the caption of this control?:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/e891c7ba-bada-49b4-b577-52028b1c3dd6)

I think brevity is better:  "Backspace key unindents"

Add tooltip with lengthier text:  "Backspace key will remove trailing space character(s) back to column-multiple of indent size"

**Comment by pryrt** [comment]
> I think brevity is better: "Backspace key unindents".  Add tooltip with lengthier text

I concur (as I [indicated earlier](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15180#issuecomment-2130240235)) ...

> "Backspace key will remove trailing space character(s) back to column-multiple of indent size"

"Trailing" indicates what comes at the end of the string... From how I understand how scintilla does it, this option allows backspace to remove "preceding" or "leading" character(s), not "trailing" character(s).

**Comment by alankilborn** [comment]
@pryrt 

"Trailing" was perhaps a bad choice of word; I have amended my prior suggested tooltip text.

**Comment by alankilborn** [comment]
>Tooltip for me is when the feature is complex and need a lot of explanation...

Unfortunately, in this case, until user is familiar with how it works, it DOES need a lot of explanation...and that explanation, in words, is not succinct and short.

>I prefer remain the original idea...

OK, sticking with the original plan!

**Comment by donho** [comment]
> Unfortunately, in this case, until user is familiar with how it works, it DOES need a lot of explanation...and that explanation, in words, is not succinct and short.

If the users request the explanation in the future, then we can consider adding the tooltip.

**Comment by sXNA** [comment]
Why not just add that it emulates tab character behaviour for indentation

"Backspace key unindents (emulate behaviour of tab characters when using spaces)"
