### ISSUE TITLE
[BUG] Crash happens while "Next Search Result" command is applied on the empty search result.

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#15247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Running "Next Search Result" command on the empty search result leads Notepad++ crash.

### Steps To Reproduce

1.    Open empty document (e.g. New 1)
2.    Open Find dialog (ctrl+f)
3.    Press "Find All in Current Document" button -> Search results with 0 hits
4.    Open menu Search->Next Search Result

### Current Behavior

Notepad++ crashes.

### Expected Behavior

No crash.

### Debug Information

```shell
Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Home (64-bit)
OS Version : 23H2
OS Build : 22631.3672
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by donho** [comment]
More info:

1.    Open stylers.xml
2.    Select WordsStyle and press ctrl+f
3.    Press "Find All in Current Document" button -> Search results with hits for WordsStyle
4.    Now delete 2nd line -> search results is empty except 1st line with Search "WordsStyle" ...
5.    Open menu Search->Next Search Result

And if 1st line is deleted crash won't happen.

**Comment by xomx** [comment]
@donho 
This issue should be reopened, the crash is still there, just one specific case has been fixed.

previous STR1:
- just use the "Previous Search Result" (Shift F4) instead of the "Next Search Result" (F4)

previous STR2:
- this is still crashing even with the F4

STR3 (similar to STR2):
- open some file, e.g. the N++ "change.log"
- use "Find All In Current Document", e.g. I searched for the "Fix" there (9 hits...) and select the output in the "Search results" panel like
  ![npp-F4-crash1](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/2f49116d-6431-4f16-8394-2641db62bcc4)

- erase by pressing the Del-key
  ![npp-F4-crash2](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/862e7d24-302c-4f5a-9d8c-50934875edb8)

- use the F4 or Shift+F4

**Comment by donho** [comment]
@xomx 
Thank you!
It should be OK in #15293 - could you check it?

**Comment by xomx** [comment]
@donho 
Tested, now it is ok.

**Comment by donho** [comment]
Thank you @xomx !
