### ISSUE TITLE
[BUG] Encoding + Conversion Problem

### ISSUE THREAD

**Issue by SupportRainbow** [notepad-plus-plus/notepad-plus-plus#15324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Hello Notepad ++ Community,

So, with the new release of 8.6.8 we're running into problems with changing our Encoding and trying to Convert to a different format. When using version 8.6.8 we have to change the "encode" section of the file to ANSI and convert it to "UTF-8", after running the convert feature it then empties the entire file, no error message happens or anything specific to identify, but when I run this on a version back "8.6.7" I can change it to ANSI and "Convert to UTF-8" just fine, just want to throw this bug out there because currently it seems like the conversion feature has been botched with the recent update.

### Steps To Reproduce

1.  Open any sort of .csv file with Notepad ++
2.  Under "Encoding" change it to "ANSI", and then do "Convert to UTF-8".
3.  After doing the steps in step 2., you will notice that all of the contents of the file disappear, in version 8.6.7 it converts successfully and keeps all of the items within that file there.

### Current Behavior

Everything works fine until you hit the "Convert to UTF-8", once that is ran it empties the contents of the file.

### Expected Behavior

What should happen is after pressing "Convert to UTF-8" it should just convert all of the files content that needs converted and not clearing/emptying the file.

### Debug Information

```shell
Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.4529
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by JamesParrott** [comment]
I've just updated np++ to 3.6.8 and couldn't reproduce this.  Perhaps it doesn't occur in Windows 11 (my OS), only in Windows 10 pro for some reason?  

It sounds like a serious bug though.  Please can you upload an example .csv file encoded in ANSI that notepad++ deletes the contents of?

**Comment by rddim** [comment]
Confirm the bug with v8.6.8

v8.6.8 - `UTF-8` > `Convert to ANSI`
![868-UTF-8_to_ANSI](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/8998791/2c5745c4-7caa-4431-9bf7-4990e1c82dbc)

v8.6.8 - `UTF-8` > `ANSI` > `Convert to UTF-8`
![868-ANSI_to_UTF-8](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/8998791/b2fb4609-25af-407c-849b-0e1e7b512704)

There is no problem with v8.6.7

v8.6.7 - `UTF-8` > `Convert to ANSI`
![867-UTF-8_to_ANSI](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/8998791/9ce18fe4-6015-4b15-ad5f-a6bd610051cc)

v8.6.7 - `UTF-8` > `ANSI` > `Convert to UTF-8`
![867-ANSI_to_UTF-8](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/8998791/f5c4e50a-9c44-47f9-9ef7-b67663c6bfb0)

### Debug Info
```
Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : D:\npp.8.6.8.portable.minimalist.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.3737
Current ANSI codepage : 1251
Plugins : none
```
### Other Info
Later today I will test with Win 10

**Comment by miika-prose** [comment]
I can confirm the bug.

**Comment by JamesParrott** [comment]
Thanks very much both of you.  I must be lucky.  I can't see what's different in my system:
```
Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Home (64-bit)
OS Version : 23H2
OS Build : 22631.3737
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by xomx** [comment]
Cannot reproduce (Win10Pro x64)

But then I tried to use this and after Win restart there is such a difference in between the v8.6.7.& v8.6.8:

![npp-convert-problem](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/0e4f8d9b-b0f7-4904-a336-fee504db192f)

**Comment by SupportRainbow** [comment]
Sorry, had a busy day yesterday and just got back to this forum but, @rddim posted the exact example of what's currently happening, I will go ahead and update back to 8.6.8 and try the windows setting @xomx found and see if that helps fix the issue, I appreciate everyone's response and feedback so far!

**Comment by SupportRainbow** [comment]
Okay, just to update on the issue, I enabled that settings and updated back to version 8.6.8 and tried the encoding conversion, same issue occurred with it emptying the file so, I'm going to revert back to version 8.6.7 for the time being so we can do the conversion successfully but, if anyone has anymore suggestions to try just let me know, if not hopefully the Notepad devs see this issue and fix it in the next update, I appreciate everyone's input and assistance and will check this regularly for a while just in case anyone has updates on this!

**Comment by rddim** [comment]
Confirm the bug with v8.6.8 on Win 10. v8.6.7 work as expected. There is no difference with the settings provided by @xomx - the text is gone in v8.6.8. Tomorrow I will check Win 11 with enable/disable this option.

### Debug Info
```
Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : D:\npp.8.6.8.portable.minimalist.x64\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Enterprise LTSC 2019 (64-bit)
OS Version : 1809
OS Build : 17763.316
Current ANSI codepage : 1251
Plugins : none
```

**Comment by xomx** [comment]
> try the windows setting @xomx found and see if that helps fix the issue

There is a misunderstanding - by that setting in Windows, I wanted to say that only with this setting I do see such a problematic difference in between the v8.6.7 & v8.6.8 on my PC.

I see other similar report - #15271 , so maybe there really is a problem in the latest v8.6.7.

**Comment by xomx** [comment]
Now it has started to be weird - I was once able to reproduce this issue by using the file "SQLsharp_SETUP.sql" mentioned in that #15271 (I opened it, was detected as the ANSI, then converted to UTF8 and boom -> empty N++ filebuffer). Then I closed my testing N++ (fresh portable v8.6.8), relaunched it and tried that once more - but this time to no avail... Now I cannot reproduce it anymore.

**Comment by chcg** [comment]
Most likely this issue is caused by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/b4b76ff7706b12237aba1a2cf1723c3c45ac6c2b#diff-479ffaff15f2bc1cb40f8287eceaa812676c89a320080fd04bea89b2f3a923d4 . I can't reproduce the issue with the default encoding but after switching on the beta feature of UTF8 support (https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window) I can also reproduce it.

**Comment by xomx** [comment]
@chcg 
I have already know what caused that and now I can reproduce it consistently.

**Comment by srutzky** [comment]
I don't believe this is related to setting the Windows ANSI code page to UTF-8 / 65001 as I'm not using that and was just able to reproduce this, although only temporarily (mirroring what @xmox was observing). As I just noted over in the related issue #15271 , while I was initially unable to reproduce the problem, something changed and I was (temporarily) able to reproduce this issue. I don't think I changed anything. AND, I've been able to reproduce the issue on _any_ ANSI file, including the `SQLsharp_SETUP.sql` file and even the `C:\Program Files\Notepad++\change.log` file. This is definitely not specific to the SQL# setup script, and as a result of that, the issue is also not due to the invalid UTF-8 byte sequence of the `A9` byte by itself, nor due to "current ANSI codepage" (as this seems to be happening across several of those).

I'm now thinking this has something to do with some internal state of Notepad++ given that I was for a while able to reproduce this behavior with the `C:\Program Files\Notepad++\change.log` file (in fact, I was not able to _not_ get this behavior), but I did something and now I can no longer reproduce the issue, on either the `SQLsharp_SETUP.sql` file or the `C:\Program Files\Notepad++\change.log` file. I have not closed / re-opened Notepad++, but I do have many tabs open and made an edit in one of them (which I have tried before in this testing and it hasn't seemed to have had any effect), and maybe changed to various tabs. Hmmm, I think I will need to check what encodings I am using in those other tabs.

Essentially, I was originally not able to reproduce this on any file, then I was able to reproduce it on all files, and now I'm back to not being able to reproduce it on any file.

**Comment by xomx** [comment]
@donho 
I can confirm that there is this serious regression in v8.6.8 and I will fix it later (there are also other problems in this part of code).

It is really caused by the #15195, as @chcg thought. The code enhancement "Nullpointer checks" enhanced safety of this part of code but unfortunately also created a hole in the correct handling of the clipboard:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/6b441b738a951ed225632f4085a46c95cd4aa13f/PowerEditor/src/NppCommands.cpp#L3125-L3141

Now it is possible there that the OpenClipboard succeeds but has no obligatory CloseClipboard paired as the GetClipboardData(CF_TEXT) can fail (when there is no CF_TEXT data in the Clipboard) and then its appropriate CloseClipboard will not be called...

To reproduce - simply empty the Windows Clipboard 1st:

![npp-clipboard-clear](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/18a469b3-efdf-41fa-991c-bcbe746d9863)

then follow the user STR above.

One can also check that condition by the N++ Clipboard History panel (if something is visible in this panel, the problem will not occur):
 
![npp-clipboard-clear2](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/6ec4e596-0135-47aa-a928-1262f07abd4c)

![npp-clipboard-clear3](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/fcc7350d-f556-442a-96fe-a4a03d0481d6)

**Comment by chcg** [comment]
@xomx So it just started to appear in my case because of the windows restart which is needed to activate the UTF8 feature and it was just "luck" that the same PR caused the problem as I guessed the Utf8_16 class modifications are causing the trouble.

**Comment by chcg** [comment]
@xomx It seems to be sufficient to move https://github.com/notepad-plus-plus/notepad-plus-plus/blob/6b441b738a951ed225632f4085a46c95cd4aa13f/PowerEditor/src/NppCommands.cpp#L3140 down out of the if clause to fix this issue. Could you confirm?

**Comment by xomx** [comment]
@chcg 
> So it just started to appear in my case because of the windows restart which is needed to activate the UTF8 feature 

Yes, that was exactly also my case in my 1st post here.

> and it was just "luck" that the same PR caused the problem as I guessed the Utf8_16 class modifications are causing the trouble.

At the time you posted your 1st comment here I have already solved this problem, so it was not misleading for me :-)

**Comment by xomx** [comment]
@rdipardo 
> in other words, we are pasting from an empty clipboard:

No, the problem is that the N++ code unintentionally block the access to the Clipboard for the following Scintilla calls, so here it then has to return false, because the OpenClipboard there cannot succeed:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/6b441b738a951ed225632f4085a46c95cd4aa13f/scintilla/win32/ScintillaWin.cxx#L2798-L2808

**Comment by chcg** [comment]
For some calls to `::OpenClipboard()`, see  https://github.com/search?q=repo%3Anotepad-plus-plus%2Fnotepad-plus-plus+OpenClipboard&type=code the check of the return value is missing. Probably that should be also fixed.

**Comment by donho** [comment]
@xomx 

Thank you for the investigation!



@chcg 
> It seems to be sufficient to move... 

The line of `::CloseClipboard(); ` ?

I didn't try, but this line was there before the regression.

I just restore the concerning code before the modification: #15333, and it fix the problem.

**Comment by donho** [comment]
> move it down out of the if clause to fix this issue.

OK. Try it and test OK. I just close #15333 which restored the old code. Please create a PR for it @xomx ?

**Comment by donho** [comment]
@chcg 
> For some calls to `::OpenClipboard()`, see https://github.com/search?q=repo%3Anotepad-plus-plus%2Fnotepad-plus-plus+OpenClipboard&type=code the check of the return value is missing. Probably that should be also fixed.

Yes, It should be done as well.

**Comment by xomx** [comment]
@donho 

> I will fix it later (there are also other problems in this part of code).

> > For some calls to `::OpenClipboard()`, see https://github.com/search?q=repo%3Anotepad-plus-plus%2Fnotepad-plus-plus+OpenClipboard&type=code the check of the return value is missing. Probably that should be also fixed.
> 
> Yes, It should be done as well.

Yes, @chcg nailed down the main problem. I see this incorrect N++ OpenClipbord handling as a potential culprit e.g. for the long standing occasional problem with the N++ undo as is seen in the issue 9426 (I intentionally omitted the # as I have no proof yet - my idea is that a N++ paste-op can somehow be influenced by a previous invalid clipboard manipulation, leading to some Scintilla malfunction, as seen in this regression case...).

> Please create a PR for it @xomx ?

Will do.

First I will fix this specific code part only, to fix the regression. There is also (now) invalid variable casting, probably from the pre v8.3 era.

Then I will look for all the places with the OpenClipboard and correct the naive design without the return value checking.

Personally, I am also for OpenClipbord substitution in the N++ code with a variant of the Scintilla OpenClipboardRetry shown above. OpenClipboard WINAPI handles a global Windows resource, so it can/will fail sometimes because of there are also other apps running and using the Windows Clipboard. You can easily test that situation - just debug N++ and break after a N++ successful OpenClipboard call, then test the standard text Ctrl+C/Ctrl+V functionality in other running apps... (it will not work).

**Comment by SupportRainbow** [comment]
@xomx  Hey Xomx,

Sorry I haven't replied about this until just now, I see you fixed the issue which is great but, I'm not the best with Notepad ++ and just submitted this for my DP team but, how exactly do I go about applying this fix to the problem machines running into this issue, any help would be greatly appreciated and great job and founding out the issue, that's some magic!

**Comment by xomx** [comment]
@SupportRainbow 
The simplest answer - wait for the next N++ release (~2 weeks, RC has been already [announced](https://community.notepad-plus-plus.org/post/95533)).

At this stage the PR #15346  fixing this issue is not yet fully completed (accepted), details need to be fine-tuned and tested. But if you want to test the fixed notepad++.exe binary builds right now, you can follow e.g. these steps: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/15316#issuecomment-2175775856

**Comment by SupportRainbow** [comment]
@xomx 
Okay I can wait and I'll inform them, like I've preached I really appreciate your work as well as @donho, you guys are some Notepad wizards, thanks once again!
