### ISSUE TITLE
[BUG] App-V Deployment Context Menu Issue

### ISSUE THREAD

**Issue by ntmmfts** [notepad-plus-plus/notepad-plus-plus#15354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

My organization deploys Notepad++ with App-V that results in a right-click context menu named "Notepad++ Context menu" which does not work.  I'm aware of the change on how the shortcut is created since version 8.5.7, so I'm asking that the creation method be restored to work like before, or to redesign it to work when deployed with App-V.  The following article describes the problem and offers workarounds, but my organization wants the problem fixed in the application instead of the effort required for a workaround.  [https://techcommunity.microsoft.com/t5/msix/notepad-8-5-7-and-quot-explorercommandhandler-quot-used-to/m-p/3929171](url)

### Steps To Reproduce

1. Deploy Notepad++ version 8.5.7 or higher with App-V.

### Current Behavior

Non-working right-click context menu item as described in the description section.

### Expected Behavior

Functional right-click context menu shortcut.

### Debug Information

```shell
N/A
```

**Comment by xomx** [comment]
@ntmmfts 
This issue rather belongs here: https://github.com/notepad-plus-plus/nppShell/issues
If you could, please recreate it there.   (FYI @GurliGebis )

I will not further comment about this specific issue but after reading your info [link](https://techcommunity.microsoft.com/t5/msix/notepad-8-5-7-and-quot-explorercommandhandler-quot-used-to/m-p/3929171) and the included link [there](https://www.tmurgent.com/TmBlog/?p=3643), I have a common note - I cannot help myself but wonder that someone (devs there) apparently knowledgeable and experienced in this shell-extension area are complaining only about the changes (forced on the N++ by the Windows 11's not so much sensical shell extension requirement changes) and rather are creating their own modified workarounds/patches instead of helping with the possible fixes directly at the N++ source (?). The N++ is open sourced folks, so why not help fixing it directly at its source and just not wasting energy in complaining or writing a whole blog about it!

This is IMO one of the "dark sides" of the open source apps development - many have requirements on them, but few actually contribute something.

**Comment by ntmmfts** [comment]
Thank you.  I recreated the issue under nppShell/Issues as requested.
