### ISSUE TITLE
Search window does not appear

### ISSUE THREAD

**Issue by DannyN358** [notepad-plus-plus/notepad-plus-plus#15357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When I do a search the search window does not appear. I have also tried F7 and it doesn't appear.

### Steps To Reproduce

1.  Find
2.  enter text to find
3.  select "find all in current document" (but I get the same result no matter what I pick)

### Current Behavior

It appears to go through a search

### Expected Behavior

I expect the search results to pop up in either an embedded window or a separate window.

### Debug Information

```shell
Notepad++ v8.6.5   (64-bit)
Build time : Mar 29 2024 - 17:04:43
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Enterprise (64-bit
OS Version : 22H2
OS Build : 19045.4529
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by xomx** [comment]
Probably #13084 .
If so, the fix will be in the upcoming N++ version (v8.6.9).

If you do not want to wait and fix this right now, you can:
- either try to replace your notepad++.exe with the patched binary from the GitHub [Actions](https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/9425320105) build (for the commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/8beda66cb8c77361216a43075e9be44ca32edbec )
- or try to follow this guide: https://community.notepad-plus-plus.org/topic/24876/faq-i-cannot-find-my-panel

**Comment by DannyN358** [comment]
I do have multiple screens but I can't find it on any of the screens.

Danny New
[AirBorn Logo]
802.318.8747
***@***.******@***.***>
www.airborn.com<https://www.airborn.com/>

**Comment by DannyN358** [comment]
Thank you. Editing the config.xml worked.

Danny New
[AirBorn Logo]
802.318.8747
***@***.******@***.***>
www.airborn.com<https://www.airborn.com/>

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/8beda66cb8c77361216a43075e9be44ca32edbec

**Comment by DarkNami** [comment]
I have 3 monitors.
Since version v8.6.9, If I moved "Search results window" to other monitor (not same monitor with Notepad++ window),
when I restart Notepad++, the "Search results window" will be moved to Notepad++ monitor, position and size changed.

Schematic:
![Schematic](https://github.com/user-attachments/assets/f1e80de8-6334-40d4-bec6-210623ce5fec)

**Comment by ArkadiuszMichalski** [comment]
@DarkNami  It would be best if you opened a new issue and described the problem.

**Comment by xomx** [comment]
@DarkNamiIt is most probably due to my "Lost panels" patch in v8.6.9. I will be one more week computer-free and then I will look into it.Dne 29. 7. 2024 14:01 napsal uživatel Dragon ***@***.***>:
I have 3 monitors.
Since version v8.6.9, If I moved "Search results window" to other monitor (not same monitor with Notepad++ window),
when I restart Notepad++, the "Search results window" will be moved to Notepad++ monitor, position and size changed.

**Comment by DarkNami** [comment]
@xomx 
Thank you for your help. You can process this issue when you have time. It's not an urgent issue.
