### ISSUE TITLE
Request: recent sessions list

### ISSUE THREAD

**Issue by pgibe** [notepad-plus-plus/notepad-plus-plus#1550]
Saving the workspace as a session is a very useful feature.
Also useful could be the capability to have in file menu a submenu with a list of the recent sessions, for a quick pick. Could be implemented? Thank you in advance!

**Comment by anorhoads** [comment]
Yes indeed sessions needs help!

I will have a half-dozen Notepad++ sessions open -or more- each for a different subject/project.  I like the UI and how the mouse & keyboard shortcuts are working.

The problem is that over time, as a project spreads, I won't remember where the folder is that I created the .NP++ session file and the is no save (current) session as each save opens a Save As dialog rather than giving the options to save and save as.

Having a list of open sessions to jump to the appropriate window would be great (yep, i use Alt+Tab but that can be a long list and the paths are long so not much help identifying the right session).

Opening another session while in a session might give the option to open in a new Notepad++ window or to merge the sessions or make a new session consisting of both sessions.

I would be great if the session name should be in the Title bar - preferably before the current file name.

I would be great if the session name would be what you would see in the Alt+Tab list (if using a session otherwise the filename is working well).

Sometimes it can be a mystery as to the name and location of the original session file name (.NP++) so making it clear which session an instance of Notepad++ is using would be so very helpful.

I can't make these changes myself but I can contribute $$ if that would get this done!

I write thousands of small .txt files, hundreds of PowerShell scripts, SQL querys, some Perl, some batch/command, even UNIX shell scripts (many flavors) and I really get a log of benefits from Notepad++ so I appreciate all that it does.  I hope to be adding C# soon.

Could it perhaps add the ability to open powershell.exe, cmd.exe, ssh (using Putty which would really be cmd.exe), and RDP sessions (could also be cmd.exe sessions)?   Some folks may still be able to use telnet.  This is perhaps over-the-top but as Notepad++ is already multi-tab perhaps there is a way?

**Comment by MAPJe71** [comment]
Try the `Session Manager`-plugin.

**Comment by pgibe** [comment]
I was used to save the sessions as xml in a well-known path, but the Session Manager plugin seems very interesting: thank you for the hint!
