### ISSUE TITLE
Pasteboard

### ISSUE THREAD

**Issue by stavpup** [notepad-plus-plus/notepad-plus-plus#15530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

capture Clipboard text

### Describe the solution you'd like.

Lets you automatically capture into a document any text that is copied to the Clipboard. This is very useful wrhen copying alot of text from different sources.

### Debug Information

```shell
Notepad++ v8.6.9 - 支持台灣獨立
```

**Comment by stavpup** [comment]
It is a feature request

**Comment by pryrt** [comment]
The **Edit > Clipboard History** gives you _almost_ what you want.  While Notepad++ is running with the Clipboard History panel, it is capturing every time text is added to the Windows Clipboard.

But in order to get it into a file, you would have to double-click on each entry in the Clipboard History to paste it into the current document.  So, if it's really a lot of separate Clipboard entries, it might still take some effort on your part to get them all into the same file in Notepad++ (having to double-click each entry).  

To make my amendment to your feature request, I would think it would be nice if Clipboard History had a "paste all" button, which immediately pasted all the entries (in original chronological order) into the active document.

**Comment by alankilborn** [comment]
> To make my amendment to your feature request, I would think it would be nice if Clipboard History had a "paste all" button

Or... if you could multi-select certain entries (or all, via Ctrl+a?) and then right-click and a popup menu would appear and have a "Insert" (into current doc) menu choice...

**Comment by stavpup** [comment]
Also, add an empty line between pastes, because now if you double click, you can continuous text

**Comment by alankilborn** [comment]
Shouldn't this be "closed as not-planned" rather than "completed"?
