### ISSUE TITLE
[Feature request] Option to disable horizontal scrolling when clicking line in search results

### ISSUE THREAD

**Issue by Shassk** [notepad-plus-plus/notepad-plus-plus#15575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When searching in a large file some lines with words you search can be short, some may be long with searchable content close to the end.
And when clicking a long line now it scrolls it to the right to the place search word is at. Meanwhile shorter found lines above/below become not visible entirely, and you have to manually scroll back to the left every time.

Example: 
1. Open `PowerEditor\installer\nativeLang\english.xml`
2. Search for `Notepad` (no quotes)
3. Click line 1426
4. See half of the lines disappear (too short):

![ex](https://github.com/user-attachments/assets/48a7aac8-6f7a-4bdb-85a1-013c9e626c0e)

### Describe the solution you'd like.

A toggle in settings to prevent scrolling (i,e. make it behave the way it was at least in 7.8.6).

Or if that's not happening - at least would like to know where in sources this is done so I can recompile for myself.

### Debug Information

```shell
Notepad++ v8.6.6   (32-bit)
Build time : May  6 2024 - 21:55:48
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "C:\Users\Monty\Desktop\notepad-plus-plus-b32c07f7469362adfc90fe71bbb28b8b26ef65f1\PowerEditor\installer\nativeLang\english.xml"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Home (64-bit)
OS Version : 23H2
OS Build : 22631.4037
Current ANSI codepage : 1251
Plugins : 
    ComparePlus (1.2)
    NppConverter (4.6)
```

**Comment by alankilborn** [comment]
>...you have to manually scroll back to the left every time.

Or press the Home key.

**Comment by Shassk** [comment]
> Or press the Home key

Plz find it because I can't see it:

![Снимок экрана (4)](https://github.com/user-attachments/assets/ee875bb1-40ae-406a-bc0a-95588aa5696b)

**Comment by alankilborn** [comment]
>Plz find it because I can't see it

Suggestion: Use a standard keyboard?

**Comment by Shassk** [comment]
> > Plz find it because I can't see it
> 
> Suggestion: Use a standard keyboard?

I'm curious whether you understand the point of a *portable* device is in being portable, not in carrying a separate keyboard around.

Gotta love when asking for help getting X the immediate reply is "you don't need X".

Can ***I*** decide what ***I*** need pretty please?

I'm just asking for help figuring out where this happens in code so I can do it for myself if nobody else is interested in adding this to release functionality.

**Comment by Shassk** [comment]
> The suggestion for using a standard keyboard was because Notepad++ can't always solve everyone's every problem

True, and that's why I've said I'm ready to do it myself if necessary.
Because some things I already have to change this way.
For example making MRU again affect only Ctrl+Tab order, but not closing tab order - because when bulk opening, searching something (which migh be found in 3 files out of 50, so you're not visiting all of them) and closing files becomes a nightmare. And many people did want the change, even tho I'd put 2 separate toggles instead of one for both settings.

>especially when there is (IMO) a fairly reasonable solution for people using "standard" stuff, e.g. in this case the Home key.

One big reason why it's not very good even with Home key available: whrn double clicking line - focus shifts to main editor windows away from search results. So not only you need Home key, but first you have to click back into search results window.

> I'm just learning about this being a portable device scenario.

Ok, sorry for that.
FYI on-screen keyboards are used on touch-capable devices which are mostly 2-in-1s and tablets. And not even all 2-in-1s and laptops have Home key as a standalone key (i.e. accessible directly, not via Fn+...) or even have it at all, especially smaller ones with 11"-13" screen sizes.

>No one said that. But unless it is a need that more than one user has, it is unlikely to be changed by the Notepad++ author (this statement based on historical observation).
>Also, has somewhat of a disdain for adding additional preference settings (this statement based on historical observation).

Fair enough ig.
Does it affect pull requests with changes other users did or only author's own work?
Also does this mean just posting a question instead of a request would've given me a different reply? Thanks, I will take note.

>So if this problem could be solved _without_ that, it would have more appeal.

Ah so you've in fact tried to prevent this situation instead?
Sorry once again.
 
>My guess: See the calls to `SCI_SCROLLRANGE` in `FindReplaceDlg.cpp`. Since there are a few ways it can happen, e.g. mouse double click, or Enter press with input focus in `Search Results` window, or F4 press with input focus in editor window or `Search Results`...

Thanks, I will test it.

Also will ask again just in case: do you perhaps know when it was added? I couldn't find anything in the patchnotes for 7.x-8.x versions file. This would make things easier. Worst case scenarion I'll start installing versions one by one in a VM, but still.

**Comment by alankilborn** [comment]
>Does it affect pull requests with changes other users did or only author's own work?

I'm not sure what you're asking here.  If on the chance you are asking if contributors are allowed to add pref settings, and that the author doesn't like to for the features he works on, the answer is No.  And this makes sense: If he doesn't like additional settings, he doesn't like them globally, and isn't going to entertain adding them in to the release codebase.  A rough quote from him: "too many options is not an option".  This isn't to say that settings/options are never added, for sure, it's just that it has to be a really strong need that appeals to many users before it is allowed.  Often an issue comes up, and instead of taking action, the author will say, again roughly, "let's backburner this until we see if more users need it".

---

>does this mean just posting a question instead of a request would've given me a different reply?

No, but (opening an issue to ask) questions are frowned upon here and belong [HERE](https://community.notepad-plus-plus.org) instead -- that site is accessible from your Notepad++ help menu, BTW.

---

>so you've in fact tried to prevent this situation?

No, not me, and I don't know of any others that have tried.
I do understand your need, though, I just haven't experienced such a need myself.
There's all kinds of text data out there, and thus all kinds of needs for processing it -- obviously one tool can't do everything ideally for all situations.

---

>do you perhaps know when it was added? 

I asked github to show me the "blame" view on one of the SCI_SCROLLRANGE lines that are relevant.
Gulp.  It appears that _I_ fixed what was considered a bug.  Obviously what some consider a feature (you), some others considered a bug.  :-)
See https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5c10f58212ed1f2efbfa2e8daa812961b6b26e1f
Github tells me that v8.5 of N++ would be the first to have this change in it.
