### ISSUE TITLE
[Feature request] Disabling the "Move to Start" & "Move to End" functions

### ISSUE THREAD

**Issue by cheonmux** [notepad-plus-plus/notepad-plus-plus#15610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Hello. I have many (1,000+) files open in Notepad++ and frequently use the "Move to Other View" feature to compare two codes.

However, with the introduction of the "Move to Start" & "Move to End" functions, they have replaced the original position of the "Move to Other View" option.

As I'm accustomed to the previous location, I often accidentally select "Move to Start". When many files are open, this can take a considerable amount of time to complete.

I would appreciate if there was an option to disable or hide these new functions.

Thank you.

### Describe the solution you'd like.

Option to hide 'Move to Start' and 'Move to End' context menu items

### Debug Information

```shell
none
```

**Comment by alankilborn** [comment]
> the "Move to Start" & "Move to End" functions, they have replaced the original position of the "Move to Other View" option.

You must be meaning the tab right-click context menu's _Move Document_ area, because that seems to be the only place in the UI where _Move to Start_ and _Move to Other View_ appear together.  Note that these commands also appear via the _View_ main menu item, but there one is in the _Tab_ submenu and the other is in the _Move/Clone Current Document_ submenu.

---

>frequently use the "Move to Other View"

If you use it often, shouldn't you assign a keycombo to it for faster access?  Then hiding things becomes moot.

---

>Describe the solution you'd like.  Option to hide 'Move to Start' and 'Move to End' context menu items

The solution already exists.  You just need to make a custom tab right-click context menu that removes (or changes the order of) some menu commands.  Details for doing so are found in the Notepad++ user manual [HERE](https://npp-user-manual.org/docs/config-files/#the-context-menu-tabcontextmenuxml).

---

This issue may be closed.
