### ISSUE TITLE
Flush or sync on file write

### ISSUE THREAD

**Issue by dhalbert** [notepad-plus-plus/notepad-plus-plus#15614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

I believe it is the case Notepad++ currently does not do a flush or sync or equivalent when the user saves a file. So it is not necessarily that the file contents have been written immediately to the drive. In the past I looked through the source code and could not find such code.

I am a CircuitPython core developer. CircuitPython (a friendly fork of MicroPython) runs on microcontroller boards and presents a USB MSC FAT disk drive (CIRCUITPY) to the host computer.

We often have users who would like to use Notepad++ to edit files on the CIRCUITPY drive. However, if the user unplugs the board or resets the board too soon, then any incomplete writes will be lost, and CIRCUITPY might even become corrupted. In addition, when the user edits and writes a file, CircuitPython automatically restarts and re-runs the primary code file (code.py) to incorporate any changes the user has made. If writes are delayed, this feature is not as useful.

We recommend using editors that do perform a flush or sync on file write: https://learn.adafruit.com/welcome-to-circuitpython/recommended-editors describes the issue, and lists recommended and not-recommended editors. We've had to put Notepad++ on our "not recommended list", but would like to make it a recommended editor, since it is so popular.

### Describe the solution you'd like.

Do a flush or sync or the equivalent when the user saves a file. If this might be problematic or non-performant (e.g. due to some auto-save mechanism) as the default, then provide a Preferences option to enable such an option.

### Debug Information

```shell
n/a
```

### Anything else?

A related issue is whether Notepad++ uses the current drive for auto-save information, etc. That might be redirected to a different drive to minimize writes to the CIRCUITPY drive.

This situation used to be worse in the past, because Windows delayed writes to FAT12 drives for far longer than larger drives (FAT16 and up). We have been told that this was fixed in Windows 10 a few years ago. Background: https://github.com/adafruit/circuitpython/issues/111

**Comment by xomx** [comment]
> I believe it is the case Notepad++ currently does not do a flush or sync or equivalent when the user saves a file. So it is not necessarily that the file contents have been written immediately to the drive. In the past I looked through the source code and could not find such code.

Wrong, N++ uses the MS [FlushFileBuffers](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-flushfilebuffers) WINAPI and from the v8.6.5+ even reports to the users if that call fails ([e.g.](14990)):
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/6cbebedb1e87d01165f677fb8c39edff51fb4fa8/PowerEditor/src/MISC/Common/FileInterface.cpp#L101

This is a necessity these days due to possible user unexpected Windows Update restarts.

Unexpected power outages can also occur, and in the past users of N++ have reported their file data being overwritten with NUL bytes because of that (those reports are rare these days with the `FlushFileBuffers` used and usually have nothing to do with the N++ at all).



> A related issue is whether Notepad++ uses the current drive for auto-save information, etc. That might be redirected to a different drive to minimize writes to the CIRCUITPY drive.

Redirect or switch of completely:
![npp-Pref-Backup](https://github.com/user-attachments/assets/aa565335-f8e8-4544-a83a-a2aea7eabebd)

Here are summarized all the N++ options relevant for your needs:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4696#issuecomment-736083686

**Comment by dhalbert** [comment]
I apologize for the false report. I had looked at the code in detail, but it was several years ago. We'll report Notepad++ as fine in this regard, and also note that the backup path can be changed. Thank you.
