### ISSUE TITLE
[Feature request] Please de-emphasize Global Override in the style list

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#15640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

There is a long history of people not understanding the right way to change the normal text font, which is inherited by all the languages.

Because the Style Configurator places **Global override** before **Default Style**, then people assume that's the "right" place to change the font.  But really, the **Default Style** should be the primary location for making that change (because people don't always understand what the true consequences of **Global override** really are).

![image](https://github.com/user-attachments/assets/7589fb60-3890-4480-955c-f6ae61b8c6d0)

Examples of Global Override being used when Default Style would have been more appropriate
- https://community.notepad-plus-plus.org/topic/26132/changing-the-font/
- https://community.notepad-plus-plus.org/topic/25701/font-size-on-popup-window-please
- https://community.notepad-plus-plus.org/topic/25224/failed-to-display-text-using-simultaneously-combined-chinese-fonts-characters-correctley/4
- https://community.notepad-plus-plus.org/topic/24571/change-tab-font-size-and-document-font-color/3
- https://community.notepad-plus-plus.org/topic/23768/default-font-for-utf-8
- https://community.notepad-plus-plus.org/topic/23590/good-old-highlighting-issue-topic/5
- https://community.notepad-plus-plus.org/topic/23496/background-colors-since-8-4-5-upgrade-of-notepad
- https://community.notepad-plus-plus.org/topic/23420/japanese-font-not-displaying-in-notepad
- https://community.notepad-plus-plus.org/topic/22443/persian-farsi-font-has-different-style-in-np-and-ms-np
- https://community.notepad-plus-plus.org/topic/21451/styles-keyword-highlighting-stopped-working/3
- https://community.notepad-plus-plus.org/topic/21009/underline-a-single-word/3
- https://community.notepad-plus-plus.org/topic/20128/help-selected-lines-are-blacked-out-how-to-fix
- https://github.com/tonsky/FiraCode/wiki/Notepad-Plus-Plus-instructions

These are just examples going back to 2020... I didn't dig any further back; and I didn't include ones in the list where I diagnosed the problem as someone had set the Global Override instead of Default Style, but they never came back and replied to let us know whether it was the cause of their problem; there were about as many of those as the list above.  The last was an external link I happened to run across while researching something else, where a font developer gave their "official" recommendation as to how to use their font in Notepad++, thus showing that the misunderstanding is pervasive across the internet, not just people having problems once they do set a Global Override and come asking for help.

### Describe the solution you'd like.

There are at least ways that I can think of to improve this: implementing one or both of these would be quite helpful:
1. Deprioritize **Global override** in the **Global Styles**'s list of style choices -- put **Default Style** first, and either put **Global Override** second, or (even better) put it at the very end of the list, so that users have to go looking for it.
2. Make it obvious in the **Global override** panel that overriding is an "option of last resort" and that most of the time, what a user really wants is to set the **Default Style**.
    - Suggested statement: `Enabling global override here will override that parameter in all language styles.  What you probably really want is to use the "Default Style" settings instead`
        - maybe put that text as a label with a description -- though it takes up a lot of space
            ![image](https://github.com/user-attachments/assets/35de7c76-781d-49c7-afd5-87d1ba8739c7)
        - maybe put one of your [?] buttons in that dialog, and have that pop up the text instead
    - include a link on the `"Default Style"` text to the **Default Style** page

### Debug Information

```shell
n/a
```

**Comment by Coises** [comment]
What practical functional loss, if any, would there be if the following were done?

* Remove **Global override** as a selection in the **Styles** list.
* Add the checkboxes from **Global override** to the bottom of the **Default style** box, changing them from “enable global” to “force for all styles”; for example, make a box at the bottom labeled **Force default style setting for all styles** and put checkboxes **Foreground color**, **Background color**, **Font name**, etc. in that box.

Would this fix the problem this request is meant to address? I think it would, and I think it would be a less confusing paradigm than the separate “Global override,” since “Default style” properties also propagate to other styles — the difference being only whether they are “forced” even when the style has a different value set.

The only thing I can see that would be lost in doing it this way would be the ability to toggle global override for a particular property on and off while having the default style for the property revert to something other than the global override value of the property when you toggle it off. Is that something anyone uses in practice?

**Comment by Xeverous** [comment]
This change is a regression for me, with technically possible but practically unusable workaround.

I used global override since I started using Notepad++ and now I can no longer well, override the theme.

I understand the motivation behind the change - it is merging 2 very similar functionalities into 1, which simplifies the program.
But there is a catch - global override actually did override. `Global Styles: Default Style` only changes the default styles of a theme, and **multiple themes have specific settings for each syntax element in each language that causes "default style" to be ignored** in many cases.

For example, the Vibrant Ink theme has font size specified for some elements (e.g. COMMENT in C, C++ and CMake) with hardcoded value of 8. If I change default style font size, it is still being overridden by the theme for certain language elements like comments. This ends up with a situation where subsequent lines of code can have different size and/or style.

<img width="752" height="432" alt="Image" src="https://github.com/user-attachments/assets/1747e74e-6873-4528-ad67-e7c4ad6346eb" />

<img width="385" height="112" alt="Image" src="https://github.com/user-attachments/assets/89774d40-370f-427f-b0a3-74eb003a3142" />

**So in short, `Global Styles: Default Style` does not work like (now removed) global override. It only changes the default, which is ignored in many themes for many syntax elements in many languages**. This also breaks ctrl+scroll font size changing (themes still keep overriding the size).

The workaround:
At least the font name and font size have a "null" value in its drop-down list which causes them to inherit default style. But bold/italic etc. do not implement this concept which means that If I want to have a bold font (some fonts look better if always on bold) I have to tick the "bold" checkbox for every element in every language.

Please return the feature of global override (can be in a different place). I don't want to have to tick checkbox for X styles in N languages to have a bold font. It was a really nice feature to conveniently fix font/font size/background/bold regardless of theme. Now it's gone.

**Comment by Xeverous** [comment]
Update: sorry, I missed, the "Global Override" option is still there, just way down the list in `Global Styles -> Style`.

**So my previous comment is pretty much irrelevant now.**

However - why do certain themes have hardcoded font size for some elements (like on the screen I attached)? Is this intentional?

**Comment by pryrt** [comment]
> **So my previous comment is pretty much irrelevant now.**

Glad you figured that out.

> However - why do certain themes have hardcoded font size for some elements (like on the screen I attached)? Is this intentional?

It was likely unnoticed, because eons ago, when most of the themes were made, the default stylers had a few hard coded sizes, and those just got replicated.  Feel free to create issues and PR for any themes you think need fixing.

**Comment by Xeverous** [comment]
I wanted to remove font sizes from the themes but now I see 441b32c fixed it already.

But after grepping all theme files for non-empty font size, I found a small inconsistency:
```
Bespin.xml:1045:        <WidgetStyle name="Default Style" styleID="32" fgColor="BDAE9D" bgColor="2A211C" fontName="DejaVu Sans Mono" fontStyle="0" fontSize="10" />
Bespin.xml:1056:        <WidgetStyle name="Line number margin" styleID="33" fgColor="E5C138" bgColor="4C4A41" fontName="" fontStyle="0" fontSize="8" />
Bespin.xml:1097:        <WidgetStyle name="Global override" styleID="0" fgColor="BDAE9D" bgColor="2A211C" fontName="DejaVu Sans Mono" fontStyle="0" fontSize="10" />
Black board.xml:1035:        <WidgetStyle name="Default Style" styleID="32" fgColor="F8F8F8" bgColor="0C1021" fontName="DejaVu Sans Mono" fontStyle="0" fontSize="10" />
Black board.xml:1046:        <WidgetStyle name="Line number margin" styleID="33" fgColor="EEEEEC" bgColor="2E3436" fontName="" fontStyle="0" fontSize="8" />
Black board.xml:1087:        <WidgetStyle name="Global override" styleID="0" fgColor="F8F8F8" bgColor="0C1021" fontName="DejaVu Sans Mono" fontStyle="0" fontSize="10" />
Choco.xml:1035:        <WidgetStyle name="Default Style" styleID="32" fgColor="C3BE98" bgColor="1A0F0B" fontName="DejaVu Sans Mono" fontStyle="0" fontSize="10" />
Choco.xml:1046:        <WidgetStyle name="Line number margin" styleID="33" fgColor="EEEEEC" bgColor="2E3436" fontName="" fontStyle="0" fontSize="8" />
Choco.xml:1087:        <WidgetStyle name="Global override" styleID="0" fgColor="C3BE98" bgColor="1A0F0B" fontName="DejaVu Sans Mono" fontStyle="0" fontSize="10" />
DansLeRuSH-Dark.xml:1154:        <WidgetStyle name="Default Style" styleID="32" fgColor="C7C7C7" bgColor="2E2E2E" fontName="Source Code Pro" fontStyle="0" fontSize="10" />
DansLeRuSH-Dark.xml:1165:        <WidgetStyle name="Line number margin" styleID="33" fgColor="8F8F8F" bgColor="363636" fontName="" fontStyle="0" fontSize="9" />
DansLeRuSH-Dark.xml:1206:        <WidgetStyle name="Global override" styleID="0" fgColor="C7C7C7" bgColor="2E2E2E" fontName="Source Code Pro" fontStyle="0" fontSize="10" />
DarkModeDefault.xml:1772:        <WidgetStyle name="Default Style" styleID="32" fgColor="DCDCCC" bgColor="3F3F3F" fontName="Consolas" fontStyle="0" fontSize="10" />
DarkModeDefault.xml:1825:        <WidgetStyle name="Global override" styleID="0" fgColor="DCDCCC" bgColor="3F3F3F" fontName="Consolas" fontStyle="0" fontSize="10" />
Deep Black.xml:1041:        <WidgetStyle name="Default Style" styleID="32" fgColor="FFFFFF" bgColor="000000" fontName="Courier New" fontStyle="0" fontSize="9" />
Deep Black.xml:1094:        <WidgetStyle name="Global override" styleID="0" fgColor="FFFFFF" bgColor="000000" fontName="Courier New" fontStyle="0" fontSize="9" />
Hello Kitty.xml:1013:        <WidgetStyle name="Default Style" styleID="32" fgColor="000000" bgColor="FFB0FF" fontName="Courier New" fontStyle="0" fontSize="10" />
Hello Kitty.xml:1065:        <WidgetStyle name="Global override" styleID="0" fgColor="FFFF80" bgColor="FFB0FF" fontName="Courier New" fontStyle="0" fontSize="10" />
HotFudgeSundae.xml:1170:        <WidgetStyle name="Default Style" styleID="32" fgColor="B7975D" bgColor="2B0F01" fontName="Consolas" fontStyle="0" fontSize="10" />
HotFudgeSundae.xml:1222:        <WidgetStyle name="Global override" styleID="0" fgColor="B7975D" bgColor="2B0F01" fontName="Consolas" fontStyle="0" fontSize="10" />
khaki.xml:1167:        <WidgetStyle name="Default Style" styleID="32" fgColor="5F5F00" bgColor="D7D7AF" fontName="Consolas" fontStyle="0" fontSize="10" />
khaki.xml:1219:        <WidgetStyle name="Global override" styleID="0" fgColor="5F5F00" bgColor="D7D7AF" fontName="Consolas" fontStyle="0" fontSize="10" />
Mono Industrial.xml:1040:        <WidgetStyle name="Default Style" styleID="32" fgColor="FFFFFF" bgColor="222C28" fontName="DejaVu Sans Mono" fontStyle="0" fontSize="10" />
Mono Industrial.xml:1051:        <WidgetStyle name="Line number margin" styleID="33" fgColor="EEEEEC" bgColor="2E3436" fontName="" fontStyle="0" fontSize="8" />
Mono Industrial.xml:1092:        <WidgetStyle name="Global override" styleID="0" fgColor="FFFFFF" bgColor="222C28" fontName="DejaVu Sans Mono" fontStyle="0" fontSize="10" />
Monokai.xml:1056:        <WidgetStyle name="Default Style" styleID="32" fgColor="F8F8F2" bgColor="272822" fontName="DejaVu Sans Mono" fontStyle="0" fontSize="10" />
Monokai.xml:1067:        <WidgetStyle name="Line number margin" styleID="33" fgColor="EEEEEC" bgColor="2E3436" fontName="" fontStyle="0" fontSize="8" />
Monokai.xml:1108:        <WidgetStyle name="Global override" styleID="0" fgColor="F8F8F2" bgColor="272822" fontName="DejaVu Sans Mono" fontStyle="0" fontSize="10" />
MossyLawn.xml:1170:        <WidgetStyle name="Default Style" styleID="32" fgColor="F2C476" bgColor="58693D" fontName="Consolas" fontStyle="0" fontSize="10" />
MossyLawn.xml:1222:        <WidgetStyle name="Global override" styleID="0" fgColor="F2C476" bgColor="58693D" fontName="Consolas" fontStyle="0" fontSize="10" />
Navajo.xml:1167:        <WidgetStyle name="Default Style" styleID="32" fgColor="000000" bgColor="BA9C80" fontName="Consolas" fontStyle="0" fontSize="10" />
Navajo.xml:1219:        <WidgetStyle name="Global override" styleID="0" fgColor="000000" bgColor="BA9C80" fontName="Consolas" fontStyle="0" fontSize="10" />
Obsidian.xml:1072:        <WidgetStyle name="Default Style" styleID="32" fgColor="E0E2E4" bgColor="293134" fontName="Courier New" fontStyle="0" fontSize="10" />
Obsidian.xml:1124:        <WidgetStyle name="Global override" styleID="0" fgColor="E0E2E4" bgColor="293134" fontName="Courier New" fontStyle="0" fontSize="10" />
Plastic Code Wrap.xml:1052:        <WidgetStyle name="Default Style" styleID="32" fgColor="F8F8F8" bgColor="0B161D" fontName="DejaVu Sans Mono" fontStyle="0" fontSize="10" />
Plastic Code Wrap.xml:1063:        <WidgetStyle name="Line number margin" styleID="33" fgColor="EEEEEC" bgColor="2E3436" fontName="" fontStyle="0" fontSize="8" />
Plastic Code Wrap.xml:1104:        <WidgetStyle name="Global override" styleID="0" fgColor="F8F8F8" bgColor="0B161D" fontName="DejaVu Sans Mono" fontStyle="0" fontSize="10" />
Ruby Blue.xml:891:        <WidgetStyle name="Default Style" styleID="32" fgColor="FFFFFF" bgColor="112435" fontName="DejaVu Sans Mono" fontStyle="0" fontSize="10" />
Ruby Blue.xml:902:        <WidgetStyle name="Line number margin" styleID="33" fgColor="FFFFFF" bgColor="1F4661" fontName="" fontStyle="0" fontSize="8" />
Ruby Blue.xml:943:        <WidgetStyle name="Global override" styleID="0" fgColor="FFFF80" bgColor="FF8000" fontName="Courier New" fontStyle="0" fontSize="10" />
Solarized-light.xml:1178:        <WidgetStyle name="Default Style" styleID="32" fgColor="657B83" bgColor="FDF6E3" fontName="Consolas" fontStyle="0" fontSize="10" />
Solarized-light.xml:1230:        <WidgetStyle name="Global override" styleID="0" fgColor="657B83" bgColor="FDF6E3" fontName="Consolas" fontStyle="0" fontSize="10" />
Solarized.xml:1570:        <WidgetStyle name="Default Style" styleID="32" fgColor="839496" bgColor="002B36" fontName="Consolas" fontStyle="0" fontSize="10" />
Solarized.xml:1622:        <WidgetStyle name="Global override" styleID="0" fgColor="839496" bgColor="002B36" fontName="Consolas" fontStyle="0" fontSize="10" />
Twilight.xml:1041:        <WidgetStyle name="Default Style" styleID="32" fgColor="F8F8F8" bgColor="141414" fontName="Consolas" fontStyle="0" fontSize="10" />
Twilight.xml:1052:        <WidgetStyle name="Line number margin" styleID="33" fgColor="EEEEEC" bgColor="2E3436" fontName="" fontStyle="0" fontSize="8" />
Twilight.xml:1093:        <WidgetStyle name="Global override" styleID="0" fgColor="F8F8F8" bgColor="141414" fontName="Consolas" fontStyle="0" fontSize="10" />
Vibrant Ink.xml:1011:        <WidgetStyle name="Default Style" styleID="32" fgColor="FFFFFF" bgColor="000000" fontName="Monaco" fontStyle="0" fontSize="10" />
Vibrant Ink.xml:1063:        <WidgetStyle name="Global override" styleID="0" fgColor="FFFF80" bgColor="FF8000" fontName="Courier New" fontStyle="0" fontSize="10" />
vim Dark Blue.xml:1003:        <WidgetStyle name="Default Style" styleID="32" fgColor="FFFFBF" bgColor="000040" fontName="Consolas" fontStyle="0" fontSize="10" />
Zenburn.xml:1740:        <WidgetStyle name="Default Style" styleID="32" fgColor="DCDCCC" bgColor="3F3F3F" fontName="Consolas" fontStyle="0" fontSize="10" />
Zenburn.xml:1792:        <WidgetStyle name="Global override" styleID="0" fgColor="DCDCCC" bgColor="3F3F3F" fontName="Consolas" fontStyle="0" fontSize="10" />
```

I understand default style and global override but some fonts specify font size for  `Line number margin`. Should it be removed?

**Comment by pryrt** [comment]
> I wanted to remove font sizes from the themes but now I see 441b32c fixed it already.

Yep


> I understand default style and global override but some fonts specify font size for `Line number margin`. Should it be removed?

I would say it probably should.  Feel free to create the issue (and PR, if you're willing)
