### ISSUE TITLE
[BUG] filebuffer flushing fail

### ISSUE THREAD

**Issue by burnhardo** [notepad-plus-plus/notepad-plus-plus#15657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Hi there,

since 8.6.5 and Windows 11 i have a Problem. I cannot write anymore to my external drive, there comes a filebuffer flushing fail error. Before i used Windows 10 and there was no Problem at all, since i upgraded to Windows 11 (clean install) i have this. I tested all versions back and with 8,.6.4 it works, all higher versions this problem occurs for me. So what can i do?

Regards

### Steps To Reproduce

1.  Open textfile on external drive, write something, press save.

### Current Behavior

filebuffer flushing error

### Expected Behavior

That it should work?

### Debug Information

```shell
Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\Users\bene\Downloads\npp.8.7.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 24H2
OS Build : 26100.1742
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by xomx** [comment]
> Before i used Windows 10 and there was no Problem at all, since i upgraded to Windows 11 (clean install) i have this.

Most probably you have a specific problem with the drive driver selected after the upgrade to Win11. Such a thing has been already reported before: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6133#issuecomment-1965978341 and read all the preceding post of that user.

> there comes a filebuffer flushing fail error.

Could you describe exactly that error-msg (a screenshot will do or you can use the usual Ctrl+C in that error messagebox dialog, or at least write out the error-code reported there...)

> since 8.6.5 ...

> I tested all versions back and with 8,.6.4 it works, all higher versions this problem occurs for me.

  As of the v8.6.5, N++ has only added a user-msg about the possible FlushFileBuffers WINAPI failure ( #14842 ). Until that version the flushing data problem could be there too but hidden. The reporting has been added also because users like you usually blamed the N++ when they lost their data because of that. Now the users are at least informed that they have a serious HW/SW/setting problem on their PC and can act accordingly...

> OS Version : 24H2
OS Build : 26100.1742

Is it some preview version of Windows?

**Comment by burnhardo** [comment]
I didnt blame N++, i use N++ for years and i didnt loose data. It is Windows 11 24H2, no preview anymore. I take a look into 14842, thanks.

**Comment by burnhardo** [comment]
Hi there,

i reformatted the external drive and now it works. Thanks for the hints, i close this now.

**Comment by xomx** [comment]
@burnhardo 
Glad to hear you were able to resolve it.
Thanks for the info, so even a problem with a disk format can cause the data flushing fail, interesting!

Just for the record - what error number has been shown on your N++ error-msg?

![npp-flush-fail-msg](https://github.com/user-attachments/assets/142002f7-33d7-4ffc-8862-13059802e7a2)

**Comment by burnhardo** [comment]
Dont know if there was a Problem, it was a Ventoy Disk that i update weekly with Programs etc.
As i said, i switched to Windows 11 last week and on Windows 10 there was no Problem at all with any N++ Version, i always use the lastest. I formatted it today, made a new Ventoy Disk and the Problem is gone. So, thanks for the hint that it can be a Hardware failure or something, so my idea was i format it first ;)
It was Error Code 6
