### ISSUE TITLE
[BUG] Uncheckmarked 'Enable Copy/Cut Line without selection' makes Ctrl+c in 'Search results' panel do nothing

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#15739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

See Steps to Reproduce (STR).

### Steps To Reproduce

1. Create a new tab with text `foo`
2. Run a _Find All in Current Document_ for `f` with the new tab active (_Search results_ panel will open)
3. On _Settings_ > _Preferences..._ > _Editing 1_, checkmark _Enable Copy/Cut Line without selection_
4. Select some text in _Search results_ panel and press Ctrl+c
5. Do a paste into the tab created in step 1 (observe that the text copied in step 4 is the same text that was just pasted -- good)
6. On _Settings_ > _Preferences..._ > _Editing 1_, remove the checkmark from _Enable Copy/Cut Line without selection_
7. Select some text in _Search results_ panel (making sure it is different text from the selection made in step 4) and press Ctrl+c
8. Do a paste into the tab created in step 1 (observe that the text copied in step 7 is NOT the same text that was just pasted, in fact what was pasted is the text copied in step 4)

### Current Behavior

Ctrl+c in _Search results_ panel not always working.

### Expected Behavior

Ctrl+c in _Search results_ panel always working.

### Debug Information

```shell
Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\NotepadPlusPlus\Misc\_NoBackup\Releases\npp.8.7\npp.8.7.portable.x64\notepad++.exe
Command Line : -titleAdd="8.7 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.4317
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    PythonScript (2)
```

**Comment by pedroeloy21** [comment]
This issue has been very anoying!, because I've been missing many copy/pastes from the  search results. Sometimes it worked fine (when i copied the text with right click menu of the mouse), sometimes it didn't work (when using Ctrl-C).

**Comment by Coises** [comment]
I can see how the problem arises. It’s somewhat related to the NPPM_MODELESSDIALOG problem from Issues #14557 and #14568.

Keyboard shortcuts for the cut, copy and paste commands direct to Notepad++ menu commands since, if I recall correctly, 8.6.1. A fix was added in commit [f7c44b4](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/f7c44b4413457e42e0ba56ae84f34ef0540029e8) to fix the unexpected impact on modeless dialogs used in plugins that don’t call NPPM_MODELESSDIALOG.

However, the keyboard shortcuts still go through the Notepad++ main menu; therefore, when Cut and Copy are disabled, the shortcuts do nothing. This affects keyboard shortcuts in the search results panel.

So, note that in the steps to reproduce, if between steps 6 and 7 you select something in the edit window, the copy will work.

Presumably the same problem occurs in plugins with modeless dialogs that do not call NPPM_MODELESSDIALOG (including docking windows); I haven’t attempted to identify such a plugin and test that, though.

To fix this, either the enabled status of the Cut and Copy menu items has to change when the focus isn’t in the edit window, or the shortcuts have to be dispatched with a different accelerator table when focus isn’t in the edit window.

**Comment by softmgr** [comment]
In the newly added function `allowCopyAction()` in `FindReplaceDlg.h`, there’s an issue:

When Notepad++ is in the background and then brought back to the foreground, the `checkClipboard()` function is forcefully executed to refresh the UI. However, before this function is executed, the focus automatically shifts to `_pEditView`. As a result, even if there is already selected text in the search results, it does not get the focus, leading to the execution of `enableCommand(IDM_EDIT_COPY, false, MENU | TOOLBAR);`.

To reproduce this issue:
	1.	Select some text in the `Search results`.
	2.	Move Notepad++ to the background.
	3.	Bring it back to the foreground.
	4.	Right-click on the selected text in the `Search results` (without changing the selection).
	5.	Left-click on the Notepad++ window’s title bar (the right-click menu will disappear, and the cursor focus will be on `_pFinder->_scintView`).
	6.	Go to the main menu -> Edit, and you’ll notice that the "Copy" menu item is grayed out and unavailable. At this point, pressing Ctrl+C will also not copy the text from the `Search results`.

Here’s a simple fix for this issue, shared for your reference:

```

	bool allowCopyAction() {
		HWND focusedHwnd = GetFocus();
		Finder* finder = getFinderFrom(focusedHwnd);

		if (finder)
		{
			return finder->_scintView.hasSelection();
		}

		if (!finder)
		{
			if (_pFinder && _pFinder->_scintView.isVisible())
				return  _pFinder->_scintView.hasSelection();
		}

		return false;
	};

```

**Comment by Coises** [comment]
@softmgr wrote:

> To reproduce this issue:
> 1. Select some text in the Search results.
> 2. Move Notepad++ to the background.
> 3. Bring it back to the foreground.
> 4. Right-click on the selected text in the Search results (without changing the selection).
> 5. Left-click on the Notepad++ window’s title bar (the right-click menu will disappear, and the cursor focus will be on _pFinder->_scintView).
> 6. Go to the main menu -> Edit, and you’ll notice that the "Copy" menu item is grayed out and unavailable. At this point, pressing Ctrl+C will also not copy the text from the Search results.
> 
> Here’s a simple fix for this issue

I tested and also found that this does fix the specific sequence you described.

If instead of steps 4 and 5 as stated above, you press F7, the same problem occurs without your fix and your fix corrects that, too.

If instead of 4 and 5 as stated above, you left-click in the title bar of the Search results window, the same problem occurs without your fix; with your fix, the Copy command is enabled, but Ctrl+C doesn’t copy anything.

All these can also be reproduced by simply clicking in the edit window rather than steps 2 and 3 above.

**Bigger problem:** if you just do steps 1-3 or 1 and click in the edit window (either way, focus is now in the edit window), the Copy command is enabled (though it won’t copy anything). In general, your fix causes the Copy command to be enabled whenever there is a selection in the search results window, regardless of where focus is.

I think the problem requires a bit more examination. I suspect what is happening is that some means of returning focus to the search results window are putting focus onto the container and not onto the Scintilla control, which is causing detection to fail. Possibly (not examined or tested yet) a better solution would be to assure that whenever focus goes into the search results container, the actual Scintilla control is focused.

**Comment by donho** [comment]
@softmgr 
The code you provided check if Search result window is visible for making Copy command available.
As @Coises has pointed out:
> your fix causes the Copy command to be enabled whenever there is a selection in the search results window, regardless of where focus is.

That's not what I aims for. 

I did the fix about F7 - it should work better now:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/8f0484caf3e413cd3e28590f8a4e1c11e10f6c39

The fix works also for the scenario provided by @softmgr 
However, Left-click on the Search result title bar instead of Notepad++ window’s title bar doesn't work.
It's due to the work around here (just comment this line and you will see), which has been done 15 years ago: 
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScintillaComponent/FindReplaceDlg.rc#L119

For the bug I just described, I have no idea how to fix, but globally it works much better now.
