### ISSUE TITLE
[Feature request] Get rid of the messagedialog "... doesn't exists anymore. Keep this file in editor?

### ISSUE THREAD

**Issue by jvanlangen** [notepad-plus-plus/notepad-plus-plus#15765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When done moving some files, opening notepad++ again, gives these very annoying popups of non-existing files. This is the same with "new version popup naggings"

popups are sooo windows xp.   :-(

### Describe the solution you'd like.

Instead of nagging the user, you could change it by changing the color of the filename in the tab.

### Debug Information

```shell
Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Dev\PWRPack\Applications\MachineSystem5-Baseline\Source\Library\Controls3\AssemblyInfo.cs" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.4894
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
>When done moving some files, opening notepad++ again, gives these very annoying popups of non-existing files. 

Presume this means moving some files with Windows Explorer.

Popups are there to warn you when something unexpected happens.  If it is truly expected (because you intentionally moved the file), then it could be considered slightly annoying.  However, if it is NOT expected (due to a screw-up on your part) then you'd be glad the popups are there, alerting you to your PBKAC and giving you early warning about fixing the problem before further damage is done.

Regardless, I don't see the complaint of this issue driving any changes to the software.

---

>This is the same with "new version popup naggings"

Separate thing.  Please confine issues to one specific topic each.  If you'd like to complain about "new version popup naggings" please create a separate issue for it.

---

>popups are sooo windows xp. :-(

Nonsensical statement.

**Comment by pawelzwronek** [comment]
Despite widnows xp statement I would agree to @jvanlangen This popup is most of the time unnecessary. I suggest to remove the popup and mark the tab as a deleted file. When user close it no further popup would show.

![obraz](https://github.com/user-attachments/assets/deaa3c0d-a218-416f-b28d-9d34b761221b)

**Comment by pawelzwronek** [comment]
@donho What's you opinion in replacing "doesn't exists anymore" popup with an X icon and `deleted` text after a file name? Also, deleted file could be in to read-only mode (to additionally indicate it doesn't exist), and "unlocked" only when user save it with Ctrl+S or so. If you like this idea I could try to implement it.

**Comment by donho** [comment]
I agree with what @alankilborn said totally.

**Comment by pawelzwronek** [comment]
I respect and understand your decision, but despite all the coolnes N++ has (I use it all the time), it has in my opinion, things could be changed, and I'm 100% sure it's one of them. @jvanlangen please expect my custom build with this feature, cos it'll save a lot of time and nerves. I totally understand your opinion about popups. @donho thx for this awesome piece of software 🤘
