### ISSUE TITLE
[BUG] Opening files from Smb share fails

### ISSUE THREAD

**Issue by Absolutely-Free** [notepad-plus-plus/notepad-plus-plus#15776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

I have a file share from a Samba server on my home network that I use to store Windows related notes in txt files. In previous versions of notepad++, I was able to open those files directly from the shared directory and edit them there. This functionality has broken in a recent version. I am not experiencing any problems with the SMB server. I can still open these files directly from the SMB server with regular notepad just fine, and if I copy the files to a local directory I can edit the copy with notepad++, but I always get errors when I try to open the files directly from the shared path with notepad++. For example:

![image](https://github.com/user-attachments/assets/59052e41-fd5d-4de4-8916-f22fa8cb9290)

This is the path to the files. I double click on one of the files, and I get this error when opening it:

![image](https://github.com/user-attachments/assets/b1e53d13-3a25-4658-bd57-6783edc64649)

Followed by this message when I click OK:

![image](https://github.com/user-attachments/assets/9b37d7db-4e37-446f-9463-fd6db7243c93)

### Steps To Reproduce

1.  In file explorer, navigate to an SMB shared directory containing a txt file.
2.  Open the txt file in notepad++

### Current Behavior

Currently I get error messages as shown above

### Expected Behavior

The files should be able to be opened with notepad++ and edited as usual.

### Debug Information

```shell
Notepad++ v8.7.1   (64-bit)
Build time : Oct 31 2024 - 00:48:56
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro N (64-bit)
OS Version : 22H2
OS Build : 19045.5011
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

### Anything else?

I tried renaming the plugins folder and then opening the files from the SMB share, but it had no effect.

**Comment by xomx** [comment]
@Absolutely-Free 

Could you download the fix draft x64 binary 

https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/11761446995/artifacts/2167545451

replace your "notepad++.exe" file and test your scenario again?

**Comment by Absolutely-Free** [comment]
@xomx First, I should mention that I installed notepad++ via Chocolatey in case that has any possible ramifications.

I navigated to C:\Program Files\Notepad++, renamed the notepad++.exe file in there, and extracted the executable you provided to that location.

In an attempt to eliminate possible Chocolatey shenanigans, I just double clicked the exe you provided to launch the application, then used the Open functionality to open the file (rather than double clicking on the file in file explorer as I did previously). Now I am getting a slightly different error message:

![image](https://github.com/user-attachments/assets/2f2308ad-70dd-496f-a376-f2f03630d998)

I also get that same new error message if I try double clicking the file from file explorer as I did in my original example.

**Comment by xomx** [comment]
@Absolutely-Free 
Ok, right track (`fileSize == -1`) but different reason why.
Test please with another binary & show again screenshots with all the messages:
https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/11763773201/artifacts/2167979037

**Comment by Absolutely-Free** [comment]
@xomx Sure thing!

I overwrote the executable with this new version, opened notepad++ by double clicking the executable again, and used the open functionality to open the file. Here are the error messages I get:

![image](https://github.com/user-attachments/assets/a2d1e53b-1ada-4ecd-8917-6e19fd4e1ff4)

![image](https://github.com/user-attachments/assets/e7e8d950-9a68-47bd-a671-8ebd20fe84ef)

![image](https://github.com/user-attachments/assets/d4bd1e9b-632e-4e0e-8191-84a19519c806)

![image](https://github.com/user-attachments/assets/d6b19d89-5bc4-46c8-a60e-ead0c3620850)

**Comment by xomx** [comment]
@Absolutely-Free  once more please:

https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/11768779064/artifacts/2168896965

**Comment by Absolutely-Free** [comment]
@xomx I repeated the same process as in my most recent message. I am now getting only these 2 error messages:

![image](https://github.com/user-attachments/assets/6751b5a6-1832-49fe-9230-d710bb0132bb)

![image](https://github.com/user-attachments/assets/cf5f8291-4545-44ca-978d-0be4164a7d78)

**Comment by xomx** [comment]
@Absolutely-Free 
Weird, from the described behavior it looks like the N++ getFileAttributesExWithTimeout worker thread gets stuck on an existing file and has to be terminated. We will see from the next test binary:
https://github.com/xomx/notepad-plus-plus/actions/runs/11769634848/artifacts/2169063196

**Comment by Absolutely-Free** [comment]
@xomx Interesting results this time. Again, I extracted the executable and replaced the one in C:\Program Files\Notepad++ with this new one.

If I double click the executable, use the open function from within the program, and open a txt file from a Samba share, the file opens correctly and the application seems to function as expected. When I open the file like this, this is the debug info I see:

> Notepad++ v8.7.1   (64-bit)
Build time : Nov 11 2024 - 00:08:03
Path : C:\Program Files\Notepad++\Notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro N (64-bit)
OS Version : 22H2
OS Build : 19045.5011
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)


If I navigate to the file in file explorer and double click the file to open it, I still get this error:

![image](https://github.com/user-attachments/assets/3efdba31-cc84-4c98-b684-89e56854cdb8)

When I do this, this is what I get in the debug info:

> Notepad++ v8.7.1   (64-bit)
Build time : Nov 11 2024 - 00:08:03
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "\\10.30.42.10\windowsData\Notes\windows setup.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro N (64-bit)
OS Version : 22H2
OS Build : 19045.5011
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)

**Comment by xomx** [comment]
@Absolutely-Free 
Hmm, I am starting to think it has something to do with network storage credentials. But I absolutely need one error message that I still cannot get invoked on your computer yet, so maybe now?
https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/11789169196/artifacts/2174026968

**Comment by Absolutely-Free** [comment]
@xomx Here is what I see if I double click the provided executable and use open to open the file:

![image](https://github.com/user-attachments/assets/77c354f0-3a39-45b8-8ec1-f073a35e930d)

If I click OK on that screen, the file opens correctly.

Here is the sequence of errors I see when I navigate to the file in file explorer and double click on the file:

![image](https://github.com/user-attachments/assets/3964fcbf-cd77-404e-8d2c-9074b67e5b70)

![image](https://github.com/user-attachments/assets/7278eded-1123-44a2-bc78-6cf0a947038d)

In this case, the file does not open afterwards.

**Comment by xomx** [comment]
@Absolutely-Free 

> dwFileAttributes: 16

So the problem is that your Samba is telling the Windows OS that your file is a directory!?

(16 (0x10 hexa) means [FILE_ATTRIBUTE_DIRECTORY](https://learn.microsoft.com/en-us/windows/win32/fileio/file-attribute-constants))

So this is not a N++ problem. In pre-v8.7.1 versions your problem was masked by the fact that the N++ used different filesize checking way (POSIX one, `fopen` + `fseek` at the file end + `ftelli` reported that position).

**Comment by donho** [comment]
> So the problem is that your Samba is telling the Windows OS that your file is a directory!?

Hmm... could it be a problem of Samba settings?
If not, then we will have a lot of complain soon - The auto-update has been just triggered for a few minutes for v8.7.1
Let's wait & see.

**Comment by xomx** [comment]
@donho 
> Hmm... could it be a problem of Samba settings?

Yes, it could:
https://askubuntu.com/questions/1288678/some-files-on-samba-shares-are-displayed-as-folders

But there are two different problems mixed together in this issue:

1) Already revealed that Samba is flagging user txt-files somehow as a dir.

2) Double-clicking the txt-file (from the user 1st pic in this issue is evident that he has the N++ associated with txt-files) behaves differently than launching the N++ 1st and then File > Open... (Ctrl+O). For a long time I could not figure out the reason, but I had it in front of my eyes the whole time - look at what user [reported in that case](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15776#issuecomment-2467037378) as the N++ Debug Info:
`Command Line : "\10.30.42.10\windowsData\Notes\windows setup.txt"`
It should be instead:
`Command Line : "\\10.30.42.10\windowsData\Notes\windows setup.txt"`

I did a quick test to confirm if there can be a problem with the cmdline parsing in N++ for such a network path but it is ok, at least for me - STR:
- associate your N++ with txt-files (rightclick > Open with...)
- put a test txt-file in your %WINDIR% (my one was `C:\Windows\npp-test1.txt`)
- open MS Explorer and reach the test file for doubleclicking opening this way via localhost:

  ![npp-explorer-localhost-doubleclick-txt](https://github.com/user-attachments/assets/9ed9a092-05a5-40da-b6ec-860de15ac064)

- after the doubleclicking in Explorer I've got the correct double backslash at the beginning of the cmdline path passed by Explorer:

  ![npp-explorer-localhost-doubleclick-txt-debuginfo-ok](https://github.com/user-attachments/assets/d8058b19-a9db-4311-af3d-e74acb566698)

So the question remains why the @Absolutely-Free has got that one backslash at the beginning, so then the `GetFileAttributesEx` correctly reports that error code 87 (The parameter is incorrect.).

**Comment by Absolutely-Free** [comment]
I agree that the error message is strange, but Notepad++ is the only application that I am seeing any problems with. I can open these exact same files and edit them in place on the Samba share with Notepad, Wordpad, VS Code, and Visual Studio. If I ls on the directory that contains those files in Powershell, the files do not appear to be directories. 

> Yes, it could:
https://askubuntu.com/questions/1288678/some-files-on-samba-shares-are-displayed-as-folders

I am not having the problems described in this post. I tried adding the suggested option to my smb.conf file anyway, but it had no effect. I still get the same errors.

**Comment by Absolutely-Free** [comment]
I did some further investigation on my Samba server. I was running version 4.16 on my NAS running FreeBSD 13.4 because it was the only version available for the longest time, but recently Samba version 4.19 became available. I was not aware of this. I updated to the new version and restarted the samba service. I also restarted the windows VM that I have been doing all this testing in.

I now seem to be getting slightly different results than I was previously. Now If I double click the Notepad++ executable and use the open functionality to open the file, I get this error message:

![image](https://github.com/user-attachments/assets/db12286b-16a1-45a2-be61-41795f893fe3)

The file does actually open after clicking through that error and is editable, and this is what I get in the debug info:

> Notepad++ v8.7.1   (64-bit)
Build time : Nov 12 2024 - 01:46:04
Path : C:\Program Files\Notepad++\Notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro N (64-bit)
OS Version : 22H2
OS Build : 19045.5011
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)

If I double click on the txt file in file explorer, this is what I see for error messages:

![image](https://github.com/user-attachments/assets/be1fc269-cc92-4221-9604-e61c68221a50)

Now I seem to be getting the same results as if I opened the file via the open functionality in Notepad++ itself, the file does actually open and is editable after clicking through the error message. This is what I get in the debug info in this scenario:

> Notepad++ v8.7.1   (64-bit)
Build time : Nov 12 2024 - 01:46:04
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "\\10.30.42.10\windowsData\Notes\windows setup.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro N (64-bit)
OS Version : 22H2
OS Build : 19045.5011
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)

**Comment by xomx** [comment]
> dwFileAttributes: 128

Good, so now it shows in the same situation one from the expected values - `FILE_ATTRIBUTE_NORMAL`. The No. 1 ("file as dir") really was a problem on your specific Samba installation or setting.

But there is still the problem No. 2 ("doubleclicked file path"). What confuses me is that the N++ Debug Info still shows an incorrect path corresponding to the error code 87 shown, while e.g. in my debug code `data._filePath` is the correct one?! And also how could the `GetFileAttributesEx` WINAPI show error 87 but at the same time correctly return 128 for the `dwFileAttributes`...

**Comment by Absolutely-Free** [comment]
> > dwFileAttributes: 128
> 
> Good, so now it shows in the same situation one from the expected values - `FILE_ATTRIBUTE_NORMAL`. The No. 1 ("file as dir") really was a problem on your specific Samba installation or setting.

Seems so. Strange that it took a few years to manifest into a problem, but thankfully was fixed with a simple update!

I replaced the executable again. This is the sequence of pop ups when opening Notepad++ and opening the file from within the application:

![image](https://github.com/user-attachments/assets/7e054a9e-299b-4f37-be32-fa7bf8c2bd72)

![image](https://github.com/user-attachments/assets/5212043b-d8df-4b59-8088-f78c0bbb5cbe)

The file then opens correctly and is editable. Here is the debug info in this scenario:

> Notepad++ v8.7.1   (64-bit)
Build time : Nov 13 2024 - 12:27:05
Path : C:\Program Files\Notepad++\Notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro N (64-bit)
OS Version : 22H2
OS Build : 19045.5131
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)


And here is the sequence of pop ups when I double click the file from file explorer:

![image](https://github.com/user-attachments/assets/d4b68109-7074-4341-8f03-dc9c56607518)

![image](https://github.com/user-attachments/assets/83abf4a1-96b9-41b0-af2c-e5a9d500c89c)

![image](https://github.com/user-attachments/assets/c8d00d30-688b-4091-9e84-82ec207b31bb)

![image](https://github.com/user-attachments/assets/41c54bb3-94de-4e8d-a5f4-d8a5236a88c9)

![image](https://github.com/user-attachments/assets/7cbc3b76-2630-4ca0-8da0-0ca26f69bad9)

![image](https://github.com/user-attachments/assets/6ad86933-00ca-4172-b875-5a60fcf4907a)

The file then opens correctly and is editable. Here is the debug info in this scenario:

> Notepad++ v8.7.1   (64-bit)
Build time : Nov 13 2024 - 12:27:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "\\10.30.42.10\windowsData\Notes\windows setup.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro N (64-bit)
OS Version : 22H2
OS Build : 19045.5131
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)

**Comment by xomx** [comment]
@Absolutely-Free 

So all the remaining problematic stuff is ok, now I have explanation for everything in this issue.

> But there is still the problem No. 2 ("doubleclicked file path"). What confuses me is that the N++ Debug Info still shows an incorrect path corresponding to the error code 87 shown, while e.g. in my debug code `data._filePath` is the correct one?!

There is no such problem at all. This is all about how the GitHub changes here some of the path-data representation:
- this is my relevant Debug Info line, when pasted here as a text (note that there is one backslash missing at the beginning):
  Command Line : "\\127.0.0.1\admin$\npp-test1.txt"
- and this is exactly the same text but formatted as a code:
  `Command Line : "\\127.0.0.1\admin$\npp-test1.txt"`

One mystery solved.


> And also how could the `GetFileAttributesEx` WINAPI show error 87 but at the same time correctly return 128 for the `dwFileAttributes`...

2nd mystery - again, not a real problem. I made a mistake in my additional debug code - I used existing N++ custom func for translating the WIN32 error codes to the human understandable sentences. Unfortunately, for the error code 0 (aka the `NO_ERROR`) this func does not directly show the equivalent text "The operation completed successfully." but instead it fires up its own `GetLastError()` detection call, which is wrong here as these error codes are per-thread in Windows and the right error-code to report originates from another worker thread. So that 87 visible was completely irrelevant here, as it was an error state for some other WINAPI call (unfortunately, that 87 made sense in the context of debugging - which was just a coincidence but confuses me enough).

**Comment by xomx** [comment]
@donho
> Hmm... could it be a problem of Samba settings?
> If not, then we will have a lot of complain soon - The auto-update has been just triggered for a few minutes for v8.7.1
> Let's wait & see.

It is ok, the problem was entirely on the user's Samba side (after the Samba update, incorrect reporting of file attributes as if they were directories stopped).

So no flood of complaints from the Samba users...

I will only do a minor PR for:
- fixing remaining missing inits for some `dwFileAttributes`
- if you agree I will also add one dwError variable to the `struct GetAttrExParamResult` to make the checking, for the possible used WINAPI state, possible from the main N++ thread
- changing misleading `DWORD _result` there to `BOOL _result`

**Comment by donho** [comment]
@xomx 
Thank you for the investigation!

> I will only do a minor PR for:

Go ahead please. We can discuss during the code review anyway.
