### ISSUE TITLE
[BUG] Follow current doc. option should coordinate better with the Directory input field

### ISSUE THREAD

**Issue by notdodgeball** [notepad-plus-plus/notepad-plus-plus#15908]
### Steps to Reproduce the Issue
1.  Open Find in Files
2.  Check **Follow current doc.** checkbox (The directory displayed will be updated to the current one if it isn't already)
3.  Manually edit the directory to a different one
4.  Click **Find All**

Then the search is executed in the given directory despite the **Follow current doc.** checkbox 

The checkbox should either:
- gray out the Directory field
- be automatically unchecked if the Directory field is modified

### Debug Information
Notepad++ v8.7.1   (64-bit)

**Comment by alankilborn** [comment]
I like it the way it is.
The suggested changes would make me expend more effort in my searching.

Note: "Follow current doc." is really "Load the directory of the file in the active tab when FindInFIles is invoked".  As you'll notice, if the FindInFiles window is left open while the user goes back to the editor window and changes the active tab, no changes occur in the _Directory_ box, hence the "when FindInFiles is invoked" clause.  But of course the text that explains it all is too long to put for caption text on a control.

Tip: To _really_ follow the current doc at the moment, uncheckmark _Follow current doc_ and then re-checkmark it.  This will freshen the _Directory_ box to contain the folder of the active tab.

**Comment by notdodgeball** [comment]
@alankilborn, try reconsidering your opinion, if you say
> "Follow current doc." is really "Load the directory of the file in the active tab"
then it's a indication that we have a problem. In fact, that's exactly what I'm trying to indicate here that's is confusing.

Either the current doc is not being "followed" or not, and the search as it is now, can be executed completely opposite to the checkbox.

The checkbox can renamed of course, but I thought of this option as a search directive.

**Comment by alankilborn** [comment]
So suggest some acceptable alternative caption text for the checkbox.
Don't attempt to change existing functionality, such that it impedes my workflow, to adapt to the current caption text.

**Comment by notdodgeball** [comment]
> Don't attempt to change existing functionality, such that it impedes my workflow, to adapt to the current caption text.

Yeah, crazy of me to think a software should do what it says it does.

To your own admission the text is wrong, so feel free to suggest other caption text. It will be clearly more useful than your participation so far in this discussion.

I, if it's not obvious enough, think the text is correct, it's not doing what it says, which is according to the docs is:

`
If checked, it will default to searching the folder that contains the current active document
`

Notice it does not read "Overwrite the Directory input combo with the path of the current file" or similar, it could be less ambiguous of course but it doesn't not matter. Either way we have two conflicting gui elements, that's why this bug report was open.

**Comment by alankilborn** [comment]
>so feel free to suggest other caption text. 

That's just it; I don't have an awesome suggestion.  IIRC this has been discussed before (somewhere, not sure where) and there was no resolution because better text could not be found.

---

>according to the docs is...

@pryrt What do you think, can the docs be improved to better capture current functionality?  While we're at it, do you have an opinion about current functionality?

---

Another idea:

* Move _Follow current doc._ checkbox to _Preferences_ > _Searching_ (and give it a better caption there where there is slightly more space), reflecting the functionality that having the checkbox checkmarked there will cause the invocation of (note, that is the important point, THE INVOCATION OF..) _Find in Files_ to populate the _Directory_ combobox with the active document's folder.  If uncheckmarked, there is no functionality.
* Add a button by the existing FIF _Directory_ combobox that, when pressed, copies the text of the active document's directory to that combobox (again, not sure of what a great caption would be for this, that would be short enough)

---

>It will be clearly more useful than your participation so far in this discussion.

It isn't productive to degrade the conversation to this level; let's be mature.
We all want the software to be the best it can be, so let's stick to that goal, without being rude or insulting.

**Comment by pryrt** [comment]
> it's not doing what it says, which is according to the docs is:
> 
> `If checked, it will default to searching the folder that contains the current active document`
> 
> Notice it does not read "Overwrite the Directory input combo with the path of the current file" or similar, it could be less ambiguous of course but it doesn't not matter. Either way we have two conflicting gui elements, that's why this bug report was open.

Notice that it does not read `forces the directory to _only_ be that of the current doc`, which is how you seem to have interpreted the manual. It says `it will default to search the folder that contains the current active document`.  Saying "will default to searching" does not mean "will force it to always and only search".  When you launch the dialog with that option checked, or if you toggle that option off and then back on, it sets the Directory field to the current directory (hence, it _defaulted_ to searching that directory); but if you manually overwrite that directory, then it's going to use whatever you enter, because you overwrote the default.  As with all defaults, you are allowed to change them.

I will add in a clarification in the User Manual that explains more of the detail, because apparently it wasn't clear that "default" is only where it starts.

**Comment by pryrt** [comment]
> While we're at it, do you have an opinion about current functionality?

Sorry, forgot to answer that one: I definitely want the functionality as-is.  I use the default to set to approximately/usually want it, but I often take it up a directory or two so that I can search a whole repo, rather than just the subdirectory where my current file happened to be.  I do that on a nearly daily basis -- its part of my normal workflow.

Don't anyone dare change that behavior. If I had to toggle that checkbox off every time in order to manually change the directory, and then remember to toggle the option back on so that when I run FIF from a file in a different project it will properly change to that file's folder, I would throw a massive hissy fit, the likes of which no one in this repo or the Forum has ever seen from me.

**Comment by pryrt** [comment]
@notdodgeball / @alankilborn ,

I said,
> I will add in a clarification in the User Manual that explains more of the detail, because apparently it wasn't clear that "default" is only where it starts.

How is this for a potential improvement to the docs?
> * **☐ Follow current doc** ⇒ If checked, it will default to searching the folder that contains the current active document.
>    - If this is checked, it will set that "default" directory to the current document's directory when you launch **Find in Files** dialog, or if you toggle the checkbox off and then back on.  If you manually change the directory (either through typing, or using the `...` button), it will search the newly-entered directory, rather than using the directory it defaulted to.  The next time you launch the dialog, it will update the default directory again (assuming the option is still checked).
>    - The state of this checkbox is saved in the `fifFolderFollowsDoc` attribute in `config.xml`, so your choice for this option _is_ remembered from one run of Notepad++ to the next.

**Comment by alankilborn** [comment]
@pryrt said:

>I definitely want the functionality as-is

Well, if the functionality/captioning could be changed to improve things, without impacting your workflow, my workflow, and user "n"'s workflow (that we haven't heard from), _should_ it be considered?

I proposed one way [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15908#issuecomment-2518108679), see "Another idea",  which doesn't seem like it would break the workflows of either of us...

**Comment by alankilborn** [comment]
@pryrt 

A later thought about the user manual entry:

"Follow current doc." (because it is so very short amount of text) can certainly be construed that as a user changes the active tab in the editor window, that the "Directory" box will change in lockstep as that occurs.

Does the UM describing current functionality need to come right out and state that is NOT what happens?

**Comment by notdodgeball** [comment]
>     * Add a button by the existing FIF _Directory_ combobox that, when pressed, copies the text of the active document's directory to that combobox (again, not sure of what a great caption would be for this, that would be short enough)

Something like that?
![image](https://github.com/user-attachments/assets/e4aedc97-2397-481f-b4b5-259ce38ee490)

but then @pryrt would have to press it s

**Comment by alankilborn** [comment]
Continuation of my "Another idea" thought from above; I've fleshed it out:

Button with caption "Dir. from active doc."  Press of button sets the Directory combobox text to the directory of the active document. 

Checkbox in _Preferences_ > _Searching_; caption "Invoking sets Directory from active doc"  No need to say anything about "Find in FIles" because that's the only one that has the Directory box.

**Comment by pryrt** [comment]
@notdodgeball said,
> No, I actually didn't, as I said it was somewhat ambiguous and "forcing" it to be was could be one of the suggest remedies, not as I interpreted it to be.

In your original problem statement, you claimed that it should either gray out the Directory field or uncheck the checkbox, both of which, combined with your other statements, made it "seem" to me that you thought the checkbox means force (or that you thought it should force it, whatever it means).  I obviously could not know how you really interpreted it, but only had the clues you had given to go on, hence I said, "which is how you _seem_ to have interpreted...".  My use of the word `seem` was my way of indicating that it was my interpretation, not a statement of absolute fact.  So apparently, what I inferred from your statements was not what you were implying in your statements; that's bound to happen in communication.

@notdodgeball asked,
> What's your opinion on changing not only the user manual but the caption text? A better one, I think, would be "Set directory to current file path", but it's too long

I believe that the discussion that Alan alluded to had tried unsuccessfully to come up with any better phrasing that fit within the available space, and the "Follow current doc" was the thing that came closest to conveying the intent.  I have never claimed to be good at coming up with phrasings for the UI (and, in fact, most of the time I've tried, people haven't liked my suggestions).

@alankilborn mentioned,
>  I don't know that you need the bullet point about `config.xml` though

It used to be there as a parenthetical phrase 
![image](https://github.com/user-attachments/assets/e70a7d22-0a1a-46fe-b0a1-df7c26443672)
... I just moved it from parenthetical to a full point, since the parenthetical seemed to interrupt the flow to my explanatory point.  I went back and checked, and the mention of that attribute (in some form or another) has been in there since the original edits after porting from the ancient Wiki, so I'm not going to remove it at this point.

@alankilborn asked,
> Does the UM describing current functionality need to come right out and state that [where "that" refers to field-update-on-tab-activation] is NOT what happens?

I guess my "when you launch" and "if you toggle" enumeration wasn't strong enough to imply "those choices, and only those choices".  I can add `(but not when you just activate a different document tab when the FiF dialog is already open)` to clarify.

**Comment by pryrt** [comment]
@alankilborn ,
> Button with caption "Dir. from active doc." Press of button sets the Directory combobox text to the directory of the active document.
> 
> Checkbox in _Preferences_ > _Searching_; caption "Invoking sets Directory from active doc" No need to say anything about "Find in Files" because that's the only one that has the Directory box.

I'm not sure I like that caption; the "invoking" not having a clear object might cause confusion.  My suggested phrasing (for what little it's worth) would depend on whether the checkbox would go in the **When Find Dialog is Invoked** box, or grouped with the other checkmarks after that box:
- If in the box, then just "Set Directory field based on active document"
- If not in the box, then "Set Directory field based on active document when dialog is invoked"

> To be clear, this idea removes entirely _Follow current doc_ checkbox from the Find in Files tab.

**Comment by alankilborn** [comment]
> * If in the box, then just "Set Directory field based on active document"

This seems reasonable.  I hadn't actually visited the "prefs" to see what was currently there.

**Comment by alankilborn** [comment]
Here's an example of a "button" approach, from some other software I use:

![image](https://github.com/user-attachments/assets/e9b0faa3-7dc1-4b32-9589-39a3a9ff4b34)

**Comment by notdodgeball** [comment]
Example within notepad++:

![Untitled](https://github.com/user-attachments/assets/f1a39f28-07dc-4149-9b3d-a295cadf7ff7)

Something like that maybe, and the button would have a popup with a help text explaining it. But then, you'd have to press it every time to get to the current path, after that strong opinion by @pryrt, not sure he or others would be on board with that.

Being a preference, it also becomes harder to change it as oppose to being there right a the find dialog. And when not active, there won't be a easy way to get the current path.

Am I reading the situation correctly?

**Comment by pryrt** [comment]
I like the idea of the button being `<<` with hover text, as that's simple.

> But then, you'd have to press it every time to get to the current path,  ... not sure he or others would be on board with that.

The way you described it, I would be quite against it.  The way @alankilborn described it, it would be fine.

> Am I reading the situation correctly?

It doesn't appear to me that you and @alankilborn are describing the same thing, so I don't think you are reading it the same way I am.

Per @alankilborn's description, it would essentially work the way it does now, but the option would be in a different location: if the option were checked in the Preferences page, then when you launch the FiF dialog, it would automatically populate the Directory field as the "default" location to do your FiF, but if you manually enter the Directory field, it would search there instead of the auto-populated Directory.  Whether or not the option was checked, the `<<` button would re-populate the Directory field from the active tab.  

The benefit to moving the checkbox from the dialog to the **Preferences > Searching** is that there would be more room for making a longer name, like `☐ Automatically set Directory field based on active document`, which will be much less likely to confuse users than the `☐ Follow current dir` phrasing now used.

But the important thing is that it would not change my existing workflow, in that with the option set, I would not need to hit the `<<` to get the Directory; it would be correctly auto-populated when I launch the FiF dialog.

The path we take from here depends on @donho:
1. Do nothing: Don is happy with the way it is, and doesn't like the suggestions described
2. Minimal changes: Don wants the checkbox to stay where it is, with the existing text `Follow current dir`, but is willing to add a hover-text to clarify
3. Reword: Don has miraculously come up with a better phrasing than `Follow current dir` which will still fit on the existing dialog
4. Full implementation: Don is willing to have the checkbox moved to Preferences with the longer name, and to have a `<<` button with hover text on the FiF dialog for on-demand Directory update.

(And whatever decision is made for the future, the manually has already been updated to match with the reality of the current implementation, so there's at least that for now.)

But we would need Don's decision before we could do anything else regarding this request.

**Comment by alankilborn** [comment]
>...the checkbox to stay where it is, with the existing text `Follow current dir`, but is willing to add a hover-text to clarify

I know with certainty that hover text can't be added to a checkbox control (in Notepad++, for some reason that I don't recall).  So that is "out" as a suggestion.

**Comment by donho** [comment]
Thank you @pryrt for the pertinent summarizing.
It's indeed not clear at all the checkbox in question.
So I would take the option 4, by accepting both suggestions from @alankilborn & @notdodgeball : 
1. Move "Follow current doc" option and naming it as **"Automatically set Find in Files Directory field based on active document"**.
2. Add the button "<<" with tip **"Set Directory field based on active document"**

@alankilborn might be interested in implementing it. But if it's not case, I will do it.

**Comment by alankilborn** [comment]
@donho Sure, I will do it.  Please assign me.

**Comment by alankilborn** [comment]
I like how we had good conversation in this issue, culminating in a clear and concise specification for a behavior change.

**Comment by alankilborn** [comment]
I said:

>I know with certainty that hover text can't be added to a checkbox control (in Notepad++, for some reason that I don't recall).

Forget certainty, as I see this:

![image](https://github.com/user-attachments/assets/03e431b1-32f1-4dfa-952c-bbc75ba744c6)

:-(

**Comment by xomx** [comment]
@alankilborn 
> hover text can't be added to a checkbox control

Maybe you confused it with edit-ctrls, we once met that in #14287 .

**Comment by pryrt** [comment]
> Forget certainty, as I see this:

... but at least you have an example of how it can be done for this, and future such requests. ;-)

**Comment by donho** [comment]
OK. Let's do as following:
1. Move "Follow current doc" option and naming it as **"Fill Find in Files Directory Field Based On Active Document"**.
2. Add the button "<<" with tip **"Fill Directory Field Based On Active Document"**

**Comment by donho** [comment]
@alankilborn 
BTW, the current behaviour of the checkbox is quite wired for the new #.
IMO, in the case of new document (untitled) both the new checkbox in preferences and the button in FiF should do nothing.

**Comment by alankilborn** [comment]
> BTW, the current behaviour of the checkbox is quite weird for the new #.

I literally had a penciled note tucked between the rows of keys on my keyboard, from last night's debug session:  "what if press `<<` button when `new 1` is active doc?"

I'll deal with it in the change.

**Comment by alankilborn** [comment]
I'm just making a note of this (current, released) behavior here, maybe for my own benefit:

* In 8.7.4, if _Follow current doc._ is uncheckmarked, when N++ is started up and Ctrl+Shift+f is pressed, the _Directory_ field is set to the last folder in which a search was executed in the previous run (this is pulled from `config.xml`'s "FindHistory" data).  Note that if during the previous run, the user changes the text in the _Directory_ field, but does not run a search after that, the specified directory is not retained.
