### ISSUE TITLE
Request for two new file formats

### ISSUE THREAD

**Issue by mmbsman7171** [notepad-plus-plus/notepad-plus-plus#1591]
As a machinist I would deeply appreciate it if you would add .tpl (tool path language) and .gcode files as a readable and writable option.  It would mean I could code in notepad++ and drop my code straight into camotics and other CAM programs with no hassle.  I understand that might be a bigger undertaking than I imagine so if you can't manage that is okay.  But, if you do decide to do it but can only focus on one or the other, please choose .gcode files as that is a little more industry standard.  Regardless,thanks a lot, because even without that notepad++ is making my coding experience for cnc machines much more efficient and convenient!

MMBsman77

**Comment by MetaChuh** [comment]
we are closing this issue due to minor relevance for the majority of notepad++ users.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
