### ISSUE TITLE
Request for Apolitical Release Notes and Documentation

### ISSUE THREAD

**Issue by DoloMike** [notepad-plus-plus/notepad-plus-plus#15932]
The recent updates to Notepad++ have included political statements within the release notes and documentation, which could be perceived as taking a political stance. Here are the direct links to the versions in question:

- [Notepad++ v8.7.3 Release Notes](https://notepad-plus-plus.org/downloads/v8.7.3/) - "leaving X for Bluesky"
- [Notepad++ v8.7.2 Release Notes](https://notepad-plus-plus.org/downloads/v8.7.2/) - "in a world of Elon, be a Zelensky"
- [notepad-plus-plus.org/index.xml](https://pbs.twimg.com/media/GeYE3NzXsAAleMh?format=png&name=large)

Concerns:

1. By including political messages, Notepad++ risks alienating users who prefer their development tools to remain neutral. This can lead to a loss of user base and potentially encourage the rise of competing software.

2. Software documentation and release notes traditionally maintain a level of professionalism and neutrality. Political endorsements or statements can detract from this expectation, impacting the project's reputation.

Suggestions:

- Future release notes and documentation should focus on technical changes, features, and updates, avoiding any political connotations or endorsements. 

- Consider initiating a discussion within the community about how best to maintain the project's integrity while fostering an inclusive environment for all users.

This issue is raised not just as criticism but as a constructive suggestion to keep Notepad++ a universally respected tool, ensuring it remains focused on its primary function of aiding developers and users across diverse backgrounds without introducing divisive political elements.

Edit: @The-King-of-Toasters pointed out more examples by searching historical release notes

- Support Taiwan's return to the UN
- Boycott Beijing 2022
- Free Uyghur
- Yellow vest protests

**Comment by kevinwwillis** [comment]
Daily N++ user for 6 yrs. Uninstalled instantly when this was brought to my attention.

**Comment by raunak51299** [comment]
+1

**Comment by The-King-of-Toasters** [comment]
First off, nice list of AI slop "concerns". Next time you should use that big, politically neutral brain of yours to come up with an original idea.

Also, a [quick search](https://hn.algolia.com/?dateRange=all&page=0&prefix=true&query=%22https%3A%2F%2Fnotepad-plus-plus.org%22&sort=byDate&type=story) of previous N++ release notes shows that the authors have constantly inserted their strongly held political beliefs on:
- Supporting Taiwan over China.
- Supporting Hong Kong.
- Supporting the rights of the Uyghur peoples.
- Supporting the Yellow Vest protestors.
- Denouncing the CIA's use of DLL injection into programs (including N++!).

Apparently this was all fine before, but attacking daddy Elon (richest man in the world btw) is crossing the line?

**Comment by Gauva1n** [comment]
+1

I recognize and appreciate that the open source community is built upon freedom of speech and collaboration. There are times I engage in political or lifestyle discussions within dev Discords, for example, and see no problem with this. However, there are concerns that come when politically-driven agendas and messages begin to escape from discussion threads and instead start to find their way into documentation or even source. This raises substantial security concerns, especially given such past examples as vue-cli and the ES5-ext library. Those use cases began as commentary in the codebase but turned into people writing malicious commits into the code in the name of furthering their desired causes.

Unfortunately after getting bitten by these previous examples, my company's stance has become one where open-source products that engage in overly political messaging must be blocked due to the heightened potential of a bad actor pushing malicious commits in the name of hacktivism. The inability to keep documentation agnostic and focused solely on the product reflects a mentality where politics has taken precedence over the product, and history has shown time and again that this mentality can quickly devolve into product instability or even malicious activity.

**Comment by DoloMike** [comment]
> Apparently this was all fine before, but attacking daddy Elon (richest man in the world btw) is crossing the line?

No this definitely falls into the same category. I will add these examples to the issue. Thanks.

**Comment by xomx** [comment]
If the Notepad++ author overreacted a little bit to Musk/X/MAGA, this issue is not any better.

Request for apolitical Release Notes, maybe, why not, but for apolitical documentation? Show me please one such political line in the N++ docs.

And then another one, speculating that it could maybe lead to something malicious might appear in the code over time. Nice nudge. FYI: https://community.notepad-plus-plus.org/post/81387

**Comment by frankbrn** [comment]
Just wanted to add to the excellent comment from Gauva1n. This sort of political evangelism is an odd one in that the host certainly believes in his/her "good news" but not in its voluntary reception. Instead, the "good news" is spread by means of a cudgel, a rebuke of sorts that is shoved down the throats of a captive audience whether they like it or not.

It’s a fragile mindset whose message is rarely offered up on equal/neutral/appropriate grounds. In its need for total affirmation, it seeks out locales that most people would not expect to find such behavior. But then that's the point of contriving captive audiences. The negative feedback as a result is far more satisfying than preaching to the choir.

**Comment by alankilborn** [comment]
This issue should be closed by the petitioner, for 2 reasons:

* The author of Notepad++, when he notices this issue, will close it himself anyway, without action or comment (we've been down this road before)
* The sanctioned place for a complaint of this ilk is [Boycott Notepad++](https://community.notepad-plus-plus.org/category/8/boycott-notepad).

If anyone disagrees with the way things are current, they are free to take such drastic action as to stop using the Notepad++ software, and / or apply for their refund.

**Comment by AlmostHuman34** [comment]
Clown world, can't even keep your feelings/politics away from coding and math. Weak times.

**Comment by Gauva1n** [comment]
Thanks to @xomx for the forum callout. I haven't waded through the Notepad++ forums but I appreciate the info straight from the dev team that they have no intention to build that sort of hacktivist behavior into source. That post is a couple years old so hopefully that mentality still stands. That helps build confidence, even if only at a personal level.

That said, a forum post does not hold up when faced with a security audit from a company with 200+ programmers when a program is in direct violation of their P&Ps. My comment is meant to draw attention to the fact that the corporate world does not currently hold a favorable position or forecast to political messaging being present in open source software, especially given the current political situation in not only the US but around the world. I understand there is no monetary gain that the lead dev is getting for this project and that at the end of the day it doesn't matter to their livelihood if 200+ programmers are forced to switch to VS Code. My concern is that, when programmers are forced to work in VS Code 8+ hours a day, they will invariably switch over to that for their home use as well; it's just human nature. Given enough corporate influence, increased politicization in NPP could, in the mid-term, lead to decreased adoption rates and a falloff of user base. NPP has been the go-to text editor since I started in the field almost 20 years ago, and it would be a shame to see it fade into obscurity or obsolescence due to the need of the lead dev to include something as minor as politics into their software. I understand the current approach is and has been a meme-like approach with "Send in a refund request lol" and the like. But while there is freedom of speech, there is no freedom from consequence of speech. Hopefully the dev realizes that this politicization is more harmful in the long run than the short-term enjoyment of getting likes on BlueSky.

**Comment by DoloMike** [comment]
Closing this. Top contributors mention this is a feature not a bug. Has been discussed many times previously and the author is not concerned.

**Comment by angelsenvy228** [comment]
Great, glad we have some clarity now, I was waiting to stop using NP++ to see if they would reverse this, since they have no problem putting out release notes with personal politics in it I will now uninstall it and find a replacement. Thanks for the visibility @DoloMike

**Comment by jfmatth** [comment]
Just curious, when DJT and Elon get the war in Ukraine to stop, then what will you post?

I doubt you'll ever leave the echo chamber that is IT software and culture, which is too bad, you're clearly a smart developer.

I loved NP++ until VSCode came out, but I'm sure you're against that since MS created it?

**Comment by jmoralesv** [comment]
@jfmatth it seems like the two girls didn't stop any war so far, right?

On the other hand, [version 8.8.1 has some answers for you](https://notepad-plus-plus.org/downloads/v8.8.1/).

**Comment by jfmatth** [comment]
@jmoralesv Impressive that you came back to answer this, thank you 😄 

Glad to see that NP++ is still moving forward.
