### ISSUE TITLE
[BUG] Antivirus Essential detects `npp.8.4.6.Installer.x64.exe` as `Win.Malware.Rugmi-10040069-0`

### ISSUE THREAD

**Issue by 7wells** [notepad-plus-plus/notepad-plus-plus#15983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Antivirus Essential (running on my Synology NAS, with latest firmware and latest virus definitions) detected `npp.8.4.6.Installer.x64.exe` (downloaded from official website https://notepad-plus-plus.org/downloads/) as malware `Win.Malware.Rugmi-10040069-0` and moved it to quarantine.

### Steps To Reproduce

Not applicable

### Current Behavior

Unexpected detection of the NPP installer as malware

### Expected Behavior

There should be no false positive malware warning.

I understand that this is maybe(?) rather a problem of the virus scanner or its virus definitions (i.e. a false positive). However, maybe this is related to a specific packaging of NPP, too?

### Debug Information

```shell
Not applicable
```

### Anything else?

Please accept my apologies if this post does not belong under "issues" (bugs).

Wishing all of you a peaceful Christmas/winter season and all the best for 2025! 🕊️🍀

**Comment by alankilborn** [comment]
>Please accept my apologies if this post does not belong under "issues" (bugs).

It does not.

---

>I understand that this is maybe(?) rather a problem of the virus scanner or its virus definitions (i.e. a false positive).

BINGO.

**Comment by wismann** [comment]
FYI: The issue has been fixed in [yesterdays signature updates](https://lists.clamav.net/pipermail/clamav-virusdb/2025-January/008895.html) for ClamAV, after rescanning in virustotal.com the installers should be reported as clean again (verified for `npp.8.7.5.Installer_x64.exe`).
Somebody added the notepad++ help text as signature. Literally this text was one of 5 conditions in an assembly (as pseudo-UTF-16) to trigger an obvious false positive:

```
notepad++ [--help] [-multiInst] [-noPlugin] [-lLanguage] [-udl="My UDL Name"] [-LlangCode] [-nLineNumber] [-cColumnNum
```

Makes me wonder how such signatures even make it into the database...
