### ISSUE TITLE
dosbox.conf lines starting with # bug

### ISSUE THREAD

**Issue by hackwrench** [notepad-plus-plus/notepad-plus-plus#1633]
I discovered that Notepad++ will put # on one line and the rest of the string on a different line.
![image](https://cloud.githubusercontent.com/assets/8695599/13789806/0f198b7c-eabc-11e5-9222-5d429e4f9624.png)
Also, selecting "View all" whitespace isn't working and the two may be related.

**Comment by hackwrench** [comment]
Further testing showed that this was confusion due to not being able to turn on whitespace marking. There are spaces there, forcing the line down, but since View all doesn't work, I couldn't tell by looking.

**Comment by dail8859** [comment]
> not being able to turn on whitespace marking

It's on in the screen, just sometimes the little dots it puts where the space are can be hard to see.

**Comment by hackwrench** [comment]
There once was a time where I could see them plain as day. If they are there, then it's not just become hard, but impossible. If the code hasn't changed, then I'm at a loss to explain it. It's been some time and another computer since I had it on, though.

**Comment by dail8859** [comment]
You can change the color it uses for marking whitespace under the style configurator. Notepad++ only uses a single pixel to indicate whitespace. Technically with a plugin you could increase the size of that to say 4x4 pixels but currently Notepad++ doesn't give you that option. 

Since there isn't actually any bug here, you can close this issue.

**Comment by hackwrench** [comment]
Did the default color for whitespace change? https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1260 suggests that it might be from Scintilla, since it states that not being able to change the color most likely wouldn't be changed unless Scintilla implements it, and it appears that Scintilla recently implemented. This may yet be a bug.

**Comment by dail8859** [comment]
> Did the default color for whitespace change?

Not as far as I know.

>  #1260 suggests that it might be from Scintilla,

That issue is with the end of line and non-printing symbols, where this issue deals with whitespace (spaces, tabs). See the screenshot below. I used `Settings > Style configurator > Global Styles > White space symbol` and set it to black. There are single pixel dots between each word.

![capture](https://cloud.githubusercontent.com/assets/3694843/13860607/a42a1eb2-ec5f-11e5-9fc1-49fcadd2c361.PNG)
