### ISSUE TITLE
Autosave session file on close

### ISSUE THREAD

**Issue by ThomasHeinrichSchmidt** [notepad-plus-plus/notepad-plus-plus#1646]
You can set a file extension for session files, so that double-clicking automatically opens the session in Notepad++. I am using "xml++". This works fine.
EXCEPT: I have to manually fill out the   `File / Save Session / File Dialog`    when I want to save the current status of my session. This is time consuming and unnecessary.
**FEATURE REQUEST**: Automatically save the session to the recently opened session file when closing Notepad++ so that everything is restored when re-opening the session file.

**Comment by Avaray** [comment]
+1 It would be very useful.

**Comment by giuin** [comment]
+1 looking for the same feature

**Comment by eyevish** [comment]
+1 request is useful - should always save session to the file NPP was opened with.

**Comment by l-aloha** [comment]
+1 I think it is very comfortable feature!
Maybe a simple solution:

1. add in _src/Parameters.h/NppParameters_ class **openedSessionFile** static field:

	`static TCHAR *openedSessionFile = null; // the opened session file name`

2. replace in _src/Parameters.cpp/NppParameters::loadSession()_ method:
from:
	```
	if (loadOkay)
		loadOkay = getSessionFromXmlTree(pXmlSessionDocument, &session);
	```
	to:
	```
	if (loadOkay)
	{
		loadOkay = getSessionFromXmlTree(pXmlSessionDocument, &session);
		if (loadOkay)
		_tcscpy(NppParameters::openedSessionFile, sessionFileName); // store the opened session file name for saving by close
	}
	```
3. replace in _src/NppBigSwitch.cpp/Notepad_plus::process()_ method in case _NPPM_INTERNAL_SAVECURRENTSESSION_:
from:

	`nppParam->writeSession(currentSession);`

	to:

	`nppParam->writeSession(currentSession, NppParameters::openedSessionFile);`

4. replace in _src/NppBigSwitch.cpp/Notepad_plus::process()_ method in case _WM_QUERYENDSESSION_ and _WM_CLOSE_:
from:
	```
	//
	// saving session.xml
	//
	if (nppgui._rememberLastSession && !nppgui._isCmdlineNosessionActivated)
		saveSession(currentSession);
	```
	to:
	```
	//
	// saving session.xml
	//
	if (nppgui._rememberLastSession && !nppgui._isCmdlineNosessionActivated)
	{
		if (NppParameters::openedSessionFile)
		{
			pNppParam->writeSession(currentSession, NppParameters::openedSessionFile); // if this opened session, then write this
		}
		else
		{
			saveSession(currentSession); // write default...
		}
	}
	```

**Comment by ThomasHeinrichSchmidt** [comment]
@l-aloha have you actually tried your changes? Maybe they are good for a pull request.

**Comment by noamshan** [comment]
+1 any news here? looking for the same feature

**Comment by ThomasHeinrichSchmidt** [comment]
Never had a feedback, don't know how they assign prorities.

**Comment by ThomasHeinrichSchmidt** [comment]
Never had a feedback, don't know how they assign proriti

**Comment by YakovL** [comment]
I'd say, interval autosaving of a session will be even nicer: for instance, if session is autosaved each minute, when Windows reboots due to some update or bluescreen, the session will survive too.

Does anyone know how to implement this via a plugin/macro/script? I'm not familiar with n++ customizing yet.

**Comment by ZenTurnip** [comment]
+1 for some well-thought version of this. I suggest this is one that should not alter current default behavior.

**Comment by donho** [comment]
I'll see what I can do about it, but I promise nothing.

**Comment by ThomasHeinrichSchmidt** [comment]
We are looking forward to it, anyways.

**Comment by donho** [comment]
Just checked session file loading behaviour in order to implement this feature,
here is the current session file loading behaviour:
The opened files are not closed before loading all files saved in a session. That will make session auto-saving inconsistent:
Let's say "num.session" contains 1.txt, 2.txt & 3.txt. And "alpha.session" contains a.txt, b.txt & c.txt.
If "num" session is opened (so 1.txt, 2.txt & 3.txt are opened in Notepad++), then user opened "alpha" session -  a.txt, b.txt & c.txt are added in Notepad++. Now we have a new session: a.txt, b.txt, c.txt,1.txt, 2.txt & 3.txt. This new session should save as "num.session" automatically or as "alpha.session" or both?
The automatic save will bring the confusion, even bugs.
The current unnamed session will always be saved automatically for next Notepad++ startup. Please use it instead.

**Comment by ThomasHeinrichSchmidt** [comment]
The behavior you describe ("opened files are not closed before loading all files saved in a session") should be handled as follows:
1. If no files are already open (e.g. when you double click a session file) ==>  open files from session as usual. This is probably 99% of the cases when you are working with session files: double click a session, work with the files, close down N++, work on some other things, double click the next session file. Here it is so important that the (previous) session file automatically receives the latest changes.
2. If files are already open when opening a new session: ==> Then you should ask, if the already open files should stay open and become part of the newly opened session or if they will be closed (and their session updated if any) before opening the files of the new session.

That's all there is to it.

**Comment by ZenTurnip** [comment]
> Just checked session file loading behaviour... ...This new session should save as "num.session" automatically or as "alpha.session" or both?

Ah! I open sessions in a new instance (see Multi-instance settings). I would love the autosave because each session is like a separate work space. My setting keeps each session discreet. 

- Do this feature, but only if that setting is on?
- This feature surely must be optional (and not default). Make the two settings exclusive of each other? The two could even present nicely in the one Multi-instance settings section.

**Comment by ZenTurnip** [comment]
> The behavior you describe ("opened files are not closed before loading all files saved in a session") should be handled as follows:
> ...
> 2. If files are already open when opening a new session: ==> Then you should ask, if the already open files should stay open and become part of the newly opened session or if they will be closed (and their session updated if any) before opening the files of the new session.

I don't think its that simple. Sessions provide many different, creative options for managing the user's space, and your binary choice could impact some of those patterns negatively.

Actually, I think you might be treating the session concept more like the instances concept; see my post just previous.

**Comment by donho** [comment]
OK, I'll add an option for saving automatically.

**Comment by ZenTurnip** [comment]
@donho, Thanks. I will enjoy it, and it will simplify my work---in a small way, but every single day.

I aspire to become a collaborator and contribute to the effort. "Aspire" in the sense of get through the current work load. I'm a 25 year veteran and don't need to aspire to the skills.

**Comment by donho** [comment]
Implemented in PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10935
Please let me know if it's what you expected.

**Comment by donho** [comment]
![image](https://user-images.githubusercontent.com/90293/147140681-a1ca00f7-dc24-4b70-8148-979b46201181.png)

**Comment by donho** [comment]
Binaries for testing:
32-bit:
https://ci.appveyor.com/api/buildjobs/wendbbowa88h2ek7/artifacts/Notepad%2B%2B.Win32.Release.exe
64-bit:
https://ci.appveyor.com/api/buildjobs/xig7t54ccnpy4bky/artifacts/Notepad%2B%2B.x64.Release.exe

**Comment by donho** [comment]
I personally don't like this feature due to its inconsistency. If no one cares about this feature and test it I prefer to not implement it.
So please test the binaries mentioned above. With the absence of feed in 1 day back this feature request will be closed.

**Comment by ZenTurnip** [comment]
I intend to test this. I think your timeline might be a little sharp for a holiday.

**Comment by YakovL** [comment]
@donho hooray! This is awesome, very helpful indeed, thanks! Can you predict if this session saving will be applied when Windows forcefully updates itself and reboots? Would be even more helpful; I can report back when such case tooks place again (those are not very often, approximately once a month, but quite painful/annoying).

**Comment by donho** [comment]
> I personally don't like this feature due to its inconsistency. If no one cares about this feature and test it I prefer to not include it.
So please test the binaries mentioned above. With the absence of feedback in 1 day this feature request will be closed.

After some iteration, the new behaviour is more consistent - saving session on exit is effected only when the option "Open session in a new instance" is enabled, and there's no other option needed to enable this behaviour.

No holidays for me so I will merge it and continue on the next bug to fix - it takes me too much time already this task.

> Can you predict if this session saving will be applied when Windows forcefully updates itself and reboots (hence closes all the apps)?

I didn't test it, but I'm pretty sure the session will be saved normally.

**Comment by ThomasHeinrichSchmidt** [comment]
32-bit binary for testing https://ci.appveyor.com/api/buildjobs/wendbbowa88h2ek7/artifacts/Notepad%2B%2B.Win32.Release.exe had 11 findings on [totalvirus.com](https://www.virustotal.com/gui/file/688ee99056a865a0e2b013262b77ea6f03264c8b3df41f6e64ae0ad5d7190dd5?nocache=1)
![Notepad++](https://user-images.githubusercontent.com/8068047/147388567-3cd5b68b-d7b9-47a0-a004-bd70bcfb7348.jpg)

**Comment by YakovL** [comment]
@donho this is kinda confusing: today I've finally found where to set this on in 8.2.1 and found that currently settings complicate things:

1. the desired option is switched on when "only sessions are opened in new window" (I'm translating back from Russian, presumably it reads "Open session in a new instance" as you mentioned)
2. it is ok (and helpful) that a session is always opened in a new window
3. it is not ok that when I'm trying to open a file notepad++ (from Windows Explorer, both with "Open with .." and "Open in Notepadd++") it is attached to an open session instead of getting opened in a new window
4. by the way, I'm able to reopen it in a new window via drag&drop, but that's awkward (and I hope that won't hurt the session to which the file was initially attached)

Is there a reason why the "open session in a new window" option is combined with the "don't open new files in a new window" option? If not, I'll probably create a separate issue.

**Comment by ThomasHeinrichSchmidt** [comment]
I've installed and used 8.2.1 and it works exactly as I was expecting. I've selected 
`Settings / Preferences / Multi-Instance & Date: ◉ Open session in a new instance (and save session automatically on exit)`

- Now, when I open (double click) a session file the session is opened in a new N++ window. On exit every changes I've done to the session, e.g. opening other files, is automatically saved. ✔
- When I attempt to "Edit with Notepad++" or "Open with ... Notepad++" the newly opened file will be added to the N++ window that last had focus. For my way of working this is exactly what I'm expecting. Most of the time I only have one session/window open anyway and I'm working on this one session. So when I open another file it's related to this session and therefor I want it to be opened (and later saved) in my current session. ✔
- If I wanted to open an unrelated file in a new / other N++ window (not related to my current session) I would need to start or switch to another N++ window. Then "Edit with Notepad++" or "Open with ... Notepad++" on the unrelated file would open the file in the N++ window that last had focus.  For me this is OK as it does not happen very often that I need to open an unrelated file while I'm working on one session. ✔

I'm happy with the new feature, it saves me time and headache when working with sessions. 
![Thumbs UP](https://user-images.githubusercontent.com/8068047/153421597-960d8bdd-c475-478a-8b37-fd0e3bcbe13a.jpg)
