### ISSUE TITLE
[feature] Add support for ligatures

### ISSUE THREAD

**Issue by raidenfreeman** [notepad-plus-plus/notepad-plus-plus#1651]
Add support for ligatures like in those fonts:
- [Fira Code](https://github.com/tonsky/FiraCode)
- [Hasklig](https://github.com/i-tu/Hasklig)
- [Monoid](https://github.com/larsenwork/monoid)

**Comment by MetaChuh** [comment]
we are closing this issue due to limited demands of such implementation from the notepad++ community.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by glen-84** [comment]
> we are closing this issue due to limited demands

Based on what information? It is literally the 2nd-most wanted feature with 13 votes here and 12 votes in #2287.

😕
