### ISSUE TITLE
[Feature requests] for new version ! Please consider them for real !!

### ISSUE THREAD

**Issue by sng843ndf86nd8** [notepad-plus-plus/notepad-plus-plus#1682]
Please come on ~

#1, Automated deletetion of Auto-Completed half of parenthesis (brackets, ...), when user manually deletes it's first half of it. 

#2, Deletion of transformed Tabbed whitespaces by only one keyboard hit of Backspace/Delete. By 'transfered' I mean Tab Settings in Preferences - for example four spaces for python. If one tab press, will do four normal spaces, would be useful to let user delete it by one press, not four times (Backspace/Delete).

#3, Resetting key bindings/keyboard shortcuts to default from GUI. Not by some manual magic manipulation within files.

#4, Exclude numbers from Auto-Completion. Exclude user specific strings from Auto-Completion per file or default for anything opened.

#5, Enlarge Find and replace window (ctrl + h) for more comfortable multi lines operating. This window has in right down corner an enlarge mark, but it does not work (windows 7 ultimate 32 bit).
And maybe bug: When occurs Tab whitespace from very beginning of the line pasted into text fields, it is longer than same Tab whispace in middle of that text field. Try select two lines in code, where both start tabbed and paste it into window's text fields. Second tab will be shorter. 

#6, Remembering correctly default folder. Ability to set any default folder for something (for example for opening sesssion). File > Load Session ...
It opens me in some other folder every time (maybe not in same program load, but other day).
NP++ does not remember any folder for anything (it feels to me like this).

I'm looking every day web with high expectations for new version. If developers won't listen for those essential needs I wrote above, users will migrate to other projects !
Those -seems dead projects, are back to life:
http://www.sublimetext.com/3dev
http://lighttable.com/blog/
And Atom is doing great progress: http://blog.atom.io/

When np++ users will have to wait long months for basic and good features, project will go down.
Devs if you reading this, please do something.

Thank you for understanding

**Comment by dail8859** [comment]
Please do not repost issues you have already posted. #1507 #1401

**Comment by sng843ndf86nd8** [comment]
it's not 100 % same and i better formulated !!!

**Comment by leewz** [comment]
For the sake of organization, it's better to have one, and only one, issue for each unrelated request. Unlike a forum, all open issues are considered to need attention, and duplicate issues are closed. An issue tracker also doesn't sort by new responses, so bumping does nothing. If you have more to add to an existing issue, make a reply to the existing issue.

Please understand that this is a volunteer project, and devs will work on whatever feature they are interested in making. There's not much we can do about it. They make no money from this, so there is no incentive to keep users. They're making it for themselves, and sharing the result with everyone else.

----

Do not use `#1` for a list item, since that causes the Github system to link to the issue with that number. Instead, use `1.` at the start of the line, and it will be a list item.

1. Item 1.
2. Item 2.
3. Item 3.

----

Here are some workarounds for your requests.

1. How about Ctrl+Z to undo?

2. Press Ctrl+Z to undo, or press Shift+Tab to unindent.

3. Do you mean you can't undo a deleted shortcut? I would agree that this is an issue. I just made issue #1686 for it.

4. Huh? Autocomplete is trying to complete your numbers? Well, you can tune the settings, at least. You can change both the minimum characters and what it should complete: words, functions, or both. What language are you having issues on?

5. Have you tried the TextFX plugin's Ctrl+R search window? It has multi-line text fields.
    The tab size thing sounds like a bug report waiting to happen.

6. Some people like having the sessions saved in their current work folder, I'm guessing. There's a Default Directory setting, though.

**Comment by dail8859** [comment]
Moving discussion to #2090
