### ISSUE TITLE
>>> UDL Ideas <<<

### ISSUE THREAD

**Issue by Craftist** [notepad-plus-plus/notepad-plus-plus#1713]
# Hello! There's my ideas for UDL:
## 1. REGEX keywords:

![image](http://i.imgur.com/7T6GBWI.png)
If Regex checkbox was checked, UDL will parse items below like Regular Expressions.
For example:
This
![image](https://cloud.githubusercontent.com/assets/13656215/14281790/c3856eea-fb43-11e5-84d1-63ddba216f7e.png)
means that in your language will higlight all of english words that are 8 symbols length (only small) and words look, good and super in all cases.
Regexes must be delimited by new line.
## 2. New "styler" window:

![image](https://cloud.githubusercontent.com/assets/13656215/14282002/f692e028-fb44-11e5-97e9-49782f676322.png)
Changed: color shape -> color text field with button that'll open standard color dialog
## 3. New "comment" section:

![image](https://cloud.githubusercontent.com/assets/13656215/14282233/2bb6bd6e-fb46-11e5-9964-fc8ea641b316.png)
Added: documentation comment (have higher priority than standard multiline comment)
Changed: decimal separator radiobox -> decimal separator text field
## 4. New "Folder & Default" section:

![image](https://cloud.githubusercontent.com/assets/13656215/14282332/920b89e6-fb46-11e5-9f17-b575104d6de0.png)
Added: start highlighting & stop highlighting text fields:
means the code part which to highlight.
For example PHP: Notepad++ highlights only code in <? and ?> tags.
<? is a start highlighting and ?> is a stop highlighting.
Code not in this frame will be black (or like in "Default style")

@donho Please look at it.
For russians (I don't speak English very well):
# Привет! Это мои идеи для UDL:
## 1. Ключевые слова, парсящиеся через регулярку:

<Картинку смотрите выше>
Если флажок REGEX отмечен, то будут подсвечиваться не просто ключевые слова, а регулярки. Удобно же :D
К примеру:
Это
<Картинку смотрите выше>
значит, что в моем языке будут подсвечиваться все слова, написанные на латинице и длиной в 8 символов (только с маленького регистра) и слова look, good и super в любом регистре.
Регулярки должны разделяться новой строкой.
## 2. Новое окно "стиль":

<Картинку смотрите выше>
Изменено: фигура с цветом -> однострочное поле с цветом, а так же кнопкой, открывающей обычный диалог цвета
## 3. Новое окно "комментарий":

<Картинку смотрите выше>
Добавлено: комментарий документации (имеет приоритет выше, чем обычный комментарий)
Изменено: разделитель дробных чисел в виде переключателей -> разделитель дробных чисел в виде однострочного поля
## 4. Новое окно "Стандартный":

<Картинку смотрите выше>
Добавлено: поля "Начало подсветки" и "Конец подсветки".
Они ограничивают ту часть, которая будет подсвечиваться.
Приведу пример: PHP. В Notepad++ при выбранном языке PHP будет подсвечиваться код только внутри тегов <? и ?>.
<? - это "Начало подсветки", а ?> - это "Конец подсветки".
Код вне этих тегов будет подсвечен черным (или выбранным в "Стиль по-умолчанию")
Прошу перевести мой кривой английский, или редактированием поста, или в комментариях.

**Comment by TonyGravagno** [comment]
+1 for Regex in UDL. @JamesBMcCarthy posted a similar issue in #3257.

**Comment by dinkumoil** [comment]
I would appreciate this feature too. Already missed it.

**Comment by utybo** [comment]
Regex in UDL would be fantastic!

**Comment by FatalBulletHit** [comment]
I second this, are there any plans on updating the UDL? Maybe even in the near future?

**Comment by azjio** [comment]
Add support for regular expressions. Add a tab with multiple fields. Add the “Select group” flag to highlight only the group in the found. Then the old will not break. If it brakes, people will not use it themselves.

Add, to delimiters, so that you can specify the beginning of the line, for example \n"keyword" or ^keyword. Add it so that you can specify “keyword1 keyword2”, and also " ", so if the end is not found, it would end on the first blank, not the end of the line.
https://notepad-plus-plus.org/community/topic/15874/feature-request-udl-regular-expressions

**Comment by MetaChuh** [comment]
@Craftist 

many thanks for your udl enhancement ideas.

unfortunately we currently do not have devs with extensive udl know-how, who are willing and enjoying to code at the udl part.

our sincere apologies for that.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by dinkumoil** [comment]
@MetaChuh 

IMHO the current lack of qualified developers is not a valid reason for closing this issue. It is a legitimate request and the feature would be very useful. There are a lot of other issues in this archive which are better candidates for closing them, e.g. all these "The UI design of Notepad++ is bad/ugly/oldfashioned".

**Comment by mbl123** [comment]
Syntax highlighting is a major feature in a text editor like NP++. It's such a shame the UDL editor seems targeted to novice users, when to my knowledge, the program is mostly used by software programmers who would likely _not_ shy away from advanced RegEx expressions.
Please reconsider implementing RegEx in UDL.

**Comment by darthglowball** [comment]
Please, I need regex! UDL is so limited. I am making a highlighter for Javascript within HTML. Just trying to do the most basic patterns, such as coloring method names of a javascript object or class, is a nightmare or impossible (atleast I haven't figured it out after 10 hours..). I'm using the delimiter tab. If I could just enter: start at char 0 of line, look for first `[a-zA-Z_]`, then start coloring until not `[a-zA-Z_]` (or even better, find first \w (word)), and then a lookahead conditional: `(` with stuff inbetween, ending with `){`. (I omitted a few whitespace tokens, which would be useful to have). So for example, the text to be colored would be "my_method" of `my_method(arg1, arg2){`. Regex could do this easily. Of course javascript can be formatted differently and I would need a more complex regex, but you get the idea. Also, generally, I end up using crap like a typed out alphabet ((a b c d e f g h i j k l m n o p q r s t u v w x y z )), to detect random words next to delimiters (well, a limited hack that detects a letter, and then I assume that the rest. For example, I made the a tag styler, which needs to account for when nesting javascript in HTML, to let the UDL parser ignore "<" and ">" in javascript so that it isn't considered part of HTML tags, by doing: Begin: `((<a <b <c <d <e <f <g <h <i <j <k <l <m <n <o <p <q <r <s <t <u <v <w <x <y <z </a </b </c </d </e </f </g </h </i </j </k </l </m </n </o </p </q </r </s </t </u </v </w </x </y </z))` End: `>`. This is: a) annoyingly long, and b) it is a hack that breaks down when in javascript there is no space between a "<" and an expression, 3) this doesn't even color the HTML tag type or attributes, for which I would need lookahead and "one or more chars" functionality (so telling the parser: "find < or </, but color the word next to it (the type), and give < and > its own color, but possibly different from javascript's <").
