### ISSUE TITLE
Allow to search for not commented out stuff

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#1763]
Hi, I just has the following situation: I want to test a script, and for that I need to comment out every line which contains a specific word, so I used search. It would be great, if there is a search option that allows to search for only things that are currently commented out or not, depending on the currently highlight.

**Comment by chcg** [comment]
This could be probably achieved by some regex magic, see e.g. https://stackoverflow.com/questions/5989315/regex-for-match-replacing-javascript-comments-both-multiline-and-inline.

You could check out:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
