### ISSUE TITLE
Fullscreen and Post-It modes from Maximized overwrite normal window size

### ISSUE THREAD

**Issue by leewz** [notepad-plus-plus/notepad-plus-plus#1780]
Reproduction:
1. Have N++ in windowed mode, so that you can see things behind it.
2. Maximize it.
3. Turn on Fullscreen (F11) or Post-It (F12).
4. Turn it off again. (Same key.)
5. Unmaximize N++.

Result: N++'s windowed mode now covers the whole screen.

Somehow, Post-It/Fullscreen overwrite the "windowed mode" position and sizes.
- Fullscreen: Makes it screen size (going past taskbar).
- Post-It: Makes it maximized window size (not going past taskbar).

Maximized Post-It doesn't even make sense. Post-It mode is supposed to be used over other windows. Maybe it should unmaximize before entering Post-It mode.

**Comment by Kerubis** [comment]
If im not mistaken FullScreen(F11) does exactly what it should do, it is the same in every program.
A complete monitor is filled with notepad++

Post-It(F12) in maximized screen is very useful because it is like fullscreen without overlapping with the taskbar, at the moment it is buggy, as you and I mentioned

**Comment by leewz** [comment]
I am talking about a side effect of using Fullscreen and Post-It mode.

Try out the steps: start in windowed mode, maximize, Fullscreen,
unFullscreen, unmaximize.

It should give you the original window size and position. Instead, it is a
fully-stretched window.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by DMI-1407** [comment]
I was able to reproduce the bug but i dont know if its related to windows, npp or vlc.
To reproduce the bug follow the instructions on the picture i attached, the screenshots are read from left to right then from top to bottom.
(i dont know if its because of some framework or so...)

### Debug Information
Notepad++ v8.1.2   (32-bit)
Build time : Jul 16 2021 - 01:56:21
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll JSLintNpp.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll 

VLC media player: 3.0.16 Vetinari
My Desktop has 3 Screens (each 1 left & right from my mainscreen), here i just use the mainscreen.

![nppVLCbug](https://user-images.githubusercontent.com/53574099/126407181-43a6a97c-de60-4e6a-b9c3-533a623c21ca.png)
