### ISSUE TITLE
Allow drag & drop in Administrator mode

### ISSUE THREAD

**Issue by AireAyquaza** [notepad-plus-plus/notepad-plus-plus#1782]
Hey ! I've an issue for you, when I open notepad++ in administrator mode, it's impossible to me to drag & drop file into notepad++. Drag & drop when not in administrator mode work nice.

**Comment by ixperiencenl** [comment]
Same problem here. In Administrator mode, it's not possible for me to save to network locations (they aren't visible in the dialog box) and I can't open files from the context menu in Explorer either. Closing NP++ and opening it in normal mode makes everything work again....

**Comment by dail8859** [comment]
At least for the drag-and-drop this is due to Windows, not Notepad++. Windows doesn't allow non-elevated processes to send messages to elevated processes. 

For reference see https://blogs.msdn.microsoft.com/patricka/2010/01/28/q-why-doesnt-drag-and-drop-work-when-my-application-is-running-elevated-a-mandatory-integrity-control-and-uipi/

So unfortunately it would be nice to have this work, there doesn't seem to be a safe way of allowing it.

**Comment by ixperiencenl** [comment]
Ah that's a shame (for Microsoft of course). But it leaves me questioning why it _did_ work in older versions. Any idea to that?
