### ISSUE TITLE
Give Notepad++ Default File Associations

### ISSUE THREAD

**Issue by robotortoise** [notepad-plus-plus/notepad-plus-plus#1786]
Hi,

Currently, Notepad++ doesn't, by default, show up when you go to "default applications" in the control panel in Windows, meaning you can't set it as the default text editor for most common files. 

I think this  is also the reason why NP++ doesn't show up on the "Open With" list.

It'd be pretty awesome if you guys could maybe implement NP++ as a default application sometime!

**Comment by tobsimon** [comment]
The required API calls are described here: [https://msdn.microsoft.com/en-us/library/windows/desktop/cc144154(v=vs.85).aspx](url)

I'm not currently sure if the installer asks, which files should be associated. But it is possible to set file associations in Notepad++ under Settings > Preferences > File Association or with Windows methods, by specifying the executable in the Open With dialog.

**Comment by robotortoise** [comment]
For some reason, Notepad itself doesn't show up in the "open with" dialogue by default. You have to specify the .exe. It's....annoying.

**Comment by brendankehoe** [comment]
When you specify the exe that should be used to open a file once it is added to the list. For example you could choose notepad++.exe to open .txt files by navigating to the location of notepad++.exe. You can choose Notepad++ from the list if you want to choose another file extension next like .log or anything else.

What I find ridiculous is the file association within Notepad++. If you want to associate 1 or a few file types it's ok but if you want to associate Notepad++ with all file types in the list it is awkward because of the categories.

Would it be difficult to add an associate all option in the settings? I also don't see that option during the install process either.

**Comment by robotortoise** [comment]
> Would it be difficult to add an associate all option in the settings?

That's exactly what integrating it into the Windows file association would do, though. There's a "associate with all possible types" button.

And I don't think it's that difficult in the scheme of things. I think it's the matter of setting a registry value. Not that I have room to talk and claim something is "easy" when I can't even do the commit myself...

**Comment by roimvargas** [comment]
I was facing same problem here. In my case I upgraded Notepad++ from 32-bits to 64-bits.
More specifically I uninstalled version 5.9.4 32-bits and installed version 7.5.4 64-bits.
For some reason there was a record in Windows registry that was still pointing to the old 32-bits installation path.

The registry key HKEY_CURRENT_USER/software/classes/applications/notepad++.exe/shell/open/command/(Default) had the value: "C:\Program Files **(x86)**\Notepad++\notepad++.exe" "%1"

After changing the value to point to the right 64-bits installation path ("C:\Program Files\Notepad++\notepad++.exe" "%1"), the file association started to work again.
The "Notepad++" application also started to show in the context menu "Open With..." list and in the screen that shows after selection "Choose default program..." option.

**Comment by ofcgk9** [comment]
I searched the GitHub bug reports for my problem and I found, among other posts, this post.

The posts that I found either make no reference to operating system or reference Windows 10, but the problem is not limited to Windows 10.

I have Notepad++ installed on a Dell E6520 with 64 bit Windows 7 Pro with i5 processor, 8 GB RAM.  Here is the "debug" info:

Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

I have 2 problems and I believe problem 2 is related to problem 1:

1.  I cannot set Notepad++ as the default .txt application.  Here is what I have tried:

a. Right click on .txt file, click on Open With, then on "Choose default program.".  NP++ not displayed, even in other programs. Browse to NP++ .exe file, selection does not work, even with "Always use the selected program to open this kind of file"

b. Control Panel/Set your default programs.  NP++ not displayed, not selectable

c.  Control Panel/Associate a file type . . .  NP++ change program selection does not work

Note:  right click on .txt file and "Edit with Notepad++" works

2.  Recently opened files not displayed when right click on NP++ icon on Task Bar (even after changing the number of files to be displayed).  Recently opened files ARE displayed when File in menu is clicked on.

This bug report, now over 3 years old, is still open.  I am not a programmer, so I can't help fix it, but I definitely would like to see it fixed and an update to NP++ released, since I am not comfortable with editing the Registry.

Is there any schedule for this problem to be fixed?  For a program update with fix to be released?

**Comment by MetaChuh** [comment]
@ofcgk9  

our apologies.
file association has already been integrated into notepad++, but this old issue was not closed yet.

guide to set .txt or other file associations for notepad++:

* close notepad++ if it is open

* right click on your notepad++ icon and choose "run as administrator"
(make sure you see `[Administrator]` at the top bar of your notepad++ window (see screenshot)

* go to `settings > preferences > file association` and make sure your needed extensions, like .txt are visible at the registered extensions panel (last panel on the right) as seen on this screenshot:

![Imgur](https://i.imgur.com/m0St1R0.png)

* hit close and exit notepad++

* now reopen notepad++ normally, and go to `settings > preferences > file association` again, and make sure your needed extensions are also visible for the standard user account.

* then exit notepad++ again

* right click on e.g. any .txt file and choose `open with > choose other app` and select notepad++ from this list.

* select `always use this app to open .txt files`and hit ok.

* close notepad++ again and retry opening your .txt file by double clicking on it.

best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by ofcgk9** [comment]
This DID NOT WORK!

NP++ does not appear in the list of Open With programs (neither the recommended nor other programs).  When I browse to the NP++ .exe file and try to "open" (or double click on it) to select it, the selection fails, even when the "Always use the selected program . . . " is checked.

NP++ still does not appear in the list of Control Pnel/Set your default programs list, nor does the Control Panel/Associate a file type . . . work

After following your instructions when I double click on .txt file it still opens in Microsoft Notepad.

**Comment by ofcgk9** [comment]
I forgot to mention that the list of file extensions displayed in the far right panel of NP++ under Settings/Preferences/File Association is:

css, ini,java, js, log, php, txt, xml

Unlike your screen shot (which was not attached to your message), the middle panel in my installation is empty and the add/delete buttons are grayed out.

**Comment by ofcgk9** [comment]
Silence in NOT appropriate here.

Despite "MetaChuh's" assertion, the issue is NOT resolved (as I demonstrated - MetaChuh's "solution" fails) and this thread is should NOT have been closed.

Issue #1786 needs to be reopened and someone needs to be working on this problem.  As I said in my original post, I am not a programmer, so I am unable to help (I would help if I could).

**Comment by sasumner** [comment]
>Silence in (sic) NOT appropriate here.

Wow, seems someone's got a false sense of entitlement going on...

**Comment by MetaChuh** [comment]
@ofcgk9 

there is no reproducible problem with notepad++ file associations, if you have read, understood, and followed the guide from above, or any other guide for notepad++ file associations you can find around the web.

my apologies for assuming, that silence would eventually help you re-read, absorb, and apply the information you have been given.

please also read the general notes again, to learn how to visit our user community forum, if you need help setting up your pc, as this issue tracker is for source code related purposes only.

many thanks and best regards.

**Comment by ofcgk9** [comment]
Note to MetaChuh

Fact #1:  Just because I am not a programmer does NOT mean I am NOT technically knowledgeable - about other aspects of computers and other technical subjects.

Fact 2:  There are a number of competing products available, so I found one, downloaded, installed, and tested it.  It does everything you claim NP++ does but does not.  It has more features, better features, and better support.  In today's world, NP++ is out of date.

Conclusion #1:  Since the other program works perfectly well, the problem is with NP++

Conclusion #2:  Under the set of conditions I described to you in detail, NP++ does indeed, have a file associations problem (a source code problem).

Conclusion #3:  You claim you can't reproduce the problem.  That means that instead of doing more research on the failure under the conditions I described to you to help solve the problem you decided you were dealing with an incompetent user and were therefore free to insult the user.

Conclusion #4:  Your technical arrogance is unacceptable.  It can only be classified as incompetence.  If you were in a normal working environment you would be terminated for insulting the customer in the way  you have.

You should not be surprised to learn that I have uninstalled NP++ from my computer, and I will tell all of many my contacts not to use the program.

**Comment by sasumner** [comment]
First, I must admit, I have never used the "file associations" feature of Notepad++.  I don't feel a compelling need to open, e.g. .txt files by double clicking them in Explorer.  Drag and drop is just simply a good enough thing for me.  However, I tried Meta Chuh's instructions for setting this up.  

(Actually had no idea that Administrator mode was necessary, and had some fun on my "managed" PC trying to get N++ to run in Admin mode -- rightclick Run as Admin didn't work because it wanted a Admin username/password which I don't have...finally I got the idea to get a cmd.exe Admin prompt and run notepad++.exe that way, and that worked)

Anyway Meta Chuh's instructions were perfectly flawless and worked awesomely.  Thanks Meta Chuh for great data and support, as you provide so many times.  (Of course this is for something I don't need)

**Comment by titou10titou10** [comment]
The fix given by @roimvargas did the trick for me. Thx    
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1786#issuecomment-381385109

**Comment by natekinnee** [comment]
@ofcgk9 In spite of the aforementioned entitlement you displayed, and in spite of the fact that you have already moved onto another program, I wanted to point out that I faced the same issue you did in not being able to select NPP in the Windows file association popup, but I found a solution in the post immediate above your initial post: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1786#issuecomment-381385109
