### ISSUE TITLE
Opening big .sql file render notepad++ nonresponsive

### ISSUE THREAD

**Issue by Snorvarg** [notepad-plus-plus/notepad-plus-plus#1841]
Hi, 
I occasionally use notepad++ to open and edit big .sql files (currently 216 mb) because it has always worked. Today though, notepad++  stopped responding completely. 

Killing notepad++ and restarting it does not help, it tries to reopen the file. 
To resolve, I had to kill notepad++, rename the file, then reopen notepad++.

This has been working well in previous versions of notepad++, with a few seconds delay when opening the file. I am not sure which version though. It might have been two months ago I did this though. (I always update notepad++ to latest version when it ask me)

I don't have any plugins more than the default ones. 

I can see that notepad++ starts coloring the sql-tags in the file, so I guess it gets occupied with doing this for the entire file. 

Anything I can do to stop notepad++ from doing whatever it is trying to do with the file? Like for example open it in a pure text-mode.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

preferably use the 64 bit version due to your file size.

please also make sure that you remove the dspellcheck plugin, if above does not provide the desired solution.

if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
