### ISSUE TITLE
not on Mac

### ISSUE THREAD

**Issue by 1NEGROUP** [notepad-plus-plus/notepad-plus-plus#1859]
Is there a Way we could get this on mac?

**Comment by jtrent238** [comment]
It can be ported.

**Comment by dimohamdy** [comment]
@jtrent238  how ?

**Comment by milipili** [comment]
I am closing the issue not because we don't want the feature but because we're trying to clean up a bit all those those issues. But you're are free to continue to comment on this issue.

To answer to your questions (same for linux) it requires a complete rewrite of the interface code, which is not that simple. But anyway just rewriting the C++ code would be inefficient, a plugin approach would be far better (and not native C plugins), to make n++ more flexible to user specific workflow. This is our direction right now and we will try to be transparent. We will see with Don what we can do about that.
