### ISSUE TITLE
Monitoring conflict with state autodetection of the file?

### ISSUE THREAD

**Issue by TroudhuK** [notepad-plus-plus/notepad-plus-plus#1884]
I was very happy about this new monitoring feature, because I use a lot of log files and need to validate the reload when changed thousands times a day.

But it doesn't work well enough to me: a monitored file, when I minimize the window then maximize it again, ask for reloading or say it is deleted (because it was recreated). I don't want to disable popups about autodetection because sometimes (for non-monitored files) I want to reject the modification.

So: as the title said, there is a conflict, a monitored files shouldn't be watched by the modification autodetection anymore, and if the file is removed, it should clean the content (maybe gray it) and wait for recreation.

**Comment by cwacha** [comment]
Monitoring (tail -f) seems to work very well for some files. But on others the "reload message" keeps popping up. It seems that monitoring keeps an eye on the file handle and re-reads contents as it gets added to the file. This works nicely when an app opens a file and then keeps logging to it. 

It does not seem to work for applications that close the logfile between log writes. Unfortunately this is quite a normal behavior for logging applications.

The following behavior seems to cause issues (I can only suspect since I cannot test this here...)

monitoring (tail -f) does not work when the applications does the following:


open
write
close
open
write
close

each open/write causes notepad to show the popup message to "Reload" message (This file was modified by another program. Do you want to reload it?)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
