### ISSUE TITLE
Copy result of find onto other tab

### ISSUE THREAD

**Issue by trivalik** [notepad-plus-plus/notepad-plus-plus#1976]
For Logfile analysis it would be nice to shrink the log file by searching. The best would be to copy the result to a complete new file.
Furthermore for analysis it would be good to copy only line which are not maching the search term, so a checkbox to enable this would be good.

**Comment by dail8859** [comment]
Use the LineFilter2 plugin. Does exactly what you are asking for.

**Comment by sasumner** [comment]
>The best would be to copy the result to a complete new file.

If you are talking about match-contents and not whole-lines, I completely agree that there should be a way to have it selected so it is manipulatable (e.g. for a copy operation).  Otherwise, I think what you are requesting is already possible via Mark searching and using Bookmarks with their operations.
