### ISSUE TITLE
Convert to ANSI

### ISSUE THREAD

**Issue by ugplus** [notepad-plus-plus/notepad-plus-plus#2017]
I have a file with roughly 170.000 lines encoded in UTF-8-BOM

When I use the function "Convert to ANSI" the file goes blank.

The problem is fixed if I downgrade to version 6.8.8 of NP++, any higher version results in the error.

EDIT: The error occured in 6.8.8 also, I'm on 6.3 now at it seems fine, not sure whats going on.

**Comment by dail8859** [comment]
Try disabling your plugins. If that doesn't work try turning off Periodic Backups.

**Comment by ugplus** [comment]
I installed the latest version again. Removed all the plugins (only had the default ones), and disabled periodic backups. No difference, still the same bug.

**Comment by Gabr-F** [comment]
I found out what's likely the problem, it exists since the first version (4.8 - 092235e).

It's due to the fact that the feature is implemented by using the clipboard: all the file's contents are cut to the clipboard, the encoding is changed and then a paste is attempted.

This approach is crazy, there's an high chance that the final paste doesn't succeed, or that the clipboard's contents have been changed since the cut.

The "enhancement" of emptying the undo buffer after the conversion attempt (dd1dd75) is the icing on the cake.

I found out that the feature fails almost always on my system when I have [this clipboard utility](https://github.com/aviaryan/Clipjump) enabled. Disabling it makes the feature normally work.

It's likely that other clipboard utilities interfere similarly.

The fault is not on the part of the clipboard utilities though, it's the approach that's wrong.
There has to be another way to do it.

In the meanwhile, I request that at least the undo emptying thing be removed.
I suppose it was done to avoid showing the step when buffer is empty, before the paste is attempted, but:

1. I'm pretty sure you can avoid that by using an UNDOACTION
2. Seeing that step is a lot less troubling to any user than losing the whole document, in case the paste doesn't succeed
3. It's completely unexpected that the undo history get lost when using this feature, the user might have had something important and unsaved in a previous undo state that he was confident would not get lost by simply doing the conversion. If it's not necessary the undo history should not be cleared, and if it is necessary you must warn and ask for confirmation to the user before proceeding.

Actually the way it's implemented this feature is so dangerous that I think it should be disabled, until it is fixed.

**Comment by Gabr-F** [comment]
Can at least the "bug:low" label be changed?? This is a very serious bug, people can easily lose entire entire documents (few people would make a backup before trying to change the encoding of a file).

It is probably not hard to fix genuinely but as all problems for the users can be quickly neutralised by disabling the feature it should be given a high priority.

At the very least you should remove that undo emptying thing, although it would be safer, more respectful towards the users, to disable the feature entirely until it is completely fixed.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
