### ISSUE TITLE
the utf8 symbol "⇐" can not show correctly on notepad++, it shows a "?" in a box

### ISSUE THREAD

**Issue by longbowape** [notepad-plus-plus/notepad-plus-plus#2084]
the utf-8 symbol "⇐" which likes "<=" can't show on notepad++, my font is consolas and the symbol can show on my IDE and web browser.

**Comment by yzwduck** [comment]
Consolas does not have glyph ⇐ (U+21D0).
Some IDE support font fallback, so they can display the symbol.
But Notepad++(Scintilla technology=SC_TECHNOLOGY_DEFAULT) does not support fallback currently.

**Comment by Kemipso** [comment]
This is a bit late, but you can use font linking to work around the issue, a feature from Microsoft Windows.

Here is Microsoft presentation about it:
https://docs.microsoft.com/en-gb/globalization/input/font-technology#font-linking

As an example, because I wanted to use Inconsolata and get support for Cyrillic characters and symbols, I added the following in my registry:

**Path:**
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink`

**New multi-string, with value name:**
`Inconsolata`

**Value data:** 
```
CONSOLA.TTF,Consolas Regular
SEGOEUISL.TTF,Segoe UI Semilight
MSJH.TTC,Microsoft Jhenghei UI
MSYH.TTC,Microsoft YaHei
MALGUNSL.TTF,Malgun Gothic Semilight
SEGUISYM.TTF,Segoe UI Symbol

```
