### ISSUE TITLE
In 6.9.2, after 'clone to other view', the two views have different font size/spacing

### ISSUE THREAD

**Issue by greiginsydney** [notepad-plus-plus/notepad-plus-plus#2091]
Hi,

I can't see how to address the issue above with any of the View settings so I'm guessing it might be a bug?

I'm running 6.9.2 under Windows 10, and if I clone an existing document to another view, the cloned version fits fewer lines on the screen compared to the original view beside it.

This makes it harder to align the two views, etc.

Here's an example of a full screen, with the middle chopped out to save space:
![np cloneviewsizing](https://cloud.githubusercontent.com/assets/11004787/16899095/879d1610-4c3a-11e6-9c37-20c93eab0323.png)

**Comment by dail8859** [comment]
Make sure you have the zoom set the same for each view.

**Comment by greiginsydney** [comment]
Aha! Yes, that fixes it, thanks. I needed to select the first (initial) instance and reset its zoom.

But shouldn't a "clone" of the first view open at the same zoom level as the one being cloned?

**Comment by dail8859** [comment]
> But shouldn't a "clone" of the first view open at the same zoom level as the one being cloned?

At least the way it is currently a lot of settings can be applied per "view", such as zoom, folding, syntax, etc. I agree at times it can get a bit confusing since there is no clear way to easily see the different settings between the two views. So I don't know if forcing the views to have the same zoom would be a good idea or not as some users may intentionally have different zoom levels set.

**Comment by SinghRajenM** [comment]
@MetaChuh what do you think about this ticket. Shouldn't be it closed?
