### ISSUE TITLE
Add user and password on Proxy Settings

### ISSUE THREAD

**Issue by rafarolo** [notepad-plus-plus/notepad-plus-plus#2101]
Please add `user` and `password` fields on **Proxy Settings** for the enterprise connections can be able to upgrade to the latest versions. Thank you!

**Comment by mtsiakiris** [comment]
In addition to @rafarolo, add a new section on the settings form in order to control proxy settings that the app should use on any request.
It must include everything like proxy address and port, secure proxy address and port, authentication details (username / password) that must be kept locally and encrypted, exclusion hosts and ips list, bypass local.
This is a proper way in order to support network communication (external or internal) for an enterprise network setup.
Thank you.

**Comment by mtsiakiris** [comment]
Any news on this? I submitted new issue on this: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3534
Thanks

**Comment by mtsiakiris** [comment]
![image](https://user-images.githubusercontent.com/10559137/42138851-c2f4343e-7d8c-11e8-9902-4a336f63760e.png)

**Comment by M-GLEICH-MCQUADRAT** [comment]
Hello,

I need this feature immediately.

Actual situation with NPP 7.6.6: The Windows "Proxy Settings" does not support proxy authentication with username and password.  (PSPad is supporting this)

The Windows "Proxy Settings" should get the feature "authentication" (Username and Password).
My Company requests Proxy-authentication necessarily.
Otherwise the following error occurs: "Received HTTP code 407 from proxy after CONNECT"

VERY IMPORTANT: The password should saved encrpted --> NOT plain text

Thanks.

**Comment by donho** [comment]
The authentication should not be part of Notepad++.
This feature won't be implemented.
