### ISSUE TITLE
Plugin download/installation not possible if you have many files open, Notepad++ crashing

### ISSUE THREAD

**Issue by Quinity** [notepad-plus-plus/notepad-plus-plus#2120]
### Description of the Issue
When having opened a lot of files (test case 45-50 files) and installing a plugin through the Plugin Manager, the program crashes after pressing the "install" button (download form is visible).

### Steps to Reproduce the Issue

1.  Open 50 files
2.  Select any installable plugin inside the Plugin Manager
3.  Click install
4. Notepad++ crashes

### Expected Behavior
Plugin installation should start and - if no problems occur - the installation should finish successfully

### Actual Behavior
Notepad++ crashing to Desktop:
Notepad++ has stopped working.

### Debug Information
Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppToolBucket.dll PluginManager.dll 

Installation of plugins working flawlessly when only a few files are opened.

**Comment by dail8859** [comment]
See: https://github.com/bruderstein/nppPluginManager/issues/3

There have been some known problems with the Plugin Manager crashing because it can't download the plugin (e.g. sourceforge being unreachable, proxy issue, etc). This may be unrelated to the number of files open. You might try downloading different plugins or trying again later. I tried opening 50 files and it worked fine for me.

**Comment by Quinity** [comment]
I also thought so in the beginning but the problem only occured if many files were open. 
Well I restarted my computer and suddenly the problem is solved, most likely the problem was related to something else. 
-- issue closed

**Comment by dail8859** [comment]
Glad to hear it is working. If it keeps happening feel free to reopen.
