### ISSUE TITLE
"Save All" button - Should it have a confirm action dialog?

### ISSUE THREAD

**Issue by dhaupin** [notepad-plus-plus/notepad-plus-plus#2124]
### Description of the Issue

The save all button has no confirm, so a mis-click or mis-key will init the save-frenzy. This has undesirable or even dangerous effects if you are in a session with old files, possibly production, possibly in NppFTP....which is exactly what happened recently.
### Steps to Reproduce the Issue
1. Open a session at work, use NppFTP if you like. This session may have lots of old work in tabs. Work on a critical file(s).
2. Go home and work on those files some more via NppFTP using a different PC and session.
3. Come back to work, continue on 1 file, but accidently hit save all, watch as NppFTP overwrites all the old files open in the session, effectively wiping out the work you did at home.
4. Erm....go back home to get the files? I dunno it's just annoying from here on out :)
### Expected Behavior

Exactly what Np++ did. Although some sort of "are you sure you want to save everything in this session" dialog would be very much appreciated.
### Actual Behavior

Np++ did exactly what is expected and normal behavior, it saved everything. This can have undesirable effects if you aren't expecting it.
### Workaround

By using the "customize toolbar" plugin one can remove the icon for save all, reducing mis-clicks. Changing the shortcut to something more complex helps too. But for people who are using stock Np++ and fire off a save all by mistake at the wrong time, a confirm action dialog could save their butts.

**Comment by HonoredMule** [comment]
If you're directly editing production code, that's on you and you're pretty much asking for trouble even if this doesn't happen.

That said, in dev environments it can be handy to open and edit many files at once, only saving them when work in progress is believed to be at a runnable state.  Some legitimate examples of accidental save-all being disruptive:
 - test-driven development where a process is watching for changes and will fire off unit tests when they occur
 - playing with tweaks to logic you don't want to keep and are copying into another tool like a db query browser
 - just have many files open and some may have rogue edits from accidental clicks or keypresses (especially when making frequent switches between text area and search dialog)
 - those unfortunate situations when you are working on something not in source control (yet or ever)

I don't know if the legitimate cases really warrant a modal dialog preventing accidental usage, but I will note that it can be a real hassle if you have many files open and can't even remember which ones had disposable/bad edits in them that you didn't intend to save.

**Comment by nikoelgatito** [comment]
I was actually searching for this issue on Google as, although not while working on production directly, I faced this situation multiple times already either via click of keyboard shortcut. I'm actually surprised that this can't at least be enabled from the configuration panel.

An example of issues that can arise by the fact that no confirmation dialog is prompted is having documents opened and adding content to these either voluntarily or by mistake without willing to save anything and then triggering the "Save All" function by mistake. 

When working on a large amount of files at the same time, anything that was added without intend to save will be saved and difficult to track unless a versioning software is present.

**Any function actually proceeding to multiple write operations should always ask for a confirmation first.**

When saving a single file by mistake it is easy to use undo to revert these changes however to my knowledge there is no such undo option for the "Save All" function.

As I understand that in some specific scenarios some users might want to use the "Save All" function quickly without having to confirm, I would suggest the presence of a modal confirmation that is enabled by default with a configuration option to disable it.

In my opinion, this is definitely a requirement.

**Comment by ArkadiuszMichalski** [comment]
> **Any function actually proceeding to multiple write operations should always ask for a confirmation first.**
I think so too, or at least there should be an option to enable it on demand (in Pref or hidden), similar to what we have for Searching (replace in all files). Possible undoing changes in all files (resulting from accidental writing) is a big problem.

**Comment by vsrawat** [comment]
By this logic, every key combo will end up requiring a save all button. 

Any key combo can be pressed by mistake.

For starters and newbies, windows notepad or even wordpad or MS Word (talking about windows) would be intuitional software to use.

For those, who have come to know about npp and installed it and using it, they are already at a higher level of intellect that it is not reasonable to expect that they would commit such mistakes.

Then why make a change in a software to handle rare mistakes, that would put additional burden on regular users who had been careful enough to use it discreetly as and when required.

Control-S is to save, and should there be a confirmation dialogue for it? I guess "no."

Similarly If someone has bothered to go to menu - File - Save All, or someone who has pressed an uncommon keyboard shortcut of Control-Shift-S, all this happening due to some mistake is rare of the rarest.

I had been using Control-Shift-S to save all files since I start using npp and now that thing is broken by this "issue". It makes me sad.

My suggestion is - don't do anything on it, and close the issue. Discard it, reject it.

Anyone who maked the mistake of clikcing or pressing this by mistake, will learn from his/ her mistake, and will be cautious in future not to repeat it. or he can confine himself to windows pain siimple notepad till he graduates to use npp.

Thanks.

**Comment by mere-human** [comment]
> Then why make a change in a software to handle rare mistakes, that would put additional burden on regular users who had been careful enough to use it discreetly as and when required.

You can't change what is happening already. You can't teach everybody to use the software "right". Instead, users tend to use the software as they like. Then if something is not suitable, they come here and request a feature or report a problem. Then several subsequent feature requests can shape the feature to its final form. It is a continuous process of improvement.

**Comment by vsrawat** [comment]
Good enough.

But It would be also be wrong to add changes to entertain one single change request, even if that breaks down the existing method of working and creates problem with millions of other existing happy users.

A line needs to be drawn somewhere. 

One person asking something is often a good thing when it only gives an idea of something new to the developer, and then the developer thinks it over and implements something wider and larger that helps all his users.

But it is not even an improvement idea, nor a feature suggestion. It was just a problem faced and reported by one single individual. One persons problem was solved in such a way that all other users got disturbed.

Anyway, I am not in favour of nor against this suggestion or problem. I would be happy if Control-Shift-S continues sillently saving all files, without asking even once.

Thanks.

**Comment by nikoelgatito** [comment]
Hi @vsrawat, I was surprised to read comments against the addition of a confirmation dialog as in my point of view saving all files at once is more of a risk than a feature. Although the Save All function can also be triggered via the "File" menu and via a specific keyboard shortcut, it can primarily be triggered by accidentally clicking the wrong button as the "Save All" button is right aside of the "Save" button in the toolbar. In any cases, as mentioned previously "_Any function actually proceeding to multiple write operations should always ask for a confirmation first._".

As an experienced senior developer, I've never used this Save All feature aside from accidentally as having precise control onto which specific file I'm actually editing is important. I'm also frequently working on multiple projects at the same time on the same Notepad++ instance and while multitasking, saving all files accidentally can have very important repercussions. Although I might have accidentally triggered the Save All feature only a few times, the time wasted tracking down nonapplicable changes resulting from this action was enough to justify the dialog.

On the other hand, I understand that under other circumstances some users may benefit from quickly saving several files. This is why I had previously suggested the addition of a configuration field to control this behavior. The changes that ended up being committed should be pleasing both parties as there is a configuration field allowing to disable the confirmation dialog.

When it comes to enabling the dialog by default, this was the right thing to do in my opinion as this operation can be destructive. Those willing to get rid of the confirmation dialog can simply and consciously disable the function on their workstation once and for all from the configuration. After all, the potential complications caused by inadvertently saving all files for those in favor of the dialog by far outweigh the simple configuration change required for those against.

Please note that although this issue had been reported by a single user here on Github, I'm sure it has been encountered by and has caused losses to several developers throughout the community who will welcome this new dialog.
