### ISSUE TITLE
Installing NppExec via Plugin Manager leads to warning about verification

### ISSUE THREAD

**Issue by reed9999** [notepad-plus-plus/notepad-plus-plus#2188]
### Description of the Issue

When I select NppExec from the Plugin Manager, I get the dialog: 

> It has not been possible to validate the integrity of 'NppExec.dll' needed to install or update a plugin. Do you want to copy this file anyway (not recommended)?

I managed to install another arbitrarily selected plugin, so this doesn't appear to be a global problem. 

### Debug Information
(Windows 10) 

Notepad++ v6.9
Build time : Feb 21 2016 - 21:27:55
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll PoorMansTSqlFormatterNppPlugin.dll 

(I'm new to using the Plugin Manager so please be patient if this request isn't well-stated; I'll gladly provide any other info needed to help troubleshoot!)

**Comment by MAPJe71** [comment]
I got the same message from the PluginManager when installing updates for the plugins:
- NppGTags (v4.2.1)
- EditorConfig (v0.3.1.0).

I presume it's plugin related i.e. the files are not 'signed'.

### Debug information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files\Notepad++\notepad++-6.9.2.0.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows XP
Plugins : CustomizeToolbar.dll FunctionList.dll InsertLoremIpsum.dll NppEditorConfig.dll NppGTags.dll PluginManager.dll PythonScript.dll TagsJump.dll TextFX.dll VisualStudioLineCopy.dll XMLTools.dll

**Comment by dail8859** [comment]
When a plugin is "registered" with the plugin manager it saves a hash of the file. Later when a user downloads a plugin it rehashes the download to make sure that it got the expected files. If the hash does not match then you get that message. 

In most cases this warning can be ignored...however, if you are overly concerned about security it may be good to cancel the installation. 

The best course of action would be to contact the authors of the individual plugins because they need to update the registration with the plugin manager.

**Comment by MAPJe71** [comment]
Are these the md5 hashes in the 'PluginManagerPlugins.xml'-file?
A lot are missing md5 hash!

**Comment by dail8859** [comment]
@MAPJe71 Interesting...I thought it *always* saved a hash for every plugin, but you are correct that alot of the plugins do not have the hash in the XML file.

Either way the plugin authors still need to correct the issue for their plugins.
