### ISSUE TITLE
Feature request: Different tab layout when many files are open

### ISSUE THREAD

**Issue by RollingStar** [notepad-plus-plus/notepad-plus-plus#219]
I can't figure out if feature requests are allowed here. If not, I will stop making them. :)

When the user has many documents open, the tab bar fills up. After that point, the only way (that I know of) to navigate between them is by the arrow buttons on the right of the tab bar. Maybe the scroll wheel works, but I wouldn't know because I use a trackball mouse without one.

If the user wants to go from one side of their documents to the other, they have to click the arrow several times, once per document not visible. This can be cumbersome. I have to click 10 times to go from my first document being visible on the tab bar to my last document being visible on the tab bar.

I'm not going to suggest a better way to do it, because the best way might be something I didn't think of. However, Google Chrome handles many tabs by shrinking the horizontal width of tabs when there are too many, and by truncating the title of each tab. I think Firefox has tab scrolling functionality similar to Notepad++, but it also truncates the title of each tab. That way, a title bar like "this is a really long title that goes on and on and never stops" doesn't take up a large portion of the tab bar.

![image](https://cloud.githubusercontent.com/assets/4810902/8154244/02dead44-1306-11e5-9787-379fef74f52a.png)

**Comment by xylographe** [comment]
In the meantime, you could use Ctrl-PageUp and Ctrl-PageDown to navigate through the tabs.

**Comment by Rikk** [comment]
> Ctrl+PageUp and Ctrl+PageDown
Personally, I'm used to Ctrl+Tab and Ctrl+Shift+Tab

**Comment by mat-m** [comment]
Truncating could be annoying when the end of the filename is meaningful. NetBeans, Visual Studio are IDEs and do not truncate.

FWIW, I use the "Multi-line" setting, and I love it. When it is even too cluttered, I resort to the "doc switcher" plugin.

**Comment by karasuhebi** [comment]
I use the Multi-line option myself and that would work pretty well if it wasn't for Notepad++'s behavior of making the active line always be the one on the bottom. This causes issues like #917 (although that could be fixed without removing this behavior) and also for me it's an issue since I'm used to rows/lines of tabs/documents being in chronological order, so for me the first line would be my first set of documents while the second would be the remaining set of documents. Having the lines constantly changing makes it harder for me to get used to where to look for my documents when I go to click on them. If documents could stay in one line, that would be great.

Thanks!

**Comment by dmitton42** [comment]
I have a minor pile-on for this request,  I wish the tab scrolling buttons were on the LEFT side, not the right.  It's a long mouse move to an infrequent area.  And then maybe add First and Last arrows.

**Comment by karasuhebi** [comment]
This Issue can probably be closed. Notepad++ 7.0 can do tab scrolling with the mouse wheel.

**Comment by dail8859** [comment]
Seems like this issue can be closed now. 9967c59912a05bfac57854e583d573877fdcb787 also addresses part of the concerns here.
