### ISSUE TITLE
Support multiple themes for external lexers.

### ISSUE THREAD

**Issue by sanastasiou** [notepad-plus-plus/notepad-plus-plus#224]
Currently, an external lexer needs to supply an .xml file with the language's token and their relevant styles.

e.g.

![image](https://cloud.githubusercontent.com/assets/2955627/8160745/7314ec88-1372-11e5-8371-2808bce27f68.png)

While this works, the problem, or rather inconvinience is, that if the user selects a different theme, he has to change all the coloring. 

For the already integrated languages this is not the case. There are multiple styles for multiple themes under ..\AppData\Roaming\Notepad++\themes

There for every theme, all the supported languages are defined, so each language has it's own settings for any given theme.

Please enable this functionality for external lexers as well.

**Comment by DavidHansen-0x454d43** [comment]
I am working on an external lexer and have hit this issue as well. 

When I add a new theme, and switch to it in the Style Configurator, my lexer is listed but when I modify it on that theme, it updates the default style instead. 

If I manually add my lexer styles to the theme's xml, then I get two entries for my lexer in the Language listbox.  This allows me to switch between two different themes for my lexer... for a time, because, if I update my 'manually added' styles in the Style Configurator, it will again overwrite the styles in the default theme when clicking "Save & Close" (this seems like a bug to me) . 

I'm not sure what the best approach would be to solving this, but maybe 
1. Don't display custom lexer styles in alternate themes, unless the user has manually added them by editing the theme.xml, or 
2. automatically add custom lexer styles to newly added themes, so that they can be changed by the Style Configurator

**Comment by MetaChuh** [comment]
closed due to inactivity
