### ISSUE TITLE
Set- and EndLocal Batch keywords not colored in case of `@`-prefix

### ISSUE THREAD

**Issue by MAPJe71** [notepad-plus-plus/notepad-plus-plus#2270]
### Description of the Issue

The Windows command script (aka batch) keywords `setlocal` and `endlocal` are not colored as keywords when preceded by an at-sign.

### Steps to Reproduce the Issue

1. download attached file [Test.cmd.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/467919/Test.cmd.txt);
2. rename the file to `Test.cmd`;
3. open file `Test.cmd` in Notepad++.

or ...

1. download attached file [Test.cmd.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/467919/Test.cmd.txt);
2. open the file in Notepad++;
3. set language to `Batch`.

### Expected Behavior

**All** `setlocal` and `endlocal` keywords correctly colored (see left side of image below).

### Actual Behavior

SciTE v3.6.7 on the left vs. Notepad++ v7.0 RC on the right.
![capture-2016-09-12-19 06 51](https://cloud.githubusercontent.com/assets/6494038/18445351/74d1d326-791d-11e6-9b67-c38ef9475ae8.png)

### Debug Information

    Notepad++ v7   (32-bit)
    Build time : Sep  1 2016 - 02:21:07
    Path : C:\Program Files\Notepad++\notepad++-7.0.0.0-RC.exe
    Admin mode : OFF
    Local Conf mode : ON
    OS : Windows XP
    Plugins : CustomizeToolbar.dll EditorConfig.dll FunctionList.dll InsertLoremIpsum.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll PythonScript.dll TagsView.dll TextFX.dll VisualStudioLineCopy.dll XMLTools.dll 

Same incorrect result when opening the file in Notepad++ w/o plugins (-noPlugin argument).

**Comment by dail8859** [comment]
I tried with SciTE v.3.5.6 (which is the version N++ is on) and it still has the same results, meaning it isn't a bug with the Lexer. So I poked around using LuaScript ;)

Notepad++ is detecting `setlocal` and `endlocal` as `SCE_BAT_COMMAND` (not sure how the lexer works, guess because it is at the start of a line).

If you add `setlocal` and `endlocal` to `Style Configurator > Batch > Keywords` the the style looks correct and N++ detects these as `SCE_BAT_WORD`.

Scite uses [this list](https://sourceforge.net/p/scintilla/scite/ci/default/tree/src/others.properties#l70) for Batch keywords.
