### ISSUE TITLE
Do not add file to Recent Files List if it is just moved to the other view

### ISSUE THREAD

**Issue by pnedev** [notepad-plus-plus/notepad-plus-plus#2277]
### Description of the Issue

File is added to the _Recent Files List_ when it is only moved to the other view.
The behavior is wrong because the file is not actually closed.
### Steps to Reproduce the Issue

1. Open N++ and clear the _Recent Files List_.
2. Open two files.
3. Move one of them to the other view.
4. Look at the _Recent Files List_ - the moved file is added there.
### Expected Behavior

Just move the file to the other view without adding it to the _Recent Files List_.
### Actual Behavior

File is added to the _Recent Files List_ when it is only moved to the other view.
### Debug Information

When moving the file to the other view it is first closed in the current view which causes it to be added to the _Recent Files List_.

**Comment by SinghRajenM** [comment]
Additional info:
If NPP is restarted, the file which was added to _Recent List_ is removed from the list.

**Comment by Yaron10** [comment]
Hello,

Some simple changes in three NPP source files seem to solve this issue.

**In Notepad_plus.h replace**
`void doClose(BufferID, int whichOne, bool doDeleteBackup = false);`
**with**
`void doClose(BufferID, int whichOne, bool doDeleteBackup = false, bool addToClosedList = true);`

**In Notepad_plus.cpp replace**
`//just close the activate document, since thats the one we moved (no search)
doClose(_pEditView->getCurrentBufferID(), currentView());`
**with**
`//just close the activate document, since thats the one we moved (no search)
doClose(_pEditView->getCurrentBufferID(), currentView(), false, false);`

**In NppIO.cpp replace**
`void Notepad_plus::doClose(BufferID id, int whichOne, bool doDeleteBackup)`
**with**
`void Notepad_plus::doClose(BufferID id, int whichOne, bool doDeleteBackup, bool addToClosedList)`

**and also replace**
`if (PathFileExists(buf->getFullPathName()))`
**with**
`if (PathFileExists(buf->getFullPathName()) && addToClosedList)`

Thank you.
BR

**Comment by SinghRajenM** [comment]
Fixed issue in #2665

**Comment by pnedev** [comment]
Hello @SinghRajenM ,

Great, thank you for the fix.

Hello @donho ,

Thanks for accepting the fix so promptly.

BR
