### ISSUE TITLE
minor changes

### ISSUE THREAD

**Issue by ranjan-ranjan** [notepad-plus-plus/notepad-plus-plus#2387]
![1](https://cloud.githubusercontent.com/assets/16834561/19065700/91f77a84-8a32-11e6-8714-cb42ca85ebd1.png)

**Comment by MAPJe71** [comment]
`Find Next` enables you to skip occurrences when you iterate through the document.

**Comment by ranjan-ranjan** [comment]
This can be done in another tab also - "Find" tab. The same option is already present.

**Comment by MAPJe71** [comment]
So that would mean you'd have to switch to the "Find" tab every time you want to skip a replacement, not very convenient.
Maybe the functionality of the `Find Next` button would be more clear if it read e.g. `Skip Replacement`.

**Comment by vlakoff** [comment]
Agree with MAPJe71, this button is useful.

I think `Skip Replacement` would be misleading as the button can be used to reach the first candidate. So this button is more of a "reach next" rather than "leave current".

However, I think `Find Next` brings confusion with the regular "find" functionality.

May I suggest `Go to Next`?

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
@ranjan-ranjan "Find Next" in Replace window is 100% correct and fine.  "Replace All", true, it is for the current document, but more accurately it should be "Replace All in Direction" because unless Wrap around is ticked, "Replace All" will not truly replace all in current doc.  But, it is all rather a difficult point, because the button is small and won't fit a lot of text.
