### ISSUE TITLE
Find/Replace On Large File Causes Crash

### ISSUE THREAD

**Issue by macdjord** [notepad-plus-plus/notepad-plus-plus#240]
When I try to run a regular-expression find/replace operation on a large file, Notepad++ crashes.
- I don't think it's the fault of the regex. It's relatively simple - no backreferences, no nested repeats, and no repeatable sections which can match a newline (so it can't go mad and try to match the entire file)
- The thing I am replacing with is the blank string, so I'm pretty sure that's not the problem.
- It is definitely correlated with the size of the input to the find/replace; if I select a small enough part of the file and use 'In Selection', no crash:
  - Selection: 422932 characters, 8816 lines. Result: 1759 matches found and replaced, no crash
  - Full file: 1555727characters, 32212 lines. Result: 6433 matches found and replaced, but Notepad++ crashes as soon as the find/replace operation finishes.
- The crash appears to take place after the find/replace operation has finished - the 'X occurrences replaced' status on the Replace dialogue updates, and in the background I can see the file being re-rendered - but before control is actually returned to me after I have clicked the 'Replace All' button
- Error messages are as follows:
  - Win32Exception: "An exception occurred. Notepad++ cannot recover and must be shut down.
    The exception details are as follows:
    Code: 0xC0000005
    Type: Access violation
    Exception address: 0x5DCB0F3A
  - Do you want to save a dump file?
    Doing so can aid in developing
    [Yes] [No](I select yes.)
  - Failed to create dump file 'C:\Program Files (x86)\Notepad++\NppDump.dmp' (error 5)
  - Notepad++ will attempt to save any unsaved data. However, dataloss is very likely.
  - Notepad++ was able to successfully recover some unsaved documents, or nothing to be saved could be found.
    You can find the results at:
    C:\Users[redacted]\AppData\Local\Temp\N++RECOV
  - Notepad++: a free (GNU source code editor has stopped working
    A problem has caused the program to stop working correctly.
    Windows will close the program and notify you if a solution is available.
  - Sometimes an additional dialogue complaining about a 'pure virtual function call' appears, but I haven't been able to reproduce that reliably so I don't have the details.
- It does not appear to be correlated with memory usage; I watched the task manager during the find/replace and crash, and notepad++.exe's memory usage remained level throughout
- It appears to be correlated with the number (or possibly total size) of matches; I changed my regex by one character so it would require the same search pattern but fail to find any matches, and I got no crash.

**Comment by macdjord** [comment]
Update: It happened again, and this time I got the details of the 'virtual function' error message:
````
Runtime Error!
Program: C:\Program Files (x86)\Notepad++\notepadd++.exe
R6025
- pure virtual function call
````

**Comment by macdjord** [comment]
Update: It seems to correlate with number of matches rather than total length of matched text. I changed my regex to be repeatable, so that multiple consecutive copies of the target pattern would be treated as a single match; the total amount of text matched actually went up slightly, but the number of distinct matches went from ~6.5k to ~20, and I haven't seen a crash since.

**Comment by ariccio** [comment]
The [pure virtual function call](http://blogs.msdn.com/b/oldnewthing/archive/2004/04/28/122037.aspx issue is probably a separate bug.)

**Comment by likeearth** [comment]
Notepad++ can even crash with a normal ReplaceAll, e.g. replacing all occurrences of "@" by "-uniq-" when there are about 4000 occurrences spread over a file of 1311 lines (file contains 140.257 characters only). Even replacing all those "@"s by "~"s sometimes crashes Notepad++.
It can also crash when undoing such replace by using Ctrl-Z (if it didn't crash by then yet, try a series of Ctrl-Y(==redo), Ctrl-Z(==undo) after this, crash will be nearby)

**Comment by likeearth** [comment]
Update: found people mentioning PlugIn "Location Navigate" when Notepad++ crashed. So I decided to uninstall this PlugIn. Now the crash problem seems to be gone!
So my conclusion for now is: 
Don't use PlugIn "Location Navigate" version 0.4.7.7.

**Comment by benamada** [comment]
Uninstalling the "Location Navigate" plugin for me also stopped Notepad++ from crashing when doing a simple regex search and replace a 2775 line text file.  Each line containing 4 fragments that get replaced.

**Comment by Barbapoux** [comment]
I've noticed that the last version where it works correctly is the npp 6.5.5.
I can replace anything with this version without any crash, of course they are new features in following versions that are missing. Anyway I cannot work correctly with them.
Here's a file that is producing the problem with version 6.9.
Edit the file (94Mo) and select Edit / Blank Operations / Trim Trailing Space
=> Code: 0xC0000005 Type: Access violation Exception address: 0x698F1B8D

Regards

[testnpp.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/188031/testnpp.zip)

**Comment by gvenjava** [comment]
Work Around:
Open the below file and remove the tag for big file from it. Enjoy Notepad++ again..
%AppData%/Notepad++/session.xml

**Comment by Barbapoux** [comment]
This is irrelevant, it only remove my big file from next session. 
I can use the close button for that.
Did you try what I have written?
Download the zip file, unzip it, edit it with npp and try to do "Edit / Blank Operations / Trim Trailing Space"

**Comment by Barbapoux** [comment]
Hi,
I've just tested the bug with new version that fix the CIA hacking of NPP V7.3.3. 
And it's still crashing, here's a dump. But you're able to create one if you do what I have written one year ago.

Note: Could be good to create the DUMP out of Program files directories or do we need to run NPP as admin in order to catch dump? If so, maybe you can add a note to "Failed to create dump file" message.

[NppDump.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/881621/NppDump.zip)

Regards

**Comment by glakovic** [comment]
I've done lots of replacing on large files without problems, but recently I added LocationNavigate plugin and NPP started to crash. I removed it and now it works fine.
Not sure are there more reasons to crash, but this (great) plugin is definitely a reason.

**Comment by drockcode** [comment]
I'm using NPP v7.5.1, Location Navigate 0.4.7.7. 

The plugin will crash anytime a large number of changes are performed on a file in a short amount of time:
* As others have seen, if you perform a Find / Replace with a large number of replacements in a single file.
* You can also crash the plugin by doing a large column mode selection (e.g. over 5000 lines), and typing in several letters.

I didn't want to disable the plugin, because it's useful, so I did some debugging using the plugin source at SourceForge and Visual Studio 2013.

I think I've found the problem: it appears to be a concurrency issue. The plugin uses a std::list called ActionDataList to record file editing events in the beNotified function. In a seperate thread (created by the plugin), the ThreadFunc function reads the ActionDataList to populate the "Location History" list in the plug-in's option window, removing each list item as it goes. When a large number of edits are performed in a short amount of time, these threads access the ActionDataList simultaneously, i.e. in an indeterminate state. Hence ThreadFunc causes a memory violation.

Adding std::mutex locks and unlocks around all accesses to ActionDataList appears to resolve the issue.
Is the plugin developer still maintaining this project, and are they aware of this problem? I may have to create a SourceForge login in order to contact them...

**Comment by floporin** [comment]
I'm using NPP v7.5.7 portableApps, Location Navigate 0.4.7.7.
i had the same issue. re-insatlling the plugin from plugin manager and re-starting NPP seems to fix the issue

**Comment by vinsworldcom** [comment]
@drockcode - I've been "debugging" the source as well - first off changing from Chinese characters to US English.  Care to post your updates re: mutex on your Github?  I'm sure others would like to see what you've done especially if it's working!  I just found the Location Navigate plugin recently and love it, but everytime I close N++, it hangs for about 5 seconds then says it crashed and offers to close or debug.  Disabling the Location Navigate plugin eliminates the close/crash so I'm quite sure Location Navigate plugin is the culprit.  Would love to get that plugin working correctly!

https://github.com/vinsworldcom/nppLocationNavigate

Cheers.

**Comment by Barbapoux** [comment]
Currently, this has no effect on the problem I have described 2 years ago.
There is no plugin at all in my version, only basic installation.
Download and install the latest Npp version 7.5.8.
Download the zip file upper (24 Mar 2016).
Unzip the text file.
Open the big text file with Npp.
Select Edit / Blank Operations / Trim Trailing Space
=> kaboom
Same on W7, 32 or 64, or W10.

Regards.

**Comment by ClaudiaFrank** [comment]
@Barbapoux - thx for sharing the document.
While investigating a similar issue I can confirm that using your document 
and doing the described steps it consistently crashes npp when backup is activated, 
while it seems to work without a problem if backup is disabled.

I' currently running some automated tests to see if this is really the case.

One additional info - your file is a bit unusual for a text editor, 
as it contains different eols and binary data.
The impact of this content needs to be investigated as well.

Will keep this thread updated.

**Comment by Barbapoux** [comment]
Thanks Claudia ( or Frank :) )
I never noticed that this backup switch has this effect, that's going to help me to test deeper.
Original file is from Linux, the \r is used in the original tool as a text breakline, you may have multiple breaklines in one line (a bit weird I know), then the report is sending the \r then blank until the final \n.

The description of the error supra, is a simple case that always generate a dump. Originaly I had random crashs by replacing ' AAA AA' (and other strings) by space or nothing. Sometimes no crash but result contains non ASCII characters and missing lines. I have the feeling that the bug is the same in both cases as it looks like storage violation on big file (I could have more that 100000 replacements per command). 
Anyway, I will try to generate a new file today and to remove these \r firstly.
Regards

**Comment by rolandh** [comment]
I still get "not responding" when navigating and closing large (75mb) text files. Word wrap makes things infinitely worse and the application goes not responding whenever you do basically anything.

Using Notepad++ v7.8.1 64bit with no spelling plugins installed.

How do I fix the not responding with large text files? It is the main reason I use the application. I used to love how fast it is, newer versions seem very slow compared to back in the day.

**Comment by Ekopalypse** [comment]
The first thing I would give a try is to use a plain npp setup, meaning no additional plugins only the ones which do come bundled. The easiest way to do this is, imho, to use a zipped version as this can be used together with an installed version.
For the record, I can open 600mb text files without an problem.

**Comment by rolandh** [comment]
It is a plain notepad++ setup with the standard plugins.

**Comment by rolandh** [comment]
I can reproduce the massive scrolling/not responding lag by running the standalone package with word wrap turned on.

npp.7.8.2.bin.x64.7z

**Comment by Ekopalypse** [comment]
Because you use word wrap, could it be that your files do have a lot of really big lines?
This is a known issue related to scintilla, the underlying control used by npp.
To check if this is the case you could do a simple test.

Open npp and goto **settings->preferences-editing** and check **show vertical edge**
Set where the column should be visible by entering a number in **number of columns**
Close the settings dialog.
Open your file and once loaded press **ctrl+a** and **ctrl+i** (assuming you have not remapped the default shortcuts otherwise go to the menu and do **select all** and **split lines**
It will take some time to do this.
For me it took 15 seconds to do this for a 45mb test file but I don't own a fast pc.

If the scrolling is now good, then this is the cause of our problem if not, then something else is
still interfering.
