### ISSUE TITLE
CONTRIBUTING.md needs clarification

### ISSUE THREAD

**Issue by MattTheGeek** [notepad-plus-plus/notepad-plus-plus#241]
# CONTRIBUTING.md needs clarification

The contributing file is not clear enough on what pull requests will be accepted, and what won't. This could cause developers to spend unnecessary effort into fixing issues, and the project maintainer spending unnecessary time on examining and denying pull requests.

Quoting from the ```CONTRIBUTING.md``` file:
 ```"Only bug-fix and feature request will be accepted. For the other things, I can run static code analysis tool myself."```

Some developers see fixing documentation and other non-code improvements as bug-fixes. This rule needs to expanded upon to avoid this kind of confusion in the future. I recommend replacing the above quoted text with: 

```
"Only Pull Requests consisting corrections made to code, and additions of features will be accepted. Pull requests consisting of:
- Addition, Correction, or Updating of documentation or comments.
- Correction of code style.
- [other restrictions...]

Will generally be denied and closed."
```
Then the contributing documentation should cover what kind of code bug-fixes are acceptable. Consider these areas of improvements/bug-fixes:
- Code optimization.
- patches for confirmed issues.
- Patches for unconfirmed issues.
- Patches for code that may cause problems.
- etc...

For the unacceptable pull requests, what should developers do? Should developers file issues for these kinds of unacceptable pull requests? Or should developers ignore the problem and not bring it up? 

The project's maintainer stance on documentation also needs to be known. Is any improvement or additions to documentation allowed?

**Comment by milipili** [comment]
Since you ask, it probably needs clarification. I will try to answer it. I will let @donho correct me if he sees fit.

From my personal understanding, a bug happens (and not *may happen*) and prevents the user from uses the product. This may be too restrictive, but some boundaries must be defined.
As a consequence, like many other softwares, a patch (PR in this case) for fixing a bug must be as minimal as possible and must strictly fix it. Simply for being easily back-ported in previous versions (even if n++ does not currently exactly use semver nor LTS version). Thus no coding style change nor indentation nor etc can be accepted.

Obviously, any problem must be reported. It is an important knowledge base and even if some issues are closed for some reasons, it is important to have them (but duplicates should be avoided of course)

Whenever there is doubt for a new feature or for some enhancements, a question can be asked (in github, an issue can be a question) before coding something that may not fit or may be useless (again, like any other project). And we would be glad to answer it as soon as possible to find a solution together.

It is sometimes difficult to share a vision, but in any cases it is mandatory to keep a direction. When contributing, personal tastes are important, but they must remain personal. They will be followed anyway if they seems good.

About updating the `contributing.md`, I will let @donho answer :)

**Comment by donho** [comment]
@milipili I could not say better!

@MattTheGeek In the Contributing.md the direction is given clearly, but there're no fixed rules for a pr - that's why we call "pull request" - by its nature, is a request.

**Comment by ariccio** [comment]
Perhaps examples of "bad" and "good" pull requests would help?

**Comment by ariccio** [comment]
Xref: #218
Xref: #223
Xref: #225

**Comment by MattTheGeek** [comment]
@donho I think information about contribution ownership should be added, and if contributors retain their copyright to the submitted contribution or if the copyright is assigned to the project.

**Comment by milipili** [comment]
We will try something very simple. Except for translation and user documentation (which should be coming soon I hope), a PR can be accepted only if attached to a github issue (bug, enhancement, question). For enhancement and questions, it must be approved by one of the administrators, via the new label "accepted". If an issue is still not accepted, anyone who wants to take the job can ask for it.

Like that, anyone would be able to specify the wanted changes and implementation details can be discussed, and useless work should be avoided.

**Comment by milipili** [comment]
AFAIK, any contribution falls under the project's copyright

**Comment by MattTheGeek** [comment]
>We will try something very simple. Except for translation and user documentation (which should be coming soon), a PR can be accepted only if attached to a github issue (bug, enhancement, question). For enhancement and questions, it must be approved by one of the administrators, via the new label "accepted". If an issue is still not accepted, anyone who wants to take the job can ask for it of course.

>Like that, anyone would be able to specify the wanted changes and implementation details can be discussed, and useless work should be avoided.

@milipili This is exactly what is needed in the file. A detailed explanation.

**Comment by milipili** [comment]
This sounds good to me.

**Comment by ariccio** [comment]
Yay! This should be much clearer for newbies.

However, we really do need a *strict, reason based, and self-consistent* definition of an "enhancement". Otherwise, there'll be never ending squabbles over whether a given Pull Request is an "enhancement" or not. *Particularly* with regards to *rejected* Pull Requests.

**Comment by milipili** [comment]
There won't be never ending quabbles. A PR for not being rejected must now be related to an issue, which must be accepted first if not for resolving a bug (and we will do the code review anyway).
