### ISSUE TITLE
[REQUEST] An option to always have the caret visible

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#2471]
Hello,

I think that an option to always have the caret visible (i.e. when mouse-scrolling up/down) would be appreciated by many users.

Thank you.

**Comment by guy038** [comment]
Hi **Yaron**,

Ah! Yes, you would like that, as soon as we hold **down** the **left**-mouse button, **after** dragging along, the **caret** comes **inside** view, **automatically**, wouldn't you ?

In the meanwhile, **Yaron**, we, just, can :

- Click anywhere, on the **current** screen reached ( Obvious ! )

- Use the Scintilla command **SCI_MOVECARETINSIDEVIEW**

To use it, simply set a shortcut to that command, in **Settings > Shortcut Mapper... > Scintilla commands > 20**

---

There are **four Scintilla** commands, relative to the **caret**, recapitulated in the table below :

~~~
   •============================================================•
   |    Scintilla Command      |  Id  |       MY shortcuts      |
   •===========================•======•=========================•
   |  SCI_SCROLLCARET          |  18  |   Ctrl  +            =  |
   |  SCI_MOVECARETINSIDEVIEW  |  20  |   Ctrl  +  Shift  +  =  |
   |  SCI_SWAPMAINANCHORCARET  |  96  |   Alt   +            =  |
   |  SCI_ROTATESELECTION      |  97  |   Alt   +  Shift  +  =  |
   •============================================================•
~~~

- The **`SCI_SCROLLCARET`** move the **editor** windows to the **present location** of the **caret**

- The **`SCI_MOVECARETINSIDEVIEW`** move the **caret** to the **present** editor **window**

- The **`SCI_SWAPMAINANCHORCARET`** swap the **caret** between the **start** and the **end** of the **present normal** selection

- The **`SCI_ROTATESELECTION`** move to the **next normal** created selection ( even **outside** view ! ) when **multiple** selections exists AND if the option **Multi-Editing**, in **Settings > Preferences... > Editing**, is **enabled**, of course !

Best Regards,

guy038

**Comment by Yaron10** [comment]
Hello Guy,

Thank you for this reply as well. I appreciate it.

As always, I've learned some nice tips. :)
But I think it would be useful to have the requested behavior as a NPP option.

Best regards.

**Comment by thedarkfalcon** [comment]
@guy038 That sounds really useful but it doesn't seem to work for me :-/ after assigning the shortcut (tried several different shortcuts) pressing it did nothing. Scrolling didn't keep the caret on the screen, and using the arrow keys after scrolling would return me to the carets position.

I'm using NP++ 7.1 32x on windows 10.

**Comment by guy038** [comment]
Hello, **thedarkfalcon**,

Well, let's begin with the **SCI_MOVECARETINSIDEVIEW** Scintilla command, which moves the **caret** to the **present** editor window :

- I suppose that you already affected a **shortcut** to that command

- Open, for instance, the N++ **license.txt** file

- Replace, if necessary, the **caret** at the **very beginning** of that file

- Now, **hold down** the **left** mouse on the **vertical** lift, on the right, in order to **scroll down** the contents, till you do **not** see the caret **anymore**

- Hit your assigned shortcut, for the **SCI_MOVECARETINSIDEVIEW** Scintilla

=> The **caret** should appear, as expected, at the **beginning** if the **first visible** line of the **present** editor window :-))

Remark :

- If the caret is near the **end** of the file and that you **scroll up**, with the mouse, till the **beginning** of the document, the action of the shortcut would move, this time, the **caret** to the **last visible** line of the **present** editor window !

Best Regards,

guy038

**Comment by MetaChuh** [comment]
@Yaron10 

the caret position is visible on 7.6.6 when mouse scrolling, as long as its position is within the scrolled view.

by editor design, the position itself will not be altered.
if you still need this, please click on another position, as soon as you have scrolled up or down.

thank you for your help and best regards.
