### ISSUE TITLE
Regex groups above 9th can not be referenced in replace

### ISSUE THREAD

**Issue by winnetou1357** [notepad-plus-plus/notepad-plus-plus#2514]
Hi,

### Version Info
Notepad++ v7.1 (64-bit) version produces the issue

### Steps to Reproduce
1. Do regex replace with more than 9 groups (subexpressions)
2. Try reference the 10th subexpression in _Replace with_: it fails with all of the following: `\g{10}` `\k<10>` `\g10` `\10` `\{10}` (I know some of these should not work by definition, I just tried around a bit to make it work - yet I couldn't).
#### Example
File content: `abcdefghijklmnopqrstuvwxyz`
_Find what_ (regular expression): `(a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)(l)(m)(n)(o)(p)(q)(r)(s)(t)(u)(v)(w)(x)(y)(z)`
_Replace with_: `\g{10}`

The result is: `g{10}`
I expect: `j`

### Note
`\g{10}` and `\k<10>` syntax is based on the following docs:
1. http://docs.notepad-plus-plus.org/index.php/Regular_Expressions
2. http://www.boost.org/doc/libs/1_49_0/libs/regex/doc/html/boost_regex/syntax/perl_syntax.html (also referenced by the above wiki page)

Maybe it is a bug with `\g` and `\k` substitution syntax because I could not make them work even for smaller numbers: while replacing with `\9` gives `i` (which is correct), neither `\g9` nor `\g{9}` works.

**Comment by winnetou1357** [comment]
Could it be that the 64-bit build does not use Boost's Perl regex implementation but POSIX regex instead? Could it be intentional or is it still a bug if this is the case? I did not find info on that but it looks like a possible cause.

**Comment by guy038** [comment]
Hello, **winnetou1357**,

No, you're wrong about it !! Indeed, with the **Boost 1.55** C++ regex library, used in **Notepad++**, you can, perfectly, use, references for groups, with number **greater than 9** :-))

---

As a summary, references to a **capturing** group, of number **`N`**, in the **searched** regex, can be referenced, in **replacement**, by the following syntaxes :

- The usual form **`\N`** ( with the **double** condition **`1 <= N <= 9`** )

- The form **`$N`** ( with the **unique** condition **`N > 0`** )

- The form **`${N}`** ( with the **unique** condition **`N > 0`** )

In addition, the **overall** searched regex can be referenced by the syntaxes **`$0`** or the syntax **`${0}`**

**Remarks** :

- Note that the syntax **`${N}`** must be used if the other syntax **`$N`** would be followed by a **digit**, in order to distinguish between the **true number** of the group and the **total** range of **digits** ! For instance, in replacement the regex **`${12}345`** would replace the matched expression found by the contents of group **12**, followed by the **number 345**  :-))

- Any referenced group with a number, which does **not** exist, in the search regex, will be replaced by a **zero length** string

---

Some simple examples :

- Let's suppose the search regex **`(((((((((group 9))))))))) (group10) (group11) (group12)`**, with a **space** character between a **closing** parenthesis and the **next opening** one

- And that the **subject** text, to apply the S/R to, would be  : **group 9 group10 group11 group12**

Then, if the replacement regex is :

- **`<$0>`** , you would get the text : **\<group 9 group10 group11 group12\>**

- **`12345${0}67890`** , you would get the text : **12345group 9 group10 group11 group1267890**

- **`[$9] and [$10] and [$11] and [$12]`** , you would get the text : **[group 9] and [group10] and [group11] and [group12]**

- **`${10}0------0\90------0$12`** , you would get the text : **group100------0group 90------0group12** 

- **\1 $2 \3 $4 \5 $6 \7 $8 \9 $10 $11 $12`** , you would get the text : **group 9 group 9 group 9 group 9 group 9 group 9 group 9 group 9 group 9 group10 group11 group12**


For that matter, click to the link, below :

http://www.boost.org/doc/libs/1_48_0/libs/regex/doc/html/boost_regex/format/boost_format_syntax.html#boost_regex.format.boost_format_syntax.placeholder_sequences

Best regards,

guy038

P.S. :

You'll find **good documentation**, about the new **Boost C++ Regex library, v1.55.0** ( similar to the **PERL Regular Common Expressions, v1.48.0** ), used by **`Notepad++`**, _since its **`6.0`** version_, at the **TWO** addresses below :

http://www.boost.org/doc/libs/1_48_0/libs/regex/doc/html/boost_regex/syntax/perl_syntax.html

http://www.boost.org/doc/libs/1_48_0/libs/regex/doc/html/boost_regex/format/boost_format_syntax.html


- The **FIRST** link explains the **syntax**, of regular expressions, in the **SEARCH** part

- The **SECOND** link explains the **syntax**, of regular expressions, in the **REPLACEMENT** part


You may, also, look for **valuable** informations, on the **sites**, below :

http://www.regular-expressions.info

http://www.rexegg.com

**Comment by winnetou1357** [comment]
Wow, many thanks for the detailed explanation. It seems I just missed the Boost format syntax thing and tried to use Perl's backreference syntax instead.

Anyway, it would be great if both Boost links you gave here were present on [the appropriate page of the Notepad++ Wiki](http://docs.notepad-plus-plus.org/index.php/Regular_Expressions). Currently there is only one link to the [Perl syntax ](http://www.boost.org/doc/libs/1_48_0/libs/regex/doc/html/boost_regex/syntax/perl_syntax.html) but there is no link to [Boost format](http://www.boost.org/doc/libs/1_48_0/libs/regex/doc/html/boost_regex/format/boost_format_syntax.html). I would do it willingly but there is no anonymous editing nor open registration to the wiki, so it takes a more privileged guy than me to fix this :)

Regards,
winnetou1357
