### ISSUE TITLE
"Sel" shows a smaller number of characters

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#2546]
### Description of the Issue

Depending on the "Encoding" status bar in field "Sel" shows different numbers of characters.
### Steps to Reproduce the Issue

1. I write some text:
2. `abc¤‰ţ•˘µ˙ąćęłńóśźż`
3. I set encoding WIN1250:
4. [Encoding->Character Set->Central European->Windows-1250]
5. I select all text:
6. [Ctrl+A]
7. I set encoding WIN1252:
8. [Encoding->Character Set->Western European->Windows-1252]
9. I select all text:
10. [Ctrl+A]
11. I set encoding ANSI:
12. [Encoding->Encode in ANSI]
13. I select all text:
14. [Ctrl+A]

### Expected Behavior

Result "Sel" at step:
  6: 19
  10: 19
  14: 19

### Actual Behavior

Result "Sel" at step:
  6: 19
  10: 19
  14: 9
because np++ is not counted 10 characters (step 14, in ANSI encoding):
`¤‰•˘µąłśźż`

### Debug Information

Notepad++ v7.2 (64-bit)
Build time : Nov 2 2016 - 11:27:56
Path : C:\Program Files\Notepad++\notepad++.exe
OS : Windows 10 Home
Local code page: WIN1250

**Comment by h-h-** [comment]
I would like to have this fixed. It´s still there in v7.5.4 (32-bit).
You also can reproduce it with a section sign (§) and switching between ANSI and ISO 8859-1.
Select it in ANSI and Sel shows 0. Change to ISO 8859-1 and Sel shows 1.

**Comment by joxeanr** [comment]
On Notepad++ v7.7 (64-bit)

I just found a bug and must be related to this one. Sel does not count the inverted question and exclamation marks in ANSI mode.
[https://en.wikipedia.org/wiki/Inverted_question_and_exclamation_marks](https://en.wikipedia.org/wiki/Inverted_question_and_exclamation_marks)

**Steps to Reproduce the Issue**
1. Create a new document: [Ctrl+N]
2. Type the inverted question and the inverted exclamation marks or copy them from the Wikipedia page and paste it.
3. Select all text: [Ctrl+A]
4. Sel shows 0.

**Expected Behavior**
Sel should show 2.
