### ISSUE TITLE
[Feature Request] Search in Shortcut mapper

### ISSUE THREAD

**Issue by rillig** [notepad-plus-plus/notepad-plus-plus#2562]
When I open the Shortcut mapper, I see a large list of Name/Shortcut pairs.

When I want to change a shortcut now, I first have to find it in the list by reading all the list items. This is inconvenient because I most probably have and idea of what I want to find, e.g.

* All commands that are assigned to the F5 key
* All commands whose shortcuts have Ctrl+Shift in them
* All commands that do rot13 encoding

There should be a possibility of filtering the list of shortcuts. The simplest idea is to have a single text field above the list where I can enter several words, like `Ctrl`, `file`, `toggle`, `rot13`. Then, in the list below that text field, only the relevant shortcut mappings should be shown.

Any of the following conditions makes a shortcut mapping relevant for a search term:

* Its command name (either in English or localized) contains the search term
* The path in the main menu (either in English or localized) contains the search term
* Its shortcut (either in English or localized) contains the search term

**Comment by LOfaday** [comment]
Yes. Urgently needs a simple find facility, nothing complex, just type eg: "symbol" and it goes to the first entry with "symbol". Pressing F3 goes to next etc. It takes me several minutes to find the entry I want to remap because they are unsorted and seem to have no relationship to (eg) menu location. I read down quickly and often miss the one I want so I give up... :-(

**Comment by cmeriaux** [comment]
a Pull Request is in progress #4096
