### ISSUE TITLE
[Suggestion] Golang language

### ISSUE THREAD

**Issue by jD91mZM2** [notepad-plus-plus/notepad-plus-plus#2574]
Hi, awesome Notepad++ team! I just thought, it would be cool to have a pre-defined Golang language! Also, you could (optionally) automatically change the font to [their new font](https://blog.golang.org/go-fonts) when Go is selected! Just a simple idea!

Thanks,
LEGOlord208
(Bad name, I know)

**Comment by dknippers0** [comment]
You van find User-Defined Language files for golang here http://docs.notepad-plus-plus.org/index.php/User_Defined_Language_Files
As for the font, you will have to add that interesting font yourself :-)

**Comment by linquize** [comment]
See also #1222

**Comment by LEGOlord208** [comment]
The user defined language is buggy like they usually are. I am using that user defined language, but keywords gets canceled with an ending semicolon et.c.

As for the font, I didn't notice you could change font for user defined languages, only for normal languages.

Anyways it'd be awesome to have built in!
And thanks for the duplicate warning linquize. I'll research if it already exists next time. However, that issue was a year ago, so I could proooobably not add a comment there because of necroing. No idea

As you can see I'm nooby with Git :(

**Comment by dknippers0** [comment]
You can email the creator of the UDL here -> ajstarks@gmail.com.
But if you can describe the problems in more detail here, perhaps I can help you fix it.

**Comment by LEGOlord208** [comment]
Dear dknippers0, sorry for the late response. The author will not be able to do anything as this is a problem with all user defined languages I am pretty sure.

**Comment by MetaChuh** [comment]
please use one of the golang udls like: https://gist.github.com/blinksmith/99e5234ea601af8ba8bfab35c8fbebef

thank you for your help and best regards.
