### ISSUE TITLE
[Feature Request] Command line option for encoding (utf-8)

### ISSUE THREAD

**Issue by asfernandes** [notepad-plus-plus/notepad-plus-plus#2578]
I use notepad++ as editor in gitconfig with options '-multiInst -nosession "$*"'. But it opens the new file in ANSI mode, but I want to write commit messages in UTF-8.

This requires a manual click in the menus to convert the file.

I suggest a command line option to set the encoding of the opening file.

**Comment by asfernandes** [comment]
May you explain why closed with wontfix?

**Comment by MetaChuh** [comment]
my apologies.
after 2 years of inactivity, i assumed that you have already found that setting.

please go to `settings > preferences > new document` and set your encoding to `utf-8` and activate `apply to opened ansi files`, as seen at the screenshot below, if you want to set your default to utf-8 instead of ansi.

![Imgur](https://i.imgur.com/AarYeSx.png)

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by asfernandes** [comment]
I solved my problem in a different way. My git commit editor writes utf comments to the file before open notepad++, so it detects the file as utf8. I think it's a hack and would be much better to have that as a command line parameter. I don't want to change the default.
