### ISSUE TITLE
Cannot open files when you drag them into Notepad++.

### ISSUE THREAD

**Issue by AraHaan** [notepad-plus-plus/notepad-plus-plus#2641]
### Description of the Issue
Since the update from 7.1 to 7.2.2 opening a file via drag and drop is broken.

### Steps to Reproduce the Issue
1. Update to 7.2.2
2. Open Notepad++ v7.2.2 after installing.
3. Drag and drop any file into editor and it wont open.

### Expected Behavior
To open the file from dragg & drop just like v7.1 allowed me to.

### Actual Behavior
Files dragged & dropped into Notepad++ are not opened.

### Debug Information

```
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : E:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : MenuIcons.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppExec.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll NppSaveAsAdmin.dll PluginManager.dll PyNPP.dll Python Indent.dll PythonScript.dll ReloadButton.dll Translate.dll ZenCoding-Python.dll zoomdisabler.dll 
```

**Comment by dail8859** [comment]
Works fine for me...

```
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll DoxyIt.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 
```

**Comment by SinghRajenM** [comment]
There might be a case that Notepad++ is running as administrator (can see from debug info), while your explorer is running with lower privileges. I assume that you may have checked "open Noptepad++" on finish dialog which will elevate N++ (run with admin privilege).

If this is the case, then it is windows expected behavior. However, there are ways to handle it but again that will be lead to security issues otherwise why MS would have blocked it.
Some links for your reference - 
[stackoverflow](http://stackoverflow.com/questions/8239271/uac-elevation-does-not-allow-drag-and-drop)
[MSDN blog](https://blogs.msdn.microsoft.com/patricka/2010/01/28/q-why-doesnt-drag-and-drop-work-when-my-application-is-running-elevated-a-mandatory-integrity-control-and-uipi/)

I think that your test scenario is as below in which drop n drop won't work. 
![image](https://cloud.githubusercontent.com/assets/14791461/20864328/51aab404-ba12-11e6-80d4-21ac426c665f.png)

**Comment by SinghRajenM** [comment]
I feel, issue is similar to #159 and some other issues are referenced there.

@AraHaan 
Could you please confirm that issue is occurring when NPP is launched from finish page of installer or it is occurring even if you run NPP separately?

**Comment by AraHaan** [comment]
yep this might be the case.

**Comment by SinghRajenM** [comment]
@AraHaan thank you for confirmation.

**Comment by donho** [comment]
@dail8859 Are you sure that works for you in Administrator mode is ON ?

**Comment by dail8859** [comment]
@donho I did the following:

1. Logged into Windows as an administrator account
2. Installed latest N++
3. N++ is automatically launched once installation is complete
4. Dragged file into N++
5. Worked as expected

I think the problem is that in step 1 the user is logged in as a **non**-administrator account, then N++ gets launched as administrator (while explorer is still non-administrator). I don't have a non-administrator account on this computer to test with though.

**Comment by SinghRajenM** [comment]
@donho  and @dail8859 ,
> I think the problem is that in step 1 the user is logged in as a non-administrator account

In window 10 the case is little different. I use windows 10 and I have only single account (of course admin), but in this case explorer runs with lower privileges which is not elevated. This is default behavior which can be tweaked. [Run explorer with as admin](http://superuser.com/questions/1060456/is-there-any-way-to-run-file-explorer-as-administrator-under-windows-10)

**Comment by reapo** [comment]
I'm having this same issue, however my problem occurs when NPP is not on the main monitor.

**Comment by moymike** [comment]
EXACTLY...
Neither Explorer or Notepad++ are elevated.  I can drag and drop file into Notepad++ all day long on primary monitor.  If I move Notepad++ on monitor #2...  dropping files on to it does NOT work at all.   Strange, huh?
