### ISSUE TITLE
User-defined language styling not compatible with Themes

### ISSUE THREAD

**Issue by assad-ebrahim** [notepad-plus-plus/notepad-plus-plus#2662]
### Description of the Issue

Selecting a theme (e.g. choco) does not work in a language file that is using user-defined styling.  This appears to be because background colors defined in the user defined styling are not overridden by the theme.

### Steps to Reproduce the Issue

1. Define a user defined language - e.g. Forth.  Define a comment (let background color be white as per default)
2. Change Theme to Choco
3. Notice all comments are now patch-work white against choco black background.

### Expected Behavior

Consistency with all other languages, which take the background color from the theme.

### Actual Behavior

Seemed to take the background color from the user-defined styling.

### Debug Information

Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\totalcmd\ToolboxEditors\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 8.1
Plugins : MathPad.dll mimeTools.dll NppCCompletionPlugin.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppSnippets.dll NPPTextFX.dll PluginManager.dll Pork2Sausage.dll RunMeU.dll ScrollPastEOFUni.dll SnippetPlus.dll SpeechPlugin.dll SpellChecker.dll TopMostU.dll 

<img width="683" alt="screenshot 0400" src="https://cloud.githubusercontent.com/assets/24500021/21077036/d050e8ee-bf3c-11e6-808e-42dc50966156.png">
<img width="624" alt="screenshot 0401" src="https://cloud.githubusercontent.com/assets/24500021/21077037/d055f55a-bf3c-11e6-8227-4f1cf3eb68e6.png">
<img width="807" alt="screenshot 0402" src="https://cloud.githubusercontent.com/assets/24500021/21077038/d05d90f8-bf3c-11e6-8737-1234a99d9029.png">

**Comment by mrbrahman** [comment]
It would be nice if this issue is fixed soon! :simple_smile:

**Comment by LRWeber** [comment]
This isn't a bug: There's actually a simple fix to this.
In the Style Configurator, simply check the box next to "Enable global background colour". This will override the background color for any user defined languages as well!

![image](https://user-images.githubusercontent.com/29315109/39953368-5d5ed0de-555f-11e8-8e0d-945d254bb6f6.png)
Hope this helps!

**Comment by treier57lol** [comment]
Please fix this!

**Comment by LRWeber** [comment]
**If you check the box in the Style Configurator that says "Enable global background color", it makes for a partial workaround.**
It won't adopt the entire theme, but it will get rid of the unexpected ugly boxes. Unfortunately, if your custom language styling includes custom background colors to create a sort of highlighted effect, those will be overridden as well.


This behavior has to do with how user-defined languages are handled. The User Define Dialog allows you to define some basic, fairly comment elements like folding, comments, keywords, etc. Then you use the Styler to set specific colors/styles for these elements. This is quite different from how the built-in languages are handled; If you open the Style Configurator, you will see it has a Language list, and each language has its own Style list (which may include things like NUMBER, STRING, KEYWORDS, CLASSNAME). The actual appearance is defined for each named Style, which allows themes to intelligently swap out colors and more.

The Notepad++ documentation provides some explanations for the current language defining tools:

> Some of the 'standard' or 'more common' programming languages are not built with this tool. For example, Batch. And they cannot because they often have very idiosyncratic syntax features which are nearly unique. Making them as something parametrisable like in the User Defined Languages panel seems both unrealistic and unconvenient, as it would lead to an even more complex interface.
http://docs.notepad-plus-plus.org/index.php/User_Defined_Languages

> Nearly every complex language, be it about programming, scripting or other purposes, had its own quirks. This is why it is not realistic to expect User Defined Languages to duplicate the features of most Built-in Languages.
http://docs.notepad-plus-plus.org/index.php/Limitations_Of_User_Defined_Languages


I do appreciate the simplicity and the intuitive nature of the GUI based User Define Dialog. I agree that duplicating the features of the built-in languages via this panel is "not realistic". That can only really be achieved by more advanced users through writing code (Sublime Text's custom syntax definitions are a good example). However, **I do think there could be a similar way to assign a named Style to the user defined elements so they can be affected by themes the way the built-in languages are.**

**Comment by LRWeber** [comment]
Perhaps the Style Configurator could include a Language called "User Defined", wherein the Style list would have an entry for each element the User Defined Language currently provides a separate Styler for.

**Comment by Hser** [comment]
I know there could be a thousand ways that this could be done and none are likely to be pursued, but in case anyone else relates to this: what I would find useful is two simple checkboxes in each of the Stylers in the User Defined Language interface. The check boxes would allow you to apply the global theme to that background or foreground color. Similar to the "Enable Global Background Color" except this makes it more granular. For example, if the only thing that I wanted to be different from the global theme was the background color for comments, then I would go to the Comment Styler and _uncheck_ the proposed "enable global background color" checkbox for the background color in that specific Styler. Then whenever I change the global theme, every other styler will change with the theme except for the ones where I have unchecked the box. 

Hope that makes sense and can be useful to others.

**Comment by mckenzm** [comment]
We effectively need the Style configurator to override the UDL styling.  
The global background workaround is not a solution, as foreground colours are then too dark.
Using global background and foreground together removes syntax highlighting and we are back to notepad.

- We want UDL's named in the Style Configurator Language list
- We want styles to impact UDL's in the same way as builtin languages.
- It would be nice to have multiple file extensions for association *.c,*.hpp,*.h,*.win .cpp, .c++  etc.

**Comment by webketje** [comment]
Any news on this? I work a lot with markdown files and use dark background themes, and it's really a pain for the eyes. Currently the only workaround eg. if you have 5 themes you use on a regular basis, is to create 5 versions of the same UDL which is very cumbersome.

**Comment by Immueggpain** [comment]
We just need the UDL to able to reference the styles defined in themes, by names maybe?

**Comment by mwerle** [comment]
Given some of the rather esoteric languages already supported by Notepad++, the lack of native Markdown support does seem a bit odd.

Having said that, the most basic "solution" for custom languages is to give each group in the UDL editor (keywords, numbers, whatever) with a custom style name and remove the "Styler" from this editor entirely.  Custom style names could either be existing names (eg COMMENT) or user-defined ones (eg MYLANG_FOOBAR).

Then add support for UDLs to the theme editor. It can parse the UDLs and create entries for any custom language(s) and their custom styles.

This would neatly separate the language definition (what constitutes the parsing of the language) from the way it is displayed (ie, theming).

**Comment by tarihci** [comment]
I don' t know whether anyone is still following this, but I might have come across a solution to this.

My own problem: I wanted code folding functionality for my plain txt documents and I used another [solution](https://superuser.com/questions/626194/how-to-use-codefolding-feature-of-notepad-for-normal-text-documents) to enable that. However, this caused a bad color highlighting effect. I often use Obsidian theme and the global styler choices for foreground and background colors for code folding became a horrendous problem for me as shown by @assad-ebrahim above.

Solution: Go to Language > User Defined Language > Default Style > Styler
Right click on Background Color, then right click on Foreground Color. They become hatched, like [this](https://i.stack.imgur.com/Pt4Jw.png).
If you have the config box to the side, you will see the correcting effect of your clicks on the text in real-time. Solution idea came from [this](https://superuser.com/questions/695921/notepad-user-defined-background-colour) and [this](https://superuser.com/questions/160925/adding-a-new-language-to-notepad) exchange.
I think this would also work for correcting highlighting color discrepancy between custom changes in other languages and theme style colors.
Who would have thought of right clicking boxes, amirite?

I checked with other dark themes from the style configurator and the styler seems to dynamically adopt foreground and background colors of each theme without any further changes, so the problem seems to be solved.

**Comment by Zaf9670** [comment]
> I checked with other dark themes from the style configurator and the styler seems to dynamically adopt foreground and background colors of each theme without any further changes, so the problem seems to be solved.

Maybe a potential solution for this issue would be to simply have the UDL give a dark/light selection for the background/foreground. I wonder how other theme engines or programs determine when to adjust colors based on surrounding themes.

**Comment by LRWeber** [comment]
> I wonder how other theme engines or programs determine when to adjust colors based on surrounding themes.

Many have adopted the TextMate standard for naming different "contexts" such as keywords, comments, strings, etc. Language definitions are written in terms of those contexts, and then the themes can simply reference those named contexts to assign colors.
https://macromates.com/manual/en/language_grammars

This is actually fairly similar to what NP++ has exposed in the Style Configurator. Although I've yet to examine the source code, this seems to suggest that the built in languages use a similar mechanism (even if not the same naming conventions).

The real problem is that the UDLs doesn't use the same named mechanisms to decide styling. And, given that the UDL editor is already broken into these named elements, it frankly makes very little sense not to.

All that's really needed is a User Defined Language entry in the Style Configurator with the list of "styles" matching the definable elements in the UDL editor instead of making the styling a part of the UDL definition itself.

**Comment by MegMM** [comment]
I'm a hobby programmer and use Notepad++ with a customized theme in Style Configurator for Python and Default (and I'm happy with it). I would like to add a Delimiter in User-Defined Language. So I have my customized theme and tried to add one thing in the UDL and it ignored Style Configurator settings (as mentioned in earlier posts). I removed the Language, hit Delete. NPP did not restore my theme. I tried re-starting, but it turns out I had to manually delete the stylers.xml in order to restore access to Style Configurator. That would be lovely if there's a better way for that particular 'feature'.

As for Theme+UDL, I don't know enough to know if that is programmatically possible with NPP and UDL, but from a User perspective this process seems like it makes sense:

Style Configurator > my_own_theme 
Language > User-Defined Language 
The UDL would have an option to select a language from a pre-existing theme. Then fill in the UDL based on the language selected. Maybe it could only allow the choice of a single programming language per each UDL. That would be fine.

**Comment by Ekopalypse** [comment]
I think, nowadays, UDL is compatible with themes. Afaik, one only has to right click the color so that it changes to this

![image](https://user-images.githubusercontent.com/47723516/91611025-9bf49200-e97a-11ea-8689-e3a6f9bdf6ad.png)

and a value gets assigned which is replaced by the default back-/foreground color of the theme.

**Comment by sasumner** [comment]
Closing due to information provided by @tarihci and @Ekopalypse
