### ISSUE TITLE
Crash, current file gets wiped out

### ISSUE THREAD

**Issue by herbherb** [notepad-plus-plus/notepad-plus-plus#2672]
To whom it may concern:

When I was working on a CSS file of several hundred lines length, Notepad++ crashed (reason unknown). The problem is that the file I was working on was empty (0 bytes) after the crash, thus my work done sadly lost. (I always save new changes immediately while working on a file.) The two other files open in Notepad++ at the time were not affected.

Here is the crash dump:

Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : ClipboardHelper.dll ColorPicker.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

Cheers!

**Comment by donho** [comment]
I would suggest you remove ColorPicker.dll from your plugin directory.
Please let me know if it's the culprit.

Regards,
Don


----- Mail original -----
De: "herbherb" <notifications@github.com>
À: "notepad-plus-plus/notepad-plus-plus" <notepad-plus-plus@noreply.github.com>
Envoyé: Lundi 12 Décembre 2016 17:35:03
Objet: [notepad-plus-plus/notepad-plus-plus] Crash, current file gets wiped out (#2672)



To whom it may concern: 

When I was working on a CSS file of several hundred lines length, Notepad++ crashed (reason unknown). The Problem is that the file I was working on was empty (0 bytes) after the crash, thus my work done sadly lost... 

Here is the crash dump: 

Notepad++ v7.2.2 (32-bit) 
Build time : Nov 27 2016 - 16:31:07 
Path : C:\Program Files (x86)\Notepad++\notepad++.exe 
Admin mode : OFF 
Local Conf mode : OFF 
OS : Windows 7 
Plugins : ClipboardHelper.dll ColorPicker.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

Cheers!

**Comment by herbherb** [comment]
Thanks Don. So it's been known to happen with color picker? I've removed it. Anyway, if the crash occurs again, I'll let you know here. This was the first time, had the same thing a year or two ago with an older version but not since, the real problem is not the crash, but that the file gets wiped out.

**Comment by donho** [comment]
Yes, please let me know if crash still happen.

----- Mail original -----
De: "herbherb" <notifications@github.com>
À: "notepad-plus-plus/notepad-plus-plus" <notepad-plus-plus@noreply.github.com>
Cc: "Don HO" <don.h@free.fr>, "Comment" <comment@noreply.github.com>
Envoyé: Mardi 13 Décembre 2016 10:15:35
Objet: Re: [notepad-plus-plus/notepad-plus-plus] Crash, current file gets wiped out (#2672)



Thanks Don. So it's been known to happen with color picker? I've removed it. Anyway, if the crash occurs again, I'll let you know here. This was the first time, had the same thing a year or two ago with an older version but not since, the real problem is not the crash, but that the file gets wiped out.

**Comment by SinghRajenM** [comment]
@MetaChuh Since no update from user for a long time. I feel, this ticket can be closed.
