### ISSUE TITLE
feature request: shift+scroll for horizontal scrolling

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#2682]
### Description of the Issue

notepad ++ does not support horizontal scrolling with combination "shift+scroll" like Atom editor or Chrome browser

**Comment by mlochd** [comment]
if someone could send me in the right direction to look at the specific code where the changes need to be done, I wouldn't mind working on it myself;  if not I am sure it would be much easier for whoever built the scroll functions to make the changes

**Comment by stonecrusher** [comment]
Horizontal scrolling would be nice to have as a free shortcut.
For me *alt + scroll* would be more convenient or something like *shift + numpad*.

**Comment by pro-grammr** [comment]
I would really like this feature to be implemented, too!

**Comment by TroglodyteGuy** [comment]
I would also like to see a change. I use the mouse scroll wheel to move vertically in documents. For LONGER documents, it requires either a lot of scrolling or moving the mouse to the vertical scroll bar and dragging it up/down.

I would love to see the SHIFT key used to modify scrolling behavior. If I'm rolling the mouse wheel, use the mouse properties (typically 3 lines at a time). But if I hold down the SHIFT key and then use mouse scroll wheel, scroll one entire screen of text each click of wheel (up or down).

This allows for fast scrolling of large documents.

**Comment by vin7t123** [comment]
We want it too.

**Comment by jabcreations** [comment]
CTRL+Scrollwheel would fit my needs, not sure why ALT or Shift are desired; probably some other software? I'm a web developer so I don't know software development. Perhaps a simply set of options for which modifier key is used so everyone is happy? I dislike the current setting of the text size being changed on CTRL+Scrollwheel.

**Comment by stonecrusher** [comment]
@jabcreations Changing textsize/zoom with CTRL+wheel is pretty much standard everywhere. Shouldn't be changed.

**Comment by jabcreations** [comment]
@stonecrusher Oh, you're undeniably correct! Let's remove _all_ of the preferences and set everything the way you want all the time in all applications.

**Comment by stonecrusher** [comment]
I didn't say there should be no option. No need for cynicism.

**Comment by dopedup** [comment]
Oh what I'd do to have this feature. I have ridiculously long ovsdb table results ranging 10s of pages horizontally. And it is a MAJOR pain in the a$$ to analyze those results by dragging that little scroll bar on the bottom. Could we please have this feature?? Or at least a plugin?

**Comment by jabcreations** [comment]
@dopedup In a few months if money permits I'd be willing to sponsor someone to implement the feature. Unfortunately I don't know the code and am far from having the luxury of time to learn much less make an attempt. Ignore stonecrusher, some people think only their preferences are valid.

**Comment by monoblaine** [comment]
I'd love to see this implemented natively; but until then, I'm using the following AutoHotkey script:

```ahk
#IfWinActive, ahk_class Notepad++
    ~Shift & WheelUp::  ; Scroll left
      ControlGetFocus, fcontrol, A
      Loop 3  ; <-- Increase this value to scroll faster.
        SendMessage, 0x114, 0, 0, %fcontrol%, A  ; 0x114=WM_HSCROLL; 0=SB_LINELEFT
    return

    ~Shift & WheelDown::  ; Scroll right
      ControlGetFocus, fcontrol, A
      Loop 3  ; <-- Increase this value to scroll faster.
        SendMessage, 0x114, 1, 0, %fcontrol%, A  ; 0x114=WM_HSCROLL; 1=SB_LINERIGHT
    return
#IfWinActive
```

**Comment by stonecrusher** [comment]
@monoblaine Thank you, works well and I love the option to set the scroll speed!

@jabcreations Why are you bashing me again?
In my first post I vote for a free shortcut. So everyone can have what he/she wants. If you want to override living standards like `ctrl + scroll = zoom` it's your thing, but I strongly recommend not to do so by default.

**Comment by jabcreations** [comment]
@monoblaine Brilliant!

It took me a few minutes to figure it out since the AutoHotkey installer failed and I had to extract the program.

First save the script as **example.ahk**. Then when opening the file from Explorer associate it with **AutoHotkeyU64.exe**.

I can make a batch file to load the script first and then launch Notepad++ however how do we either close the script if it's running or not have it spawn an error if it already is?

@stonecrusher Dude, you're like one of those nubs who panic if someone is smart enough to disable their pagefile and you start drama because someone found a better way to do something. You are entitled to your preferences but the moment you tell someone else that they can not do something or should do something differently because others already are you end up wasting everyone's time. Either learn to participate in a constructive fashion or take your drama else where.

**Comment by monoblaine** [comment]
@jabcreations you can right-click the ahk file and click "Compile Script" which will create an executable file. Then you can have Windows run that file during startup.

**Comment by jabcreations** [comment]
@monoblaine So I have two of three things figured out. I converted to CTRL (literally) instead of Shift (not sure if case-sensitive or not?). I'm posting all of this to hopefully help someone else out.

The only thing I did not get working was increasing the integer did not produce a faster horizontal scroll.

I wanted to have this run for my shortcut for Notepad++ which uses the following as a batch file (Notepad++.bat for the full file name instead of the Notepad++ directory which I will create a shortcut to and change it's icon):

```
CD C:\MEDIA\OFFICE\Notepad++
start autohotkey_ctrl_horizontal_scrolling.ahk
start notepad++.exe
```

I also added the first line which will silence running the script multiple times. I named the file **autohotkey_ctrl_horizontal_scrolling.ahk**.
```
#SingleInstance force
#IfWinActive, ahk_class Notepad++
    ~CTRL & WheelUp::  ; Scroll left
      ControlGetFocus, fcontrol, A
      Loop 64  ; <-- Increase this value to scroll faster.
        SendMessage, 0x114, 0, 0, %fcontrol%, A  ; 0x114=WM_HSCROLL; 0=SB_LINELEFT
    return

    ~CTRL & WheelDown::  ; Scroll right
      ControlGetFocus, fcontrol, A
      Loop 64  ; <-- Increase this value to scroll faster.
        SendMessage, 0x114, 1, 0, %fcontrol%, A  ; 0x114=WM_HSCROLL; 1=SB_LINERIGHT
    return
#IfWinActive
```

**Comment by stonecrusher** [comment]
@jabcreations 
I'm not sure if you understood me correctly, at least I don't understand what you want from me.

I'll quit now, shaking my head about your behaviour.

**Comment by dopedup** [comment]
Thanks for the ahk script!

Though I can't help but notice, or help me out if it's just on my system. The scroll speed in the script doesn't feel like scroll "speed" and more like a buffered value for number of characters to scroll at a uniform pace. If I increase the number to any absurd value it just increases the number of characters to scroll but at the same speed. Slightly annoying and doesn't really feel like native mouse scrolling.

Guess we've to make do with it for the moment till anyone comes up with a native scroll feature.

**Comment by yaakov1111** [comment]
this is a very important feature , and very easy to implement , please hurry it's development

**Comment by elizabethexpialadocious** [comment]
ctrl+scroll_wheel for horizontal scrolling is fairly common among apps and would be great to see in notepad++

**Comment by ffatheranderson** [comment]
I agree this is MUST have feature to be able to scroll horizontally with "Shift + mouse wheel scroll".

**Comment by jmbockhorst** [comment]
I can work on implementing this.
