### ISSUE TITLE
Notepad should respect the indentation style of the file

### ISSUE THREAD

**Issue by SvetlinZarev** [notepad-plus-plus/notepad-plus-plus#2760]
### Provide a more detailed description to the issue itself
NP++ always uses tabs or spaces depending on it's configuration. Instead it should detect if the file uses tabs or spaces and use that respectively.

### Set of steps to reproduce this issue 
1. Open a file that uses spaces
2. Indent something using tab, or just press "enter" to let NP++ auto indent the next line

### What did you expect to happen 
If the file uses spaces I'd expect that NP++ will use spaces as well. If the file uses tabs -> NP++ shoudl use tabs. If the indentation cannot be discovered -> use the default settings.

### What actually happened 
NP++ always uses its settings and does not perform space/tab discovery

### Debug Info can be found under under the "?" menu 
Not applicable

### Feel free to include any other info, such as screenshots, etc 
Other info: NP++ should do the same for \n and \r\n line endings

**Comment by MAPJe71** [comment]
Have a look at the EditorConfig plugin and the [EditorConfig website](http://editorconfig.org/), it might solve your problem.

**Comment by SvetlinZarev** [comment]
Hi,

I wanted to report this as an "enhancement request", not a "problem" :)

That plugin allows me to define different configuration for different files and does not allow for dynamic discovery. So when I checkout a new project I have to manually check its indentation style and line endings and then write down that config in the file. For me it's a no-go because I use NP++ for files on which I do not have to do a lot of changes (i.e. a files I edit and then forget about). So this means that I have to create separate config for basically every file have to edit.

Of course this is not such a big issue, but I think implementing this feature would make a lot of people happy :)

Best regards,
Svetlin

**Comment by gstavi** [comment]
This is a patch I once upon a time prepared for this issue. It selects indent type according to lines above.
[https://github.com/gstavi/npp/blob/master/patch/0003-Improve-auto-identation-logic.patch](https://github.com/gstavi/npp/blob/master/patch/0003-Improve-auto-identation-logic.patch)

However, another important related fix is that increasing/decreasing indent will respect current indent type and this one need to go in Scintilla rather than NPP.
[https://github.com/gstavi/npp/blob/master/patch/0004-Indent-change-maintains-indent-type.patch](https://github.com/gstavi/npp/blob/master/patch/0004-Indent-change-maintains-indent-type.patch)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
