### ISSUE TITLE
Non-printable characters markers are not zoomed with the rest of text

### ISSUE THREAD

**Issue by KOLANICH** [notepad-plus-plus/notepad-plus-plus#2789]
![screenshot_20170113_184208](https://cloud.githubusercontent.com/assets/240344/21936047/374087ca-d9c9-11e6-9e9a-a1258fdc6d1e.png)

Open this in a separate tab and zoom in. You will see tiny dots which are for spaces.

**Comment by MetaChuh** [comment]
notepad++ can not open images in tabs

**Comment by KOLANICH** [comment]
>notepad++ can not open images in tabs

I meant a browser tab, not npp one.

**Comment by sasumner** [comment]
I am double confused by the statements here, but is the original complaint that the "tiny dots...for spaces" are not zoomed when the zoom level is changed?  If so this is rather by-design and the size of the "tiny dots" can (and should) be changed independently, at least that's one man's opinion. :)

**Comment by KOLANICH** [comment]
>so this is rather by-design and the size of the "tiny dots" can (and should) be changed independently

The problem is it's hard to notice them alongside of the magnified text. This issue completely defeat their purpose.

**Comment by sasumner** [comment]
Well, you *can* change the size of the "tiny dots", but it takes some effort (plugin).  Since it takes a plugin, one could use a scripting plugin and write a script that as the zoom level changes, the dot size changes as well, but it probably wouldn't be a one-to-one correspondence.  Plus I'm sure you don't want a workaround, you want something done inside Notepad++ to "fix" this. :)

**Comment by sasumner** [comment]
Actually, I personally don't find the dots all that small (meaning to the point where I wouldn't notice them), even when I'm zoomed in to a level that is "uncomfortable" otherwise.  But apparently YMMV.  Maybe for you I'd suggest a different color for them as something to try out?
