### ISSUE TITLE
Notepad++ ask too much when checking out with GIT/SVN/etc.

### ISSUE THREAD

**Issue by mirlip** [notepad-plus-plus/notepad-plus-plus#2867]
### Description of the Issue
When checking out a git folder, Notepad++ ask for each file if it should be reloaded and change focus. It would be great to have a "reload all" and "reload nothing" to keep focus on current file and save a lot of clicks.

### Steps to Reproduce the Issue
1. open 2-n files of a project managed with Git
2. checkout another branch or commit
3. you have to click yes for every file you opened to reload them (and the yes button is moving even sometime, making you click no if you click very fast.)

### Expected Behaviour
Have an option like in other program to apply decision to all files

### Actual Behaviour
Decision has to be taken for each file and focus is loosed.

**Comment by glennfromiowa** [comment]
Regarding

> ...keep focus on current file

it should be noted that after the **Steps to Reproduce the Issue**, the focus is retained on the last file that you have clicked _Yes_ or _No_ on. Based on other wording, I believe the **Expected Behavior** is that the focus should be retained on the file that had the focus before the prompt(s) appeared, regardless of whether there is a _Reload All_ or _Reload None_ button. I'd like to propose an alternate, but related scenario:

### Description of the Issue
When files have changed since Notepad++ last had the focus (whether due to checking out a git folder, changed log files, or other reason), upon regaining focus, Notepad++ displays a confirmation dialog for each file, asking if it should be reloaded, and then the MDI focus is changed to the last document confirmed. This behavior is time-consuming and has risk due to the fact that the position of the dialog box sometimes moves between file confirmations, making it likely to click a button you didn't intend to if confirming many files. Options to _Reload All_ or _Reload None_ could reduce that risk. Also, especially with multiple files being changed externally, the logical, expected behavior would be that the last file loaded (or the file previously having the focus, if no new file opened) would now have the focus. Note that a confirmation dialog also appears when loaded files have been deleted externally. In this case, however, the focus is only retained on the confirmed file if **Yes** is selected (to retain non-existent file).

### Steps to Reproduce the Issue
1. Open 2-n files in Notepad++
2. Make or allow changes in 2-n files externally, whether through Git, allowing log files to update, etc.
3. Open 1-n files associated with Notepad++, for example, using the OS shell or utility with similar function.
4. Click on each confirmation dialog that pops up, confirming whether to reload each file or not.

### Expected Behavior
1. Have buttons available to _Reload All_ or _Reload None_ of the files, in addition to the _Yes_ and _No_ buttons.
2. Restore the focus to the last file loaded from an external source, or to the file that had the focus before confirming the file reload(s).

### Actual Behavior
1. Each file must be confirmed individually, with care being taken to click on the intended button.
2. The focus is on the last to be confirmed, and you have to scan the tabs to find the file(s) that were opened.

**Comment by mirlip** [comment]
@glennfromiowa exactly what I meant. Thanks for helping other understand what I mean.

**Comment by mirlip** [comment]
what does donho wait to implement the 1600++ open issues :D I'll patiently wait the 20 years it will need to get a better confirmation box :)

**Comment by Gusgus01** [comment]
See #2724 

This feature is also requested in that issue.

**Comment by freggeldoe** [comment]
Same here. Drives me nuts that everytime I change branches I have to **confirm way too much** of these and then **search again for the last tab I worked on**.
