### ISSUE TITLE
UDL folding issues with CR or LF only

### ISSUE THREAD

**Issue by Yoshi72** [notepad-plus-plus/notepad-plus-plus#2873]
When defining your own User-Defined Language, Operators and Delimiters will shift the folding by one line for every Operator and Delimiter that is followed by only a CR or LF, but works just fine if it is a CRLF
As a result, not only will the folding go beyond the original codeblock, it will also shift following codeblocks by the same amount of lines.

A couple of screenshots to highlight the issue:
Bugged:
![cr](https://cloud.githubusercontent.com/assets/8786791/22627405/dbc4ff0a-ebc2-11e6-8cd5-7bce4a042a13.PNG)
![lf](https://cloud.githubusercontent.com/assets/8786791/22627404/dbc46ad6-ebc2-11e6-9cf7-0672bac272c2.PNG)

Working as intended:
![crlf](https://cloud.githubusercontent.com/assets/8786791/22627406/dbc653dc-ebc2-11e6-901e-d87ee172f52d.PNG)

Also "Folding in code 2 style (seperators needed)" will not highlight the keyword if its at the end of the file. Folding works still fine thought.

**Comment by rmcurtis** [comment]
This bug has been around for a while.  See [this stackoverflow post](http://stackoverflow.com/questions/23098102/udl2-folding-style-2-only-work-with-windows-eol-but-not-unix-eol) which links to an old bugtracker entry on sourceforge which is no longer accessible.

This means that code folding for UDLs is broken for Unix EOL files.

**Comment by davidreza** [comment]
I've been having the same issue since a long time ago. The more comments there are, the more strange behaviour of folding blocks. Is this issue going to be attended? I use Notepad++ mostly for review and analysis of ABAP code so I have my own ABAP User Defined Language information created.

I've been updating Notepad++ ever since and there is no fix at all. What can be done to push this issue and get it fixed?

Any example of code that you need to get this solved, I will be glad to share.

**Comment by rmcurtis** [comment]
@davidreza  I think this issue is solved in #3372 which has been approved but hasn't been merged yet.

**Comment by davidreza** [comment]
@rmcurtis Thanks for the reply Ryan! I did see those threads, however, my problem seems to be a little different since the issue in my case happens using whatever: CRLF or CR or LF, and the related issues claim that using CRLF works fine (which is what I actually use).

However, lets see if the solution of #3372 works once merged.
