### ISSUE TITLE
session.xml kept no session after Windows 10 force auto-reboot

### ISSUE THREAD

**Issue by mengmo** [notepad-plus-plus/notepad-plus-plus#2876]
I opened several tabs while working.
but sometimes when I was not in front of my PC, Windows 10 will force auto-reboot.
after that, I lauch Notepad++ ,there is only an empty window.
the session.xml file only have these inside
```
<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="0" />
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>
```

**Comment by raipat** [comment]
I had the same issue today, windows 8.1pro, after graceful reboot (via shutdown /r on cmdline) with notepad++ opened.

**Comment by jan1980** [comment]
Same issue with Notepad++ 7.5.6 32 bits. Horrible feeling lost 50 opened tabs.

**Comment by expwnent** [comment]
I had the same issue just now. I had to power off my machine and all my open files were missing.

My settings were also reset to defaults: the font size was smaller.

**Comment by MetaChuh** [comment]
please disable automatic windows update, or close notepad++ if you leave your pc.
please save all your data of all applications, before you leave a windows 10 pc unattended.

**Comment by expwnent** [comment]
I can save my files. That's not the problem. It's the session data and personalization data that gets deleted.

What should we do about Windows crashing or other situations where you have to reboot and you can't save anything because it's not responding? It happens and it can't be prevented entirely. Notepad++ isn't the only program that saves session data continuously, but it's the only one on my machine that I've had delete all session and personalization data because of power failure / forced reboot. That leads me to think it's a solvable problem.

**Comment by donho** [comment]
Fix by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6000f3bb21a42a4d28d068617e0dc642ef739b26
