### ISSUE TITLE
run as administrator problem

### ISSUE THREAD

**Issue by ranjan-ranjan** [notepad-plus-plus/notepad-plus-plus#2894]
I have started notepad++ in normal user mode. When I start it in administrator mode, it just reloads itself (in normal mode). Snapshot is attached for reference.
![1](https://cloud.githubusercontent.com/assets/16834561/22819726/662bcab4-ef99-11e6-88b7-3ac395206f1a.png)

**Comment by SinghRajenM** [comment]
Npp is configured (by default) as single instance application. So when you launch it in normal user mode and then try to launch again in admin mode, it shows the same instance instead of new instance (process) and that is expected behavior.

If you really wish to get it work (as you expect), then configure it as multi instance (via => settings->Preferences->Multi-Instance->Always open in multi-instance mode).
