### ISSUE TITLE
change.log Always re-opened on application entry [7.3.1]

### ISSUE THREAD

**Issue by mancoast** [notepad-plus-plus/notepad-plus-plus#2896]
### Description of the Issue

Recently auto-updated to Notepad++ 7.3.1 32bit on host: winsvr2016 x64.

### Steps to Reproduce the Issue

1.  Execute software.
2. Close "change.log"
3.  close/re-open software

### Expected Behavior

"change.log" remains closed

### Actual Behavior

"change.log" always present in open document tabs

### Debug Information

Notepad++ v7.3.1   (32-bit)
Build time : Jan 17 2017 - 00:21:10
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

![image](https://cloud.githubusercontent.com/assets/7040493/22827095/0c24391e-ef64-11e6-9514-f95c7392a62b.png)

**Comment by dail8859** [comment]
See [this](https://notepad-plus-plus.org/community/topic/13102/changelog-opens-every-time-i-start-npp) discussion on the forum. It seems to be due to pinning the instance of Notepad++ that was ran immediately after installing. 

So if you unpin the shortcut, open a fresh instance of N++, and then repin, it then everything should be fine.

**Comment by mancoast** [comment]
work-around confirmed.

**Comment by pryrt** [comment]
Please see [this NPP Community forum discussion](https://notepad-plus-plus.org/community/topic/13623/change-log-opens-every-time-software-is-launched-7-3-3/): the evidence is starting to point to it either being the installer's shortcut, or Win10 auto-pinning the installer's initial call to "notepad++.exe change.log".  If it were the user manually pinning the shortcut, it would make sense to ask the user to fix the shortcut.  But if it’s the installer that’s creating the bad shortcut, the long-term fix needs to be on the installer side.  And even if it’s Win10 that’s creating an additional “pin” (probably in the “recently added” or “recently used” or “frequently used” section) that includes the change.log – it might be helpful to see if there’s a way during install to convince Win10 to auto-pin the correct version of the shortcut rather than the change.log shortcut.  It seems rather inconvenient (dare I say “rude”) to ask every Win10 user NPP x64 user to manually fix auto-generated shortcuts when the evidence is pointing to it being either the installer directly, or Win10’s auto-pin behavior, that’s causing the “bad” shortcut, and not anything the user has control over.

As a thought for fixing it if it’s a Win10 auto-pin issue: I am assuming it’s when the installer auto-opens NPP with change.log that’s creating the incorrect auto-pin. I’ve never written an installer, but could the installer be made to open a “raw” copy of NPP first, then send a message to NPP to additionally open change.log – that way, the instantiation-command wouldn’t include change.log, so the Win10 auto-pin won’t include it either. I don’t know if that would work, but it makes sense to me.

**Comment by dail8859** [comment]
There does seem to be quite a few cases of users reporting this kind of behavior recently so it is possible something has changed either in the installer or something with Win10 that is causing this to happen. Either way it is very annoying and should probably be investigated at least.

I won't be able to look into this myself since I have no experience creating the installer or with Win10. Maybe @SinghRajenM has some ideas since they seem to be more familiar with the installer.

**Comment by SinghRajenM** [comment]
With current setup, npp is launched (from finish dialog) by executing a shortcut created in temp folder. This was done to make npp integrity level same explorer's integrity level, so that drag & drop functionality continues to work.

This is wired situation that first time pinning works in different way than the second time for same process.

1. Launch npp from installer page and pin it to taskbar
2. See its property.
3. Unpin it from taskbar and pin it again **without restarting npp**
4. See its property.

![image](https://cloud.githubusercontent.com/assets/14791461/25052699/bc4e86bc-2170-11e7-85ee-902376f29b34.png)

I'm going to submit a patch to handle it. Let's see how it goes.

**Comment by mancoast** [comment]
Thanks!

**Comment by glawrence** [comment]
I have version 7.4.1 (32-bit) and this issue is reported fixed in change.log as item 19. However it is not fixed for me, any ideas or suggestions please?

**Comment by SinghRajenM** [comment]
@glawrence 
> Update: sorry, should have read more closely! Unpinning and re-pinning fixed this

This issue should not occur with V7.4.1 at all assuming it is fresh installation. If this was not fresh installation, then previous version might have already pinned to task containing "Change.log" as argument.

Just to understand whether issue still persists, few questions for you - 

1. Did you install V7.4.1 freshly? If not, then the previous version was pinned to task bar?
2. If it occurs with fresh installation, then could you share us properties of pinned item showing shortcut tab?
3. Please share debug info (Open Notepad++ -> Menu -> ? -> Debug info)

**Comment by glawrence** [comment]
Sorry for the delay:

1. I installed over 7.4 and that over a previous version, and yes the previous version was pinned
2. Having read above I just unpinned 7.4.1 and re-pinned it and all was well
3. No need, I don't think

So, all good and happy days now. Thanks
