### ISSUE TITLE
Needs more columns (feature request)

### ISSUE THREAD

**Issue by skipmalley** [notepad-plus-plus/notepad-plus-plus#2901]
Thanks for making this very nice an powerful editor.  I use it a lot.

I use 2 24 inch monitors at work and 2 30 inch monitors at home.  I know it has the ability of opening 2 views that can be the same file.  I would like to open more.  I would split 1 monitor into 3 columns of the same file and could work on 195 lines of code on one 24 inch screen.  That would be great.  If you could allow more columns of the same file, I might even use both screens at the same time with 390 lines of code.  That would be awesome.

**Comment by vlakoff** [comment]
390 lines at once…

![heavy breathing](https://cloud.githubusercontent.com/assets/544424/23108316/04e605d8-f70c-11e6-8666-e7e776009099.jpg)

**Comment by MetaChuh** [comment]
more than 2 views will currently not be implemented.

thank you for your help and best regards.

**Comment by GaryBloom** [comment]
Any change of plans on this? Having more than two views would be helpful, and it would also take away an advantage of other editors (like Atom) which already support more than two views.
The workaround of opening more than one instance of N++ is flawed, since one of the main advantages in working in a single instance is avoiding conflicts between more than one instance. Although reload can be automatic, it is still possible (and annoying) to make changes in one instance, only to be told that the file has been changed elsewhere.
Any thoughts?

**Comment by Ekopalypse** [comment]
My thoughts: 
Even though I like the idea of having more than 2 views I don't think it would be easy to solve.
If I see it right, such a change would probably make most, if not all plugins stop working at once.
But I wouldn't be against such a change, well, I'm not a plugin maintainer either (not yet).
