### ISSUE TITLE
Hitting space creates newline

### ISSUE THREAD

**Issue by Alex-Brian-Carol-Deji** [notepad-plus-plus/notepad-plus-plus#2919]
### Description of the Issue
Create a line of text that wraps at least once (i.e. activate the wrapping feature).
Go to the start of the line and hit Space. Everything will move down one line.

Debug info:
Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll SelectNLaunch.dll SpellChecker.dll

**Comment by SinghRajenM** [comment]
I don't think, this is an issue. Same behavior can be seen in notepad (windows default) as well. Moreover, it can be seen in MSWORD as well.

However, this happens only when whole text is continuous. But in real word, I didn't single word/scenario where text is continuous as described in bug.

![image](https://cloud.githubusercontent.com/assets/14791461/23080524/10f09596-f577-11e6-86ce-9a69b67dd16a.png)

**Comment by Alex-Brian-Carol-Deji** [comment]
That is definitely not true, because my old Version of Notepad++ did not
have this bug (5.x) and it doesn't happen in Windows Notepad either.

Am 17.02.2017 um 20:41 schrieb Rajendra Singh:

**Comment by Pyre909** [comment]
Hi All,

I can confirm this behavior occurring in Windows Notepad, Microsoft Word, and  Notepad++ when text is continuous, but I do not see it for a single word. Even the internal editor for an SFTP application that I use displays the same behavior. The only one that I have tried that does not have this "bug" is Sublime Text itself. All Windows updates are current.

Notepad++ v7.3.2   (64-bit)
Build time : Feb 12 2017 - 23:17:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll LuaScript.dll mimeTools.dll NppConverter.dll

**Comment by MAPJe71** [comment]
Why is it an issue? What is the expected behavior?

**Comment by Alex-Brian-Carol-Deji** [comment]
Weirdly enough, at my home PC everything is fine, even after I updated
Notepad++ just now from 7.2.2 to 7.3.2. I type "Space" at the beginning
of the new line and the expected behavior happens, i.e. a space appears
at the beginning of the new line withouth anything else happening (yes,
the line was wrapped, too). I will check it again at work on Monday.
Maybe my installation is messed up.

Am 18.02.2017 um 01:12 schrieb Menno Vogels:

**Comment by bugith** [comment]
This is not a real line that is added, just some kind of spacer. We also can see it when typing a long word that is shorter than the edition window width then we shrink window width. This doesn't happen if we insert a space in the middle of the word and shrink the window (neither if the long ~word~ is made only with spaces, in which case adding a(nother) leading space won't trigger the word break). When it happens, it shows like some interpreted \n was inserted before the space. I fact this seems to be because the word wrapper always tries to keep the space on the same line as the precedent word in the same line or IOW breaks the line after the space. When the space is first on the line, same happens : line is broken after after this space, what can be highlighted by selecting the whole line.
Also, something Alex didn't say, inserting a number of leading spaces moves the whole line to the right this same number (minus one) of character width (no real space(s) inserted). And this neither M$word not notepad do it ;-) ... just to say a contrario that what these 2 (do not) do isn't always the best thing to (not) do. 
All this seem to be developers decisions about visual ergonomy.

Although, being a new notepad++ user (from today :) although I heard about for years) and trying to see I met the same xp32 ~bug~ I discovered the feature Display>Special symbols>Show all, displays a space dot spacer that is hardly visible, and worse when the current line background is coloured (what is desirable although). Maybe a **fater** dot or solid red would help old eyes.

Thank you for this great piece of soft

**Comment by Alex-Brian-Carol-Deji** [comment]
It's weird, but when I checked my Notepad today, the problem was gone.
Looks like it's one of those difficult bugs that are difficult to
reproduce. I guess a reboot was all that was required.

But thanks for the help!

Cheers
Alex

Am 19.02.2017 um 19:28 schrieb bugith:
