### ISSUE TITLE
Auto Language detection when copy-pasted into a new tab

### ISSUE THREAD

**Issue by xmrkkr** [notepad-plus-plus/notepad-plus-plus#2922]
### Steps to Reproduce(replicate) the Issue
1. Launch npp editor
2. Create a new tab (blank page)
3. Copy and paste some editor aware code snippet (xml) into the newly opened tab
4. Npp should automatically detect the language and highlight it accordingly, when it's respective menu item has been enabled (see attached screenshot)

### Expected Behavior
Npp should automatically detect the language and highlight it accordingly, when it's respective menu item has been enabled (see attached screenshot) otherwise work as is.

### Actual Behavior
This is a feature request

### Debug Information

![image](https://cloud.githubusercontent.com/assets/720559/23098621/3ed899ec-f679-11e6-8b6b-c7375386becf.png)

**Comment by brute4s99** [comment]
any ideas ?
I'm interested in this...

**Comment by MetaChuh** [comment]
language detection via code instead of via file extension will not be implemented, due to the syntax similarities of many languages leading to unpredictable false detections.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by lzp00** [comment]
+1 for this feature

**Comment by page200** [comment]
> syntax similarities of many languages leading to unpredictable false detections

For languages with similar syntax, false detections are not a big problem, because syntax highlighting will be similar. That will be much better than nothing, because it will allow to much faster understand code snippets.

**Comment by CennoxX** [comment]
There are some projects like [guesslang](https://guesslang.readthedocs.io/en/latest/) to auto detect the language, where that work is already done. So at least an addon / python script to detect the language should be possible.

**Comment by MikeAtBS** [comment]
Hi, in my opinion, at least autodetection of pasted XML should be available as it is somewhat unique. Maybe JSON too. An irritating example is when I apply XSLT transformation which generates a new tab with output XML and each time I have to manually select XML language.

**Comment by alankilborn** [comment]
>An irritating example is when I apply XSLT transformation which generates a new tab with output XML and each time I have to manually select XML language.

As Notepad++ itself doesn't do "XSLT transformation", it seems this specific complaint is against a plugin (XMLTools).  In other words, if XMLTools is going to open a new tab, it could set that tab's language to XML...

**Comment by MeWantCookiee** [comment]
Are there any updates to this issue?

**Comment by pryrt** [comment]
There are no updates, because the request was closed.  As was said in 2019 when it was closed, the heuristics are too complex.

And, not said back then: having to trigger those heuristics everytime text is pasted into an empty document, but not when text is pasted into a document that has any contents, means that you'd literally have to check the length of the file every time you paste text, to decide whether or not to do the heuristics.  That's a lot of overhead, considering you are only going to be pasting one time to any given empty document, whereas you may be pasting hundreds or thousands of times while editing a populated document.  It's a grossly inefficient task, when considered across all possible pastes.

Especially when there are some easy alternatives:
- Save the file with the right extension immediately after the paste.  Doing this will make it immediately go to the right syntax highlighting for the extension.  This is best for data safety, as well, since it will immediately establish a saved file, which is best practice.
- Right click on the `new 1` tab name, and name it `new 1.xml`, which will immediately do the highlighting for that extension, without forcing you to save the file
- If you are usually creating files of a specific type (like XML), then you can set **Settings > Preferences > New Document > Default language** to the specific type (ex: XML), and then every time you create a `New #` tab, it will be assigned that type
- If you have a handful of languages you use, you trick Notepad++ into giving it a keyboard shortcut:
    - Unfortunately, Shortcut Mapper doesn't let you assign shortcuts directly to Language menu entries
    - You can assign a shortcut to a macro, but you cannot _record_ the Language change in a macro... but you can _play_ a macro that uses that.
    - Here's an example of a macro I use, which does **File > New**, changes to **Perl**, then asks me to save the file:
        ```
        <Macro name="NewPerl" Ctrl="yes" Alt="yes" Shift="yes" Key="78">
            <Action type="0" message="2172" wParam="0" lParam="0" sParam="COMMENT: 41001 = File|New" />
            <Action type="2" message="0" wParam="41001" lParam="0" sParam="" />
            <Action type="0" message="2172" wParam="0" lParam="0" sParam="COMMENT: 46013 = Language|Perl" />
            <Action type="2" message="0" wParam="46013" lParam="0" sParam="" />
            <Action type="0" message="2172" wParam="0" lParam="0" sParam="COMMENT: 41008 = Save|As" />
            <Action type="2" message="0" wParam="41008" lParam="0" sParam="" />
        </Macro>
        ```
        (the 2172 lines are not needed, except as a way of adding "comments" to the macro, to help you understand what each line does)
   - If you remove the last two lines from the macro, it will skip the **Save As**
   - If you remove the first two lines, it will skip the **File > New**
   - This Notepad++ Community Forum [FAQ](https://community.notepad-plus-plus.org/topic/25400/faq-automating-notepad/2#:~:text=How%20to%20Cheat%20the%20Macro%20System) explains how to use a plugin like NppSpy to find the wParam value for the language you want.  Or, for the limited case of Language menu entries, looking in [menuCmdID.h](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/menuCmdID.h) and searching for `IDM_LANG` will show you all the languages, showing a `+ ###` (like `IDM_LANG_PERL` is `+ 13`), and you can add that to 46000 to get the actual value for the language (thus, Perl is 46000 + 13 = 46013), and you use that in the appropriate wParam.
   - After you save the manual macro in `shortcuts.xml`, you can exit Notepad++ and restart, and then you will have that macro available.
   - You can make similar macros for each of your frequent languages, so you could have a NewPerl, NewPython, and NewXML, if those were what you wanted.  (Or with only the middle two lines, ChangeToPerl, ChangeToPython, and ChangeToXML)
   - You aren't limited to that sequence.  You can record a macro to do what you want, save that macro, restart, then edit the macro to add the language-setting at the end. For example, here's a New then a Paste, then setting to XML
        ```
        <Macro name="NewPasteXML" Ctrl="no" Alt="no" Shift="no" Key="0">
            <Action type="2" message="0" wParam="41001" lParam="0" sParam="" />
            <Action type="0" message="2179" wParam="0" lParam="0" sParam="" />
            <Action type="2" message="0" wParam="46006" lParam="0" sParam="" />
        </Macro>
        ```
