### ISSUE TITLE
Delete Text Entries in Search/Find List Feature

### ISSUE THREAD

**Issue by Troglo37** [notepad-plus-plus/notepad-plus-plus#2931]
Description of the Issue

Sometimes I need to delete search entries because I no longer need them and it bumps off text that I’ve previously entered that I need.

I thought that all I had to do is click on the pulldown to show the list of search entries, highlight the text I want removed and press delete. 

So, it would be a great idea to add this feature. It would make the program even better.

Steps to Reproduce the Issue

Click on the binoculars on the toolbar, or click on Search > Find, 
Click the pulldown to show the list of text search entries.
Move the cursor on a text search entry and highlight it.
Press Delete.

Expected Behavior

For the highlighted text to be deleted.

Actual Behavior

Nothing happens.

Debug Information

Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by superbonaci** [comment]
I think instead of using delete it would be better to use SHIFT+DELETE like it's done in Total Commander. The DELETE alone is to delete things within the search box.

**Comment by pryrt** [comment]
Hey, @sasumner , the original requestor just harkened back in a new [forum conversation](https://community.notepad-plus-plus.org/post/66670) to your conversation in [this old forum thread](https://community.notepad-plus-plus.org/post/22075), saying that this ancient issue was still open.  Since you're now on the codebase side, rather than workaround/hacks, I thought I'd ping you to see if you were interested in tackling it (especially since you've done other search-and-replace stuff). :-)

**Comment by sasumner** [comment]
>I thought that all I had to do is click on the pulldown to show the list of search entries, highlight the text I want removed and press delete.

This is exactly how it works since Notepad++ 7.9.3 via this PR: #9396

**Comment by sasumner** [comment]
@pryrt I got to thinking about why you might not have remembered this.  I don't believe I changed the user manual in any way because of it.  Let's say I either (a) forgot, or (b) figured that the new behavior is how people sort of expect such dropdowns in Windows to work, so it wasn't worth documenting.  I'm going with (b).

**Comment by pryrt** [comment]
notepad-plus-plus/npp-usermanual#152 says that the answer is (c) pryrt forgot that you _had_ documented it in January. ;-)

**Comment by sasumner** [comment]
@Ekopalypse Is @pryrt to be admitted to our CRS (Can't Remember Stuff) club? :-)  Clearly I am President of the club.

**Comment by Ekopalypse** [comment]
@pyrt Welcome to the club :-)
Just FYI, I am standing for election as the new President of Forgetfulness.
If you vote for me you can be sure that I will forget again in no time. :-D
