### ISSUE TITLE
Option for notification on search wrapping

### ISSUE THREAD

**Issue by thdoan** [notepad-plus-plus/notepad-plus-plus#297]
When a search wraps to the top again, sometimes it is hard to see the icon flashing in the taskbar -- it would be great if there is an option to show a message box that says something like "Your search has wrapped to the beginning" when the search wraps (similar to Notepad2 editor).

**Comment by dail8859** [comment]
:+1:

**Comment by thdoan** [comment]
If a message box is out of the question, then maybe a "ding" sound when the search wraps?

**Comment by MetaChuh** [comment]
closed due to:
* a search top wrap can also be seen at the line numbers
(line numbers of the current view will be smaller than before, once a search has wrapped to the top)
* alternative: "ding" when reaching top or bottom is achieved by disabling wrap around, and using forward and backward search, either using
<kbd>enter</kbd> and <kbd>shift</kbd>+<kbd>enter</kbd>, or the <kbd><<</kbd><kbd>>></kbd> buttons.
