### ISSUE TITLE
[Feature Request / Bug Fix] Read-Only attribute not saved in session Xml file

### ISSUE THREAD

**Issue by salvarani** [notepad-plus-plus/notepad-plus-plus#2970]
### Description of the Issue ###
When saving a session where there are Read-Only documents, the Read-Only flag is not saved in the .XML session file; when restarting Notepad++ and loading the session, all documents are editable... now imagine that you have to re-apply the Read-Only flag to dozens of documents...

**Comment by andry81** [comment]
Is a better idea to just create a command line key to request new session where directly edit read only files w/o need to clearing the flag and further save it at a session level.

To save a file, Notepad++ can, for example:
1. remove the flag
2. save file
3. restore flag

For an ability to differentiate between readonly not changed and read only changed file, there is a need to redesign the tabs view, because there is about 3 versions of an icon:
* read only file
* read/write not changed
* read/write changed

When needs 4:
* read only not changed
* read only changed
* read/write not changed
* read/write changed
