### ISSUE TITLE
Feature Request: Scroll tabs when hovering over tabbar

### ISSUE THREAD

**Issue by marxl** [notepad-plus-plus/notepad-plus-plus#3001]
Currently there is the possibility to hold right-click and scroll with the mouse wheel to change tabs. The UI for that is quite slow and can crash the program on Win 10, though. Ideally it would be possible if you could **scroll through tabs with the mouse wheel when the pointer is hovering over the tabbar.**

I got really used to this back when I used a Firefox extension. Now I have to implement it on Chrome, Notepad++ etc. with AutoHotkey. Would be really nice to have this as native feature.

```
Notepad++ v7.3.2   (64-bit)
Build time : Feb 12 2017 - 23:17:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 
```

**Comment by SinghRajenM** [comment]
Somewhat duplicate to #2982, #1616, #2603, #2828, and #607 which has been fixed in [PR](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/2982) and will be available in the next release.

However, there are already exit two tab switching methods- 
1. Mouse right click + scroll
2. ctrl+Tab (ctrl+Shift+tab in reverse way)

I feel adding another method for same task (e.g. mouse hover tab n then scroll) does not make much sense, but still @donho can take decision on that.

**Comment by dail8859** [comment]
Can't you use Ctrl + Mouse Scroll over the tabs already?

**Comment by SinghRajenM** [comment]
Now, I would say three methods already exist.

**Comment by marxl** [comment]
Thanks for your replies, I didn't know about the `Ctrl + Mouse Scroll` option.
But what is the reason for using a modifier here? Is there some competing functionality on the tabbar or the risk of unintended misuse?

**Comment by dail8859** [comment]
I'm not sure why Ctrl is used but as pointed out there are quite a few was to do what you were wanting.
