### ISSUE TITLE
Changing notepad++ text displaying theme, should also change notepad++ theme

### ISSUE THREAD

**Issue by KSXGitHub** [notepad-plus-plus/notepad-plus-plus#303]
I can change theme by select 'Setting -> Themes', there are many themes to select.

When I change choose a dark-theme, text-background is changed to dark, text-color is change to light, but the other part in notepad++ (e.g. as title-bar, menu-bar, tool-bar, status-bar, tabs-bar, plugins' panel, context menu, dialogs ...) don't change to dark

![notepadplusplusrequesttheme](https://cloud.githubusercontent.com/assets/11488886/8322371/34782556-1a5e-11e5-9556-375d02236dd0.PNG)

**Comment by tommiehansen** [comment]
Yes, that's why i did a mockup on how **i would style** a new NP++.

**NEW**
![new](http://i.imgur.com/FqKopcM.jpg)

**OLD** (custom style)
![new](http://i.imgur.com/i0adi2H.jpg)

The new version is basically a merge of UI styles from Spotify, Githubs Atom.io editor and Notepad++.
Of course this darker version shouldn't be mandatory. A simple checkbox should take care of that "issue".

There is also a thread at the forums but it seems super dead.

**Comment by AbeBernabe** [comment]
How can we get the all black theme? or customize it?

**Comment by bacsidien94** [comment]
> How can we get the all black theme? or customize it?
> @tommiehansen

he said a 'mockup',  which mean everything is a design for now

**Comment by tommiehansen** [comment]
@bacsidien94 Yes, exactly. Unfortunately the developer(s) doesn't seem to care about the looks of Notepad++ at all.

**Comment by donho** [comment]
It's been done partially (all the panels).
Unfortunately it's hard (technically) to make it completely.

**Comment by Owyn** [comment]
When?

**Comment by 1keyz1** [comment]
With what software did you made this mockup? @tommiehansen

**Comment by privacyguy123** [comment]
This is amazing - how do we get it!?

**Comment by m4heshd** [comment]
I wouldn't mind paying for Npp if it looked like that. Not that I'm ungrateful for all that's given for free already. Just so satisfying to look at that crisp dark UI.

**Comment by tommiehansen** [comment]
> With what software did you made this mockup? @tommiehansen

Photoshop :)
