### ISSUE TITLE
javascript highlighting doesnt recognise null as a keyword

### ISSUE THREAD

**Issue by ThosRTanner** [notepad-plus-plus/notepad-plus-plus#3072]
### Steps to Reproduce the Issue

1. Edit a javascript file
2. type in `let varname = null;`

### Expected Behavior

`let` and `null` should both be highlighted

### Actual Behavior

only `let` is highlighted. `null` has the same colouring as `varname`

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppEditorConfig.dll NppExec.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll SpellChecker.dll XMLTools.dll

**Comment by dail8859** [comment]
This was fixed in 09d505ab1d4f008c13ffaa31cc8b5587507f3b3d and has been in Notepad++ since v6.8.9. You probably need to manually delete your `langs.xml` file (you may lose custom settings) for Notepad++ to recreate it. 

![capture](https://cloud.githubusercontent.com/assets/3694843/24074212/6a062a32-0bda-11e7-892e-1f4237ecd7a7.PNG)
