### ISSUE TITLE
[FEATURE] Open Folder command line switch

### ISSUE THREAD

**Issue by baberb** [notepad-plus-plus/notepad-plus-plus#3081]
### Feature Request
Need cmd switch to "Open Folder as Workspace"

### Why:
I would like to add this cmd to the right-click menu.  If I had a cmd line switch, I could simply add this to the context menu via the registry 
(this should also probably be done on install - Folder, Directory, and don't forget Background)

**Comment by rddim** [comment]
There is a way to open all files from folder, but this will not loading it in the 'Folder as Workspace'. It work like drag'n'drop folder with activated `Default Directory` > `Open all files of folder instead of launching Folder as Workspace on folder dropping` option. So this is not answer for your FR but is the way
