### ISSUE TITLE
langs.xml, stylers.xml fail to load

### ISSUE THREAD

**Issue by gsquidman** [notepad-plus-plus/notepad-plus-plus#3088]
## Description of the Issue

When running N++, starting the program from any menu or clicking the exe, two error messages appear. First, _"langs.xml failed to load,"_ then _"stylers.xml failed to load."_ Issue persisted after updating and reinstalling several times.

## Steps to Reproduce the Issue

I believe the issue began after I initially updated N++ to the current version and check marked less features in the installer than I did when I initially installed it.

## Expected Behavior

N++ should have opened straight to whatever file I wanted to edit without making me click "ok" on error messages, or open straight to a blank page if I run the executable.

## Debug Information

The issue occurs on Windows 10 Home, running the 64 bit version of Notepad++ 7.3.3. Installed to C:\Program Files\Programs\Notepad++\

### **The issue was finally fixed after running the installer and NOT selecting "Don't use %APPDATA%."**

 Something about storing plugins in the initial directory (which also was not the default install path) must've caused the issue. Admittedly, I wasn't trying to run N++ from a USB the way that option suggests.

**Comment by gsquidman** [comment]
I like how googling the issue brings up my bug report. Thank you, past gsquidman, for detailing how to fix this for me. Am I really the only one who has this issue? What if I don't want to use \%AppData%\?

**Comment by mikeepiazza** [comment]
https://tricksty.com/tricks/notepad-load-langs-xml-failed-fix

This link has a workaround for the langs.xml file and it worked for my system. 

Still searching for stylers.xml solution.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by johnfoxii** [comment]
Running the installer and NOT selecting "Don't use %APPDATA%." fixed issue on win 10
npp.8.3.2. x32 standalone
Installer does recognize and defaults to install folder as C:\local\Notepad++
had tried coping stylers.xml and langs.xml to APPDATA folder as well as overwriting stylers.xml with stylers.model.xml from install folder
APPDATA folder did not contain stylers.model.xml or langs.model.xml

**Comment by ragkag** [comment]
I am having the same issue with 8.5.1 for this reason: Instead of the installed folder C:\Users\xxx\AppData\Roaming\NotePad++ I created a symbolic link with the same name, pointing to D:\Users\AllUsers\AppData\NotePad++ so that the same configuration can be shared with other users on my PC.  I created the same symbolic link for all users.  The I use the context menu to select a file
I get the "langs.xml, stylers.xml fail to load" message.  In all other respects NotePad++ functions just fine with this symbolic link.  If I remove the symbolic link, the context menu also works fine. I have reinstalled 8.5.1 without the context menu since I don't use that option often.  Just an FYI.  I also tried 8.5.2 with the same results.
