### ISSUE TITLE
Changes lost in Administrator mode

### ISSUE THREAD

**Issue by Rype69** [notepad-plus-plus/notepad-plus-plus#3118]
### Description of the Issue
Changes lost when Notepad++ opens in Administrator mode

### Steps to Reproduce the Issue

1. Open Notepad++ in non-administrator-user mode 
2. Open a protected file, such as C:\Windows\System32\drivers\etc\hosts
3. Make an amendment to the protected file
4. Notepad++ prompts the user with the message "The file cannot be saved and it may be protected. Do you want to launch Notepad++ in Administrator mode?"
5. User clicks "Yes"
6. Notepad++ opens a new window with the file. The changes are not present.

### Expected Behavior
The changes to be present in the file in that opens in the new window.

### Actual Behavior
The changes are not present in the file in the new window.

**Comment by viet** [comment]
I'm having the same problem.

**Comment by jvoigtlaender** [comment]
I suspect this issue is subsumed by https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3666, which talks more generally about automatic restarts (not just automatic restarts caused by trying-to-save-a-file-without-having-the-rights-to-do-so).

@Rype69 and @viet, was your problem in a setting in which the 'Remember current session for next launch' option was disabled? If not, then it's a separate problem. Otherwise, it's subsumed by https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3666.

**Comment by riaprocoumai** [comment]
1+

**Comment by Philip82c** [comment]
Worse than this, found that reopening in administrator mode loses all open files and file history. It can be retrieved by finding the backup folder but it's a massive pain in the butt.

**Comment by Big--Mike** [comment]
As a workaround, you may use "Save as admin" plugin

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
