### ISSUE TITLE
Display "Reload" window as a banner in each tab instead of a separate popup

### ISSUE THREAD

**Issue by NeimadG** [notepad-plus-plus/notepad-plus-plus#3138]
### Description of the Enhancement

[Enhancement] Auto-reload feature is a powerful and very useful feature. However, it sometimes acts in a disturbing way (Drag&drop files not possible if another file has been modified because of the popup, ...).
The idea here is to replace (under option?) the popup by a banner shown in each modified file (with a particular icon on the tab?).
I've been using NP++ for more than 10 years and it's great ! Thanks !
Nei

**Comment by nikhilgirraj** [comment]
I agree with NeimadG, this is the most elegant solution to the annoying behavior which has multiple proposed fixes in the open issues list. (See  #1087, #1481, #1564, #745). I might've found more related open issues if I had dug up enough.
Here is what I think a banner could look like (bottom of the window in the image). May be the banner should be put at top instead of at the bottom. The colour of the tab could change to indicate that the file can be reloaded for a newer version.
Also, thank you for the features that are already there.
