### ISSUE TITLE
ASP comments not properly terminated

### ISSUE THREAD

**Issue by strider72** [notepad-plus-plus/notepad-plus-plus#3215]
In .asp files, comments are not properly terminated if the ASP end tag "%>" is on the same line.

For example, this works fine:
```
<%
'this is an ASP comment
%>
<p>This is HTML.</p>
```

...but this breaks:
```
<% 'this is an ASP comment %>
<p>Oops! Notepad++ still thinks we're inside an ASP comment!</p>
```

This is creating quite a problem reading some code I inherited wherein the author commented out inline ASP, e,g.:
```
<p>This is HTML<% 'with commented ASP code inside it %> and more HTML</p>
```

**Comment by dail8859** [comment]
This issue is also present in the latest version of SciTE (v3.7.4) so this is best reported to the Scintilla issue tracker [here](https://sourceforge.net/p/scintilla/bugs/). It may already be open on their issue tracker.

![capture](https://cloud.githubusercontent.com/assets/3694843/25484603/a524de70-2b28-11e7-9d53-22351bde9d69.PNG)

**Comment by ArkadiuszMichalski** [comment]
https://sourceforge.net/p/scintilla/bugs/650/

**Comment by strider72** [comment]
I eventually switched to VS Code for working with ASP files. There's a plugin for ASP syntax highlighting
