### ISSUE TITLE
Tab Bar drag & drop no longer works in 7.3.3

### ISSUE THREAD

**Issue by alexleduc76** [notepad-plus-plus/notepad-plus-plus#3247]
### Description of the Issue

You can no longer reorder tabs with drag & drop. Note that the checkbox "Lock (no drag and drop)" in the general settings is unchecked. I also tried to check it, close the preferences dialog box, and uncheck it again and it doesn't fix the issue.
### Steps to Reproduce the Issue

1.  Try to drag & drop a tab when more than one document is open.

### Expected Behavior

It should work.
### Actual Behavior
I upgraded from a 6.x branch to 7.3.3 and it didn't work in this new version.

**Comment by AngryGamer** [comment]
Dupe [#3108](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3108) [#3055](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3055) [#3016](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3016) [#3194](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3194)

Already fixed in future versions. Use the build I posted [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3108#issuecomment-290947032) until v7.3.4 is released.

**Comment by alexleduc76** [comment]
Awesome && thank you.
