### ISSUE TITLE
Feature Request: UDL

### ISSUE THREAD

**Issue by JamesBMcCarthy** [notepad-plus-plus/notepad-plus-plus#3257]
### Feature Request
1.  Add UDL to list of default languages 
2.  Incorporate regular expressions for UDL
3.  Provide setting of extension for saved files using UDL
4.  Provide more than eight (8) groups for keywords

### Steps to Reproduce the Issue
1.  Open program or new tab, and default is Normal text
2.  Cannot create desired syntax highlighting based on current settings
3.  Files saved while using UDL are save with no extensions

### Expected Behavior
1.  Set default language to desired UDL
2.  Use RegEx to select specific text in a string to highlight (info, warning, error)
[filer:callhome.invoke.all:info]: 
[filer:reg.options.cf.change:warning]:
[filer:asup.smtp.drop:error]: 
3.  Set a default extension for saved UDL files - .txt 
4.  Provide aditional keyword groups

### Actual Behavior
1.  Open in Normal text file language
2.  Cannot highlight specific words in a string with consecutive adjacent characters
3.  File is saved with no extension
4.  Not enough highlighting options

**Comment by JamesBMcCarthy** [comment]
Well that sucks. Reasoning?

**Comment by MetaChuh** [comment]
@JamesBMcCarthy 

i apologise for closing your feature request.

there was in no way anything awkward at your feature request, but as you have noticed, it has not been touched in the past two years, due to the lack of developers willing to code extensively at the udl part.

i have no information that this is going to change in the near future, and it makes no sense to leave this request open and abandoned, if it would eventually never be touched.

many thanks for your understanding and support.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by JamesBMcCarthy** [comment]
Fair enough, and thanks for the explanation.  If I can find the time to look at I will.  I am not a developer, and only have basic experience with C++ and Python.  Is it worth taking a shot?  What is is written in, and can I get access to it here on git hub?  I will look around in the time being.  Thanks!

**Comment by MetaChuh** [comment]
it's written in c++

if you want to dig into it a bit, most of the code is here:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScitillaComponent/UserDefineDialog.cpp

and here:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/lexers/LexUser.cxx

(all source code is accessible here at the notepad++ github project pages)

you probably already know the user documentation site of udl guru @ivan-radic : https://ivan-radic.github.io/udl-documentation/

many thanks.

**Comment by cssyphus** [comment]
With respect, sir, this issue should be re-opened. It is a hugely important improvement in UDL coding (the single biggest improvement ever) and just because it wasn't completed in two years doesn't mean it will never be addressed. There are new Linus Torvalds coming up through the university system every year, looking for interesting projects that will be their ticket to stardom. This issue shouldn't be closed - it should be advertised.

Keeping an issue tracker clean is no reason for closing an unresolved - and hugely important - issue merely because it hasn't yet been addressed. Closed means "resolved" and "overdue" is not "resolved".

**Comment by ivan-radic** [comment]
Hi everyone,

this popped in my mailbox today. 
Let me help clear few things.

>Add UDL to list of default languages

UDL is not a single language definition. Instead user is expected to create (or import) language definitions and then you will see them at the bottom of the language list. see one example here (https://i.imgur.com/hQpKB4o.png)

>Incorporate regular expressions for UDL

UDL is not based on regex and never will be. If you have a valid use case where regex must be used, please post it here.

>Provide setting of extension for saved files using UDL

It is already there. You must click `Create New...`, and as soon as you do it, extension support is displayed for you. see an example here (https://i.imgur.com/IM5DtW0.png)

>Provide more than eight (8) groups for keywords

This was the most requested feature. 
UDL3 , which was never fully finished and never published, solved this by introducing 32 groups. Unfortunately, 8 groups is the current limit.

>With respect, sir, this issue should be re-opened.

If it remains opened it might create false impression that someone is willing to work on it.
This issue really just asks for regex support which is not an option in UDL (past, current or any future versions that might or might not come one day). Simply put, design of UDL does not leave room for regex support.

Best regards,
Ivan
