### ISSUE TITLE
64 bit Plugin Manager is now available

### ISSUE THREAD

**Issue by ameer1234567890** [notepad-plus-plus/notepad-plus-plus#3264]
Plugin Manager is now available in 64 bit. The latest release (stable) of Plugin Manager (https://github.com/bruderstein/nppPluginManager/releases/tag/v1.4.9) has 64 bit binaries. Please include Plugin Manager in 64 bit release of Notepad++

**Comment by KptainBiwouak** [comment]
Yes, please include Plugin Manager in Notepad++ release and provide selection for plugin compliant 64bits.

**Comment by NN---** [comment]
The download page states "Note that the most of plugins (including Plugin Manager) are not yet available in x64 ", and finally it is not true anymore :)

**Comment by dail8859** [comment]
As of Notepad++ v7.5 the Plugin Manager is no long being shipped with Notepad++. See https://notepad-plus-plus.org/news/notepad-7.5-released.html

All Plugin Manager related issues should be reported to https://github.com/bruderstein/nppPluginManager/issues

**Comment by Armand-Smith** [comment]
Do you mean that neither 32 nor x64 release have now a plugin manager 
the offical website said this but i dont agree cuz i really need a plugin manager

"
You may notice that Plugin Manager plugin has been removed from the official distribution. The reason is Plugin Manager contains the advertising in its dialog. I hate Ads in applications, and I ensure you that there was no, and there will never be Ads in Notepad++.
A built-in Plugin Manager is in progress, and I will do my best to ship it with Notepad++ ASAP "
Source = https://notepad-plus-plus.org/news/notepad-7.5-released.html

**Comment by dail8859** [comment]
None of the releases include the Plugin Manager. You will have to install it manually.

**Comment by Nachtfrische** [comment]
You seriously removed the plugin manager, because it was thanking the company for hosting the list of plugins? Why can't you host the list yourself, then you wouldn't need to remove it because of such a dumb reason.

**Comment by Armand-Smith** [comment]
its okey if he thanks that company for hosting the plugin besides its not
that really fatal ads, we cant live whitout the plugin manager

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by zyrill** [comment]
+1 on shipping Plugin Manager again. Notepad++ is still a great software without it, but the majority of the userbase absolutely requires that plugin to be there...

**Comment by PowerAccess** [comment]
+1 for installing Plugin Manager by default again.

The Plugin Manager absolutely is critical. Without it, there is no reason to use Notepad++ any longer instead of just Visual Studio Code. 

Its also very confusing to see it disappear without notice (other than possible in the release notes always shown after install which always close since otherwise never anything critical there). 
I was about to uninstall and revert to old version assuming was a bug, as many others are likely to do. 

And others, even if don't assume is a bug, may revert to older version and stop updating Notepad++ in order to keep Plugin Manager, especially if no easy way to install it.

**Comment by PowerAccess** [comment]
Can you at very least show a menu entry for Plug-in Manager (next to where is usually shown) which, when clicked, shows explanation that is missing now, why, and provides a link to download it.

Also, can you at least include option installer to install plugin manager? 
If its a licensing issue with bundling it, then you may be able to do something like PotPlayer with OpenCodecs, where it downloads installer for you to make it easy for you to "install yourself".

Or, you could even just open browser to Plugin Manager download page if user checks Plugin Manager install option.

**Comment by hoovler** [comment]
+1 for Plugin Manager:

I'm floored that the Plugin Manager -- one of the most functionally useful components of NPP -- was removed in a version update.  That's one step forward, and falling back down to the bottom...

**Comment by Armand-Smith** [comment]
Yes We need the plugin manager immediately, if not there no reason to use
npp

**Comment by CTimmerman** [comment]
One could:
1. Wait for Npp to include its own plugin manager like Visual Studio Code and lots of other current editors have.
2. Use an older version of Npp.
3. Install the existing plugin manager.
4. Fork and host the plugin manager itself, without crediting the hosting company, and convince Npp's author that yours is easier and safer to include than his.

**Comment by flex-79** [comment]
how 2 get plugin manager:
1. download pm from https://github.com/bruderstein/nppPluginManager/releases (current 1.4.9)
2. open np++ > settings > import > import plugin(s)

worked with np++ v7.5.1 (64-bit)

**Comment by spottedmahn** [comment]
@flex-79 - am I supposed to import `PluginManager_v1.4.9_x64\plugins\PluginManager.dll` and then I should see the Plugin Manager again?  I still don't see it.

**Comment by NN---** [comment]
You copy paste both folders plugins and updater to notepad++ folder.
Pay attention to copy 64-bit I’d you installed N++ 64-bit;)

**Comment by spottedmahn** [comment]
thanks @NN--- !  Plugin Manager is back:

![image](https://user-images.githubusercontent.com/14079228/32456173-a51f2a9a-c2f2-11e7-852e-8f0b15d49215.png)

---

**Full Steps**

1. [Download Plugin Manager](https://github.com/bruderstein/nppPluginManager/releases)
1. Extract the 2 folders (`plugins` and `updater`) to `C:\Program Files\Notepad++`*

*This is for the 64bit install

**Comment by shaunjstokes** [comment]
Thanks you @NN--- :+1:

**Comment by JohnLGalt** [comment]
Npp 7.5.2 x64
PluginManager 1.4.9 x64

I've got the files installed correctly in the respective directories under npp, and PM shows up perfectly fine in npp after importing.

However, it is currently trying to update DSpellCheck, and every time it does, it asks to restart npp, then I'm given a UAC prompt, but it never actually completes the task, and if I open Npp again, it gives me the same prompts all over again.

Am I doing something wrongly?

![npp error 1](https://user-images.githubusercontent.com/7432512/33500221-273bcfd0-d6a6-11e7-9d79-af62e512f5c4.PNG)
![npp error 2](https://user-images.githubusercontent.com/7432512/33500232-2b9dae0e-d6a6-11e7-8d1d-ba9c4ea2323b.PNG)
![npp error 3](https://user-images.githubusercontent.com/7432512/33500235-2df05684-d6a6-11e7-80d5-2b296491b023.PNG)
![npp error 4](https://user-images.githubusercontent.com/7432512/33500243-3043754c-d6a6-11e7-80d2-b0c06341a9fd.PNG)

**Comment by SadChimera** [comment]
@JohnLGalt the plugin manager direct when unzipped will look like this:
- PluginManager_v1.4.9_x64
- - Plugins Folder
- - - PluginManager.dll
- - Updater Folder
- - - gpup.exe

1. copy gpup.exe into ~\notepad++\updater\ 
2. copy PluginManager.dll into ~\notepad++\plugins\

**Comment by JohnLGalt** [comment]
Yeah, that is how I had it.

I finally rebooted my machine, and it finally updated.  But many other errors running programs and such led me to clean install Windows 10 again, only o find out that there is a nasty bug in Insider Preview build 17046 that causes it to randomly start hanging when running an application that requires elevated privileges.

Anyhoo, on this install it didn't give me any stupid errors.

**Comment by peterfnet** [comment]
It makes sense that Notepad++ wishes to avoid sponsorship in its software. If I were a web hosting company, I'd love to have an opportunity to have trade hosting for advertising.

In the screenshot from the post above of the plugin, the "Why is this here?" links to [https://bruderste.in/npp/pm/sponsor/](https://bruderste.in/npp/pm/sponsor/) where it explains the history and the why.

Still, that kind of information should be pushed into the About dialog for the plugin, which is right below the plugin menu structure.

It's a slippery slope to feel as if since you're getting such a good deal, that it's easy to give credit/compensation. Seems similar to some of the tech/gaming bloggers out there getting flown out to fancy conferences, game releases events, etc. It's easy to be clouded by the benefits to make ends meet. 

The decision to exclude the plugin makes sense, especially from a bundled, 3rd-party plugin. Even if Notepad++ were to be supportive of integrated advertisement of some kind, that's a huge mess to deal with mixed 1st-party and 3rd-party.

**Comment by Jerico815** [comment]
@JohnLGalt 
Got the same error.

Try this one:
Right mouse on the files/ unblock. (check screenshot)
Do this with both files.
After a restart of notepad++ press yes if admin rights needed.

![unblock](https://user-images.githubusercontent.com/35608204/35360084-d103401c-015c-11e8-9264-dfb4e858691a.png)

**Comment by enderandpeter** [comment]
For the love of Pete Moss. The people who removed the Plugin Manager should be drawn and quartered. Does that nexinto ad from the people generously hosting these files really tear at your soul?

**Comment by Mateos81** [comment]
Looks like it's moving in the right direction: https://github.com/bruderstein/nppPluginManager/issues/80

**Comment by ojinxy** [comment]
@SadChimera It worked. Thanks.

**Comment by codingbayarea** [comment]
Thanks, got it to work.  I relied on a python script and now I was able to get it working again.

**Comment by tmtron** [comment]
> how 2 get plugin manager:
> 
> 1. download pm from https://github.com/bruderstein/nppPluginManager/releases (current 1.4.9)
> 2. open np++ > settings > import > import plugin(s)
> 
> worked with np++ v7.5.1 (64-bit)

It worked for me only, when I started npp as Admin (on a Windows 10)

**Comment by DRSDavidSoft** [comment]
#3756.
