### ISSUE TITLE
FEATURE REQUEST: OOPS, SAVED OVER MY FILE ISSUE

### ISSUE THREAD

**Issue by h3rb** [notepad-plus-plus/notepad-plus-plus#3281]
### Description of the Issue

Sometimes when I am exiting Notepad++ or during a routine save operation, something goes awry and I get confused.  This is not a "programming issue" it is a "design issue"

It starts putting me through an endless Save as... dialogue when I (maybe) accidentally hit "Save all" instead of "Save as.." and have a bunch of New unsaved but "hung onto" documents.  When this happens I sometimes get confused because I did not mean "Save All", and I convince myself there is a bug after hitting Escape several times, and end up saving as the file I'm working on, not realizing I'm overwriting my old work, because the tab I'm looking at behind the dialog is the file I'm working on. 

Then, when it asks "Was changed outside of Notepad++, reload?" I sometimes convince myself that "Yes" is the right answer (when in actually it was Notepad++ that saved it)

This happens to me regularly.  In the past I've been lucky and it is in the Roaming/ folder as a fairly recent backup, but with newer files this is not the case, and there is no backup point to restore to.

_Sometimes I lose hours, days or weeks of work_ 

What I want as a remedy: 

1.  up to 3 versions from the last day stored in AppData/Roaming/ on files less than a few hundred kilobytes (or an arbitrary byte number stored in Config / Preferences > Prior Revision Backup Limits).

2. Better wordings in the warnings  "Was changed outside of Notepad++, reload?" that emphasize perhaps the difference in size so I know if I'm going to be reloading (and losing Undo history) -- and also **a warning perhaps before you Save as... / all over a tab that is already open!!!** and maybe it should know Notepad++ saved it?

3. Separate Save As.. and Save All options more in the file menu

4. Emphasize on the dialog that you are saving all

**Comment by interstellarjam** [comment]
I would love to see proper '3 file rolling save' type options for open files (not just on save), as suggested above.

I have the same or similar issue. I am sometimes stupid or stressed and confused about popups and being able to work out exactly what I'm doing when I'm hitting yes or no.

Happens particularly with any of the 'file has been changed' dialogs. I habitually hit no because working out whether it's safe to reload or not is sometimes too complicated.

Just now I ran into this type of issue and lost work, which is the first time I can remember losing work with Notepad++ in years. I think I will post a separate issue because it's a weird corner case with Notepad++.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
@h3rb Dude, just save your documents to disk...regularly.  Don't rely on "hung onto" documents.  It is simply asking for trouble, no matter how good Notepad++ is.
