### ISSUE TITLE
Notepad ++ doesn't remember position in document after changing tab

### ISSUE THREAD

**Issue by leschek** [notepad-plus-plus/notepad-plus-plus#331]
Last few weeks I have problem with notepad++ (6.7.9.2 portable and with previous), because it doesn't remember last line where I was working before changing to tab with other file. For example if I'm on tab 1 on line 250, then I switch to tab 2 and come back to tab 1 it move me to the top of file and not to line 250 where I was before. Does anybody know, if there is some setting (I'm not able to find) to fix this very annoying behaviour.

**Comment by dail8859** [comment]
Do you have XML Tools installed?

**Comment by leschek** [comment]
Yes, I do.

**Comment by dail8859** [comment]
Try turning off "Set XML type automatically". Should fix the problem

**Comment by leschek** [comment]
Thank you. It seems it's OK now.

**Comment by dspjm** [comment]
I have the same problem, but I don't have XML tools installed.

**Comment by rhgrafix** [comment]
@dspjm, same with me, I couldn't find the setting anyways, the answer they gave was partial because Notepad++ has one of the biggest menu structures making it extremely difficult to find a setting, I Googled "where is setting in notepad++ for Set XML type automatically and it takes me to more forums which tell that part but not where to find it, so annoying.
