### ISSUE TITLE
"Column Editor" Insert End of Line Crashes

### ISSUE THREAD

**Issue by roflsunriz** [notepad-plus-plus/notepad-plus-plus#3314]
### Description of the Issue

When I use "column editor" to append some extra characters to the end of line,notepad++ 7.4.1 64bit crashes on windows 10 64bit.

### Steps to Reproduce the Issue

1. type something and make multiple line on the editor.
2. put your cursor at the end of line
3. launch "column editor" from "edit">"column editor... Alt+C"
4. put any characters or words into "text to insert" and hit "OK"
5. the editor crashed and it shows up "windows error"

### Expected Behavior

I intended to append words at end of sentences for multiple lines...it had been worked fine in older versions...why?.

### Actual Behavior

http://i.imgur.com/32bkMg5.png

### Debug Information

I don't remember which version is, but older notepad++'s this function had been worked correctly, but ( I don't now when it changed exactly) the notepad++ started occurring error from some time. 

I want to make sure, but  the latest notepad++(7.4.1) uses some extra requirements such as Java 8?
Recently I installed Java SE Development Kit 8u131 instead of older JDK and also removed older versions, too, and changed "PATH" environment variable, So, this may occurred an error, or not?

### Extra Info
This issue is Japanese(UTF-8) specified-issue, maybe occur in 2-byte characters-based languages and Emoji too.
At least In UTF-8 Japanese this error was occurred.  Single-byte characters (such as alphabet) did not occur this issue.

**Comment by SinghRajenM** [comment]
I found the faulty (rather root cause) piece of code.
```
{
	auto posAbs2Start = (*_ppEditView)->execute(SCI_FINDCOLUMN, i, cursorCol);
	auto posRelative2Start = posAbs2Start - lineBegin;
	s2r.insert(posRelative2Start, str);
}
```

s2r.insert causes crash. How?
For mutli-byte, scintilla API "SCI_FINDCOLUMN" returns incorrect position of a column (actually double).
Then while inserting new column text at wrong location causes the crash.

I could not find out way (scintilla API to detect the mutli-byte n then use appropriate API to get column position) to handle. Someone who is more aware scintilla APIs can take it forward.

P.S.
However as per scintilla doc
> SCI_FINDCOLUMN(int line, int column) → int
This message returns the position of a column on a line taking the width of tabs into account. **It treats a multi-byte character as a single column**. Column numbers, like lines start at 0.

but this is not true in our case. May be true for latest version o scintilla .

**Comment by donho** [comment]
I cannot reproduce the crash at all.
@SinghRajenM  Can you reproduce the crash from your side?

**Comment by SinghRajenM** [comment]
Yes, it can be reproduce easily. I use Japanese word "期待する" and crashed. Refer the attached PSR for details.

[nppCrash.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1034138/nppCrash.zip)

**Comment by donho** [comment]
OK, I can reproduce it with Japanese text.

**Comment by SinghRajenM** [comment]
@donho 
Submitted solution does nor work properly. It just avoid the crash but column editor does not work.

Just take an example using word "期待する", 
1. put the same word in two lines.
2. put cursor after first character
3. Use column editor (space is used).
4. expected output = first line:"期 待する" and second line:"期 待する", (space after first character)
5. but actual output = first line:"期待す る" and second line:"期待す る", (space after third character.)

More over, if the selected column position just greater than the length then character will be always put in the end irrespective of the selected position.
