### ISSUE TITLE
Notepad++ crashes on WinXPSP2

### ISSUE THREAD

**Issue by notedrop37** [notepad-plus-plus/notepad-plus-plus#3315]
Notepad++ crashes my computer with blue screen Fatal System Error 0xc000021a.

I downloaded the bin.zip package of Notepad++ 7.4.1 for Windows and extracted all the files to C:\BIN\NOTEPP. When I open the application, it works fine. When I close it and open it the second time, it opens and stays there for a second or two, and then the mouse disappears and a blue screen appears that says Fatal System Error 0xc000021a. I am using Windows XP SP2 at the moment, but I have experienced this same issue with Windows 7 years ago. This is the reason why I haven't used Notepad++ at all. I'll start using it once this issue gets fixed.

To reproduce this error :
1. Install 32-bit Windows XP Pro Service Pack 2 on your Dell Dimension computer with 2.5GB of RAM, 60GB SSD and 2TB hard drive. FAT32 file system on the SSD drive and NTFS file system on the big hard drive. Have the following programs installed : Google Chrome, Mozilla Firefox, IE6, Java 7, MS-Office 2003, CCleaner, Samsung USB driver for mobile phones, K-Lite Codec Pack 5.9.0, ATI Display Driver, and Adobe Flash Player 24.
2. Okay, once you have the same setup as mine, you install Notepad++ on your computer and start it up.
3. Close it. Wait 10 seconds. Open Notepad++ again. Puff. It crashes the system. Everytime. No exceptions.

**Comment by tanzislam** [comment]
If **user-mode applications** (not device drivers) like Notepad++ can crash your system, it's usually a sign your operating system is buggy or having unrelated problems.

You mention you're running Windows XP SP2. Apart from the fact that Microsoft has completely dropped support for Windows XP long ago (not even security fixes), it is not even up-to-date with the latest updates ever released for it (e.g. Service Pack 3). Consider using NTFS for the operating system partition, so that system files can be protected using filesystem permissions. Finally, pages like [this](https://blogs.technet.microsoft.com/jeff_stokes/2011/05/20/what-do-you-do-when-you-want-to-run-windows-xp-on-a-solid-state-drive/) suggest that running Windows XP on SSDs is more trouble that it's worth.

Keep your system up-to-date. In this case, it implies upgrading.

**Comment by MetaChuh** [comment]
windows xp sp2 is no longer supported.
