### ISSUE TITLE
Add "Remove Duplicate Lines" option in "Line Operations"

### ISSUE THREAD

**Issue by AleWin32** [notepad-plus-plus/notepad-plus-plus#3329]
Under Edit menu, Line Operations, we have lot of good stuff to do things with lines, like "Remove Empty Lines" but we don't have "Remove Duplicate Lines", i have needed this option many times, so i did it on Excel.

This can be done without any Notepad++ plugin, using a regular expression but it is not easy to remember, second answer in this URL:
https://stackoverflow.com/questions/3958350/removing-duplicate-rows-in-notepad

So this option will be very comfortable, can you add it?

THANKS!

**Comment by JMM72** [comment]
I support this suggestion because right now I'm using regex to remove duplicates on a 120k line file, and it's taking forever. I have it as a macro, but for any large file it's really a PITA even on a 4ghz CPU. Just because it can be done with regex doesn't mean it's a good idea.

And TextFX doesn't have a 64bit version so... Please, don't disregard this.

**Comment by magol** [comment]
I support this suggestion to, this is something I regular need to do.

**Comment by fml2** [comment]
This would be a nice feature, yes, but there are tools to perform this task, e.g. unix utilities ported to windows. Also, there is Python plugin which would easily allow to implement this feature.

Should we make every useful function part of NP++ core? Wouldn't it explore the program?

**Comment by Woidla27** [comment]
I would very much appreciate this feature, too.

I had used this function almost daily via TextFX. Unfortunately I have to search for an alternative now, because TextFX is not available for the 64 bit version.

Of course, you could also delete the duplicate lines using awk, powershell or similar. But first you have to save the file (I often only work with "temporary" texts which I immediately copy into other windows), switch to another program and type in the command. In principle no problem but still annoying.
At last the function is comparable to the other line operations, which could also be solved by other programs... :)

**Comment by Woidla27** [comment]
Seems like our whishes have been heared: 51f10bdba56a415d42eb829b27a08955cb7db0dd
Thanks to @donho

**Comment by Faq** [comment]
@Woidla27  Not rly as that funcrion is to Remove Consecutive Duplicate Lines

**Comment by Woidla27** [comment]
I agree with you, it's not exactly the same.
But combined with the existing "Sort Lines Lexicographically Ascending" in a macro, it should produce the same result with one click. 

Let's wait for the next release and try it out :)

**Comment by sasumner** [comment]
@Woidla27 "...combined with sort...".  Yea, okay, that works when a sort of your data is valid.  For when you can't sort, this type of remove duplicate lines is of very limited use.

**Comment by donho** [comment]
Added since v7.6.3

**Comment by sasumner** [comment]
@donho said:
>Added since v7.6.3

Well...not exactly.  This request is asking for removing duplicate lines that aren't adjacent.

Consider the text:

abc
def
def
ghi
def
jkl

The functionality in 7.6.3+ will reduce it to:

abc
def
ghi
def
jkl

But what is really wanted is to reduce it to this (keeping FIRST):

abc
def
ghi
jkl

Or maybe this (keeping LAST):

abc
ghi
def
jkl

Requesters should clarify if they want to keep FIRST or LAST.

**Comment by felix-22** [comment]
> (keeping FIRST):

This one has been implemented.
