### ISSUE TITLE
Save dialog displays open button when folder is selected but functions as a save button

### ISSUE THREAD

**Issue by RandomRhythm** [notepad-plus-plus/notepad-plus-plus#3350]
### Description of the Issue

When doing Save As if you highlight a folder the text on the button faces is Open and Cancel. However, clicking the open button does not open the folder. Instead a file is saved to the current directory.

### Steps to Reproduce the Issue

1. Open a file
2. File > Save As
3. Browse to a location on the computer that has a sub folder and highlight (single click the folder)
4. Click the Open button
5. File is saved to the current directory and the highlighted folder is not opened
6. File > Save As
7. Browse to same location in step 3 and highlight the sub folder
8. Click the Open button
9. Asks to replace the file created in step 5

### Expected Behavior

When you hit the open button while a folder is selected open the folder.

### Actual Behavior

File is saved to the current directory and the highlighted folder is not opened.

### Debug Information

Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

![saveas1](https://cloud.githubusercontent.com/assets/18624368/26758308/ab1bdba8-4897-11e7-959d-562e6247a06d.png)
![saveas2](https://cloud.githubusercontent.com/assets/18624368/26758309/ae392c96-4897-11e7-947a-46c87a85f160.png)

**Comment by irgendsontyp** [comment]
The code introducing this behaviour is commented with: // Don't touch the following 3 lines, they are cursed !!!.

And indeed, the things that are going on afterwards are really cursed. 

I think I figured out where the core of the problem is: Notepad++ installs a hook for the save dialog. Inside this hook, the window procedure of the dialog is replaced with a custom one. In the custom window procedure, the window message WM_COMMAND with the id IDOK, which is the "Open" or "Save" button (the button is the same, only the caption is changed depending on whether there's a folder selected in the dialog or not). Inside the custom window procedure, there is a check whether the string in the control for the file name (which can be an edit control or a combo box, depending on the version of Windows) contains an extension or not. If it doesn't, the extension selected in the extensions-combo box is appended. This is done via SetWindowText() for the file name's control. I think this is exactly where the problem is: By calling SetWindowText(), some internal flag seems to switch which causes the dialog to call the "save routine" even if a folder is selected in the list view (and thus the button's caption was "Open" at the time of clicking it). You can verify this by just commenting out "PowerEditor/src/WinControls/OpenSaveFileDialog/FileDialog.cpp", line TODO.

Now I had two ideas to fix this:

1. I assumed that the above mentioned routine for checking whether to call "save" or "open" is done by listening to some "text changed" event of the edit control. So I thought by replacing the edit control's window procedure with a custom one, calling DefWindowProc instead of the original one, when we are adding an extension to the edit control's content would prevent the dialog from calling the "save" routine. But I couldn't get SetWindowText to work after having replaced the edit control's window procedure. The new text just didn't appear. Anyway, I think this doesn't work out as I initially expected.

2. I thought we could just focus the list view containing the file names of the currently selected folder after having set the new content (with the extension) of the edit control. By focussing the list view, the internal dialog state would again change to "open" and thus clicking the IDOK button wouldn't call the save routine which it would have called due to the changed edit control's content. This solution works if there is a folder selected in the list view. But it doesn't work if there is a file selected. Let me explain this with an example: Open the save dialog. Create and select a file named "a.txt" in the list view. Enter "b.txt" into the edit control. Click "Save". Now the dialog saves (or tries to) the file "a.txt" because after having clicked "Save", the list view and the item "a.txt" are focussed causing the save dialog to assume you want to save the file as "a.txt".

I have no other ideas at the moment :)

I hope you can understand what I wrote. I'm not a native English speaker.

**Comment by sasumner** [comment]
No longer appears to be a problem in Notepad++ 7.9.5.
