### ISSUE TITLE
Allow separate tab size and indent size

### ISSUE THREAD

**Issue by srussel** [notepad-plus-plus/notepad-plus-plus#3382]
### Description of the Issue
The project I work on has the coding style: 4 column indent for each indented code block, tab size = 8. While Notepad++ is my preferred editor, trying to write code in with this style in Notepad++ is more trouble than it is worth. 

### Requested Enhancement
Provide separate indent size and tab size in language settings.

**Comment by VVelda** [comment]
What is it good for?

**Comment by jwt27** [comment]
I had to scroll so far down to find this.  This would be my number one feature request.

I think Visual Studio implements it very well, so that is a good example:  With tab width 8, indent size 4, pressing the tab key inserts 4 spaces.  Pressing tab twice inserts a single tab character.

This is especially useful when working with GNU-style code, where indentations are 2 spaces and a string of 8 spaces is replaced by one tab.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12333#issuecomment-1430684990
