### ISSUE TITLE
XML highlighting fails when an attributes uses single quotes and a space

### ISSUE THREAD

**Issue by DavidFichtmueller** [notepad-plus-plus/notepad-plus-plus#3403]
### Description of the Issue
The syntax highlighting for the currently selected element in an XML files has a small bug when there are two attributes of which the first one uses single quotes and has a space in the attribute content. 

### Steps to Reproduce the Issue
1. Switch to syntax highlighting to XML 
2. copy and paste this line: `<element attribute1='some content' attribute2='1234' />`
3. move the cursor inside the element

### Expected Behavior
The attributes and their content get a yellow background.

### Actual Behavior
At the first attribute, the yellow background stops with the space, at the second element, the yellow background starts after the first character.
![grafik](https://user-images.githubusercontent.com/7805030/27221900-8f99c316-528a-11e7-9172-bbafb739eff4.png)

### Debug Information
Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll XMLTools.dll

**Comment by ArkadiuszMichalski** [comment]
This is still actuall in Notepad++ 7.9 RC. 

For single quotes we have:
![a](https://user-images.githubusercontent.com/2730894/93715426-7d447e00-fb69-11ea-9d54-c1b095f3607f.gif)

For double quotes we have:
![aa](https://user-images.githubusercontent.com/2730894/93715431-803f6e80-fb69-11ea-8a6b-9e1167edf297.gif)

**Comment by donho** [comment]
@ArkadiuszMichalski It's Notepad++ issue, but not Scintilla's one.

**Comment by ArkadiuszMichalski** [comment]
https://html.spec.whatwg.org/multipage/syntax.html#attributes-2 << rules from HTML standard for attributes.

Something here should be correct:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScitillaComponent/xmlMatchedTagsHighlighter.cpp#L39

Adding just in 88 line:
```
case '"':
case '\'';
```
it's not enough because it doesn't work properly for `attr="value'more"` and `attr='value"more'`.

**Comment by donho** [comment]
@ArkadiuszMichalski 
 Are `attr="value'more"` and `attr='value"more' valid attribute values?

**Comment by ArkadiuszMichalski** [comment]
Yes it's valid, I put above link to HTML spec when we have describing all cases for attr.

**Comment by ArkadiuszMichalski** [comment]
I check some case per HTML spec for  this fix and works fine. Code for test:
```
<!-- CORRECT -->
<element attr1='some value' attr2='some_value' attr3="other"/>
<element attr1="some value" attr2="some_value" attr3="other"/>


<element attr1='some"value' attr2='some " value' attr3="other"/>
<element attr1="some'value" attr2="some ' value" attr3="other"/>


<element attr1 ='some value' attr2= 'some_value' attr3 = "other"/>
<element attr1 ="some value" attr2= "some_value" attr3 = "other"/>


<element attr1=value1 attr2=value2 attr3=value3 />

<!-- Bellow is correct because empty string after = -->
<!-- where " or ' was not used is forbidden. -->
<!-- So only attr3 is correct. -->
<element attr1= attr2= attr3=value3 />


<!-- MAYBE INCORRECT -->

<element attr1 attr2 attr3/>
```

@donho In HTLM alone attr name (without value, and without `=`) is correct. 
>Empty attribute syntax
Just the attribute name. The value is implicitly the empty string.

So last case in above example aslo can add style for `attr1`, `att2`, and `attr3` when we jump to element. Unless you assume that this mechanism only highlights attributes with a value, then more correct are not needed here.

**Comment by donho** [comment]
Checked in the browsers and with xml tool plugin, all 3 lines are not valid xml :
```
<element attr1=value1 attr2=value2 attr3=value3 />
<element attr1= attr2= attr3=value3 />
<element attr1 attr2 attr3 />
```

**Comment by ArkadiuszMichalski** [comment]
@donho Yes because per XML only attr with value inside "" or '' is valid (https://www.w3.org/TR/xml/#NT-AttValue).

The question is how this highlighting attribute (and its value) is supposed to work:
- according to the rules of XML or XHTML
- according to the rules of HTML (it is less restrictive)
- detect language and use correct rules for it.

In its simplest version, it should meet the HTML rules, because that will also include the XML rules (when the code/document is valid). After all, Notepad++ does not check the syntax validity (in-build), so the user has to create the correct code (and for valid code this highlighting will work).

Actually this highlighting follow HTML rules, with this small exception `<element attr1 attr2 attr3 />`, which is correct.
