### ISSUE TITLE
Feature request: middle-click on tab bar to open a new tab

### ISSUE THREAD

**Issue by vlakoff** [notepad-plus-plus/notepad-plus-plus#3412]
It's already possible to double-click on empty space on the tab bar to open a new blank tab.

It would be great if middle-clicking was doing it too :)

**Comment by DADMahindika** [comment]
I would like to work in this feature. can you please make the state of this is as in the working state

**Comment by DADMahindika** [comment]
There were some errors when I tried to build the source code in visual studio 2017. it indicated error in the line  #include <windows.h>. can some one please help me to fix this error.

**Comment by irgendsontyp** [comment]
Take a look at this [stackoverflow post](https://stackoverflow.com/questions/43410631/visual-studio-2017-cant-find-windows-h) regarding missing windows.h.

And if that's not enough for successfully building, take a look at #3492. The VS project file might work for you.

**Comment by DADMahindika** [comment]
thank you for your comment. and i will try those

**Comment by vort3** [comment]
Is there any progress on this? Pretty much every program with tabs (all browsers) support middle click to create new tabs, I'm so used to it, it's frustrating when I try it in Notepad++ and nothing happens.

**Comment by sasumner** [comment]
@vort3 

Middle-click is also mentioned in this issue: #7937 

I don't want to sound dumb (perhaps unavoidable here) but what is "middle click"?  I think I used my first mouse in 1985(?)ish, but I've never had a mouse with 3 buttons in order to have a middle one.  Fairly obviously, I've had mice that have a wheel and sometimes that wheel can be pushed as a button, and at times I've programmed that to be a double-click, but never a "middle click".

Perhaps my current mouse is programmable that way, but it doesn't appear in Win10 settings that way for me, and, since my mouse does everything I want/need without installing any 3rd party (Logitech) software, I'm mildly against doing that.

Anyway, can you turn some light on this for me?

**Comment by vort3** [comment]
When saying «middle click» I actually refer to mousewheel click, AFAIK everyone calls that middle click since it's in the middle. Most apps refer to it as MMB (Middle Mouse Button), and it works the same on every modern mouse without any third party tools: middle click on tab bar creates new tabs, and middle click on tab closes it. This is the default behaviour in all modern programs.

> sometimes that wheel can be pushed as a button
It is not «sometimes» but always, unless you use very ancient one.

> I've programmed that to be a double-click, but never a "middle click"
You don't need to program anything, it works as MMB by default without any third party software.

**Comment by sasumner** [comment]
@vort3 

So here I am with my Logitech M705 mouse, I guess not ancient as [amazon](https://www.amazon.com/Logitech-M705-Wireless-Marathon-Mouse/dp/B003TG75EG) sells it as of this writing.

In Chrome if I press this "middle" button in the tab bar area, nothing happens.  By the tab bar area, I mean the area to the right of the `+` for a "new tab".  If I press it ON the `+` also nothing happens (but I would never do this as just a left-click invokes that functionality -- I just did it as a test).  

If I press it when pointing to an existing tab, yes that does close the tab (and is enough to document the "deficiency" in Notepad++).

But I'm curious why I can't create a new tab with this button, at least in Chrome.

**Comment by vort3** [comment]
Apparently, Chrome never had this feature… I did a quick google search, and most Firefox users request that this feature is implemented in Chrome too, but it's not there yet.

I was wrong.

**Comment by donho** [comment]
Tested in the modern browsers (Firefox, Chrome, Edge), none of them can create new tab by middle click.

**Comment by vlakoff** [comment]
I just tested Firefox on Windows 10, and it creates new tab by middle-click. Though Chrome and Edge don't.

Also, note Windows opens new instance when middle-clicking a program in the taskbar.
