### ISSUE TITLE
Feature Request:  Export settings to an xml file

### ISSUE THREAD

**Issue by gjb56** [notepad-plus-plus/notepad-plus-plus#342]
When using NP++ on multiple PCs it would be great to be able to export/import all the settings to an xml file

**Comment by Croydon** [comment]
Related to this: I would whish that you can easily change the path where all settings are getting saved. Notepad++ can never support all cloud/synchro apps, but if I could change the path to the directory which gets synchronized it should work fine with the most things.

**Comment by dail8859** [comment]
I agree with this idea. It might work better if the settings were exported to a zip of all the XML files, since it really wasn't designed to glob all the XML settings in a single file.

@Croydon Don mentioned in gitter this would most likely be in a future release, due to the difficulty in locating directories of multiple cloud services across several OSs.

**Comment by xylographe** [comment]
@Croydon  Replace `$APPDATA/Notepad++` with a symlink to your preferred location.

**Comment by Rikk** [comment]
Better install it portable, on a writable folder?

**Comment by milipili** [comment]
see 5e240147c51b6c27f1accbcfa191d9ddc4967e68. If this modification does not suit you, feel free to re-open this issue.

**Comment by gjb56** [comment]
I don’t understand  <https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5e240147c51b6c27f1accbcfa191d9ddc4967e68> 5e24014 but to me it doesn’t appear to address saving the preferences to on location.

**Comment by Rikk** [comment]
Yea, @milipili, that commit has no relation to this "issue" -- which I also don't see the real point.

**Comment by dail8859** [comment]
@gjb56 maybe you could describe your feature a bit more? That way we have a better idea.

**Comment by gjb56** [comment]
One of the big positives' for NP++ is a plethora of user settings.  Under the settings tab you configure preferences, shortcut mapper and style configurator.  I find myself always experimenting (especially with the style configurator).  I would like to EXPORT these setting to an xml file that I could import on other PCs.

**Comment by Rikk** [comment]
>preferences, shortcut mapper and style configurator

You currently need to copy just a few xml files: `config.xml`, `shortcuts.xml`, themes/`your style.xml`.
It looks more organized keeping them separate; why merge them for split later?

**Comment by gjb56** [comment]
I understand there is a work around, it is just not very clean.  There is still no import/export function.  Plus I count 11 xml files.  


Gary J Budnik
972.953.7103

<div>-------- Original message --------</div><div>From: Ricardo <notifications@github.com> </div><div>Date:07/13/2015  11:43  (GMT-06:00) </div><div>To: notepad-plus-plus/notepad-plus-plus <notepad-plus-plus@noreply.github.com> </div><div>Cc: gjb56 <gbudnik@ngnservices.com> </div><div>Subject: Re: [notepad-plus-plus] Export settings to an xml file (#342) </div><div>
</div>preferences, shortcut mapper and style configurator

You currently need to copy just a few xml files: config.xml, shortcuts.xml, themes/your style.xml.
It looks more organized keeping them separate; why merge them for split later?

**Comment by glennfromiowa** [comment]
This [issue](https://notepad-plus-plus.org/community/topic/13354/save-user-data-during-upgrade_or-only-uninstall) has come up again, and although it's old, just wanted to bring up a couple of points:
1. Commit [5e24014](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5e240147c51b6c27f1accbcfa191d9ddc4967e68) does appear to address saving settings in an alternate location. That's awesome; I didn't know about that before.
2. However, it doesn't address **backing up** the settings, and only locates certain settings in the cloud.
    a. In addition, it doesn't address backing up plugins, themes, etc. or any settings used for them.

As I understand it, there are 3 places config files can be:
1. In the user's AppData folder
2. In the install folder for Notepad++
3. In the folder specified by the cloud\choice file

Although it's _possible_ to determine which location is being pulled from, especially using the _Debug Info_ in Notepad++, there are enough questions on the forums about _settings not being saved_ to indicate that's **confusing to _most_ users**. And although it _is_ possible to just copy the files from the appropriate location to make a backup, since **most users are confused about which location** Notepad++ is using, I think it would be an excellent idea to **have an _Export Settings_ option** available, since Notepad++ already **knows** where it's pulling the settings files from. It should not only copy the 10† files mentioned in [Configuration Files](http://docs.notepad-plus-plus.org/index.php/Configuration_Files), but also the folders _plugins_, _themes_, and possibly _localization_, which may be in a **different** location than the main configuration files.

† _session.xml_ appears to not be saved in the cloud location, which probably is appropriate - it should remain saved locally, but, oh, I would be lost if it forgot which files I was editing!!! However, there is already a Save Session option available for that purpose.

I think @dail8859 had the best idea:

>It might work better if the settings were exported to a zip of all the XML files, since it really wasn't designed to glob all the XML settings in a single file.

It wouldn't need to be in a zip file necessarily, although that would give the functionality requested.  I'm planning to open a new issue on this, unless I hear back that it would be better to re-open this one?
