### ISSUE TITLE
Queue Overflow Bug 

### ISSUE THREAD

**Issue by mhdazeem** [notepad-plus-plus/notepad-plus-plus#3453]
### Description of the Issue

When Open a Folder as Workspace, initially it works fine but as long as open a new folder in the same instance sometimes it gives the error that "Queue Overflow" message box and continuously opens the message box for a certain number of folders. I believe its due to some kind of threading or buffer overflow.

### Steps to Reproduce the Issue

1. Open few folders as a workspace lets say 4 to 5
2. Now open the file explorer and now open any of the folders we have in notepad++
3. delete or copy or paste few files or if it's a project folder then try to build it using the specific IDE for
example MS Visual Studio

### Expected Behavior
it should not open multiple message boxes saying Queue Overflow

### Actual Behavior
simply work

![queue overflowed](https://user-images.githubusercontent.com/5148166/27678605-b48b3f24-5cad-11e7-9417-ab05449fecb9.PNG)

**Comment by smx-smx** [comment]
I have the same problem aswell.
It happens frequently when working on a folder that is opened in Notepad++ as "Folder as Workspace"

Common means to spawn the error messages are working on the git tree, e.g checking out files, or building a project (using GNU Make in my case)

I also noticed that, in those circumstances, the left sidebar (directory tree) tends to refresh many times, once for each directory change perhaps?

The problem seems to be https://github.com/notepad-plus-plus/notepad-plus-plus/blob/51797bf59e689b11d80998758790f8a4cade68eb/PowerEditor/src/WinControls/ReadDirectoryChanges/ReadDirectoryChanges.h#L119

So the default queue length is 1000, which apparently is too low.
It would make sense if accounting for the refresh time happening on each change (as experienced above). If the notification queue has to wait for UI refresh then it would fill with more events than it can dispatch

**Comment by davy7125** [comment]
I also experienced this problem and this is quite important because after having closed some of these messages Notepad++ crashes. I have this issue when Notepad++ is open and when I'm updating the directories in the same time (development environment - all directories can be cleared / updated).

By the way, just before the messages I can see that the tree is blinking. Maybe this issue is linked.

**Comment by renaatdemuynck** [comment]
I also encounter this whenever npm is updating my node_modules folder. Restarting Notepad++ or removing/re-adding the project folder fixes the problem.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest 64 bit version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by amai2012** [comment]
I get this message very often
In the current session it did not open even a directory as a folder, but did before...
NotePad++ v7.7.1 (64bit), Windows 10.

**Comment by AnReZa** [comment]
I'm also affected by this bug in version 7.7. It is *not* fixed yet.

**Comment by renaatdemuynck** [comment]
I've encountered the problem again yesterday in version 7.7 after doing a `composer update`.

**Comment by renaatdemuynck** [comment]
Perhaps a one second delay instead of immediatly updating the tree could fix the problem?

**Comment by Skasi** [comment]
I've started encountering the same popup recently using Notepad++ v7.7.1
![grafik](https://user-images.githubusercontent.com/132906/62456247-4f8b5280-b778-11e9-92c9-46bcc531b60f.png)
