### ISSUE TITLE
Add Open all files command to Folder as Workspace

### ISSUE THREAD

**Issue by crypto-rsa** [notepad-plus-plus/notepad-plus-plus#3515]
### Description of the Issue
There is no way to open all files at once in a _Folder as Workspace_.

### Steps to Reproduce the Issue

1. Add some folders to the _Folder as Workspace_ panel
2. Right click on a folder in that panel

### Expected Behavior
There should be a command _Open all files_.

### Actual Behavior
There is no way to open all files in a folder at once.

### Debug Information
Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll HTMLTag_unicode.dll LocationNavigate.dll mimeTools.dll NppColumnSort.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll NppToolBucket.dll PluginManager.dll PythonScript.dll XmlNavigator.dll XMLTools.dll

**Comment by DanielTheGreat** [comment]
This issue was lodged in 2017, but there seems to have been no action towards implementing it.

I too would very much like to see this feature added to Notepad++.

A typical scenario for me is needing to work on a project (by others) that contains multiple sub-directories each containing multiple files (.c, .h, etc).  In order to locate specific functions, variables, etc, using the 'Find in all open files', the files need to first be opened in editing tabs.  Having to open a number of folders and drag dozens of files into the edit pane is a pain!

**Comment by sasumner** [comment]
@DanielTheGreat It would probably add some strength to your argument (don't get me wrong, it isn't a bad request at all) if you could describe why Find-in-Files (with appropriate Filters) doesn't help in this situation.

**Comment by DanielTheGreat** [comment]
@sasumner   I'm only a casual user of Npp, thus not familiar with many of its features.  I had not used Find-in-Files before, but tried it on your suggestion.  I struck a few (minor) problems, which (for me) make it a little slower (more steps) to achieve the desired result compared to 'Find in all open files'...

Firstly, when initiating FiF, rather than defaulting to the currently-open 'workspace', it defaults to some ancient directory I must have used eons ago.  So I first had to navigate it to my workspace directory.  When I then just clicked 'Find all' (no filter), it found 20 instances of my function name, only four of which were in .c or .h files.

Then I tried what seemed like a logical filter term: '*.c, *.h', but it only returned the one instance in a .h file.  Obviously the filter syntax is not 'intuitive' (or flexible regarding term separators – after reading the (old version) manual I find it's only spaces that will work).

But yes, FiF can help me a lot.  Thanks for alerting me to it.

**Comment by sasumner** [comment]
@DanielTheGreat 

There's a "Follow current doc" checkbox.  Tick it.  Then FindInFiles won't default to an "ancient directory", it will default to the dir of the file you are currently editing.

Space separation of multiple filespecs for a filter is as "old as the hills", not only in Notepad++ but in many many other programs.  Granted, with spaces being allowed in filenames these days, maybe this "standard" way of doing it could use some new thinking.

**Comment by DanielTheGreat** [comment]
@sasumner  Thanks for the further usage pointers, but that doesn't solve the problem...

Some 'workspaces' contain multiple sub-directories, a common directory structure (e.g. for Renesas e2studio projects) including 'Includes' and 'Source'.  So if I'm in a .c file (in Source sub-directory) and want to find all references to a particular function, ticking the 'Follow current doc' checkbox will only search other files under 'Source', and *miss* all the .h files in 'Includes'.

Daniel

**Comment by sasumner** [comment]
So the "follow current doc" suggestion was only meant to get you a lot closer to the needed directory than without it (I'm thinking the "ancient directory" mentioned before was way-far away!).  Perhaps you'll need to delete off the right part of the dir once the FindInFiles box appears and populates the dir to search box, to do your "upper-level" search.

I'm sure there are other things that help as well. Perhaps maintaining a session with all of your possible files already open is a help.

And please note, these suggestions are just meant to ease your pain before someone can look into making a source code change per your original suggestion.

**Comment by DanielTheGreat** [comment]
Yep, understood.  And I do appreciate all your suggestions, which will certainly 'ease my pain'!

Note that it wasn't "my" suggestion – I just seconded the original suggester (crypto-rsa)'s request (though I'm sure many other users have also longed for this improvement).  Note that crypto-rsa's request for an 'Open all files' command is often too broad.  In the case of a Renesas project, that would open all sorts of useless (to me!) .xml and other 'project housekeeping' files.  I'd really like to see the 'Open all files' command come with a filter facility (like FiF) so that I could, for example, just open all *.c and *.h files in a workspace (all sub-directories).

Daniel

**Comment by donho** [comment]
It's kind of over-killed feature to me and I am likely to not implement this feature.

**Comment by crypto-rsa** [comment]
I have a folder in Folder as Workspace with 16 XML files which I very often work with. So before I start, I need to:

1. right-click the folder
1. click Copy path
1. click Open
1. paste the folder path
1. click Open (that opens the folder in the open dialog)
1. select all files
1. and finally click Open

Surely a single context menu command is not an _over-killed_ way to achieve this. If FaW is meant to streamline working with common files and folders, shouldn't this actually be one of its basic features?

**Comment by CmsWares** [comment]
I'd like to voice support for adding in the "Open All Files" option for Folder as Workspace. Typical use case is, I have several instances of NP++ open, each with files from a particular set of related code, typically everything inside a given folder.

Saving and loading sessions or other "tailoring" solutions isn't really a solution, because I really can't be bothered creating and chasing sessions for each possible case. It would be much simpler to simply click "Open All" from the relevant folder.

There's already functionality for opening all files in a folder in the CLI, where ```notepad++.exe c:/codes/some/dir``` opens up NP++ with all files in the given directory opened. Can't this simply be mapped to an option in the right-click menu?

**Comment by CmsWares** [comment]
OK so I officially got tired of opening all-files-per-directory all over again. Until we have something better, here's a quick fix using the PythonScript plugin.

1. Create a new script, e.g. ```OpenCurrentDirFiles.py```:

```
import os
import glob

dirName = os.path.dirname(notepad.getCurrentFilename())
matchPattern =  dirName + '\\*.*'

fileList = glob.glob(matchPattern)

for filePath in fileList:
	notepad.open( filePath )
```
2. Map to shortcut, e.g. ```CTRL+ALT+SHIFT+O```. (Clear the conflicting "Open in Outlook"  shortcut!)

3. Open any file in your desired target folder.

4. Hit the shortcut; all files in that folder are opened. (N.B. Refine the ```*.*``` filter if you have binary files mixed in.)

5. Enjoy the decrease of wear on your buttons, your fingers, and your mind.

**Comment by alankilborn** [comment]
@CmsWares 

While I'm all for a script, why not simply do Ctrl+o, click once in the area where the filenames for the folder are shown in the _Open_ window that appears, press Ctrl+a, then press Enter?

**Comment by CmsWares** [comment]
@alankilborn ha right that would get the job done. It's four actions vs. one though, doesn't quite sizzle like a one move hotkey script. Discovered an interesting side-effect though; when in a blank tab, the script tries to open everything in ```C:\```, so. Sizzles hard. Updated the script to match.
