### ISSUE TITLE
"<<Find" (Find Previous) button is disabled for "Regular expression" search

### ISSUE THREAD

**Issue by bahusoid** [notepad-plus-plus/notepad-plus-plus#3533]
Is there any particular reason for this? Looks like a bug to me (considering that Shift+Enter works)

**Comment by dinkumoil** [comment]
Backwards search/replace was disabled for regular expression mode in Npp v7.3.3 too. I guess this operation would be too complex.

**Comment by dinkumoil** [comment]
Seems to be reverted. See 4d921b7

**Comment by sasumner** [comment]
If one traces through the history on this, one will see:

- pre-7.4.2 had up/down direction radiobuttons; up gets disabled when reg exp search mode is selected (has been this way since around version 6.3)

- 7.4.2 had got rid of up/down direction radio buttons and added <<Find and FInd>> buttons; <<Find gets disabled when reg exp search mode is selected (mimicing the pre-7.4.2 behavior)

- 7.5 got rid of the <<Find and Find>> buttons and added the backward-direction checkbox; this checkbox gets disabled when reg exp search mode is selected (mimicing the earlier behavior)

Thus, I don't see this as a real issue, unless the issue author is contending that the behavior since 6.3 is wrong.  I don't because I see backward regular expression searches as a "bad thing".  Regular expression engines are designed to work from a given position forward, not backward.

**Comment by sasumner** [comment]
Worth noting is that although upward/backward regex searching has been disabled via the Find dialog since 6.3, regex searches upward/backward with the "Find Previous" menu command ("Search" menu) or its default shortcut key (Shift+F3) have worked in every version from 6.3 to 7.5.  It would really be nice to clear up this inconsistency, one way or the other!

**Comment by uhammec** [comment]
Can we get the "< <Find" and "Find> >" buttons back that were implemented in 7.4.2?

That was very nice versus having to remember to select a "Reverse"  radio button (pre-7.4.2) or check a "Backward Direction" checkbox (7.5.1).  Moving the radio button from next to the "Find Next" to a list of search check boxes on the left was not really obvious at first. 

If the regexp backward search can't be solved, keep the "<<Find" but grey it out like the "Backward direction" checkbox is in 7.5.1.
