### ISSUE TITLE
Bug: Keep non existing file (edited from 7zip) but file exist

### ISSUE THREAD

**Issue by WiliTest** [notepad-plus-plus/notepad-plus-plus#3548]
### Steps to Reproduce the Issue
in windows 10 with the last np++ (and 7-zip) version:

1. open a a test.jar folder using 7-zip containing several files such as x.htm
2. now try to edit a file on it: either by dropping  x.html file from (from test.jar folder) into notepad++ or by double click on it.
3. go to np++, the file will be there.
4. But now go to desktop, and come back to notpad++ you will get

>   x.html doesn't exist anymore. Keep this file in editor?

But within 7zip using the context menu "edit" does work (the file will remain in np++). So the issue is only when we drag drog files from 7zip to np++ or when we double click on it (bypassing the "edit" of the 7-zip context menu).

**By the way there is also another bug (which could (also?) come from 7zip):**
Editing the 7zip file using np++ won't be detected by 7-zip unless you shutdown completly np++ (saving the file in a tab doesn't count as a save apparently) cf. https://sourceforge.net/p/sevenzip/bugs/2070/

**Comment by SinghRajenM** [comment]
This is 7-zip's behavior. When you do drag n drop (from archive such as .zip, .rar or any other) notice that a copy of dragged file is created in %temp% and gets deleted quickly.
To see this behavior, try to drag n drop on Window's notepad. You will get below error because file get deleted quickly.
![image](https://user-images.githubusercontent.com/14791461/28488376-f9c3e1f2-6ec5-11e7-8180-0aa6b1c912b0.png)



N++ is advance, even though the file gets deleted. It gives an another chance to user to keep n save the file somewhere else. :)

![image](https://user-images.githubusercontent.com/14791461/28488339-ff13443c-6ec4-11e7-9a60-0ecd3c83f401.png)

**Comment by WiliTest** [comment]
thanks for your reply and the print-screens! I forward this to 7-zip. Hopefully, they will manage to do something about it.
