### ISSUE TITLE
Unused variable in EncodingMapper.h

### ISSUE THREAD

**Issue by rushikesh90** [notepad-plus-plus/notepad-plus-plus#357]
In the file PowerEditor/src/EncodingMapper.h an unsed private member     EncodingUnit *_encodings;
is defined. I am not sure why it is declared there but if there is no use it should be removed.

**Comment by Rikk** [comment]
Unless it should not have the underline there, because it is defined without underline in https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/EncodingMapper.cpp#L34

Let's wait some veteran dev look at this...

**Comment by rushikesh90** [comment]
Also the private member of class is not used. The line you mentioned is creating and using the same structure and name but is not related to class.

**Comment by milipili** [comment]
Sorry but as previously said, this kind of issue will be temporarily labelled as "won't fix"

**Comment by Rikk** [comment]
Is it about the reformat?

**Comment by Rikk** [comment]
@milipili, Could you please point where it is discussed that cleaning up the code is something to be avoided?

**Comment by milipili** [comment]
You're right. The discussion might not have been seen by everyone. It is not that the code does not require some cleanup. The code base needs some refactoring to evolve. Somehow the current code base is frozen. As said in other issues, this issue is labelled as "won't fix" to be easily found when we will work on that part. See #217

**Comment by ariccio** [comment]
> Could you please point where it is discussed that cleaning up the code is something to be avoided?

The most direct reference is in #207.

It's not clearly spelled out (*per se*) that *clean up* Pull Requests are rejected, but it's a *de facto* standard for `Notepad++`.  

The closest thing thereto is in [`CONTRIBUTING.md`](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md):

> All Pull Requests, except for translations and user documentation, need to be attached to a issue on GitHub. For Pull Requests regarding enhancements and questions, the issue must first be approved by one of project's administrators before being merged into the project. An approved issue will have the label `Accepted`. For issues that have not been accepted, you may request to be assigned to that issue.

> Opening a issue beforehand allows the adminstrators and the communitiy to discuss bugs and enhancements before work begins, preventing wasted effort.

**Comment by Rikk** [comment]
The need for spending time with a complete code refactoring itself is the result of a failure in accepting smaller commits that would otherwise fix small problems as soon as they are spotted, and a failure in ensuring only code with good quality (well-formatted and well-thought) is published.

In the meantime, however, old code is fated to abandon, because the work is going mainly onto the reformatted version. Fixes to old code that are also good to the new one, logically should be picked selectively/manually; therefore, it doesn't matter whether it receives or not small reformats.

Furthermore, for being essentially public, open-source software should allow broad, open participation in the code refactoring itself. When it starts, these questions ought to be answered: What is the branch containing the changes? What files are being worked on currently? What changes are being made?

**Comment by ariccio** [comment]
> The need for spending time with a complete code refactoring itself is the result of a failure in accepting smaller commits that would otherwise fix small problems as soon as they are spotted, and a failure in ensuring only code with good quality (well-formatted and well-thought) is published.

> In the meantime, however, old code is fated to abandon, because the work is going mainly onto the reformatted version. Fixes to old code that are also good to the new one, logically should be picked selectively/manually; therefore, it doesn't matter whether it receives or not small reformats.

> Furthermore, for being essentially public, open-source software should allow broad, open participation in the code refactoring itself.

I agree. That said, [*your disagreement is not with me*](https://github.com/notepad-plus-plus/notepad-plus-plus/pulls?q=is%3Apr+is%3Aclosed+author%3Aariccio).

**Comment by Rikk** [comment]
True. I would merge your commits and much others if I could understand and review that kind of changes.

**Comment by ariccio** [comment]
> I would merge your commits and much others if I could understand and review that kind of changes.

Fear not, nobody understands C++!

> Just ignoring errors, inefficiencies and similar makes no sense to me at all.

At least  @milipili is [more consistent than don ho](
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/180#issuecomment-114680777)

**Comment by milipili** [comment]
It is certainly not a failure in accepting smaller commits. Smaller commits won't improve the global code architecture and won't really change anything from the project point-of-view. We only want to take some time to upgrade the global structure to make sure that the project will continue to grow and that it will continue to be a good alternative to other editors. This kind of changes is certainly not something that can be done by 50 people with 50 way of thinking radically different. I understand your frustation, however it will only be a waste of time for everyone (taken on our free time). That's why the current code base is somehow frozen.
In the new code, PR should not be a problem from my point of view even at the begining (a new folder `src` will come, and the code will be rewritten piece by piece). And we will try to provide "roadmap" issues to explain the ongoing work.
I am *sure* that you will understand.

**Comment by ariccio** [comment]
> At least @milipili is more consistent than don ho.

^ [case and point](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/357#issuecomment-117053912)

**Comment by ariccio** [comment]
> case and point

Grr. [I've mutilated it](https://en.wiktionary.org/wiki/case_and_point).
