### ISSUE TITLE
Plugin update problems

### ISSUE THREAD

**Issue by dlong500** [notepad-plus-plus/notepad-plus-plus#36]
I'm trying to update some plugins (DSpellCheck and NppFTP), and I'm getting the following error for both of them:
![screenshot 2015-05-07 11 48 51](https://cloud.githubusercontent.com/assets/430481/7519576/0ed54db2-f4af-11e4-842d-71945e4c176d.png)
Any suggestions?  I'd rather not just blindly accept things especially with the shady nature of Sourceforge lately.

**Comment by einst3** [comment]
this happens on any plugin when is updated or installed to let you know that you are installing a potentially dangerous file.

updating plugins regularly is good but i personally dont update the pre-installed plugins that come with npp because the newer version may break or not work correctly in npp. you can always see the current installed plugins in the npp change.log in the Notepad++install folder.

**Comment by dlong500** [comment]
That error has never popped up for me until now and I have been using Notepad++ and updating plugins for the past 5 or more years.  I think the issue was a temporary one with SourceForge because I just tried it again and it worked without giving that message, so that implies there is some type of validation/hash check on the file to make sure it is the correct one before running the update.

As for your recommendation about not updating pre-installed plugins, I'm not sure I follow the logic.  If there are updates to Notepad++ and updates to the pre-packaged plugins it would seem a lot more likely that NOT updating the plugins could eventually break things.  As for third party plugins it will always be a free-for-all in that regard, but the plugins released with the editor itself would seem to always be safe to update.

**Comment by einst3** [comment]
i tried that in the past giving me the same issue or causing some features to not work. updating to the latest plugin is not always good because it could break or use functionality that is not yet debugged fully on many systems, or released in npp but may be in scintilla and vise versa. ive had no problems with updating any plugin that did not come preinstalled with npp. updating the plugin manager itself i have found problematic so that one i do leave alone.
