### ISSUE TITLE
Improper autospacing of closing brace "}"

### ISSUE THREAD

**Issue by bigdavesolns** [notepad-plus-plus/notepad-plus-plus#362]
Autospacing of the indent level gets confused if braces are used within string literals.
Known as issue within Javascript editor

Example-

``` javascript
function foo(bar)
{
    var bat = 0;
    while (bar.indexOf('{L', bat) >= 0) {
        var baz = bar.substring(bat, bar.indexOf('{', bat));
        }
    }
```

when type } on next line, it doesn't decrease the indentation level, but the next } does decrease indentation level, however it should close the function.  The editor highlights the correct matching { however.

**Comment by milipili** [comment]
Another example for requiring a true language-specific parser.

**Comment by bigdavesolns** [comment]
Seems to me as a general bug.  I just tried it in the C++ editor, and the same scenario happened.

Example-

    void main() {
        string str="{{{";
        while(str=="{{{") {
            int a=str.find('{');
            }
        }

Same as before- highlights proper matching brace, but doesn't indent the typed closing brace to the proper place.

**Comment by tonyk24** [comment]
There is a Scintilla message for this, but it doesn't seem to work.

SCI_BRACEMATCH(int pos, int maxReStyle) → position
The SCI_BRACEMATCH message finds a corresponding matching brace given pos, the position of one brace. The brace characters handled are '(', ')', '[', ']', '{', '}', '<', and '>'. The search is forwards from an opening brace and backwards from a closing brace. If the character at position is not a brace character, or a matching brace cannot be found, the return value is -1. Otherwise, the return value is the position of the matching brace

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by bigdavesolns** [comment]
Still an issue.  Debug Info:
Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : D:\programs\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll
