### ISSUE TITLE
NPP Portable: _isLocal is set to "false"

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#3661]
Windows 7.

Create a folder `NPP` under `Program Files` and unzip or paste the Notepad++ zip package there.
You can add `doLocalConf.xml` to that folder and `Local Conf mode` is `ON`.

Still, in Parameters.cpp `_isLocal` is set to `false` and the folder `Notepad++` is created under `%appdata%\local` even after https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5b5dfb90a8c8654a4d911e97ead29d8ce7988a89.

```
if (_isLocal)
{
	// We check if OS is Vista or greater version
	if (_winVersion >= WV_VISTA)
	{
		generic_string progPath = getSpecialFolderLocation(CSIDL_PROGRAM_FILES);
		TCHAR nppDirLocation[MAX_PATH];
		lstrcpy(nppDirLocation, _nppPath.c_str());
		::PathRemoveFileSpec(nppDirLocation);

		if  (progPath == nppDirLocation)
			_isLocal = false;
	}
}

```

**Comment by donho** [comment]
It means when you install in "Program files"in all windows, you must use "%APPDATA%\Notepad++"  , doLocalConf is not taken account.

**Comment by vbojan** [comment]
I'm not sure I understand the purpose of doLocalConf.xml because NPP still pulls configuration from roaming profile with or without this file being present.

What I believe started with 7.5 (or maybe even with 7.4.2) is that NPP started creating  "%APPDATA%\local\notepad++" empty folder during launch.
I tried 7.5.1 which references this as being fixed, but it still creates the folder with or without doLocalConf.xml being present.

**Comment by Yaron10** [comment]
> It means when you install in "Program files"in all windows, you must use "%APPDATA%\Notepad++"

Do you mean you must use `%APPDATA%\Local\Notepad++` only for the upcoming Plugin Manager?
If you mean you must use "%APPDATA%\Notepad++" *for all settings* - NPP path on my machine is under `Program Files` and `Local Conf mode` is `ON`.

Thank you.
