### ISSUE TITLE
php "md5" function colorizing bug

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#3683]
I don't think there is much to write -- The picture explains everything: https://i.gyazo.com/c7b728f849f4330b540061f62f7302a9.png

```<?php

class A
{
	private $bar;
	
	function foo()
	{
		$this->bar.md5(); // <- md5 not blue?!
		$this->bar. md5();
		$this->bar .md5();
	}
}
```

**Comment by MAPJe71** [comment]
```php
<?php
class A
{
	private $bar;
	function foo()
	{
		$this->bar.md5notblue();
		$this->bar. md5notblue();
		$this->bar .md5notblue();
	}
}
?>
```

Is `md5` maybe a PHP keyword?

**Comment by crylessdomore** [comment]
Maybe I had to add a description of the problem because you understood the opposite. I thought it was obvious but I realize that it may not be clear to everyone.

md5 is a PHP keyword and for this reason should appear in blue also in the first case since the '.' is only for concatenation and should not have any influence on it (At least I think so).

**Comment by azlux** [comment]
`$this->md5($bar)` will be blue because it's a string function (http://php.net/manual/en/function.md5.php) with the string as parameter. And it's not a reserved keyword (http://php.net/manual/en/reserved.keywords.php)

**Comment by crylessdomore** [comment]
I do not know where you have pulled out $this->md5 that does not have anything to do with what I am saying here:

```
<?php

$this->bar.md5() // md5 should be blue but it does not!!
$this->bar. md5()
$this->bar .md5()
```

They are the same thing but in first example md5 does not appear blue while it should because '.' is only for concatenation.

Bug: Keywords concatenated to members are not highlighted.

**Comment by ArkadiuszMichalski** [comment]
Looks like this was fixed in the past.

![image](https://user-images.githubusercontent.com/2730894/220632467-8a844ab6-f9bd-46e0-ba93-239536c0639c.png)
