### ISSUE TITLE
read hex file wrong result

### ISSUE THREAD

**Issue by zhanghaogithub123** [notepad-plus-plus/notepad-plus-plus#3697]
### Steps to Reproduce the Issue

1. read the a hex file which actual byes are '\x9c\xa6\xbf\xd8' with a plugin hex-editor 

### Expected Behavior

it should be display '\x9c\xa6\xbf\xd8'

### Actual Behavior

the result show 'd1 8e d0 b4 e2 94 90 d0 bf '

**Comment by zhanghaogithub123** [comment]
the attachment is the issued file.
[test.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1274858/test.zip)

**Comment by dail8859** [comment]
The Hex editor plugin is not part of the official Notepad++ project. This needs reported to the author of the Hex editor.

**Comment by Cyrillev91** [comment]
Hi,

Test file is read with "OEM 855" encoding file (detect by notepad++). 
![encodingoem_855](https://user-images.githubusercontent.com/12849364/30036484-0b83e822-91b4-11e7-8f33-65b8d05da511.jpg)


I noticed that Hex editor works fine if the encoding detected by notepad++  is: 
* ANSI
* UTF-8
* UTF-8 BOM
* UCS-2 BE BOM
* UCS-2 LE BOM

not OK with UCS2-BE (without BOM), and other (OEM 855)


I try reload test file with ANSI encoding : ***Encoding >> Encode in ANSI*** but without success
http://docs.notepad-plus-plus.org/index.php/Convert_Or_Encode%3F
The option Encode in .... OR Character sets / .... / ...., apply the chosen encoding to the actual contents of the current file.

**Comment by zhanghaogithub123** [comment]
Got it. Thx Cyrillev91, have a good day :)

**Comment by Cyrillev91** [comment]
Hi,
try this :
You can disable autodetect character encoding:
`preferences >> MISC >> disable the Autodetect character encoding`

Open test file : 
now is open with ANSI encode and Hex editor display correct '\x9c\xa6\xbf\xd8'

**Comment by DacoTaco** [comment]
disabling the preference seems to work. (had the issue opening a gameboy save file)
however, what kind of changes will that bring? 

also, any idea why this happens? ive been using notepad++ for ages as hex editor and didn't come across this untill now :/

**Comment by Yang-z** [comment]
> disabling the preference seems to work. (had the issue opening a gameboy save file)
> however, what kind of changes will that bring?
> 
> also, any idea why this happens? ive been using notepad++ for ages as hex editor and didn't come across this untill now :/

Hi, normally there is no problem when a file is of vaild 'utf-8' or any other other encoding method. However, if the file is a raw binary file without any encoding, notepad++ attemps to detect the encoding method of the file, and, and try to fix the invilad code points(or do some conversion based on wrongly detected encoding). Then the content is modified and passed to hex editor plug-in.

It normally happens when a byte is big than `0x80` where notepad++ thinks some kind of encoding takes place, but, no there are just raw bytes we want.

`disable the Autodetect character encoding` just let the hex editor to work with the exact bytes as on the file. There should be no side effects in terms of editing binary file.
