### ISSUE TITLE
Make document tabs behave more like Google Chrome tabs

### ISSUE THREAD

**Issue by shoelzer** [notepad-plus-plus/notepad-plus-plus#3719]
Notepad++ has document tabs for working with multiple open files but there is room for improvement. I think Google Chrome has an excellent tab implementation and Notepad++ should adopt some of those ideas. Specifically:

* All tabs in a window are always the same width.
* Tab width starts at a wide default and then shrinks as needed when all the tabs don't fit in the window.
* When closing the right-most tab, remaining tabs resize to fill the available space.
* When closing any tab except the right-most one, tabs to the right will shift left to fill the gap. In this case, tabs do not change width until the mouse moves away from the tab bar.

The last two points make it easy to close multiple tabs quickly because another tab's close button ends up under the cursor and you can click again without moving.

**Comment by Yincognyto** [comment]
Why on earth do you believe that shrinking tabs to the point where you can't even see what's there is a good idea? Chrome is aweful in that respect. Ok, maybe do this while you can still see the entire title, but not shrinking them to the size of a pinned tab. By the way, pinned tabs would also be a good idea (as are your other points, besides the extreme shrinking one).

**Comment by ke352802081770314** [comment]
Web pages often have quite long titles, so it is reasonably that a browser does not display the full title, only when hovering on the tab. However, filenames (without path) are often quite short, and if they are longer, it very much depends on individual circumstances whether the most significant part is their beginning, or near the end (e.g. in a C programming project, .c and .h files with the same base name may be mixed, and need to be distinguishable). So truncating filenames in the tab titles seems a very unhelpful idea to me. Best using the space by having variable width tabs seems most helpful to me, so I would appreciate if it stays the same.
I clicked on this item because I thought you are referring to keyboard handling. I'm not a Chrome user myself, but it seems that Firefox is quite similar. When clicking ctrl-tab and ctrl-shift-tab in the browser. I switch to the adjacent tab, and from one end I wrap to the other. In NP++ a clunky list of open files appears whose order seems to have nothing to do with the tab order and I have no clue how it was pieced together. So I end of using the mouse for switching tabs.

**Comment by shoelzer** [comment]
Another thing that Chrome does which (mostly) addresses the points raised by @Yincognyto and @ke352802081770314 is to show the full tab title when moused over. Then even if tabs are very small, it's easy to figure out what they are. Notepad++ actually does this already, plus it shows a thumbnail of the document. With these features already in place I don't think narrow tabs would be a big deal.

**Comment by Yincognyto** [comment]
@shoelzer The problem I have with Chrome is not necessarily that the full tab title isn't showed when the tab is shrinked (other than when you hover over it, like you correctly mentioned), but rather that when you have a lot of tabs opened, you can't even point at small tabs easily or reasonably close them without fearing that you'll somehow affect another small tab or close something else by mistake. That's why I think that _extreme_ tab shriking (the sort of which Chrome does) is a bad idea for Notepad++, as I explained in my first comment. I'm ok with shriking to a _reasonable_ width though, just not to less than, say, 1 cm or so - otherwise the functionality of the application is affected, IMHO...

**Comment by uhammec** [comment]
Shrink with flyover seems more natural than having the tabs "disappear" off the page to the right or left forcing you to scroll through the tabs.  Many times I've had too many documents open and forgotten they were out there till I started closing some and presto the forgotten ones come into view.

**Comment by Yincognyto** [comment]
Well, as far as I know, there is also the option of showing tabs vertically
in Notepad++, PLUS you have the 'Windows...' submenu in the 'Window' menu
which shows the tab/window list, so when you have a lot of tabs, it's not
that hard to see everything in one place. Just saying...

**Comment by donho** [comment]
Obviously the described behaviours in this feature request are contestable. I myself don't like these behaviours either. A code/text editor has the different audience than a browser, therefore the different needs IMO.
