### ISSUE TITLE
Macro recording for Line Operations -> Remove Empty Lines doesn't work.

### ISSUE THREAD

**Issue by tico-tico** [notepad-plus-plus/notepad-plus-plus#374]
It looks like macro recording for *Line Operations -> Remove Empty Lines* (both variants) doesn't work. Checked v6.7.8.2 and v6.7.9.2, I don't know if it worked in the previous versions.

1. Click **Start Recording** button
2. Select from menu *Edit -> Line Operations -> Remove Empty Lines*
3. Click **Stop Recording**

Result - **Playback** is inactive.

**Comment by guy038** [comment]
Hello **tico-tico**,

I suppose that you would like to create a macro, in order to be able to affect a user shortcut, for this operation,  wouldn't you ?

Indeed, the two entries **Remove Empty Lines** and **Remove Empty Lines (Containing Blanck characters)** can't be found in the **Shortcut Mapper** :-((

Luckily, you still can create a macro, which does a search/replacement with **regexes**, to delete these **specific** lines

---

To do so :

- In a **new** tab, type some text, with few **blank** lines

- Select the menu option **Macro - Start recording** OR the **red circle** button, on the **Toolbar**

- Open the **Replace** dialog ( **CTRL + H** )

- In the **Find what** zone, type **`^\R`** ( for **exact empty** lines ) or **`^\h*\R`** ( for **empty** lines with **blanks**, only ) 

- Leave the **Replace with** zone **EMPTY**

- Check the **Wrap around** option

- Select the **Regular expression** search mode

- Click on the **Replace All** button

- Select the menu option **Macro - Stop Recording** Or the **black square** button, on the **Toolbar**

- Open the menu option **Macro - Save Currend recorded Macro...**

- Type, for instance, **Suppress BLANK and EMPTY lines**, as the current **name** for this macro

- Choose a shortcut for this macro ( Take care NOT to use an **existing** Notepad++ or plugin shortcut ! )

- Click on the **OK** button, to valid your choices

Best regards,

guy038

**Comment by tico-tico** [comment]
Hi, guy038.

> I suppose that you would like to create a macro, in order to be able to affect a user shortcut, for this operation, wouldn't you ?

No, actually it should have been a part of some bigger macro operation for fast-cleaning my CSS-file out of empty-lines, comments and all that unneeded stuff. So I did use regexps for cleaning comments and as a workaround for a broken "Remove Empty..." options.
But since I faced this bug I decided to report it anyway.

I never heard about `\R` before (always used `\r\n`). Nice piece of information, thanks!
