### ISSUE TITLE
Reverse selected lines

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#3783]
### Description of the Issue
Provide an option to reverse all selected lines, from last to first. There are already numerous options to sort lines, but none to simple reverse the order of the lines.

**Comment by sasumner** [comment]
You are within your rights to request this as a feature.  However, your request may not be implemented due to other priorities of the developers, it may not be implemented for years, or the developers may not see the same value in having this feature as you do.  Given all that, there are existing ways of reversing lines (as an example:  https://sourceforge.net/p/npppythonscript/discussion/1199074/thread/e61f36ec/)

**Comment by ygoe** [comment]
I am well aware that development on this project has almost stopped. I just wanted to note it down here anyway so it won't be forgotten so easily.

**Comment by alankilborn** [comment]
Capability added in N++ 8.0.
See #9837

This issue can be CLOSED.
