### ISSUE TITLE
Cannot open (any) file when file is strored in a mapped drive and Notepad++ is opened as an 

### ISSUE THREAD

**Issue by joaogoncalv-es** [notepad-plus-plus/notepad-plus-plus#3847]
### Description of the Issue

Cannot open (any) file when file is strored in a mapped drive and Notepad++ is opened as an Administrator

### Steps to Reproduce the Issue

1. Launch Notepadd++ as an Administrator
2. Locate a file that is stored in a mapped drive (this example V:\ will be the mapped drive)
3. From the file: "Open with Notepadd++" or "Edit with Notepad++"

### Expected Behavior

The document should be opened with Notepadd++

### Actual Behavior

Error instead
- Error Title: Cannot open file
- Error Message: "V:\Folder\File" cannot be opened: Folder "V:\Folder" doesn't exist

### Debug Information

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\apps\notepad\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

### Additional information
This windows is actually Windows Server 2016 64b en, but it also occurs in Windows 10.
From Notepad++ opened as an Administrator, File » Open, it is not possible to see mapped drivers.

**Comment by dtfinch** [comment]
This is an intentional Windows bug by design, for no plausible reasons whatsoever, outside the control of Notepad++ or any other app. Maybe it's to encourage users to turn off UAC, or it's to embarrass MS, but again neither reason is plausible.

https://superuser.com/questions/199387/elevated-command-line-prompt-cant-access-shared-drives

There is a "EnableLinkedConnections" policy registry key that some have suggested, in HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System. Setting it to the dword "1" works for some people, but not for everyone. I already have UAC off so I don't know when it works or doesn't.

You could also try using full UNC paths if you're going to open something as another user.

**Comment by joaogoncalv-es** [comment]
It never crossed my mind that this issue could be related with a Windows limitation.
Normally I have Notepad++ open as a normal user, so I wont even try to fix it for me.

**Comment by Crayder** [comment]
Okay I found the problem and I know this is months later but I bet you guys were also running Notepad++ from the shared drives. The problem is the installation of Notepad++ being ran from a network location doesn't have permission to edit files on drives other than it's own (except on the PC it's running on).

For example, on your desktop, PC 1, you have multiple shared drives: oldstuff (C) and newstuff (D). NPP is installed on oldstuff. There are files on D that you want to edit. You want to edit those files in your kitchen using your laptop, PC 2. You have oldstuff mounted on letter D and newstuff on letter E on PC 2. You try to run NPP (installed on oldstuff) to edit a file on the newstuff drive, but get the "drive doesn't exist" error (the problem described in this issue). This happens because Windows on PC 2 never asks if you want to allow NPP to have access to local or remote servers as it did when first installing NPP on PC 1. Go to Windows Firewall on PC 2, add an entry for NPP and allow NPP to edit home files.

**Comment by LouWii** [comment]
@Crayder 's recommendation seems to work. I've added Notepadd++ to Windows firewall, authorized it to access public and private networks and I was able to open a file on a virtual drive (that virtual drive is link to a VM running on VirtualBox). Before doing so, I couldn't open that file.

**Comment by ndgouveia** [comment]
Fun fact:
 If you use the search feature in explorer, you will be able to open the file through the search results window...

**Comment by viadatecnologia** [comment]
@Crayder . Thats works! I tested this solution and works. 

Thanks a lot.

**Comment by Crayder** [comment]
No problem my dude 🤙

**Comment by liamomg** [comment]
> This is an intentional Windows bug by design, for no plausible reasons whatsoever, outside the control of Notepad++ or any other app. Maybe it's to encourage users to turn off UAC, or it's to embarrass MS, but again neither reason is plausible.
> 
> https://superuser.com/questions/199387/elevated-command-line-prompt-cant-access-shared-drives
> 
> There is a "EnableLinkedConnections" policy registry key that some have suggested, in HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System. Setting it to the dword "1" works for some people, but not for everyone. I already have UAC off so I don't know when it works or doesn't.
> 
> You could also try using full UNC paths if you're going to open something as another user.
> 
> Edit: I just saw the part about Notepad++ being already open, and this happening when opening a new file normally. Maybe Notepad++ could avoid reusing instances that are running as different users, or do so conditionally based on file accessibility.

This works by disabling UAC and restart the notepad++
