### ISSUE TITLE
Column editor Alt+C overwrites in place of inserting 

### ISSUE THREAD

**Issue by nirfrumer** [notepad-plus-plus/notepad-plus-plus#3878]
### Steps to Reproduce the Issue

1. select some text in column mode
2. ALT+C
3. write something in "text to insert"
4. Enter or OK button

### Expected Behavior

Text inserted
### Actual Behavior

Text in selected block is overwritten

**Comment by sasumner** [comment]
Any time you have a non-zero amount of text selected, be it a normal stream selection or a column block, any action that will create text (examples:  keypress, paste, "column editor" insert, etc) will cause the original selection to be wiped out first.

So a valid set of steps for your action might be:
1. create a zero-width column block (also known as "thin caret") at a given column and covering "n" lines
2-4 same as yours

Expected and actual behavior from that would be that your text was inserted at the thin caret column but only on the "n" lines touched by the thin caret.

**Comment by nirfrumer** [comment]
works great
I didn't know this one
thanks
the text on the ALT+C may be replaced from "Insert" to "Replace"...

**Comment by sasumner** [comment]
That text COULD dynamically change based on current INS or OVR mode...or if a selection is currently active...good point.  I think it is the way it is because most people spend 99% of their time in Insert mode so this is the way the developer thought of it when originally it was coded.

If you are happy with the explanation can you Close this issue?

**Comment by sasumner** [comment]
Another thought:  The only reason the "Text to Insert" feature exists is so that you can easily insert text at a given column in the entire document.  Otherwise just do the "thin caret" thing in the desired column on the lines you want and simply start typing--whatever you type will be inserted (or overwrite) on every line originally touched.  In other words, no need to invoke Alt+C
