### ISSUE TITLE
Non-privileged installation?

### ISSUE THREAD

**Issue by thePalindrome** [notepad-plus-plus/notepad-plus-plus#388]
I noticed that with the current install script, if you deny UAC to the installer, it closes. Would it not be helpful to, after having permission denied, assume a single-user installation.

I know NSIS can handle that, I'll do some research.

Thoughts?

**Comment by milipili** [comment]
if it is possible...

**Comment by johnwbyrd** [comment]
There's no way that the Notepad++ NSIS installer should require administrator privileges.  Especially since Notepad++ wants to auto update every time you look at it, user-level permissions should be the default for the installer.

Here's how to support it in the installer.

https://github.com/Drizin/NsisMultiUser

**Comment by MetaChuh** [comment]
closed due to:
* installation to `%ProgramFiles%` and `%ProgramFiles(x86)%` requires elevated permissions

**Comment by minecraftchest1** [comment]
@MetaChuh There are a few apps that install to either `%LocalAppData%/programs`, or to their own folder somewhere in `%AppData%` or `%LocalAppData%`. Could we do that if the user requests single-user/non-privliaged install?
