### ISSUE TITLE
text selection and cursor

### ISSUE THREAD

**Issue by Alexisback** [notepad-plus-plus/notepad-plus-plus#3909]
I wrote in the forum, no answer
replicate here

https://notepad-plus-plus.org/community/topic/14809/text-selection-and-cursor
----------------------
I have a problem

when I select a long text in notepad ++, the cursor returns to the beginning of the line
can you disable this?
I insert a small video to explain it better

https://yadi.sk/i/t5N2ALiG3Puv2M

thanks

**Comment by dail8859** [comment]
Please follow the template and provide a set of steps to reproduce the issue and post your debug info.

Also I'd recommend screenshots or gifs ([ScreenToGif](http://www.screentogif.com/) is a nice tool) as those are easier to deal with since your video will not load for me. If you do need a video please use a less sketch hosting website.

**Comment by Alexisback** [comment]
![notepad cursor](https://user-images.githubusercontent.com/18039740/33133158-f2b15cc6-cfac-11e7-980b-1cb38daa2468.gif)

**Comment by Alexisback** [comment]
thanks for the program

I do not want the cursor to go back

**Comment by dail8859** [comment]
As far as I can tell that after you select the long line you click *under* the line, which puts the cursor at the end of the next line, and scrolls left to show the caret.

**Comment by Alexisback** [comment]
I found the solution alone
go to find / mark
and unckech this "Wrap around"
Resolved
![wrap around](https://user-images.githubusercontent.com/18039740/33232977-80479cec-d220-11e7-8db9-ec263c264cfd.png)
