### ISSUE TITLE
-nosession overwrites settings

### ISSUE THREAD

**Issue by segdy** [notepad-plus-plus/notepad-plus-plus#3938]
### Description of the Issue

When `-nosession` is passed as argument, this setting is stored (and overwritten) when exiting the instance. However, `-nosession` should only be applied for the duration of the session and not stored permanently (if I wanted to have it permanently, I could just change the setting).

**I am fairly confident this used to work already** but suddently my settings are always reset when I start (a different instance) with `-nosession`. I think this bug must have introduced some time recently.

A similar issue existed for `-notabbar` (Bug #5274 on SF) and was fixed.

Background: I would like to use NPP as an advanced editor and as notepad replacement at the same time.

As an advanced editor (when I just execute notepad++.exe) I like the tabs, that my session is saved and that quick new documents are saved in the session althouth the file itself was not saved yet.

As a notepad replacement (which I use for Total Commander) I want a single session (new instance for each file), hence to tabs and and no session management.

For the first case I just use notepad++ as normal, enabling session restoration, tabs etc.

For the second case, when I use

`notepad++.exe -multiInst -nosession -notabbar`

It seems that the session setting is saved in the global configuration, i.e. it interferes with my "main advanced editor": When I close all instances and just open "notepad++.exe" again, the session setting is suddenly reset.

However, I want that "-nosession" only applies to the new and current instance I start with "notepad++.exe -multiInst -nosession -notabbar".

### Steps to Reproduce the Issue

1. Start notepad++ without command line switches and turn session management on (in "Backup").
2. Create another instance with `notepad++.exe -multiInst -nosession -notabbar`
3. Close both instances
4. Open notepad++ again without command line switches and the session management setting is reset

### Expected Behavior
Command line switches should override configuration but never interfere with them

### Actual Behavior
Command line switches interfere with setting (i.e. settings get reset)

### Debug Information
Latest version (7.2.2).

**Comment by santaranger** [comment]
I second this bug report. I actually came here to raise this exact issue and found this thread.

I have my regular np++ window with my saved session information and activated session snapshot for unsaved files, which is a very handy feature.

Now, I  have a special use case where I want a second instance of np++ opening a number of files through a script uising -multiinst/-nosession.

Whenever I close the -nosession instance last, or when the regular instance wasn't open to begin with, the session snapshot setings are reset/deactivated for the regular instance (maybe other settings as well, that I haven't noticed).

I've had this issues ever since I can remember using session snapshots.

I understand np++ has some issues with multiple instances. A quick&dirty fix could be making -nosession instances at least load the same settings as regular instances.

**Comment by segdy** [comment]
I just wanted to check if this is something that will be considered to be fixed?

**Comment by petenattress** [comment]
I have the same issue, when using Notepad++ as my main text editor and also as [Git's `core.editor`](https://help.github.com/articles/associating-text-editors-with-git/#using-notepad-as-your-editor).

In `config.xml`, you can see the `"Backup"` GUIConfig option is overridden if you open a second instance of NPP with the `-nosession` flag and then close it as @segdy describes.

**Comment by n-think** [comment]
using np++ for git and this issue is very annoying, pls fix

**Comment by VoltairesPuppet** [comment]
I use notepad++ in the same way; advanced editor an notepad replacement.  I would like to go a step further though and allow sessions to be stored with reference to "New #"  files.  At the moment this behaviour is specific to the main session file only.
