### ISSUE TITLE
NPPP Flashes Default White On Open

### ISSUE THREAD

**Issue by tilkinsc** [notepad-plus-plus/notepad-plus-plus#3955]
### Description of the Issue
The background of notepad++ shines white before turning other colors.

### Steps to Reproduce the Issue
1. Open notepad++
2. Wait for it to load, pay attention to before window elements are shown

### Expected Behavior
Notepad++ should defaulty shine in the color of the global settings. If not that, at least a dark grey or black even. Every time I open NPPP I get this really white flash shone at me. I use dark themes.

### Actual Behavior
Nothing I can find changes this white background.

### Debug Information
I would screen shot it, but NPPP loads too quick B)

**Comment by PeJeyDimO** [comment]
When minimizing notepad++ and then maximizing/open it again, the background of the edit area is flashing shortly - that's fucking annoying, especially in a dark room.
When open up the window of n++ and then open another window of any program above n++ window, switching back to n++ the flashing will not happen!

The flashing just happens when opening the n++ window from the minimized state.
You can see that much better when choosing a dark style from the style menu. The background will lighten up shortly before the color changes to the dark color of the style.

**Comment by dragokas** [comment]
++
It really bothers me.
White flash blinds eyes.
Please, make that frame to be dark when dark style theme is used.

**Comment by geoslake** [comment]
Still there, making my eyes bleed :-(

**Comment by tilkinsc** [comment]
This probably happens because the window shows before its properly been drawn to the first time.

**Comment by tilkinsc** [comment]
This assumption is totally correct. My project I am working on had a white flicker until I cleared the buffers to a default color:

```C++
	// clear white flicker
	glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
	glfwSwapBuffers(glfw_window);
	glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
	glfwSwapBuffers(glfw_window);
	glfwShowWindow(glfw_window);
```

**Comment by liudr** [comment]
Is there any plan to fix this? I have learned to close my eyes right after I start npp. It's not a solution.

**Comment by donho** [comment]
https://community.notepad-plus-plus.org/topic/21939/notepad-8-1-6-release-candidate
