### ISSUE TITLE
Shortcut for Save As is not normal (Ctrl + Shift + S)

### ISSUE THREAD

**Issue by seanspotatobusiness** [notepad-plus-plus/notepad-plus-plus#3957]
### Description of the Issue
Save as shortcut is Ctrl + Alt + S in Notepad++ but in most programs it's Ctrl + Shift + S.

### Expected Behavior
Expect Ctrl + Shift + S to trigger save as function.

### Actual Behavior
Nothing appears to happen.

Most programs use Ctrl + Shift + S as the shortcut for Save As. Why would Notepad++ use something different? Consistency in user interfaces allows me to pick up new programs more quickly and inconsistency slows me down.

**Comment by Hadakajime** [comment]
You can edit the shortcuts:
Settings > Shortcut Mapper > Main Menu > Save As

But I agree, the default value shipped is inconsistent. If I remember correctly, the default Ctrl + Shift + S mapping was to Save All (Extremely dangerous!!).

I feel it should not ship with default mappings for global operations like Save All, Close All, because this could seriously (and potentially irreversibly) damage all open files. But that's just my lowly preference. How do you think?

**Comment by sasumner** [comment]
Maybe it should not ship with ANY commands mapped to shortcut keycombos.

**Comment by Hadakajime** [comment]
that would be inconsistent too..

**Comment by alankilborn** [comment]
Recommend CLOSING this issue.

**Comment by ArkadiuszMichalski** [comment]
Changing this at this point could trigger another reports. I suggest you to use Shortcut Mapper and set the desired combination.
