### ISSUE TITLE
Access violation when closing notepad++ with tab that file is opened

### ISSUE THREAD

**Issue by thetsinling** [notepad-plus-plus/notepad-plus-plus#3959]
### Description of the Issue

computer: lenovo laptop T440p
os:win10 home 1709
notepad++: v7.5.3,v7.5.2(v7.5.1 close successful)
there is a demo.txt file in my desktop,right click demo.txt ,choose "Edit with notepad++",the notepad++ is run with a tab  demo.txt.  when closing  notepad++ with demo.txt tab, notepad++ pop up messagebox(exception,Access violation), 
### Steps to Reproduce the Issue

1. download and install notepad++ 
2. after install run notepad++ 
3. close notepad++ with tab change.log, access violation.

### Expected Behavior

close successful
### Actual Behavior

pop up messagebox  Access violation
### Debug Information

Notepad++ v7.5.3   (32-bit)
Build time : Dec  5 2017 - 10:45:46
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

![exception](https://user-images.githubusercontent.com/31873447/33652189-6b32323c-daa3-11e7-86c4-f471e31076d9.png)

**Comment by thetsinling** [comment]
np close successful after reboot system

**Comment by PCMedic67** [comment]
I'm getting the same and the reboot didn't fix the issue.

**Comment by thetsinling** [comment]
now, i can't reproduce  this issue :(.

**Comment by Eupeodes** [comment]
It seems it is fine to just open a file and read it, in my case I can consistently trigger this 'Access violation' warning by searching in a file and then close np++.
I am working on a surface pro 4 with windows 10 (build 1703) with Notepad++ v7.5.3 (64bit).

**Comment by thetsinling** [comment]
Notepad++ v7.5.2 bug-fixes and enhancement:
Add DSpellCheck plugin into distribution.
-----------------------------------------------------
i will try v7.5.3 x64 without plugin dspellcheck later.

**Comment by git-moss** [comment]
Same problem here (Windows 10 Pro).
I can reproduce it the following way:
1) Open Notepad++
2) Create and store a new file
3) Close Notepad with the file still open.

**Comment by lokilin** [comment]
I have same problem when file still open then I close it.
Solution:Disable the DSpellCheck plugin as thetsinling said.

**Comment by thetsinling** [comment]
np 7.5.4 fix it .

**Comment by jwbowen** [comment]
I'm still seeing the "Access violation" pop-up on v7.5.4, even with DSpellCheck disabled.

My issue seems to be with the Compare plugin. If I compare two small files, I can close both tabs (Ctrl+W) with now issue. With two 10 kB files, I get the "Access violation" pop-up. The original files I was working with were 54 kB. I'm not sure if the size of the file actually matters, but I couldn't reproduce the issue with two three-line files.

I've attached the files I was using for testing.
[doc1-1k.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1679227/doc1-1k.txt)
[doc1-10k.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1679228/doc1-10k.txt)
[doc2-1k.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1679229/doc2-1k.txt)
[doc2-10k.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1679230/doc2-10k.txt)

I've also tried just opening two files in separate views to see if this was the issue, rather than the Compare plugin itself, but I can open files in separate views and close them without issue.

Debug info:
```
Notepad++ v7.5.4   (64-bit)
Build time : Jan  1 2018 - 01:50:29
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins :
  AnalysePlugin.dll
  CodeAlignmentNpp.dll
  ComparePlugin.dll
  DSpellCheck.dll
  ElasticTabstops_64.dll
  MarkdownViewerPlusPlus.dll
  mimeTools.dll
  NppDocShare.dll
  NPPJSONViewer-x64.dll
  PluginManager.dll
  SQLinFormNpp64.dll
  TakeNotes.dll
  XMLTools.dll
  zoomdisabler_x64.dll
```

**Comment by dail8859** [comment]
DSpellCheck is still showing up in your debug info so it could still be causing problems. Issues for the compare plugin should be reported to the plugin's developer.

**Comment by jwbowen** [comment]
FWIW, I completely deleted/uninstalled DSpellCheck while testing. I reinstalled it after the behavior persisted.

**Comment by thetsinling** [comment]
Notepad++ v7.5.4   (64-bit)
Build time : Jan  1 2018 - 01:50:29
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll 
------------------------
compareplugin.dll from https://github.com/pnedev/compare-plugin/releases/download/v2.0.0/ComparePlugin_v2.0.0_X64.zip
in my laptop, np 7.5.4 with compare plugin worked fine ;)

**Comment by andy-smith-work** [comment]
Just in case anyone comes across this thread in the future, I also had multiple Access Violation errors when comparing two files.  They were caused by the Elastic Tabstops plugin, which was enabled from a previous file.  When I disabled Elastic Tabstops, the access violation errors went away too.
