### ISSUE TITLE
Auto-Complete does not suggest keywords in lower-case

### ISSUE THREAD

**Issue by GitMensch** [notepad-plus-plus/notepad-plus-plus#3997]
### Description of the Issue
Given a code-complete-file with `Environment ignoreCase="yes"` and all keywords in upper-case + the setting "Function completion only" keywords are completed when typing in lower-case.
As soon as "function and word completion" is active the keywords are only suggested when typed in upper-case.

### Steps to Reproduce the Issue

1. Activate auto-completion with "function completion only"
2. Create a new file and choose SQL highlighter (as the API as `Environment ignoreCase="yes"`)
3. Type "sel" -> auto-completion opens, "SELECT" is suggested --> fine
4. Activate auto-completion with "function and word completion"
5. Create a new file and choose SQL highlighter
6. Type "sel" -> auto-completion is not opened (but may be opened via [CTRL]+[SPACE] where "SELECT" is suggested)

### Expected Behavior
* suggesting lower-case keyword when the current word is in lower-case
* automatically open auto-completion when lower-case is opened, too

### Debug Information
Notepad++ v7.5.3   (32-bit)
Build time : Dec  5 2017 - 10:45:46
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll LocationNavigate.dll mimeTools.dll NppConverter.dll NppExport.dll NppSaveAsAdmin.dll PluginManager.dll SourceCookifier.dll

**Comment by raziEiL** [comment]
Please fix it

**Comment by davidbrigden** [comment]
I did some playing with this issue today.  (using the SQL.xml file because it ignores case)  
- When Autocomplete is set to Function only,  starting to type"select"  will give the suggestion of "SELECT" (that's how it is in the .xml file)  Case is ignored

-  When Autocomplete is set to Function and Word.  typing "select" will produce nothing.  You have to type "SELECT" for Autocomplete to function   Case is not ignored. 

That's the function side.  Looking at the Word side. I have the word "FunkyCase" in my edit window

- When Autocomplete is set to Word, typing "funkycase" will produce nothing.  You have to type "FunkeyCase" for Autocomplete to function. Case is not ignored

- When Autcomplete is set to Function and Word, typing "funkycase" will produce nothing.  You have to type "FunkeyCase" for Autocomplete to function. case is not ignored

So I''m guessing a couple things:

- Word completion is hard-coded to be case sensitive.  

- The case sensitivity of Word completion takes precedence over the case sensitivity of Function completion if they are both acdtive

My guess to fix this would be to somehow change the precedence, so that when Function and Word is selected (and there's an autocomplete file) that the IgnoreCase setting in the file takes precedence.  

What' I would **really** like is if the case sensitivity of **Word** completion would also respect the IgnoreCase setting iwhen there's an autocomplete file)

**Comment by GitMensch** [comment]
Just rechecked with 7.9.4, still identical. The suggestion outlined by @davidbrigden seems reasonable...
