### ISSUE TITLE
Bad session save

### ISSUE THREAD

**Issue by sorein** [notepad-plus-plus/notepad-plus-plus#4018]
### Description of the Issue

Session doesn't save correctly when more than one window is open.

### Steps to Reproduce the Issue

1.  Open 7 files (7 tabs).
2.  Move 3 tabs to a new window.
3.  Save session.

### Expected Behavior

When I open the saved session I expect to have all previous windows reopened (in this case, 3 tab + 3 tabs).
### Actual Behavior

Only one window is opened, either the one with 4 tabs or the one with 3 tabs.

**Comment by sasumner** [comment]
When you say "more than one window is open", or "move 3 tabs to a new window", I believe what you mean instead of "window" is "view".

Regardless, I tested the scenario under 7.5.3 and found no issue; a saved session with editor tabs in both views (primary and secondary) was saved and reopened correctly (tabs that were in each individual view were restored upon session load.

**Comment by sorein** [comment]
Maybe you don' know what a window is. We users of Windows call a window: "A rectangular area on a screen in which a document, database, or application can be viewed independently of the other such areas."

Think of this matter as if you used Chrome. You can use 1 window with many tabs or you can move a tab to a new Chrome window. Now you have one app working in 2 windows. Thus you can have several windows of Chrome (or Firefox) each having a random number of tabs at a certain moment.

When you close Chrome, that structure of windows&tabs is memorised and when you open it again the structure is reconstructed, so you can continue your work from where you left it.

This is not possible in Notepad++. Tabs can be moved to a new window, but you cannot save the whole Notepad++ work session. Only the structure of one of the windows is saved. All the other Notepad++ windows are lost. This is a nightmare when the power is lost unexpectedly.

I really have no idea what "view" you mean. I clearly wrote "window".

**Comment by MAPJe71** [comment]
> 3. Move 3 tabs to a new window.

You're actually moving the three tabs to a _new instance_ of Notepad++ which has its own "window".
Instances operate independently e.g. session information is not shared. Saving a session only includes the tabs of one instance (the "window" with focus). Switching to the second instance and saving its session to the same file will overwrite the session data of the first instance. So depending on which instance (the one with 4 tabs or the one with 3 tabs open) was last used to save the session data detemines how many tabs are opened on (re-)loading the saved session.

>Now you have one app working in 2 windows.

Chrome (and FireFox) starts one instance which can open several "windows" with each one or more tabs.
Notepad++ is one instance 1 window with one or more tabs.

You might want to change this issue into a feature request.

>This is a nightmare when the power is lost unexpectedly.

No feature in Notepad++ can solve power issues, try an Uninterruptible Power Supply. 😄

**Comment by sasumner** [comment]
He implies that I "don't know what a window is" and yet he types up a whole issue concerning "instances" and never once uses that term?  Are you kidding me??  Idiotic.  Where do these people come from?

**Comment by sorein** [comment]
Indeed, sasumner, you sound quite idiotic :) Go back to the first computer lessons. Learn what a program is, a window, a tab... From where have you idiots come and made the Internet stink like that  in the past 15 years? From what sewerage holes? :D Oh you stupid smartphoners and facebookers. ;)
Yes, it's the era of automatic programming, when all idiots become programmers, but they can't understand simple situations.

**Comment by DavidHansen-0x454d43** [comment]
@sasumner, I think you confused the comment @MAPJe71 made with the one @sorein did. MAPJe71 is talking about 'instances' which is what I believe sorein means when he says 'windows'. 

'Instances' is probably the term we should be using here, since that is the word used internally by Notepad++ (e.g. right click a tab, and you can see "Move to new instance"). 

I think what sorein reported is adequately being described by MAPJe71 (i.e. session files only save info on the current 'instance' being closed)

**Comment by sasumner** [comment]
@DavidHansen-0x454d43 , No confusion--where in this issue thread do you think I responded to anything @MAPJe71 said?  I didn't.  No need.  @MAPJe71 knows what he's talking about, and uses the correct Notepad++ nomenclature to do it.  :)

My post that starts out *'He implies that I "don't know what a window is" and...'* was a direct reply to @sorein 's posting that said *"Maybe you don' know what a window is. We users of Windows call a window..."*.

**Comment by DavidHansen-0x454d43** [comment]
@sasumner, DOH, you're right. I misread you. I thought you were attributing the "instance" comment to sorein.... I was just trying to deescalate the thread a bit. I recognize and appreciate your contributions here on github and on the community forums. 

@sorein, your second post may come off as a little condescending, so I'd suggest employing a little more humility. You may also consider editing your original post to be a little more precise (e.g. under expected behavior, 3+3 != 7), and to use the Notepad++ nomenclature. My understanding is that Notepad++ has two views (the left and right pane in the editor), and each of these views can have multiple tabs. Notepad++ can also be run in multi-instance mode, which creates a new "window" with its own views & tabs. 

My memory may be failing, but it seems like this issue has been reported before... Is there previous issue # we can tie this one to?

**Comment by sorein** [comment]
I don't know if "condescending" is the proper word to use here. Rude and simple-minded people like phoner sasumner have to be treated more energetically, because they pollute the professional environment.
Anyway, have the creator(s) of this app gotten smarter? Indeed, it is a helpful app, but is it so hard to generate a new "window" with multiple tabs inside the same "instance"? Just like the "commonplace" Chrome or any other browser? Apparently not, since this necessary behaviour doesn't happen yet.

**Comment by sasumner** [comment]
@MetaChuh Regarding "wontfix" and "closed" ... +10.
