### ISSUE TITLE
[Feature Request] Hide files by extension in Folder as Workspace

### ISSUE THREAD

**Issue by 94Connor949** [notepad-plus-plus/notepad-plus-plus#4049]
I'm not sure about anyone else, but for me, Folder as Workspace has been an invaluable feature. Still, there are many files we _don't_ need to see, and some we can't even edit if we wanted to (like images). Please, it would be incredibly helpful if we could blacklist and/or whitelist files by extension.

**Comment by andreszs** [comment]
A Filetype filter would be great, but since no GUI changes are made anymore, your feature will surely get discarded as well.

As a counter-measure, I always create sudirs for each filetype, for example, images, CSS, JS, and so on. It depends on the target language used of course, but it works for Web.
