### ISSUE TITLE
Feature Request: "Move to Other Instance" and "Open in Other Instance"

### ISSUE THREAD

**Issue by GaryBloom** [notepad-plus-plus/notepad-plus-plus#4092]
### Description of the Issue

Currently right-clicking a tab gives the options to Move or Clone to Other View, and Move to or Open in New Instance.  But when there is already a new instance, the ability to Move or Open into that existing instance instead of a new instance would be pretty handy.

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by sasumner** [comment]
What if there were already **2** other instances?  How would it know WHICH other instance you wanted it to go to?

But, say you have exactly 2 instances running (the following also works with any number running, but let's keep it simple):  Try dragging an editor tab from one instance and dropping it on the other.  IT MOVES.  Which I think is what you are really asking for, right?  Problem solved?

If you drag the final editor tab out of an instance (so that after the drop that instance would have zero tabs), that instance will Close!  FYI.

**Comment by dail8859** [comment]
As @sasumner suggested it is much simplier and clearer to drag and drop the tab to the instance you want. Having an option in the right-click menu to disambiguously move it would be rather hard to implement. You'd need something like:

- Move to New Instance (1)
- Move to New Instance (2)
- Move to New Instance (3)

But then it would be hard to  know which "instance" is which one. Closing since the current behavior seems to be adequate.

**Comment by GaryBloom** [comment]
Now that you mention the ability to drag, I tried it, and it achieves the "Move". I also tried holding down the Ctrl key while dragging and get a "Copy" instead of a Move. So, I agree that the existing functionality is sufficient. My apologies for not testing more before making the request.
