### ISSUE TITLE
[BUG] Session doesn't restore fold state of all files 

### ISSUE THREAD

**Issue by CheckB** [notepad-plus-plus/notepad-plus-plus#4103]
Hello,
i have:

Windows 8.1 x64 + full update
Notepad++ 7.5.4 x64
C ++ Syntax

> https://www.youtube.com/watch?v=n4oeenH_g7k&feature=youtu.be
> https://www.youtube.com/watch?v=EaHzxw4Bguw&feature=youtu.be

1. Open notepad
2. Open a C++ File
3. Code folding. We wait... 8 sec
4. Close notepad
5. Create .txt file
6. Open in notepad .txt (or any other file, after the close notepad)
And all the "Code folding" OPEN! In all files! Even where it was a day ago

**Debug info:**

> Notepad++ v7.5.4   (64-bit)
Build time : Jan  1 2018 - 01:50:29
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExec.dll PluginManager.dll

**Comment by dail8859** [comment]
Again...you should *follow the provided template* and especially post your debug info as the template states.

I have remember current session enabled:
![capture](https://user-images.githubusercontent.com/3694843/35157697-c1d3992e-fd02-11e7-9677-82926ed0aa04.PNG)


I can't reproduce the issue:
![fold](https://user-images.githubusercontent.com/3694843/35157777-fe4a3264-fd02-11e7-935f-c8edd43c19fb.gif)

**Comment by CheckB** [comment]
@dail8859 
https://www.youtube.com/watch?v=n4oeenH_g7k&feature=youtu.be

**Comment by CheckB** [comment]
> https://www.youtube.com/watch?v=n4oeenH_g7k&feature=youtu.be

It was checked on different machines, different configurations, under the same conditions - the problem is the same. And this problem goes back to versions 6.3.X

**Comment by dail8859** [comment]
It looks like this is only effects files that are unsaved, correct?

**Comment by CheckB** [comment]
@dail8859 
Unsaved?
ctrl + s?

If ctrl + s, then even the saved have a similar problem.
Even if these files will be open and saved for several days using "code folding", the problem will be the same.

But then another chip.

Now there is a file that has been open for several weeks. There, the code folding works.
But if new ones open, then code folding will work.

**Comment by CheckB** [comment]
Maybe someone has ideas for a solution?

**Comment by CheckB** [comment]
Actuality

**Comment by CheckB** [comment]
Actuality

**Comment by YakovL** [comment]
Let me copy a scenario originally posted [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5525#issuecomment-488641576) (retested in 7.6.6). Steps to reproduce:

1. create empty test2.txt and test1.txt with this content:

       . one
        . two

2. open those in the main n++ window (be sure that "Backup"→"remember current session for next launch" is enabled and if we close the window and reopen it, the same 2 files are loaded). Be sure that test2.txt is the leftmost tab and test1.txt is to the right from it (otherwise the bug is not reproduced)
3. for test1.txt select Python syntax and fold second line
4. close n++ (doesn't matter whether test1.txt or test2.txt tab was in focus)
5. open n++
**Expected behaviour**: the second line (`. two`) stays folded
**Actual behaviour**: the second line is unfolded (shown normally)

Additional info:
* if I save the session manually to a file, it looks like
```
<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="1">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1" startPos="0" endPos="0" selMode="0" lang="&#x041E;&#x0431;&#x044B;&#x0447;&#x043D;&#x044B;&#x0439; &#x0422;&#x0435;&#x043A;&#x0441;&#x0442;" encoding="-1" userReadOnly="no" filename="D:\path\to\test2.txt" backupFilePath="" originalFileLastModifTimestamp="-314148794" originalFileLastModifTimestampHigh="30736597" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="70845493" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="72" startPos="13" endPos="13" selMode="0" lang="Python" encoding="-1" userReadOnly="no" filename="D:\path\to\test1.txt" backupFilePath="" originalFileLastModifTimestamp="732851233" originalFileLastModifTimestampHigh="30736598" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no">
                <Fold line="0" />
            </File>
        </mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>
```
but if I load that session manually, the second line is still unfolded

* debug info:
Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\1my\tools_and_components\in_use_or_used\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Yay295** [comment]
Somehow since the last update (v7.7) my files are remembering their folds, though it didn't work right away for all files. I first noticed that my Python files were keeping their folds, but not my JavaScript files. Remembering that Python folding used to have issues with using Unix line endings on Windows, I tried switching my JavaScript to use Windows line endings. After re-folding everything, this actually worked. Not only that, but when I switched it back to Unix line endings, it *still* worked. I really don't know what's going on, but I suppose it probably has to do with Scintilla being updated.

**Comment by donho** [comment]
@YakovL 
Could you turn on Local Conf mode - ie. create an empty file with name ``doLocalConf.xml` in  `C:\1my\tools_and_components\in_use_or_used\Notepad++\` and try it again please ?

**Comment by donho** [comment]
OK I can reproduce the bug steadily now - every other settings than the default settings **UTF8 apply to opened ansi files** will cause C/C++ and other some languages (not for xml though) folding lost on startup:
https://community.notepad-plus-plus.org/topic/19151/session-bug-in-v7-8-5/8?_=1586361619811

**Comment by YakovL** [comment]
yes, thanks, the issues does seem to get fixed now, great!
