### ISSUE TITLE
copy & paste Chinese word display problem

### ISSUE THREAD

**Issue by microka** [notepad-plus-plus/notepad-plus-plus#411]
when i copy "題­本" and paste into npp, it display as "題­-本", but copy that "題­-本" and paste in other places (such as google chrome's browser's URL bar), it display as "題­本" (this is what i want).

![qq 20150705211417](https://cloud.githubusercontent.com/assets/490351/8511866/d3d683fe-235a-11e5-8067-d17b99877d3a.png)

![qq 20150705211429](https://cloud.githubusercontent.com/assets/490351/8511865/d3bf2a4c-235a-11e5-9bdd-3e8cf03429e1.png)

the problem is it add "­-" in npp.

this problem not only happen in "題­本" this word, some others chinese word will occur the problem too.

could it be fix?

npp v­6.7.9.2
encode in UTF-8 w/o BOM
windows 8.1 x64

**Comment by milipili** [comment]
Confirmed with Windows 10.

**Comment by Rikk** [comment]
Hey, this is an interesting thing.

The problem seems not related to Notepad++, but is much more widespread, maybe related to Windows clipboard and its internal text conversions...

Looks like this happens with any text editor... LibreOffice, MS-Word/Excel, Notepad2... Also on any Windows text input field, even on Internet Explorer.

Curiously, in Opera (which uses Chrome/Blink), the dash '-' is there but is displayed hidden (you need to press left/right twice to pass through it).

Firefox handles it better, it makes the cursor bolder when passing though these letters and don't display any signal of a hidden char in between. Maybe it understands the bug in Windows?

Looking at these letters in Hexadecimal (binary) -- when I paste the copied text --, I see the thing that in ascii is interpreted as '-' belongs to the first character (4bytes each char):
![題­本](https://cloud.githubusercontent.com/assets/2916485/8515482/d735ba28-2379-11e5-9217-58219cad28ac.png)

Ps: would be nice to see how this behaves in a Linux or Mac...

**Comment by Rikk** [comment]
Hey, this is an interesting thing.

This seems not related to Notepad++, not even a bug. I think it just helped you see an (almost-)invisible character.

The text you have (題­本) looks like is actually 3 chars, two chinese (or similar) and, in the middle, one that can be invisible depending on the conversion done by programs.

Any Windows text input field and any text editor, eg. LibreOffice, MS-Word/Excel, Notepad2, Internet Explorer, etc. will display it with the dash between chars.

Curiously, in Opera (which uses Chrome/Blink), the dash '-' is there but is displayed hidden (you need to press left/right twice to pass through it).

Firefox hides it better, it makes the cursor bolder when passing though these letters and don't display any signal of a hidden char in between, except that with a double-click it will select a single letter instead of the entire word (the two chars).

Looking at these chars in Hexadecimal (binary), we can see the thing that in ascii is interpreted as '-' after the first character:
![題­本](https://cloud.githubusercontent.com/assets/2916485/8515482/d735ba28-2379-11e5-9217-58219cad28ac.png)

Finally, the good text you are looking for is this: 題本 (just removed that bad char between).

**Comment by microka** [comment]
@Rikk Thanks for your analyzation!!
The text like "題­本" is copy from [link to YouTube!](https://www.youtube.com/watch?v=jwI0YNUV-JA) its description field.
For example, the text "兩­天" in source page is `兩<wbr>&shy;天`
![qq 20150706170433](https://cloud.githubusercontent.com/assets/490351/8518956/4f080e16-2401-11e5-87c8-81c787161e00.png)

And i found some references:
http://superuser.com/questions/628959/copying-text-from-youtube-to-clipboard-introduces-dashes
http://productforums.google.com/d/topic/youtube/rLdLkrj1OcE
https://en.wikipedia.org/wiki/Soft_hyphen

So this is not NPP's problem. Instead, NPP helps me "dig up" the annoying soft hyphen so i can remove it manually.

**Comment by milipili** [comment]
@Rikk Works as expected on MacOS
