### ISSUE TITLE
64-bit installer won't remove the 32-bit N++ entry if 64-bit copy is installed on top of 32-bit

### ISSUE THREAD

**Issue by UserNaem** [notepad-plus-plus/notepad-plus-plus#4129]
### Steps to Reproduce the Issue

1. Install the 32-bit build of N++.
2. Install the 64-but build of N++ in the same directory. (This will overwrite the 32-bit version)

### Expected Behavior
One entry in "Programs and Features" for the 64-bit copy.

### Actual Behavior
One for 32-bit, one for 64-bit, each pointing to the same uninstaller.
![image](https://user-images.githubusercontent.com/21028464/35656331-ad2d2038-0718-11e8-84ab-d6e5cec889cf.png)

**Comment by SinghRajenM** [comment]
Invalid Test case because of two reasons - 
1. x86 installation should go to "%programfiles(x86)%/Notepad++" while x64 should go to "%programfiles%/Notepad++". 

2. If you try to install 64bit npp over 32 bit npp, it will provide popup like below. If you click "Yes", then 32bit version will be removed and x64 will be installed. However there was an issue in V7.5.1 which was fixed in V7.5.2. Refer [changelog point 4](https://notepad-plus-plus.org/download/v7.5.2.html)

![image](https://user-images.githubusercontent.com/14791461/35685010-7c1cee3a-078e-11e8-9c72-76719bb72d99.png)

**Comment by UserNaem** [comment]
Uh, okay. I should have read the release notes.
