### ISSUE TITLE
Unable to drag and drop files in Admin mode

### ISSUE THREAD

**Issue by softmgr** [notepad-plus-plus/notepad-plus-plus#4144]
### Description of the Issue
Unable to drag and drop files in Admin mode!

### Steps to Reproduce the Issue

1. Running the notepad++ as an administrator
2. Drag and drop TXT files to the notepad++ window
3. Cannot drag and drop!

### Expected Behavior
The admin mode should be able to drag and drop files!

### Actual Behavior
Cannot drag and drop!

### Debug Information

PS:
Please query the API function ChangeWndMessageFilter:
ChangeWndMessageFilter(WM_DROPFILES, true);
ChangeWndMessageFilter(0x0049, true);

You can drag and drop files in the administrator mode!

**Comment by SinghRajenM** [comment]
This is windows behavior. Low integrity processes (in this case explorer runs with low integrity), are not allowed for drag n drop with higher integrity processes (in this case N++).

However, some tweaks (may be loopholes) allow to do so. Moreover, item ```0x0049``` is undocumented.
But in case of N++, it is bit tough. It has been tried out in PR #2683, but could not succeed. It would be great if you provide the fix in PR.

**Comment by CookiePLMonster** [comment]
I would **very much discourage from relying on this undocumented behaviour**. Yes, message 0x0049 is documented in Wine as `WM_COPYGLOBALDATA`, however since it's not exposed in public Windows headers I'd advise against using it.

It works for you - great. However, since it's undocumented, it may in theory stop working at any time. It works on Windows 10, but maybe it will stop working after the next Patch Tuesday? Or maybe it works on Windows 7 but not Windows 7 SP1? Maybe on Windows XP SP3 it causes a crash? With an application as _serious_ as a text editor, it may be a very bad idea to take the risk.

FYI both Command Prompt and PowerShell exhibit the same behaviour as Notepad++. Because of that, I'd classify this workaround as nothing more than a potentially unsafe hack.

**Comment by softmgr** [comment]
BOOL Notepad_plus::ChangeWndMessageFilter(UINT uMessage, BOOL bAllow)
{
	typedef BOOL(WINAPI* ChangeWindowMessageFilterFn)(UINT, DWORD);
	HMODULE hUserMod = NULL;
	BOOL bResult = FALSE;
	hUserMod = LoadLibrary(TEXT("user32.dll"));
	if (hUserMod == NULL)
	{
		return FALSE;  //If the call failed
	}

	ChangeWindowMessageFilterFn pfnChangeWindowMessageFilter = (ChangeWindowMessageFilterFn)GetProcAddress(hUserMod, "ChangeWindowMessageFilter");
	if (pfnChangeWindowMessageFilter == NULL)
	{
		FreeLibrary(hUserMod);
		return FALSE;  //If the call failed
	}

	bResult = pfnChangeWindowMessageFilter(uMessage, bAllow ? 1 : 2); // 1-MSGFLT_ADD, 2-MSGFLT_REMOVE
	FreeLibrary(hUserMod);
	return bResult;
}
@SinghRajenM I have tested the above function.
@CookiePLMonster If the function does not work, it will return to false, not crash.

**Comment by CookiePLMonster** [comment]
@softmgr the contract doesn't seem to say anything about using undocumented Windows messages, so your observations may not apply worldwide.

Please correct me if I'm wrong, however.

**Comment by softmgr** [comment]
@CookiePLMonster 
But in order to make Notepad++ easier to use, I think it is necessary to add this function (and many other software also has the function).

**Comment by CookiePLMonster** [comment]
Option sounds more sensible, true. I definitely wouldn't want to see this always enabled.

**Comment by xaliber** [comment]
I support adding this to the option. Or has this been added?

**Comment by MetaChuh** [comment]
for drag and drop from a user level explorer to an elevated notepad++ instance, you have to turn off the user level isolation by turning off uac at your windows preferences.

thank you for your help and best regards.

**Comment by 7starsone** [comment]
@MetaChuh Hello, here UAC is disabled but can't drag and drop by Admin...
