### ISSUE TITLE
Regular expressions no direction up

### ISSUE THREAD

**Issue by odie2** [notepad-plus-plus/notepad-plus-plus#415]
Hi,

Maybe that is special feature, but I don't understand it.
Why I can't use direction up when using regex?

![image](https://cloud.githubusercontent.com/assets/9401878/8521346/0682c0e6-23e3-11e5-9656-3f088710ef6f.png)

Entering from mode normal or extended with direction up cases direction switch to down.

Greetings

**Comment by vzjrz** [comment]
That's just how the regex engine works I've never seen one that can work backwards but I guess it could be hacked to start at the current line and work "down" the lines in reverse.

**Comment by odie2** [comment]
Hmm, yes multline is really confusing then. I didn't get it into mind.

But maybe we can add also option "Keep regex structure", so it will be just direction like in normal search?

**Comment by guy038** [comment]
Hello **odie2** and **vzjrz**,

No guys, You're both wrong ! With Notepad++, it's quite possible to search **backwards**, in **Ragular expression** mode

A quick example :

- In a **new** tab, write the few lines, below

    Test
    123
    Example
    
    Test
    456
    Example
    
    Test
    789
    Example
	
- Go back to the **beginning** of the text ( **CTRL + Origin** )

- Open the **Find** dialog ( **CTRL + F** )

- Check the **Wrap around** option

- Select the **Regular expression** search mode

- Type the regex `Test\R\d+\RExample` in the **search** field

- Click on the **Find Next** to reach the **first** match and to **memorize** the search regex

- Then, hit the **ESC** key to close the **Find** dialog ( **IMPORTANT** )

- Now, use the **SHIFT + F3** shortcut, to select the **previous** match => you get the **third** and **last** block !

- If you use again the **SHIFT + F3** shortcut, you select the **second** block, and so on...

Of course, any hit on the **F3** key, ONLY, will restart the search, in the **down** direction

Remark :

Let's imagine the **subject string** below :

    aaabbababaaabbbbababbbab

and the simple regex `a+b+`

Then :

- Locate the **cursor** before that string

- Do a first search to select the string **aaabb**

- Again, hit the **ESC** key to close the **Search** dialog

- After **6 other** hits, on the **F3** key, you, finally, match the string **ab**

- Now, just _go **backwards**, hitting the **SHIFT + F3** shortcut, repeatedly_

Do you see the **differences** ? And with **complicated** regexes, it can be worse, with **unpredictable** results :-(

That's why it's commonly accepted that regex's search is processed, in **downwards** direction, to always get **right** matches !

Best Regards,

guy038

**Comment by odie2** [comment]
@guy038 
Hi,
Yes this makes sense.
Closing issue then.
Greetings
