### ISSUE TITLE
Window resizes to tiny on document close

### ISSUE THREAD

**Issue by anthonybakermpls** [notepad-plus-plus/notepad-plus-plus#417]
Whenever I close a document, the notepad++ window automatically resizes itself to a tiny little rectangle in the upper left of my screen- requiring me to drag the corner and resize it to a normal, readable size.
![capture](https://cloud.githubusercontent.com/assets/5091417/8524035/2692ebe2-23be-11e5-909c-cdc7fdf99131.PNG)

Windows 7 Enterprise SP1  64 bit.

Sometimes, it only happens when the main window is 'maximized' and other times, it does not matter what the state of the original window is.

**Comment by marynconen** [comment]
Same here, also on Windows 7 SP1 64 bit

For me the behavior is consistent, even after reinstalling and flagging 'not using %appdata%'. When I open the 'Find in files' window it resizes. The Search Results window is completely gone now (not sure where I put it last, but somehow it is hidden completely thereafter)

**Comment by C4ptain** [comment]
I'm going to keep investigating but I get the same improper resize when doing clipboard related things. It has been happening since OPs posting date.

**Comment by blue-sun-tech** [comment]
This shrinking issue is occurring recently for me as well. It happens on certain toolbar or context menu commands:
- Under File: New, Save, Save All (but not Save As...), Close, Close All
- Most commands under Edit (some that don't: Items under Paste Special, Column Editor/Mode, Character Panel, Clipboard History).
- Any of the style commands (using/clear Nth style) 
- Start/Stop macro
- some others
- When clicking the black X in the menu bar to close a window (but **not** when clicking one of the red X boxes in the tab bar).
- The bug also happens when any of the above commands are selected from the right-click context menu, either on the editing area or on the tab bar.
- The bug does **not** happen when using the keyboard shortcuts for these commands.
- The bug does **not** happen when the NP++ window is maximized

A related, and especially annoying bug is when any of the above commands pop up a dialog box (e.g. "Save File...?" when clicking Close), it gets moved beyond the left edge of the screen, and I must do Alt-Space, M to retrieve it):
![1](https://cloud.githubusercontent.com/assets/18428497/14474452/0cd4cb36-00b2-11e6-8322-6856fad28160.PNG) 
This occurs whether or not NP++ is maximized, unlike the shrinking problem.

I've included the text from the Debug Info window.

`Notepad++ v6.9.1
Build time : Mar 28 2016 - 19:48:40
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll XMLTools.dll `

Hopefully this can get some attention soon. It is making NP++ almost unusable, and a couple other people reported the bug recently.

If any other information could be useful here, I'd be happy to provide it.

**Comment by C4ptain** [comment]
I'm curious if anyone else seeing the issue is using a computer with an nvidia graphics card with nview desktop manager.

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.

**Comment by andrewjatnieks** [comment]
ME TOO ^^
