### ISSUE TITLE
Bug with parenthesis color when coding Windows batch files

### ISSUE THREAD

**Issue by untroll** [notepad-plus-plus/notepad-plus-plus#4191]
### Description of the Issue
There is a bug when writing windows batch files (.BAT). The parenthesis after the "else" condition are not highlighted in red when cursor is on them.

### Steps to Reproduce the Issue
Try this code to test : 
if %COMPUTERNAME%=="PC" (
echo "PC"
) else (
echo "NOT PC"
)

### Expected Behavior
The parenthesis after the "else" condition should be highlighted in red when I click on them

### Actual Behavior
The parenthesis after the "else" condition is not highlighted in red

### Debug Information
Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

Thank you

**Comment by proeng** [comment]
Yes awesome something i can do, i just checked it and indeed when batch is selected this issue happens.

**Comment by dail8859** [comment]
@untroll

This is related to #4169 which has some similar issues with syntax highlighting. (which is the response I gave 5 minutes after you posted in the Gitter chat).

@proeng 

Unfortunately this is not something that should be fixed in the Notepad++ project. The syntax highlighting is done by Scintilla and since it is not correctly highlighting the parenthesis, then the brace matching is not working correctly. Brace matching only matches braces that are in the *same* style.

**Comment by proeng** [comment]
dail8859
Thats to bad but i think i learned a tiny bit on the way.
I tracked down to this line:
 braceOpposite = int(_pEditView->execute(SCI_BRACEMATCH, braceAtCaret, 0));
And indeed it is Scintilla that can't find the other parenthesize cause of whitespace. I'm not entirely sure how it is mapped using the dll, but obviously it is in the EditView files. 
I will try to find something else to do.

**Comment by bkmdev** [comment]
I too was having this problem but it seems this may be fixed now in Scintilla in 2020 (see  https://sourceforge.net/p/scintilla/code/ci/bc6bc207a6d4a5ce787b9cb3320c8e1a0b22adb2), FYI @dail8859 .  

PS:  Why are these tickets (including #4641 & #2865) just being closed?  Just because the issue derives from an upstream issue doesn't mean they shouldn't be left open here to track against it.  That way when it is fixed upstream, it would be a sign that the new version of the lib can be pulled in and these tickets can be updated to indicate that this issue has been fixed.  It seems disingenuous to just close it even if it is an upstream issue?
