### ISSUE TITLE
line comment > block comment

### ISSUE THREAD

**Issue by Cryosaur** [notepad-plus-plus/notepad-plus-plus#421]
In a user-defined language, if a character used for a line comment is part of a block comment delimiter, the app will look at a block comment and detect a line comment.

**Comment by c2k-** [comment]
I believe I am having the same issue.
Here is an example of my problem, please tell me if it is not the same issue.
Comment line style -> Open: `REM`
Comment style -> Open: `REM(`
Comment style -> Close: `)`
Because `REM` is used for the line comment, it won't allow the block comment to work, it just formats the first line as a line comment and the remaining lines are normal.
If I remove the line comment, then the block comment works.
Can't seem to find a way to get both to work at the same time.

I tried checking the nesting boxes, but no difference.
I am using the latest notepad++ version 6.8.1

**Comment by donho** [comment]
I believe this issue has been implemented since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
