### ISSUE TITLE
JSON file open ends in exception: bad allocation

### ISSUE THREAD

**Issue by erwinmars** [notepad-plus-plus/notepad-plus-plus#4231]
If i open a file my file "filme.json" NPP needs a very long time and than, i get a message box with title: exception and text "bad allocation". The file is not shown. It seems, the reason is because of the large size. The second issue is, that it cannot be stopped. It seems, that NPP tries endless to allocate the storage for the file. 

I tried to attach the json file which reproduces the error, but where not able because of the size. Its about 134.188 KB.

**Comment by dail8859** [comment]
I generated a random 300KB+ JSON file and it opens instantly for me. Is there anything peculiar about your JSON structure? Deep nesting? Long lines? 

Also, try disabling your plugins as it could be one of those causing the problem.

Can you post your debug info as the template requested?

**Comment by CookiePLMonster** [comment]
You may very well pack your JSON file and upload it anywhere externally.

**Comment by erwinmars** [comment]
Hi, i've zipped and uploaded the file filme.7z on a google drive. You can access it with the link  https://drive.google.com/open?id=1kOK5g98giM0_0lSDl8V7VO3bMoF8m1Es

The file filme.json is created and used by https://mediathekview.de/

**Comment by erwinmars** [comment]
Because with that file, NPP hangs and i get a sandbox cursor, i've no debug infos. But i hope, you can recreate it with the sample filme file.

**Comment by dail8859** [comment]
> Its about 134.188 KB.

I originally thought this meant the file was about 134 Kilobytes. However the file is about 135 Megabytes...so much larger than I originally thought. I'm assuming in this case the `.` is used as a thousands separator rather than a decimal separator. :)

This file has no newlines, so it is completely on a single line. This is a known issue with Scintilla (the core of Notepad++) that it does not handle extremely long lines. So in short there is nothing Notepad++ can do to open and display the file.

**Comment by erwinmars** [comment]
Ok, thanks for your help. I'll contact the file creator how to get more lines.
