### ISSUE TITLE
Parse of c++ syntax is incorrect

### ISSUE THREAD

**Issue by fromasmtodisasm** [notepad-plus-plus/notepad-plus-plus#4254]
### Description of the Issue

Instead of commenting, the combination "://" gives a hyperlinknk
![hyperlink](https://user-images.githubusercontent.com/20030852/36901723-33888cda-1e39-11e8-911a-cd6aa7d0ed32.png)

**Comment by sasumner** [comment]
How about putting a space between the : and the first / and just chilling out?

**Comment by AdminOfLife** [comment]
Yes, it works, but it's not entirely correct, in terms of c ++ syntax.
Perhaps the wrong regular expression is written

3 мар. 2018 г. 4:10 ДП пользователь "sasumner" <notifications@github.com>
написал:

How about putting a space between the : and the first / and just chilling
out?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4254#issuecomment-370101972>,
or mute the thread

**Comment by ArkadiuszMichalski** [comment]
This was fixed with new URL parser https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8921.
