### ISSUE TITLE
Match whole word only in search treats INVERTED QUESTION MARK (in the text) as a word character

### ISSUE THREAD

**Issue by DavidHaslam** [notepad-plus-plus/notepad-plus-plus#4255]
### Description of the Issue
**Match whole word only** in search treats INVERTED QUESTION MARK (in the text) as a word character.

### Steps to Reproduce the Issue
One line in the text (Spanish Bible RV1865) reads as follows:
```
\v 20 Y clamando a Jehová, dijo: ¿Jehová Dios mío, aun la viuda en cuya casa yo soy hospedado, has afligido, matándole su hijo?
```
1. A normal search of the full text file for `Jehová Dios` gave 189 hits.
2. A **whole word search** for `Jehová Dios` found only 188 instances.
3. The instance it failed to find was the one where the search string occurs immediately after `¿` as shown in the line above.

### Expected Behavior
A whole word search should have found all 189 instances.
cf. A whole word search of the same work using **BabelPad** for `Jehová Dios` found all 189 instances.

### Background
- Spanish texts use `¿` at the start of a question and `?` at the end.
- Spanish texts also use `¡` at the start of a exclamation and `!` at the end.

### Ancillary evidence
- A whole word search for `¿Jehová Dios` found the one instance.

NB. One would not normally enter that in the search box before a whole words search, because the `¿` is a punctuation mark, and therefore not a suitable character for part of the whole word search string.

Updated: 2018-03-04

**Comment by sasumner** [comment]
For a whole-word search to be considered valid, the first and last characters of the text to be searched for must be word characters, typically thought of as A-Z, a-z, 0-9 and underscore (and unicode equivalents).  Reference this for more information:  https://notepad-plus-plus.org/community/topic/13004/bugs-in-normal-search-for-v7-2-2-on-windows-7

Since the question mark (inverted or not) is not a word character, this isn't a correct whole-word search, so results can be "unexpected".  

Regarding your BabelPad comment, all I can say is "Super! Use BabelPad".  If you choose to use Notepad++, add how whole-word searches in it work to your knowledge database.

**Comment by DavidHaslam** [comment]
#### Notepad++ is a Unicode text editor!
It should adhere to Unicode standards as to what is a word character and what is a punctuation character.

- A word can only begin with a word character.
- That a non-space character might precede a word should be ignored if it's not a word character.

A punctuation character is clearly not part of the word when it occurs immediately _after_ a word.
A punctuation character immediately _before_ a word should be treated in exactly the same manner.

The Notepad++ search algorithm with **match whole words only** is just wrong in this respect.

**Comment by sasumner** [comment]
I think you are missing the point.  Since you *know* that punctuation is NOT a word character, it is up to you as the user to not specify it in the search box when you also specify "whole word" as a parameter.  Garbage in...garbage out.  You are certainly entitled to your own opinion on how this should work, but I can guarantee that this is known and accepted behavior and won't be changed.

**Comment by DavidHaslam** [comment]
It's not I who is missing the point.
I was not searching for `¿Jehová Dios` when I first came across the anomaly.

A whole word search for `Jehová Dios` should have found all 189 instances in the text.
I merely toggled **Match whole words only** and spotted that the count was reduced by 1.
That simply should not have happened, precisely because `¿` is not a word character.
Its presence before one instance of the search text should have made no difference to the result.

That's confirmed by comparison with the fact that **BabelPad** does a whole word search exactly as one should expect. _This is the only reason for mentioning it_.

It's certainly not a case of "Garbage in...garbage out"!

**Comment by DavidHaslam** [comment]
#### Further evidence
- I just replaced all 3228 instances of `¿` by `#`.
- Now a search for `Jehová Dios` gave 189 hits.
- A **whole word** search for the same also gave 189 hits.

This clearly demonstrates that `\xBF` is being treated differently to the punctuation character `#`.

#### Notepad++ has a bug.
`U+00BF` should be treated as a punctuation character not as a word character.

**Comment by sasumner** [comment]
My apologies.  I really did miss the point.  Somehow I thought the entirety of the complaint was a consequence of doing a whole-word search where you start the search text with a punctuation character.  This has come up before, maybe that's why I grabbed onto the notion of it.  Clearly, reading back now I see that that isn't it.

It does seem like the inverted question mark is being treated as a word-character here for this literal search.  And to go at your `[[:punct:]]` test another way, `\w` won't match the inverted characters and `\W will, confirming that the regular expression engine indeed knows how to handle these.

**Comment by DavidHaslam** [comment]
Thanks. @sasumner 

I recognise that reporting issues is a challenging task, one that demands conciseness as well as precision.

When I have a bit more time, I'll reword the issue report with a view to preventing other users misunderstanding in like manner.

**Comment by DavidHaslam** [comment]
#### Further evidence
It just so happens that 12 instances of `Jehová Dios` are followed by a comma, thus `Jehová Dios,`.

Accordingly, as an experiment I replaced all `Jehová Dios,` by `Jehová Dios¡` in order to see what happens afterwards.

- This time the **whole word search** for `Jehová Dios` found only 176 locations.

This indicates that the incorrect classification of these punctuation characters during whole word search is _not_ position dependent relative to the search string.

**Comment by DavidHaslam** [comment]
If it turns out to be a **Scintilla** issue, I suppose that's then unlikely to be straightforward fix.
I'd guess there are reasons why the Notepad++ team have not adopted the latest version.

**Aside:** This issue may impact users of non-Roman scripts even more than for the Spanish currently in focus.
e.g. The Devangari script used for Hindi and some other Indic languages, etc.

**Comment by MetaChuh** [comment]
this is a limitation of the implemented boost engine, which is an external project.
there is currently nothing we can do at the notepad++ part.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
