### ISSUE TITLE
Notepad++ hangs and then unable to click on notepad++ window anywhere.

### ISSUE THREAD

**Issue by Abhinickz** [notepad-plus-plus/notepad-plus-plus#4295]
### Description of the Issue
Notepad++ hangs and then unable to click on notepad++ window anywhere.

### Steps to Reproduce the Issue
1. Open Notepad++ Window.
2. Open any program & and after sometime Notepad++ hangs and show the process in "Suspended" state.
3. Only closing from the taskbar "Close Window" & reopening solves this problem and sometimes "Close window" also does not work then Only "End Task" from Task Manager do the trick.
4. If there are some unsaved file open, I do see the option to save file, But still Notepad++ remains unclickable.

### Expected Behavior
1. Notepad++ should not hang and becomes unclickable.

### Actual Behavior
Notepad++ hangs and then unable to click on notepad++ window anywhere.

### Debug Information
Notepad++ v7.5.5   (32-bit)
Build time : Feb 27 2018 - 21:44:21
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll FileSwitcher.dll JSMinNPP.dll MenuIcons.dll mimeTools.dll NamedBookmarks.dll NppConverter.dll nppcrypt.dll NppExport.dll NppFTP.dll NPPJSONViewer-win32.dll NppTextFX.dll PluginManager.dll PoorMansTSqlFormatterNppPlugin.dll SQLinFormNpp.dll Tidy2.dll TopMost.dll WakaTime.dll XMLTools.dll

**Comment by CollinChaffin** [comment]
LOL that's two now duplicate of mine same exact issue as #4276

**Comment by AngryGamer** [comment]
I ran into a strange hang while closing Notepad++. I had an unsaved tab which triggered the "Your backup file cannot be found (deleted from outside)." dialog and when pressing cancel, Notepad++ was in a half hung state. I say half hung because clicking tabs on the Tab Bar or Doc Switcher updated Notepad++'s title to new tab's file path, but the tab was not shown selected and did not update the display area's contents. The only way to unfreeze Notepad++ was to click outside of the window on either the desktop or Windows' task bar. This hang reproducible until I dealt with the unsaved tab and the dialog went away. I haven't tried reproducing on a newly opened Notepad++. This hang reminds me of the hang described in [PR#3367](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/3367#issuecomment-306584172) except it's occurring at an even earlier state (before the tab is shown selected).

Another similar issue #3891

**Comment by AngryGamer** [comment]
I wonder if this is more LockWindowUpdate problems. I fixed one of the "hangs" in [PR#4611](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/4611)

If this "hang" happens again, try this to restore functionality: keep Npp open (not minimized) and click either somewhere on desktop wallpaper or task bar (like windows' audio volume, date/time, etc). If everything starts working again, then that suggests a problem with LockWindowUpdate.

**Comment by AngryGamer** [comment]
Does Npp work again after resuming the process in Resource Monitor (_steps: Task Manger -> Performance -> Open Resource Monitor -> Right click process -> Resume Process_)?

**Comment by Lewistrick** [comment]
> Plugins : [...] WakaTime.dll [...]

Uninstalling WakaTime worked for me...

**Comment by Randoragon** [comment]
I'm also experiencing this bug, it's very vexing. I don't have WakaTime.dll anywhere in my plugins folder.
My plugins are:
Code::Stats, DoxyIt, DSpellCheck, Mime tools, Npp Converter, NppExec, Save as admin, SelectQuotedText and SurroundSelection.
I doubt any of these are the real cause behind the issue though. I'll try running notepad without plugins using the -noPlugin flag.

**Comment by chcg** [comment]
@Randoragon With which version of N++ do you use? A current one with the fix of #4611

**Comment by Randoragon** [comment]
@chcg I have the latest version of Notepad++ installed, I've reinstalled it two days ago with a freshly downloaded installer from the official site. I'm not sure if the issue is still there, I think I've encountered it once after the reinstallation, which was a bummer, but I've been deliberately leaving my n++ open for the last 2 days and it just hasn't been happening anymore. I'm not sure what fixed it, perhaps it was running it via cmd with the -noPlugin flag. Everything seems in tact so far, even with the plugins turned back on. I'll update my situation here if I ever encounter this bug again.

**Comment by pinodev** [comment]
@Randoragon  I have the same problem, and I also have Code::Stats fairly recently installed...

(I also have DSpellCheck, NppExec, Save as admin and Snippets, but I had those for months or years without any problem)

I don't want to put the blame on Code::Stats without being certain, but it does work on every keystrokes and it also connects to internet, so... hum...

Not sure how to analyze/debug such problem...

**Comment by p-is-for-pangolin** [comment]
I have the same problem.  It doesn't happen 100% of time time, but most of the time.  Adding the -noPlugin parameter makes the problem go away completely, as does deleting the DSpellCheck directory from my plugins or removing the DSpellCheck plugin through the Plugin Manager.

**Comment by Sodoshi** [comment]
Good shout. Launching with -noPlugin then updating DSpellCheck fixed mine too.

**Comment by johnfoxii** [comment]
-noplugin didn't work for me. I cleaned up  %AppData%\Notepad++\config.xml

**Comment by siddmuk2005** [comment]
Regularly hanging seems one of the worst update came recently

**Comment by alanhamlett** [comment]
These issues related to the WakaTime plugin should be fixed in v5.1.1 of [notepadpp-wakatime](https://github.com/wakatime/notepadpp-wakatime).
