### ISSUE TITLE
(closed) export and import shortcut mapper 

### ISSUE THREAD

**Issue by longtth** [notepad-plus-plus/notepad-plus-plus#4330]
### closed comment
I've checked shortcuts.xml, thanks sasumner. 

### Description of the Issue
I use notepad++ on servers, actually, everytime I config a new server, I install notepad++ on it. 
 
### Steps to Reproduce the Issue

N/A 
### Expected Behavior

Export Shortcut Mapper to a XML or JSON file then import to new PC. 

### Actual Behavior

currently can't 
### Debug Information

N/A

**Comment by sasumner** [comment]
See **shortcuts.xml** ?

**Comment by pbarney** [comment]
This is not completed. `shortcuts.xml` contains only user-defined shortcut keys. People are looking for a list of all shortcut definitions (menus, macros, run commands, plugin commands, scintilla commands) so that it's easy to find an unused key combination to assign to macros or autohotkey scripts.

The data is all right there in the shortcut mapper, there's just no simple way to see it in a sortable list.

**Comment by alankilborn** [comment]
@pbarney A possible solution is the script found [HERE](https://community.notepad-plus-plus.org/post/46125).
