### ISSUE TITLE
Replace MessageBox on MessageBoxEx (dialog box buttons language)

### ISSUE THREAD

**Issue by Aynyuh** [notepad-plus-plus/notepad-plus-plus#437]
Hi all!
I will be so happy if buttons language in dialog boxes will be as NPP localization.

**Bad:**
![image](https://cloud.githubusercontent.com/assets/4816782/8592575/213c1db2-2639-11e5-9c3d-7cd042bde053.png)

I think this is required feature for many international programmers who have english layouts as their default layout.

Just change this

``` c
return ::MessageBox(_pPublicInterface->getHSelf(), displayText, title, type);
```

to this

``` c
return ::MessageBoxEx(_pPublicInterface->getHSelf(), displayText, title, type, MAKELANGID(getLangId, SUBLANG_DEFAULT));
```

**Good:**
![image](https://cloud.githubusercontent.com/assets/4816782/8592913/b9716b80-263b-11e5-861e-59f4bec243ba.png)

**Comment by CookiePLMonster** [comment]
This was accepted the same day it was submitted, yet as of Oct 2018 `MessageBoxEx` is nowhere to be found in n++ code... meh.

And yes, this was not fixed in another way - Yes/No/Cancel still use OS localization.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
