### ISSUE TITLE
[BUG] Word after caret gets selected when opening Find dialogue

### ISSUE THREAD

**Issue by aaaxx** [notepad-plus-plus/notepad-plus-plus#439]
Actually, even the word before, if it's positioned at the end of it.

Happens with all Search functions: Find | Replace | Find in Files | Mark

**Comment by h-h-h-h** [comment]
I agree that this is often not desired as well as having the last input of the search textbox replaced by that string. Sometimes you just want to close the find dialog so that it doesn't obscure any text. When you reopen it, you want to be able to go on where you left. Also it changes the start position for a search from the start of the string to the end of the string. That's not so good.

**Comment by aaaxx** [comment]
Could this finally be fixed, or at least acknowledged? It seems like a pretty simple fix.

It's been almost a year and it's still very much annoying.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
