### ISSUE TITLE
Read-only Flag Cleared Upon Close & Reopen

### ISSUE THREAD

**Issue by nathanm** [notepad-plus-plus/notepad-plus-plus#4409]
### Description of the Issue
I usually keep a text file open in Notepad++ with special characters that I use to paste into documents. Because I don't want to inadvertently change it, I have the read-only flag set, just in case. However, with the latest update to Notepad++, the read-only flag is cleared when I open Notepad++.

I tried setting the file's read-only attribute in Windows Explorer, while Notepad++ was closed. Then, after reopening Notepad++, the flag was still set. However, after clearing it and setting it again in Notepad++, the wrong behavior continued.

### Steps to Reproduce the Issue
1. Set the read-only flag on a file
2. Close Notepad++
3. Open Notepad++

### Expected Behavior
The read-only flag should remain set or cleared for each file, whatever its state was when last open.

### Actual Behavior
The read-only flag is cleared for a file that was previously set.

### Debug Information
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll GedcomLexer.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by sasumner** [comment]
It has worked this way as long as I've been using Notepad++.  It's meant to be a temporary thing.  But who knows...there is no documentation about it that I know of.

**Comment by dinkumoil** [comment]
I guess you are mixing up two different mechanisms for write protecting a file. But the UI of Notepad++ is admittedly confusing in this point. 

There are two menu entries which tell us that they manipulate the file's write protection:

1. `Edit - Set Read-only`
2. `Edit - Clear Read-only flag`

The first one only toggles an internal flag of Notepad++ (or the underlying Scintilla component) whereas the second one clears the file system's "Read only" file attribute - and this is an one-way ticket because it's not possible to **set** this attribute from within Notepad++.

**Comment by dinkumoil** [comment]
I think this can't be achieved in the way you would prefer. Imagine Notepad++ would store the state of its internal read-only flag for **all** files which it has been opened ever - the config file would grow to GBs over time.

**Comment by nathanm** [comment]
I don't mean every individual file, just the ones that were open when Notepad++ was closed.
