### ISSUE TITLE
Crash on exit when DSpellCheck and UniversalIndentGUI_NPP both loaded on W10 RS1 (1607)

### ISSUE THREAD

**Issue by GeographicCone** [notepad-plus-plus/notepad-plus-plus#4427]
Notepad++ crashes on exit with exception 0xc0000602 (_STATUS_FAIL_FAST_EXCEPTION_) in `combase.dll` when these two plug-ins are both loaded:

* **DSpellCheck** (1.4.3.0)
https://github.com/Predelnik/DSpellCheck

* **UniversalIndentGUI_NPP** (1.0.2.0)
https://github.com/danblakemore/universal-indent-gui/tree/master/src/UniversalIndentGUI_NPP

Happens on my Windows 10 x64 RS1 (1607) (`combase.dll` version 10.0.14393.187) but doesn't on Windows 8.1 (6.3.9600.17415).

This issue might be induced by a certain Windows 10 build, or something specific to another program on my system. If you don't mind checking, can anyone else reproduce it on Windows 10 RS1 or later?

#### Similar Issue Reported Earlier

Somewhat related to #2150 but unlike the user reporting that issue:
* I did not have `TabTip.exe` or `TabTip32.exe` running, and _TabletInputService_ was set to _Manual (Triggered Start)_ and not running.
* Starting and stopping, or disabling `TabTip[32].exe` and/or the service have no effect on the error for me.
* No other programs are crashing on my system, which I've been using on a daily basis for over 18 months now with this exact setup.

### Steps to Reproduce
1. Put `DSpellCheck.dll` and `UniversalIndentGUI_NPP.dll` in `%ProgramFiles(x86)%\Notepad++\plugins`.
2. Rename or delete `%APPDATA%\Notepad++` to make sure issue is not profile-related.
3. Run `%ProgramFiles(x86)%\Notepad++\notepad++.exe`. No need to open any document.
4. Exit, whether by choosing _File_ → _Exit_, clicking ×, or pressing Alt-F4.

### Expected Behavior
Clean exit.

### Actual Behavior
* A dialog pops up saying  _"Notepad++ [...] has stopped working"_, have to click _"Close the program"_ to dismiss.
* An error event is logged, details as above.

### Debug Information
```Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll UniversalIndentGUI_NPP.dll
```
(Other plugins removed as they play no role in the issue.)

**Comment by SinghRajenM** [comment]
Are you sure issue is in "DSpellCheck.dll"? I'm asking because I could not reproduce using your steps. Try to remove "UniversalIndentGUI_NPP.dll" and check whether culprit is "UniversalIndentGUI_NPP.dll" or "DSpellCheck.dll".

FYI - I'm using Windows 10 x64 RS3 (1709). I could not see any issue with Dspellcheck.dll.

**Comment by GeographicCone** [comment]
> I could not reproduce using your steps.

Thank you for your answer. To be more clear:

* `DSpellCheck.dll` only: no crash
* `UniversalIndentGUI_NPP.dll` only: no crash
* Both `DSpellCheck.dll` and `UniversalIndentGUI_NPP.dll`: crash

So yes, the crash no longer happens when either one of the plug-ins is removed.

Can you reproduce it when **both** plug-ins are loaded at the same time?

> Are you sure issue is in "DSpellCheck.dll"? 

Not sure at all but there were a couple of similar DSpellCheck issues in the past:

_Incorrect threads shutdown leading to crash_
https://github.com/Predelnik/DSpellCheck/issues/51

_NULL pointer dereference on exiting Notepad++_
https://github.com/Predelnik/DSpellCheck/issues/52

Discussion: _Major design flaw_
https://github.com/Predelnik/DSpellCheck/issues/53

_SendMessage deadlock on exit_
https://github.com/Predelnik/DSpellCheck/issues/92
(also discussed in #3558)

It could be something related to the above.

**Comment by MasoudRahmani** [comment]
SAME ISSUE!
removed the plugins, everything is fine.

**Comment by MetaChuh** [comment]
for plugin issues, please contact the plugin authors.

thank you for your help and best regards.

**Comment by RobertOnGit** [comment]
Notepad++ v8.4.8 with 8 plug-in installed:
I have the same crash on Windows Server 20xx, not on Windows 10/11.
After removing all plug-in and adding them back in one-by-one I found that Zoom Disabled 1.2 is causing this same error.

**Comment by rdipardo** [comment]
@RobertOnGit,

> After removing all plug-ins and adding them back in one-by-one I found that _Zoom Disabler 1.2_ is causing this same error.

You're on the right track. The underlying problem is that DSpellCheck does not play nice with plugins coded in *Delphi*[^1], like [Zoom Disabler] and the &#x2014; [equally incompatible]  &#x2014; ExtSettings plugin.

Delphi plugins implicitly call into COM libraries to create and destroy dialog windows. DSpellCheck makes [*explicit* calls to the same functions], against [the advice of Microsoft] to *never* call them from the context of `DllMain`,

> [b]ecause there is no way to control the order in which in-process servers are loaded or unloaded

DSpellCheck invalidates the Delphi plugin's own de-initialization by releasing the same resources first.

---
[^1]: Or rather, *Object Pascal*, since even Free Pascal plugins [are not immune to this issue](https://bitbucket.org/rdipardo/htmltag/issues/4/unsafe-call-to-oleuninitialize-in-fpguis).

[Zoom Disabler]:https://github.com/StanDog/npp-zoomdisabler
[`::OleUninitialize`]: https://learn.microsoft.com/windows/win32/api/ole2/nf-ole2-oleuninitialize
[equally incompatible]: https://github.com/Predelnik/DSpellCheck/issues/173#issuecomment-593865625
[*explicit* calls to the same functions]: https://github.com/Predelnik/DSpellCheck/blob/0de37ac74bc189eab8d940211989e81acea26fec/src/common/winapi.cpp#L95-L98
[the advice of Microsoft]: https://learn.microsoft.com/windows/win32/api/combaseapi/nf-combaseapi-couninitialize#:~:text=do%20not%20call%20CoInitialize%2C%20CoInitializeEx%2C%20or%20CoUninitialize%20from%20the%20DllMain%20function.

**Comment by RobertOnGit** [comment]
@rdipardo,

Sorry, I forgot to mention that I haven't installed DSpellCheck on the systems on which I can reproduce the crash with Zoom Disabler.

But from what you're saying is that the crash after Zoom Disabler is added is the _effect_, not the _cause_.
Thus I should do another test to find:
-remove all plugins
-then first install Zoom Disabler
-the crash should not happen at this point
-then add the other plugin one-by-one to see at what point the problem reappears.
After that I should report the issue with the found plugin.

I'll do that test and add the result here.

**Comment by RobertOnGit** [comment]
I've tested again today.
I've removed all plug-in and restart Notepad++. Then only installed Zoom Disabler 1.2. After that I already get the crash event logged on Win2019 (remember, only on Window Server operating systems, not on Windows client OSes).

Here are the full details:
Before my test I had the following six plug-in, which all six where removed before doing my test:
Compare 2.0.2
JSON Viewer 2.0.4
JSTool 1.2205
Mime tools 2.9
Npp Converter 4.5
NppExport 0.4
XML Tolls 3.1.1.13
Zoom Disabler 1.2

After only installing the Zoom Disabler 1.2 plug-in the follow error event is logged:

```
Faulting application name: notepad++.exe, version: 8.4.8.0, time stamp: 0x63a747f8
Faulting module name: combase.dll, version: 10.0.17763.3887, time stamp: 0x1436878c
Exception code: 0xc0000602
Fault offset: 0x0000000000026f77
Faulting process id: 0x264
Faulting application start time: 0x01d925cd358bf545
Faulting application path: C:\Program Files\Notepad++\notepad++.exe
Faulting module path: C:\Windows\System32\combase.dll
Report Id: fb79ca50-714c-4b74-a27d-ff3bb4ba5220
Faulting package full name: 
Faulting package-relative application ID: 

```
Details:

```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
 <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2023-01-11T14:58:59.415484800Z" /> 
  <EventRecordID>10168</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>rg-dev-rps2</Computer> 
  <Security /> 
 </System>
 <EventData>
  <Data>notepad++.exe</Data> 
  <Data>8.4.8.0</Data> 
  <Data>63a747f8</Data> 
  <Data>combase.dll</Data> 
  <Data>10.0.17763.3887</Data> 
  <Data>1436878c</Data> 
  <Data>c0000602</Data> 
  <Data>0000000000026f77</Data> 
  <Data>264</Data> 
  <Data>01d925cd358bf545</Data> 
  <Data>C:\Program Files\Notepad++\notepad++.exe</Data> 
  <Data>C:\Windows\System32\combase.dll</Data> 
  <Data>fb79ca50-714c-4b74-a27d-ff3bb4ba5220</Data> 
  <Data /> 
  <Data /> 
 </EventData>
</Event>

```
Conclusion:
It really is the Zoom Disabler 1.2 plug-in that causes the crash.
