### ISSUE TITLE
Feature request: Possibility to "Replace" without automatically doing "Find next"

### ISSUE THREAD

**Issue by P-Si** [notepad-plus-plus/notepad-plus-plus#4437]
### Description of the Issue
I'm doing a fairly complex RegEx "search & replace", and would like to see what my RegEx actually did to the firstly found string before jumping ahead to next matching string in my file. 

### Steps to Reproduce the Issue
Do any "Replace" and after replacing the cursor jumps automatilcally to the next item, so I cannot see what the replace actually did to the found string.

### Desired Behavior
Have a possibility to press (for example) "alt" key while pressing "Replace" button in order to just replace without jumping ahead to next matching string in file

pekka

**Comment by dinkumoil** [comment]
I would like to have such a feature too.

**Comment by Yyyyes** [comment]
Hi.  I would like to have such a feature too.  - I have that same problem over and over again.  Thanks

**Comment by sasumner** [comment]
So a known workaround to this, is after doing your replace (single), switch back to the editor tab and do an Undo than a Redo (use keystrokes).  Your caret will be left where the substitution occurred.  Ideal? Nope.  Workable? Well, I find it to be.

**Comment by Yyyyes** [comment]
I used the workaround for quite some time, but I am fed up with it..  
Not having the text moved on the screen would make it much easier to check the replacement (presently, when coming back, the doc doesn't display at the same line as before, so I have to search for the cursor position too).  Very often, I ask myself "did it do what I expected?,"  And I go back to check...   "  a real pain, with the risk of adding errors in the process.  

What makes it so difficult to split the <replace> button into two button ----- a first<replace & stay// go next if just replaced here> and  --- a second <replace & go to next>?  
For the shortcut keys, the SAME shortcut key should allow, first hit to <replace and stay> and, second hit, if no cursor move has been done, to <go to next>.  
Alternatively, a solution coud be to optionnaly put a delay (1-2 seconds)  in order to view the replacement result before proceeding to next occurence. 
Why is it such an extraordinary request to be able to check the result of the operation before going to the next one  ?   For instance, Textpad does it with a <Replace>  <Replace Next> pair of buttons.

Y.
PS I would also ask for shortcut keys for the <   >>   find next> and < <<   find previous> operations.

**Comment by sasumner** [comment]
>I used the workaround for quite some time, but I am fed up with it.

Here's another workaround that can be handy, but you won't like:  Press Replace All.  The screen doesn't change so you can see your first replacement.  You can undo it like the other workaround and then continue on...

>What makes it so difficult to split the button into two button...

Nothing.

>Why is it such an extraordinary request...

It isn't.

**Comment by Yyyyes** [comment]
Thanks,Y

 

De : Don HO ***@***.*** 
Envoyé : lundi 26 avril 2021 10:29
À : notepad-plus-plus/notepad-plus-plus
Cc : Yyyyes; Comment
Objet : Re: [notepad-plus-plus/notepad-plus-plus] Feature request: Possibility to "Replace" without automatically doing "Find next" (#4437)

 

Closed #4437 <https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4437>  via  <https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a0177e8d050291992a24e334762c824005ffcc06> a0177e8.
