### ISSUE TITLE
Feature Request: Showing whitespace symbols only for the indentation area.

### ISSUE THREAD

**Issue by SalviaSage** [notepad-plus-plus/notepad-plus-plus#4476]
### Description of the Issue:
I looked into the scintilla API and it is possible to configure it in such a way that it only shows the whitespace symbols for the indentation area of code.
However, this is only on a more recent version of Scintilla, and thus can not be done in notepad++.

You can already make it so that only the whitespace symbols outside of the indent area would be shown.
We should also be able to make it so that only the whitespace symbols INSIDE the indent area would be shown.

It is useful to be able to see the space or tab characters in the indentation area, which the editor can already do anyway.

Thanks for your consideration;

Related forum post here:
https://notepad-plus-plus.org/community/topic/15507/feature-request-show-only-line-final-whitespace

**Comment by sasumner** [comment]
As you have been informed, this is not controlled by Notepad++ but rather by Scintilla.  There is nothing to be done for it unless/until Notepad++ adopts a Scintilla version that supports this.  Thus, technically you should make a request that Scintilla be updated rather than this request.  But..., I'm sure that there is already an issue requesting a Scintilla update.  Even that is not really needed as the Notepad++ author is well-aware of the status of the primary Notepad++ component.  He chooses when to update Notepad++ with a new Scintilla version, and apparently hasn't felt the need to do so in a number of years--nothing to be done for it.

**Comment by fml2** [comment]
> He chooses when to update Notepad++ with a new Scintilla version, and apparently hasn't felt the need to do so in a number of years--**nothing to be done for it.**

Fork? ;-)

**Comment by Ekopalypse** [comment]
@SalviaSage npp 7.7 which uses a Scintilla 4.x version is available now. If you are using scripting plugins
you should be able to make it work like you want it to behave.

**Comment by MetaChuh** [comment]
@SalviaSage 

a separate indentation case whitespace highlight will currently not be implemented at the notepad++ core, but it is a customisation option for script and plugin developers, like other cases you have experienced as long term member at our community.

please note, that your idea and desire is not wrong or awkward, but we are currently trying to make the core as issue free and highly customisable as possible, which is only possible by leaving certain features to our community developers, instead of trying to deal with too much at once at the main core.

as always many thanks for your understanding and best regards.

**Comment by sasumner** [comment]
@SalviaSage For a scripting example, see one of the sub-examples presented here:  https://notepad-plus-plus.org/community/topic/17626/plugin-update-luascript-v0-9-supports-scintilla-v4-1-4

**Comment by SalviaSage** [comment]
Thank you.
This is now possible in Notepad++ by the use of a plugin.

**Comment by dinkumoil** [comment]
I wrote a plugin that can be used to display whitespace used for indentation normally but after the first visible character, it is shown as dots and arrows. Its name is _ExtSettings_. You can download it [>>> here <<<](https://sourceforge.net/projects/extsettings/). It will also be available soon via _PluginsAdmin_.
