### ISSUE TITLE
Indian rupee symbol ₹ not displaying

### ISSUE THREAD

**Issue by milindsmart** [notepad-plus-plus/notepad-plus-plus#4536]
### Description of the Issue
When I type a ₹ (Indian rupee symbol : U+20B9), notepad++ displays a ▯. Windows default Notepad has no problems with it. 

Very curiously, if I select the character and right-click on it, it shows 'Ignore "₹" for the current session' menu option correctly.

Renaming plugins folder does not help.

### Steps to Reproduce the Issue

1. New text file
2. Type (RightAlt + 4) or paste the ₹ symbol
3. Select it and right click

### Expected Behavior
₹ symbol is rendered
'Ignore "₹" for the current session' shows the character correctly

### Actual Behavior
▯ character appears
'Ignore "₹" for the current session' shows the character correctly

### Debug Information
Notepad++ v7.5.6   (64-bit)
Build time : Mar 19 2018 - 00:23:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by sasumner** [comment]
This may help explain things:  https://notepad-plus-plus.org/community/topic/15758/some-characters-are-not-displayed-unicode/
Especially the part where Notepad.exe displays correctly and Notepad++ doesn't.

**Comment by craftwar** [comment]
I have similar display issue after upgrading Win10 1709 to 1803.

**Comment by milindsmart** [comment]
The link was absolutely excellent, and helped me understand how some fonts seemed to support everything. 

So, do Composite Fonts figure on the Notepad++ dev roadmap?

**Comment by MetaChuh** [comment]
@milindsmart 

your issue is not reproducible on 7.6.6.
₹ (Indian rupee symbol : U+20B9) is shown correctly, as seen at the screenshot below:

<img width="409" alt="Bildschirmfoto 2019-05-07 um 03 23 18" src="https://user-images.githubusercontent.com/45773305/57265347-997c7380-7077-11e9-8133-d967a3acfa2c.png">

<kbd>Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NppJumpList.dll</kbd>

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
