### ISSUE TITLE
Consider using the `/Gw` compiler switch (can shave ~50k from Notepad++ executable!)

### ISSUE THREAD

**Issue by ariccio** [notepad-plus-plus/notepad-plus-plus#455]
The [`/Gw` compiler switch](http://blogs.msdn.com/b/vcblog/archive/2013/09/11/introducing-gw-compiler-switch.aspx) allows removal of unused data.

In my tests, an unmodified `Unicode Release` build creates a binary thats ~(2MB + 48KB) big:

```
07/10/2015  01:41 AM         2,048,000 notepad++.exe
07/10/2015  01:41 AM         9,908,224 npp.pdb
```

With `/Gw`, we shave ~45KB from the binary:

```
07/10/2015  01:50 AM         2,003,456 notepad++.exe
07/10/2015  01:50 AM         9,908,224 npp.pdb
```

**_HOWEVER**_, [under certain circumstances](http://stackoverflow.com/questions/29056890/is-visual-studio-2013-optimizing-correctly-in-the-presence-of-opticf/29057190#29057190), it can _generate bad code_. If we avoid _referencing global data by address_, then we can benefit from this optimization.

**Comment by milipili** [comment]
We will see later with the cmake build

**Comment by bviktor** [comment]
So um, 2% size reduction on one executable (0% for the whole distribution) in exchange for stability? What kind of sense does that make to you, mate?

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
