### ISSUE TITLE
extended or regex search in files for a pattern with a leading newline shall report the lines following the matching newlines

### ISSUE THREAD

**Issue by Rainald62** [notepad-plus-plus/notepad-plus-plus#4568]
### Description of the Issue
When I search for a pattern at the beginning of lines, the "Find result" list presents the lines ending with the matching newline characters.

### Steps to Reproduce the Issue
1. Copy the following four lines into an empty tab ("new 1"). 
1st line of code
// comment A
2nd line of code
// comment B
2. Open the Find dialog.
3. Type \n// into the Find What field.
4. Activate Extended mode.
5. Hit the "Find all" button.

### Expected Behavior
Search "\n//" (2 hits in 1 file)
  new  1 (2 hits)
	Line 2: // comment A
	Line 4: // comment B

### Actual Behavior
Search "\n//" (2 hits in 1 file)
  new  1 (2 hits)
	Line 1: 1st line of code
	Line 3: 2nd line of code

**Comment by sasumner** [comment]
The `\n` is the first thing in your search string.  In the Find result panel, the line-ending is highlighted as (the start of) the match (and since the line-ending is part of the line it belongs to, you see lines 1 and 3 rather than 2 and 4.  The Find result panel does not show multiline results; it only shows the first line of such a result.  Note that there are other "issues" open (as feature requests) to allow mulitline matches to be shown as such.  But the way it stands now, for your scenario, Notepad++ is working properly.

BTW, you can get the results you want by searching for this regular expression instead: `(?<=\r\n)//` if you use Windows line endings, or `(?<=\n)//` if you use Unix line endings.  For some reason the more generic `(?<=\R)//` doesn't seem to work in this case.

**Comment by Rainald62** [comment]
I would prefer the notion of "line break" over "line ending". That would not only solve my problem without multiline output, but would also prevent the oddity of a last "line without ending".

Thanks for reminding me of regex assertions.

^// is easier and would yield a comment as the very first line. I tried ^ before my post, unsuccessfully so, don't know why.
