### ISSUE TITLE
PHP function stripos() not recognized

### ISSUE THREAD

**Issue by jaap198503** [notepad-plus-plus/notepad-plus-plus#459]
The function stripos remains black in the editor. I expect it to become bold and blue.
http://php.net/stripos
It is almost the same function as strpos.

**Comment by Rikk** [comment]
I think it is because `langs.model` is more outdated than individual language auto-completion (API) files.

I don't know why Notepad++ uses keywords from `langs.model` instead of auto-completion files for highlight... Whatever, people updating API files should remember to update `langs.model` too.

(Not to mention auto-completion files are almost 3-4 years old -- except my few recent additions)

I added this to my fork [langs.model branch](https://github.com/Rikk/notepad-plus-plus/commits/langs.model)
