### ISSUE TITLE
Hot Key (Accelerator) needed for 'Find all in current document'

### ISSUE THREAD

**Issue by rpaddu** [notepad-plus-plus/notepad-plus-plus#4590]
### Description of the Issue
Feature Request : Hot Key (Accelerator) needed for 'Find all in current document'

### Steps to Reproduce the Issue
Please provide a Hot Key (Accelerator) needed for 'Find all in current document' like Alt+A or Alt+D

**Comment by dinkumoil** [comment]
I think there is only a little chance that this will be implemented because it wouldn't make sense to provide access only to the "Find all in current document" feature and omit the rest of the Find/Replace dialog.

If you are in urgent need of this functionality you could use the same approach like in [this comment](https://notepad-plus-plus.org/community/topic/15804/macro-delete-lines-that-contains-text-in-clipboard/6) on the community forum.

The script's code for your use-case would be:

    set local NirCmdPath = <Path-to-the-folder-of-step-3>\nircmdc.exe

    npp_sendmsg WM_COMMAND IDM_SEARCH_FIND  // show Find dialog

    "$(NirCmdPath)" sendkeypress ctrl+v  // paste from clipboard
    "$(NirCmdPath)" sendkeypress alt+<accelerator-key-for-Find-All-In-Current-Document-button>  // search
    "$(NirCmdPath)" sendkeypress esc  // close Find dialog

To define an accelerator key for the Find-All-In-Current-Document button you can edit one of the following files (in the caption string of the button add a &-character **before** the letter you want to use as accelerator key, be aware that the accelerator keys of **all** tab pages of the Find/Replace dialog must be unique):

* `%UserProfile%\AppData\Roaming\Notepad++\nativeLang.xml`
* `<Notepad++-install-dir>\localization\<your-locale>.xml`.

If you edit the first file the changes will disappear after updating Notepad++ and when you temporarily change Npp's UI language. In order to take place the changes you have to restart Notepad++.

If you edit the second file the changes will only disappear after updating Notepad++. In order to take place the changes you have to temporarily change Npp's UI language to an arbitrary language and then switch back to your language again.

**Comment by sasumner** [comment]
As a workaround, did you know that you can edit your language file (e.g. english_customizable.xml) and add `&amp;` before the letter in the text of the command you want to be the accelerator?

**Comment by sasumner** [comment]
Also, see #4531

**Comment by ArkadiuszMichalski** [comment]
@donho @sasumner This was fixed.
