### ISSUE TITLE
libcurl is built without the HTTPS-proxy support.

### ISSUE THREAD

**Issue by ytterx** [notepad-plus-plus/notepad-plus-plus#4602]
### Description of the Issue

Unsupported proxy, '<proxy>', libcurl is built without the HTTPS-proxy support.

### Steps to Reproduce the Issue

1. Make sure you use a proxy with https
2. Start Notepad++
3. Goto menu '?'
4. Select 'Update Notepad++'

### Expected Behavior

Notepad++ to check for newer versions

### Actual Behavior

Got the error:
Unsupported proxy, '<proxy>', libcurl is built without the HTTPS-proxy support.

**Comment by versat** [comment]
I have this issue after updating from pre 7.6 to 7.61. It worked for years without a problem:
https://notepad-plus-plus.org/community/topic/16790/notepad-7-6-1/64

**Comment by versat** [comment]
I found the reason why it was not working for me:
When setting the proxy for the updater Notepad++ (or GUP) wants to create the file `gupOptions.xml` in the installation directory under the folder "updater". For me this is "C:\Program Files\Notepad++\updater". Since one needs administrator rights to create files there i needed to start Notepad++ as admin when setting the proxy.
Once the file is created the check for an update works also as normal user.

It would be great if Notepad++ could ask for admin rights before trying to create or change files in such protected directories (or at least open a message box that i have to start Notepad++ as admin when i want to set a proxy). I guess another solution would be to move such files to a folder where no admin rights are needed like the ProgramData or ApplicationData folder.

**Comment by chcg** [comment]
@ytterx Do you have the same as issue as described by @versat ?

**Comment by ytterx** [comment]
@chcg Yes, it seems that gupOptions.xml indeed doesn't get created or written to if Notepad++ has no admin rights.
Also, Notepad++ doesn't read or use the environment variables HTTP_PROXY and / or HTTPS_PROXY?
But that might be more of a feature than a bug.

The workaround, by running Notepad++ in administrator mode, and then setting the proxy settings works.
