### ISSUE TITLE
Symbols change after saving and reopening a file

### ISSUE THREAD

**Issue by mooncrater31** [notepad-plus-plus/notepad-plus-plus#4612]
### Description of the Issue

Symbols like 'म' and 'ः' get converted to '?' and other non-related symbols.
### Steps to Reproduce the Issue

1.  Save a file with 'म' or 'ः'
2.  Reopen it

### Expected Behavior

The symbols should not change, once the file is written to disk.
### Actual Behavior

The symbols change once the file is written to the disk.
### Debug Information

Check line numbers 87 and 91.
![Before](https://user-images.githubusercontent.com/34881801/42027562-a8092e9c-7ae7-11e8-89c3-5325f2307395.png)
![After reopening](https://user-images.githubusercontent.com/34881801/42027563-a86b7ee4-7ae7-11e8-9595-bdbda4f115e6.png)

**Comment by rddim** [comment]
I can't reproduce this, because may be I have missed fonts. On 1st screen your file is in UTF-8 and the 2nd is in OEM-866. Check the state of `Autodetect character encoding` in `Settings` > `Preferences...` > `MISC.`. If it is enabled just disable it and try again. Also your Debug Information must be copied from `?` > `Debug Info...`
