### ISSUE TITLE
Line numbers starting with zero

### ISSUE THREAD

**Issue by ajtruckle** [notepad-plus-plus/notepad-plus-plus#4613]
This has to be easy to implement. Can we please have an option to start line numbers with 0. 

Thank you.

**Comment by cmeriaux** [comment]
It may be handle by Scintilla. So it's no easy to do.

**Comment by dinkumoil** [comment]
@ajtruckle 

I wrote a plugin which can display 0-based line numbers (if you want as hex numbers, too). It can be (de-)activated by an entry in the Plugins menu and saves its activation state and settings in an INI file in order to restore them at the next run of Notepad++.

You can download it [here](https://github.com/dinkumoil/CustomLineNumbers). It would be great if you would provide some feedback and/or ideas for enhancements.

Since the plugin is not available via PluginManager (and will not in the near future), it has to be installed manually. Installation instructions can be found on the project page.

**Note:** If you work with large files (10000 or more lines, depends on your hardware) the plugin will cause a serious performance decrease when loading the file and inserting or deleting lines because custom line numbers in Scintilla can only be done by self-filled text margins.

**Comment by dinkumoil** [comment]
@cmeriaux 

> nice plugin !

Thank you!

> I'm just curious, what is the plugin language ? Pascal ?

It's Delphi (version XE2 to be precise, published in 2010). So yes, it's a sort of Object Pascal.

**Comment by dinkumoil** [comment]
@ajtruckle 

> Is it possible that we have the column 4 characters wide for the whole document?

Sorry, that's not possible with a plugin. The width of the line numbers margin is managed by Notepad++. I've already tried to set the margin width according to the **actual** width of **hexadecimal** line numbers (the number of digits of hexadecimal numbers grows slower than the number of digits of decimal numbers) - it failed.

The Notepad++ documentation at [this page](http://docs.notepad-plus-plus.org/index.php/Margins) states:

> Since the width of the margin is computed whenever display changes, setting its width may not be useful. The width is computed to be as large as needed, with a minimum of three digits (to avoid annoying jump effects btween line 99 and 100).

**Comment by ajtruckle** [comment]
No worries. Thanks any way ... 😊

________________________________

**Comment by dinkumoil** [comment]
@ajtruckle  and @cmeriaux 

The latest release of my plugin no longer causes a performance decrease of Notepad++, even when editing large files. You can download it [here](https://github.com/dinkumoil/CustomLineNumbers).

**Comment by sasumner** [comment]
@dinkumoil Curious, what was the cause of the performance problem, and if interesting, what was the fix?  I looked at the changes but it was not clear to me...

**Comment by dinkumoil** [comment]
@sasumner 

> I looked at the changes but it was not clear to me...

Yes, I have to apologize. Since I'm currently the only contributor to this project I don't have the discipline to only check in small changes and to avoid simply cosmetic changes like code restructuring.

> what was the cause of the performance problem

My code for activating and actually doing line numbering was inspired by [this posting](https://github.com/jacobslusser/ScintillaNET/wiki/Displaying-Line-Numbers#custom-line-numbers). The author uses a brute-force algorithm for line numbering - "Number all lines of the document" respectively "Number all lines starting from the point a line was inserted or deleted".

I understood that it would be better to hook some sort of "OnDocumentScrolled" event but since there were some other problems to solve I've postponed this problem to the end of development - well, nearly to the end. Today I became aware that increasing the size of the Notepad++ window leads to missing line numbers, I've already released a new version.

**Comment by ajtruckle** [comment]
@dinkumoil I am struggling to find the actual dll in the downloads.

**Comment by dinkumoil** [comment]
@ajtruckle 

Go to [this page](https://github.com/dinkumoil/CustomLineNumbers/releases) and download the appropriate ZIP file for your Notepad++ version (32 bit => `CustomLineNumbers_v1.1.5_UNI.zip`, 64 bit => `CustomLineNumbers_v1.1.5_x64.zip`). Follow the installation instructions [here](https://github.com/dinkumoil/CustomLineNumbers#manual-installation).

**Comment by dinkumoil** [comment]
Just for completeness: The plugin is available now via _PluginManager_ (Notepad++ v7.5.9 and below) and via _PluginsAdmin_ (Notepad++ v7.6 and above) as well. 

Its repository has been moved to [_sourceforge.net_](https://sourceforge.net/projects/customlinenumbers/). Thus all links to the old _GitHub_ repo in my comments above will not work anymore.

**Comment by sasumner** [comment]
@dinkumoil Just curious on why a move from github to sourceforge?  TBH I have NEVER heard of that kind of move--sure, LOTS of moves in the other direction! :)
