### ISSUE TITLE
PHP function list ignores functions starting with "for"

### ISSUE THREAD

**Issue by laxamar** [notepad-plus-plus/notepad-plus-plus#4627]
### Description of the Issue

In my classes and functions, I have a bunch of functions starting with "format" like "function format_input(" and "function formatBrowse"

These functions do not show in the functions list

### Steps to Reproduce the Issue

1. Create a ckass in PHP
2. create a function with the name starting with 'format' such as 'function format_input'
3. These functions do not display in the function list
4. Profit

### Expected Behavior

Every function name should appear!

### Actual Behavior

Functions with names starting with format do not show up

**Comment by laxamar** [comment]
Thank will try .. as soon as I find out where Notepad++ saves the parsers ... :-)
Could you guide me where to look for it?

**Comment by laxamar** [comment]
functionList.xml => that's where I changed it

Same result. Still not working.
I looked at the regex and don't understand why "format" would not be recognized. Is this the only place where things are parsed?

**Comment by MAPJe71** [comment]
1. There might be more than one `functionList.xml` file on your system.
2. Make sure the source files end with an empty line.

**Comment by Skrol29** [comment]
I have the same issue, but I cannot get rid of it.
I have Notepad++ version 7.8.1., Windows 10  64 bits.
I’ve deleted the file _functionList.xml_ placed in the folder _AppData\Roaming\Notepad++_ , when Notepad++ restart then this file is replaced with a new one which date is 2019-09-27, and which has the same size as the same named file in the application folder. Exact size is 65.536 bytes.

**Comment by igll** [comment]
The issue remains:

### Description of the Issue
Function list shows wrongly the PHP functions starting with "For" or "for"

### Steps to Reproduce the Issue
1. Create and save an example.php file with this one line: function ForExample(){}
2. Menu View > activate Function List

### Expected Behavior
Function list should show "ForExample"

### Actual Behavior
Function list shows "orExample"

### Debug Information
Notepad++ v7.8.5   (32-bit)
Build time : Mar  4 2020 - 11:04:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1909
OS Build : 18363.752
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll Tidy2.dll
