### ISSUE TITLE
How do I install this fix for inline comments?

### ISSUE THREAD

**Issue by protonpacks** [notepad-plus-plus/notepad-plus-plus#4640]
I came across a problem with YAML in np++ where comment highlight syntax stops working in certain scenarios. I found a thread on sourceforge.net where apparently someone about that exact issue and a file to fix the problem was attached.

it's a file called LexYAML.cxx and I have no idea how to actually install this fix to np++

here is the link to the thread:
https://sourceforge.net/p/scintilla/bugs/1660/

does anyone know how I can install the LexYAML.cxx file?

**Comment by warg0x4e** [comment]
The LexYAML.cxx is a `C++ source code` file for _Scintilla_. Notepad++ 7.5.6 uses SciLexer.dll version 3.5.6 from Scintilla. The LexYAML.cxx you linked to was committed to Scintilla on September 23, 2016. It is likely fixed in SciLexer.dll version 3.7.0 and later. You would need to compile Scintilla  yourself. However, it is unlikely to work, as Notepad++ uses a _signed_ SciLexer.dll ([v7.3.3 - Fix CIA Hacking Notepad++ issue](https://notepad-plus-plus.org/community/topic/13415/v7-3-3-fix-cia-hacking-notepad-issue/14)).

I suggest searching here for issues requesting the use of a newer version of SciLexer.dll, and showing your support with a ![2018-07-07_22-03-05](https://user-images.githubusercontent.com/2155010/42416021-8fcc6118-8231-11e8-941c-e1d0baca6631.png), or submitting your own.

**Comment by Ekopalypse** [comment]
@protonpacks  - npp 7.7 which uses a Scintilla 4.x version is available now, I assume this issue can be closed, right?

**Comment by dail8859** [comment]
@Ekopalypse Using the example in that Scintilla bug report it doesn't seem fully fixed.

![image](https://user-images.githubusercontent.com/3694843/58267934-7e398580-7d52-11e9-921b-8164b3c0e100.png)

**Comment by dail8859** [comment]
Closing as this issue is no longer needed since Notepad++ updated its version of Scintilla.

Use #4638 for further discussions about the YAML lexer.
