### ISSUE TITLE
Icon too similar to spreadsheet software icons.

### ISSUE THREAD

**Issue by ClarusDignus** [notepad-plus-plus/notepad-plus-plus#4654]
### The Problem

The icon for Notepad++, as in the icon that appears in the Windows taskbar, looks to similar to the icon for spreadsheet software. E.g. Libre Office Calc.

Both are green vertical oblongs. I'm constantly confusing the two.

The green colour scheme for spreadsheet icons was likely "standardised" by Microsoft Excel. The green colour scheme is an at-a-glance association with spreadsheets for users.

Icons are functional as much as they are aesthetic. User's at-a-glance association with the Notepad++ icon shouldn't be  muddled.

### Proposed Solution

The Notepad++ icon icon colour scheme should be a neutral white to avoid confusion.

Furthermore, the pencil and "N" should be removed on the basis that they are redundant and too complex in terms of graphical detail. A page with two plus symbols is sufficient.

**Comment by sasumner** [comment]
Wow, I guess the color green is forever-more unusable in icons....

**Comment by dinkumoil** [comment]
Oh yes, and also think about blue, it is the color for text processing software because MS Word has set it as a standard. But damned, Visio is also blue, it's even the **same** kind of blue like Word. And Outlook is blue, and Internet Explorer, and TeamViewer, and TotalCommander, and InnoSetup, and ... 

The only solution to prevent 50% of world wide computer users from going to the madhouse is - **Patented colors including all of their shades** for all MS office programs! It will be interesting to see the Word and Viso divisions fight each other at the courts.

If you complain "But the only remaining colors will be black, white and grey!" - that doesn't matter, it fits the glorious design of Windows 10 in an optimal way.

**Comment by ClarusDignus** [comment]
The facetious responses are, at the very least, humorous.

I maintain my stance that the icon for Notepad++, as a notepad software, should be white.

The very name of the **Notepad**++ software is derivative of Microsoft's **Notepad**. Not too great a leap is required to consider that colour scheming should be correspondingly derivative. 

It's a matter of intuitive association. If I glance at my task bar in the hopes of identifying Notepad++, my brain expects a white vertical oblong icon, akin to Microsoft's Notepad. Once my brain kicks into gear and comes to expect to find a green vertical oblong, I intermittently end up selecting my opened spreadsheet software.

In the interests of objectivity, the icon of Adobe's Dreamweaver, a code editor, is green which presents a counter-basis for my recommendation.

That being said, I'm still of the view that a white icon is the best choice for a notepad software.

**Comment by ClarusDignus** [comment]
I stand corrected. The Microsoft Notepad icon is a white pad with a translucent blue cover. It's the very same on Windows 10.

**Comment by MetaChuh** [comment]
@ClarusDignus 

thank you for your ideas concerning the notepad++ icon.

unfortunately we can not change the icon, as it might cause confusion, as well as some users not being able to identify the notepad++ icon anymore.

an idea you can pursue, is to request an icon change for libre office calc.
to learn how do so, please visit the [documentfoundation pages](https://wiki.documentfoundation.org/QA/BugReport).
alternatively use a different spread sheet application, which has a more distinguishable icon.

many thanks and best regards.
