### ISSUE TITLE
Custom search engine

### ISSUE THREAD

**Issue by xuhdev** [notepad-plus-plus/notepad-plus-plus#466]
Hard wiring Google search in Notepad++ seems a bit strange: Notepad++ should be neutral on which search engine to use (even Chrome allows you to change the default).

In addition, even hard wiring a search engine, I would do Duckduckgo instead of Google, with which Notepad++ shares a similar value of freedom.

**Comment by Rikk** [comment]
Myself I would opt for completeness in results instead of ideology based on unproved suppositions...

**Comment by xuhdev** [comment]
@Rikk The main topic of this issue is that Notepad++ should not hard wire a specific search engine, hard wiring duckduckgo is only a fallfack of the original proposal.

**Comment by milipili** [comment]
I agree with you @Rikk, even if I also agree with @xuhdev...

**Comment by vgturtle127** [comment]
@milipili @donho Has any research or work be done for this?

**Comment by milipili** [comment]
Adding DuckDuckGo (and potentially others like bing or yandex) would be a good thing I guess.

**Comment by milipili** [comment]
see #407

**Comment by milipili** [comment]
See PR #468 [User defined commands: using DuckDuckGo as default search engine]

**Comment by scootergrisen** [comment]
Basically i don't want to see any company name in context menu from a fresh Notepad++ installation.
Firefox have for a long time use google as the default search engine and got a lot of money for it but its annoying when you dont want to use google that google is there as default choice.
You could make a setting to have the user select a search engine from a list and until the users have selected one the search menu item does not appear, but please don't make google or other the default like in Firefox because its annoying when you try to avoid certain companies with bad practices.
I would prefer that no search engine was the default.
But i never really used the context menu search so i don't know what would be best for the users that does use it.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e451efbd290f36300fe08a3b5be5460c5dd94f84
