### ISSUE TITLE
Stupid Issue On Which Side is 'Other View'

### ISSUE THREAD

**Issue by tilkinsc** [notepad-plus-plus/notepad-plus-plus#4660]
### Description of the Issue
When swapping which side tabs are on, they sometimes all go to the right and the left is stuck with the tab you were trying to put over there.

### Steps to Reproduce the Issue
Unknown how to reproduce, but sometimes resolves when you close all tabs. Reproduce it when the bug is occurring by right clicking a tab with no tabs open and click move to other view.

### Expected Behavior
My tabs to always go to the right side of the screen, not the left

### Actual Behavior
The tabs went to the left side

### Debug Information
Notepad++ v7.5.7   (64-bit)
Build time : Jun 29 2018 - 00:53:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

Windows 10 and confirmed on windows 7, been a part of notepad++ for a long while now.
![image](https://user-images.githubusercontent.com/7494772/42685489-1949b6ec-8661-11e8-93e3-ed0d9db52408.png)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by tilkinsc** [comment]
I actually found the issue and it isn't resolved.

When you close all left side tabs and it shrinks down to one window, your move to other window is swapped.

I updated and still reproduced.

**Comment by sasumner** [comment]
So what happens is that when you move documents to view0 to view1...and you move ALL of them, they are now ALL in view1 (which makes sense I guess).  Since there is nothing now in view0 to show, the Notepad++ screen appears as if all the documents are in view0 now (but they aren't, they are still in view1). Thus, picking a document from this stage and moving it to other view is actually working (it gets moved to view0), and view0 is restored on the left (or top) side of the Notepad++ tab area.  So it is a bit unexpected (visually), but I suppose it makes sense the way it works.  

IMO I would rather that if the number of open tabs in view0 ever becomes zero, that all tabs in view1 get shifted to view0 and view1 disappears.  But I'd guess that that would upset people used to the current behavior (if anyone has ever noticed it).

**Comment by tilkinsc** [comment]
Yeah it's time to find a new text editor.

**Comment by sasumner** [comment]
@tilkinsc I understand your feeling, but hopefully THIS issue isn't the one that pushed you over the edge.  :)

**Comment by tilkinsc** [comment]
Nah all my issues got shot down.
