### ISSUE TITLE
Re-Design for NPP

### ISSUE THREAD

**Issue by talentlessguy** [notepad-plus-plus/notepad-plus-plus#4667]
<h1>NPP's UI looks ancient :/</h1>
<p>I have some submissions how to improve UI to make it more modern</p>
<img src=https://user-images.githubusercontent.com/35937217/42728122-d95d1536-87bb-11e8-9051-744b2ef32f47.png>
<h1>First Step: Get rid of unnecessary tab</h1>
<img src=https://image.ibb.co/fJUk7T/1.jpg>
<p>Buttons's style remind me Windows XP :)
But the problem is that it is unnessesary tab, you can use them in the upper tab, so It is useless (Sorry for being rude). If we get rid of this, we will have addiotional free space!</p>
<h1>Second Step: footer doesn't have a required functionality</h1>
<img src=https://image.ibb.co/my0du8/2.jpg>
<p>In other editors, (e.g. Atom or VS Code) we can click on "UTF-8" and change the encoding. But in  NPP we need to go to Menu Bar > Encoding. This is also unnessary. It can be packed just into encoding button like changing INS/OVR. Also syntax info needs to be moved to right (I mean "Hyper Text Markup Language FIle"). Syntax choosing should be moved to footer like with encoding to get more free space. I hope you undestand me :)</p>
<h1>My Submission for Re-Design</h1>
<h2>It is not the main part!</h2>
<p>I spent nearly 1,5 hours and now I can show you my suggestion, with the light theme, and dark theme. Themes will be able to be changed as always :) These are the sketches, not completed UI</p>
<h2>Dark theme:</h2>
<img src=https://image.ibb.co/cbqgxT/NPP_UI_dark.png>
<h2>Light theme:</h2>
<img src=https://image.ibb.co/edWocT/NPP_UI_light.png>
<h2>Some global changes to editor</h2>
<p> I will edit this issue from time to time.</p>
<h3>1. Get rid of 3 options from menubar and saved some space</h3>
<h3>2. Transfered Encoding and Syntax tabs to footer</h3>
<h3>3. Added margins to the main tab (space between text and edges of the tab)</h3>
<h3>4. Make plugins more interactive</h3>
<h3>5. W.I.P. Combine Tools & Plugins to Extensions tab</h3>
<img src=https://image.ibb.co/fjovP8/NPP_UI_Colored.png>

<h3> What do you think about it? Share your ideas below! :smile_cat: </h3>

**Comment by sasumner** [comment]
Nice effort, probably no one cares... see https://notepad-plus-plus.org/community/topic/250/it-s-time-for-ui-update

**Comment by DavidHansen-0x454d43** [comment]
@talentlessguy, I appreciate your ideas, and mockups. However, to me it seems like the consensus on that community thread is, "meh... the current UI works and doesn't suffer some of the drawbacks of a flat/ribbon UI". 

There is also the problem that a UI refresh is kind of a massive undertaking, and unless you are willing to put in a lot of that work yourself, its probably not going to get done. 

I like your Split Up/Down/Right/Left right click options though, and think it might get some traction. The project panel is one area that could use some improvement. Maybe you could submit a feature request for just that part?

Also, what do you mean by "4. Make plugins more interactive"?

**Comment by talentlessguy** [comment]
@DavidHansen-0x454d43 I mean add them more GUI. It may sound a bit weird, but creating an MD5 encryptor & decryptor interface with the similar GUI would be cool. I'll send some more extensions (tools + plugins) ideas.

**Comment by talentlessguy** [comment]
@DavidHansen-0x454d43 what about removing a tab with icons and replacing to tool bar? Also re-optimising toolbar and replacing commands?

**Comment by sasumner** [comment]
@talentlessguy You can make the changes and submit a pull request for them....see if it gets accepted

**Comment by Charon77** [comment]
I believe while this looks cool, we just currently don't know how to make fancy tabs like that while not degrading performance. I mean, I'd totally work on it if I know how. I stumble upon this issues looking for the same issues.

Editors like Atom could do it because they run HTML CSS. I'd LOVE to use Atom if only it runs as fast as Npp. But it doesn't.

That being said I totally agree that it'd be better if _at least_ we can change the toolbar to black or smth

**Comment by talentlessguy** [comment]
@Charon77 the main idea is not color scheme, but there is no need to add Electron framework. Look at Adobe Phototshop - it is colored in non standard scheme - why not to do it in NPP? Also unusable UI is the main problem

**Comment by sasumner** [comment]
@talentlessguy what does this part mean?: "Also unusable UI is the main problem"

**Comment by MetaChuh** [comment]
@talentlessguy 

many thanks for your user interface submissions.
please give us a short note, as soon as you are finished coding them into notepad++.

thank you for your help and best regards.

**Comment by aplocher** [comment]
A simple dark theme option and a flat UI instead of these old Windows 95ish 3D tabs wouldn't require Electron or any extra resources.  Yes Atom and  VSCode look great and have some very rich UI features, and I don't think anyone is asking NPP to sacrifice performance for those types of things, but certainly a slight modernization could be done without that.

Suggestions (which shouldn't cause performance issues):

* Flat UI option (*can be disabled by people who want to look like they're running Windows 95*)
* Updated toolbar icons (a contest might see some great submissions)
* Dark mode (*can be disabled by people who want to look like they're running Windows 95*)
* New Styles
   - Updated/modernized Stylers.xml
   - Classic.xml (*for the people who want to look like they're running Windows 95*)
   - Dark.xml (a dark version of the "updated/modernized" version)

**Comment by aplocher** [comment]
@sasumner I haven't done much cpp dev in quite some time, but I may take a crack at it in the coming days... :)
