### ISSUE TITLE
Modification for read only files

### ISSUE THREAD

**Issue by TomB2** [notepad-plus-plus/notepad-plus-plus#4699]
### Description of the Issue
Read only files can not be changed in editor

### Steps to Reproduce the Issue

1. Open a read only file e.g. Outlook attachment
2. Try to modify it

### Expected Behavior

Content should be changeable in editor. Save button must be disabled or automatically invoke SaveAs
or ask to overwrite.

### Actual Behavior

No changes are possible. This is really annoying if you want to e.g. format xml or add a note in a log file.
Currently you always have to click on Edit --> Remove read only attribute

**Comment by sasumner** [comment]
I think it is better with the existing functionality.  You know immediately when you try to change something that the original file isn't going to be savable (say the file is beyond your control--it has to be named what it is, and it has to be in the folder it is in).  That way you don't *think* that your changes are going to be accepted, and spend time making edits, only to find you've wasted your efforts.

I don't know if making one quick menu selection (the one you mentioned) qualifies as "really annoying".  But I suppose YMMV.

My opinions only...don't take offense...I'm not trying to lessen your feature request.

[And BTW, you can script something to solve this "problem"...have your desired solution TODAY instead of having to wait for it to even be considered...]

**Comment by netpog** [comment]
In every other editor, you're allowed to edit the read-only file, but your efforts are not wasted.  Instead, your "save" command is answered with the "save as" dialog.  

In that way, a read-only file is exactly like a template (e.g. in MS-Office), which is an excellent reason to have them around.

Naive users are given no indication as to what's going on; they simply can't make edits.  And they are expected to (1) figure out why they can't type, and (2) that they must use the menu to invoke save-as, to get past this hurdle.    (Whereas those of us who save using ctrl-S, in every context, don't automatically open a menu to save a thing, ever.)

And I'd no idea until this moment that you could manage file attributes within NPP. (Cool!)

In the peculiar use case where you must have that filename in that location, you can surely save your work elsewhere, and then copy into the (resistant) target location.  MS-Windows makes you do this constantly, when trying to change things in start menus or in Program Files. 

(I refer to the Windows message that reads: "Please save this to your desktop before you then move it to the desired location, so that you can show proper respect and give full consideration to our operating system's majesty, and only then will your desires be acknowledged.")

**Comment by netpog** [comment]
I filed a new issue (#5334) in order to provide more detail, including a more-explicit listing of the behaviors in question.  If this wasn't the right thing to do, then please forgive;  I'm new to this community.

**Comment by fml2** [comment]
I also think that files with read only attribute in the file system should be editable in NP++ (but then only savable under other name).

Another issue in NP++ (IMO) is that the menu entries "Set Read-Only" and "Clear Read-Only Flag" are named very similarly but do quite different things. The former changes the _status of the buffer_ while the latter changes the _attribute of the file_.

**Comment by sasumner** [comment]
@fml2 
>Another issue in NP++...

Yes, but since this is an "issues" list, you should have not mentioned that here, but rather created a new issue or found that issue as existing (hard to believe that it wouldn't already exist! :) ) and added your opinion there.  No worries, but that would have been the best way to have your "vote counted". Cheers. :)

**Comment by MetaChuh** [comment]
@TomB2 

please choose `save as` for a read only file before editing, and save it with a different name if the location is writable, or to a different location, if the current account has no write permissions on that folder.

this behaviour is by design, to prevent editing, and only noticing that it can't be saved to the original location, at the end.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
