### ISSUE TITLE
Clipboard text is not pasted correctly into Notepad++ when copied from specific text file.

### ISSUE THREAD

**Issue by mdell-seradex** [notepad-plus-plus/notepad-plus-plus#4736]
When copying the text from a specific file and pasting it into Notepad++ all line breaks are doubled.

### Steps to Reproduce the Issue
1.  Open attached text file in Notepad (Note that I also attached the text file in a zip in case the upload somehow modified the file)
2.  Copy Text
3.  Paste into Notepad++

### Expected Behavior
The same number of line breaks should exist in the pasted text as in the original file.

### Actual Behavior
All (or if not then most) line breaks are doubled.

### Debug Information
Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)

Plugins : ActiveX.dll PluginManager.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

[New Text Document.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2255380/New.Text.Document.txt)
[New Text Document.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2255384/New.Text.Document.zip)

**Comment by dinkumoil** [comment]
The content of your file is ill-crafted.

When you configure Notepad++ to show also control characters

![grafik](https://user-images.githubusercontent.com/24699812/43616977-7e7b57e6-96bf-11e8-8a33-64675a343275.png)

you can see the following:

![grafik](https://user-images.githubusercontent.com/24699812/43616989-8d1da18c-96bf-11e8-935e-be18d63fe587.png)

I guess the content of your file was produced by pressing CTRL+C when a message box displayed by a particular software was the active window. The middle part (between the two minus sign framed blocks) is the content of the message box and as such has been generated by the software.

In the second picture you can see that all lines of the message text are terminated with a CR (carriage return) sign followed by a CR+LF (carriage return + line feed). CR is the line break symbol in Macintosh format and CR+LF is the line break symbol in Windows format. Since Notepad++ is able to interprete both line break formats it does simply what it is expected to do - it generates line breaks.

So it's not a problem of Notepad++, it's a problem of the software generating the message box content since it fills in line breaks in an illegal format. The Windows MessageBox function used to display the original message box is tolerant about illegal line breaks thus you don't see them.

**Comment by mdell-seradex** [comment]
That is interesting.  I do not get the same results when I view special characters using the toolbar button.
Yes, it did come from a copied message box (the .NET MessageBox.Show method in my own application)
I have attached my screenshot to show you how it looks for me.
Notepad does not display the extra carriage returns.

![image](https://user-images.githubusercontent.com/40300659/43617492-579125cc-9690-11e8-836b-c9faff025f27.png)

**Comment by mdell-seradex** [comment]
Do you mean that Windows Notepad is eating a carriage return when displaying the text file because of the "CR" before it, but it still allows copying it?

**Comment by dinkumoil** [comment]
> Please keep in mind that I did not open the file in Notepad++. Instead, I opened it in Windows Notepad and copied the contents which I then pasted into Notepad++.

If I do the same I get the same result like you.

> Do you mean that Windows Notepad is eating a carriage return when displaying the text file because of the "CR" before it, but it still allows copying it?

CR is not a valid Windows line break symbol, so yes, Notepad eats it when displaying the text file. But when the content of the Notepad window is copied to the clipboard there seems to happen some kind of conversion CR -> CR+LF. I don't know who is responsible for that - Notepad by itself or the Windows clipboard routines.

If you open your text file in a hex editor you can see that its content is exactly like it's shown in my second picture above.

**Comment by sasumner** [comment]
If you open this ill-crafted file with Notepad++, the inconsistent line-endings will remain.  If you use the clipboard to copy its data from somewhere else (e.g. notepad.exe), Scintilla will intercept the paste and will convert all different line-endings to the current line ending type that Notepad++ is using for the current file (see the right side of the status bar).  Because it really doesn't know (and really can't know) what the user wants it to do with oddball line-endings, you get the conversion you see. The moral of the story is don't mix line-endings in your data...only bad things result from this.

**Comment by dinkumoil** [comment]
@sasumner 

> Scintilla will intercept the paste and will convert all different line-endings to the current line ending type

Thanks for clarification.

**Comment by mdell-seradex** [comment]
Ok so part of the issue is copying text from the .NET message box.   Either it copies incorrectly or Microsoft is generating it incorrectly.
But to me it seems that part of the problem is that Scintilla is converting the bad line endings instead of dropping them (the additional CR).
I believe that there should be a way to keep these two visually the same.  (This is the file open in notepad & I copy this text).  I think that for the normal user, copying this (see image) to get the result above in Notepad++ appears to be a failure in the copy/paste operation.
![image](https://user-images.githubusercontent.com/40300659/43663595-106cfce0-9738-11e8-9ddd-60e377b9b608.png)

Can't there be a setting somehow to control this?  Perhaps in a "Paste Special" action.  I would think that the default Paste action should be to drop standalone "CR" entries when "EOL Conversion" is set to "Windows" and to allow "Paste Special" to include them and/or convert them.
I would think many users would consider the current behaviour where I don't get what I see as wrong.

By the way, I appreciate all of your feedback.
Thank you so much for the understanding and helpful information.

**Comment by sasumner** [comment]
The way it is handled now follows the default Scintilla model.  The easiest way for Notepad++ to handle editing behavior is to turn it over to Scintilla and let it do what it does.  This is not to say that more Notepad++ code could not be written to deal with the situation.  BTW, I tried this in SciTE (Scintilla's demo editor) and it is the same as in Notepad++ (which I totally expected).

It would probably be tough to decide on something to please everyone for the default paste action.  Sure, from your example you know what you would like, and that is to drop standalone CR...but does that please everyone all the time?  Tough call.

At least Scintilla's paste UNIFIES what could have been real line-endings in source text.  Much better than pasting mismatched line-endings that the user wouldn't know about unless visible line-endings are turned on--something I suspect few users do because they are "visually heavy".

It is sort of an interesting situation.  Where you say "where they don't get what they see...is wrong", that is interesting because to "see" something depends upon how one thing showed it to you; who's to say that whatever did the original displaying is correct? :)

Another interesting tidbit is that the original data is generated by some .NET thing, which means Micro$oft.  As crazy historically as the line-ending thing has been, you'd think that something from M$ would definitely not produce anything but CR+LF as line-endings--seems like that would be blasphemous.

Good rousing discussion about this, though!  All opinions heard and appreciated.  Nice.

**Comment by dinkumoil** [comment]
@mdell-seradex  Windows Notepad and MS Word don't support Macintosh-style line breaks (single CR chars) but Notepad++ does. That's the reason why Npp processes them and converts them to the format used for the current file. As @sasumner already wrote Notepad++ can not predict if it makes sense to do that conversion in a certain situation.

**Comment by mdell-seradex** [comment]
I understand that.
It just seems to me that when I am running Notepad++ on Windows in Windows Line End (CR/LF) mode that its normal behaviour should be to only pay attention to normal Windows line breaks (CR/LF).
This could be something controlled by a preference.  It seems like that would be the desired way to deal with this since it seems like some people have concerns with this.

**Comment by mdell-seradex** [comment]
Is there any thoughts as to making this controllable in the future via an option/setting to allow each user to make their own decision about this behaviour?

**Comment by sasumner** [comment]
@mdell-seradex If it bothers you a lot, you could probably "script" something that would resolve it for you.

**Comment by mdell-seradex** [comment]
I am not sure how I could because once it is pasted into Notepad++, it has already been converted.

**Comment by sasumner** [comment]
A script could read the clipboard for its data, filter that content as desired, and then insert (not paste) the filtered result into the editor buffer.  Perhaps it gets a bit complicated, but I think definitely doable.

**Comment by mdell-seradex** [comment]
Notepad++ scripts can interact with the clipboard?  I had no idea.  It seems like it would probably not be a simple task, but since I am unfamiliar with the scripting language Notepad++ uses, it would probably require extra time to ramp up... :)
Thankfully this hasn't really been an issue for me since I first logged it, one that re-occurred that is.

It just seems to me that scintilla is making some decisions for me that it should not.
Instead it should provide the user with the ability to change that behaviour to something that is more desirable based on the situation they are currently in.

I thought that perhaps since this is still marked as "Open", then it might be available for future consideration for improvement, however, I have seen no evidence of that either.  If not then I would have expected someone to close it as "Won't Fix". :)

At least I know now why it occurred.  Also, I want to thank you for responding to an older thread.  Some other sites seem to abandon threads that are more than a few days old.

I appreciate your feedback on this and look forward to any further insight.

**Comment by sasumner** [comment]
What I use for scripting is the Pythonscript plugin.  This plugin's built-in clipboard handling is admittedly a bit weak (see my request for improvement here: https://github.com/bruderstein/PythonScript/issues/106).  Luckily, Python provides something called "ctypes" so one can call low-level clipboard routines (e.g. https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getclipboarddata)/ directly from Python.

So basically via a script you could obtain the data in the clipboard (with its line-endings intact), put it in a Python string variable, do what you want with that variable (after maybe prompting the user for what THEY want to do when weird line-endings are encountered), and then insert modified (or unmodified) text (from that variable) into the Notepad++ doc at the current caret point.  In your case you might want to give the user 3 choices (add it "as is", drop the oddball line endings, or correct them before insertion...oh, yea, and maybe a 4th choice: cancel).

If you are interested in implementing this I can certainly provide answers to questions you might have during it...just let me know.  Probably not difficult; probably all the code to do it would fit on screen in a N++ window.

Quite often issues remain open for a long time with no action.  I wouldn't read anything into that.  Sometimes issues are rejected, but often most just languish in the open state.

**Comment by sasumner** [comment]
Scripting a solution is easier than what I made it sound like above.  Scintilla has a function to directly control this:

https://www.scintilla.org/ScintillaDoc.html#SCI_SETPASTECONVERTENDINGS

Thus in, for example, Pythonscript, it becomes as easy as a single call:  `editor.setPasteConvertEndings(False)`

It seems like it could also be accomplished with the NppExec plugin or LuaScript with an equivalent call.

Due to this, and long period of inactivity, I'm closing this issue.

**Comment by dinkumoil** [comment]
_NppExec_ plugin: `sci_sendmsg SCI_SETPASTECONVERTENDINGS 0`
_LuaScript_ plugin: `editor.PasteConvertEndings = false`

**Comment by mdell-seradex** [comment]
> Scripting a solution is easier than what I made it sound like above.  Scintilla has a function to directly control this:
> https://www.scintilla.org/ScintillaDoc.html#SCI_SETPASTECONVERTENDINGS
> Thus in, for example, Pythonscript, it becomes as easy as a single call:  editor.setPasteConvertEndings(False)
> It seems like it could also be accomplished with the NppExec plugin or LuaScript with an equivalent call.
> Due to this, and long period of inactivity, I'm closing this issue.

If it is as easy as you say then it should be simple to add an option/setting to turn this on/off.
I still think this would be a good idea, but thank you for providing me with this information.  Hopefully others will find it useful as well.
I would love to read in the help documentation how to do this, but I cannot find it currently.

**Comment by sasumner** [comment]
>Can't there be a setting somehow to control this? Perhaps in a "Paste Special" action.

Haha, there is!  I'm surprised this wasn't mentioned earlier in this issue thread.  If one does `Edit` (menu) -> `Paste Special` -> `Paste Binary Content`, then mixed-line-endings get pasted without "mangling".  Perhaps this satisfies?

>If it is as easy as you say then it should be simple to add an option/setting to turn this on/off.

It is easy to *script* an add-on solution that individual users can take advantage of.  Adding an option/setting into N++ core speaks more to the desire of developers to do it, how many users would need it, translation of setting text into many languages, and other such concerns that often get glossed over in an "it's easy" statement.

>I would love to read in the help documentation how to do this, but I cannot find it currently.

Not sure what this means, I pointed to the Scintilla docs earlier; the extent of the Pythonscript docs for it look like this:

![image](https://user-images.githubusercontent.com/30118311/62948616-b4ffc480-bdb2-11e9-8c2b-32ffd15e98b0.png)

...but maybe you meant something else?

**Comment by mdell-seradex** [comment]
Thank you very much for the information @sasumner.  It is greatly appreciated.  I believe that "Paste Binary Content" will be very helpful in the future.  It is unfortunate that I need to go that route just to stop the line ending conversions, but it is also unfortunate that these extra characters are added via the .NET Messagebox class! Thankfully, this workaround is not a massive hardship :smiley:.

You are correct in regards to the "simple" comment.  It seems to me that the number one thing preventing this would be asking if it is worth the time to add this when all the translations would need to be created for it and few appear to be requesting this.  Being a developer myself, I can understand that could be enough to prevent adding this, although I do not deal in multi-language applications.  Being that this specifically is only an on/off flag, I'm unsure what other concerns there would be, but that can definitely come into play in other so-called "easy" scenarios.

In regards to the help documentation, I was speaking about Notepad++.  I have no idea how to create a plugin/script/whatever it is for it.  There used to be some documentation on Notepad++, but it appears to have been taken down.  I think it would be nicer for me if I could figure out how to create a plugin (Npp/Lua/other) that runs on start of Notepad++ and turns the PasteConvertEndings flag off, but I can live with the Paste Binary for now.

Thank you again for your responses @sasumner.

**Comment by dinkumoil** [comment]
@mdell-seradex 

It seems you misunderstood something. You don't need to

> create a plugin (Npp/Lua/other)

You only need to install a **scripting plugin**, i.e. a plugin that provides a programming interface to Notepad++ and its features and allows to write code in a certain programming language to use that interface.

Currently there are the following plugins of this kind available:

* _NppExec_ plugin (mostly low-level scripting by sending events, custom language, 64 bit version available)
* _Python Script_ plugin (scripting in Python)
* _LuaScript_ plugin (scripting in Lua, 64 bit version available)
* _Automation Scripts_ plugin plus _CS-Script_ plugin (scripting in C#)
* _jN Notepad++ Plugin_ (scripting in JavaScript, 64 bit version available)

At least the first 3 of this list (I haven't tested the other 2) provide the ability to define a startup script that is executed every time Notepad++ starts up. That's the place where you can integrate an one-liner script to deactivate EOL conversion on paste operations.

**Comment by sasumner** [comment]
...or, you could just define a new shortcut using Shortcut Mapper for `Paste Binary Content`.  Maybe Shift+Ctrl+v ?  Then, the only pain is in remembering to add the Shift key into the Ctrl+v when you absolutely need this functionality.

Anyway, it seems there are several options open to you, @mdell-seradex  :)

**Comment by mdell-seradex** [comment]
Actually, I was able to use Shortcut Mapper to remap Ctrl-V to `Paste Binary Content`.  That was very helpful.  I left Shift-Ins to `Scintilla-Paste`.
It would be nice to learn how to create plugins, but I guess it isn't required anymore.
I don't know, but I'd hope those plugins you mention have some documentation on how to use them.
I am used to other software that have their own built-in scripting language (VBA and wscript are obvious examples) where you add a script or specify a script file so I blame my misunderstanding on that. :slightly_smiling_face:

Thank you so much for the new info.  I greatly appreciate all the time you have spent on this.

**Comment by sasumner** [comment]
@mdell-seradex 

Yes, everything has documentation; often it is better than Notepad++'s.

For LuaScript, see https://github.com/dail8859/LuaScript (info on how to install and use is, well, right there).

For NppExec's latest release, see https://github.com/d0vgan/nppexec/releases/tag/v06-RC3 (I believe a manual is found inside the release).

For PythonScript, see https://github.com/bruderstein/PythonScript and http://npppythonscript.sourceforge.net/ , especially the latter link's `documentation` area.  There is more documentation once you have PythonScript successfully installed, the best IMO being context-sensitive help -- put your caret on an `editor.` or `notepad.` object function name, invoke context-help, and bam...help is there.  A bit unfortunately, Pythonscript is in a bit of a bad state maintenance-wise at the moment.  It fully works, but installation is a bit obscure.

I don't have enough familiarity with the other 2 scripting plugins that were mentioned earlier by @dinkumoil , so I can't comment on location of their documentation with any certainty.

**Comment by dinkumoil** [comment]
@mdell-seradex 

I wrote a plugin that can turn off EOL conversion when pasting (and some other things). Its name is _ExtSettings_. You can download it [>>> here <<<](https://sourceforge.net/projects/extsettings/). It will also be available soon via _PluginsAdmin_.
