### ISSUE TITLE
Page header and footer preferences do not set properly

### ISSUE THREAD

**Issue by StevenLStiff** [notepad-plus-plus/notepad-plus-plus#4749]
### Description of the Issue
Notepad++ version 7.5.8 (32-bit)

When printing a file, the page header and page footer do not print as set in **Settings / Preferences / Print**.

### Expected Behavior & Actual Behavior
When **bold** is checked, the output prints in italics; applies to both header and footer.
When **italics** is checked, the output does not print in italics; applies to both header and footer.
It is not possible to set the header and footer to **bold**.

**Comment by lscorcia** [comment]
I experienced this issue today and had a look at the code. From a quick glance it looks like a typo in 
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/ef13902206f80e00dcfd7d85b342066ed6f86d66/PowerEditor/src/ScitillaComponent/Printer.cpp at lines 147-148 and 167-168. The parenthesis are on the wrong side of the ternary operator, assigning unpredictable result to the variables fontWeight and isFontItalic .

Unfortunately I don't have a build environment available, so someone else should step in and provide a merge request. Hope it gets fixed in the next release!
