### ISSUE TITLE
Regex lookahead causes entire file to be selected

### ISSUE THREAD

**Issue by MadSpaniard** [notepad-plus-plus/notepad-plus-plus#4761]
### Description of the Issue
Notepad++ erroneously selects the entire file when searching using a regex that includes a lookahead that scans over 1000+ lines to determine a match.

For example, the following regex will select the entire file when the amount of text traversed in order to find the next successful match exceeds approx. ~1000 lines:

\<record\>((?!\</record\>).)\*?text-string-to-find.\*?\</record\>

Basically, there seems to be a limit or constraint in how far ahead notepad++ can traverse when searching with a regex that includes a lookahead.  When it exceeds that limit, notepad++ selects the entire file.

### Steps to Reproduce the Issue
1.  To illustrate, consider a long XML file with hundreds or thousands of multi-line "records" (e.g. 10-50 lines per record) defined between opening/closing \<record\>/\</record\> tags.  Some of these records contain a particular "text-string-to-find", others do not.
2.  Search the records file using the regex above, and hit Find Next repeatedly to traverse the matches.
3.  The regex above is trying to match records that contain "text-string-to-find".  The negative lookahead ensures that we don't return matches that span multiple records when doing a Find Next from the current cursor position in the file.

### Expected Behavior
The regex should match the entire text between (and including) the opening/closing record tags for only those records that contain "text-string-to-find".  It should match from the opening "\<record\>" through the closing "\</record\>" tag for each such record.  Each "find next" should find and select the entire text of the next record that contains the string.

### Actual Behavior
1.  If the # of lines between one match and the next match is large, i.e. greater than approx. 1000 lines, then upon "find next" notepad++ erroneously selects the entire file, rather than properly finding and selecting the very next match. 
2.  However, if the # of lines between matches is small, i.e. approx. 50-200 lines, then notepad++ properly finds and matches only the records that contain "text-string-to-find".  The match is limited to a single record (and does not span across multiple records).  
3.  If there are no matches at all in the entire file (i.e. no records contain "text-string-to-find"), notepad++ selects the entire file when it should select nothing.
4.  In summary:  "find next" works if the number of lines to the next match is small, but selects the entire file if the number of lines to the next match is fairly large (approx. > 1000 or so).

### Related Issue & Other Info
This may be related to Issue #683 .

**Comment by ClaudiaFrank** [comment]
Note sure if you can blame npp for doing possible catastrophic backtrcking regexex.
It would be nice if npp would throw an error instead of selecting everything but the regex itself
should be changed imho, although not an regex expert at all.

I guess this one does what you want.

`(?is)<record>(?>(?!</record>).)*?text-string-to-find.*?</record>`

**Comment by ClaudiaFrank** [comment]
Looks like I haven't made myself clear - I absolutely agree that in case of an error, like a stack overflow, 
npp should return an error instead of matching the whole text - that is definitely a misbehavior of npp.

It was about "your expected behavior" that the regex should match, even in such cases,
which led me to propose another regex solution, but now I see that your concern is the same as mine.
Npp needs to take care that errors like stack overflows can happen and should not result in returning 
the whole document as the only match.

Sorry for confusion.

**Comment by ClaudiaFrank** [comment]
What I found out so far - an exception is thrown but searchInTarget function returns 0, which is, of ourse,
a valid position aka the first position in a document. 
One possible solution might be to call [SCI_GETSTATUS](https://www.scintilla.org/ScintillaDoc.html#SCI_GETSTATUS) because this is set to1 in this case.

**Comment by thatgdfox** [comment]
Hi. I also encountered this issue, so I thought I'd pass along what I found in case it's useful. I'm using a negative lookahead:
^(.(?!zyx))*
I'm attaching a file that I created to test. I found this expression works fine on lines up to 19,988 characters long (including cr & lf), but when npp attempts to apply this expression to the line with 19,989 characters, it returns the entire file as a match. Note that is also affects the results you get when you click the Count button; it returns a count of 6, but it should return a count of 7.
[Line with 19989 chars causes neg lookahead to fail.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2393675/Line.with.19989.chars.causes.neg.lookahead.to.fail.txt)
![notepad _2018-09-18_12-22-42](https://user-images.githubusercontent.com/43141698/45702493-f9052d80-bb3f-11e8-912c-a303c45e013d.png)

**Comment by patrickdrd** [comment]
I've encountered it yesterday too, please fix

**Comment by neffmallon** [comment]
This happens without lookarounds as well. I have a csv that is 134MB but only 1600 lines and consists entirely of single digit numbers (mostly 0 and 1) and commas. Searching for ,[23456789], selects the entire document. Likewise, doing a replace all on (0,)+ to nothing replaces one instances and clicking the Replace All button again causes the program to say there were 0 matches. However, Replace still replaces the next matching string.

**Comment by sasumner** [comment]
@neffmallon What is happening is that the regular expression engine is being overwhelmed and it coughs up an error but apparently Notepad++ is ignoring that error in an interesting way. See @ClaudiaFrank 's comments above.

**Comment by sasumner** [comment]
A fairly simple scenario that replicates this issue is taken from here:  https://www.regular-expressions.info/catastrophic.html :

In Notepad++, create a file tab containing:

    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    zzzzzzzzzzzzzzzzzzzzzzzzzzzzzz

Do a regular expression search for `(x+x+)+y` via a `Find All in Current Document`.  After a bit of time where the `Find what` window is empty (Notepad++ is doing some big-thinking), it should "come back" having found 1-hit-in-1-file.  Trouble is immediately apparent as we observe line # 1 with a bunch of `a`'s being hit.  Double-clicking the hit line in Find-result window will result in the entire file contents being selected.

Note, I'm sure other, less lengthy variants of the file contents will also show the bug.  The intent here wasn't to find the shortest thing, but rather a _simple_ bit of data.  Hopefully any others that try this scenario will also get my observed behavior.

**Comment by sasumner** [comment]
This commit: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/926e6e97d82b3d63103cb2297b372af5cd469ca6
will close this issue as fixed.
