### ISSUE TITLE
Blink Compare

### ISSUE THREAD

**Issue by nelsontx** [notepad-plus-plus/notepad-plus-plus#4783]
Suggest a blink compare mode.  
### Description of the Issue

A blink compare mode would be useful.  
Make only one view visible.  Provide a shortcut to switch between views. 
This kind of compare makes it easy to find small differences in dense text.

(If there is already a way to do this, I could not find it)
### Steps to Reproduce the Issue

1. Open two similar files in different views
2. Change to single view.
3. Switch between views.  Anny differences naturally "pop out" visually.

### Expected Behavior

N/A
### Actual Behavior

N/A
### Debug Information

N/A

**Comment by DavidHansen-0x454d43** [comment]
@nelsontx I think the [Compare plugin](https://github.com/pnedev/compare-plugin) may do what you require, since it highlights character differences.

**Comment by nelsontx** [comment]
Well, yes and no.  Certainly, the compare plugin shows differences and it is often the best tool for the job.  But, what I describe is similar to what astronomers used to detect object movement.  By rapidly switching between pictures, objects that had moved relative to the background stars would "pop out" visually.  It is a great technique for detecting small changes.  I'm not suggesting it as a compare plugin replacement, but as another tool in the compare arsenal.

**Comment by nelsontx** [comment]
You don't have to scan for the differences.  The point of a blink compartor is that your eye picks them up automatically.  They just "pop out" at you.

No need to sync lines either.  Blink between and your eyes go, "Aha!  There are added lines here".

What more can I say.  For sure blink compare is not as sophisticated or capable as traditional compare.  But, sometimes it's just the thing for a quick, "I know there's something different, what is it?"

**Comment by DavidHansen-0x454d43** [comment]
There needs to be _some_ kind of syncing, otherwise you go to page 2 on your first document, and your second document is still on page 1... then all you see is changes. 

You run into a similar problem with added/removed lines. Say you're looking at line 1000 in document one, but your second document has 50 lines removed somewhere before line 1000. You can't just blink to line 1000 in document two because the two views will look _completely different_... and you won't know which document has added or removed lines. 

So this feature would need to have some kind of syncing, otherwise your two views have no similarities and they become useless for detecting changes.

**Comment by MetaChuh** [comment]
@nelsontx 

many thanks for your feature ideas.

while this idea might be an interesting task for an external plugin, it will not be implemented at the notepad++ core.

thank you for your help and best regards.
