### ISSUE TITLE
Function List functionality has changed

### ISSUE THREAD

**Issue by stepher1** [notepad-plus-plus/notepad-plus-plus#4811]
### Description of the Issue

In Function List used to be able to click on a label once, pause, then click a 2nd time which allowed a copy/paste for copying a label (or parts of it) into the main code. Now that "feature" no longer works.

### Steps to Reproduce the Issue

1. Click once on label in Function List, label is "highlighted" (reverse color (white on blue on my system))
2. Pause
3. Click 2nd time on same label and label, or parts of it, should be able to be copied, but is not. It remains "locked"

### Expected Behavior

Label is "unlocked" and placed in a copy-able mode

### Actual Behavior

Label is highlighted after 1st click, as expected. After 2nd click, label remains highlighted and locked

### Debug Information

Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : CustomizeToolbar.dll DSpellCheck.dll Explorer.dll FunctionList.dll HexEditor.dll mimeTools.dll NppCalc.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll PyNPP.dll PythonScript.dll 

NOTE: This problem 1st occurred in V7.56 (was not an issue in V7.55 and previous versions)

I discovered this issue coding in assembly language. I have not yet tried to use it coding in C++, but just checked and behavior is the same.

Community discussion link:  https://notepad-plus-plus.org/community/topic/16226/function-list-change

**Comment by susantruong** [comment]
@stepher1 Hi, I want to work on this issue, but I am not sure if I can fix it. Would you please assign it to me? I want to get one pull request of my 5 needed pull requests for this month. After 31-Oct-18, if I still can not fix it, I will let you know. 
First, I forked and cloned the code to my local machine. Is it the newest version? (Notepad++ v7.5.8 (32-bit)). As you said, this problem was not an issue in V7.55 and previous versions. Would you please show me how I can get either V7.55 code or previous versions code? I want to compare code to see how someone changed the code and start to work on this issue.
Many thanks for your help!!! :)

**Comment by sasumner** [comment]
@susantruong , @stepher1 maybe just reported the bug, probably cannot answer the types of questions you asked.  If you forked/cloned the code, you have the newest version (it isn't 7.5.8 or any named/numbered version, it is just the "head"revision).  This problem surfaced in version 7.5.6 so you could grab the source for 7.5.5 and 7.5.6 and compare them.  One way to do this is to get them via the download page (https://notepad-plus-plus.org/download)--there's a link to download the source on a per-version basis.  I think there might be a clue to what changed for the function list in the change notes for 7.5.6:  "Function List enhancement: Highlight the current function based on cursor position."  So, we see that some work was done in the function list area; it probably messed with the functionality that @stepher1  was used to and is complaining about in this bug report.

**Comment by stepher1** [comment]
@sasumner - I should have cc'd the right emails. Apologies. Here is my 
note back to Susan (some of which you have echoed in your email to her):

Hi Susan,

   I'm glad, and truly appreciate, you (or, at least, someone) have 
taken an interest in this. However, it's not clear I have any authority 
to authorize anyone to do anything about this. My sense is it comes from 
someone/somewhere else. I'm only a user (and wanna be coder :)

   As for V7.5.5....if you go to the website 
(https://notepad-plus-plus.org/) just left of the "About" column is a 
list of versions back to 7.5(0?). Click on the Notepad++ 7.5.5 released 
<https://notepad-plus-plus.org/news/notepad-7.5.5-released.html> link 
(or this link might work :) and it should take you to the download page 
for both binaries and source. BTW - newest version from a few days ago 
is 7.5.9. (you should see that at the top).

   If anyone should be appreciative for someone's help, it would be me 
(and a few other people who noticed this change) of yours for stepping 
up to take this on. I hope you can solve this becuz I miss this "feature".

   Thanks again and cheers....Steph R.

**Comment by susantruong** [comment]
@sasumner Thank you for your response. Would you please show me how I can get a list of changed notes for each release? (file name, what someone changed, issue number). Or would you please give me the link to the issue someone fixed on "Function List enhancement: Highlight the current function based on cursor position." ? I want to see what he/she changed. Thanks ;)

**Comment by cmeriaux** [comment]
@susantruong  here is the list of every commits between v7.5.5 vs v7.5.6

https://github.com/notepad-plus-plus/notepad-plus-plus/compare/v7.5.5...v7.5.6 

here is the commit of "function list enhancement" 
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a724cc49a663f336b0a124c2a5969c489b70da62

**Comment by susantruong** [comment]
@cmeriaux Thank you so much!
@GaryBloom and @donho Hi Gary, I am working on this issue and maybe it is caused relate to your commit of "function list enhancement"  [`a724cc4`] (https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a724cc49a663f336b0a124c2a5969c489b70da62). I compared your changes and noted that you wrote one line `_treeView.makeLabelEditable(false)` (line 777). I am not sure it is causing @stepher1 's problem, he could not copy the label after the 2nd click. 
You can find more information about this issue in the communication discussion link: https://notepad-plus-plus.org/community/topic/16226/function-list-change
I don't want to break your code because I maybe have some misunderstanding. Would you please kindly give me some suggestion?

**Comment by sasumner** [comment]
@susantruong So if I were you I wouldn't expect or sit around waiting for a response to that.  The way it works is, if you think that line of code is causing a problem, you change it in your local source code sandbox, and you test it to see (a) if the functionality in this current issue is restored, (b) if you break the intended functionality from the "function list enhancement" commit, and (c) that you don't break something else.  If all is good after extensive local testing, you submit it as a pull request...and then you wait to see if it is approved and put into the master branch for subsequent release in a future Notepad++ version.  And...if that one line of code isn't the problem, you go looking for some other cause of it.  Sound difficult?  Yep, software development IS hard.  :-)

**Comment by stepher1** [comment]
Hi,

   Since I'm just a "lowly user", my name can be removed from this 
distribution list. I don't have any need to know what's going on except 
whether or not this "feature" has been restored. And I can find that out 
if/when it appears in a future update.

   Thanks and cheers....

**Comment by sasumner** [comment]
@stepher1 If you mean by "distribution list" the emails you receive from github when someone posts to this thread, then you'll have to turn off github emails globally (drastic) or click the "mute this thread" option in one of the emails (not quite sure if that works if you are the issue creator--like  you are--but it probably does).  But...I'd think you'd want to stay informed (rather than just try the functionality in the future N++ releases...and hoping...).  Since you put "lowly user" in quotes, I went back to see if I used that phrase about you, and I didn't (whew!).

**Comment by stepher1** [comment]
@sasumner

My concern was getting onto some individual's distribution list when I 
really didn't need to be there. Since it's automatic becuz of my posting 
to github, I'll figure out how I want to deal with it. Maybe I will just 
continue to lurk in the background :) Thx.

"Lowly user" was A) my self-deprecating humor (kind of like "I am not 
worthy" and B) to make sure people didn't mistake me for the coder who's 
going to look at the problem I posted. I can code, but this is way 
beyond anything I would be willing, or capable, to take on.

Appreciate the feedback. Cheers and regards.....

**Comment by susantruong** [comment]
@stepher1 @sasummer Sorry, I could not set up environment to build the code in my local machine, so I could not test anything. Also, I have not gotten any answers from @GaryBloom yet. I can not break any code of his functionality that already accepted and merged. Therefore, I will give up this issue and I hope someone else can help you. @stepher1

**Comment by sasumner** [comment]
@susantruong Wow...that effort didn't last long...  :-(

**Comment by stepher1** [comment]
Ahhh...such joy and hope...then gone in moments  :(   So very sad.....

**Comment by stepher1** [comment]
> Meaning what, exactly??
