### ISSUE TITLE
Feature request: Keep unsaved files between sessions

### ISSUE THREAD

**Issue by squelart** [notepad-plus-plus/notepad-plus-plus#4828]
### Description of the Issue
Instead of being forced to save modified files when closing Notepad++, I would like them to just be remembered (silently stored somewhere).

### Steps to Reproduce the Issue
1. Create a new file or modify an existing one.
2. Close Notepad++, or restart Windows.

### Expected Behavior
Notepad++ just closes, no questions asked.
When reopening later on, unsaved files should still be there in the same state I left them in.

### Actual Behavior
Dialog asks "Save file... Yes/No/Cancel".
Note that this blocks Windows from shutting down / restarting.

Implementing this feature would also solve https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4402

### Debug Information
Notepad++ v7.5.8   (64-bit)
Build time : Jul 23 2018 - 02:06:36
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by sasumner** [comment]
I think you can get your desired behavior (I don't use it that way so not 100% sure) by Settings->Preferences->Backup->Session snapshot...->TICK "REMEMBER CURRENT SESSION..." and TICK "ENABLE SESSION SNAPSHOT..."

**Comment by slundahl2** [comment]
I have been using NotePad++ for years and it has had this behavior up until I recently upgraded and I was just looking for why it has changed and how to change it back, if I can.  I have long used new, unsaved "files" as temporary places to store snippets of information between shutdowns of my computer.  These are typically things I don't really want to physically save into a new file but am not yet ready to delete for whatever reason.  I can have quite a number of these open at once.  While poking around in Settings->Preferences, I found the setting on Backup that is "Enable snapshot and periodic backup" which also includes a backup period setting in seconds.  Since I have never had periodic backups on, this is clearly a change made in the behavior.  By using this feature, it may get me back to being able to save unsaved new files between sessions but I would have to be much more careful on existing files to make sure that any changes I make I REALLY want to keep, unless there is an option to discard any changes made when you actively go to save the file with Ctrl-S.   I will experiment with this feature (and I see that while writing this, sasumner has also suggested this setting) but I'd either like the behavior changed back or have the default behavior changed so that new, unsaved files are still saved automatically between sessions and independent of this "Session snapshot..." feature.

**Comment by sasumner** [comment]
@slundahl2 Yea, I think there was an unannounced change in the default setting in a recent version that switched how this worked.  I actually think it is better to have the defaults be the way they are now.  Here's why:  Your description reminds me of many others (that eventually lose data) because they have only one copy of their "important" data.  You did hint that this data is not super-important to you, but perhaps it is more important than you think--consider losing all of it at once--would you miss it?  If so, I would advise always using named files (the TakeNotes plugin can make this super-easy) and back up those files regularly.  Just my 2c, do what you will...  :-)

**Comment by slundahl2** [comment]
Hi!

I totally understand the importance of an autobackup and have used it on
editors that I use for coding in the past.  Like most people, I've
certainly been burned way too many times by forgetting to save (when I
don't have an autosave on) and losing an hour or two of code.  Not fun!

I don't really use NotePad++ for coding, though, and mainly use it as my
default editor for text files of other kinds and use IDE's for coding,
including fixing problems in downloaded extract files that I need to fix
because of some sort of stupid problem on the vendor's extract program in
order for them to be imported into our system.  This is a case where I
REALLY don't want an autosave because I want to make darn sure that I'm
only saving it when I want to save it.  (Yes, making a backup first, is
always a good idea!  :-)  )

Anyway, I do realize that autobackup is generally a very good idea but this
change in the behavior threw me for a loop.

I just tested it more fully with this feature set to ON with both new,
unsaved files and a changed existing file with a test change, and it now
appears that this setting provides exactly the behavior that existed before
and that the only difference is that the new version turned it off.  With
the setting explicitly turned back on, I believe it is back to the way I'm
used to having it.

CRISIS AVERTED!!!!   :-)

(Not really.  It's just a bit annoying to have a behavior change in
something you use every day and then waste time to try to figure it out.)

Thanks for your reply!

**Comment by squelart** [comment]
The session snapshot does what I want, thanks @sasumner . I'm happy to close this issue.

The option should probably be worded differently, as "backup" and "snapshot" feel more like a crash-recovery thing.
Maybe explain what happens with unsaved files. Make it enabled by default. And/or have a separate option nearby about showing the "save?" dialog when closing Notepad++ with unsaved files?
Please open a new issue if you/someone would like that...

**Comment by Fohsap** [comment]
This totally surprised me and pissed me off.  One day I upgraded and lost all of my tabs.  I didn't know where all of the file locations were, and I still have yet to locate many important files.
