### ISSUE TITLE
An alleged BUG in regular expression search

### ISSUE THREAD

**Issue by meirivry** [notepad-plus-plus/notepad-plus-plus#4855]
### Description of the Issue
a regular expression search for '\b' should find a word boundary, however it finds boundary between each individual characters.

### Steps to Reproduce the Issue
1. Type few words like "Hello world!!!".
2. Click CTL-F for search.
3. On the Search Mode select regular expression
4. On the "find what :" field type \b and click "find next" button several times.

### Expected Behavior
It should find the inter-character place before "H" of the "Hello world!!!", the place after the "o", the place before "w" and the place after "d".

### Actual Behavior
It finds all inter-character places.

**Comment by sasumner** [comment]
It hits as you describe because the buffer it searches STARTS (when you Find-Next) at the caret position.  There is NOTHING to the left of the caret position (as far as the search is concerned).  Thus if there is a word character to the right of the caret position when you initiate a search you will get a hit, no matter what you can see to the left.  

So think about your insert caret between the "w" and the "o" in your example.  If you hit Find-Next here, it hits the "o" because there is NOTHING to the left of it (for searching purposes).

I'm not trying to be judge-and-jury on this being correct/incorrect behavior, just providing the WHY for existing behavior.

There is more discussion about this type of behavior here:  https://notepad-plus-plus.org/community/topic/16104/how-to-find-and-highlight-a-specific-occurance-of-a-symbol
