### ISSUE TITLE
Feature request: Clone to new file

### ISSUE THREAD

**Issue by sharuzzaman** [notepad-plus-plus/notepad-plus-plus#4858]
### Description of the Issue
New feature to clone a currently opened file to a new file

### Steps to Reproduce the Issue
1. Open a file
2. Right click - no option to clone to a new file
3. Click "File" menu - no option to clone to a new file

### Expected Behavior
Right click or File menu have option to clone to a new file

### Actual Behavior
No current behaviour. Feature not yet implemented.

### Debug Information
Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll IndentByFold.dll JSMinNPP.dll NppFTP.dll NPPJSONViewer.dll NppTextFX.dll PluginManager.dll Python Indent.dll PythonScript.dll SpellChecker.dll Tidy2.dll XMLTools.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
File -> Save As...
OR
File -> Save A Copy As...

In the event that the "new file" you are talking about is a unsaved file such as "new 2", "new 5", etc., do the following keypresses with your file of origin active:  ctrl+a, ctrl+c, ctrl+n, ctrl+v.  If this need is frequent, record to macro and assign a keycombination to that.

Please close this issue.

**Comment by sasumner** [comment]
@sharuzzaman Developers aren't going to spend time on something like this.  One reason that features like macros (and scripting plugins) exist is to ease the burden on developers for esoteric user needs that users would otherwise ask for as new features.

**Comment by sekkuar** [comment]
You mean this?
![nppp_clone](https://user-images.githubusercontent.com/16503688/46163576-ed151c00-c261-11e8-8c15-5a8b81bc7784.png)

**Comment by sasumner** [comment]
@sekkuar I think the originator's use of "Clone" might be leading you astray (unless I am confused).  Since "clone" already has a use in Notepad++ (the one you show), I think maybe @sharuzzaman could have used "Duplicate" as a better choice (although even that has a definition in Notepad++ -- but maybe one in a different enough context to keep the desired functionality clear).  [Whew!]

**Comment by sekkuar** [comment]
So what he wants is a "ctrl + c" and "ctrl + v" on a single button?
That seems very lazy.

**Comment by sasumner** [comment]
@sekkuar Well I think more accurately it would be double that number of keystrokes: ctrl+a, ctrl+c, ctrl+n, ctrl+v.  But...I pointed out that this could be recorded into a macro which could then be tied to exactly ONE keystroke.  Which would be equivalent to ONE menu command which developers could work hard to implement for the originator.  Which explains why this would never be implemented:  a bunch of work for zero gain.

**Comment by alankilborn** [comment]
@sasumner is right.
Suggest REJECTION and CLOSURE of this item.

**Comment by freezer2022** [comment]
>  alankilborn : but there hasn't been a bunch of "me, too" in this 5 year old issue thread, or any call that I can remember for it on the Notepad++ support community web site.

- then why it is implemented in all internet browsers...
maybe because it looks like a basic useful feature...
- also currently it's 2 users want it vs 3 users don't want it, not so much domination

Anyway, what I don't get, is why some people believe their use of a tool is the only legit one..., 
if they don't want it, doesn't mean it can't be implemented for those who still want it...
