### ISSUE TITLE
Tab dragdrop makes other tabs unusable

### ISSUE THREAD

**Issue by Wurstbrotc4** [notepad-plus-plus/notepad-plus-plus#4885]
### Description of the Issue
Dragging a tab to another position has the effect that other tabs can't be activated by clicking anymore. Additionally, dragging such a tab drags the first one instead (the one that was dragged before).

Without code change, it can either be resolved by closing and restarting the whole program, or by dragging the dragged tab back to its original position.

### Steps to Reproduce the Issue
I can always reproduce it in the latest version (7.5.8), without plugins. It works for me with older 6.x.x versions in the very same environment.

### Expected Behavior
After tab dragging, the tab bar still works 100%

### Pull request will be opened in some minutes...

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/895c315df0c5649bfdf4737472e6937242347358

**Comment by AngryGamer** [comment]
I can't replicate this issue and no debug information is provided. Please provide more information about your setup so that someone can replicate the problem (such as OS, use of a compatibility layer like WINE, etc).

Also does [PR#5792](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5792) impact your problem in anyway?
