### ISSUE TITLE
n++ is blocking the folder although the file has been closed already.

### ISSUE THREAD

**Issue by gooly** [notepad-plus-plus/notepad-plus-plus#489]
Hi,
I (Win7-64, n++ 6.7.9.2) faced this issue several times:
1) I created a folder e.g. "XXX",
2) In that folder I created a txt-file (Win.-Explorer => right mouse menu => new => Textdocument) 
3) I opened it in n++ (Win.-Explorer => right mouse menu => Edit with Notepad++).
4) I changed something, saved it and closed the tab of this file.
5) I am going up and want to rename the folder => not possible folder is in use,  close.. 
6) After I closed n++ I immediately can rename this folder.
May be it's a Win-7 bug?
Thanks !

Rem: It would be nice for any post concerning n++ to have a copy-able line in the little Info or About n++ containing OS and n++ version like in my case: Win7-64, n++ 6.7.9.2?

**Comment by Rikk** [comment]
Are you sure it was being hold in use by N++? Couldn't it be some anti-virus? (these usually causes this kind of trouble)

**Comment by dg9ngf** [comment]
Can't reproduce this either. I tried it in the most likely way (directory follows file; open only a single document) because I know this issue from another text editor. Pleased to see that NPP does not lock the directory.

**Comment by Petewg** [comment]
Hi,
the problem is still there (Np++ 6.92 - Win7 pro Sp1)
and can be reproduced with these steps.

1. Create a folder ->  x:\test
2. Create a .txt file -> test.txt
3. Open the file with Np++
4. Do some editing..
5. Save and **Close** file
6. Try to **delete** `x:\test` folder -> **it fails** with message "The action can’t be completed because the file is open in another program"
7. Close Np++ and repeat step 6. -> **success!** (folder deleted)

 

 

Remarks: 

1. Seems that Np++ "forget" to release **folder** (not file) handle when closing file.
2. There is a [sysinternals](https://technet.microsoft.com/en-us/sysinternals/bb896655.aspx)  utility that shows "which program has a particular file or directory open".  You can use it this way: `handle "test"` and see the result. It clearly states \[notepad++.exe\] (along with explorer.exe)


regards,
