### ISSUE TITLE
File-open dialog: support manually entered wildcard patterns

### ISSUE THREAD

**Issue by qgppl** [notepad-plus-plus/notepad-plus-plus#4923]
### Description of the Issue
File-Open dialog ignores manually entered wildcard patterns

### Steps to Reproduce the Issue
1. File - Open
2. In Filename: enter a wildcard pattern e.g.: "\*abc\*.txt"
3. Press Enter

### Expected Behavior
Dialog stays open, displaying only files which match the entered pattern for further browsing

### Actual Behavior
Dialog closes and all files matching the wildcard filespec are opened as tabs

**Comment by sasumner** [comment]
The "Expected Behavior" as per the above is what happens in 7.5.9 when one has Settings (menu) -> Preferences... -> Default Directory -> Use new style dialog... TICKED.

When this checkbox is UNTICKED, then the "Actual Behavior" above is what occurs (although I'd add to the description so that it reads "Dialog closes and all files matching the wildcard filespec are opened as tabs").
