### ISSUE TITLE
Add the ability to insert time/date stamps to documents without external plugins

### ISSUE THREAD

**Issue by vgturtle127** [notepad-plus-plus/notepad-plus-plus#497]
The title says it all.

Well, except what I'm about to say. :stuck_out_tongue_winking_eye: 

This could be added so that we could time or date our commits, add time/date to journals, add info to version control systems without time/date implementations, etc.

Seems easy enough. I know I keep saying that, but you know. It's not re-writing a PS1 emulator from scratch or anything. :wink: 

Thanks for reading. :smile:

**Comment by Rikk** [comment]
This, #496 and maybe #495 you can solve with TextFX plugin.

**Comment by vgturtle127** [comment]
Yeah, but the TextFX plugin isn't very stable. It keeps crashing Notepad++ on larger projects.

**Comment by dail8859** [comment]
Using the PythonScript plugin is very flexible and can do lots of things like this. Insert date/time, filter characters, convert case, etc. For something that can easily be done with a plugin (and probably only targets a small group of users) I don't see the need to add it to the actual N++ code base. Not meaning at all its not a useful feature in some cases.

**Comment by vgturtle127** [comment]
I suppose, but if the plugin doesn't get updated or if the plugin ever breaks then you would be kind of screwed.

**Comment by dail8859** [comment]
You could say that about any plugin at all...

**Comment by ReflexivR** [comment]
Re: TextFX, there is not a 64 bit version nor a 64 bit version of the python script plugin. So as far as I can tell there is no way to insert date/time on the 64 bit version.

**Comment by MAPJe71** [comment]
@ReflexivR try the LuaScript plugin it's available for 64 bit.

**Comment by dail8859** [comment]
> Since this is a duplicate of #2821 should I close this?

It doesn't really matter.

>  I don't anticipate anybody getting it to work just for timestamp/date functions.

AFAIK the source code isn't available anywhere so it would have to be rewritten from scratch.

> I couldn't get it to work reliably, unfortunately.

What problems did you have exactly? I'm the author of the LuaScript plugin so I'm certainly interested in fixing any bugs you encountered. BTW this is how you'd use the LuaScript plugin to insert a date/time:

```lua
npp.AddShortcut("Insert Curent Date/Time", "Ctrl+Shift+D", function()
	editor:ReplaceSel(os.date("%m/%d/%Y %I:%M:%S"))
end)
```

You can adjust the format and shortcut to your liking.

**Comment by vgturtle127** [comment]
@dail8859 Every time it would paste something, it would just paste an EOL character instead of whatever I wanted it to add.

I was kind of going at the plugin wrong, I thought it was basically a plugin to write plugins in Lua, so I thought I was going to have to go about writing something from scratch. Oops.

**Comment by dail8859** [comment]
> Every time it would paste something, it would just paste an EOL character instead of whatever I wanted it to add.

Very odd for sure, never seen anything like that happen.

> I meant a simple function like this should just be added to the main application instead of put into some plugin.

Probably not as simple as you'd think. Sure, adding a few lines to insert the date/time is easy, however you'd also have to:
- Make it configurable since everyone will probably want a different format
- Add the ability to insert the (a) date, (b) time, and (c) the date + time
- Add some GUI elements so that users can configure it
- Point to documentation somewhere so they know how to use it
- Validate the settings
- Save the settings in XML
- Make the GUI elements translatable

All very doable and in the end I'm sure many users would find it useful, but it takes alot more work than just a simple function.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
