### ISSUE TITLE
Notepad++ cannot be set as the default program for certain file types on Windows 10

### ISSUE THREAD

**Issue by craigstern** [notepad-plus-plus/notepad-plus-plus#4984]
### Description of the Issue
Notepad++ cannot be set as the default program to open certain file types on Windows 10 Home.

### Steps to Reproduce the Issue
1. Attempt to set Notepad++ as the default program to open (for instance) xml files by right-clicking a file of the aforementioned type, selecting Open As, selecting Notepad++, checking the box to always use this program, and clicking Okay.
2. Attempt the same by going into System Settings > Apps > Default Apps >Choose default apps by file type.

### Expected Behavior
The files of the selected type will automatically open with Notepad++ going forward.

### Actual Behavior
The first time I tried it, the system erroneously assigned the files to Microsoft Edge instead. Subsequent attempts produced no change.

### Debug Information
There is an unofficial fork of Notepad++ that fixes this issue. See here: https://superuser.com/questions/1324367/how-can-i-make-notepad-default-program-for-txt-files#comment2056803_1324372

**Comment by TheDarkerPhantom** [comment]
There is a known file association issue, that was introduced in Windows 10 April 2018 Update Build 17134.320 and Windows 10 October 2018 Update Build 17763.55, this issue, by the way, has already been fixed in Windows 10 April 2018 Update Build 17134.441 and Windows 10 October 2018 Update Build  17763.168
