### ISSUE TITLE
7.6.0 plugin migration should be automated

### ISSUE THREAD

**Issue by bughit** [notepad-plus-plus/notepad-plus-plus#5015]
Why ask the user to do it manually?

```
Find the name of plugin you want to migrate in %PROGRAMFILES(x86)%\Notepad++\plugins\myAwesomePlugin.dll (or %PROGRAMFILES%\Notepad++\plugins\myAwesomePlugin.dll, according the achetecture of your Notepad++).
go to %LOCALAPPDATA%\Notepad++\plugins\ to create myAwesomePlugin folder.
move the plungin myAwesomePlugin.dll from %PROGRAMFILES(x86)%\Notepad++\plugins\ to %LOCALAPPDATA%\Notepad++\plugins\myAwesomePlugin\.
That’s it. Restart Notepad++ and you get your beloved plugins back.
```

**Comment by MetaChuh** [comment]
> Why ask the user to do it manually?

because notepad++ is free software and hence we do not have the money nor the wish to hire people that do it for you, so we need your help to do your stuff yourself.

thank you for your help and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
