### ISSUE TITLE
No Plugins load when Notepad++ 7.6 is installed with "Don't use %APPDATA%

### ISSUE THREAD

**Issue by armith** [notepad-plus-plus/notepad-plus-plus#5017]
I have an installed instance of Notepad++ in which it is configured to not use %APPDATA%. When I load Notepad++ I don't even have the Plugins menu.  I know the instructions say simply move the plugins to the %LOCALAPPDATA% folder but that is precisely where I don't want my plugins for this instance.

Steps:
-Install Notepad++ 7.6 and select "Don't use %APPDATA%" option.
-Run Notepad++

no plugins menu
![image](https://user-images.githubusercontent.com/45083707/48590628-40c0ef00-e90e-11e8-98e5-88a0eb80f05d.png)

**Comment by Big--Mike** [comment]
First: *%LocalAppData%*
 is user specific, while *%ProgramFiles%\...* is global for all users on the machine. If you want to deploy a new version, manipulating user configuration folders is ugly and leads to problems.
Also folders in %UserProfile% are meant for the personal user, not for the admin.
Second: %LocalAppData% is for (machine specific) user configuration data, not for binaries. Binaries should be placed in %ProgramFiles% where they are well protected from standard user access (and malware running in default user context).

**Comment by paralaks** [comment]
I noticed updater was not working so I decided to upgrade from 7.5.9 to 7.6 and I have same problem.

**Comment by MetaChuh** [comment]
this has been fixed in newer versions of notepad++.

the "Don't use %APPDATA%" option is now automatically greyed out, if installed at %ProgramFiles%, as it gets in conflict with missing write permissions for this folder.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.6.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
