### ISSUE TITLE
PluginAdmin delete plugin if network not available

### ISSUE THREAD

**Issue by bammab** [notepad-plus-plus/notepad-plus-plus#5019]
### Description of the Issue
If you want to update a plugin and network (internet) is not available, the restart need much time and after it, the plugin is gone.
If the pluginAdmin could not downlod the file, it should abort the process instead of "delete, try download, skip" workflow.

### Steps to Reproduce the Issue
1. Install a fresh npp 7.6
2. Disconnect network or add a wrong route
3. Start npp
4. Start PluginAdmin
5. Select one of the updates and select update (and yes for the dialog)
6. After a few seconds npp starts and the selected plugin is not anymore in the list

### Expected Behavior
If the pluginAdmin could not download the plugin(update) it should skip the whole process.

### Actual Behavior
If the pluginAdmin could not download the plugin(update) it deletes the current version completely.

### Debug Information
(After "update" of the spelling plugin)
Notepad++ v7.6   (64-bit)
Build time : Nov 13 2018 - 00:12:05
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by chcg** [comment]
@bammab Seems you are talking about the builtin pluginAdmin and not the separate plugin pluginManager ( https://github.com/bruderstein/nppPluginManager ) as the pluginManager plugin doesn't appear in your debug info. Is this correct?

**Comment by bammab** [comment]
You are correct! This was a major failure on my side. I'll change the topic.

**Comment by MetaChuh** [comment]
@bammab 

this issue has been fixed in recent versions.

now plugins admin will not delete an older version of a plugin, if the new plugin update has not been downloaded successfully.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html)

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
