### ISSUE TITLE
Any plans to update Spell Checker?

### ISSUE THREAD

**Issue by MurraySobol** [notepad-plus-plus/notepad-plus-plus#5022]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by MurraySobol** [comment]
I noticed that you using this Spell Checker:
![image](https://user-images.githubusercontent.com/40715947/48638051-84166e80-e99d-11e8-8e63-9974f7888872.png)

Any plans on upgrading to use new Windows 10 Spell Check API?
It was introduced in Windows 8.1.
I realize that this would be a problem for user running older versions of Windows.

**Comment by chcg** [comment]
@MurraySobol I think to right place is here https://github.com/Predelnik/DSpellCheck/issues. As the plugin maintainer needs to support this.
From my understanding you are not requesting to bundle the latest release 1.4.8 with N++ version as the title might make one think of first.
Could you confirm that this issue here could be closed in favour of one to dspellcheck?

**Comment by MurraySobol** [comment]
I moved this issue here:
I think to right place is here https://github.com/Predelnik/DSpellCheck/issues. As the plugin maintainer needs to support this.
