### ISSUE TITLE
Plugins not available for standard windows users

### ISSUE THREAD

**Issue by johndoe84329** [notepad-plus-plus/notepad-plus-plus#5026]
### Description of the Issue
There is no Plugins menu in the notepad++ launched from standard user account. As result no ability to start Plugins Admin for installing plugins.

### Steps to Reproduce the Issue

1. Create two accounts in Windows, for example administrator and standard. 
2. Install Notepad++ 7.6 from the administrator's account.
3. Start Notepad++ from standard account.

### Expected Behavior
Plugins should be available to all users, not the one installed the application.

### Actual Behavior
No plugins menu. No standard plugins available that was selected during installation. No way to launch Plugins Admin.

**Comment by sasumner** [comment]
IMO we don't need a bunch of issues logged while the brand-spanking-new Notepad++ plugin stuff is evolving.  Best course of action is to follow/participate in discussions about it on the Community site ( https://notepad-plus-plus.org/community/ ).

**Comment by MetaChuh** [comment]
the issue of a missing plugins menu has been fixed in newer versions of notepad++.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.6.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
