### ISSUE TITLE
TextFX "Line up multiple lines" misaligns when lines contain accented characters

### ISSUE THREAD

**Issue by wgw** [notepad-plus-plus/notepad-plus-plus#5036]
### Description of the Issue

1. Begin with a set of lines, some with no accented characters and some with accented characters
2. Use the "line up multiple lines" function
3. lines are misaligned

### Expected Behavior

Lines aligned

### Actual Behavior

Lines are misaligned

### Debug Information

Start: 

here = example 1
there = example 2
with accents like voilà = example 3
and = example 4
other é = example 5

finish: 

here____________________=_example_1
there___________________=_example_2
with_accents_like_voilà=_example_3
and_____________________=_example_4
other_é________________=_example_5

**Comment by wgw** [comment]
Sorry -- it isn't  in the list of plugins (from plugin manager), so I thought it was built-in.

**Comment by sasumner** [comment]
@wgw It _may_ have been bundled in the past if you are a long-time user...and you have it hanging around because upgrades don't remove existing plugins (well, with the _OLD_ way of doing plugins...).  But still -- not valid to create an issue regarding it on _this_ list.  No worries...no need to be "sorry".

**Comment by chcg** [comment]
@wgw You may want to checkout https://github.com/HQJaTu/NPPTextFX, at least some current development seems to go on there.
