### ISSUE TITLE
[BUG]file open bug

### ISSUE THREAD

**Issue by 2warlord** [notepad-plus-plus/notepad-plus-plus#5041]
### Description of the Issue

NP++ displays file as empty though it is not.
unzip first: [doc.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2599839/doc.zip)

### Debug Information

Notepad++ v7.6   (32-bit)
Build time : Nov 12 2018 - 23:51:42
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows XP (32-bit)
Plugins : none

**Comment by PopeSpaceous** [comment]
Hi, 
I was trying to reproduce your bug. I have unzipped the file and I am getting (when I open the file in NP++) is a comment line: //컴컴컴컴컴
When I open in in any other editor I get: //ÄÄÄÄÄÄÄÄÄÄ
Could you provide any more information on reproducing this issue?
Thanks

**Comment by MetaChuh** [comment]
the file detection system that caused your issue is fixed on notepad++ 7.6.5 and above.

on 7.6.6 your test file will be detected correctly as 14 bytes, 12 chars without line ending and one line ending with cr+lf, in a total of 2 lines.

<img width="269" alt="" src="https://user-images.githubusercontent.com/45773305/57258021-6b893600-705b-11e9-8eaf-a08bbb142556.png">

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.6.

thank you for your help and best regards.
