### ISSUE TITLE
Versão 7.6 - plugins instalados não aparecem na lista de menu

### ISSUE THREAD

**Issue by MarcianoMendes** [notepad-plus-plus/notepad-plus-plus#5047]
### Description of the Issue

Na versão 7.6, plugins instalados, como por exemplo XML Tools, não são apresentados no menu, mesmo estando instalados/reinstalados, tendo que voltar a versão 7.5.9 para normalizar a situação.

### Steps to Reproduce the Issue

1. Acesse o Menu Plugins 
2. Verifique que plugins instalados não estão disponíveis no menu

### Expected Behavior

Apresentar na lista do Menu os plugins instalados

### Actual Behavior

Não apresenta na lista do Menu os plugins instalados

**Comment by chcg** [comment]
In version 7.6, installed plugins, such as XML Tools, do not appear in the menu, even though they are installed / reinstalled, having to go back to version 7.5.9 to normalize the situation.
Steps to Reproduce the Issue

     Access the Plugins Menu

     Make sure that installed plugins are not available in the menu

Expected Behavior

Display installed plugins in the Menu list
Actual Behavior

Does not display installed plugins in the Menu list
