### ISSUE TITLE
Optional auto-reset of 'Find/Replace/Find in Files/Mark' settings

### ISSUE THREAD

**Issue by alexhenzell** [notepad-plus-plus/notepad-plus-plus#506]
It's easy to forget that you changed some of the settings (such as "Match case", "In selection", "Direction") the previous time you were using the 'Find/Replace/Find in Files/Mark' popup, and do something incorrect as a result.

**Possible solution:**

An additional tickbox named something like "Reset settings to default each time popup is opened".

Also:
- The user may want to reset the settings while the popup is open
- The user may want to change the default settings
- It may be worth indicating that settings changes apply to all four tabs (Find, Replace, Find in Files, Mark)

**In total the additions could be:**

Heading text above the settings:

"Settings _(changes apply to all tabs)_"

Options below the settings:

"Reset settings to default" (button)
"Save current settings as default" (button)

"Reset settings to default each time popup is opened" (tickbox)

**Comment by h-h-h-h** [comment]
I think this will clutter the dialog with elements that are less import in my opinion than the ones of issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/452#issuecomment-128483383. However, I don't think this is nonsense. What about this button at the bottom that lets a menu appear that contains the actions and options spoken of?
```
+--------+
| More > |
+--------+
```
It seems appropriate because they are a kind of meta-actions/meta-options.

I guess users would easily find out themselves that the actions and options apply to all tabs, for it's the same with the current options. So, stating this would be cluttering, too, in my opinion.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
