### ISSUE TITLE
Maybe they/he/she should get their own name...

### ISSUE THREAD

**Issue by DanaMW** [notepad-plus-plus/notepad-plus-plus#5060]
https://www.microsoft.com/en-us/p/unofficial-notepad/9plhc123mqwt?activetab=pivot:overviewtab

**Comment by sasumner** [comment]
I think you are 100% correct, but I don't know that it belongs here as an issue! :-)

**Comment by jakevis** [comment]
Known issue.. open to ideas as well @DanaMW 
Also not the only instance... 
https://twitter.com/Notepad_plus/status/992934011533254656
https://snapcraft.io/notepad-plus-plus

**Comment by donho** [comment]
It doesn't bother me the reuse of the name "Notepad++" with "unofficial" term as they don't make pay for users. At least, users know that they download and install Notepad++, and the package is unofficial. And if there's need, why not?

**Comment by sasumner** [comment]
If that's the attitude about it, why not get the damn thing *officially* in the store? Sheesh.

**Comment by Edditoria** [comment]
@sasumner This is part of open source ecosystem. If it doesn't break the license, just let it go.

There are much workload to maintain things on app store. User comments, app ratings, requirements by Microsoft, etc. Believe me. Those works suck. If the development team cannot manage it very well, or don't want to handle problems occurred by app stores. Just don't do it. Focus on the product instead.

**Comment by sasumner** [comment]
@Edditoria I don't like it because, as someone that used to provide Notepad++ support, which product am I supporting?  I have been doing software engineering (all sides of it, in a real sense) for 28 years...as soon as you change one bit of binary, you have a different product.  And it should have a different enough name so that people wanting support on this app store product don't come to the regular Notepad++ sites to get it.  @donho is okay with what has been done with this for the store (see above)...well, that's great, FOR HIM...because he isn't out there providing support for Notepad++ (the evidence for this is his pretty-much zero activity on the official Notepad++ support sites).

**Comment by Edditoria** [comment]
@sasumner I don't like it either. I concern more about security. I will be angry if someone use my codes to do bad things. But developers can't control much once he choose to open source his software on the market. Involving in controls need money and time. Also require a team to handle it. Or, in this case, you will trend to get low rating in the app store.

For example, there is an open source game called Pixel Dungeon. Lots of people put a similar name and "re-release" it. Almost nothing the original developer can really do, even someone put ads or tracking to Android users. I think a different name is much worse than calling an app "Unofficial XXX". At least Unofficial Notepad++ identifies itself.

In fact, the mass market don't care about it.

I am an OEM PC seller and system administrator for many years. I tried to prevent users to download malware. But I finally found that: whatever I do, people, who don't listen and read, just don't care! I am sad with it. I was deeply depressed and saw doctor because of it. And finally, as I said, just let it go.

I'm open to discuss about this topic. May be we should choose another place for discussion because this issue is closed.

**Comment by sasumner** [comment]
@Edditoria Discussions can continue on closed issues...no problem with that.  But I don't know that there really is any more to say.  :-)

**Comment by jakevis** [comment]
@Edditori @sasumner as the publisher on the app store.. I am happy to have a chat with you about how to make this supportable and not raise stress levels...

**Comment by sasumner** [comment]
@jakevis Thanks for the offer.  As I don't do Notepad++ support any longer, it is someone else's problem; it no longer matters to me.
