### ISSUE TITLE
Why still use C-style type casts instead of C++-style?

### ISSUE THREAD

**Issue by MAPJe71** [notepad-plus-plus/notepad-plus-plus#51]
i.e. static_cast, reinterpret_cast, const_cast and dynamic_cast.

**Comment by ariccio** [comment]
...but *how else* are we to [execute floating point arrays](http://www.underhanded-c.org/_page_id_2.html) and dereference `((int*)0)`?!!?!


***Real men*** don't need type safety.

**Comment by ariccio** [comment]
In other words, we should **ban C-style casts.**

**Comment by rcdailey** [comment]
+1

**Comment by NN---** [comment]
@donho What do you think about this ?
Shall we use only C++ casts by convention ?

**Comment by milipili** [comment]
C++style casts promise more security, so it is quite common to recommend them. However, in the real world, you still have to understand properly what you're doing and do not really protect against issues. It is not because your code compiles with a static_cast or a reinterpret_cast that it is correct anyway. Additionally the compiler (especially gcc and clang) may prevent the developer from making casts where it is required (reinterpret_cast is not always strictly equivalent to a c-style cast). Since, c++ style casts are not fully reliable, it can not become a strict rule. As a consequence, it becomes a matter of taste, thus C-style casts like C++style casts are fine to me. However, whatever the type of the cast, it has to be justified.

PS: obviously, I am not talking about dynamic_cast or const_cast here. `const_cast` should not be used from my point of view, as it is often the symptom of a structural issue.

**Comment by NN---** [comment]
You do have better security and if you need more you can do it easily.
Also you can make user defined casts with similar syntax , for instance you can write safe_reinterpret_cast<To, From> which check what size of To and From are the same.
C=style cast is loose cast, it tries static_cast, reinterpret_cast and then const_cast with reinterpret_cast.
Using C++-style cast you do it explicitly thus making intentions more clear.

Take a following example:
With C-style cast you do not have any warning but you definitely have a bug.
With static_cast you get an error:  'static_cast': cannot convert from 'DWORD (__cdecl *)(LPVOID)' to 'LPTHREAD_START_ROUTINE' !

**Comment by milipili** [comment]
As said, nothing will stop you from using c++-style casts for new code if you prefer and if it compiles  :)

**Comment by rcdailey** [comment]
@milipili Hogwash. There is nothing a C++ style cast can't do that a C-style cast can do.

C++ style casts are safer because it makes you choose a specific cast for a specific intent. It makes code more self documenting, safer, more robust, and more type safe. C-Style casts are still in C++ the same reason why structs and everything else are still here: backward compatibility. That doesn't mean you should use them.

Programmers that use C-style casts are just lazy.

**Comment by milipili** [comment]
As *said*, nothing should stop you from using c++-style casts for new code

**Comment by ariccio** [comment]
Speaking of C-Style casts in new code:

https://github.com/notepad-plus-plus/notepad-plus-plus/commit/251e987a715cdb7ff829e23319677e849705a6b8#commitcomment-11559918

**Comment by NN---** [comment]
Current coding style doesn't require you C++ casts only, so now it is a
matter of choice.
