### ISSUE TITLE
Maximised Window on Win10 is 1 pixel too wide

### ISSUE THREAD

**Issue by Kyudos** [notepad-plus-plus/notepad-plus-plus#5102]
On Windows 10 I have three monitors, if I maximise the Notepad++ window on my left-hand monitor, 1 pixel of the window shows on my center monitor. This doesn’t seem to happen from centre to right, or from right to centre.

My centre monitor is 4K on HDMI, left and right are HD on DVI, it that makes any difference.

**Comment by chcg** [comment]
@Kyudos 
With which version of N++ do you observe this?
Is N++ the only program showing this problem?

**Comment by Kyudos** [comment]
This is N++ v7.5.9 (64 bit) and yes, I only see this problem with N++.

**Comment by MetaChuh** [comment]
i can not reproduce this on notepad++ 7.6.6 on windows 10 build 1809 using a variety of retina and standard displays, using e.g. 200% scaling on the main screen, and other scaling factors on the extended screens.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9.

if your fullscreen size is still off by one pixel or more, please right click on your notepad++ icon and select `properties > compatibility > change high dpi settings`, activate `override high dpi scaling behavior` and set `scaling performed by:` to `system (enhanced)` instead of `application`, as seen at the screenshot below.

![Imgur](https://i.imgur.com/qVQ4Bg8.png)

note: you can also choose the `system` scaler, for a classic notepad++ look on scaled displays, which will look like this:

![Imgur](https://i.imgur.com/WqSSpUo.png)

note: it is recommended to disable smooth font for the classic scaler look, by going to `settings > preferences > editing` and unchecking `enable smooth font` in notepad++, if it is enabled as seen at the screenshot below.

![Imgur](https://i.imgur.com/vFFvIOR.png)

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
