### ISSUE TITLE
Random Crashing on launch with dependancy to Viber?

### ISSUE THREAD

**Issue by mach0gr** [notepad-plus-plus/notepad-plus-plus#5103]
### Description of the Issue
Using Notepad++(64bit) on Windows 10 (tried on 7.5.x and 7.6)
Even after a clean install I notice Notepad++ randomly crashing (not responding) on launch. 
I say randomly because it does not happen all the time. 
When it does it will just say (Not Responding) and will stay there forever. You can force close it from task manager.

### Steps to Reproduce the Issue
On my computer I also have Viber (messaging client installed. App from Windows App store). Interestingly I discovered while troubleshooting the crashes that while program is on (Not responsing) state, if you go to 
Task Manager > Performance > Open Resource Monitor > right click on "Notepad++ (Not Responding)" select "Analyse Wait Chain" you will see that it depends on Viber.exe. If you go and just close viber application, poof, notepad++ goes from the not responding state to opening normally.

![notepadd crash](https://user-images.githubusercontent.com/10363157/49571857-0e217980-f943-11e8-80fa-b6f2aff50df2.png)

I have absolutely no idea why notepad++ is related to viber.exe !!!
When Viber App is not running, not is taskbar, then all is well notepad++ will launch all the time.

Thank you,
Petros

**Comment by DavidHansen-0x454d43** [comment]
@mach0gr, can you post your debug info? (In Notepad++ its located under the '?' menu) 

I don't think Notepad++ is related to Viber at all... and since Viber is a free, closed-source messaging app, its most definitely spying on you. Maybe it has a file lock on one of Notepad++'s configuration files? Have you ever shared a file in Viber that you have worked on in Notepad++?

Also, [Microsoft's Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) is going to give you the a much better view of whats going on.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
