### ISSUE TITLE
Can`t change encoding to UTF8

### ISSUE THREAD

**Issue by shredder2003** [notepad-plus-plus/notepad-plus-plus#5126]
### Description of the Issue

Text (log) file in UTF8 encoding, contains Franch symbol.
NPP opens it as ISO-8859-7 and dont allows change encoding to UTF8

### Steps to Reproduce the Issue

1. Download example text file in UTF8 encoding: https://cloud.mail.ru/public/Dc3j/iLxSdY1zx
2. NPP shows it as ISO-8859-7.
3. Try to change encoding: Encoding -> UTF8. After clicking on this menu point, nothing happens and encoding is still ISO-8859-7.

**Comment by x9t9** [comment]
Can confirm this issue on 7.6. both x64 and 32 ( "portable" from archives )
Working well on older versions ( I have 6.3.3 Unicode .. very old I know, but works )

**Comment by lautis0503** [comment]
Disable  "Autodetect character encoding", and then change encoding to UTF-8.
Attention: This is not a valid UTF-8 text file. The second character é in 8-bit \0xE9 is illegal in UTF-8. This file could be a combination of UTF-8 and ISO-8859-15 encoding.
It seems that Notepad++ cannot be forced to use UTF-8 encoding to an invalid UTF-8 file when autodetect encoding enabled.

**Comment by SmashManiac** [comment]
Similar problem here on v.7.6.4. I have a UTF-8 document containing the “🔙”character  (U+1F519), and Notepad++ is stuck on Windows-1252 even when I select "Encode to UTF-8". When I delete the character and reload the file, everything is OK.

**Comment by MetaChuh** [comment]
**Referenced to:**
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5299 , https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5310 , https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5202

@SmashManiac 

unfortunately autodetect character encoding is broken since notepad++ version 7.6.
the implementation of UCharDet 0.0.6 since version 7.6 has caused this.

let's hope @CookiePLMonster reverts or fixes this. (ping, ping)

our last resort of hope would be that @donho takes the lead on that, to step in and revert autodetection to the old 7.5.9 code, even though he has not produced this near escalation himself.

ps for @donho : as soon as the auto updater is set to 7.6.4 this issue can possibly escalate, as it produces **broken files**, due to wrongly mixed encoding of characters when re-saving, as long as autodetect character encoding is enabled by **default**.

so please help us and keep repeatedly pinging @CookiePLMonster ... and tell him he is very invited to help us answering our every day user requests over at the community, **INCLUDING** all incomings regarding his commit 😉

# workaround for @SmashManiac :

**currently, until a fix is decided it is necessary to:**
* go to `settings > preferences > misc` and **disable** `auto detect character encoding` as seen at the screenshot below.

![settings - auto detect character encoding](https://i.imgur.com/9SZ5ufh.png)

* then go to `settings > preferences > new document` and set your preferred default encoding to e.g utf-8, as seen at the screenshot below.

![Imgur](https://i.imgur.com/AarYeSx.png)

**Comment by CookiePLMonster** [comment]
I will submit a PR reverting uchardet for the time being. I am not sure if @donho commented on this and I don't have the power to decide nor to merge the commit, but looking at the amount of issues it causes I think it's the lesser evil.

Proper test cases should be created for the next time uchardet receives an update. Better yet, those should be taken upstream to uchardet itself.

**Comment by SmashManiac** [comment]
@MetaChuh Thanks for the workaround! It's not ideal obviously, but I confirm I can at least switch encodings just fine afterwards.

**Comment by CookiePLMonster** [comment]
I have now submitted #5414.

**Comment by MetaChuh** [comment]
can be closed with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/486e2188b2d4f5e897d5ffffa9b3dcd23b3ae2d6

-----

update for @shredder2003 :

your issue, that you were not able to manually set your encoding to utf-8 on your test file has been fixed by the boss.

i have re-tested and verified this fix with your file, and it is now possible to manually set it to e.g. utf-8 or ansi, if autodetect character encoding is enabled.
the fix is currently scheduled to be released with notepad++ 7.6.5 until further notice.

but your file `bad_encoding3.txt` already has mixed character encoding, with french in ansi and russian in utf-8, as mentioned by @lautis0503 , which triggers wrong auto detection on all currently tested auto detection routines, so you have to correct the french ansi part manually.

-----

update for @SmashManiac :

i have re-tested your auto detection issue with files containing a “🔙”character (U+1F519), and your issue that you were not able to manually set your encoding back to utf-8, as long as autodetect character encoding was enabled.
both of your issues are also solved with the latest fix.

-----

@CookiePLMonster :
thanks for your help and my apologies for all the stress.
if we look at this from a positive side: now we all have a huge amount of submitted auto detection test files, which we would not have, if uchardet 0.0.6 would behave correctly on windows.
it might come in handy for any future autodetect tests.
and as don has frozen all auto updates, none of the affected versions were deployed at large scale.

-----

to all:

please feel free to visit us at the [notepad++ community forum](https://notepad-plus-plus.org/community/unread) to check for any announcements, or for any notepad++ related questions.

**Comment by MetaChuh** [comment]
fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/486e2188b2d4f5e897d5ffffa9b3dcd23b3ae2d6
