### ISSUE TITLE
Email addresses are exposed to search engines

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#5135]
http://docs.notepad-plus-plus.org/index.php/Plugin_Central

This page is currently being indexed by Google and others. There are exposed mailto: links everywhere.

**Comment by DavidHansen-0x454d43** [comment]
@Aidolii, that page hasn't been updated since 2014.... and the last update to the wiki was in 1/2015. I've tried to register to edit pages, but have been unable to find a way to do so. As far as I can tell the wiki is read-only now. 

 @sasumner, do you know of a way to update the wiki? Or maybe @donho can chime in?

**Comment by sasumner** [comment]
@donho is the man will all of that power; I have none.  :-)

**Comment by DavidHansen-0x454d43** [comment]
@sasumner, don't sell yourself short... knowledge is power, and you have considerable knowledge about the N++ ecosystem. I figured if anyone knew it'd be you. 

Looking at the wiki history, people other than @donho have contributed, so there was probably a registration option at one point. I'm hoping Don can tell us what happened to that place. I know myself and others would help update it if given the opportunity.

**Comment by ArkadiuszMichalski** [comment]
Out of date.
