### ISSUE TITLE
Notepad++ don’t remember encoding

### ISSUE THREAD

**Issue by duzers** [notepad-plus-plus/notepad-plus-plus#5138]
### Description of the Issue
Notepad++ don’t remember encoding for new unsaved file after 7.5.9 version, after sets default encoding as ANSI.
I write text "śśśśśś óóóóó źźźź", encoding ANSI is not sets, but there isn't problem for normal letters like "hsdfsf sdfsd".

### Steps to Reproduce the Issue
1. Settings
2. Preferences
3. New Document
4. Encoding, set ANSI
5. Write text "śśśśśś óóóóó źźźź" (polish letters)
6. Close Notepad++ without save
7. Open Notepad++

### Debug Information
Notepad++ v7.6.1   (32-bit)
Build time : Dec 12 2018 - 01:24:22
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

![obraz](https://user-images.githubusercontent.com/1188931/49991388-30d61280-ff81-11e8-9369-cacef61dd0b9.png)

**Comment by lautis0503** [comment]
I cannot paste these characters correctly in ANSI encoding.
Using ISO-8859-2 is good for me.

**Comment by MetaChuh** [comment]
@duzers 

your specific file encoding format issue is fixed in 7.6.5 and above.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.6.1, as the plugin folder structure has changed again in 7.6.3.

thank you for your help and best regards.
