### ISSUE TITLE
Issue with find/replace for round bracket

### ISSUE THREAD

**Issue by kostya-fr** [notepad-plus-plus/notepad-plus-plus#5153]
### Steps to Reproduce the Issue
1. Into regex mode I search for any string, and it works well
2. When I try to replace by another string containing round brackets '(' or ')' but it replace by nothing(erase selected string)

For example I tried to replace by : 'test)-test', ')-test', 'test)', '(' , ')', ');'

### Debug Information
Notepad++ v7.6   (32-bit)
Build time : Nov 12 2018 - 23:51:42
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
`(` and `)` have special meaning in the **Replace with** zone in regex mode.  If you want them to appear literally, you must escape them:  `\(` and `\)`.  Please close this issue.

**Comment by kostya-fr** [comment]
OK, I think it is a new behaviour and I'm not used to. But I don't get why we should use `\)` into "Replace with" field, because regex should be applying only on Search field

**Comment by sasumner** [comment]
>I think it is a new behaviour

It is **NOT** a new behavior.  It has worked this way in Notepad++ since it added true regular expression support (version 6.0 I think it was).

>and I'm not used to

This seems very true.

> I don't get why we should use \\) into "Replace with" field, because regex should be applying only on Search field

When regular expression mode is selected, **BOTH** the **Find what** and **Replace with** zones/fields may contain characters that are interpreted _specially_ ... and this is one of those cases for the **Replace with** zone -- the `(` and `)` characters have special meaning there.  Note that they ALSO have special meaning in **Find what**, but that is more commonly understood.

As an example, see the regular expression replacement here:  https://notepad-plus-plus.org/community/topic/12887/switching-letters-with-one-regex

As you can see there, there are `(` and `)` used in the **Replace with** zone.  But these are the special meaning ones.  That regular expression replacement will turn the text `news` into `swen` ...and in `swen` there are no `(` or `)` so hopefully you can now see how this works.

And BTW, if you use unescaped `(` or `)` wrongly in a replace expression, I believe they are just totally ignored (which may have led you to post this issue). :-)
