### ISSUE TITLE
None plugin available via the plugin manager

### ISSUE THREAD

**Issue by WagnerGMD** [notepad-plus-plus/notepad-plus-plus#516]
I create a rule inside my firewall. Despite this fact, Notepad++ can't find any plugin. The list is empty (literally). Even after a restart, the message : **None new plugin available** is still there.
There's something wrong ? The archive (.zip and .7z) is damage ? I can't find a version (like the v6.7.9.2) which works. I stop my research with the v6.7.5. I also checked the hash (a few) and nothing wrong...

I don't know but there's a trouble with sourceforge ? Right now, the website seem's temporarily in static offline mode. It's the cause ? In this case, can you add a warning to inform the user ?

It will be nice to improve this aspect from the plugin manager. The word **new**, it's a little confusing. Specially at the first launch. Maybe to remove ? And I didn't see any warning about the firewall.

**Comment by Joe136** [comment]
***the website seem's temporarily in static offline mode***
Yes, I think that's the problem.

I've checked the HTTP request of the updater. SourgeForge redirects the URL from **http://downloads.sourceforge.net/project/npppluginmgr/xml/plugins.zip** to **http://downloads.sourceforge.net/#!/project/npppluginmgr/xml/plugins.zip** (with **#!/**) with HTTP status code **302 Moved Temporarily**

The **plugins.zip** can be downloaded by following the `Location:` header. I'm not sure, if this will help to download the plugins itself.

**Comment by cmeriaux** [comment]
it's ok for me now. Connection from Paris

**Comment by WagnerGMD** [comment]
With this file (**plugins.zip**), sorry but can you explain me how to proceed ? I should remain the file once is extracted ? Because it doens't match with the file (already) inside the directory **plugins**.
The folder content : **PluginManager.ini**. The archive content : **PluginManagerPlugins.xml**.

By precaution, I download and extract again the latest version (v6.7.9.2). The hash still match.
I believe, the trouble is gone for now... and sourceforge (some part) is still under maintenance...
In the futur, to prevent this trouble, it won't be better to provide a backup via the GitHub (or something else) ?

**Comment by Joe136** [comment]
After you have downloaded the **plugins.zip**, extract it. There is the file **PluginManagerPlugins.xml**.

Copy the file to **C:\Users\** ***\<USER\>*** **\AppData\Roaming\Notepad++\plugins\config\** (alternative **%AppData%\Notepad++\plugins\config\**). Normally the AppData Directory is hidden. The fastest way to open the folder is to paste the alternative address into the address bar (http://i.stack.imgur.com/gdCIc.png).

These parts of SourceForge are working now. This is the second time I have seen/realized that SourceForge has such problems. A backup via GitHub will not help. As long the plugins cannot be downloaded, you will not need the *plugins.zip* because you can't download (and install) the plugins, too. You have to backup every plugin, too.

It would be nice to have a better explanation instead of "Installation of plugin failed" (it can be any reason for it), maybe "Download of plugin failed". Additionally a small message that the plugin manager couldn't update the plugin list (*PluginManagerPlugins.xml*) would be nice, too.

**Comment by Joe136** [comment]
It would be nice to have a better explanation instead of "Installation of plugin failed" (it can be any reason for it), maybe "Download of plugin failed". Additionally a small message that the plugin manager couldn't update the plugin list (*PluginManagerPlugins.xml*) would be nice, too.

**Comment by WagnerGMD** [comment]
I see now, thank you and specially for the explanation. I don't check the latest version (6.8) but I assume it's still the same (according to the changelog).

**Comment by milipili** [comment]
Feel free to re-open this issue if needed

**Comment by CEHA** [comment]
Its OK now

**Comment by opcwebm** [comment]
@gitHub admins or moderators: i dont know if my comment is at the good place here.Sorry.

for many developers like me who meet difficulties with plugin manager:
-install last release npp++ (7.4.1 actually x86 version) and plugin manager X86, not 64bits! (from the official site):not such 64b plugins available.
-if you dont work with a special proxy combination within ur network structure, deactivate proxy or configure it if necessary from the command line (relative dos invite path)+gup -options 
-Not plugins shown? i create i blank file called "allowAppDataPlugins.xml" and i stored it inside npp+ folder. enjoy!
