### ISSUE TITLE
Notepad++ Froze on startup, waiting for explorer.exe

### ISSUE THREAD

**Issue by danvim** [notepad-plus-plus/notepad-plus-plus#5227]
### Description of the Issue

Notepad++ Froze when startup and did not fix itself by restarting app. Checking in Task Manager with "Analyze wait chain", it seems that Notepad++ was waiting for `explorer.exe`. Upon terminating explorer, Notepad++ returned to normal.

Several unsaved and saved documents are in Notepad++.

### Steps to Reproduce the Issue

1. Start Notepad++.
2. It is immediately non-responsive.
3. Open Task Manager, go to Details.
4. Right Click on notepad++.exe, Analyze Wait Chain.
5. Seeing `explorer.exe` is being waited. Terminate `explorer.exe`.
6. Notepad++ resumes to normal.

### Expected Behavior

To open normally.

### Actual Behavior

Froze on startup.

### Debug Information

Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by imallett** [comment]
I am also getting this issue sporadically. Sometimes closing other applications helps (in-particular, closing everything never fails to make it start, although the minimal such set of programs is unpredictable).

Probing it with the MSVC debugger sometimes resolves it also, although it sometimes doesn't. In such a case, I got the following stack trace of the hang showing that in at least this case it is due to the spellcheck plugin:

![notepad hang](https://user-images.githubusercontent.com/8649790/52541648-c0ffc080-2d54-11e9-9d78-2c5abcf8858d.png)

It'd be nice if symbols were shipped, although I suppose one could just build it themselves . . .

**Debug Information**
Notepad++ v7.5.9 (32-bit), although I have gotten this in previous versions as-well.
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll

**Comment by Faq** [comment]
The same happens with v7.6.3?

**Comment by imallett** [comment]
After moving to 7.6.3 and 64-bit, the problem has not recurred in the more than two weeks since, even once. I believe this problem must have been fixed by some change between the versions, or by the increased bit-iness, and therefore tentatively consider it solved.

**Comment by Faq** [comment]
@danvim problem for you still valid with latest 32bit 7.6.3 ? if not, please close this issue.

**Comment by imallett** [comment]
Of course, no sooner does it seem to be working than it comes back.

It was failing repeatedly with three Visual Studio windows open. Attaching with one of them gives the following stack trace showing it's hanging in apparently a similar place:
![hang](https://user-images.githubusercontent.com/8649790/53693424-64912f00-3d5d-11e9-9063-87abd936d89d.png)

Closing two of the Visual Studio windows and retrying was enough to get it to work, but reopening them and retrying wasn't enough to reproduce it again.

Notepad++ v7.6.3   (64-bit)
Build time : Jan 27 2019 - 17:16:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by danvim** [comment]
I am unable to reproduce my own problem. I had no idea why it was waiting for explorer.exe, so I guess without any other people's input on clues. It's unlikely that this issue will do any help.
