### ISSUE TITLE
notepad++ 7.6.2:On limited user ,when i try to install the plugins through plugin admin ,i get UAC prompt.How can i supress it?

### ISSUE THREAD

**Issue by 01mrunalshinde** [notepad-plus-plus/notepad-plus-plus#5244]
notepad++ 7.6.2:On limited user(the user has no admin rights) ,when i try to install the plugins through plugin admin ,i get UAC prompt.How can i supress it?

**Comment by sasumner** [comment]
user with no admin rights is supposed to get UAC

...but this is a question, not an issue, so look for answers (which probably already exist) or ask this question here: https://notepad-plus-plus.org/community

**Comment by bviktor** [comment]
This **is** an issue, since you get the UAC prompt even when running in portable and thus you have write access to the folder as a user.

This whole plugin mess is a friggin' disaster. It's no longer possible to mass-deploy Notepad++ at all. The moment you push it out, all your users lose ALL their plugins and have to reinstall them all. Assuming they're admins, since this only works with admin rights due to the erroneous UAC prompt.

Your selection of 3rd party plugins is a configuration element, not an installation element. So why the hell would you put them in the install folder. How the hell does this improve security? Particularly stupid given that plugins can still put binaries in your AppData folder, like 3P. So what kind of problem does this solve? Practically none. Oh, but an audit program said you _have_ to eliminate this option, so let's just do that without putting any thought into it.

If several users use the same computer, if you install a 3rd party plugin, it'll appear to all. Even if they don't want it. Then they can remove it.... and then _all_ users will lose it.

The whole mess looks like someone from the 90s designed it, where you had only one user on the host, and she was always an admin. So yeah, nice going with these new releases. First they broke it with the installer installing stock plugins ONE user's AppData, then they managed to make it even _worse_ with this stupid crap of putting everything into the install dir. That's quite an achievement.

It's so stupid it's beyond belief.

**Comment by MetaChuh** [comment]
@01mrunalshinde 

please perform an all users ProgramData install, to allow all users of a specific machine to install and remove plugins without elevated rights:

* use the [npp.7.6.6.Installer.exe](https://notepad-plus-plus.org/repository/7.x/7.6.6/npp.7.6.6.Installer.exe) or [npp.7.6.6.Installer.x64.exe](https://notepad-plus-plus.org/repository/7.x/7.6.6/npp.7.6.6.Installer.x64.exe)  (x86 or x64 is completely of your choice)

* install notepad++ 7.6.6 to `%ProgramData%\Notepad++`
**important note**: when installing, make sure you select `Don't use %AppData%`.

* this will install notepad++, so that all users on this specific machine have the right to install plugins, without any uac prompt.
note: all local users will share the same plugins and settings.
(you can also choose any other folder, where all or specific users have access to, as long as you don't use e.g. %ProgramFiles% or %ProgramFiles(x86)% )

for more details and silent deployment scripts, please visit our notepad++ community.
example topic: [install notepad++ plugin without admin rights ](https://notepad-plus-plus.org/community/topic/17232/install-notepad-plugin-without-admin-rights)

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
