### ISSUE TITLE
In App Update not working

### ISSUE THREAD

**Issue by Daptonic** [notepad-plus-plus/notepad-plus-plus#5292]
### Description of the Issue
In app update method not working. Has not worked for me since 7.5.9

### Steps to Reproduce the Issue

1.  Click ?
2. Update Notepad++
3. "No Update Available"

### Expected Behavior
I expected to be prompted to get v 7.6.3

### Actual Behavior
No Update Available message. 

### Debug Information
Notepad++ v7.6.2   (64-bit)
Build time : Jan  1 2019 - 00:02:38
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

https://imgur.com/a/7Qk4sSP

**Comment by TazzyT** [comment]
Same issue for me except I am still on v7.5.9 (64-bit).

**Debug Information**
Notepad++ v7.5.9   (64-bit)
Build time : Oct 14 2018 - 15:19:55
Path : J:\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll ComparePlugin.dll

**Comment by sasumner** [comment]
There's a good reason for this. Plugins handling has radically changed.

**Comment by TazzyT** [comment]
> 
> 
> There's a good reason for this. Plugins handling has radically changed.

I know plugin handling has changed but there is nothing anywhere that states you must manually update with every release now.  If you notice Daptonic has manually updated to v7.6.2 and it still is not automatically updating to the next release.

If automatic updates is not just broken and has been removed then a note stating there is an update available with a link that opens the download page would be very helpful.

If automatic update has only been disabled in v7.5.9 because of the plugin change then a note on the main page somewhere stating this would be very helpful since there is also a note stating that "the next release wont be pushed until it is stable".  One could then argue that the v7.6.* releases are not stable since they have not been pushed, however they have been and are available from the main download page as the main download. 

So I am just looking for some insight as to whether or not it is broken or has been disabled.

Thank you!

**Comment by rafrafek** [comment]
I can confirm that v7.5.9 says "No update is available".

**Comment by sasumner** [comment]
People:  This is **_BY DESIGN_**.  Let it go.
