### ISSUE TITLE
Minor 7.6.3 bug: File open filtering not working properly

### ISSUE THREAD

**Issue by Dobrotescu** [notepad-plus-plus/notepad-plus-plus#5295]
### Description of the Issue

If in the file open dialog a specific selection is chosen (YAML, for instance), the proper filtering takes place. However, when the file open dialog is used again, the filtering selection is remembered, but doesn't do anything. If the filter is changed to something else and then changed back, it works (for the current dialog only).
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by MetaChuh** [comment]
description:

note: concerning **old style dialog** only.

when using old style dialog at `settings > preferences > default directory`, the drop down file type mask is remembered, but the files will not be filtered, when reopening the open or save dialog.

when using **new style dialog** the behaviour is as designed and expected:
manual file masks by typing e.g. `*.xml` followed by <kbd>enter</kbd>.
drop down file mask will, by design, not be remembered.

best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by Dobrotescu** [comment]
I verified the old style dialog vs new style dialog behaviours (didn't know about the new one), both work as described.

Is there any chance the old style dialog will be fixed, or should I close the bug?

Thanks.

**Comment by MetaChuh** [comment]
thank you for your question about closing this issue.
this is completely your choice, as it would depend on your needs.

if you are satisfied with the new style dialog behaviour, and manual wildcard filtering with typing `*.yml`, which is usually quicker than searching within a large drop down menu, you can close this issue.

but if you prefer the old style dialog, and you want to eventually get it fixed some day, you can leave it open as a verified issue.

i don't know though, if the old style dialog will ever get fixed, as it currently makes more sense to remove it some day in the future, as most of the reporting users prefer the new style dialog, and like having the windows native quick access favourites at the side bar, which is not possible at the old style dialog.

many thanks for your help and best regards.

**Comment by Dobrotescu** [comment]
The new style dialog good enough for me ... I'm closing this issue.
Thanks.
