### ISSUE TITLE
Cannot keep utf-8 and umlauts when saving new file

### ISSUE THREAD

**Issue by BugFeedbacks** [notepad-plus-plus/notepad-plus-plus#5299]
Hello. When I save a new txt-file, html-file and others, Notepad++ does not save the umlauts correctly. Then: When I open the menu and go to Coding (Kodierung) and select "UTF-8" and when I immediately re-open Coding, I see that Notepad++ has not saved my selection. There is still no point before "UTF-8" or any other coding. The problem could be the combination of Windows (7) and UNIX (LF) end of line format (Format Zeilenende) and UTF-8 in the Options/New files (Neue Dateien).

Please fix that bug. Thank you very much!

**Comment by Faq** [comment]
You forgot to mention N++ version and used plugins.

**Comment by BugFeedbacks** [comment]
I checked the latest version of today. The problem is still NOT solved.

**Comment by sasumner** [comment]
>I checked the latest version of today. The problem is still NOT solved.

You probably didn't need to check the latest version.  If there was any action on this, there would have been follow up comments RIGHT HERE in this issue thread.

**Comment by MetaChuh** [comment]
@BugFeedbacks 

if you open an utf-8 file, which contains german umlaute, and you can not see the bullet at `encoding > encode in utf-8`, you probably have 7.6 to 7.6.3 installed.
you might also experience files, where you try to set `encoding > encode in utf-8` and the bullet will disappear immediately.

the implementation of the autodetect character encoding "UCharDet 0.0.6" since version 7.6 has caused this.
currently, until a fix is found it is necessary to:
* go to `settings > preferences > misc` and **disable** `auto detect character encoding` as seen at the screenshot below.
(entferne den haken bei kodierung automatisch erkennen)

![settings - auto detect character encoding](https://i.imgur.com/9SZ5ufh.png)

* then go to `settings > preferences > new document` and set your preferred default encoding to e.g utf-8, as seen at the screenshot below.

![Imgur](https://i.imgur.com/AarYeSx.png)

please report back if this workaround fixes your issue experience.

**Comment by BugFeedbacks** [comment]
Thank you all. I tried your settings. But the bug is still there. I am using a Notepad++ 32 Bit on a Windows 7 64 Bit. The 64 Bit version has a malfunction with the Dateiverknüpfungen (always open files with Notepad++ does not work). That's why I use the 32 Bit version of Notepad++.

Now to the new bug. Notepadd++ cannot save ß without umlauts in the file.

The evidence:

Please open a new file with Notepad++ v7.6.4 (32 Bit) on a Windows 7 (64 Bit).

Then please enter ONLY the following text:

Friedrich Meier
Schienenstraße 12
12099 Berlin

Then save a txt-file "Evidence.txt" with the following settings:
- Coding UTF-8
- UNIX (LF) end of line format

(on a NTFS-SSD)

Close the txt-file and re-open it.

You will see the following:

Friedrich Meier
SchienenstraĂAPCe 12
12099 Berlin

So Notepad++ cannot save "ß", when umlauts do not occur in the file. At least that bug I could reproduce. The "ß" is a very important character in german. So please help.

Please fix that bug. Thank you.

**Comment by MetaChuh** [comment]
@BugFeedbacks 

i can not reproduce your experience, if both settings of the workaround above are correctly set.
(see screenshot of my testing result)

![Imgur](https://i.imgur.com/e9aAmZn.png)

if i create "Evidence.txt" with the contents:
```
Friedrich Meier
Schienenstraße 12
12099 Berlin
```
make sure it is set to utf-8, change the line endings to unix (lf), and save it to a ntfs ssd.
then i close the "Evidence.txt" tab.
(optional but irrelevant: close notepad++ completely, and reopen notepad++)
re-open "Evidence.txt" by either using the "edit with notepad++" ("mit notepad++ öffnen") context menu, or the open file menu from within notepad++.

the file is correctly loaded as utf-8, because we have previously `disabled auto detection`, and set our `default to utf-8` and checked `apply to opened ansi files`.

can you please re-check, to help us find out which of your settings might differ, which might cause what you see ?
all answers might be of use for others at our [notepad++ community](https://notepad-plus-plus.org/community/recent), as this broken autodetection issue is currently one of the most discussed issues, or maybe the most discussed already.

**Comment by chcg** [comment]
Without the workaround the file is detected as ISO 8859-2.

**Comment by BugFeedbacks** [comment]
-

 

Hello MetaChuh,

 

I put a file for you into this email attachment. These are my Notepad++ Settings. I am sorry that you can not reproduce the bug.

 

1. Please use the german version of Notepad++ with v7.6.4 (32 Bit) on Win7 (64 Bit) with my attached settings.

 

2. Close all Notepadd++. Open a new instance then.

3. Open the "Kodierung" menu.

4. You see a blue point before UTF-8

5. Go back to the body and enter the german sign "ß".

6. Save it as a new file ("Speichern" icon) "evidence.txt" on a NTFS formatted SSD.

7. Close Notepad++ and re-open the file.

8. The blue point before UTF-8 is still there in "Kodierung".

9. Replace the body with "Friedrich Meier, Schienenstraße 12, 12099 Berlin".

10. Close Notepad++ and re-open the file.

11. The blue point before UTF-8 in Kodierung is GONE.

12. The body says now: "Friedrich Meier, SchienenstraĂ�APCe 12, 12099 Berlin"

(The APC in Schienenstraße has a black background color)

 

Thank you very much for your help!!!

 

BugFeedbacks

 

 
 

 

Gesendet: Mittwoch, 13. März 2019 um 12:32 Uhr
Von: "MetaChuh" <notifications@github.com>
An: notepad-plus-plus/notepad-plus-plus <notepad-plus-plus@noreply.github.com>
Cc: BugFeedbacks <bonne_soiree@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [notepad-plus-plus/notepad-plus-plus] Cannot keep utf-8 and umlauts when saving new file (#5299)


@BugFeedbacks

i can not reproduce your experience, if both settings of the workaround above are correctly set.
(see screenshot of my testing result)



if i create "Evidence.txt" with the contents:

Friedrich Meier

Schienenstraße 12

12099 Berlin



make sure it is set to utf-8, change the line endings to unix (lf), and save it to a ntfs ssd.
then i close the "Evidence.txt" tab.
(optional but irrelevant: close notepad++ completely, and reopen notepad++)
re-open "Evidence.txt" by either using the "edit with notepad++" ("mit notepad++ öffnen") context menu, or the open file menu from within notepad++.

the file is correctly loaded as utf-8, because we have previously disabled auto detection, and set our default to utf-8 and checked apply to opened ansi files.

can you please re-check, to help us find out which of your settings might differ, which might cause what you see ?
all answers might be of use for others at our notepad++ community, as this broken autodetection issue is currently one of the most discussed issues, or maybe the most discussed already.

**Comment by MetaChuh** [comment]
@BugFeedbacks 

i have followed your new step by step guide, and i am still not able to reproduce this ... unless you have forgotten to disable the broken `autodetect character encoding` option.

it is important that you disable the broken `autodetect character encoding` feature.

if you don't do that, your bullet (the blue point at e.g. `kodierung > utf-8`) will always disappear and jump to a wrong encoding, which is `kodierung > weitere > osteuropäisch > iso-8859-2` in your case.

**entferne unbedingt den haken bei der option `einstellungen > optionen > diverses > kodierung automatisch erkennen`, die funzt seit längerem nicht korrekt (seit version 7.6.0) !**

i've attached a new screenshot with your sample file and all important information, including debug info and the needed preferences you have to set.

![Imgur](https://i.imgur.com/G5nyZ5Q.png)

**Comment by BugFeedbacks** [comment]
Hello MetaChuh,

 

your solution is working!!! Thank you very much!!!

 

 

LG


 

 


Gesendet: Sonntag, 24. März 2019 um 10:58 Uhr
Von: "MetaChuh" <notifications@github.com>
An: notepad-plus-plus/notepad-plus-plus <notepad-plus-plus@noreply.github.com>
Cc: BugFeedbacks <bonne_soiree@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [notepad-plus-plus/notepad-plus-plus] Cannot keep utf-8 and umlauts when saving new file (#5299)


@BugFeedbacks

i have followed your new step by step guide, and i am still not able to reproduce this ... unless you have forgotten to disable the broken autodetect character encoding option.

it is important that you disable the broken autodetect character encoding feature.

if you don't do that, your bullet (the blue point at e.g. kodierung > utf-8) will always disappear and jump to a wrong encoding, which is kodierung > weitere > osteuropäisch > iso-8859-2 in your case.

entferne unbedingt den haken bei der option einstellungen > optionen > diverses > kodierung automatisch erkennen, die funzt seit längerem nicht korrekt (seit version 7.6.0) !

i've attached a new screenshot with your sample file and all important information, including debug info and the needed preferences you have to set.

**Comment by MetaChuh** [comment]
@BugFeedbacks 

perfect, thank you very much for reporting back.

**update and more good news:**
this autodetect issue has been **fixed** by the lead developer, and the fix is reported to be available at the **next version 7.6.5.**

your specific example was also re-tested and is verified to be working correctly with autodetect character encoding enabled on the upcoming notepad++ version 7.6.5.

**Comment by sasumner** [comment]
@MetaChuh 

>autodetect issue has been fixed by the lead developer

"Fixed"? Isn't it just going back to the way it used to be?  I may not call that a "fix" as there must have been some compelling reason to upgrade the detection algorithms in the first place.

**Comment by MetaChuh** [comment]
@sasumner 

> "Fixed"? Isn't it just going back to the way it used to be?

yes, you are absolutely correct, it is a rollback.
and you have intentionally omitted an important word at your quotation: **"this"** autodetect issue has been fixed.

>  I may not call that a "fix"

you may, you may. no-one would forbid you to do so, except maybe yourself, if you take the time to reproduce as many issues as you can and eventually prove it all wrong ... not 😉

the rollback has been verified to be the best current choice.
so far there are no other known options, that have been verified to successfully pass the same amount of tests.

> as there must have been some compelling reason to upgrade the detection algorithms in the first place.

yes, you are correct again.
the implementation of uchardet 0.0.6 should have improved a few detection issues with non utf-8 and non ansi files, which would have been achieved, if the original uchardet code would work on windows, like it does on mac or linux, but it does not.
this got overlooked, as the uchardet 0.0.6 commit was not tested thoroughly enough, and more assumed that it would work properly.

note: some issues, like #940 (one byte utf-8 file with a single `§` without any line break, detected as tis-620), would not have been fixed, even with a correctly working 0.0.6, and can currently not be detected correctly on any operating system with any routines i've tested so far.

if you have time, and this topic is of interest to you, please compile and re-test anything you can find. maybe you will find a better solution.
(i'm a bit jaded at the moment, regarding auto detection topics and tests)

thanks and greetings
metachuh

**Comment by BugFeedbacks** [comment]
Fixed? No. It works now because I now unchecked the "Autodetect character encoding" in the MISC options.

 

 

Thank you for your help!!!
