### ISSUE TITLE
UDL Keywords List - Total number of keywords/characters in a section has a limit

### ISSUE THREAD

**Issue by scot-65** [notepad-plus-plus/notepad-plus-plus#5300]
### Description of the Issue

Manually adding a keyword list, specifically VLA- functions, where the number of keywords is around 2055 (about 46800 total characters) and the number of characters for each keyword ranges from 7 up to 42. Foxe is my editor of choice.

### Steps to Reproduce the Issue

1. Copy-clip/paste from notepad into Foxe - All 2055 keywords/46800 characters.
2. Verifying no carriage-returns or special characters (except dashes "-") in the list.
3. Restarting Notepad++ (v7.5.9 32-bit) on W7-64.

### Expected Behavior

Coloring of the keywords.

### Actual Behavior

Default coloring. However, the keyword sections above and below rendered OK.

### Debug Information

Resolved: Splitting the list into 3 parts, thus occupying 3 keywords sections (for this situation the list could be split into 3 parts however, I could have tried splitting into 2 parts).

**Comment by MetaChuh** [comment]
@scot-65 

this udl limitation can currently not be fixed.
thank you for sharing and using the workaround of splitting your keywords into more than one section.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by Luashine** [comment]
> this udl limitation can currently not be fixed.

**She/he closed this as wontfix in 2019, is there any reason as to why?**

- the maximum lists limit is coming from Scintilla? https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6020
   - https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12143 straight up suggested dynamic number of keyword lists
- what's the reason to limit the length of these lists?

# use case

I made a syntax highlighter for the JASS scripting language of Warcraft 3. To properly highlight all the standard API functions I must insert the full function names. There are many of those, but that list is static and "prefix mode" would be highlighting typos too.

So I did apply the workaround of splitting one list into multiple groups and ended up wasting two extra groups.

1. Language keywords
2. Predefined types
3. Game API (aka natives) part 1
4. Game API (aka natives) part 2
5. Well-known global variables (Blizzard.j)
6. Official helper functions (Blizzard.j)
7. API Constants part 1
8. API Constants part 2

Due to this limit and only having 8 groups max, I had to sacrifice marking as keywords another part of the API: `common.ai` file.

For what it's worth, the exported XML file shows `\r\n` as delimiter (escaped as quoted XML entities): `BJDebugMsg&#x000D;&#x000A;RMinBJ&#x000D;&#x000A;RMaxBJ...` I am not sure this could be tricked somehow for one less byte per entry.
