### ISSUE TITLE
Feature request: consider implementing SCI_SETIDENTIFIER

### ISSUE THREAD

**Issue by Ekopalypse** [notepad-plus-plus/notepad-plus-plus#5327]
In order to be able to distinguish which scintilla instance send which scintilla notification
it is needed to set an identifier as described [here](https://www.scintilla.org/ScintillaDoc.html#SCI_SETIDENTIFIER)
Would you consider implementing it?
Thank you

**Comment by dail8859** [comment]
How are you currently distinguishing between which editor sent a notification?

**Comment by Ekopalypse** [comment]
@dail8859 - sorry, but I'm unsure about your question. 
Currently npp does not set the identifier, hence the feature request.
To make it work, with lua for example, you would set it 
with, let's say 0 for view0 and and 1 for view1 and when receiving a notification you would read that value from notification header. Is that what you are asking about?

**Comment by dail8859** [comment]
I'm not arguing against it. It is just that since Notepad++ doesn't use it internally...if a plugin needs it then it would set it itself. (Although if several plugins set it to something different that could cause a whole mess of problems...so maybe it is worth setting within Notepad++)

For all of my plugins I use the `hwndFrom` field in the notification. Or I use `NPPM_GETCURRENTSCINTILLA`.

**Comment by Ekopalypse** [comment]
Don't get me wrong - whether it will be implemented and/or accepted is up to you (contributors) and I agree with what you said, if there is no benefit of having such identifier from npps point of view and plugins should use there own mechanism to identify which editor sends which notification then I'm fine with it, but just as you've said, it might get messy if multiple plugins are using this api differently. Nevertheless, I really appreciate your thoughts, insights and considerations about this.

**Comment by sasumner** [comment]
@Ekopalypse I've read your original description and followups but perhaps what is missing is a specific example of where this capability would help you.  Not a general thing, but a rather specific thing that really hammers home the utility.

I have done some pretty amazing Pythonscripts (humble, humble...) without it, but now I am wondering if I could have done them better/easier with it...but I'm unsure how to truly judge this.  Again a specific example from you might help me understand...

**Comment by Ekopalypse** [comment]
@sasumner -  I think it is useful in the case that both views are used and notifications sent by the inactive editor needs to be considered like in scrolling the text and act accordingly like highlighting certain text.

The issue raised when I tried to enhance udl and builtin lexers with a python script. As I scrolled the inactive editor the coloring didn't take place on this editor rather than on the active one.

Does this makes sense to you?

**Comment by Ekopalypse** [comment]
@dail8859 - I guess so. Afaik hwnd are unique during npps lifetime and don't change, right?
Currently I ask myself why idFrom has been added to 
struct Sci_NotifyHeader {   // This matches the Win32 NMHDR structure
    void *hwndFrom;     // environment specific window handle/pointer
    uptr_t idFrom;        // CtrlID of the window issuing the notification
    unsigned int code;  // The SCN_* notification code
};
if hwndFrom is already unique.

SCI_SETIDENTIFIER(int identifier)
SCI_GETIDENTIFIER → int
These two messages set and get the identifier of the Scintilla instance which is included in notifications as the idFrom field. When an application creates multiple Scintilla widgets, this allows the source of each notification to be found. On Windows, this value is initialised in the CreateWindow call and stored as the GWLP_ID attribute of the window. The value should be small, preferably less than 16 bits, rather than a pointer as some of the functions will only transmit 16 or 32 bits.

**Comment by dail8859** [comment]
> Afaik hwnd are unique during npps lifetime and don't change, right?

Yes.

> Currently I ask myself why idFrom has been added to...

I can't say for sure. From my knowledge when Scintilla was first created it tried to be compatible with Win32 messaging. That's why the `Sci_NotifyHeader` is the way it is. Over time Scintilla has changed to work on multiple operating systems and frameworks...which means some of these values were not applicable to other operating systems(e.g. MacOS or Linux) and was probably just reused.

**Comment by Ekopalypse** [comment]
So I guess, this FR can be closed as hwndFrom is already part of the notification header.

**Comment by sasumner** [comment]
@Ekopalypse and @dail8859 

You guys are speaking a foreign language as far as I can tell.  When I create a Pythonscript notification, I do something like this:

    def callback_sci_UPDATEUI(args):
        pass
    editor.callback(callback_sci_UPDATEUI, [SCINTILLANOTIFICATION.UPDATEUI])

If the code looks at the `args` I don't see anything that looks like an `hwndFrom`.  I have some test code that hooks into all the notification callbacks individually and dumps the `args` for each...and nothing that looks like this magical hwnd pops out at me.  Can either of you enlighten me as to how I would see this at the Pythonscript level?

I'm totally confused...and have a need very similar to Eko's "...scrolled the inactive editor the coloring didn't take place on this editor rather than on the active one".

**Comment by Ekopalypse** [comment]
hwndFrom is part of the c++ struct Sci_NotifyHeader. PS plugin needs to implement the field into the 
args dictionary first.

**Comment by sasumner** [comment]
@Ekopalypse 

Oh, okay, I get it.  You guys were talking about a possible future implementation.  From the discussion I thought it was something already available that maybe wasn't documented.  Makes sense now; thanks for the clarification.  It does seem like something more likely to be implemented on the PS side of the house.
