### ISSUE TITLE
bad alloaction Exception

### ISSUE THREAD

**Issue by EbATpy** [notepad-plus-plus/notepad-plus-plus#5330]
### Description of the Issue
PluginsManager::runPluginCommand Exception
bad alloaction

### Steps to Reproduce the Issue
1. switch Spell check ON
2. Open lagre File
3. Try to Collaps all levels 

### Actual Behavior
Exception box is comming more then one time
bad alloaction

### Debug Information
Notepad++ v7.6.2   (32-bit)
Build time : Jan  1 2019 - 00:00:08
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

![unbenannt](https://user-images.githubusercontent.com/15367388/53030740-b8ea0400-346b-11e9-9447-d45425835483.png)

**Comment by donho** [comment]
PluginsManager is a plugin, so it's not Notepad++ issue.

**Comment by SinghRajenM** [comment]
@MetaChuh Seems this issue is from plugin....

**Comment by MetaChuh** [comment]
@EbATpy 

thank you for your detailed information.

please remove the DSpellCheck plugin as this issue is caused by DSpellCheck.

note: if you need the DSpellCheck plugin, you have following options:
* update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and re-install the newer version of dspellcheck via plugins admin.
* if any spell checker issue still persists, please file an issue report at: https://github.com/Predelnik/DSpellCheck/issues
as this plugin is not maintained by the notepad++ team.

many thanks and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
