### ISSUE TITLE
Notepad++ Wrong Render

### ISSUE THREAD

**Issue by LongChampion** [notepad-plus-plus/notepad-plus-plus#5332]
### Description of the Issue

When use Windows+Tab to switch between different windows, Notepad++ have wrong render for some build-in sub-window, such as Function List and Project Panel.

### Steps to Reproduce the Issue

1.  Open Notepad++
2.  Make sure that you have Function List sub-window (if not, View -> Function List to show it)
3.  Press Window+Tab (not Alt-Tab)
4. Select Notepad++ window again

### Expected Behavior

Function List reappear with BLACK background

### Actual Behavior

Function List reappear with WHITE background

### Debug Information

Notepad++ 32-bit version: 7.6.3
Windows 10 1809 64-bit (Version 10.0.17763.316)

![correct](https://user-images.githubusercontent.com/47727306/53067861-affb4000-3508-11e9-9325-dbcbdeb45f5e.png)
![wrong](https://user-images.githubusercontent.com/47727306/53067863-b093d680-3508-11e9-8f1c-6c073234b8cf.png)

**Comment by MetaChuh** [comment]
@LongChampion 

we can not reproduce a <kbd>windows</kbd>+<kbd>tab</kbd> rendering issue on panels, using notepad++ 7.6.6, when using themes, caused by notepad++.
(see screenshot below)

<img width="349" alt="" src="https://user-images.githubusercontent.com/45773305/56475728-a94b6380-648c-11e9-9fd8-6accc034b9f4.png">

best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
