### ISSUE TITLE
-ro ignored on commandline

### ISSUE THREAD

**Issue by RoyLehmann** [notepad-plus-plus/notepad-plus-plus#5336]
### Description of the Issue

Running Notepad++ via command line
Using Microsoft Access for Office 365 VBA
executing the following command line via windows API CreateProcessA

C:\Program Files (x86)\Notepad++\Notepad++.exe -ro "C:\Users\RoyLehmann\VisualStudio\MyData\MyFinances.xml"

### Expected Behavior

1.  Changes to file not allowed
or
2a File save exits with error message
2b file save as displays warning message

### Actual Behavior

changes are allowed without warning.  This could corrupt my project

### Debug Information

Notepad++ v7.6.3   (32-bit)
Build time : Jan 27 2019 - 17:20:30
Path : C:\Program Files (x86)\Notepad++\Notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

[Notepadtest.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2887176/Notepadtest.txt)
[ExecCmd.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2887177/ExecCmd.txt)

**Comment by MetaChuh** [comment]
@RoyLehmann 

in order to be opened as read only using -ro, your document C:\Users\RoyLehmann\VisualStudio\MyData\MyFinances.xml must **not** have been opened before in a saved session.
(you have to close MyFinances.xml, as -ro will only work if the file will not be loaded by a session)

if you want to use -ro, you have to disable
`settings > preferences > backup > remember current session for next launch`
and
`settings > preferences > backup > enable session snapshot and periodic backup`,
otherwise this will override your -ro command line, as the session already contains a normally opened "MyFinances.xml".

a workaround, if you don't want to change those settings at your installed, every day notepad++,
is to download a portable version from [>>> here <<<](https://notepad-plus-plus.org/repository/7.x/7.6.3/npp.7.6.3.bin.zip),
extract it to e.g. C:\PortableApps\npp.7.6.3.bin,
start it by double-clicking on C:\PortableApps\npp.7.6.3.bin\notepad++.exe,
disable sessions in this portable (completely independent) notepad++,
and then use the command line:
`"C:\PortableApps\npp.7.6.3.bin\notepad++.exe" -ro "C:\Users\RoyLehmann\VisualStudio\MyData\MyFinances.xml"` instead

hope this helps.

**Comment by RoyLehmann** [comment]
This was the fix I needed.

I consider this a bug in notepad++

My next post will explain this in detail.
