### ISSUE TITLE
Junk character on macro playback

### ISSUE THREAD

**Issue by SinghRajenM** [notepad-plus-plus/notepad-plus-plus#5339]
### Description of the Issue

Playing recorded macro produces junk character on find window (under mark tab)

### Steps to Reproduce the Issue

1. Open notepad++ and start recording macro
2. <kbd>Ctrl</kbd>+<kbd>F</kbd>and click on "Mark"
3. Type some text and click on "Mark All"
4. Now stop macro recording.
5. Now start playback (menu->macro->playback) **without closing find window**
6. Observe text on Find window status bar

### Expected Behavior

Find window status bar should have respective marked word counts.

### Actual Behavior

Find window status bar should has junk characters.

### Debug Information

Notepad++ v7.6.3   (64-bit)
Build time : Jan 27 2019 - 17:16:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

![image](https://user-images.githubusercontent.com/14791461/53303050-cb10db80-388b-11e9-83d1-01bf9bcc77d9.png)

![image](https://user-images.githubusercontent.com/14791461/53303064-f0054e80-388b-11e9-9361-976f88555137.png)

**Comment by MetaChuh** [comment]
@SinghRajenM 

nice find and very intriguing.

i can confirm and reproduce your discovery on **all** my current test setups, notepad++ 7.5.5, 7.5.9, 7.6, 7.6.2 and 7.6.3, installed as well as portable, both x86 and x64.

it will probably be the same behaviour on **all older versions**, that have a **status bar at the find window**.
(i don't see this character junk on e.g. version 5.9.3, because it is so old, that it didn't have the find status bar implemented yet)
