### ISSUE TITLE
Triple click selecting carriage return and moving to next line

### ISSUE THREAD

**Issue by Protonus** [notepad-plus-plus/notepad-plus-plus#5342]
### Description of the Issue
When triple clicking to select the whole line, the cursor is moving automatically to the start of the next line.  When copying in this state, it's therefore copying the carriage return, and so you end up pasting two lines, instead of one, with the second line blank.  This is causing me headaches when pasting into text entry fields that only show a single input line. 

### Steps to Reproduce the Issue
1.  Open a text doc that contains multiple lines.
2.  Triple click a line of text, one that has another line of text after it.  
3.  Note that the whole line of text is selected, and then the cursor is moved to the next line
4.  CTRL+C or right click->Copy, to copy
5.  Paste elsewhere.  Note that the desired line is pasted, along with a new line, that's blank.

### Expected Behavior
Only have the current line the cursor is in, copied, after triple click.  Only one line should be pasted then.

### Actual Behavior
An extra blank line is copied and pasted due to the cursor being moved to the next line on triple click.

### Debug Information
Notepad++ v7.6.3   (64-bit)
Build time : Jan 27 2019 - 17:16:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by sasumner** [comment]
This might be a six-of-one, half-a-dozen-of-the-other situation.  If it worked the way you desire, there would be others that favor current behavior (and that includes me).  I'd leave it alone.

**Comment by Protonus** [comment]
Perhaps a setting could be added then for this behavior? Even if it defaulted to current behavior I could at least fix it then.

**Comment by sasumner** [comment]
Let's let the implementers decide on that, of course.  Meanwhile, have you considered scripting a solution? I don't know that you could assign as scripted solution to the triple-click, but you could certainly tie it to a keycombination of your choosing.

**Comment by MetaChuh** [comment]
@Protonus 

it is by design to select eol on a triple-click.
this main function will not be changed, as many users rely on this behaviour.
this is used e.g. to quickly copy paste specific log file entries to a new tab for further analysation.

you can however, perform a line copy, at cursor position, without eol, even quicker,
using the <kbd>shift</kbd>+<kbd>ctrl</kbd>+<kbd>c</kbd> macro:

* open `%AppData%\Notepad++\shortcuts.xml` in notepad++.
* paste the following code to your `<Macros>` section:

```
        <Macro name="Copy Line" Ctrl="yes" Alt="no" Shift="yes" Key="67">
            <Action type="0" message="2453" wParam="0" lParam="0" sParam="" />
            <Action type="0" message="2453" wParam="0" lParam="0" sParam="" />
            <Action type="0" message="2453" wParam="0" lParam="0" sParam="" />
            <Action type="0" message="2452" wParam="0" lParam="0" sParam="" />
            <Action type="0" message="2452" wParam="0" lParam="0" sParam="" />
            <Action type="0" message="2452" wParam="0" lParam="0" sParam="" />
            <Action type="0" message="2178" wParam="0" lParam="0" sParam="" />
        </Macro>
```

* save `shortcuts.xml`.
* restart notepad++.

now regardless of where you put your cursor in any line, <kbd>shift</kbd>+<kbd>ctrl</kbd>+<kbd>c</kbd> will trim-select the whole line and copy it to your clipboard.
paste it as usual using <kbd>ctrl</kbd>+<kbd>v</kbd>

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
