### ISSUE TITLE
Unsaved files cannot be dragged to open a new window

### ISSUE THREAD

**Issue by CHN-STUDENT** [notepad-plus-plus/notepad-plus-plus#5344]
### Description of the Issue

A Unsaved files cannot be dragged to open a new window
### Steps to Reproduce the Issue

1.  Open np++ then new a file without saved
2.  Try to drag it tab on second screen and open a new window
3.  The saved file can be dragged then open a new window, but the unsaved file can not do this thing.

### Expected Behavior

![image](https://user-images.githubusercontent.com/21209416/53394384-133e1400-39da-11e9-8752-8f81d64c47e8.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/21209416/53394370-08837f00-39da-11e9-88da-f120611a1e48.png)

**Comment by sasumner** [comment]
Ugh. Save the file first.  Really, unsaved (e.g. "new 4") files are by design supposed to be really REALLY temporary.

**Comment by CHN-STUDENT** [comment]
Ugh. Is it not a bug?

**Comment by sasumner** [comment]
You are free to call it a "bug" if you'd like.

**Comment by Palollo** [comment]
More on the same bug...
Right click in the "new 1" tab: the option "move to new window" is disabled. But it is enabled in saved tabs.

I don't know why it is disabled, because you can get the same objective with a (let's call) "trick":
 1. move one of the saved tabs to a new window,
 2. move the unsaved "new 1" tab to the new window,
 3. move the saved tab back to the first window.

This is the really annoying workaround I need to do when I want to simply open a new window to work on a new document in a different screen/desktop when there is already a document opened in other screen/desktop.

**Comment by sasumner** [comment]
> "move to new window"

I have no such option in my tab right-click menu (localization: English).  Are you using a non-English N++ version and translating what you see in that version's UI to English for purposes of posting here?

**Comment by MetaChuh** [comment]
@CHN-STUDENT 

unsaved new tabs and unsaved edited files can not be moved to another view.
there are technical reasons why this option is also intentionally greyed out at the tab's right click menu on unsaved new tabs, and edited but yet unsaved files. 

such feature will not be implemented, as it can eventually cause data loss.
also the backup/session data can not be used as a theoretically temporary saved data pool, due to the dependency of session and backup settings for unsaved files, and possible data inconsistencies in combination with multiple instances.

some of your current options are:
save your data to safely transfer it to another notepad++ window.
copy/paste your scrap data to a new tab on the other notepad++ window.

many thanks and best regards.

**Comment by Palollo** [comment]
Sorry, the option with English localization is "Move to New Instance".
I am sorry to view this bug is closed. "Technical reasons" many times can be overcomed. May be an option in "File" menu, called "New Instance", just below the "New" option, should be helpful. It shoul be even more helpful in the OS task bar, like the "new tab" and "new window" options of the main browsers.

**Comment by Palollo** [comment]
Just remember: the same result can be achieved with the workaround that I mentioned in my first comment. I hope it can be less tedious.

**Comment by sasumner** [comment]
People:  Just save the file first (as said before). It's not that big of a deal.  And apparently isn't going to be addressed.

**Comment by Palollo** [comment]
Most of the time the new file will never be saved. Let me show you two frequent use cases in my daily work... (they can be helpful to someone)
 - To compare two similar functions that someone has written in the same source code file: the fast way is to open two new tabs in a new instance of NPP, copy-paste each functions on each tab and use compare plugin to do a quick diff. They can be two functions, two pieces of text, two rows of a big table...
 - To clarify a result of some process in raw XML format or JSON, the fast way is to open a new instance in NPP (because the main instance is in another desktop/workspace), copy-paste the long string and use the plugin to quickly auto-insert line breaks and indent lines, then I can see it is an ugly exception :(, and I will close the document when I locate the problematic line in the code ;).

**Comment by rkinnett** [comment]
Closed a long time ago but I'll add my voice anyway to say that this seemingly rudimentary feature would be extremely useful.

**Comment by shodanx2** [comment]
@sasumner 

Hello,

I am investigating multi instance usage and I have to say

I love "not saving files" and it seems to not be possible for a reason related to this current issue

And by "not saving files" I mean, I love that notepad++ does the computer grunt work of actually keeping my unsaved files saved and backed up, including the undo history without me so much as having to think "what name should I give this file and where should I save it"

This create a lot less friction to writing stuff down, similar to the app I am trying to run away from, google keep. I want to stop using it, but it is so convenient to "push ONE button and start writing". Us old people will easily lose idea if we have to "press one button think something else then press another button".

I would say, there's a 25% chance I will lost my idea for every button I have to press that isn't writing my actual idea.

**Comment by JamesFrankel** [comment]
It's very disappointing to see that this bug is not considered a bug.
"Just save your file" is also one of the most dismissive, disrespectful things I've seen in a while.

**Comment by shodanx2** [comment]
One solution could be to auto save into a purpose made "unname saved files folder" where a temporary name, probably based on date and time is saved until the user renames it. It preserve the "just open tab and write" that is free of management aspect while enabling "drag to new window". However I would hope the feature to preserve unsaved changes afterward is preserved as well.

**Comment by JamesFrankel** [comment]
I'm currently working around this by enabling "multi instance mode", but the annoying thing about that is that new files will always be opened in a new instance, rather than opening in the old instance, and having the ability to manually open new instances when needed (like, when I need to view my temporary notes on the second monitor). Yes, I can manually drag the opened saved files into one window, but that's extra steps and therefore, bad for productivity.

Personally, I don't use the session feature nor the 'save unsaved changes' feature. I use notepad++ as a fast text and config file viewer and as a 'notepad' for quick notes. And for that, I need to be able to move around the individual opened notepads freely. And with my quick notes, it's not possible thanks to this bug.

Of course, I understand that development is lot of work and that bug fixes are not to be taken for granted, but I do want to explain the use case for this bug fix and why it should be fixed, especially since there are hacky workarounds around it with multi instance mode, so why not just properly fix the bug?
