### ISSUE TITLE
Wrong detection of ANSI Encoding

### ISSUE THREAD

**Issue by Vlado-99** [notepad-plus-plus/notepad-plus-plus#5355]
### Description of the Issue

When opening existing plain text file, encoded in ANSI Windows-1250, encoding is not correctly detected by Notepad++ 7.6.x (32bit). Detection routine worked well in versions 7.5.9 and older.

Information about OS: Windows 7 Pro x64, fully patched. English GUI, Slovak regional settings, Slovak system locale for non-unicode programs.

### Steps to Reproduce the Issue

1. Create plain text, Windows-1250 encoded file with text ```Päťtýždňové vĺčatá nervózne štekajú na môjho ďatľa v tŕní.``` (This sentence contains all accented Slovak characters.)
2. Open this text file in Notepadd++

### Expected Behavior

Text displayed correctly, Notepadd++ detects file as Windows CR LF, ANSI encoding. This was how version 7.5.9 and previous worked.

### Actual Behavior

Text crippled, characters ť, ž and š displayed as control characters, ľ is displayed as ž. Notepad++ detects file as Windows CR LF, ISO 8859-2. (or 8859-1 if I try another sentences).

### Debug Information

Notepad++ v7.6.3   (32-bit)
Build time : Jan 27 2019 - 17:20:30
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by MetaChuh** [comment]
@Vlado-99 

yes, you are correct.

the implementation of UCharDet 0.0.6 since version 7.6 has caused this.
currently, until a fix is found it is necessary to:
* go to `settings > preferences > misc` and disable `auto detect character encoding`
* go to `settings > preferences > new document` and set your preferred default encoding to e.g windows-1250, as seen at the screenshots below.

![settings - auto detect character encoding](https://i.imgur.com/9SZ5ufh.png)

![Imgur](https://i.imgur.com/vKWOrLL.png)

afaik, fixing this without regressing to the old code, is apparently going to be very difficult, because the identical UCharDet 0.0.6 code behaves completely different on windows, than it does on linux.
(UCharDet 0.0.6 works perfectly on linux)

i believe @CookiePLMonster and @donho have already analysed this, but i, as a user, don't know the status quo of what can be done next.

**Comment by Vlado-99** [comment]
@MetaChuh 
Thank you for the workaround, it works. It's a useful aid.

**Comment by MetaChuh** [comment]
fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/486e2188b2d4f5e897d5ffffa9b3dcd23b3ae2d6
