### ISSUE TITLE
Folder paths with double slashes causing issue

### ISSUE THREAD

**Issue by melban** [notepad-plus-plus/notepad-plus-plus#5368]
### Description of the Issue
When clicking to open a file and pasting in a full path with double slashes results in locked application
c:\\\\

### Steps to Reproduce the Issue
1. File -> Open
2. type C:\\\\
3. Click enter

### Expected Behavior
Navigates to specified folder to pick files

### Actual Behavior
A loop or unforseen action is happening and locks program.

**Comment by MetaChuh** [comment]
@melban 

i can confirm this issue, but only if you are using the old open/save dialog style.

please go to `settings > preferences > default directory` and make sure that `use new style dialog` is activated, as seen at the screenshot below.

![Imgur](https://i.imgur.com/fibS0kv.png)

please retry, after you have activated the new style dialog.
attempting to open `c:\\` as a file, will now give you an expected, invalid file name alert, instead of looping/freezing.

**Comment by sasumner** [comment]
Still, it should be fixed, for the "old style" case. :)

**Comment by MetaChuh** [comment]
@sasumner 

yes, you are absolutely correct, and i had more or less exactly the same sentence written down already.
(my deleted end quote: "but you're right, it should work on the old style dialog too.")

but i hesitated and removed that, as i don't know yet, if any fixing change at the old style dialogue code might get in conflict with it's functionality on wine platforms.

**Comment by melban** [comment]
@MetaChuh When I enabled "use new style" I do not have the issue and am prompted with the dialog box.  Thank you.
