### ISSUE TITLE
Auto-updater is run even when corresponding option is disabled

### ISSUE THREAD

**Issue by Gitoffthelawn** [notepad-plus-plus/notepad-plus-plus#5375]
### Description of the Issue
Auto-updater `gup.exe` is automatically run once in a while even when `Enable notepad++ auto-updater` is unchecked.  I verified that `noUpdate` is set to `yes` in `config.xml`.

### Test Environment
Notepad++ v7.6.3 32-bit **non**-installer package on Win7.

**Comment by MetaChuh** [comment]
@Gitoffthelawn 

yes, you are correct.

the reason is, because gup.exe is used for the built in plugins admin, in addition of being used as the auto updater, due to the close relation of downloading an update and downloading an updated or additional plugin.

a little extra: if you wish to temporarily, or permanently, strip a portable version from data traffic, you can rename gup.exe to gup.ex_, which will also remove the `plugins > plugins admin`, and the `? > update notepad++` menu entries completely.
notepad++ is aware if gup.exe is missing, and will adapt accordingly, without producing any missing file error messages.

thank you for your help and best regards.

**Comment by Gitoffthelawn** [comment]
@MetaChuh 

Thank you for the details.  Much appreciated.

I would like to keep `gup.exe` in place to be able to browse/update plugins, but only have it run on-demand via `plugins > plugins admin`.

Would that be possible?

Thank you again, and best regards to you as well.

**Comment by MetaChuh** [comment]
@Gitoffthelawn 

yes, you can keep gup.exe in place without activity.

as long as auto update is disabled at your portable setup, gup.exe will not be executed automatically.

gup.exe should only be executed by notepad++ under following conditions:
* auto updater is activated.
* a plugin is installed or removed using plugins admin.
* the menu `? > update notepad++` is selected.
* the menu `? > set updater proxy' is selected.

if you are using e.g. [process monitor](https://docs.microsoft.com/de-at/sysinternals/downloads/procmon), to log all process activities, and filter `process name` to `gup.exe`, it should not appear by itself.

note: if you log the activity of notepad++.exe, you will notice rw access from notepad++ to gup.exe.
this is a normal behaviour and necessary to check for it's existence at startup and to verify it's authenticity, but gup.exe will not be executed.

hope that helps and best regards.

**Comment by Gitoffthelawn** [comment]
@MetaChuh Yes, that helps. Thank you!

I think there may be a bug.

> as long as auto update is disabled at your portable setup, gup.exe will not be executed automatically.

I find that N++ tries to run `gup.exe` every couple of weeks, even with auto-update disabled.

> gup.exe should only be executed by notepad++ under following conditions:
>
>      - auto updater is activated.
Definitely not activated.
>        - a plugin is installed or removed using plugins admin.
I'm 90% sure I installed all plugins manually.
>        - the menu ? > update notepad++ is selected.
Never use that.
>        - the menu `? > set updater proxy' is selected.
Never use that either.

**Comment by ChliHug** [comment]
The original description of the issue is similar to what I'm currently experiencing myself. However, I do use the installer version (7.6.6) and instead of `gup.exe` being run I only get the "An updated package is available, do you want to download it? Yes/No" dialog. Here's what I found.

Observed behavior: Unchecking the "Enable Notepad++ auto-updater" option in the "MISC." section of the "Preferences" dialog does not prevent the updater code from running.

As Gitoffthelawn already noted, the option gets properly saved to the config file. It also gets properly restored, as it is still disabled after a restart of Notepad++.

The issues seems to be at startup when the criteria for the decision to run the updater is made. Specifically in the `WinMain` function on lines 367 to 369 of `winmain.cpp`, where the default value of the GUI is loaded into the `doUpdate` variable, which then is used on line 500 to make the auto-update decision. The actual settings from the config file are loaded in on line 382 with `pNppParameters->load();` and there's no further code that updates the `doUpdate` variable with the user-chosen option.

The relevant code of `winmain.cpp` as of this comment:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/1a76bd591370cf86a3b041d7ceb5bf534cc4d9b8/PowerEditor/src/winmain.cpp#L367-L382

I guess that pulling the default value from the GUI was deliberate decision and it should be preserved. There's some code that depends on `doUpdate` between the declaration of it and `pNppParameters->load();`. The first thing that comes to mind is adding something like this after line 382:

```c++
if (!(doFunctionListExport || doPrintAndQuit))
{
	// Now that the parameters have been loaded, check if the user enabled the auto-updater.
	doUpdate = nppGui._autoUpdateOpt._doAutoUpdate;
}
```

Not especially pretty and it's untested, but I think this should fix it.

**Comment by ChliHug** [comment]
Oh, I forgot to mention that a workaround for this is to change the `nextUpdateDate` value in `config.xml` to the next millennium. `nextUpdateDate="30000101"` for example.

To get the updates working again, delete `nextUpdateDate="30000101"` from `config.xml` and Notepad++ will set it to something reasonable again.

**Comment by Gitoffthelawn** [comment]
@MetaChuh Can we re-open this issue since it's now been confirmed and a code change has been proposed?  Thanks!

**Comment by MetaChuh** [comment]
@Gitoffthelawn 

this happened to me too after more testing.
thanks and sorry for not setting `nextUpdateDate` to an older date before.

all portable versions that include gup.exe (versions 7.6.2 to 7.7) will run auto updater at `nextUpdateDate`, even if `noUpdate` is set to `yes`.
the available update dialogue appears, which should not happen using portable versions.

(i for example, have multiple older portable notepad++ versions for testing, all of them have the auto updater disabled by default, but are triggering an update)

<img width="1095" alt="" src="https://user-images.githubusercontent.com/45773305/58861364-84aef200-86ae-11e9-843d-4b343176ee27.png">

**Comment by Gitoffthelawn** [comment]
@MetaChuh Thank you for confirming the bug!

**Comment by ChliHug** [comment]
I think the only difference (at least with this issue) between the installer and non-installer versions is that the non-installer version comes with a `config.xml` with the auto-updater option disabled. The binary is the same which means both will use the this default value.

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/d14cb43e9d3c58d02af97149cd573c81bd862c47/PowerEditor/src/Parameters.h#L857

I used to use the non-installer version and only encountered this issue after switching to the installer version. As you said, `gup.exe` was included in the non-installer version starting with 7.6.2. I must have updated it wrong on my side... should have gotten this earlier.

**Comment by Taschenbuch** [comment]
Please fix this. It is super annoying.

**Comment by rdiez** [comment]
This bug is indeed annoying.

It is still there with Notepad++ 7.8.3.

About the config.xml workarond:

1) The file to edit is:  %APPDATA%\Notepad++\config.xml

2) Do not edit this file when Notepad++ is open, or within Notepad++ itself, because Notepad++ will overwrite it on exit and your changes will be lost.

**Comment by Dean-NC** [comment]
Please fix this bug.  There's no reason to have a bug of this kind for so long in your software.

**Comment by ChliHug** [comment]
Please note that commit f3261f862022a4aa5d14de19a2b56358713bfd95 breaks the -L option.

In [Parameters.cpp:1284](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f3261f862022a4aa5d14de19a2b56358713bfd95/PowerEditor/src/Parameters.cpp#L1284), `NppParameters::load()` checks if the user has selected a different language, but this is dead code now that the parameter loading happens before `_startWithLocFileName` is filled with the argument data in [winmain.cpp:429](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f3261f862022a4aa5d14de19a2b56358713bfd95/PowerEditor/src/winmain.cpp#L429).

**Comment by donho** [comment]
@ChliHug 
Thank you for your heads up. I'll check it.

**Comment by donho** [comment]
@ChliHug Fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/1c55e0daa7c214e14e8025d2346526ecfb2e9221

**Comment by ChliHug** [comment]
The option to disable the auto updater works correctly now for me. Thanks for fixing this.

**Comment by Sharlikran** [comment]
I was just asked to update, AGAIN! as I noted in #7998

**Comment by ChliHug** [comment]
> I was just asked to update, AGAIN! Yet the option is disabled! As I noted in #7998

To narrow down the search for the issue, please provide the following information:

1. With which Notepad++ version did this happen? (Press F1 in Notepad++ to show this info)
2. What is the current `noUpdate` setting in the `config.xml` that your Notepad++ is using? You can find `config.xml` either in the directory of `notepad++.exe` or your AppData directory (`%APPDATA%\Notepad++` which usually expands to `C:\Users\<username>\AppData\Roaming\Notepad++` although your system may be different). Check if the modification date of `config.xml` matches the time you last closed Notepad++ to make sure it's the one you are currently using. The `noUpdate` line should look something like this: `<GUIConfig name="noUpdate" intervalDays="15" nextUpdateDate="20080426">yes</GUIConfig>`
3. Is there any chance Notepad++ was not able to read `config.xml`? Notepad++ enables updates per default and prompts for it if it doesn't find a config file. I could see this happen because of permission issues or a missing network connection if this was offloaded to a network device.

**Comment by Sharlikran** [comment]
![image](https://user-images.githubusercontent.com/1912426/85212385-0d72ed00-b307-11ea-9cef-42f7bd381251.png)

```xml
<GUIConfig name="noUpdate" intervalDays="15" nextUpdateDate="20200705">yes</GUIConfig>
```
![image](https://user-images.githubusercontent.com/1912426/85212421-5fb40e00-b307-11ea-8e30-2548347f6541.png)

# Changed to
```xml
        <GUIConfig name="noUpdate" intervalDays="3650" nextUpdateDate="20300618">yes</GUIConfig>
```
Because apparently it's too hard to code a program to not update when you uncheck the box.

**Comment by ChliHug** [comment]
You are using an old version. This issue was fixed with 7.8.5. I guess the updater didn't work correctly for you (perhaps permission issues? Don't know much about the updater itself). If you care about the fix, you would have to look into what blocks the update or download a newer Notepad++ version manually.

**Comment by Sharlikran** [comment]
@ChliHug well I take it all back and I sincerely apologize. I am also completely confused as to how the updater is not actually updating Notepad++. I'm embarrassed but at the same time, when it updates I just click update.

Now if by any chance there are two copies somewhere, somehow, is there any easy way to find them on windows 7?

**Comment by Gitoffthelawn** [comment]
@Sharlikran 

1. Open a command prompt,
2. Go to the root of the drive where you think Notepad++ may be installed twice.
3. Enter this command: `dir notepad++.exe /a/s`

You will then see the locations of all copies.
