### ISSUE TITLE
Lost all my user-defined languages after upgrade to Notepad++ 7.6.4

### ISSUE THREAD

**Issue by vrubleg** [notepad-plus-plus/notepad-plus-plus#5401]
Upgraded my Notepad++ from v7.6.3 to v7.6.4 (using installer from the official page, as I always did before). All my user-defined languages were removed, only two copies of "Markdown (Default)" are available instead of them.

![image](https://user-images.githubusercontent.com/2157439/54068459-fa492480-425d-11e9-8b17-120d5ea80232.png)

In my case, these options were in non-default state:
- "Don't use %APPDATA%" option was enabled.
- Auto-update was disabled.

Just in case, is it possible to restore my user-defined languages if I don't have a backup? Probably, they were stored in a different file, for example.

**Comment by MetaChuh** [comment]
@vrubleg 

you could have a look at `YourPathTo\Notepad++` and `YourPathTo\Notepad++\userDefineLangs` if it is still there (open all userDefineLang.xml or anyname.xml files you find in notepad++ or another editor, and check if it contains `<UserLang name=...`).
in your case, i don't think it is in `%AppData%\Notepad++` or `%AppData%\Notepad++\ userDefineLangs`, but check there as well.
also check for any `plugins\APIs` leftovers from older versions.

do you remember if you have copied `userDefinedLang-markdown.default.modern.xml`, or an `userDefineLang.xml` that contained markdown, manually, before you updated to 7.6.3 or 7.6.4 ? 

please also give us your debug info, i will try to reproduce your udl disappearance and double markdown experience, by installing 7.6.3 at your custom location with `don't use %AppData%`, creating an udl, and then updating to 7.6.4 after we got your info.

**Comment by vrubleg** [comment]
Debug info:
```
Notepad++ v7.6.4   (32-bit)
Build time : Mar  6 2019 - 02:52:22
Path : C:\Apps\Develop\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll LightExplorer.dll mimeTools.dll NppConverter.dll NppEditorConfig.dll NppExec.dll NppExport.dll NppFTP.dll NppTextFX.dll TabIndentSpaceAlign.dll 
```

> do you remember if you have copied userDefinedLang-markdown.default.modern.xml, or an userDefineLang.xml that contained markdown, manually, before you updated to 7.6.3 or 7.6.4 ?

Do you ask me if I made a backup of these files recently? Unfortunately, no. It seems that there are no any leftovers of my user-defined languages.

FYI, it is possible that the issue is a bit older than I think. I am 100% sure that I was using intensely one of my UDLs in November. That UDL was created a few years ago, and survived a lot of updates of Notepad++. Yesterday I started to work on my old project again, and noticed that all my UDLs are missing. I have updated Notepad++ recently, that's why I thought that it is caused by the latest update. But probably it happened a bit earlier.

**Comment by MetaChuh** [comment]
> FYI, it is possible that the issue is a bit older than I think.

that concurs with my testing. 

i have tested your configuration extensively, to try to reproduce a double markdown udl, as well as to see if any `userDefineLang.xml` get's overwritten under any circumstances.

i have tested all with a blank windows 7 pro x64 vm, using various combinations of updating from 7.6.3 to 7.6.4, as well as from 7.6.2 to 7.6.3 to 7.6.4.

**double `Markdown (Default)` entry:**

this only happens, if you e.g. originally started off with a completely fresh 7.6.3 install, or a `userDefineLang.xml` with your custom udls was not present any more at `C:\Apps\Develop\Notepad++\` before running the 7.6.3 installer.

version 7.6.3 had the `Markdown (Default)` udl in the file `userDefineLang.xml`.
the 7.6.3 installer has copied `userDefineLang.xml` to your `C:\Apps\Develop\Notepad++\` folder, as it did not exist yet.

i then created a test udl, exited notepad++, and installed notepad++ 7.6.4 on top of it.

the test udl was still there, but under this scenario i confirm to get a double entry of `Markdown (Default)`.
one in the file `C:\Apps\Develop\Notepad++\userDefineLang.xml`, as it was there from the 7.6.3 install, and one in the file `C:\Apps\Develop\Notepad++\userDefineLangs\userDefinedLang-markdown.default.modern.xml`, which is the new, multi udl file location, since 7.6.4.

**solution**: move `C:\Apps\Develop\Notepad++\userDefineLang.xml` somewhere else, e.g. your desktop, as it does not contain your own udl's, but just the `Markdown (Default)` of a fresh, or semi fresh 7.6.3 install. then restart notepad++.
you can delete it, as soon as you are sure, that you don't need it again.

**missing custom udls after updating to 7.6.4:**

i was not able to reproduce any udl file deletion or automatic replacing of an existing `C:\Apps\Develop\Notepad++\userDefineLang.xml` under any testing circumstances. 
regardless if starting with 7.6.3 and upgrading it to 7.6.4, as well as starting from 7.6.2, upgrading to 7.6.3, and then to 7.6.4.

**hopefully possible solution:**
the only thing i can recommend right now, is to search on all your drives for any old `userDefineLang.xml` files.
hopefully you have just moved your udl file manually somewhere, when you started off upgrading your older 7.5.x. 🙏

-----

**my testing debug infos:**

Notepad++ v7.6.2   (32-bit)
Build time : Jan  1 2019 - 00:00:08
Path : C:\Apps\Develop\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

-----

Notepad++ v7.6.3   (32-bit)
Build time : Jan 27 2019 - 17:20:30
Path : C:\Apps\Develop\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

-----

Notepad++ v7.6.4   (32-bit)
Build time : Mar  6 2019 - 02:52:22
Path : C:\Apps\Develop\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by vrubleg** [comment]
Oh, probably it was caused by disastrous upgrade to v7.6.0. It was released in the middle of November, and I remember that it caused a lot of issues (disappeared plugins, etc.)

As soon as the issue is not reproducible on the latest installers, I close the issue.
