### ISSUE TITLE
F7 key no longer toggles

### ISSUE THREAD

**Issue by DavidHaslam** [notepad-plus-plus/notepad-plus-plus#5412]
Notepad++ version 7.6.4

The search results pane no longer closes when the F7 key is pressed. 

F7 opens the search results - but no longer is this pane a full screen view. 

A subsequent F7 keypress merely changes the colour of the pane title bar.

**Comment by MetaChuh** [comment]
@DavidHaslam 

this is by design.
f7 will toggle focus between the search results and the editor window, to quickly switch between editing and results with a key press.
this behaviour is the same on all previous versions.

-----

```
general notes:

please close your issue as soon as you are satisfied,
to help keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and first
search if a related topics exists. you are welcome to post at either an eventually similar
topic, or create a new topic at Help Wanted or General Discussion of your choice.

```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
