### ISSUE TITLE
Auto-Updater not finding anything newer than 7.5.9

### ISSUE THREAD

**Issue by KommX** [notepad-plus-plus/notepad-plus-plus#5420]
### Description of the Issue

This is a follow-up to #5417 which was closed for unknown reason.

When you've installed version 7.5.9, neither auto-update nor manual update via ? --> Update Notepad++ will let you see/install anything newer.
In the release notes of 7.6 (https://notepad-plus-plus.org/news/notepad-7.6-released.html) it was stated that 

> Auto-updater will be triggered in few days if there's no critical issue found.

- Has there been found a critical issue in 7.6.0 or newer?
- I guess, a _few days_ have passed since the release of 7.5.9 (October 15th, 2018), right?
- Is it your intention to keep the users on 7.5.9?

### Steps to Reproduce the Issue

1. Install 7.5.9.
2. Menu --> ? --> Update Notepad++

### Expected Behavior

I expect an opportunity to install 7.6.4 or at least something newer than 7.5.9.

### Actual Behavior

Notepad++ behaves as if 7.5.9 is the most current version.

### Debug Information

Notepad++ v7.5.9   (64-bit)
Build time : Oct 14 2018 - 15:19:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by sasumner** [comment]
Dude, chillax.  Become informed.  Read some stuff.  Notepad++ is undergoing major revisions in its plugin-handling structure.  Uninformed updates (gee, there's a new release--gotta do it) can result in extreme undesirable results.  All auto-updater behavior will be (presumably) restored when the upheaval's dust has settled. In the meantime find something more important to chew on. :)

**Comment by MetaChuh** [comment]
@KommX 

the updater is currently set to 7.5.9. as a max for various technical and supporting reasons, like the plugins structure mentioned by @sasumner and other concerns.

an update will be triggered as soon as it seems fit for the lead developer and eventual technical and supportive concerns have been minimised or cleared.
this approach has worked very well in the past and will serve us well in the future.

if you like to now more in advance:
usually all users at the [notepad++ community](https://notepad-plus-plus.org/community) will get a selection of relevant information from the developers prior to a release, to ensure that as many users as possible are able to help other users on as many questions as possible.

this shared information and the communtity forum also serves as attempt to prevent issues like this to be submitted here, in order not to fill up the project's issue tracker.

note:
if you want to check which updates are available for a specific notepad++ version, without the need of having this specific notepad++ version installed and/or fired up, please open your browser and enter the following, configurable example updater url:
[`https://notepad-plus-plus.org/update/getDownloadUrl.php?version=7.58&param=x64`](https://notepad-plus-plus.org/update/getDownloadUrl.php?version=7.58&param=x64)

usage:
* the `version` get query has to be written with a single period, so you have to write it as `7.64` for notepad++ version 7.6.4
* the `param` query, which carries the architecture information can currently be `x86` or `x64`

if you like you can read and learn more about the "guts" of notepad++ at the
[>>> notepad++ community forum <<<](https://notepad-plus-plus.org/community).

visiting the community and reading as much as you can, might also be useful, because as you seem very passionate about newer notepad++ releases, you can share your passion, by helping to assist and provide answers to notepad++ users that are in need, once you have learned more about the inner life of newer notepad++ releases, and memorised some of the available solutions and workarounds for specific needs.
(don't worry about the amount: yes, there are a few million notepad++ users all around the world, but only a few of them need help, compared to that scale)

i hope this information will serve you well, and you have been provided with enough understandable information to close this issue yourself.

**Comment by KommX** [comment]
@MetaChuh 
Thanks a lot for the information!
Maybe it would have been clearer to me, if there is a sentence or two on the 7.6 release notes (https://notepad-plus-plus.org/news/notepad-7.6-released.html) instead of writing

> Auto-updater will be triggered in few days if there's no critical issue found.
which was/is misleading in this case.

**Comment by UweKeim** [comment]
Came here through Google, because I didn't understand why new versions are not detected anymore.
