### ISSUE TITLE
Feature Request: Launch unsaved file in browser

### ISSUE THREAD

**Issue by needfulthing** [notepad-plus-plus/notepad-plus-plus#5423]
It would be nice if NPP could launch unsaved files in a browser by saving them to a temp location and calling the correspondent file URL. Currently it fails in trying to open something like "file:///C:/Program%20Files%20(x86)/Notepad++/new%207"

**Comment by MetaChuh** [comment]
currently we will not implement that due to various technical reasons and dependencies of e.g. the backup settings.
please save your file before attempting to open it in a browser.

as a better alterative, you could use the [Preview HTML plugin](http://chiselapp.com/user/vor0nwe/repository/npp_preview/home), which features live preview rendering of your unsaved html code, while you are typing.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
