### ISSUE TITLE
Drag tab switches document sometimes

### ISSUE THREAD

**Issue by peso** [notepad-plus-plus/notepad-plus-plus#5450]
### Description of the Issue

If you enable multi-line tab bar and have enough documents open to have two lines, then the document you are dragging may suddenly be another document. This happens exactly in the case described in issue #2771 here with long and short document names.

### Steps to Reproduce the Issue

1. Enable multi-line tab bar under Settings -> Preferences -> General
2. Open enough documents to have two liens of tab bar
3. Select a document with a short name, and drag it around for a few seconds. Do not let go of the mouse button.

### Expected Behavior

That the document being dragged would still be dragged.

### Actual Behavior

The original tab is dropped somewhere and another is picked up to be dragged .

### Debug Information

Notepad++: version 7.6.4 (64-bit)
OS: Windows 10

**Comment by weirdalsuperfan** [comment]
Might also be related to #3055

I also get this problem when Word Wrap is turned on (is that another name for "multi-line tab bar?"). I just discovered Word Wrap and was really happy to finally have this functionality, but since it breaks tab dragging (and dropping between views), it would at least be nice if there were a keyboard shortcut for Word Wrap so it could be toggled quickly when reorganizing tabs.

This seems to have been an issue since at least 2017. No idea why it hasn't been fixed.
### Debug Information
Notepad++: version 7.6.6 (64-bit)
OS: Windows 10

**Comment by CurbedLarry** [comment]
This drives me mad on a daily basis!

_Notepad++ v7.7 32bit on Windows 10_

**Comment by AngryGamer** [comment]
This regression (along with Issue[#5072](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5072)) is caused by PR[#4886](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/4886).

The problem PR[#4886](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/4886) allegedly fixes (Issue[#4885](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4885)) is alleged to be "_always_ reproduc[ible]" but I've never experienced it. Too bad @Wurstbrotc4 never provided any debug information. I'm curious what OS he was using and/or whether he was using a compatibility layer  like WINE.

**Comment by CurbedLarry** [comment]
Multi-line makes no difference.  Seems to only happen when the tab you're dragging is shorter than the one you try to drag over.  Focus/selection flips as soon as the mouse crosses the boundary between them.

After the flip you can keep dragging the tab wherever you want, no further flips.  Of course it's not the tab you wanted to move.

Problem is when the drag is initiated or the first movement.  Hope this helps.

**Comment by AngryGamer** [comment]
@peso @TroudhuK @weirdalsuperfan @CurbedLarry 

Test the binary with PR#4886 reverted. Here's appveyor artifacts for [x64](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/25276260/job/486pspl565jm781a/artifacts) and [x86](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/25276260/job/eap5rijghqu49pse/artifacts). Do not replace/copy SciLexer because certificate is not signed.
