### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by mkocourek** [notepad-plus-plus/notepad-plus-plus#5454]
### Description of the Issue
Download this .txt file [priklad.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3000454/priklad.txt) (should be in UTF-8) and try to open it with N++. I've tried to change every single encoding but the file is still displaying incorrectly.
When I open it with Windows Notepad, PhpStorm... (any other editor), it displays correctly.

What's wrong with N++?

PS: I'm here to report a bug only. :)

**Comment by Faq** [comment]
ref #5414

**Comment by MetaChuh** [comment]
can be closed with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/486e2188b2d4f5e897d5ffffa9b3dcd23b3ae2d6

@mkocourek 

thank you for providing us with your original file and detailed information.

we can reproduce and confirm, that your czech utf-8 file with emojis, was detected incorrectly as tis-620 on notepad++ versions 7.6.0 to 7.6.4, and you can't set it manually back to utf-8 on those versions.

**note:** a fix for your issue has already been committed by the lead developer.
i have verified that the fix works on your specific file. the fixed version will open your file correctly as utf-8.
this fix is currently scheduled for the next notepad++ 7.6.5 release.

if you are already on notepad 7.6.4. and you need a pre release fixed version of notepad++ for testing sooner, please provide us with your current notepad++ debug information either here, or at the [notepad++ community forum](https://notepad-plus-plus.org/community/) as soon as this issue is marked as closed.
(you can find your debug information at the notepad++ menu `? > debug info... > copy debug info into clipboard`)

please also feel free to visit us at the notepad++ community forum, if you have any other notepad++ questions.
