### ISSUE TITLE
Freeze when opening a folder

### ISSUE THREAD

**Issue by Marnix0810** [notepad-plus-plus/notepad-plus-plus#5470]
Freeze when navigated to "C:\Windows\Downloaded Program Files\" in 'open file...'.

this is because 'Downloaded Program Files' is a link to Control Panel, so this can be fixed with a message box saying 'this is not a folder'.

**Comment by MetaChuh** [comment]
@Marnix0810 

you did not provide us with your debug information, as shown by the template when creating a new issue, but i suppose you are on windows 10.

you have to go to the notepad++ menu `settings > preferences > default directory` and enable `use new style dialog`, as seen at the screenshot below.
(this setting is the default setting since 7.6.4.)

![Imgur](https://i.imgur.com/fibS0kv.png)

-----

general note:
please help us to keep the notepad++ issue tracker clean, by marking your issue as solved, as soon as your issue has been solved with satisfaction.

**Comment by donho** [comment]
Closed due to the absence of information.
