### ISSUE TITLE
Infinite internal loop on large scale Search / Replace

### ISSUE THREAD

**Issue by SMeyerTX** [notepad-plus-plus/notepad-plus-plus#5471]
Search / Replace of Tab (extended \t) with Vertical Bar (|) in a large tab delimited text file (40.11MB - 135K lines with 169 tabs per line) appears to enter an infinite loop.  Task Manager shows continuous memory allocation by the Notepad++ process until the system locks.

Notepad++ v7.5.9 (32-bit)
Build time : Oct 14 2018 - 15:02:52
Windows 10 Pro (64-bit)
Intel Core i7 CPU w/ 32GB RAM

To reproduce, create a large tab delimited text file (40.11MB - 135K lines with 169 tabs per line) then Search for and Replace tab (extended \t) character with a vertical bar (|).

Note: This did not occur in previous versions.  While I have not attempted this process in the last few months, I used to be able to do so using Notepad++ without problem with the exact same file.

**Comment by MetaChuh** [comment]
welcome to the notepad++ issue tracker, @SMeyerTX 

i can not reproduce your issue on any notepad++ version from 7.6.5rc2 64 bit down to 7.5.5. 32 bit.

i've created and attached a test file with 135'000 lines, each line containing 170 numbers as data and separated by 169 tabs, making a total of 22'815'000 tabs.
[#5471 SMeyerTX, replace 135000 lines, 169 tabs per line.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3026274/5471.SMeyerTX.replace.135000.lines.169.tabs.per.line.zip)

both extended replace and regex replace work as expected, as seen at the screenshots below.

**important note: on a medium to high end system, the replace will take appx. 25 minutes, which translates to a normal value of appx. 15210 replaces per second.**

extended replace result:
![Imgur](https://i.imgur.com/3hWU90e.png)

regex replace result:
![Imgur](https://i.imgur.com/nlPWjhe.png)

this behaviour might be caused by a plugin and is not related to notepad++ itself.
unfortunately we do not have your debug information, so we don't really know what plugins you might have.

please download the portable, independent notepad++ 7.6.4, which does not contain plugins that can cause this and does not require any installation, as it usually helps to find the culprit faster:

* download the notepad++ 7.6.4. portable version from [>>> here <<<](https://notepad-plus-plus.org/repository/7.x/7.6.4/npp.7.6.4.bin.x64.zip).
(the portable version runs completely independent and isolated from your installed version. all custom settings, as well as anything you might want to try at the portable version, will not modify your installed version)

* extract `npp.7.6.4.bin.x64.zip` to e.g. your desktop.

* open the extracted `npp.7.6.4.bin.x64` folder and start this portable version by double-clicking on `notepad++.exe` inside this folder.
(note: notepad++.exe will just be seen as notepad++, if you have enabled to hide all known file extensions at your explorer settings)

after that, please close this non notepad++ code related issue, and visit us at the
[notepad++ community forum](https://notepad-plus-plus.org/community/).
we will continue this support, or any other questions you might have, over there, at either the category help wanted, or general discussion.
(no extra account is required, you can use your current github account to sign in)

best regards

-----

```
general notes:

please mark your issue as solved, as soon as you are satisfied, to help keeping the
notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
```

**Comment by SMeyerTX** [comment]
Just as a follow up...  Very high end system.  No plugins.  Even tried with NP++ as the only active foreground program.  Gave up after 45 minutes.  Have since moved to a quicker method anyway.

Thanks for investigating.

I consider the issue closed since there is a simple work around on my part.

**Comment by sasumner** [comment]
It would still be great to have the original file to test with, if that is possible...

**Comment by SMeyerTX** [comment]
Having been in software development for almost 40 years, I appreciate 
the difficulty of reproducing a situation as the challenge in 
troubleshooting.  Unfortunately, the file is official government data 
which cannot be shared.

Thanks anyway.


At 09:48 AM 03/31/2019 -0700, sasumner wrote:
>It would still be great to have the original file to test with, if 
>that is possible...
