### ISSUE TITLE
Word wrap end line

### ISSUE THREAD

**Issue by lsansan** [notepad-plus-plus/notepad-plus-plus#5478]
### Description of the Issue

Incorrect cursor position with word wrap view option enabled.

If you type a long word that can't fit in a single line with "word wrap" view enabled and you press "End" key to go to the end of the line. The cursor goes to the second-to-last character of the line

### Steps to Reproduce the Issue

1. Enable word wrap option in the View menu
2. Type anything long enough so that it can't fit in a single line with no spaces. 
3. Go to the beginning of the line with "Home" key
4. Go to the end of the line with "End" key
5. The cursor position is before the last character of the line

### Expected Behavior

The cursor position should be after the last character of the line

### Actual Behavior

The cursor position is before the last character of the line

**Comment by MetaChuh** [comment]
welcome to the notepad++ issue tracker, @lsansan 

this is an expected behaviour.

please double-tap on your <kbd>home</kbd> key to reach the end of a wrapped line.
your cursor will be placed after the last character, before the physical end of line.

a single tap on <kbd>home</kbd> will only bring you to the beginning of the last reachable character of a wrapped line. (one cursor position to the right of this position would put your cursor at the beginning of the next segment of a wrapped line.)

same is valid for the <kbd>home</kbd> key. please press <kbd>home</kbd> twice to reach the physical beginning of the line if you are not on the first segment of the wrapped line.

best regards

-----

```
general notes:

please close your issue as soon as you are satisfied,
to help keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and first
search if a related topics exists. you are welcome to post at either an eventually similar
topic, or create a new topic at Help Wanted or General Discussion of your choice.

```
<kbd>https://notepad-plus-plus.org/community/</kbd>

**Comment by sasumner** [comment]
@MetaChuh 

Interestingly, when I read the "email" version of your post, it was all about "home", confusing me very much:

![image](https://user-images.githubusercontent.com/30118311/55409346-dfea2a00-552f-11e9-85eb-1a51fd5fad71.png)

**Comment by MetaChuh** [comment]
yes, my sincere apologies @sasumner 

this happened while copy pasting, as many buttons are pre-made text fragments, like the answers.
i saw that after carelessly hitting submit, but not before, hence the immediately edited version afterwards.

i will try to not let such thing happen again, sorry. 🙏

**Comment by sasumner** [comment]
Haha. Okay, okay...didn't notice the editing. Thought it was something odd being done with those fancy home / end buttons of yours and the github software. LOL

**Comment by lsansan** [comment]
Thank you @MetaChuh for your reply. Windows Notepad works different but it is ok. This is a different tool and it is more powerful.

BTW: I didn't know the double tap option
