### ISSUE TITLE
New "Save" dialog style should default to "*.txt" not to "*.*" 【7.6.6】

### ISSUE THREAD

**Issue by amwei** [notepad-plus-plus/notepad-plus-plus#5485]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by MetaChuh** [comment]
welcome to the notepad++ issue tracker, @amwei 

to set your default to *.txt for new files on 7.6.6, please go to `settings > preferences > default directory` and disable `use new style dialog`.

note: the new style dialog `*.*` default file mask is by design, as the majority of users are editing other file types than plain txt files, e.g.: cpp, php, ini, conf, etc.

-----

```
general notes:

please close your issue as soon as you are satisfied,
to help keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and first
search if a related topics exists. you are welcome to post at either an eventually similar
topic, or create a new topic at Help Wanted or General Discussion of your choice.

```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by amwei** [comment]
thanks

**Comment by sasumner** [comment]
@MetaChuh For your "general notes" boilerplate, maybe you want to add "please do some searching of the issues to see if your issue is existing (there are SO many that it likely IS !) before creating a brand-new, possibly duplicate one".  My 2c.

**Comment by MetaChuh** [comment]
> My 2c.

you are making me very rich 😉
consider it done 👍
