### ISSUE TITLE
Copy copies wrong word in Arabic

### ISSUE THREAD

**Issue by DJDoena** [notepad-plus-plus/notepad-plus-plus#5504]
This is my name just for fun in arabic:

كارستن سشرامم

It consists of two words:

كارستن
سشرامم

When you paste them as one line into Npp and then select the first one (which is the right one) and press copy, it will put the unselected second one (the left one) into the clipboard (and vice versa)

Video demonstrating the issue: https://youtu.be/vOgwZRBrqNw

Issue is the same as described here which was closed without fix: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/500

Still persists in 7.6.6

**Comment by MetaChuh** [comment]
@DJDoena 

you would have to use rtl mode for rtl writing as seen at the screencast below, as this is caused by the difference between rendering and physical order.

this is a known limitation of the scintilla component.
unfortunately scintilla is an external project, so you will have to file your issue at the [<kbd>scintilla bug tracker</kbd>](https://sourceforge.net/p/scintilla/bugs/).
we apologise for that.

note: you will experience [more issues](https://sourceforge.net/p/scintilla/bugs/2032/) than just copy paste using ltr mode with rtl texts, so i suggest it's best not do use ltr for rtl when using notepad++.

![#5504 arabic rtl](https://user-images.githubusercontent.com/45773305/55830449-41526000-5b11-11e9-911d-f455bc883bc8.gif)

-----
```
general notes:

please close your issues as soon as you are satisfied,
to help keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if a related topics exists. you are welcome to post at either an eventually similar
topic, or create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
