### ISSUE TITLE
Folded Blocks are not Automatically Saved on Exit

### ISSUE THREAD

**Issue by Yay295** [notepad-plus-plus/notepad-plus-plus#5525]
### Description of the Issue
Blocks that are folded/collapsed will be reopened after closing and reopening N++.

### Steps to Reproduce the Issue
1. Open a file in N++. I had the changelog file open since this was a fresh install, but it doesn't matter what the file is.
2. Open a code file in N++.
3. Collapse a block in the code file.
4. Wait for N++'s session to auto-save.
5. Close N++.
6. Open N++.

### Expected Behavior
The blocks I folded should still be folded.

### Actual Behavior
The blocks I folded are not folded.

### Debug Information

Tested with a fresh install of v7.6.6 on 64bit Windows 10.

### Additional Note

This also occurs if you manually save the session, close the files, and then load the manually saved session.

**Comment by YakovL** [comment]
This is not an accurate description: in some files, block folding is saved in the session and restored on reopen.

I've described one particular case when block folding is not saved here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1454#issuecomment-375963334 And what I think I should retest is: are the folded states saved in the session file in that case? Because the problem can be with session saving and/or session restoring.

So I really encourage you to do some testing, extract a minimal reproducible example like I did – and may be we'll generalize the case a bit and help guys fix this at last.

**Comment by donho** [comment]
I did your code, and set it in Python:
```
. one
 . two
```
I folded it and exit Notepad++ without even save the file.
I launch Notepad++ again then unsaved document with the python text opened and text is folded as the session before.
My debug info is:
```
Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 
```

**Comment by donho** [comment]
I also saved the python file, always folded, and save a session manually, closed all files, relaunch Notepad++ and load saved session manually - it restored the fold as expected.

**Comment by YakovL** [comment]
@donho have you saved the file with .txt extension?

If so, I can retest this in the latest n++, I'd just like to be sure you failed to reproduce the issue – I'm a bit lazy because I have a number of n++ windows each with a number of tabs, so it will take time to reopen those. Yeah, a session for multiple n++ windows would be nice ;)

**Comment by donho** [comment]
![image](https://user-images.githubusercontent.com/90293/56098260-ed73bc80-5efe-11e9-91d4-989d64ffb021.png)

**Comment by donho** [comment]
@Yay295 Test it with the newest version please.
If it doesn't work, please provide the detail info for reproducing it, as well your debug info.

**Comment by YakovL** [comment]
@donho ok, I'll do this; yet, your screenshot shows that you haven't tried what I described: file extension should be .txt, but syntax should be set to python

**Comment by Yay295** [comment]
@donho I tested with version 7.6.6, as I wrote in my initial post. Which newer version do you have that I need to test with?

**Comment by Yay295** [comment]
I took some pictures for you since it seems you didn't read the steps I wrote before.

Open N++
![00](https://user-images.githubusercontent.com/8922038/56100682-754ace00-5ee1-11e9-88ea-1c21aaa195a9.jpg)

Create a new file
![01](https://user-images.githubusercontent.com/8922038/56100692-8f84ac00-5ee1-11e9-9640-47a4d83646ea.jpg)

Put some code in the new file
![02](https://user-images.githubusercontent.com/8922038/56100694-93b0c980-5ee1-11e9-9af1-75c23ffefe3c.jpg)

Change the language of the file to match the code
![03](https://user-images.githubusercontent.com/8922038/56100696-a1664f00-5ee1-11e9-964a-4c24fca2490b.jpg)

Collapse the block of code in the file
![04](https://user-images.githubusercontent.com/8922038/56100700-ae833e00-5ee1-11e9-84d2-070bbd3c2d99.jpg)

Save the file somewhere
![05](https://user-images.githubusercontent.com/8922038/56100706-bcd15a00-5ee1-11e9-881b-37c588dafe1d.jpg)

Close N++
![06](https://user-images.githubusercontent.com/8922038/56100708-c65ac200-5ee1-11e9-98b2-102c40f9b3bf.jpg)

Open N++ and notice that the code block is not collapsed
![07](https://user-images.githubusercontent.com/8922038/56100714-d377b100-5ee1-11e9-873d-f0eaaf1ba8de.jpg)

picture of the debugging information
![17](https://user-images.githubusercontent.com/8922038/56100721-e7231780-5ee1-11e9-9be6-c57112c30e00.jpg)

text of the debugging information
```
Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

**Comment by Yay295** [comment]
and again manually saving the session

Click the Save Session menu item
![08](https://user-images.githubusercontent.com/8922038/56100749-27829580-5ee2-11e9-9282-2456ba67aaec.jpg)

Save the session to a file somewhere
![09](https://user-images.githubusercontent.com/8922038/56100759-41bc7380-5ee2-11e9-86ee-35c34faf0bb4.jpg)

Open the session file to see what it says
![12](https://user-images.githubusercontent.com/8922038/56100768-5dc01500-5ee2-11e9-94d4-00d415ab334c.jpg)

Close some files
![13](https://user-images.githubusercontent.com/8922038/56100782-9e1f9300-5ee2-11e9-8d5c-a6c472807861.jpg)

Click the Load Session menu item
![14](https://user-images.githubusercontent.com/8922038/56100789-ac6daf00-5ee2-11e9-9a3e-ceb4dd0c6322.jpg)

Select the session file you saved earlier
![15](https://user-images.githubusercontent.com/8922038/56100795-b8597100-5ee2-11e9-9be4-135a7568d72a.jpg)

Notice that the previously collapsed block is not collapsed
![16](https://user-images.githubusercontent.com/8922038/56100803-c6a78d00-5ee2-11e9-9f9b-5b179f846c08.jpg)

**Comment by donho** [comment]
@YakovL 
![image](https://user-images.githubusercontent.com/90293/56101197-d4c8ce00-5f21-11e9-872b-3e7965963ff6.png)

@Yay295 
I did save session then load it, it still works.

**Comment by Yay295** [comment]
Okay, but that doesn't mean there isn't a bug. It just means there's some difference between your install and my install that makes it work for you and not for me.

**Comment by YakovL** [comment]
Ok, finally I took my time and retested this. Now on n++ 7.6.6. The steps to reproduce are almost the same as [before](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1454#issuecomment-375963334).

1. create empty test2.txt and test1.txt with this content:

       . one
        . two

2. open those in the main n++ window (be sure that "Backup"→"remember current session for next launch" is enabled and if we close the window and reopen it, the same 2 files are loaded). Be sure that test2.txt is the leftmost tab and test1.txt is to the right from it (otherwise the bug is not reproduced)
3. for test1.txt select Python syntax and fold second line
4. close n++ (doesn't matter whether test1.txt or test2.txt tab was in focus)
5. open n++

**Expected behaviour**: the second line (`. two`) stays folded
**Actual behaviour**: the second line is unfolded (shown normally)

Additional info:
* if I save the session manually to a file, it looks like
```
<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="1">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1" startPos="0" endPos="0" selMode="0" lang="&#x041E;&#x0431;&#x044B;&#x0447;&#x043D;&#x044B;&#x0439; &#x0422;&#x0435;&#x043A;&#x0441;&#x0442;" encoding="-1" userReadOnly="no" filename="D:\path\to\test2.txt" backupFilePath="" originalFileLastModifTimestamp="-314148794" originalFileLastModifTimestampHigh="30736597" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="70845493" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="72" startPos="13" endPos="13" selMode="0" lang="Python" encoding="-1" userReadOnly="no" filename="D:\path\to\test1.txt" backupFilePath="" originalFileLastModifTimestamp="732851233" originalFileLastModifTimestampHigh="30736598" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no">
                <Fold line="0" />
            </File>
        </mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>
```
but if I load that session manually, the second line is still unfolded

* debug info:
Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\1my\tools_and_components\in_use_or_used\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

PS yeah, one of the reasons why I postponed this testing was I was expecting suprises on updating. Indeed, all old plugins got disabled and I had to search a bit and manually reinstall those using [these instructions](https://notepad-plus-plus.org/community/topic/17029/after-installing-update-of-notepad-7-6-2-the-old-plugins-get-removed-how-can-i-preserve-the-old-plugins/2). But the good thing is – I've made this new test for a "clean" n++ 7.6.6, so it should be easier to reproduce.
