### ISSUE TITLE
Plugin Updater not working with BeyondTrust PowerBroker Elevation

### ISSUE THREAD

**Issue by phibu** [notepad-plus-plus/notepad-plus-plus#5532]
### Description of the Issue
Working with PowerBroker Administrative Elevation, the Plugin Manager is not working properly.

Powerbroker enables IT-Admins to remove local admin permissions, and only elevate specific Processes or add an admin-Token to the to-be-elevated Application.

Adding the Token  to Notepad++ is working, however that would give users access to all System Files, which is not wanted.
Elevating the gpup.exe has been working till Version 7.5, with the change to the PluginManager Elevation is no longer working.

If only gpup.exe is elevated, Notepad++ Closes on Updating the Plugin, opens up an explorer Windows and nothing else happens.

### Steps to Reproduce the Issue
Beyond Trust PowerBroker is a requirement

1. Install Notepad++ as Administrator
2.Create Rule in PowerBRoker to grant gpup.exe an Admin Token. 
3. Run Notepad++ as User
4. Try Updating a Plugin

### Expected Behavior
Plugins being updated

### Actual Behavior

Notepad++ Closes 
Windows Explorer Window is being opened
Nothinbg else happens.

### Debug Information
I´m in Contact with PowerBroker Support. They were able to reproduce the Issue, however they have no solution till now.

[https://www.beyondtrust.com/endpoint-privilege-management/desktops](url)

**Comment by MetaChuh** [comment]
@phibu 

unfortunately `Plugin Manager` is an external plugin, which is is not maintained by the notepad++ team.

the external plugin `Plugin Manager` is also not compatible with notepad++ above version 7.5.9.
if you are on a recent and supported version of notepad++, like 7.6.6, the old `Plugin Manager` will not work on any system, and it will not be able to install, or update any plugins.

on newer versions, like 7.6.6, please use the built in `Plugins Admin` instead of 3rd party solutions, to manage your plugins.
(separate spawn process for installing plugins: `updater\GUP.exe`)

if you still would like to continue using `Plugin Manager` with older versions of notepad++, please file an issue at the `Plugin Manager` issue tracker:
https://github.com/bruderstein/nppPluginManager/issues

alternative: you can install a current version of notepad++, in ways that it does not require elevation for any plugin installation or update actions using `Plugins Admin`, also meaning not to require `PowerBroker` for plugin maintenance, as notepad++ or any spawn process, will never need to be elevated.

for details on non admin installations, and/or corporate plugin deployment scripts, please head to our notepad++ community forum and conduct a search, or open a new topic. (link at the bottom)
example topic: [install notepad++ plugin without admin rights](https://notepad-plus-plus.org/community/topic/17232/install-notepad-plugin-without-admin-rights)

many thanks and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
