### ISSUE TITLE
Versions after 7.3.3 crash on startup

### ISSUE THREAD

**Issue by RadioPlanner13** [notepad-plus-plus/notepad-plus-plus#5543]
### Description of the Issue

I cannot upgrade beyond V7.3.3 because NPP crashes on startup.  It creates a dumpfile, which I cannot seem to be able to attach (my Windows7 SP1 Machine opens file but it does not seem to upload).
This happens on Windows 7 64 bit for both NPP 32-bit and 64bit.  I tried this about 3 months ago and same issue arose.  When I tried to upgrade today and it still crashes on startup.  I have also tried to install it on a Windows10 machine with same result.

### Steps to Reproduce the Issue

1.  Download update (either Notepad++ Installer 32-bit x86 or Notepad++ Installer 64-bit x64)
2. Run Installer
3. Start NPP 64 bit which doesn't start (no image visible in taskmanager) .. just a quick flash on screen.
4. On 32 Bit NPP an Error Code messagebox appears as follows:-
Exception Code Details
Code: 0xC000005
Type: Access Violation
Exception Address: 0x00DB3692
In addition a second information box appears stating that the file is too big to open.  I reinstalled V7.3.3 and closed ALL files.  Reintsall V7.6.6 and this "file too big" still appears.  This test completed on Windows7 machine.
5. Reinstall V7.3.3 and issue goes away

### Expected Behavior

Start Normally
### Actual Behavior

Stated above
### Debug Information

Here is the information under the 7.3.3 Help Menu
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck2.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll SpellChecker.dll 

I have Symantec endpoint protection AND Sophos Endpoint protection running on these machines - both provided by Corporate

**Comment by Ekopalypse** [comment]
What about trying to download the official portable version, unzip it and see if you can run it?

**Comment by MetaChuh** [comment]
@RadioPlanner13 

i can not reproduce your issue with versions above 7.3.3 on our test systems.

**please test the following, to verify, if a clean notepad++ would work on your system.**

* download the notepad++ 7.6.6. 64 bit portable version from [>>> here <<<](https://notepad-plus-plus.org/repository/7.x/7.6.6/npp.7.6.6.bin.x64.zip).
(the portable version does not require any installation and runs completely independent and isolated from your installed version. all custom settings, as well as any stuff you might want to try at the portable version, will not modify your installed version)

* extract `npp.7.6.6.bin.x64.zip` to e.g. your desktop.

* **important note:** make sure to close all instances of notepad++ that might be running, before starting the portable version at the next step, to be sure you are using the portable version for this test.

* open the extracted `npp.7.6.6.bin.x64` folder and start this portable version by double-clicking on `notepad++.exe` inside this folder.
(note: notepad++.exe will just be seen as notepad++, if you have enabled to hide all known file extensions at your explorer settings)

* optionally: repeat above with notepad++ 7.6.6. 32 bit portable from [>>> here <<<](https://notepad-plus-plus.org/repository/7.x/7.6.6/npp.7.6.6.bin.zip).

after trying the portable version(s), please visit us at the notepad++ community (link at the bottom), open a topic at `help wanted` with a link to this issue, and we will give our best to help you on your current experience more extensible over there.
(no extra account is needed, just use your github account to sign in)

note: as your issue is not directly related to the notepad++ source code we will close this issue.

thank you for your help and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by RadioPlanner13** [comment]
OK Tried that and I needed to install 7Zip on my Windows10 computer to unzip the 7Z file.  And I couldn't install that either so it is something to do with my configuration (Symantec endpoint protection AND Sophos Endpoint protection for some reason) which I suspect is the root of the problem.  Probably the way the installer operates causes this issue.
Thus you can regard this as closed.
