### ISSUE TITLE
PHP Keywords

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#555]
Some php natives function are missings.
We can add them manually but it reset at each update.

session_name header session_destroy strlen filter_var preg_match substr rand preg_replace filesize round microtime ceil intval array_sort is_numeric is_array asort arsort htmlspecialchars filemtime ksort sort count

**Comment by Rikk** [comment]
Most of these you mentioned are already on 6.8 -- you need to update your `langs.xml` using `langs.model.xml` manually, because Npp doesn't do it automatically (you can delete/rename `langs.xml` so it is recreated from `langs.model.xml`).

I've been adding PHP keywords lately... (eg. #488) (cooking more [at my fork](https://github.com/Rikk/notepad-plus-plus/commits/langs.model)). Will add the ones you mentioned...
Btw, curiously `array_sort` is not on the [list of Array Functions](http://us1.php.net/manual/en/ref.array.php), I think it may be an alias of `sort` (you could use that meanwhile).

**Comment by Jukino** [comment]
I didn't know npp didn't update it automatically, my bad, I was still using list of npp 6.4.
Thanks you.
You can easily get a list of all functions here: http://php.net/manual/en/function.get-defined-functions.php

**Comment by Rikk** [comment]
Thanks for pointing it, will take a look; although probably it doesn't include constants (that are also added to the list).

**Comment by Jukino** [comment]
PHP has function to get lists of constants too: http://php.net/manual/en/function.get-defined-constants.php

**Comment by Rikk** [comment]
:smiley:

**Comment by Jukino** [comment]
Using php 5.4.38
[Constants](http://jukino.ovh/php_constants.php)
[Functions](http://jukino.ovh/php_functions.php)

**Comment by Rikk** [comment]
tomorrow will review, test more php versions(nix/win) and create a pr.
many thanks

**Comment by Rikk** [comment]
Ok, almost done with this [never-ending] job. For now, some conclusion:
Many functions/constants comes from php extensions, but whether they are or are not enabled is something that greatly vary from server to server... With that, we can better find more new keywords using php website lists, for two extra reasons: it lists both keywords of latest and deprecated versions, and we don't need to mess around with server configs enabling extensions (and having every one enabled is almost impossible).
Even being possible to add more keywords, the new list grew almost 60%.

**Comment by Rikk** [comment]
@Jukino I will not create a PR for Npp yet, because I plan to add more keywords soon (and certainly before next release), but you can get the updated file from here:
https://github.com/Rikk/notepad-plus-plus/blob/langs.model/PowerEditor/src/langs.model.xml

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
