### ISSUE TITLE
Notepad++ randomly messes up the encoding of files.

### ISSUE THREAD

**Issue by EAFSC** [notepad-plus-plus/notepad-plus-plus#5552]
The #1 annoyance (actually, I'd say it's far more than an annoyance...) I've had with Notepad++ for all the years I've been using it, with countless reinstalls over countless fresh reinstalls of Windows and many different machines/Windows versions, is that it randomly messes up my text files' encoding.

Without me having done anything in particular, I will one day notice syntax errors with my .php files that weren't there before, because Notepad++ somehow, at some unknown point, for some reason, changed (for example) a "å" character into something bizarre (multiple characters).

I always use UTF-8 and actively select/convert to UTF-8 whenever I get an opportunity. This, however, happens on its own. Not when I convert to or select UTF-8. It just happens. It really frustrates and angers me, because it often forces me to sit and manually retype large amounts of text and symbols, and it breaks my code. It basically makes me feel like I can never trust Notepad++ to not mess with my source code or my text files. I wish at least I could understand *why* it happens!

I have a feeling that it may be happening in relation to me pasting text into the document, but I don't get why or how to avoid it.

**Comment by MetaChuh** [comment]
@EAFSC 

unfortunately you did not fill out the required issue template, but maybe the general character encoding guide will suit you:

your experience is probably caused by the autodetect character encoding feature, which can only estimate an encoding to its closest match.
the lesser information it has, the more probable it is that it will fail.

if you frequently have to handle such cases:

* please go to `settings > preferences > misc` and **disable** `auto detect character encoding` as seen at the screenshot below.

![settings - auto detect character encoding](https://i.imgur.com/9SZ5ufh.png)

* then go to `settings > preferences > new document` and set your preferred default encoding to e.g utf-8 and activate `apply to opened ansi files`, as seen at the screenshot below.

![Imgur](https://i.imgur.com/AarYeSx.png)

after that you will be able to edit and reload your utf-8 files, like your mentioned .php files, without data corruption, and not being interpreted as anything else but utf-8.

many thanks for your help and support.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
