### ISSUE TITLE
More powerful user-defined filename matching for language selection

### ISSUE THREAD

**Issue by wbierman** [notepad-plus-plus/notepad-plus-plus#5553]
### Description of the Issue
Right now in 'Style Configurator' I can specify extensions which I want to be associated with a certain language.  This is great, but sometimes the part of the file I want to match is not the extension.  An example of this is python scripts that are part of a SCons build system.  In this case, I would want to tell Notepad++ to interpret all files named `SCons*` as python.

I can see how introducing this would be difficult from a backward-compatibility standpoint.  That is, if existing user-defined settings start matching against the whole filename it might produce undesirable results.  Perhaps it would be enough to initially allow this option exclusively in the `lang.xml` file as an optional attribute to the `<Language>` tag.

Example:

```xml
<Language name="python" ext="py pyw" wholefile="scons*" commentLine="#">
```

### Expected Behavior
Allow full filename matching for language selection

### Actual Behavior
Currently only the extension is matched

**Comment by MetaChuh** [comment]
@wbierman 

thank you for your feature idea and your knowledge about the difficulty of implementing it.

selecting the programming language based on a file pattern instead of the extension will currently not be implemented at the notepad++ core code.

this could however, be a nice possible feature for 3rd party plugins,
and it could also be done with e.g. a pythonscript running at the pythonscript plugin, as the pythonscript plugin has control of the notepad++ internals.

a good suggestion is, to visit our notepad++ community at the link at the bottom and state your idea for python.
as the community has quite a few python pros, maybe one or two might find it interesting enough to code such a script. 

thank you for your help and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
