### ISSUE TITLE
Backup on save keeps failingy

### ISSUE THREAD

**Issue by mzso** [notepad-plus-plus/notepad-plus-plus#5556]
### Description of the Issue
The setting keeps resetting to "none", from the usual custom backup directory I set (once it somehow changed to creating bak files.)

### Steps to Reproduce the Issue
God knows. I only notice when I need it that it failed a long time ago. In march
Can't imagine why it happens, something like #3298 can't be the case because, that snafu with the pre-existing configuration file is not done for config.xml

### Expected Behavior
Have a reliable backup mechanism.

### Actual Behavior
Backup fails long before I would need it.

**Comment by MetaChuh** [comment]
@mzso 

we can not reproduce your described issue, that `backup on save > simple backup` or `backup on save > verbose backup` is getting disabled automatically under any circumstances.

however, if you have multi-instance enabled, the setting `enable session snapshot and periodic backup` will be disabled by design, as soon as a second notepad++ window is opened, to prevent altering the session backup data from a secondary instance.

if this is your case, please either activate mono instance (disable multi instance), or use one installed version of notepad++ as your main, mono-instance notepad++, with your preferred snapshot and backup settings, and a portable notepad++, which has a completely independent folder and settings location, for your multi instance needs.

if you experience other snapshot settings issues, please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
