### ISSUE TITLE
x64 7.6.6 unknown publisher on Windows

### ISSUE THREAD

**Issue by ShadowLNC** [notepad-plus-plus/notepad-plus-plus#5567]
In 7.6.6, the installer is no longer "signed" in Windows - it does not have a verified publisher.

Is this related to the new GPG signatures? Does the GPG signature prevent having a verified publisher for the executable?

It was surprising to me when NPP suggested the update, but then the installer warned me of an unknown publisher.

(SHA256 checksum `f19f407f0c2ec95f176f09df7816b6382b8ebad7e6d69004221e4a3d078a7add` matches, and no virus detected by Malwarebytes, so I believe it's legitimate, but I was concerned that it no longer lists the publisher.)

**Comment by MetaChuh** [comment]
@ShadowLNC 

yes, this is due to the switch to gpg signatures, which are unfortunately not implemented natively in windows.

you will find more info at: https://notepad-plus-plus.org/news/v7.6.6-with-gpg-signatures.html

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
