### ISSUE TITLE
Error in select text in Right to left languages in ltr view such as arabic or persian

### ISSUE THREAD

**Issue by haftsad** [notepad-plus-plus/notepad-plus-plus#5578]
### Steps to Reproduce the Issue

1. type سلام علیکم
2.double click on سلام to select it
3. you can see its not selected properly and when you copy selection you can see علیکم is copied!
4. in the rtl view this error not appeared.

**Comment by MetaChuh** [comment]
@haftsad 

you would have to use rtl mode for rtl writing as seen at the screencast below, as this is caused by the difference between rendering and physical order.

this is a known limitation of the scintilla component.
unfortunately scintilla is an external project, so you will have to file your issue at the [<kbd>scintilla bug tracker</kbd>](https://sourceforge.net/p/scintilla/bugs/).
we apologise for that.

note: you will experience [more issues](https://sourceforge.net/p/scintilla/bugs/2032/) than just copy paste using ltr mode with rtl texts, so i suggest it's best not do use ltr for rtl when using notepad++ and other scintilla based editors.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if a related topics exists. you are welcome to post at either an eventually similar
topic, or create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
