### ISSUE TITLE
Notepad++ PEs Unsigned 7.6.4.0+

### ISSUE THREAD

**Issue by extremegixxer** [notepad-plus-plus/notepad-plus-plus#5602]
### Description of the Issue

Notepad++ executables are not digitally signed, which causes FP security events from security products.
This happened the first time on v7.6.4.0 and continues to this day on v7.6.6.0. Something seems to have changed during the build flow in regards to the signing of the PEs.

### Steps to Reproduce the Issue

1. Examine Notepad++ version 7.6.3.0 or lower with SysInternal's SigCheck.exe
2. Confirm executables are digitally signed
3. Examine Notepad++ version 7.6.4.0 or higher with SysInternal's SigCheck.exe
4. Notice executables are NOT digitally signed

### Expected Behavior

Notepad++ executables to be digitally signed.
### Actual Behavior

Notepad++ executables are NOT digitally signed
### Debug Information

[SigCheck Results for Notepad++ v7.6.4.0+ Showing Unsigned](https://drive.google.com/open?id=1TftrWZkbWKW2d5Vv_iQAv4Ixoqrq1E92)

[SigCheck Results for Notepad++ v7.6.3.0- Showing Signed](https://drive.google.com/open?id=1DeuFn0I2cxg0iW2leeRpDEqk1zlvsrUH)

**Comment by sasumner** [comment]
Design change.  Things are no longer "signed".  See https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2524#issuecomment-478077154

**Comment by MetaChuh** [comment]
welcome to the notepad++ issue tracker, @extremegixxer 

yes, you are correct.
this is caused by the switch from windows code signing to gpg signatures.
more details at: https://notepad-plus-plus.org/news/v7.6.6-with-gpg-signatures.html

no major and reliable security product will identify any part of notepad++ as a false positive.
virustotal example of notepad++.exe with none of 72 antivirus and malware engines showing a positive: https://www.virustotal.com/#/file/1e573140f4eb5ab3ca9b82b3db1bb80cb30b0218f7eefc159294b9b52c480a5c/detection

the switch from windows code signing to gpg does not elevate a security risk, when downloading from official sources, but it makes users aware to be more precautious.
note: everyone in possession of any windows code signing cert can and often do sign malware, which will not even trigger a windows unknown publisher alert when downloading or executing. once this windows code signing cert is eventually revoked, it is usually already too late.

many thanks for your help and best regards.
