### ISSUE TITLE
Meta: Cleanup of old issues

### ISSUE THREAD

**Issue by Marcono1234** [notepad-plus-plus/notepad-plus-plus#5607]
During the past month @MetaChuh closed multiple old issues. I can understand that you want to get rid of outdated issues since there were indeed cases where bugs have been fixed, but the respective issue report remained open.
However, could a report please be reopened once it is confirmed again?

Or do you really want separate duplicate reports?

**Comment by MetaChuh** [comment]
@Marcono1234 

thank you for asking.

notepad++ has grown to be one of the world wide most widely used and still maintained open source projects during the past sixteen years, and we are only are a very small team, compared to the amount of notepad++ users around the world.
we rely on the help of our community, to re-verify old, unhandled issues using the latest notepad++ releases.

note: before you file your issue `Text fields for text to search and text to replace with can be blank during replacing` #2707 again, which is the only of your closed issues still valid: this enhancement will not be integrated, due to the proven data reliability of the sequential process handling. the search/replace fields will get updated and responsive again, after the search/replace task has finished.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
