### ISSUE TITLE
New Feature for SFZ language

### ISSUE THREAD

**Issue by DJCroG** [notepad-plus-plus/notepad-plus-plus#5608]
### Description of the Issue

I've just recently discovered Sforzando (great xml tool for musicians) and there is even an unofficial plugin for language on the web. Since it is unofficial, I wonder how to have it officially as a language syntax in notepad++? Reference for that is here: https://musescore.org/en/node/99411 
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by chcg** [comment]
Currently that is an UDL (https://ivan-radic.github.io/udl-documentation/) extension. To have builtin support first https://www.scintilla.org/ (the base component for N++) has to support it and then N++ would need an update to that version. I guess that is quite unlikely to happen at least not in a midterm time frame.

**Comment by DJCroG** [comment]
I have no idea what you've just said :-D But ok, the answer is now, go look for another editor that supports it - I just find it awkward that other software does support it without going through some internal bickering and fighting about what's right and what's wrong in Open Source world. Appreciating your answer none the less, thank you!

**Comment by sasumner** [comment]
@DJCroG So let me see if I understand.  You found a great text editor (Notepad++).  Then you found something someone put together to help with musician stuff within Notepad++.  And apparently it works(?).  But you are upset that it isn't built right into Notepad++, so you are abandoning everything instead of using it, when apparently it has value??  That makes little sense to me.

Scintilla = the editing component (a separate project, see https://www.scintilla.org ) at the heart of Notepad++.  Scintilla is used so that Notepad++ (and others like it) can embed a lot of core text editing functionality without reinventing the (text-editing) wheel.  A downside to that is that, for certain features, like language parsing/coloring (called "lexing"), Notepad++ can't really change (or add to) what Scintilla does.  Of course when the Scintilla project people add support for a language, when Notepad++ updates the version of Scintilla that it embeds, it gets the language addition for "free".

UDL = User Defined Language.  Notepad++ allows one to build up a parser for custom languages that haven't (yet) been supported by Scintilla.  They don't become a hardcoded part of Notepad++/Scintilla, but rather are "softcoded" addtions, loaded when the program starts up.  At the user level, you don't really notice the difference between a "hard" language and a "soft" (UDL) language.

**Comment by DJCroG** [comment]
Hi @sasumner! Thanks for taking the time and elaboration, it IS appreciated! 
You got me a bit incorrect there and indeed, I'll continue using Notepad++ as it's a remarkable tool, saved my butt way too many times to mention :-) 
Saying "I'll have to go somewhere else" means exactly that - I'll have to go somewhere else :-) Don't add much to that statement. Reason about the remark is that SFZ is an Open Source and no one maintains it, everyone has their own way of crafting it and since already someone did porting to enchance Notepad++ even for musicians, my report was to put some real beef on it and finally claim the standard. Now, I'll have to go and fiddle with dodgy text editors just to get this (simple, heh!) functionality rather than to use it in a way I am used to with other stuff I already have o nNotepad++. So, see, it's not the flame, it's more of a dissapointment statement as fixing someone else's standards is way above my league - and even now, that I know what scintilla and UDL are, it still makes no difference in actual usage in my, musician, world :-) No flame meant 👍
