### ISSUE TITLE
[Feature Request] Improve usability in Shortcut mapper: Provide a single shortcut edit field

### ISSUE THREAD

**Issue by rillig** [notepad-plus-plus/notepad-plus-plus#5613]
Extracted from #2563:

## Provide a single shortcut edit field

When editing a shortcut, a small dialog is shown.

Consider replacing the three checkboxes and the select box with a single input field where I can enter the shortcut directly.

**Comment by sasumner** [comment]
>replacing the three checkboxes and the select box with a single input field where I can enter the shortcut

Yes. OMG, YES.  Multi-edit had this capability in 1995.

The small dialog is especially clunky when trying to remove Scintilla shortcut assignments (other tabs have a Clear button for this, but the Scintilla tab has the Clear button disabled).  I have to drop down the box and scroll up to "none" (tip: press Home instead of scrolling up); painful.

**Comment by MetaChuh** [comment]
@rillig 

many thanks for your feature request.
as millions of users are used to the current checkbox design, implementing such feature would be like hiding the clutch of a car, from the position drivers are used to have it, to the glove compartment.

for supportive reasons, we will leave it the way it is.

thank you for your help and best regards.
