### ISSUE TITLE
What about Qt?

### ISSUE THREAD

**Issue by MarcoSulla** [notepad-plus-plus/notepad-plus-plus#5618]
Hello. I'm an ex WIndows user and there's only two programs that I miss very much: Notepad++ and WinMerge.

I know that I could use them using Wine, but Wine is a potential vehicle of viruses.

Could you not consider to pass from win32api to Qt? Qt is extremely performant, powerful and it runs everywhere.

Thank you anyway.

**Comment by sasumner** [comment]
close. Close. CLOSE. CLOSE!

**Comment by MarcoSulla** [comment]
@sasumner I appreciate your argumentations against...

**Comment by MetaChuh** [comment]
@MarcoSulla 

there are no present plans for a qt rewrite of notepad++.

thank you for your help and best regards.

**Comment by MarcoSulla** [comment]
Well, I find [Atom](https://atom.io/). It seems much more powerful than Notepad++ itself, and runs on Windows, Linux and Mac.
Thank you anyway.

PS: so long @sasumner

**Comment by GeorgGa** [comment]
I understand this is an already closed issue and their are no plans present of a rewrite of Notepad++, which is fine for me.
Anyways, as I, totally unrelated to this repository, recently heard news about the famous always-has-been-there open-source project [Audacity currently undergoing a major structural change](https://github.com/audacity/audacity#user-content-this-repository-is-currently-undergoing-major-structural-change), I was wondering, could something similar like this be feasible and useful for Notepad++ too?
Project lead Tantacrul also did [a very informative video](https://www.youtube.com/watch?v=QYM3TWf_G38) to the what and why of their efforts, acknowledging both existing long-time users, as well as new users. 
I know projects like [NotepadNext](url) exist, which are trying to resolve some issues, but I feel like this is something contradictory to the main goal of Notepad++ and efforts should be joined.
What are the thoughts on doing something similar to what the Audacity team is trying, to Notepad++? Although I don't think Notepad++ is some sort of hacked together piece of software - I think it is doing well and is well structured - it undeniable has roots in old, but not abandoned, software (Scintilla) and maybe could very well benefit in be put on a future proof and easier to maintain basis.

**Comment by xomx** [comment]
@GeorgGa 
The following is only my personal view, nothing official.

Comparing the situation of Notepad++ and the upcoming Audacity4 is not very appropriate in this case because:
- Audacity 3.x has been already a multi-platform app ([Win, Linux, Mac)](https://www.audacityteam.org/download/)
- if I got it right, the announced v4.0 is a switch from one cross-platform UI framework [wxWidgets](https://en.wikipedia.org/wiki/WxWidgets) to another [Qt](https://en.wikipedia.org/wiki/Qt_(software))
- even when it's a cross-platform to cross-platform transition (so they already have separated the SW own functionality code from the platform dependent one), they "`spent years replacing Audacity internals`" or "`getting to this stage` (means currently only half-finished wxWidgets -> Qt) `required about 4 years` (!) `of refactoring the original codebase`" (quotes are from the Audacity head dev)
- they probably have more active core devs than N++ for such a thing


> I know projects like [NotepadNext](https://github.com/dail8859/NotepadNext) exist, which are trying to resolve some issues, but I feel like this is something contradictory to the main goal of Notepad++

Don't know what is contradictory on the [NotepadNext](https://github.com/dail8859/NotepadNext) ?! It does exactly what this issue is all about - it's a cross-platform Qt re-implementation of Notepad++. It's a nice project, but deserves more active devs (just like this N++ one).

> and efforts should be joined.

Maybe, but this is rather a question for the N++ and N++Next leading devs.

> What are the thoughts on doing something similar to what the Audacity team is trying, to Notepad++?

https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/FAQ#support-for-systems-other-than-the-ms-windows-family

Especially quoted from the above: "`...Due to lack of human resources, there are no plans to porting Notepad++ to other systems...`"

**Comment by Marco-Sulla** [comment]
Not a problem for me, I moved to Sublime Text. Multiplatform, a lot of plugins, very powerful and handy. The only annoying thing it's the reminder to get a pro version...

**Comment by alankilborn** [comment]
@Marco-Sulla said:

>I moved to Sublime Text. Multiplatform, a lot of plugins, very powerful and handy. The only annoying thing it's the reminder to get a pro version...

There is no "pro version" of Sublime Text.  If you mean that it prompts you to buy a license, and you don't, then you are in violation of its terms-of-use.

**Comment by xomx** [comment]
@Marco-Sulla 
Seems you're still looking and not finding in the original editor category :wink: (no offense).

Last time it was the Atom (discontinued, now Pulsar?), a typical JS/Electron-based mastodon, where the main executable file definitely exceeds 100 MB!, now it's the Sublime which is good but a paid one though.
