### ISSUE TITLE
disable "enhancement": after file reload user can still undo.

### ISSUE THREAD

**Issue by dev-101** [notepad-plus-plus/notepad-plus-plus#5626]
Hi, thank you for continuous improvements of Notepad++.

In recent Notepad++ v7.6.5 version you introduced a new feature: undo past reload from disk.

This 'feature' effectively completely destroyed my workflow, and now I feel exactly like [XKCD #1172](https://xkcd.com/1172/).

Please, add option to **disable** this fancy thing in Preferences > Editing. Until then, I have to revert to earlier version.

When I achieve certain 'stage' point, I reload the file, and start new thing. Undo/Redo from that point should revert to my previous point, not whole session.

Additionally, in every software I've ever used, **reload from disk** feature always resets undo/redo history states. This feature should definitely be optional in the Preferences, and not a default counter-intuitive behavior. Please, re-consider it.

Thank you!

**Comment by sasumner** [comment]
Workaround:  *Close* file (ctrl+w) then *Restore Recent Closed File* (shift+ctrl+t).  Maybe make a macro out of those 2 steps?

**Comment by dev-101** [comment]
Hi, thanks, I already know that, but reload from disk function is now rendered useless and redundant. Why is reload from disk even present now? Who will use it instead of simple save? (excluding certain bugs with formatting I've noticed and reported earlier)

**Comment by sasumner** [comment]
@dev-101 ...all good questions, those... :)

**Comment by MetaChuh** [comment]
@dev-101 

undo after file reload has been removed in 7.7, as it caused more problems than advantages.

thanks for your input.

**Comment by sasumner** [comment]
>undo after file reload has been removed in 7.7

Is this the change.log entry that refers to this?:

"Fix a regression of memory issue while reloading a file."

If so, it doesn't really tell the story...

**Comment by MetaChuh** [comment]
@sasumner 

the biggest problem was, that every reload re-populated the undo buffer, regardless if the file itself was modified or not, causing to run out of memory if either done frequently, or reloading huge files.

see here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5595

and here: https://notepad-plus-plus.org/community/topic/17530/performance-hit-due-to-allow-undo-on-reload/3

thanks again to @SinghRajenM and @dinkumoil for extensive testing and suggestions.

**Comment by sasumner** [comment]
@MetaChuh 

Right, I know *THAT* story.  What I didn't know is that 7.7 totally backs out the earlier behavior, and I didn't get that from the change.log entry.  From the change.log entry, I would have thought that the new feature lives on and its "bugs" have now been addressed (I do understand that it is one of those "hard problems to solve").  If I'm confused about that point, other users could be as well?

I'm not going to submit a PR to change the change.log ;)
I guess I was just pointing out that I thought the entry might have been better.
Just another 2c from me...
Of course, everything we all do could be "better"...

**Comment by MetaChuh** [comment]
@sasumner 

you will be more up to date about npp and plugin development, if you visit the community more often.
the issue tracker has only a fraction of the information.

yes, the change log meanings were probably only clear to all of us who tested the release candidates, so we didn't give it another thought, also because we were more focused on testing this huge upgrade version.

(i also bet you would have spotted the typo instantly prior to release, avoiding multiple change.log typo prs 😉)

**Comment by weirdalsuperfan** [comment]
Could you add this feature back as optional (off by default)??? This actually proved extremely useful for me for debugging things and pinpointing regression bugs, and didn't impact my workflow or memory. However, the most recent patch fixed a problem that I really needed fixed (the tab dragging issue), so I feel like I can't really do without either of these things now.

**Comment by AndrewAdov** [comment]
Die, die, die! I have lost three days of the my work! Die!

**Comment by weirdalsuperfan** [comment]
@AndrewAdov when you say "die," do you mean you somehow LOST work because of the existence of undo after reload feature? Or that you lost work because this feature was removed? If the former, can you explain how (and upgrade your notepad++)? If the latter, can you add your support for issue #5813 ?

Can someone explain to me exactly why this feature (especially if optional) causes problems other than potential memory ones?

@MetaChuh why can't this be made optional? I've been using 7.6.6 for over 2 years now with no issue, precisely because this feature is essential for me. And maybe I'm just dumb, but frankly, I don't even understand what kind of workflow the OP is talking about, and if this change was actually just made to accommodate their workflow, even though there are at least 3 people supporting the issue asking to restore this feature as optional (#5813), then do you not think removing this altogether was a bit premature??
