### ISSUE TITLE
Language detection from simple session file w/o lang property is broken (Reopen)

### ISSUE THREAD

**Issue by andry81** [notepad-plus-plus/notepad-plus-plus#5629]
Previous: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5338

I still can repro in 7.6.6 x86 in Windows 7 x64:

Save into the root of the `d:` drive these files:

*111.bat*

```
@echo off

setlocal

set a=1
```

*111.xml*

```
<?xml version="1.0" encoding="utf-8"?>
<NotepadPlus>
    <Session>
        <mainView>
            <File filename="d:\111.bat" />
        </mainView>
    </Session>
</NotepadPlus>
```

Open the notepad++ session from the menu `File->Load Session...` using file `111.xml`.
Observe an uncolored text.

**Comment by bpersonick** [comment]
This is also true when re-loading a instance of NP++ which has files open which, when the Session was closed, were not associated with any particular language type (no extension matched on load) and which a UDL with extension was subsequently added for.

I believe this is likely the intended behavior, they're trying to track the language formatting that is associated with each file on a closed session and continue using it on a reloaded session, which sounds nice in theory, but I'd prefer to have NP++ just re-check the extension and change to the default (in many cases, but yes I see some edge cases where I'd prefer  NPP++ remember and reuse the ones associated).

So it seems maybe the default languages don't get an association to the file in a saved the session, but do on a closed and opened session?  Maybe?  Strange.

Either way, I suggest adding some preferences under the Session Settings to change which behavior you prefer ie (ie: remember language associations in a session file, if language sessions found in session file "use(If present, otherwise work by extension)/Reassociate(use Extension to match Language)/Ignore(Load all as default text)")

**Comment by andry81** [comment]
I don't understand why i have to change anything when it was working in 7.6.1 as expected.

**Comment by MetaChuh** [comment]
@andry81 

this feature has been introduced, to allow reloading of custom language selections on files, when loading sessions, instead of using the file extension.

please set the `lang` property at your custom created session files, to set your desired language.

many thanks and best regards.

**Comment by andry81** [comment]
>please set the lang property at your custom created session files, to set your desired language.
How do you think users can detect the language when the detection feature is on the side of notepad++? That detection becomes pointless with that approach.

**Comment by andry81** [comment]
I can repro this in 8.6.1 x64 in Windows 8 x64.
