### ISSUE TITLE
Syntax highlighting for Tcl missing 8.6 keywords

### ISSUE THREAD

**Issue by urbasus** [notepad-plus-plus/notepad-plus-plus#5640]
### Description of the Issue

Syntax highlighting for Tcl is missing keywords from Tcl/Tk 8.6:
https://www.tcl.tk/man/tcl8.6/TclCmd/contents.htm
https://www.tcl.tk/man/tcl8.6/TkCmd/contents.htm

### Steps to Reproduce the Issue

1. Set syntax highlighting to TCL
2. Type "lassign {1 2} one two"
3. Type other new keywords from Tcl 8.6

### Expected Behavior

lassign and other 8.6 keywords are highlighted

### Actual Behavior

lassign and other 8.6 keywords are not highlighted

**Comment by urbasus** [comment]
I'll fix it myself if having your blessing and support :-)

**Comment by MetaChuh** [comment]
hi @urbasus 

currently you do not need our permission to contribute your missing keyword list for tcl to `langs.model.xml`.

you only need to edit your local `langs.xml`, and once you are satisfied with your local copy's result, learn how to setup and create a pull request at github, by using one of the many (project independent) github guides available.

if you like, this issue will serve as the required reference issue for your pull request.

**note**: we have currently dropped the previously mandatory accepted flag for pull request preceding issues, as the accepted flag on issues abandoned by their authors without committing, was causing confusion months or years later, leading to the question why this issue was accepted back then, if no-one ever worked on it.

it is also currently dropped, because many good and merged pull requests have been committed without the accept label at the issue, receiving the accept or reject label at their finished commit.

this might change in the future, but for now it seems more logical to us, to put an accept or reject flag to already committed work we can see and evaluated, instead of labeling the preceding pr issue based on a hope.

many thanks and best regards.

**Comment by ArkadiuszMichalski** [comment]
@urbasus you fix this? If yes then please close this bug.
