### ISSUE TITLE
Typewriter scrolling for Search and Replace (scroll matched string to the centre of screen)

### ISSUE THREAD

**Issue by aaaxx** [notepad-plus-plus/notepad-plus-plus#5687]
An option to automatically center the line with the found string vertically on the screen would make searching and replacing much more pleasant when you're searching for or replacing a specific occurrence of a string. This way, you could keep your eyes focused on a single line instead of having to look for each match all over the screen.

Currently, this is already the behaviour if the next match is outside of the current screen (it will scroll to the center), but if the next match is within the same screen, the selection will just jump to it without centering it.

The option is called typewriter scrolling in other editors.

**Comment by sasumner** [comment]
I've never had to "look for each match all over the screen".  The found-text is always selected, creating a big dark blob on the screen that even the visually impaired can probably see just fine.  Also, probably a good number of users also have the option to highlight the current line turned on, further localizing where the caret next to the match is.

That all being said, I'm not opposed to the typewriter-scrolling thing.  I just don't really see the need.  I guess a personal-preference-kind-of-thing. :)

**Comment by aaaxx** [comment]
The problem is not so much trying to spot it on screen – the highlighting makes that more or less easy, as you mentioned – but having to refocus your eyes all over the screen specifically when you're working with a big file with lots of matches.

It's particularly annoying with a vertically pivoted screen, which is what a lot of programmers use.

**Comment by sasumner** [comment]
So I will point out an upside of the current behavior:  It makes it easy to tell where your next match is _in relation to_ your previous match.

**Comment by MetaChuh** [comment]
@aaaxx 

while displaying the find results at the centre of the editing area seems a good option for an add on as script or plugin, we will currently not implement it at the notepad++ core.

please note, that your idea and desire is not obstrusive or awkward, but we are focusing to make the notepad++ core as issue free and highly customisable as possible, which is only possible by leaving certain features to our community developers, instead of trying to deal with too much at once at the main core.

many thanks for your understanding and best regards.
