### ISSUE TITLE
Error the Message on the Change Log

### ISSUE THREAD

**Issue by exampletech012** [notepad-plus-plus/notepad-plus-plus#5712]
### Description of the Issue

Error on the typo mistake : Remoes -> Romoves on the 10th modification. 

### Steps to Reproduce the Issue

1.  Update to version v7.7 
2. Read the change log message.
3. Navigate to 10th message 

### Expected Behavior

10. Fix all plugins being removed problem while Plugin Admin romoves an old plugin (of old system).

### Actual Behavior

10. Fix all plugins being removed problem while Plugin Admin removes an old plugin (of old system).

### Debug Information

![notepad errors](https://user-images.githubusercontent.com/50601624/58600297-679dac00-82c7-11e9-89a5-0349017df3a1.png)

**Comment by MetaChuh** [comment]
@exampletech012 

many thanks for finding this typo at the change log.

we will fix this at the next release ... or not ... mainly because this line isn't going to exist at the next release notes 😉

ps: if you are eager to find things like this, please join our community to test the release candidates.
this way you can find typos **BEFORE** they are released.

many thanks and best regards.
