### ISSUE TITLE
Indentation depth of wrapped lines

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#572]
Hello,

there's the following option: Settings > Preferences... > Editing > Line Wrap > Indent. I would like to specify the additional depth of the indentation as _2 tabs._

If you have a wrapped line, and a line thereafter that you manually indented with 1 tab, some people as me view this as a conflict as both the continuation line and the next one will appear indented by 1 tab. Judging with regard to printed poetry, it is not uncommon to indent wrapped lines deeper than lines that are indented at the beginning.

These citations show others like this style, too:
- <q>I presonally prefer indenting the continuation of a line with TWO additional tabs so it is good to distinguish from a normally indented command block. ... maybe this won't win a design contest but it is a simple and non-ambiguous coding style</q>
- <q>A continuation of a statement in the following line is indented by. two additional tabs.</q>
- <q>Statements that continue over more than one line should be indented each line after the first line with two additional tabs. This will differentiate the continuation portion of the statement from the encapsulated body of a block.</q>

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
