### ISSUE TITLE
Add a very simple replace Value=**** with Value=10 (The replace feature is too noisy I just want to use a wildcard.)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [notepad-plus-plus/notepad-plus-plus#5720]
### Description of the Issue

So I decided to try Notepad++ but it still lacks one very simple feature which is great for Minecraft configuration editing. It is replace wildcard. Ie "*" Basically using Notepad2mod is more preferably because all I need to do is say 

![2019-05-30 19_54_39-Window](https://user-images.githubusercontent.com/10351221/58674334-fc7ac680-8314-11e9-80fd-bac025302178.jpg)

It will replace any matching expressions of value=17 value=16 with whatever replace value I want like value=200 for example. I googled how to do this in Notepad++ and it is VERY confusing. I just want my star wildcard back.

### Steps to Reproduce the Issue

1. Stop using Notepad2mod
2. Switch to Notepad++
3. Become confused and frustrated because you are not a coder.

### Expected Behavior

A simple one option replace all wildcard search.

### Actual Behavior

A confusing replace regular expression with @.@

### Debug Information

NA

![2019_05_30_19_58_35_Window](https://user-images.githubusercontent.com/10351221/58674472-9e9aae80-8315-11e9-8130-17972416b776.jpg)

**Comment by frank-orellana** [comment]
Actually regular expressions are also simple and more powerful, try using `.+` (a dot and a plus sign) instead of all the asterisks and search with the regular expression checkbox marked. 

You can try some sites to play with regular expressions like [regexr](https://regexr.com/), also you can find help in the [notepad community](https://notepad-plus-plus.org/community/)

This should not be a bug, or a request since adding yet another way to search or replace to the existing ones (normal, extended and regular expression) might just make things more confusing to everyone.

**Comment by P3rf3ctXZer0** [comment]
Alright I guess I will try that real quick.
![2019-05-30 20_54_11-Window](https://user-images.githubusercontent.com/10351221/58676281-4bc4f500-831d-11e9-8051-7ae1f80567aa.jpg)
Did not work.

**Comment by frank-orellana** [comment]
I meant one dot and one plus sign instead of ALL the asterisks:

Find what: `Minimum height=.+`
Replace with: `Minimum height=10`
Regular expression: marked

*explanation:* the dot means any character, the plus sign means it should be one or more ot said character, so basically it means that it should match any characters after the equal sign.

Regular expressions are your friend! really, try [regexr](https://regexr.com/) and see it's cheatsheet, or else find a quick regular expression intro course, it will take 10 minutes and will serve you for life (not just minecraft!)

**Comment by P3rf3ctXZer0** [comment]
It legit deleted everything in the document and I only wanted the one line.

**Comment by frank-orellana** [comment]
seriously, play with regexr or any other online regular expression site. you can paste your document there or a part of it and try the regex. 
In your case I bet the problem is because you have the `. matches newline` option checked. uncheck it and it should work fine

**Comment by P3rf3ctXZer0** [comment]
Why - why have it be anything less than a few options?! Sigh I guess I will have both installed for now.

**Comment by frank-orellana** [comment]
I know, Regular expressions seem intimidating at first, but just learn the basics and you will not stop using them ever

**Comment by xylographe** [comment]
```
Find    : (Minimum height)=[0-9]+
Replace : $1=200
```
