### ISSUE TITLE
backup doesn't back session.xml when NotePad++ Crashed

### ISSUE THREAD

**Issue by wayne-zhang** [notepad-plus-plus/notepad-plus-plus#5737]
When notepad++ shutdown abnormal (application crash or Windows shutdown force quite the application), last session (opened tabs etc) will lost.

Even though I have have enabled back (settings >backup) for session, session.xml file is not backed up in the backup folder (the default one is C:\Users\{user_name}\AppData\Roaming\Notepad++\backup). Please backup session file (default is session.xml) too in case of NP++ exit abnormal and previous session has been lost, to make it possible to restore session manually (copy session.xml backup file and replace it).

To reproduce this issue, please shutdown Windows and let Windows kill the hanging processes (and NP++ is hanging).

**Comment by wayne-zhang** [comment]
When crash, session.xml (in folder C:\Users{user_name}\AppData\Roaming\Notepad++) is empty and ALL opened tabs are lost.

Note, unsaved files are not lost, they are backed up the backup folder (C:\Users{user_name}\AppData\Roaming\Notepad++\backup).

**Comment by MetaChuh** [comment]
@wayne-zhang 

session save is triggered by a graceful shutdown by design, as it should be the last thing to do when exiting.

i can also not reproduce a notepad++ application crash, if you don't have any plugins that can cause this.

for unattended reboots of windows itself, please disable automatic windows update reboot, if you tend to leave notepad++ open, while your pc is unattended.

for disaster recovery you still have your backups, if you have activated either internal or external backups.
note: it's recommended to use both of those backup ways, just to be on the safe side.

many thanks and best regards.

**Comment by donho** [comment]
Fix by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6000f3bb21a42a4d28d068617e0dc642ef739b26
