### ISSUE TITLE
[Feature request] Add new plugins API messages for getting/releasing Scintilla indicator number

### ISSUE THREAD

**Issue by pnedev** [notepad-plus-plus/notepad-plus-plus#5744]
### Description of the Issue

There are currently several plugins that use Scintilla [indicators](https://www.scintilla.org/ScintillaDoc.html#Indicators) but there is no way for a plugin to know which indicator number is already used by another plugin so an unwanted plugins "cross-talk" happens as they track indicators placed by another plugin.

To name several plugins using indicators - DSpellCheck, DoxyIt, Compare

### Steps to Reproduce the Issue

It appears that Compare v2.0 and DoxyIt plugins currently use the same indicator number.

1. Install both plugins.
2. Compare two files that have several lines differing by just one word (so you have changed lines, not only added/removed)
3. Press `TAB` key (DoxyIt shortcut for visiting function description fields)

DoxyIt will visit the Compare changed highlight indicators as well because the Compare's indicator number is the same as DoxyIt's.

This is just an example of the problem. It might appear in the future in different forms depending on the plugins.

### Suggestion
Add new NPPM_GET_SCINT_INDICATOR and NPPM_FREE_SCINT_INDICATOR plugin API messages so each plugin gets a different indicator number.
Of course Notepad++ should keep a list of the free indicator numbers.

**Comment by sasumner** [comment]
+10.  For my own purposes, which is a multitude of Pythonscripts, I create and maintain an indicator number "pool" (via something in my startup), and then "client" scripts obtain and release to this "server" pool. I would much rather turn this burden over to Notepad++ itself.  :)

OT: BTW, don't (custom) margins suffer the same problem? Worse: And yesterday I just wanted to find out how many margins there were, currently, and I was stymied...

**Comment by pnedev** [comment]
@sasumner 
> BTW, don't (custom) margins suffer the same problem?

Yes, I guess you are right.

**Comment by dail8859** [comment]
There is already `NPPM_ALLOCATEMARKER` for allocating unique markers (which to be honest I've never used).

But if you look at the code for that Notepad++ message, there is already support for generically allocating IDs so it might not be that hard to add support for indicators, margins, and anything else that needs managed by Notepad++ to keep these kinds of conflicts from happening.

**Comment by Ekopalypse** [comment]
What about using [SCI_INDICSETFLAGS](https://www.scintilla.org/ScintillaDoc.html#SCI_INDICSETFLAGS)
with SC_INDICFLAG_VALUEFORE, wouldn't this solve the issue?

**Comment by sasumner** [comment]
Am I going crazy of didn't @Ekopalypse have an additional comment here?  Was it deleted?

**Comment by Ekopalypse** [comment]
Sorry, I deleted it and I was hoping that no one has  already read the nonsense I wrote.

**Comment by alankilborn** [comment]
@donho I can implement this if you are agreeable to accepting it; let me know by replying and assigning me, please.

**Comment by Coises** [comment]
What happens if the authors of existing plugins aren't available and willing to rework their plugins to use the new system? For example, DoxyIt, mentioned above, hasn't seen a commit since 2020 or an issue closed since 2019. The same author (https://github.com/dail8859) recently archived the long-used version of Elastic Tabstops. It's fair guess he won't have the time or inclination to update it.

I'm not saying this isn't a good idea, just that it might not help as much as we'd like to think, at least not until enough years have gone by that existing popular but unmaintained plugins that use indicators have broken anyway. It's a perennial source of frustration to users when plugins (for any program) on which they rely just randomly (from the user's standpoint) stop working. I'd hate to see us effectively "break" old plugins by encouraging authors of new plugins to think they can use the new mechanism and not concern themselves with possible conflicts.

Of course, the old plugin authors didn't concern themselves either, apparently, they just assumed they were the only plugin that mattered. I came across this issue because I'm working on a new plugin that in some circumstances will use an indicator, and the only way I could figure to avoid conflict was to include a configuration option for the user to select the indicator number. That's not good, because the indicator number is meaningless to end users.

Would it make sense to incorporate some sort of list of well-known legacy plugins that use indicators and the indicator numbers they use, and automatically reserve those numbers if those plugins are installed, thereby making the new system work with the most commonly-used existing plugins without the need to get their authors to change them? (Removing them, of course, when and if the plugin authors do update them to use the new system.) And/or -- simpler for developers, but mysterious for users -- include a user option somewhere to list reserved indicator numbers, and make it known what numbers should be reserved for commonly-used plugins?

**Comment by rdipardo** [comment]
@Coises,
> I'd hate to see us effectively "break" old plugins [ . . . ]

It wouldn't be [the first time](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11198).

At a more fundamental level, *any* plugin that has to be *compiled* from a subset of Npp's own source code will be subject to inevitable bit rot.

The only better alternative is a plugin system based on dynamically loaded scripts, ideally supported by a Python subsystem, such as [Vim], [Sublime Text] and [CudaText] have had for years.

[CudaText]: https://wiki.freepascal.org/CudaText#Python_integration
[Sublime Text]: https://www.sublimetext.com/docs/porting_guide.html#python-3-3
[Vim]: https://vim-jp.org/vimdoc-en/if_pyth.html

**Comment by alankilborn** [comment]
@donho Did you miss seeing my ping here?: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5744#issuecomment-1513073634

**Comment by donho** [comment]
> Did you miss seeing my ping here?: [#5744 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5744#issuecomment-1513073634)

@alankilborn
Sorry I missed your ping.
I thought it does exist these 2 messages.
Sure, go ahead.
