### ISSUE TITLE
A BIG BUG(When file is not too long, the data is cutted)

### ISSUE THREAD

**Issue by sky5454** [notepad-plus-plus/notepad-plus-plus#5751]
The origin Issues in [A BIG BUG（When file is not too long）](https://github.com/chcg/NPP_HexEdit/issues/16)

> image
When file is not too long, hex display has a bug.
![img](https://user-images.githubusercontent.com/12370628/58529829-f7335400-820e-11e9-9f12-043d264ddd08.png)
The image show the different between BZ and HexEditor.
And BZ is right. HexEditor has a bug when file is not too long (such as the file only has 6bits )

 >@chcg
 Owner
chcg commented 8 days ago
@sky5454 Which version of HexEditor do you use? Together with which version of N++? 32 or 64bit?

 >@chcg
 Owner
chcg commented 7 days ago • 
Reproduced with N++ 7.7.0 64bit and current Hexedit release. Also the data without Hex View is cutted in this case, see:
grafik  
![img](https://user-images.githubusercontent.com/12630740/58628681-b0129500-82da-11e9-9602-346b7ed6d1f8.png)
with file size of 6 bytes and encoding ansi.

 >@chcg chcg referenced this issue 18 hours ago
 Closed
HEX viewer is completely broken now #5747

**Comment by MetaChuh** [comment]
@sky5454 

please do not open a plugin issue here, especially as you already opened the same issue at @chcg 's hexeditor plugin repo more than a week ago.

instead please answer the question you have been asked at the plugin issue tracker.

best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sky5454** [comment]
But this is no a plugin's issue, we finally found that it is NPP' s bug. Please view the issuse again. Thanks.

**Comment by sasumner** [comment]
@sky5454 Remove the Hex Editor plugin from your setup.  If the problem then goes away, it is not a Notepad++ bug.

**Comment by sky5454** [comment]
> @sky5454 Remove the Hex Editor plugin from your setup. If the problem then goes away, it is not a Notepad++ bug.

When I removed the plugin "HexEditor", the problem still exist.
![image](https://user-images.githubusercontent.com/12370628/59156575-f5e80e00-8acf-11e9-8f58-4a74212fdef6.png)

**Comment by Cyrillev91** [comment]
Hello,
I confirm a bug in notepad ++ (and another one in plugins hex editor)
When you open your file in notepad ++, it is detected as **UCS-2-LE (without BOM)** (1 chararcter = multiple bytes)
![encode1](https://user-images.githubusercontent.com/12849364/59157529-86acf280-8aac-11e9-9d0d-7a6e83738038.jpg)

I noticed that Hex editor plugins works fine if the encoding detected by notepad++ is:
-    ANSI
-    UTF-8
-    UTF-8 BOM
-    UCS-2 BE BOM
-    UCS-2 LE BOM
not OK with UCS2-LE (Without BOM), and other ...


I try reload test file with ANSI encoding : Encoding >> Encode in ANSI but without success because 
**Encode in ANSI** function function is broken in notepad++ ( #3764) and Fix (#3836)

**After apply Fix in my PC**
I try reload test file with ANSI encoding : Encoding >> Encode in ANSI success
![ok_withFix](https://user-images.githubusercontent.com/12849364/59157676-caa0f700-8aae-11e9-8ef8-f79f8bd8055f.jpg)

and Now with HEX editor plugins
![hex_ok](https://user-images.githubusercontent.com/12849364/59157680-f1f7c400-8aae-11e9-8238-084eec3eacd7.jpg)

**Comment by sky5454** [comment]
LOG:
> Notepad++ v7.6.5   (64-bit)
> Build time : Mar 29 2019 - 02:43:47
> Path : C:\Program Files\Notepad++\notepad++.exe
> Admin mode : OFF
> Local Conf mode : OFF
> OS : Windows 10 (64-bit)
> Plugins : DSpellCheck.dll HexEditor.dll mimeTools.dll NppConverter.dll 
>
Npp read file in options "use other Encode" will change the file.
And I wonder if it could read a file without changing the file, like vscode's "reopen with UTF-8".
That might solve the problem.

**Comment by Cyrillev91** [comment]
**Differences between the options Encoding -> Convert to ... and Encoding -> Encode in .... :**
- The option **Encode in ....** OR Character sets / .... / ...., apply the chosen encoding to the actual contents of the current file. **(The display changes, the contents of the file do not change)** 

- The option **Convert to...** transforms the current file, with its actual encoding, to the same contents file, translated in the chosen encoding. **(The display does not change, the contents of the file change)**

But there are bugs in **Encode in ....** : the contents of file do change 👎 

More informations : #4588
