### ISSUE TITLE
Notepad autocompletion cannot be changed

### ISSUE THREAD

**Issue by dvdvideo1234** [notepad-plus-plus/notepad-plus-plus#5758]
### Description of the Issue

The autocompletion setting of NPP cannot be changed to anything else and stays at `1` all the time. When it is deleted, a digit cannot be inserted in the box. The digit is not seen. When `[x]` is clicked the setting returns to `1`.

### Steps to Reproduce the Issue

1. Install NPP 7.7
2. Go to `Settings` -> `Auto-Completion`
3. Click on `1` of `From `[1]()` th character`
4. Delete the value or write a digit

### Expected Behavior

Digit to actually change

### Actual Behavior

Digit cannot be changed. 

### Debug Information

Notepad++ v7.7   (32-bit)
Build time : May 19 2019 - 13:08:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll GmodLua.dll HexEditor.dll HTMLTag_unicode.dll LuaScript.dll MarkdownViewerPlusPlus.dll mimeTools.dll NewFileBrowser.dll NppConverter.dll nppcrypt.dll NppExport.dll NppFTP.dll NppQrCode32.dll NppTextFX.dll SpellChecker.dll 

![image](https://user-images.githubusercontent.com/9112662/59099839-fd22e680-892c-11e9-94f7-11a759c6288f.png)

**Comment by Ekopalypse** [comment]
Does work here, assume that something corrupted your config.xml.
Temporarily rename the file in %APPDATA%\notepad++ directory, start npp and retest.

**Comment by MetaChuh** [comment]
@dvdvideo1234 

i can not reproduce this on notepad++ 7.7 on windows 7 or windows 10.
but maybe you have a windows scaling problem, due to a specific zoom percentage.

please do the following:
* exit notepad++ if it is running.
* right click on your notepad++ icon.
* select `properties > compatibility > change high dpi settings`.
* activate `override high dpi scaling behavior`.
* and set `scaling performed by:` to `system (enhanced)` instead of `application`, as seen at the screenshot below.

![Imgur](https://i.imgur.com/qVQ4Bg8.png)

after that, open notepad++ and try to change your autocompletion character value.

many thanks and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
