### ISSUE TITLE
Notepad++ local configuration does not work. AppData is used instead

### ISSUE THREAD

**Issue by dvdvideo1234** [notepad-plus-plus/notepad-plus-plus#5759]
### Description of the Issue

The zero length file `doLocalConf.xml` exists in the installation folder, but Notepad++ uses `%AppData%` instead

1. Install a fresh copy of NPP 7.7
2. Select Don't use `%AppData%`
3. Check that `C:\Users\<user_name>\AppData\Roaming\Notepad++` exists

### Expected Behavior

The directory above must not exist because the file `doLocalConf.xml` exists

### Actual Behavior

The directory above must not exist according to the manual file regarding [`doLocalConf.xml`](http://docs.notepad-plus-plus.org/index.php/Configuration_Files).

### Debug Information

Notepad++ v7.7   (32-bit)
Build time : May 19 2019 - 13:08:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : `OFF` **See here !**
OS : Windows 7 (64-bit)
Plugins : GmodLua.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppDocShare.dll NppExport.dll NppQrCode32.dll 

![image](https://user-images.githubusercontent.com/9112662/59102826-e765ef00-8935-11e9-915a-bdf900ae8a0a.png)

**Comment by dvdvideo1234** [comment]
This seems to be related to the one below:

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3661

**Comment by sasumner** [comment]
@dvdvideo1234 

Is the problem that the directory even exists? (which I would call a non-problem) Or that your Notepad++ is using it even though you have local config specified?

**Comment by MetaChuh** [comment]
@dvdvideo1234 

the installer will not permit you to select `do not use %AppData%` when you use `C:\Program Files (x86)\Notepad++\` as the install path, as this location is read only for the user account.
this option will be greyed out if you try.

creating a `doLocalConf.xml` there manually will not work, due to the missing permissions to that folder.

if you want to install notepad++ without `%AppData%`, having all files inside the notepad++ program folder, please install to a folder location, where the user account has write permissions without elevated rights required.

most common installation location examples for doLocalConf installations:
`%ProgramData%\Notepad++`
`C:\PortableApps\Notepad++`

many thanks and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
