### ISSUE TITLE
ASP Syntax Highlighting Removed

### ISSUE THREAD

**Issue by chauhankiran** [notepad-plus-plus/notepad-plus-plus#5763]
### Description of the Issue
If you have `.asp` file and code with `<%` and `%>` then it highlight with different background color than white. That differentiate the ASP code from other language code such as HTML, CSS, JavaScript if all are written within same page. Now, the background is removed and displaying with white.

### Steps to Reproduce the Issue
1. Create a file with `.asp` extension. That should have bunch of ASP and html code.
2. Open in Editor.
3. You will not see syntax highlighting for ASP code.

### Expected Behavior
The ASP code should highlight with background color. https://prnt.sc/nzso4w

### Actual Behavior
The ASP code is displaying with white background. https://kiranchauhan.tinytake.com/tt/MzU3NTE5NF8xMDc5MjMyNA

**Comment by MetaChuh** [comment]
@chauhankiran 

this has been fixed by @dail8859 in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e5de0c6d44ffcfe4dc66e5fb679ca94731e0c8a4, as seen at the screenshot below.
this fix will be available at the next release.

<img width="910" alt="" src="https://user-images.githubusercontent.com/45773305/59190492-25088900-8b7d-11e9-94bf-859212b7f4f3.png">

referenced to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5702 and https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5677 

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.
```
