### ISSUE TITLE
HTML Tag (CTRL+Shift+T) not working

### ISSUE THREAD

**Issue by crystrk** [notepad-plus-plus/notepad-plus-plus#580]
CTRL+Shift+T command not working on v6.8

**Comment by Rikk** [comment]
It is shortcut for "Restore Recent Closed File", wouldn't it be better that plugin change its shortcut?

**Comment by Rikk** [comment]
Duplicate https://github.com/notepad-plus-plus/notepad-plus-plus/issues/370

**Comment by crystrk** [comment]
ah okay, but I prefer CTRL+Shift+T for "select tag and content:" than "Restore Recent Closed File"
![cats](https://cloud.githubusercontent.com/assets/5161918/8923323/64884336-3519-11e5-9993-e742a225a2b9.jpg)

**Comment by Rikk** [comment]
I understand... but for Npp as default I think it is perfect for restoring tabs, because it is same shortcut browsers use; in this case, I think it's better either the plugin be updated (dunno who is the author), or in the meanwhile you can change the keys for restoring tabs so the plugin works, eg:
![ctrl-shift-t](https://cloud.githubusercontent.com/assets/2916485/8923500/ebeb36fa-34c7-11e5-82b2-1a3c9e59cad8.png)
