### ISSUE TITLE
Digitally Sign Uninstaller

### ISSUE THREAD

**Issue by wrolisonaflac** [notepad-plus-plus/notepad-plus-plus#5806]
### Description of the Issue
Notepad+= Uninstaller is not digitally signed

### Steps to Reproduce the Issue

1. Install Notepad++
2. Uninstall Notepad++ via official uninstaller
3. Notice uninstaller is not digitally signed

### Expected Behavior
I expected the Notepad++ uninstaller to be digitally signed just like the installer and dlls

### Actual Behavior
Notepad+= Uninstaller is not digitally signed so some software may detect as malicious

https://notepad-plus-plus.org/community/topic/17838/notepad-uninstaller-is-not-digitally-signed

**Comment by MetaChuh** [comment]
welcome to the notepad++ issue tracker, @wrolisonaflac 

the nsis installer's `uninstall.exe` is not detected as malicious by any of the top ~70 antivirus/antimalware engines.

please see the current virustotal.com results:

uninstall.exe (7.7)
https://www.virustotal.com/gui/file/a9e7777005905f608973696b4d83b8013ebfa82fc5dcad327390acba6ff3ce52/detection

uninstall.exe (7.7.1)
https://www.virustotal.com/gui/file/5ff7a866c0cce74680b01142bb9613388fef23b5cd68215c02dfe9baccc88487/detection

npp.7.7.1.Installer.exe
https://www.virustotal.com/gui/file/6787c524b0ac30a698237ffb035f932d7132343671b8fe8f0388ed380d19a51c/detection

please also make sure you only download notepad++ from our official resources at https://notepad-plus-plus.org/download/

many thanks and best regards.

**Comment by wrolisonaflac** [comment]
Was being picked up by CrowdStrike. It's been fixed for that.

But still why close? And why not sign the uninstaller just like everything else?

**Comment by MetaChuh** [comment]
@wrolisonaflac 
> But still why close? And why not sign the uninstaller just like everything else?

because `uninstall.exe` is not a shipped file, but a helper file created on the fly, by the nsis installer at the time of installation.
if you might ask: the version information you see, is also created on the fly by nsis, using the info provided at the installer script.

in short: there is no possible way to sign this file on a target system.
(except theoretically implementing a post installation script, and shipping everything needed to sign it, which will obviously never happen 😉)

many thanks and best regards.

**Comment by wrolisonaflac** [comment]
Got ya. FYI: https://nsis.sourceforge.io/Signing_an_Uninstaller

Don't look that hard to get signed ;) Just saying. But I'm moving on, I got my answer. Thanks
