### ISSUE TITLE
Scintilla update callback?

### ISSUE THREAD

**Issue by kevstev01** [notepad-plus-plus/notepad-plus-plus#5809]
### Description of the Issue

The MarkdownViewer++ preview does not dynamically update

### Steps to Reproduce the Issue

1.  Install the MarkdownViewerPlusPlus plugin
2. Open the preview panel
3. Type, and nothing appears in the preview
4. Close and re-open the preview and typed content is displayed

### Expected Behavior

The markdown preview panel should be dynamically updated.

### Actual Behavior

I would guess that the update to Scintilla no longer calls a callback.
Downgrading to Notepad++ v7.6.6 (64 bit) restores expected behaviour.

### Debug Information

Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll 

Whilst I realise that the contribution guidelines say not to submit reports about non-default plugins, this issue appears to have been **caused by changes to the notepad++ package** rather than being a plugin issue

**Comment by dail8859** [comment]
Unfortunately there is nothing we can do (or try to debug) simply because a "plugin doesn't work".

That doesn't mean it isn't N++ fault in some way but **we need specific details**. If there is a particular notification or message that is not working then that would give enough information on this end to start debugging the problem.

One suggestion is to try the 32-bit version of N++ and MarkdownViewer++ to see if that has the same issue. I'd recommend contacting the developer of MarkdownViewer++ (or if someone can debug it themselves) and reopen the issue with specific details so it can be reproduced by another plugin.
