### ISSUE TITLE
Recent Files: Prompt if file has been deleted

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#582]
If a file in the Recent Files list has been deleted from the disk, a message with the option to remove that file from the list should be generated.

**Comment by milipili** [comment]
Why ? The file is no longer available and this message would be really annoying. Another solution might be to keep the entry but to make it not clickable

**Comment by Rikk** [comment]
No, a common behavior in many programs is to ask to remove from list, **when** the user click (in a Recent Files list) on a file that doesn't exist on disk. Another common behavior is to display a message like "Cannot open the selected item because the file could not be found." with an OK button; clicking Ok will automatically remove file from list.

**Comment by Marshallx** [comment]
+1 for this

The current behavior of Notepad++ is that recent files that no longer exist are automatically removed from the recent files list. This is INCREDIBLY annoying. When I'm switching repository branches files often pop into and out of existence. I would really like an option to not remove deleted files from the list - and the entry should still be clickable. The only time NPP should ever check a recent file is when you try to load it - and a prompt when it doesn't exist is perfect.

With the current behavior, the recent files list is almost unusable to me.

I find it hard to believe there is anyone who likes the current behavior - but if there is then make it optional.

**Comment by Yaron10** [comment]
Hello @Marshallx,

The following setting might help you.
Preferences -> Recent File History -> Don't check at launch time.

Best regards.

**Comment by MetaChuh** [comment]
@Yaron10 here goes another one 😉

we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
