### ISSUE TITLE
Editor session wiped if unsaved file aborts Windows shutdown

### ISSUE THREAD

**Issue by kaiof** [notepad-plus-plus/notepad-plus-plus#5831]
### Description of the Issue

NPP wipes the tab session state if you interact with it during Windows 10 restart/shutdown.

### Steps to Reproduce the Issue

1. Open any existing file(s); do not change them.
2. Open a new tab, type something but do not save.
3. Restart or shutdown Windows.
4. Windows will prompt that a program is preventing shutdown.
5. Cancel shutdown, then answer NPP's prompt (it doesn't matter if you save or discard)
6. NPP closes all open tabs (shutting down), then opens a new tab.
7. Restart the computer, then open NPP again.
8. NPP has only the new tab open, and no state recovery appears to be possible (e.g., from recently closed files).

### Expected Behavior

Do not wipe the session when NPP interrupts windows restart/shutdown.

### Actual Behavior

Session and MRU list zapped; it appears that the (spurious?) auto-opened new tab becomes the last session instead.

### Debug Information

Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

Existed in a previous version; I just updated to the latest version (7.7) and confirmed the issue still existed before filing.

[edit]
Note: After checking the backup folder, I found stale files from a while back. For whatever reason (it's supposed to be ON), "Settings | Preferences | Backup | Enable session snapshot and periodic backup" was NOT checked. Also: "General | Tab Bar | Exit on close the last tab" was NOT checked so...I suspect one/both of these are required to be OFF to duplicate this issue.

**Comment by Paebbels** [comment]
I assume, that Notepad++ updates clear the "auto save" checkbox. I noticed after updates I loose unsaved files while restarting, they haven't been save to appdata because the checkbox was unchecked before.

If there was no update, and Notepad++ got killed in a reboot, at least saved files can be found and opened from appdata ...

**Comment by donho** [comment]
>6. NPP closes all open tabs (shutting down), then opens a new tab.
>7. Restart the computer, then open NPP again.

The session is your last state of your opened files. In this case it's the new opened tab state which is memorized for the next session. So I don't see the unexpected behaviour here.

**Comment by Ben-Voris** [comment]
Claimed to be fixed in https://github.com/alef162/notepad-plus-plus/commit/8df43a4292e9e282ad81375e4678ac8303fe9915 but 8.3.3 64-bit left left empty backup files after an unplanned Windows 10 update restart. 

Windows Explorer shows the "Date modified" of the files as a few *days* before the shutdown. 

- [x] Remember current session for next launch
- [x] Enable session snapshot and periodic backup

Backup in every 30 seconds. 

Backup on save is none.

----

As expected, if I create a file and enter a bit of text, the backup file gets that text.

And yet, when Windows kills Notepad++, the backup file is empty.

**Comment by donho** [comment]
Fix by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6000f3bb21a42a4d28d068617e0dc642ef739b26
