### ISSUE TITLE
Wildcard in File Open dialogue opens all files instead of filtering

### ISSUE THREAD

**Issue by jweinraub** [notepad-plus-plus/notepad-plus-plus#5864]
### Description of the Issue

When using *.cc as filename in the open dialogue it will open all .cc files instead of filtering all .cc files.  This is unexpected behaviour from MDIs.

### Steps to Reproduce the Issue

1. Click File
2. Click Open
3. Type in *.cc or whatever extension you have in a path where n >= 1

### Expected Behavior

I expected to see .cc files filtered

### Actual Behavior

It opened all .cc files

### Debug Information

Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : MarkdownViewerPlusPlus.dll mimeTools.dll NppBplistPlugin.dll NppConverter.dll nppcrypt.dll NppExport.dll NPPJSONViewer.dll NppSaveAsAdmin.dll VisualStudioLineCopy.dll XBrackets.dll

**Comment by Ekopalypse** [comment]
Goto **settings->preferences->default directory** and check **use new style dialog...**

**Comment by alankilborn** [comment]
Tested in N++ 8.4.4 (current version as of this writing) and could not repro, probably because somewhere between 7.6.6 and 8.4.4 the choice between "old style" and "new style" dialog disappeared, leaving only "new style", and it was the "old style" dialog that exhibited this problem.
Recommend CLOSURE of this item.
