### ISSUE TITLE
Incorrect use of WIN32_FIND_DATA.cFileName

### ISSUE THREAD

**Issue by MojaveWastelander** [notepad-plus-plus/notepad-plus-plus#5871]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/3f7956dc1bd16445f031a38bca8aa9e72806a408/PowerEditor/src/MISC/PluginsManager/PluginsManager.cpp#L329

WIN32_FIND_DATA.cFileName contains the extension as well so lines 329 and 330 break proper plugin find and load procedure.

**Comment by dinkumoil** [comment]
As far as I can see, in line 320 the search is done for directories because since Npp v7.6 every plugin needs its own directory in the `plugins` folder with the same name like the plugin DLL file (without the `.dll` extension).

Thus, `foundData.cFileName` contains the name of plugin's directory which is appended to `pluginsFullPathFilter` (line 326) which in turn contains the path to Npp's `plugins` folder. To the resulting  string, the plugin's name and the string `.dll` is appended (line 330) which results in the full path to the plugin DLL file.

Nothing wrong, please close this issue.

**Comment by MojaveWastelander** [comment]
Yes, seem to be right. I think if the function was written with std::filesystem it would have been clearer what the code was meant to do as it has better interface than WinAPI functions.
