### ISSUE TITLE
Since 7.7.1 mark or find and replace not working as expected

### ISSUE THREAD

**Issue by lennaertp** [notepad-plus-plus/notepad-plus-plus#5938]
### Description of the Issue
When using Mark, it will only mark search items from the point of your cursor and up.  Same goes for find and replace.

**Clear all marks** appears to work fine.

Had friend try older version (7.7) and it worked fine there.  Unable to download older version my self due to a 503 error from notepad++ site.

### Steps to Reproduce the Issue
1. Open file
2. Pick a some characters to set a mark on
3. If cursor is at top of file (position 1,1) it finds nothing

### Expected Behavior
When clicking **Mark All** or **Replace All** it should be entire file.

**Comment by Ekopalypse** [comment]
Works for me - are you sure that the checkbox Wrap around has been checked?

**Comment by lennaertp** [comment]
/facepalm 

I don't think I've ever turned this off in I don't know how many years, so I never noticed it before.  That was it.  Thanks @Ekopalypse.

**Comment by sasumner** [comment]
I don't know that this issue should have been closed, since it hints at the REAL issue; when the OP said:

>it will only mark search items from the point of your cursor and up.

Why, given the options one can see on the Mark page, should it ever do a "caret and up"-scoped marking??  It shouldn't; read on:

There is a long-standing bug in N++ where Mark actions are influenced by the "Backward Direction" checkbox that doesn't even appear on the Mark page.  Of course, this doesn't matter if the "Wrap around" box on the Mark page is ticked (which was the solution/workaround for the OP above)

So there are (at least) 2 solutions for this:

First, add "Backward direction" checkbox to Mark page.  This gives the user maximum flexibility for his Marking operation.

OR

Second, remove "Wrap around" checkbox from Mark page, and change the code so that when a Mark action is performed, it operates as if the "wrap around" checkbox is ticked.  This isn't as flexible for the user, but IMO it would be a very acceptable solution.

**Comment by Ekopalypse** [comment]
Not sure, having wrap around checkbox allows to mark only those from current version until end of doc
or all, if checkbox is ticked. I assume it doesn't do any backwards search in that case, but have to admit that I haven't checked the source code yet, instead it just reads buffer[pos:to_end] and buffer[0:pos]. 
So the only "missing feature", from my point of view is the possibility to mark only from top to current position.

**Comment by sasumner** [comment]
@Ekopalypse Tsk, tsk.  Usually you read my comments better and understand them.  :(

**Comment by Ekopalypse** [comment]
Oooppps, what did I miss? :-)
My "top to current pos" is your "backward mark" or do you really mean back and foward marks in steps like the find next does?

**Comment by sasumner** [comment]
>Oooppps, what did I miss?

I mean that there is an option ("backward direction") on the "Find" page that controls what is happening on the "Mark" page.  This shouldn't be!  :)

Was I really so unclear?

**Comment by Ekopalypse** [comment]
>Was I really so unclear?

Not if someone carefully reads _actions are influenced_, sorry. :-(
