### ISSUE TITLE
Windows 10 

### ISSUE THREAD

**Issue by A-SQLDEVELOPER** [notepad-plus-plus/notepad-plus-plus#596]
I just updated from Windows 7 to 10, downloaded last release of notepadd++ and installed notepad.
Unfortunatelly notepad++ won't start open

**Comment by Croydon** [comment]
If you can you should provide more information. Did any error message shown up? Any warnings? Anything else? How did you start it?

**Comment by ariccio** [comment]
Does it remain visible in Task Manager after *not opening*/*starting*?

**Comment by donho** [comment]
@A-SQLDEVELOPER Just upgrade to Windows 10 and install Notepad++ v6.8.
I got no issue here. If you in tablet mode, you have to switch to the launched Notepad++ manually.

**Comment by A-SQLDEVELOPER** [comment]
Yesterday I tried the upgrade feature of Microsoft, which wasn't a good idea. So I made the experiance as described above. Later I installed W10 on my PC and then notepad ++ again. Now notepad works as expected

**Comment by frekele** [comment]
+1

**Comment by Nvictuz** [comment]
Issue:
After upgrading to Windows 10 Notepad ++ would not open.
When running the .exe (as current user or administrator) it would act like it was going to start but just wouldnt.
I spent some time reinstalling, installing to new drive/location, modifying permissions, etc... without much luck.

Resolution:
During installation i selected the "Dont use %AppData%" (which writes the configuration file in the install folder rather than the appdata folder) (default installation has this unselected).
With this option selected the install completed and Notepad ++ began working again
