### ISSUE TITLE
"Search in files" searches text in old cached version of updated files if a file is open in a tab (but not reloaded yet)

### ISSUE THREAD

**Issue by shultays** [notepad-plus-plus/notepad-plus-plus#5966]
### Description of the Issue
"find in files" does not find a text when an updated file is open in editor (but it is not refreshed yet, it is open in another tab)

### Steps to Reproduce the Issue
1. Create a new text file
2. Open it in notepad++ then open another file so the new file is no longer current tab
3. Open the new text file with another editor and type "text" and save
4. Go back to notepad++, search in files for "text" (ensure path/filters etc is all correct and the new file will be searched)
5. Notice that "text" is not found
6. Switch new file's tab, it will ask you to reload file. Click OK
7. Now searching for "text" works

### Expected Behavior
It should always search in updated files (or that should be default behavior that is toggleable in settings?). This is especially problematic when you work with a source control program that updates a file that is open in notepad++ and you are no longer able search newly updated stuff unless you reload every tab.

### Actual Behavior
It searches the cached versions of file

### Debug Information
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
When I try the steps to reproduce, when I "go back to Notepad++" in step 4, I get the reload prompt for the "new text file" created in step 1, before I can perform any search.  Now, I realize this is going to be dependent upon the _File Status Auto-Detection_ settings, but for working with files that have the possibility of being externally modified, isn't it best to have those settings set "correctly" for your situation? 

Your described search is a _Find in Files_ search, which is perhaps misleading (the name) when it comes to open file tabs. I believe what happens is that if this type of search sees that a file is open in Notepad++, it searches that buffer (i.e., the "cached version") instead of the actual disk file.  It does this because there could be unsaved changes in the file that you want the search to be aware of.

**Comment by shultays** [comment]
Setting `File Status Auto-Detection` to `Enable for all opened files` is a bit annoying when you have some logs file open. I would rather not toggle that. (and default value for that toggle is `Enable` which only asks for reload when you switch to the tab of the file)

Hmm, I think you are correct. notepad++ searches the buffered/"cached version" of files when you have a file open but not saved yet. The intent must be to allow it to find text that is not saved yet. That sounds reasonable as well, but it is still a bit unexpected for notepad++ to not find stuff that is actually in files because the file is open in notepad++ and waiting for you to manually reload it from disk.

**Comment by dinkumoil** [comment]
Despite the fact that Notepad++ has some advanced features for working with text files it is primarly a text editor. Thus, if you want to search a bunch of files for something it's better to use a search tool.

The tool I use is [_grepWin_](https://tools.stefankueng.com/grepWin.html). It integrates into Explorer context menu, has a powerful search **and replace** function supporting regular expressions, can filter files for size and age and can call an editor of your choice with filename, line and column number of a match. Since Notepad++ supports to be called with these info as command line parameters you will finally end up in our beloved editor again.

**Comment by R-Adrian** [comment]
@shultays i used to do that with Notepad++ to keep watch on some logs but then i discovered that PowerShell is a much better tool for monitoring those log files
try this command in PowerShell:
` Get-Content -Path '_log_filename_here' -Tail 10 -Wait`
it's basically the equivalent of tail -f in linux.

or 
` Get-Content -Path '_log_filename_here' -Tail 10 -Wait | Select-String 'string_to_filter_for'`
which is the equivalent of tail -f | grep
