### ISSUE TITLE
In functionList.xml association with extension does not work.

### ISSUE THREAD

**Issue by heckl** [notepad-plus-plus/notepad-plus-plus#5986]
I am using notepad++ 7.7.1

In functionList.xml I created a parser for markdown files. I tested it in a c file where I could use association with langId. It worked. I tried to associate this parser with .txt file without success. I realized association with file extension does not work at all .
Here is the parser:

			<parser id="Heckl_md_header_parser" displayName="$functionName"> 
				<function mainExpr="#+ [\w\d ]*\s">
				</function>
			</parser>  			

Here is the association:

                        <association id=	"Heckl_md_header_parser" 	  ext=".txt"   				   		/>

**Comment by sasumner** [comment]
@heckl 

I have success with tying it to `langID`; recommend you try this:

`<association id="Heckl_md_header_parser" langID= "0" />`

**Comment by MAPJe71** [comment]
Known issue!Sent from my phoneOp 31 jul. 2019 16:10 schreef sasumner <notifications@github.com>:@heckl
I have success with tying it to langID; recommend you try this:
<association id="Heckl_md_header_parser" langID= "0" />

**Comment by sasumner** [comment]
@MAPJe71 Not sure that's a valuable comment, without a citation.  Also, maybe throttle back some of the spurious text from your phone, eh? :)

**Comment by heckl** [comment]
I realized that 
    <association id="Heckl_md_header_parser" langID= "0" />
only works if "language / normal text" is selected.

I thought I can used the "Markdown (Default)" language for highligt and at the same time use my parser for function list.

    <association id="Heckl_md_header_parser" userDefinedLangName="Markdown (Default)" />
seems to work just go to Language / define your language  / select Markdown (Default) / add txt to the extensions.

**Comment by MAPJe71** [comment]
@heckl 
Yes, that would be nice (I can't edit the page though).

**Comment by DGrv** [comment]
I could make it work for me with helped of post in the [Forum of Notepad++](https://community.notepad-plus-plus.org/topic/18458/display-markdown-outline-view-through-functionlist).

You have to modify your functionList.xml:
- associationMap part
  - it is important that your userDefinedLangName fit to the language used when your open your extension
- parser part
  - I modifiied the main expression in order to have before the # tag possibility to have 1 or several tabs (`|\t{1,5}`), because this is my way to structure my markdown file for lisibility : `"(?x)((?:^|\n|\t{1,5})[#]+\s+(.*?)(\r*|\n*)$)"`

Here what I mean regarding the tabs in my files
![Picture2](https://dorian-gravier.com/assets/blog/20200414_functionList_markdown_2.jpg)
![Picture2](https://dorian-gravier.com/assets/blog/20200414_functionList_markdown_3.jpg)


```xml
<associationMap>
	<association id=    "markdown_header"        userDefinedLangName="Md Drakula"           />
	<association id=    "markdown_header"        ext=".md"                                />
</associationMap>
```

```xml
<parsers>
	<!-- ======================================================== [ Markdown ] -->
	<!-- Based on code modified from https://community.notepad-plus-plus.org/topic/18458/display-markdown-outline-view-through-functionlist/7 -->
	<parser 
		displayName="Md Drakula" 
		id="markdown_header"
		commentExpr="">
		<function
			mainExpr="(?x)((?:^|\n|\t{1,5})[#]+\s+(.*?)(\r*|\n*)$)">
		</function>
	</parser>
</parsers>
```

Here the result:

![Picture2](https://dorian-gravier.com/assets/blog/20200414_functionList_markdown_1.jpg)

If someone knows how to use the `functionName` (example  below) to replace the \t with space in order that the hierarchy is more lisible in the function list it would be great. 

```xml
<functionName>
                        <nameExpr expr="(?:[#]+\s+)(.*)"/>
</functionName>
```
