### ISSUE TITLE
[IMPROVEMENT] Find and Replace Dialog

### ISSUE THREAD

**Issue by wonkawilly** [notepad-plus-plus/notepad-plus-plus#6010]
### Description of the Issue
What about to add a new button in **Find and Replace** dialog and in **Find and Replace in Files** dialog to switch the text content of the **Find what** text field with the **Replace with** text field?

The aim is to facilitate the user which needs to invert the text content of those fields. In fact at this moment in case you need to do the operation you have to do a lot of steps that make the operation really tedious, especially if you need to do it a lot of times for particular editing of the text file(s) you are modifying:

1. select the text of the **Find** field
2. copy/cut the text of that field
3. paste it elsewhere
4. select the text of the **Replace** field
5. copy/cut the text of that field
6. paste it into the **Find** field
7. select the text of the **Find** field previously pasted elsewhere
8. copy/cut that text
9. paste it into the **Replace** field

There are nine passages!!! IMHO it's way too much for a so simple operation that can be done automatically with a click on a button. Unfortunately I'm one that needs to do those operations really a lot of times per day so a button placed right there could facilitate a lot my complex editing and find and replace operations.

Look at the attached image file to see the aspect of the button I propose to implement: as simple as that:

![Notepad++ Find Replace Form New Button](https://user-images.githubusercontent.com/34818345/62495086-3d8bcd00-b7d5-11e9-805e-648c1e002fd7.png)
![Notepad++ Find Replace in Files Form New Button](https://user-images.githubusercontent.com/34818345/62495088-3e246380-b7d5-11e9-9727-c64d4703584c.png)

Thanks for comprehension.

**Comment by xylographe** [comment]
The Find dialogue is already too full and unclear. Another button in an awkward place is the last thing it needs. However, I would welcome a shortcut that delivers this switch functionality.

**Comment by wonkawilly** [comment]
@xylographe:
> The Find dialogue is already too full and unclear. Another button in an awkward place is the last thing it needs. However, I would welcome a keyboard shortcut that delivers this switch functionality.

IMHO the dialog is ok and clear enough to host another functionality and even more. Also a keyboard shortcut would be "visible" for the final user if there is a GUI element to make it know. Else it will remain hidden and unused. Also a normal user that uses n++ occasionally, cannot go to look up for the keyboard shortcut every time it forgets it just right before when it is needed. Else the keyboard shortcut must be indicated somewhere into the dialog it self. This will occupy some space. At that point the button would be better than having a note that says "To invert **Find what** with **Replace with** press Ctrl+Shift+Alt+i". No thanks: IMHO the button is the best choice and also it is self explanatory about what it does.

**Comment by dinkumoil** [comment]
I think an exchange button for the find/replace input fields would be a useful feature and indeed I've missed it quite a lot.

@xylographe 
The only reason why the Find/Replace dialog is unclear are these weird "Search forewards/backwards" buttons and the checkbox to activate them.  It was an ill concerned decison to include them because this dialog is the wrong place for that. There are already keyboard shortcuts for these features and by using the _Customize Toolbar_ plugin even toolbar buttons can be added.

**Comment by sasumner** [comment]
>Another button in an awkward place is the last thing it needs

(Strangely,) I sort of like the idea of, and the look and placement of, the proposed button. :)

BUT...it is not up to me; DonHo would have final decision on such a UI change to the Replace window.

>Else the keyboard shortcut must be indicated somewhere into the dialog it self.

The way keyboard shortcuts are done in the Find/Replace/Mark dialog is via Alt+"key".  They get "indicated" by having some text on a button, and then a press and release of the Alt alone shows the user the activating Alt+"key" combo by underlining a single character in the text.  (I realize the proposed button currently shows NO text).

>the button is the best, shorter, most visible, ergonomic choice and also it is self explanatory

But ignoring those that dislike the mouse is a bad design decision; there should be a keyboard way of activating it.

>The only reason why the Find/Replace dialog is unclear are these weird "Search forewards/backwards" buttons and the checkbox to activate them.

Some people love that.  Some people don't think it goes far enough (that would be me some time ago: https://notepad-plus-plus.org/community/topic/14372/the-find-button-has-returned-sort-of-and-has-brought-friends).  :)

**Comment by xylographe** [comment]
@sasumner 
In this case I meant a real keyboard shortcut, configurable in the Mapper. AFAIC no default is necessary. An Alt-X keyboard accelerator would require a visible Control (button, menu item).

**Comment by sasumner** [comment]
@xylographe 

>In this case I meant a real keyboard shortcut, configurable in the Mapper. 

This is unlikely (of course, perhaps the whole feature is same!) as it would set a new precedent.  Currently Shortcut Mapper has no influence on Find windows.

**Comment by wonkawilly** [comment]
@dinkumoil
> I think an exchange button for the find/replace input fields would be a useful feature and indeed I've missed it quite a lot.
> 
> @xylographe
> The only reason why the Find/Replace dialog is unclear are these weird "Search forewards/backwards" buttons and the checkbox to activate them. It was an ill-considered decison to include them because this dialog is the wrong place for that. There are already keyboard shortcuts for these features and by using the _Customize Toolbar_ plugin even toolbar buttons can be added.

Thank you for your support.
But I don't agree about what you say about forwards/backwards buttons: in fact I find them very useful: I use them continuously. I would just remove the checkbox to activate them and I would keep them always on.

**Comment by Ekopalypse** [comment]
@wonkawilly, isn't that one #4029 the same?

**Comment by sasumner** [comment]
@wonkawilly, why did you open a new issue for this?  It just makes more maintenance work for the people that process issues when you do this.  If you have new information to add (which you didn't AFAICT) you should just add it to the original issue.

But good point about the `...` button not having an alt+key combo; I never noticed that before.  See below for more on this button.

>doesn't have a keyboard shortcut and so others

As to the "others", the Alt+key stuff is not well-maintained by N++ developers any longer, and here's the reason why: N++ is capable of having its UI translated into many languages; picking an appropriate Alt+key combo for all those translations would be burdensome or even forgotten to do at the time the translation is done.   

The language translation capability also has a bonus for English:  you as a user can go in and make the UI text be whatever you want.  So if you don't like the default Alt+key combo (if there is one) for a given UI element in the Find windows, edit the XML and put/move `&amp;` right BEFORE the character you want to serve as the Alt+key key.

So back to the `...` button.  For a UI element to be translateable, it has to have an entry in a language's XML file.  The `...` button doesn't appear to have an entry there so it can't be translated, and thus can't have an Alt+key activator.

**Comment by wonkawilly** [comment]
àòà-à

**Comment by neil9327** [comment]
This feature is exactly what I came on here just now to suggest.
A common task I have is to replicate a paragraph of code for a sequence of table names. I do this by sequentially updating the table name in the piece of code, and copy-pasting it out one by one into an output script file. This means each time that I have to put in the "Find" window the text that I had previously put in the "replace" field.

**Comment by sasumner** [comment]
>IMHO this feature is a must have asap.
Hmmm, almost 2 years later.  :-)

I like this feature as well.  I will work on it and we'll see if it gets accepted.

A very-closely related feature I would like to see as well:
Very often I want to replace some text with something extremely similar (e.g. slight change to a variable name).  It would be nice to have a button that copies the _Find what_ box contents to the _Replace with_ box contents.  This is simply half of the "swap" that is the main focus of this issue.

**Comment by wonkawilly** [comment]
I'm really sorry if I'm bothering you all, but maybe the participants to this thread would want to give their opinion about this new and rich proposal about the improvement of the Find and Replace dialog at this link: #9627. Which will be a great improvement and perhaps even a real game changer for all of us that use N++ for more advanced uses than just editing the shopping list.
Please partecipate and ask others to. More opinion are welcome. Thank you all.

**Comment by capbussat** [comment]
Thanks for the implementation. I find it really useful.

**Comment by davidalayachew** [comment]
Hey, this is great. Any chance we could get a keyboard shortcut made for this too?

**Comment by shodanx2** [comment]
Hello here is my proposal for an improved Find & replace dialog 

<img width="2103" height="1184" alt="Image" src="https://github.com/user-attachments/assets/edcf3862-6e09-4842-85f7-7c79d93f10f6" />

Most of this is self-explanatory
If you think about it you can probably figure out what everything means but here is my explanation

This icon section means as follows

<img width="769" height="196" alt="Image" src="https://github.com/user-attachments/assets/4f78c126-e207-4c0e-818c-87e269d44764" />

Top row is search mode, this is "radio style" button only one can be enabled at once.
The modes are like current, but with one addition.

Literal search (normal mode)
Escaped Literal search (extended mode)
Regex Search (regex search)
Semantic search (no current equivalent, what would be a 250MB offline/local llm direct search module)

the rest are all toggle switches

<img width="772" height="205" alt="Image" src="https://github.com/user-attachments/assets/fdc7b937-ea16-4cea-be2a-dc4dfe7066b0" />

Case sensitive search
Diacritic sensitive search (that is accents and special characters, example  whether e matches é è ê ë and so on)
dot includes newline (this toggle only means something in regex mode)
fuzzy logic search ( this allows for instance "boat~" to find stuff like bat, boar, bost, oat, coat, goat, bots, boats, boating and combined with semantic search, it allows synonym search such as canoe, ship, ferry, yacht, vessel and off course, scooner )

<img width="767" height="199" alt="Image" src="https://github.com/user-attachments/assets/530716e7-fb2d-48c6-a77c-e4aa8c4c5631" />

wrap around
word search (match whole word only)
boolean search
and settings

Next we have the search and replace operators

<img width="1175" height="438" alt="Image" src="https://github.com/user-attachments/assets/f03ab94a-7142-4b8e-9602-c8a0ad0ab465" />

These are fully spelled out, and because we have separate buttons for "in document" and "in selection" we never have to care about checking "In Selection" ever again, that setting is simply made redundant !! Yay, my biggest pet peeve and worry and the impetus for making this proposal !

<img width="369" height="131" alt="Image" src="https://github.com/user-attachments/assets/bef9629d-eef7-4302-bb4c-ee27824047a1" />

And this last line of controls, represents the Mark operation, which I never remember exist when i need them and I won't go to another tab to use (instead I just double click the word and that's all I use the mark function, but this would be useful if it were more ergonomic to use)

So here is what the symbols mean

<img width="372" height="131" alt="Image" src="https://github.com/user-attachments/assets/f75f28cc-f095-4952-abeb-72bf171afc6c" />

Highlight previous
Highlight ALL
Highlight next

<img width="370" height="135" alt="Image" src="https://github.com/user-attachments/assets/3626de30-89c8-4472-b919-e0862b4eaae1" />

bookmark previous
bookmark ALL
bookmark next

<img width="606" height="135" alt="Image" src="https://github.com/user-attachments/assets/b5f07021-2958-4f35-a5d5-74ac3c928011" />

Copy highlights
Copy bookmarks
Delete bookmarks
Delete highlights
Delete ALL

and last is a toggle switch

<img width="127" height="122" alt="Image" src="https://github.com/user-attachments/assets/b863f6bb-bf0d-4b72-8e85-98e7097e5f41" />

This means "copy whole line" I should add the "copy" symbol as well. 
What this does when active, is when you click Copy Highlights, instead of copying only the exact highlight, which is just your find string with various case, it will copy the whole lines which contain highlights, which I think is more useful.
That one might not even be a toggle. I thought it would be a toggle because it could affect bookmark as well, but actually, "copy bookmarks" already copies the entire bookmarked lines. So probably this should just be a separate action

So maybe that 

<img width="285" height="280" alt="Image" src="https://github.com/user-attachments/assets/5e2b7d0b-6971-40e3-985c-2fe146b8f2b8" />

 
Ah and the setting button, would serve to hide the important settings that we don't need to interact on a day-to-day basis, but easier to get there than going to preference->whatever->etc..

<img width="572" height="557" alt="Image" src="https://github.com/user-attachments/assets/5b253855-3312-4019-bd0e-c102e26dbe23" />

And of course, once we have a single layout like this, it's easy to put a layout toggle in the settings menu

Example hiding the Mark/Bookmark section

<img width="1685" height="948" alt="Image" src="https://github.com/user-attachments/assets/73f0a337-db3a-488f-a6c2-d6db74cfccd3" />

Also, didn't have the time to include it and I have no more credits to make images but I would add a button to change the colours of "highlight/marks" so you can have multiple sets of highlighted terms with different colours. (Also I would make these sets independantly copiable/deletable from a list somewhere else)

hiding replace all in all documents

<img width="1681" height="943" alt="Image" src="https://github.com/user-attachments/assets/30835f9f-9ba3-4fa3-9e9a-c5411aa161a8" />

Hide replace functions

<img width="1602" height="947" alt="Image" src="https://github.com/user-attachments/assets/4e79a85d-4d97-4934-9d3d-5812cad19d49" />

**Comment by pryrt** [comment]
@shodanx2 , you already made this proposal in your own #16229; there is no reason to duplicate the suggestion in another already-closed issue as well.  You will find that being too overly eager with your proposals (creating multiple issues of the same, and posting the same suggestion in other related issues) can quickly be interpreted/perceived as spamming the issues repo, rather than a goodwill attempt to have a meaningful discussion.    Keep all of the discussion in your #16229, and you will come across better, and won't be accused of, or banned for, spamming.

If you want to "hook" into other discussions, the best way would be in _your_ conversation (ie, in a reply in #16229) to say, `I think what I've proposed here would be applicable/relevant to the discussions in issues #xyz and #pdq as well`, which will post the auto-links from the other discussions into your active discussion, without duplicating your proposal in multiple locations.
