### ISSUE TITLE
Brace matching with angled brackets does not work

### ISSUE THREAD

**Issue by Ekopalypse** [notepad-plus-plus/notepad-plus-plus#6013]
# Description of the Issue
Brace matching does not work with angled brackets but [code](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/92bad0a60ad606b30df9ed97aecf4ff27bb6e967/scintilla/src/Document.cxx#L2610) suggests it should

### Steps to Reproduce the Issue
type ( < > )
put caret after >

### Expected Behavior
The opening angled bracket as well as the closing angled bracket
should be highlighted as it does for round, curly and square brackets.

### Actual Behavior
Nothing happens

### Debug Information
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : D:\...\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

Failed on angled bracket
![image](https://user-images.githubusercontent.com/47723516/62538752-1c61c580-b843-11e9-96b3-1fd1a27dfe05.png)

Example of working round bracket
![image](https://user-images.githubusercontent.com/47723516/62538788-313e5900-b843-11e9-937e-69bd224c497b.png)

**Comment by sasumner** [comment]
Additional discussion on Community:  https://notepad-plus-plus.org/community/topic/18035/creating-a-new-coloring-matching-character/

**Comment by sasumner** [comment]
@Ekopalypse 

In `Notepad_plus::findMatchingBracePos()`, there is code like this in two places:

`TEXT("[](){}")`

Seeing that makes me think the the omission of `<>` is intentional.  I'm wondering if the common usage of `<` and `>` for less-than and greater-than, respectively, in programming languages, where they are NOT part of a bracketing pair, convinced the original author of this code that it would be too annoying to the user to have Notepad++ continually processing and showing oddball brace-matching for these characters.  What's your feeling?

**Comment by Ekopalypse** [comment]
That makes perfectly sense. I tried to find if there is git commit explaining the reasons not to include angled brackets but it seems that this was already decided before moving to github. At sourceforge 
I found some statements that it doesn't work because of being used as an operator but nothing concrete.
I'm going to close this and inform the OP from the community. Maybe there will be feature request coming for languages which don't use angled brackets in their syntax!?
