### ISSUE TITLE
Theme not saving in portable mode

### ISSUE THREAD

**Issue by saudiqbal** [notepad-plus-plus/notepad-plus-plus#6092]
Notepad++ settings file config.xml saves the full path to the directory instead of relative path in settings file which makes Theme default to white in different computers. Even if I try environment variables like %OneDrive% it still extracts the full path and makes it permanent.

Please fix this bug.
`<GUIConfig name="stylerTheme" path="%OneDrive%\NPP\themes\Obsidian.xml" />`
Becomes
`<GUIConfig name="stylerTheme" path="E:\OneDrive\......\themes\Obsidian.xml" />`

Even using relative path
`<GUIConfig name="stylerTheme" path="themes\Obsidian.xml" />`
Becomes
`<GUIConfig name="stylerTheme" path="E:\OneDrive\......\themes\Obsidian.xml" />`

**Comment by TehPsychedelic** [comment]
I almost got this working (modified addThemeFromXml() at Parameters.h) however I think by design it would be complicated to reach a compromise (unless the compromise is to support env vars on the path). For example, users may install Notepad++ to c:\Program Files, then, say you want to have a few custom themes for your (e.g) non-admin user, so you copy those to %appdata%\Notepad++\themes. Then the application will gladly load the default themes from the installation folder PLUS the ones in %appdata%, so as you see there is a mixture there that would make it hard to handle if you were to only use relative paths.

**Comment by saudiqbal** [comment]
I don't think the author cares too much about this problem.

**Comment by TehPsychedelic** [comment]
Indeed, portable mode is more of an afterthought that just works. However most people love installing apps, the few of us that loathe the registry or any kind of installation are the minority by thousands or millions.

**Comment by sasumner** [comment]
>portable mode is more of an afterthought that just works.

I don't know that this is a true statement at all.

**Comment by ArkadiuszMichalski** [comment]
I vote for it, especially in the case of the portable/locale version, all paths in the `config.xml` (for files from the portable folder) should be relative to the `notepad ++. exe file`.
