### ISSUE TITLE
User-Defined Language, review comment line

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#612]
Hi,
i have problem at Comment & Number/Line comment position TAB:

There is no difference between "Force at beginning of line" and "Allow preceeding whitespace": (see photos)

and you can change these features in: 
-inline comment (space, tabs or characters are accepted)
-force at beginning of line...
![001](https://cloud.githubusercontent.com/assets/13587582/9007038/f2c62386-378d-11e5-834e-d0e845f29a43.jpg)
![002](https://cloud.githubusercontent.com/assets/13587582/9007039/f2cee282-378d-11e5-9567-b348aab13324.jpg)
![003](https://cloud.githubusercontent.com/assets/13587582/9007040/f2da340c-378d-11e5-83cb-b360320cb8bf.jpg)

many thank's for all

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
