### ISSUE TITLE
Search Window Goes Off Screen

### ISSUE THREAD

**Issue by frankforte** [notepad-plus-plus/notepad-plus-plus#613]
![notepad_plus_plus_window_bug](https://cloud.githubusercontent.com/assets/898430/9008619/7fdddc70-3769-11e5-9e75-7a5030eb6c15.png)

Sometimes when connecting a second monitor, the search window goes half way off screen. The title bar becomes inaccessible, with no way to move it!   It becomes impossible to use.  Disconnecting and/or reconnecting the second monitor does not help.

Please allow the search window to be dragged when clicking any part of the window, not just the top title bar (which I cannot click right now!). Alternatively, if it is above the top of the screen, the window should automatically be repositioned so that it is accessible again.

If the top of the search window is above the top of the screen (either screen), it should automatically move down and maybe a bit to the right so that the title bar can be accessed.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
