### ISSUE TITLE
Menu Icons disappear after the menu has dynamically changed

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#614]
Hello,

Can anyone think of a possible cause/solution to [this](https://notepad-plus-plus.org/community/topic/238/menuicons-disappear) bug in the MenuIcons plugin?

Thank you.

**Comment by milipili** [comment]
@Yaron10  sorry for the long wait. Still got issues on that ?

**Comment by Yaron10** [comment]
Hello milipili,

The problem is still there.
Thank you.

BR

**Comment by MetaChuh** [comment]
hi @Yaron10 
another cleanup issue, i hope you don't mind.
we have to do that, as it is impossible to read the tracker filled with old ballast right now, without wanting to shutdown the pc and do something else 😉.

greetings

-----

we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
