### ISSUE TITLE
Find & Replace window does not always open in the same display as Notepad++

### ISSUE THREAD

**Issue by arvindhmani** [notepad-plus-plus/notepad-plus-plus#6141]
### Description of the Issue

NOTE: This bug is observed only when multiple displays are available.
This issue is noticed when Notepad++ was earlier in a particular display. If it is moved to another display and then the Ctrl+F or Ctrl+H hotkeys pressed, the Find & Replace window opens in the previous display where Notepad++ first was.

### Steps to Reproduce the Issue

1. Open Notepad++. Let's say it opens on Display 1.
2. Move the window to another display, say Display 2.
3. Press Ctrl+F or Ctrl+H.

### Expected Behavior

The Find & Replace window should open on Display 2.

### Actual Behavior

The Find & Replace window opens on Display 1.

**Comment by sasumner** [comment]
The Find window initially opens (the first time) centered on the Notepad++ main window.  If the user moves the Find window (likely, because centered is likely annoying), then the position moved to is remembered as the "desired" position.  It is then forevermore independent of the position of the Notepad++ main window.  This behavior is by design.
