### ISSUE TITLE
[Feature Request] 'Show white space and TAB' should be separate options.

### ISSUE THREAD

**Issue by LAPIII** [notepad-plus-plus/notepad-plus-plus#6145]
The tab arrows are very useful. I only use tabs in lists.

**Comment by dinkumoil** [comment]
Showing indicators for whitespace characters is done by Scintilla, the underlying edit component Notepad++ uses internally. It is not possible to turn on tab arrows and space indicators separately, see [here](https://www.scintilla.org/ScintillaDoc.html#WhiteSpace).

You could file a feature request at the [Scintilla project site](https://sourceforge.net/p/scintilla/feature-requests/).

**Comment by LAPIII** [comment]
They responded to the ticket [here](https://sourceforge.net/p/scintilla/feature-requests/1313/).  They gave the code, and: 

> I do not use or work on Notepad++ and have no idea how to change its code.

Possibly that code is in `Do youkniw how to get to `%APPDATA\Notepad++\config.xml`? I tried puttng `%APPDATA`into File Explorers address bar,ut that didn't work.

**Comment by xylographe** [comment]
@LAPIII If you install the LuaScript plug-in you can change the [white space Scintilla settings](https://dail8859.github.io/LuaScript/classes/Editor.html#White_space).

**Comment by sasumner** [comment]
@LAPIII 

So with Luascript as @xylographe mentioned above, or with Pythonscript as follows:

`editor.setWhitespaceSize(0)`

You can make the dots that identify a space character invisible, which seems to be what you are wanting when one considers you saying "The tab arrows are very useful."

However, if one considers your title text `'Show white space and TAB' should be separate options` then the scripting does not help for the opposite case, where one might want the space-dots but not the tab-arrows to be visible.

But I will close this issue because it seems that what you truly want has been satisfied.
