### ISSUE TITLE
BUG: Map highlight in multiple desktop

### ISSUE THREAD

**Issue by Mava02** [notepad-plus-plus/notepad-plus-plus#6149]
### Description of the Issue

If you're working with Notepad++ on a PC with one screen but multiple desktops, if you activate Document Map and you switch desktop, you will get the map highlight in the same position.

### Steps to Reproduce the Issue

1. In Notepad++, activate Document Map
2. Switch desktop with 'CTRL+WIN+Right arrow' or WIN+TAB

### Debug Information

Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by FabienFellay** [comment]
### Confirmation of the issue
I confirm this issue. I am also suffering from this since months. Find below 2 screenshots showing the bug: 

- The first screenshot shows that Notepad++ with document map is opened on desktop number 01.
- The second screenshot shows an empty desktop number 02 featuring a kind of 'ghost' map highlight at the same position (the bug).

![Desktop_#01](https://user-images.githubusercontent.com/33905146/66088333-09d1e700-e57b-11e9-9101-aa6ff77e6341.png)
![Desktop_#02](https://user-images.githubusercontent.com/33905146/66088347-19513000-e57b-11e9-85e9-d7498984e22b.png)

### Debug Information
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll

**Comment by korpx** [comment]
Bug verified. This issue seem to be a duplicate of the earlier reported https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5294

**Comment by Mava02** [comment]
Closed as a duplicate of #5294
