### ISSUE TITLE
[Feature Request] Not highlight word when opening 'Replace' and insertion indicator is at a word 

### ISSUE THREAD

**Issue by LAPIII** [notepad-plus-plus/notepad-plus-plus#6161]
## Description of the Issue
When opening 'Replace' and insertion indicator is at a word, that word highlights.

### Steps to Reproduce the Issue

1. In a tab with text, leave insertion indicator at a word  
2. Press 'Ctrl + H'

### Expected Behavior
Nothing to be highlighted nor in the appear in the 'Find what' text box.

### Actual Behavior
The word that the insertion indicator is at will highlight and that word will appear in the 'Find what' text box.

**Comment by sasumner** [comment]
Sorry, that behavior is by-design and is long-standing functionality.  It won't be changed.

If you have something in the `Find what` box that you don't want to lose, either switch to the Find/Replace window with the mouse, or move the caret to be surrounded by some whitespace before invoking via keyboard.

[On a personal note, I'd like to see that same word appear in the `Replace with` box as well when invoking ctrl+h, because often I just want to do a slight tweak to something existing and it would save me time to have the original there.]
