### ISSUE TITLE
Auto Save with Revision feature

### ISSUE THREAD

**Issue by mbailey218** [notepad-plus-plus/notepad-plus-plus#617]
Don't you hate it when you've been writing some code, it's working, and then you make some changes and then all the sudden it starts crashing and you're not sure exactly what you changed?

I'd love to see an "Auto-Save" feature that could either be event, or time based, and/or a single button on the tool bar that I could click which would automatically save my file with a revision number appended.  I'd like to be able to configure the auto-save settings, and specify what pattern to use for my revision schema.

Thanks,
Mike

**Comment by aaaxx** [comment]
@mbailey218
In the meantime you can help yourself with "Preference > Backup > Verbose backup". It will make a timestamped copy of your file at every Save.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
