### ISSUE TITLE
add download from github release page

### ISSUE THREAD

**Issue by laroche** [notepad-plus-plus/notepad-plus-plus#6174]
Download from the official project site seems to be very slow.You could add the
binary releases also to the github.com release page to have an alternative download
site.

best regards,

Florian La Roche

**Comment by sasumner** [comment]
No. That has been discussed before.  The quantity of download would create an unaffordable cost.

**Comment by Ekopalypse** [comment]
Not sure about that and maybe has changed since then because github, officially, states
_We don't limit the total size of your binary release files, nor the bandwidth used to deliver them. However, each individual file must be under 2 GB in size._
See https://help.github.com/en/articles/about-releases#limitations-on-binary-files
