### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by dmitryponv** [notepad-plus-plus/notepad-plus-plus#6175]
Not sure if this is the right place to post feature requests

I would like to request adding the Find in Files feature of Notepad++ to the context menu in Windows, so right clicking on a folder would take the user to the Find in files prompt with that folder listed in the search directory.

**Comment by sasumner** [comment]
>this is the right place to post feature requests

It is the right place.

>...context menu in Windows (Explorer), so right clicking on a folder would take the user to the Find in files prompt with that folder listed in the search directory.

There is a fairly expeditious way to do that already.  Maybe you don't know it?  Since you are talking about Explorer, drag a file from the desired folder into Notepad++.  Press Shift+Ctrl+f.  The directory of the file should now be in the Directory box (assumes `Follow current doc.` is checked).  Perform your search.  I do this type of thing all the time; I find it very fast.

**Comment by sasumner** [comment]
No followup by OP; presume that the response provided is adequate.
