### ISSUE TITLE
Npp freezez when oppening workspace that is not available due to network

### ISSUE THREAD

**Issue by tm8544** [notepad-plus-plus/notepad-plus-plus#6178]
### Description of the Issue
I use View Foldr as Workspace feature, and the folder is on a network drive.

When I'm outside my home network and that given folder is not available, Npp does not start, it freezes while trying to open the folder.

### Steps to Reproduce the Issue
1. Open a network folder as a workspace. See that it functions as expected
2.  Close Npp, close computer
3.  Connect the computer to another network, srat windows and open Npp
4. Npp freezes

### Expected Behavior
Npp would start without freezing.
perhaps informing that workspace folder is not available, or maybe silent,

Anyway, user should not be expected to remove folder from workspace every time before closing Npp, if there is expected to be some change in network.

### Actual Behavior
Described above

**Comment by ddgunter** [comment]
I have a very similar issue. I include it here since it is probably the same bug:

# Steps to Reproduce the Issue
1. Map a network location to a drive letter, like "Y:".  Let's assume that this network is at work.
2. Create a file on that mapped drive.
3. Open that file in Npp.
4. Sleep laptop and go somewhere that this network location is not available, like home.
5. Wake laptop and change to Npp application with this network file open.
6. Npp freezes.

**Comment by iliptak** [comment]
I have a similar issue that manifests with a network drive mapped and still available in Windows 10.



I use NPP on my Windows 10 (Home) laptop and have PHP files on my desktop PC (that I also use to run XAMPP). 
The partition of the PC that has the PHP files is mapped on my laptop and connected automatically.
I open a PHP file to edit it, do what I need to do, and leave it open for later. 
When I switch to another program for a while - say, half an hour - then back to NPP, it becomes unresponsive for anywhere between 10 and 40 seconds. 

Note that the network drive is available and mapped.



### Steps to Reproduce the Issue

1. Map network  drive under Windows 10
2. Open file from the network drive in NPP
3. Switch to another program/window
4. Switch back to NPP after 20-30 minutes

### Expected Behavior

To be able to continue to work immediately on the file that's open

### Actual Behavior

NPP freezes/becomes unresponsive for 10 to 40 seconds, then behaves normally

### Debug Information

Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll

**Comment by AntonKukoba1** [comment]
The freeze also happens if you try to close the tab for the file which was situated on the network share which became unreachable.

**Comment by donho** [comment]
@AntonKukoba1 @iliptak  @tm8544 
Please try the latest state of fixed binary here (x64):
https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/11118197845/artifacts/1998785683

The hanging issue should be improved considerably.

**Comment by tm8544** [comment]
I tested as follows:
- opened a text file on a network drive
- disconnected the network
- tried to reload the text file

Notepad++ was unresponsive for a while, about 60 seconds, then it recovered and displayed a dialog saying that the file does not exist anymore and asked if I want to keep the file in editor.

**Comment by donho** [comment]
> tried to reload the text file
Notepad++ was unresponsive for a while, about 60 seconds, then it recovered and displayed a dialog saying that the file does not exist anymore and asked if I want to keep the file in editor.

Hanging cannot be avoid, since the file is inaccessible physically, what I'm trying to do is reduce the hanging time.
So my question is: Is the situation improved for the fixed binary?

**Comment by tm8544** [comment]
It is improved.
