### ISSUE TITLE
Add editorconfig built-in/out-of-the-box

### ISSUE THREAD

**Issue by rugk** [notepad-plus-plus/notepad-plus-plus#6183]
There is a de-facto standard called "editorconfig", which tries to make collaboration easier by using a simple `.editorconfig` file, which sets options such as indentation or tabs/spaces usage for a project.

More information can be found on http://editorconfig.org/.

Many applications already include this feature by default (see http://editorconfig.org/#download) including famous code hosting platforms such as GitHub etc.
Also for Notepad++ there is a plugin available: https://github.com/editorconfig/editorconfig-notepad-plus-plus

It would be nice to have this included by default - maybe even activated by default - so one does not need to care about it and it all works. (or just re-code/hardcode it)
Including this would be logical as GNOME Builder also supports it by default, so when switching between applications, this would ensure consistency.
All in all Editorconfig's aim is consistency and with widespread adoption of it, this goal can be reached.

----

I've [also written in the forums about it](https://community.notepad-plus-plus.org/topic/18304/notepad-should-support-editorconfig-out-of-the-box).

**Comment by sasumner** [comment]
Closed (duplicate).

**Comment by rugk** [comment]
…of which issue?

**Comment by rugk** [comment]
In case you've meant #3389, this **is not a dupe**. The issues tackle different things (editorconfig support vs usage in source code).
I've explained the difference in detail, here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3389#issuecomment-536738140

As such, please reopen this issue.

**Comment by sasumner** [comment]
OK, reopening.  Do we know if Scintilla supports enough of the editorconfig stuff so that this could be realized?

**Comment by rugk** [comment]
I dunno. That [is not listed here](https://editorconfig.org/#download), so I doubt so. :smile:

**Comment by treyhunner** [comment]
As a Python teacher, **I'd love to have EditorConfig support built-in to Notepad++**.

I do Python trainings for a living and many of my clients use Notepad++ (I always recommend my students use the editor they're already familiar with if possible).

Unfortunately, since Notepad++ defaults to tabs for `py` files, whenever my students edit *my* Python class files they end up inserting tabs into them which produces a file with mixed tabs and spaces which is invalid in Python.

Since all the other editors my students tend to use (Visual Studio, Atom, Sublime Text, VS Code, etc.) default to 4 spaces in Python files, I need to work with this community standard of 4 spaces so the "just use tabs" solution won't work for my situation.

While I'd love to see #5506 (defaulting Python to 4 spaces instead of tabs) resolved, that seems unlikely based on the comments there.

I realized that even with #5506 closed as "won't fix", this issue on adding built-in EditorConfig support, could fix my issue as well (because I include a `.editorconfig` file in the repository of skeleton `py` files they work from).

I imagine many other Notepad++ users in the Python community would probably find this issue very helpful as well (since the majority of us use 4 spaces for indentation).

**Bias note**: I'm in a somewhat awkward position in that I originally created EditorConfig along with Hong Xu, so I'm certainly not unbiased on this matter. (As one of the EditorConfig co-founders, I'd also love to see EditorConfig support built-in as well of course.)

**Comment by chcg** [comment]
See https://github.com/editorconfig/editorconfig-notepad-plus-plus#readme about the supported editorconfig functionality by the N++ plugin. It is working for me.

**Comment by ffes** [comment]
Adding the plugin during installation of Notepad++ could also be an option. No need for the authors of N++ to keep up with the ongoing things in the EditorConfig world and the users of N++ will just get the support they expect when an .editorconfig file is present in their code tree.

But I am afraid this is not going to happen. I see the list of plugins offered during installed being reduced over time to the ones that Don made himself.
And since the repo of N++ doesn't even have a .editorconfig file (and looking at the age of #3389 is not gonna get) I don't see support being built-in any time soon.

> There seems to be a plugin for this for Notepad++; is the plugin insufficient?

It works fine. Use it literally on every project I work on.

But being a contributor/maintainer of the Notepad++ EditorConfig plugin I may be biased 😉

**Comment by sasumner** [comment]
>...the list of plugins offered during installed being reduced over time to the ones that Don made himself

I see this as a good thing.  I'd like to see NO plugins at install time for N++, actually.

**Comment by rugk** [comment]
It's just a matter of definition of what you consider "important" ("default") for an IDE/editor today in 2019, and what you consider an additional feature/optional ("plugin").

How you technically implement it (in the main code base vs default installed plugin) hardly matters then…

**Comment by sasumner** [comment]
Just a note in reading over the previous comments in this thread:

>Unfortunately, since Notepad++ defaults to tabs for py files, whenever my students edit my Python class files they end up inserting tabs into them which produces a file with mixed tabs and spaces which is invalid in Python.

Notepad++ now defaults to spaces for py files, on a clean install.  If updating an older version of Notepad++, it will keep the old default to insert tabs (in which case the user has to change this, but only one time).

**Comment by donho** [comment]
It's not a good idea to follow the outside rules - once the rules change, our code should follow too.
This feature won't be implemented as built-in feature. User can always use the plugin:
https://github.com/editorconfig/editorconfig-notepad-plus-plus
