### ISSUE TITLE
Locking files

### ISSUE THREAD

**Issue by elicym** [notepad-plus-plus/notepad-plus-plus#623]
It would be really useful to have the option to open a file and 'lock' it, until the file is closed, similar to the way MS Word locks files. This means I don't need to be concerned about overwriting changes made to the file during my edits.

**Comment by szheng95** [comment]
This should be an option - the ability to work on a file without locking it is one of NPP's key features for me.

**Comment by elicym** [comment]
Absolutely, but once in a while it would be really useful to lock it. So I don't think it should be an option, but a separate menu item (Open with Lock), or a checkbox on the open file dialog.

**Comment by milipili** [comment]
A menuitem would be good indeed

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
