### ISSUE TITLE
manually activated autocomplete list not properly working

### ISSUE THREAD

**Issue by chrd5273** [notepad-plus-plus/notepad-plus-plus#625]
While using notepad++ in javascript, I noticed some bug on autocomplete list.
For example, if i want `appCodeName` and I type `app` then press `ctrl-space`, there only appears "Applet". if i type `appCode` then press `ctrl-space`, nothing appears. It seems that the notepad++ cannot recognize lower-case 'a' if some specific letters-like 'p' or 'b'-are followed. You can avoid this bug by adding `<Enviroment ignoreCase="no"/>` in the first line of the autocomplete file. But this forces case sensitive autocomplete.

This is very annoying because I am trying to add `appendChild` to function autocomplete list. But one strange this is, there is no problem in list that appears as you type in. Only list that appears by `ctrl-space` have this problem.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
