### ISSUE TITLE
Opening files per drag&drop form explorer does not work anymore

### ISSUE THREAD

**Issue by 1Nick1Name** [notepad-plus-plus/notepad-plus-plus#663]

**Comment by Croydon** [comment]
You should provide more information. Do you use the latest Notepad++ Version, on what OS are you? 
It's working fine for me. Perhaps you running Notepad++ as an Admin?

**Comment by Rikk** [comment]
Drag-drop often fails when one of the two programs is running with elevated privileges (ie. as admin).

**Comment by 1Nick1Name** [comment]
os is windows.
notepad is the latest.
runnig as admin ... how should i know?

works now. happened just after uüpdating.

**Comment by Croydon** [comment]
It's written in the title "[Running as Administrator]" or something similar. After updating, Notepad++ is running as an admin. This issue was discussed somewhere else by @donho and some other people, but I don't remember the issue(?).

**Comment by 1Nick1Name** [comment]
Well as it's working now and problem seems to be related to installaing or running in admin mode,
shall I close this issue now?

**Comment by Rikk** [comment]
Yes

**Comment by h-h-h-h** [comment]
@Rikk:
> Drag-drop often fails when one of the two programs is running with elevated privileges (ie. as admin) and the other normal privs.

@1Nick1Name:
> it's working now and the problem seems to be related to installaing or running in admin mode

There seems to be a possibility to make it work. Please google for `ChangeWindowMessageFilter admin drag drop`. If this really works, it should be incorporated. What do you think about it?

**Comment by GitMensch** [comment]
@h-h-h-h Yes I think "if it works" it would be a nice feature.
@milipili Do you know of any possible security issues? Should we discuss this here more or create a new feature request issue directly?

**Comment by cmeriaux** [comment]
It works fine on my config
Use the debug info.

> Notepad++ v6.9
Build time : Mar  4 2016 - 09:09:43
Path : C:\soft\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : CodeAlignmentNpp.dll ComparePlugin.dll Explorer.dll FileFinder.dll HexEditor.dll LanguageHelp.dll LightExplorer.dll MenuIcons.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppMarkdown.dll NppMenuSearch.dll NppTaskList.dll PluginManager.dll PythonScript.dll SherloXplorer.dll WindowManager.dll

**Comment by GitMensch** [comment]
Thank you for your answer.

It doesn't work for me if NPP was opened as Administrator and the drag'n'drop comes from a "normal" explorer / another application.

~~~~
Notepad++ v6.9
Build time : Feb 21 2016 - 21:27:55
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : CodeAlignmentNpp.dll ComparePlugin.dll LocationNavigate.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppJumpList.dll nppplugin_ofis2.dll nppplugin_solutionhub.dll nppplugin_solutionhub_ui.dll nppplugin_svn.dll NppSaveAsAdmin.dll PluginManager.dll SourceCookifier.dll SpellChecker.dll 
~~~~

You can see the `+` when dragging in the tab area, on drop nothing happens. This works fine in a "normal" setup but I've read this issue is about "Admin mode: ON".
