### ISSUE TITLE
Preferences: the main toolbar is not properly refreshed when switching over small/big icons

### ISSUE THREAD

**Issue by milipili** [notepad-plus-plus/notepad-plus-plus#673]
![small-big-icons](https://cloud.githubusercontent.com/assets/5516919/9138053/faeaeabc-3d21-11e5-8d81-33e6cda8c97d.png)

Especially after selecting "Big icons", the toolbar is not resized.

**Comment by Rikk** [comment]
?
Looks ok here:
![bigico](https://cloud.githubusercontent.com/assets/2916485/9147211/771f9c5a-3d3a-11e5-8597-02b7dd5ee5e3.gif)

**Comment by Croydon** [comment]
That's interesting, sometimes it's working for me, sometimes not.
In some cases I don't see icons at all, in some cases the height of the toolbar isn't getting smaller when I'm switching from the big icons to the small icons. Just try to wildly change this option in different orders. I can't see a real pattern there. I'm on Windows 7.

A bit off-topic: I suppose the big majority will agree that the old icons are ugly. Why keep them? Same with stuff like the old application icon, which you can select in the installer. What's the purpose of that?

**Comment by Rikk** [comment]
Imo, people could even ditch the idea of a new interface if we use cooler iconset.
Having 'big icons' using the same 'standard icons' would be a good start.
Also, 'small icons' have the same size of 'standard icons', so imo they are doing nothing.

**Comment by Croydon** [comment]
Speaking of me, I won't drop my friendly request for a new UI just because of new icons. Some fonts are too small in menus to be eye friendly, the navigation texts in the option dialog is for e.g. cut off, because of a too narrow navigation and on a lot spots the colours don't match the set theme.

Also it's hard to navigate in the menus because of so many options (which is great, but then you need a good UI as well) and too less icons or seperations on which you can orient yourself.

**Comment by Croydon** [comment]
Related: #686

**Comment by Rikk** [comment]
I reproduce this when using higher-dpi.
