### ISSUE TITLE
Replacing from my regex find, does nothing

### ISSUE THREAD

**Issue by GoldfishSandwich** [notepad-plus-plus/notepad-plus-plus#713]
I'm using the regex `(?<=\d)"(?=\s)` to find the quote marks at the end of a number in a tab/newline delimited file. In the find and replace dialog, when I click on <kbd>Replace</kbd> my selection is advanced to the next find result, but the previously selected " isn't replaced. My replace value seems irrelevant, I started with no replace value (removing " ) and tried using some random keysmash with no different results. 

Notepad++ v6.7.9.2

**Comment by dail8859** [comment]
It works for me in v6.8.1. What is your file encoding (toward the bottom right of the screen, ANSI, UTF-8, etc)?

**Comment by GoldfishSandwich** [comment]
@dail8859  UTF-8 Without byte order marking, my line endings are UNIX ( `/n` ), if that makes a difference. I also updated to Notepad++ v6.8.1. The file changed indicator (* in title bar, blue/red floppy) isn't going off when I <kbd>Replace</kbd>. I tried toggling the multi-selection (<kbd>Ctrl</kbd>+ <kbd>Mouse Click</kbd>) setting. I just tried running <kbd>Replace All</kbd> and it worked, along with <kbd>Replace All</kbd><kbd>In Selection</kbd>. 

I also just tried: 
- `(?<=\d)\"(?=\s)`
- `(?<=\d)["](?=\s)`
- `(?<=[0-9])[\x22](?=[ \t\r\n\v\f])`
- `(?<=\d\d)"\s"`
- `(?<=\d)"`
- `"(?=\s)` 
<hr>
- This works `"(?=\s)`
- This doesn't `(?<=\d)"`


To me this suggests that the Regex Lookbehind [ `(?<=...)` ] code is somehow misbehaving.

**Comment by goozak** [comment]
This bug is still present in v7.2.2.  Encoding and line ending doesn't seem to be a factor.  Found text is properly highlighted, but the replacement isn't happening.

Bug title should probably be : "Unable to replace text found with a regex that contains a lookbehind"

I'm guessing not enough users are using lookbehind to bring this bug near the top of the pile.  :-)

**Comment by dail8859** [comment]
Additional info: If there is only 1 match in the file then the replace works. If there is more than one match, the replace doesn't work.

Looking at the code seems to be due to starting to search at the caret's position, but in theory it would have to start before that to be able to "look behind". I don't know of a simple solution currently.

**Comment by goozak** [comment]
Just curious - since this bug is still present, why close it?
