### ISSUE TITLE
Multiple Notepad++ update boxes

### ISSUE THREAD

**Issue by GaurangTandon** [notepad-plus-plus/notepad-plus-plus#714]
**PC:** Windows 7

**Problem:**
It often happens that while working on my browser, I launch Notepad++, go to update it, and then it starts running in the background. But, then, while running, the new boxe's icon doesn't show up in the taskbar _and_ gets hidden behind all the windows open. As such, I get confused and launch another update, hoping that the previous one didn't complete. With the result, when I close all the application windows, multiple Notepad++ update boxes are downloading the packages.

**Proposed solution:**
Run a quick check so as to make sure that there is no update box running in the background when the user initiates a update request to download updated packages.

Picture of the update box (in case it sounds ambiguous as to what i am talking about);

![update box](http://s21.postimg.org/wb19fryhj/npp.png)

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
