### ISSUE TITLE
Null characters terminate strings in directory search result list

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#716]
![2015-08-14_174630](https://cloud.githubusercontent.com/assets/5197361/9277758/7dc3903a-42ac-11e5-84f5-c08666465175.png)
The image and title pretty much explain it.
If important, I am using the latest notepad++ version on win 8.1

**Comment by milipili** [comment]
Any character actually, not just only null characters

**Comment by dail8859** [comment]
Just curious why wouldn't this be labeled a bug? The find result clearly show a line without a match in it when it should.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
