### ISSUE TITLE
Wrong line spacing

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#720]
Hello,

when you choose a small font size for the Scintilla control, but a large font size for the line number margin and hide the line number margin, the line spacing of the text in the Scintilla control is too big.

I can't think of a better behavior than having a too large line spacing when having the line number margin shown, but when it's hidden, I think the line spacing is not necessary.

_Advantage:_ When having box drawing symbols in the editor you could easily show them joined by hiding the line number margin without being forced to change the font size of the line number margin. Surely there are other cases where you would benefit from a different behavior.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
