### ISSUE TITLE
Jumping block selection

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#730]
Hello,

you can use <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>Left</kbd>/<kbd>Right</kbd>/<kbd>End</kbd>/... for block selection spanning multiple lines. However, this type of selection can have a behavior that's not desirable in my opinon:
- Use this text:

```
aaaaaaaaaaaaaaaaaaaa
aaaaaaaaaa
aaaaa
aaaaaaaaaaaaaaaaaaaa
aaaaaaaaaa
aaaaa
aaaaaaaaaaaaaaaaaaaa
aaaaaaaaaa
aaaaa
```
- Put the cursor at line 1, column 1 and start selecting with <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>End</kbd>
- While holding <kbd>Alt</kbd>+<kbd>Shift</kbd> go down with <kbd>Down</kbd> and you'll notice a jumping selection

In my opinion a jumping selection is not desirable while block-selecting. The cursor should stay exactly where you have put it. You can go past the ends of lines anyway with <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>Right</kbd>.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
