### ISSUE TITLE
Make anit-aliasing optional - regalrdless of the ClearType system settings

### ISSUE THREAD

**Issue by fghber** [notepad-plus-plus/notepad-plus-plus#731]
I just installed Notepad++ on Windows 10 and noticed bad font rendering. First I thought it's due some incompatibility. But it turned out that the fonts look as usual if I use an older build - pre 6.5.4. There is a closed issue that made the font anti-aliasing following the system settings: Since this is a good idea, I would to suggest to make this optional, as if people - like me - like ClearType in general, expect in N++. Therefore, this is more an RFC then an issue. However, I guess many people are interested in such an option.
Many thanks and best wishes.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by fghber** [comment]
I think it was fixed. I have no issues with the default font rendering of N++ anymore.

**Comment by MetaChuh** [comment]
@fghber 
great to hear that is is fixed.
thanks for reporting back.
