### ISSUE TITLE
Suggestion: Move Issue Tracking somewhere else

### ISSUE THREAD

**Issue by IamRifki** [notepad-plus-plus/notepad-plus-plus#7450]
Seriously though, this is getting out of hand.

**Comment by Jan200101** [comment]
#7407 related
but that would not help too much unless someone finds a issue tracker that is blocked by china
I'd suggest disabling issues for the time being

**Comment by Orlys** [comment]
I think M$ should add some validation mechanisms for the new members to avoid today's situation.

**Comment by FlyEmojiStudiooo** [comment]
nah, if block country they can use VPN or something to be unblocked
And I think GitHub and notepad++ need do something.

**Comment by Jan200101** [comment]
forcing them to use a VPN would be a step in the right direction I suppose
I agree that GitHub should step in but I don't think they will

**Comment by Jan200101** [comment]
temporary sure
permanently it could pose a problem

I myself started out by just reporting issues

**Comment by Orlys** [comment]
Can somebody provide the report link to suggest M$ to improve what this repository occurred?

**Comment by FlyEmojiStudiooo** [comment]
But Issue maybe need locked on a long time

**Comment by michaellee8** [comment]
There are good strategy to deal with these stupid dumb ass/bots, I should post it here as well:

1. Considering those issue spammers, I believe that it is possible to make a script to immediate close all those issues with the GitHub's API, maybe just scan for Chinese characters inside in those posts and close them automatically.
2. I would also suggest a permanent repo ban to those spammers, a significant proportion of those issues are with identical title and content.
3. I believe that you should contact GitHub support asap so that they can do something about this, maybe ban those users from GitHub permanently or even issuing a region restriction to your repo temporarily since most Chinese don't access GitHub with VPN (they don't have to yet).

I guess I will start to implement a Golang bot for it in Golang soon, since these kind of ridiculous attack would happen more and more frequently these days. I am unfortunately hoping that gfw would do a GitHub ban as well.

**Comment by luciusmagn** [comment]
To be honest, I think that this is just a transient issue, they will probably get bored within a few days or sooner. The best strategy is to just not respond and not give a shit. Classic online bully tactics

**Comment by michaellee8** [comment]
@FoxInFlame Of course it would be in single repo only, I don't wanna cause any discrimination as well. After all as an Hongkonger I am an ethnic Chinese as well.

LOL just wanna know which repo got spammed like this before, wanna see for some fun, and to adjust my algorithm xd.

**Comment by Andre601** [comment]
I personally just filed a report mentioning this repo (instead of every user one by one) and stated the current situation. So if GitHub reads the reports (Which I believe they do) instead of just managing them automatically, they'll look into this.
