### ISSUE TITLE
Take this somewhere else

### ISSUE THREAD

**Issue by ArcticKona** [notepad-plus-plus/notepad-plus-plus#7478]
Instead of spamming the Issues page to the disadvantage of regular users,
we should give this debate to a proper forum like https://www.debate.org/, https://reddit.com/, or news://soc.politics

**Comment by realnacht** [comment]
Couldn’t agree more.

**Comment by Wagnerp** [comment]
I really wish that GitHub has a automatic spam filter/block function. The question is why spam Notepad++?

**Comment by rubyFeedback** [comment]
Propaganda goes both ways dhowland.

> I really wish that GitHub has a automatic spam filter/block function. The question
> is why spam Notepad++?

Because donho decided to turn notepad++ into a political project rather than an editor.

Also I disagree that there should be automatic filters merely for not filling in a template.
Most templates just totally suck or try to auto-sign you into a CoC, which is not acceptable
either.

The best solution is the simplest - focus on notepad++ as an editor rather than an agenda
tool. I was not even aware that notepad++ was no longer an editor but became a religion.

**Comment by Wagnerp** [comment]
@rubyFeedback I think that I may turn to VS Code now as my goto default editor. This must be one of the reasons why you can't even download 7.8.1, the connection just times out.
