### ISSUE TITLE
If you support those affected by china, the repo below may interest you! #FreeHK

### ISSUE THREAD

**Issue by Faunsce** [notepad-plus-plus/notepad-plus-plus#7483]
### Description of the Issue
A lack of information on other chinese misdeeds.

### Steps to Reproduce the Issue
1. Live in the 21'st century
2. Have you companies be cucked by china
3. Not receive the truth (Tienanmen Square, HK, etc.)

### Expected Behavior
People to have this info

### Actual Behavior
Not enough people did

### How to Solve
Check out this repo, contribute to it, start it
https://github.com/caffeine-overload/bandinchina by [Caffiene-Overload](https://github.com/caffeine-overload) *I've also contributed myself
and
https://github.com/taibangle/awesome-china by [MeiWithHongKong](https://github.com/MeiWithHongKong/) under their GH Organization [taibangle](https://github.com/taibangle)

**Comment by masterworgen** [comment]
Stop acting like a hypocrite

**Comment by Faunsce** [comment]
> Stop acting like a hypocrite
And your evidence for that is? @masterworgen

**Comment by klarstrup** [comment]
What does "cucked" mean?

**Comment by masterworgen** [comment]
> > Stop acting like a hypocrite
> 
> And your evidence for that is? @masterworgen

You live in another country.
The fact that you are developing any application or service for this region is 1%.
The fact that you are trying to impose your policy in ANOTHER COUNTRY, and not how they are and how they are, you do not care. This is a different country, a different mentality, a different political life, what is accepted by you is not accepted by them. But no, you are trying to impose your ideology. STOP. Thanks.

**Comment by britmob** [comment]
@masterworgen ok kiddo

**Comment by Loys** [comment]
> What does "cucked" mean?

Synonymous with "cuckolded." One whose company has had sexual relations with Communist Party of China (CPC) (in modern use, often with the employee's approval) has been cucked.

**Comment by tamakisquare** [comment]
@masterworgen 
... ok. Notepad++ is not based in China. Why do the Chinese netizens care what the creator says. Your reasoning doesn't work out, mate.

**Comment by masterworgen** [comment]
> @masterworgen
> ... ok. Notepad++ is not based in China. Why do the Chinese netizens care what the creator says. Your reasoning doesn't work out, mate.

Its only problem user China. I as the Creator of any application or service, I choose with whom I work.

**Comment by Loys** [comment]
> Its only problem user China. I as the Creator of any application or service, I choose with whom I work.

Yeah, because You ("as the Creator") are so smart, right? 😂

**Comment by AIndoria** [comment]
> You live in another country.
> The fact that you are trying to impose your policy in ANOTHER COUNTRY, and not how they are and how they are, you do not care. This is a different country, a different mentality, a different political life, what is accepted by you is not accepted by them. But no, you are trying to impose your ideology. STOP. Thanks.

Yes because if a country wants to genocide its own population it should be freely able to do so right? It was also totally okay in the holocaust, Armenia, and USSR Gulag units as well. How dare the world has something to say about how they manage their internal policies.

**Comment by klarstrup** [comment]
@Loys that is very confusing

**Comment by Faunsce** [comment]
@klarstrup the meaning has evolved over time but the modern word "cucked" comes from "cuckolding" which basically means "a man who enjoys the act of his wife sleeping with other men", when people say cucked is generally describes "the submission of power to another person with little to no attempt to combat it" so the companies are submitting their power to china and not fighting it. the meaning is quite nuanced but the more you hear it the easier it gets. also @Loys explanation wasn't the best.

**Comment by Loys** [comment]
@klarstrup Sorry i tried my best, but found a joke on the side 😄

**Comment by Faunsce** [comment]
@Loys Cucked/Cucking/Cuck are still 100% slang and brand new terms so its all good. also its a very american term that has only recently been spreading more and more to other countries.

**Comment by marekr** [comment]
> > > Stop acting like a hypocrite
> > 
> > 
> > And your evidence for that is? @masterworgen
> 
> You live in another country.
> The fact that you are developing any application or service for this region is 1%.
> The fact that you are trying to impose your policy in ANOTHER COUNTRY, and not how they are and how they are, you do not care. This is a different country, a different mentality, a different political life, what is accepted by you is not accepted by them. But no, you are trying to impose your ideology. STOP. Thanks.

None of us are imposing our policy. We are enacting our own government provided free speech. We say what we want about ourselves and others. Shit, we trash talk our own president, the small hand oompa loompa sexual predator, because we can.

**Comment by rubyFeedback** [comment]
@tamakisquare wrote:
> @masterworgen ... ok. Notepad++ is not based in China. Why do the Chinese netizens  care
> what the creator says. Your reasoning doesn't work out, mate.

I am not chinese. However had, this fake-debate affects people who are merely using notepad++ as an editor rather than a political lame0r tool as it became.

The chinese sinomarxist party is a coward, we all know that. Equally the western countries are fucking hypocrites too. Who is selling weapons all over the world? USA and EU do so happily. Saudi Arabia chops up people in embassies and ... gets more weapons as reward. Scotland can vote whether they want to remain in the UK or not (and voted for remain) yet the people in Span are beaten down when they wish to be free from Franco-Madrid (catalans) - or detained and held as political prisoners, as is the case right now. Then there is the issue of ... uhm ... if the west cares that much, why are they producing in china and selling that to us? That is hypocritical too. Why did they support ISIS mercs on the grounds when they went against the syrian people? Hypocrites all over the place. Go watch oldschool Noam Chomsky. Try to understand why the USA manhunts Snowden or Assange - the latter of who did a "crime" of making public war crimes by the USA (and they refuse to hand over their war criminals to Den Haag - not that Den Haag ever worked, but still slightly better than having no fake-court at all to begin with).

Uighurs are not all peaceful either. You can watch the youtube (!) riots and then tell me that they are all 100% peaceful. Or that there are not armed uighurs either. That does not warrant the failure of the sinomarxist party (as said, it is a coward idiot party and the Hong Kong people are currently showing how to demonstrate how idiotic the sinomarxist party is, through peaceful demonstrations) but it is SO FUCKING ONE-SIDED.

Most importantly, though - it has absolutely nothing at all to do with an editor. None of this has to do with an editor. There is no point to give any name to the release. The creator wants to provoke.

He actually did so before (Hebdo Charly) and he hijacked the computers of the downstream users, as you can see when you read what happened (auto-typing). That is BY DEFINTION a trojan.

You can rant about the lame0r spammers from china but don't defend idiocy coming from YOUR side here. And the author of notepad++ beautifully demonstrated his own hypocrisy too. By the way, Macron, french roleplaying baguette fake-president poser, is using his thugs to beat up the yellow vests. A few died here. Why does the author of notepad++ not focus on improving what is going wrong in France first? Too much work? Too scared of the cops? One sided hypocrites.
