### ISSUE TITLE
Close issues due to spam. 

### ISSUE THREAD

**Issue by ajloveslily14** [notepad-plus-plus/notepad-plus-plus#7484]
Maybe just disable issues for now?

**Comment by Ertego** [comment]
There's actually a GitHub feature to disable everything for 24 hours for exactly this kind of scenario

**Comment by masterworgen** [comment]
I agree, these clowns are already tired

**Comment by archi-tektur** [comment]
Woah, nobody expected Chinese inquisition here :p

**Comment by Msprg** [comment]
Is it just me, or really nobody is actually doing anything with this spam?

**Comment by miyu** [comment]
> I agree, these clowns are already tired

Well, it _is_ 5am in China.

**Comment by MeiWithHongKong** [comment]
I of course can't speak for Don Ho, but I believe the purpose was to spread awareness to the fact that China is currently keeping 1-3 million Uyghurs in Concentration Camps where they are subject to rape, torture and human experiments. For crimes that include having WhatsApp installed on the phone, knowing people living abroad, and whatnot.

It's deeply disturbing and disheartening that Chinese developers would attack him for that, and while it's unfortunate that there are hundreds of issues filled with personal attacks, memes and spam, then closing them now, rather than waiting a couple of days, would be counterproductive. A lot of people, including Chinese, are being redirected to this project from Hacker News, Reddit, Weibo, WeChat, etc. I suspect many news sites and blogs will pick it up as well.

GitHub isn't banned in China, so it's the perfect place to raise awareness, especially now that thousands of Chinese people are being redirected to this project. It's currently midnight in China, so they will likely return in a few hours.

---

If you're from China, please take a moment to educate yourself on what's happening in Xinjiang and Hong Kong.
I realize it's difficult to get access to truthful and uncensored information within China, and that every day the censorship become worse and worse. I have therefore mirrored relevant articles and videos to GitHub here: https://github.com/taibangle/awesome-china.

**Comment by jhpratt** [comment]
I agree with @Ertego. Please restrict this repository for 24 hours (and renew as necessary) to pre-existing contributors. That will limit _everything_.

**Comment by g19980115** [comment]
> I of course can't speak for Don Ho, but I believe the purpose was to spread awareness to the fact that China is currently keeping 1-3 million Uyghurs in Concentration Camps where they are subject to rape, torture and human experiments. For crimes that include having WhatsApp installed on the phone, knowing people living abroad, and whatnot.
> 
> It's deeply disturbing and disheartening that Chinese developers would attack him for that, and while it's unfortunate that there are hundreds of issues filled with personal attacks, memes and spam, then closing them now, rather than waiting a couple of days, would be counterproductive. A lot of people, including Chinese, are being redirected to this project from Hacker News, Reddit, Weibo, WeChat, etc. I suspect many news sites and blogs will pick it up as well.
> 
> GitHub isn't banned in China, so it's the perfect place to raise awareness, especially now that thousands of Chinese people are being redirected to this project. It's currently midnight in China, so they will likely return in a few hours.
> 
> If you're from China, please take a moment to educate yourself on what's happening in Xinjiang and Hong Kong.
> I realize it's difficult to get access to truthful and uncensored information within China, and that every day the censorship become worse and worse. I have therefore mirrored relevant articles and videos to GitHub here: https://github.com/taibangle/awesome-china.

造谣造到github来了，你还有脸说香港？都是你们暴恐分子在破坏香港，还怪别人了？
