### ISSUE TITLE
Close All to the left/right

### ISSUE THREAD

**Issue by SinghRajenM** [notepad-plus-plus/notepad-plus-plus#7501]
### Description of the Issue

Improve "Close all to the left/right" functionality.
This is an enhancement request. Similar request was made in past #2555, but has been closed during tracker cleanup process.

### Steps to Reproduce the Issue

1. Create 4 tabs says (tab 1, tab 2, tab 3, tab 4)
2. Make all the tab dirty (I mean type, something in each tab, but don't save any).
3. Now right click on tab 1 and choose "Close All to the right"
4. Three popup for asking to save file will appear (For tab 4, tab 3 and tab 2)
5. Click "No" for tab 4 and tab 3. And click cancel for tab 2.

### Expected Behavior

After step 5, tab 4 and tab 3 should be closed. And for Remaining tabs, operation should be cancelled.

### Actual Behavior

Nothing happens after step 5.

Same defect reproduction steps are applicable for "Close all to the left".

### Debug Information

Notepad++ v7.8.1   (64-bit)
Build time : Oct 27 2019 - 22:57:19
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1903
OS Build : 18362.449
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
The reason this happens is because the Notepad++ does a 2-step procedure:  First it looks through all the tabs for those it needs to save, prompting the user.  Once that part (the saving, or not) is complete for all of the tabs, the second part runs to close the needed files.  One can see this 2-step thing in progress:  Have two or more modified files and invoke the command.  N++ will prompt you to save a file (mentally note which one) and respond to the prompt (with either Yes or No).  N++ will then prompt you for the next file, but at this point you will still see the first file (i.e., it hasn't been closed).  Only when you are finished answering all the prompts will the tabs that you were prompted about be closed/removed.

IF, however, you answer a prompt with "Cancel", the entire process is aborted and everything is left as it currently is at the moment of cancelling.

This comment was also added to the earlier issue (#2555).
