### ISSUE TITLE
Improve: "Close all but This" functionality

### ISSUE THREAD

**Issue by SinghRajenM** [notepad-plus-plus/notepad-plus-plus#7553]
### Description of the Issue

Improve "Close all BUT This" functionality.
This is an enhancement request. This is followed enhancement request of #7501.

### Steps to Reproduce the Issue

1. Create 4 tabs says (tab 1, tab 2, tab 3, tab 4)
2. Make all the tab dirty (I mean type, something in each tab, but don't save any).
3. Now right click on tab 3 and choose "Close All BUT This"
4. Three popup for asking to save file will appear (For tab 1, tab 2 and tab 4)
5. Click "No" for tab 1 and tab 2. And click cancel for tab 4.

### Expected Behavior

After step 5, tab 1 and tab 2 should be closed. And for Remaining tabs, operation should be cancelled.

### Actual Behavior

Nothing happens after step 5.

_We can mix these above steps with by Cloning/moving one or two tab on other view._

### Debug Information

Notepad++ v7.8.1   (64-bit)
Build time : Oct 27 2019 - 22:57:19
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1903
OS Build : 18362.449
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
The reason this happens is because the Notepad++ does a 2-step procedure:  First it looks through all the tabs for those it needs to save, prompting the user.  Once that part (the saving, or not) is complete for all of the tabs, the second part runs to close the needed files.  One can see this 2-step thing in progress:  Have two or more modified files and invoke the command.  N++ will prompt you to save a file (mentally note which one) and respond to the prompt (with either Yes or No).  N++ will then prompt you for the next file, but at this point you will still see the first file (i.e., it hasn't been closed).  Only when you are finished answering all the prompts will the tabs that you were prompted about be closed/removed.

IF, however, you answer a prompt with "Cancel", the entire process is aborted and everything is left as it currently is at the moment of cancelling.

This comment was also added to the earlier issues #7501 and #2555.

**Comment by vlakoff** [comment]
From 2b0f5dd commit message:

> The files for which user has answered for saving will be close, **even the cancel answer at the end**.

Does this mean the file for which the user clicks "Cancel" will be closed without saving? ("tab 4" file in OP's example)

If so, I don't mean it should be. "Cancel" means "abort" here. Don't close the file and forever lose the changes…

**Comment by vlakoff** [comment]
From 2b0f5dd commit message:

> The files for which user has answered for saving will be close, **even the cancel answer at the end**.

Does this mean the file for which the user clicks "Cancel" will be closed without saving? ("tab 4" file in OP's example)

If so, I don't think it should be. "Cancel" means "abort" here. Don't close the file and forever lose the changes…
