### ISSUE TITLE
Statusbar: replace 'length' and 'lines' with 'words', 'char', 'lines'

### ISSUE THREAD

**Issue by Eldaw** [notepad-plus-plus/notepad-plus-plus#757]
On the statusbar, instead of seeing

```
length: 35  lines: 3
```

it would be more useful and informative to see

```
words: 5  char: 31  lines: 3
```

**Comment by dail8859** [comment]
It would probably be *very* CPU intensive, especially with a file of any decent size since you need to apply a regex to the entire file to count matches.

**Comment by Eldaw** [comment]
Do you mean for word count only? If so, then I still think it would be a good idea to replace 'length' with 'characters'. On the rare occasions where one would like to see the EOL markers included in the count,  the 'View -> Summary' feature could be used.

**Comment by dail8859** [comment]
Yes for the word count. Also, length in bytes does not necessarily equal the number of characters, but probably wouldn't be too bad to keep track of.

**Comment by Eldaw** [comment]
Indeed, as far as I can tell, 'length' appears to be a count of visible characters + EOL characters. For every CRLF newline in a Windows file, the length displayed on the statusbar goes up by 2.

I'd prefer the statusbar to just show the count of visible characters. Thus, replace 'length' with 'characters'.

**Comment by Rikk** [comment]
I vote for keeping 'length'

**Comment by h-h-h-h** [comment]
"length" should definitely be kept!

---
Related issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/737

**Comment by sky5walk** [comment]
I cannot see the full contents of the 2nd and 3rd statusbar field. Does anyone else have this problem?
I reported it as a bug, but it has not been assigned. Really confused how something so simple is not addressed quickly.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
