### ISSUE TITLE
Problem with "\0" in replacement string with regex enabled

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#766]
Hello,

when you have the text `a1a` and replace `\d` with `\0\0` with regular expressions enabled, this leads to `aa` (truncated replacement). When you replace `\d` with `$0$0` or `(\d)` with `\1\1`, it works: `a11a`.

**First:** It's a bug that Notepad++ truncates the replacement string before `\0`.

**Second:** Is Notepad++ right in interpreting `\0` _in the replacement string_ as binary zero, whereas it interprets `\1` as the result of a capturing group? This way you are forced to use `$0`, even if you use `\1`. It's not that a binary zero wouldn't be possible otherwise. There's still `\x00`. When you look at [this page](http://www.regular-expressions.info/refreplacecharacters.html) at the row of "NULL escape", it says PCRE2 doesn't define `\0` as a placeholder for binary zero. Although [this page](http://www.regular-expressions.info/refreplacebackref.html) speaks of `\0` not referencing the whole match, it also speaks of `\1` not being supported, but in practice, the latter it works.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
