### ISSUE TITLE
4k Resolution and/or Windows 10

### ISSUE THREAD

**Issue by ZykezIX** [notepad-plus-plus/notepad-plus-plus#775]
Good Morning, 

It seems there are a few small issues when running Notepad++ on a 4k screen in Windows 10. I don't venture that it's only 4k as when I was running Windows 8.1 I did not experience these issues. It appears that there is some sort of scaling problem happening here. When setting my line edge to 80 columns as I've always done, it certainly doesn't expand to that length at all. (Screenshot Attached)

Additionally, some of the UI windows are finding themselves cut off, still functional of course, but cut off none the less. (Screenshot attached)

I'm not sure what information you'd like, but I'm willing to provide any information you need to help you resolve this issue, so please feel free to ask away!

Thanks so much, 

John A. Reed

Screenshots:

<img width="1321" alt="4k-np" src="https://cloud.githubusercontent.com/assets/9407482/9409698/4b64e13c-47ea-11e5-9df8-bb7beba685d1.PNG">

<img width="761" alt="np 2" src="https://cloud.githubusercontent.com/assets/9407482/9409702/4f468a1c-47ea-11e5-81be-cf33b66ca4e2.PNG">

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
