### ISSUE TITLE
find's search order goes backwards when pressing ENTER.

### ISSUE THREAD

**Issue by GhbSmwc** [notepad-plus-plus/notepad-plus-plus#7808]
![NPPP_backwardsFind](https://user-images.githubusercontent.com/13095760/71663050-b873f800-2d21-11ea-842d-0b9ca8788cfe.gif)
If you start NP++, the default direction to search is towards the beginning of the text when pressing ENTER. However, once you set the “search mode” to “regular expression”, the default direction now corrects itself for the rest of of the program running. If you close the program out after this, it will reset itself and this bug happens again.

I tried unchecking/checking the checkbox at the top right, does not affect this.

**Comment by sasumner** [comment]
>If you start NP++, the default direction to search is towards the beginning of the text when pressing ENTER.

No, not from a fresh install.

In your screencast, I can see you have the `Backward direction` checkbox ticked.  That setting is respected when Enter is pressed.  (To reverse the logic, use Shift+Enter)

Since Regular Expression searches in the backward-direction are currently disabled (see #3640), when you select that `Search Mode` you can watch the `Backward direction` checkbox become unticked.  Thus an Enter press after that will search in the forward direction.

Note however that your scenario after restarting perfectly describes the original bug that #3640 started with (that issue has sort of been hijaaked for a debate of whether or not regular expression searches should or should not be allowed in a backward direction).

Regardless, THIS issue leads to no bug, or at least to no bug that isn't a duplicate. :-)

**Comment by GhbSmwc** [comment]
Oh, should looked closely at the window, my bad. Sorry!
