### ISSUE TITLE
"Mark All" in Find window searches from after the cursor

### ISSUE THREAD

**Issue by ranjan-ranjan** [notepad-plus-plus/notepad-plus-plus#7838]
"Mark All" in Find window searches from after the cursor

Eg. if there is a word which we have to find and the cursor is in the middle of the file, then "Mark All" will find all the instances of the word after the cursor. It will not find from the beginning of the file,

**Comment by sasumner** [comment]
Tick the `Wrap around` checkbox before pressing the `Mark All` button.  

Perhaps it is the "All" part that is misleading about this?

**Comment by ranjan-ranjan** [comment]
Yes, this solved the problem
This isn't consistent with "Find" window

**Comment by sasumner** [comment]
>This isn't consistent with "Find" window

What do you mean by that?

**Comment by ranjan-ranjan** [comment]
We don't have to select tick the `Wrap around` checkbox in `Find window`, but we have to do it in `Mark All window`

**Comment by sasumner** [comment]
@ranjan-ranjan :

Ah, now I understand your meaning...you are really speaking of `Find All in Current Document` and perhaps `Count` (both in the `Find` tab).

`Count` is really *always* "Count All".  It cannot be considered "Count All in Direction" (like others, see below) because it never functions directionally (perhaps it should).

`Find All in Current Document` is sort of a separate usage (all the searches the write the the `Find result` panel search full not partial files).  Perhaps it should consider partial files (dependent upon the `Backward Direction` checkbox)?

`Wrap around` usage *IS* consistent among `Replace` tab (for `Replace All`) and `Mark` tab (for `Mark All`).  Better names for `Replace All` and `Mark All` (when `Wrap around` not ticked) might be "Replace All in Direction" and "Mark All in Direction" but of course, historically they are not, and those texts are a bit long for button captions...

Of course, the language in the UI is completely configurable, so one can make the labeling consistent for themselves, for those that agree that it could just be a labeling issue...

**Comment by sasumner** [comment]
Regarding this part of the above comment:

`Count is really always "Count All". It cannot be considered "Count All in Direction" (like others, see below) because it never functions directionally (perhaps it should).`

see issue #7876 and PR #7917
