### ISSUE TITLE
notepad++ does not keep session after windows 10 reboot (version 782, 64-bit, portable)

### ISSUE THREAD

**Issue by siubb** [notepad-plus-plus/notepad-plus-plus#7839]
### Description of the Issue
1. notepad++ does not keep session after windows 10 reboot (version 782, 64-bit, portable)
before windows reboot, the session is restored after closing and opening notepad++

### Steps to Reproduce the Issue
1. open some files in notepad++, open some new files too, unsaved
2. reboot windows 10, without closing notepad++ first
3. open notepad++ after reboot
4. congratulation, you get an empty notepad++ session!

### Expected Behavior
1. I want my session back after rebooting windows

### Actual Behavior
1. oh my session...
2. after some reboots, the session is restored, after some other reboots notepad++ just show 1 new file, yet to discover a pattern 

### Debug Information
Notepad++ v7.8.2   (64-bit)
Build time : Dec  4 2019 - 01:39:49
Path : C:\Users\wilfred\Downloads\npp.7.8.2.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Home (64-bit) 
OS Version : 1903
OS Build : 18362.535
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
@siubb 
I cannot reproduce it at all (I restart Windows10 gracefully) - can you reproduce it steadily?

**Comment by pnedev** [comment]
@siubb ,

You report that the session is not restored, but were you able to find your files on the disk and open them manually?
Were they corrupted?

@donho ,

Since @siubb had that problem with Notepad++ v7.8.2 the NUL file corruption problem was still there and it might be the culprit in that case as well.
But I'm getting the impression that what's actually happening (even after the NUL fix in v7.9.1) is that the _session.xml_ is not always valid in the case of reboot.

**Comment by pnedev** [comment]
@donho ,

I reproduced it two times from two tries - seems steadily reproducible.
I did my test with Notepad++ version is 7.9.1 with the exact steps described by @siubb (thanks for that) and as I suspected only the _session.xml_ is not correct. All the files exist where they should (the real user files + the unsaved ones in the backup directory) and they are not corrupted at all - no real data lost. I tested with the periodic backup on and the session snapshot, without Backup-on-save.
I think I have an idea what the problem might be - I need to verify that.
I suspect this is also the problem that @nichollsvi reported in the re-opened https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6133 .

**Comment by donho** [comment]
@pnedev 
> Since @siubb had that problem with Notepad++ v7.8.2 the NUL file corruption problem was still there and it might be the culprit in that case as well.

I didn't see any description about NUL file corruption in this issue (opened by @siubb )

> I think I have an idea what the problem might be - I need to verify that.

OK. Please let me know what you discover.

**Comment by pnedev** [comment]
@donho ,

> OK. Please let me know what you discover.

In _NppBigSwitch.cpp_ on `WM_QUERYENDSESSION` and `WM_CLOSE` (same `case:`) :

1) `MainFileManager.backupCurrentBuffer()` is called that on some occasions calls `Notepad_plus::saveCurrentSession()`.
But in some occasions the actual session save is not done here because `NPPM_INTERNAL_SAVECURRENTSESSION` is posted (`::PostMessage`) on the message queue.

2) After that the files list is gotten for the session snapshot (`getCurrentOpenedFiles(currentSession, true)`) and then the files are closed (`bool allClosed = fileCloseAll(false, isSnapshotMode)`)

3) Later, the session is saved with the file list gotten in 2) - `saveSession(currentSession)`

4) In some cases the posted `NPPM_INTERNAL_SAVECURRENTSESSION` from 1) executes after 3) and `NPPM_INTERNAL_SAVECURRENTSESSION` re-gets the opened files list that is now empty because of 2) and the session is saved again but with no opened files.

BTW, `NPPM_INTERNAL_SAVECURRENTSESSION` can be posted also in 2) from calling `fileCloseAll(false, isSnapshotMode)` since it uses `activateBuffer()` that also calls `Notepad_plus::saveCurrentSession()`.

You can either call `NPPM_INTERNAL_SAVECURRENTSESSION` using `::SendMessage` instead of `::PostMessage` to execute it immediately (as in my PR) or add some flag that locks `NPPM_INTERNAL_SAVECURRENTSESSION` when `WM_QUERYENDSESSION` and `WM_CLOSE` are received.

The important thing is to not have `NPPM_INTERNAL_SAVECURRENTSESSION` executed after step 3) because it gets the empty file list and saves empty session.

**Comment by donho** [comment]
@pnedev 
Thank you for the very detail explanation.
So after your fix, can you reproduce this issue again?

**Comment by pnedev** [comment]
@donho ,

After the fix I couldn't reproduce the issue anymore.

**Comment by donho** [comment]
@pnedev 
Cool! Thank you for the fix!

**Comment by siubb** [comment]
Thank you for the fix!!

**Comment by donho** [comment]
Fix by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6000f3bb21a42a4d28d068617e0dc642ef739b26
