### ISSUE TITLE
Feature request: VIM style editing

### ISSUE THREAD

**Issue by duytrung** [notepad-plus-plus/notepad-plus-plus#7861]
### Description of the Issue
Npp is a good editor. Integrate vim-style editing is good for programmers.

I'm new to vim as well and found Vim is very interesting, however, I've used Npp since its released for a long time. Is there anyway to integrate these functionalities.

I found there was a plugin for Npp to behave like Vim but it is no longer in development.

Thanks

**Comment by donho** [comment]
What do you meam by "vim-style editing" exactly ?
Its 2 modes "beep repeatedly" and "break everything" ?

**Comment by sasumner** [comment]
My opinion: Notepad++ tries to to its own style of editing (full GUI) well.  Trying to make it do something different, well, seems counterproductive to its mission.  

@duytrung, why don't you just use one of the many VI editor clones available, instead of requesting that Notepad++ be twisted into something it isn't?

**Comment by chcg** [comment]
Maybe https://github.com/chcg/visimulator is of interest for this case, also the orig repo was deleted and no updates could be expected.
