### ISSUE TITLE
Move to the menu "Collapse and Expand All" ...Folder as Workspace

### ISSUE THREAD

**Issue by andrecool-68** [notepad-plus-plus/notepad-plus-plus#7863]
Can delete these icons and create these two entries in the context menu?
It will be much more convenient than these terrible buttons, which only take up space in the "Folder as Workspace" window

![](https://user-images.githubusercontent.com/3471892/72663069-ebdba580-39f6-11ea-871f-8ce3dd5d4446.png)

**Comment by sasumner** [comment]
Please take questions to the *Community* site.

**Comment by andrecool-68** [comment]
@andrecool-68 sasumner By what right do you close my question?
I already talked there with @donho, and he advised me to create this topic here !!!

https://community.notepad-plus-plus.org/topic/18773/notepad-v7-8-3-free-uyghur-edition

**Comment by sasumner** [comment]
>By what right do you close my (issue)?

Because I'm on the development team and I can. :-)

@donho was telling you not to post in that specific thread on the Community, as that thread is only supposed to be for critical issues with the release.

Probably I would have not closed this issue if you would have provided the Community link in the original issue description.  Without that context, however, it looks like a *question* on how to do something, rather than a feature request.  And *questions* belong on the Community, not in *issues*.

As a feature request, however, I personally would deny it.  @donho made a decision to put those buttons in, and for the majority of users, those buttons are probably desirable.  Just because you don't like the change, well, you can't keep all the people happy all the time, and development has to advance.

I'll reopen, but I'd advise @donho to reject this request, and he can obviously do what he wants.

**Comment by andrecool-68** [comment]
@sasumner If  transfer this to the context menu, it will be convenient for everyone ... and not for me personally)))

**Comment by sasumner** [comment]
>I offer you an idea how to improve the program interface

You did, and @donho will judge.  
I've already provided my opinion on it.

**Comment by andrecool-68** [comment]
@sasumner Hope dies last)))

**Comment by donho** [comment]
I agree with the argument of @sasumner - for me it's the best place for this 3 new features.
However, I could be wrong - if there are more such feature request coming, I'll consider it. In the meantime, let's close it.
