### ISSUE TITLE
Feature request: single click to open a file in "Folder as workspace"

### ISSUE THREAD

**Issue by niente0** [notepad-plus-plus/notepad-plus-plus#7868]
Hi,
is there a way to make Notepad++ open files in “Folder as Workspace” by using a single click instead of a double click? Would it be possible to implement this feature?
Thanks

**Comment by sasumner** [comment]
IMO this doesn't make sense for most users.  Sorry.

**Comment by anikinsl** [comment]
However this is the default behavior, for example, in Explorer and Atom.io.

**Comment by chen3feng** [comment]
> However this is the default behavior, for example, in Explorer and Atom.io.

and in Visual Studio Code

**Comment by alankilborn** [comment]
The FAW tree-list presentation view works like other such UI presentations in N++; double-click to take the action.  IMO, such presentations should be consistent so user isn't confused ("hmm, do I single click here or double click...try single...damn, nope, have to double click").

For me very personally, single-click doesn't make sense because of "accidental mouse click syndrome".  Double-click is more of a "confirmed, I really want to do this" action (when the action is larger than e.g. the trivial move-caret-to-different-pos-in-editor).

**Comment by shodanx2** [comment]
I would vote in favour of this option
I've just started using "Folder As Workspace" and I'd like the option of single click open
As well as the option to close all (and only) currently opened files that have been opened this way

The option of single-click open should be a per-folder option

Example 

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10621885/a517bf75-db7a-475b-83de-732db3fbdd78)

And the state of that textbox should be what it was the last time it was used.
