### ISSUE TITLE
Tab change using mouse-wheel roll up is broken in Windows 10

### ISSUE THREAD

**Issue by poshcodebear** [notepad-plus-plus/notepad-plus-plus#788]
After upgrading to Windows 10 Pro, mouse-roll-up (holding the right mouse button and rolling the mouse wheel) to change tabs doesn't work.  It brings up the list and will move the selection only one spot either forward or back, but will not go further than that; also, after using it, the selection screen gets stuck on the screen and can't be dismissed outside of force closing Notepad++, and I'm unable to click on anything other than the tab selector until I force close and reopen.

I upgraded to the latest version of Notepad++ (6.8.2) and disabled all plugins, but the issue persists.

**Comment by poshcodebear** [comment]
After disabling and re-enabling "Enable MRU behaviour" in settings, I can no longer replicate this issue.  I think there's a bug here, but I'm not sure how it can be replicated...

**Comment by poshcodebear** [comment]
After using Notepad++ for a while, the problem returns.  I don't know how to replicate it directly still.

**Comment by jeanrenaud** [comment]
This issue is **leading to a crash** on my system. I know how to replicate it :

1. Press down right mouse button
2. While holding right mouse button, roll the mouse wheel one position.  The roll-up menu will appear. **Do not release the right button now**.
3. Continue to roll the wheel **while leaving the right mouse button pressed**.  Each time the wheel makes one displacement, another "roll" popup window will appear on top of the old one. But if you release the right button (after two or more wheel moves), only the last popup will disappear, so the other ones will stay there and lock the interface.

**To correct the issue** : if your wheel moved, say, 8 times in a row, you have to click 7 times on the list (each list will disappear with one click, but **all of them** must be closed. Then, the inferface will be available.

**To crash the application** : Roll the wheel a lot of times while leaving right mouse button pressed. On my system, after 28 wheel moves, the application crashes (too much handles ?).

I found this bug while cleaning my mouse :)

**Comment by aceRage** [comment]
Still getting this issue almost a year later. Tried versions 6.9 - 7.1 so far, none with any luck.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
