### ISSUE TITLE
Wrong number of lines with selected text shown in statusbar

### ISSUE THREAD

**Issue by Eldaw** [notepad-plus-plus/notepad-plus-plus#791]
Presumably the 'Sel : 17 | 2' part of the statusbar is supposed to indicate how many characters (including newlines) are selected, on how many lines.

If so, then selecting some text on 1 line, currently shows you something like this
Sel : 15 | 0

Surely it should be
Sel : 15 | 1

Also, I notice that if you use Ctrl to select multiple sections of text on different lines, it just changes to
Sel : N/A

**Comment by h-h-h-h** [comment]
:+1:
Related issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/737

**Comment by dg9ngf** [comment]
When I select one entire line excluding the line break, I get "… | **0**".

When I select the line break as well, I get "… | **2**".

Where did **1** go? I'd suggest considering the characters on the first line as one line. Also I'd suggest ignoring a single line break at the very end of the selection. When I select entire lines all from the first column (where I keep my cursor most of the time when dealing with entire lines), I'd like to know the number of lines I've selected, not the number of lines that selection and cursor somehow touch.

**Comment by h-h-h-h** [comment]
> I'd suggest *ignoring a single line break at the* ***very end*** *of the selection*. When I select entire lines all from the first column (where I keep my cursor most of the time when dealing with entire lines), I'd like to know the number of lines I've selected, not the number of lines that selection and cursor somehow touch.

This sounds reasonable.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by ygoe** [comment]
@MetaChuh Still not fixed, still a problem, please reopen.
