### ISSUE TITLE
Using 1st-5th Style highlighting color confusion

### ISSUE THREAD

**Issue by gps7** [notepad-plus-plus/notepad-plus-plus#7916]
### Description of the Issue
I am very often using highlighting of text for log file analysis which really helps. But I always face a problem which color is what text part is highlighted. As result I am trying to remember which Style is hiding which color. This is makes hard to understand to highlighting.

### Steps to Reproduce the Issue
1. Open any text file
2. Select any text
3. Right click with mouse and choose Style Token menu
3. Try to mark selected text as green (valid) or red (not valid) or simply highlight with yellow (well that I remember is number in the middle: 3rd)

### Expected Behavior
Clear highlighting color assignment to the each Style number by adding at lease color text in brackets. Also I would like to have wider range of highlight colors. I know that I could mix two color styles which gives other color, but again - cannot predict when you don't know primary highlighting color.

Ideally this is a new new feature: 
- As NotePad++ user I want to have customization of Style Tokens where I can apply colors, fonts, font styles so the choosing custom Style Token I can apply custom instead inbuilt ones.
- As NotePad++ user I want to have customization of Style Tokens names for custom custom Style Tokens so that I can easily select style based on my token name.

### Actual Behavior
Unclear highlight colors. Not possible to add new colors

### Debug Information
Not required. All this is visualization.

**Comment by xylographe** [comment]
**Settings > Style Configurator...** to change colour/font style?
Modify `%APPDATA%\Notepad++\nativeLang.xml` to change text of menu items.

**Comment by gps7** [comment]
Not really. I want to change the Style token's font/color once highlighted for all matches. I am just opening a text/log file with custom language already.
I did not found such a file in my user folder.

**Comment by sasumner** [comment]
>Clear highlighting color assignment to the each Style number by adding at lease color text in brackets.

The reason this does not exist already, or even make sense, is that the user can change the colors.  Thus, you wouldn't want the menu saying "Green" when the user has changed the color to blue.

Of course, as @xylographe pointed out, you can change the text, the colors, or both.  For myself, I kept the default colors and just changed the menu text to reflect the actual colors:

![image](https://user-images.githubusercontent.com/30118311/73747224-ff8c4900-4724-11ea-9e78-3b7c74f737f0.png)

Now in your followup (starting "Not really") you seem to change the scope of what you want.  Here it seems as if you want to change the styling/coloring of something that has previously been styled/colored.  This is currently not possible and really isn't on the Notepad++ development roadmap.  It probably could be achieved with a scripting plugin.  If you are interested in that, please say so.  Barring that, I'm closing this issue.

>Debug Info:  Not required. All this is visualization.

@xylographe @donho  See what we get because users (that want to fill in "Debug Info") misinterpret what it means?  We really need that issue template change, clarifying "Debug Info"

**Comment by gps7** [comment]
Hi Sorry, I was not able to find these styles as I was looking for exact name in the suggestion Style Configuration. So that's great. Just how can I change then a name of context menu as shown in the screenshot?

**Comment by sasumner** [comment]
>how can I change then a name of context menu as shown in the screenshot?

I change mine in `english_customizable.xml` then I select "English (Customizable)" in Preferences > General > Localization.

**Comment by gps7** [comment]
Great. That worked. The file location was in "C:\Program Files (x86)\Notepad++\localization". Thanks!
