### ISSUE TITLE
Feature Request: Close tab with Ctrl+F4

### ISSUE THREAD

**Issue by IvenBach** [notepad-plus-plus/notepad-plus-plus#7923]
### Description of the Feature
Use `Ctrl+F4` to close a tab in N++. Just like behavior in web browsers.

### Expected Feature Behavior
1 - Have 2 tabs open
2 - Press `Ctrl+F4` to close the active tab, leave the remaining tab open.
3 - Smile

### Actual Behavior
`Ctrl+F4` doesn't perform any action.

**Comment by sasumner** [comment]
Assign it in `Settings` menu > `Shortcut Mapper`.

**Comment by PeterinScotland** [comment]
This still does not work!  I automatically use CTRL-F4 - I've been using it for 25 years or so, and find it annoying to have to use CTRL-W instead.

**Comment by PeterinScotland** [comment]
BTW I do not understand sasumner's reply.  Is he/she saying the user should have to assign this.  I wouldn't know how, and don't see why I should have to.  It works in other programs as standard!

**Comment by funkymaster** [comment]
This is a setting, which can be individually set to users demands.
The default setting is Ctrl+W and Ctrl+Shift+W to close one or all tabs.
You can change this to what ever you want under Settings / Shortcut Mapper...

**Comment by sasumner** [comment]
Once a keycombo is chosen and assigned in Notepad++, it rarely if ever changes.  Why?  Well, because there are users that will have gotten used to that keycombination, and would object if it were changed.  Another great point, that I tried to make earlier, is:  If _you_ don't like it, the software gives you the opportunity to change it to your liking.
