### ISSUE TITLE
Make Find Next (F3) resume last search upon launch [enhancement]

### ISSUE THREAD

**Issue by scottcopus** [notepad-plus-plus/notepad-plus-plus#7939]
### Description of the Issue
Every now and then I'll open files from several places and want to search for the same text in each of them.  But sometimes I close and reopen Notepad++ repeatedly over the course of an hour/day/etc.  I think it would be a minor improvement if the Find Next (F3) command would either resume the last search (after a close & relaunch) or bring up the Find dialog (or be a configurable choice).  I know there's better ways to do this and I'm open to suggestions, but that's just how I do it sometimes.  :-)

### Steps to Reproduce the Issue
1. Open Notepad++
2. Open a file (or use 'Edit with' context menu)
2. Press F3 (Find Next)

### Expected Behavior
Resume the last Find operation, or bring up the Find dialog.

### Actual Behavior
Find Next (F3) does nothing (at least on a new launch w/o doing an initial search first).

### Debug Information
Notepad++ v7.8.4   (64-bit)
Build time : Jan 29 2020 - 01:31:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.592
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
If you open the Find window and navigate to the Find-what box and press the down arrow key, or click the down arrow part of the control, you should be able to see and recall your previously used search term.  It is easy as selecting it (so that it again fills the Find-what box) and then pressing the Find-Next button.

**Comment by scottcopus** [comment]
Sure.  It was just a suggestion.  I was just aiming to increase efficiency by reducing the number of keystrokes down to 1-2 instead of 3-4.

**Comment by sasumner** [comment]
>I was just aiming to increase efficiency

I don't think that's going to help much, because most people just never shut Notepad++ down; well when they shut the whole PC down, but even if they do that, say, once a day, it would only be a couple of keystrokes one time per day (negligible) to restore the last search term.

But, yea, in general, keep thinking of ways to make things better. :-)
