### ISSUE TITLE
[Feature request] Add feature to Search -> Bookmark -> Submenu: Select bookmarked lines

### ISSUE THREAD

**Issue by bege10** [notepad-plus-plus/notepad-plus-plus#7943]
### Description of the Issue
[Feature request] Add feature to Search -> Bookmarks -> Submenu: Highlight bookmarked lines

### Steps to Reproduce the Issue
I want to comment out all lines that contain the search result.
I can bookmark these lines with the last tab of search dialog, but to comment them out I need to highlight the lines.

This feature would also help with other actions on the highlighted lines

**Comment by sasumner** [comment]
How does "highlighting" (not sure exactly what that means, so maybe we start there...) help with "commenting them out"?

What "other actions" might be performed on these lines?

**Comment by bege10** [comment]
I changed to English UI: "Select" is the correct word. So my request is to add "Select bookmarked lines"
1. Search the term and bookmark all lines that contain the term
2. Select the bookmarked lines
3. rightclick and comment them out

Or you can add this feature to the search dialog tab "Mark".

You can do all line related actions with this feature.

**Comment by sasumner** [comment]
Well, a lot of "line related actions" don't currently work on multiple selections.  They typically want a single selection.

How about just using a regular expression replacement to insert comment markers in front of the lines that contain your search term.

So like for this text:

```
Jack and Jill
Went up the hill
To fetch a pail of water
Jack fell down
And broke his crown,
And Jill came tumbling after.
```

and you replaced `(?-s)^(?=.*?Jack).*` with `// $0` you would get this:

```
// Jack and Jill
Went up the hill
To fetch a pail of water
// Jack fell down
And broke his crown,
And Jill came tumbling after.
```

So basically this is saying "put C++ comments on any lines containing `Jack`"

This is how people would typically do it.  It does take a bit of regular expression knowledge, though. :-)

**Comment by bege10** [comment]
Thank you for your suggestion.
It is a pity that most line related actions don't work on multiple selection.

I have very basic knowledge of RegEx so that I don't understand your expression and my internet search for (?-s) didn't give a result. I can save your code and use that but I actually just wanted to edit some CSS files and not begin "programming" the editor.  :sweat:

**Comment by sasumner** [comment]
>It is a pity that most line related actions don't work on multiple selection.

I do agree, but Notepad++ devs work for free in their spare time, so we don't get to everything. :-(

> "programming" the editor

regex isn't really programming; some might argue that point :-)

>very basic knowledge of RegEx so that I don't understand your expression

How the find works:

`(?-s)` : don't let future `.` match line-ending chars
`^` : match at start-of-line-only
`(?=.*?Jack)` : "Jack" must appear in the line for a match to happen
`.` : match any one character (except line ending due to earlier thing)
`*` : match zero or more of preceding

Thus the `.*` part matches the entire line (so that it can be replaced).  In fact this is the only part of the match that "consumes" characters ("selecting" them into the match).  All the stuff that came before is "asserting" things that must happen for an overall match to happen (key part is `Jack` being in the line).

The replace expression consists of:

`//` : C++ style comment to end-of-line
a space
`$0` : what was matched in the "find" part

So, overall it can be said in English:  If a line contains `Jack` replace it with `//` followed by a space, followed by the original line.

Good info here for deeper learning :  https://www.regular-expressions.info/
