### ISSUE TITLE
Previous installation not detected?

### ISSUE THREAD

**Issue by TBugReporter** [notepad-plus-plus/notepad-plus-plus#7946]
### Description of the Issue
Quoting from [this Community post of mine](https://community.notepad-plus-plus.org/topic/18876/bump-previous-installation-not-detected) (which I, in turn, quoted from [this older post](https://community.notepad-plus-plus.org/topic/15578/previous-installation-not-detected)):

> > Every time I download a new version and run its installer, previous install location is not detected and it tries to install to default location (C:\Program Files\Notepad++). I think it used to detect the previous installation before and tried to upgrade instead.

### Steps to Reproduce the Issue
From [this response](https://community.notepad-plus-plus.org/post/50546) in that thread:

> * install [v7.7.1-64b](https://notepad-plus-plus.org/downloads/v7.7.1/) from installer, to `c:\Program Files\DonHo\Notepad++`
> * when it runs, it immediately asks to update
> * I say yes, and it downloads [7.8.4-64b installer](https://notepad-plus-plus.org/downloads/v7.8.4/)

### Expected Behavior
* It prompts me to install in `c:\Program Files\DonHo\Notepad++` (My previously chosen location)

### Actual Behavior
> * It prompts me to install in `c:\Program Files\Notepad++` (default location)

**Comment by Vatharian** [comment]
This is extremely inconsistent behaviour. I encountered this bug on some of my systems, while sometime it just works. I suspect it may be connected how the N++ installer is invoked for the first time on the machine, whether it's ran as admin from the get go, or it elevates itself, because that's only difference between systems I can recall that may be relevant.

**Comment by pryrt** [comment]
In a [recent post](https://community.notepad-plus-plus.org/post/53587) in a similar thread in the Forum, user Jerry-B suggested
> A simple reg read at the beginning of the installation process would do the job. E.g.:
> HKLM\Software\Notepad++
> HKLM\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\App Path\notepad++.exe

This sounds like a reasonable check for the installer to make

**Comment by ErtjeTheFreeze** [comment]
Indeed this is very annoying. At every update, Notepad++ keeps prompting it's default install path, not the path in which it has been installed on the machine itself.

**Comment by Suesskirsche** [comment]
Yes, that is annoying me too since long (I do use [a different drive and] folder for my tool installations for about 25 years) so much that I even registered to check if an improvement was already requested. Yes, it is - since very long...

Would be nice if the installer also would "remember" the parameter setting "save in path" (or something similar, don't remember now while typing at my smartie) by reading it from the registry. 

Except for that: thank you! for your constant effort to improve N++ 
Mike

Am 30. November 2020 15:05:57 MEZ schrieb ErtjeTheFreeze <notifications@github.com>:

**Comment by JeremyZoss** [comment]
This issue has also affected me for a while, although for me the annoyance is slightly different: my company uses a software management tool to automatically deploy updates of applications.  The process is fully automated, so I assume they're using NPP's "silent install" mode.  Since it's not interactive, there is no opportunity to manually correct the install location.  In that case, I'm left with duplicate installs - my original install folder plus the automated install to the default folder.  I frequently have to clean things up manually - removing both the older install (in my preferred directory) and the automated install (default directory), and re-installing the latest version in my preferred directory.

If the installer used the existing install path, it would fix this (minor) annoyance.

**Comment by xomx** [comment]
This issue is relevant only for 64-bit N++ installations, 32-bit ones are ok.

Source of this problem - probably an unexpected x86/x64 Registry redirection.

When a 32-bit N++ installation finishes successfully, it creates RegKey with the current real installation path in the HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Notepad++. When the N++ updater is then launched, it picks up this path and it offers that as the default installation place.

When a 64-bit N++ installation finishes successfully, the relevant RegKey is written to the HKEY_LOCAL_MACHINE\SOFTWARE\Notepad++, but the N++ updater then cannot find it. If we cancel the update (with the now 'incorrect' N++ default path offered to us), create manually the HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Notepad++ RegKey with our custom path and restart the update process, everything is ok again.

The NSIS-executable generated for the 64-bit N++ installations is still a 32-bit app (most NSIS installation packages in the wild is still created in this way, this is ok). So I think, that when the N++ update package is downloaded and started, the InstallDirRegKey NSIS-attribute, which handles the looking for the previous installation location, looks at the wrong WOW6432Node place.
