### ISSUE TITLE
'&' not visible in C++ files

### ISSUE THREAD

**Issue by timofey-retailnext** [notepad-plus-plus/notepad-plus-plus#797]
versions tested: 5.9.8,6.7.5,6.7.8.2,6.7.9.2,6.8,6.8.1,6.8.2

given a string "	while (x < ((x_end-d_num) & ~0x7) /*(x_end-x-1)>=d_num*/) {"

when I store it as a test file I see '&' before ~0x7, 
when I store it as *.cpp/*.h file '&' disappears.

Similar, '&&' disappears in string "for (int x8=8; x8>0 && x < x_end; --x8) {}"
![h](https://cloud.githubusercontent.com/assets/10067721/9450603/7925018a-4a5e-11e5-8f87-7c2c7d069469.png)
![txt](https://cloud.githubusercontent.com/assets/10067721/9450602/792456d6-4a5e-11e5-9689-2b246183cbdc.png)

**Comment by h-h-h-h** [comment]
See issues https://github.com/notepad-plus-plus/notepad-plus-plus/issues/547, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/729 and similar ones.

**Comment by timofey-retailnext** [comment]
Thanks for clarification. I'm using 6.8.2 and seems that "Source Code Pro" is still default font for C/C++ stylers.
I explicitly changed "C operators" and "C++ operators" font to "Courier New" and this works for me.

P.S. does NPP update no a newer version update prog.lang.stylers or older one is reused ?
In other words do I need to perform this manual bypass after every NPP upgrade (until font issue will be finally fixed) ?

**Comment by h-h-h-h** [comment]
If it's not working properly, it should be remarked in the appropriate issue.

**Comment by donho** [comment]
@timofey-retailnext
stylers.xml will never be erased by installer since this file can be modified by users via Styler Configurator.
 
In v6.8 & v6.8.1, Notepad++ Installer put Source Code Pro font in Notepad++ installed directory, load it then use it, without interfering with system.

In v6.8.2, Installer removes Source Code Pro font if user upgrad from 6.8/6.8.1, and Notepad++ doesn't load Source Code Pro font, but use only the font in stylers.xml. If Source Code Pro font is in stylers.xml and user has installed it before, then it will be used.

@h-h-h-h You can use Styler Configurator to set Default font as system font or remove stylers.xml so Notepad++ will regenerate it on startup. Otherwise there's no obvious way to solve it.
