### ISSUE TITLE
Opening file : type custom *.xxx do not filter list

### ISSUE THREAD

**Issue by coucout** [notepad-plus-plus/notepad-plus-plus#7978]
### Description of the Issue
When opening a file, if you type custom extension via "*.xxx", file list is not filtered according to this

### Steps to Reproduce the Issue
1. file/open
2. type "*.au3" (for an example)
3. press tab : the list is not filtered according to this
4. press "Open" button. The dialog is closed but nothing happens

### Expected Behavior
The list have to be filtered according to custom extension

### Actual Behavior
the list is not filtered

**Comment by sasumner** [comment]
I'm not sure where you are getting the feeling that the Tab key should do what you are suggesting here.  Is this a standard in other programs?  If so, which?

*Resolution:*
In step 3, press Enter instead of Tab.  This presumes that "Use new style dialog..." is selected in the Preferences.

If "Use new style dialog..." is not selected in the Preferences, I don't think there is an easy way to do custom extension filtering (you'd have to use what is already provided in the Filters drop-down).

Strong suggestion:  Enable "Use new style dialog..." if not already using it.
