### ISSUE TITLE
"Find in these found results" with regular expression searches content instead of found results

### ISSUE THREAD

**Issue by gullbyrd** [notepad-plus-plus/notepad-plus-plus#8056]
### Description of the Issue
Search in results window searches content instead.

### Steps to Reproduce the Issue
Search in a file for a term.
In the results window, right click and choose "Find in these found results".
Enter a regular expression and click the regular expression radio button. Search.
The results displayed are from the content window, not the results window.

### Expected Behavior
I expected to get search results from the results window only.

### Actual Behavior
I got results from the content window.

**Comment by sasumner** [comment]
Works fine for me in 7.8.5.  Unknown which version you used because you didn't provide that information.

You also didn't provide enough information to perfectly reproduce your problem.  

Perhaps a likely scenario:  You aren't setting this setting correctly?:

![image](https://user-images.githubusercontent.com/30118311/77169882-9e2ff780-6a90-11ea-8789-601293aa2f0f.png)

**Comment by gullbyrd** [comment]
I was careful to check the "search only in found lines" box (it's set by
default anyway). In any event, I upgraded from 7.8.4 to 7.8.5 and now it
works. Thanks.
