### ISSUE TITLE
[Feature request] Go / Golang language support

### ISSUE THREAD

**Issue by Skuldo** [notepad-plus-plus/notepad-plus-plus#8090]
Request for Go language (https://golang.org/) syntax highlighting to be included in the official distribution.

There are some user defined language files that could be brought in e.g. https://github.com/tlowry/npp-golang/blob/master/golang.xml

Previous issues have requested this but have been steered down the UDL route (#3037 #4778 #2574).

It's been consistently picking up in popularity over the last few years, so I think it would be beneficial to include it (https://hackernoon.com/googles-go-programming-language-is-going-places-by-how-far-bwbb3dnl). 

It's more popular/relevant than a few of the languages that are supported at the moment.

**Comment by chcg** [comment]
@Skuldo UDLs should be added here: https://github.com/notepad-plus-plus/userDefinedLanguages.
Go seems to be not supported yet by https://www.scintilla.org/ which is the base for integrated programming language support of N++.

**Comment by ffes** [comment]
And don't hold your breath on it being added by Scintilla. It was requested there a long time ago and closed as "Won't implement". https://sourceforge.net/p/scintilla/feature-requests/search/?q=golang

**Comment by sasumner** [comment]
> That was a decade ago

On the upside, though, it is still "open" :

![image](https://user-images.githubusercontent.com/30118311/102093238-ea755180-3dee-11eb-82a1-d3f54f88da72.png)

**Comment by CreativeQuilt** [comment]
But Atom, Sublime Text, and VS Code, Notepad++  big three have support for GO.

**Comment by ArkadiuszMichalski** [comment]
If someone writes a parser for Scintilla, there is a good chance that it will be added in Notepad ++ as well.

**Comment by ffes** [comment]
Yep, as so often: Somebody (from the Go community, I guess) has to do it

That means:
* Add the parser to Scintilla
* Wait for @donho to upgrade to that version of Scintilla
* Then do all the plumbing required to use that parser in N++

**Comment by alongL** [comment]
Notepad3 has golang support.  It also use scintilla. 
https://github.com/rizonesoft/Notepad3/pull/157
The method may be copyed to this project.

**Comment by pryrt** [comment]
> UDLs should be added here: https://github.com/notepad-plus-plus/userDefinedLanguages

BTW: the UDL Collection has had a [go UDL](https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/UDLs/go_byAnthonyStarks.xml) since its inception (though I will admit that until Feb 2022, there was a bug in the UDL definition which made it not work).  So people looking for Golang can at least get it as a UDL from the UDL Collection

**Comment by pryrt** [comment]
A user in the Community [asked again](https://community.notepad-plus-plus.org/topic/25645/cuando-estara-disponible-el-formateo-para-lenguaje-golang), even though they had been [answered two years ago](https://community.notepad-plus-plus.org/topic/23546/i-need-support-to-golang-language/).  

But despite the records finding that Scintilla had claimed it was a "Won't implement" -- the recent SciTE editors _do_ syntax-highlight `*.go` files (internally, it's mapped to the "cpp" lexer, with a different set of keywords).  Since Notepad++ already mapes, C, C++, Java, JavaScript/ActionScript, Swift, and others to the "cpp" lexer, it shouldn't be _that_ much overhead to map Golang to the same lexer and then copy over the list of keywords from [SciTE's cpp.properties](https://fossies.org/linux/gscite/cpp.properties).

@chcg / @ArkadiuszMichalski , have I misunderstood the requirements/difficulty to map a new language to the existing "cpp" lexer, or do you agree that this is something that could (and should) be pursued?

**Comment by ArkadiuszMichalski** [comment]
@pryrt I don't know "go" and I don't know if the "cpp" lexer will be sufficient, but if so, it's better to have it supported in this form than to wait forever for a separate lexer for "go" in Lexilla project. From what I remember, recently some languages were also mapped to an existing lexer of another language, so you can see how exactly it was done (unfortunately I don't remember which one exactly).

**Comment by pryrt** [comment]
I also don't know Go.  I just assumed if the SciTE authors thought that mapping Go to the cpp lexer was sufficient, there was a good chance that it would work (especially considering how many other languages also use the cpp lexer)

> so you can see how exactly it was done

Hmm... I hadn't been planning on being the one to implement, because I've never set up an environment for building N++.  However, I did just confirm that I can build it using the mingw-based gcc that comes with Strawberry Perl, so I actually _do_ have the build environment.  So maybe I will give it a try, as I have time.
