### ISSUE TITLE
Notepad++ Uses wrong mouse pointer for text select

### ISSUE THREAD

**Issue by chloemccarty** [notepad-plus-plus/notepad-plus-plus#8112]
### Description of the Issue
I cannot understand why, but instead of using the normal text select pointer when I am editing text in npp, it just keeps with whatever pointer was used last.
This is incredibly frustrating, because usually when I enter the window, it turns my mouse into the "resize" pointer, making it nearly impossible to select text with any sort of precision.
Here's a video to demonstrate what I mean. https://webpagefx.mangoapps.com/sf/MzIzOTYxXzczMTI2ODI

### Steps to Reproduce the Issue
I don't know how to reproduce the issue

### Expected Behavior
I expect the pointer to turn into a text selector pointer like https://bit.ly/3cf0Cez

### Actual Behavior
It doesn't change at all when you mouse over the text editing area.
Also, when I tried to copy the debug info to clipboard, the mouse kept going between a "normal select" and a "quick select", although the video doesn't show it very well https://webpagefx.mangoapps.com/sf/MzIzOTY3XzczMTI2OTk

### Debug Information
Notepad++ v7.8.5   (32-bit)
Build time : Mar  4 2020 - 11:04:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.720
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

Please help! If I can't get this fixed I am going to have to switch to a different text editor. I really like Notepad++ but I can't justify using it for all the frustration and waste of time this is causing me.

**Comment by dail8859** [comment]
Unfortunately without a way to reproduce it, then it is nearly impossible to try to fix it. There have been other users experience this (including myself) but as far as I know there is no way to reproduce it. If you do find a way then please include those details and reopen this issue.

**Comment by fizzymagic** [comment]
Just because an issue is not reproducible doesn't mean it is not a problem.  And this one is a killer.  The problem is so bad that I am using v 7.8.6 because anything newer has this problem.  It's clearly an interaction with the Windows OS.

Please don't put the burden on the user to debug system interaction bugs.

**Comment by dail8859** [comment]
Yes, it is a problem but from the developer's side of it, there is nothing to try to even begin to identify a fix to the problem if it can't be reproduced.

**Comment by fizzymagic** [comment]
> Yes, it is a problem but from the developer's side of it, there is nothing to try to even begin to identify a fix to the problem if it can't be reproduced.

Maybe some additional information will be helpful.  I understand that debugging hard-to-reproduce bugs is difficult, and I appreciate that without a stable way to reproduce the bug, debugging is far more difficult.  But in real life, there are a lot of bugs like this one that need some extra time to find. Giving up is, for me at least, never an option.

Here is what I observe:

- The issue can be usually be fixed by re-starting Notepad++.  It is always fixed by re-booting the system.
- Once NP++ starts displaying the wrong mouse pointer, the cursor position is no longer visible in any NP++ window.
- Once the wrong mouse pointer appears, it remains that way. The pointer itself can change, but it is never set to the correct shape in the NP++ window. This fact implies that there is some state being set in which the application no longer responds to a system notification that the cursor is in its window. That, in turn, could be caused by a variety of things, depending on what gui framework is used.
- Text selection still works, except you can't see where the cursor is.
- The mouse pointer displayed in the window tends to be either the default up-left mouse pointer or the vertical window resize pointer (up-and down arrows)
- Once the new mouse pointer appears, the cursor position in NP++ is not longer visible.

I hope this information is useful in tracking down the issue.  On my machines (three of them) it almost always appears within 48 hours of starting NP++.  Indeed, it is so frequent that I believe that leaving the application open for 48 hours is probably a reproducible way to see it.

**Comment by mere-human** [comment]
Is it still reproducible in latest version of Notepad++?

**Comment by fizzymagic** [comment]
Saw it last week on 7.9.2

**Comment by Peyda** [comment]
I think I found a way to reproduce the issue and also a quick fix without restarting Notepad++.

I get this strange cursor behavior when I:
1. Press Ctrl + Shift + R while Notepad++ is active
2. Move the cursor to another window
3. Move the cursor back to Notepad++

I saw in the video of your first post that you were working on a website. It is fairly common to use Ctrl + Shift + R to reaload a web page and so it can happen that you try to reload while still in Notepad++. I ran into the same problem and randomly figured it out somehow.

Now to fix this problem, simply press Ctrl + Shift + R again while Notepad++ is active and it magically returns to normal.

Debug Information:
Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.985
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll

**Comment by fizzymagic** [comment]
Great find!  While I never personally use ctrl-shift-r, the described action does indeed trigger the problem and, when repeated, resolve it.  I am hoping that the use of the key combination will work in every circumstance in which it occurs!

**Comment by sasumner** [comment]
The Ctrl+Shift+R scenario does not help this reproduce for me on:

Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\\..........\npp.7.9.5.portable.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1440
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll
