### ISSUE TITLE
Move to Recycle Bin [File Menu & Tab Context Menu Item]: also make a "Delete" Option Available, Alternatives

### ISSUE THREAD

**Issue by Doryforos** [notepad-plus-plus/notepad-plus-plus#812]
I am badly missing the `Delete [from Disk]` File Menu & Tab Context Menu Item that subject item replaced in recent versions of Npp.

Would it be possible to make **_both**_ options available in the File Menu & Tab Context Menu (i.e. as two different items)?

Alternatively:
a. offer an option (to make available **_either or both**_ items in the File Menu & Tab Context Menu):
   i. in Npp's settings or
  ii. during installation (just like the one for Npp's icon)
b. somebody make a plugin (as mentioned @ http://docs.notepad-plus-plus.org/index.php/Context_Menu#The_Tab_Bar_Context_Menu) to make either or both options available (in both File Menu & Tab Context Menu)
c. [as a last resort/quick and dirty (maybe temporary, certainly non-ideal) amendment] make subject item delete the file (i.e. bypass the Recycle Bin) by SHIFT+clicking (i.e. using the standard MS-Win keyboard shortcut for this action)

**Comment by h-h-h-h** [comment]
:+1:
I think, it's a nice feature to be able to delete a file from within Notepad++. Of course, an option for this would have to be in the settings rather than a question in the installation process or something else. However, I don't see why it should be an option when a notable message box for confirmation is shown.

**Comment by Doryforos** [comment]
Being an Edit Menu Item was my mistake; its place is, of course, under the File Menu, since a **file** is deleted, not [part of] the **content** of a file -- I have edited my post to correct this.

**Comment by h-h-h-h** [comment]
I edited my post, too. ***So, let us delete these last two cluttering posts.***

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
