### ISSUE TITLE
Add "Find all in selection" capability

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8133]
In current Notepad++ (7.8.5) there is no ability to conduct a search operation in a selected region of text.  

The ability should exist to do so for a single (i.e., "main") selection.  

The results of the search should go to the `Find result` window, just like, for example, current *Find All in Current Document* output does.

**Comment by sasumner** [comment]
So in implementing this the hardest part is going to be dealing with similar effects to the problem reported here:  #7927 
:-(
:-(

**Comment by sasumner** [comment]
User desire:  https://community.notepad-plus-plus.org/topic/15209/find-in-selected-text

**Comment by Uhf7** [comment]
After reading #8207, I have another idea to implement this consistently:
- Remove the **Find All In Current Document** button from the **Find** page.
- Replace the **Count** button of the **Find** page with a **Find All** button, equal to the **Replace All** button in the **Replace** page.
  _Assumption:_ We don't need the **Count** button, because the list of search results contains the number of hits anyway.
- Now, the new **Find All** button finds all occurrences of the search target within the current document or in the current selection, depending on the checkmark beside it. And, **Find All** now works very similar to **Replace All** in the **Replace** page.

The function seems to be already there, only that it will be triggered by **Find All** instead of **Find All In Current Document**.

**Comment by sasumner** [comment]
@Uhf7 

Part of the goal when changing long-established software is to not change it too much; we wouldn't want existing users to be looking for a "missing" **_Find All in Current Document_** button, putting issues in saying "where did it go?"  And they would, I have no doubt of that.

Another note on "changing too much": In my PR notes, I talked about how I considered and discarded the idea of swapping the placement of two buttons -- as too disruptive to an established UI.

**_Count_** on its own is still useful, at least to me as a user as well as a developer.

**_Find All_** would be confusing, because the Find in Files tab already has a **_Find All_** button.

That all being said, I'm certainly not vehemently opposed to your suggestions, but @donho, as software owner, has final decision.  Let's see if he has any input on it.  We all want the best design.

**Comment by Uhf7** [comment]
The problem of the **_Find All_** button in two different pages could be solved by renaming the button in the **Find in Files** page to **_Find in Files_**. Then it would perfectly fit to the button below: **_Replace in Files_**.

**Comment by sasumner** [comment]
>The problem of the Find All button in two different pages could be solved by renaming...

Yes, but again you are talking about changing an established UI.

One thing you haven't perhaps considered (and I should have mentioned earlier) is all of the languages that Notepad++ is translated into.

These translations have taken the current UI text and translated the English versions into the same meaning in the other languages.

Translations are NOT managed by the Notepad++ dev team, so if you change a base English UI element, you immediately have a mismatch between the English and all of the other languages.
In theory these mismatches could last for years until all of the translations "catch up".

It is actually easier to add a new UI element:  The text of the new element appears in English in the foreign language versions, becoming an easy target for the people that use those versions and provide the translations.

**Comment by Uhf7** [comment]
I see the problem, and, what really must be avoided, is simply to rename a menu element in English, but keeping its ID, so that it appears in other languages with another meaning. Replacing a button would actually mean to remove the old button and to insert a new one at the same place, perhaps even leaving abandoned items in most language.xml's. I understand, that this should be done as seldom as possible. 

But it is also a strategy question here: If the current UI is regarded established and unchangeable, then the operabilty of Notepad++ will not getting better. If the main question at each modification is: "How can we preserve the existing UI?", then the progress of Notepad++ will eventually stall.

Of course, it is easier to add a new UI element for each new flavour of the Find function instead of making an existing UI element more systematic. But, preserving might not lead to a better solution.

Sorry for suggesting to sacrificy the **_Count_** function, but it seems redundant to me. Would it be better, if one would show the number of hits not only in the search result window but also in the status line of the Find dialog, or is the "pollution" of the search result window the problem here?

And, as always, it is my personal opinion, that my idea for **Find All** is a good solution, systematic and all. You might not see it that way. But at least, I told you about it.

**Comment by xylographe** [comment]
The **Count** button is very important, as it shows the number of matches without opening a new window.

**Comment by Uhf7** [comment]
That's indeed a reason, I didn't think about, so I would update my suggestion like this:

The frame around the existing **_Count_** button and the **_In Selection_** checkmark could be extended to the left, keeping its height. Then, within this frame, the following elements are placed from left to right:
- the **_In Selection_** checkmark, 
- the _**Count**_ button (right edge lined up with right edge of **_Find What_** text input,
- the **_Find All_** button (exactly below **_Find Next_**).

Why I find this solution better than swapping **_Find In Current Document_** and **_Find In All Opened Documents_** and then draw the frame around both?
- It looks more similar to the **Replace** page of the dialog.
- The frame has the same hight as in the **Replace** page, this helps implementation.
- The **_Find All_** button looks very different to the **_Find In All Opened Documents_** button, so they cannot be mixed up so easy. One reason for disard the swap solution might be, that the buttons look very much equal, both two lines text beginning with **_Find All..._** end ending with **_Document_**(**_s_**).

From the functional side, this solution is the same as swapping the buttons and drawing a bigger frame. And I find this solution, although already discarded for disruptiveness, better then a solution without frame and a hint for the **_In Selection_** checkbox.

**Comment by sasumner** [comment]
>If the current UI is regarded established and unchangeable, then the operabilty of Notepad++ will not getting better. If the main question at each modification is: "How can we preserve the existing UI?", then the progress of Notepad++ will eventually stall.

It wasn't my intent to say it is "unchangeable".
It should be changeable where needed, but historical familiarity needs to be kept in mind.
Can the Notepad++ UI be made better?  Absolutely 100%.
Can any UI in any program be made better? Absolutely 100%.
It's all absolutely very subjective as well.

**Comment by sasumner** [comment]
Related to the UI part of the discussion!? :  #8213

**Comment by sasumner** [comment]
Released in N++ version 7.8.8
