### ISSUE TITLE
Make "new " string for new tab translatable

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#815]
Hello,

[line 62 of `Buffer.h`](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScitillaComponent/Buffer.h#L62) hardcodes the string used as title for new tabs:

``` C++
const TCHAR UNTITLED_STR[] = TEXT("new ");
```

I suggest to make that string translatable _with arbitrary number position_.

I would translate it to German with: `Unbenannt (%d)`. `Unbenannt` is derived from Windows' Notepad, and `(%d)` is derived from Windows Explorer's naming of files.

**Comment by Ach3r0n** [comment]
I also would like this string to be translatable, but I don't like the string getting changed from "new" to "untitled". To differentiate untitled files from files with a filename maybe additional characters can be added, like block quotes or :: for example. I prefer :: over block quotes as it makes reading the label a bit harder.  I would also suggest to change the title from new to new document and add the number sign to it. 

The title would then become something like this:  :: new document #1 ::

**Comment by h-h-h-h** [comment]
How long is that document new? Because Notepad++ can restart keeping unsaved buffers, one might let "new" documents reside for some time! In my opinion, "new" is not appropriate.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
