### ISSUE TITLE
Switch to using the new PCRE2 library

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#816]
Hello,

the PCRE library has changed its API and will provide new features only by means of the new API. Notepad++ should therefore switch to the new one.

Let me quote the official website (http://www.pcre.org/):

> The original, very widely deployed PCRE library, originally released in 1997, is at version 8.37, and the API and feature set are stable—future releases will be for bugfixes only. All new future features will be to PCRE2, not the original PCRE 8.x series.

You can find a summary of the changes under the following link: https://lists.exim.org/lurker/message/20150105.162835.0666407a.en.html.

---

Related discussion: https://notepad-plus-plus.org/community/topic/9703/is-it-planned-to-switch-to-pcre2

**Comment by h-h-h-h** [comment]
PCRE2 makes a feature available to replace according to a list with only one regular expression. This is done via the `pcre2_substitute()` function.

Example:
```
Target:       apple lemon
Find:         apple(*:pear)|lemon(*:orange)
Replace with: ${*MARK}
Result:       pear orange
```

View the latest version of the following file to see the documentation about this: http://vcs.pcre.org/pcre2/code/trunk/doc/pcre2.txt ([rev. 360](http://vcs.pcre.org/pcre2/code/trunk/doc/pcre2.txt?revision=360&view=markup)). Search for:
- `${*MARK}`
- `PCRE2_ALT_VERBNAMES`

Is it possible to make this functionality available in Notepad++? *Note:* To allow *any* replacement string in `(*:...)`, `PCRE2_ALT_VERBNAMES` has to be set. It allows escaping (e.g., `\)`), free spacing and comments.

**Comment by Erutan409** [comment]
Is there any efforts being made on this topic?  I'm sorely missing the functionality I'd expect in PCRE, such as: backtracking control verbs.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
