### ISSUE TITLE
"Find in these found results" does nothing when first "Find result" window opened via macro execution

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8199]
### Description of the Issue

If a macro is run that causes the first output to the "Find result" window in a Notepad++ run, then right-clicking in the "Find result" window and choosing "Find in these found results" results in nothing further happening with that.

### Steps to Reproduce the Issue
1. Record and save a macro that causes data to be written to the "Find result" window (the simplest being a "Find All in Current Document" search).
2. Restart Notepad++
3. Play the previously saved macro.
4. Right-click in the "Find result" window and choose "Find in these found results..." from the popup menu.

### Expected Behavior
After step 4 is executed, I expect to see this dialog box appear:

![image](https://user-images.githubusercontent.com/30118311/80864423-82ec0680-8c50-11ea-8b5a-b11911dbe311.png)

### Actual Behavior
Nothing happens (no dialog opens) after step 4.

### Debug Information
Notepad++ v7.8.6   (32-bit)
Build time : Apr 21 2020 - 15:17:06
Path : C:\.........\npp.7.8.6.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1039
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Some initial investigation shows that the message NPPM_INTERNAL_FINDINFINDERDLG is sent when the user chooses "Find in these found results..." but that message is never received so no further processing occurs.  This is obviously for the "bug" case.

In the "non-bug" case (where a macro is not run to create the initial "Find result" window -- meaning an interactive "find all..." has created it), the message NPPM_INTERNAL_FINDINFINDERDLG is sent (in `FindReplaceDlg.cpp`) when the user chooses "Find in these found results..." and it is correctly received (in `NppBigSwitch.cpp`) allowing processing to continue, and the dialog box for the subsequent search operation to appear.

**Comment by Uhf7** [comment]
I investigated further. It is an initialization problem.

The function `FindReplaceDlg::execSavedCommand(...)` 
is called before the FindReplaceDlg is initialized. FindReplaceDlg then initializes the `_pFinder` window (dockable window for the search results), and uses `_hSelf` as parent for `_pFinder`. Which is zero. Later on, the **SendMessage** to `_hParent` does not work.

**Verification**
Start Npp and immediately execute the pre-recorded macro. Now, the function **_Find in these found results_** doesn't work. 
Then Start Npp, open the Find dialog, close the Find dialog without searching anything, and then execute the pre-recorded macro. Now, the function **_Find in these found results_** works. 

**Suggestion**
Replace
`_pFinder->init(_hInst, _hSelf, _ppEditView);`
with
`_pFinder->init(_hInst, (*_ppEditView)->getHSelf(), _ppEditView);`.

It is around line 2333 in **FindReplaceDlg.cpp**, at the beginning of the `findAllIn` function.

**Comment by Uhf7** [comment]
Working a few days with my quick solution revealed a hard-to-explain problem in it.

The idea of my solution is, that the `_hParent` window of `pFinder` is needed only to send the command messages to the parent of `_hParent`. Which is the Big Switch main window. So I used the current edit view as `_hParent`, because it's parent is the Big Switch too, and it is available even when the window of the **FindReplaceDlg** has not been initialized yet.

But there is one strange call `_pFinder->display();`. It sends a **NPPM_DMMSHOW** message to `_hParent` of `_pFinder`. This is originally the window of the **FindReplaceDlg**. The dialog procedure of it, `FindReplaceDlg::run_dlgProc`, doesn't handle this message and returns false. So actually, that's why I call the call 'strange', it does nothing ever.

However, with my suggestion applied, this call comes to a live. The **NPPM_DMMSHOW** is sent now to a Scintilla edit view, which interprets it as **SCI_STYLESETITALIC** (message constants have same value), and in turn, my edit view is _italic_ now. I didn't intend this.

Now I suggest to comment out the `pFinder->display()` call too. For a quick solution. It is at the end of the same if clause, in which `pFinder->init` is called earlier.

I searched for any places where `_hParent` of `pFinder` could be used, and found nothing else until now.

**Comment by sasumner** [comment]
@Uhf7 It looks like you had some good investigation going here.  Are you going to wrap it up into a PR?

**Comment by Uhf7** [comment]
@sasumner , it's long time ago, good that I posted it.

After re-investigation, the parent initializing problem is here
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/7399257f56f6830f2952ea7a3a2a8733fb84df0e/PowerEditor/src/ScitillaComponent/FindReplaceDlg.cpp#L2358
and here
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/7399257f56f6830f2952ea7a3a2a8733fb84df0e/PowerEditor/src/ScitillaComponent/FindReplaceDlg.cpp#L2474

Both can still be solved in the described way. 

----

The 'strange' `_pFinder->display()` call I mentioned is here:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/7399257f56f6830f2952ea7a3a2a8733fb84df0e/PowerEditor/src/ScitillaComponent/FindReplaceDlg.cpp#L2421
This one occurs a second time too, here:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/7399257f56f6830f2952ea7a3a2a8733fb84df0e/PowerEditor/src/ScitillaComponent/FindReplaceDlg.cpp#L2535

Both calls are still useless, because, even it they would work as intended, they are overridden in both cases a few code lines later by a working `SendMessage (_hParent, NPPM_DMMSHOW/HIDE...` call. So, from my today's point of view, I would remove the `_pFinder->display()` method completely.

----

OK, after re-investigating it, I think I'm able to wrap it up into a PR within the next 14 days.
