### ISSUE TITLE
[Feature Request] Add SCI_MULTIPLESELECTADDEACH and SCI_MULTIPLESELECTADDNEXT 

### ISSUE THREAD

**Issue by Ekopalypse** [notepad-plus-plus/notepad-plus-plus#8203]
[Both](https://www.scintilla.org/ScintillaDoc.html#SCI_MULTIPLESELECTADDNEXT) are parameter-less functions like SCI_CUT, SCI_PASTE etc.
but provide powerful functionality to npp, so I suggest to add them to the list of scintilla commands (shortcut mapper) and respective places.

**Comment by sasumner** [comment]
SCI_MULTIPLESELECTADDEACH seems useful because, say, if a user wants to replace all occurrences of "cat" with "feline" it could provide an easy and quick mechanism to accomplish it (Notepad++ 's *Replace* dialog could obviously be used but would be more cumbersome in this case).

SCI_MULTIPLESELECTADDNEXT seems less useful...but maybe I am missing something?

Are there use-cases which would more powerfully demonstrate why these are useful?

Also, I'm concerned about the Scintilla description where it says "within the target".  Does this have any implications?  End user would have no reasonable way to set a "target" prior to running.

**Comment by Ekopalypse** [comment]
SCI_MULTIPLESELECTADDNEXT - let's say you want to change only within a function block but not generally then you could hit the key stroke multiple times and only the selected ones will be replaced.

>"within the target" - I will follow up on this with some tests and examples later

**Comment by bitagoras** [comment]
I use VSCode multiediting now for a while and in my experience you will use ADDNEXT much more often than ADDEACH. With ADDEACH you have to make sure that you do not rename something else unintentionally. Typical use case is that you want to rename the variable "i" in a for-loop, but not outside the scope. You just press several times ctrl-D at the first occurence until all those local variables are selected and then you just rename it. This gives you full controll about the changes you make. It takes 2 seconds to select 5 variables and you can be sure not do not forget one in between. You also have a quick choice between selecting whole words only or also parts of words by starting at either an unselected or selected variable. You will get used to this new function very quickly and you really get addicted to it.

In VSCode there are even two more keyboard shortcuts for this workflow where you can undo (ctrl-u) or skip (ctrl-k) one of the ADDNEXT selections. But I did not find this function in scintilla.

**Comment by sasumner** [comment]
Seems to be a similar discussion going on here on the Community: https://community.notepad-plus-plus.org/topic/11360/multi-selection-and-multi-edit

**Comment by Ekopalypse** [comment]
For my tests:
When a new blank document is opened, then the target is set to (0,0).
If an existing document is opened or moved to another document with text,
then Target is set to the visible area and their positions.
If you insert text in an empty document, which exceeds the visible range,
the target is also reduced to the positions of the visible area.
Each search also modifies the target.

In short, simply calling the calls is not enough,
but the solution is just as simple and is called SCI_TARGETWHOLEDOCUMENT.

SCI_TARGETWHOLEDOCUMENT
SCI_MULTIPLESELECTADDNEXT

SCI_TARGETWHOLEDOCUMENT
SCI_MULTIPLESELECTADDEACH

Does this lead to problems with the above mentioned functions?
I don't think so, because already the change from one document to another changes the target
and this has certainly always been done.

To extend the functionality by "skipping", one would have to do
[SCI_TARGETWHOLEDOCUMENT](https://www.scintilla.org/ScintillaDoc.html#SCI_TARGETWHOLEDOCUMENT)
SCI_MULTIPLESELECTADDNEXT
[SCI_DROPSELECTIONN](https://www.scintilla.org/ScintillaDoc.html#SCI_DROPSELECTIONN)([SCI_GETSELECTIONS](https://www.scintilla.org/ScintillaDoc.html#SCI_GETSELECTIONS)()-2)


Translated with www.DeepL.com/Translator (free version)

**Comment by sasumner** [comment]
Scintilla docs also say: "The current searchFlags are used so the application may choose case sensitivity and word search options."  Thus, perhaps this logic is best:

"add next":
- SCI_TARGETWHOLEDOCUMENT
- SCI_SETSEARCHFLAGS(SCFIND_MATCHCASE + SCFIND_WHOLEWORD)
- SCI_MULTIPLESELECTADDNEXT

"add each":
- SCI_TARGETWHOLEDOCUMENT
- SCI_SETSEARCHFLAGS(SCFIND_MATCHCASE + SCFIND_WHOLEWORD)
- SCI_MULTIPLESELECTADDEACH

"skip":
SCI_TARGETWHOLEDOCUMENT
SCI_SETSEARCHFLAGS(SCFIND_MATCHCASE + SCFIND_WHOLEWORD)
SCI_MULTIPLESELECTADDNEXT
SCI_DROPSELECTIONN(SCI_GETSELECTIONS()-2)

**Comment by bitagoras** [comment]
What seems not being supported by Scintilla is the choice between whole-word or partial-word seach. Here is how it works in VSCode:
![multiSelect](https://user-images.githubusercontent.com/10660123/80953448-d3ec2e00-8dfb-11ea-9348-05bf772dfca3.gif)
For SCI_MULTIPLESELECTADDEACH you can use SCI_GETSELECTIONS and SCI_GETSELECTIONEMPTY to distinguish the two cases. But for SCI_MULTIPLESELECTADDNEXT, unfortunately, I did not find a way to uniquely distinguish if the user has manually selected the first word or if it was done by a previous call of SCI_MULTIPLESELECTADDNEXT.

**Comment by dinkumoil** [comment]
I would like to suggest a "remove" operation too. That's because the "skip" operation (implemented like suggested by @Ekopalypse) not only removes the current selection but auto-advances to the next occurence of the search term and selects it.

Additionally the case of "multi-select mode is off" should be covered as well by the new functions.

FYI: This is my Lua implementation of the 4 functions. I use them in Npp v7.5.6 (whose _Scintilla_ doesn't support the _SCI_MULTIPLESELECTADDxxx_ commands).

```Lua
-- =============================================================================
-- Add menu entry to select all occurences of word under or next to cursor or
-- already selected word
-- =============================================================================

npp.AddShortcut("Selection Add All", "", function()
  local flags     = SCFIND_WHOLEWORD -- can use 0
  local startWord = -1
  local endWord   = -1
  local s         = ""

  editor.SearchFlags = flags

  if editor.SelectionEmpty or not editor.MultipleSelection then
    startWord = editor:WordStartPosition(editor.CurrentPos, true)
    endWord   = editor:WordEndPosition(startWord, true)

    editor:SetSelection(startWord, endWord)
    
    if not editor.MultipleSelection then
      return
    end
  else
    local i   = editor.MainSelection

    startWord = editor.SelectionNStart[i]
    endWord   = editor.SelectionNEnd[i]
  end

  s = editor:textrange(startWord, endWord)

  while true do
    editor:SetTargetRange(0, editor.TextLength)

    local i            = editor.MainSelection
    local searchRanges = {{editor.SelectionNEnd[i], editor.TargetEnd}, {editor.TargetStart, editor.SelectionNStart[i]}}
    local itemFound    = false

    for _, range in pairs(searchRanges) do
      editor:SetTargetRange(range[1], range[2])

      if editor:SearchInTarget(s) ~= -1 then
        editor:AddSelection(editor.TargetStart, editor.TargetEnd)
        itemFound = true
        break
      end
    end

    if editor.TargetStart == startWord and
       editor.TargetEnd   == endWord   or
       not itemFound                   then
      break
    end
  end

  -- To turn on Notepad++ multi select markers
  editor:LineScroll(0, 1)
  editor:LineScroll(0, -1)
end)



-- =============================================================================
-- Add menu entry to select next occurence of word under or next to cursor or
-- already selected word
-- =============================================================================

npp.AddShortcut("Selection Add Next", "", function()
  -- From SciTEBase.cxx
  local flags = SCFIND_WHOLEWORD -- can use 0

  editor:SetTargetRange(0, editor.TextLength)
  editor.SearchFlags = flags

  if editor.SelectionEmpty then
    local startWord = editor:WordStartPosition(editor.CurrentPos, true)
    local endWord   = editor:WordEndPosition(startWord, true)

    editor:SetSelection(startWord, endWord)
  else
    local i = editor.MainSelection
    local s = editor:textrange(editor.SelectionNStart[i], editor.SelectionNEnd[i])
    local searchRanges = {{editor.SelectionNEnd[i], editor.TargetEnd}, {editor.TargetStart, editor.SelectionNStart[i]}}

    for _, range in pairs(searchRanges) do
      editor:SetTargetRange(range[1], range[2])

      if editor:SearchInTarget(s) ~= -1 then
        if editor.MultipleSelection then
          editor:AddSelection(editor.TargetStart, editor.TargetEnd)
        else
          editor:SetSelection(editor.TargetStart, editor.TargetEnd)
        end

        -- To scroll main selection in sight
        editor:ScrollRange(editor.TargetStart, editor.TargetEnd)

        break
      end
    end
  end

  -- To turn on Notepad++ multi select markers
  editor:LineScroll(0, 1)
  editor:LineScroll(0, -1)
end)



-- =============================================================================
-- Add menu entry to select next occurence of word under or next to cursor or
-- already selected word but remove selection from word under cursor
-- =============================================================================

npp.AddShortcut("Selection Skip Current", "", function()
  -- From SciTEBase.cxx
  local flags = SCFIND_WHOLEWORD -- can use 0

  editor:SetTargetRange(0, editor.TextLength)
  editor.SearchFlags = flags

  if editor.SelectionEmpty then
    local startWord   = editor:WordStartPosition(editor.CurrentPos, true)
    local endWord     = editor:WordEndPosition(startWord, true)

    editor:SetSelection(startWord, endWord)
  else
    local i = editor.MainSelection
    local s = editor:textrange(editor.SelectionNStart[i], editor.SelectionNEnd[i])
    local searchRanges = {{editor.SelectionNEnd[i], editor.TargetEnd}, {editor.TargetStart, editor.SelectionNStart[i]}}

    for _, range in pairs(searchRanges) do
      editor:SetTargetRange(range[1], range[2])

      if editor:SearchInTarget(s) ~= -1 then
        if editor.MultipleSelection then
          editor:AddSelection(editor.TargetStart, editor.TargetEnd)
        else
          editor:SetSelection(editor.TargetStart, editor.TargetEnd)
        end

        -- To scroll main selection in sight
        editor:ScrollRange(editor.TargetStart, editor.TargetEnd)

        break
      end
    end

    editor:DropSelectionN(editor.Selections - 2)
  end

  -- To turn on Notepad++ multi select markers
  editor:LineScroll(0, 1)
  editor:LineScroll(0, -1)
end)



-- =============================================================================
-- Add menu entry to remove current main selection
-- =============================================================================

npp.AddShortcut("Selection Remove Current", "", function()
  if editor.Selections == 1 or not editor.MultipleSelection then
    editor.SelectionNCaret[editor.Selections - 1] = editor.SelectionNAnchor[editor.Selections - 1]
  else
    editor:DropSelectionN(editor.Selections - 1)
  end
  
  editor:ScrollCaret()

  -- To turn on Notepad++ multi select markers
  editor:LineScroll(0, 1)
  editor:LineScroll(0, -1)
end)
```

**Comment by sasumner** [comment]
It seems as this evolves, it losing its tight tie with SCI_* functions and is becoming its own thing. :-)

**Comment by Ekopalypse** [comment]
> "_**The current searchFlags are used so the application may choose case sensitivity and word search options**_."

Actually, I have tested this and cannot confirm that it has any influence.
With a PythonScript, that calls getSearchFlags and getTarget, I have tested as follows:

Npp restarted, only one new document available

Target is set to (0, 0)
Searchflags 0x600000 means 
  POSIX
  REGEXP

Text written and SCI_TARGETWHOLEDOCUMENT, SCI_MULTIPLESELECTADDNEXT called several times

Target is set to (0, 82)
Searchflags 0x8000002 means 
  WHOLEWORD
  REGEXP_SKIPCRLFASONE

Started find dialog and "match whole word only", "match case" and "wrap around" are set.
Executed "Count" with a "normal" search

Target is set to (68, 82)
Searchflags 0x8000006 means 
  MATCHCASE
  WHOLEWORD
  REGEXP_SKIPCRLFASONE

Switched to the document and called SCI_TARGETWHOLEDOCUMENT, SCI_MULTIPLESELECTADDNEXT again

Target is set to (0, 82)
Searchflags 0x8000002 means 
  WHOLEWORD
  REGEXP_SKIPCRLFASONE

Made the same test with SCI_TARGETWHOLEDOCUMENT, SCI_MULTIPLESELECTADDEACH with the same result.

**Comment by Ekopalypse** [comment]
@bitagoras 
> What seems not being supported by Scintilla is the choice between whole-word or partial-word seach
Not directly, yes, but using the calls together with the search flag "none" would result in searching
word parts instead of whole word.

**Comment by bitagoras** [comment]
@Ekopalypse : Sure, you can do the two sorts of selection and bind them to different keyboard shortcuts. But in editors based on the electron framework you can use the same shortcut ctrl-D for both operations, as I demonstrated above. In Notepad++ I use now ctrl+D and shift-ctrl-D for the two operations. This workaround is ok for me. For addEach I succeeded with NppExec to make it work using only one shortcut for both cases. Also the undo operation works perfectly (like ctrl-U in VSCode). I am currently struggling with implementing the skip operation. I will show the code when I succeeded.

**Comment by Ekopalypse** [comment]
@bitagoras 
I guess you can do this in Npp too by using a global variable which indicates whether whole_word_mode is active or not and maybe resetting it when a char gets added.
Something like this PythonScript

`
from Npp import editor, FINDOPTION

try:
   WHOLE_WORD_MODE
except:
    WHOLE_WORD_MODE = False
    
if editor.getSelectionEmpty():
    WHOLE_WORD_MODE = True

editor.setSearchFlags(FINDOPTION.WHOLEWORD if WHOLE_WORD_MODE else FINDOPTION.NONE)
editor.targetWholeDocument()
editor.multipleSelectAddNext()
`

**Comment by bitagoras** [comment]
@Ekopalypse : I think this would not only require to catch keyboard events but also mouse events. Nevertheless, in my opinion such modern feature as multi editing should be a basic functionality of any editor.

**Comment by bitagoras** [comment]
Here is my entire solution with NppExec which gives Notepad++ all the multi editing functionality from VSCode. The only difference is that there are two different shortcuts each for addNext and for skip.

**addNext** (Ctrl-D):
```C
NPP_CONSOLE 0
sci_sendmsg 2690  // SCI_TARGETWHOLEDOCUMENT
sci_sendmsg SCI_SETSEARCHFLAGS 0
sci_sendmsg 2688  // SCI_MULTIPLESELECTADDNEXT
```
![multiSelect_D](https://user-images.githubusercontent.com/10660123/81012658-3b38cb00-8e5a-11ea-9464-8c85087b0389.gif)

**addNextWholeWord** (Shift-Ctrl-D):
```C
NPP_CONSOLE 0
sci_sendmsg 2690  // SCI_TARGETWHOLEDOCUMENT
sci_sendmsg SCI_SETSEARCHFLAGS SCFIND_WHOLEWORD
sci_sendmsg 2688  // SCI_MULTIPLESELECTADDNEXT
```
![multiSelect_DW](https://user-images.githubusercontent.com/10660123/81012815-7cc97600-8e5a-11ea-9da2-2775a4f55dd2.gif)

**addEach** (Shift-Ctrl-L):
```C
NPP_CONSOLE 0
sci_sendmsg 2690  // SCI_TARGETWHOLEDOCUMENT
sci_sendmsg SCI_GETSELECTIONEMPTY
if $(MSG_RESULT) == 1 then
  sci_sendmsg SCI_SETSEARCHFLAGS SCFIND_WHOLEWORD
else
  sci_sendmsg SCI_SETSEARCHFLAGS 0
endif
sci_sendmsg 2689  // SCI_MULTIPLESELECTADDEACH
sci_sendmsg 2689  // SCI_MULTIPLESELECTADDEACH
```
![multiSelect_EACH](https://user-images.githubusercontent.com/10660123/81013568-a46d0e00-8e5b-11ea-81bd-9ac8cc2e6832.gif)

**undoAddNext** (Ctrl-U):
```C
NPP_CONSOLE 0
sci_sendmsg SCI_GETSELECTIONS
set n ~ $(MSG_RESULT) - 1
sci_sendmsg SCI_DROPSELECTIONN $(n)
```
![multiSelect_DU](https://user-images.githubusercontent.com/10660123/81013243-198c1380-8e5b-11ea-92dd-eb5c0826c609.gif)

**skip** (Alt-Ctrl-D):
```C
NPP_CONSOLE 0
sci_sendmsg SCI_SETSEARCHFLAGS SCFIND_NONE
sci_sendmsg 2688  // SCI_MULTIPLESELECTADDNEXT
sci_sendmsg SCI_GETSELECTIONS
set n ~ $(MSG_RESULT) - 2
sci_sendmsg SCI_DROPSELECTIONN $(n)
```
![multiSelect_DS](https://user-images.githubusercontent.com/10660123/81013252-1db83100-8e5b-11ea-8983-bc53a1334be0.gif)

**skipWholeWord** (Alt-Shift-Ctrl-D):
```C
NPP_CONSOLE 0
sci_sendmsg SCI_SETSEARCHFLAGS SCFIND_NONE
sci_sendmsg 2688  // SCI_MULTIPLESELECTADDNEXT
sci_sendmsg SCI_GETSELECTIONS
set n ~ $(MSG_RESULT) - 2
sci_sendmsg SCI_DROPSELECTIONN $(n)
```

**Comment by Ekopalypse** [comment]
@bitagoras - as a keyboard focused user I constantly forget about the mouse

>in my opinion such modern feature as multi editing should be a basic functionality of any editor.

As I do, hence the feature request.

**Comment by sasumner** [comment]
@bitagoras 

Your NppExec scripts for `skip (Alt-Ctrl-D)` and `skipWholeWord (Alt-Shift-Ctrl-D)` are exactly the same.

**Comment by sasumner** [comment]
@bitagoras 

In your NppExec script for `addEach (Shift-Ctrl-L)`, is it intentional to have TWO of these in a row at the end?:

```
sci_sendmsg 2689  // SCI_MULTIPLESELECTADDEACH
sci_sendmsg 2689  // SCI_MULTIPLESELECTADDEACH
```

**Comment by sasumner** [comment]
Just an aside to the current issue, I like this idea, perhaps only for myself.  :)

- Click+drag from higher-position in a document to a lower-position, stopping and releasing the drag when somewhere inside the word you want to multiselect in the block (the start of block doesn't necessarily have to extend to the start of that word).
- Press an assigned keycombo.
- All of the occurrences of the word in the block become selected, for easy change via overtyping.

**Comment by dinkumoil** [comment]
@sasumner 

Yeah, this is heading in direction of a sync-edit feature.

The Delphi IDE has it and for the open source editor _CudText_ there is a plugin available that can do it too, but it is less comfortable than Delphi.

The steps are the following:

1. Select a range of source text where you want to rename an identifier.
2. Press a key-combo. The selected area gets a special background color that is different from the one for normal selected text.
3. All identifiers which occur more than once in the highlighted text get marked by e.g. surrounding boxes (Delphi) or colored background (CudaText). **BUT** keywords of the used programming language are **not** marked.
4. Navigate the cursor using the arrow keys or by mouse click to the identifier you want to rename and start typing. You will get automatically multiple cursors at all other occurences of the identifier and can change them synchronously. The marking of the identifiers grows/shrinks while you type. Copy & paste also works synchronously for all marked identifiers.
5. If you want to change another identifier, again navigate the cursor using the arrow keys or by mouse click to the identifier you want to rename and start typing (this is **not** possible in CudaText).
6. If you want to exit sync-edit mode just navigate the cursor out of the marked range of source code by using the arrow keys or by mouse click.

It would be great to see this feature in Notepad++ one day!

**Comment by bitagoras** [comment]
> @bitagoras
> 
> Your NppExec scripts for `skip (Alt-Ctrl-D)` and `skipWholeWord (Alt-Shift-Ctrl-D)` are exactly the same.

Yes indeed, the second should have the SCFIND_WHOLEWORD flag rather than the SCFIND_NONE flag.

**Comment by bitagoras** [comment]
I edited the comment again with the proposed NppExec solution. I simplified it by a unified key for skip (Ctrl-E) for both partial and whole word matching. I also made the search case sensitive.

**Comment by Auncaughbove17** [comment]
any news on this?

**Comment by JergenRoss** [comment]
im waiting for update this

**Comment by hosamn** [comment]
What is the current status of this??

**Comment by donho** [comment]
Sorry for joining the discussion very late. I was not aware of it, until @alankilborn has mentioned this FR.

This feature request deserves add the extra bonus as the core feature in Notepad++.

Inspired by the NppExec script of @bitagoras, I would add 10 menu command under menu **Edit** as following structure:

```
...
Edit -> On selection
==================================================================================
Edit -> Multi-select all      -> Ignore case and whole word     Ctrl-          E
                              -> Match case only                Ctrl-Shift    -E
                              -> Match whole word only          Ctrl-      Alt-E
                              -> Match case and whole word      Ctrl-Shift-Alt-E
								 
								 
     -> Multi-select next     -> Ignore case and whole word     Ctrl-          ?
                              -> Match case only                Ctrl-Shift    -?
                              -> Match whole word only          Ctrl-      Alt-?
                              -> Match case and whole word      Ctrl-Shift-Alt-?
						  
     -> Undo last multi-select                                  Ctrl-?-?
     -> Skip a multi-select                                     Ctrl-?-?
===================================================================================
Edit -> Column mode...
...
```
What do you guys think about it?
It's pity that for the shortcut, only **E** is available, I would prefer to have another letter which is available completely for Multi-select next.

Please let me know your opinions.

**Comment by bitagoras** [comment]
@donho In my opinion the already wide-spread shortcuts (ctrl+D etc.) should be used in notepad++, since this is already the standard for mulit editing in important other applications (e.g. SublimeText, VSCode, Gitlab, Eclipse Theia) . I am working with VSCode and Notepad++ in parallel. It would be very annoying when this elementary function would behave different. Other functions on "D" should be removed from Notepad++. I never used ctrl+D for "line doubling", since you can do the same by copy and paste in 1 second.

**Comment by bitagoras** [comment]
Here is another demonstration for multi editing in notepad++ I did for the project [PyPadPlusPlus](https://github.com/bitagoras/PyPadPlusPlus/)

![](https://raw.githubusercontent.com/bitagoras/PyPadPlusPlus/master/demo/multiedit.gif)
* select next: `<Ctrl> + <D>`
* select next whole word: `<Shift> + <Ctrl> + <D>`
* undo select next: `<Ctrl> + <U>`
* skip and select next: `<Ctrl> + <E>`
* select all: `<Shift> + <Ctrl> + <L>`

**Comment by Ekopalypse** [comment]
Nice, I like it - yes - there are already a lot of predefined shortcuts and I tend to agree with @alankilborn not to assign any existing because see below 
@bitagoras - I wouldn't reassign shortcuts as users may have already become accustomed to them.

**Comment by donho** [comment]
@bitagoras 
> Here is another demonstration for multi editing in notepad++ I did for the project [PyPadPlusPlus](https://github.com/bitagoras/PyPadPlusPlus/)

It looks really awesome! All the multi-select operations in your demo do not exist in current implementation of Notepad++.
Are you using [BetterMultiSelection plugin](https://github.com/dail8859/BetterMultiSelection)?

> In my opinion the already wide-spread shortcuts (ctrl+D etc.)...

Ctrl-D is there since long time ago, and many people use it (including me) so I will follow the opinion of @alankilborn & @Ekopalypse - just keep these command shortcuts empty and let users to assign what they want to these 10 commands.

@Ekopalypse 
With the 10 commands that I suggested, do we still need to add SCI_MULTIPLESELECTADDEACH and SCI_MULTIPLESELECTADDNEXT to users?

**Comment by donho** [comment]
Please check PR #14295 to make sure if the commands are implemented correctly, and they are what you expect.

**Comment by Ekopalypse** [comment]
Tested with the x64 release artifact from [here](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/48404920/job/e586rluy9q48bapn/artifacts) and it works as I would expect. I can't think of any other use case, so I don't think it's necessary to add the calls to the Scintilla commands. From my point of view, the FR is more than processed. 
Thank you very much for this contribution.

**Comment by JergenRoss** [comment]
I'm crying about this. Awesome. comeback to programming gang.

**Comment by alankilborn** [comment]
If this is a "first step" towards full multi-editing support, that's fine and it seems to work well.  But is further support going to be added for the first release of N++ that contains this?  Such further support would be doing the things that @bitagoras shows [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8203#issuecomment-1785187665) and the desired behavior of the [other issue](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14266) that rejuvenated this discussion.  I'd guess that users would be disappointed if full support is not added all at once.  Also, such full support would make the [BetterMultiselection plugin](https://github.com/dail8859/BetterMultiSelection) obsolete.  @bitgoras and others: What's the feeling?

**Comment by bitagoras** [comment]
@donho 
> It looks really awesome! All the multi-select operations in your demo do not exist in current implementation of Notepad++. Are you using [BetterMultiSelection plugin](https://github.com/dail8859/BetterMultiSelection)?
Yes, BetterMultiSelection and NppExec are both used in combination to privide this functionality. You can download there a preconfigured Notepad++-Version for the Python environment to directly try the multi-edit with this workaround. I would really appreciate if this becomes a basic functionality.

I am using multi-editing this way now for several years. After some time you will use it in many situations where you would have used the "macro" function or the "search and replace" function in the past. For programming the multiedit "Select next" became my most-used function after the normal "Search" function.

Another observation is that the "select next" shortcut is mostly used as case-sensitive. I never had any use-case for the "non-cases-sensitive" selection, since variables in most programming languages are case-sensitive. I would therefore strongly recomment to use a preferred key for the the case-sensitive selection.

**Comment by Ekopalypse** [comment]
@alankilborn - for this FR I would say that everything (and more) has been done. The last missing piece to have full multi-editing support, from my point of view, is that rectangular selection is converted to multiselection, as discussed in the other issue. If this is also added natively to Npp, then BetterMultiselection will indeed be obsolete. Until then, I am a happy and grateful user of this plugin and of course Npp.

**Comment by VisarDomi** [comment]
Everything is coming together. Notepad++ just jumped up to the big leagues with this feature, as it's a serious alternative if you don't like how memory heavy vscode and similar editors are. So you would either use notepad++ or go for the very heavy IDEs.

**Comment by donho** [comment]
@bitagoras 
> Yes, BetterMultiSelection and NppExec are both used in combination to privide this functionality. 

Could you check PR #14313 without using the 2 plugins above to see if it meets your need?

@alankilborn @Ekopalypse @VisarDomi and others, I invite you to check PR #14313 as well.

**Comment by donho** [comment]
@bitagoras 
May I use your animated gif for the demo of v8.6 on release page?

**Comment by bitagoras** [comment]
> @bitagoras May I use your animated gif for the demo of v8.6 on release page?

Yes sure, your can use it.

**Comment by bitagoras** [comment]
> Could you check PR #14313 without using the 2 plugins you're using above to see if it meets your need?
Sorry that I did not react to your request, since I just did not understand how this commit was related to the SCI_MULTIPLESELECTADDEACH and SCI_MULTIPLESELECTADDNEXT feature. The commit seemed to be only for the "column mode to multi-caret" request, which is something different. In the animation I only used the shortcut for the SCI_MULTIPLESELECTADDEACH. But I could not find this keyword in this commit in the file ScintillaEditView.cpp. Maybe there was some misunderstanding. Is this feature now implemented or not?

**Comment by donho** [comment]
@bitagoras 

> Is this feature now implemented or not?

Yes it's implemented in v8.6 under the menu **Edit**:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/90293/d89b436e-6e63-46c5-afc9-0d91a996a376)


As well multi-edit has been enhanced in v8.6, you can do [what you have shown in the animated gif](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8203#issuecomment-1785187665) without BetterMultiSelection and NppExec.

**Comment by bitagoras** [comment]
> Yes it's implemented in v8.6 under the menu **Edit**

Sorry, I was looking for the feature in the shortcuts for "Scintilla Commands". Even this is already too late: Yes, I confirm that everything I did in the animation is now possible without any plugins. It's just perfect. Thank you so much for this update!

**Comment by eldepor** [comment]
Those features on the gif looks awesome but how to use them? Any manual? Most of the steps I see there I have no idea how to reproduce them. Thx

**Comment by eldepor** [comment]
Those features on the gif looks awesome but how to use them? Any manual? Most of the steps I see there I have no idea how to reproduce them and its too fast to identify. Thx

**Comment by eldepor** [comment]
Those features on the gif looks awesome but how to use them? Any manual? Its too fast and some of the steps I see there I have no idea how to reproduce them. Specially the last one where you select every "object" word wihout using any edit menu and the other one is the 4th step or so where you select a whole column of words and the paste it between the quotes.

Thanks

**Comment by bitagoras** [comment]
To reproduce the demonstration you first have to set a shortcut to the new function:

- In Notepad++ v8.6 go to menu "_Settings / Shortcut mapping ..._"
- Go to tab "_Main menu_"
- Find the command "_Multi-select Next: Match Case Only_" (line 104)
- Double click to the empty field in column "_Shortcut_"
- Choose **Ctrl + D** as shortcut
- When the shortcut becomes red and it says "conflict found", go to that entry (e.g. SCI_LINEDUPLICATE in "Scintilla Commands") and set the other shortcut to "none" in order to disable it.
- There are also other useful commands for multi editing. They were not used in the animation, but for completeness I recommend the following list of shortcut mappings, so that you get used to similar shortcuts in other common projects (e.g. Visual Studio Code):
  - `Multi-select Next: Match Case Only`: **Ctrl + D**
  - `Multi-select Next: Match Case and Whole Word`: **Ctrl + Shift + D**
  - `Undo the Latest Added Multi-Select`: **Ctrl + U**
  - `Multi-select All: Match Case Only`: **Ctrl + L**
  - `Multi-select All: Match Whole Word Only`: **Ctrl + Shift + L**
  
In the animation the only new shortcut that was used is **Ctrl + D**. All other commands where standard shortcuts from any other Windows editor.

To start with the example, copy this line into Notepad++:
`var1, var2, object1, object2, object3, flag1, flag2`

Now these are the first steps I did in the animation:
- Add another comma at the end
- Select the first comma
- Press **Ctrl + D** seven times. This is the magic command that does the whole trick. Try it and you will love it!
- Now you can do everything you normally do with a sinlge selection and a single cursor: **Backspace**, **Backspace**, **Enter**, ... Even Copy and Paste is working in the expected way.
- **Ctrl + D** was also used in the animation for the selection of lines with "obj."  and for the renaming of "object" to "data".

Here is again the animation from above:
![](https://raw.githubusercontent.com/bitagoras/PyPadPlusPlus/master/demo/multiedit.gif)

**Comment by bitagoras** [comment]
One more note to the solution: There is a little difference in the multi-select functions compared to other editors such as VSCode. When in Npp a part of a word is selected and then the command "Multi-select All: Match Whole Word Only" is applied, the result is in a sense inconsistent, since the first selection remains a part word selection, which contradicts the "whole word only". In VSCode this is solved in a way that the two functions "Multi-select All: Match Case Only" and "Multi-select All: Match Whole Word Only" are unified in one shortcut. There you can choose:
- If something is selected, the command is started in the "Match Case Only" mode.
- If nothing is selected, the command is started in the "Match Whole Word Only" mode and the word below the cursor is the whole word to be selected.

The advantange is that you need to remember one shortcut less while the usage is quite intuitive. The same unification is done for "Multi-select Next: Match Case Only" and "Multi-select Next: Match Case and Whole Word". Maybe this concept could also be an option for a future Notepad++ version? Currently there are 10 multi-select commands each of which make only sense if it is bound to a keyboard shortcut. It could help if these features could become accessible by less shortcuts.
