### ISSUE TITLE
Request Auto-Indent option to choose indent style

### ISSUE THREAD

**Issue by oliezekat** [notepad-plus-plus/notepad-plus-plus#821]
Auto-Intend option apply "Smart Indent" feature to some languages (C, Java, PHP, Javascript) since Notepad++ 6.7

This feature promote only K&R indent style and become a nightmare if we prefer another style like  Allman or Whitesmiths.
I had explained how to solve this problem with NppAutoIndent plugin at end of the issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/296

**I submit that Auto-Indent feature include an optional option to choose between "Previous line" (Allman), "Block Indent" (Whitesmiths), or "Smart Indent" (K&R) methods** like NppAutoIndent plugin.

Nb: Notepad++ applied "Previous line" method before 6.7 release.

**It's could be great that Notepad++ detect indent style of current document and switch Auto-Indent to right method.**

Nb: more indent styles exists, see https://en.wikipedia.org/wiki/Indent_style

My personal skill is to use Whitesmiths style if I create JS or PHP file, Allman style for CSS file, but I apply K&R (or other) style while I edit a third party file. I'm most aware than Notepad++ ^^

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by oliezekat** [comment]
Problem not solved.
