### ISSUE TITLE
Closing modified clone produces make periodic backup lost

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8227]
### Description of the Issue

When a file tab is cloned into another view, by definition there is an exact-copy file tab in the opposite view.  When one of the cloned tab is closed by the user, it can be discarded without any save prompting because the file will still be open in a tab in the opposite view, with all data intact.  

Unfortunately, it doesn't happen this way and save prompting occurs.

### Steps to Reproduce the Issue
1. Create a new file or open an existing disk file in Notepad++
2. Modify the file in some way
3. Clone the file (e.g. right-click its tab, choose _Clone to Other View_)
4. Close either of the tabs for this file

### Expected Behavior
I expect the file tab to quietly disappear in the view I've told it to close in; because of its cloned nature nothing can be lost.

### Actual Behavior
I'm prompted to save:
![image](https://user-images.githubusercontent.com/30118311/81214585-105b8d80-8fa6-11ea-99ce-4f60601f4d79.png)
I'm not ready to save at this point, but I want the clone closed, so I choose `No`.
The clone closes, which is good, but I should not have been prompted in the first place

Even stranger, if I leave the file unsaved and attempt to quit Notepad++, I get this prompt:
![image](https://user-images.githubusercontent.com/30118311/81214938-97106a80-8fa6-11ea-8966-7491595cc202.png)

Backup preferences are set this way:
![image](https://user-images.githubusercontent.com/30118311/81215059-c030fb00-8fa6-11ea-9824-496218fd4100.png)

### Debug Information
Notepad++ v7.8.6   (32-bit)
Build time : Apr 21 2020 - 15:17:06
Path : C:\..........\npp.7.8.6.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1039
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by alankilborn** [comment]
I encountered this problem in something I was doing today.  I was attempting to script a solution for #12353 when I noticed it.

**Comment by alankilborn** [comment]
First reported over 4 years ago, and such an obvious bug remains unfixed.  :-(
I can repro exactly as OP first reported with 8.6.8.

**Comment by donho** [comment]
I didn't see this bug report. It's not a bug to me. Though it could be inconvenient for some.

The following situation can happen:
1. User opened a "new 2" tab and type some notes without saving and it lasts several months (it happened for some people that I've noticed in the bug reports).
2. User clones "new 2" to the 2nd view by accident one day.
3. By noticing the wrong action, user closes "new 2" of the 2nd view immediately.

If the behaviour is as you expected, then the note of sevral month will be lost forever.
So the current behaviour can be considered as a saver in above case.

**Comment by alankilborn** [comment]
>User clones "new 2" to the 2nd view by accident one day.  By noticing the wrong action, user closes "new 2" of the 2nd view immediately.  If the behaviour is as you expected, then the note of sevral month will be lost forever.

Hardly.
As said in the original _Expected behavior_ of 4 years ago, "...because of its cloned nature nothing can be lost".
The original `new 2` note will still present in the 1st view -- it's the 2nd view's clone counterpart, after all.

What makes it worse is that user can't go back to his original situation after his "accidental cloning"¹.  At the next N++ exit (when user probably has long-forgotten this accident), he is left wondering why the `new 2` note that he's been carrying for months is now going to be lost if he doesn't save it into the file system -- he just wants it to continue on as `new 2` -- but now this is impossible and he's forced to change something.  A poor recovery to his "accident".

¹:  This is one of the most unlikely-to-occur N++ situations that I've ever pondered

**Comment by alankilborn** [comment]
Consider the case for when the original file is saved into the file system, e.g. file is `d:\test.txt`, rather than being a "note" (e.g. `new 2`).
The `test.txt` file tab is cloned by the user and then modified in one of the views.
Then it is simply desired to remove the cloned status, keeping the (modified) file in the other view.

This **_IS_** possible, but it is awkward, as user attempting to close produces the "Save file `test.txt`?" prompt.
User doesn't necessarily want to save the file, just wants to ditch the cloned status.

Answering No to the prompt does what is desired, but user first wonders "will I lose my data if I say No?".

IMO the clone should be closed without prompting, and it would not bother me if the same document in the other view is left as the active doc after the action (as a possible reminder that the file WAS cloned).  

Off-topic, but perhaps a better reminder of the cloned status would be this potential feature: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15384

**Comment by donho** [comment]
> EDIT: I thought the above worked, but at N++ exit, the same "Your backup file cannot be found..." dialog occurs as for the new 2 note case. This is horrible.

That's indeed a bug to me: Could you open a bug for it please?

**Comment by donho** [comment]
> I'm not ready to save at this point, but I want the clone closed, so I choose No.
> The clone closes, which is good, but I should not have been prompted in the first place

> Even stranger, if I leave the file unsaved and attempt to quit Notepad++, I get this prompt:

That's indeed a bug, sorry for misreading the post.
