### ISSUE TITLE
Text marking with color or underlined or colored background (like textmarker)

### ISSUE THREAD

**Issue by aw24nbg** [notepad-plus-plus/notepad-plus-plus#8237]
![mark](https://user-images.githubusercontent.com/64982632/81330695-bee3f900-90a0-11ea-9f89-58de997e5537.jpg)

**Comment by sasumner** [comment]
Closing as it is incoherent as an issue.

(Top part appears to be copying of the 7.8.6 change log for some reason).

If you have a real issue, please follow the issue-creation template instead of deleting it out (which you must have done to post here without it.

>Is it possible to mark...?

Please take questions to one of the support forums; suggest https://community.notepad-plus-plus.org/
