### ISSUE TITLE
file modified detection reload scroll behavior

### ISSUE THREAD

**Issue by asdef** [notepad-plus-plus/notepad-plus-plus#8268]
### Description of the Issue
For a file that is longer than a single screen full of text, when an external application makes a modification to it and the file change detection dialog pops, the resulting reload moves my view of the file to the bottom, whereas when I use File > Reload from disk my scroll position is preserved (preferred).  The specific use case I have for this is I keep my jboss standalone.xml file open in notepad++ so I can change the DB JNDI information as I'm debugging on my local between server startups.  The process of starting and stopping jboss thru IntelliJ updates a section near the end of standalone.xml, causing the change detection to fire.  When I come back to the file in notepad++, I find that my best path is to decline the change detected reload and use file > reload from disk so I don't loose my scroll position over the DB JNDI section.  My best guess as to why it scrolls to the bottom is that's where the change was detected, but by the time I reload it, the change is gone, because I've stopped the server.

### Steps to Reproduce the Issue
1. Load a file that has enough lines to scroll beyond the visible view ( > 100 lines)
2. scroll to someplace in the middle of the file with content not visible above and below, make a change and save
3. use an external tool to make a change near the end of the file, but not at the end (a few lines up)
4. when the change detected dialog pops up, allow the reload

### Expected Behavior
I expected the file to reload, and leave the scroll position in the file where it is in the middle.

### Actual Behavior
The file gets scrolled to the bottom of the file.

### Debug Information
Notepad++ v7.8.6   (32-bit)
Build time : Apr 21 2020 - 15:17:06
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.1565
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll PluginManager.dll XMLTools.dll

**Comment by sasumner** [comment]
Excellent issue report. :-)

I could not reproduce it on a 7.8.6 setup. :-(
Caret and user view always remained where I had it before the external modify; in the middle of the file.

I was using the default settings as shown here:

![image](https://user-images.githubusercontent.com/30118311/81965248-c5fd9080-95e5-11ea-99dd-4eab55b627e2.png)

You probably have the same settings, but since you didn't specifically say...

Perhaps remove some plugins as a test, perhaps something there is causing strange interaction behavior.

I don't suspect it of causing a problem, but perhaps remove PluginManager for good as it is something that is not currently useful.

These are the plugins that were active during my unsuccessful testing:

- mimeTools.dll 
- NppConverter.dll 
- NppExport.dll

**Comment by asdef** [comment]
@sasumner Didn't even know that setting was there!  Unchecked the Scroll to the last line after update, and it fixed my issue.  Closing the issue.
