### ISSUE TITLE
Just deactivate the find-and-replace dialog on Esc

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#828]
Hello,

it would be helpful to have an option what to do when pressing <kbd>Esc</kbd> while the find-and-replace dialog is active. There should be the options:
- _Close dialog_ (current behavior)
- _Deactivate dialog and give focus to Scintilla._ This is especially useful when having a very transparent dialog when deactivated. You still have <kbd>Alt</kbd>+<kbd>F4</kbd> to close the dialog. With this option you would be able to achieve the same effect with the keyboard as when giving focus to Scintilla with the mouse!

**Comment by xylographe** [comment]
:+1: 

It's really annoying that you need mouse to change focus from find dialogue to text.

**Comment by aaaxx** [comment]
Good idea. Although, in fairness, the whole dialogue should have been made dockable ages ago.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
