### ISSUE TITLE
Cannot save changes made in a new file with extension different than .txt

### ISSUE THREAD

**Issue by mgiupponi** [notepad-plus-plus/notepad-plus-plus#8287]
### Description of the Issue
Cannot save changes made in a new file with extension different than .txt

### Steps to Reproduce the Issue
1. Create a new file
2. Type some lines
3. Save file with an extension different than .txt (for example .sh, .yaml, .xml)
4. Type more lines to the file
5. Try to save the file again

### Expected Behavior
Changes to the file should be saved

### Actual Behavior
Changes to the file are not being saved

### Debug Information
Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1158
Plugins : ComparePlugin.dll Linter.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PythonScript.dll RunMe.dll SessionMgr.dll

**Comment by alexander-narbut** [comment]
Having the same issue, I've lost a few hours of my life thinking that ctrl+s saves my file, but it silently did nothing.

**Comment by mauriciolp** [comment]
This bug has been around for years now.
From time to time I forget about it, and lose a day worth of new notes, very annoying.
I hope the developers can fix it.

In my case, saving with a .txt extension also causes it.

**Comment by sasumner** [comment]
@mauriciolp said

>I hope the developers can fix it.

Reproducing it is the big barrier.
Anything else you can add that would help in that?

**Comment by mauriciolp** [comment]
Just now I tried something different, and surprisingly the bug did not happened.
I think this bug is related to the language highlighter.
My Notepad++ is configured to use "Shell" language for '.txt' files.
So what I did now was to set up the language of the new (unsaved) file to "Shell", only then I saved it.
When I did this there was no problem, the file could be updated and new saves were working.

So whenever Notepad++ has to change the Language after saving the file, it seems the bug occurs.

@sasumner let me know if that helps a bit =]

### Debug Information

Notepad++ v7.9   (64-bit)
Build time : Sep 22 2020 - 03:19:04
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2004
OS Build : 19041.572
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll SessionMgr.dll

**Comment by sasumner** [comment]
@mauriciolp 

So I don't have to waste time guessing, can you be explicit (in Notepad++ terms) about what you set up to achieve this?:

`configured to use "Shell" language for '.txt' files`

By this:

`set up the language of the new (unsaved) file to "Shell"`

I do take it to mean you did this:

![image](https://user-images.githubusercontent.com/30118311/96348400-6b75ce00-1076-11eb-8e20-594cca33e300.png)

**Comment by donho** [comment]
I did the following steps and cannot reproduce this bug:

1. Create a new file
2. Type some lines
3. Save file with the extension .sh
4. Type more lines to the file
5. Try to save the file again

Could you guys remove all plugins and try again?

**Comment by donho** [comment]
Culprit found: It's bug of Session Manager plugin - remove SessionMgr.dll manually or uninstall it via Plugin Admin will solve your problem.

**Comment by tomastelensky** [comment]
> Culprit found: It's bug of Session Manager plugin - remove SessionMgr.dll manually or uninstall it via Plugin Admin will solve your problem.

but if I remove Session Manager, will it not be missing? Won't the NPP be missing some functionality then? What was Session Manager doing?

**Comment by sasumner** [comment]
@tomastelensky Per 9475 (see just above) it appears that this will be fixed in the release of N++ following 7.9.3.
After that you should be able to use _Session Manager_ plugin again.
