### ISSUE TITLE
Styler Configuratior: User extensions are overwritten by default extensions

### ISSUE THREAD

**Issue by dfs-** [notepad-plus-plus/notepad-plus-plus#8304]
### Description of the Issue

The Style Configurator dialogue allows the user to specify an arbitrary amount of user extensions per language. I use this to allow our sql procedures (which have varying extensions, one of which is .PRO) to be syntax highlighted as SQL files.
However the PRO extension is assigned to “Visual Prolog” instead of SQL, as the default extensions for Visual Prolog are “**pro** cl i pack ph”. User defined values should always be 

### Steps to Reproduce the Issue

1. Go to Settings > Style Configurator...
2. In the dialogue select language "SQL"
3. Add "pro" to User ext. (note, that pro is one of the default extensions for Visual Prolog
4. Save & Close the dialogue
5. Open a file with the PRO extension
6. Syntax Highlighting is set to Visual Prolog, but should be SQL.

You can also see a visual representation in the community thread I opened: https://community.notepad-plus-plus.org/topic/19438/user-extensions-in-style-configurator-are-overwritten-by-default-extensions

### Expected Behavior

It is expected, that user defined language file extensions are of higher priority, than default file extensions

### Actual Behavior

The priority seems to be determined by the method last one wins.

### Debug Information

Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.778
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll PythonScript.dll XMLTools.dll

**Comment by ProxyPlayerHD** [comment]
If i may add to this, i've been having the same issue on v8.4.4 when i tried to add OpenCL's `.cl` extension to C and it also mapped to Visual Prolog... somehow.

and it was even more confusing for me because i kept looking through the style configurator's language/extension list and couldn't for the life of me even find "Visual Prolog" let alone the extensions NP++ was aparently mapping to it.

turned out i disabled a lot of languages i never use in the preferences (Language Menu) a while ago and Visual Prolog is under the "Disable Items".

so question is why does the file extension for a manually disabled language have a higher priority than a user extension? or rather why does it have any priority at all? NP++ already hides sytaxes for languages you disable from the language tab, so why shouldn't it then also ignore the language's extensions?
if you want a language to be gone it should be fully gone and not have NP++ pull it's syntax from the graveyard just because you opened a file with one of its extensions.
