### ISSUE TITLE
Multi-thread "find in files" for np++

### ISSUE THREAD

**Issue by wtfiwinomgs** [notepad-plus-plus/notepad-plus-plus#8329]
### Description of the Issue
NP++ not using all the cores and I/O capable provided by computer. hardware have advanced massively over last 2-3 years. I even have optane SSD and a 16 cores CPU, find in files still takes forever and barely using the hardware.

please before mentioning that **scintilla** does not allow it, read this comment by scintilla. they are saying issue is with notepad ++.  https://sourceforge.net/p/scintilla/bugs/1194/?page=1&limit=25#4fdf

### Steps to Reproduce the Issue

1.  Find in files
2.  *.* search 30k+ files
3.  watch it search forever while CPU barely any usage and no disk I/O on SSD.

### Expected Behavior
search finish much quicker taking advantage of I/O CPU cores.

### Actual Behavior
slow, takes over 30 mins to search.

**Comment by wtfiwinomgs** [comment]
bump.. any update? its been close to half a year now

**Comment by donho** [comment]
The multi-thread for find in files is unlikely to be implemented.

**Comment by pps83** [comment]
> The multi-thread for find in files is unlikely to be implemented.

as mentioned, the code itself seems to be incredibly too slow: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8329#issuecomment-906357069
plus, it may not need to use threads, but it MUST not use gui thread to do the work. Not sure if it's the same garbage as I wrote about it 3 years ago. Hopefully it's fixed since then, as it's too obvious that something was wrong.
