### ISSUE TITLE
Notepad++ in "Post-it" view mode won't minimize

### ISSUE THREAD

**Issue by Avtem** [notepad-plus-plus/notepad-plus-plus#8345]
### Description of the Issue
Can not minimize notepad++ in "Post-it" view mode.

### Steps to Reproduce the Issue

1. Open notepad++
2. Switch to "Post-it" view mode (F12 hotkey or View->Post-it)
3. Try to Display the desktop with standard windows hotkey (win + D)

### Expected Behavior
Normally any program minimizes and if you press (win+D) again it restores (It works fine when Notepad++ not in "Post-it" mode)

### Actual Behavior
When (win+D) is pressed nothing happens

### Debug Information
Windows 7, Notepad++6.8.6

**Comment by Ekopalypse** [comment]
Isn't that the whole idea of the post-it feature?

**Comment by Avtem** [comment]
Oh, that's right. Sorry for misunderstanding, i should check the meaning of "Post-it".
i used "Post-it" mode because it removes all bars completely and only text remains.
Thank you for the answer. Do i delete this post or close?

**Comment by Ekopalypse** [comment]
I would close it, but it is your issue, so do what you like to do, and please keep in mind that just because one has a different opinion does not mean that your request is not legitimate.
If you feel it the window should be handled by WIN+D shortcut keep it open. At the end the project
owner has to decide what to do.

Under Settings->Preferences->General you can show/hide all the different parts, except for the window frame. If you want to get rid of that too, you, afaik, have to, for example, use the 
Pythonscript plugin and call [SetWindowLong](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowlongw) and [SetWindowPos](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowpos) with the correct parameter.

**Comment by Avtem** [comment]
@Ekopalypse Thanks for the suggestion! However i use shortcut F12 very often, so changing settings all the time (even via macros) isn't good for those who like to hide/show all toolbars often, like me
