### ISSUE TITLE
Typing Unicode character number for Indian rupee symbol (₹) displays another symbol (╣)

### ISSUE THREAD

**Issue by Pavitrag** [notepad-plus-plus/notepad-plus-plus#8358]
### Description of the Issue
In Windows machines, we can enter a Unicode character in notepad++ by pressing [ALT] key and simultaneously pressing the Unicode character number in decimal format. For example, when I press [ALT] + 0223 I get German symbol: 'ß'. because 'ß' has Unicode value (in decimal) 0223.
Similarly, I wanted to enter the Indian Rupee symbol: '₹', which has Unicode value: 8377 (in decimal) and 20B9 (in hexadecimal). To do so I entered [ALT] + 8377 but instead of displaying character: ₹  it displays character '╣'

### Steps to Reproduce the Issue
1. Create a new document in notepad++ (keyboard shortcut: [CTRL] + N)
2. In the new document press [ALT] key and simultaneously press numbers 8377
3. Observe that character: '╣' is displayed instead of '₹'

### Expected Behavior
It should display the character '₹'

### Actual Behavior
Displaying character '**╣**'

**Comment by Uhf7** [comment]
> In Windows machines, we can enter a Unicode character in notepad++ by pressing [ALT] key and simultaneously pressing the Unicode character number in decimal format.

That's a commonly widespread myth. What you actually enter with Alt+0nnn, is a decimal coded code point in the ANSI code page, which is currently active on your system. If you omit the "0" (Alt+nnn), then it is a code point in the OEM code page, which is currently active on your system.

To explain the effects, have a look at the code page 1252 at Wikipedia:
https://en.wikipedia.org/wiki/Windows-1252

Let's take two example characters: The "Sharp S" (ß), and the "Z with Caron" (Ž).

ß: Unicode U+00DF, code point in 1252: 0xDF, 0xDF == 223, U+0223 inserts ß on system with 1252 as current ANSI code page. Not because ß has the decimal Unicode 223, but because at the code point 223 in code page 1252 is occupied with the ß.

Ž: Unicode U+017D, code point in 1252: 0x8E, 0x8E == 142, U+0142 inserts Ž on systems with 1252 as current ANSI code page. The Unicode 0x017D == 381. U+0381 inserts }. Why? Because this input method cuts all bits above the 8th's, so actually U+0381 enters the code point 0x7D instead of code point 0x17D (which does not exist anyway).

U+8377: 8377 = 0x20B9 enters the code point 0xB9 of the current OEM code page, usually 437, and what we find at code point 0xB9, see https://en.wikipedia.org/wiki/Code_page_437, is Unicode U+2563 (╣). 

You cannot enter Unicode decimal using the Alt key under Windows. To enter Unicode hexadecimal in Windows 10, search the internet for the  `EnableHexNumpad` registry value.

**Comment by sasumner** [comment]
Closing due to explanation provided by @Uhf7
