### ISSUE TITLE
Security Vulnerability - Unquoted Service Path Enumeration

### ISSUE THREAD

**Issue by subalancex** [notepad-plus-plus/notepad-plus-plus#8386]
Scenario:

exec **Windows_Path_Enumerate.ps1** via PowerShell, script is accessible here:
https://gallery.technet.microsoft.com/scriptcenter/Windows-Unquoted-Service-190f0341

Screenshot **Notepad++**

![notepad++](https://user-images.githubusercontent.com/46025286/83977983-fd254000-a90c-11ea-8d03-0fb1c57dcc76.jpg)

**Note:**

Unquoted service executable path could allow to cause a denial of service and malicious file execution via carefully crafted and named executable files.

**Comment by donho** [comment]
@subalancex @chcg 
I don't follow the description of this issue at all.
Could you guys give me a hint?

**Comment by dodmi** [comment]
@donho: I don't know how severe the issue is in this case. But the general problem with unquoted paths containing spaces is:
Depending of the logic:
- won't work at all (error File not fount, because there is no executable with basename `program` in `C:\`)
- will work as intended (the software surrounds the string with quotes itself)
- or may have unexpected results (like in this case, probably, because the software will use the best fitting):
If there's an executable `program.exe` in `C:\`, the file executed would be `C:\Program.exe` with parameter `Files\Notepad++\uninstall.exe`, while otherwise `C:\Program Files\Notepad++\uninstall.exe` will be executed as intended.

Security impact:
An attacker could use this, to get his (malicious) code executed, by placing a file named `program.exe` im `C:\`

**Comment by donho** [comment]
`Windows_Path_Enumerate.ps1` is not part of Notepad++ so even this security issue exist, it's not come from Notepad++.
