### ISSUE TITLE
Requesting "Go to Column" feature

### ISSUE THREAD

**Issue by TomasRiker** [notepad-plus-plus/notepad-plus-plus#842]
We can go to lines and file offsets, but not to a certain column within a line. Let's say you're dealing with a minified JavaScript script file that still contains some newlines, and your browser tells you there's an error in "Line 3, Column 13778", then it would be nice to be able to directly jump there, without having to calculate the correct offset in the file.

**Comment by h-h-h-h** [comment]
I don't see any obstacles for this regarding the GUI design.

"Go To..." dialog:
```
( ) Line     ( ) Offset     (*) Column
```

The question is: Is that enough or would one want the ability to specify line and column at once?

**Comment by rafaelcastrocouto** [comment]
How can I help with this? This seems pretty straight forward to implement.
I'm working on large files and I'm missing this feature a lot.

**Comment by sasumner** [comment]
@rafaelcastrocouto 

>How can I help with this? This seems pretty straight forward to implement.

You make a PR for it.

I (Python-)scripted this behavior a long time ago since it seems "reluctant" (well, request was from 2015) to go native:

    desired_col = notepad.prompt('What column?', '', '')
    try:
        desired_col = int(desired_col) - 1
    except ValueError:
        pass
    else:
        if desired_col >= 0:
            cur_line_start_pos = editor.positionFromLine(editor.lineFromPosition(editor.getCurrentPos()))
            len_cur_line_content = len(editor.getCurLine().rstrip('\n\r'))
            new_pos = cur_line_start_pos + desired_col
            if new_pos > cur_line_start_pos + len_cur_line_content:
                new_pos = cur_line_start_pos + len_cur_line_content
            editor.setCurrentPos(new_pos)
            editor.chooseCaretX()
            editor.setSelection(new_pos, new_pos)

**Comment by SalviaSage** [comment]
Scott, how do I use this script exactly to go to the desired column
after placing it in the startup file?

**Comment by sasumner** [comment]
@SalviaSage You don't put it in the startup file. You run it from the Pythonscript menu, or toolbar button (if assigned) or keycombo (if assigned).

**Comment by rafaelcastrocouto** [comment]
Thanks a lot for the reply and the awesome code @sasumner 
But it seems like a lot to install the Pythonscript menu and a custom script for such a simple feature.
And this feels to me like it should be native, doesn't it?

**Comment by SalviaSage** [comment]
Yes, I agree, this feature should be there in Notepad++
But, as always, it just comes down to the developers willing to implement it.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by rafaelcastrocouto** [comment]
Are you serious or is this some kind of joke? 
I just lost my time downloading and reinstalling this editor for nothing.
So after 4 years, instead of implementing this simple feature that would take less than 15 minutes,
you are closing it and asking us to re-open just because "it's old"? Did you know you can filter issues by time in the github search.
Can you tell me why or how this will help?

**Comment by sasumner** [comment]
@rafaelcastrocouto said:

>Thanks a lot for the...awesome code @sasumner...But it seems like a lot to install...

I bet with the closure of this ticket my provided script code just got EVEN more awesome, and the effort to install Pythonscript and set up the script just got a lot less burdensome... LOL
