### ISSUE TITLE
Remove transparency options from find-and-replace dialog

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#843]
Hello,

as for me, the transparency options could be removed from the find-and-replace dialog and be put into the ordinary settings dialog. That would make the dialog less complex and less multi-topical.

Quite possibly, there isn't a significant number of users that don't just stick to one setting but change it a lot.

Also, if issues like ["Multiline find-and-replace"](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/563) and ["Saved Find & Replace strings"](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/452#issuecomment-128483383) get approved, the dialog would get some other GUI elements. So, cleaning up might be appropriate. (Even more issues [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/449#issuecomment-135799762).)

_Here's a thread of the official forum to track opinions about it: https://notepad-plus-plus.org/community/topic/9726/why-transparency-options-in-find-and-replace-dialog._

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
