### ISSUE TITLE
Open file from command line fails to jump to the correct line if file not already loaded

### ISSUE THREAD

**Issue by cs-hv** [notepad-plus-plus/notepad-plus-plus#8476]
### Description of the Issue

When working with Cppcheck, notepad++ is used as external editor to edit source files. Since some time, notepad++ no longer jumps to the correct line number passed by option "-n" when the affected source file is not already loaded into notepad++.
### Steps to Reproduce the Issue

1. Create a batch job (Windows .bat) calling notepad++ with a filename and a line number (option -n).
2. Execute the batch job, notepad++ will open the file but not jump to the line number passed.
3. Execute the batch job again - don't close the file before - and notepad++ will now jump to the line number passed.

### Expected Behavior

Notepad++ should always jump to the line number passed by option -n.
### Actual Behavior

The file is opened but positioned at line #1.

### Debug Information

Notepad++ v7.8.6   (32-bit)
Build time : Apr 21 2020 - 15:17:06
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.900
Plugins : GhNppExec.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Yaron10** [comment]
@cs-hv,

The problem also occurs if the file is opened in NPP but it's not the _current file_.
If you uncheck `View -> Word Wrap`, NPP does scroll to the line as expected. 

Is that correct?
***

@developers,

In `Notepad_plus.cpp`:
Before
`_pEditView->scrollPosToCenter(_pEditView->execute(SCI_GETCURRENTPOS));`
you should add
`_pEditView->_positionRestoreNeeded = false;`

It's currently accessible there. 
***
Related:

In `RunDlg.cpp`:
The line
`wsprintf(expandedStr, TEXT("%d"), lineNumber);`
should be replaced
with
`wsprintf(expandedStr, TEXT("%d"), lineNumber + 1);`

**Comment by cs-hv** [comment]
@Yaron10,

Yes, I can confirm all details in your question.

**Comment by cmeriaux** [comment]
@cs-hv  @Yaron10   I can confirm the issue. 

@yaron10 In case of wrapped buffer, **scrollPosToCenter** function calls a **scroll** that would fails because 
line wrapping is a background activity that takes time, specially for huge file. We need to set the position of the buffer, the call `_pEditView-restoreCurrentPosPreStep()` Then `restoreCurrentPosPostStep()` will be call by Notification handler once buffer is painted (NppNotification.cpp SCN_PAINTED)

I'm trying to fix this issue

**Comment by Yaron10** [comment]
@cmeriaux,

Thank you for looking into it.

If you fix it without the need to set `_pEditView->_positionRestoreNeeded = false;`, remember the line `(*_ppEditView)->_positionRestoreNeeded = false;` added in `FindReplaceDlg.cpp` for the same reason.

**Comment by cmeriaux** [comment]
@Yaron10 , @cs-hv , I've submited a PR to fix this behavior.
now the command line argument is handled.
When Wrap mode is **disabled** , the PR works like a charm. 
When Wrap mode is **enable**, in some circumstances (big file, small windows ...), the scroll action will not be accurate because `ScintillaEditView::scrollPosToCenter(size_t pos)` function must be reworked to handle the fact that line wrapping is a scintilla background activity that takes time, specially for huge file ( see 9387dcdaef19289af87f24639bf7336526d027f5 )  This would be done in another issue

@Yaron10 about the code  `(*_ppEditView)->_positionRestoreNeeded = false;` added in FindReplaceDlg.cpp, I don't understand why it compiles, because the _positionRestoreNeeded variable is private. I'm missing something. I rather not change a code that a don't understand.

**Comment by Yaron10** [comment]
@cmeriaux,

Thank you for the PR.
:+1: 

`_positionRestoreNeeded` is `protected`and `friend class Finder;`.

**Comment by Yaron10** [comment]
#8477 might be related as well.

**Comment by donho** [comment]
@Yaron10 
Thank you for the hint !

**Comment by Yaron10** [comment]
@donho,
Thank you for your work.

https://github.com/notepad-plus-plus/notepad-plus-plus/commit/4b8d83a8f882e6cd7c0acb570f871a519104e691 solves this issue but https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8477 still exists.

@cmeriaux,
Thanks again.
