### ISSUE TITLE
Reload all files

### ISSUE THREAD

**Issue by NN---** [notepad-plus-plus/notepad-plus-plus#848]
I would like to see an additional button 'Reload all' in addition for asking each file.

**Comment by Croydon** [comment]
Please implement that, it's annoying me almost daily.

**Comment by TeoTwawki** [comment]
It is insanely irritating that I can accidentally replace something in all open files when I have many files open, and then my only hope of fixing it has me using undo or reload from disc one at a time.

**Comment by emilioplatzer** [comment]
+1

**Comment by william-boatin** [comment]
Please, please please! make this so!
I also use notepad++ to open multiple log files, in the high tens. And when a modification is detected, my coworkers think I am having a mini-stroke because I am rapidly clicking reload (rapidly because anything else would drive me insane). A reload all modified files would be a live saver

**Comment by cmeriaux** [comment]
+1

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ba60fbdd715d647aa5ce7be5b6b75182b4a52951
