### ISSUE TITLE
Open target file on Drag and Drop a shortcut

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8483]
**STR:**
Create a Windows Shortcut (.lnk‬) to a text file.
Drag and drop the _Shortcut_ into Notepad++.

**Result:**
The .lnk file is opened.

**Expected Result:**
The target text file should be opened.
***
Notepad++ v7.8.3   (32-bit)
Build time : Jan 17 2020 - 18:20:02
Path : C:\---\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit) 
OS Build : 7601.23964
Plugins : ComparePlus.dll HTMLTag_unicode.dll MenuIcons.dll PythonScript.dll _CustomizeToolbar.dll

**Comment by sasumner** [comment]
Verified on 7.8.7 32-bit.
If opening a `.lnk` file via _File_ > _Open_ , however, the target file is opened correctly.
A competitor has this same issue, or at least they did 8 years or so ago: https://sublimetext.userecho.com/communities/1/topics/3233-open-lnk-files-with-drag-and-drop-on-windows-is-not-opening-the-shortcuts-target-file

**Comment by Yaron10** [comment]
:+1: 
Works as expected in Firefox and another competitor (EditPad).

**Comment by sasumner** [comment]
If the code shown [HERE](http://www.cplusplus.com/forum/windows/64088/#msg347098) is integrated into Notepad++'s [doOpen()](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/1314af7d6f88a75a2bc9f8839c0dbb676ac76b22/PowerEditor/src/NppIO.cpp#L133) function (at the top), it seems to open the target file of a .lnk file rather than the .lnk file itself.  No special check needs to be done to see if an incoming argument has a .lnk extension, as the call to `ResolveIt` fails (harmlessly) if the filename does not "resolve" into something.

Not sure if there are any negative aspects to this; any comments are appreciated.

**Comment by Ekopalypse** [comment]
It looks like this is the [recommended way](https://docs.microsoft.com/en-us/windows/win32/shell/links#resolving-a-shortcut) of doing it.

**Comment by sasumner** [comment]
>it looks like this is the recommended way of doing it.

I saw that code; the code I cited used it in a "real world" way, so I chose that to link to instead.
Plus I had lost the M$ link by the time I found the one I used.

**Comment by KnIfER** [comment]
Managed to [add](https://github.com/KnIfER/NotMad-Text-Editor/blob/6d099be471aed2e67bf086f4df19de8bc31f72a4/PowerEditor/src/NppNotification.cpp#L567) a 'Open Linked File'  option in the TabBar Context Menu. 

![output_ConvertNo 0_SchivoNo 0_SchivoNo 0_GifNo 0](https://user-images.githubusercontent.com/11593903/91630163-bde52780-ea01-11ea-9b54-6b99e2ad7180.gif)

**Comment by Yaron10** [comment]
@KnIfER,

Why would you want to open the`.lnk` file?

**Comment by KnIfER** [comment]
You mean way I want to see the raw text?

I can modify the `.lnk` file and then create relative short-cuts, which is not allowed but windows's property dialog——it think it's 'invalid'

**Comment by Yaron10** [comment]
OK. Thanks.
