### ISSUE TITLE
Feature Request: Have backups get placed in their own folder inside the backup folder

### ISSUE THREAD

**Issue by Zalerinian** [notepad-plus-plus/notepad-plus-plus#857]
Hello!

I use Notepad++ for almost all my code writing, but I one think I'd really like to have implemented is that when using backups, verbose especially, that each file has it's own sub-folder to place it's backups in. I have narrowed down that the backups are made in the nppIO.cpp file, with the fileSave method starting on line 1029 for Notepad++ 6.8.2. I did manage to modify the source code to make folder for myself, but I figured it'd be a good feature for the base program. 

For myself, I use the verbose backup feature, so I only applied the code changes there, but this is what I did:

``` c++
fn_dateTime_bak += name;
fn_dateTime_bak += TEXT("\\");
if (!::PathFileExists(fn_dateTime_bak.c_str()))
{
    ::CreateDirectory(fn_dateTime_bak.c_str(), NULL);
}
```

around line 1093. You can see it more clearly in [this screenshot](http://i.imgur.com/ogERWeN.png)

Thanks for reading!

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
