### ISSUE TITLE
 No investigation, no right to speak. 

### ISSUE THREAD

**Issue by GaaiLam** [notepad-plus-plus/notepad-plus-plus#8593]
Don HO and his followers:

Notepad++ is a powerful editor compared to notepad and you are professional programmers. However, the politic views you have expressed with the open source project is not that professional. 

Have you ever come to XinJiang or even contact with the Uyghur? How do you know the facts about Hong Kong? Just from the media which Trump call "fake news"? You always say the word "free" but you even do not know what free means. Libya, Iraq and Ukraine are "free", leaving a complete devastation and the flame of the war is still burning. George Soros, the elite of the free world, an adherent of the free market, destroy millions of families in Asia without any punishment while Hong Kong survived with the help of the central government of China. So these are so called "free"? 

Unless you have investigated a problem, you will be deprived of the right to speak on it. Isn't that too harsh? Not in the least. When you have not probed into a problem, into the present facts and its past history, and know nothing of its essentials, whatever you say about it will undoubtedly be nonsense.

You must investigate!

You must not talk nonsense!

**Comment by franklin776283** [comment]
YOU HAVE EVER INVESTIGATED?
show something rather than words?

**Comment by FranciscoPombal** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

Listen to me carefully, paid PRC shills: Emperor Winnie the Pooh and your army of mindless drones will never win as long as there are people like me who do this for free.

In the Free West, despite its many flaws, we can say whatever the fuck we want.

**Comment by ner00** [comment]
Seems that the point is lost on everyone, and this was bound to happen the moment a few confused people decided to turn Npp political: do not mix open-source and politics, that's next-level incompetence. Act out your moral and political convictions in real life, where it matters, doing so in this domain is ridiculous and only serves to create division and diversion from where the real change happens: in the field, not on some open-source software's "About" window.

**Comment by FranciscoPombal** [comment]
@ner00 

I'll say this again here:

> Not all political topics are appropriate to mix with FOSS (namely bullshit identity politics), but everything pertaining to Freedom absolutely is.

This is not just "open-source", as you are claiming. This is a Free (as in Freedom, a much stronger statement than just "OSS") software project, and thus inherently political in all matters pertaining to Freedom. The PRC hordes have the right to voice their discontent, but hey, talk shit, get hit. They will hear back from all Freedom-defending people until they learn what Freedom means.

> Act out your moral and political convictions in real life, where it matters,

This IS real-life. Or do you only use software/computers in some kind of dream-like simulation inside a stasis chamber?

> doing so in this domain is ridiculous and only serves to create division and diversion

No one needs these people who got "divided" by this pro-Freedom statement in a FOSS project. If they are so butthurt, they can always fork it. You don't need to please everyone. The message is loud, clear, logical, and desirable: ANTI-FREEDOM TROLLS, GET THE FUCK OUT OF THIS FOSS PROJECT.

> from where the real change happens: in the field, not on some open-source software's "About" window.

As if any time at all was taken away from something "more important". It probably took the author less than 30 seconds to make this change... The fact that this made so many anti-Freedom cockroaches come out of the woodwork spewing their anti-Freedom rhetoric and showing their true colors proves this was a very needed, effective, and efficient change.

**Comment by ner00** [comment]
@FranciscoPombal Firstly, watch your language, you might be under the impression that you're speaking to some of your relatives. When I said "real-life", I meant it metaphorically - you hardly bring any change by playing politics behind a keyboard, although it's plenty clear how much you think it empowers you - fantasy aside, it doesn't. You're playing politics in a place where there shouldn't be any at all. What's next on the list? Jump on the cancel-culture bandwagon? Endorsing Trump or Biden campaign on the next Npp release?

> The fact that this made so many anti-Freedom cockroaches come out of the woodwork spewing their anti-Freedom rhetoric and showing their true colors proves this was a very needed, effective, and efficient change.

This demonstrates perfectly how naïve you, and the people that intended for this to mean anything meaningful for Hongkongers, really are. You seem to be under the misguided impression that my stance is "anti-Freedom" simply because I am of the unpopular opinion that mixing politics with FOSS is a very bad idea; for the record, it's not only bad, it's stupid, immature and poorly thought through.

**Comment by FranciscoPombal** [comment]
@ner00 

> @FranciscoPombal Firstly, watch your language, you might be under the impression that you're speaking to some of your relatives.

Or what, tough guy? Here's an actual, unironic threat: if I ever see you in real life, I'll beat the fucking shit out of you until you learn what the "F" in "FOSS" stands for. You might be under the impression that people won't talk back at you in a FOSS project communication channel to defend Freedom. Guess again.

> You're playing politics in a place where there shouldn't be any at all. What's next on the list? Jump on the cancel-culture bandwagon? Endorsing Trump or Biden campaign on the next Npp release?

>You seem to be under the misguided impression that my stance is "anti-Freedom" simply because I am of the unpopular opinion that mixing politics with FOSS is a very bad idea; for the record, it's not only bad, it's stupid, immature and poorly thought through.

Retarded straw-man fallacy. I already said such politics have no place in FOSS projects, and I am against them as you are. But everything pertaining to Freedom should be addressed and defended. FOSS is inherently political in matters where Freedom is concerned. If you can't understand this, I don't know what can be done.

> When I said "real-life", I meant it metaphorically - you hardly bring any change by playing politics behind a keyboard, although it's plenty clear how much you think it empowers you - fantasy aside, it doesn't.

> This demonstrates perfectly how naïve you, and the people that intended for this to mean anything meaningful for Hongkongers, really are. 

I am well aware of the fact that, at the end of the day, some words on a piece of software won't magically solve the problem the People of Hong Kong the very next day.

But as FOSS developers, in everything that concerns Freedom, we should make every little gesture that we can to further the cause, however small it is. It is our duty to spread the message of Freedom, to fight and expose anti-Freedom agents and cast them away from our communities, online or IRL, so that pro-PRC and anti-Freedom evil doesn't take root within them. The current situation in Hong Kong is the result of everyone (mainly in the West, even) ignoring the signs for too long. To prevent a similar situation, proactive measures have to be taken from the start, on every front, including FOSS. The slippery slope is real - if you let anti-Freedom propaganda run free, today, a software project will fall, tomorrow, another country.

>  you hardly bring any change by playing politics behind a keyboard, although it's plenty clear how much you think it empowers you - fantasy aside, it doesn't.

You are doing a disservice to everyone if you don't do your due diligence of defending Freedom in a FOSS project. It's not that difficult - just a small gesture like the copy-pasta above helps. I have no illusions about the dimension and impact of my contribution, as you imply. You cannot seriously call yourself a FOSS developer if you aren't willing to fight for Freedom like that, and if you keep arguing "muh no politics in software" (ti's in the name, you smoothbrain; _Free as in Freedom_). If that's the case, go back to your "OSS BSD/MIT license" cuck tribe, where you are all free to be amoral cuck bootlicking, passively anti-(true) Freedom weaklings, look the other way, and live by your "You've got yours, and I've got mine" creed.
