### ISSUE TITLE
.nfo files default to OEM-US instead of detecting encoding

### ISSUE THREAD

**Issue by aaaxx** [notepad-plus-plus/notepad-plus-plus#860]
This is giving me a lot of grief with XBMC's .nfo files, which are encoded in UTF-8.

**Comment by tedych** [comment]
The problem with auto detecting encoding exists for other files too (5MB txt file in my case).
In my case it is 5MB UTF-8 file listing. If I shorten the file so the first UTF-8 multibyte (foreign) chars are closer to the top of the file, NP++ detects the encoding correctly, otherwise it is always ANSI with garbled characters.
Other editors open the file(s) correctly all the time. It seems NP++ is set to somehow look for UTF-8 codepoints up to a certain length in the opened file, while trying to autodetect the encoding. I already lost considerable amount of time troubleshooting a non-existing problem with my files because of that.

**Comment by aaaxx** [comment]
This is a separate issue. The files in my case are short, with UTF-8 characters appearing in the first few lines, and the encoding is detected as OEM-US, not ANSI, which would be the default fallback. Also, [Wikipedia](https://en.wikipedia.org/wiki/.nfo) mentions that .nfo files historically use [code page 437 (a.k.a. OEM-US)](https://en.wikipedia.org/wiki/Code_page_437).

All of this leads me to believe that there's a hardcoded rule in the source that tells N++ to open .nfo files as OEM-US instead of doing the actual encoding detection.

**Comment by aaaxx** [comment]
[I think I've found the cause.](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/fdf954f714325b41a86b745f3e3525277ba17ca4/PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp#L1506)

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
