### ISSUE TITLE
Unmapped shortcut keys are being consumed by Notepad++

### ISSUE THREAD

**Issue by boinka** [notepad-plus-plus/notepad-plus-plus#8607]
### Description of the Issue
When using a shortcut key mapped in autohotkey, but not mapped in Notepad++, while Notepad++ has focus, the shortcut key is consumed by Notepad++ and not passed to the autohotkey script.

### Steps to Reproduce the Issue
1. map ctrl-alt-shift-1 to some action in autohotkey
2. verify ctrl-alt-shift-1 is not mapped in Notepad++ shortcut mapper nor in any menu
3. focus Notepad++ and press ctrl-alt-shift-1
4. the autohotkey action does not occur

### Expected Behavior
the autohotkey action should occur

### Actual Behavior
nothing

### Debug Information
Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1803
OS Build : 17134.1610
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppTextFX.dll

**Comment by Ekopalypse** [comment]
Isn't that normal windows application behavior? Doesn't this happen too if, for example, MS Notepad is used?

**Comment by boinka** [comment]
Nope, normal windows app behavior is to pass keystrokes out to the OS that aren't mapped in the application, i.e., not to consume the keystroke.

    On Friday, July 24, 2020, 6:10:49 AM MDT, Ekopalypse <notifications@github.com> wrote:  
 
 


Isn't that normal windows application behavior? Doesn't this happen too if, for example, MS Notepad is used?

**Comment by boinka** [comment]
Sorry, just discovered that this is a quirk on my installation - my windows user is non-administrator, but my Notepad++ is apparently always running as a full administrator, which means the keystrokes cannot be passed out to my windows explorer shell.  False alarm, and profuse apologies.
-boinka

    On Friday, July 24, 2020, 6:10:49 AM MDT, Ekopalypse <notifications@github.com> wrote:  
 
 


Isn't that normal windows application behavior? Doesn't this happen too if, for example, MS Notepad is used?

**Comment by Ekopalypse** [comment]
> Nope, normal windows app behavior is to pass keystrokes out to the OS that aren't mapped in the application, i.e., not to consume the keystroke.

No, that's not what applications do.
Metaphorically speaking, Windows creates a message queue for each application when it starts and puts the messages intended for that application in that queue. The application has the duty to process these messages and does this with GetMessage, TranslateMessage and DispatchMessage. That's it, nothing is returned to the system.

What you probably mean has nothing to do with shortcuts or accelerators but with HotKeys.
It is so that Windows keeps a global table with key combinations, which, under certain circumstances, can be changed by an application if this combination is also contained in their accelerator table. If this is not the case, i.e. the application does not have this key combination, then the application does not know anything about it because it is directly forwarded to the recipient and not, as you assume, through Npp.
