### ISSUE TITLE
Allow plugins to retrieve settings directory.

### ISSUE THREAD

**Issue by sanastasiou** [notepad-plus-plus/notepad-plus-plus#862]
That's a feature request, I guess, which I will happily implement myself.

With release 6.8.3 the shortcuts.xml file is being properly updated during runtime, which allows plugin developers to implement shortcuts for their own languages and also allows them to use a modified shortcut in case a user changes the default settings.

This work, as long as the user does not use any cloud settings. In that case, the default shortcuts.xml is not updated, rather the one under the cloud directory is.

To overcome this, I've introduced another message, NPPM_GETSETTINGSDIR which retrieves the actual settings directory.

I reckon, this might be useful for many other features as well since all relevant settings are placed under this directory.

**Comment by cmeriaux** [comment]
Hello @sanastasiou,
You may have misunderstood the  4fc06e2bc196da8f1d2ee056e422d80d3744c2c2 .  The shortcuts.xml file isn't updated during runtime. Don Ho refused my PR. Here is the actual behavior : 

1.  shortcuts.xml is updated during closure
2. when user didn't change any shortcut, the shortcuts.xml isn't updated.

**Comment by sanastasiou** [comment]
@cmeriaux Even so, this PR is useful. The shortcuts would then be actual after a notepad++ restart. Currently this is not possible when the user is using cloud settings.

**Comment by jamesford42** [comment]
Note: Microsoft has a 3 gig download of all the visual studio icons available for free somewhere. They might have a more professional look than these icons.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
