### ISSUE TITLE
Backup not working as expected

### ISSUE THREAD

**Issue by KlausWilly** [notepad-plus-plus/notepad-plus-plus#8628]
As far as i understand your description it is possible to have Backups with Timestamp in the same Directory where the File exists.

I read in the OnlineUserhelpfile  `https://npp-user-manual.org/docs/preferences/` about Backup and found:
> Backup on save
   **Verbose backup**: it will save a copy of the file, with a date-and-timestamp added to the filename as well as the .bak extension.
     if no Custom Backup Directory is defined, it will save it in `.\nppBackup\ subdirectory` of the file’s current directory, so 
    `c:\path\to\file.txt` will create a backup `c:\path\to\nppBackup\file.txt.yyyy-mm-dd_hhmmss.bak`
> **Custom Backup Directory**: leave blank to put the backup in the same directory as the file; set to a directory to have all files backed up to one directory

I have done so, but i don't reach the described result.
Saving a File gives allways:  `.\nppbackup\filename.ext.DateTime`
This behaviour i would expect if their is **NO mark** in the Box for _Custom Backup Directory_

But I am sure the box for _Custom Backup Directory_ is marked and nothing is in the Textfield. 

Maybe their is a Problem ?

I use NPP 7.8.9 32-Bit in Portablemode with following Plugins
> Compare
HexEditor
NppTextFX
> TopMost

Thanks a Lot for this very fine Editor.

Greetings from Germany 
Klaus

**Comment by alankilborn** [comment]
>As far as i understand your description it is possible to have Backups with Timestamp in the same Directory where the File exists.

This is only possible for "Simple" backup, not "Verbose" backup.
"Simple" generates at most ONE extra file for the backup, ever, a file that is backed up.
Because "Verbose" generates an extra file EVERY TIME a file to be backed up is saved, it is judged to be too overwhelming/annoying to have these files be in the same folder as the original file.

Relevant section of the user manual: https://npp-user-manual.org/docs/preferences/#backup

Recommend CLOSURE of this item.

**Comment by KWRuppert** [comment]
Hello 
OK, everything good
