### ISSUE TITLE
Feature request: automatically propose "new 2.txt" instead of "new 1.txt" if "new 1.txt" already exists in folder

### ISSUE THREAD

**Issue by notepaddo** [notepad-plus-plus/notepad-plus-plus#864]
I often write new notes by opening Notepad++ e saving them on my desktop.
When I close Notepad++ and something needs to be saved, it asks me if I want to save it and it suggests "new 1.txt" as a default name.
It would be very useful for me if Notepad++, before suggesting "new 1.txt", would check if a file with this name already exists in the folder and, if so, would suggest "new 2.txt" (or "new 3.txt" if "new 2.txt" already exists, and so on). At present I often need to manually correct manually the suggested default name.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
