### ISSUE TITLE
Link is "hover-highlighted" when it's not hovered 

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8647]
**STR:**
Have a link at the first visible line (or simply paste a link into a new file).
Hover over the link and move the mouse up to the toolbars.

**Result:**
The link is still "hover-highlighted".
***
Notepad++ v7.8.9   (32-bit)
Build time : Jul 23 2020 - 22:44:42
Path : C:\---\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit) 
OS Build : 7601.23964
Current ANSI codepage : 1255
Plugins : ComparePlus.dll HTMLTag_unicode.dll MenuIcons.dll PythonScript.dll _CustomizeToolbar.dll

**Comment by Yaron10** [comment]
Fixed with the latest commit in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8641.
:+1: 

There still are two minor issues:

**1.**
Have a link at line 1 and another link at line 2.
Left-click the Line-Margin on line 1 (> line 1 is selected).

Result:
The link in line 2 is "hover-highlighted".

**2.**
Have a link at line 1 and another link at line 2.
Left-click the Line-Margin on line 1 (> line 1 is selected).
Move the cursor away to remove the "hover-state" from line 2.
Hover over line 2 and move up to line 1.

Result:
The link in line 2 is "hover-highlighted".

**The second issue existed in older NPP versions as well.**

**Comment by Uhf7** [comment]
Thank you for testing. I think both new issues can be observed in the current version 7.8.9 too. I would describe them as follows:

The first effect is: If a line is selected by a mouse click to the margin (URL or not doesn't matter), and the line below the selected line starts with an URL, then this URL is displayed in hovered style. An explanation for this seems to be, that the hovered style is also applied, if the text cursor is moved into the URL using the keyboard arrow keys. And Scintilla acts here as if the text cursor was moved to the beginning of the URL by keyboard.

The second effect is: If a selection begins or ends immediately after/before an URL, and the mouse cursor is moved from the URL to the selection, then the display style of the URL remains hovered, until the mouse cursor leaves the selection. I don't think I have an explanation for this today.

**Comment by Yaron10** [comment]
> I think both newly mentioned effects can be observed in the current version 7.8.9 too.

Correct. I just mentioned that the second issue existed in older NPP versions as well.

> The first effect is: If a line is selected by a mouse click to the margin (URL or not doesn't matter), and the line below the selected line starts with an URL, then this URL is displayed in hovered style. An explanation for this seems to be, that the hovered style is also applied, if the text cursor is moved into the URL using the keyboard arrow keys. And Scintilla acts here as if the text cursor was moved to the beginning of the URL by keyboard.

:+1: 

> The second effect is: If a selection begins or ends immediately after/before an URL, and the mouse cursor is moved from the URL to the selection, then the display style of the URL remains hovered, until the mouse cursor leaves the selection. I don't think I have an explanation for this today.

Should I close this issue? Or do you want to further investigate it?

Thank you.

**Comment by Uhf7** [comment]
@Yaron10 

I produced new artifacts for testing:
Debug 32 Bit: https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/34415032/job/03kgrg6thp38iuyd/artifacts
Debug 64 Bit: https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/34415032/job/n3etxf7768l2975r/artifacts
They should solve the two effects you mentioned last. 

You need both, `Notepad++.exe` and `SciLexer.dll`. The modifications are in the `SciLexer.dll` only, but make sure, that both binaries fit together.

The 1st effect is solved by preventing hovered style after margin clicks at all, because if the margin is clicked, the mouse cursor cannot be hovering over an URL.

The 2nd effect was surprisingly easy to see in the Scintilla code, and is still hard to describe (for me, today). So I keep my promise not to explain it today. I will have to do this anyway, when I create the Scintilla ticket, which I will do only, if
- You test it and say it is OK
- No one else comes and tests or sees it and says it's not OK
- The current Scintilla ticket 2193 addressing the hovered style after leaving the window is accepted or rejected.

**Comment by Yaron10** [comment]
Both issues are fixed. Well done. :+1: 

> And, of course, you cannot click the margin with the keyboard, hopefully

Well, you can select a line + EOL with a script. :)

Thank you.
