### ISSUE TITLE
freedom of speech, freedom of ideas

### ISSUE THREAD

**Issue by 365670123** [notepad-plus-plus/notepad-plus-plus#8648]
You have the freedom of speech, you can say China is the hell on earth, people are prisoned by dictator.

I have the freedom of speech, I can say you are a liar, you didn't tell the truth.

It is not a problem of freedom or democracy. It is a war of fighting for living space.

Free Uyghur, Stand with Hong Kong or whatever you like, it doesn't matter. China will be stronger, our lives will be better, your screams will be louder and louder.

**Comment by ccuser44** [comment]
Wumao are losers sponsored by the chinese government to spread misinformation and basically jerk eachother off in their little echo chambers. They are some of the goofiest people on the interent and tend to give off "small dick energy" because of their hilarious arguments and insults, as they are typically copied directly from google translate. They are the fungus that grow on uncleaned public toilets.

Wumao: Hi, I am 33 years old and unemployed. I never had a gf and I smell like sewage but that's ok because I get all the sweet honey I need from the great leader, Winnie the Pooh
