### ISSUE TITLE
NPP jumps from "New 1" to "New 3" if "Find Results" is displayed

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8677]
**STR:**
Open NPP (for simplifying the case: no session, `New 1` is open).
Open the Find dialog and press `Find All in Current Document`.
-- The `Find Results` window is displayed.
Open a new file.

**Result:**
`New 3` is opened instead of `New 2`.

(The same happens if you open Python Script console).

**Apparently a minor issue, but https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8461 might be related.** 

***
Notepad++ v7.8.9   (32-bit)
Build time : Aug  1 2020 - 16:33:01
Path : C:\---\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit) 
OS Build : 7601.23964
Current ANSI codepage : 1255
Plugins : ComparePlus.dll HTMLTag_unicode.dll MenuIcons.dll PythonScript.dll _CustomizeToolbar.dll

**Comment by sasumner** [comment]
@Yaron10 Haha, you are trying to refocus our attention on 8461. :-)

I don't know if user's have a right to complain about this one.
N++ developers can name temporary files anything they want. :-)

But yes, point taken.  This has (somewhat) bothered me as a user from day # 1 of my N++ usage.

**Comment by Yaron10** [comment]
> Haha, you are trying to refocus our attention on 8461.

To a certain degree. :)

> I don't know if user's have a right to complain about this one.
N++ developers can name temporary files anything they want. :-)

That's correct. I have opened the issue because of the possible relation to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8461.

> But yes, point taken. This has (somewhat) bothered me as a user from day # 1 of my N++ usage.

I've encountered the apparently random numbers many times before. But, again, `Find Results` and https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8461...

**Comment by Yaron10** [comment]
> Haha, you are trying to refocus our attention on 8461.

To a certain degree. :)

> I don't know if user's have a right to complain about this one.
N++ developers can name temporary files anything they want. :-)

That's correct. I have opened the issue because of the possible relation to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8461.

> But yes, point taken. This has (somewhat) bothered me as a user from day # 1 of my N++ usage.

I've encountered the apparently random numbers many times before. But, again, `Find Results` and https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8461...

**Comment by Esco441-91** [comment]
Hello, 

I checked upon this issue because I wanted to learn contributing to open source (this could be my first contribution! :) ). I found the reason for the bug and fixed it. Just as @Yaron10 mentioned, It relates to addressing the Find Results -window as an "unnamed document" and is then checked from list of buffers that such exists. This results to having +1 unnamed documents. 

I actually missed the part in "How to contribute" where it says I should be assigned this issue before working on it, but oh well :) As I am new to open source and contributing to NPP, could someone let me know if I can create a PR on the issue? Thanks :)

**Comment by sasumner** [comment]
@Esco441-91 
You (or anyone) can attempt a PR for it.  "Assigning" to non-team members is problematic as it is unknown if there will be follow-through on it.

**Comment by Yaron10** [comment]
@Esco441-91,

Looking forward to your PR. :+1:

**Comment by Esco441-91** [comment]
@Yaron10,

Now you're making me nervous for the expectation :D

I'll make the PR tomorrow when I get back to my work computer.

**Comment by Yaron10** [comment]
@Esco441-91,

We'll treat you and your PR with the utmost respect. :)

**Comment by Esco441-91** [comment]
I now created the PR. Let's see how it'll turn up :)

**Comment by Esco441-91** [comment]
Here's an update on my findings, if anyone else wants to try. I'm not sure if I have the terminlogy correct, but when I say window, I mean anything user can see that he can type into or interact with.

The reason why this occurs is because other windowss, like `Find Results` and `Python Console` are treated and initialized just like any other document. Upon initialization, all document buffers, hidden windows and those mentioned above are marked as unnamed (DOC_UNNAMED). Whereas named documents are renamed after creation or changed, hidden, unnamed documents and other windows are not. Hidden windows are fine because their usage is different. 

I was able to create a new way to distinguish `Find Results` (because it's all inside NPP source) from the other document buffers, but I didn't find a way to do distinction to buffers initialized by plugins. Worse, it seemed impossible to me to dinstinquish, whether the plugin opens an actual document or an utility window like the `Python Console`. Though impossible to me might be trivial to someone else :)

I think one way to fix this, while keeping backwards compatibility with plugins, would be to make a better distinction on what is a user document and what is not. But if I am correct, it can't be done without marking user documents as something else, because plugin windows and others cannot be marked as anything else without changing their sources. This means that whenever we want to open an actual user document, that would have to be marked as something else. But concidering it can happen from atleast opening a new session, loading an old session or just opening a new document, I don't think I can find the right functions to do this in.

**Comment by Yaron10** [comment]
@Esco441-91,

Thank you for further investigating it and updating. I think it'll be helpful.

**Comment by bzaugt** [comment]
Same problem occurs with "Document Map" (View -> Document Map)
Version info:
- Notepad++ v7.9.5   (32-bit)
- Build time : Mar 21 2021 - 02:09:07
- OS Name : Windows 10 Enterprise (64-bit) 
- OS Version : 2009
- OS Build : 19044.1706
- Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppEditorConfig.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll XMLTools.dll

**Comment by donho** [comment]
891e8f936e03586b0bbf2850523a4af72701f622
