### ISSUE TITLE
Add keyboard shortcuts for switching to Project Panels, Folder as Workspace and Function List

### ISSUE THREAD

**Issue by Uhf7** [notepad-plus-plus/notepad-plus-plus#8719]
I would like to add user-definable keyboard shortcuts for the following functions:

- Switch to Project Panel 1
- Switch to Project Panel 2
- Switch to Project Panel 3
- Switch to Folder as Workspace
- Switch to Function List

In the View menu, this panels can be turned on and off, there is a checkmark beside them, while they are turned on.
The keyboard shortcuts for this (toggling) menu commands are already there too.

Now I want to add keyboard shortcuts, which can be used to switch the focus to this panels without mouse. This keyboard shortcuts are not needed/useless in the menu.

**Comment by donho** [comment]
A quick and rough spec needs to be talked here:

For all docking panels, there are 3 main actions for managing the window:
1. Launch it 
2. Switch it
3. Close it

I see the intention is use the same commands `A` for togging (launch & close) and the invisible commands`B` for switching.
My question is, what it happens if a panel isn't launched yet (for example "Function List"), but the user trigger the shortcut of `B`?

**Comment by donho** [comment]
So AFAICT, `A` is done for all the docking panels, you want to implement `B`, and they are shown only in Shortcut Mapper.
Do you confirm?

How about for Document Map ?

**Comment by Uhf7** [comment]
Yes, I confirm, the `A` commands are already there, and the `B` commands are only needed as keyboard shortcuts. From the menu, the `A` commands can be used.

And I left out the Document Map, because this can only be used with the mouse, so there should be no need to switch the keyboard input focus to it with a keyboard shortcut.
