### ISSUE TITLE
Turkish character problem (only two characters)

### ISSUE THREAD

**Issue by SkyDncr** [notepad-plus-plus/notepad-plus-plus#875]
Thanks for this awesome editor. There is a very little bug about two Turkish characters;
i am writing my own codes as c++ and i am using ansi character code encoding for some reasons.
There is no problem except when i using "ç" character after "ö" (i don't know if you will see these two characters in here).
i mean;
- i wrote öç text in any file at ansi encoding
- i saved my file
- i closed and reopened it
- then my character encoding automatically changed (i don't know which encoding) and all my Turkish characters in this file changed.

**Comment by Tmp341** [comment]
You can't use unicode characters as a ansi character. I mean, try using utf-8 encoding and see if they are problematic.

**Comment by SkyDncr** [comment]
i can use utf-8 but in c++ mode i am using ansi (with server communications.)

**Comment by SkyDncr** [comment]
231 and 246 ascii tabled characters i mean.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
