### ISSUE TITLE
[Feature Request] Option to remove old search results from Find-result window when doing a new search

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8777]
There as been a user request to clear out any prior-search results from the _Find result_ window when a new search that writes output to that window is initiated.

See https://community.notepad-plus-plus.org/topic/19850/setting-to-clear-previous-search-results-before-files-search

This seems to be a reasonable idea, as a subsequent right-click menu _Open All_ can easily (and unintentionally) open many more documents than the user truly needs/wants (this was pointed out by a different user in the above Community thread).

### Debug Information
Feature request based on behavior current to N++ version 7.8.9.

**Comment by sasumner** [comment]
Some questions, for anyone that cares to answer:

* Is this better fulfilled as a _Preference_ choice setting, or as a right-click option choice in the _Find result_ window's context menu?  Both of these ways would be "remembered".   Example UI text for either could be: _Clear old results when running new search_

* Keying on the _Open all_ point made above, would it be better to NOT implement this issue's core idea (allowing automatic clearing), and simply have an additional context menu entry _Open all from most-recent search_, or possibly _Open all from uncollapsed searches_ ?

**Comment by Yaron10** [comment]
The user might want to change this setting several times in one session. - Not suitable for the `Preferences` dialog.
`Open all from most-recent search` would not solve the clutter issue the OP in the forum mentioned.

The `Find Results` window may be hidden when a new search is initiated.
So, ideally it should be in the `Find` dialog (as implemented in MS VS).

But the `Find` dialog is too large and dense as it is. Would it be reasonably possible to squeeze in another setting without implementing `Show More/Less`?

`Clear old results when running new search` in the `Find results` window's context menu is not bad.
But not ideal IMO.

**Comment by Ekopalypse** [comment]
If this feature, "delete previous search result" should be implemented, then I would expect it in the "Find in Files Dialog", 
because the dialog is already open at any time this feature would be needed. Preference feature wouldn't be as nice.

Yes, a context menu option, to open only the all files from the last search, would be an alternative.
And as more as I think about it, I would prefer the context menu solution.

**Comment by sasumner** [comment]
@Yaron10 said:

>The user might want to change this setting several times in one session. - Not suitable for the Preferences dialog.

Agreed -- removing _Preferences_ from consideration.

>Open all from most-recent search would not solve the clutter issue the OP in the forum mentioned.

True, but I tend to agree that the primary mechanism for "clutter removal" is the collapsing of the old searches.
We're not necessarily out to implement _exact_ requests from single users, but to migrate a bit toward some general enhancements useful to "many". :-)

>Clear old results when running new search in the Find results window's context menu is not bad.

I'm leaning toward agreement.

>But the Find Results window may be hidden when a new search is initiated.

Yes, but it could be acceptable that if you'd want to change this option, you'd have to make it shown first.  I don't think it is something one would change constantly.

>So, ideally it should be in the Find dialog (as implemented in MS VS).

I think it would be hard to "sell" that.
It applies only to searches that output to _Find result_ and that would (somehow) have to be made clear in the UI.

>implementing Show More/Less

Also a "hard sell".

**Comment by sasumner** [comment]
@Ekopalypse said:

>Yes, a context menu option, to open only all files from the last search, would be an alternative. And as more as I think about it, I would prefer the context menu solution.

I can't tell if you mean only one context menu option ("open only...") or maybe that plus a second one ("clear output before new search").

Don't get hung up on proposed verbage; I have thought too much about that, just trying to convey the meaning for fleshing out the (possible) feature(s).

**Comment by Ekopalypse** [comment]
Yes, I wasn't very clear at this one.
Is there a benefit of clearing the find result window other than avoiding to open unnecessary files?
I mean, a new search collapses the previous result so I don't see any cluttering in here.
For me, only one additional context menu action to open all files from the most recent search would be beneficial.
Apart from that there is nothing I need additionally.

**Comment by Yaron10** [comment]
> We're not necessarily out to implement exact requests from single users, but to migrate a bit toward some general enhancements useful to "many".

Currently you have the `Clear All` option. 
I believe the "clutter removal" would be useful to *most users* who might be interested in the new setting.
Implementing it without "clutter removal" would be a waist/bloat IMO.

> Yes, but it could be acceptable that if you'd want to change this option, you'd have to make it shown first. I don't think it is something one would change constantly.

One might want to change it on each new search (from my personal experience).

> It applies only to searches that output to Find result and that would (somehow) have to be made clear in the UI.

It should only be shown in the `Find` and `Find in Files` tabs.

**Comment by Yaron10** [comment]
> Is there a benefit of clearing the find result window other than avoiding to open unnecessary files?

I think that "clutter removal" could be useful to many regardless of opening files.

I can also think of a case you would *not* want to clear the old results, but still want to open only the last search files. :)

**Comment by sasumner** [comment]
>Is there a benefit of clearing the find result window other than avoiding to open unnecessary files? I mean, a new search collapses the previous result so I don't see any cluttering in here.

I tend to agree, but one user (Community posting) had a brain that saw collapsed searches as "clutter".  :-)

>For me, only one additional context menu action to open all files from the most recent search would be beneficial.

I might be inclined to go with "all uncollapsed" rather than "most recent" here.  By default, this would cover only the most-recent, but if user wanted to uncollapse addtionally some earlier search(es) to open files from, it would also work.

**Comment by sasumner** [comment]
@Yaron10 said

>One might want to change it on each new search (from my personal experience).

This seems like a _stretch_ to me.  But that's just me.

**Comment by Ekopalypse** [comment]
Most of the time I use find in files to see if there is a difference before and after file modifications hence I need the "history".
But I don't mind if there is an option to clear the "history" either. (but only in the dialog)  :-)

**Comment by sasumner** [comment]
@Ekopalypse said

>But I don't mind if there is an option to clear the "history" either.

Not sure I understand this as _Find result_ already has _Clear all_ context menu action.
This issue is discussing an automated pre-clear, but I'm sure you understand that fully.
Hence my confusion.

> (but only in the dialog)

I think changes to the Find family of tabs itself is the "hard sell" I mentioned earlier.
As the issue under discussion is really a very minor thing, I can't see it driving a change to the main Find interface.

**Comment by Ekopalypse** [comment]
The request to automatically delete a previously found search result is nothing I need but in case the feature/option should be implemented I see its advantage only in the find dialog. If it is hard sell and I can see it might be, then, personally, I would not offer it because as @Yaron10 said, if you have such an option one might want to use it and then it is annoying to either always click in the search result window first and set the option or open a preference dialog and reset the option. It's like selling a car with 12 cylinders but allowing the drivers to use only 6 per default and if they want to change it, then they have to open the hood and recable stuff. :-) 
Just my opinion.
The only advantage for me is an additional "open all ..." feature in the context menu of the find in result window.
I tend towards your recommendation to "all uncollapsed" - gives even more flexability.

**Comment by sasumner** [comment]
>if you have such an option one might want to use it

Indeed.  LOL

**Comment by KnIfER** [comment]
What about another menu option : 'Open All  (Last Search) '
Ah...someone has already mention it

Then What about  ctrl-click on the 'find button' to first clear existing results and then launch search?
This way 'ctrl' stansds for 'clear', seems to make sense !

**Comment by Yaron10** [comment]
> Then how about enabling ctrl-click on the 'find button' to first clear existing results and then launch search?

It seems the best solution.
The OP in the forum requested a permanent setting, but I think that `Ctrl+Find` would be useful to most users.
(The `Open All (Last Search)` is a separate issue/request). 

Now you can add a setting in `Preferences` as to the default `Find` (without `Ctrl`) behavior.
I'm kidding!

**Comment by sasumner** [comment]
I don't know how to feel about a Ctrl+button action.
It certainly isn't obvious (user would have to have prior knowledge) -- no UI hints, although I suppose a tooltip...
And I don't know how @donho would feel about such a thing.

If we are considering this, we don't need an `Open all (last search)`...just use the existing `Open all` and hold Ctrl while doing it (I actually mentally considered this BEFORE anyone brought up the Ctrl modifier idea). :-)

**Comment by Yaron10** [comment]
> It certainly isn't obvious (user would have to have prior knowledge)

Isn't that common in many applications?

> although I suppose a tooltip...

I thought about that too. Necessary? - I don't know.

> just use the existing Open all and hold Ctrl while doing it 

:+1: 
That's very nice. I did NOT think about that but I should have! :)

**Comment by sasumner** [comment]
If Ctrl+buttons in the Find dialog is a viable thing, then I would have
solved issue 8527 differently. :-)

**Comment by Uhf7** [comment]
What I would expect, is slightly different from this discussion. I would expect, that every find command opens its own Find Results tab, which is activated after the Find command. So I deal with only one find result after each find command, without loosing the old ones.

And I would expect, that the find results get numbers to identify them, "1" for the 1st find result, "2" for the second, and so on, so that I can refer to the results later.

And I would expect, that the caption of the docking window showing the find results, contains more or less detailed information about the find command done, like "Find Results 1: Find 'abc' in all opened documents", or "Find Results 7: Find 'xyz' in Find Results 3".

And I would expect, that on closing a Find Results tab, dependencies are checked, so that, when I close "Find Results 3: Find 'uvw' in all opened documents", then the "Find Results 7: Find 'xyz' in Find Results 3" tab is closed with it, because "Find Results 7" become meaningless without "Find Results 3" in this example.

Only a thought, but I say, think big here. First step could be indeed an option, whether to open a new Find Results tab for each Find command or not, and from this point on, it could be improved later.

**Comment by sasumner** [comment]
@Uhf7 's comments are maybe along the lines of #8235 but amplified a whole bunch.  :-)

**Comment by Yaron10** [comment]
@sasumner,

> If Ctrl+buttons in the Find dialog is a viable thing, then I would have solved issue 8527 differently.

1. That's correct.
2. Those who found the confirmation dialog interruptive, would not like the modifier either.
In our case the modifier spares more actions.
3. A setting would be better here too but it's a "hard sell".

***

@Uhf7,

> I would expect, that every find command opens its own Find Results tab, which is activated after the Find command. So I deal with only one find result after each find command, without loosing the old ones.

:+1: 
I assume it should be optional.

> And I would expect, that the caption of the docking window showing the find results, contains more or less detailed information about the find command done, like "Find Results 1: Find 'abc' in all opened documents", or "Find Results 7: Find 'xyz' in Find Results 3".

:+1:

> because "Find Results 7" become meaningless without "Find Results 3" in this example.

Is that always the case? Can't you close "Find Results 3" and still be interested in `xyz`?

**Comment by sasumner** [comment]
>Those who found the confirmation dialog interruptive, would not like the modifier either.
In our case the modifier spares more actions.

Off-topic but I started it, so...  :-)
I would have said "too bad" to those that didn't like having to add the modifier to avoid the prompt.

>Can't you close "Find Results 3" and still be interested in xyz?

I agree with this.  Maybe not always you'd be interested, but I can see certainly sometimes.

**Comment by Uhf7** [comment]
> Can't you close "Find Results 3" and still be interested in xyz?

Be interested, sure, but the find results would loose their history, because they would be labeled "Find Results 7: Find 'xyz' in Find Results 3", and if the "Find Results 3" don't exist anymore, you cannot trace how it came to the "Find Results 7".

That leads me to another thought: Currently, any new Find command adds it's results to the main Find Results panel, while each "Find in Find Results" opens a new Find Results panel. If this would be the opposite, it may become easier: Each new Find command should open a new Find Results panel, and the results of a "Find in Find Results" should be added to the Find Results panel where the "Find in Find Results" has been started from. This would have the advantage, that all find results only restricting previous find results are together in one Find Results panel. Then, any Find Results panel could be closed without caring about dependencies.

**Comment by sasumner** [comment]
>Be interested, sure, but the find results would loose their history, because they would be labeled "Find Results 7: Find 'xyz' in Find Results 3", and if the "Find Results 3" don't exist anymore, you cannot trace how it came to the "Find Results 7".

Well, that presumes that your idea for the captioning of the windows was adopted.  Then, yes I agree.
But, I don't know that "FR 3" or "FR 7" conveys much that is meaningful.  It might be better to see the search term rather than a number in the caption.  I realize that you could then end up with multiple windows with the same title (same search term).

>That leads me to another thought...

Interesting.  Thank you for sharing.

**Comment by Uhf7** [comment]
> I don't know that "FR 3" or "FR 7" conveys much that is meaningful.

It does convey a reference number for the search. And the complete headline, as I wrote, should be: "Find Results 3: Find 'uvw' in all opened documents" or "Find Results 7: Find 'xyz' in Find Results 3". 

The reference number is to prevent creating headlines like: "Find 'xyz' in (Find 'uvw' in all opened documents)", which would lead to unreadable cascades after some searches in the results of the results.

And I also imagined, that it would be possible or easy to write this number on the switching tab below the Find Results panel, so that a referred Find Results panel can be found easily.

**Comment by Yaron10** [comment]
> Be interested, sure, but the find results would loose their history, because they would be labeled "Find Results 7: Find 'xyz' in Find Results 3", and if the "Find Results 3" don't exist anymore, you cannot trace how it came to the "Find Results 7".

So, `Shift + Close` closes dependencies. :) 

> That leads me to another thought: Currently, any new Find command adds it's results to the main Find Results panel, while each "Find in Find Results" opens a new Find Results panel...

Another interesting and good idea. :+1:

**Comment by ArkadiuszMichalski** [comment]
@sasumner 

> @Ekopalypse said
> 
> Is there a benefit of clearing the find result window other than avoiding to open unnecessary files? I mean, a new search collapses the previous result so I don't see any cluttering in here.
> 
> I tend to agree, but one user (Community posting) had a brain that saw collapsed searches as "clutter". :-)

So there are already two people like that:)  Sometimes I accidentally click on older results and it bothers me. When the previous result was long, I have to do some extra work to get to the right one. When I don't need previous results then I shouldn't worry about such things. Usually, after searching, I want to have only what is up-to-date, not what was before.

**Comment by sasumner** [comment]
As I said in 9641, I'll implement something on this, but I'll keep it simple and on-topic to this issue.  I have kind of a different idea for how it might work in the UI, but I think it is good.
