### ISSUE TITLE
Allow defining a second keyboard shortcut for "Close document"

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#879]
Windows usually lets you close documents with Ctrl+F4. Linux applications mostly use Ctrl+W. I'm used to both and they could well be used here simultaneously. Notepad++ only lets me define a single shortcut for each function. Recording a macro that would do it is not possible.

**Comment by BobStein** [comment]
:+1:

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by ygoe** [comment]
@MetaChuh Not fixed, still highly annoying every day! Please reopen and assign a priority so that it isn't forgotten about again for the next 3.5 years.

**Comment by sasumner** [comment]
It is sort of a pain when one feels it should be in the standard product, but a second (third, etc) keycombo can be added to functions via scripting as a workaround.  I think the burden of creating a whole scheme to the shortcut-mapper for handling this kind of thing natively is going to be too big for N++ developers to ever take it on.
