### ISSUE TITLE
File closed in second view not removed from Document List panel (aka Doc Switcher)

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8800]
### Steps to Reproduce the Issue (STR)

1. Start with "new 1" as the only N++ tab (from a fresh install or portable version unzip)
2. _Show_ the _Document List Panel_ by ticking the box in _Preferences_ > _General_; observe new docked window titled _Doc Switcher_ appears
3. Create new tab with Ctrl+n; now have "new 2" in addition to "new 1"; observe _Doc Switcher_ window looks like this:
![image](https://user-images.githubusercontent.com/30118311/92026071-724aba80-ed2e-11ea-9a7b-39923ee9d9cd.png)
4. Right-click "new 2" tab and choose Move to Other View from the menu that appears
5. Close "new 2" via the `x` on its tab

### Expected Behavior

I expect the _Doc Switcher_ window to only contain the "new 1" file because "new 2" is closed and forgotten about.
"new 2" should be removed from _Doc Switcher_.

### Actual Behavior

_Doc Switcher_ window contains both "new 1" and (the now-closed) "new 2":
![image](https://user-images.githubusercontent.com/30118311/92026260-c05fbe00-ed2e-11ea-9244-b3f21a030884.png)

### Debug Information
Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\\.................\npp.7.8.9.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1339
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PythonScript.dll 

### Additional

This bug discovered when evaluating PR 8721 ; see here:  https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8721#pullrequestreview-481054114

**Comment by Yaron10** [comment]
The cause of this problem is in `bool Notepad_plus::removeBufferFromView(BufferID id, int whichOne)`.

```
	//Cannot close doc if last and clean
	if (tabToClose->nbItem() == 1)
	{
		if (!buf->isDirty() && buf->isUntitled())
		{
			return false;
		}
	}
```

Apparently, in Double-View mode "last and clean" can be closed.
So `if (!buf->isDirty() && buf->isUntitled() && !bothActive())` should fix this issue.

But then in the **STR** above, a new file is created in the closed view (`BufferID newID = MainFileManager.newEmptyDocument();` in `removeBufferFromView()`.
And the behavior in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8697 (**without https://github.com/notepad-plus-plus/notepad-plus-plus/commit/7c7dcd8fccdddceacc05ee0fd4cf75e22165d439**) changes: a "new 3" is displayed in the "Windows" window. 

Properly fixing *both issues* requires some further investigating and work.

**Comment by Roshni-P** [comment]
Well, not sure if I have understood things correctly.

I tested the scenarios mentioned in Issues 8800 & 8697 with my fix and they seem to work correctly.
Is it that my fix is not logically correct & the code change needs to be done in Notepad_plus::removeBufferFromView function?

**Comment by Yaron10** [comment]
Currently the `new 2` buffer remains in the closed view and therefore it's not removed from the `Doc Switcher`.

Replacing
`if (!buf->isDirty() && buf->isUntitled())`
with
`if (!buf->isDirty() && buf->isUntitled() && !bothActive())`

-- the `new 2` buffer is removed from the closed view, consequently removed from the `Doc Switcher` as well and the issue here is fixed.

The downside is that `new 2` is replaced by `new 3` in the closed view which means some "extra work".

The correct approach requires a better understanding of the buffers structure.
