### ISSUE TITLE
New file default save as type

### ISSUE THREAD

**Issue by jairocontreras** [notepad-plus-plus/notepad-plus-plus#8866]
i would like the save as dialog to have Save as type: All types (`*.*`) as default for new files when normal text is the default language. that way i can type in whatever extension i want to save the file as, for example, test.html, without needing to select the dropdown menu. it's easier and quicker

**Comment by sasumner** [comment]
That would upset all users that expect to type `myfile` and press Enter and end up with `myfile.txt`.
They would end up with `myfile` (no extension) and they will open new issues here.

BTW, if I have a "normal text" new file, say `new 3`, and I do a save on it, and type `test.html` and press Enter in the prompting box, I actually get `test.html`, which I assume is what you want, and apparently you aren't getting that?

**Comment by sasumner** [comment]
For reference:

![image](https://user-images.githubusercontent.com/30118311/93924052-38902280-fce2-11ea-8eb4-ddfd370eb487.png)

**Comment by sasumner** [comment]
Related #8616

**Comment by sasumner** [comment]
Related #8615

**Comment by sasumner** [comment]
Related #8398

**Comment by sasumner** [comment]
It has just been brought to my attention that if you add double-quotes to the _SaveAs_ dialog's _File name:_ box, this issue is no longer an issue; in other words, it is a workaround.

So, as an example, you attempt to save an untitled document as `test.zzqzz` by typing that in the _File name:_ box, and you end up with `test.zzqzz.txt` as the file on disk.  However, if you'd have typed exactly `"test.zzqzz"` instead, you'd have ended up with what you wanted:  `test.zzqzz`.

**Comment by donho** [comment]
> It has just been brought to my attention that if you add double-quotes to the SaveAs dialog's File name: box, this issue is no longer an issue; in other words, it is a workaround.

Good to know. However I bet 8/10 users won't find this trick (including me).
