### ISSUE TITLE
ANSI-encoded file cannot be opened properly

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#888]
I have a text document with ANSI encoding (Windows-1252). It contains the following characters:

— … ü ä

When I open it in Notepad++ I get strange characters in these places. Chinese or control characters, it could be anything not even close. Switching the encoding from the encoding menu changes these characters to other wrong characters. The only solution is to explicitly select "Windows-1252" from deep down in the encoding submenus.

From what I understand about Windows and ANSI encodings, this should be the same as the "ANSI" shortcut. But it isn't.

Notepad++ version 6.8.3 on Windows 7 x64 SP1, default encoding configuration, first opened document after installation on this computer.

**Comment by h-h-h-h** [comment]
Do you have discovered the options in the settings dialog, third category? Try "UTF-8 without BOM" together with the indented checkbox.

**Comment by dg9ngf** [comment]
That is the default and I did try. But even explicitly selecting the "ANSI" encoding from the menu did not work when "Windows-1252" worked. Both should be the same. If they aren't, I don't know what "ANSI" is. Maybe the current meaning of it should be included in parentheses, like: ANSI (Windows-1252)

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
