### ISSUE TITLE
Allow switching documents in MRU order without the list window

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#889]
Right now I have two options:
1. (Default) Use the doc switcher that allows me to switch documents with the Ctrl+Tab hotkey in MRU (most recently used) order. This opens a list window when I press Ctrl+Tab and only hides the window and switches the document tab when I release the Ctrl key.
2. Disable the doc switcher and switch through document tabs in visual order. No list window is displayed and tabs are switched as soon as I press the Tab key.

Can I have a middle way please? I'd like to switch tabs in the natural MRU order but without that extra window. I'd like to look inside each document while I keep the Ctrl key pressed.

Possible solution: Enable the "MRU order" checkbox in the settings even when the "Enabled" checkbox above it is unchecked.

**Comment by dogancelik** [comment]
This should be an option. I agree :+1:.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
