### ISSUE TITLE
Folder as Workspace: folder-images do not change after using "Expand/Collapse All"

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8912]
**STR:**
Open a folder as Workspace.
Expand the root folder.
Press the **"Collapse All"** button.

**Result:**
The folder-image is "expanded".

![תמונה](https://user-images.githubusercontent.com/10229320/94365951-9e631c80-00dd-11eb-9bb2-adaef64dd477.png)

Just an interesting minor issue.

***
Notepad++ v7.8.9   (32-bit)
Build time : Sep 25 2020 - 21:35:54
Path : C:\---\Notepad++.Win32.Unicode Release.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit) 
OS Build : 7601.23964
Current ANSI codepage : 1255
Plugins : ComparePlus.dll HTMLTag_unicode.dll MenuIcons.dll PythonScript.dll _CustomizeToolbar.dll

**Comment by donho** [comment]
@Yaron10 I don't get your issue. Do you mean the 1st (expand) and the 2nd (collaps) buttons are not working?
I cannot reproduce it at all with my v7.9 32 bits.

**Comment by ArkadiuszMichalski** [comment]
@donho Look this:
![a](https://user-images.githubusercontent.com/2730894/94404036-a028f080-016e-11eb-9cdf-fc9ed91cb23b.gif)
But the same is for uncolapse button, folder-image is not change. Only [+] and [-] change this icon.

**Comment by Yaron10** [comment]
@donho,

The toolbar buttons **do** expand and collapse all.
They **do not** set the "image-state" (opened/closed) correctly.

Thank you for looking into it.

@ArkadiuszMichalski,

Thank you for explaining and illustrating it much better than I did. :)

**Comment by donho** [comment]
OK, I've got it.
Thank you for the explanation.

**Comment by Yaron10** [comment]
@donho,

Thank you for working on it.

And thanks again for https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8880. :+1: 
I find myself using it quite frequently.

**Comment by GoverLabs** [comment]
Hi, @donho ,
I've took a look at the issue, and found WinAPI expanding-collapsing mechanism a little strange. Icon's picture is being changed in `FileBrowser::notified`, when `TVN_ITEMEXPANDED` code is being passed. It works fine with clicking on + icon. 
But as posted at [MSDN page](https://docs.microsoft.com/en-us/windows/win32/controls/tvm-expand) about TVM_EXPAND message:

>When an item is first expanded by a TVM_EXPAND message, the action generates TVN_ITEMEXPANDING and > > >TVN_ITEMEXPANDED notification codes and the item's TVIS_EXPANDEDONCE state flag is set. As long as this state flag >remains set, subsequent TVM_EXPAND messages do not generate TVN_ITEMEXPANDING or TVN_ITEMEXPANDED >notifications. To reset the TVIS_EXPANDEDONCE state flag, you must send a TVM_EXPAND message with the TVE_COLLAPSE >and TVE_COLLAPSERESET flags set.

It seems that `TVN_ITEMEXPANDED` would never be passed, until `TreeView::fold` is modified this way:
`TreeView_Expand(_hSelf, tvProj, TVE_COLLAPSE | TVE_COLLAPSERESET);` 
But in this case all children nodes would be removed, because of `TVE_COLLAPSERESET` flag.

Removing children nodes to clear `TVIS_EXPANDEDONCE` flag is the thing I cannot understand. As a workaround I can suggest to change icons manually inside `TreeView::foldExpandAll`.

**Comment by donho** [comment]
@GoverLabs 

Thank you for taking look at it.

TVN_ITEMEXPANDED notification is sent only in the following actions (I guess these are MS TreeView controls default actions):
1. double click on the foldable items
2. click on the `+` & `-` of foldable items 
3. type arrow keys `<` & `>` on selected foldable items

I did google Win32 solution about it, but only found MFC one (ON_NOTIFY_REFLECT), so I will stop investigating this issue.
Feel free to do a PR for it if anyone here got the solution.
