### ISSUE TITLE
Make Tabbar enlarge again!

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#8929]
### Description of the Issue
Tabbar enlargement doesn't work once restart Notepad++.

### Steps to Reproduce the Issue

1. Go to Preferences dialog, uncheck reduce.
2. Observe Tabbar getting bigger.
3. Quit Notepad++ and restart it.

### Expected Behavior

Tabbar remain the large size.

### Actual Behavior

Tabbar reduce to its normal size.

### Debug Information

Notepad++ v7.9   (32-bit)
Build time : Sep 14 2020 - 22:58:18
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.508
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppXmlTreeviewPlugin.dll

**Comment by sasumner** [comment]
Here's what happens for me:

Before doing anything:
![image](https://user-images.githubusercontent.com/30118311/94719093-afe83680-0320-11eb-94b4-225659424072.png)

Right when I uncheck _Reduce_:
![image](https://user-images.githubusercontent.com/30118311/94718587-ecfff900-031f-11eb-8d72-897fa7aa23db.png)

After the next restart:
![image](https://user-images.githubusercontent.com/30118311/94718631-00ab5f80-0320-11eb-8bc0-71fcea1fdd22.png)

So I get more of the _Expected Behavior_ rather than the _Actual Behavior_.
Notice that not only does mine not "reduce to its normal size" after the restart, the icon actually gets a bit bigger.

-----------------

Why is my build-time different??

Notepad++ v7.9   (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : C:\GM\Utilities\npp.misc\Releases\npp.7.9\npp.7.9.portable\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1397
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
Same for me as for @sasumner, debug:

Notepad++ v7.9   (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : D:\_test\NPPClean\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1250
Plugins : none

**Comment by donho** [comment]
> Why is my build-time different??

Mine is a RC.

**Comment by donho** [comment]
Cannot reproduce any more.
