### ISSUE TITLE
You have NEVER been in china, bet it? Judge things based on "IMAGINATION".

### ISSUE THREAD

**Issue by augustunbear** [notepad-plus-plus/notepad-plus-plus#8934]
What is your final target? Motivate China to seperate to 30 small conturies? Then people living like Afghanistan, Syria, Irak?

You can live where you want, but you don't have the right to destroy the life of chinese people.

**Comment by ccuser44** [comment]
Wumao are losers sponsored by the chinese government to spread misinformation and basically jerk eachother off in their little echo chambers. They are some of the goofiest people on the intetet and tend to give off "small dick energy" because of their hilarious arguments and insults, as they are typically copied directly from google translate. They are the fungus that grow on uncleaned public toilets.

Wumao: Hi, I am 33 years old and unemployed. I never had a gf and I smell like swage but that's ok because I get all the sweet honey I need from the great leader, Winnie the Pooh
