### ISSUE TITLE
Render the vertical edge line in the background layer

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#894]
The vertical edge line seems to be rendered on top of everything else. When a line of text is longer than the specified number of characters and crosses that edge column, and the line is selected, then the edge is painted over the selection background. It should be behind anything else, but still above the text background colour, if any, to remain visible.

**Comment by dg9ngf** [comment]
The same applies to the tab indenting rulers, they also appear brightly above the darker selection background.

**Comment by h-h-h-h** [comment]
> The vertical edge line seems to be rendered on top of everything else.

Fortunately not on top of the characters. You test it with the character U+2588: `██`.

---

The vertical line should not be invisible when having a selection. For me it's okay as it is now. Do you advocate for mixing the colors?

**Comment by dg9ngf** [comment]
Mixing/blending colours would be the ideal way. And with it, people should be able to specify their colours including the alpha value (opacity) to control the effect. The basic Windows colour picker is certainly not suitable for that. It's primitive enough for picking RGB colours.

**Comment by dg9ngf** [comment]
Actually I believe that the edge is painted over characters as well. Enable the display of line endings in the View menu and push a line ending under that edge. Since the line ending symbol is wider than a normal character, it extends across that pixel column. In my case, the bright line separates the white-on-black "LF" indicator in two parts!

**Comment by h-h-h-h** [comment]
You're right, `CR` and `LF` are painted below the line, but `SUB`, in turn, is painted above (press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Z</kbd>). That's strange.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
