### ISSUE TITLE
Context menu opened by the menu key opens at the wrong place

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#895]
When the editor context menu is opened by the menu key on the keyboard (mostly between Space/Alt/AltGr and the right Windows key), is appears at the mouse cursor location, whereever that is. Other applications open it at the text input cursor location in this case.

Events triggered by the mouse should appear where the mouse points to; events triggered by the keyboard should appear where the keyboard focus currently is.

(And BTW no, I don't recognise that the mouse wheel is a keyboard input, even when Microsoft has implemented their old Win32 API so that it follows the keyboard focus, which is just stupid. .NET WPF does it correctly though, like all web browsers.)

**Comment by h-h-h-h** [comment]
:+1:

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by ygoe** [comment]
Still not fixed, but I don't run into this very often. I consider this move as a "won't fix" acknowledgement.
