### ISSUE TITLE
Text cursor keeps blinking while the menu is focused

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#902]
The editor text cursor keeps blinking even when the user has opened a menu from the menu bar or pressed the Alt key to navigate through the menu bar. The cursor is not only an indicator of where editing will go to, it is also an indicator of where the keyboard focus is. And when keyboard currently goes into the menu, the cursor must not blink at the same time. This is confusing.

The same applies to the context menu in the editor.

Other applications:
- Visual Studio, TextPad: Cursor disappears while in the menu.
- Notepad: Cursor freezes while in the menu (it's either invisible or constantly visible (non-blinking) depending on its last state when the menu was opened)
- Firefox, Chrome, Internet Explorer: Cursor keeps blinking like in NPP now.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by afwn90cj93201nixr2e1re** [comment]
How can i figure out why npp from some version started blink mouse cursor sometimes?
![GIF](https://user-images.githubusercontent.com/9306996/108350243-ea714380-71db-11eb-9b2b-4323f48da797.gif)

Just randomly. Cursor doesn't blink on other applications, for example in browser.

@donho
