### ISSUE TITLE
Encoding: UCS-2 or UTF-16

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#903]
Is it really UCS-2 or rather UTF-16? I don't know all the differences between the two, only that UTF is a successor of UCS. From what I know, Windows natively uses UTF-16 since some version and before that it was the more limited UCS-2. For basic text, these are identical, but there are definitely differences and the encoding name should correctly reflect which of them is used. I suspect it's actually UTF-16.

**Comment by xylographe** [comment]
UCs-2 is a fixed-width 16-bit encoding which can represent every code point in the BMP, but no code points outside the BMP. UTF-16 is a variable-length encoding (one or two 16-bit units per code point) which can represent all code points (except reserved range from U+D800 to U+DFFF).

Notepad++ supports UCS-2 (see #801).

**Comment by cup** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1360
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1727
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/801
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/903

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
