### ISSUE TITLE
Multiple default buttons in Find dialog after Count

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#908]
Steps to reproduce:
1. Open the Find dialog
2. Press the Count button

Expected result:
The Count button is the default button (blue highlighting in Windows 7 Aero) because it is focused.

Actual result:
The Find and the Count buttons are both default buttons (blue highlighting) at the same time. The user has no idea which of these commands will now be executed when pressing the Enter key.

I think the Win32 API is dumb enough to let that happen, but normally only one button may be a default button at a time.

**Comment by h-h-h-h** [comment]
:+1:

When you proceed with clicking on "Count", the dialog ends up alternating the default button state between "Find Next" and "Count". But when "Count" is the only default button and you press <kbd>Enter</kbd>, the "Find Next" action is performed.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
