### ISSUE TITLE
Saving file with specified extension gets ".txt" added

### ISSUE THREAD

**Issue by Marmotian** [notepad-plus-plus/notepad-plus-plus#9081]
Saving a new file with an extension that isn't one recognized by NPP will add the '.txt' extension after the specified extension. The same thing happens if you "Save As" and try to change the extension. I set the "Use new style dialog (without Unix style path capacity)" option and it makes no difference.

### Steps to Reproduce the Issue
1. Click 'New' button
2. Type a few characters
3. Click 'Save' button
3. Type a filename and extension <name.ext> NOT recognized by NPP (I used test.zot)
4. Click 'Save' button

### Expected Behavior
File will be saved as typed
### Actual Behavior
File saved as <name.ext>.txt

### Debug Information
Notepad++ v7.9   (64-bit)
Build time : Sep 22 2020 - 03:19:04
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1909
OS Build : 18363.1139
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

The only workaround I've found is to let NPP save it, open a Save As dialog, use Windows procedure (click name, F2) to change the name there in the listing portion of the dialog, and then cancel the save as. Then load the "new" file, and switch back to the "old" tab where NPP will complain that the file doesn't exist and you can close that tab.

**Comment by sasumner** [comment]
In 7.9.1 and later, tick this choice:

![image](https://user-images.githubusercontent.com/30118311/97777994-5440e100-1b4a-11eb-8b57-00e4cf81b3ac.png)

**Comment by sasumner** [comment]
Related to #8866 and its resolution

**Comment by liekensk** [comment]
Hi @sasumner,

That would be a perfect solution for me, but ticking that option in my preferences has no effect on the Save As.. dialog box.

**Comment by sasumner** [comment]
In 7.9.1, WITHOUT ticking the option:

![image](https://user-images.githubusercontent.com/30118311/102539783-2244f900-407c-11eb-9075-f24f10016c1f.png)

In 7.9.1, WITH the option ticked:

![image](https://user-images.githubusercontent.com/30118311/102539873-40125e00-407c-11eb-9407-6e06d743903b.png)

**Comment by sasumner** [comment]
@liekensk 

Please try the workflow pictured above.
Create a new document with Ctrl+n (or _File_ menu, then _New_ )
You should have a new tab with the name `new` and then a number (`1` is shown above but your number could be different).
Type a character into this new tab, e.g. `x` used above.
The _Save As_ box that appears should follow the above images.

**Comment by liekensk** [comment]
What a response time :-)

You're right, in the given circumstances it is the case.  Thx for pointing that out. But it's only true for brand new files it seems.

Instead, I was expecting the behaviour to be dependent on the file type given in the status bar.
![afbeelding](https://user-images.githubusercontent.com/7486057/102549307-2d1f7e00-40bc-11eb-9d58-9e62ab9eec10.png)

Once saved, it never easily saves without the extension (except after manually changing the file type to 'All types (*.*)' )
please try continuing as follows after the 4 steps you describe:
5. Name your file 'new1' (without extension) 
 That works fine.
6. Try again "Save As..." (the combo box after 'Save as type' selects now: 'Normal text file (*.txt)')
 You cannot save it as 'new2' unless you add double brackets around the file (as you pointed out in #8866, thx!) name or change the type to *.*
Also, suggesting any other filename with an extension unknown to np++ will result in '.txt' being added

There are a couple of exceptions (I accidentally found) that behave differently:
Take (or make) the file new3.ext, (also an unknown extension to np++). In the status bar at the bottom is says 'Normal text file'.
Doing 'Save As...' still shows the 'Normal text file (*.txt)' and if I set file name 'new_s2d.lvs.report.ext' it does NOT add the .txt in the filename. 
(.log is another example where the .txt is not added)

All of the above (except the 5th step of course) is independent on whether the setting in the preferences is ticked or not.
Unless the behaviour I describe is unintended, the checkbox should say 'Set Save dialog file extension filter to .* instead of .txt for new files.'

**Comment by Marmotian** [comment]
Standard Windows behaviour is that the extension specified as part of the typed filename **always** wins. Try this with any mainstream Windows program if in doubt. Doing it properly is just a matter of checking to see if the filename already contains a "dot" and not appending the extension if it does. 

You might want to allow that the old policy be retained for anyone who wants to do the "Unix thing" of having multiple dots in a name. You can do this in Windows, but it typically causes problems so most people don't do it.

**Comment by sasumner** [comment]
>But it's only true for brand new files it seems.

Yes, that was the design goal for the checkbox colored yellow above.

Users were upset that when they saved a new file, that they hadn't given a "Language" to, and that they wanted to give an extension to, that `.txt` was always appended when Windows didn't "know" the extension they were trying to provide.

It was difficult if not impossible to come up with succinct yet all-encompassing text to put next to the checkbox to describe that.  Originally I had it on the "New Document" page in the _Preferences_, but this wasn't liked so it got moved to the "MISC." page.  ("New Document" at least hinted that it was related to saving a new doc).
When it got moved, its text had already started to "harden" as to what it was going to be.

As files without extension are a rarity, it isn't a huge burden to have the user change the _Save as type_ filter for the situation of _SaveAs_ on an extensionless file.

I couldn't really follow your "couple of exceptions" section.  I found that `.ext` and `.log` are both known to my Windows setup.
