### ISSUE TITLE
Notepad++ 7.9.1 function list is empty with new user profile

### ISSUE THREAD

**Issue by bdbl** [notepad-plus-plus/notepad-plus-plus#9134]
### Description of the Issue

Since Notepad++ 7.9.1 and function list refactor, function list may be empty when workstation is used by multiple users

This situation is due because function list is using configuration from user profile only
The setup program installs new required files in current user profile folder, but not in other users profiles

### Steps to Reproduce the Issue

1. Install Notepad++ 7.9.1 with default options
2. Launch Notepad++ with current user, function list is OK
3. Log on with another user and launch Notepad++ , function list is empty
4. functionList subfolder is not present in the second user profile folder _C:\Users\user\AppData\Roaming\Notepad++_

You can also reproduce the issue with current user:

1. Delete profile folder _C:\Users\user\AppData\Roaming\Notepad++_
2. Launch Notepad++
3. Profile folder is created without _functionList_ subfolder

Also, the function list remains empty if I manually copy _functionList_ subfolder in Notepad++ install directory (not in user profile)

### Expected Behavior

As function list is now using configuration from user profile only, I can suggest :

* Keep installing functionList folder in Notepad++ install folder
* Use this folder as default one if it don't exist in user profile folder
* **Or** copy the content of this folder in user profile folder (if don't exist) when launching Notepad++

Of course, any other idea is welcome

### Actual Behavior

Function list is empty for some users

### Debug Information

Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows Server 2019 Standard (64-bit) 
OS Version : 1809
OS Build : 17763.1577
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by codebrainbv** [comment]
Yes, I have the same issue, please fix this.

**Comment by pryrt** [comment]
I see that Don has accepted this, but I thought I'd add that we've seen [a complaint in the forum about it](https://community.notepad-plus-plus.org/topic/20352/function-list-no-longer-works/) now, and I've confirmed the behavior: I confirmed it with two separate users, rather than by deleting the AppData Notepad++ folder: the installing user gets the functionList folder, but any additional users do not.

**Comment by donho** [comment]
@pryrt 
> I confirmed it with two separate users, rather than by deleting the AppData Notepad++ folder: the installing user gets the functionList folder, but any additional users do not.

Could you elaborate it please?

**Comment by pryrt** [comment]
@donho ,

1. I have a computer with two users, Kids and Peter.
1. I upgraded a computer from v7.7 to v7.9.1 using account "Kids".  
2. In the Kids' `%AppData%\notepad++\`, the `functionList` subfolder was properly created and populated, and the Function List feature works properly
3. I switched to the Peter account on the same computer, and ran Notepad++ v7.9.1.  The Function List feature does not work (the panel is empty, because it found no functions)
4. Peter's `%AppData%\notepad++\` folder does _not_ contain the `functionList` subfolder.
5. If I copy the `functionList` folder to the Peter account location, then running Notepad++ v7.9.1 there will allow the Function List to work, too.

(screenshots of the process were shown in [my forum post](https://community.notepad-plus-plus.org/post/60024))

FIX: Any time Notepad++ loads and the settings folder (whether it's AppData or the Cloud folder) doesn't contain the `functionList` subfolder, Notepad++ should populate it with the default files.  (That means it probably needs to keep a copy of `functionList\` folder in the installed directory as well, so that it's got a golden template to work from; that also makes it easier to switch any installation or portable version from doLocalConf to AppData or back.)

**Comment by donho** [comment]
Thank you @pryrt for your detail explanation.
So in next release (v7.9.2) I'll make function list files installed in Notepad++ installation folder, and populated to `%APPDATA%\Notepad++\` if they don't exist - just like functionList.xml's behaviour.

**Comment by dekthai99** [comment]
We have the function list empty issue with user-defined language with a single user

**Comment by dodmi** [comment]
@donho: May I propose a slightly different implementation in general:
- Put the files in the installation directory (in a sub folder defaultSettings or similar)
- **Don't copy them over to the user profile** until they change
- If a user changes Notepad++ settings, create the corresponding file in %AppData%\Notepad++
- If there's a file in the user profile, use the custom file, if there's none, use the one in the installation directory

Updating files in the %AppData% folder is critical, because user changes can get lost (example: I change the Markdown UDL coming with NPP matching my theme; upgrading the file overwrites my changes)
On the other hand: Not updating the files is also a problem: Not updating stylers.xml or langs.xml for example, may lead to unexpected coloring behavior. The users don't get the latest settings.

If a user wants to customize a file, he can copy it over and adapt it. (Behavior as it is now, for example users can add new own theme files)
If a user changes settings in NPP, NPP creates the customized file in %AppData%. (Means any user can still have his custom settings, no admin privileges are required to save the settings)
In any other case NPP uses the latest version coming with the installer.

- Any new user will get Notepad default settings
- Any long term user profits of the latest files if he didn't change any setting concerning this file (I'm especially thinking of stylers.xml, langs.xml and functionList directory - even if a user customizes one file in functionList directory, he'd still get the updates for any other lang)
- Any user can reset his settings by deleting (or renaming) his Settings folder, at the moment, essential files are missing in this case
- A complete set of default settings is available for comparison (for example if I changed some colors in a theme, the original latest version would still be placed in the installation dir)
- This wouldn't change any existing users experience, since all files are in the %AppData% folder at the moment. They need to cleanup themselves if they want to profit from the changes
- Especially in multi user environments: Admins can easily deploy default settings by cutomizing the files in the install dir

**Comment by donho** [comment]
@dodmi 
The new behaviour of loading function list will be (for the installer package):
Try to load from `%APPDATA%\Notepad++\functionList\`, if it failed, then load from `%PROGRAMFILES%\Notepad++\functionList\`.
In this way, users can override function list in `%APPDATA%\Notepad++\functionList\` manually. Otherwise, function list won't be empty.
