### ISSUE TITLE
*.nfo files are always recognized as OEM-US encoding

### ISSUE THREAD

**Issue by jirijanata** [notepad-plus-plus/notepad-plus-plus#9153]
### Description of the Issue
NFO Files are incorrectly recognized with encoding OEM-US.

### Steps to Reproduce the Issue
1. Create in notepad some text file with nfo extension.
2. Open this file in Notepad++.
3. You will see OEM-US encoding in the bottom information line.
4. If you change the extension to the txt, the encoding will be correctly recognized.

### Expected Behavior
Notepad++ should detect encoding.

### Actual Behavior
Notepad++ detects always at nfo files OEM-US encoding.

### Debug Information
Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Enterprise 2016 LTSB (64-bit) 
OS Version : 1607
OS Build : 14393.4046
Current ANSI codepage : 1250
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by jirijanata** [comment]
Even if I disable Autodetect character encoding, the file opens with the wrong encoding.

**Comment by sasumner** [comment]
Autodetection of encoding isn't an exact science.

**Comment by northword** [comment]
Add ext `nfo` to `langs.xml` and `langs.model.xml` (in the installation directory of the program) to solve it. 
Line 259 in langs.xml and 398 in langs.model.xml: 
```xml
        <Language name="xml" ext="xml xaml xsl xslt xsd xul kml svg mxml xsml wsdl xlf xliff xbl sxbl sitemap gml gpx plist nfo" commentLine="" commentStart="&lt;!--" commentEnd="--&gt;">
```
After that, restart notepad++, open a .nfo file, it will be recognized as an eXtensible Markup Language file and the character encoding is recognized as utf-8.

**Comment by madmax2** [comment]
> Add ext `nfo` to `langs.xml` and `langs.model.xml` (in the installation directory of the program) to solve it. Line 259 in langs.xml and 398 in langs.model.xml:
> 
> ```
>         <Language name="xml" ext="xml xaml xsl xslt xsd xul kml svg mxml xsml wsdl xlf xliff xbl sxbl sitemap gml gpx plist nfo" commentLine="" commentStart="&lt;!--" commentEnd="--&gt;">
> ```
> 
> After that, restart notepad++, open a .nfo file, it will be recognized as an eXtensible Markup Language file and the character encoding is recognized as utf-8.

Can this fix be made permanently in an update version of notepad++?

**Comment by madmax2** [comment]
> No, the current latest release 8.4.4 has not fixed this issue, I have switched to VS Code.

yeah i know, cos I encountered this issue with that version,

Do the developers pay attention to feature requests here?
and how should we word it as a feature request in regards to this fix?

**Comment by alankilborn** [comment]
>Do the developers pay attention to feature requests here?

Yes they do, but there are already a LOT of open issues, and everyone has limited time. :(

**Comment by madmax2** [comment]
@Pocokk are you are developer of this program?
Why are you asking?

I don't know if it is still issue or not because I had to manually fix the problem as suggested by @northword 
The only way to know is to remove any manual changes fix made and uninstall + reinstall the software

**Comment by Pocokk** [comment]
no I'm not a developer, just found this ticket/issue opened and I asked if anything was changed in the last 10 months or so.

**Comment by madmax2** [comment]
@Pocokk why curious?
do you have the same issue?

If you have latest version and not made any manual fix as mention here.
Can you test if this issue occurs?
I can give you NFO file to test if you need?

The main issue here is NFO files that only contain XML tags not showing the tags in their proper color encoding due to the wrong encoding detection.

I think if they had fix this issue, they probably would have close it already or made a note/update here.
Seems like this issue is low priority to them.
It is not a hard for them to fix either, just make the changes as suggested by @northword (manual fix) and add that to newest update..
OR do they need to fix their actual detection code, which maybe harder to fix.

As someone mention
"Yes they do, but there are already a LOT of open issues, and everyone has limited time. :( "

**Comment by rdipardo** [comment]
>  OR do they need to fix their actual detection code, which maybe harder to fix.

When Notepad++ opens any `*.nfo` file, it *deliberately* sets the encoding to CP437 &#x2014; for [historical reasons](https://en.wikipedia.org/wiki/Code_page_437) &#x2014; and changes the font to Lucida Console  &#x2014; also for [historical reasons](https://devblogs.microsoft.com/oldnewthing/20070516-00/?p=26843).

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/a561cd37d499911cdc53988466a341905ee98c83/PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp#L1609-L1638

This code has been there [since 2009](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5b4f8e3e11b8e09b5ea9cf926f09655984ed909f).

If it hasn't been changed yet, either someone is very nostalgic for MS DOS, or they've completely forgotten this code in the source tree.

**Comment by thezoggy** [comment]
media managers use .nfo store metadata, which can be utf8. this bug in notepad++ caused me to think the upstream app was writing bad data.. but actually its just notepadd++ doing bad encoding. if I take the file and rename it to another extension then the utf8 data is displayed correctly (or use another app that doesnt mangle the encoding).

**Comment by jopereirapt** [comment]
This can be solve by adding:

-  Settings -> Style Configurator -> XML -> User Ext. -> "nfo"

(editing _langs.model.xml_ didn't work for me)

**Comment by Alex-Tsarik** [comment]
Do I understand correctly that this issue is still not resolved for the application from the new installation?

**Comment by pryrt** [comment]
@djgraco ,

For eons past, NFO defaulted to OEM-US.   But in [v8.7.4](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Changes#874), it was changed to allow any encoding (and I think defaults to UTF-8 now, though that might only be because I have UTF-8 as my default for other files).  

And, unfortunately, the bytes used by box-drawing in OEM-US files seem to align with common byte patterns in EUC-KR, so the encoding auto-detect misidentifies it as Korean instead of box-drawing.

My recommendation: if you often use NFO files that were saved as OEM-US, you should probably turn off encoding auto-detect.  But I cannot guarantee that will keep you from have to pick the encoding.

See more discussion on the Forum: 

https://community.notepad-plus-plus.org/topic/27318/ascii-nfo-sh-problem-dos2unix-is-required-to-fix-the-bash-files
