### ISSUE TITLE
svn urls not links since 7.9.1

### ISSUE THREAD

**Issue by nikita-leontiev** [notepad-plus-plus/notepad-plus-plus#9155]
### Description of the Issue
Since 7.9.1 svn urls are not links any more, so can't be open, for example, via TortoiseSVN.
Suppose related to https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9090

### Steps to Reproduce the Issue
Add any svn URL to editor, for example: svn://svn.notepad-plus-plus.org

### Expected Behavior
Link.

### Actual Behavior
Simple text.

### Debug Information
Notepad++ v7.9.1   (32-bit)
Build time : Nov  2 2020 - 01:03:56
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Home Premium (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1251
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll

**Comment by donho** [comment]
In order to fix several bugs of URL link, the parsers of URL has been rewritten (by @Uhf7).
The current implementation handles much better URL. OTOH, it has some limit to support other protocol, like `svn://`.
@Uhf7 please correct/complete if what I mentioned above is not accurate.

**Comment by Uhf7** [comment]
That's correct so far. The previous regex based parser accepted nearly everything as scheme name, the new version limits the allowed scheme names to the schemes which can be handled by the installed web browser and the installed email software.

`svn:` is a custom URL scheme, which may be installed on computers, but it is not available "out of the box". That may be one reason, why custom URL schemes are not detected by MS VC++, MS Outlook or MS Word. The other reason is, that every URL scheme actually has it's own format, although the `svn:` scheme format looks very similar to the `http:` scheme format.

How to get custom schemes supported? I can imagine a configurable list of custom schemes, which would then be handled like the `http:` scheme, if this is desperately needed. I cannot imagine to parse each and every custom scheme installed on a given computer or even check for the custom schemes installed. Many schemes I see on my computer seem to be for internal use by the software which installed them.

**Comment by FreeAndNil** [comment]
@Uhf7 How about a checkbox for enabling the old behavior?

**Comment by donho** [comment]
@Uhf7 
> I can imagine a configurable list of custom schemes, which would then be handled like the http: scheme, if this is desperately needed. I cannot imagine to parse each and every custom scheme installed on a given computer or even check for the custom schemes installed. 

Sounds reasonable.

@FreeAndNil 
> How about a checkbox for enabling the old behavior?

Unfortunately no. It's impossible to bring back the old, inaccurate detection.

**Comment by ThomasNygards** [comment]
Similar issue for me. Literally added a custom protocol **yesterday** using this:
https://stackoverflow.com/questions/389204/how-do-i-create-my-own-url-protocol-e-g-so

**Comment by andry81** [comment]
>Unfortunately no. It's impossible to bring back the old, inaccurate detection.
For the sake of another inaccurate detection?

**Comment by donho** [comment]
@andry81 @FreeAndNil 
Sorry I wasn't clear. I meant there's no way to add an option for this issue. 
OTOH, we can add the protocols we need with the old detection way upon the new detection (if it's refused by the new detection). 
What do you think @Uhf7 ?

**Comment by andry81** [comment]
> Sorry I wasn't clear. I meant there's no way to add an option for this issue.

What about to delegate all not known extensions to a browser or Windows Explorer?

**Comment by Uhf7** [comment]
> What about to delegate all not known extensions to a browser or Windows Explorer?

Notepad++ calls only the Windows shell, which decides, what software is to start.

After using a computer some time and installing some software, there are surely hundreds of custom schemes registered. Notepad++ cannot check them all, we don't want await a registry scan at each start.

There is a second problem: It may be the case, that software is installed, which is actually not much valued by the user of the computer. We all know, how eagerly some service providers install their preferred view of the world. If we would make all installed schemes clickable, then we may have links to something, which we do not want to run under any circumstances.

> What do you think @Uhf7 ?

I don't think we need two different parsers to solve this. I just tested a suitable solution for the problem. It is a configuration string, containing a space-separated list of additional schemes the user wants to allow. In the code it looks like this:

`generic_string const mySchemes = L"svn:// xyz: abc://"`

As you notice, this configuration contains the slashes after the scheme, so that there is a chance to use it for custom schemes without `//` too (A build-in scheme without `//` is `mailto:`).

This configuration would need a place somewhere. Two ways:
- a hidden configuration, which can be modified by editing the config.xml.
- an additional parameter in the MISC. page of settings. Here we have two sub-choices too:
  - below "workspace file ext." (not the best place logically, but low impact on the menu)
  - below "Enable fullbox mode" (increases the height of the Preferences menu).

**Comment by andry81** [comment]
> Notepad++ cannot check them all, we don't want await a registry scan at each start.

Why not run scan in parallel thread and update text links in the text? Why not to put the result of a scan into shared memory between multiple Notepad++ instances? Or even run a mini service to hold intermediate parse results?

> There is a second problem: It may be the case, that software is installed, which is actually not much valued by the user of the computer. We all know, how eagerly some service providers install their preferred view of the world. If we would make all installed schemes clickable, then we may have links to something, which we do not want to run under any circumstances.

If you go "out of NP" by open a link (ctrl+click or double-click), then you can do it like in the browsers: open popup/sub menu to select variants with descriptions what they does.

**Comment by donho** [comment]
@Uhf7 
> I don't think we need two different parsers to solve this. I just tested a suitable solution for the problem. It is a configuration string, containing a space-separated list of additional schemes the user wants to allow. In the code it looks like this:
generic_string const mySchemes = L"svn:// xyz: abc://"
As you notice, this configuration contains the slashes after the scheme, so that there is a chance to use it for custom schemes without // too (A build-in scheme without // is mailto:).

Sounds great! But in this case, why don't we make some default schemes (like "svn://" & "mailto://") plus customizable schemes, which are added by users via MISC of preferences dialog?


> This configuration would need a place somewhere. Two ways:
> - a hidden configuration, which can be modified by editing the config.xml.
> - an additional parameter in the MISC. page of settings. Here we have two sub-choices too:
>  - below "workspace file ext." (not the best place logically, but low impact on the menu)
>  - below "Enable fullbox mode" (increases the height of the Preferences menu).

below "Enable fullbox mode" it makes more sense to me.
I can take in charge this part after you adding "Customized schemes" settings in `config.xml`

**Comment by Uhf7** [comment]
> Why not run scan in parallel thread ...

Because the likelihood of crashes increases with the complexity of the software. And, as I mentioned, I don't want to run most of the software, which installed schemes on my computer. Under no circumstances. So I would need a exclude list then.

> popup/sub menu to select variants with descriptions ...

This would make the URLs more than one double-click away for the user, so some users will complain about the extra layer in the operation.

And, new point: We are not talking about only 100 schemes, it is more like about 500 to 2000 schemes. About 10 percent of them may work as clickable links, the rest of them was installed for internal use of the software which installed them. Too hot for me.

**Comment by Uhf7** [comment]
@donho
> I can take in charge this part after you adding `<GUIConfig name="URL customized schemes"></GUIConfig> settings in config.xml`.

Thank you. This makes it much easier to me. PR is coming soon.

**Comment by Uhf7** [comment]
@donho

> Why don't we make some default schemes (like "svn://" & "mailto://") plus customizable schemes, which are added by users via MISC of preferences dialog?

We can specify "svn:// pdf://" as default value for the setting, right? The user can then extent this. "mailto:" is already standard. Or do you want to make the standard schemes excludable too?

**Comment by donho** [comment]
@Uhf7 
> We can specify "svn:// pdf://" as default value for the setting, right? The user can then extent this. "mailto:" is already standard. 

👍  It will be served as example furthermore.

> Or do you want to make the standard schemes excludable too?

Sorry, I don't follow you ?

**Comment by Uhf7** [comment]
@donho

Make the standard schemes excludable would mean we accept only the schemes which are specified in the configuration. To keep the behavior of 7.9.1, the configuration would have be:
`ftp:// http:// https:// mailto: file://`. 
The user would then be able to de-select the standard schemes too.

The drawback is, that nothing works, if this configuration is empty. And we could end up to have to gray out the "Enable clickable links" box in the Preferences menu, if this configuration is empty. So I would prefer just to extend the standard schemes by the configuration.

**Comment by donho** [comment]
@Uhf7 

> The drawback is, that nothing works, if this configuration is empty. And we could end up to have to gray out the "Enable clickable links" box in the Preferences menu, if this configuration is empty. So I would prefer just to extend the standard schemes by the configuration.

That makes perfect sense. So let's do it in this way.

**Comment by donho** [comment]
Related https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9172

**Comment by ArkadiuszMichalski** [comment]
@donho It will not be possible https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9155#issuecomment-731622690? We can't turn off some of default `ftp:// http:// https:// mailto: file://`?
Frome last PR actual list is `svn:// cvs:// git:// imap:// irc:// irc6:// ircs:// ldap:// ldaps:// news: telnet:// gopher:// ssh:// sftp:// smb:// skype: snmp:// spotify: steam:// sms: slack:// chrome:// bitcoin:`.

**Comment by donho** [comment]
@ArkadiuszMichalski 
> We can't turn off some of default ftp:// http:// https:// mailto: file:// ?

No, we can't.
But why do you need to turn off the above schemes?

**Comment by ArkadiuszMichalski** [comment]
I misread the above post and thought that you want add possibility to change all. Personally, I don't need it at the moment, but if someone asks about it, I will direct them to this topic.
