### ISSUE TITLE
Tab contents disappear

### ISSUE THREAD

**Issue by CaptainCyril** [notepad-plus-plus/notepad-plus-plus#916]
Hi,

I usually code in NotePad++ and try the code directly in FireFox on localhost. When satisfied with the result I use FileZilla to upload to the server. Around once a month, NotePad++ stops responding and deletes the whole code of the edited tab and the file uploaded is 0 bytes.. So I have to go to AppData and get the file from backup.

1) Edit Tab
2) Save Tab
3) Upload using FileZilla
4) Crash

Thanks!

Cyril

**Comment by fedorg** [comment]
Not only that, npp *erases* the contents of the *original file* when it crashes. Just happened to me. I was rescued by an occasional recent commit, but it was scary.

**Comment by CaptainCyril** [comment]
Yes this is what I meant. It deletes the contents of the original file and it becomes 0 bytes. You can get the contents most of the time from the backup folder in AppData.

**Comment by CaptainCyril** [comment]
I uninstalled NotePad++ and deleted everything in the folder then reinstalled it. Now the crash is not happening but I have only been trying for 2 weeks. I think the problem but not sure that it was from the plugin Explorer.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
