### ISSUE TITLE
NPP v7.9.1 renaming file on Tab isn't long enough

### ISSUE THREAD

**Issue by swgmike** [notepad-plus-plus/notepad-plus-plus#9173]
I have npp v7.9.1. 
I created a new file from the menu dropdown list.
I then tried to rename the file by right-clicking on the npp tab for the new filename.
A popup appears to enter the new name.
However, if I enter a name longer than the popup box, it will not scroll to the left to allow me to enter the full name.
I can save the new file with the new name up to the limit that the rename allows me to and in the save-as file manager popup
change it to the full "long" name I want it to be.
Moreover, if I edit my long filename that was already saved to disk, the tab shows the long filename. Then if I right-click on the 
long filename in the tab to rename it, the save-as file manager popup appears showing it so that I can change it to a shorter or even longer filename.

Need to change the rename popup so that it scrolls left and allow one to enter a filename up to the maximum allowed by
Windows 7-10 particularly when the filename is "new".

**Comment by sasumner** [comment]
>I created a new file from the menu dropdown list.
I then tried to rename the file by right-clicking on the npp tab for the new filename.
A popup appears to enter the new name.

I believe what you are referring to is a "temporary name"; so instead of looking at "new 2" for example, you can give the temporary buffer a more meaningful name, without saving it to disk.  This "temporary name" is NOT a filename, it is just a mnemonic name if you want to (for whatever reason) NOT save the buffer as a disk file at the current time.

If your true intent is to save it to disk, don't use _Rename_ at this point, use _Save_.
You will be able to save with whatever length filename you want, within the limits of the OS of course.
The same is true for a _Rename_ _AFTER_ you've done the first _Save_.

**Comment by sasumner** [comment]
Closing due to lack of any response; assume response given already is adequate.
