### ISSUE TITLE
Enhancement: Automatic Dark mode - follow system setting (W10, possibly others)

### ISSUE THREAD

**Issue by Zvone7** [notepad-plus-plus/notepad-plus-plus#9183]
Hi! 
Haven't found an open issue with this idea/request exactly, but it would be really sweet if notepad++ could follow the theme set in W10 automatically. (possible extended to other OS as well)
This issue does relate to #5852  but it's taking a step further.

**Comment by HaroldPetersInskipp** [comment]
Would love to have this as well, but I've heard it isn't possible until Scintilla has some updates as Notepad++ is built with Scintilla. Really any kind of dark mode (NOT high contrast) would be tremendously helpful to those with visual impairments.

**Comment by muRn** [comment]
I was thinking about this feature myself when I saw [people making **custom builds**](https://superuser.com/a/617810) of Notepad++ just to not have the toolbar so bright when everything around is dark.

I did some research and looks like app can detect if dark theme is enabled and behave accordingly. [This](https://stackoverflow.com/a/41763234) is how this can be done in UWP app. And [this](https://stackoverflow.com/a/58494769) is how to do the same by reading from windows registry. Correct me if I'm wrong but as I understand Notepad++ is not an UWP app but a plain C++ & WinAPI one, so first link is not an option. But the second one is, ain't it? It should be pretty straightforward to read from registry, right?

I'm not a C++ developer but I had some C++ experience in the past. I can try blow the dust from Visual Studio and implement the change myself if someone from core contributors confirms that my understanding is correct and feature is welcome/desired.

**Comment by n3tcom** [comment]
What I have done to get near this result is use the Style Configurator to style the Editor Background, Fonts, etc., as well the inactive tab background and font is able to be styled, however not the active tab (I suspect due to an ancient bug in applying the color styles incorrectly). I then disable the menu and toolbar.  This only leaves the active tab, scrollbars, and status bar as the remaining bright objects on-screen.  Better than nothing.

**Comment by adzm** [comment]
I was messing around with this recently and managed to get some basic functionality following the undocumented stuff eg from win32-darkmode. There are a lot of miscellaneous changes that would need to be done in order to get everything truly dark mode, especially with dialog boxes and all that, but owner-drawn menus and toolbars and statusbars would be able to handle all of the main window in dark mode. I'm tempted to give this a shot, but uncertain if it would be wasted effort if it is not something that would get merged by devs eventually. Regardless, I might as well use some of my win32 experience for something and at least get the main window darkmode-aware, which would at least be a starting point for future changes in the static dialogs (which are the trickiest due to the tab / property page backgrounds, and the various other controls and hardcoded colors in there, as well as potential issues with third party plugins)

**Comment by mere-human** [comment]
@adzm 
> I might as well use some of my win32 experience for something and at least get the main window darkmode-aware, which would at least be a starting point for future changes in the static dialogs

I think, having at least dark mode support for the main window is a good start and better than nothing.
Gotta start somewhere!

I wanted to bring this to your attention. There is a tool called [Google trends](https://trends.google.com/trends) that shows what people search for.
The dark mode seems to be one of the hot Notepad++ related topics. So we better implement it one way or another.
![image](https://user-images.githubusercontent.com/9664141/104573468-96fc5a80-565d-11eb-8db1-bd03750fead7.png)

**Comment by adzm** [comment]
#7692 is dark mode in general. #9183 is having it follow system themes automatically, which is worth considering since when implemented it will likely need a dark/light/system option like many other apps. #5852 seems to describe the scintilla autocomplete popup but I think was originally intended to be a dark mode issue like #7692.

I'll keep the dark mode discussion in #7692 so as to keep things on topic and leave this for the system/automatic stuff.

I do have dark mode working out pretty well; just need to clean up the code a bit one night and make a PR. You can see the screenshot https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7692#issuecomment-776804467

**Comment by SirTwsted** [comment]
@donho  THANK YOU THANK YOU THANK YOU..!!  Finally Dark Mode !!

How do I get it to follow Windows 10 dark theme now?  or is that not coded in?
Anyways its still awesome thx :)

**Comment by mere-human** [comment]
@EatonZ @SirTwsted 

> Please add a setting to sync with the current Windows them/mode. Thanks.

Maybe, you should create a new feature request for that:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by sasumner** [comment]
>Please add a setting to sync with the current Windows theme/mode.

IMO this is not important, at all.
If you want a certain mode, just flip the checkbox for it.

**Comment by EatonZ** [comment]
@sasumner All about preference I guess. I prefer not to have to toggle the setting each time I open the app at a certain time of day.

**Comment by sasumner** [comment]
@EatonZ Ah, I guess that is a good point.  As one that has never set up my PC to have different themes at different times of day, I lacked understanding of this.  Thank you for pointing it out.

**Comment by Zvone7** [comment]
> @EatonZ @SirTwsted
> 
> > Please add a setting to sync with the current Windows them/mode. Thanks.
> 
> Maybe, you should create a new feature request for that:
> https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#reporting-issues

New ticket shouldn't be created since this ticket is titled "Automatic dark mode". Think it's wrong to consider this ticket closed, because, yes Dark Mode was added 🎉 , but it's not activated automatically and is not paying attention to Theme being active in windows.

**Comment by dogancelik** [comment]
Microsoft Office programs **sync** with System Theme:
![system settings](https://user-images.githubusercontent.com/486818/135810559-4d8c3aee-15af-4fb4-88be-81ecda8e0179.png)

**Comment by dogancelik** [comment]
Commit 5a3bf49c86acca8863a1be2fb12038f18c54594a doesn't seem to detect changes.

![sync theme 3](https://user-images.githubusercontent.com/486818/135844733-c59abf84-e9d1-44bb-b93d-991405d412fc.gif)

My Notepad++ version: `8.1.5` (32-bit)
My plugins: Compare, Mime tools, Npp Converter, NppExport

**Comment by anddilolz** [comment]
Why is this closed? Automatic dark mode doesn't work. This would be a tremendous addition! I like to use automatic transition to dark/light mode at sunset/sunrise.

**Comment by shantanub08** [comment]
This ticket indeed isn't supposed to be closed. I don't have anything useful to say, just commenting to show that people are still looking for Auto Dark Mode so this ticket should be open until it gets implemented

**Comment by EatonZ** [comment]
@donho Can you re-open? Or do you prefer a new issue be opened at this point?

**Comment by YakovL** [comment]
While #10644 was suggested to be a duplicate, it's actually a separate issue regarding dark mode autodetection so may be further duscussion should go there

**Comment by YakovL** [comment]
Besides "me too", let me note that the dark mode is governed by `HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize\AppsUseLightTheme .AppsUseLightTheme` registry value (I've tested that it's enough to [switch it](https://superuser.com/a/1724237/576393) to make all the apps supporting "follow system setting" feature repaint).

**Comment by EatonZ** [comment]
@donho **Thank you** for doing this! Been eagerly awaiting this, and can't wait for the next release.

**Comment by donho** [comment]
@EatonZ 
Please thank @onzone10 - it's the contribution from him.

**Comment by ZMYaro** [comment]
Thank you so much!  This has been my most wanted feature for a while, and I am so appreciative to see it finally arrive!
