### ISSUE TITLE
Find in Files - when Directory path has leading or trailing spaces the search does not work

### ISSUE THREAD

**Issue by mauriciogracia** [notepad-plus-plus/notepad-plus-plus#9199]
### Description of the Issue
When using the  Find in Files feature if the path contains a space at the beginning the search does not work and does not show any error about not finding the path.

### Steps to Reproduce the Issue

1. Open the find files window
2. Type a valid path but include a " " before it
3. Click on Find All (nothing happens)

### Expected Behavior
The path should be trimmed or an error message of "invalid path" should be shown

### Actual Behavior
Notepad did not search for any files or reported error in path

**Comment by sasumner** [comment]
Title of issue does not agree with description in body.
Actually, my testing in 7.9.1 shows that **EITHER** _leading_ or _trailing_ spaces on the _Directory_ causes the search to not be run to produce output.
So, I am changing the title to reflect this.

**Comment by mauriciogracia** [comment]
The description in the body mentions a "space" a the beginning (or leading) so it does match the issue I found, I did not test for trailing spaces so I did not mention it.

**Comment by sasumner** [comment]
Hmmm, your original title has "trailing spaces" in it, so I think you did mention it...
But no matter, BOTH types are a problem.

**Comment by mauriciogracia** [comment]
correct, hope the fix is as fast as the attention to details ;-)

**Comment by sasumner** [comment]
I've got a workaround suggestion for you for the meantime...

**Comment by mauriciogracia** [comment]
Haha, i wish I could help you solve issues in the future.

**Comment by sasumner** [comment]
@donho 

Can you look at this one?
I tried removing any leading/trailing spaces off of the directory so that `::PathFileExists()` will succeed, but the reward for my effort is a search-result-lexer assert in debug mode.
If I run in release mode, the search-result output appears as I would expect it to, so I'm not sure what data it is lexing in debug mode that it doesn't like.
Also if I disable the lexer in debug mode, the search-result output text appears as expected (but obviously without nice lexing).

Not for this issue, but a nice feature would be to somehow highlight invalid "Directory"s.
Maybe turn the "Directory" field pink/red like the incremental-find box when there is no match there?
But, if I can't even remove some leading/trailing spaces here successfully, there isn't much hope for that.

**Comment by sasumner** [comment]
@donho Disregard my previous request.
The assert I'm getting isn't related to this issue.
I'll open another issue regarding that.

I'll proceed with a PR that will fix this current issue.

**Comment by mauriciogracia** [comment]
Thanks, that was amazing fast.
