### ISSUE TITLE
Copy paste with multiple selection ( column mode ) fails

### ISSUE THREAD

**Issue by sanastasiou** [notepad-plus-plus/notepad-plus-plus#922]
Easy to reproduce, hold alt+shift and selected multiple lines, try to copy them somewhere, where there aren't enough empty lines ( i.e. less than the ones you've selected ). Observe the messed up buffer :)

**Comment by h-h-h-h** [comment]
You seem to refer to column mode (see Edit menu). Therefore, I don't know why you are talking about <q>multiple selection.</q> Here, Notepad++ pastes the copied block correctly.

**Comment by uhlmul** [comment]
When I give a selection of more than 8000 lines several times it ends up by corrupting the structure of the file
![step1](https://cloud.githubusercontent.com/assets/16224580/11686215/5dad4488-9e7f-11e5-9121-c30dfcc2001a.jpg)
![step2](https://cloud.githubusercontent.com/assets/16224580/11686216/5dcd2a3c-9e7f-11e5-8e3a-ebe8a8023797.jpg)
![step3](https://cloud.githubusercontent.com/assets/16224580/11686217/5dd18a82-9e7f-11e5-91e7-5bd28d57365e.jpg)

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
