### ISSUE TITLE
Ability to localize "Line" preceding each line number on Search Results

### ISSUE THREAD

**Issue by Patriccollu** [notepad-plus-plus/notepad-plus-plus#9224]
Hello,

When using `Find All in Current Document` or `Find All in All Opened Documents`, that kind of result is displayed:

```
Circà "margine" (3 risultati in 1 ducumenti frà 1 ducumenti circati)
  C:\Users\patriccollu\Downloads\corsican 201203.xml (3 risultati)
	Line 854:                 <MarginsBorderEdge title="Margine è bordu">
	Line 855:                     <Item id="6201" name="Margine di piegatura"/>
	Line 932:                     <Item id="6607" name="Preferenze di margine (Unita : mm)"/>
```

Everything is translated, excepted the word "**Line**" preceding each line number. Would it be possible to localize this word?

Thanks,
Patriccollu.

**Comment by sasumner** [comment]
@Patriccollu 

It appears to be possible; example:

![image](https://user-images.githubusercontent.com/30118311/101049616-af069780-3551-11eb-8089-c910b86243de.png)

Unless @donho or someone else has an objection to making this translatable, I will take on the task of doing it.

And then I will change my own translation to simply "L" :-)

**Comment by sasumner** [comment]
Oh, wait.  In the above example the line numbers had the default lexing color/style setup.
If one changes that, it shows that it does NOT lex correctly:

![image](https://user-images.githubusercontent.com/30118311/101082736-f012a200-3579-11eb-82dc-a4337042e8a2.png)

It would probably work if the translation text was always four characters in length, but that's probably not reasonable.

We probably don't want to get into changing the lexer to make this work. :-(

But...I will take a look at it...

**Comment by sasumner** [comment]
A bit more info:

Yes, changing this would involve changing the lexer; here's the offending code that ties the text for "Line" to being 4 characters:  https://github.com/notepad-plus-plus/notepad-plus-plus/blob/fefdbc9cad7bbe4f505adf184147e7daae29a73f/scintilla/lexers/LexSearchResult.cxx#L65

If a change is to be implemented, probably the text for "Line" (whatever the translation) should be restricted to non-space characters, and then the lexer can look for the first space character to determine where it ends.

There are some other problems with the lexer code as well:

* Since the text for "Search" is translatable, user in the translation could begin that text with a space or with a tab character, making the "Search" line be lexed as if it is a file-header line or as a "Line" line, because the lexing code only examines the first character of each line in the "Search result" window to determine the line's "type" ("Search", filepath, or "Line").  Suggested fix:  strip off any space/tab characters at start of user's translation string.

* the styling of the line number data in the "Line" lines actually begins one character position too soon, so that the styling affects the space before the line number; example:
![image](https://user-images.githubusercontent.com/30118311/101184740-0e7ea900-361f-11eb-95cc-fb9f6a602b1a.png).  Suggested fix: Simple to just skip over the space before beginning the styling of line-number digits.

**Comment by donho** [comment]
I do understand that the translator's role is make all translated.
However, even for a non-English speaker who doesn't know the word "Line", he/she will understand the meaning of "line", with the context and some double-clicking. 
Considering between the complexity of coding (the cost of maintenance) and the gain of translation of this word for the users, it won't be implemented.

**Comment by Patriccollu** [comment]
@donho I'm (just) a little bit disappointed ;-) but I understand your concerns regarding the code maintenance.
@sasumner Thanks a lot for your work in related PR to answer my request in a very responsive way and @ArkadiuszMichalski for your comments.

Cheers,
Patriccollu.

**Comment by sasumner** [comment]
@Patriccollu  I guess it took one more person -- @ArkadiuszMichalski -- to do the convincing that this was a necessary thing to do.  :-)
