### ISSUE TITLE
Heading message in alert Box is Gramatically Incorrect.

### ISSUE THREAD

**Issue by sumitgsh** [notepad-plus-plus/notepad-plus-plus#9259]
![Notepad++error](https://user-images.githubusercontent.com/43777569/102011677-cde40580-3d6b-11eb-9ca6-3784c848b671.png)

### Description of the Issue

Even though the default language is set to English, but when an alert box appears the spelling of workspace has wrongly appeared

Its like-Folder as worspace(it should be workspace)
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by sasumner** [comment]
To pinpoint the problem better without a lot of reading, here it is:

![image](https://user-images.githubusercontent.com/30118311/102012218-1de4ad00-3d17-11eb-9b7a-b646a8ddc32f.png)

`Worspace` should be `Workspace`

This "bug" will only happen _before_ a "Localization" language is chosen, i.e. it does not appear because of what is in "english.xml" (those contents are correct).

This happens because the text that appears in the code is wrong; see [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5e96dd01664d8e7bf00bf2748862ffa68a575b4a/PowerEditor/src/WinControls/FileBrowser/fileBrowser.cpp#L1063).

Reference version of N++: 7.9.1 (because OP skipping filling in Debug Information)

**Comment by mere-human** [comment]
@sasumner Please, take a look at my PR.
I didn't change the string ID "FolderAsWorspaceSubfolderExists" though.

**Comment by sasumner** [comment]
>I didn't change the string ID "FolderAsWorspaceSubfolderExists" though.

Not necessary to change.
It's just a spelling mistake in the code.
User doesn't see it.
