### ISSUE TITLE
incorrect sorting in Russian alphabet

### ISSUE THREAD

**Issue by Fossius** [notepad-plus-plus/notepad-plus-plus#927]
"ё" must be after "e", now it's the last letter
see Russian alphabet
А а   Б б   В в   Г г   Д д   Е е   Ё ё  Ж ж    З з   И и   Й й   К к   Л л   М м  Н н    О о   П п   Р р   С с   Т т   У у
Ф ф   Х х   Ц ц   Ч ч   Ш ш  Щ щ  Ъ ъ  Ы ы  Ь ь   Э э   Ю ю   Я я

**Comment by xylographe** [comment]
NPP uses ordinal string comparison when sorting.

**Comment by jonandr** [comment]
I thought about this when I made the latest changes to the sorting code a few months back. The problem is that you can't reliably detect automatically if the user wants an ordinal sort or something else, so you'll have to add an option for every language. Some languages, like Swedish, will require *two* options. This greatly increases GUI complexity.

**Comment by ordtrogen** [comment]
Is it worth keeping this issue open? It's 3.5 years old...

**Comment by chcg** [comment]
@ordtrogen Thanks for bringing this up again. After all this time no developer taking care of it I think it could be closed.
