### ISSUE TITLE
Colors for marking styles as per #8983 not showing in latest version

### ISSUE THREAD

**Issue by SherylHohman** [notepad-plus-plus/notepad-plus-plus#9278]
### Description of the Issue
Love the concept of this new feature #8983. 
Unfortunately, After multiple restarts, changing and resetting themes, I cannot get the colors to show up.  

On the other hand, I learned about this marking feature, which is something I really wanted, but did not existed (I had a very limited semi-workaround, but it meant I could not use find for find next). So thanks!
If I can get this new color preview to show up, the highlight/mark class of features would be *super* useful.

I am using the default theme, on windows 10.

### Steps to Reproduce the Issue
1.  The colors simply do not show up in the related menu items. 
There is space to the left of the text, where the color samples should be though.

### Expected Behavior
Color samples for style 1, style 2, etc to show up in the menus as per #8983,  
and as shown in (https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9089#issue-513522692)

### Actual Behavior
The space where the color samples should appear are "transparent" - it just looks like the background.

### Debug Information
Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.1198
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
>Love the concept of this new feature #8983.

Thank you. :-)

>Unfortunately, After multiple restarts, changing and resetting themes, I cannot get the colors to show up.

That's because there has been no Notepad++ release yet which incorporates this new feature.

If you are going to browse github for these types of enhancements, please learn how to tell when/if something has been released.  Here's how:

Find the commit for the change:  For 8983 it is seen on that issue page like this:
![image](https://user-images.githubusercontent.com/30118311/102634852-73a6c400-4120-11eb-95a7-8f1f4514a064.png)
Click on the blue c28116a link (on that page, not in the above which is just a screenshot).

You will go to a page where you will see something like this:
![image](https://user-images.githubusercontent.com/30118311/102635021-b4064200-4120-11eb-9ce3-017bae2b47a8.png)
See where it says "master"?

If it had been in a released version of Notepad++, it would show you the release version, like this (which is for another feature):
![image](https://user-images.githubusercontent.com/30118311/102635215-06476300-4121-11eb-98ee-9c68e7e23fa8.png)
