### ISSUE TITLE
The extension does not open in the style I want

### ISSUE THREAD

**Issue by schmidt39** [notepad-plus-plus/notepad-plus-plus#9302]
Online translator.

File x.inc
Opens in syntax "Pascal" by default.

My task is to open it in syntax "C++".
Settings > Preferences > Language > Available items > Pascal to "Disabled items".
Settings > Style Configurator > C++ User ext > inc
I closed x.inc, restarted Notepad++, opened x.inc, and what do you think is going on?
It just looks like regular text and no style is selected!!!

I can do this:
Language > C > C++, ok it's works.
But if I close the file and open it again, then I see normal text again!!!

You can "say go to Settings > Style Configurator > Pascal and change the style as you want",
but no, this curve syntax, it does not understand comments like /* this */ and it comments even the usual lines.

You have so many settings, but I can't do this simple obvious thing? I'm grossed out.

I can live with the fact that you are forced to use the language by default depending on its extension. But if I want to change this and turned off this unnecessary language and registered the file extension in another language, then it must now open in this other language!

**Comment by sasumner** [comment]
You could have just asked the question...
You didn't have to add something like this:  "You have so many settings, but I can't do this simple obvious thing? I'm grossed out."

But really, questions belong here:  https://community.notepad-plus-plus.org/
If there is no real resolution to a question's discussion on that site, then come here and create an issue.
And when you are creating an issue, follow the template, don't simply delete out the template.

The resolution to your issue is to open `langs.xml` and to move the `inc` extension from the Pascal language to the C++ language.

**Comment by schmidt39** [comment]
Thanks, it works. I don't know why I didn't think of it.

**Comment by schmidt39** [comment]
> You could have just asked the question...
> You didn't have to add something like this: "You have so many settings, but I can't do this simple obvious thing? I'm grossed out."
> 
> But really, questions belong here: https://community.notepad-plus-plus.org/
> If there is no real resolution to a question's discussion on that site, then come here and create an issue.
> And when you are creating an issue, follow the template, don't simply delete out the template.
> 
> The resolution to your issue is to open `langs.xml` and to move the `inc` extension from the Pascal language to the C++ language.

Thanks, it works. I don't know why I didn't think of it.
