### ISSUE TITLE
MATLAB - function collapsing/minimizing

### ISSUE THREAD

**Issue by poulet67** [notepad-plus-plus/notepad-plus-plus#9303]
If one minimizes a function, it will stop at a %} (maybe it's just the }, haven't played around with it too much)  instead of end keyword

![image](https://user-images.githubusercontent.com/63618022/103107041-88d39500-45ef-11eb-95b1-7966bfb4391b.png)

![image](https://user-images.githubusercontent.com/63618022/103107048-94bf5700-45ef-11eb-8170-a9151f118f63.png)

**Comment by chcg** [comment]
Matlab code folding is handled by https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/lexers/LexMatlab.cxx and therefore depends on a fix from https://www.scintilla.org/ .

Probably the issue is located somewhere at:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/lexers/LexMatlab.cxx#L202
Likely related to fix for https://sourceforge.net/p/scintilla/bugs/1902/. So I'm not completely sure if this is a bug as the comment should start with %{ from what I read in the scintilla bug ticket.

**Comment by vinsworldcom** [comment]
@sasumner 

Agree with @chcg , the syntax shown in the issue above seems to be not valid MatLab so the Lexer behavior would be undetermined.  Adding the appropriate `%{` to start the comment parses correctly with both current Notepad++ SciLexer.dll 4.2.0 and the new SciLexter 4.4.6.

I think this can be closed?

Cheers.
