### ISSUE TITLE
Rename localization files to common and well known names

### ISSUE THREAD

**Issue by alexhass** [notepad-plus-plus/notepad-plus-plus#9307]
### Description of the Issue
Everytime I update the MSI setup with new language files I need to search and *guess* what _Language/region decimal ID_ the localization file names may be. Can we rename the files to something more common so it is world-wide 100% safe, please?

I suggest we use _Language/region decimal ID_ or _Language/region tag_ from https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/available-language-packs-for-windows list as file names. Normally I see everywhere language codes like "en", "de" and if a dialect is used "ch-TW". It is 100% safe what this means, where "HongKongCantonese" is not clear to me.

**Comment by chcg** [comment]
See also https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f617325006e7b7f22340b0a49f60a82e3d0392b4/PowerEditor/src/Parameters.cpp#L3834-L4015 for the transformation between the iso language code and the file name.

**Comment by alexhass** [comment]
OMG. 

I wasn‘t aware that such a useless transformation exist in code. The code could be simplified than a lot, too. This only proves that the current mapping should be removed and simlified with iso codes.

**Comment by alexhass** [comment]
And the name of the hong kong cantonese sounds also wrong... in wikipedia it is named „Yue Chinese“.

**Comment by Edditoria** [comment]
I am from Hong Kong. Please, come on. We are not exactly speak and write in Yue Chinese. You won't say English in United States and United Kingdom are the same thing, right?

In Notepad++ setup, the Yue language is missing (and it highly depends on what region you are talking about). Currently, there is only Hong Kong Cantonese.

Sorry that the ISO "system" create such kind of problem. We Hong Kong people live in the real world as a mankind. Don't make us to abandon our culture and follow the "system"/"wiki".

**Comment by sasumner** [comment]
@Edditoria 

>In Notepad++ setup, the Yue language is missing

Translations in Notepad++ are largely user-provided.
Can't you just create your own specific one, and then submit it for inclusion, and become the maintainer of it?
Of course, maybe I am misunderstanding what is being said.

**Comment by Edditoria** [comment]
@sasumner LOL. I'm afriad you are misunderstanding something. I'm the maintainer of Hong Kong localization. 😂

**Comment by sasumner** [comment]
@Edditoria Sorry, not being close to the situation, I misunderstood what your complaint was about or what you were asking for, if it wasn't a complaint.

**Comment by alexhass** [comment]
Nobody said you cannot use or speak your language. 

I only say we should name rhe files by the language id or well known iso codes based on https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/available-language-packs-for-windows. That simplifies the npp code and setups. Currently I have no idea language id s hong kong cantonese is. Can you check the list and find out, please?

**Comment by Edditoria** [comment]
@alexhass If you are founding the code for scripts, ”Chinese (Hong Kong SAR) | zh-HK (no longer used) | 0x0c04 | 3076“ is the only code representing Hong Kong region.

As I wrote above, in common software, please assign zh-HK, e.g. Google Chrome.
Some software doesn‘t support zh-HK. Please assign zh-TW, e.g. CDBurnerXP.
For development software like Notepad++, please assign en-US.

**Comment by alexhass** [comment]
It is really fascinating that no operating system supports you, but notepad++ tries it. 

From my point of view software schould translated how you „write“ and not how you speak. In Germany we also have many dialects and honestly I do not understand all, but it is all german. It is the same like texas... you do „not“ understand them if they speak, but they write in standard english. 

I would never expect a software translated to any dialects. In German all is „high german“ including switzerland with swiss german. That is normal... but software never translated with a dialect.

**Comment by donho** [comment]
> It is really fascinating that no operating system supports you, but notepad++ tries it.

So? If you don't want to follow the standard, then you create standard.

> I would never expect a software translated to any dialects. In German all is „high german“ including switzerland with swiss german. That is normal... but software never translated with a dialect.

It's just your viewpoint - I'm glad I don't have the same one.

**Comment by xslidian** [comment]
[Likely Subtags](https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/likely_subtags.html) is a good source.
It lists default mappings determined mostly by population and changes over time:
- `und_HK` → `zh_Hant_HK` (Formal documents in Hong Kong were written with minimal accents)
- `yue` → `yue_Hant_HK`
- `yue_CN` → `yue_Hans_CN`

It's sad that M$ doesn't provide a Cantonese language pack.
There's a defined language ID for HK Cantonese (`0x048E` == `zh-yue-HK`) in [their document](https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-LCID/%5BMS-LCID%5D.pdf), but I don't think it's compatible with the current Windows locale configuration.

Considering Cantonese is widely used in HK as the de facto oral language, I think it's okay to add an exceptional mapping: `und_HK` → `yue_Hant_HK`.
`0x0c04` can be used. Only the standalone language pack is deprecated.

If Edditoria would like, he may want to maintain another zh_Hant_HK variant for the elderly. Both can be presented to the end users for selection.

**Comment by Edditoria** [comment]
@xslidian I considered very carefully how to localize this software. There are 2 directions:

1. Follow the patterns of software ecosystem.
2. Stick with how we speak in our real life.

This localization is workong on (2) with some balance (or say, compensation) on (1).

NPP's philosophy is surprisingly good way to reserve HK's culture for **next generation**.

The ecosystem emphasis on "text" people write. It's all about Tranditional Chinese for us. So, usually we accept zh-TW, i.e. there is no need zh_Hant_HK because they share (almost) the same texts. We are higly inspired by Taiwan in software industry in 80s/90s, e.g. technical terms we use in MS-DOS. If users want to follow the patterns, Taiwan localization is exactly how we consume software applications.

What I am doing is to "click what we speak in daily life". This is something like how a Hong Kong human talk to the machine. It is NOT about texts.

For example, we really say "size" rather than "大細 (big or small)" in HK Cantonese. I keep this in NPP.

I kept doc in my own repo: https://github.com/Edditoria/notepad-plus-plus-localization-hong-kong
Please see the README for philosophy.

There are some Hongkongers discussing on-and-off-line. We will improve on this continuously :)

**Comment by alexhass** [comment]
Translation is always a burden. You never find enough people who are willingly to do the job for years. In Drupal we have something names translation inheritance.

The process is as following 
- Lets say - someone translates all to "de" (German).
- Than the Austrian comes in picture... they search for all the words in German (DE) they do not like and do the translation for these few words to de_AT
- And the Switzerland people do the same. They do translation from "de" to "de_CH"

On the end the effort to translate the SwissGerman or AustrianGerman is limited. It may be guessed 2% difference only.

From what you write it sounds like you are in the same situation. Basic TW is for all TW people and than your dialect comes in and you may also need to change only a fraction of the TW strings? We would end up with two translations - the one for TW people and your dialect. Both can be maintained and kept up to date. Are you doing it this way or is is community chaos? :-)

**Comment by xslidian** [comment]
Software giants like M$ used to provide both `zh_TW` and `zh_HK`. 
They did exactly what alexhass expected: 
* Translate everything to `zh_Hant`(Traditional Chinese), and make it `zh_TW` (de facto equivalent of `zh_Hant` in the industry)
* Replace a few terms with their Hong Kong version, and make it `zh_HK`.

However, this is a written form of Chinese, different from the colloquial Cantonese (`yue`) spoken by most HKers in daily life. 
It's heavily used because people can communicate in it, even when they don't understand each others' dialects.

The modern Hong Kong Cantonese is mostly a mixture of [written Cantonese](https://en.wikipedia.org/wiki/Written_Cantonese) and English. Although it's not yet standardized, it's a major culture in HK. 
Edditoria's `hongKongCantonese.xml` reflects this culture perfectly. 

Here's my suggestion:
old name | new language tag | M$ language id | note
-- | -- | -- | --
`chineseSimplified.xml` | `zh_Hans` | 0x0004 | Simplified Chinese
`hongKongCantonese.xml` | `yue_Hant_HK` | 0x048E | Hong Kong Cantonese
`taiwaneseMandarin.xml` | `zh_Hant` | 0x7C04 | Traditional Chinese

With the help of [the CLDR Likely Subtags data](https://github.com/unicode-org/cldr-json/raw/master/cldr-json/cldr-core/supplemental/likelySubtags.json), you automatically get:
user locale config | target in CLDR Likely Subtags | final target (language file)
-- | -- | --
?_CN | zh_Hans_CN | zh_Hans 
?_HK | zh_Hant_HK | zh_Hant
?_MO | zh_Hant_MO | zh_Hant
?_TW | zh_Hant_TW | zh_Hant
zh_SG | zh_Hans_CN | zh_Hans
zh_MY | zh_Hans_CN | zh_Hans
yue_CN | yue_Hans_CN | (no perfect match; no volunteer translations available)
yue_HK | yue_Hant_HK | yue_Hant_HK
yue_MO | yue_Hant_HK | yue_Hant_HK
ko_CN | ko_Kore_KR | ko
en_MO | en_Latn_US | en

Extra coding may be needed for the installer, if older Windows versions can't select the correct target.
It's normal that `yue_HK` don't show up automatically, since M$ doesn't provide an easy visual way to change system-wide locale to `yue`.

**Comment by Edditoria** [comment]
I have different view with system engineer. User-selectable options should be good for understanding for that user(s). Even local Hong Kong people won't understand what is "zh_Hant_*". I doubt general people in Taiwan understand what is "zh_Hant" vs "zh_Hans". For language files, existing file namespace (e.g. taiwanMandarin.xml) is good enough.

But I agree that there can be a XML tag or something else for lang config. May be one consolidated file, acting as a dictionary for both human and OS, could help engineer like @alexhass ? In my experience in my OEM PC works, still need some scripting (batch, bash, etc.) because each piece of software may have different setup. MSI is not that perfect.

**Comment by alexhass** [comment]
We are only talking about clear and common FILENAMES here. In user interface we should still use user friendly human readable names.

if you habe any objections about msi you can tell me by mail I know it is the best setup available. Customizable and it has repair mode and so on. No other setup available can customized by admins - none! The only thing I‘m aware of where people with limited knowledge complain about the local cachong of the msi. But without you cannt repair and disks are large enough. Clearly a false argument. All offtopic here...

**Comment by xslidian** [comment]
The change won't affect existing end-users. 
Only underlying files and unnecessary code will be refactored.
New and clean installs may benefit from the automatic selection of the dropdown box.

Likewise, 99.99% of moviegoers in Hong Kong don't need to understand what `QMT` and `QTM` stand for. 

`Hans` & `Hant` are simply [ISO 15924](https://en.wikipedia.org/wiki/ISO_15924) script codes, like `Latn` for Latin.
Using these two tags makes sure a Cantonese translation made by a Canton-based team won't pollute the UI of Hong Kong users (with their default Windows configuration).

**Comment by graphemecluster** [comment]
I am a contributor to Edditoria/notepad-plus-plus-localization-hong-kong. I think I should point out that the plan to add Hong Kong Cantonese to Notepad++ is originally an idea by @donho, the author of Notepad++.

In my opinion, as we are not going to implant `zh_Hant_HK` in contrast to `zh_Hant_TW`, we could map this translation into `zh_Hant_HK`, so that Hong Kong users are more likely to know the existence of this translation. I don't know whether 0x0404 and 0x0C04 are available for `zh-TW` and `zh-HK` respectively, but it would be great if it does.

FYI, Cantonese (Hong Kong) exists in language settings of both YouTube subtitles and Apple devices.

ISO 15924 is the codes for writing systems, not languages. For example `Jpan` and `Kore` are aliases for `Hani + Hrkt` (while `Hrkt` = `Hira + Kana`) and `Hani + Hang` respectively. So `Hant + Latn` would be the codes for this translation.

**Comment by myh66** [comment]
One country, two systems multiplied by three

**Comment by donho** [comment]
Notepad++ has its own installation system, so some exceptions could be the standard in Notepad++
