### ISSUE TITLE
(Mouse) Double click / (Keyboard) Enter to add associations

### ISSUE THREAD

**Issue by dogancelik** [notepad-plus-plus/notepad-plus-plus#932]
Under _Preferences > File Association_, it would be nice if a user could:
- move extensions just by double clicking on them to Registered exts list box.
- navigating through extension list box with up/down arrow keys and pressing enter on keyboard to move them to the registered extensions list box.

I think it would help users a lot and can save time.

If we assume user's mouse is not working, there is no way to add associations after first attempt:
1. User opens assoc. dialog
2. User navigates through list box on far left using Tab key, jumps to second list box on left
3. Selects an extension and _Tab_s to <kbd>-></kbd> button and presses <kbd>Space</kbd> to add it to Registered exts list box
4. Button loses focus and you can't use <kbd>Tab</kbd> or <kbd>Shift + Alt</kbd> again.

**Comment by h-h-h-h** [comment]
Moving the items with <kbd>Left</kbd>/<kbd>Right</kbd> isn't bad either.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
