### ISSUE TITLE
Column-copy from Find result window gives only last line

### ISSUE THREAD

**Issue by rhermsen** [notepad-plus-plus/notepad-plus-plus#933]
(also described here: https://notepad-plus-plus.org/community/topic/10437/column-copy-from-find-result-window-gives-only-last-line)

Starting with version v6.7.9 (.1) column-mode, copy in the Find window doesn’t work anymore.
Highlighting the column to copy (using Alt + mouse selection) does work >but : copy the too clipboard (right-mouse-button, and copy from the pop-up selection window) > paste results in only the full last line (without containing line number).

Also tried to rename the plugins folder (like suggested here https://notepad-plus-plus.org/community/topic/10202/deleting-in-column-mode-doesn-t-work-as-expected), but still same behavior, no column-mode copy in the Find result window.

With v6.7.8.2 copying in column-mode in the Find results window is working normally.

Suspect related with:
https://notepad-plus-plus.org/community/topic/10436/containing-line-numbers-from-find-window-not-copied-anymore
https://notepad-plus-plus.org/community/topic/10423/copy-text-from-search-text-in-folders
(and maybe: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/68)

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
