### ISSUE TITLE
Unable to copy line data from search results in N++ 7.9.2

### ISSUE THREAD

**Issue by happyduck1** [notepad-plus-plus/notepad-plus-plus#9334]
I just noticed with the new 7.9.2 that I am unable to right-click copy from the search results window. 
All I seem to get in the clipboard buffer – that I can tell when I paste later – is a single blank line – at least I think that is what it is.

Here’s a picture which shows more detail about what I’m doing, and choosing from the menu. Sorry, for german language of the screenshot – that’s how I normally use NPP.

![image](https://user-images.githubusercontent.com/61066437/103445625-aaaec680-4c44-11eb-9c5d-ed0fc10601f3.png)

Please let me know if you need any more information on this issue.  I would be much pleased to provide.

I also posted this here:  https://community.notepad-plus-plus.org/post/61292

**Comment by happyduck1** [comment]
Also, I think my screenshot shows confirmation of #9306 !
See the title bar of the search results window, where it says "Search resu" -- that's all you can see.
But...it is clearly in english when it should not be!

**Comment by sasumner** [comment]
@happyduck1 

The lack of copy happens because [THIS CODE](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/3373756afbeb66cea8be36087538aab12a171491/PowerEditor/src/ScitillaComponent/FindReplaceDlg.cpp#L3622) was not changed when the "Line" text was made translatable.
If you'll recall, prior to 7.9.2, you had the English "Line" appear instead of the "Zeile" you see now, even though most of the rest of the text of the UI was in German.

For the historical record, I put forth a PR ( #9233 ) that would not have allowed this problem to occur (see [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9233/commits/43fffd8c4aaf52a2a45d2e4d3ac29be7c8fd2c96#r550820514) ), but my PR was rejected as "too complicated" and I was not given the chance to make it "simpler" so that it could have eventually been accepted.  The originating issue ( #9224 ) was completed by someone else, and thus the origin of the bug.

**Comment by donho** [comment]
@sasumner @happyduck1 
Sorry, I don't see any bug or regression here. Am I missing somethings?

**Comment by donho** [comment]
@sasumner @happyduck1
I see where is the problem now.
