### ISSUE TITLE
Notepad++ crashes when searching in large binary files

### ISSUE THREAD

**Issue by mere-human** [notepad-plus-plus/notepad-plus-plus#9456]
Originally reported on the Community forum https://community.notepad-plus-plus.org/topic/20641/find-in-all-files/

### Steps to Reproduce the Issue

1. Open menu _Search > Find in Files_
2. Select a directory with some large binary files (e.g. a game directory)
3. Enable "In all subfolders"
4. Type any text e.g. "1"
3. Start search

### Expected Behavior

Search completes normally

### Actual Behavior

Notepad++ crashes at some point

### Debug Information

Notepad++ v7.9.2   (64-bit)
Build time : Jan 27 2021 - 21:15:12
Path : e:\Development\notepad-plus-plus\PowerEditor\visual.net\x64\Unicode Debug\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.746
Current ANSI codepage : 1252
Plugins : none

---

The crash is in the `SciLexer.dll`.
The `position` variable seems to be overflown.
Call stack:
`
>	SciLexer.dll!Scintilla::LexAccessor::operator[](__int64 position) Line 78	C++
 	SciLexer.dll!FoldSearchResultDoc(unsigned __int64 startPos, __int64 length, int __formal, Scintilla::WordList * * __formal, Scintilla::Accessor & styler) Line 137	C++
 	SciLexer.dll!Scintilla::LexerModule::Fold(unsigned __int64 startPos, __int64 lengthDoc, int initStyle, Scintilla::WordList * * keywordlists, Scintilla::Accessor & styler) Line 126	C++
 	SciLexer.dll!Scintilla::LexerSimple::Fold(unsigned __int64 startPos, __int64 lengthDoc, int initStyle, Scintilla::IDocument * pAccess) Line 51	C++
 	SciLexer.dll!Scintilla::LexInterface::Colourise(__int64 start, __int64 end) Line 76	C++
 	SciLexer.dll!Scintilla::Document::EnsureStyledTo(__int64 pos) Line 2240	C++
 	SciLexer.dll!Scintilla::Editor::StyleToPositionInView(__int64 pos) Line 5099	C++
 	SciLexer.dll!Scintilla::Editor::IdleWork() Line 5175	C++
 	SciLexer.dll!ScintillaWin::IdleWork() Line 1856	C++
 	SciLexer.dll!ScintillaWin::WndProc(unsigned int iMessage, unsigned __int64 wParam, __int64 lParam) Line 1393	C++
 	SciLexer.dll!ScintillaWin::SWndProc(HWND__ * hWnd, unsigned int iMessage, unsigned __int64 wParam, __int64 lParam) Line 3456	C++

`

**Comment by Uhf7** [comment]
I can reproduce it. It is interesting, because the the crash is caused by totally different mechanisms in Windows 32 and Windows 64, and that different are the error messages/reports too. Thank You @mere-human for this 64-bit error report, it confirms my suspicion.

The bug doesn't depend on how many files you search in how many sub directories, but it depends on how many search results you produce. The search over files is executed in two steps:
- Search all files and add the search results to `_pMainFoundInfos`.
- Expand the search result into the Search Results window to present them to the user.

The 32-bit version of Notepad++ crashes at the 1st step, the 64-bit version crashes on the 2nd step.

### Steps to reproduce the issue:
- Unpack the portable versions of Notepad++ into directories of your choice. I'm talking about `npp.7.9.2.portable.zip` and `npp.7.9.2.portable.x64.zip`, from the official Notepad++ site. Users with 32-bit systems can test the 32-bit system only.
- Unzip my great test zip file, consisting of 20 text files with only `a` characters in it, to a directory of your choice. Here is the link:
[Issue_9456.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5906562/Issue_9456.zip)
- Then, start a Find In Files search over this directory. Search without regular expressions. Search `a`, to find the maximum number of search results, Search `b`, to find nothing. Compare, what happens. Report the results here, please. Thank You.

**Comment by Uhf7** [comment]
I debugged again. The two steps I mentioned in my previous post are in the same loop. It's no 2-pass processing, as I may have suggested misleadingly.

There are limits:
- In the 32-bit version, the vectors with the search result infos cannot be extended,  because there is not enough consecutive memory left in the memory space of the process. This applies to `_pMainFoundInfos`, `_pOldFoundInfos`, and some others. The problems here started at my system at about 3.000.000 hits.
- In both versions, the document size of the buffer with the find results cannot be larger than `MAX_INT` bytes. This limits the number of search results as follows: 2048 bytes per displayed line, the buffer can be full after 1.000.000 hits.

It's not easy to fix the problems. One measure should be to limit the number of results from a single search to 10.000. Scrolling in a longer list of search results is no fun anyway.

But then remains the task of limiting the document size of the find results buffer. This must work for more than a single Find command, because this size accumulates over several Find commands. And then there is the size of  `_pOldFoundInfos`, which accumulates too and can become a problem for the 32-bit version.

**Comment by mere-human** [comment]
Interesting results. This seems like a complex issue indeed.

Still, I think Notepad++ should search only non-binary files by default. 
There is even a dedicated issue for this #9445

**Comment by Uhf7** [comment]
> Still, I think Notepad++ should search only non-binary files by default.

This has nothing to do with the crashes in my opinion. It may reduce the probability of crashes, but this is not the right way to prevent them. 

So, blocking the search of "binary" files is more a convenient function for all users using the "Folder As Workspace" philosophy in their workflow. I don't. 

What I would appreciate, is the possibility to search all files added to a, what it is called in this software, "Project Panel". The only thing Notepad++ lacks is the capability of searching all files contained in a Project Panel. And because of this lack users complain constantly: please, let us exclude the evil large binary files from searching, because they increase the probability of a crash.

Crap! 

First - The search function should never crash, no matter what files are feeded into it.

Second - The "Folder as Workspace" philosophy does work only for projects, which contain mainly text files in this folder. In all other cases, using the Project Panel gives better results, because the files included to the project can be selected more precisely. But what is needed desperately here is a function to search all files within a Project Panel.

**Comment by sasumner** [comment]
@Uhf7 said:

>...possibility to search all files added to a, what it is called in this software, "Project Panel". The only thing Notepad++ lacks is the capability of searching all files contained in a Project Panel. 

You said all that and you didn't link to #8125 ??  :-)

**Comment by Uhf7** [comment]
> You said all that and you didn't link to #8125 ?? :-)

Yes, sharply watched.

**Comment by mere-human** [comment]
> This has nothing to do with the crashes in my opinion. It may reduce the probability of crashes, but this is not the right way to prevent them.

You're right. The crashes have to be fixed anyway.

> The only thing Notepad++ lacks is the capability of searching all files contained in a Project Panel.

This would be nice to have. 
Then it will be something akin to Look in - "Current Project" (rather than "Current Directory") in Visual Studio.

But as for me, when searching files in Notepad++ I usually specify the path. 
I don't use "Project Panel" or "Folder as Workspace" very often.

**Comment by sasumner** [comment]
As a user, I would like to use the "Project" features more, but @Uhf7 is correct, the lack of a way to search only the project files is a crippling omission.  But let's not get too far off track with _this issue_.  :-)

**Comment by afwn90cj93201nixr2e1re** [comment]
@donho Can you add visual part for 'file indexing' state too? Example: just try to search for something in '`Temp`' folder, app freezes and we can't decline it. Just copy paste code for displaying search progress in files.

**Comment by somanuell** [comment]
Today, I am once again bitten by crashes when searching in big directory structures with a lot of files.
I am absolutly certain that the crash has nothing to do with count of found occurences, as it happens at will with big random b64 strings, wich are NOT on my drive.
This bug (crash when searching) is **old, now, and very annoyning**.
_How can I help?_

**Comment by somanuell** [comment]
![image](https://user-images.githubusercontent.com/6695774/148051193-8a10f271-0407-4c67-a5ee-3703e1a8429e.png)

I can reproduce. Again, How can I Help?

**Comment by somanuell** [comment]
![image](https://user-images.githubusercontent.com/6695774/148051598-c3686c69-faeb-41d1-9f3c-e8a922c6380f.png)

Where can I found npp.pdb for:
Notepad++ v8.2   (64-bit)
Build time : Dec 30 2021 - 03:40:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1415
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll

**Comment by somanuell** [comment]
Progress were made in recent versions of notepad++ The perfectly reproducible crash which was occurring in one of my directory doesn't happen anymore, thank you!

But I still can reproduce a crash in another directory!
Notepad++ v8.3.3 (64-bits)

AGAIN: HOW CAN I HELP?

**Comment by somanuell** [comment]
![image](https://user-images.githubusercontent.com/6695774/160372545-a622534b-4646-4685-a053-38b02e8a359a.png)

**Comment by somanuell** [comment]
I have a reproducible directory with few dozens files, each one a few hundreth KB at most.
![image](https://user-images.githubusercontent.com/6695774/160441336-bf327bb8-18ae-416e-ab47-f4352ff59c47.png)

**Comment by somanuell** [comment]
After a painful bisection, I found the offending file which crashes notapadd++!
It is a pak file, for an electron application, of 214 KB.

@donho, I can't publicly share the contents of that file. Can you give me an email address where I can send the file?

**Comment by somanuell** [comment]
@donho The crash has nothing to do with Find In Files. My pak file crash n++ just when opening.
I ma currently debugging.

**Comment by somanuell** [comment]
I didn't find the root cause, yet, but I did find why it's crashing:

1. `FileManager::loadFileData` calls `fread` in a loop 
2. first round (`isFirstTime` is true) the static method `Utf8_16_Read::determineEncoding` returns `uni8Bit`
3. then `Utf8_16_Read::convert` is called, which in turn calls the instance method `Utf8_16_Read::determineEncoding`. That time the return value is `uni16LE_NoBOM`, because the Win32 API `IsTextUnicode` returns TRUE
4. Then `Utf8_16_Read::convert` allocates a new `m_pNewBuf` buffer, with the formula `newSize = len + len / 2 + 1`;

The file is 219 113 bytes in size.  blockSize is 131 076. The loop turns 2 times.
First turn: newSize = 196615
Second turn: newSize = 132056

Then `m_Iter16` WRITES BEYOND THE ALLOCATED SPACE.

The crash vanishes if I replace `newSize = len + len / 2 + 1;` by `size_t newSize = len * 2;`

Now, I am trying to understand the bug in `m_Iter16`...

**Comment by mere-human** [comment]
> Now, I am trying to understand the bug in `m_Iter16`...

My guess is that it stumbled upon done NULL bytes somewhere in the middle of the file which is unexpected. You can check the contents of the file in HEX to prove this theory of you want.

**Comment by somanuell** [comment]
The file is an electron pak file. It's binary! Of course there are null bytes...

**Comment by alankilborn** [comment]
Using a text editor to work with binary files is not a good idea.  Sure, it shouldn't crash, but there are many ways in which Notepad++ isn't ready to be a full hex editor.

**Comment by somanuell** [comment]
@alankilborn I strongly disagree.

1. writing beyond heap allocated buffers is, and always has been, a severe security bug.
2. you can't decide if a file is binary, unless you try to open it
3. Searching for a string in all files in a directory is a feature, that is rendered useless if it just crashes

**Comment by alankilborn** [comment]
>you can't decide if a file is binary, unless you try to open it

As a user, you usually know this, because you know what you are doing.
Of course it shouldn't crash, I already said that

My point was to simply point out that Notepad++ is not ready to be a hex editor, not yet...
So it is probably best if people don't try to use it as one.

**Comment by donho** [comment]
I do believe the issue is fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/126505180f82557aacd4fc432ef4382abb18b473
If it's not, please let me know - I will reopen it.
