### ISSUE TITLE
Sorting lines does not work if line ends with \n and not \r\n

### ISSUE THREAD

**Issue by baftek** [notepad-plus-plus/notepad-plus-plus#9476]
### Description of the Issue
When lines in a file does not end with \r\n but only \n the lines sorting is not successful.

### Steps to Reproduce the Issue
1. Lets assume a file with contents:
aa\r\n
bb\r\n
cc\r\n
aa\r\n
aa\r\n
where \r\n represents here whitespaces "carrier return" and "new line" and not slash and letter 'r' or 'n'
2. Go to Search -> Replace, 
3. select search Mode to "Extended"
4. replace '\r\n' to be '\n'
5. Go to Edit -> Line operations -> Sort Lines Lexicographically Ascending
6. Observe that nothing happened

### Expected Behavior
6. Lines should be sorted.

### Actual Behavior
Lines were not sorted when they end with just '\n'.
When lines end with \r\n sorting works just fine.

### Debug info
Notepad++ v7.9.1   (32-bit)
Build time : Nov  2 2020 - 01:03:56
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2004
OS Build : 19041.685
Current ANSI codepage : 1250
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll

**Comment by sasumner** [comment]
>select search Mode to "Extended"
replace '\r\n' to be '\n'

To change line endings, you should not do it this way.
Do it this way:  _Edit_ menu > _EOL Conversion_ > ...

Sorting used the file's EOL type in order to partition the lines for sorting.
The current EOL type can be seen on the status bar (e.g. `Windows (CR LF` )

Otherwise, see the related issue #7735
