### ISSUE TITLE
Docked windows do not work when the -nosession command line option is used

### ISSUE THREAD

**Issue by gregmarkv** [notepad-plus-plus/notepad-plus-plus#9487]
### Description of the Issue
Docked windows do not display when Notepad++ is started with the -nosession command line option. This issue did not occur in version 7.9.1.

### Steps to Reproduce the Issue
1. Start Notepad++ with the -nosession command line option.
2. Attempt to open a docked window (View->Document Map for example)

### Expected Behavior
The docked window should display.

### Actual Behavior
The docked window does not display.

### Debug Information
Notepad++ v7.9.2   (32-bit)
Build time : Dec 31 2020 - 03:58:36
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.746
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by thomassmith311** [comment]
Tested and confirmed.

![image](https://user-images.githubusercontent.com/19561856/107124714-8eb9c880-6873-11eb-831b-272fc77cb017.png)

The docked window actually does display, but it has to be dragged out. When viewing the Document Map, I have to move my cursor to the far right side, click, and drag to the left.

![image](https://user-images.githubusercontent.com/19561856/107124934-a47bbd80-6874-11eb-8b82-dcf3098ab8ca.png)
![image](https://user-images.githubusercontent.com/19561856/107124942-ac3b6200-6874-11eb-92ab-d9166592e23f.png)

**Comment by mere-human** [comment]
There were at least several similar issues: #9341 and #9363
Seems the problem wasn't solved completely.

**Comment by sakkamade** [comment]
@mere-human  It may already be solved, but there was no official version comprising that https://github.com/notepad-plus-plus/notepad-plus-plus/commit/67234d22697f054e2f3b6985a87195eb00744bcb fix.

**Comment by thomassmith311** [comment]
> @mere-human It may already be solved, but there was no official release comprising that [67234d2](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/67234d22697f054e2f3b6985a87195eb00744bcb) fix.

I tested that fix you just linked to and can confirm that it does solve the problem (version 7.2.9, on Windows 10 PC, no plugins).

**Comment by dev-masta** [comment]
I've been struggling with this same issue for a while now, and now I see that there is already a fix? Cool.
How do I compile it and start using it, February 6th was a long time ago.

**Comment by pryrt** [comment]
While verifying the [recent report in the forum](https://community.notepad-plus-plus.org/topic/21076/nosession-behavior), I confirmed this issue still exists:
* Fresh v7.9.5-64bit portable
* Install NppFTP
* Dock the NppFTP window
* exit/re-load, the NppFTP window stays visible/docked
* exit.  Re-run with `notepad++.exe -nosession` -> the NppFTP window is _not_ visible
* exit. re-run normally -> the NppFTP window is visible again

It appears that, while some fixes were implemented (the aforementioned 67234d2 claims to be in v7.9.3 - v7.9.5), that doesn't seem to be sufficient to cover all occurrences of this problem.  

```
Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\usr\local\apps\npp\npp.7.9.5.portable.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.1256
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll 
```

**Comment by pryrt** [comment]
And unlike @thomassmith311 Feb 6 report with the Document Map, the NppFTP window isn't even turned on: when I open it normally, you can see the window, and the plugin menu shows the checkmark next to "Show NppFTP Window", showing that it's open.  When I open with `-nosession`, that menu does _not_ have the checkbox.  See screenshots: ![image](https://user-images.githubusercontent.com/17455758/116095564-62853b00-a65d-11eb-8d33-676e29518db0.png)
... so it's not just that the window was made tiny... it was completely closed.

**Comment by jimmydevine** [comment]
I am running into a problem with nppftp opening when -nosession in use as well, similar setup

```
Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.928
Current ANSI codepage : 1252
Plugins : mimeTools.dll nppAutoDetectIndent.dll NppConverter.dll NppExport.dll NppFTP.dll 
```

**Comment by ArkadiuszMichalski** [comment]
@donho It's not a regression introduced by https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8005? Because of this one panel, the others are disabled, which has not happened before (before 7.9.2). If the current behavior is intentional then this issue can be closed.

**Comment by jimmydevine** [comment]
IMO panels like this are not session related and should not be affected by -nosession.  I use -nosession because when I open a new instance of notepad++ (with -multiInst) I don't want previous files to open with it as they are likely not relevant, but the nppftp panel is always relevant to me because 99% of the time this is the first thing I go to.

**Comment by pryrt** [comment]
If you want to make an official decision as to whether or not to show built-in docked windows when used with `-nosession` (as you already have), that's one thing, and perfectly reasonable for the application developer to do.  But plugins are separate entities, and the use cases can often go beyond the normal "session" ideas in a standard Notepad++ instance -- for example, always wanting the docked NppFTP window that @jimmydevine wants to remain open every time, regardless of session state.

As a deciding factor, I would think that any of the Docking settings stored in `config.xml` <GUIConfig name="DockingManager"><PluginDlg pluginName="..."> with a non-empty `pluginName` that has any value but `Notepad++::InternalFunction` should be honored rather than auto-hidden in the `-nosession` situation.

**Comment by donho** [comment]
It's a fix than an issue:

14. Fix docked panels appear with “-nosession” cmd line parameters. (Fix #8005)
ref: https://notepad-plus-plus.org/downloads/v7.9.2/

**Comment by sasumner** [comment]
>It's rather a fix than an issue

Probably what should happen here is that doc panels that don't relate to the session concept should still be shown when `-nosession` is used, and those that do relate should not be shown.

_Folder As Workspace_ is a good candidate to not be shown (as per #8005).

Something like _Function List_ for example, probably should be shown.

Unless...the concept of "session" goes beyond file/tab related stuff and into the core setup of the user's work environment.

**Comment by ArkadiuszMichalski** [comment]
> @donho 
>It's rather a fix than an issue:

It depends, even the description of this argument says nothing about panels:
```
-nosession : Launch Notepad++ without previous session
```

The problem is that it affects every panels, not just this one.  Personally, I'd except a separate `-nopanels` argument that no affect` -nosession` (which just shouldn't load session file), if omitting all is needed . 

Anyway more detailed description of what actually omits `-nosession` would be desirable, because this is another issue asking the same thing (https://npp-user-manual.org/docs/command-prompt/).

**Comment by jimmydevine** [comment]
@donho what is the difference between a fix and an issue?

**Comment by sasumner** [comment]
>what is the difference between a fix and an issue?

I think he is meaning to say that "this is fixed; no longer an issue".
But that is just my interpretation.

And...I don't necessarily agree that it is fixed.  :-)

**Comment by donho** [comment]
@sasumner @ArkadiuszMichalski 
I see your point. However, no members highlighted this "issue" when the modification was done.
OTOH, the panel settings for me including in the "Session" - this was a bug that I wanted to fix since long time ago.
So let's keep the current behaviour. Again, if there are a lot of request to change the current behaviour, I would consider it.

**Comment by sasumner** [comment]
>no members highlighted this "issue" when the modification was done.

Hmm, well even members don't always deep dive into examining changes, especially those coded by the project owner.  We presume he knows best. :-)

On a cursory level, if I see a fix happen with title 'Folder as Workspace panel opened even with "-nosession" ', my presumption would be that only that panel was affected by the fix, not ALL panels.

**Comment by ArkadiuszMichalski** [comment]
If anyone needs to have any panels open with `-nosession`, then you can open it with some add-on, eg PythonScript (after starting Notepad++). Not perfect, but still possible. There is no need to wait for further decisions.

**Comment by sasumner** [comment]
@ArkadiuszMichalski 

>you can open it with some add-on, eg PythonScript (after starting Notepad++)

You might want to show an example of exactly how to do that.

**Comment by ArkadiuszMichalski** [comment]
No, because I use Python sporadically (and not in Notepad ++). But as far as I know, we can check the arguments passed and if we have "-nosession" we can invoke plugin command to open some panel? Attach this script at Notepad ++ startup. Well, but I can be wrong.

**Comment by sasumner** [comment]
OK, I try showing something then; this partial script seems to work to open some docking panels:

```
if '-nosession' in notepad.getCommandLine():
    notepad.runMenuCommand('Edit', 'Character Panel')
    notepad.runMenuCommand('Edit', 'Clipboard History')
    notepad.runMenuCommand('View', 'Function List')
```
