### ISSUE TITLE
Shortcut Mapper UI text clarifications

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#9505]
Making this an issue rather than straight-to-PR in case there is need of debate over the non- `...` part.

### Description of the Issue

![image](https://user-images.githubusercontent.com/30118311/107851234-76e3c680-6dd6-11eb-9fcf-ab695f259ea1.png)

should be changed to:

![image](https://user-images.githubusercontent.com/30118311/107851286-d0e48c00-6dd6-11eb-8e46-780d2a4d0864.png)

Also, when pressing the _Delete_ button, the prompt can be misleading, as it implies that the shortcut keycombo and not the command will be deleted:

![image](https://user-images.githubusercontent.com/30118311/107851303-f6719580-6dd6-11eb-9ae5-004900dae8ed.png)

Suggest changing it to this for maximum safety:

![image](https://user-images.githubusercontent.com/30118311/107851463-2705ff00-6dd8-11eb-9142-92e712461844.png)

### Debug Information

Comments based upon English text in N++ 7.9.2

**Comment by sasumner** [comment]
Adding the `...` to the buttons works for the English translation.
Maybe to support it best for other translations we need to make the buttons a bit wider?

**Comment by ArkadiuszMichalski** [comment]
These dots just introduce more problems than benefits. Are there any popular programs that also use them in this context?

**Comment by mere-human** [comment]
> Are there any popular programs that also use them in this context?

This is commonly used to signal there are more options when you click it, not just a single action.

**Comment by sasumner** [comment]
>This is commonly used to signal there are more options when you click it, not just a single action.

Also used when an action generates another window opening up with further "questions", e.g. _File_ > _Open..._
Such is the case here.

**Comment by ArkadiuszMichalski** [comment]
> mere-human
> This is commonly used to signal there are more options when you click it, not just a single action.

I know that, but for xxx years I didn't even realize it and didn't pay attention to these dots. From what I can see most programs (what I have) use them, so I don't have any more questions.

**Comment by sasumner** [comment]
Some interesting reading about `...` here: https://stackoverflow.com/questions/637683/when-to-use-ellipsis-after-menu-items?rq=1

**Comment by donho** [comment]
@sasumner 
Please make 4 buttons larger for the Ellipsis.

> The crucial factor is whether the menu option requires additional information (input or a selection) before it carries out the operation.

Please remove Ellipsis from `?->Command Line Arguments...` and I'm wondering if we remove Ellipsis from `?->Debug Info...`

**Comment by sasumner** [comment]
@donho

>Please enlarge 4 buttons for adding the ellipsis.

OK.

>Please remove Ellipsis from ?->Command Line Arguments... and I'm wondering if we remove Ellipsis from ?->Debug Info...

Is this a _strong_ desire?
I rather like the `...` on these.
Can we extend the definition of "use ..." to include "opens another window for purely informational purpose"?
_Debug Info_ could be regarded as "needs further input" in the form of clicking the copy.

Also, another one that needs `...` that doesn't have it currently is _Move to Recycle Bin_ (both on _File_ menu and on tab r-click menu).

**Comment by donho** [comment]
> Is this a strong desire?

Not really. (I have the same opinion as @ArkadiuszMichalski), but since we want to apply this rule, why do we give the exception?

> Debug Info could be regarded as "needs further input" in the form of clicking the copy.

OK, makes sense.
So let's remove ellipsis from `?->Command Line Arguments...`.

**Comment by sasumner** [comment]
Sure.
I guess by going down this path, I have somewhat thwarted my own desires.  :-(
Stupid me!

**Comment by ArkadiuszMichalski** [comment]
What about:
1. Folder as Workspace > right click inside empty panel and from context menu `Add` has  missing `...`?  
2. Project(1/2/3) > right click inside empty panel and from context menu `Open Workspace` has missing `...`? 
3. Project(1/2/3) > right click on file item and from context menu `Modify File Path` has missing `...`? 
Btw, `Workspace` and `Edit` button in prroject bar (above list) open next popup (context menu) to select next item, so should have `...` to?


@donho
> So let's remove ellipsis from ?->Command Line Arguments....

It makes sense (although it's worth mentioning that here `Ctrl+C` and `Ctrl+V` works well and we can copy the entire description).

I also have question here: `Plugins > Open Plugins Folder...` has elipsis, but:
1. `File > Open > Explorer/Cmd/FaW` not (same as we do right click on tab and see the same commands). What about `Open in Default Viewer` in `File` and in tab's context menu?
2. right click on tab and `Print` not (look that `File > Print...` has it).
3. `Edit > On Selection > Open containing folder in Explorer` and `Search on Internet`
4. Folder as Workspace > right click on root or item and `Explore here` or `Cmd here` not.
5. `Search > Incremental Search` open bottom bar and move focus, should have `...`? Same as `Search Result Window` here, should have `...`?
6. `View > View Current File in`, browsers should have `...`?
7. `View > Move/Clone Current Document`, commands should have `...`?
8. Why `View > Summary...` has it but Project(s), FaW, Document Map and Function List not?
9. `Run > Get PHP help, Wikipedia Search, Open file in another instance` should have `...`?

Info from https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9505#issuecomment-778880309 doesn't explain much, in fact each program does it its own way. I don't like these dots, but once they exist it's best used it in a consistent manner.  It would be good to analyze the above cases and tell why (or not) to add `...` and possibly change it in one shot (if necessary). 

@sasumner 
I also wondering if adding `...` to commands due to the possibility of an alert/prompt is the right solution. As far as I remember, quite a few commands need confirmation in Notepad++, and you would have to add these `...` in many places. Here you only touch the Shortcut Mapper, but it's obviouse that there is more.

**Comment by sasumner** [comment]
@ArkadiuszMichalski 

I'm totally done talking about or working on anything involving `...`
I've learned my lesson. :-)

**Comment by donho** [comment]
I don't really think these cosmetic "fixes" could bring any advantage.

**Comment by sasumner** [comment]
It is sad that the non-cosmetic change in this was lost in the `...` controversy. 
:-(

**Comment by mere-human** [comment]
I thought it was approved based on older comments.

**Comment by sasumner** [comment]
@mere-human 

>I thought it was approved based on older comments.

I think there was a change-of-mind due to the `...` diversion.
