### ISSUE TITLE
strange regex find behavior for \b\w

### ISSUE THREAD

**Issue by ssmithh** [notepad-plus-plus/notepad-plus-plus#951]
I'm surprised to see (using Find, regular expression) \b\w is the same as \w (and not the start of words)

\w\b seems fine - finds ends of words

Hoping it's not just me

**Comment by h-h-h-h** [comment]
I can approve it. This seems strange.

**Comment by tx9191** [comment]
that problem remains in v6.8.8

**Comment by bn7q** [comment]
Stumbled upon this issue. Still there in v7.4.1
More info:
it seems like it thinks that cursor is the beginning of the string.
Like if you are searching for "**\b[abc]**" in a line "**abcdefabc**" first you'll find **a** then **b** then **c** then search stops (**abc**defabc). But if you place cursor before second **a** and try to find the same regex, it will find the second **a** then second **b** and so on (abcdef**abc**)

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
