### ISSUE TITLE
REGRESSION: DPI scaling broken in v7.9.3

### ISSUE THREAD

**Issue by Whissi** [notepad-plus-plus/notepad-plus-plus#9513]
### Description of the Issue
I am using multiple monitors with different DPI scaling settings, like 100% and 120%.

It was never a problem to open Notepad++ on the monitor with the 100% setting and move it to the 120% screen -- once the program window was shown on the 120% screen, UI scaled up as expected. When I moved the UI back to the other other monitor, UI scaled back down to 100%.

This doesn't work anymore with v7.9.3. I'll get 120% scaling (which is coming from my main monitor) on all screens.
Downgraded back to v7.9.2 fixes the problem.

### Steps to Reproduce the Issue
1. Get multiple monitors and apply different DPI scaling.
2. Open Notepad++ on first monitor, check that everything looks like you are expecting and now move UI to a monitor with different DPI scaling.

### Expected Behavior
UI should adapt to different scaling like in <=7.9.2.

### Actual Behavior
UI always renders with highest DPI scaling (or with DPI settings from main monitor) which makes it looking too big on monitors where no DPI scaling should apply on.

### Debug Information
```
Notepad++ v7.9.2   (64-bit)
Build time : Dec 31 2020 - 04:01:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro for Workstations (64-bit) 
OS Version : 2009
OS Build : 19042.804
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

**Comment by sasumner** [comment]
You need to provide the _Debug Information_ that was required in the issue template.

**Comment by Whissi** [comment]
I added debug information. I expect that for v7.9.3 only version number has changed since I already downgraded.

**Comment by sasumner** [comment]
So for me in 7.9.3, display is crisp and great on all four of my various screens, in contrast to 7.9.2 where it was blurry on some.  This is always using the "Recommended" _Scale and layout_ settings for all monitors; which causes a mix of 125% and 100% settings, examples:

![image](https://user-images.githubusercontent.com/30118311/107955209-847e8500-6f6b-11eb-8964-a7a52e0dbb81.png)

![image](https://user-images.githubusercontent.com/30118311/107955237-8ea08380-6f6b-11eb-87ad-be22b04359c2.png)

Maybe "DPI" is one of those areas where a legacy program like Notepad++ can't truly be made to make everyone happy all the time?  Or the "magic bullet" for doing so hasn't yet been discovered.

**Comment by jiangzhenjerry** [comment]
I confirm that this issue happens to me as well. I have a main 15'' 4K monitor (with 250% scaling) and an external monitor (with 100% scaling). Moving NP++ from the main monitor to the external monitor doesn't change the scaling correctly - NP++ remains 250% scaling.

**Comment by donho** [comment]
@sasumner 
> Maybe "DPI" is one of those areas where a legacy program like Notepad++ can't truly be made to make everyone happy all the time? Or the "magic bullet" for doing so hasn't yet been discovered.

I don't call an application on its dev is quite intensive to follow the last OS and released every 2 months "legacy program".
v7.9.2 has a correct behaviour but v7.9.3 has not, so it's clearly a regression to me.

**Comment by donho** [comment]
@jiangzhenjerry & @Whissi 
I've checked the [modification ](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/1364b199b4eff3aa2bdc370e6adf6d6186576218)(the cause of) this issue, it's the way MS suggests.
OTOH, in your old Notepad++ v7.9.2, is display a little bit blurry than the other application? 
Are you using the projector as the 2nd monitor?

**Comment by donho** [comment]
**Config**:
laptop (125% 1920x1080) + monitor (100% 2560x1400)
**result**: on the 2nd monitor

![image](https://user-images.githubusercontent.com/90293/108153549-b0b91380-70db-11eb-860f-3b75d54e196e.png)

**Comment by jiangzhenjerry** [comment]
@donho Thank you for trying to help, but you misunderstood one detail. The 2nd monitor is not in the projection/mirror/duplication mode, but in the "extension" mode. When dragging NP++ to the 2nd monitor, NP++ looks awfully huge. I took two pictures and I hope they help explain the issue.

![1](https://user-images.githubusercontent.com/9311082/108155423-b4c14300-7093-11eb-8eb0-e4f1788bb255.jpg)
![20210216_200328b](https://user-images.githubusercontent.com/9311082/108155424-b559d980-7093-11eb-8714-16aed31b6046.jpg)
![20210216_200337b](https://user-images.githubusercontent.com/9311082/108155426-b5f27000-7093-11eb-9cca-fb99b91bd724.jpg)

**Comment by donho** [comment]
**Config**: laptop (150% 2256x1504) + projector(100% 1920x1080)
**result**: on the 2nd projector v7.9.2 (left) vs v7.9.3 (right)

![image](https://user-images.githubusercontent.com/90293/108155639-8cf7cc80-70df-11eb-804d-3cc2b1e00838.png)

**Comment by jiangzhenjerry** [comment]
> **Config**: laptop (150% 2256x1504) + projector(100% 1920x1080)
> **result**: on the 2nd projector v7.9.2 (left) vs v7.9.3 (right)
> 
> ![image](https://user-images.githubusercontent.com/90293/108155639-8cf7cc80-70df-11eb-804d-3cc2b1e00838.png)

Please see my post above. The issue is not about external projection.

**Comment by donho** [comment]
So after checking the implementation/modification and tested on the different configuration, I would say it's not a regression. The result is the managed by windows 10.

**Comment by jiangzhenjerry** [comment]
> So after checking the implementation/modification and tested on the different configuration, I would say it's not a regression. The result is the managed by windows 10.

I was hoping you would take a look at my photos and understand that your testing is **not relevant** to the issue reported here. Just to clarify a third time that @Whissi and I were talking about **"extended"** screen mode, not **"projection"** you tried to test. It should be clear enough from my photos that it is not right to have an application that *huge* on an extended monitor. And again, **no other apps look like this** - just Notepad++. Don't jump to blame Windows 10 easily.

However, I do respect your choice - if this is indeed what you intend, so be it - I'm fine with that. It's easy enough for @Whissi and I to switch to a different editor.

**Comment by donho** [comment]
@jiangzhenjerry I see your screenshots and your point. Both my test environments are in "extended" screen mode.
What I try to say is the modification/implementation was intended to fix Notepad++ on the 2nd monitor blurry bug, by using MS recommended way.
I'm not blaming Windows 10, I just have no idea for this issue - for some ppl it's a good fix but for others it's a regression - depending their environment.

I will reopen this issue. If anyone have any perfect solution, please let us know.

**Comment by jiangzhenjerry** [comment]
@donho Thank you for your explanation. Now I understand what you meant by "the MS recommended way". I agree with what you said - it may be hard to achieve both goals at this moment. Hopefully one day others will contribute ideas to solving this. Meanwhile, I thank you for working on this issue and replying to me in a very timely manner.

P.S. I remade my photos below. The information is redundant to what I had already posted, but I am hoping that others who may be interested can understand this tricky issue easier through the new photos. I opened File Explorer, MPC-BE and Notepad++ on the main screen (left), which looked great...

![00](https://user-images.githubusercontent.com/9311082/108158112-1afc9480-7099-11eb-8094-963b12507873.jpg)

Here is a screenshot of the main screen (left), just for the reference.

![01](https://user-images.githubusercontent.com/9311082/108158197-497a6f80-7099-11eb-9b6f-28d68de2376b.jpg)

Now I dragged the three applications to my extended monitor. File Explorer and MPC-BE were automatically scaled down, but Notepad++ remained the same scaling...

![02](https://user-images.githubusercontent.com/9311082/108158262-6c0c8880-7099-11eb-80e8-5b3b02f1f05c.jpg)

And here is the screenshot of the extended screen (right), to better illustrate the unexpectedly large Notepad++ interface.

![03](https://user-images.githubusercontent.com/9311082/108158316-83e40c80-7099-11eb-9531-efae5bdac0c3.jpg)

**Comment by 7Z0t99** [comment]
> 
> 
> @jiangzhenjerry & @Whissi
> I've checked the [modification ](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/1364b199b4eff3aa2bdc370e6adf6d6186576218)(the cause of) this issue, it's the way MS suggests.
> OTOH, in your old Notepad++ v7.9.2, is display a little bit blurry than the other application?
> Are you using the projector as the 2nd monitor?

I am afraid that this modifiction is not what Microsoft suggests. The modifiction tells Windows that notepad++ is PerMonitor DpiAware, and not just DpiAware, but notepad++ is only DpiAware, and this causes problems.

A window that is PerMonitor DpiAware needs to process the WM_DPICHANGED message correctly, see https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/ne-shellscalingapi-process_dpi_awareness , but as far as I can tell notepad++ does not do anything when it receives WM_DPICHANGED, see https://github.com/notepad-plus-plus/notepad-plus-plus/blob/ab5c1d3e2a9718a3cc365c1e44bfae09bb7355bc/PowerEditor/src/NppBigSwitch.cpp#L2498-L2501
There already is an issue about implementing WM_DPICHANGED, see #5873 . As I have commented in #8115 , fully handling WM_DPICHANGED requires an upgrade to scintilla 4.4.0 or newer

Therefore please revert this change until WM_DPICHANGED is fully implemented, and reopen #8115

**Comment by mere-human** [comment]
> fully handling WM_DPICHANGED requires an upgrade to scintilla 4.4.0 or newer

Maybe, it is the right time to upgrade Scintilla?

**Comment by sasumner** [comment]
@donho 

>I don't call an application on its dev is quite intensive to follow the last OS and released every 2 months "legacy program".

"Legacy" is not meant as any kind of insult, of course, I would not insult N++ in any way.  I'm sure you know this.
The context I meant it in is a long-standing program that perhaps cannot easily take advantage of features of newer versions of the OS.  Certainly this is true of other aspects as well, dark mode being one example.

Hey, Don, did you know there's a cat sitting in front of your projection?? :-)

**Comment by sasumner** [comment]
>Maybe, it is the right time to upgrade Scintilla?

It has been the right time for a while now (#8900), but if this is what it takes to push it over the hump, so be it! :-)

**Comment by sasumner** [comment]
So if this gets reverted, then my Notepad++ experience is lessened (blurry on some monitors) while others get theirs improved?  It hardly seems fair.  :-)

**Comment by xianyun666** [comment]
It is recommended to upgrade the version of Scintilla first

**Comment by mere-human** [comment]
Probably, related: https://community.notepad-plus-plus.org/topic/20774/dual-monitor-with-different-resolutions-didn-t-scale-well-with-latest-7-9-3/

**Comment by 7Z0t99** [comment]
Oh nice, I see that an upgrade to Scintilla v4.4.6 has been commited https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d7819cf601051510b7fa1640ca17fedad297e1f8

The second step would be write a handler for WM_DPICHANGED that also forwards WM_DPICHANGED to Scintilla.

**Comment by iridris** [comment]
This issue can be worked around by adjusting the High DPI compatibility settings on the shortcut to override with "System (Enhanced)".
![image](https://user-images.githubusercontent.com/952387/108766606-5e388680-7523-11eb-8ccc-d91296d18793.png)
![image](https://user-images.githubusercontent.com/952387/108766748-888a4400-7523-11eb-8fd7-126e171ff1ae.png)

**Comment by mere-human** [comment]
> This issue can be worked around by adjusting the High DPI compatibility settings on the shortcut to override with "System (Enhanced)".

If it really works, then it is worth adding it to [user manual](https://npp-user-manual.org/), for example.
I don't have such a monitor to check it.

**Comment by rallets** [comment]
@mere-human yes, I have exactly the same problem @jiangzhenjerry described. 
@iridris I tried that too (and all the possible combinations), and yes it fixed the problem but then introduced another one :) so basically the labels on the main menu were truncated. So I cannot consider that a solution, but I rolled back to 3.9.2 and now I'm again a notepad++ happy user :)

**Comment by gstavi** [comment]
Something I wrote [about DPI](https://community.notepad-plus-plus.org/topic/19085/font-in-sidebars/4).

I really wish you good luck fixing it but I don't have high hopes.
Internet browsers spoiled us by introducing nearly perfect scaling of everything. But it comes at a price of insane rendering technology that evolved over the last 20 years.
Win32 **LEGACY** API just does not work that way.
Font sizes and dialog components are pretty much detached. You enlarge fonts and they spill out of their components. You enlarge components and font becomes non-proportional. And users would like to enlarge/shrink with ctrl+wheel.

In theory you should have all the graphics aspects sized into some virtual ultra-high resolution and then project it into the actual resolution. But can you do it for the extremely complex "Preferences" dialog?

The compatibility hacks in a shortcut MAY fix behavior for a single monitor but still break when you switch monitors.

For the record, some legacy aspects of Windows desktop (explorer.exe) are broken as well. I set the task bar to "legacy mode" and add toolbar. When switching DPI (docking or undocking the laptop) the icons in the toolbar become too large or too tiny.

So in my opinion:

- 1st priority is for Notepad++ to behave OK on a single screen, either Standard DPI (96) or High DPI.
- 2nd priority is to support well docking/undocking - single screen switch from high to low or vice versa.
  - Preferably on its own but if not then with application restart.
- Supporting multi screen DPIs is only 3rd priority and must not break higher priorities.

BTW in task manager "details" pane you can right click a column header and select to add "DPI Awareness" column. This can help you evaluate other legacy WIN32 API apps.

**Comment by DougEwellBCT** [comment]
Sorry to be fashionably late to the party.

I have the opposite problem as @Whissi because my main display, a real monitor, is 100% (recommended) and my second display, the laptop, is 125% (recommended is 150%, which would show too little material on the screen). So N++ looks fine on Display #1 and microscopic on Display #2.

I will have to stay on 7.9.2 until this is reverted. It's clearly a `WM_DPICHANGED` issue, as @7Z0t99 explained. I can investigate the Compatibility setting discussed above, but apparently that is one step forward and one step back.

**Comment by donho** [comment]
@sasumner 
> "Legacy" is not meant as any kind of insult, of course, I would not insult N++ in any way. I'm sure you know this.
The context I meant it in is a long-standing program that perhaps cannot easily take advantage of features of newer versions of the OS.

Call me a dying old man or whatever you want, but don't use the word "legacy" on my boy :D 
No worry. No harmed feeling. 

> Certainly this is true of other aspects as well, dark mode being one example.

Take any win32 native program (legacy or new one), you will see there's no dark mode - that's my point. You have to obey the physical law of Microsoft, or you take a browser to transform it into an editor (or other application) and you use js & css to make a dark mode. Performance or aesthetic - your call. 

> Hey, Don, did you know there's a cat sitting in front of your projection?? :-)

Yes, I'm aware of it.
In fact, pretending to fix this regression gives me a chance to show how my cute cate is awesome under the projector light! 
;)

**Comment by sasumner** [comment]
@donho 

Note that @gstavi used the term "legacy" FOUR times in his recent posting.  :-)

**Comment by donho** [comment]
@sasumner 
But "You were the chosen one!"
:)

**Comment by donho** [comment]
Here is Notepad++ v7.9.3 + Scintilla v4.4.6 on the 2nd monitor (projector) : 
![image](https://user-images.githubusercontent.com/90293/108795551-059ad500-7587-11eb-8e72-4aded31c0c71.png)

Scintilla part looks good - even more clear than VS beside. 

So it remains to resize all the windows of Notepad++  in WM_DPICHANGED processing - it would be the hardest part I guess.

**Comment by xianyun666** [comment]
I researched out a good solution。
```
<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <asmv3:application xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
    <asmv3:windowsSettings>
	  <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness>
          <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
    </asmv3:windowsSettings>
  </asmv3:application>
</assembly>
```

Upgrade PerMonitor to PerMonitorV2，At this time the menu bar and title bar will also zoom.
https://docs.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows
![image](https://user-images.githubusercontent.com/22339210/108809677-5391f600-75e4-11eb-973a-e689d7c1fc09.png)

Because the Scintilla version is upgraded, the editing area will also be zoomed.

But when there are two interfaces moving between monitors with different zoom ratios, the style will be confused,need to be resolved

![image](https://user-images.githubusercontent.com/22339210/108809334-94d5d600-75e3-11eb-8fef-4318609903c6.png)
![image](https://user-images.githubusercontent.com/22339210/108809374-aa4b0000-75e3-11eb-9ccd-617140e105ec.png)


Attached is the file I compiled, I only modified **dpiAware.manifest**


@donho @sasumner @Whissi
[bin.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6027116/bin.zip)

**Comment by gstavi** [comment]
> Note that @gstavi used the term "legacy" FOUR times in his recent posting. :-)

Note that my "legacies" were associated to win32 API.
And that is the core of the problem. As far as Microsoft is concerned the GUI parts of WIN32 API should not be used directly.
They want you to use higher level APIs that I never bothered to study but I assume is is more browser like.

BTW, I am an experienced programmer but my GUI expertise is nearly non existent.
I did encounter during my short playing with this problem the dialog artifacts pictured above. Focus on these as I assume it is the hardest problem. Can you scale a dialog that is defined in a resource file and displayed by WIN32 using a single "show dialog indirect" call?

**Comment by donho** [comment]
> Can you scale a dialog that is defined in a resource file and displayed by WIN32 using a single "show dialog indirect" call?

Yes. It's possible. There are some such calls in Notepad++, and the most of them work fine.
This is a balls-breaking issue, I doubt we can find the solution for that.

**Comment by donho** [comment]
I have tried `PerMonitorV2`, it would be the ideal solution if there were no custom control in Notepad++ : some part of the custom controls like panels and Find dialog are not rendered properly in `PerMonitorV2` mode.

Wheras in `PerMonitor` mode (in v7.9.3), it's clearly a regression because `WM_DPICHANGED` message is not treated and make Notepad++ unusable under 4K monitor.

Without "PerMonitor" feature (in v7.9.2), it will be a little bit blurry, but at least the system resizes all parts of application correctly, so let's go back to the way in v7.9.2.

It's not easy this issue, all I can do is chose the **less worst** way, just like people in the world vote for choosing their political leader.

**Comment by gstavi** [comment]
In my opinion "little bit blurry" is a bigger problem for users than unprocessed WM_DPICHANGED.

The higher priority that every user will be able to use a crisp Notepad++ on his single primary monitor whatever DPI it has. If a user need to restart Notepad++ on a new monitor it is a small price to pay, especially since session can be saved.

Better processing of DPICHANGED should be a secondary priority. It is annoying for users who drag Notepad++ from screen to screen or dock/undock a lot but it can't come at the price of hurting single monitor users.

**Comment by jiangzhenjerry** [comment]
@gstavi It is quite rude to bluntly call out others' problem as a "secondary priority" just because you don't have the problem and don't feel the pain. "Restart[ing] Notepad++ on a new monitor" is not a solution, because the scaling remains the same regardless of which monitor it starts from. It is more than a minor annoyance that you imagined, and there is currently no alternative other than going back to the 7.9.2 way.

I totally agree with your earlier comment that "1st priority is for Notepad++ to behave **OK** on a single screen." But "OK" doesn't necessarily mean"perfect". What if I say a slight blur is still OK? How would you feel? Sure, everyone wants their issue to be addressed asap, but I wouldn't force the developer to treat my issue as the top priority.

**Comment by gstavi** [comment]
@jiangzhenjerry, do you understand the meaning of the word **secondary**?
The world is full of problems and prioritizing them is a common practice among engineers to decide order of solving.
Other words you should learn are **mitigate** or **workaround**.
A problem that the user CAN NOT solve for himself should be prioritized over a problem that can "go away" with a bit of extra work from the user side. Obviously there are other criteria as well, number of impacted users is typically a major factor.

If your claim of "scaling remains the same regardless of which monitor it starts from" holds then indeed my proposed mitigation does not work. But at the moment I don't take **your** word for it.

For a program that its sole purpose is to show text on the screen, any fuzziness is not OK.
Tiny font is indeed worse than fuzziness.

Since @donho stated that both problems cannot be solved together, the choice of the problem to solve should consider mitigation.

**Comment by jiangzhenjerry** [comment]
@gstavi You sound like "Oh cooling air conditioner is much more important for the world that heating air conditioner, because I live in Phoenix, Arizona and I don't take the word from people in Chicago for their cold winter." Sorry man, but this is just childish nonsense. Remember, the sun doesn't revolve around you.

Prioritization is absolutely necessary but **only** under the condition that everyone understands the full story. In any real situation, one is not qualified to suggest prioritization when all he cares is his own suffering, otherwise prioritization cannot be done because everyone would simply say his own problem should be the top priority. And I don't need you to take my word for anything. You can either test it out yourself, or - if you don't have the physical equipment to test - stop downplaying the importance of things that you don't have an idea about.

Besides, let's try not to step on the developer's toes, such as defining the "sole purpose" of Notepad++, shall we? You are so rude and single-minded that you think everyone (including the developer) needs to agree with your philosophy, even on things like the purpose of the Notepad++. Wow.

**Comment by gstavi** [comment]
@jiangzhenjerry, Your basis assumption that my comments are self serving is broken. I can stick with a version that suits me and don't need to work with the latest. I can (and do) modify Notepad++ by myself for my private needs. I have many comments in the Notepad++ forum that demonstrate this consistent trend.
This is in sharp contrast to your definite self serving egoistic view of the problem.

Notepad++ is a text editor and its sole purpose is to show text on the screen. I guess it could spawn an auxiliary thread to mine bitcoin or participate in SETI but I hope it does not. I understand the full story in a way that you never will.

**Comment by xianyun666** [comment]
Notepad 3 is my primary editor right now, after all, it works well in Permonitorv2 .
I personally hate ambiguity in software

**Comment by 7Z0t99** [comment]
> I have tried `PerMonitorV2`, it would be the ideal solution if there were no custom control in Notepad++ : some part of the custom controls like panels and Find dialog are not rendered properly in `PerMonitorV2` mode.
> 
> Wheras in `PerMonitor` mode (in v7.9.3), it's clearly a regression because `WM_DPICHANGED` message is not processed and that makes Notepad++ unusable under 4K monitor.
> 
> Without "PerMonitor" feature (in v7.9.2), it will be a little bit blurry, but at least the system resizes all parts of application correctly, so let's go back to the way in v7.9.2.
> 
> It's not easy to solve this issue, all I can do is choose the **less worst** way, just like people in the world-wide vote for choosing their political leader.

I suppose implementing `PerMonitorV2` would be the best solution, but similarly to `PerMonitor`, or one more window messages related to the DPI change need to be processed in `PerMonitorV2` mode. Depending on how the custom control panels are programmed, implementing this may be more or less difficult. 

I agree that the revert was the best solution for the time being.

**Comment by deqing** [comment]
@xianyun666 thanks for sharing the `bin.zip`, it works perfectly for me.
