### ISSUE TITLE
How to remove single entries from recent file list?

### ISSUE THREAD

**Issue by Suncatcher** [notepad-plus-plus/notepad-plus-plus#9524]
### Description of the Issue
I want to remove certain entries from recently opened files

### Steps to Reproduce the Issue

1. I open config.xml
2. Edit the recent lines, delete some of them
3. Save it

### Expected Behavior
I want so that the recent history was as per my edits

### Actual Behavior
It doesn't change and and on next open of config.xml it is restored again discarding my edits

**Comment by mere-human** [comment]
Do you mean the `config.xml` in thsi directory `C:\Users\User\AppData\Roaming\Notepad++\`?
Did you edit the file with Notepad++? If so, then the Notepad++ has likely overwritten the file upon closing.

You can edit it with e.g. Windows Notepad.

Or, you can empty the entire recent file list from the menu:
![image](https://user-images.githubusercontent.com/9664141/108045607-5329b600-704c-11eb-898d-ff90a446789b.png)

**Comment by Suncatcher** [comment]
Yes, editing with Windows Notepad had solved the problem. Thanks.

**Comment by sasumner** [comment]
I'm surprised the issue wasn't a request for removing singular entries from the list _within_ N++ itself. :-)

**Comment by Suncatcher** [comment]
I'm quite surprised too. Cleaning different clutter from recents is quite a common need

**Comment by smjgordon** [comment]
> You can edit it with e.g. Windows Notepad.

Or you can edit it with Notepad++ and save as a new file, then close N++ and rename the files within Explorer.

I do this not infrequently in order to edit things like macros.

> Or, you can empty the entire recent file list from the menu: ![image](https://user-images.githubusercontent.com/9664141/108045607-5329b600-704c-11eb-898d-ff90a446789b.png)

That isn't removing single entries from the list.  The whole point of the OP's question is to remove specific files from the list, not to erase the whole list.

But this brings us to a simple workaround: Open the files you want to keep in the list, then select Empty Recent Files List, then close the files you opened.
