### ISSUE TITLE
Suggestion : Allow Line Comment Symbol as start of folding symbols

### ISSUE THREAD

**Issue by Bluezy** [notepad-plus-plus/notepad-plus-plus#955]
**briefly :** Let NPP recognize the comment marker **ALSO** as indicating the beginning of a folding symbol of style 1

![folding](https://cloud.githubusercontent.com/assets/12245739/10024560/c00e67c0-6125-11e5-9f10-9ad949905dd6.jpg)

**More elaborately** 
In its UDL editing dialog, NotePad++ offers a few ways to add language-specific **folding commands**. Unfortunately, an essential folding method used by PureBasic, my favourite programming language, cannot be implemented within the existing rules of NotePad++.

Folding in PureBasic is accomplished in 2 ways: 
 **(1) keyword pairing :** no problem here. NPP's **code 2 style** works perfectly.
 **(2) matching symbols inserted at the start of a line comment :** (example below) This cannot be accomplished in NPP since NPP stops parsing a line once it has dentified the **Line Comment** marker. Logical enough, you'll say. But...

In PureBasic, line comments begin with a semi-colon. For instance : 
**;** comment about the following genial code
 ... code ...
 ... code ...   ; comment specific to this action
 ... code ...
**;** another comment

Simple enough.

But comment markers serve double duty in PureBasic. they are used to indicate folding sections when followed immediately by a symbol (or text) specified in its ini file. The user will enter, in PB's ini file, matched pairs of folding symbols. They can be anything (symbols, letters, ...), but must begin with '**;**', the comment symbol, When a comment line starts with a folding symbol, it remains a comment and is treated as such, but it also controls folding as follows :

For instance, we define ';-<' and ';>' as a matched pair, and the following familiar fold/unfold marking then appear in the source code :
[-]  ;-<   comment beginning with an **opening** folding symbol
 |   ... code ...
 |  ... code ...
 |  ... code ...
 |_ ;>  a comment beginning with the matching **closing** symbol

Example #2 : we add '; START' and '; FINISH' as matched folding markers to the ini file, which results in

[-]  ; START this does that
 |    ... code ...
 |   ... code ...
 |   ... code ...
 |_ ; FINISH

[-]  ; START some more smart coding
[-]  ;-<  more code
 |   ... code ...
 |   ... code ...
 |   ... code ...
 |_ ;>  a comment beginning with the matching **closing** symbol
 |_ ; FINISH my smart stuff

[-]  ; START folding section
[+]  ;-<   more code
 |_ ; FINISH

Sorry for being so wordy, but i think you get the idea.
I'll try to upload a picture. 
It's sometimes more clear than explanations.

Thank you for providing this opportunity for input.

**Comment by thdoan** [comment]
I would really like this feature as well. Right now I'm having a difficult time syntax highlighting Markdown's headline and quoted content using different styles. I can define one as a line comment, but the second one cannot be defined reliably using Delimiters since there's no way to specify that it should only be highlighted if the symbols in Open start the line.

One solution is to allow `((EOL))` in the Open field as well, e.g.:

```
Open: ((EOL))>
Escape:
Close: ((EOL))
```

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
