### ISSUE TITLE
Show absolute cursor position alongside line and column numbers

### ISSUE THREAD

**Issue by gnodarse** [notepad-plus-plus/notepad-plus-plus#9575]
Just a feature suggestion

At the bottom of the notepad++ window there is some helpful information about the file length and cursor position. 

![np++](https://user-images.githubusercontent.com/46761795/109069670-8a890a00-76bf-11eb-9a3c-c83055bd7305.png)

More than once I've wished that this information contained absolute position of the cursor in the file. It's not calculable because column length varies. To give an instance of when it would've been helpful, I was trying to read a text file into python but there were a few bad bytes; python gave me the locations of the bytes, and if absolute position of the cursor was displayed I could've quickly and easily deleted them. I'm sure that many people have scanned through files trying to find specific byte locations by approximation.

**Comment by sasumner** [comment]
Well, you were supposed to follow the template when creating an issue.
But you chose to delete it out.

Had you followed the template, we could have seen what version you were using, from the _Debug Info_ section.
It was probably an older version (current version as of this writing is 7.9.3) because a few versions back (7.9.1, I think) the status bar was changed to look like this:

![image](https://user-images.githubusercontent.com/30118311/109083288-a39bb600-76d3-11eb-9b29-fd5f3e7b153f.png)

where, as you'll note, the `Sel : 0 | 0` area (which truly _was_ useless) has been replaced by `Pos : xxx`.

Currently, `Pos` is the "byte position", not the "character" position; you may not understand the difference, but you asked about bytes, so I think it provides what you want.

**Comment by sasumner** [comment]
Reference: #8524

**Comment by TrevorBai** [comment]
> 

Good thread, thanks for the clarification.
