### ISSUE TITLE
Please could you change the File -> Open dialog to a OpenFileDialog like SublimeText 3?

### ISSUE THREAD

**Issue by krugert** [notepad-plus-plus/notepad-plus-plus#9586]
### Description of the Issue
Could you please change the Open file dialog in Notepad++ as shown in the 1st image attached (notepad++ open dialog.png) to the open file dialog shown in the 2nd attached image (sublime open dialog.png).

![notepad++ open dialog](https://user-images.githubusercontent.com/16652943/109297207-5128d980-783a-11eb-924d-121e7e82f251.png)
![sublime open dialog](https://user-images.githubusercontent.com/16652943/109297223-584fe780-783a-11eb-9ea0-58402198b3a2.png)
[Notepad++ open file dialog change request.pdf](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6049563/Notepad%2B%2B.open.file.dialog.change.request.pdf)

### Steps to Reproduce the Issue

1. File
2. Open...
3. Open dialog

**Comment by sasumner** [comment]
First, in whatever version you are using, which you didn't supply (WHY????), there is a preference setting that you have unticked, like this:

![image](https://user-images.githubusercontent.com/30118311/109301621-36d50880-7806-11eb-8c71-28063601220b.png)

Had you had it ticked, like this:

![image](https://user-images.githubusercontent.com/30118311/109301676-45bbbb00-7806-11eb-8be4-288bcb88217c.png)

You would not have filed this issue, because the Open dialog would appear like the one you desire.

However, in the newest N++ as of this writing (7.9.3), the setting I show is no longer present, and the Open dialog always looks like the one you desire.

**Comment by krugert** [comment]
Hi There

Thanks for the info provided, I'm using Notepad++ version 7.9.2 which
I'm assuming doesn't have this option either?
However I'll have a look for the option you mentioned below.

Vheers,
Tim K

On 2/26/21, sasumner <notifications@github.com> wrote:
> First, in whatever version you are using, which you didn't supply (WHY????),
> there is a preference setting that you have unticked, like this:
>
> ![image](https://user-images.githubusercontent.com/30118311/109301621-36d50880-7806-11eb-8c71-28063601220b.png)
>
> Had you had it ticked, like this:
>
> ![image](https://user-images.githubusercontent.com/30118311/109301676-45bbbb00-7806-11eb-8be4-288bcb88217c.png)
>
> You would not have filed this issue, because the Open dialog would appear
> like the one you desire.
>
> However, in the newest N++ as of this writing (7.9.3), the setting I show is
> no longer present, and the Open dialog always looks like the one you
> desire.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9586#issuecomment-786626168


-- 
Kind Regards,

*Tim Kruger* | *Entrepreneur | Freelance Software Developer | Ideas
Guy | Extreme Sports Fanatic*

**Comment by sasumner** [comment]
7.9.2 **_HAS_** the option, otherwise I would **_not_** have indicated that 7.9.3 is the first version to **_NOT_** have it:

from 7.9.2:

![image](https://user-images.githubusercontent.com/30118311/109305383-a39ed180-780b-11eb-92dc-23d37f4bb321.png)

same spot in 7.9.3:

![image](https://user-images.githubusercontent.com/30118311/109305287-7eaa5e80-780b-11eb-89a4-e2e1f98d1053.png)

If you want to keep using 7.9.2 (which is fine), tick the checkbox circled in red in the 7.9.2 screenshot.

**Comment by krugert** [comment]
Great thanks very much, I found the option as you specified.
So I'm assuming 7.9.3 has the new style dialog by default?
Hence the exclusion of that option.

On 2/26/21, sasumner <notifications@github.com> wrote:
> 7.9.2 **_HAS_** the option, otherwise I would **_not_** have indicated that
> 7.9.3 is the first version to **_NOT_** have it:
>
> from 7.9.2:
>
> ![image](https://user-images.githubusercontent.com/30118311/109305383-a39ed180-780b-11eb-92dc-23d37f4bb321.png)
>
> same spot in 7.9.3:
>
> ![image](https://user-images.githubusercontent.com/30118311/109305287-7eaa5e80-780b-11eb-89a4-e2e1f98d1053.png)
>
> If you want to keep using 7.9.2 (which is fine), tick the checkbox circled
> in red in the 7.9.2 screenshot.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9586#issuecomment-786645084


-- 
Kind Regards,

*Tim Kruger* | *Entrepreneur | Freelance Software Developer | Ideas
Guy | Extreme Sports Fanatic*

**Comment by sasumner** [comment]
>So I'm assuming 7.9.3 has the new style dialog by default?
Hence the exclusion of that option

Basically correct.  7.9.3 totally reworks the Open/Save/Browse dialogs, so much so that this change prevents Notepad++ from running on Windows XP.  But at a user level, the dialogs will basically look the same as the one you indicated you prefer.
