### ISSUE TITLE
Scintilla 4.4.6 (x64)  - regression  'Find Result' field 

### ISSUE THREAD

**Issue by GOLEM777** [notepad-plus-plus/notepad-plus-plus#9595]
At the moment, I cannot fully describe the reproduction of the problem.
But it get with periodic search with at the same time editing of files.

![capture_02282021_112247](https://user-images.githubusercontent.com/13437340/109412856-6d07b900-79bb-11eb-97d5-c032b7a0ee6a.png)

![capture_02282021_112714](https://user-images.githubusercontent.com/13437340/109412857-6e38e600-79bb-11eb-9e17-4970acf1b4f9.png)
English version with english text!

![capture_02282021_115516](https://user-images.githubusercontent.com/13437340/109412966-0c2cb080-79bc-11eb-9d68-e37130ff5305.png)

![capture_02282021_115912](https://user-images.githubusercontent.com/13437340/109413106-d89e5600-79bc-11eb-9715-6ddac7e7476e.png)

------
Notepad++ v7.9.3   (64-bit)
Build time : Feb 14 2021 - 03:15:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.804
Current ANSI codepage : 1251
Plugins : ComparePlugin.dll DSpellCheck.dll NavigateTo.dll NppDocShare.dll NppQrCode64.dll SelectToClipboard.dll zoomdisabler_x64.dll _CustomizeToolbar.dll

**Comment by GOLEM777** [comment]
A litle more information...

1 - Last searching  - **BLUE** underline 
2 -  Previous searching` "%ConfirmInv` - **RED** underline 

Text of info displace last searching text.
![capture_02282021_131337](https://user-images.githubusercontent.com/13437340/109415595-9c71f200-79ca-11eb-8ec6-6a15af4bb9cb.png)

Note: 
Search = Поиск (rus)

**Comment by Uhf7** [comment]
I can reproduce the issue like follows:

1. Open a new file and leave it empty
2. Open Find dialog, Find tab (Ctrl-F)
3. Find what: `abc`
4. Click "Find All in Current Document"
5. The result is displayed correctly:
  `Search "abc" (0 hits in 0 files of 1 searched)`

From here, there are two ways:
- Good: Repeat step 4 without any interaction with the Search Results window: everything is fine
- Bad: Click at the text in the search result window, anywhere after the first `S` of `Search`. Now, the internal cursor of the Search Results window is not at position 0 anymore, and the result lines of the next search get mixed.

I could "repair" it by clicking before the first character in the Search Results window.

The effect occurs only with the new SciLexer.dll 4.4.6, not with 4.2.0. I used an Appveyor artifact (32 bit release) for testing, combined with a current debug build of the Notepad++.exe, producing a version info like this:

Notepad++ v7.9.3   (32-bit)
Build time : Mar  1 2021 - 21:12:00
Path : C:\Tools\Npp\Npp\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1607
OS Build : 14393.576
Current ANSI codepage : 1252
Plugins : MenuIcons.dll SessionMgr.dll

**Comment by donho** [comment]
If the mouse click is on the non zero position in the search result, it seems `SCI_ADDTEXT` call doesn't set the current position to the last added character - that makes all the chaos because the wrong position get from `SCI_GETCURRENTPOS`  in the search result.
I'm not sure it's an regression of Scintilla (by searching on its bug trackers, I didn't see any related opened bug), but `SCI_ADDTEXT` behaviour has been changed for sure.
I keep finding a solution for this critical regression (regression at least in Notepad++). If anyone has any idea about this bug, please let me know.

**Comment by Uhf7** [comment]
OK, I think, `SCI_ADDTEXT` is broken in the new Scintilla. It can happen, that it moves the current position twice as far forward than it should during `SCI_ADDTEXT`.

There are two factors to it:
- There is a modification of the function `SelectionRange::MoveForInsertDelete` in `Selections.cxx`.

   This function updates positions of caret(s) and anchor(s).

   I don't fully understand yet, how it is supposed to work in Scintilla 4.4.6, but sure is, that the caret is moved here now, but only if the anchor position of the current selection is greater than the caret position.

   In Scintilla 4.2.0., however, the caret is not moved, if the insertion position is equal to the caret position.

   This creates a slightly complex behavior.

- The caret position is moved forward in the `SCI_ADDTEXT` switch case of `Editor.cxx` in both versions of Scintilla, so that the text length is added twice to the caret position in Scintilla 4.4.6 sometimes.

I see a workaround:
Replace `_scintView.execute(SCI_SETCURRENTPOS, 0);`
with 	`_scintView.execute(SCI_SETSEL, 0, 0);`
in 	`Finder::beginNewFilesSearch()`.

This works now with Scintilla 4.2.0, with Scintilla 4.4.6, and it should work with the future fixed Scintilla version too.

**Comment by donho** [comment]
@Uhf7 
Thank you for the workaround! It does work indeed.
Thank you also for the explanation.
It's more clear to me now it's a regression in Scintilla 446.
