### ISSUE TITLE
Release key expires tomorrow

### ISSUE THREAD

**Issue by TomyLobo** [notepad-plus-plus/notepad-plus-plus#9626]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/README.md
This lists "2021-03-10" as the expiry date of the Notepad++ Release Key.
Uh, that's tomorrow, so will that break anything?

**Comment by pryrt** [comment]
@TomyLobo , as I [explained in the forum](https://community.notepad-plus-plus.org/topic/20858/release-key-expires-tomorrow), it's not critical, because it won't prevent people from installing or using Notepad++.

But it would be nice if the key was not listed as expired, because otherwise people who like checking GPG signatures won't be complaining.

@donho, you should be able to [edit the expiration date](https://www.google.com/search?q=gpg+edit+expiration+date) on the existing key, and then re-publish the [public key](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/nppGpgPub.asc) .

**Comment by TomyLobo** [comment]
Don't forget to update the key in the repo:
```
$ curl -s https://raw.githubusercontent.com/notepad-plus-plus/notepad-plus-plus/master/nppGpgPub.asc | gpg -
pub  4096R/8D84F46E 2019-03-11 Notepad++ <don.h@free.fr>
sub  4096R/DFABBC55 2019-03-11 [expires: 2021-03-11]
```

**Comment by donho** [comment]
@TomyLobo 
I just did:
```
$ gpg --keyserver pgp.mit.edu --send-keys 14BCE4362749B2B51F8C71226C429F1D8D84F46E
gpg: sending key 6C429F1D8D84F46E to hkp://pgp.mit.edu
```
But not sure the effect is taken.
Could you check it and confirm it to me please?

**Comment by TomyLobo** [comment]
`nppGpgPub.asc` on the github repo is still expiring tomorrow

**Comment by donho** [comment]
Could you give me an hint to get the new pub key?

**Comment by Doridian** [comment]
Usually you can export the key using `gpg --armor --export 14BCE4362749B2B51F8C71226C429F1D8D84F46E > file.asc` and then you should be able to push it up to github like that.

**Comment by donho** [comment]
I have updated the public key here:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/nppGpgPub.asc

I hope I didn't miss anything.
