### ISSUE TITLE
Scrollbar Reset

### ISSUE THREAD

**Issue by amoltarte** [notepad-plus-plus/notepad-plus-plus#9637]
Notepad++ does not reset the horizontal scrollbar after splitting large line in multiple lines.
Severity: Very Low

### Steps to Reproduce the Issue

1. Write a looooooong line (Say SQL statement)
2. split it to multiple lines using find / replace ( , to be replaced by \n) or use any SQL formatter plugin
3. 

### Expected Behavior

Horizontal scrollbar to be hidden if everything is inside page.

### Actual Behavior

Horizontal scrollbar remains same as when entered a long line.

**Comment by sasumner** [comment]
Perhaps people would stop complaining about this if the horizontal scrollbar was simply always shown; hmm, but that would waste space for the typical case.  NVM, they'd still complain.  :-)

It's problematic for a number of reasons, probably discussed before in other issues of this nature.  Here's one example:  What happens if you have lines that are long enough to need a horizontal scrollbar in one section of your document, but you are currently working in a section of your document where all lines shown are short enough not to need it.  Is the bar shown, or not?  Some would argue yes, some would argue no, and of course some wouldn't care.

Regardless, this is a "won't fix" issue.

**Comment by mogu1121** [comment]
can let the user choose in the preferences
