### ISSUE TITLE
NPP not starting since 7.9.3

### ISSUE THREAD

**Issue by TheColin21** [notepad-plus-plus/notepad-plus-plus#9660]
Notepad++ does not start since version 7.9.3. The current version 7.9.4 does not start either. Both versions throw this error in the Windows Event viewer: 

> 
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-03-15T15:15:33.1994515Z" /> 
  <EventRecordID>211371</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>Colin-PC</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>notepad++.exe</Data> 
  <Data>7.9.4.0</Data> 
  <Data>604ea4e0</Data> 
  <Data>clr.dll</Data> 
  <Data>4.8.4300.0</Data> 
  <Data>5f7e616e</Data> 
  <Data>c0000005</Data> 
  <Data>0000000000669f10</Data> 
  <Data>3538</Data> 
  <Data>01d719ae0ac99cbf</Data> 
  <Data>C:\Program Files\Notepad++\notepad++.exe</Data> 
  <Data>C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll</Data> 
  <Data>f906f3dd-9f5a-423c-ae7d-b07fd7fcd362</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by TheColin21** [comment]
Tried to insert XML, didn't work very well

**Comment by sasumner** [comment]
SaveAsAdmin plugin?
If so, Remove it for now.
And please report back here.

**Comment by TheColin21** [comment]
yeah that was it, thanks

**Comment by donho** [comment]
@sasumner 

Do we know the reason of SaveAsAdmin plugin prevent Notepad++ from starting up since v7.9.3 ?

**Comment by sasumner** [comment]
>Do we know the reason of SaveAsAdmin plugin prevents Notepad++ from starting up since v7.9.3 ?

I believe it is related to the introduction of the new open/save/browse dialogs in N++.
@mere-human can probably provide more detail on it.

The author of SaveAsAdmin has released a new version that makes it compatible with 7.9.3+.

But unfortunately this type of issue reporting is likely to continue for quite a while to come.
When N++ doesn't start, it is automatically N++'s fault. :-(

**Comment by dodmi** [comment]
@donho, @sasumner : The cause is described at the [SaveAsAdmin issue tracker](https://github.com/Hsilgos/nppsaveasadmin/issues/24): 
After the open/save dialog changes in NPP 7.9.3, the plugin throws an exception upon initialization, which is never caught and leads to a silent crash of NPP 7.9.3 / NPP 7.9.4.

The author provided a fix within days, but this requires awareness and manual action by any user.
- Because of the silent crash, the user has no hint of the cause and needs to search himself
- Plugin Admin is unreachable (as it's only available in NPP itself), so the plugin must be removed manually from the NPP plugin folder
- Plugin Admin doesn't show the latest version (so even after the new version was checked into the plugin repository, users, who manually removed SaveAsAdmin got the old version vie plugin admin), so the updated version must be manually downloaded and put into the right place, to get the features back
- I've opened [an issue for NPP](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9514) to improve plugin handling. But from the answers, I got the impression, that NPP can't do anything to get more robust against those sort of crashes. [If you really can't do anything about that, you may close my issue]
- You had a block list in the installer for old versions of HexEditor, which offered to remove the plugin at install - it would be handy to handle old versions of SaveAsAdmin this way, so that users of upcoming versions of NPP would be aware of the issue at install time (please read my suggestions in the issue here, before closing).

**Comment by mere-human** [comment]
> Do we know the reason of SaveAsAdmin plugin prevents Notepad++ from starting up since v7.9.3 ?

Yes. There is a bug in NppSaveAsAdmin repository that provides all the details:
https://github.com/Hsilgos/nppsaveasadmin/issues/24
In general, the plugin hooks up functions `GetSaveFileName` and `GetOpenFileName` to elevate privileges before file access.
In 7.9.3 and later Notepad++ doesn't use these functions anymore for file operations.
The plugin can't resolve mentioned functions and throws an exception during the DLL loading which causes a whole application to crash. If an exception was thrown after the DLL is loaded, it would have been handled correctly.

But in the most recent version of the plugin, the problem should be fixed.

Also, there is a related issue #9561 about implementing "save as admin" functionality correctly in the Notepad++ itself.

**Comment by donho** [comment]
Thank you everyone for your suggestions.
I just posted a comment [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9514#issuecomment-800324744)
Let's talk about this issue in this thread.

**Comment by mere-human** [comment]
What if the Notepad++ installer could offer an option to upgrade plugins during while installing a new version?
If a user agrees, then the installer would do this:
1. Remember the installed plugin list
2. Remove any existing plugins
3. Install the latest version for each plugin in the list

Or do a similar check for the latest plugin version via Plugin Admin and prompt the user.
