### ISSUE TITLE
Protecting Notepad++ community & preserving our Internet environment

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#9663]
[Announcement on Twitter](https://twitter.com/Notepad_plus/status/1371579205817864192)

Several Notepad++ users inform us there are 3 fake sites of Notepad++ under the following domains:
1. https://notepa-plus-plus.org/
2. https://note-pad.ccmmsl.com/
3. https://notepadplusplusdownload.com/

The malwares are distributed in the 3 fake sites.

Please help us to report the 3 fake sites above by using the 2 following links:
1. https://safebrowsing.google.com/safebrowsing/report_badware/?hl=en
2. https://microsoft.com/en-us/wdsi/support/report-unsafe-site-guest

It's not only for protecting Notepad++ community, but also for preserving our Internet environment.

**Comment by rdipardo** [comment]
<ol><li>https://notepa-plus-plus.org</li>
<li><strike>https://note-pad.ccmmsl.com</strike></li>
<li>https://notepadplusplusdownload.com</li></ol>

~~~shell
$ nslookup note-pad.ccmmsl.com 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find note-pad.ccmmsl.com: NXDOMAIN
~~~

**Comment by rdipardo** [comment]
According to WHOIS, domains n.<sup>o</sup> 2 and 3 were registered with NameCheap:

- <https://www.whois.com/whois/ccmmsl.com>
- <https://www.whois.com/whois/notepadplusplusdownload.com>

This might explain what happened to them: 
### [Namecheap ends service for Russian customers due to government's war crimes]


[Namecheap ends service for Russian customers due to government's war crimes]: https://www.theverge.com/2022/3/1/22956581/russia-ukraine-namecheap-ends-service-war-crimes
