### ISSUE TITLE
Word separators ` `, `/`, and `\` work differently in the Search's textarea. (Space, Slash or Forwardslash, and Backslash.)

### ISSUE THREAD

**Issue by sapioit** [notepad-plus-plus/notepad-plus-plus#9675]
Word separators ` `(space), `/` (slash or forwardslash), and `\` (backslash) work differently in the Search's textarea.

### Steps to Reproduce the Issue
1. Press Ctrl+F to open the Find window.
2. Write `aa/bb\cc/dd ee` (random characters).
3. Hold `Shift` pressed down and press `Left` 3 times, observing the result after each press.

### Expected Behavior
4. It selects selects `b`.
5. Selects `dd ee`.
6. Selects `cc/dd ee`

### Actual Behavior
4. Selects `ee`.
5. Selects `\cc/dd ee`.
6. Selects `aa/bb\cc/dd ee`

### Debug Information
Notepad++ v7.9.4   (32-bit)
Build time : Mar 15 2021 - 01:00:14
Path : V:\Programs\Notepad++Portable\App\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
>Hold Shift pressed down and press Left 3 times, observing the result after each press.

Shift+arrow does not select text.
Perhaps you mean Shift+Control+arrow?  That combination selects text.
The rest of my comments here presume you mean this.
Additionally, I think in your "Expected Behavior" step 4 you meant to say "selects `ee`" instead of "selects `b`"?  There is no `b` on the right-hand side of the _Find what_ expression.
Please make a bit more of an effort to get things correct in your issue description, so that people can more easily reproduce and understand what you are discussing.

What you describe is a Windows behavior, not a Notepad++ behavior.
Try it in Windows' notepad.exe -- you'll see the same result -- example after your step 5:

![image](https://user-images.githubusercontent.com/30118311/111866882-f10fe980-8946-11eb-93b1-b445c8181ae4.png)

Could this be changed in Notepad++?  Yes, but then perhaps their are situations where other users, that are familiar with and understand the default Windows behavior for such a thing, are disappointed, and open future issues requesting the Windows behavior be restored.

**Comment by sapioit** [comment]
> > Hold Shift pressed down and press Left 3 times, observing the result after each press.
> 
> Shift+arrow does not select text.
> Perhaps you mean Shift+Control+arrow? That combination selects text.

Yes, my bad, I forgot about the `Ctrl` key. Thank you for pointing it out!


> The rest of my comments here presume you mean this.
> Additionally, I think in your "Expected Behavior" step 4 you meant to say "selects `ee`" instead of "selects `b`"? There is no `b` on the right-hand side of the _Find what_ expression.

Again, thank you! I thought I changed it, but I apparently only written it in the "actual behaviour" part.

> Please make a bit more of an effort to get things correct in your issue description, so that people can more easily reproduce and understand what you are discussing.

Thank you! I updated it.

> What you describe is a Windows behavior, not a Notepad++ behavior.
> Try it in Windows' notepad.exe -- you'll see the same result -- example after your step 5:
> 
> ![image](https://user-images.githubusercontent.com/30118311/111866882-f10fe980-8946-11eb-93b1-b445c8181ae4.png)
> 
> Could this be changed in Notepad++? Yes, but then perhaps their are situations where other users, that are familiar with and understand the default Windows behavior for such a thing, are disappointed, and open future issues requesting the Windows behavior be restored.

It could be a added with a checkbox in the search window, to include more word separators. For example, like in the edited screenshot below. (The added text is slightly yellower, to be easier to spot.)

![screenshot 970](https://user-images.githubusercontent.com/3173159/111887819-45b37300-89e0-11eb-9890-474b0f6ba2ca.png)

**Comment by sasumner** [comment]
>It could be a added with a checkbox in the search window

I'm certain the author of Notepad++ wouldn't accept that kind of change.
It simply isn't important enough.  Sorry.

**Comment by sapioit** [comment]
> > It could be a added with a checkbox in the search window
> 
> I'm certain the author of Notepad++ wouldn't accept that kind of change.
> It simply isn't important enough. Sorry.

Thank you! I hope the author does accept that kind of change, but I can only hope.
