### ISSUE TITLE
Recorded macros with find/replace commands

### ISSUE THREAD

**Issue by naiveknave** [notepad-plus-plus/notepad-plus-plus#968]
Find/replace commands work fine during macro recording, and macros that include these commands do what they're supposed to with no problems. Usually, when recording a macro, other macros that have been recorded and saved can be implemented, and their individual commands get inserted into the macro currently being recorded - however, this does not work when implementing a macro that includes any kind of find/replace command.

For example, if I have a macro called 'move_left_3_times', which includes 3 move-left commands, I can implement this when recording a new macro. If I want to create one called 'move_left_6_times', rather than manually typing the left arrow six times, I can simply implement 'move_left_3_times' twice while recording. This works just fine.

However, if I record a macro called 'replace_next_foo_with_bar', which simply finds the next appearance of 'foo' and replaces it with 'bar', I cannot then record a macro called 'replace_next_2_foos_with_bars' by implementing 'replace_next_foo_with_bar' twice during recording.

If this bug could be fixed, the macro-recording feature would be tremendously more useful as I would be able to record the smaller building-blocks of my macros independently and then quickly build more complex macros that are each distinct but made of the same basic components.

**Comment by mslonik** [comment]
Hi naiveknave, Could you please check if recording of macros in Notepad++ ver. 6.8.3 works as expected? In order to do that please:
a. move temporarily file with your macros (C:\Users(...)\AppData\Roaming\Notepad++\shortcuts.xml) to safe location,
b. restart Notepad++, so new (empty) file named shortcuts.xml will be automatically created in the same location,
c. try to record any macro, preferably of the kind 'find / replace',
d. try to safe a macro and then restart Notepad++.
Let us know if you were able to rerun this macro after restart of Notepad++.
Remark: If it doesn't work to you, don't forget to move your original file with macros to initial location.
Regards, mslonik.

**Comment by naiveknave** [comment]
Thanks for responding. One of the first things I tried was exactly as you said. I had tried that with version 6.8.1. Just now I installed 6.8.3 and tried all of that again - the problem persists.

Again, macros that are recorded with find/replace commands work just fine on their own. The problem begins when I try to use one of these *while recording a new macro*. All commands embedded in a macro I use while recording automatically get put into the new macro's command list - except the ones that involve find/replace.

In fact, when I record a macro that consists *only* of find/replace commands (call it X), then invoke it one or more times while recording a new macro (call it Y) - and do nothing else except invoke X - by the time I have stopped recording and wish to save Y, I don't have that option. It's as if I had clicked 'record', then clicked 'stop recording' immediately without doing anything. If, however, X contains other commands (e.g. 'move-left'), I can save Y after only invoking X during recording. When I do this though, only X's non-find/replace commands get copied in - it's as if I had skipped the find/replace commands entirely.

Please try to reproduce this and let me know if you can.

**Comment by mslonik** [comment]
Hi naiveknave. I confirm this problem, n++ 6.8.3.

Here is a text file which I've prepared (beginning of the file: ---, end of the file: ---):

---
MacrO1: exchange letter O with capital O. CRLF
CRLF
MacrO2: add three rOws Of text: aaa, bbb, cccCRLF
aaaCRLF
bbbCRLF
cccCRLF
CRLF
NOw put sOme text cOntaining letter 'O':CRLF
CRLF
One, twO threeCRLF
NOw start recOrding twO abOve macrOs:
aaaCRLF
bbbCRLF
cccCRLF
CRLF
Now let's try to rerun combo:CRLF
aaaCRLF
bbbCRLF
cccCRLF
---

As one might see combo doesn't work as expected.
Please notice that I still can't store any macro between reopening of n++ due to a bug #992.

Regards, mslonik

**Comment by ReFuller1** [comment]
I may not be in the correct thread, please redirect me if I'm wrong.  I am wondering if it is possible to edit macros after they are saved?

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
