### ISSUE TITLE
[Ideas] File type icons in tabs in "saved" state; tab pinning; option for standard visual style for tabs

### ISSUE THREAD

**Issue by monstercho** [notepad-plus-plus/notepad-plus-plus#9699]
Hi,

I'm doing quick and dirty experiments in Notepad++ repo fork for personal use and was wondering if it's interesting for others. Example screenshot:
![image](https://user-images.githubusercontent.com/15175445/112371250-1013d000-8ce7-11eb-8271-af77540bc065.png)
- **Show file type icons in tabs.** Used only when tab is in 'saved' state. Downside: disabled alternative icons setting.
- **Support for pinned tabs.** Pinned tabs cannot be closed and show only the first filename char as tab title. Pin/unpin from tab context menu. Tabs 'm', 'o' and 'c' in the screenshot are pinned.
- **Tabs use standard visual style.** Downsides: no **multi-line** and **vertical** tabs; no **close** button in tabs (middle mouse button or double click instead). 

My C++ is very rusty and those experiments are not good for PR. Just done fast to see the result.

**Comment by mere-human** [comment]
@monstercho at least first 2 points look interesting as for me!

**Comment by sasumner** [comment]
For me the first two are okay but the third one is not good.  No multi-line would be trouble for me.  But as optional behavior I suppose all are okay.

For the file type icons, I would think such a feature would need to be made compatible with the "alternate" icons when the file is unsaved or readonly (as those icons offer much improvement over the "diskette" icons).  I don't know that showing the file type icons has A LOT of value, but visually it looks nice.

Do the "pinned" tabs get pinned where they are in the tab-order at the time of pinning? Or does a tab that gets pinned automatically move to the left side and put adjacent to any other pinned tabs?
In general, I don't really understand the "pinned" tabs desire.  If you don't want a tab closed, don't close it.  If the desire is to make the tab width smaller on it, that can make some sense, and I suppose showing only the first letter of its name is reasonable but has some drawbacks.

You can certainly try to get your changes accepted.
However, if you do so, please break this into 3 separate issues and deal with each independently.
I realize that this issue was created to solicit feedback -- try to remember to come back and close it at some point.

**Comment by monstercho** [comment]
Thanks for the feedback!

> to be made compatible with the "alternate"  ... as those icons offer much improvement over the "diskette" icons

Will try to make it compatible. 

> I don't know that showing the file type icons has A LOT of value, but visually it looks nice.

Indeed my goal was to look nice :) Sometime it's also useful when looking for specific file like csv, but only if you have many opened.

> Do the "pinned" tabs get pinned where they are in the tab-order at the time of pinning?

They move to the left, but I haven't disabled manually dragging them back into the unpinned tabs. Probably should?
I also want to have slightly different icon for pinned tabs - the file type icon + page corner fold for example.

> If the desire is to make the tab width smaller on it

Yes, not sure if good idea in general. I decided to try using NPP also for note files into google drive folder as replacement for Sticky Notes to have auto backup and versions (got into bad habit of using stickies for important stuff). So I thought it will be good if they take minimum space since those tabs will be persistent in such usage. 
I use a lot of pinned tabs and workspaces in Opera, but don't think they are so useful in NPP as in browser.
 
Maybe will try to make PRs in free time according to contributing rules and your suggestions. Currently it's too dirty disabling incompatible functionality with #defines, not real options.

Will close the issue soon.
