### ISSUE TITLE
Add an option to change the line spacing

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#971]
I had the impression that the lines are more tight in Notepad++ than in other editors for a while now. And directly comparing a document (or just line numbers) from Visual Studio shows that there seems to be an extra line spacing of one pixel. Text is easier to read with a slightly increased line spacing so I'd suggest adding an option to change the default spacing of lines, both negative and positive.

This should be possible with Scintilla ([reference](https://github.com/jacobslusser/ScintillaNET/wiki/Increase-Line-Spacing)).

**Comment by dail8859** [comment]
It is possible. Would be nice to have a specific option for this. I know some other editors do and it can make a big difference. As a *temporary* solution, I think if you install nppexec you can specifically make Scintilla calls and use [these](http://www.scintilla.org/ScintillaDoc.html#SCI_SETEXTRAASCENT) if you'd like this sooner rather than later :)

**Comment by dg9ngf** [comment]
The nppexec plugin had a problem and it was not recommended to install it. I'd vote for the integrated option.

**Comment by aaaxx** [comment]
I bump up the size of "Indent guideline style" as a workaround.

**Comment by dg9ngf** [comment]
Thanks for the workaround. I also needed to select another font to make more fine-grained adjustments. When 10pt Consolas is your editor font, 10pt Tahoma makes one pixel more per line. 11pt Consolas is already much bigger.

**Comment by u01jmg3** [comment]
For anyone wondering, this is the command to run:

```
NPP_CONSOLE 0
SCI_SENDMSG SCI_SETEXTRAASCENT 5
SCI_SENDMSG SCI_SETEXTRADESCENT 5
```

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by dinkumoil** [comment]
I wrote a plugin that that can be used to configure an extra spacing above and beneath lines. Its name is _ExtSettings_. You can download it [>>> here <<<](https://sourceforge.net/projects/extsettings/). It will also be available soon via _PluginsAdmin_.

**Comment by cyrildtm** [comment]
> 
> 
> I wrote a plugin that that can be used to configure an extra spacing above and beneath lines. Its name is _ExtSettings_. You can download it [>>> here <<<](https://sourceforge.net/projects/extsettings/). It will also be available soon via _PluginsAdmin_.

Thank you dinkumoil. However when I try to install the plugin, nothing shows up. My Notepad++ version is v7.7.1 32-bit, and I'm using several methods like Setting -> Import -> Import plugin, and copying the dll file to the plugins folder.

**Comment by cyrildtm** [comment]
> 
> 
> For anyone wondering, this is the command to run in NppExec to achieve increased line padding:
> 
> ```
> NPP_CONSOLE 0
> SCI_SENDMSG SCI_SETEXTRAASCENT 5
> SCI_SENDMSG SCI_SETEXTRADESCENT 5
> ```

This method works for displaying on screen, but does not affect printing.

**Comment by dinkumoil** [comment]
@cyrildtm 

> when I try to install the plugin, nothing shows up

Please follow installation instructions at the [download page](https://sourceforge.net/projects/extsettings/files/).

> This method works for displaying on screen, but does not affect printing.

That's true, the Scintilla component doesn't take into account extra line spacing when printing, I'm not aware of any command to change that behaviour. But you could make a feature request [at the project's home page](https://sourceforge.net/projects/scintilla/).
