### ISSUE TITLE
Function List button tool tips are mixed up

### ISSUE THREAD

**Issue by mere-human** [notepad-plus-plus/notepad-plus-plus#9804]
### Description of the Issue

![image](https://user-images.githubusercontent.com/9664141/116144028-817ae000-a6e4-11eb-8e0c-02bdfbe312f5.png)
![image](https://user-images.githubusercontent.com/9664141/116144057-8a6bb180-a6e4-11eb-99d0-f6844cea79f9.png)

### Steps to Reproduce the Issue

1. View > Function List
2. Hover a cursor over the buttons in the Function List panel

### Expected Behavior

1st button shows a tool tip "Reload" and 2nd button shows "Sort".

### Actual Behavior

Should be vice versa.

### Debug Information
```
Notepad++ v7.9.5   (64-bit)
Build time : Apr 24 2021 - 12:11:48
Path : E:\Development\notepad-plus-plus\PowerEditor\visual.net\x64\Unicode Debug\Notepad++.exe
Command Line : -nosession -multiInst
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.928
Current ANSI codepage : 1252
Plugins : none
```

**Comment by vinsworldcom** [comment]
Seems to have been fixed in one of the commits since 7.9.5 - as I'm running the latest AppVeyor 64-bit EXE:

![image](https://user-images.githubusercontent.com/9657169/117053807-6a8d4c80-ace7-11eb-8923-f7fdb7a31c9c.png)


Notepad++ v7.9.5   (64-bit)
Build time : May  1 2021 - 18:25:12
Path : C:\usr\bin\npp64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1500
Current ANSI codepage : 1252
Plugins :

**Comment by sasumner** [comment]
@vinsworldcom 

Not sure why it would appear OK for you.  Here's the problem:  

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/cd1a468b1c0b6668daac4f9ff01f8a806699cb91/PowerEditor/src/WinControls/FunctionList/functionListPanel.h#L116

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/cd1a468b1c0b6668daac4f9ff01f8a806699cb91/PowerEditor/src/WinControls/FunctionList/functionListPanel.h#L117

I will do a quick PR to fix this.

**Comment by vinsworldcom** [comment]
@sasumner Weird!

Could it be the localization file I'm using is overriding the code - although those code snippets you show don't seem to be localized.

Cheers.
