### ISSUE TITLE
Handling of "In Selection" in FIND and REPLACE modal is a bad user interface

### ISSUE THREAD

**Issue by biz1atrichardcarlson** [notepad-plus-plus/notepad-plus-plus#9811]
Handling of "In Selection" in FIND and REPLACE modal is a bad user interface

When text is selected, and the "In Selection" box is ticked, clicking the button "Find all in Current Document" only finds the search string in the currently selected text. 

This is a change from the prior version, and not a good one. 

While it's probably convenient to be able to search/replace within selected text, the label on the button is completely misleading.

I would prefer two button, one devoted to searching/replacing within the selected text and one devoted to searching/replacing within the entire file. 

I would also prefer that the "In selection" setting be maintained for both the SEARCH and the REPLACE modals independently (Ie, if you select for one modal, it does not set to the other).
(See attached image)

 
### Steps to Reproduce the Issue

1. ctrlf-f
2. tick "In Selection"
2. Select some text
3. ctrl-f
3. click "Find all in current document"

### Expected Behavior
It says "Find All in Current Document".... it should do this.

### Actual Behavior
It only finds within the selection (the box around "in selection" implies this, but (a) it's inconvenient (b) it's a change in behavior from prior versions and (c) it's very subtle.)

### Debug Information
v 7.9.5 (32 bit)
n/a

![Image1](https://user-images.githubusercontent.com/83347118/116397813-0d7c2d00-a7f5-11eb-9ef2-b4b6841cb5bc.jpg)

**Comment by sasumner** [comment]
Thank you for your comments.
Unfortunately, UI design is often a controversial and subjective thing.

>it's very subtle

It is, a bit subtle; sadly Windows' color scheme doesn't make group boxes stand out as much as desired.  An upcoming version of N++ will feature an internal "dark mode" which makes it less subtle; sample:

![image](https://user-images.githubusercontent.com/30118311/116407143-736db200-a7ff-11eb-876a-e19f56b6853e.png)

But in general, we like this UI as it is now, so we won't be making any changes based upon the inputs in this issue.  Sorry.

**Comment by sasumner** [comment]
>If anyone else is interested, you can fix this by downgrading

I'm not sure why anyone (else) would downgrade in order to get less functionality, but to each his/her own.

>7.8.8 ... introduced the bug where prior selections are not respected in the REPLACE modal.

I'm not sure what this means.
If it is important, please say more about it.

**Comment by biz1atrichardcarlson** [comment]
_I'm not sure why anyone (else) would downgrade in order to get less functionality, but to each his/her own._

It's not to get "less" functionality, it's to get the functionality specified by the button ("Find All In Current Document"). The button label is wrong when "in selection" is set. **It does not do what it says**. So if you select/^F/Find All in Current Document, all you get is the current line. You then need to unset the "In selection" to get the actual function it purports to be. For me, the expansion of the "In selection" scope from "Count" to "Find" was both ill-advised and not well implemented (at the very least, the button label should change, it would still be inconvenient, but it would at least be an accurate description of function)

_7.8.8 ... introduced the bug where prior selections are not respected in the REPLACE modal._

On occasion, if you have pre-selected some text, access the REPLACE modal, the "In Selection" is grayed out. You then need to go back to the edit screen and reselect the block of text. I'm not sure how to reproduce, so I'm not reporting as an official bug (and since I've downgraded to avoid the error above, I probably will not encounter it again).

**Comment by sasumner** [comment]
>It does not do what it says

Not to go too far down this (subjective UI design) road, but it is probably best to think of the _In selection_ checkbox within the groupbox as an **override** to the stated button functionality.

That's the way I've always thought of it, just like _In selection_ does for _Replace All_ , which curiously you did not mention as suffering from a similar problem, and in some ways (what is "all"?) is arguably worse.  Downgrading may not help with that one.

**Comment by biz1atrichardcarlson** [comment]
This was functionality that changed in 7.8.8 in the FIND modal. The 
REPLACE modal functioned similarly to this in prior versions, but the 
use-case is different and the "In Selection" modifier makes more sense 
there.

The major problem with FIND is that I want to double click to select the 
word I want to find and then search the entire document for it. Instead, 
it just searches the text I just selected, even though the button claims 
it will search the entire document. Then I have to think for a 
second..."wait a minute.... I know I use that variable all over the 
place... WTF?"

I then remember to "untick" the "in selection" every time I want to 
search to get the old functionality back. I honestly don't think I'd 
ever use the "find all in selection", if I'm doing something like that 
I'll use find next to cycle down.

Clearly, the choice of "REPLACE ALL" is a better label for a button that 
has a modifier such as "In Selection". You should have changed the 
button on the FIND modal to "FIND ALL" to be consistent. Instead, it's 
now just misleading.

Honestly, however, with so much configuration in the rest of the editor, 
you'd think there would be a way to satisfy everyone 
(Settings/Preferences/MISC./ [ ] Link Selection to Find in Find DIalog-- 
just below "Don't fill in find field in Find Dialog with selected word" )

After a day of using 7.8.7 with the exception of the "Find all in all" 
being in the wrong place (it should have been under the "find all in 
current") it's been quite pleasant not have to fight with the modal 
every time I want to do a search.

BTW, despite the flubs introduced in 7.8.8 NOPTEPAD++ is still one of 
the best on the market. Our entire team uses is on a daily basis. We've 
tried several other IDE's and keep coming back to NPP.

re
-rich

**Comment by sasumner** [comment]
I should have mentioned earlier perhaps that the end user can change almost any text in the user interface, to suit their own tastes and desires.

This probably won't ease the pain of the original poster for this issue, but if any future readers are tempted to take the downgrade advice simply because they disagree with some bit of UI text, here's what you can do:

Locate the file containing your language's translation in Notepad++ configuration file folder structure.  For example, perhaps look for english.xml or english_customizable.xml.  Open that file and locate the UI text you'd like to change.  Change it. Save the file.  Go to _Settings_ menu and choose _Preferences..._.  In the _General_ category, locate _Localization_.  Change that dropdown to select the language corresponding to the xml file you just edited, EVEN IF THAT ONE IS ALREADY THE ACTIVE CHOICE.  At that point the UI text you've altered will be put into use.

As an example, using the original poster's idea above, in the xml file will be found:

`<Item id="1641" name="Find All in Current Document"/>`

Change that to:

`<Item id="1641" name="FIND ALL"/>`

**Comment by Suesskirsche** [comment]
Would it be too complicated / too much effort to alternatively display the text of the button "Find all in current document" to "Find all in selection" depending upon the status of the check box "In selection"?



Am 29. April 2021 02:51:40 MESZ schrieb sasumner ***@***.***>:

**Comment by pryrt** [comment]
> Clearly, the choice of "REPLACE ALL" is a better label for a button that has a modifier such as "In Selection". You should have changed the button on the FIND modal to "FIND ALL" to be consistent. 

To bring in an outsider's perspective:  Part of me wants to agree that changing the (default, as-shipped) text for that button to "Find All" (and thus matching the "Replace All") would be a good idea... But there are two disagreeing voices in my head to that one: 

1) My guess is that the reason why "Find All In Current Document" made sense was to make sure there was no confusion between "... In Current Document" and "... In All Open documents" -- if it were "Find All" for the single-document version, some user might rightfully argue that just "Find All" is not sufficient to describe the button compared to other buttons.  

2) Since the button text is user-configurable, and most users don't seem to be complaining about the text of that button, changing its text at this stage in the game would confuse rather than clarify.  (And other than this issue, I cannot remember a single time I've heard a complaint about this in the Community Forum, where lots of users express their opinions as to just how much the developers missed the mark for changing a certain feature, or for not changing something that they don't like.

> Instead, it's now just misleading. 

It could be considered misleading, but I don't really think so.  For a subset of users, just about any UI choice can be considered misleading; there is only a limited amount of information you can convey in a single dialog box, and the Find (and similar) have a lot going on already.  

The way I think of the phrasing that currently exists: Without the "in selection" checked, the "Find All in Current Document" means it finds all matches that are in the current document.  With the "in selection" checked, the "Find All in Current Document" means it finds all matches that are in the current document _**and**_ are simultaneously in the selection.  That is, there is no contradiction, just an additional restriction added by the checkbox.

You may disagree with my opinions if you like... but that's because they are opinions.  Every Notepad++ user brings their own opinions and desires to the table.  The Development team has the goal of picking and choosing what features to implement or changes to make, in order to make Notepad++ as useful as it can be, while still fitting their particular design styles.  This means that, inevitably, some subset of Notepad++ will disagree with the decisions made.

**Comment by sasumner** [comment]
>...if it were "Find All" for the single-document version...

Just a note to say there's already a `Find All` button, but on the `Find in Files` tab.
While technically there's no prohibition against two buttons having the same caption, creating such a situation could result in "tech support" problems, where a user states they press the `Find All` button, but don't make it clear as to which one, and context doesn't provide a clue either.

**Comment by biz1atrichardcarlson** [comment]
Ahhh.. nothing like UI wars.
I will chose to disagree with you that there is such as thing as "good UI" and "bad UI" and it's not all "opinion". Good UI is clear, does what it says and is not easy for the user to screw up.

![Capture](https://user-images.githubusercontent.com/83347118/116573102-873a1680-a8da-11eb-9764-87f957c876a5.JPG)

Again, my comment was to separate the link between "In selection" and FIND (the way is was in 7.8.7) as it does not play well in the usage model "Select and find in document" and would have preferred if this behavior was selectable by the user. 

(ie, change Settings/Preferences/MISC./ adding a preference:

      [ ] Link Selection to Find in Find Dialog

to be located just below "Don't fill in find field in Find Dialog with selected word" ) 

Preserving the 7.8.7 functionality for those who liked it and allowing others who find the "in selection" criteria linkage useful.

... or, provide a "FIND IN SELECTION" / "FIND IN DOCUMENT" / "FIND IN ALL DOCUMENTS" ability (3 buttons as opposed to 2 with increasing "power") which would probably be the most effective way of providing the capability. 

Look, again, I want to compliment NPP and the development team. This is an excellent piece of code. It's dependable, functional and I use it daily, almost all day long. As I've said, our team has tried to identify "better" environments (IDE's and Editors) for our purposes and we keep coming back to NPP and we are grateful that it's here and we can use it. I just checked our repository and the first version of NPP is 4.6 from 2014 and I know were were using it before then.

My initial comment was intended to highlight an area where functionality changed and that made our job harder. As a developer, I like to hear when our code makes people's lives easier and try to react when they tell me a change is a making their work harder. If we're the only ones who don't appreciate the new setup, we'll just happily live on the old version. That sucks for us, but it's like the pebble in the shoe. Some things you can live with, some things are just such a daily, chronic annoyance that you need to get that pebble out.  

I'm sorry you cannot see your way to making this a configurable option. Thanks for taking the time to respond.

re
-rich
