### ISSUE TITLE
Increase Line Indent malfunction(?)

### ISSUE THREAD

**Issue by Petewg** [notepad-plus-plus/notepad-plus-plus#983]
If you press **[Increase Line Indent]** button, when it is selected (highlighted) a portion of that line (from one letter to many words -but no the entire line), the selected portion is deleted!

As I understand it, seems that [Increase Line Indent] acts like a Tab key-press, which of course, (and similarly to any other key-press over a selected text) means: _replace the selected text with the key pressed._
But _"replace the selected text..."_  is quite a different thing than _"Increase Line Indent"_ --if we do agree that _"Increase Line Indent"_, actually means: _"Add  a Tab character to the BEGINNING of the line(s)."_

regards
Pete

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by Petewg** [comment]
Hi, 
I made the suggested update to version 7.6.6 and tested again; the problem persists (same behavior as described in my 1st post.) I think it's a problem that should be addressed but not sure I 'd want to open this issue again.

My new problem now is that this  7.6.6  update has messed up my setup, because some very useful plugins are not working any more and particularly these:
LanguageHelp, SourceSwitch, and MenuIcons. Also Plugin Manager gives some error..) Trying to fix things... :-(
