### ISSUE TITLE
functionlist in C improper working

### ISSUE THREAD

**Issue by xenpac** [notepad-plus-plus/notepad-plus-plus#9830]
The all important "functionlist" feature is behaving strange in C code.

void Ext0_int(void) interrupt 0
{
some_code........
	
}

The Ext0_int(void)   function is not listed. Probably because it has some more text after the (void).
If you have things like that in your code, the overall functionlist gets messed up, not showing all functions or showing functions being called in code.

**Comment by mere-human** [comment]
What is `interrupt 0`? It doesn't look like a standard C syntax.

**Comment by sasumner** [comment]
> It doesn't look like a standard C syntax.

It isn't.
It is typically used in embedded system compilers in order to automatically have preamble/postamble code added to the assembly language generated for the function.
It is pretty much compiler vendor specific on how they implement it (although for me it has been "a while" and perhaps some "standards" have evolved).

**Comment by MAPJe71** [comment]
> > It doesn't look like a standard C syntax.
>
> It isn't.

Ergo, the Function List C parser works as intended.

**Comment by xenpac** [comment]
another example :
void IRAM_ATTR function(void *arg)

yes, its embedded.
So there are non-standard C syntax words in the function definition.

The parser should scan the function brackets  {...}, and take the functionname from the text before the from before the normal bracket ( .

**Comment by sasumner** [comment]
@xenpac 

If you'd like to work on adding this capability to the function list parser, I encourage you to do so, however, I am in no position to guarantee that such work would be accepted.

It's a bit of a challenge because not only do you have to add the "new" syntax, you have to make sure you don't break the existing.
