### ISSUE TITLE
need “Match case” in Mark RegEx ?

### ISSUE THREAD

**Issue by nr1995** [notepad-plus-plus/notepad-plus-plus#9835]
Hi, noob here.
Just wondering why
when using Mark (last tab to the right of “Find” and “Replace”, etc.)
I need to have the “Match case” checkbox checked to match case,
even when I'm using regular expression.
e.g.
/u  in RegEx means an uppercase letter, but unless “Match case” is checked,
it will seemingly just match... all letters(?); upper and lower-case.
Is it just me, or is this dumb?
Shouldn't “Match case” just grey itself out when in RegEx mode?
Thanks,
N

**Comment by sasumner** [comment]
This one comes up every now and again.
Most programs treat regex as strictly case sensitive.
Notepad++ elects to go the other way (with the _Match case_ box), probably because of its history (regex was a late -- v6.0 -- addition)...when the implementers put regex into the existing framework, I'm sure they thought "Great, match case is here, let's use it".

I agree it is a bit weird for the `\u` and `\l` usages.

However, I don't see this issue driving any kind of change; sorry if that perturbs you.

**Comment by nr1995** [comment]
Yeah it sure does perturb me.
This seems like a totally massive oversight.
But if you say no one will do anything about it,
I'll believe you and drop it.
But god damn though.

**Comment by sasumner** [comment]
There's some Community discussion about this [HERE](https://community.notepad-plus-plus.org/post/63855).
