### ISSUE TITLE
Show actual encoding instead of ANSI

### ISSUE THREAD

**Issue by aaaxx** [notepad-plus-plus/notepad-plus-plus#987]
I take it "ANSI" is supposed to mean the system's codepage? If so, why not show the actual codepage?

**Comment by Lin-Buo-Ren** [comment]
I :+1: for this, as "ANSI" is [merely a Windows mistake](http://stackoverflow.com/questions/701882/what-is-ansi-format)

> ANSI is not just a "slight" misnomer, it is a completely wrong name. This name clearly implies that whatever it refers to is an ANSI standard, which it is not; that is a black-and-white matter of fact. With that said, it's so widely used that we're stuck with it. –  Nate C-K Sep 28 '11 at 6:58

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by Lin-Buo-Ren** [comment]
Refiled at #5508 .
