### ISSUE TITLE
Updater crashes on some older CPU's [win32]

### ISSUE THREAD

**Issue by UC3829** [notepad-plus-plus/notepad-plus-plus#988]
I have an old machine which is used to test application compatibility on CPU's which do not support the SSE2 instruction set.  I see the Notepad++ updater is crashing on this platform with exception c000001d in libcurl.dll.  I believe the problem is created when libcurl is compiled with the "SSE2 optimizations" flag enabled.  Please see the following links for more information on retaining compatibility with old CPU's.

https://stackoverflow.com/questions/21256792/write-access-violation-on-read-instruction
http://zone.ni.com/reference/en-XX/help/371361H-01/lvconcepts/sse2_caution/
https://msdn.microsoft.com/en-us/library/7t5yh4fd.aspx
https://duckduckgo.com/?q=c000001d+sse2
https://en.wikipedia.org/wiki/SSE2

**Comment by linquize** [comment]
Please update Notepad++ to 6.7.3 or later version

**Comment by linquize** [comment]
Recently, `libcurl.dll` is updated along with 6.7.8.0, 6.7.8.1 and 6.7.8.2 in May 2015.

**Comment by UC3829** [comment]
The problem still exists in 6.8.3

**Comment by UC3829** [comment]
Problem signature:

  Problem Event Name:	APPCRASH
  Application Name:	gup.exe
  Application Version:	3.2.0.0
  Fault Module Name:	libcurl.dll
  Fault Module Version:	7.42.1.0
  Exception Code:	c000001d
  Exception Offset:	0001c66a
  
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
