### ISSUE TITLE
Notepad++ v8 RC crash on Dark mode 

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#9911]
Here's the crash report:
https://community.notepad-plus-plus.org/topic/21183/notepad-v8-release-candidate/35?_=1622065401647

Obviously it is due to crash in subclassing ([0xC000041d](https://superuser.com/questions/869526/what-does-the-error-message-0xc000041d-mean)).

**Comment by donho** [comment]
@adzm Any idea ?

**Comment by adzm** [comment]
This is curious indeed. If we can get the full callstack that would be
really helpful. You can use the Microsoft symbol server to at least get
info for those functions further to the call stack which can still shine
some light on where it might be failing. Ideally though we would try a
build with the pdb symbols too. I will also try to reproduce the issue; if
you notice any pattern please let us know.

**Comment by adzm** [comment]
Additionally you can send me a crash dump and I can try to figure out what
I can from that. Careful, because crash dumps can contain sensitive data.

**Comment by mere-human** [comment]
Adding missing info from the forum.

### Steps to Reproduce the Issue

1. Download and run the portable v8RC http://download.notepad-plus-plus.org/repository/8.x/8.0.RC/npp.8.0.portable.x64.7z
2. Open n++, set Dark Mode, restart n++ and just minimize it to give it the time to crash

### Expected Behavior
No crash.

### Actual Behavior
Unhandled exception at 0x0000000000000000 in notepad++.exe: 0xC000041D

### Debug Information

Notepad++ v8 (64-bit)
Build time : May 18 2021 - 22:46:05
Path : C:\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 8.1 Enterprise (64-bit)
OS Build : 9600.20018
Current ANSI codepage : 1250
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by mere-human** [comment]
Can anyone try on Windows 8 or on a VM?

**Comment by donho** [comment]
I have installed VS2017 on my 1 generation of Surface, reproduced the crash and debugged on it.
It crashed on `_GetIsImmersiveColorUsingHighContrast()` function call and due to the variable `_GetIsImmersiveColorUsingHighContrast` becomes NULL.

It's easy to reproduce the crash: 
Launch Notepad++ and change it into the Dark mode. Put machine on pause mode (by clicking ON/OFF button on the device), then turn it on again (by clicking always ON/OFF button on the device), login and Notepad++ crash with 0xC000041D exception.

So my guess is Windows 8 reinitializes `_GetIsImmersiveColorUsingHighContrast` after the pause. After the fix of checking all the function variables before calling them, there's no more crash on my machine.
