### ISSUE TITLE
"&" key not show on .vbs edditing

### ISSUE THREAD

**Issue by hamacker** [notepad-plus-plus/notepad-plus-plus#997]
Edit a new .vbs file and press & key.
It´s not showing "&" but it´s there.
If I change to Language->H->Html then Show all "&".
If I load vb/vbs file, all "&" are showed, but new press "&" will be hidden.

So, this bug only appear when press "&" in vb/vbs eddting and shell script as .sh
The problem is default theme, if changeit, everything is OK.

Notepad++ version 6.8.3 Sept  4 2015
Windows 7 64bits/12GB RAM/Up2date

**Comment by dail8859** [comment]
This issue has been reported before. It was due to Notepad++ including the SourceCode Pro font for a release or two before this issue was noticed. However you might still have your font or a setting from a previous install. You can make sure in your style configurator to not use the SourceCode Pro font for the default style. Or make sure it isn't in your `C:\Program Files (x86)\Notepad++` folder still. [Here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues?utf8=%E2%9C%93&q=ampersand+is%3Aissue) are some of the other reported issues you might read through in case they help.

**Comment by donho** [comment]
If you got the problem of displaying & in Notepad++, please check the solution here:
https://notepad-plus-plus.org/community/topic/8202/notepad-new-release-6-8-2-updated
