### ISSUE TITLE
Clickable links can break syntax highlighting

### ISSUE THREAD

**Issue by Ceremony64** [notepad-plus-plus/notepad-plus-plus#999]
With clickable links enabled, put the following code in a new N++ tab/file:

``` php
<?php
$issue = "
x://y
";

$high->light("gimme " . 5, '!');
?>
```

Now switch to PHP highlighting and insert any character somewhere in line 4 (`";`) and the highlighting will be broken.

**Comment by vanteroknor** [comment]
Bug is still present as of v7.5.6 (Build time Mar 19 2018)

It also affects CoffeeScript highlighting. I suspect this bug can be triggered just with scrolling and changing tabs, but I can't find a reliable way to reproduce it that way. But I do have another example where editing can reproduce it.

Download the attached file and save as unit.coffee, open it, and go to line 89. (Or download it from [https://raw.githubusercontent.com/swarmsim/swarm/c17835174d676b15b02a96ad938495199ffc1244/app/scripts/services/unit.coffee](https://raw.githubusercontent.com/swarmsim/swarm/c17835174d676b15b02a96ad938495199ffc1244/app/scripts/services/unit.coffee))

[unit.coffee.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1960555/unit.coffee.txt)

Alternatively, start a new document, set language to CoffeeScript, and paste in this code:

```
  count: (secs) ->
    # Horner's method should be faster here:
    # https://en.wikipedia.org/wiki/Horner's_method
    # http://jsbin.com/doqudoxopo/edit?html,output
    # ...but I tried it and it wasn't.
    ret = new Decimal 0
	for coeff, degree in @getCoefficients()
      # c * (t^d)/d!
      ret = ret.plus coeff.times(Decimal.pow(secs, degree)).dividedBy(math.factorial degree)
    return ret
```

Now, make any change to the last two comments in the 4-comment block. Or make any change to the "ret = new Decimal 0" line right after the comment block.

Result: the entire file from the comments to the end of the file will now appear in green (or whatever style you have set for comments)

**Comment by MetaChuh** [comment]
verified to be reproducible on 7.6.6

**Comment by Ekopalypse** [comment]
looks like coffeescript lexer needs to be added to the exclusion list in[ notepad_plus.cpp](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/Notepad_plus.cpp#L2436)
I can't seem to reproduce the php problem.

**Comment by Uhf7** [comment]
This can be solved by using _standard indicators_ instead of _style byte partitioning_ for URL highlighting. I copied this technical terms from **ScintillaDoc.html**.

This document says, that style byte indicators are not supported anymore, so switching might be inevitable at some point.

**Pro's**
- Syntax highlighting remains intact
- Code is much shorter
- Can be implemented to behave exactly like in current version, except for one point:

**Con**
- It is impossible to support the _URL hovered_ style anymore, because the style of _standard indicators_ cannot be set freely. There is a list of possible ways to emphasize the hovered link, but it will never look exactly the same as it looks now.
